### ISSUE TITLE
Cannot read ClickHouse plugin

### ISSUE THREAD

**Issue by gubinjie** [apache/incubator-superset#10006]
I have installed sqlalchemy-clickhouse (Successfully installed sqlalchemy-clickhouse-0.1.5.post0)
Why does it appear when I connect to Clickhouse
INFO:superset.views.core:Invalid driver Can't load plugin: sqlalchemy.dialects:clickhouse

**Comment by mistercrunch** [comment]
It seems like a problem with your environment or the driver you are using, not a Superset problem. You try to connect `SQLALchemy` to your `Clickhouse` cluster in an interpreter. Once you can get through that Superset should work well.
