### ISSUE TITLE
I can't see 'Druid Clusters' on 'Sources' menu

### ISSUE THREAD

**Issue by waw3ru** [apache/incubator-superset#10009]
- I successfully installed apache-superset on my virtualenv using `$ pip install apache-superset[druid]`

- I created `superset_config.py` and added the following configurations
```python
SQLALCHEMY_DATABASE_URI = 'postgresql://xx:xx@127.0.0.1:5432/superset-db'
```
- I then continued to setup superset as instructed in the docs
```sh
# Initialize the database
superset db upgrade

# Create an admin user (you will be prompted to set a username, first and last name before setting a password)
$ export FLASK_APP=superset
superset fab create-admin

# Load some data to play with
superset load_examples

# Create default roles and permissions
superset init

# To start a development web server on port 8088, use -p to bind to another port
superset run -p 8088 --with-threads --reload --debugger
```
- When I went to the superset UI, **druid clusters** was not available as one of the options on the list of **sources**

#### Screenshots

![image](https://user-images.githubusercontent.com/11578670/83995213-7fd7ea80-a961-11ea-9f46-6f59b770017a.png)

### Environment

- superset version: `0.36.0`
- python version: `Python 3.6.9`
- node.js version: `v10.13.0`
- npm version: `6.14.4`

_Is there something I did wrong during the setup ? and how can I get the menu option available ?_

**Comment by nytai** [comment]
@waw3ru The native druid connector is deprecated, you should use the sqlalchemy connector and connect as you do any other database (using a connection string). You can enable the legacy connector, if you really need to, via a config flag: https://github.com/preset-io/incubator-superset/blob/master/superset/config.py#L221

**Comment by waw3ru** [comment]
Thanks

**Comment by willbarrett** [comment]
Looks like this is resolved. If you need further guidance @waw3ru feel free to reopen.
