### ISSUE TITLE
Annotation Layers

### ISSUE THREAD

**Issue by the-dcruz** [apache/incubator-superset#1000]
I noticed that annotation layers are currently listed in [TODO.md](https://github.com/airbnb/caravel/blob/master/TODO.md).

What are some of the high-level implementation plans for this? I feel like it would not make sense to store annotation data in Druid so I think it makes sense to be able to query from the `table` datasource for all annotations even when creating a Druid slice.

If no one is currently working on this I was thinking of giving it a try. Let me know what you think.

**Comment by hajdbo** [comment]
This should probably be closed since https://github.com/apache/incubator-superset/pull/3521
