### ISSUE TITLE
Using admin for user and pwd results in "Invalid login. Please try again."

### ISSUE THREAD

**Issue by arniwesth** [apache/incubator-superset#10007]
Following the instructions to launch using docker-compose from
https://superset.incubator.apache.org/installation.html

Using `admin` for user and and pwd results in
```
Invalid login. Please try again. 
```

**Comment by arniwesth** [comment]
Restarted and now admin works.

**Comment by Sidra-adnan** [comment]
Hi ,

I am facing the same issue in superset with username as admin and pass as admin
"Invalid login. Please try again. "

Would appreciate it if anyone could please guide me on this.

Many thanks!!
