### ISSUE TITLE
Cannot use explore data function

### ISSUE THREAD

**Issue by chrislin1991** [apache/incubator-superset#10019]
When click the table in tablemodelview list, explore data page is always loading. 

### Expected results

Can generate visualization type like table, line chart, bar chart and so on.

### Actual results

explore data page is always loading, cannot generate table .

#### How to reproduce the bug

1. Go to 'menu sources'
2. Click on 'menu tables'
3. Click on table name

### Environment

(please complete the following information):

- superset version: `0.36`
- python version: `3.7`
- node.js version: Centos7, doesn't install node.js
- npm version: Centos7, doesn't install node.js

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@chrislin1991 I am unable to reproduce this bug. Can you share some more context on when this happens?

**Comment by chrislin1991** [comment]
i did some secondary developments. some days after i changed codes, explore data function cannot be used, is always loading, and URL is always 127.0.0.1/8088/superset/explore/table/14/. i changed some code below 1. static/assets/explore****.js，',.3f' is changed to ',.0f'. 2. superset/db_engine_specs/hive.py, alter create_table_from_csv() function  3.alter views/sql_lab.py, remove async_=True. Please click this link to see the superset secondary development part, this is chinese, but you can see the code screenshot, https://www.notion.so/Superset-c72534b9ee964d8f875443cb51cf47af. thank you~~~

**Comment by chrislin1991** [comment]
when i click table name to explore data, terminal displayed view.py's explore function results, but didn't run explore_json function. so that explore page is always loading. why doesn't superset run explore_json? 

INFO:werkzeug: * Detected change in '/data/anaconda3/envs/superset37/lib/python3.7/site-packages/superset/views/core.py', reloading
INFO:werkzeug: * Restarting with stat
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/data/anaconda3/envs/superset37/lib/python3.7/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 339-202-523
explore start
{'time_range_endpoints': (<TimeRangeEndpoint.INCLUSIVE: 'inclusive'>, <TimeRangeEndpoint.EXCLUSIVE: 'exclusive'>), 'datasource': '14__table', 'adhoc_filters': []} ImmutableMultiDict([])
explore end
INFO:werkzeug:127.0.0.1 - - [12/Jun/2020 15:24:36] "GET /superset/explore/table/14/ HTTP/1.1" 200 -

**Comment by chrislin1991** [comment]
I find the problem, I changed the format for explore**.js file. So that it appears bug,  '>' cannot be recognized.
