### ISSUE TITLE
steps to fix broken white page when start it using docker (and bug report)

### ISSUE THREAD

**Issue by cocodrino** [apache/incubator-superset#10017]
Hi guys, recently I was the same problem described here #8818  I was able to fix following these steps (you will need node and npm or yarn installed):

1) enter in the  superset-frontend folder, remove the node_modules folder and reinstall the dependencies using `npm install ` or `yarn`

2) if you try to build the project, probably will get an error with the cross-env package

```
superset-frontend git:(master) ✗ yarn run build
yarn run v1.22.4
$ cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors
/bin/sh: cross-env: command not found

```

you only need install cross-env using pm (or yarn)

3) I try to build the project again but this time **I get some type issues**  (seems to be a problem related to installing new versions of dependencies) 

```
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(45,22):
TS2339: Property 'hidden' does not exist on type 'HeaderGroup<{}>'.

ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(48,28):
TS2339: Property 'sortable' does not exist on type 'HeaderGroup<{}>'.

ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(54,27):
TS2339: Property 'sortable' does not exist on type 'HeaderGroup<{}>'.

ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(85,33):
TS2339: Property 'hidden' does not exist on type 'ColumnInstance<{}>'.

ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Admin/Downloads/proj/avanti/deltaio/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(87,53):
TS2339: Property 'cellProps' does not exist on type 'ColumnInstance<{}>'.

```

I did a small patch for these interfaces (not the best solution but change the original code to adapt to the new version of the lib would be more difficult):

go to `/incubator-superset/superset-frontend/node_modules/@types/react-table/index.d.ts` and add **cellProps** and **hidden** to **ColumnInstance**, do the same with **HeaderGroup** and **sortable** and **hidden** properties

the final code is

```ts
export interface ColumnInstance<D extends object = {}>
    extends Omit<ColumnInterface<D>, 'id'>,
        ColumnInterfaceBasedOnValue<D>,
        UseTableColumnProps<D> {
            cellProps: any
            hidden : Boolean
        }

export interface HeaderGroup<D extends object = {}> extends ColumnInstance<D>, UseTableHeaderGroupProps<D> {
    sortable?: Boolean
    hidden? : Boolean


```

after that you will be able to compile and build the project...then just run docker-compose up and the project must be displayed correctly (remember to increase docker memory from 2gb to 4gb)

It's not a definitive solution but I hope this helps other people with the same problem

Best regards.

**Comment by ispulkit** [comment]
Facing the same issue

**Comment by hfuthippop** [comment]
> Faced the same issue.
> Just install react-table v7.0.2. It was listed as a dev-dependency. Either move it to dependencies or install dev-dependencies.
> This is my package-lock.json
> 
> ```
> @types/react-table": {
>       "version": "7.0.2",
>       "resolved": "https://registry.npmjs.org/@types/react-table/-/react-table-7.0.2.tgz",
>       "integrity": "sha512-sxvjV0JCk/ijCzENejXth99cFMnmucATaC31gz1bMk8iQwUDE2VYaw2QQTcDrzBxzastBQGdcLpcFIN61RvgIA==",
>       "dev": true,
>       "requires": {
>         "@types/react": "*"
>       }
>     }
> ```

It does not work.
