### ISSUE TITLE
TIME_GRAIN_ADDON not working in superset_config

### ISSUE THREAD

**Issue by mbh86** [apache/incubator-superset#10012]
I set up the following property in my superset_config.py: 
`TIME_GRAIN_ADDONS = {'P3M': 'quarter'}` 
But it doesn't display in the app.

The property `TIME_GRAIN_BLACKLIST` works fine though.

### Environment
- superset version: `0.36.0`
- python version: `python 3.7.3`

**Comment by villebro** [comment]
@mbh86 is there some reason you're not using `P0.25Y` that's already predefined and implemented for engines that support it?

**Comment by mbh86** [comment]
> @mbh86 is there some reason you're not using `P0.25Y` that's already predefined and implemented for engines that support it?

Thank you @villebro, I didn't know that. I will use it from now on.
Unfortunately, it didn't solve the issue.

**Comment by villebro** [comment]
What is the issue, apparently quarters are not showing up on the time grain dropdown? That should happen if the time grain in question isn't implemented for your database in `db_engine_specs`. What database are you on?

**Comment by mbh86** [comment]
Exactly, the time grain is not showing up. The database is SQLite (examples database).

**Comment by villebro** [comment]
Unfortunately the quarter time grain hasn't been implemented for sqlite. If you are able to add it that would be a great idea for a PR!

**Comment by mbh86** [comment]
Thank you for the info @villebro.
