### ISSUE TITLE
Altair charts ?

### ISSUE THREAD

**Issue by sandys** [apache/incubator-superset#10011]
hi guys
is there any interest in implementing Altair charting into superset ? 
Altair is built on vega lite 
https://altair-viz.github.io/

Charts are configured in json. It also defines charts in a very grammar of graphics style. It is natively available on Google Colab

**Comment by kalimuthu123** [comment]
hi @sandys i am interested to do the same

**Comment by JunlinC** [comment]
https://preset.io/blog/2020-07-02-hello-world/ you can now easily build your own chart using new data viz plug-in.  Superset will be using Echarts as the main library. https://echarts.apache.org/examples/en/index.html

**Comment by JunlinC** [comment]
🏷 chart library

**Comment by willbarrett** [comment]
Tagging @rusackas - perhaps the plugin architecture will support this?

**Comment by rusackas** [comment]
The big trick here is that this is a Python library. It looks like it has the ability to save a chart as HTML, but I'm not sure what would be the best way to serve/surface that to the frontend. 

It also appears, however, that this is built on vega-lite, which you can TOTALLY use in viz plugins. I would recommend exploring that as an alternative path if it meets your needs.
