### ISSUE TITLE
Unable to fetch thumbnail image data, getting OK Async in response instead

### ISSUE THREAD

**Issue by AshishKapoor** [apache/incubator-superset#10022]
Unable to fetch thumbnail image data, getting OK Async in response instead.

Ref PR: https://github.com/apache/incubator-superset/pull/8947

### Expected results
Should return the image data.

### Actual results
I'm getting `{  "message": "OK Async" }` when calling for the thumbnail.

#### Screenshots
<img width="734" alt="Screenshot 2020-06-09 at 4 46 55 PM" src="https://user-images.githubusercontent.com/5203107/84142666-d123cf00-aa72-11ea-964e-a4d4a7ed05da.png">

![Screenshot 2020-06-09 at 4 21 00 PM](https://user-images.githubusercontent.com/5203107/84139290-3b397580-aa6d-11ea-9b82-2dd92087b625.png)

#### How to reproduce the bug

1. Go to 'Dashboard'
2. Goto URL: `<hostname>:<port>/api/v1/dashboard/<thumbnail_url>`
3. Observe the response

### Environment

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.7.7`
- node.js version: `v12.16.3`
- npm version: `6.14.4`
- operating system: Fedora 31 (Workstation Edition) x86_64

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @AshishKapoor,

Thumbnails need cache and celery workers, take a look at: https://apache-superset.readthedocs.io/en/0.36/installation.html#celery-tasks

Also on celery use: `CELERY_IMPORTS = ("superset.sql_lab", "superset.tasks.thumbnails")`

**Comment by AshishKapoor** [comment]
Okay, I'll do that.

Thanks. 🙏

**Comment by AshishKapoor** [comment]
### Got the thumbnail in Cache. Now how to retrieve it in the superset frontend client?
![Screenshot 2020-06-18 at 7 23 34 PM](https://user-images.githubusercontent.com/5203107/85028871-44c38b80-b199-11ea-8ae2-b251b32a0f94.png)

**Comment by dpgaspar** [comment]
Cool! Do a get request to `/api/v1/dashboard/` on the `result` key you'll get an attr key named `thumbnail_url` use that URL to get your thumbnail

**Comment by AshishKapoor** [comment]
@dpgaspar I followed it. Now I am seeing this.
<img width="934" alt="Screenshot 2020-06-18 at 9 30 11 PM" src="https://user-images.githubusercontent.com/5203107/85044197-ef907580-b1aa-11ea-8504-3e5509a9e0c9.png">
