### ISSUE TITLE
AWS Athena Connection with MFA/Session Tokens

### ISSUE THREAD

**Issue by jjgong7** [apache/incubator-superset#10027]
**Is your feature request related to a problem? Please describe.**
I have MFA activated for AWS on my IAM, so I need to include a session token in my 
 SQLAlchemy URI to connect with AWS Athena. I'm unable to find a solution to connect since SQLAlchemy doesn't seem to take session tokens.

**Describe the solution you'd like**
With the PyAthena REST or PyAthenaJDBC URI it doesn't seem like there's a parameter for session tokens or temporary access. Are there any work arounds that can be considered? Or is this implicit in SQLAlchemy not taking session tokens. 

**Describe alternatives you've considered**
I tried using PyAthenaJDBC with a temporary session and it worked, but there doesn't seem to be an option with PyAthena SQLAlchemy.

Thanks!

**Comment by jtotoole** [comment]
@jjgong7 did you ever figure out a solution this?
