### ISSUE TITLE
New chart save fails

### ISSUE THREAD

**Issue by dmfay** [apache/incubator-superset#10023]
I'm evaluating Superset using the docker-compose quickstart on Linux, cloned from Git. I am unable to create new charts. However, opening an existing chart and saving it (with or without modifications) under a new name does work.

### Expected results

Saving a new chart works.

### Actual results

The save modal closes silently, but reopening shows the message "Failed to save slice". No new chart is created. A 500 error appears in the log, but no stack trace is available and the PostgreSQL container's /var/log/postgres is empty as logging does not seem to be configured.

```
superset_app             | 172.20.0.1 - - [09/Jun/2020 15:05:57] "POST /superset/explore/?action=saveas&slice_name&add_to_dash=noSave&goto_dash=false HTTP/1.1" 500 -
superset_app             | INFO:werkzeug:172.20.0.1 - - [09/Jun/2020 15:05:57] "POST /superset/explore/?action=saveas&slice_name&add_to_dash=noSave&goto_dash=false HTTP/1.1" 500 -
```

#### Screenshots

![1591714567](https://user-images.githubusercontent.com/3075455/84163665-be43d700-aa3f-11ea-8f90-d404929c8214.png)

#### How to reproduce the bug

1. Create a new chart from the birth names sample set (I've seen the problem with both tables and big number/trendlines). In the screenshot below I adjusted the time range and group by and ran the query to validate, but those don't appear strictly necessary.
2. Save the chart, entering a name. The modal closes but nothing else happens.
3. Reopen the save modal to see the error message.

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bcbilgin** [comment]
Same here.

Note: Overwriting works. I can't save a chart from scratch, but if I edit one of the existing chart examples, it successfully saves.

**Comment by stvacs** [comment]
I had this behaviour too - until yesterday.

When I build from the master branch ( commit > cb1705fdae8cb53ac146ba946c67071f721c257c)
for me saving a new chart started working again.

You might try the new version and see if it works for you.

**Comment by mikhail-yarosh** [comment]
@stvacs yes, creation works fine, but what about deletion?a have an error when i'm trying to delete just created chart.

**Comment by ananthagopi9381** [comment]
same this only I had another bug 

when we overwrite the slice name the duplicates are created.

I want to stop this duplication.

**Comment by lilkumsy** [comment]
hello everybody, i am having the same issues on Apache superset as am unable to create new dashboards or save charts as each time i try to save a chart it brings the error message: Failed to save slice

please i do appreciate any help from anybody here that has been able to solve the same issue.

**Comment by acanimal** [comment]
Same situation here. The error is thrown also when making a fresh installation of superset via docker-compose (superset version 4.0.2). Just a clean installation, create an admin user, run `superset db upgrade` and `superset init` and when I made a sql lab query, create a table chart and try to save the Failed to save slice` error is thrown.

Any ideas?

**Comment by akramdz38** [comment]
Hello time to time i get this issue and i don't know how to solve it i can't do anything :( 👍 

![Image](https://github.com/user-attachments/assets/aa09876c-8b81-4877-8d29-7ef5abcc6352)
