### ISSUE TITLE
Email report got `all_datasource_access` permission

### ISSUE THREAD

**Issue by tong900801** [apache/incubator-superset#10044]
Got "`all_datasource_access` permission" error when using email report sometimes.
 
### Expected results-can get this result sometimes
<img width="1171" alt="邮件内页dash" src="https://user-images.githubusercontent.com/44745938/84460590-ee3be600-ac9c-11ea-8009-b36cc918af39.png">

### Actual results-got this result most time
<img width="1169" alt="email error" src="https://user-images.githubusercontent.com/44745938/84458408-8767fe00-ac97-11ea-9117-9e65b346fbf1.png">

what actually happens.

### Description
Completed email report settings, I can receive emails from superset, but inline content got lost usually, I can get right result(both inline and attachment), but always got inline picture with "`all_datasource_access` permission" error.

in config.py, set as below
EMAIL_REPORTS_USER ="admin"

Why admin user don't have "`all_datasource_access` permission"? Thanks!

(please complete the following information):

- superset version: `0.999dev`
- python version: `python --3.6.9`
- node.js version: `node -v`
- npm version: `npm -v`

**Comment by bkyryliuk** [comment]
email reports are ran as specific user, looks like that user doesn't have some permissions

**Comment by tong900801** [comment]
Hi bkyryliuk,

Thank you for your response.
I used the admin user,I suppose it should have all permissions.
EMAIL_REPORTS_USER ="admin"

Shall I create a new user with all permissions?

Thanks a Lot

**Comment by bkyryliuk** [comment]
double check if `admin` has enough permissions

**Comment by tong900801** [comment]
Checked. admin user has "all_datasource_access" permission, and the problem is I can get right dashboard email sometimes, but also got results with no permission error.
