### ISSUE TITLE
Is there a way to programmatically access query history as available in SQL Lab -> Query Search

### ISSUE THREAD

**Issue by dolorez** [apache/incubator-superset#10049]
SQL Lab -> Query Search has some preset filters (single user, preset date intervals etc)

Is there a way to programmatically access this data (preferrably through SQL, but anything else is OK too) in order to conduct a more refined search or aggregate usage data?

Example:
select user, count(1) from queries where time between X and Y and user in (A, B, C) group by user

**Comment by rumbin** [comment]
Provided you want to give access to users, you may simply expose Superset's application Database to Superset as a data source.
This way the Superset data is browsable in SQLLab. There you can easily address all of the usage and query history and perform custom queries on this data.
However, be aware that the data model of Superset's app database may change during upgrades. The migration is managed by Alembic. It might break existing analyses on this database, as it will not respect the queries that you defined on this data.

**Comment by dolorez** [comment]
Thanks!
