### ISSUE TITLE
ModuleNotFoundError 'cachelib' during Docker setup for Superset

### ISSUE THREAD

**Issue by vijay925** [apache/incubator-superset#10057]
I'm trying to setup the Superset environment to for development purposes. According to the documentation below, it can be easily setup using docker

https://superset.incubator.apache.org/installation.html

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
# you can run this command everytime you need to start superset now:
docker-compose up
```

I get the following error when I `docker-compose up` and not able to run the app. I know its dependency related but not sure where to include the library. I'm new to python so any help is appreciated.

```
superset_app             | ModuleNotFoundError: No module named 'cachelib'
superset_app             | 127.0.0.1 - - [15/Jun/2020 19:08:14] "GET /health HTTP/1.1" 500 -
superset_app             | Traceback (most recent call last):
superset_app             |   File "/app/superset/__init__.py", line 21, in <module>
superset_app             |     from superset.app import create_app
superset_app             |   File "/app/superset/app.py", line 30, in <module>
superset_app             |     from superset.extensions import (
superset_app             |   File "/app/superset/extensions.py", line 26, in <module>
superset_app             |     from cachelib.base import BaseCache
superset_app             | ModuleNotFoundError: No module named 'cachelib'
```

**Comment by grimbeorn74** [comment]
Sorry I have the same issue, did you manage to solve it?

**Comment by janko-zpeng** [comment]
Me To, Hello. How to resolve it ?

**Comment by nytai** [comment]
@janko-zpeng can you try to pull down the latest master and then run `docker-compose up --build`

**Comment by janko-zpeng** [comment]
> @janko-zpeng can you try to pull down the latest master and then run `docker-compose up --build`

Perfect,Thanks，I add params "--build" for docker-compose up, it is successful.
