### ISSUE TITLE
bug: URLs generated by SQL Lab for loading schemas and tables are busted

### ISSUE THREAD

**Issue by willbarrett** [apache/incubator-superset#10072]
### Expected results

When I select a Database from the dropdown, SQL Lab requests a list of schemas from the back-end. This should result in a URL like `/superset/schemas/1/<true or false>` with the last URL parameter being interpolated.

When I then select a schema from the following dropdown, SQL Lab requests a list of tables from the back-end. This should result in a URL like `/superset/tables/1/<schema name>/<substr>/<force_refresh>`

### Actual results

Selecting a database from the list results in a request to /superset/schemas/1/[object%20Object]/

Selecting a schema then results in a request to /superset/tables/1/public/undefined/%5Bobject%20Object%5D/

#### Screenshots

n/a

#### How to reproduce the bug

1. Open SQL Lab
2. Open the Network Inspector
3. Select a database from the list
4. Observe the odd back-end request
5. Select a schema from the list
6. Observe another odd back-end request

### Environment

(please complete the following information):

- superset version: 26120467af3825577a30190f42d942836b147c9f
- python version: 3.6.8
- node.js version: 12.10.9
- npm version: 6.10.3

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@ktmud do you think this might have something to do with the recent upgrade of our dropdown components?

**Comment by ktmud** [comment]
Could be. Let me take a look.
