### ISSUE TITLE
How to replace existing geojson file in superset.

### ISSUE THREAD

**Issue by gyanranjanm** [apache/incubator-superset#10083]
### Expected results
I am expecting to see  exact map as per  given geojson file.
 
### Actual results
I want to update  the existing  India geojson file with latest geojson file(PFA),I have tried to replace it with new file in same name, but it is not working as expected.
 
Screenshots
n/a
### Environment

(please complete the following information):

- superset version: 0.36
- python version: python 3
node.js version: 12.10.9
npm version: 6.10.3

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Need cofig details to achieve this.

[geojson file.zip](https://github.com/apache/incubator-superset/files/4792148/geojson.file.zip)

**Comment by gyanranjanm** [comment]
> Issue Label Bot is not confident enough to auto-label this issue. See [dashboard](https://mlbot.net/data/apache/incubator-superset) for more details.

**Comment by willbarrett** [comment]
@rusackas do you have any thoughts here?

**Comment by rusackas** [comment]
Hi @gyanranjanm!

I'm assuming that we're talking about replacing the map data for the "country map" viz plugin here. I'm also curious what features you're looking to add to the map, but I'll focus on answering your question...

I was able to take your attached file and make a drop-in replacement of the `india.geojson` file for that plugin. It's not ideal though. A couple of initial issues:

1) The file is huge - the standard one is 457KB, but this new one is 76.6MB. That's a big payload, obviously.
2) The boundaries of the geojson seem to lie far beyond India, meaning the country renders quite small in the viz plugin
![image](https://user-images.githubusercontent.com/812905/85634883-6d340580-b631-11ea-9cab-f2962e717940.png)

That said, if you want to experiment with this yourself, you'll want to do the following:
1) Clone the Superset-UI [repo](https://github.com/apache-superset/superset-ui)
2) With your terminal, `cd` into that directory, and `yarn install`. A `yarn build` after that couldn't hurt ;)
3) `cd` into wherever your locally running `incubator-superset` instance is, and then into `superset-frontend`
4) type `npm link ../../the/relative/path/to/superset-ui/plugins/legacy-plugin-chart-country-map`
5) server your local superset as normal with `npm run dev` or `npm run dev-server`

That should put you into dev mode for that plugin. If you edit anything in the `legacy-plugin-chart-country-map/src` folder, you should see webpack rebuild, and see the changes reflected in your local superset.

At that point, you should be able to replace the file at `legacy-plugin-chart-country-map/src/countries/india.geojson` and see your work.

Once it works as planned, please feel free to open a PR on `superset-ui` if you feel it's something the community could use!

**Comment by gyanranjanm** [comment]
Thanks Team.

It  have decreased th file size and just replace it,it is working fine now.

**Comment by willbarrett** [comment]
Awesome! Closing issue.

**Comment by prathavich** [comment]
> Thanks Team. It have decreased th file size and just replace it,it is working fine now.
> […](#)

@gyanranjanm I have installed the superset using pip in python venv Is there is any way to change india.geojson file ?
and how you did that ? please can you explain
