### ISSUE TITLE
@dpgaspar Thanks.  It works!

### ISSUE THREAD

**Issue by emeka-obi** [apache/incubator-superset#10089]
@dpgaspar Thanks.  It works!

While I looked up the setting, I found the [pull request](https://github.com/apache/incubator-superset/pull/9218).  It seems like it doesn't convert the examples to use another database tho.

_Originally posted by @hc128168 in https://github.com/apache/incubator-superset/issues/9748#issuecomment-624641390_

**Comment by emeka-obi** [comment]
@hc128168 I have the same problem as you did earlier (SQLite database cannot be used as a data source for security reasons). I was wondering if you could show me how to apply the solution recommended by the previous user. I tried but it did not make much sense to me.

**Comment by dpgaspar** [comment]
Place `PREVENT_UNSAFE_DB_CONNECTIONS = False` on superset config. Note SQLlite is really not advisable for production use and you always use our `docker-compose` for a quick spinup

**Comment by emeka-obi** [comment]
@dpgaspar Thanks a lot for your help.
