### ISSUE TITLE
table view crash

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#10081]
The browser crashes when the amount of data is high

**Comment by ktmud** [comment]
we are working on a total rewrite of the table chart. In the meantime, you can add row limit or pagination (from the Customize tab) to mitigate this issue.

**Comment by qinzl1** [comment]
@ktmud 
thx
But the demand side needs to query all the data, and the data volume is quite large

**Comment by aman101097** [comment]
Hi is it resolved?
