### ISSUE TITLE
Table's time column is NaN

### ISSUE THREAD

**Issue by whitefirer** [apache/incubator-superset#10097]
Table's time column is NaN when using the docker image amancevice/superse:0.36.0.
![image](https://user-images.githubusercontent.com/12084604/85007002-7d5d6800-b18d-11ea-8766-7a5a372f5e4a.png)

### Environment
- docker image: amancevice/superse:0.36.0
- superset version: 0.36.0

**Comment by willbarrett** [comment]
@whitefirer please provide more information on the underlying database engine you are using and the datatype of the column that is displaying incorrectly. Thanks!

**Comment by ktmud** [comment]
I think this has been fixed by #9493 . Please use a newer image.

**Comment by willbarrett** [comment]
A fix for this will be part of the next official 0.37 release.

**Comment by whitefirer** [comment]
> @whitefirer please provide more information on the underlying database engine you are using and the datatype of the column that is displaying incorrectly. Thanks!

![image](https://user-images.githubusercontent.com/12084604/86321688-18fdd680-bc6c-11ea-8864-6d4a88c8c190.png)
![image](https://user-images.githubusercontent.com/12084604/86321924-8447a880-bc6c-11ea-9faf-5f31cdaefe9b.png)
