### ISSUE TITLE
Can't click on histogram/separator/mapbox in the dropdown menu

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#1009]
Clicking on histogram/separator/mapbox in the dropdown menu of Chart Type doesn't have feedback
(in the explore view of table)
<img width="1427" alt="screen shot 2016-08-24 at 11 45 44 am" src="https://cloud.githubusercontent.com/assets/20978302/17943444/486f5916-69f0-11e6-9313-0c63317171cd.png">

**Comment by ascott** [comment]
@vera-liu do you see any js errors in the console when this happens?

**Comment by vera-liu** [comment]
This is not always reproducible, but the chart type dropdown menu behaves wonky sometimes:
1. Go to Sources->Tables
2. Click on one table, enter the explore view
3. Select histogram/separator/mapbox in the dropdown menu of chart type, click on query
4. The dropdown menu flashes, but histogram/separator/mapbox are not shown, other visualization type is drawn instead (sometimes it's box plot, sometimes it's treemap).

**Comment by shrutimkrishnan** [comment]
@vera-liu were you able to resolve this issue - I'm running into it now

**Comment by mistercrunch** [comment]
That's an old bug and should be much better in current master. @shrutimkrishnan what version are you running?

**Comment by shrutimkrishnan** [comment]
Hi @mistercrunch thanks for the msg.. we're using version 0.18.5

**Comment by mistercrunch** [comment]
I just pushed `0.19.0`, mind trying that?

**Comment by shrutimkrishnan** [comment]
Cool - thanks @mistercrunch will give it a try and come back to you.

**Comment by shrutimkrishnan** [comment]
Worked perfectly - thanks a lot @mistercrunch!!
