### ISSUE TITLE
CockroachDB Alchemy Migraitons failure

### ISSUE THREAD

**Issue by reidlai** [apache/incubator-superset#10096]
### Expected results
I am expecting superset can run all migrations successfully in create schema in brand new database with Cockroachdb Alchemy dialect and driver

After running "superset upgrade", "superset init", and "superset run", superset flask app is up and all database data should be populated into cockroachdb tables

### Actual results

Howevere, I got many errors related to the follow error during migration upgrade (superset upgrade):

(psycopg2.errors.InvalidForeignKey) missing "id" primary key column

If I switch back to use SQLLite Alchemy, it is working.

#### Screenshots

[error.txt](https://github.com/apache/incubator-superset/files/4797155/error.txt)

#### How to reproduce the bug

just put COCKROACHDB cluster url in SQLALCHEMY_DATABASE_URI and start the server

### Environment

(please complete the following information):

- superset version: clone from master branch, error occur when running superset version inside docker
- python version: 3.6.9

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @reidlai,

Apache Superset only supports MySQL and PostgreSQL for has it's metadata database. `SQLALCHEMY_DATABASE_URI` on config is for configuring the metadata connections string. Note that support for CockroachDB, Druid, ORACLE etc... are for analytics DB, and those are configured on superset -> Databases, you can configure has many connections has you like and for multiple db engines

**Comment by reidlai** [comment]
@dpgaspar if talking about MySQL, can i use MySQL Client as wrapper to connect vitess as metadata database?

**Comment by willbarrett** [comment]
@reidlai we are not aware of anyone using Vitess as a metadata back-end for Superset. It may very well work, but it is not explicitly supported by the project. We are aware of organizations using MySQL clusters and Postgres clusters successfully. Typically the metadata database for Superset is not under heavy load, so horizontal/vertical scaling is usually not necessary. Do you expect your system to be under heavy load?

**Comment by reidlai** [comment]
@willbarrett Beacuse Postgresql and Mysql architecture lasts for many years and we are now migrating to NewSQL engine like CockroachDB, Yogabytes, Vitess, TiDB, etc which supports high scalability and availability features.  Wish Superset can support those backend in your roadmap

**Comment by willbarrett** [comment]
Thanks for the clarification. I think I understand the disconnect @reidlai - we do not store large datasets in our metadata databases. Superset connects to your data warehouse and performs operations directly against the warehouse. Some result sets are cached in an appropriate back-end (Redis or S3, for example) based on Superset's confguration to avoid hitting the warehouse on every request. The list of supported analytical databases can be found here: https://superset.incubator.apache.org/installation.html#database-dependencies - this includes CockroachDB. We use Postgres or MySQL for the metadata database as the information stored there is relatively small and we benefit from ACID semantics in the metadata store. Superset scales to support vast data warehouses through analytical connections. If you are looking for an analytical query engine to run outside of your warehouse, I know a number of organizations leverage Presto for this quite successfully, running Superset on top.

**Comment by sujanpgowda** [comment]
@reidlai @willbarrett Same here. Don't see an option for TiDB as an option in supported databases.
