### ISSUE TITLE
Order By Clause Appended in Query 

### ISSUE THREAD

**Issue by som2014** [apache/incubator-superset#10107]
I have created a Line Chart using my Data Source Query looks like this :
```
SELECT date_trunc('minute', CAST("event_time" AS TIMESTAMP)) AS "__timestamp",
       COUNT(*) AS "count"
FROM "table"
WHERE "event_time" >= from_iso8601_timestamp('2020-06-12T00:00:00.000000')
  AND "event_time" < from_iso8601_timestamp('2020-06-19T00:00:00.000000')
GROUP BY date_trunc('minute', CAST("event_time" AS TIMESTAMP))
ORDER BY "count" DESC
LIMIT 1000;
```

Here Order BY is appended in my query by default ideally it should be order by `__timestamp`.
How to get rid of this ?

**Comment by zhaoyongjie** [comment]
`Order By` clause can not be modified in the current Superset LineChart query object. However it has been sorted by timestamp in the visualization.

**Comment by som2014** [comment]
@zhaoyongjie  why it's designed like this ? It's expected or bug ?
