### ISSUE TITLE
[dashboard] Custom CSS stopped working

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#10102]
### Expected results

Superset dashboard user used to be able to add custom css in dashboard, by raw css or template.

### Actual results

When I add css it can reflected in dashboard, but cannot save into backend. **After page refresh**, all css settings, both raw css or template, are lost.

#### Screenshots

![QOhVehubpW](https://user-images.githubusercontent.com/27990562/85058769-6a2fa580-b157-11ea-9770-6a8191f4ea23.gif)

#### How to reproduce the bug

See screenshot.

### Environment

lastest version

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @rusackas @suddjian

**Comment by mldeepakfernandez** [comment]
CSS is not working while reloading the page

**Comment by rusackas** [comment]
> CSS is not working while reloading the page

What version of Superset are you using? Did you save the dashboard before refreshing?
