### ISSUE TITLE
Pivot View Column Rename

### ISSUE THREAD

**Issue by pavankanth1985** [apache/incubator-superset#10100]
In the superset version 0.36 we are using a Pivot view with Verbose name set on the columns. However the results don't consider the Verbose column name and show the names as per the underlying table. When flipping over to Table view the results show up as per Verbose name.

### Expected results

The columns in the pivot view to be named as per the Verbose names provided to the columns.

### Actual results

Only the first column in the pivot view get the verbose name applied. The rest all show the table column name as it is.

![image](https://user-images.githubusercontent.com/27360770/85034740-5fbddd80-b150-11ea-96dd-584d39377895.png)
![image](https://user-images.githubusercontent.com/27360770/85034800-72d0ad80-b150-11ea-9da6-4a979d997d4d.png)

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by GiannisDimitriou** [comment]
+1

**Comment by zhouyan8603** [comment]
+1
