### ISSUE TITLE
Background memory usage

### ISSUE THREAD

**Issue by Chloejay** [apache/incubator-superset#10116]
Memory ran out with small datasets. 
Running environment: Docker.

Should expected to build some demo charts with relatively small datasets, the data sets are already processed and summarized, so should be OK. 

Issue: 
Ran into zero memory problem. I attach log screenshoot for further infos. 
<img width="685" alt="bug" src="https://user-images.githubusercontent.com/24205486/85198147-d574a580-b318-11ea-9d62-b7760b8f2775.png">

**Comment by willbarrett** [comment]
Hi @Chloejay - how much memory do you have allocated for the docker containers?

**Comment by Chloejay** [comment]
yes @willbarrett actually I allocated memory to 2GB and swap to 1GB on Mac. I'm thinking I probably need to do some config there, for the demo dataset I used is quite small. I would not consider the data volume would be an issue.

**Comment by willbarrett** [comment]
I doubt that the data volume here is the issue. The docker-compose system contains multiple containers, including database, cache, front-end build, initialization, web server, celery process, and a test container. This group of processes can be memory-intensive, and the base resource requirements are somewhat higher than what you have configured. Locally for my development environment I allocate 6GB of RAM to Docker with a 1GB swap.
