### ISSUE TITLE
Problem with annotation

### ISSUE THREAD

**Issue by Timbo094** [apache/incubator-superset#10133]
![Edit Annotation Layer](https://user-images.githubusercontent.com/67272070/85288878-cd427480-b496-11ea-817e-89725488e47b.jpg)

![Superset Window](https://user-images.githubusercontent.com/67272070/85288945-eb0fd980-b496-11ea-9d08-1e0f04995df3.jpg)

I am currently trying to understand this tutorial: https://superset.apache.org/usertutorial.html#annotations.

In this case, it is the volcanic eruptions that had an impact on aviation.

The problem is that there is no annotation in Superset.

Screenshots are above.

Maybe someone can help :)

**Comment by eugeniamz** [comment]
I just tested with the latest master and everything seems to work as expected. We are working in docs for preset (hosted Superset) and I added a couple of reference while I tested for your reference. You can find it [here](https://docs.preset.io/docs/superset-annotations).
