### ISSUE TITLE
Date is not coming in proper format in partition chart 

### ISSUE THREAD

**Issue by xxsacxx** [apache/incubator-superset#10137]
While using partition chart with BigQuery as data source the date which is of format "2020-05-27" i.e yyyy-mm-dd in superset gets displayed as epoch time. 
While running the same query on sqllab,bigquery or csv export from superset give it in proper format (yyyy-mm-dd)

### Expected results

expected "date" to be displayed in "yyyy-mm-dd"

### Actual results

date is getting displayed in epoch format

#### Screenshots

![screenshot](https://i.imgur.com/zDxIaxY.png)

#### How to reproduce the bug

1. Creating a date column in format "yyyy-mm-dd"
2. ![screenshot](https://i.imgur.com/7sf21JB.png)
3. Sqllab and csv export from superset gives the date in proper format i.e "yyyy-mm-dd"

### Environment

(please complete the following information):

- superset version: `superset version` --- 0.35.1
- python version: `python --version` ---- 3.6.9
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eugeniamz** [comment]
It reproduce with other databases too. Thanks for reporting it!

**Comment by xxsacxx** [comment]
> It reproduce with other databases too. Thanks for reporting it!

What are the next steps,here?

**Comment by willbarrett** [comment]
We have confirmed that this is a bug on the current master branch. As this is an open source project, we do not have SLAs for fixing bugs. An existing contributor may contribute a patch for this issue, or we are happy to review pull requests from the broader community. If you'd like to attempt a fix, we are happy to point you in the right direction.

**Comment by xxsacxx** [comment]
> If you'd like to attempt a fix, we are happy to point you in the right direction.
@willbarrett sure should I start with [this](https://github.com/apache/incubator-superset/blob/master/superset/viz.py)?

**Comment by willbarrett** [comment]
You are most likely correct. @villebro would you mind providing some guidance to @xxsacxx on where in that massive file to start? You're quite familiar with its inner secrets.
