### ISSUE TITLE
Dremio connector support

### ISSUE THREAD

**Issue by ealtuna** [apache/incubator-superset#10136]
The current support it does not work in the "SQL Lab". When you try to explore the database you get the list of schemas, but once you try drill down to get the list of tables for an schema, it fails. When you go to the logs in the server the error says it's unable to parse the response.

```
(pyodbc.Error) ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\nstartLine 1\nstartColumn 71\nendLine 1\nendColumn 71\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TAB...[see log] (1040) (SQLPrepare)')
[SQL: SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema]
```

I was able to replicate the same error using the installation instructions for Docker and native in MacOS.

In my opinion the key to the solution is in:

https://github.com/apache/incubator-superset/pull/7048/files

I was able to make it work replacing the file `/app/superset/db_engine_specs/dremio.py` with:

```
class DremioBaseEngineSpec(BaseEngineSpec):

    engine = "dremio"

    _time_grain_expressions = {
        None: "{col}",
        "PT1S": "DATE_TRUNC('second', {col})",
        "PT1M": "DATE_TRUNC('minute', {col})",
        "PT1H": "DATE_TRUNC('hour', {col})",
        "P1D": "DATE_TRUNC('day', {col})",
        "P1W": "DATE_TRUNC('week', {col})",
        "P1M": "DATE_TRUNC('month', {col})",
        "P0.25Y": "DATE_TRUNC('quarter', {col})",
        "P1Y": "DATE_TRUNC('year', {col})",
    }

    @classmethod
    def get_table_names(cls, database: "Database", inspector, schema):
        sql = f'SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = \'{schema}\''
        schemas = [row[0] for row in inspector.engine.execute(sql)
                   if not row[0].startswith('_')]
        return sorted(schemas)

    @classmethod
    def epoch_to_dttm(cls) -> str:
        return "TO_DATE({col})"

```

not sure if with the current version other changes in the previous PR are still relevant. Also I noticed in the base class `BaseEngineSpec` the schema is of type Optional[str], I think this is never going to be the case for Dremio the schema in null, but it needs validation.

**Comment by mistercrunch** [comment]
A stacktrace would help if you can provide it.

**Comment by villebro** [comment]
This sounds like a problem from a while ago, but it has been fixed a few months ago (both in the driver and Superset). What versions of Superset and `sqlalchemy-dremio` are you on?

**Comment by ealtuna** [comment]
> A stacktrace would help if you can provide it.

INFO:werkzeug:127.0.0.1 - - [18/Jun/2020 17:58:34] "GET /superset/schemas/2/false/ HTTP/1.1" 200 -
(pyodbc.Error) ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\nstartLine 1\nstartColumn 71\nendLine 1\nendColumn 71\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TAB...[see log] (1040) (SQLPrepare)')
[SQL: SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema]
[parameters: {'schema': 'MySchema'}]
(Background on this error at: http://sqlalche.me/e/dbapi)
Traceback (most recent call last):
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TABLE_SCHEMA = :schema\nstartLine 1\nstartColumn 71\nendLine 1\nendColumn 71\nSQL Query SELECT TABLE_NAME FROM INFORMATION_SCHEMA."TABLES" WHERE TAB...[see log] (1040) (SQLPrepare)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/superset/models/core.py", line 479, in get_all_table_names_in_schema
    database=self, inspector=self.inspector, schema=schema
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/superset/db_engine_specs/base.py", line 623, in get_table_names
    tables = inspector.get_table_names(schema)
  File "<string>", line 2, in get_table_names
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 203, in get_table_names
    self.bind, schema, info_cache=self.info_cache
  File "<string>", line 2, in get_table_names
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy_dremio/base.py", line 200, in get_table_names
    result = connection.execute(sql, **params)
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2244, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1012, in execute
    return self._execute_text(object_, multiparams, params)
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1187, in _execute_text
    parameters,
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/Users/userhome/Documents/repository/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)

**Comment by ealtuna** [comment]
> This sounds like a problem from a while ago, but it has been fixed a few months ago (both in the driver and Superset). What versions of Superset and `sqlalchemy-dremio` are you on?

This is my Dockerfile

```
FROM preset/superset:latest
USER root
RUN apt-get update -y && apt-get install -y alien
RUN wget https://download.dremio.com/odbc-driver/1.4.2.1003/dremio-odbc-1.4.2.1003-1.x86_64.rpm -P /tmp/
RUN alien -k -i /tmp/dremio-odbc-1.4.2.1003-1.x86_64.rpm --scripts
RUN apt-get install -y unixodbc-bin && apt-get install -y unixodbc-dev
RUN pip install pyodbc && pip install sqlalchemy_dremio && pip install dremio_client[full]
USER superset
```

It's using Superset from Master and the last version of the sqlalchemy-dremio.

**Comment by ealtuna** [comment]
I have been running the Superset-Dremio connector with the mentioned changes without issues, but I wonder if the other changes are useful in use cases I am not currently using.

**Comment by villebro** [comment]
@ealtuna If you have the time, it could be helpful to add the part about how to use alien to convert the `rpm` to `deb` to the installation docs in `docs/installation.rst`.

**Comment by yograjpshinde** [comment]
I have installed superset on the Linux VM using docker. As per the steps in Superset docs i could only installed the MySQL client but failing for others. I tried for Snowflake and Dremio by adding sqlalchemy-dremio and snowflake-sqlalchemy in the file /docker/requirements-local.txt. 

Please find below the errors i am getting. Please help with the solution.

superset_worker         | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f485c555cd0>, Connection to pypi.org timed out. (connect timeout=15)')': /simple/sqlalchemy-dremio/
superset_app            | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fab49119f50>, Connection to pypi.org timed out. (connect timeout=15)')': /simple/sqlalchemy-dremio/
superset_worker_beat    | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f47365fbe10>, Connection to pypi.org timed out. (connect timeout=15)')': /simple/sqlalchemy-dremio/
superset_cache exited with code 1
superset_worker         | ERROR: Could not find a version that satisfies the requirement sqlalchemy-dremio
superset_worker         | ERROR: No matching distribution found for sqlalchemy-dremio
superset_worker exited with code 1
superset_app            | ERROR: Could not find a version that satisfies the requirement sqlalchemy-dremio
superset_app            | ERROR: No matching distribution found for sqlalchemy-dremio
superset_worker_beat    | ERROR: Could not find a version that satisfies the requirement sqlalchemy-dremio
superset_worker_beat    | ERROR: No matching distribution found for sqlalchemy-dremio
