### ISSUE TITLE
How can I hide the "+ New" Button for cutom user?

### ISSUE THREAD

**Issue by sweileh** [apache/incubator-superset#10145]
## Question
I'm trying to provide access to certain users or employees. However, even after I set the permissions to minimum required permissions, the (+ New) button still shows in their screen. How can I hide this button for these users? 
![Screenshot from 2020-06-24 07-19-42](https://user-images.githubusercontent.com/34817857/85495368-6e424400-b5eb-11ea-883e-ab0830aac72c.png)
Also, how can I disable the the options on the chart to keep the chart simple? or at least hide some of these options.
![Screenshot from 2020-06-24 07-25-15](https://user-images.githubusercontent.com/34817857/85495697-15bf7680-b5ec-11ea-96d6-97261197af23.png)

Thanks in advance

**Comment by sweileh** [comment]
+1

**Comment by willbarrett** [comment]
Hi @sweileh - I don't believe this functionality exists in Superset right now. I'm tagging this issue as an enhancement request.

**Comment by sweileh** [comment]
Thanks Will!
This would be great.

**Comment by MHammad200** [comment]
Is this functionaly implemented?

**Comment by junlincc** [comment]
Hi @MHammad200 and @sweileh , thanks for the enhancement request. I will be considering implementing this feature next year after some product research. assigning this issue to myself, feel free to follow up with me in Slack.

**Comment by sunnyuff** [comment]
+1
