### ISSUE TITLE
Is it posible to disable Chart for public user? (question)

### ISSUE THREAD

**Issue by larsmars** [apache/incubator-superset#10141]
Is it posible to disable Chart and "Explore chart" for public user?
Without disabling the posibility to use iFrame of the chart.

I do not want the public user to have the posiblity to change/customize and play around with the chart.
ie: changing:
- Datasource
- Visualization type
- Time/range/filter
- Query
- Row limit

I still need the iFrame of the chart to be publicly available.
I still need published dashboards to be publicly available.

### Expected results
Option/Role/Permission to limit public role access to chart and chart editing/"Explore Chart"

### Actual results
Can not find any option for this?
If I remove "can explore on superset" the chart, chart editing and "Explore chart" is hidden for the public user, but then I can not use iFrame of charts for public user.

#### Screenshots
![limit_access](https://user-images.githubusercontent.com/5154589/85409268-e5cd9000-b565-11ea-9b8b-b6dcb2b5f556.PNG)

#### How to reproduce the bug

1. Create public role
2. Create iFrame
3. Explore chart
4. Explore iFrame
5. Play with public role permissions (see img under)

### Environment
superset version: 0.36.0
python version: 3.6.10
node.js version: 12.16.1
npm version: 6.13.4

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

###Additional context
![role_public_list](https://user-images.githubusercontent.com/5154589/85409498-2c22ef00-b566-11ea-8e98-9894fb6a4256.PNG)

**Comment by larsmars** [comment]
bump

**Comment by srinify** [comment]
Hi there @larsmars have you tried messing with the **Public** role at all?

https://www.oreilly.com/library/view/apache-superset-quick/9781788992244/8f89fc24-9f91-4eee-bb0f-883b94aaf17f.xhtml
