### ISSUE TITLE
Additional language is not picked up by GUI

### ISSUE THREAD

**Issue by larsmars** [apache/incubator-superset#10140]
Extra language is added to superset/translations but the language is noe picked up by the GUI

### Expected results
Additional language is available in GUI

### Actual results
Additional language is available but only en language is displayed.

#### Screenshots
![lang_dropdown](https://user-images.githubusercontent.com/5154589/85381228-100b5780-b53e-11ea-9699-fca4da17180f.png)
![lang_copy_build](https://user-images.githubusercontent.com/5154589/85381532-595ba700-b53e-11ea-80cb-b5811f16d3d2.PNG)
![copy_lang](https://user-images.githubusercontent.com/5154589/85381542-5c569780-b53e-11ea-8c22-0144f2d1a616.PNG)
![superset_config](https://user-images.githubusercontent.com/5154589/85381861-afc8e580-b53e-11ea-8688-39d42e733489.PNG)
![messages_json](https://user-images.githubusercontent.com/5154589/85389012-2833a480-b547-11ea-91b9-e6ac5544d971.PNG)
![messages_po](https://user-images.githubusercontent.com/5154589/85389053-3681c080-b547-11ea-81f6-d1d9510e0f90.PNG)
![docker_file](https://user-images.githubusercontent.com/5154589/85389407-a7c17380-b547-11ea-8f82-11dad725cfa4.PNG)

#### How to reproduce the bug
1. Add new translations folder with name no, containing .json and .po files with lang
2. Copy content as part of build
3. Update superset config
4. Observe Norwegian lang is selected in portal but lang is english

### Environment
superset version: 0.36.0
python version: 3.6.10
node.js version: 12.16.1
npm version: 6.13.4

### Checklist
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
To make sure there is nothing wrong with the messages.json and messages.po files the "es" lang files have been used, see screenshots.

**Comment by willbarrett** [comment]
@dpgaspar I think you're familiar with the translation interface

**Comment by nytai** [comment]
@larsmars what's in your superset config? https://github.com/preset-io/incubator-superset/blob/master/superset/config.py#L275

**Comment by larsmars** [comment]
There is an img posted in the bug above with the related config. What are you looking for?

**Comment by larsmars** [comment]
bump
