### ISSUE TITLE
How to customize Google OAuth screen?

### ISSUE THREAD

**Issue by sedhha** [apache/incubator-superset#10151]
I have been trying to find the files which render the login oAuth screen of Apache superset. Does anyone know what location can I find them in?

**Comment by axelet** [comment]
I think you want to override flask_appbuilder's template `./site-packages/flask_appbuilder/templates/appbuilder/general/security/login_oauth.html`
Copy the file to `.superset/templates/appbuilder/general/security/login_oauth.html` and change things here.

**Comment by sedhha** [comment]
In my /superset/templates/appbuilder/general there's no security, it's just: **model  widgets**. 
Superset version I am using: 0.36.0
other dependencies:
Python 3.8.2
Flask 1.1.2
Werkzeug 0.16.1

**Comment by axelet** [comment]
Feel free to create it

**Comment by sedhha** [comment]
Oh i see... Have you a sample of yours? Just wanted to see how the attributes are linked there .
