### ISSUE TITLE
Does anyone know how to pass variables/metrics in apache superset in markup variable widget?

### ISSUE THREAD

**Issue by sedhha** [apache/incubator-superset#10152]
I have a table as shown below:
![image](https://user-images.githubusercontent.com/36355685/85561470-408be800-b649-11ea-8b20-07a4593d2c4b.png)
I want to show up the metric or variable data in a markup widget as a variable name. Is there any way to do so>?

**Comment by sedhha** [comment]
👍

**Comment by zufolo441** [comment]
I already asked for this possibility, but no answer.
https://github.com/apache/incubator-superset/issues/9949
