### ISSUE TITLE
Support more "realtime" options in "Time Range" filter

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-superset#10167]
**Is your feature request related to a problem? Please describe.**
We are using Superset with databases having realtime data ingested and wanna have the feature to support showing realtime metrics update.

E.g. Current "Last Day" option doesn't include today (The snapshot is taken on June 25, and Last day doesn't contain today's data).

![image](https://user-images.githubusercontent.com/1202120/85795576-6074e780-b6ed-11ea-92d3-5373e68973ac.png)

**Describe the solution you'd like**

In "Time Range" filtering, expect options like: "Today", "This Week", "This Month", etc to include today as part of time filtering.

Also in Custom section, we have an option for `Last` and `Next` but missing the option to specify start/end date to be relative from today.

E.g. I can config a custom time range querying for Last 24 hours.

The purpose of this is to just config the dashboard once and the metrics will be refreshed every time user open/refresh the dashboard.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by bkyryliuk** [comment]
@fx19880617  you can go to the custom field and say:
![image](https://user-images.githubusercontent.com/5727938/85805835-4560a280-b702-11ea-8a8c-93712fede4d6.png)

to get what you are looking for

**Comment by fx19880617** [comment]
nice! 
Many thanks !
