### ISSUE TITLE
The latest release tag not shown by github

### ISSUE THREAD

**Issue by Naitreey** [apache/incubator-superset#10184]
I'm just beginning investigating superset as visualization tool. But seeing that the latest release shown by github is `0.34.0`, as shown by screenshot:
![CleanShot 2020-06-28 at 11 35 26](https://user-images.githubusercontent.com/10528297/85937199-eedaaa80-b933-11ea-9d68-80d2153d89e4.png)

This makes me think the project didn't make any release since 09/2019, which is not a very uplifting first impression IMO.

But it's not true since the project has made multiple releases since 0.34.0.

Can you guys do something about it? To make the actual latest release marked as "latest" by github UI?

**Comment by etr2460** [comment]
I've added a release on Github corresponding to the 0.36.0 tag that already existed: https://github.com/apache/incubator-superset/releases/tag/0.36.0

I'll also update the release documentation so that this step is taken in the future. Thanks for the feedback!
