### ISSUE TITLE
Time Range  bug  , last week  last month  unknown lasttime

### ISSUE THREAD

**Issue by yuexianchao** [apache/incubator-superset#10186]
Time Range  前开后闭区间，(2020-04-01,2020-04-07] 在sql_lab查询结果是有数据2020-04-07的，在图表里面不显示2020-04-07，应该是一个小问题 ，希望优化 谢谢

**Comment by eugeniamz** [comment]
@yuexianchao  the message is not in English so ti is difficult to understand the exact issue, could you provide screenshots ?
