### ISSUE TITLE
Superset celery beat for scheduler email report doesn't work

### ISSUE THREAD

**Issue by UsherChen** [apache/incubator-superset#10198]
I use superset 0.36 in developing mode (code debug). The celery work can send "Test email" successfully. But celery beat doesn't work, that means the Scheduler doesn't work. These are my celery config:

`
class CeleryConfig:  # pylint: disable=too-few-public-methods
    BROKER_URL = "sqla+sqlite:///celerydb.sqlite"
    #BROKER_URL = "redis://localhost:6379/0"
    CELERY_IMPORTS = ("superset.sql_lab", "superset.tasks")
    CELERY_RESULT_BACKEND = "db+sqlite:///celery_results.sqlite"
    #CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
    CELERYD_LOG_LEVEL = "DEBUG"
    CELERYD_PREFETCH_MULTIPLIER = 1
    CELERY_ACKS_LATE = False
    CELERY_ANNOTATIONS = {
        "sql_lab.get_sql_results": {"rate_limit": "100/s"},
        "email_reports.send": {
            "rate_limit": "1/s",
            "time_limit": 120,
            "soft_time_limit": 150,
            "ignore_result": True,
        },
    }
    CELERYBEAT_SCCHEDULE = {
        "email_reports.schedule_hourly": {
            "task": "email_reports.schedule_hourly",
            "schedule": crontab(minute=1, hour="*"),
        }
    }

`
I follow official documents and use these commands to start celery:
`
celery worker --app=superset.tasks.celery_app:app --pool=prefork -O fair -c 4
celery beat --app=superset.tasks.celery_app:app
`

**Comment by bkyryliuk** [comment]
can you please add an celery beat error message?

**Comment by nate-goop** [comment]
what happens if you change CELERYBEAT_SCCHEDULE to CELERYBEAT_SCHEDULE?
