### ISSUE TITLE
0NaN-NaN-NaN NaN:NaN:NaN in Tables when Include Time is enabled

### ISSUE THREAD

**Issue by bearloga** [apache/incubator-superset#10203]
When checking the "Include Time" option in the GROUP BY section of a chart and using the Table visualization, the output doesn't print the actual datetimes.

### Expected results

Datetimes based on time range & granularity selected

### Actual results

"0NaN-NaN-NaN NaN:NaN:NaN"

#### Screenshots

Attaching screenshots from both datasource types (Druid Table, classic cube):

<img width="1412" alt="Screen Shot 2020-06-30 at 11 34 03 AM" src="https://user-images.githubusercontent.com/1807519/86147549-891f2780-bac7-11ea-9810-37b73fac64b8.png">
<img width="1415" alt="Screen Shot 2020-06-30 at 11 37 28 AM" src="https://user-images.githubusercontent.com/1807519/86147557-8c1a1800-bac7-11ea-9598-c1dd230e1166.png">

#### How to reproduce the bug

1. Create a new Table chart
2. Adjust time granularity, range, etc.
3. In the GROUP BY section, check "Include Time" option
4. Run query

### Environment

- superset version: 0.36.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
  - Don't have access to the host but hopefully @elukey can provide
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by durchgedreht** [comment]
Hi,
we encounter the same issue, but with the pattern "NaN/NaN/0NaN". 

- superset version: 0.36.0
- clickhouse 
- native clickhouse alchemy driver

<img width="756" alt="Time_formatting" src="https://user-images.githubusercontent.com/4490840/88162074-20802200-cc11-11ea-9330-6c30a445d915.png">

When looking in the query log, ordering per week applies a toMonday() function after a toDatetime(). Result will not be DateTime but Date (have a look in the. "__timestamp" field - no time infos available). I'm not sure where the issue resides, but the rending in HTML shows a zeroed out Datetime with format "yyyy-MM-dd 00:00:00" (first picture at the bottom shows the chrome dev inspect window with <td> data-sort="2020-02-24T00:00:00" ) . 
<img width="639" alt="Superset_toMonday" src="https://user-images.githubusercontent.com/4490840/88162805-20345680-cc12-11ea-8e85-e98d76172447.png">

So I believe it's just the rendering that's impacted. Many NaN Date rendering is related to wrong Date input, so maybe columns are mixed up, wrong format pattern applied, index wrong (month values 0-11 vs 1-12). 

I can provide more infos if needed. Please advise which data might be helpful.

**Comment by durchgedreht** [comment]
Additional infos: Chart's CSV export also uses the date from query. No issues exporting the data.
 
...,2020-04-27, ...

**Comment by durchgedreht** [comment]
Seems related to
#10097 
and is fixed in 0.37 (not yet testet - will try to verify)
#9493

**Comment by mistercrunch** [comment]
0NaN-NaN-NaN NaN:NaN:NaN - hey hey hey - goodbye!

**Comment by allantaylor81** [comment]
the same problem !  Did it work out in the end ？ Look forward to your reply ! thanks

**Comment by whitefirer** [comment]
0.37 has sloved it.

**Comment by durchgedreht** [comment]
+1 
Works from >= 0.37

**Comment by bearloga** [comment]
<img width="1433" alt="Screenshot of Superset 0.37.2 showing fixed timestamps when including time in GROUP BY via checkbox and visualizing with table chart" src="https://user-images.githubusercontent.com/1807519/94690863-9e8e3280-02fe-11eb-8996-37b6f0a164ac.png">

We just upgraded to 0.37.2 and I can confirm this problem is gone. Thank you!

**Comment by stevensuting** [comment]
This still happens in 0.38.0 for column that are placed in the group by list. This [issue](https://github.com/apache-superset/superset-ui/issues/731) describes the same

**Comment by villebro** [comment]
@stevensuting can you add the following information: 
- the database type
- the datatype of the "Last Appointment Date" and "Last Feedback Date" columns?

Also, the cell values that are displaying `NaN`..., are those `NULL` values?

**Comment by stevensuting** [comment]
- Database Type: Postgres
- Data type of columns Last Appointment Date" and "Last Feedback Date: timestamptz
- Cell value in DB for which Superset is displaying NaN: NULL
- Data type set in Superset implicitly: TIMESTAMP WITH TIME ZONE

**Comment by bonedi** [comment]
I still have this Issue in version 2.1.2. 
I have tried to cast the value to varchar, still I get 0nan-nan... in the chart.

**Comment by MilenaSilva10** [comment]
I also have this problem, how can I solve it?

**Comment by villebro** [comment]
@MilenaSilva10 which version are you on, and which database type? This should not be happening on recent versions of Superset.

**Comment by MilenaSilva10** [comment]
@villebro it is showing version 0.0.0-dev. I saw it happened in August 2023 too, but I think the problem came back 
https://github.com/apache/superset/pull/24696

![versao](https://github.com/apache/superset/assets/117678229/4ba256bd-5f78-466f-8c30-d8be9d9fd042)
