### ISSUE TITLE
Embedding visualizations as Iframe 

### ISSUE THREAD

**Issue by raoofnaushad** [apache/incubator-superset#10217]
I am facing the same issue. But in my case Superset is installed via HDP. I am not able to find the superset location (config.py). And I am not sure where is it.? Help is very much appreciated.

_Originally posted by @raoofnaushad in https://github.com/apache/incubator-superset/issues/4393#issuecomment-652340791_

**Comment by karen-pal** [comment]
Hmm I'm not very familiar with HDP. How does your folder structure look like? If you are using linux I recommend the `locate` command, it's a lifesaver.

`locate superset/config.py`

**Comment by raoofnaushad** [comment]
Thanks a lot I was able to find via that command. But now the problem is there 6 workers and in every worker I can find superset and config.py file? This is not configured by me. 
And I also face another issue that when I tried Flask web app that render the Iframe with authentication and served it with nginx and gunicorn. I was able to view it from my computer but it shows refused to connect when I tried it in another.

**Comment by karen-pal** [comment]
Hmmm if you could provide a screenshot of the error it would be easier, but I think I have run into that issue. 
If you haven't changed the config file, you have to override some configuration flags in order to make the embedding work on a browser!
For that you have to modify superset_config.py (create the file first if needed) and add your custom settings.

To work with embedded charts I have added:
```
SESSION_COOKIE_HTTPONLY: False
SESSION_COOKIE_SAMESITE: None
```

Remember to add superset_config.py to your python path.
Let me know if it works.

**Comment by raoofnaushad** [comment]
I have actually changed the config.py file instead of overriding. I am attaching the changes I made and screenshots. 
I can see it from the server I am accessing but not from my mobile (which is connected to the same network).[
![1](https://user-images.githubusercontent.com/26721994/86271501-9a148980-bbea-11ea-8800-d1498e2f24e4.png)
![2](https://user-images.githubusercontent.com/26721994/86271507-9bde4d00-bbea-11ea-800f-21cde73ae6ed.png)
![4](https://user-images.githubusercontent.com/26721994/86271511-9da81080-bbea-11ea-856f-f45ce708272c.png)
![WhatsApp Image 2020-07-01 at 10 29 26 PM](https://user-images.githubusercontent.com/26721994/86271521-9f71d400-bbea-11ea-81c9-fb08385135c3.jpeg)



](url)

**Comment by GOPIPACHA** [comment]
Can you guys help me out How to run superset  on back ground(deamon) process.I am trying but i cound't able do this.Plase let me know if any one had  idea about this will help me a lot

**Comment by 1997827** [comment]
> I have actually changed the config.py file instead of overriding. I am attaching the changes I made and screenshots.
> I can see it from the server I am accessing but not from my mobile (which is connected to the same network).[
> ![1](https://user-images.githubusercontent.com/26721994/86271501-9a148980-bbea-11ea-8800-d1498e2f24e4.png)
> ![2](https://user-images.githubusercontent.com/26721994/86271507-9bde4d00-bbea-11ea-800f-21cde73ae6ed.png)
> ![4](https://user-images.githubusercontent.com/26721994/86271511-9da81080-bbea-11ea-856f-f45ce708272c.png)
> ![WhatsApp Image 2020-07-01 at 10 29 26 PM](https://user-images.githubusercontent.com/26721994/86271521-9f71d400-bbea-11ea-81c9-fb08385135c3.jpeg)
> 
> ](url)

I changed 

> I have actually changed the config.py file instead of overriding. I am attaching the changes I made and screenshots.
> I can see it from the server I am accessing but not from my mobile (which is connected to the same network).[
> ![1](https://user-images.githubusercontent.com/26721994/86271501-9a148980-bbea-11ea-8800-d1498e2f24e4.png)
> ![2](https://user-images.githubusercontent.com/26721994/86271507-9bde4d00-bbea-11ea-800f-21cde73ae6ed.png)
> ![4](https://user-images.githubusercontent.com/26721994/86271511-9da81080-bbea-11ea-856f-f45ce708272c.png)
> ![WhatsApp Image 2020-07-01 at 10 29 26 PM](https://user-images.githubusercontent.com/26721994/86271521-9f71d400-bbea-11ea-81c9-fb08385135c3.jpeg)
> 
> ](url)

I did what you have done, Still not getting in web itself, Please share the file it would be help ful
