### ISSUE TITLE
Preserve Column Order in Table CSV Export

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#10218]
I am experiencing this new issue with superset 36. 

I am pretty sure in the previous versions of superset Table exported in CSV had column order preserved. 
I also have trouble exporting CSV data with 'latin-1' encoding, which I did not have before 

Is this possible or I am dreaming and it never worked ? :/

**Comment by lilila** [comment]
I come back on this issue, the problem is still not resolved with superset 37. 
Here is an example : 

The chart : 

<img width="856" alt="Screenshot 2020-08-12 at 15 46 45" src="https://user-images.githubusercontent.com/607430/90022746-31bdcb00-dcb3-11ea-86c0-f29c9165d45e.png">

and the CSV export : 

<img width="716" alt="Screenshot 2020-08-12 at 15 46 50" src="https://user-images.githubusercontent.com/607430/90022814-4306d780-dcb3-11ea-8b00-9f008b3419a0.png">


As you can see, the columns' order is modified and additionally the names of the columns were replaced by the variables :(

**Comment by michalgala** [comment]
I have the same issue, and it can be quite annoying for tables with many columns

**Comment by lilila** [comment]
I found out the problem (at least for the table export) comes from this line :
https://github.com/apache/incubator-superset/blob/ca9ca995109ee5251918b9df60980bffaf9b9a24/superset/viz.py#L325


The set function does not preserve the original order , I have seen this `list(set( .... ))` or `set(gb)` in many places in the via.py file. 
Is there any better way to preserve unicity in columns and make sure there is no duplicate?

**Comment by michalgala** [comment]
As a quick fix you could use:

`concat_list = gb+columns`
`sorted(set(concat_list), key=concat_list.index)`

However, there might be some performance issues if you have many columns.

**Comment by JunlinC** [comment]
Hi Lila, our team mentioned that you have been providing valuable product feedbacks and requests in the community. I would like to invite you to join Superset new designated user panels. I couldn't find you on Slack, would you mind sharing your email with me and I can share more info with you if you are interested. Thanks! @lilila
