### ISSUE TITLE
How to update the customized changes in Apache Superset?

### ISSUE THREAD

**Issue by sedhha** [apache/incubator-superset#10214]
Operating System: Ubuntu 18.04 LTS
Superset Version: 0.36.0
Setup globally in a GCP instance and running in debugging mode using the command: superset run -p 8080 -h 0.0.0.0

I have been referring to docs and making some changes to customize my superset UI. Once I do all the changes in local path folder i.e. 

/home/usr/.local/lib/python3.6/site-packages/superset/static/assets/stylesheets/less/

I see my changes get reflected by running the command:

superset init

But while cloning the code, I also have a folder incubator-superset where I have made changes to superset_frontend. Am not able to see those changes getting reflected, like for example adding additional color schema. (tcColors in this case)
![image](https://user-images.githubusercontent.com/36355685/86210487-55f59a80-bb92-11ea-9c2a-bbd4f0929fe2.png)

File I have changed is: apache_superset/incubator-superset/superset-frontend/src/setup/setup_color.js
Now after doing these changes, how do I reflect them to appear in my webapp UI?

**Comment by karen-pal** [comment]
@sedhha  After following the [installation steps](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#frontend-assets), with the backend running, open another terminal and run the frontend using the command `npm run dev-server` inside the superset-frontend directory. You will see your changes when you open localhost:9000 in your browser.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md

**Comment by sedhha** [comment]
> superset@0.999.0-dev dev-server /home/shivam/apache_superset/incubator-superset/superset-frontend
> NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/shivam/apache_superset/incubator-superset/superset-frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 5.3.0-1029-gcp
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev-server"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! superset@0.999.0-dev dev-server: `NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev dev-server script 'NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shivam/apache_superset/incubator-superset/superset-frontend/npm-debug.log

Getting this

**Comment by etr2460** [comment]
did you `npm install`?

**Comment by sedhha** [comment]
> did you `npm install`?

No, I want to run and test the changes made in superset front end and then reflect them back to my orignal superset.

**Comment by karen-pal** [comment]
Hey @sedhha that error message means you are lacking a npm module that you need to install! You probably need to run `npm ci`, as the [documentation states](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#frontend-assets). Try that and see if it works.

**Comment by sedhha** [comment]
Tried npm ci,

![image](https://user-images.githubusercontent.com/36355685/86428307-0508b200-bd0a-11ea-91bc-d9d7e5636811.png)

after that npm run-dev server gives:

![image](https://user-images.githubusercontent.com/36355685/86428363-249fda80-bd0a-11ea-9323-6df73581e091.png)

**Comment by mistercrunch** [comment]
Looks like an old `npm` version, please upgrade npm and maybe node too. Just FYI I'm currently running
```
$ node --version
v12.16.2
$ npm --version
6.14.5
```
