### ISSUE TITLE
Tables with hyperlinks: open link in new tab

### ISSUE THREAD

**Issue by curiousus** [apache/incubator-superset#10227]
**Is your feature request related to a problem? Please describe.**
I have in my source tables URLs, which I use in a CONCAT to generate hyperlinks (something like CONCAT("<a href='" , url , "'>Link to data record</a>") ).  I have then added target='_blank' to the tag, but it seems this tag is escaped before the hyperlink is generated. Although I am far from being an expert in this area, I am aware of the existence of the target='_blank' security vulnerability.

**Describe the solution you'd like**
Some way to have the hyperlink be opened in a new tab without the need to right-click > "Open link in new tab".

**Describe alternatives you've considered**
I have added rel= "noopener noreferrer" to the tag, but the target attribute is escaped nonetheless.
I have also tried some JavaScript alternatives (_onclick="window.open(this.href,'_blank');return false;"_), but they don't work either.
The current "solution" was to change the hyperlink's text to "Right click to open in new tab".

**Additional context**
Our customer would like that the link be opened in a new tab with one simple click.

EDIT: currently using 0.35.2

**Comment by etr2460** [comment]
I believe this is now fixed in master, and will be part of the 0.37 release

**Comment by rmgpinto** [comment]
doesn't work for me, is there a solution for this? Thanks
