### ISSUE TITLE
Which presto is supported, prestosql or prestodb or both?

### ISSUE THREAD

**Issue by Naitreey** [apache/incubator-superset#10238]
In doc of [query cost estimation](https://superset.incubator.apache.org/sqllab.html#query-cost-estimation), it states

> Here, “version” should be the version of your Presto cluster. Support for this functionality was introduced in Presto 0.319.

Which I assume referring to PrestoSQL 0.319 version, because [it matches PrestoSQL changelog](https://prestosql.io/docs/current/release/release-319.html) and PrestoDB only released 0.237.1 to this date. But [on doc index page](https://superset.incubator.apache.org/index.html#databases), the Presto support is linked to [PrestoDB](http://prestodb.github.io/).

I know it's a headache. But I hope there's some clarification on this. Maybe it would be nice to also clarify this situation in the doc?

**Comment by mistercrunch** [comment]
Forks break my heart 💔 

I'm assuming both and Athena as well. No one has reported issues on either side AFAICT

**Comment by Naitreey** [comment]
Thank you for clarifying this.
