### ISSUE TITLE
How can i make filter non editable in superset

### ISSUE THREAD

**Issue by ashish1807** [apache/incubator-superset#10230]
Hello community. I have "country_name" filter on world bank dashboard. I saved it as with preselect_filters as "United States" now i don't want anyone to change it. Can anybody help how can I do it? Is there any property which I can add in char metadata of filter char?

**Comment by klazaj** [comment]
That depends on the users. If you have other user with different roles in your setup, then you can remove the 'Edit Dashboard' feature from these users.

**Comment by ashish1807** [comment]
> 
> 
> That depends on the users. If you have other user with different roles in your setup, then you can remove the 'Edit Dashboard' feature from these users.

@klazaj but i am not able to find any "Edit dashboard" permission in list roles

**Comment by klazaj** [comment]
I haven't looked up the roles in a while but I remember doing that myself. Something regarding 'menu access in Dashboards' or similar. You can search the roles, or just type 'dashboard' in the search bar and you'll see all the options.

**Comment by ashish1807** [comment]
> 
> 
> I haven't looked up the roles in a while but I remember doing that myself. Something regarding 'menu access in Dashboards' or similar. You can search the roles, or just type 'dashboard' in the search bar and you'll see all the options.

@klazaj  but i want to make my filter non editable. So is there any connection between menu and filter? Or is there any property which i can add char metadata of that filter chart?
