### ISSUE TITLE
Welcome page pagination is inconsistent

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#10232]
The pagination of dashboards on the welcome page doesn't have a consistent number of dashboards per page, and the record count isn't sequential. There record counts also seem to flicker and update to different numbers as the page loads (e.g. displaying 1-11, then updating to 1-15 once items render)

### Expected results
Each page to have the same number of items, record counting to be sequential (e.g. first page is 1-10, 2nd is 11-20, 3rd is 21-30, etc)

#### Screenshots
<img width="1192" alt="Screen Shot 2020-07-02 at 8 49 25 AM" src="https://user-images.githubusercontent.com/7409244/86380810-657fec80-bc41-11ea-987f-7fdee435c850.png">
<img width="1190" alt="Screen Shot 2020-07-02 at 8 49 33 AM" src="https://user-images.githubusercontent.com/7409244/86380816-67e24680-bc41-11ea-921b-5315cc19adbc.png">

#### How to reproduce the bug
Paginate on the welcome page

### Environment

(please complete the following information):

- superset version: `master`

We have not yet enabled React List Views in our environment

to: @nytai, I think you were working on this?

**Comment by nytai** [comment]
@etr2460 I have noticed some weirdness with the record counts being inconsistent, I'll look into that now. To be clear, you have "whited-out" the dashboard and creator columns in the screenshots and that isn't a bug?

**Comment by bkyryliuk** [comment]
I've gotten similar bug reports from our users.

**Comment by nytai** [comment]
I'm also confused where the 10 records per page is coming from. In the code it's currently set to 25, https://github.com/preset-io/incubator-superset/blob/master/superset-frontend/src/welcome/DashboardTable.jsx#L28

**Comment by dpgaspar** [comment]
I think this may be related to a bug I currently fixed on FAB related with m-m relations on lists. The amount of owners are counted has records also, will publish an FAB 3 RC2 tomorrow if it's not too urgent

**Comment by etr2460** [comment]
@nytai: correct, I whited out the dashboard and creator columns to prevent exposing sensitive data.

@dpgaspar: thanks for the fix!
