### ISSUE TITLE
Cannot edit datasources from the Pivot Table viz

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#10247]
When the pivot table viz is selected in Explore and I click on the datasource name, I don't see the option to edit the datasource, only change it or explore it in sql lab.

### Expected results

See the option to edit the datasource

### Actual results

Don't see that option

#### Screenshots

![image](https://user-images.githubusercontent.com/7409244/86641458-00552f80-bf90-11ea-9267-d02cb4ec6070.png)

#### How to reproduce the bug

1. Open a chart in explore
2. Change it to viz type pivot-table
3. Click on the datasource name
4. don't see the edit datasource option

### Environment

(please complete the following information):

- superset version: `master`

@rusackas or @suddjian, do you think this is related to moving the pivot table controls into superset-ui? I know it happened a while ago, but I can't think of another reason for this to break, so tagging you here

**Comment by suddjian** [comment]
I don't see anything suspicious at first glance in the control config. I can do a deeper investigation later today.

**Comment by etr2460** [comment]
Thanks @suddjian!

**Comment by mistercrunch** [comment]
Oh hit this issue too and found a solution. I'm guessing this is related to the controls refactor (?)

**Comment by mistercrunch** [comment]
See fix here https://github.com/apache/incubator-superset/pull/10283
