### ISSUE TITLE
Regression Scatterplot Map: List of not loaded with the dimension data when trying to select dimensions for colors 

### ISSUE THREAD

**Issue by eugeniamz** [apache/incubator-superset#10246]
When doing a scatter plot map and want to define different colors per a dimension the list of dimension is not loaded but it does have the right count of possible values. It also does not allows to insert a value 

![image](https://user-images.githubusercontent.com/58375897/86605269-79468e00-bf74-11ea-8b79-063c57040e07.png)

### Expected results
Expected that the different options are in the list 

### Actual results
It shows in the count but there are not options.

**Comment by eugeniamz** [comment]
Hi @ktmud , @villebro said that you may know about this issue. Something related to the `react-select` version bump. Can you help me?

**Comment by wildsonc** [comment]
How i fix that on superset v 0.999.dev?
