### ISSUE TITLE
Feature: Minimize side bar to see full width chart

### ISSUE THREAD

**Issue by nickrox** [apache/incubator-superset#1026]
Side bar provides measures, group by etc. I   like to minimize the side-bar after selections and show full width chart.

**Comment by xrmx** [comment]
@ascott do you have any opinion? :)

**Comment by ascott** [comment]
i like this idea. we've also thought about making the chart sticky so only the filters on the side bar scroll, so you always see the chart. there is a refactor happening on this page, so i'd like to wait for those changes to land before tackling this, but let's definitely keep it open.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 311 days. Feel free to comment and request for this issue to be reopened.
