### ISSUE TITLE
migration failed new database model

### ISSUE THREAD

**Issue by Z08JBECH** [apache/incubator-superset#10272]
Hello everyone.

**I have an issue to migrate from 0.25 to 0.36 superset**

I can run it into a new venv with new installation and without to use my postgresql database, but when i try touse my database, I have some errors (new columns)
For example in the dashboard tab
![image](https://user-images.githubusercontent.com/46780967/87066830-7ddca200-c213-11ea-87cb-894e40699a0c.png)

I can see that this new version use new column for the new features

I tried "superset db upgrade" to update model database but i have some errors (see databaseèupgrade.txt file)

[database upgrade.txt](https://github.com/apache/incubator-superset/files/4898168/database.upgrade.txt)

Does I need to create a new database and migrate the data manually ?

Thanks in advance for your answer.

**Comment by dpgaspar** [comment]
Hi @Z08JBECH,

Looking at your log:

```
psycopg2.errors.UniqueViolation: could not create unique index "uq_table_columns_column_name"
DETAIL:  Key (column_name, table_id)=(<new column>, 101) is duplicated.
```

So it seems you have a duplicate column name for a table, remove the duplicate and rerun the migration
