### ISSUE TITLE
api/v1/dashboard API response time format is wrong

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#10307]
I found the **Modified** column for `welcome` page is messaged up, which was caused by the time format from `api/v1/dashboard` API.
For example if i crated a dashboard at 2020-07-13 19:09:54.991076 PSD time, API responded as `changed_on: "2020-07-13T19:09:54.991076+00:00"`. Then front-end js will parse it as `Mon Jul 13 2020 12:09:54 GMT-0700 (Pacific Daylight Time)`

Compare the welcome page vs dashboard list view:
### Expected results
<img width="959" alt="Screen Shot 2020-07-13 at 7 10 41 PM" src="https://user-images.githubusercontent.com/27990562/87372660-fb1e5480-c53c-11ea-9a09-291ac0e324f2.png">

### Actual results

<img width="943" alt="Screen Shot 2020-07-13 at 7 10 30 PM" src="https://user-images.githubusercontent.com/27990562/87372644-f3f74680-c53c-11ea-8958-1a9d70c20935.png">

### Environment

(please complete the following information):

latest master branch

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
@villebro I think this issue is 0.37 blocker.

@dpgaspar @etr2460

**Comment by nytai** [comment]
we're using moment.js on the frontend to format the timestamp, so that might be the issue (if the data doesn't include timezone).

**Comment by villebro** [comment]
Thanks @graceguo-supercat , I'll flag this for 0.37.

**Comment by dpgaspar** [comment]
This is an interesting problem, actually on marshmallow 2 the response from the API is correct: `changed_on: "2020-07-13T19:09:54.991076+00:00"` if your metadata database is configured for UTC and your web server.

I actually just found a problem with marshmallow 3 upgrade, since it will not add the UTC timezone to naive datetime, and it seems that is what superset is saving. I have a fix for that, but need more info, it seems that your web server is on PSD is that correct?

**Comment by graceguo-supercat** [comment]
> This is an interesting problem, actually on marshmallow 2 the response from the API is correct: `changed_on: "2020-07-13T19:09:54.991076+00:00"` if your metadata database is configured for UTC and your web server.
> 
> I actually just found a problem with marshmallow 3 upgrade, since it will not add the UTC timezone to naive datetime, and it seems that is what superset is saving. I have a fix for that, but need more info, it seems that your web server is on PSD is that correct?

Yes.

**Comment by etr2460** [comment]
@graceguo-supercat, @dpgaspar: our webserver and metadata databases are on UTC, not Pacific Time.

**Comment by dpgaspar** [comment]
@etr2460 ok but the above example makes sense on a Pacific Time server. Yet we got a problem here, I'll make a PR tomorrow

**Comment by dpgaspar** [comment]
fixed on master
