### ISSUE TITLE
Can't open the "Security -> List Users" page  ,When config the auth_ldap

### ISSUE THREAD

**Issue by pokyu** [apache/incubator-superset#10308]
### Expected results

When config the auth_ldap  ,  ldap user can login，but the admin user can't open  the "Security -> List Users" page.
Click the page ,it go to  "profile"    " **Dashboards   Recently Viewed   Favorites**"

config.py :
```
#AUTH_TYPE = AUTH_DB
AUTH_TYPE = AUTH_LDAP
#AUTH_LDAP_UID_FIELD = "uid"

# Uncomment to setup Full admin role name
AUTH_ROLE_ADMIN = 'Admin'

# Uncomment to setup Public role name, no authentication needed
# AUTH_ROLE_PUBLIC = 'Public'

# Will allow user self registration
AUTH_USER_REGISTRATION = True

# The default user self registration role
#AUTH_USER_REGISTRATION_ROLE = "Public"
AUTH_USER_REGISTRATION_ROLE = "Admin"

# When using LDAP Auth, setup the LDAP server
AUTH_LDAP_SERVER = "ldap://ldap.nextop.cc"
AUTH_LDAP_SEARCH = "dc=vantopgroup,dc=com"
AUTH_LDAP_UID_FIELD = "cn"

AUTH_LDAP_BIND_USER = "cn=user,ou=IT,dc=vantopgroup,dc=com"
AUTH_LDAP_BIND_PASSWORD = "password"

```

superset version:0.36.0
python :3.6.8

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi, thank you for reporting this. A fix (#10310) just got merged on master that may be related to this. Can you update and run `superset init` then try again?
