### ISSUE TITLE
Getting error when executing query in SQL Lab query editor

### ISSUE THREAD

**Issue by naresnayak** [apache/incubator-superset#10309]
i'm getting error **{e}** when trying to execute SQL query.Please help me.

![image](https://user-images.githubusercontent.com/65640697/87392536-534f6800-c5ca-11ea-97f4-30a7a83e83b6.png)

**Comment by villebro** [comment]
@naresnayak what version are you on? Filling out the standard issue template makes it much easier for contributors to pinpoint the problem.

**Comment by naresnayak** [comment]
Hi villebro,

i'm using apache-superset 0.36.0 latest version.Preview of the table is also showing the same error.

![image](https://user-images.githubusercontent.com/65640697/87394264-25b7ee00-c5cd-11ea-8832-588c4e26d53f.png)

**Comment by villebro** [comment]
Ok, in that case we can close this issue, as it should be fixed in the upcoming `0.37.0` release (new release candidate expected to ship today).
