### ISSUE TITLE
[bug] sql-lab better error feedback

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1031]
we need better error feedback on badly formed sql &/or backend errors

<img width="1280" alt="screenshot 2016-08-29 14 39 42" src="https://cloud.githubusercontent.com/assets/130878/18068430/1aec9814-6df6-11e6-8b7d-9ee28a0dc923.png">

**Comment by dmigo** [comment]
This one doesn't seem to be relevant anymore.
