### ISSUE TITLE
Create SQL Lab View using Dataset REST API

### ISSUE THREAD

**Issue by swecooo** [apache/incubator-superset#10311]
I was trying to create a Superset [Terraform provider](https://www.terraform.io/docs/extend/writing-custom-providers.html) for managing datasets (and also charts) using Terraform. I wanted to create the resources in Superset using the [FAB Model REST API](https://flask-appbuilder.readthedocs.io/en/latest/rest_api.html#model-rest-api). However I found out that there is no possibility to create an SQL Lab View using the `/dataset` REST API since the POST request only supports 4 parameters: `database`, `schema`, `table_name` and `owners`.

It would be great if we could also provide the `is_sql_lab_view` and `sql` parameters to the `/dataset` POST request and create an SQL Lab View directly using this endpoint.

As a very limited workaround I used POST request to create a dataset linking to a table and then updated the record with `/dataset` PUT request where I could already provide all the parameters needed (`is_sql_lab_view` and `sql`). However one does need to manually change the dataset columns after updating the record.

**Comment by saviobabu** [comment]
https://github.com/apache/superset/issues/10311#issue-656550149 @sweco  same issue here. only physical dataset able to create through rest api. no mention about creating virtual dataset(sql lab code instant view) through rest api. anyone ???

**Comment by Praytic** [comment]
Please reopen this issue or navigate to another way of creating a virtual dataset.
