### ISSUE TITLE
Disable co-editing dashboard to prevent changes being lost

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#10327]
**Is your feature request related to a problem? Please describe.**
**Request:** As a dashboard producer, I need a to ensure dashboard edits can be done safely (without losing any changes).

**Current behavior (Problem):** When one dashboard is being edited by multiple people at the same time (usually when multiple people building the dash together), some changes are not saved properly, and are lost when the other person made changes at the same time. 
This feature does not address co-editing, it focuses on addressing the immediate problem of users might get their work lost (over written) if multiple people edit dashboard at the same time. 

**Describe the solution you'd like**
1. On Edit - don't let them edit. (=> A feature to notify current editor that the dash is being edited by someone else therefore they can't edit etc).
OR
2. On Save - don't let them save it.

**Describe alternatives you've considered**
The ideal solution is to enable co-editing, but that is more complex. This would address the immediate issue that if two users are editing at the same time, or even same user in multiple tabs, one of them loses the changes.

**Comment by akelai** [comment]
Since there's no way to know that others have that same dashboard opened in edit mode, thus with the potential to destroy one's changes, or to have their changes destroyed by other's changes, and since the application supports multiple users, this is at the edge between a bug and an enhancement: I'd say "enhancement" ok, but that's actually an understatement - it's a severe UX issue.

**Comment by mistercrunch** [comment]
Confirming that this is a problem.

**Comment by zuzana-vej** [comment]
We had a discussion on this with our team, and split it into two stories:
1) Solve the immediate problem which users face (which has two options, summarized above). I think not letting user edit if someone else is editing (and probably display the name of that person who is editing so that users can coordinate) is better. This would solve the immediate problem which users face when they make edits, click on "Save" and their edits get lost. --> this issue
2) Long term - enable co-editing dashboards - which will require little more discussion on solutions along the lines of your comment @mistercrunch.

**Comment by akelai** [comment]
> 1. Solve the immediate problem which users face (which has two options, summarized above). I think not letting user edit if someone else is editing (and probably display the name of that person who is editing so that users can coordinate) is better. This would solve the immediate problem which users face when they make edits, click on "Save" and their edits get lost. --> this issue

@zuzana-vej is this (the "1." in your comment above) being/been done somewhere?

**Comment by zuzana-vej** [comment]
@akelai as far as I know, noone had worked on it yet.

**Comment by graceguo-supercat** [comment]
I would propose to use eTag to prevent 2nd edit submitted to server-side: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag and see **Avoiding mid-air collisions** section.

**Comment by zuzana-vej** [comment]
@graceguo-supercat did this feature: https://github.com/apache/incubator-superset/pull/11220 closing this issue

**Comment by akelai** [comment]
I've tested simulating a collision on version 0.38, and I've not experienced differences since last time I wrote here (0.35). Should that have been addressed on Superset 0.38 (and I should make a better test)?

**Comment by zuzana-vej** [comment]
two users can still enter edit mode at the same time. The feature that @graceguo-supercat implemented is to prevent colision on save, so if person B made and saved changes while person A was also in edit mode, person A will see the warning when they are trying to save the dashboard and won't be able to do that. Not ideal long term solution but at least user knows their changes aren't getting saved. In the past - it would appear like it will get saved and it didn't which was much worse user experience.

**Comment by akelai** [comment]
Yes I remember the past, and it was bad: in fact, what you describe is the test that I've done to see how it behaves now on 0.38 - but I've got no warning message, and the experience has been the same as in the past.

I'll repeat the test, I've tried just one time - maybe I did it wrong.
