### ISSUE TITLE
Make it easier to add new charts to empty dashboard

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#10329]
**Is your feature request related to a problem? Please describe.**
For new dashboards, for the first item you add to the dashboard, you need to drag it to the top of the dashboard and let go once you see the blue line at the top of the dashboard
Even for folks who work on Superset, this was confusing behavior and resulted in erroneous filing of a bug or asking questions (repeatedly). It's difficult for a user to discover that they must drag to the top of the dashboard (and that target is small), even if they know to drag.

**Describe the solution you'd like**
 Ideally it would be triggered regardless of where you dragged it to and automatically added it to the top.

**Comment by JunlinC** [comment]
🏷 dashboard

**Comment by JunlinC** [comment]
@steejay 🙏 🏷 UX

**Comment by junlincc** [comment]
@zuzana-vej added to post 1.0 roadmap inbox. the current experience is driving me crazy as well......... https://github.com/apache-superset/superset-roadmap/projects/1

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/11525 done

**Comment by zuzana-vej** [comment]
I don't know how I missed this update! But just tried to today and it works perfectly now. Thanks!
