### ISSUE TITLE
[SQL Lab] Directly export query results to .csv

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#10331]
**Is your feature request related to a problem? Please describe.**
User wants to export 300,000 rows of query results to .csv file. But sql lab only allow user to run the query first, download all the results to browser and display them in a table, then user can click the .csv button to export it to a file.

This way makes user less productive. Issues:
- Download huge result data took a lot of browser's localStorage, user will see the warning message and may not know how to do next
- Sql lab by default only show 1000 rows of results. In order to have full results in .csv file, user have to change row limit to a huge number. otherwise .csv file only contains 1000 rows of results.
- Display 300,000 rows in sql lab is not necessary. User barely can see that much of rows in small area.

**Describe the solution you'd like**
Besides Run Query button, we can show a Export .CSV button, so that user can direct export all query results to .csv, without display them in sql lab results table.

**Comment by JunlinC** [comment]
unsolved, reopening
