### ISSUE TITLE
Filter isn't applied to word cloud chart on a dashboard

### ISSUE THREAD

**Issue by bryanck** [apache/incubator-superset#10348]
If you apply a filter to a dashboard that has a word cloud chart on it, the word cloud chart will not be filtered.

### Expected results

When a filter is applied to a dashboard, the word cloud chart should have the filter applied as well.

### Actual results

The filter is not applied and the query sent to the backend does not include the filter. However, if you click on the ellipsis menu and "Explore" the word cloud chart in the chart editor, then the filter shows up and is applied.

#### How to reproduce the bug

1. Create a filter box
2. Create a word cloud chart that uses the same datasource as the filter box
3. Create a dashboard and place the filter box and the word cloud chart on it.
4. Apply a filter using the filter box.
5. The filter is not applied to the word cloud chart

### Environment

- superset version: 0.37.0 RC 2
- python version: 3.6.10
- node.js version: 12.14.1
- npm version: 6.13.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Thanks for reporting! I'll investigate.

**Comment by villebro** [comment]
I reproduced the problem. I have a working solution, but need to add proper tests to ensure this doesn't happen again. The fix will unfortunately probably need to trigger `rc3`.
