### ISSUE TITLE
Why is email uniqueness enforced? 

### ISSUE THREAD

**Issue by durchgedreht** [apache/incubator-superset#10343]
We use custom authentication and have different roles in our application. Roles work, but we have a problem when we let Superset auto-create users based on our authentication as Superset throws an error if the Email is already existing.  

I would expect a key that identifies the user - which is the username. I do not know why Email would need to be unique? A single user could hold two usernames with different roles which is quite common in enterprise apps.

This way you end up creating fake emails id1@fake.com, id2@fake.com,... (not even sure if None bypasses this issue).

This is also blocking us from using email functionality. Is there a way to omit the email check by config?
 If not, will changing the Superset DB DDL (removing unique constraint) be resulting in an app disaster because of multiple email entries?

Code in the custom_security_manager looks like (all vars are Strings that have been filles by our custom authentication, nothing special here on the user creation):

```
                    user = self.appbuilder.sm.add_user(
                        username    = user_login,
                        first_name  = user_first_name,
                        last_name   =user_last_name,
                        email       = user_email_address,
                        role        = user_registration_role,
                    )
```

**Comment by etr2460** [comment]
I can't comment on why email uniqueness was originally enforced, but you should be able to make multiple users connect to the same email by appending `+something` to the email address.

So you could have an admin account connected to `my.name+admin@example.com` and another account connected to `my.name+restricted@example.com`, and emails should all end up in `my.name@example.com`'s inbox.

I'd recommend the above workaround as opposed to manually removing the unique constraint, as there may be issues/implications with diverging from Superset's db schema. Hope this helps!

**Comment by vivek-kandhvar** [comment]
Is there an answer to this? Appending some text doesn't make sense. Length of the email field is also limited, which would anyways not help.

**Comment by erviszyka-workable** [comment]
Hello, is it possible to have multiple users with the same email?

**Comment by Yuval-Moshe** [comment]
Hi, is there a solution for this one yet other than just setting random strings?

**Comment by rusackas** [comment]
> Hi, is there a solution for this one yet other than just setting random strings?

If there's a better architecture, you're welcome to propose and implement a solution via a SIP. Maybe something like using a UUID for the user as the primary key. This would allow any number of accounts with the same email address, but that might drive certain administrators (and users) crazy for other reasons, thus a need for a SIP/consensus.
