### ISSUE TITLE
Rendering Visualizations for customized engines

### ISSUE THREAD

**Issue by ShengyaoQian** [apache/incubator-superset#1035]
We've added a third datasource to caravel. The code for this change is completely separated. But when it comes to rendering the UI part, I have to add the datasource id field in the Slice model in models.py and in the explore function in views.py so it can acknowledge this new datasource. And load viz for it. Can you make this more generic so when we add a new source, the views part can automatically recognize it. In this way we can add our customized part separately and still use your package so we don't need to maintain our own fork.

**Comment by ShengyaoQian** [comment]
@joshwalters

**Comment by xrmx** [comment]
@ShengyaoQian sorry but i haven't understood what your issue is. If you need some changes feel free to send a pull request so it's easier to understand what you want to do.

**Comment by ShengyaoQian** [comment]
https://github.com/airbnb/caravel/pull/1078

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 591 days. Feel free to comment and request for this issue to be reopened.
