### ISSUE TITLE
bug:  Integrity error, probably unique constraint  

### ISSUE THREAD

**Issue by yuexianchao** [apache/incubator-superset#10358]
For different dB, adding the same table name will result in an error. The source is two different dB, the index of tables table unique (table_ Name) should be changed to unique (database_id,table_name)I hope this problem can be corrected in the next version. Thank you

**Comment by dpgaspar** [comment]
Hi @yuexianchao thank you for reporting this. 

I can't reproduce with the current master. Can you please post the version of superset you're using?

**Comment by yuexianchao** [comment]
> Hi @yuexianchao thank you for reporting this.
> 
> I can't reproduce with the current master. Can you please post the version of superset you're using?
0.36.0 version ,   Adding the same table in different database connections will give an error, the table name already exists

**Comment by yuexianchao** [comment]
> > Hi @yuexianchao thank you for reporting this.
> > I can't reproduce with the current master. Can you please post the version of superset you're using?
> > 0.36.0 version ,   Adding the same table in different database connections will give an error, the table name already exists

Integrity error, probably unique constraint

**Comment by danilostochi** [comment]
I have the same error!
Version Superset: 0.36.0
![image](https://user-images.githubusercontent.com/68624533/88449718-74605600-ce1f-11ea-86cb-15f6a6e4df71.png).

Base: Postgres
I have two schema, cliente01 and cliente02, this schema has tables same name "teste".

Superset:
when trying to call as different schema tables, we have an error.
"Integrity error, probably unique constraint"

.gif
![error](https://user-images.githubusercontent.com/68624533/88449957-88a55280-ce21-11ea-9f9c-63418c97bf3b.gif)
