### ISSUE TITLE
Front-end changes not reflecting in superset

### ISSUE THREAD

**Issue by sedhha** [apache/incubator-superset#10352]
Superset Version: 0.36.0
OS: Ubuntu 16.04 LTS
node version: 12.18.2
npm version: 6.14.5

When I try to make changes in superset frontend and then build those changes in dev server by running the command in incubator-superset/superset-frontend

npm install
npm install webpack
npm run dev-server

I get this error:
![image](https://user-images.githubusercontent.com/36355685/87748018-72d8d180-c812-11ea-9d1d-f7f8ce9016e1.png)
When I view log file, I get this:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev-server' ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]
5 info lifecycle superset@0.999.0-dev~predev-server: superset@0.999.0-dev
6 info lifecycle superset@0.999.0-dev~dev-server: superset@0.999.0-dev
7 verbose lifecycle superset@0.999.0-dev~dev-server: unsafe-perm in lifecycle true
8 verbose lifecycle superset@0.999.0-dev~dev-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/s$
9 verbose lifecycle superset@0.999.0-dev~dev-server: CWD: /home/shivam/apache_superset/incubator-superset/superset-frontend
10 silly lifecycle superset@0.999.0-dev~dev-server: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webp$
10 silly lifecycle ]
11 silly lifecycle superset@0.999.0-dev~dev-server: Returned: code: 137  signal: null
12 info lifecycle superset@0.999.0-dev~dev-server: Failed to exec dev-server script
13 verbose stack Error: superset@0.999.0-dev dev-server: `NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node$
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid superset@0.999.0-dev
15 verbose cwd /home/shivam/apache_superset/incubator-superset/superset-frontend
16 verbose Linux 5.3.0-1030-gcp
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev-server"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 137
22 error superset@0.999.0-dev dev-server: `NODE_ENV=development BABEL_ENV=development node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode=development`
22 error Exit status 137
23 error Failed at the superset@0.999.0-dev dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by rusackas** [comment]
Hmmmm... I'm curious why you've got the `npm install webpack` step there. Webpack is already in the devDependencies of package.json. It may sound basic, but I'm curious what happens if you `rm -rf node_modules` then only run `npm install` and `npm run dev-server`

**Comment by sedhha** [comment]
So basically superset freezes here: 
![image](https://user-images.githubusercontent.com/36355685/87845787-21027b00-c8e8-11ea-8f55-ebf93bb92a53.png)
I tried checking 9000 port hoping that maybe it's running but it's not.

I had one big question, git clone <superset git repository> is only if you have docker right? When I did a venv installation, i didn't find any superset-frontend folder. To build the changes in venv based installation as per the [instructions](https://superset.incubator.apache.org/installation.html) where should we run the above commands to see the changes? Just curious, since there's no such directory when the installation is done virtually.

**Comment by rusackas** [comment]
You'd want to clone the github repo to do run superset in venv OR in docker. Did you get the code you're running from somewhere other than github? Also, I'm not sure why you're hitting the system limit error above, but it doesn't seem to be complaining about not finding files in the `superset-frontend` folder. Maybe @craig-rueda has better advice than me here 🤔

**Comment by sedhha** [comment]
I did a `pip install apache_superset` after creating a venv. Also I did follow your preset blog on adding custom ui and youtube video as well. What I discovered that when I do `git clone`  instead of a `pip install apache_superset` you don't get a `superset-frontend` folder.  Instead you get a similar structure which is generally located under `/venv/lib/python3.x/site-packages/superset/static/assets `. But the files within this aren't structurized same as you have when you do a `git clone `. If you want me to go with exact `git clone ` then in that case if I am not using `docker-compose up` then I don't see any way to start superset or proceed installation after that in `venv`. Also just wanted to confirm if you have tried running all the plug in changes in `superset version 0.36.0` also? Seems like this is the only difference that I have in installation and setting up pluggin. Rest all, I have been doing exactly the same things using `yeoman` and then making additions in `package.json` and `MainPreset.jsx`.

**Comment by mistercrunch** [comment]
I haven't read the whole thread, but you don't want to run `pip install apache_superset`, as it will install the version from pypi into your site-packages and use that. With a `venv` you want to `pip install -e .` - that command should fixes that. It basically puts symlinks into your site-packages that point to your local repo.

**Comment by sedhha** [comment]
Just for more clarification, so you mean git clone and then make a venv within `incubator-superset` directory and then do a` pip install -e`?

**Comment by sedhha** [comment]
@mistercrunch You mean to create `venv` and `git clone` into `venv` or `git clone` and then create `venv` in there?
