### ISSUE TITLE
Interlinking of visuals in a dashbaord

### ISSUE THREAD

**Issue by prachigupta2607** [apache/incubator-superset#10353]
Hi,

I am new to superset. My requirement is to create dashboards having interlinked visuals. If I click on any part, a bar or a Slice of pie, other visuals should be updated. I am not getting how to do that. I read somewhere that we will have to make code changes but I am not getting proper way to do that.

**Comment by JunlinC** [comment]
Hi, this is feature is on our roadmap, to receive status update or contribute to the project, please join our slack channel - https://apache-superset.slack.com/archives/C0188FT3V2S #dashboar-filters.
