### ISSUE TITLE
Pivot Table : Ability to keep the same granularity in the time section when using the time_column in the GROUP BY

### ISSUE THREAD

**Issue by eugeniamz** [apache/incubator-superset#10362]
In a Pivot Table if changing the time grain of the data time field and select the Time field as a Group By field, it does not do respect the Time Grain granularity. 

![image](https://user-images.githubusercontent.com/58375897/87861779-69855d00-c917-11ea-8410-e4269d774727.png)

### Expected results

Rows of the GROUP BY be grouped per week. 

### Actual results
Shows the raw data.

#### How to reproduce the bug

1. Go to : Pivot Table  - Select a Time grain grater than the raw data and select the Time Column field as GROUP BY field.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [ C] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
This has been fixed by #10344
