### ISSUE TITLE
Integrate a headless browser to render Slices as images

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#1037]
If we had a toolkit to render slices (and dashboards) as images, it could be useful to use in emails, and to create thumbnails to use in the UI. For instance a gallery of dashboards or slices would be very nice.

It seems like Phantom.js may works nicely for that.

**Comment by mahendra** [comment]
you can see an implementation here - https://github.com/apache/incubator-superset/pull/5294

Easy to wrap an API around it.
