### ISSUE TITLE
Unexpected error cannot import name 'PhoenixDialect'  

### ISSUE THREAD

**Issue by LucasDurian** [apache/incubator-superset#10375]
I have already installed superset,however,I cannot connet Hbase via Phoenix as "Unexpected error cannot import name 'PhoenixDialect'  ". Hopefully, I can receive your reply. Thanks a lot.

**Comment by willbarrett** [comment]
@LucasDurian I don't believe Superset has direct support for HBase, but a couple of options for connecting are detailed in this issue https://github.com/apache/incubator-superset/issues/9720 - can you share more about your setup so we can help you?
