### ISSUE TITLE
SQL Lab database/tables permission issues

### ISSUE THREAD

**Issue by redmonki** [apache/incubator-superset#10370]
Permissions assigned to a user roles are not being propagated in SQL Lab. For example, a database has two tables "Table A" and "Table B". The user role was assigned permission to {database}.{Table A}. But, the user can not see the database in SQL Lab and is presented with an error "It seems you don't have access to any database". If the permissions are assigned at data base level, the user can query both the tables.

### Expected results

Use should only be allowed to query the tables that they are permitted to.

### Actual results

If the permissions are assigned at table lever, the user is presented with an error. If permissions are set at database level, the user can see and execute queries against all the tables.

#### Screenshots

Error when "database access" is not assigned.
![image](https://user-images.githubusercontent.com/3455037/88002795-36c69a80-cab8-11ea-8837-78809c2437c9.png)

#### How to reproduce the bug

1. Create a new role and assign the users to this role in addition to "Gamma" and "sql_lab" roles.
2. They are allowed to query a {datasource}.{table}
3. The user goes to the sql editor
4. Runs into the error: "It seems you don't have access to any database"

### Environment
- superset version: `0.36`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@redmonki Can you please describe the issue you're encountering?

**Comment by redmonki** [comment]
@nytai updated the bug with steps to reproduce

**Comment by chuancyzhang** [comment]
I agree。

**Comment by grvhi** [comment]
I have also come up against this problem.

**Comment by sankeshi** [comment]
same problem ,so how can just show and access the authoried tables in sql editor?

**Comment by AbhishekPabba98** [comment]
I came across the same problem and wanted to know whether anyone found the solution for this. Please help me with the solution if you have solved it.

Thanks a lot in advance.
