### ISSUE TITLE
Pivot Table can't display Null value when some column is null

### ISSUE THREAD

**Issue by chuancyzhang** [apache/incubator-superset#10373]
when some datasource column is null, Pivot Table can't display Null value.
### Expected results
![image](https://user-images.githubusercontent.com/23111194/88021382-f589c580-cb5f-11ea-8b60-c3fa0ae5e42b.png)

### Actual results
![image](https://user-images.githubusercontent.com/23111194/88021194-aa6fb280-cb5f-11ea-82c7-cfe960d0942a.png)

#### How to reproduce the bug

1. Go to Chart
2. Click on Pivot Table
3. Scroll down to some Null Value in datasource

### Environment

(please complete the following information):

- superset version: 0.36.0
- python version: 3.6.6
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Finally, I find the bug that is DataFrame in PivotTableViz Class not fill Null. pandas will throw away nulls when grouping/pivoting,
so i substitute NULL_STRING for any nulls in the necessary columns.

```
df = df.fillna(value=NULL_STRING).pivot_table(
            index=groupby,
            columns=columns,
            values=metrics,
            aggfunc=aggfunc,
            margins=self.form_data.get("pivot_margins"),
        )
```

**Comment by villebro** [comment]
Thanks for opening this ticket @chuancyzhang ! Your proposed solution looks valid; would you be interested in opening a Pull Request for this?

**Comment by chuancyzhang** [comment]
> Thanks for opening this ticket @chuancyzhang ! Your proposed solution looks valid; would you be interested in opening a Pull Request for this?

please refer PR [#10371](https://github.com/apache/incubator-superset/pull/10376)

**Comment by GiannisDimitriou** [comment]
@villebro is this issue fixed?

I am experiencing a similar issue, when the `Group By` column has null value it is not displayed at all.

I can open a new ticket if this is a different issue after all
![image](https://user-images.githubusercontent.com/47314887/99085598-0f4c8e00-25d1-11eb-99f7-b3986e4fbc0f.png)

**Comment by villebro** [comment]
@GiannisDimitriou please open a new ticket if this problem persists in master branch or the latest released version.
