### ISSUE TITLE
superset Database on mysql Unexpected error name '_mysql' is not defined 

### ISSUE THREAD

**Issue by liuyuchuan** [apache/incubator-superset#10396]
i install superset on MacOS 10.15.5
when i want to add the DB source of mysql, i click the  button of [Test Connection],they out the error message

```
ERROR: Unexpected error occurred, please check your logs for details
```

then i see the console out the error info
```
Unexpected error name '_mysql' is not defined
ERROR:superset.views.core:Unexpected error name '_mysql' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Jul/2020 23:10:09] "POST /superset/testconn HTTP/1.1" 400 -
```

### Expected results

i don't know what to do, please tell me what to do.

#### How to reproduce the bug

1. when i running the cmd of start superset and visit the web http://localhost:8088/, 
2. use the menu -- > Sources --> Databases, input something then Click on 'Test Connection'
```
Unexpected error name '_mysql' is not defined
ERROR:superset.views.core:Unexpected error name '_mysql' is not defined
INFO:werkzeug:127.0.0.1 - - [22/Jul/2020 23:10:09] "POST /superset/testconn HTTP/1.1" 400 -
```

### Environment

(please complete the following information):

- superset version: `superset 0.36.0`
- python version: `Python 3.7.7`
- node.js version: `node v12.10.0`
- npm version: `npm v6.11.3`
- mysql version:`mysql 8.0.19`
- mysqlclient version:`mysqlclient 2.0.1`
- mysql-connector-python version:`mysql-connector-python 8.0.21`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Can you post the mysql URI you're using?

**Comment by liuyuchuan** [comment]
it's my post URI: Request URL: http://127.0.0.1:8088/superset/testconn


![image](https://user-images.githubusercontent.com/12453224/88256484-036d5100-ccee-11ea-906b-cbcdc49edab8.png)

**Comment by dpgaspar** [comment]
oh, I haven't made my self clear, I mean the SQLAlchemy URI. Or send the payload your sending for the HTTP POST on http://127.0.0.1:8088/superset/testconn

**Comment by willbarrett** [comment]
Please remember to remove your secrets before posting :)

**Comment by willbarrett** [comment]
The same issue has now been reported in #10495

**Comment by liuyuchuan** [comment]
i am sorry, i forget.

when i try use the SQLAlchemy URI 

mysql://root:Root1234@localhost/superset

mysql+mysqldb://root:Root1234@localhost/superset

the question is same.

**Comment by liuyuchuan** [comment]
OMG!
The problem is solved after i  installed the pysql driver like this: 
`pip install pymysql`
then i use the SQLAlchemy URI like this: 
`mysql+pymysql://root:Root1234@127.0.0.1:3306/superset
`

![image](https://user-images.githubusercontent.com/12453224/90464710-82fd0d00-e140-11ea-8f2c-75af35a54dd6.png)

**Comment by liuyuchuan** [comment]
mth

**Comment by ananthagopi9381** [comment]
where we are using the IP address instead of localhost it's showing the same error

**Comment by fly904021125** [comment]
> OMG! The problem is solved after i installed the pymysql driver like this: `pip install pymysql` then i use the SQLAlchemy URI like this: `mysql+pymysql://root:Root1234@127.0.0.1:3306/superset `
> 
> and i use the uri like this is work too. `mysql+mysqlconnector://root:Root1234@127.0.0.1:3306/superset `
> 
> ![image](https://user-images.githubusercontent.com/12453224/90464710-82fd0d00-e140-11ea-8f2c-75af35a54dd6.png)
> 
> i want to know why i can't use the SQLAlchemy URI like this:
> 
> ```
> mysql+mysqldb://root:Root1234@127.0.0.1:3306/superset
> or
> mysql://root:Root1234@127.0.0.1:3306/superset
> ```

it also works for me.
