### ISSUE TITLE
form_data on request could be editable, and run a custom query

### ISSUE THREAD

**Issue by rubenSastre** [apache/incubator-superset#10411]
The form_data send on a request, could be modified by a "gamma" user and read all the content from the database.
By modifying the request, we are able to forge our own query and interact with the current database in a manner not provided by the application. For instance, we can get, the current database, the current user, the database version.
By modifying the "datasource" parameter (which is in the format XX_table, where XX is the ID, we can list all the tables connected with superset.

### Screenshots
Getting all the tables by changing the ID on XX_table:
![image](https://user-images.githubusercontent.com/25669722/88289130-0f104600-ccf5-11ea-8de9-b7895f725698.png)

Finding the database and version:
![image](https://user-images.githubusercontent.com/25669722/88289281-50a0f100-ccf5-11ea-98d6-bf5df366cd8b.png)

Changing tables and values to add on the query:
![image](https://user-images.githubusercontent.com/25669722/88289799-12f09800-ccf6-11ea-8ca4-446ecff2aa30.png)

- superset version: `0.35`
- python version: `3.6`

**Comment by dpgaspar** [comment]
Hi @rubenSastre thank you for reporting.

Will try to replicate on current master
