### ISSUE TITLE
when I use docker-compose error happen

### ISSUE THREAD

**Issue by dingsheng999888** [apache/incubator-superset#10438]
when I use docker-compose to start superset,error happen.

### Expected results

I want superset-init container to work,but error happen

### Actual results

superset_init    | Traceback (most recent call last):
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_master
superset_init    |     ws.require(__requires__)
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 899, in require
superset_init    |     needed = self.resolve(parse_requirements(requirements))
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 790, in resolve
superset_init    |     raise VersionConflict(dist, req).with_context(dependent_req)
superset_init    | pkg_resources.ContextualVersionConflict: (slackclient 2.6.2 (/usr/local/lib/python3.6/site-packages), Requirement.parse('slackclient==2.5.0'), {'apache-superset'})
superset_init    | 
superset_init    | During handling of the above exception, another exception occurred:
superset_init    | 
superset_init    | Traceback (most recent call last):
superset_init    |   File "/usr/local/bin/superset", line 4, in <module>
superset_init    |     __import__('pkg_resources').require('apache-superset==0.999.0.dev0')
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3256, in <module>
superset_init    |     @_call_aside
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
superset_init    |     f(*args, **kwargs)
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
superset_init    |     working_set = WorkingSet._build_master()
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
superset_init    |     return cls._build_from_requirements(__requires__)
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
superset_init    |     dists = ws.resolve(reqs, Environment())
superset_init    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 785, in resolve
superset_init    |     raise DistributionNotFound(req, requirers)
superset_init    | pkg_resources.DistributionNotFound: The 'slackclient==2.5.0' distribution was not found and is required by apache-superset
superset_init exited with code 1

### Environment

(please complete the following information):

the newest master code,with docker-compose up

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@dingsheng999888 can you try running `docker-compose up --build` that might fix it.

**Comment by dingsheng999888** [comment]
"docker-compose up --build" doesn't works .At first time compose-up work well, but now i want append cx_oracle to support oracle, and  rm all container and only keep "preset/superset:dev" and use docker-compose up ,and this error happen.Should I remove "preset/superset:dev" to solve this error?

**Comment by dingsheng999888** [comment]
It looks like the newest superset app doesn't install in the superset_init container,but I see the the newest superset app has been install in the superset container . when building  superset-init,it use caches think the cache cause the error.

**Comment by dingsheng999888** [comment]
When I build superset container the log is:
"Installing collected packages: apache-superset
  Attempting uninstall: apache-superset
    Found existing installation: apache-superset 0.999.0.dev0
    Uninstalling apache-superset-0.999.0.dev0:
      Successfully uninstalled apache-superset-0.999.0.dev0
  Running setup.py develop for apache-superset
Successfully installed apache-superset"
but when I go into the superset container I see:
"superset@09c1fd5ef0f8:/app$ cat /usr/local/bin/superset
#!/usr/local/bin/python
# EASY-INSTALL-DEV-SCRIPT: 'apache-superset==0.999.0.dev0','superset'
__requires__ = 'apache-superset==0.999.0.dev0'
__import__('pkg_resources').require('apache-superset==0.999.0.dev0')
__file__ = '/app/superset/bin/superset'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
superset@09c1fd5ef0f8:/app$ 
"
I don't know what happend.

**Comment by melarsen** [comment]
Any update on this? The docker-compose setup in the docs is currently not working due to this. Any steps recommended for a manual solution to this?

**Comment by dingsheng999888** [comment]
you can try to change the requirements.txt "slackclient==2.5.0"

**Comment by melarsen** [comment]
The file ./requirements/base.txt already states slackclient==2.5.0

**Comment by dingsheng999888** [comment]
which branch you have pull?I pull the 0.37 and it works.

**Comment by willbarrett** [comment]
The way dependencies are handled was recently updated, requiring a new docker build from scratch. The issues you are experiencing are the result of cached dependencies. Please follow the instructions here: https://github.com/apache/incubator-superset/issues/10149#issuecomment-671067844 to resolve the issue.

Closing as a duplicate.
