### ISSUE TITLE
Is it possible to view all dashboard reports with live stream? 

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#10449]
**Is your feature request related to a problem? Please describe.**
Try to see/implement all dashboards with live stream(auto refresh).

**Describe the solution you'd like**
Dashboard reports has to be update/sync with Data source in every second with user refreshing dashboard/reports. Is there any way to implement socket connections for dashboard charts/reports?

**Describe alternatives you've considered**
Since we have module flask socketio (https://flask-socketio.readthedocs.io/en/latest/), can we achieve this or do we have any cons respect to data sources? 

**Additional context**

**Comment by willbarrett** [comment]
@thammaneni this is not currently supported, though we've discussed moving queries to a socket connection in the future. I'd be concerned about refreshing your dashboards that frequently. Depending on the underlying database, this could overwhelm your database server with expensive queries. Are you using a real-time database like Druid?
