### ISSUE TITLE
Sqllab run button doesn't expand for large text

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#10440]
Type query in sqllab and select the query

### Expected results

![image](https://user-images.githubusercontent.com/5727938/88587156-5b67c880-d00a-11ea-835f-9f2a2c8a2ebd.png)

### Actual results
![image](https://user-images.githubusercontent.com/5727938/88587117-468b3500-d00a-11ea-9ce5-fa270a661f9a.png)

Probably introduced here: https://github.com/apache/incubator-superset/commit/0483c26254bec2d70c8e86c1468ecb7d891ea102

cc @mistercrunch

**Comment by mistercrunch** [comment]
Oops, my bad. Fix coming right up
blame: https://github.com/apache/incubator-superset/pull/10404
fix: https://github.com/apache/incubator-superset/pull/10461
