### ISSUE TITLE
Libs with GPL licenses in Superset

### ISSUE THREAD

**Issue by Rosso-corsa** [apache/incubator-superset#10448]
I found out that these two libraries are used in Apache Superset:
pylint 
po2json

These libraries have GPL license([the first](https://pypi.org/project/pylint/), [the second](https://github.com/mikeedwards/po2json/blob/master/LICENSE)). As I see, libraries with GPL cannot be used in Apache products: "_However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law_" ([link](https://www.apache.org/licenses/GPL-compatibility.html)).

Could you confirm that there is a problem with these two libs license or it's my misunderstanding?

**Comment by mistercrunch** [comment]
- `pylint` is a dev dependency and isn't bundled with or needed to run/operate the software, it is use (and commonly used) to help us lint the code (code quality)
- similarly, `po2json` is a dev dependency and isn't bundled with or needed to run/operate the software, it is used to process our translations string 

From my understanding (I'm not a lawyer, so don't take this as legal advice) those are not issues.
