### ISSUE TITLE
About superset-0.37 run error:Requirement.parse('apispec[yaml]<2,>=1.1.1'))

### ISSUE THREAD

**Issue by michaelai0313** [apache/incubator-superset#10447]
### Expected results

INFO:werkzeug: * Running on XXXXXXX

### Actual results

pkg_resources.VersionConflict: (apispec 3.3.1 (d:\test110\envs\lib\site-packages), Requirement.parse('apispec[yaml]<2,>=1.1.1'))

### Environment

- superset version: 0.37
- python version: 3.7.3
- node.js version: v12.4.0
- npm version: 6.9.0

### Additional context

modify requirements.txt can fix this bug
apispec[yaml]==3.3.1    -> apispec[yaml]==1.3.3

**Comment by villebro** [comment]
@michaelai0313 `apispec==3.3.1` is required by `flask-appbuilder==3.0.1` which we're using. Perhaps you have an old version of `flask-appbuilder` installed which is causing this conflict?

**Comment by michaelai0313** [comment]
> @michaelai0313 `apispec==3.3.1` is required by `flask-appbuilder==3.0.1` which we're using. Perhaps you have an old version of `flask-appbuilder` installed which is causing this conflict?

Thankyou，when I run install requirements.txt again, Superset was  runing successfully.
