### ISSUE TITLE
[React CRUD] Bogus error message on duplicated dataset creation

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#10460]
### Expected results

Error msg telling that dataset already exists

### Actual results

Error saving dataset Object Object

#### Screenshots

![image](https://user-images.githubusercontent.com/5727938/88740567-639b3300-d0f2-11ea-9b14-2fe1e9725b4d.png)

#### How to reproduce the bug

1. dataset list view in react CRUD
2. create dataset
3. try to create same dataset

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

latest master

cc @nytai

**Comment by mistercrunch** [comment]
@lilykuang @nytai

**Comment by nytai** [comment]
should have been fixed with https://github.com/apache/incubator-superset/commit/78cad9a4a86179c2305036d08740c0f01c4b0695#diff-910af846ee243a9628839783c7553af5R100
