### ISSUE TITLE
Question: Does Superset support Async mode querying in charts

### ISSUE THREAD

**Issue by juneauwang** [apache/incubator-superset#10463]
Hi,
We set up a Superset cluster with version below:
apache-superset        0.34.0
celery                 4.4.2
gunicorn               19.9.0
PyHive                 0.6.2
Python            3.8.2

And build some datasource with Async mode on, charts and dashboards. 

However, we found the query in SQL Lab can be run in asynchronous mode but queries in charts can't be run in async mode. 

Does Superset Asynchronous mode only support SQL Lab Queries yet?

**Comment by villebro** [comment]
Not yet. There is a Superset Improvement Proposal for adding global async query support that has been approved, but not yet implemented: https://github.com/apache/incubator-superset/issues/9190 .

**Comment by juneauwang** [comment]
Thanks a lot! @villebro
