### ISSUE TITLE
Nessus detected CGI Generic SQL Injection (blind)

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#10469]
### Expected results

No issue when scanning Apache Superset with Nessus Scanner

### Actual results

Severity of this issue is **High** as reported by Nessus

```
Using the POST HTTP method, Nessus found that :

+ The following resources may be vulnerable to blind SQL injection :

+ The 'csrf_token' parameter of the /login/ CGI :

/login/ [username=&password=&csrf_token=ImE2MWI1OWIwMWFlMTY5ZWM3MzQxM2Ji
OWU4YjYxZjBjOWNhNTg4NWMi.XyD1qA.BEgX-o2rsY4akXtPmPtgh6LG0rQzz&password=&
csrf_token=ImE2MWI1OWIwMWFlMTY5ZWM3MzQxM2JiOWU4YjYxZjBjOWNhNTg4NWMi.XyD1
qA.BEgX-o2rsY4akXtPmPtgh6LG0rQyy]

-------- output --------
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF tokens do not match.</p>


-------- vs --------
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF token is invalid.</p>
------------------------
```

#### How to reproduce the bug

1. Have Nessus Scanner installed
2. Scan for vulnerablities in Superset

### Environment

- superset version: `0.34.0`
- python version: `3.6.9`
- flask-appbuilder version: `2.1.9`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @syazwan0913 

This issue is already open on flask-appbuilder let's follow it there

**Comment by syazwan0913** [comment]
@dpgaspar Yeah sure.
