### ISSUE TITLE
dashboard slug is cleared on import

### ISSUE THREAD

**Issue by stuarthu** [apache/incubator-superset#10479]
Import a dashboard using `superset import-dashboards` cmd

### Expected results

dashboard is imported as yaml file described

### Actual results

dashboard is imported but slug is cleared

### Environment

(please complete the following information):

- superset version: `0.37`
- python version: `Python 3.8.5`
- node.js version: `v12.4.0`
- npm version: `6.14.7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The slug is cleared on purpose, which is to avoid conflict, see https://github.com/apache/incubator-superset/blob/master/superset/models/dashboard.py#L316.
But that behavior is not expected in some cases.
If a dashboard is exported to a yaml and imported later, I would expect the same dashboard gets overwritten rather than creating a new dashboard with an empty slug.
This is very useful when I want to create/update dashboard automatically without manual intervene.
If user wants to avoid conflict, user can manually edit dashboard yaml file and set slug to null instead of hard clear in superset code.

**Comment by stuarthu** [comment]
@mistercrunch

**Comment by villebro** [comment]
FYI slug importing was disabled on purpose in #10118 . @stuarthu can you elaborate on your use case so we can assess if the current flow should be changed?

**Comment by villebro** [comment]
For instance, we might want to introduce an option where the user can choose to 1) ignore the to-be-imported slug 2) overwrite a possibly conflicting pre-existing slug 3) fail the import on conflicting slug. I think this may be a good option going forward that supports most use cases.

**Comment by stuarthu** [comment]
@villebro 
The slug is cleared on purpose, which is to avoid conflict, see https://github.com/apache/incubator-superset/blob/master/superset/models/dashboard.py#L316.
But that behavior is not expected in some cases.
If a dashboard is exported to a yaml and imported later, I would expect the same dashboard gets overwritten rather than creating a new dashboard with an empty slug.
This is very useful when I want to create dashboard automatically without manual intervene.
If user wants to avoid conflict, user can manually edit dashboard yaml file and set slug to null instead of hard clear in superset code.

**Comment by andy-clapson** [comment]
> I am having the same problem as @stuarthu. I need to automate dashboard imports but it seems impossible to do this in a consistent way due to this slug clearing.
> 
> Anyone knows a way to solve this?

the best solution I've foubdn so far (as of version `1.5.1`) is to have an import script that roughyl does the following:
- finds target dashboard(s) to import, named by slug
- deletes any existing dashboards with that slug
- import the target dashboards
- then send a `PUT` to set the slug values on each
