### ISSUE TITLE
Database config

### ISSUE THREAD

**Issue by chart41** [apache/incubator-superset#10470]
Hello. Just installed apachesuperset on ubuntu 18.04.
When I trying to import some csv file, I can't to do it, because no one database there. I saw [this guide  ](https://superset.incubator.apache.org/installation.html) but don't understand how to connect any database.
Is it should be initialized in superset_config.py ? How to do it right? Could you send me some example of this file please.

**Comment by willbarrett** [comment]
Hi @chart41 - Superset's Github issues are for bug reports and development only. Please try asking your question on [tack Overflow](https://stackoverflow.com/questions/tagged/superset)
