### ISSUE TITLE
In SQL lab, "CTAS" button not working: success message (without table name), and no table created actually

### ISSUE THREAD

**Issue by akelai** [apache/incubator-superset#10497]
In SQL Lab, I have a working query (a simple join of two tables, both in th "public" schema of a PostgreSQL database).
Everything works (Results, Save Query, Explore, CSV, ...) except the "**CTAS**" button ("Create table as with query results"):

I try to write a valid string into the input field on its left (I've tried e.g. "test01", "public.test01", with or without single or double quotes...), i.e. a string that could be used as a name for a new table in the PostgreSQL database, but when I click the "CTAS" button I get a message that looks like everything went fine, but actually it has no table name in it, and in fact there is no new table created in the database. The message I get is:

> Table [] was created

...it's in a light cyan message box, and on its right there is a "Query in a new tab" button.

Superset version is **0.35.2**

Something's wrong on my side, or bug?

**Comment by willbarrett** [comment]
@bkyryliuk do I remember correctly that this was added by Dropbox? Any quick brainstorms on what might be happening here?

**Comment by bkyryliuk** [comment]
dropbox changes were done after 0.35.2 - probably not relevant to this issue

**Comment by bkyryliuk** [comment]
there were some bugs in the flow we fixed, e.g. inconsistent schema handling - upgrading should solve the problem

**Comment by akelai** [comment]
Thanks, good to know. I'll check again after upgrading.
