### ISSUE TITLE
Trying to connect to a Mariadb

### ISSUE THREAD

**Issue by tiago-as** [apache/incubator-superset#10495]
Hi, I'm trying to connect superset to a remote Mariadb database. I've looked at the SQLAlchemy docs and it seems that the URI needed for this should be just like a mysql one.

I'm using the following URI: mysql+mysqldb://username:pwd@host/database

When I try to "Test Connection" the following lines appear on the server output:

```
Unexpected error name '_mysql' is not defined
ERROR:superset.views.core:Unexpected error name '_mysql' is not defined
```

I've followed the instructions in your documentation and installed the dependencies for mysql: https://superset.incubator.apache.org/installation.html?#database-dependencies

```
sudo apt install libmysqlclient-dev
python -m pip install mysqlclient
```
What am I missing?

Thanks in advance for any help regarding this matter.

**Comment by willbarrett** [comment]
Hi @tiago-as - what's your Superset version? This will help us track down the problem.

**Comment by tiago-as** [comment]
Hi @willbarrett pip list says the following version:
```
apache-superset        0.36.0
```

**Comment by willbarrett** [comment]
The same issue has been previously reported in #10396

**Comment by tiago-as** [comment]
@willbarrett thanks, somehow I missed that issue when I researched for similar stuff... Let me add information to my issue. I'm using Ubuntu 20.04 and Python version is 3.8.

**Comment by willbarrett** [comment]
@tiago-as I wonder if the Python version is to blame... 0.36.0 supports 3.6 and 3.7 explicitly. Would you be able to try one of those versions and see if it resolves the issue?

**Comment by tiago-as** [comment]
@willbarrett I'm not sure if I am able to donwgrade to 3.6, I'd have to check. But anyhow I'll try to see if I can do that. Nonetheless,
its a good think you guys already have feedback for Python 3.8, this way you can expect an issue. I'll get back with feedback when I'm able too.
Once again, thanks for the quick answers!

**Comment by tiago-as** [comment]
@willbarrett I just checked if I could downgrade to python3.6 or 3.7. I'm using a Ubuntu 20.04 machine and due to the client environment I have security restrictions that wont allow me to use a ppa for getting other python versions like https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa for example.

Is it possible for you guys to check if this issue is indeed python3.8 fault?
Thanks in advance

**Comment by willbarrett** [comment]
Hmm...looking at the older ticket it appears the problem is also present in Python 3.7.7 so my hunch is not supported by other evidence.
