### ISSUE TITLE
Allow changing the "Time Range" filter label #enhancement 

### ISSUE THREAD

**Issue by alextanghk** [apache/incubator-superset#10503]
When I'm working on a dashboard container several date filter but in current version, the time range filter can only name as time range, I could use the filter box title as their label but the style will not match the others unless I use title as the label for all of them.

Would it be possible to add feature to allow user change the "Time Range" label?

**Comment by junnychen** [comment]
> When I'm working on a dashboard container several date filter but in current version, the time range filter can only name as time range, I could use the filter box title as their label but the style will not match the others unless I use title as the label for all of them.
> 
> Would it be possible to add feature to allow user change the "Time Range" label?

do you mean allowing users to change the filter name on the filter box?

**Comment by junnychen** [comment]
do you mean add feature that allowing users to change the filters' name on the filter box?

**Comment by junlincc** [comment]
@alextanghk editing the filter chart title is the solution for now, but we can certainly consider a solution as we are moving to dashboard native filter. feel free to reach out to me in Slack to check on the status. closing this issue for now.
