### ISSUE TITLE
Doc or example around latest swagger API

### ISSUE THREAD

**Issue by feng-tao** [apache/incubator-superset#10520]
This is not really a bug but a question. Recently we move to 0.36 which has the openAPI. I would like to understand a bit more about the API. It would be good if there is any doc around the API with examples (or could help to point out which PRs contribute to the dashboard endpoint). Thanks. 

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Swagger is self documenting, take your browser to `/swagger/v1` and you'll see a bunch of interactive examples
<img width="929" alt="Screen Shot 2020-08-06 at 9 38 25 PM" src="https://user-images.githubusercontent.com/487433/89609595-2f7bec80-d82d-11ea-95e9-435c202dd63e.png">
