### ISSUE TITLE
Editing chart properties causes dashboards to become un-linked to the chart

### ISSUE THREAD

**Issue by suddjian** [apache/incubator-superset#10528]
When you edit chart properties via the "edit properties" modal, it breaks any dashboards the chart appears in.

### Expected results

The chart would still be associated with the dashboard

### Actual results

The chart is no longer associated with the dashboard

#### Screenshots

<img width="1655" alt="Screen Shot 2020-08-05 at 5 13 41 PM" src="https://user-images.githubusercontent.com/1858430/89476234-05e49780-d73f-11ea-998f-a2541c5d7d6c.png">
These two charts were edited, changing the title and the cache timeout

#### How to reproduce the bug

1. Add a chart to a dashboard
2. Use the "edit properties" modal to edit the chart
3. The chart is no longer associated with the dashboard

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/issues/11623

@kgabryje let's address these two issues together

**Comment by mistercrunch** [comment]
Is this still an issue?

**Comment by junlincc** [comment]
yes, i tested when i filed #11623 @mistercrunch 
![Uploading Screen Shot 2020-11-09 at 10.01.29 PM.png…]()

**Comment by kgabryje** [comment]
On it

**Comment by kgabryje** [comment]
I think it's a backend bug. After making a PUT request to /api/v1/chart/${slice_id} , the modified chart is not returned in the response to Dashboard view (or rather in data-bootstrap which is server-rendered).
@kkucharc Could you take a look?
