### ISSUE TITLE
Row Limit popover in SQL Lab is oddly formated

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#10525]
As titled. The buttons should be in the same row

#### Screenshots

![image](https://user-images.githubusercontent.com/7409244/89439755-7f5c9580-d6ff-11ea-869d-200b248a74d6.png)

### Environment

(please complete the following information):

- superset version: `master`

cc @rusackas @mistercrunch

**Comment by ktmud** [comment]
Same happens with dashboard time range filter: https://github.com/apache/incubator-superset/issues/10471

**Comment by mistercrunch** [comment]
Related to https://github.com/apache/incubator-superset/pulls?q=is%3Apr+is%3Aclosed++doctype ?
