### ISSUE TITLE
KeyError after installing a new plugin 

### ISSUE THREAD

**Issue by Alfran007** [apache/incubator-superset#10532]
### Expected results
Plugin should work without throwing any Error

### Actual results

```

superset_app_alfa2       | DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: postgresql://superset:XXXXXXXXXX@db:5432/superset
superset_app_alfa2       | ERROR:superset.models.slice:'hello_world'
superset_app_alfa2       | Traceback (most recent call last):
superset_app_alfa2       |   File "/app/superset/models/slice.py", line 173, in data
superset_app_alfa2       |     data = self.viz.data
superset_app_alfa2       |   File "/app/superset/utils/core.py", line 166, in __call__
superset_app_alfa2       |     value = self.func(*args, **kwargs)
superset_app_alfa2       |   File "/app/superset/models/slice.py", line 160, in viz
superset_app_alfa2       |     viz_class = viz_types[self.viz_type]
superset_app_alfa2       | KeyError: 'hello_world'

```

#### How to reproduce the bug

1. Install package for new plugin using `yeoman`.
2. Put the package inside `node_modules/@superset-ui`(rather than creating npm-link)
3. Deploy using `docker-compose up`.
4. Go to charts/add and open your plugin.

### Environment

- superset version: `0.999.0dev`
- python version: `Python 3.6.8`
- flask version: `Flask 1.1.2`
- node.js version: `v14.6.0`
- npm version: `6.14.7`

**Comment by mistercrunch** [comment]
Looks like you might be using an old version? Can you try on the latest `master`?

**Comment by Alfran007** [comment]
I tried with the latest version too. Seems like the problem was unable to get the configured key of `MainPreset.js` file inside the yeoman built package. I mentioned the same key `hello_world` in metadata field for `HelloWorld.tsx` and after a clean docker build it resolved this error. Closing the issue. Thank you.
