### ISSUE TITLE
How to sort table by timestamp by default?

### ISSUE THREAD

**Issue by zn19920623** [apache/incubator-superset#1055]
I have created a table and add it to dashboard.
But the table is always sorted by the first metric. How can I change the default sort key to timestamp?

Thx very much!

**Comment by JessicaDuan** [comment]
@zn19920623 you can find in "assets/visualizations/table.js", and search by the keyword "order("desc")".

**Comment by vnnw** [comment]
Care to give more details on how to edit the code to make the table order by timestamp by default?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 213 days. Feel free to comment and request for this issue to be reopened.
