### ISSUE TITLE
[Question]  

### ISSUE THREAD

**Issue by reenarosid** [apache/incubator-superset#10561]
We would like to document the APIs and corresponding function calls that are being made in the superset.  
Example :
http://localhost:8088/chart/edit/<id> 

for the above API call, a function will be triggered, and we would like to document that. 
But for chart and Dashboard module we weren't able to trace the function (edit, delete(single delete)).

Kindly give us some lead on how we can trace such API calls

**Comment by villebro** [comment]
Ping @dpgaspar
