### ISSUE TITLE
OAuth provider blocking failure

### ISSUE THREAD

**Issue by amitNielsen** [apache/incubator-superset#10568]
We have been using OAuth provider  feature for a while now
I tried upgrading to  the upcoming release 0.37 and found that the feature is now broken

### Expected results

sign in should redirect to provider actual login page

### Actual results
we get 400 response code and an internal exception

what actually happens.

#### Screenshots

![image](https://user-images.githubusercontent.com/47772523/89817491-e390b680-db50-11ea-9c63-0d97b87d198a.png)
![image](https://user-images.githubusercontent.com/47772523/89817519-f4d9c300-db50-11ea-968a-965b5f942cb6.png)

#### How to reproduce the bug

0. enable OAuth
1. Go to 'login page '
2. Click on 'OAuth provider then Sign-in'
4. See error in browser and logs

### Environment

(please complete the following information):

- superset version: `0.37`
- python version: `3.6`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Logs when clicking on login button:
superset_1       | DEBUG:flask_appbuilder.security.views:Provider: okta
superset_1       | DEBUG:flask_appbuilder.security.views:Going to call authorize for: okta
superset_1       | DEBUG:authlib.integrations.base_client.base_app:Saving authorize data: {'redirect_uri': 'https://localhost:8088/oauth-authorized/okta', 'url': 'https://<oursubdomain>.okta.com/oauth2/default/v1/authorize?response_type=code&client_id=None&redirect_uri=https%3A%2F%2Flocalhost%3A8088%2Foauth-authorized%2Fokta&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuZXh0IjpbIiJdfQ.fdfto7RZFzoca-BIwMaXI9t-jsGjhSPMH_ltWoj85-Y', 'state': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuZXh0IjpbIiJdfQ.fdfto7RZFzoca-BIwMaXI9t-jsGjhSPMH_ltWoj85-Y'}

when loading in browser the following link: https://localhost:8088/oauth-authorized/okta

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 681, in oauth_authorized
>     resp = self.appbuilder.sm.oauth_remotes[provider].authorize_access_token()
>   File "/usr/local/lib/python3.6/site-packages/authlib/integrations/flask_client/remote_app.py", line 74, in authorize_access_token
>     params = self.retrieve_access_token_params(flask_req, request_token)
>   File "/usr/local/lib/python3.6/site-packages/authlib/integrations/base_client/base_app.py", line 138, in retrieve_access_token_params
>     params = self.framework.generate_access_token_params(self.request_token_url, request)
>   File "/usr/local/lib/python3.6/site-packages/authlib/integrations/flask_client/integration.py", line 38, in generate_access_token_params
>     'code': request.args['code'],
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
>     raise exceptions.BadRequestKeyError(key)
> werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
> KeyError: 'code'

**Comment by villebro** [comment]
@amitNielsen did you check the required changes mentioned in `UPDATING.md`? See #9964 and the FAB link for context.

**Comment by amitNielsen** [comment]
@villebro I have not. will do

**Comment by amitNielsen** [comment]
@villebro after  review UPDATING.md it all worked out.
thanks for the great work

**Comment by villebro** [comment]
Happy to hear @amitNielsen 🙂
