### ISSUE TITLE
Dashboard Bind to specifc role

### ISSUE THREAD

**Issue by vbhama21** [apache/incubator-superset#10575]
Hi team,

i have a issue , i want to bind my dashboard to specific role rather than giving the ownership to each individual user .

What i want is let say we have a dashboard and i associate this dashboard to some specific role . than that role is automatically created by our custom security manager and role is assigned to him . so that he can view the dashboard.

So that i dont have to manually give access to ownership for that dashboard .
Any help is highly appreciated.

**Comment by dpgaspar** [comment]
Hi @vbhama21 there is a current proposal for this implementation on: https://github.com/apache/incubator-superset/issues/10408

Feel free to add any comments there.
