### ISSUE TITLE
Row level security filter

### ISSUE THREAD

**Issue by PragmaticDeveloper** [apache/incubator-superset#10577]
On the same table each role has a different condition clause.
Each user has a different role.
When I login as a user I expect a condition clause corresponding to the user/role role to be applied.
What happens is that for a given user/role applies clause from other user/role or no clause at all. 
A chart where this should take effect is a filter chart.
Please check it out. Is there a bug or I use this feature in wrong way.

### Expected results

Clause to be applied. Results to bi filtered according to the clause.

### Actual results

Applies clause which is set to different role or no clause applied. 

#### Screenshots

![image](https://user-images.githubusercontent.com/16608077/89916815-5a34bf00-dbf8-11ea-8886-9949f5685c27.png)

### Environment
- superset version: `0.36.0`

**Comment by villebro** [comment]
@PragmaticDeveloper there have been important fixes to RLS in the upcoming `0.37.0` release. I suggest testing the latest RC (`0.37.0rc4`) that will most likely become the official `0.37.0` release once the vote completes (hopefully soon).

**Comment by PragmaticDeveloper** [comment]
@villebro thank you! The issue is solved in v37.
