### ISSUE TITLE
Word_Cloud not working in superset 37

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#10588]
I am experiencing a new issue with word cloud charts on the latest release of superset 37.0rc4.

When I use the Public role (without login in) Word Cloud charts appears as 
<img width="609" alt="Screenshot 2020-08-12 at 15 16 04" src="https://user-images.githubusercontent.com/607430/90019469-bf4aec00-dcae-11ea-8b27-0b7ed64285e0.png">

In the logs I can see the following error : 

```
superset-37.0rc4/superset/models/slice.py", line 160, in viz
    viz_class = viz_types[self.viz_type]
KeyError: 'word_cloud'
ERROR:superset.models.slice:'word_cloud' 
```

When I log in as Admin user , the chart loads properly 
<img width="581" alt="Screenshot 2020-08-12 at 15 19 09" src="https://user-images.githubusercontent.com/607430/90019802-34b6bc80-dcaf-11ea-8ec5-6b9951e3ad51.png">
event if I still see the same ```KeyError: 'word_cloud'``` error message 

Additionally, inspecting the web page when not logged in shows the following error : 

``` Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)```

**Comment by lilila** [comment]
@villebro , do you know which authorisation I should add to the Public role to get the word cloud charts rendering properly ?

**Comment by villebro** [comment]
@lilila  This has been fixed in master branch and will be included in the next release: https://github.com/apache/incubator-superset/pull/10538 . If you wish you can probably cherry pick this into your release if that fixes the problem.

**Comment by villebro** [comment]
@lilila with regards to the `401` error, I believe you should set `PUBLIC_ROLE_LIKE_GAMMA = True` in your config, run `superset init` then add the datasource access to the dataset to the public role.

I think the exception you're seeing is mostly a cosmetic problem for now, so fixing the permissions should solve your problem.

**Comment by lilila** [comment]
you are great, thank you :D 
it works well

**Comment by lilila** [comment]
@villebro 
I just notice the new Word Cloud chart does not pick up adhoc filters.  :(

**Comment by villebro** [comment]
Thanks for reporting @lilila ! I will look at this shortly. In the meantime it would be great if you can open a new ticket with replication steps to make it easier to reproduce the bug and serve as an example for building a unit test.

**Comment by lilila** [comment]
Done here https://github.com/apache/incubator-superset/issues/10609
