### ISSUE TITLE
Word Cloud and adhoc Jinja filters in Superset 0.37.0

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#10609]
Filter values set up with Jinja syntax are not considered in the new version of Word Cloud chart

**Comment by villebro** [comment]
@lilila I am unable to reproduce the problem on `0.37.0`, see the attached screenshot where an ad-hoc filter leveraging jinja is correctly interpreted:
![image](https://user-images.githubusercontent.com/33317356/90327969-421ac200-dfa1-11ea-8dd1-ce2a3a39600e.png)

Can you describe your problem in greater detail?

**Comment by lilila** [comment]
If I create a simple table as : 

```
{% set title_target =   ' "'  + filter_values('title_target', 'Joker' )[0]  + '" '  %} 

SELECT {{title_target}}  as  title
```

and use this as a source of a word cloud chart, I get the following : 

<img width="929" alt="Screenshot 2020-08-17 at 07 06 24" src="https://user-images.githubusercontent.com/607430/90359100-41913280-e058-11ea-9d44-ad6000ca8b46.png">

**Comment by JunlinC** [comment]
🏷chart

**Comment by villebro** [comment]
Thanks @lilila , I'll look into this shortly!

**Comment by villebro** [comment]
L👀 king into this now
