### ISSUE TITLE
How to add a new chart plugin in superset0.37?

### ISSUE THREAD

**Issue by Sherhang** [apache/incubator-superset#10617]
According to  https://preset.io/blog/2020-07-02-hello-world/,
I tried to add a new chart plugin to superset0.37，just like what I do in superset0.36, but the code in superset/viz.py didn't work.
In terminal, the INFO is 
```
 INFO:superset.common.query_context:Cache key: e4fd71cd0177306d5ec282c473eb6b81
```
I hope it runs in superset.viz 
```
INFO:superset.viz:Cache key: 3ab3562d5bc67fef2760f0ddd1307fc5
```
What should I do?

**Comment by Sherhang** [comment]
solved. just add
 
index.ts
``` js
useLegacyApi: true,
```

**Comment by JunlinC** [comment]
🏷closed

**Comment by willbarrett** [comment]
Closing as the question has been answered.
