### ISSUE TITLE
Unix timestamp to yyyy-mm-dd

### ISSUE THREAD

**Issue by manojitgordon** [apache/incubator-superset#10614]
I have a column that has date in unix timestamp as int need to convert it into date time yyyy-mm-dd h:m:s how can it be done

**Comment by villebro** [comment]
@manojitgordon you can specify the date format of your string based column editing the datasource metadata by making it `is temporal` and specifying the timestamp format in the `Datetime format` property:
![image](https://user-images.githubusercontent.com/33317356/90358025-7c499980-e05d-11ea-8e2a-f0450e366deb.png)
