### ISSUE TITLE
How can I add my customize page in the menu?

### ISSUE THREAD

**Issue by dingsheng999888** [apache/incubator-superset#10618]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I have try to add a view in the menu behind Dashboard,but superset can not add my view with permission.

**Describe alternatives you've considered**

**Additional context**
        appbuilder.add_view(
            MyView,
            "MyView",
            label=__("MyView"),
            icon="fa-dashboard",
            category="MyView",
            category_icon="",
        )

**Comment by JunlinC** [comment]
🏷dashboard

**Comment by JunlinC** [comment]
🏷 navigation 🗑🏷 dashboard

**Comment by JunlinC** [comment]
🗑🏷 dashboard

**Comment by JunlinC** [comment]
🏷 navigation

**Comment by mistercrunch** [comment]
Check out `FLASK_APP_MUTATOR`
https://github.com/apache/incubator-superset/blob/master/superset/config.py#L657-L661

**Comment by dingsheng999888** [comment]
What can I chang to be?My config.py is the following:
FLASK_APP_MUTATOR = None
