### ISSUE TITLE
Set user lockout after X amount of failed logins (prevent brute force attack)

### ISSUE THREAD

**Issue by larsmars** [apache/incubator-superset#10620]
Set user lockout after X amount of failed logins to protect against bruteforce attacks.

- Feature toggle in config
- Configurable number of logins in config
- Admin can reset user (Is Active true/false)
- Email recovery link

**Comment by JunlinC** [comment]
🏷 login

**Comment by nytai** [comment]
This issue would make more sense in https://github.com/dpgaspar/Flask-AppBuilder as that's what's handling our login. You could also achieve this with a custom security manager, overriding the login method.

**Comment by nytai** [comment]
also, duplicate of https://github.com/apache/incubator-superset/issues/10560

**Comment by willbarrett** [comment]
Closing as duplicate.
