### ISSUE TITLE
user_attribute table and welcome_dashboard_id?

### ISSUE THREAD

**Issue by gtg472b** [apache/incubator-superset#10622]
I'm not sure whether this is a bug or request or what.

edit: I'm using master, last pulled a couple weeks ago.

I stumbled on code in superset/views/core.py referring to a welcome_dashboard_id, and poking around I found the user_attribute table and the welcome_dashboard_id column. I manually added a record with a user_id and welcome_dashboard_id and it correctly redirects the user to that dashboard upon login. So it looks like this feature works perfectly.

My question is, is there a better way to apply this feature than to manually log in to postgres and add these entries? I can't find anything in the List Users area.

Thanks!

**Comment by nytai** [comment]
@gtg472b you can set the welcome_dashboard_id in config https://github.com/preset-io/incubator-superset/blob/69046f08d44fece691798fcce0eea986e509e015/superset/config.py#L734 and every new user should have the same welcome dashboard. If you want to have different welcome dashboards for each user then setting it manually in the db is the only way.
