### ISSUE TITLE
In Dashboard filters -  The multiple line filters runs a cycle behind

### ISSUE THREAD

**Issue by eugeniamz** [apache/incubator-superset#10641]
if I add a multiline chart to a dashboard and apply time range the Multi Line chart gets updated a cycle behind. 
In the attached gif I show the 2 line charts and the multiline with the 2 charts and change the Time Range, you can see how the Simple Line charts gets updated but the multiline get updated with the previous selected setting. 

### Expected results

Mutliple line filter shows time ranged specified
### Actual results

It shows values of previous selection 
#### Screenshots

![2020-06-28_10-41-33 (2)](https://user-images.githubusercontent.com/58375897/90651661-4813db80-e20b-11ea-837f-f6eb1b771f2d.gif)

#### How to reproduce the bug

1- Create 2 line chart and 1 Muti-line chart and add to the dashboard
2- Create a filter using the same dataset
3- Apply Time ranges

**Comment by JunlinC** [comment]
🏷filter

**Comment by nytai** [comment]
This should be fixed in the latest master since https://github.com/apache/incubator-superset/pull/10966 was merged.
