### ISSUE TITLE
Maybe superset can modify the code of China according to the ISO-3166 which has changed on 2017

### ISSUE THREAD

**Issue by SKingNight** [apache/incubator-superset#10671]
According to the iso-3166-2 ,Codes for the representation of names in China:
https://www.iso.org/obp/ui/#iso:code:3166:CN

SuperSet version 0.37
Python 3.6.2

### Expected results
We should modify the 'ISO' in  china.geojson file (b3c8bf97ee7cc642bf10e0eecbe25c36.geojson) 

![image](https://user-images.githubusercontent.com/17975178/91150077-7eab9380-e6ee-11ea-8508-a9fc9a3b0285.png)

### Actual results
![image](https://user-images.githubusercontent.com/17975178/91150242-b6b2d680-e6ee-11ea-9bf6-2501b1d456e4.png)

**Comment by dpgaspar** [comment]
@SKingNight geojson files are not kept on this repo, plz open a new issue on superset-ui:

https://github.com/apache-superset/superset-ui/tree/master/plugins/legacy-plugin-chart-country-map/src/countries
