### ISSUE TITLE
Filter Box UI regression after upgrading to 0.37.0

### ISSUE THREAD

**Issue by unarmedcivilian** [apache/incubator-superset#10672]
I upgraded superset from 0.35.2 to 0.37.0. After the upgrade, I am noticing a regression in the UI for multi-select FilterBox. After selecting and removing a value, an additional Null item seems to get added to the list. 

### Expected results

The filter list should not contain invalid values

### Actual results

The filter list contains an additional `NULL` value

#### Screenshots

<img width="418" alt="Default" src="https://user-images.githubusercontent.com/8530446/91180857-cb4e9900-e705-11ea-8977-867c5b043480.png">
<img width="261" alt="Select Any Value" src="https://user-images.githubusercontent.com/8530446/91180872-d0abe380-e705-11ea-8ba4-2d61f9d50826.png">
<img width="271" alt="Deselect" src="https://user-images.githubusercontent.com/8530446/91180874-d1dd1080-e705-11ea-98aa-50020480d97c.png">
<img width="1052" alt="Select Null" src="https://user-images.githubusercontent.com/8530446/91180918-e02b2c80-e705-11ea-83e2-069e6cc170d6.png">

Selecting the invalid value sends requests with null as the selected value. 

`    "extra_filters": [
        {
            "col": "region",
            "op": "in",
            "val": [
                null
            ]
        }
    ] `

#### How to reproduce the bug

I am able to reproduce consistently on any dashboard with multi select filters. Please refer to screen shots based on the sample dashboards as an example.

### Environment

(please complete the following information):

- superset version: 0.37.0
- python version:  3.6.12
- node.js version: `node -v` 
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@unarmedcivilian I am unable to reproduce this on both master and 0.37.0. Can you record a video of how you were able to produce this error?

**Comment by unarmedcivilian** [comment]
@villebro I have uploaded a recording here. https://streamable.com/q8z08v 
I wondered if this could be because of something that I missed during the upgrade so I tested it out in a fresh local install and still ran into this issue. 
I'm using the containers in dockerhub created from this repo https://github.com/amancevice/docker-superset

**Comment by Leandro-GPIN** [comment]
I have the same problem.

I'm using supserset 0.37.0 with docker.

![filter_bug](https://user-images.githubusercontent.com/19553149/91222702-f3ce9700-e6f5-11ea-9bff-57cb8cddbdda.gif)

**Comment by villebro** [comment]
Thanks @unarmedcivilian and @Leandro-GPIN , I was able to reproduce the problem.
