### ISSUE TITLE
Use of Emoji in a Feddback based Superset Dashboard

### ISSUE THREAD

**Issue by NikhilBansal21** [apache/incubator-superset#10679]
**Is your feature request related to a problem? Please describe.**
I have to show ratings on my feedback analysis dashboard on the basis of emojis, initially i thought superset will automatically render ":)" or ":(" to emojis. But superset is not letting me even to go ahead with explore, it is showing me some alert box where it is asking me to refer to a github issue #5739

**Describe the solution you'd like**
I would like a way, in which i would pass on a DB Table column filled with emojis like ":)" , ":/" , ":(" , and superset dashboard would parse it to real emojis.
**Describe alternatives you've considered**
I want an intuitive dashboard, i am afraid there is no alternative for introducing emojis in my dashboard as of now, so i will have to use words like "Good" , "Bad" and etc

**Comment by willbarrett** [comment]
Hi @NikhilBansal21 you should be able to fill your table column with Unicode characters that represent emoji and display them in Superset - I just ran a test locally and this appears to work as expected. For the actual UTF8 characters for the various emoji, please refer to https://unicode.org/emoji/charts/full-emoji-list.html - I think for some data types, parsing ":/" into an emoji would be especially confusing - imagine a table full of URLs for instance.

**Comment by NikhilBansal21** [comment]
hi @willbarrett  thankyou for your reply, i would like to know in which format are saving utf codes in table? cz i tried a select where these codes were being saved as string and that is not working for me.

**Comment by willbarrett** [comment]
@NikhilBansal21 that depends on your underlying database. The database's encoding must support the 4-byte upper plane of Unicode characters. For MySQL, for instance, you'll need one of the `*_ext4` encodings. What database are you using to store the information?

**Comment by NikhilBansal21** [comment]
@willbarrett  I am using MYSQL
