### ISSUE TITLE
Question:  Are automated CSV exports possible?

### ISSUE THREAD

**Issue by dylanz** [apache/incubator-superset#10689]
We'd like to run a nightly job that exports dashboards (it looks like this would have to be slice by slice) to CSV files.  Is there a direct URL I can hit for a slice that allows me to grab a CSV file?  It looks like the button is behind a bunch of code that's not very easy to unravel.

Any insight welcome!  Thanks!

**Comment by bkyryliuk** [comment]
@dylanz there is a similar feature to what you are looking for - email / slack report for the chart, it can be delivered as a screenshot or just a raw data:
![image](https://user-images.githubusercontent.com/5727938/91463140-e3c2ce80-e83f-11ea-8450-56473bd79f65.png)

**Comment by dylanz** [comment]
@bkyryliuk oh wow... that's perfect!  Is this something on master or a WIP on a branch somewhere?

**Comment by bkyryliuk** [comment]
it is on master & also part of the 0.37

You can find some pointers on how to set it up here: https://github.com/apache/incubator-superset/issues/8201
