### ISSUE TITLE
Custom colors in LineChart

### ISSUE THREAD

**Issue by PragmaticDeveloper** [apache/incubator-superset#10685]
Is there a way to set your own colors for lines in LineChart?
Currently superset sets it's own random colors. 
What I would like to have is to set a fixed set of colors and order them by priority.
Thanks!

![image](https://user-images.githubusercontent.com/16608077/91284260-f4197180-e78b-11ea-9551-448b6bf3383d.png)

**Comment by JunlinC** [comment]
@villebro is it available in Echarts? 🙏

**Comment by JunlinC** [comment]
if you add the line chart to dashboard, you can customize the line colors by Edit Dashboard -> dropdown Edit Dashboard Properties -> click Advance edit JSON Metadata. please let me know if you have questions, closing issue for now~ 
<img width="695" alt="Screen Shot 2020-09-19 at 12 19 26 AM" src="https://user-images.githubusercontent.com/67837651/93661640-28402500-fa0e-11ea-9e45-dea8bdc0601c.png">
