### ISSUE TITLE
Superset connectivity with clickhouse

### ISSUE THREAD

**Issue by sanjaypocket52** [apache/incubator-superset#10700]
How to connect clickhouse with superset clickhouse://default@IP:9000/data_lake

It is gave me below error
ERROR: Could not load database driver: clickhouse

while i have installed pip install clickhouse-sqlalchemy

**Comment by sanjaypocket52** [comment]
Please, help me out

**Comment by suedschwede** [comment]
You must use clickhouse native
clickhouse+native://superset:XXXXXXXXXX@localhost/DEFAULT

**Comment by mgulaydin** [comment]
Hi @sanjaypocket52 First please be sure that you write down the correct SqlAlchemy URI (clickhouse://default@IP:9000/data_lake). 
Then can you try it with `pip install sqlalchemy-clickhouse` instead of clickhouse-sqlalchemy

**Comment by sanjaypocket52** [comment]
Thanks , Apache/Incubator-Superset, native is working fine.
