### ISSUE TITLE
How to translate some words in the  Explore page

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#10702]
### Expected results

When you click the language button, the text on the Explore page switches to the current language。
example："Query Mode" -->"查询方式"

### Actual results

There was no change。

#### Screenshots

![image](https://user-images.githubusercontent.com/1625023/91510229-05d75200-e90f-11ea-94dd-0e758d54af3a.png)

#### How to reproduce the bug

1. Login superset
2. Go to Explore page
3. Click the switch language button

### Environment

- superset version: 0.37
- python version: 3.7.7
- node.js version: 12.16.2
- npm version: 6.14.4

### Additional context
The Explore page·s word in file superset-frontend\node_modules\@superset-ui\plugin-chart-table\lib\controlPanel.js：
“label: (0, _translation.t)('Query Mode')”，“  [QueryMode.aggregate]: (0, _translation.t)('Aggregate'),
  [QueryMode.raw]: (0, _translation.t)('Raw Records')”，but fab babel-extract not generated to file messages.po，help pls！Thanks！

**Comment by ktmud** [comment]
Translations for charts should now reside with the plugins. Check this PR for details: https://github.com/apache-superset/superset-ui/pull/724

The particular piece in your screenshot should have already been translated for Chinese in the latest branch.

**Comment by toop** [comment]
Thanks！
