### ISSUE TITLE
UI Issue (button) on Datasource Editor screen within Explore view

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#10725]
When you are on Explore, and Click on Edit Datasource and get the Datasource Editor --> Metrics screen, the "add metric" button appears missing in the edit data source. After some investigation, it is actually not missing, but you need to scroll all the way to the right side, which isn't apparent. Experiences users report this as a bug, new users assume adding a metric is not supported feature.

### Expected results
As a user, I expect the button to be visible, so that I am able to add a new Metric. 

### Actual results
User perceives the button is missing and perceives this as a bug.

#### Screenshots
1st step: Button is not visible.
<img width="873" alt="superest-issue-1" src="https://user-images.githubusercontent.com/61221714/91626897-cd179700-e967-11ea-9cd0-3cb2cf2eb5f9.png">

2nd step: After scrolling right (which is not intuitive) button appears on the top right corner.
<img width="904" alt="superset-issue-add_item" src="https://user-images.githubusercontent.com/61221714/91626898-cee15a80-e967-11ea-8fce-381550b3e0aa.png">

#### How to reproduce the bug

1. Go to 'Explore view of any chart'
2. Click on 'Edit Datasource' tab 'Metrics'
3. If your have "SQL Expressions" column filled out, you will not see the button to add a metric.

### Environment
Chrome 

(please complete the following information):

- superset version: latest version

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
WiP~

**Comment by zuzana-vej** [comment]
It looks like https://github.com/apache/incubator-superset/pull/10983 will fix this. Will close this issue once validated.

**Comment by satyndragautam** [comment]
Right now, I have the same problem; I am running the query and the result is showing but when I try to explore the queried data, I can not see the "Explore" option. This is really very frustrating. Please help me because I am completing the assignment for my job.
