### ISSUE TITLE
Can I import the field description when I Import a table definition?

### ISSUE THREAD

**Issue by prs1022** [apache/incubator-superset#10736]
Now I import a table definition,I see the field is imported but description is none, Can I do this?

**Comment by zhaoyongjie** [comment]
@prs1022  you want retrieve Table comment from SQLlab siderbar?

**Comment by prs1022** [comment]
> @prs1022 you want retrieve Table comment from SQLlab siderbar?

Thank you for your reply. not from SQLlab but from Sources > Tables >Add a new Record ,while a table definition is added, the table information import from the Database, but I find the fields comment in the table  are not imported, bad solution，I will do it myself one by one.
