### ISSUE TITLE
Error loading charts for presto table with null column types

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#10743]
When loading chart based on a presto table that has null column type get an error [on this line](https://github.com/preset-io/incubator-superset/blob/master/superset/db_engine_specs/base.py#L892) because type_ is None. @villebro looks like this was added [here](https://github.com/apache/incubator-superset/pull/10658)

### Expected results

Chart should load

### Actual results

Error on chart
```
  File "/srv/superset-internal/incubator-superset/superset/db_engine_specs/base.py", line 901, in get_sqla_column_type
    match = regex.match(type_)
TypeError: expected string or bytes-like object
```

#### How to reproduce the bug

1. Create a datasource with columns that have null types
2. Try to create a chart with the datasource

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Thanks @michellethomas and sorry for the regression; I'll make a fix in a second 👍

**Comment by villebro** [comment]
@michellethomas I'd like to add some unit tests to minimize risk of future breakage, as currently the methods are quite light on unit tests and are fairly complex. Would you be able to provide me with a few complex nested data types that you've encountered in your env that I could use as a template for a few unit tests? Ping @john-bodley

**Comment by bkyryliuk** [comment]
Json type example:
```
SELECT CAST(CAST(ROW(123, 'abc', true) AS ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN)) AS JSON) -- JSON '[123,"abc",true]'
```

row type example:
```
SELECT
    CAST(ROW(1, 2.0) AS ROW(x BIGINT, y DOUBLE)) as simple_row
```

map type example:
```
select MAP(ARRAY['foo', 'bar'], ARRAY[1, 2]) as column
```

**Comment by villebro** [comment]
Thanks @bkyryliuk !
