### ISSUE TITLE
[sql-lab] implement no tabs state, or disallow closing last tab open

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1076]
![sql-lab-no-tabs-ux](https://cloud.githubusercontent.com/assets/130878/18333824/5abce204-7527-11e6-8db4-6c07b2d98d88.gif)

**Comment by milapbhojak** [comment]
Hi @ascott I will work on this issue. Can we make this like we open and close a tab on browser?

**Comment by ascott** [comment]
i think what we want to do here is disable the close tab option when there is only one tab left. what do you think @mistercrunch?

**Comment by milapbhojak** [comment]
So, Basically user can create tabs but they can't close the last tab and they can should able to rename tabs. Right?

**Comment by milapbhojak** [comment]
![image](https://cloud.githubusercontent.com/assets/5056619/18340406/5d53ed8c-75c2-11e6-992b-7e6fe1284615.png)

@ascott Something like this?
