### ISSUE TITLE
(docker) ERROR: apache-superset 0.999.0.dev0 has requirement pyarrow<0.18,>=0.17.0, but you'll have pyarrow 1.0.1 which is incompatible.

### ISSUE THREAD

**Issue by imavo** [apache/incubator-superset#10768]
docker-compose up throws error for pyarrow version incompatibility but continues to run 

(during Step 1/5 : FROM preset/superset:dev)
…
Installing collected packages: apispec, attrs, botocore, boto3, brotli, cffi, cryptography, flask-cors, humanize, openpyxl, pyarrow, sqlalchemy, tableschema, typing-extensions, apache-superset
E
**ERROR: apache-superset 0.999.0.dev0 has requirement pyarrow<0.18,>=0.17.0, but you'll have pyarrow 1.0.1 which is incompatible.**

### Expected results

No errors from `docker-compose up`
Also expected that if there is a build error, that the build should then STOP .

### Actual results

**ERROR: apache-superset 0.999.0.dev0 has requirement pyarrow<0.18,>=0.17.0, but you'll have pyarrow 1.0.1 which is incompatible.**
and the `docker-compose up` continues and waits for connections from host on http://localhost:8088.

#### How to reproduce the bug

Using ubuntu 18.04.5 LTS, with docker 19.03.12, and docker-compose 1.26.2.

Follow instructions on this page:   https://superset.incubator.apache.org/installation.html#getting-started

git clone https://github.com/apache/incubator-superset/

cd incubator-superset

docker-compose up

### Environment

- superset version: `superset version` (as per Dockerfile)
- python version: `python --version`  (3.6.9 on the host) otherwise as per Dockerfile.
- node.js version: `node -v` (as per the Dockerfile)
- npm version: `npm -v` (as per the Dockerfile)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset. 
(I assume that when I do the `git clone ...` that I get the latest version )

- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

 mention of pyarrow in #10765 but not identical symptom.

**Comment by craig-rueda** [comment]
Just merged a fix for this: #10766
