### ISSUE TITLE
REDACTED by @willbarrett

### ISSUE THREAD

**Issue by kelly-grizzle-sp** [apache/incubator-superset#10785]
REDACTED by @willbarrett

**Comment by dpgaspar** [comment]
Hi kelly-grizzle-sp thank you for reporting this. Will try to replicate and find a solution for this

**Comment by mistercrunch** [comment]
In the future, please report vulnerabilities privately using `private@superset.apache.org`, so that we can publish a patch prior to divulging the vulnerability.

**Comment by robdiciuccio** [comment]
Thanks for reporting. Please follow vulnerability reporting procedure in the link below and delete this issue until a fix is verified and included in an official release: https://www.apache.org/security/committers.html

We’ll update the docs with clearer information on reporting security issues.

**Comment by kelly-grizzle-sp** [comment]
Sorry about that.  I am new to collaborating with the superset team and did not know the appropriate channels to go through.

**Comment by willbarrett** [comment]
It's OK @kelly-grizzle-sp - we're glad we know, we're glad you told us, but it's better if these reports aren't in public.
