### ISSUE TITLE
dashboard list does not show dashboards created by others

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#10780]
userA (ADMIN) creates 4 dashboards and shares them
userB (GAMMA) logs in and goes to dashboard/list/ but the 4 dashboards that userA created are not shown,  api/v1/dashboard/ is empty too

**Comment by amitNielsen** [comment]
#10408 this SIP is addressing the issue

**Comment by willbarrett** [comment]
@tooptoop4 for Gamma to see the dashboard they must have access permissions to all of the referenced datasources and the dashboards must be published. Closing as without more information this is the current desired behavior.
