### ISSUE TITLE
k8s log show  error" tcp is not a valid port number"

### ISSUE THREAD

**Issue by scany1211** [apache/incubator-superset#10806]
hi experts,
    I download the superset source code and try to build the docker image with command "docker build -t xxx:xx .", then upload the image to docker registry and create the K8S pod. By the way,  I create the K8S pod with offical superset images, it has no problem. Only having  the problem when I use the image built by  myself.
   Do I need to modify anything in the source code ?

Thanks

**Comment by dpgaspar** [comment]
Hi @scany1211, can you share a bigger chunk of the log and more detailed info on how are you deploying to k8s. Also please fill the default template to report bug's or questions
