### ISSUE TITLE
Chinese translation is incomplete

### ISSUE THREAD

**Issue by hengaini2055** [apache/incubator-superset#10801]
I install incubator-superset 0.37 on window 10, but chinese tranlation is incomplelte. 

### Expected results

Top menu items such as Dashboards, Charts, Sources, should be translate to chinese.

### Actual results

Top menu items such as Dashboards, Charts, Sources, cannot be translate to chinese.

#### Screenshots

![image](https://user-images.githubusercontent.com/20587475/92291092-861e3880-ef49-11ea-9214-25b1f39987b4.png)

### Environment
- superset version: 0.37
- python version: 3.8.5
- node.js version: 12.18.0
- npm version: 6.14.5
- OS version: Windows 10 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment]
Superset relies on the community to add i18n translations. You are welcome to contribute to the translations of your language by following the [CONTRIBUTING](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#add-translations) guide.

**Comment by JunlinC** [comment]
@ hengaini2055 you can also join our [Superset slack ](https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU) #localization channel if you have questions on contributing to translation.

**Comment by prs1022** [comment]
I find a solution,compile the messages.po file into messages.mo ,it works

**Comment by hengaini2055** [comment]
@prs1022 I cannot replay your actions. Could you send the file to hengaini2055@qq.com, Thanks!

**Comment by prs1022** [comment]
@hengaini2055 ,the file directory is superset/translations/zh/LC_MESSAGES/message.po, you just compile the message.po to message.mo  in the same directory ,it works .The compile tool I use is Poedit.

**Comment by prs1022** [comment]
[messages.mo.zip](https://github.com/apache/incubator-superset/files/5192831/messages.mo.zip)

**Comment by hengaini2055** [comment]
@prs1022 Thank you! It does work.
