### ISSUE TITLE
Drill down based on one type of chart  REf: issues #6774

### ISSUE THREAD

**Issue by bigbprp** [apache/incubator-superset#10809]
I am really interested in either importing a chart plug-in or any other way to have an option to drill down based on selection from one chart to other.. ref. [https://github.com/apache/incubator-superset/issues/6774 ](https://github.com/apache/incubator-superset/issues/6774 )

Having a drill down capability  or dynamically changing charts based on **Multiple chart drilldown**
showcased at [https://github.com/apache/incubator-superset/issues/6774 ] makes a huge difference for me... 

Regards, 

Bhavin Panchal

**Comment by bigbprp** [comment]
Hi Again, 

I am very much aware about Filter box capabilities.. but that doesn't serve the purpose because it doesn't give us capabilities like power bi to Tableau where one can click on any charts in a dashboard & filter based the selection. 

Looking forward for your inputs... 

Regards, 

Bhavin Panchal

**Comment by amitNielsen** [comment]
Drill-down or cross-filter as we call it is cannot be supported in the current filter mechanism logic.

There is a task force that works on re-implementing dashboard filter to support this use-case and few more .
You can Followup  #9935

**Comment by JunlinC** [comment]
this feature has been added to Superset roadmap. you can see status update by joining Superset slack channel 
https://apache-superset.slack.com/archives/C0188FT3V2S  closing the issue for now.

**Comment by bigbprp** [comment]
Thank you so much for considering this feature.
