### ISSUE TITLE
 Line Chart Freeze

### ISSUE THREAD

**Issue by WenQiangW** [apache/incubator-superset#10827]
The superset line chart loads a large amount of data and the loading is complete, causing the browser page to freeze

#### Screenshots

![image](https://user-images.githubusercontent.com/19701559/92711950-93915380-f38b-11ea-9640-e90fbed6a5e4.png)

#### How to reproduce the bug
1. use line chart
2. load big data
3. The mouse arrow moves on the line chart
4. you can see very freeze
### Environment

(please complete the following information):

- superset version: `0.36` 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [✓] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✓] I have reproduced the issue with at least the latest released version of superset.
- [✓] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
The solution here is to sample the data being loaded into the line chart. Loading a large amount of data into any graph rendered in a browser will result in performance issues.

This is solvable by the user.

**Comment by leeoniya** [comment]
@WenQiangW 

here are some benchmarks of line chart libs:
