### ISSUE TITLE
No field class for LowCardinality(String)

### ISSUE THREAD

**Issue by MrSsunlight** [apache/incubator-superset#10826]
database: clickhouse 
The field type of LowCardinality(String) under clickhouse is not supported

**Comment by zhaoyongjie** [comment]
This is Clickhouse dialect issue, please raise this issue to clickhouse python dialect community. 
https://github.com/mymarilyn/clickhouse-driver

**Comment by JunlinC** [comment]
thanks @zhaoyongjie  @willbarrett please close this issue 🙏
