### ISSUE TITLE
"Add Item" button in Datasource Editor too big

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#10838]
"Add Item" button in Datasource Editor seems too big and ran out of the last column in the Metrics tab.

### Expected results

Button doesn't overflow.

#### Screenshots

![image](https://user-images.githubusercontent.com/335541/92867589-a4ef5580-f3b5-11ea-90fc-65481d631fbb.png)

#### How to reproduce the bug

1. Go to edit any datasource in the Explore page.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
@lilykuang hey Lily, this relates to your [dataset editor improvement](https://github.com/apache/incubator-superset/pull/10444) properly? could you please take a look? 🙏

**Comment by nytai** [comment]
this was likely introduced in https://github.com/apache/incubator-superset/commit/a3e2e65121fadc8ca507c490eb5a3b26d8153041#diff-43b9aaf2f0ad9833ac0362f7beb20235R749

**Comment by JunlinC** [comment]
resolved
