### ISSUE TITLE
Query Search, empty page with 403 error

### ISSUE THREAD

**Issue by eugene-belarus** [apache/incubator-superset#10830]
When user without can_access_all_queries permission go to **Query Search** and filter by user (click on his username) then 403 error appears

### Expected results

There's no error.

### Actual results

There's a empty page with 403 status response.

#### Code

```
@has_access
    @expose("/search_queries")
    @event_logger.log_this
    def search_queries(self) -> FlaskResponse:
        query = db.session.query(Query)
        if security_manager.can_access_all_queries():
            search_user_id = request.args.get("user_id")
        elif (
            request.args.get("user_id") is not None
            and request.args.get("user_id") != g.user.get_user_id()
        ):
            return Response(status=403, mimetype="application/json")
```
I think `request.args.get("user_id")` returns string type and `g.user.get_user_id()` returns integer type thus appears 403 error.

#### How to reproduce the bug

1. Go to **Query Search**
2. Click on **username** without _can_access_all_queries_ permission
3. See a empty page with 403 error

**Comment by nytai** [comment]
@eugene-belarus you were correct -- easy fix

**Comment by dpgaspar** [comment]
Fixed on master
