### ISSUE TITLE
Timer in SQL Lab and Explore doesn't work

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#10849]
The timer in SQL Lab doesn't work. When you run the query 1st time, it shows some number (unsure if accurate). When you run a query 2nd time the value on the timer doesn't change. 

### Expected results
The timer should reset every time user hits the "RUN" button, and start counting again from 0. 

### Actual results

Timer is stuck.

#### Screenshots

Step 1: Running 1st query: (timer has some result, which looks inacurate, the query took longer than 0.67 sec
![sqllab-timer-bug](https://user-images.githubusercontent.com/61221714/92983326-96597a80-f457-11ea-95a3-f4a4dcbe00ea.png)
Timer detail:
<img width="85" alt="Screen Shot 2020-09-11 at 5 55 40 PM" src="https://user-images.githubusercontent.com/61221714/92983409-09fb8780-f458-11ea-899f-73358f6d46a8.png">

Step 2: Change to different SQL Lab tab and run 2nd query: 
![step1](https://user-images.githubusercontent.com/61221714/92983344-b9842a00-f457-11ea-8fe2-525f39ac4a4f.png)
Timer detail:
<img width="93" alt="Screen Shot 2020-09-11 at 5 56 02 PM" src="https://user-images.githubusercontent.com/61221714/92983418-1b449400-f458-11ea-9a42-1331316752b8.png">

See query is running - timer value doesn't change
![step2](https://user-images.githubusercontent.com/61221714/92983348-c0ab3800-f457-11ea-9a43-ac5b759e56be.png)
Timer detail:
<img width="87" alt="Screen Shot 2020-09-11 at 5 56 08 PM" src="https://user-images.githubusercontent.com/61221714/92983422-20a1de80-f458-11ea-8d39-5a2f48f53257.png">

Query finished and returned result - timer is still displaying same value as before hitting RUN button:
![steap3](https://user-images.githubusercontent.com/61221714/92983368-ce60bd80-f457-11ea-97d6-d68d3d0faed4.png)
Timer detail:
<img width="77" alt="Screen Shot 2020-09-11 at 5 56 13 PM" src="https://user-images.githubusercontent.com/61221714/92983424-2992b000-f458-11ea-8995-5fb731cd3074.png">

#### How to reproduce the bug

1. Go to SQL Lab
2. Click on RUN query
3. See the timer and whether it changes
4. Run query again, see the timer and whether it changes

### Environment

- superset version: `latest`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
thanks for reporting the timer issue.

**Comment by john-bodley** [comment]
Note I believe the timer is also broken in explorer as well.

**Comment by zuzana-vej** [comment]
Yes, correct, it happens on Explore as well. Here is an example:
1. Clicked to refresh the chart (which was previous cached). While query is running, it displayed this timer: (even right after click it says 5s) 
<img width="327" alt="Screen Shot 2020-09-15 at 12 22 38 PM" src="https://user-images.githubusercontent.com/61221714/93255118-4d067500-f74e-11ea-87bc-44b37cd1ba14.png">
2. Once query finished, timer looks like this (query took longer than 5 seconds):
<img width="363" alt="Screen Shot 2020-09-15 at 12 22 48 PM" src="https://user-images.githubusercontent.com/61221714/93255161-57c10a00-f74e-11ea-8a40-9ef3144316de.png">

**Comment by JunlinC** [comment]
@tanmaylaud @rusackas

**Comment by tanmaylaud** [comment]
@JunlinC @rusackas I haven't been able to reproduce this issue locally. The master branch seems to be working fine. 
Here's a video of me running the queries: https://www.youtube.com/watch?v=RTr0lXGjrO0

**Comment by JunlinC** [comment]
@Zuzana Vejrazkova <zuzana.vejrazkova@airbnb.com> it works fine for me as
well. also, I believe that the timer is showing 5 millisecond instead of 5
secs? could you provide a .gif or video? Thanks!

Thank you Tanmay for looking into this!

**Comment by zuzana-vej** [comment]
@tanmaylaud can you confirm which version you see this is working as expected? (the latest superset release or master ( and master as of which day))? Everyone from our team sees the same issue. Is it possible that it was fixed recently (within last few days)? I shared couple videos with Junlin directly, she can share the folder with you.

**Comment by graceguo-supercat** [comment]
@tanmaylaud  please run a longer query in SQL lab. in your example, query is too short that you can't tell if Timer display a correct running time. 
Run a query like `select * from wb_health_population  limit = 500`.
This is what i experienced:
![LwMnIK6BxF](https://user-images.githubusercontent.com/27990562/93833697-379db900-fc2e-11ea-8868-80fcd73f3e19.gif)

**Comment by zuzana-vej** [comment]
We believe the issue is with this PR https://github.com/apache/incubator-superset/commit/a6fa02aaec1ec5cba1fa010cf6910f65a965eaf7 (reverting it locally fixes the timer issue locally). I can slack you link to the video recording.

**Comment by mistercrunch** [comment]
revert?

**Comment by JunlinC** [comment]
thanks @ktmud for fixing!
