### ISSUE TITLE
[Bug] Unable to login by clicking on SignIn or Google Icon.

### ISSUE THREAD

**Issue by csurfer** [apache/incubator-superset#10845]
After Superset upgrade to `0.37.0` I am not able to log into the product by clicking on SignIn button or Google icon.

### Expected results

Log into SuperSet.

### Actual results

Stays on the Login page without any changes.

#### How to reproduce the bug

1. Go to Login page of super set.
2. Click on SignIn button or Google icon to login via Google authentication alone and you will see you are not logged in.
3. Click Google Icon and SignIn button in quick succession, and you will be shown the google account choice window to log in with and you can continue now to log in correctly. (Rage clicking showed this to be working :P)

### Environment

- superset version: `0.37.0`
- python version: `2.7.6`
- node.js version: `v13.12.0`
- npm version: `6.14.8`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I checked network tab for calls being made (Both Incognito and Otherwise) and following are the details.
1. Upon clicking Login button : We see a bunch of static resources being loaded and login call being made which returns with 200.
2. Upon clicking Google icon : We see no network calls being made.
3. Upon clicking SignIn icon : We see no network calls being made.
3. Upon clicking Register icon : We see no network calls being made.

I also checked the developer console and I see no error logs.

**Comment by zhaoyongjie** [comment]
hi, @csurfer.
1. why you use google login to Superset? 
2. If you don’t mind, can you share config.py? Have you configured an additional login manager?
