### ISSUE TITLE
superset clickhouse load Nullable(String) columns as UNKOWN type

### ISSUE THREAD

**Issue by reesezxf** [apache/incubator-superset#10856]
I use tablemodelview/add a clickhouse table, its DDL:
```
CREATE TABLE business.tCompany_dim_all
(

    `cID` String,

    `chsynDate` Date,

    `cCreateTime` Nullable(DateTime),

    `cUpdateTime` DateTime,

    `cName` Nullable(String)
)
ENGINE = Distributed('cluster_test',
 'business',
 'tTestTable',
 cityHash64(cID))
```
but in tablecolumns, cCreateTime ,cName type is UNKOWN

**Comment by zhaoyongjie** [comment]
Hi, @reesezxf , Clickhouse has some specify column type
1. please use ansi-SQL column type
2. override 'db_column_types' attribute in superset.db_engine_specs.ClickHouseEngineSpec
