### ISSUE TITLE
Babel can not extract words from superset-ui packages

### ISSUE THREAD

**Issue by grace-shi** [apache/incubator-superset#10858]
### Expected results
when extracting new strings for translation, words inside superset-ui packages should be extracted as well.

### Actual results
Babel only extracts words from superset-frontend/src and backend code. ignored superset-ui plugins inside node_modules

#### Screenshots
![Screen Shot 2020-09-14 at 10 06 19 PM](https://user-images.githubusercontent.com/11971026/93096096-8bf8e400-f6d6-11ea-88c3-df54deae16c2.png)

#### How to reproduce the bug

1. Go to project root directory 
2. Run flask fab babel-extract --target superset/translations --output superset/translations/messages.pot --config superset/translations/babel.cfg -k _ -k __ -k t -k tn -k tct
3. See logs

### Environment

- superset version: `0.37`
- python version: `3.7.0`
- node.js version: `v12.18.2`
- npm version: `6.14.5`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Many chart plugins use `t` function to translate strings, but these strings can not extracted for translation.

**Comment by zhaoyongjie** [comment]
Hi, @grace-shi. there are a workaround to fetch translation from any directory that specify a custome `babel.cfg` file. The `babel.cfg` contains superset-ui-plugs directory.

**Comment by JunlinC** [comment]
closing ... issued has been resolved by  https://github.com/apache/incubator-superset/pull/10902.
