### ISSUE TITLE
Error code links no longer work

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#10852]
It looks like these weren't migrated from the old docs site.

### Expected results
Links like this to work: https://superset.apache.org/issue_code_reference.html#issue-1002

### Actual results
They don't work

#### How to reproduce the bug
Generate a database error, e.g. through a non existent column. See the broken link in the error message

### Environment

(please complete the following information):

- superset version: `master'

to: @pkdotson @mistercrunch

**Comment by serenajiang** [comment]
While we're at it, it'd also be great to fix these:

* https://github.com/apache/incubator-superset/blob/4eeee4c2eb49a46d1c98d93f4c93bbffee5d8164/superset-frontend/src/addSlice/AddSliceContainer.tsx#L125
* https://github.com/apache/incubator-superset/blob/4eeee4c2eb49a46d1c98d93f4c93bbffee5d8164/superset-frontend/src/SqlLab/components/TemplateParamsEditor.jsx#L86
