### ISSUE TITLE
[SIP-53]  Proposal to create a Superset public roadmap

### ISSUE THREAD

**Issue by benceorlai** [apache/incubator-superset#10894]
### Motivation
I got involved in the Superset project in January 2020 as a Product Manager. New to the project, I was trying to understand what work was in flight, or what other projects were coming up for development. As a PM, it was natural for me to look for a product roadmap. A Product Roadmap is the "prototype of the product vision". It is a document that gives interested parties visibility into the future of the project; what is the direction the product will take and what are the features that are on the boards.

At Apache Superset, the list of contributors, committers, PMC members, and new adopters has grown steadily over the recent months and years. New joiners are often asking whether Feature X or Z is in the cards or will be happening anytime soon. At the moment, for those questions to be answered, one has to dig thru PRs, SIPs, or ask around the community and it is very difficult to grasp the direction or Superset on a high level.

### Proposed Change
We propose to establish a publicly available product roadmap for Superset. This document will be created in and maintained by, the community as part of the open-source project. The roadmap will be a "registry" of features and projects that members intend to work on across the community.

We suggest that the roadmap be hosted as a separate repository under apache/superset-roadmap (or equivalent). This setup follows the best practices of other public roadmaps (examples [here](https://github.com/checkly/public-roadmap/projects/1) or [here](https://github.com/mjmlio/mjml/projects/1)), including [Github's own public roadmap](https://github.com/github/roadmap).

We also suggest that committers and PMC members have write access to that repository and have the capacity to adjust and alter the roadmap in a way that reflects the commitments that they are ready to make in the community. Committers and PMC members are also welcome to act as a proxy to other contributors to alter the roadmap in ways that reflect those actor's commitments. Ideally, items on the roadmap provide a minimum amount of clarity around scope, timeline, and ownership. In this sense, the community roadmap becomes a summation of different engagements made by different parties. It also creates more opportunities for community members to plan together, collaborate, and for new contributors to find opportunities to get involved.

Requirements around adding roadmap items:
* Outcome-centric definition of the scope
* A loose timeline
* A clear owner, or group of owners, represented as GitHub assignees to the GitHub issue, one whom should be a committer to the project and can act as a proxy for other contributors
* A commitment to update the status of the roadmap item and respond to inquiries around it

Note that contributing to the roadmap is NOT a prerequisite to contributing to the project. It's still perfectly fine for someone to contribute a new feature that never touched the roadmap.

### New or Changed Public Interfaces
Use a Github Project and an associated Board as the interface for the Roadmap. This project and board will be available for everyone in the community or interested in the project. The Superset website will have a direct link to this board.

![screenshot_roadmap](https://user-images.githubusercontent.com/8263072/93261303-5fd17780-f757-11ea-88d4-0e50aa83d856.jpg)
(A Project Board used as a roadmap. Source: /github/roadmap/)

### Rejected Alternatives
Other document formats were considered (md file, Google Sheet, Trello Board) but Github Projects and Boards are native parts of the project repository, provide an intuitive interface, and require no further setup or cost to use.

**Comment by mistercrunch** [comment]
FYI folks at Preset are driving this and using this approach as a vector to publish and socialize our roadmap for Superset. We believe that this will create clarity in the community and more opportunities to collaborate with other individuals and organizations. 

We'd love to hear from others are interested in publishing roadmap items that they have for Superset.

**Comment by benceorlai** [comment]
I have created a project and board to capture the projects we are working on.
https://github.com/apache-superset/superset-roadmap
