### ISSUE TITLE
style: missing padding in VizTypeControl on "New Chart" page

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#10917]
Missing some padding in the viz type selector on "Add new chart" page:

### Actual results

![image](https://user-images.githubusercontent.com/335541/93382265-bf428c80-f816-11ea-8c3d-fcaacd829300.png)

### Expected results

The viz type control should look the same as on Explore page:

![image](https://user-images.githubusercontent.com/335541/93382336-d8e3d400-f816-11ea-83e5-0c56dd4ff9f0.png)

#### Screenshots

See above

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@@kgabryje 🙏

**Comment by junlincc** [comment]
not sure which pr fixed it, but it's fixed. closing the issue

**Comment by ktmud** [comment]
This issue is back
