### ISSUE TITLE
Is Superset Support join from multiple tables with SQL ?

### ISSUE THREAD

**Issue by zsellami** [apache/incubator-superset#10910]
Hello,
the documentation of superset indicate that is not possible to use join in Explore or Visualization UI https://superset.incubator.apache.org/docs/frequently-asked-questions#can-i-join--query-multiple-tables-at-one-time

Currently, is it possible when create SQL query in the SQL Lab of superset to use join function ?
if no, there is a planning to implement this functionalty ? roadmap ?
is the developpment of this functionality is complicated ? any estimation ?

Best Regards,
Zied Sellami

**Comment by zhaoyongjie** [comment]
"Currently, is it possible when create SQL query in the SQL Lab of superset to use join function ?"
Yes, It is possible create a view in SQLLab and then apply this view as a datasouce to Explore.

**Comment by zsellami** [comment]
Thank you for the quick answer

**Comment by mistercrunch** [comment]
https://superset.apache.org/docs/frequently-asked-questions#can-i-join--query-multiple-tables-at-one-time
