### ISSUE TITLE
Line chart exception with Druid data (regression from 0.36 to 0.37.1)

### ISSUE THREAD

**Issue by elukey** [apache/incubator-superset#10928]
Hi everybody,

after upgrading from Superset 0.36 to 0.37.1 I noticed that a dashboard containing line charts, using a Druid backend, do not visualize correctly anymore.

### Expected results

The line charts displaying data.

### Actual results

I see the usual red bar indicating an error on each chart with the word `'filter'`. In the Superset logs I can see:

```
Sep 17 07:57:14 superset[5963]: Traceback (most recent call last):
Sep 17 07:57:14 superset[5963]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 472, in get_df_payload
Sep 17 07:57:14 superset[5963]:     df = self.get_df(query_obj)
Sep 17 07:57:14 superset[5963]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 250, in get_df
Sep 17 07:57:14 superset[5963]:     self.results = self.datasource.query(query_obj)
Sep 17 07:57:14 superset[5963]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/connectors/druid/models.py", line 1440, in que
Sep 17 07:57:14 superset[5963]:     query_str = self.get_query_str(client=client, query_obj=query_obj, phase=2)
Sep 17 07:57:14 superset[5963]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/connectors/druid/models.py", line 1017, in get
Sep 17 07:57:14 superset[5963]:     return self.run_query(client=client, phase=phase, **query_obj)
Sep 17 07:57:14 superset[5963]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/connectors/druid/models.py", line 1399, in run
Sep 17 07:57:14 superset[5963]:     df, pre_qry["dimensions"], qry["filter"]
Sep 17 07:57:14 superset[5963]: KeyError: 'filter'
```
I have inspected `qry` and indeed there is no `filter`.  I am using pydruid 0.6.1 after https://github.com/apache/incubator-superset/pull/10046.

#### Screenshots

![Screen Shot 2020-09-17 at 10 15 10 AM](https://user-images.githubusercontent.com/1536240/93439502-efe5fd00-f8ce-11ea-8b76-53938f2aab28.png)

### Environment

(please complete the following information):

- superset version: 0.37.1
- python version: 3.7
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@elukey are you able to hop on Slack? I can help debug this problem if you wish (seems like a quick fix). In the meantime, have you considered migrating to Druid SQL? The legacy connector isn't actively maintained anymore, so we recommend moving to the SQL connector if possible.

**Comment by elukey** [comment]
> @elukey are you able to hop on Slack? I can help debug this problem if you wish (seems like a quick fix). In the meantime, have you considered migrating to Druid SQL? The legacy connector isn't actively maintained anymore, so we recommend moving to the SQL connector if possible.

Sure! We are migrating all the charts to the SQL connector but it might take more time, if this is too problematic to maintain I can try to migrate the dashboard that is currently broken and then close :)
