### ISSUE TITLE
Security page is unavailable

### ISSUE THREAD

**Issue by dylanz** [apache/incubator-superset#10947]
```
09:26 $ wget https://superset.incubator.apache.org/security.html
--2020-09-17 15:36:45--  https://superset.incubator.apache.org/security.html
Resolving superset.incubator.apache.org (superset.incubator.apache.org)... 95.216.24.32, 95.216.26.30, 40.79.78.1
Connecting to superset.incubator.apache.org (superset.incubator.apache.org)|95.216.24.32|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-17 15:36:46 ERROR 404: Not Found.
```

I found this page but it's just a disclaimer and doesn't touch on any of the security aspects (permissions, roles, etc) of the framework like `/security.html` used to.

**Comment by nytai** [comment]
@dylanz the superset docs website is currently being implemented with a more modern UI so some areas are still incomplete. You can find a previous version of that page here https://apache-superset.readthedocs.io/en/0.36/security.html

**Comment by mzangie** [comment]
Please unsubscribe me from all of these many many threads I guess they are called. I get like 20emails or more a day seriously and I don't even have any idea what any of them mean. Please if you can see if. Me out of all this ok. Thanks
