### ISSUE TITLE
Button break lines when saving an existing query in SQL Lab

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#10950]
Button break lines when saving existing query in SQL Lab

### Expected results

Buttons don't break lines

### Actual results

what actually happens.
![image](https://user-images.githubusercontent.com/335541/93558472-5b14eb00-f932-11ea-97f7-4eb399964570.png)

#### How to reproduce the bug

1. Click on "Save" on SQL Lab
2. Save the query
3. Click on "Save" again

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
@riahk 🙏

**Comment by riahk** [comment]
https://github.com/apache/incubator-superset/pull/11164 Fixed by this!

**Comment by junlincc** [comment]
thank you, Moriah!
