### ISSUE TITLE
'Query search', returns broken links for 'Open in SQL editor'

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#10954]
Login as admin

Navigate to superset/sqllab#search

Search by another user

Click 'Open in SQL editor' link on far right

Nothing happens on the UI but Chrome Dev Tools shows a 404 response from kv/store/

![search](https://user-images.githubusercontent.com/33283496/93610812-73821580-f9c5-11ea-9542-51c7eb471256.png)
env is v0.36

**Comment by nytai** [comment]
@tooptoop4 this issue was fixed ~3 months ago by https://github.com/apache/incubator-superset/pull/10128 please upgrade to the latest version or superset.

**Comment by nytai** [comment]
Feel free to reopen if you're able to repro on master
