### ISSUE TITLE
Is there any other way to accelerate dashboard?

### ISSUE THREAD

**Issue by appleyuchi** [apache/incubator-superset#10969]
I deploy some charts about san_francisco in the following link
http://49.235.108.13:5000/superset/dashboard/3/
I have used redis in config.py
but it takes about 17 seconds to show all contents.
Is there any other way to accelerate it?
Thanks

**Comment by appleyuchi** [comment]
my whole config file is :
https://paste.ubuntu.com/p/wMCdHYxpJb/
Thanks for your help

**Comment by nytai** [comment]
@appleyuchi there is a lot at play here. The fastest way to make a dashboard load faster is to use a faster database. Which database are you using?

**Comment by appleyuchi** [comment]
> @appleyuchi there is a lot at play here. The fastest way to make a dashboard load faster is to use a faster database. Which database are you using? How fast do your queries run on that db vs superset? Answering this should help narrow down whether the issue is with superset or with your underlying database.

Thanks for your replies
I use mysql now
sorry for my late reply.

**Comment by zuzana-vej** [comment]
@appleyuchi the 3 major ways to optimize dashboard (excluding possibility with some issue with configurations which I wouldn't know about):
1. Engine optimization - can you use faster engine (as @nytai  pointed out above)
2. Query optimization
-- how complex is the SQL of your queries for the dashboard charts? Are you doing multiple joins, calculations, etc. did you limit how much data you query, optimizing the SQL query should have impact on the load time of your dashboard.
3. Dashboard complexity 
-- how complex is your dashboard meaning how many total charts do you have on the dashboard? These an initial load time to process metadata of the charts. We have seen in some cases for dashboards with large number of charts, and large amount of metadata (filter scopes, color settings etc) that just this time can go up to 7 seconds. By large number of charts I mean scale of 200 charts on a dashboard. 

There is `logs` table which you can go through to understand little more on where the time is coming from. It should have details on slice_id so you can see which charts are slowest, and the json column I believe should have lot more details.

**Comment by mistercrunch** [comment]
Also:
- summarize the data further - maybe you have a table with billions of rows, but you have an opportunity to create an aggregated table that can power many charts in your dashboard
- hard to tell if that's part of the problem for you, but sometimes you're just returning too many rows and putting a burden and the network and user browser. Make sure you don't have lots of charts hitting the 10k row limits or populating millions of cells in in data tables for instance. The general solution there is to group or sort/limit. It's very rare that showing hundreds of thousands of datapoint is actually intelligible
