### ISSUE TITLE
Set up timeout session in Superset application for UI users.

### ISSUE THREAD

**Issue by kvdevopse** [apache/incubator-superset#10980]
Set up timeout session for users in Superset Application
 
Hi, We set up the superset application and we are trying to achieve the application UI timeout session for the users. In config.py file we setup "PERMANENT_SESSION_LIFETIME = 60" for one minute but session timeout for users is not working. The logout for users is not happening automatically and also if we refresh the superset application UI page, it is logging in directly without prompting login page.

These are the timeout session values we passed in config file.
SUPERSET_WEBSERVER_TIMEOUT = 60
**PERMANENT_SESSION_LIFETIME = 60**

SQLLAB_TIMEOUT = 30

Please help us to fix the timeout session.

**Comment by nytai** [comment]
@kvdevopse did you set `SESSION_PERMANENT = True`? It seems that is needed to make `PERMANENT_SESSION_LIFETIME` work

**Comment by dpgaspar** [comment]
@kvdevopse just set:

```
from datetime import timedelta

...
 PERMANENT_SESSION_LIFETIME = timedelta(seconds=10)
```

**Comment by kvdevopse** [comment]
> @kvdevopse did you set `SESSION_PERMANENT = True`? It seems that is needed to make `PERMANENT_SESSION_LIFETIME` work

Hi, Where I have to set 'SESSION_PERMANENT = True`. Is it in the same configuration file? I don't find "SESSION_PERMANENT" parameter in configuration file. is it okay to edit the manually?

**Comment by tooptoop4** [comment]
crispy
