### ISSUE TITLE
[BUG] Top Tabs can't switch back

### ISSUE THREAD

**Issue by hushaoqing** [apache/incubator-superset#11032]
### Environment
- superset version:  build from latest code: 8e9b0b3f1100120a14134c0ca0c5dd4dd4a9e8bb
- python version:  `3.6.5`
- node.js version: `v14.0.0`
- npm version: `6.14.4`

#### Screenshots
![Sep-24-2020 10-54-02](https://user-images.githubusercontent.com/10289162/94095663-c55aed80-fe54-11ea-8e24-f6c5c3cc8869.gif)

**Comment by JunlinC** [comment]
thanks for reporting, we will look into it~

**Comment by JunlinC** [comment]
@kgabryje is this related to #10868?

**Comment by etr2460** [comment]
This should be fixed in master now
