### ISSUE TITLE
PR #10970 breaks the filter box control

### ISSUE THREAD

**Issue by codepic** [apache/incubator-superset#11047]
When you pull  #10970 and run `docker-compose up --build` and go to Filter Box visualization in the control panel, the filter configuration popup will not open.

### Expected results

Filter configuration popup to open.

### Actual results

Filter configuration popup does not open.

#### Screenshots

![image](https://user-images.githubusercontent.com/3933589/94166681-e8ed5a80-fe8b-11ea-99e5-abdc5a63882b.png)

#### How to reproduce the bug

1. Clone incubator-superset
2. `git reset --hard e4e78b66fa82acbe8e5bc425d697ff11b4a0cc3f`
3. `docker-compose up --build`
4. Wait for the `superset_init` to complete
5. Open http://localhost:8088
6. Go to data > datasets > birth_names
7. Change the visualization type to filter box
8. Under Filters configuration, click (+) icon to add a filter
9. Try to edit the filter
10. See browser console producing 

### Environment

(please complete the following information):

- superset version: `e4e78b66fa82acbe8e5bc425d697ff11b4a0cc3f`
- python version: `Python 2.7.17`
- node.js version: `v12.18.3`
- npm version: `6.14.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The filter box plugin works with the previous commit to master 41dfcd4834cb0db76d8aeffb28f55b90d79dccd6

**Comment by JunlinC** [comment]
thanks for reporting. @rusackas

**Comment by rusackas** [comment]
I've said it before, and I'll say it again. I _really_ appreciate your thorough bug reports with the repro steps.

**Comment by mistercrunch** [comment]
+1 , thanks @codepic !

**Comment by codepic** [comment]
@rusackas thanks for your kind words. I guess it goes with myself receiving so many shrug reports in my life and wasting so much time trying to figure out how to replicate them. Once you've been through enough reports like "it doesn't work", it becomes nearly impossible for one to write them.

But for sure I'm also being selfish. I want Superset to work (for me) so my best bet is to make sure you guys see what I see and of course be able to know when it's fixed. Which is semi-impossible if you can't replicate it in the first place. I also know that getting a timely response from you is much more likely when the repro steps are there and a dev don't need to start with figuring out how to replicate the bug. Since I managed to break it, I might aswell save everyone's time by telling how. And boy, can I break things!

Looking forward to writing more reports and having received your positive feedback I'm motivated to keep up the quality of them.

And thanks! Good job with Superset so far!
