### ISSUE TITLE
Big Number doesn't support aggregate queries on date fields

### ISSUE THREAD

**Issue by woodbine** [apache/incubator-superset#11042]
Using the big number visualisation using the MAX() aggregate query returns 'null'.

When using the AGG queries in Superset for Big Number I expect it to be able to return the max() date or the min() date.

I'd expect to either have limited input, e.g. limiting the field to only using numeric fields, or to be able to return the max date from that visualisation. 

I just get null when I use aggregates.

#### How to reproduce the bug

1. Create new visualisation.
2. Select 'Big Number'
3. Make sure time range covers your latest data
4. Select "AGG MAX" in the metric dropdown
5. Select a date field for the target column in the metric dropdown
6. Run query

### Environment

(please complete the following information):

- superset version: `0.36.0rc2 `
- python version: `python --v3.2`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
fixed
