### ISSUE TITLE
Looking for  suggestions on the right database 

### ISSUE THREAD

**Issue by abhishekkumaresan** [apache/incubator-superset#11048]
HI, 
     I am using superset for the dashboard, My data resides in Mysql, There are about 15 Million records for 2 years and growing at a rate of 70,000 (approx.) records per day,  I have a 5 tabbed dashboard with 41 Charts, I have aggregated the data which I  could aggregate but for other charts, The data is in its normal form and we have to give the users the ability to change time grail. Can anyone give me suggestions on the right database to use?

The time taken to display the hourly average for a single day is fine (5-6 seconds per chart after Indexing and partitioning in Mysql) (which is the default), But the time taken  for the 
"Last Week" is 52 seconds
"Last Month" is 1 minute and 14 Seconds
"Last Quater" filter is about 3 minutes and 40 seconds 

Will databases like Druid work for this case or should I try to aggregate the data more.

Note:- I am not sure if this is the right place to ask this question.

Thank you.

**Comment by JunlinC** [comment]
@srinify 🙏

**Comment by nytai** [comment]
@abhishekkumaresan Yes switching databases should speed things up. MySQL is an excellent choice for a metadata db, but being an OLTP db it's inherently at a disadvantage to something like Druid. Druid should help speed things up. You can also find a comparison of various OLAP databases here https://en.wikipedia.org/wiki/Comparison_of_OLAP_servers

**Comment by srinify** [comment]
Hi Abhishek, there's a few approaches you can take.

1. I would read more about optimizing MySQL first. I'm definitely not the expert here, but making sure you have appropriate indexes (https://www.tutorialspoint.com/mysql/mysql-indexes.htm), shards (https://medium.com/pinterest-engineering/sharding-pinterest-how-we-scaled-our-mysql-fleet-3f341e96ca6f), and dedicated compute resources for your MySQL server is the first thing I'd try. Using EXPLAIN will help you figure out where the bottlenecks are (https://dev.mysql.com/doc/refman/5.6/en/using-explain.html). There's people running MySQL at scale with petabytes of data!

2. Try introducing an ETL layer so Superset is only querying intermediate data / aggregates. You can stick with MySQL and use a tool like DBT to introduce some intermediate tables (https://www.getdbt.com/).

3. Druid is definitely a good choice if your data has lots of aggregations and you need it to be real-time: https://netflixtechblog.com/how-netflix-uses-druid-for-real-time-insights-to-ensure-a-high-quality-experience-19e1e8568d06 If real-time isn't important, then Druid *could* be a little overkill (remember, each database makes their own set of tradeoffs).

**Comment by abhishekkumaresan** [comment]
@srinify @nytai @junlincc  Thank you for the suggestions,
@srinify  As you said I have done indexing and I am also experimenting partitioning, I will also look into sharding and DBT, Thank you.

**Comment by mistercrunch** [comment]
The database market is so large, fast evolving and diverse. People's need are also diverse and evolving. There are much better resources out there to figure out which database engine and setup you may want/need.
