### ISSUE TITLE
CSRF token is missing Error

### ISSUE THREAD

**Issue by trsree** [apache/incubator-superset#11065]
While integrating Superset with our webpage , we receive the following error:

Bad Request
The CSRF session token is missing.

<img width="1661" alt="Screen Shot 2020-09-25 at 12 23 55 PM" src="https://user-images.githubusercontent.com/5104605/94291786-0a9d1f00-ff2a-11ea-8974-3bae6cd04703.png">

**Comment by nytai** [comment]
You can disable CSRF protection by setting the config `WTF_CSRF_ENABLED = False`. This will disable all CSRF protection which has security implications.

**Comment by nytai** [comment]
Alternatively you can disable CSRF protection on certain routes with this config https://github.com/preset-io/incubator-superset/blob/master/superset/config.py#L173

**Comment by amitNielsen** [comment]
If you upgraded lately to 0.37 this might have happen to you
Try to clean the cookie in Dev tools under application tab in chrome browser
