### ISSUE TITLE
Recently Viewed tab sorting

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#11085]
### Expected results

Dashboard is sorted when clicked.

### Actual results

Dashboard doesn't sorted

#### Screenshots

![bug1](https://user-images.githubusercontent.com/28984703/94401959-f3666780-019d-11eb-8432-773ed5b06b2a.PNG)

#### How to reproduce the bug

1. Go to welcome page
2. Click on 'Recently Viewed'
3. Click on 'Name'

### Environment

(please complete the following information):

- superset version: `master`
- python version: `based on Dockerfile`
- node.js version: `based on Dockerfile`
- npm version: `based on Dockerfile`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks for reporting the bug, Mohamad. we are currently working on a new home screen and will deprecate this view soon. meanwhile, this is a good first issue if anyone in the community would like to contribute.

**Comment by junlincc** [comment]
@syazwan0913 Superset is no longer supporting this view. please check out our latest master for new list views and landing page.

**Comment by syazwan0913** [comment]
@junlincc Yeah I checkout it out already. Thanks
