### ISSUE TITLE
unable to import dashbaords: manage button greyed out

### ISSUE THREAD

**Issue by grimbeorn74** [apache/incubator-superset#11087]
I cannot import my dashboard. I'm logged in as admin, it's a brand new deployed superset environment.
version pulled:
commit 41dfcd4834cb0db76d8aeffb28f55b90d79dccd6 (HEAD -> master)
Author: Kasia Kucharczyk <2536609+kkucharc@users.noreply.github.com>
Date:   Mon Sep 21 21:26:17 2020 +0200

### Actual results

what actually happens.

#### Screenshots

![image](https://user-images.githubusercontent.com/61703561/94416779-8cd25100-017f-11eb-9ecc-08969850c866.png)

#### How to reproduce the bug

1. Go to 'settings'
2. try to Click on 'manage' but it's greyed

### Environment

(please complete the following information):

- superset version: ### 0.37.1 (2020/09/05 17:28 +00:00)
- python version: python3.6 
- node.js version: v8.10.0

**Comment by dpgaspar** [comment]
The manage greyed out is correct, have you run `superset init`?

**Comment by grimbeorn74** [comment]
no, thought it was embedded in the docker-compose, I will try

**Comment by grimbeorn74** [comment]
![image](https://user-images.githubusercontent.com/61703561/94417094-f0f51500-017f-11eb-93f1-14f81020946c.png)

done but nothing seems changed

**Comment by dpgaspar** [comment]
it is your right! can you checkout the latest master please?

**Comment by grimbeorn74** [comment]
you mean pull latest version 37.2?

**Comment by dpgaspar** [comment]
Not really since your using a specific commit, checkout `39cce712afdc00af73daa2243cbae08a14b7dc0e`

**Comment by grimbeorn74** [comment]
ok thx I will check this version

**Comment by grimbeorn74** [comment]
I used the hyperlink http://localhost:8088/superset/import_dashboards and it worked without changing the superset version

**Comment by dpgaspar** [comment]
that should work, but after checking out the latest master and rerunning `docker-compose` did the "Import Dashboards" menu showed up?

**Comment by codepic** [comment]
@dpgaspar I can verify 39cce712afdc00af73daa2243cbae08a14b7dc0e does indeed show the menu item.

We have also tested the import functionality with @grimbeorn74 using 39cce712afdc00af73daa2243cbae08a14b7dc0e and that works also.

**Comment by dpgaspar** [comment]
ok, then, closing the issue.
