### ISSUE TITLE
SQL Lab doesn't display query history

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11096]
SQL Lab query history is broken. This bug is as a regression which was introduced some time between 1-2 weeks before 9/23.

### Expected results

After user runs a query in SQL Lab, it should show in the Query History tab.

### Actual results

The Query history is blank.

#### Screenshots

<img width="1286" alt="Screen Shot 2020-09-28 at 7 35 14 PM" src="https://user-images.githubusercontent.com/61221714/94506430-3cc8ae00-01c2-11eb-930b-27ec2a0061fe.png">

#### How to reproduce the bug

1. Go to SQL lab
2. Run a simple query
3. Click on Query history
4. See there are no records

### Environment
- superset version: latest master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@dpgaspar, Daniel, could you please take a quick look, thanks! 🙏

**Comment by nytai** [comment]
Looks like this was introduced in https://github.com/apache/incubator-superset/pull/10981

**Comment by graceguo-supercat** [comment]
For async queries, we should be able to see old queries' results by clicking VIEW RESULTS link. this feature is not working right now:
![EXx44bCHu0](https://user-images.githubusercontent.com/27990562/94768030-1726da80-0363-11eb-89db-680992938c48.gif)

**Comment by nytai** [comment]
@graceguo-supercat that looks like a separate issue, would you mind filing another ticket?

**Comment by mistercrunch** [comment]
Popover + emotions break! We need to migrate all Popovers to antd quickly. I fixed the `SpatialControl` yesterday and I bet this is the same root cause...

**Comment by graceguo-supercat** [comment]
@nytai After the revert (or maybe have other fixes at the same time?), `VIEW RESULTS` link in query history works good now:
![rJgWdqoKBT](https://user-images.githubusercontent.com/27990562/95361098-25a05500-0881-11eb-9043-92eb1907ea27.gif)
