### ISSUE TITLE
echart timeseries group by error

### ISSUE THREAD

**Issue by grimbeorn74** [apache/incubator-superset#11092]
Adding a field in group-by control menu makes the chart show an error " Referenced columns not available in dataFrame"

### Expected results

show multiple rows based on group-by values

### Actual results

showing error

#### Screenshots

![image](https://user-images.githubusercontent.com/61703561/94457105-6d095000-01b4-11eb-8f7b-189ee5ddb9ee.png)

#### How to reproduce the bug

1. Go to 'chart'
2. create a new chart based on flights table
3. choose echarts timeseries
4. time column: ds, metrics:sum(taxi_out) (or whatever metrics field), group-by: day_of_week (or whatever field)

### Environment

- superset version: 0.37.2 39cce712afdc00af73daa2243cbae08a14b7dc0e (HEAD -> master, origin/master, origin/HEAD)
- python version: python3.6
- node.js version: v8.10.0

**Comment by junlincc** [comment]
@villebro 🙏

**Comment by villebro** [comment]
Oh, I didn't notice this! This was fixed by #11103 (this feature is not available on 0.37.2)
