### ISSUE TITLE
New dashboard Tab is created when click on "Left" arrow key on keyboard

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#11097]
### Expected results

The cursor will move to the left

### Actual results

New Tab is created

#### Screenshots

![Capture](https://user-images.githubusercontent.com/28984703/94507029-67a61700-0241-11eb-8071-39317ffd6749.PNG)

#### How to reproduce the bug

1. Go to 'Dashboard Edit mode'
2. Click on 'Tab A'
3. Click on Left arrow key on keyboard
4. New Tab created

### Environment

(please complete the following information):

- superset version: `master`
- python version: `based on Dockerfile`
- node.js version: `based on Dockerfile`
- npm version: `based on Dockerfile`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Thanks! It only creates a new tab when you are already at the first tab(Tab A). I don't think this is an issue but feel free to provide a solution if you would like.

**Comment by syazwan0913** [comment]
Yeah I just noticed it happened on first tab(Tab A). Also I noticed when on second tab(Tab B) and cursor is after letter "b", when I clicked on Left arrow on keyboard, the cursor moved to first tab(Tab A). The cursor should move before letter "b"

![tab](https://user-images.githubusercontent.com/28984703/94511075-e9e70900-024a-11eb-8227-a87b42d46de2.gif)
