### ISSUE TITLE
style: DatasourceControl dropdown z-index issue

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11094]
When datasource name is long or browser window is small, DatasourceControl dropdown menu cut in half on narrow screens.

### Expected results

The dropdown menu should be able to overflow from the side bar.

This should be fixable by adding z-index or rendering the dropdown in portal.

Another option is to right-align the dropdown menu.

### Actual results

![image](https://user-images.githubusercontent.com/335541/94491190-9ae29a80-019c-11eb-999c-fc35389b7c70.png)

#### How to reproduce the bug

1. Go to Explore page
2. Select a datasource with very long name
3. Narrow your browser window
4. Click on the "..." dropdown.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ x I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Not sure if this is a regression, but should be somewhat related to #10971

cc @mistercrunch

**Comment by junlincc** [comment]
@kgabryje 🙏

**Comment by kgabryje** [comment]
I think it's going to solve itself when I refactor react-bootstrap dropdowns to Antd

**Comment by zuzana-vej** [comment]
Similar to https://github.com/apache/incubator-superset/issues/11377 (these are the only two cosmetic / overflow issues I am aware of).

cc @junlincc

**Comment by kgabryje** [comment]
@ktmud @junlincc https://github.com/apache/incubator-superset/pull/11395 should fix the issue.

**Comment by mistercrunch** [comment]
Merged, and confirmed this is fixed in master:
<img width="588" alt="Screen Shot 2020-10-24 at 11 26 05 AM" src="https://user-images.githubusercontent.com/487433/97089313-b9954f00-15eb-11eb-94e0-01df65232a60.png">
