### ISSUE TITLE
Dashboards visible by groups or roles

### ISSUE THREAD

**Issue by rimolive** [apache/incubator-superset#11117]
**Is your feature request related to a problem? Please describe.**
I currently manage a shared Superset environment where many teams create their own dashboards. Problem is that when you list the dashboards, everyone can see others dashboards too in a single list.

**Describe the solution you'd like**
There should be a way to group the dashboards by team

**Describe alternatives you've considered**
Maybe change dashboards listing to show as a tree structure or either add tags to the dashboards so people can have easy ways to list only their team dashboards.

**Additional context**
Worth also consider RBAC access to the dashboards to avoid other users change dashboards from other teams too

**Comment by amitNielsen** [comment]
you might find this #10408 interesting

**Comment by junlincc** [comment]
for tagging system, please check out A tagging system for dashboards, charts and queries [#5524](https://github.com/apache/incubator-superset/pull/5524), it was backend solution only, but we are considering to finish it. @rimolive want to collaborate?

**Comment by rimolive** [comment]
@amitNielsen @junlincc Thank you so much for the responses. I'll collaborate on the open PRs.

Closing the issue.
