### ISSUE TITLE
When using Big Number with Trendline Big Number doesn't give output as per metric

### ISSUE THREAD

**Issue by xxsacxx** [apache/incubator-superset#11116]
Big Number with Trendline gives only the last available day's count irrespective of whatever metrics you chose.
My Data looks like : 
![screenshot](https://i.imgur.com/fz3ij2x.png)

### Expected results

Now if I am doing sum(signup_done) I expect the Big Number should show the sum of signup_done done column

### Actual results

Instead, I get the  last available day's count which is the last point in the trendline

#### Screenshots

![screenshot1](https://i.imgur.com/xeq6qHE.png)

### Environment

(please complete the following information):

- superset version: `superset version` --- 0.35.1
- python version: `python --version` ---- 3.6.9

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Big Number with Trendline chart is a visualization that is used to place focus on a key performance indicator with associated percentile changes. I would recommend you to choose Big Number chart, which is used to place focus on a more general key performance indicator, like Sum or Average. closing this issue for now.
