### ISSUE TITLE
upgrade to 0.37.2: where is Sources menu?

### ISSUE THREAD

**Issue by zufolo441** [apache/incubator-superset#11128]
Hi, I tried to upgrade - from git - an installation of Superset: i saw that menus have been changed. Where is Sources menu?
thanks!

**Comment by dpgaspar** [comment]
Sorry I'm confused, have you upgraded from 0.37.2 or to 0.37.2. On 0.37.2 they should be on the same place, can you send a screenshot?

**Comment by villebro** [comment]
Some of the menus have changed recently. Have you run `superset init` after your upgrade? Please note, that it's not a good idea to run different versions of Superset against the same metadata store, as it will very likely not work properly, and can end up corrupting your metadata.

**Comment by zufolo441** [comment]
Thansk, villebro. I'll try. I thought that superset init should be called only for first installation. 
I don't run multiple versions: we have two installations with two differents databases, installed both from git. Sometimes I upgrade them.

If you like, please see: https://tomcat.istitutodegliinnocenti.it/nubia/
and https://superset.istitutodegliinnocenti.it/superset/dashboard/covid/

**Comment by zufolo441** [comment]
Thanks! using "superset init" caused the resurrection of Data menu! Now, I've a further problem after login: it stucks on loading image....
![Screenshot_20201006_120816](https://user-images.githubusercontent.com/45826835/95188540-d993d880-07cc-11eb-862c-2aa37631a9eb.png)
![Screenshot_20201006_120753](https://user-images.githubusercontent.com/45826835/95188542-dac50580-07cc-11eb-9ee7-cedfcad57bf5.png)

**Comment by dpgaspar** [comment]
@zufolo441 seems like your using public roles, so notice that your not authenticated, on this view you are a Gamma user. The infinite superset logo is normally a sign that you need to build your frontend assets

**Comment by zufolo441** [comment]
Thanks to everyone, I solved. Last question: why can't I create new iframe graphics?

**Comment by zufolo441** [comment]
for example, please visit: https://superset.istitutodegliinnocenti.it/superset/dashboard/covid/

**Comment by mistercrunch** [comment]
Oh, nice! Can we add your organization to the list here!? https://github.com/apache/incubator-superset/blob/master/INTHEWILD.md

**Comment by zufolo441** [comment]
> Oh, nice! Can we add your organization to the list here!? https://github.com/apache/incubator-superset/blob/master/INTHEWILD.md

Sure!
