### ISSUE TITLE
Installation via Docker does not works

### ISSUE THREAD

**Issue by edgars** [apache/incubator-superset#11165]
### Expected results

Trying to install the latest docker-compose.yml it complains that the port 5432 is already used by another container. 

```
[Warning] One or more build-args [NPM_BUILD_CMD] were not consumed
Successfully built 424d1de91eea
Successfully tagged incubator-superset_superset-tests-worker:latest
WARNING: Image for service superset-tests-worker was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating superset_cache ... 
Creating superset_db    ... 
Creating superset_db    ... error

ERROR: for superset_db  Cannot start service db: driver failed programming external connectivity on endpoint superset_dCreating superset_cache ... done
.1:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint superset_db (68e29817629c9ee178eb06052d7b57398a548f8738cb88f8bb03aaa512d279bf): Error starting userland proxy: listen tcp 127.0.0.1:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
root@vmi452115:~/incubator-superset# 
```
I followed exactly what is on the docs

Any help please? 

OS- Ubuntu 18.04 and Macos - Same error on both.

**Comment by nytai** [comment]
Looks like another container is running on that port. You can check which docker processes are running with `docker ps`. You should stop all other docker processes and then try `docker-compose up --build`

**Comment by edgars** [comment]
@nytai I had no other container instance, the docker environment was fresh installed from zero.

**Comment by nytai** [comment]
Do you have another process running on port `5432`?

**Comment by mistercrunch** [comment]
Conflicting Postgres?

**Comment by edgars** [comment]
No other process running on that port, the server is a bran new instance

**Comment by mistercrunch** [comment]
`sudo reboot`

**Comment by edgars** [comment]
@mistercrunch I will try, but as I saw, it was totally clean.

**Comment by mistercrunch** [comment]
"5432: bind: address already in use"

**Comment by oggers** [comment]
In my case I had the same error yesterday. The problem was a postgresql instance running on the same host.

I ended up changing the port on docker-compose.yml file and it worked:
`  db:`
`    env_file: docker/.env`
`    image: postgres:10`
`     container_name: superset_db`
`    restart: unless-stopped`
`    ports:`
`      - "127.0.0.1:5433:5432"`
`    volumes:`
`      - db_home:/var/lib/postgresql/data`
