### ISSUE TITLE
bug: SQLLab dropdown CTAS/CVAS button group is broken

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11177]
<img width="323" alt="Screen Shot 2020-10-06 at 2 18 33 PM" src="https://user-images.githubusercontent.com/487433/95262173-7ca21d80-07e0-11eb-8e21-d2e635e6b7ae.png">
Expecting to see a dropdown button with 2 options right of the input field in the screenshot

**Comment by bkyryliuk** [comment]
it would be great to prioritize this issue, it's blocking our internal superset update :(

**Comment by junlincc** [comment]
added cosmetic-issue label to move it to the Polidea project board.

**Comment by mistercrunch** [comment]
@kgabryje can you please look into this?

**Comment by kgabryje** [comment]
I think it's related to antd global.less stylesheet, which is going to be removed soon by one of my open PRs. I'll take a look and try to confirm it.

**Comment by zhaoyongjie** [comment]
@kgabryje @mistercrunch  input-group-buttons font-size is zero . I will fix it soon
