### ISSUE TITLE
cosmetic: pagination label is out-of-scroll

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11178]
<img width="360" alt="Screen Shot 2020-10-06 at 2 32 57 PM" src="https://user-images.githubusercontent.com/487433/95262429-f76b3880-07e0-11eb-83cf-0ddc00c6e6ad.png">

This should be a full page app, but the pagination label falls off of the page viewport, creating a tiny amount of scroll. 

Also not that using an extra row in the FPA to just have the `4 out of N` seems like a waste, I'd love to not use more than one row to fit the pagination selector AND label.

**Comment by Steejay** [comment]
We’re removing the scroll window and just letting the 2 rows render however they do and scroll the whole page if it overflows.

**Comment by nytai** [comment]
closing this as it no longer makes sense with the current implementation
