### ISSUE TITLE
SQL Lab show more tabs dropdown overflows

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#11188]
## Screenshot

![image](https://user-images.githubusercontent.com/7409244/95360472-46b47600-0880-11eb-9287-1b75cabe1083.png)

## Description
looks like a z-index issue with the dropdown menu

**Comment by kgabryje** [comment]
@etr2460 This dropdown menu should be scrollable. Adding a permanent scrollbar is problematic, as Antd Tabs doesn't expose API for customising the dropdown. I could override a proper CSS class in `antd/index.less` stylesheet... but I think that would make @rusackas quite unhappy. What I can do here is try to fix the styles of dropdown menu items - apparently the styling from the Tabs (like `display: flex`) don't apply to them.

**Comment by kgabryje** [comment]
Here's the fix for unstyled dropdown items: https://github.com/apache/incubator-superset/pull/11287. As I said, I can also add a permanent scrollbar in `antd/index.less`, but first I'd like to hear @rusackas's opinion.

**Comment by junlincc** [comment]
@kgabryje thanks for fixing!! closing the issue
