### ISSUE TITLE
The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

### ISSUE THREAD

**Issue by codepic** [apache/incubator-superset#11183]
`docker-compose up` results in `node_superset` reporting compilation errors.

### Expected results

No errors

### Actual results

```log
superset_node            | <s> [webpack.Progress] 98% after emitting
superset_node            | <s> [webpack.Progress] 98% after emitting SizeLimitsPlugin
superset_node            | Type checking in progress...
superset_node            | <s> [webpack.Progress] 100% 
superset_node            | 
superset_node            |    7712 modules
superset_node            | ERROR in /app/superset-frontend/src/components/FilterableTable/FilterableTable.tsx(388,19):
superset_node            | TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
superset_node            | ERROR in /app/superset-frontend/src/components/FilterableTable/FilterableTable.tsx(420,17):
superset_node            | TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
```

#### How to reproduce the bug

1. Clone `incubator-superset` 39cce712afdc00af73daa2243cbae08a14b7dc0e
2. `docker-compose up --build`
3. Observe error

### Environment

(please complete the following information):

- superset version: 39cce712afdc00af73daa2243cbae08a14b7dc0e
- python version: `Python 2.7.17`
- node.js version: `v12.18.4`
- npm version: `6.14.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The below diff should fix it.

```diff
index 77b27108e..1a11f575d 100644
--- a/superset-frontend/src/components/FilterableTable/FilterableTable.tsx
+++ b/superset-frontend/src/components/FilterableTable/FilterableTable.tsx
@@ -385,7 +385,7 @@ export default class FilterableTable extends PureComponent<
             ...style,
             top:
               typeof style.top === 'number'
-                ? style.top - GRID_POSITION_ADJUSTMENT
+                ? (style.top as number) - GRID_POSITION_ADJUSTMENT
                 : style.top,
           }}
           className={`${className} grid-cell grid-header-cell`}
@@ -417,7 +417,7 @@ export default class FilterableTable extends PureComponent<
           ...style,
           top:
             typeof style.top === 'number'
-              ? style.top - GRID_POSITION_ADJUSTMENT
+              ? (style.top as number) - GRID_POSITION_ADJUSTMENT
               : style.top,
         }}
         className={`grid-cell ${this.rowClassName({ index: rowIndex })}`}

```

**Comment by shutaG** [comment]
Hello! This problem how do you solve？I also met. Has been compiled not successful

**Comment by codepic** [comment]
@shutaG the solution is in the diff in my original message. Cast the style.top as number.

**Comment by shutaG** [comment]
> @shutaG the solution is in the diff in my original message. Cast the style.top as number.

thank you !  i get it .
