### ISSUE TITLE
Cannot find the Row-Level Security menu

### ISSUE THREAD

**Issue by oggers** [apache/incubator-superset#11184]
Yesterday I downloaded and installed Superset following the docker method. When I searched for the row-level security filter entry in the menus I couldn't find it. Searching on the Internet I found this screenshot from the row-level security proposal where I see several menu entries not present in my installation:

![imagen](https://user-images.githubusercontent.com/1022039/95309438-70bf6580-088b-11eb-9f2a-b011fd1bd034.png)

Screenshots from my installation:

![imagen](https://user-images.githubusercontent.com/1022039/95309747-d4499300-088b-11eb-88fd-614f5a21f160.png)

Is there any way to enable these features? What am I doing wrong?

**Comment by oggers** [comment]
Made some progress.

I found the config ENABLE_ROW_LEVEL_SECURITY in config.py. So, I created incubator-superset/superset/superset_config.py (the log has reported that the file was found and loaded) setting this variable to True, but without success, nothing different happens on the interface.

**Comment by dpgaspar** [comment]
Have you executed `superset init` after the config change?

**Comment by oggers** [comment]
I suppose it was executed when I executed `docker-compose up` after creating the superset_config.py file

I can see a stopped container called superset_init (the last execution time was when I executed docker-compose up), and its log says that all went ok, so I suppose that it's ok.

**Comment by oggers** [comment]
I have deleted all containers and reinstalled everything. Result, the same, no Row-Level Security menu entry.

Can anyone confirm that using the default docker installation method the security menu appears complete?

**Comment by dpgaspar** [comment]
If you're using `docker-compose` add the config key here: https://github.com/apache/incubator-superset/blob/master/docker/pythonpath_dev/superset_config.py

**Comment by oggers** [comment]
@dpgaspar Thank you very much, it worked.

I have included my local changes in docker/pythonpath_dev/superset_config._docker.py.
