### ISSUE TITLE
cosmetic: SQLLab - jumpy vertical split when clicking on "Query History" tab

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11191]
## Screenshot
![captured](https://user-images.githubusercontent.com/487433/95369234-0529c800-088c-11eb-8160-a57534d06efa.gif)

## Description
shouldn't jump around when clicking on tabs!

**Comment by mistercrunch** [comment]
@kgabryje

**Comment by kgabryje** [comment]
@mistercrunch I think we can close this issue?

**Comment by rusackas** [comment]
@junlincc let's confirm it's behind us :)

**Comment by junlincc** [comment]
tested on 10/20,  all good! closing
