### ISSUE TITLE
Source tab on Edit Dataset modal inconsistent with Datasource on Chart Explore view

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11190]
~1week ago a change was merged redesigning the modal "Edit Datasource" on Chart Explore. It is not clear what should be the behavior of the section _Source_ on _Edit Dataset_:

![Screen Shot 2020-10-07 at 10 18 07 AM](https://user-images.githubusercontent.com/61221714/95365033-6cdd1480-0886-11eb-8cad-04d34e931aab.png)

### Context

**Use case 1: Changing datasource using Change Datasource**
This change is local - only for the chart user has open. This works as expected.
![Screen Shot 2020-10-07 at 10 18 58 AM](https://user-images.githubusercontent.com/61221714/95365152-9ac25900-0886-11eb-9d5c-44b468cc2c34.png)

**Use case 2: Changing datasource using Edit Datasource --> Source** 
Previously the Source tab was last on the right side, merged with settings. 
It's unclear what is changing the source on this modal supposed to do. 
Typically, any changes to "Edit Datasource" are applied globally to ALL CHARTS using the datasource. User is warned about this. 
What is changing the source on the 1st tab actually supposed to do?
![Screen Shot 2020-10-07 at 10 21 37 AM](https://user-images.githubusercontent.com/61221714/95366011-b5490200-0887-11eb-9aaa-61884a4468fc.png)

### Current behavior:
Currently, if you change the name of table (Datasource) nothing happens.

![Screen Shot 2020-10-07 at 10 12 43 AM](https://user-images.githubusercontent.com/61221714/95365956-a1050500-0887-11eb-8b6d-277b8446865b.png)

After saving the change nothing happens to the chart, and the changes are not saved when opening the modal again.

### Expected behavior:
Unclear. If this is another way to change datasource LOCALLY for the one chart, (1) the warning shouldn't be displayed and (2) the change should apply to the current chart. This change should not apply globally to all charts.

#### How to reproduce the bug

1. Go to Chart Explore
2. Click on Edit Datasource
3. On 1st tab (Source) change the name of table
4. Save
4. Nothing happens

### Environment

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
@junlincc

**Comment by mistercrunch** [comment]
I think publishing a glossary would help clarifying all this. We started writing one internally for publishing, but we have a bit more work to do.

To clarify, a chart points to a dataset, and a dataset points to either a) a physical table or a view OR b) is a virtual dataset and is defined as a SQL query (essentially a Superset-managed view). A dataset also defines a set of settings, metrics (as aggregate expressions) and calculated dimensions.

`Change Dataset` (note that the labels have been updated in `master` to move away from the term datasource in favor of dataset.) allows you to point the chart to another Dataset entity. 

`Edit Dataset` allows you to point the Dataset to another table or view, or enrich/configure the dataset.

Having a clear glossary and tooltips might help here.

**Comment by zuzana-vej** [comment]
`Edit Dataset` allows you to point the Dataset to another table or view, or enrich/configure the dataset. 

1. Is the use case to Edit dataset if a table is for example renamed? `my_daset` --> `my_dataset_new` 

2. Impact (is change locally to chart of globally)
2.a: If you make this change under Change Dataset, only the current chart is impacted (current behavior, as expected)
2.b: If you make this change under Edit Dataset, it should get applied to all charts? Or what is the expected behavior here?

Btw. Currently the Edit dataset dropdown on Edit Dataset modal doesn't do anything. Point 2.b is what's not clear.

**Comment by zuzana-vej** [comment]
So basically editing dataset on the edit dataset modal (screenshot in my previous message) will be applied locally to the chart. It's just another way to do it (in case user is already on the modal). I think that makes sense. I question whether it's necessary to have this here, since user can do it via Change Datasource. 

And if we keep this functionality on this modal, the warning message whey you are saving the change needs to change. Currently it says that "all changes will be applied to all charts" which is true if you edit Metrics, Columns or Calculated columns. But message should be different if you just edit datasource which is only applied to this chart (warning user that this chart might break if their new datasource doesn't include same columns, but not warning user about other charts)

![Screen Shot 2020-10-14 at 9 36 48 AM](https://user-images.githubusercontent.com/61221714/96019207-10877100-0e01-11eb-85db-a76216ca6fd2.png)
![Screen Shot 2020-10-14 at 9 36 56 AM](https://user-images.githubusercontent.com/61221714/96019212-13826180-0e01-11eb-91c7-f9c542a02285.png)

**Comment by junlincc** [comment]
I agree that this functionality is a bit redundant and if we keep it modal,
the warning message should be either louder and more specific. Zuzana,
let's explore a better solution after getting the bug fix. Thanks for
suggesting!

**Comment by zuzana-vej** [comment]
Closing this as we had some discussions and this bug is resolved. There is a new different bug - raising new issue for tracking.
