### ISSUE TITLE
Refresh button change to Search button

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#11200]
**Is your feature request related to a problem? Please describe.**
When clicked the `Filter List`, no Search button appered. So need to press Enter on keyboard

**Describe the solution you'd like**
Search button appeared when click on `Filter List`

**Describe alternatives you've considered**

**Additional context**
![1cTt0R3pnT](https://user-images.githubusercontent.com/28984703/95441971-61284580-098d-11eb-8236-076909123fda.gif)

**Comment by junlincc** [comment]
@syazwan0913 thanks for suggesting, the current filter search is a bit confusing. we are in the process of improving overall content discoverability in Superset and will likely have new search experience soon. feel free to reach out in Slack for status update. closing this issue for now.
