### ISSUE TITLE
BIGINT not filterable when using Presto as datasource

### ISSUE THREAD

**Issue by stevensuting** [apache/incubator-superset#11219]
I am required to cast bigint to int to make it filterable.  
`cast("my_bigint_column" AS INTEGER)`

The logs show no error and SQL labs says:
`The query returned no data`

Superset Version:
0.37.1

**Comment by villebro** [comment]
@stevensuting Can you state which version you're on?

**Comment by stevensuting** [comment]
Updated original post.

**Comment by villebro** [comment]
Can you also elaborate more on the context in which this isn't working. With filterable, do you mean you can't create a FilterBox? You also mention SQL Lab; does this mean that a simple `SELECT cols FROM tbl` doesn't work if your dataset has a `bigint` column, but works if you cast it to `integer`? A few screenshots would also be very helpful.

**Comment by stevensuting** [comment]
**In Explore Chart**
`select  cast("clbprogid" AS INTEGER) AS  "clbprogid" from table`
<img width="541" alt="Screenshot 2020-10-13 at 3 02 27 PM" src="https://user-images.githubusercontent.com/8875448/95843580-7de5c400-0d65-11eb-873b-5e0eb3b6f9b5.png">

`select clbprogid  from table`
<img width="913" alt="Screenshot 2020-10-13 at 3 01 47 PM" src="https://user-images.githubusercontent.com/8875448/95843638-8b9b4980-0d65-11eb-962b-fe068354cb97.png">


**In SQL LAB**
With CAST
<img width="488" alt="Screenshot 2020-10-13 at 3 10 36 PM" src="https://user-images.githubusercontent.com/8875448/95844355-75da5400-0d66-11eb-9de5-2c96280324ea.png">

Without CAST
<img width="365" alt="Screenshot 2020-10-13 at 3 11 53 PM" src="https://user-images.githubusercontent.com/8875448/95844388-7f63bc00-0d66-11eb-8369-0df423d7f282.png">

**Comment by mistercrunch** [comment]
Oh wow, that looks more like a Presto bug to me now. What version of Presto are you on? I bet you'll get the same odd behavior in the Presto CLI

**Comment by mistercrunch** [comment]
https://github.com/prestosql/presto/issues/2166 ?

**Comment by villebro** [comment]
Agreed, it seems this is a bug in the version of Presto you are using.

**Comment by stevensuting** [comment]
Presto version:  0.232
This is a Presto issue and not Superset.
