### ISSUE TITLE
加载数据太慢怎么办呢 

### ISSUE THREAD

**Issue by yu-chun-yu** [apache/incubator-superset#11248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dpgaspar** [comment]
@yu-chun-yu the language used on this repo is English, please translate your title to "What to do if loading data is too slow", and fill out the issue template form.

If your talking about analytical data, consider setting up cache

Going to close this issue, feel free to reopen
