### ISSUE TITLE
[Bug] New pie chart labels and control overlap with controls & actual viz

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#11243]
New pie chart labels look messy in the dashboard view and there are some issues in the explore view as well. 
Screenshots provide additional context

### Expected results

![image](https://user-images.githubusercontent.com/5727938/95795301-e28a1b80-0c9e-11eb-8442-0af8dd8f22dd.png)

### Actual results
![image](https://user-images.githubusercontent.com/5727938/95795245-ba9ab800-0c9e-11eb-8331-53778abf2391.png)

![image](https://user-images.githubusercontent.com/5727938/95795447-339a0f80-0c9f-11eb-90b7-69ecfdc3b5b2.png)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bkyryliuk** [comment]
cc @junlincc @eugeniamz

**Comment by bkyryliuk** [comment]
Another example, current:
![image](https://user-images.githubusercontent.com/5727938/95798873-ea9a8900-0ca7-11eb-9162-7bc0f9599a36.png)

Previous:
![image](https://user-images.githubusercontent.com/5727938/95798966-21709f00-0ca8-11eb-84b8-2f7040275ebb.png)

**Comment by junlincc** [comment]
@bkyryliuk hey Bogdan, thanks for reporting. we are aware of this issue and will work on it!

**Comment by villebro** [comment]
@bkyryliuk this PR should fix threshold + blurriness problems introduced by the new chart: https://github.com/apache-superset/superset-ui/pull/806

**Comment by bkyryliuk** [comment]
> @bkyryliuk this PR should fix threshold + blurriness problems introduced by the new chart: [apache-superset/superset-ui#806](https://github.com/apache-superset/superset-ui/pull/806)

Wow, thank you for the prompt fix!

**Comment by junlincc** [comment]
issue resolved! thank you so much Ville!! closing
