### ISSUE TITLE
Dashboard Markdown deletes edits when changing the size of the component

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11257]
When user adds new markdown into dashboard, edits the text and changes size of the markdown, the text gets lost.

### Expected results
Both text and re-size should be saved

### Actual results
Text user just wrote gets lost

#### How to reproduce the bug

1. Go to Dashboard
2. Click on 'Edit
3. Add Markdown
4. Edit text into the markdown & in a same step resize the markdown
5. click away - markdown size stays, text is lost

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@kgabryje

**Comment by kgabryje** [comment]
I'll look into it

**Comment by kkucharc** [comment]
@zuzana-vej @junlincc Can you check if the problem still appears after fix?

**Comment by junlincc** [comment]
![gif111](https://user-images.githubusercontent.com/67837651/97328502-5138ae80-1833-11eb-814c-0b9fb83d64e9.gif)
tested, all good! Thank you, Kasia!! closing~
