### ISSUE TITLE
Missing sort arrows in Pivot Tables

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#11250]
### Expected results

In pivot tables, there is a place where sort icons are displayed. Used to work fine with 0.36 and before.

### Actual results

 In v 0.37.2 in my case, a blank square appears. 

#### Screenshots

I obfuscated data, you'll see the issue anyway :

In 0.36.0 : 

![image](https://user-images.githubusercontent.com/4623644/95899919-881db780-0d91-11eb-9a79-a4d3d6cffc8b.png)

in 0.37.2 :

![image](https://user-images.githubusercontent.com/4623644/95899827-61f81780-0d91-11eb-8de4-7fbf35426a6f.png)

Here is a more complete view with we developer console open, missing icon selected. I compared oth workig and non working : they display the same thing.

![image](https://user-images.githubusercontent.com/4623644/95900736-9e784300-0d92-11eb-8fae-7f552b5915bc.png)

#### How to reproduce the bug

Visualize any pivot table

### Environment

(please complete the following information):

- superset version: `superset version`
```bash
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.37.2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

- python version: `python --version`
```py
Python 3.6.12
```
- node.js version: `node -v`
```js
v12.16.3
```

- npm version: `npm -v`

```js
6.14.4
```

Built using this Dockerfile : https://github.com/amancevice/docker-superset/blob/main/Dockerfile

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Nothing appear in browser "web console", no missing resources or warnings.

I would have bet on a missing resource file or font or something but no clue as to what I'm looking for.

**Comment by junlincc** [comment]
@villebro 🙏
hey Ville, sorting is not working properly, and the sorting icon disappear when user select more than one to aggregate. not sure if it's related to #10774

**Comment by mistercrunch** [comment]
I think this is more related to the fact that `font-awesome` stopped working properly at some point, and the solution has been to move towards the new `<Icon />` component. I'm not sure if it's possible/easy here.

**Comment by junlincc** [comment]
@mistercrunch there's another pivot table sorting bug. 
please see screenshot, after clicking the descending order sort icon, the results are not sorted properly. ... 13, 14, 15, 15, 154, 2,2 
<img width="544" alt="Screen Shot 2020-10-13 at 9 18 16 PM" src="https://user-images.githubusercontent.com/67837651/95943094-be5f3500-0d99-11eb-80d3-68d0fd549ee4.png">

**Comment by mistercrunch** [comment]
Oh gotcha, well I can confirm that icons also don't render in `master`, and I retract what I said about `font-awesome`, the issue is with Glyphicons, and ancient icon library we're trying to rip out.
<img width="378" alt="Screen Shot 2020-10-13 at 9 39 24 PM" src="https://user-images.githubusercontent.com/487433/95944245-a2a95e00-0d9c-11eb-9447-c6ee169f3796.png">

**Comment by squalou** [comment]
I was wondering if there could be a workaround. I can rebuild fro sources waiting for a proper fix, but I have absolutely no clue as to where to start looking at. I tried to compare with tag 0.36.0 but I didn't find.

I thought I could either add back a woff of the missing font (quick attempt didn't work)
,or change the icon for plain old arrows such as &#8609; but ... no idea where what is hidden.

Any clue welcome ;-)

**Comment by squalou** [comment]
For those maybe intereted, I came up with a workaround.
Using amancevice superset docker image tag 0.37.2 as a base image, I patched the file  `/usr/local/lib/python3.6/site-packages/superset/templates/superset/basic.html` like this :


before :

```html
<html>
  <head>
    <title>
      {% block title %}
        {% if title %}
```


after :

```html
<html>
  <head>
    <style>
        @font-face{font-family:'Glyphicons Halflings';src:url('/static/assets/be810be3a3e14c682a257d6eff341fe4.woff2') format('woff');
        }
    </style>  
    <title>
      {% block title %}
        {% if title %}
```

Note that `be810be3a3e14c682a257d6eff341fe4` depends on the build, so you'd better check the file exists. Else look for a 18kb  woff2 file in  `/usr/local/lib/python3.6/site-packages/superset/static/assets`, it should be it.

**Comment by squalou** [comment]
Update : just tested in 0.38.0 : the woff file disappeared. I copied it back and then the "basic.html" tweak works again.

**Comment by junlincc** [comment]
![ezgif-7-6304ac0ee2a8](https://user-images.githubusercontent.com/67837651/100374615-671bc980-2fc1-11eb-8f6c-c5c33ffdd82a.gif)
confirmed this is working properly now!

**Comment by squalou** [comment]
out of pure curiosity (so, feel free not to answer) : the glyphicons are back in this viz, and will be removed and replaced someday later ? (I remember seeing a discussion about removing glyphicons altogether).
