### ISSUE TITLE
Pivot Table Sorting By First Digit

### ISSUE THREAD

**Issue by AZsineadcheung** [apache/incubator-superset#11268]
When selecting the sort filter in the Pivot Table, the sort is only looking for the first digit of the values and inaccurately presenting the values from the highest value to the lowest and/or vice versa. 

### Expected results

The sort function should be look across across all digits and be able to determine the values from highest to lowest. 

### Actual results

The sort function is only looking for the first digit of the values and is unable to sort the values by the highest or lowest. 

#### Screenshots / Video

https://drive.google.com/file/d/1sMBcjWduhBL99-Me8n2o9v0fWwWkvYun/view?usp=sharing  (ping me if you want access)

#### How to reproduce the bug

1. Create a Pivot Table with a column that has the values 1, 10, 152, 2, 23, 25
2. Click on the sort icon filter for the lowest to highest value
3. Review the order of the values 
4. The values themselves are not being arranged by the order of lowest value to highest
5. Click on the sort icon to filter for the highest to lowest value
6. Review the order of the values 
7. The values themselves are not being arranged by the order of highest value to lowest

### Environment

Superset: 0.36.0
python: 3.6.9
node: 10-jesse

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This doesn't appear to be an issue with chart type 'table'
I'm working on getting test data for the latest release version of superset for testing purposes
logs for python stacktracess appear unrelated

**Comment by junlincc** [comment]
thanks Sinead, we will fix this issue along with https://github.com/apache/incubator-superset/issues/11250

**Comment by junlincc** [comment]
@AZsineadcheung this issue should have been fixed in master, could you check to confirm? thanks!
