### ISSUE TITLE
Dashboard CRUD view Actions have no tooltips

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#11264]
## Screenshot

![image](https://user-images.githubusercontent.com/7409244/96014416-327df500-0dfb-11eb-9d99-f93e0c6818c4.png)

## Description
It's unclear what each icon does when clicking on them.

## Design input
I'd recommend tooltips of: Delete, Download, and Edit, respectively

**Comment by nytai** [comment]
@etr2460 Which view was this on? 

Most of them do have tooltips 
<img width="258" alt="Screen Shot 2020-10-14 at 10 02 20 AM" src="https://user-images.githubusercontent.com/10255196/96021507-63165c80-0e04-11eb-8f6a-61dcf7033cdb.png">

**Comment by etr2460** [comment]
Sorry, this was on the dashboard view

**Comment by nytai** [comment]
@etr2460 which version are you on? The screenshot I posted is for dashboards view off the latest master

**Comment by etr2460** [comment]
Hmm, I might've been a week behind the current master... I'll retest in master again

**Comment by mistercrunch** [comment]
I confirmed that tooltips are available for actions on `master`, feel free to re-open if you can reproduce.
