### ISSUE TITLE
Metric field cut off on right side

### ISSUE THREAD

**Issue by rusackas** [apache/incubator-superset#11277]
## Screenshot

![image](https://user-images.githubusercontent.com/812905/96051967-75f35600-0e31-11eb-9c01-8fd54fc4c224.png)

## Description

Sort By field should take up more space AND truncate the text with an ellipsis (showing the right edge of the pill shape) when it's too long to fit.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment]
<img width="192" alt="Screen Shot 2020-11-24 at 9 35 13 PM" src="https://user-images.githubusercontent.com/67837651/100187441-f8dde680-2e9c-11eb-9700-d3f100c1d746.png">

issue fixed
