### ISSUE TITLE
elasticSearch query  error

### ISSUE THREAD

**Issue by chen-ABC** [apache/incubator-superset#11288]
![image](https://user-images.githubusercontent.com/30097790/96110904-18cfd100-0f13-11eb-923c-0bb92990713b.png)
error log:
![image](https://user-images.githubusercontent.com/30097790/96110977-2f762800-0f13-11eb-9321-94de0eaadf8e.png)

How should I connect es correctly?

### Environment

(please complete the following information):

- superset version: `0.37.0`
- python version: `3.7.9`
- node.js version: `12.18.3`
- npm version: `6.14.6`

**Comment by junlincc** [comment]
@zhaoyongjie

**Comment by zhaoyongjie** [comment]
hi @chen-ABC , this seems like ES drivers error. would you tell me **1)** which ES driver you use and **2)** SQLAlchemy ES driver version ?

**Comment by chen-ABC** [comment]
hi @zhaoyongjie   I'm using  elasticsearch-dbapi 0.1.2,   and  my Elasticsearch is 6.7 versions
this dirver only support Elasticsearch 7.X versions.  What driver should I use to connect?

**Comment by nytai** [comment]
@chen-ABC I think you can only use Elasticsearch >= 7 as anything lower lacks sql support

**Comment by junlincc** [comment]
thank you both @zhaoyongjie and @nytai. closing issue for now.
