### ISSUE TITLE
Star(favorite) alignment issue in explore

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11283]
<img width="961" alt="Screen Shot 2020-10-14 at 10 16 53 PM" src="https://user-images.githubusercontent.com/67837651/96080023-fe421d00-0e6a-11eb-89e8-18a6ce655463.png">

cosmetic issue - ⭐️ alignment in Explore

**Comment by rusackas** [comment]
This was addressed a fair bit in https://github.com/apache/incubator-superset/pull/11215, and thus will be fixed by https://github.com/apache/incubator-superset/pull/10936 in turn

**Comment by junlincc** [comment]
fixed by https://github.com/apache/incubator-superset/pull/11848 
thanks so much, Victor!
