### ISSUE TITLE
Unable to Create Source Tables from Another Schema of my Database

### ISSUE THREAD

**Issue by ogrehunter** [apache/incubator-superset#11297]
Tables from another schema of my database can not be created as data source. However, the table/data can be accessed from the SQL Editor.

### Expected results

Tables from another schema of my database can be created by adding 'schema name.' before a table name. 

### Actual results

I can not add tables from another schema of my database.

#### How to reproduce the bug

1. Go to 'Sources>Tables'
2. Fill the fields with table form another schema.
3. Click on 'Save'

### Environment

(please complete the following information):

- superset version: `Superset 0.37.2`
- python version: `Python 3.8.5`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [v] I have reproduced the issue with at least the latest released version of superset.
- [v] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
@ogrehunter Check if whether the target databasees is setting support DML.
1. Data -> Databases
2. Allow DML 

![image](https://user-images.githubusercontent.com/2016594/96356605-7d617a80-1123-11eb-963a-66b72b3bee56.png)

**Comment by ogrehunter** [comment]
UPDATED:
The problem is SOLVED.
I change the `sqlalchemy-teradata` to `teradatasqlalchemy` and the problem is solved.
