### ISSUE TITLE
Usability - button color and styling 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11299]
<img width="831" alt="Screen Shot 2020-10-15 at 9 04 53 PM" src="https://user-images.githubusercontent.com/67837651/96212020-a23ecd80-0f2a-11eb-8f88-fa26193be3ce.png">

Let's change the data viz select button's color - from grey to CTA colors like blue; please consider changing the button styling below as well. There are a few others in the explore control panel. We should get to them all gradually. @rusackas 🙏

**Comment by rusackas** [comment]
![Uploading Pasted_Image_10_16_20__9_46_AM.png…]()

**Comment by rusackas** [comment]
![Pasted_Image_10_16_20__9_46_AM](https://user-images.githubusercontent.com/812905/96285976-896b0200-0f94-11eb-9c6d-f3d8d786081d.png)

**Comment by mistercrunch** [comment]
You have to pick a dataset!

**Comment by mistercrunch** [comment]
Though the disabled styling isn't super accessible, maybe we can make the text a little darker.

**Comment by mistercrunch** [comment]
<img width="436" alt="Screen Shot 2020-10-21 at 9 31 17 PM" src="https://user-images.githubusercontent.com/487433/96824895-c7c54e80-13e4-11eb-880c-f73361bd13f5.png">

**Comment by junlincc** [comment]
I think as soon as the users select a dataset, the pill color should turn
blue.
