### ISSUE TITLE
Non-chart owners should not be able to edit chart properties

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11292]
Currently when users edit a chart they are not an owner of, they can still change things in the Edit Properties modal, but when they save, it will report "an error occurred". We should either hide the Edit icon or disable all inputs.

#### Screenshots

![image](https://user-images.githubusercontent.com/335541/96188731-1316c300-0ef4-11eb-8ce1-bb061b76a416.png)

#### How to reproduce the bug

1. Edit a chart that you are not an owner of
2. Edit chart properties and change the owner

**Comment by nytai** [comment]
I opened https://github.com/apache/incubator-superset/pull/11381 which is not a perfect fix, but it should make things a little less confusing.
