### ISSUE TITLE
Markdown resize not working when Markdown added into new tab as full width

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11304]
In some cases, markdown resize doesn't work. Specifically when markdown is being added into new tab.

### Expected results
Should be able to resize Markdown.

### Actual results

Can't resize the Markdown.

#### Screenshots

![Screen Shot 2020-10-16 at 9 41 41 AM](https://user-images.githubusercontent.com/61221714/96285438-d0a4c300-0f93-11eb-8220-cd7e57e4d9f5.png)

#### How to reproduce the bug

1. Go to Dashboard edit mode
2. Add new tab at the bottom of a page (or add tab within a tab)
3. Add Markdown into the tab
4. Markdown will be full width by default, and the resize (in right corner) doesn't work

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@kkucharc

**Comment by junlincc** [comment]
@kkucharc tested on latest master, still not working properly. 
resizing works at the dashboard level, but not tab level. 
![testmarkdown](https://user-images.githubusercontent.com/67837651/97633964-29dc1000-19f2-11eb-81c2-f0230abb1143.gif)

**Comment by zuzana-vej** [comment]
Agreed. I tested this yesterday too. This is some corner case which isn't fixed yet.

**Comment by kkucharc** [comment]
Hi, thanks for testing and letting me know. This is interesting, because on latest master I was able to resize it:

![Large GIF (640x356)](https://user-images.githubusercontent.com/2536609/97720081-2024dc00-1ac8-11eb-8e72-b317c9522fcf.gif)

Or maybe I miss some steps:
1. I go to dashboards
2. Add markdown and resize to max
3. Add tabs
4. Move markdown to tabs
3. Resize markdown


Can you tell me what browser are you using for testing?

**Comment by kgabryje** [comment]
@junlincc @zuzana-vej That's strange, I just tested in on the latest master and resizing does work in a tab. Though contrary to the description, Markdown isn't full width by default (though if I resize it to full width, further resizing still works)
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/15073128/97720898-18b20280-1ac9-11eb-80a6-a8b730b0174d.gif)
.

**Comment by zuzana-vej** [comment]
Yes! Verified. Thank you!
