### ISSUE TITLE
Chart breaking (in dashboard) after editing metadata (in explore)

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11306]
After editing the description for a chart in a dashboard and reloading the dashboard, the chart is replaced with a missing chart definition error (image attached) and can't be reverted.

### Expected results

Chart is correctly displayed on the dashboard

### Actual results

Error message on the dashboard

#### Screenshots

Step 1:
<img width="1117" alt="Screen Shot 2020-10-16 at 10 03 07 AM" src="https://user-images.githubusercontent.com/61221714/96287628-13b46580-0f97-11eb-82ba-202dbf938e55.png">

Step 2:
<img width="740" alt="Screen Shot 2020-10-16 at 10 02 34 AM" src="https://user-images.githubusercontent.com/61221714/96287637-16af5600-0f97-11eb-9e39-8b40f5e1ba23.png">

Step 3: -- BUG
<img width="1135" alt="Screen Shot 2020-10-16 at 10 03 02 AM" src="https://user-images.githubusercontent.com/61221714/96287612-10b97500-0f97-11eb-8b5f-b20c463c6b82.png">

#### How to reproduce the bug

1. go to dashboard
2. explore chart
3. add description to chart and save (Under Edit chart properties)
4. refresh dashboard / go back to the dashboard
5. See chart breaks (displays error message)

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@zuzana-vej Hey Zuzana, this issue was first reported in August. please confirm they are the same. It's in the backlog waiting for a fix. 
https://github.com/apache/incubator-superset/issues/10528
https://github.com/apache/incubator-superset/issues/11232

**Comment by zuzana-vej** [comment]
confirming this was fixed by https://github.com/apache/incubator-superset/pull/11830
