### ISSUE TITLE
sqllab can not load

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#11302]
- superset version: `0.29.0rc7 `
- python version: `3.6.8`
then sql_lab page cannot be displayed，Js error
 ![image](https://user-images.githubusercontent.com/20242930/96237170-8fca9f80-0fcf-11eb-9472-683124b97fe5.png)

**Comment by zhaoyongjie** [comment]
hi @qinzl1, Please fill in the issue template to provide more problem description.

**Comment by qinzl1** [comment]
@zhaoyongjie 
Probable cause
![image](https://user-images.githubusercontent.com/20242930/97431821-eb911300-1955-11eb-8248-81eb20e64698.png)

**Comment by zhaoyongjie** [comment]
@qinzl1 

Can it be reproduced in the latest version of Superset. The latest version is now 0.38
