### ISSUE TITLE
write tests for fundamental tasks

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#1131]
We need tests to catch regression on database, table and slice creation.

**Comment by bkyryliuk** [comment]
100 % true, @xrmx  could you please write down a list of the use cases the should be tested, it would be easier this way for others just pick a test case and implement it.

**Comment by SalehHindi** [comment]
@xrmx, I would be down to help with this. What do you mean by regression exactly? What test cases did you have in mind?

**Comment by xrmx** [comment]
@SalehHindi user can login, user can add a datasource, user can create a dashboard from that datasource, etc... When i opened this issue we had a bug where the link for creating a slice from a sql alchemy datasource was wrong and so users cannot create slices from there.

**Comment by xrmx** [comment]
@SalehHindi e.g. #1795 would be the type of bugs we can avoid with proper tests
