### ISSUE TITLE
New list view strange style

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/incubator-superset#11319]
## Screenshot
![image](https://user-images.githubusercontent.com/2016594/96339588-4611b000-10c8-11eb-95aa-db354b1060e5.png)

## Description
Can we keep these action icons displayed here instead of waiting until the pointer hoverd

**Comment by junlincc** [comment]
@zhaoyongjie thanks for suggesting. this is by design, I believe. our designer can chime in to give more details.
