### ISSUE TITLE
SQL should display "query preview" by default when user selects schema & table (past behavior)

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11329]
In the past when user selects schema and table name, SQL Lab displays list of columns on the left side and switches automatically to "Preview tab", so that the user can preview the data immediately. After the recent changes in SQL Lab, the default tab stays at "Results" (which are SQL Lab query results) so user needs to make an extra click to switch to the preview tab to preview their data.

### Expected results
Tab automatically switches to "Preview: table-name"

### Actual results
Tab remains as "Results"

#### Screenshots
1. user selects schema & table
![Screen Shot 2020-10-19 at 9 10 13 AM](https://user-images.githubusercontent.com/61221714/96477290-2cb55480-11eb-11eb-953b-338aa37fd8a7.png)

2. Default tab should change to "Preview: table-name" (this was past behavior)
![Screen Shot 2020-10-19 at 9 10 20 AM](https://user-images.githubusercontent.com/61221714/96477336-39d24380-11eb-11eb-9505-f166e317623e.png)

#### How to reproduce the bug

1. Go to SQL Lab
2. Select schema in the picker on left side
3. Select table name
4. List of columns loads properly; the tab stays at "Results" instead of switching to "Preview" so that user can preview data

### Environment

(please complete the following information):

- superset version: master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@lilykuang Lily, I believe you have been working on this area. please take a look at this issue🙏 

@willbarrett

**Comment by mistercrunch** [comment]
@junlincc this could be related to recent `antd` `<Tab/>` work by @kgabryje (?)

**Comment by kgabryje** [comment]
I'll check it out!

**Comment by kgabryje** [comment]
@zuzana-vej @mistercrunch Here's a fix: https://github.com/apache/incubator-superset/pull/11343

**Comment by zuzana-vej** [comment]
@kgabryje  thank you!

**Comment by rusackas** [comment]
Fix merged!

**Comment by zuzana-vej** [comment]
I am still seeing the issue. Switching tabs works. But in the past, when user selects a table name on left side from the schema, it automatically switched to the tab with the preview. Currently the tab shows up, but user needs to manually switch.

Is this new behavior as designed or a bug?

Image 1: Searching for the table I selected
<img width="741" alt="Screen Shot 2020-10-21 at 6 32 02 PM" src="https://user-images.githubusercontent.com/61221714/96807670-04d11700-13cc-11eb-994b-1a4a402431e0.png">


Image 2: See the data preview isn't default tab
<img width="757" alt="Screen Shot 2020-10-21 at 6 32 11 PM" src="https://user-images.githubusercontent.com/61221714/96807664-026ebd00-13cc-11eb-9613-804bf98d845f.png">

**Comment by kgabryje** [comment]
@zuzana-vej Are you sure you're testing it on the latest master? For me it was exactly like you expect (see gif).
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15073128/96847211-304b1480-1453-11eb-9280-7dd406a6bb33.gif)

**Comment by zuzana-vej** [comment]
![sqllab-preview](https://user-images.githubusercontent.com/61221714/96902587-8e72fa00-1449-11eb-9cf0-5d80315eeb87.gif)

Yes latest master, just synced it yesterday.  Using Chrome.

**Comment by kgabryje** [comment]
@zuzana-vej I'm sorry, but I cannot reproduce it 🙁  Does anybody else still experience this issue?

**Comment by zuzana-vej** [comment]
Yeah. No problem. I'll close this and if necessary reopen. Thanks for checking @kgabryje
