### ISSUE TITLE
Set up Superset at a location other than the root

### ISSUE THREAD

**Issue by neelkarki** [apache/incubator-superset#11321]
I want to run my superset other than the root directory
currently its working on localhost:8080 I want to setup this localhost:8080/superset
Any Solution for this??

**Comment by mistercrunch** [comment]
This issue is a duplicate. I can't seem to find the original but it's there somewhere...

**Comment by neelkarki** [comment]
> This issue is a duplicate. I can't seem to find the original but it's there somewhere...

do you have any solution for this

**Comment by maudrid** [comment]
I had the same question some time ago. The answer was that it could not be run on a location other than root.
