### ISSUE TITLE
Shifting cursor (forward) when editing Markdown with emoji

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11331]
When editing a markdown component with a specific emoji (which occupies two characters) - for example the start emoji which is by default on the markdown component, clicking on text places the cursor one character to the right and making editing confusing.

### Expected results

Cursor stays at correct position

### Actual results

Cursor jumps 1 step forward

#### Screenshots
It's hard without video, but here are few screenshots (I can share video if needed). In this example I am trying to correct "payouss" to "payouts"

<img width="314" alt="Screen Shot 2020-10-19 at 10 16 07 AM" src="https://user-images.githubusercontent.com/61221714/96489617-83735c00-11f4-11eb-8847-7577cdcfff2b.png">
<img width="239" alt="Screen Shot 2020-10-19 at 10 16 25 AM" src="https://user-images.githubusercontent.com/61221714/96489621-853d1f80-11f4-11eb-87ed-ab2a9ccd7364.png">
<img width="278" alt="Screen Shot 2020-10-19 at 10 17 00 AM" src="https://user-images.githubusercontent.com/61221714/96489625-8706e300-11f4-11eb-9f2d-5d7d7a1cb33b.png">

#### How to reproduce the bug

1. Go to Dashboard, Add Markdown with emoji (e.g. the start shape)
2. Try to edit a sentences (after the emoji) and see the cursor jumps around (deletes character forward, not correct one)

### Environment

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
@junlincc FYI. I know there are other two open bugs for markdown https://github.com/apache/incubator-superset/issues/11304 and https://github.com/apache/incubator-superset/issues/11257 they are all different, just wanted to surface this as it relates to the same component.

**Comment by junlincc** [comment]
@zuzana-vej Thank you, Zuzana for reporting and linking. We will get to it in a couple weeks 🙏

**Comment by junlincc** [comment]
@kkucharc 🙏

**Comment by kkucharc** [comment]
I think this is known issue of Ace Editor which is used here:
https://github.com/ajaxorg/ace/issues/4142
Even it appears when I try put ✨ in their demo:
https://ace.c9.io/
I tried check the newest version of `react-ace` but it didn't help. I suggest to wait for a fix in the library.

**Comment by zuzana-vej** [comment]
Thanks @kkucharc, closing this bug.
