### ISSUE TITLE
Error messages do not wrap

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#11352]
It seems that Superset errors do not wrap (the example is from SQL Lab and thus I'm uncertain how broad of an issue this is) meaning one needs to scroll horizontally in order to parse the message.  

### Expected results

The error message should wrap to aid with readability.

### Actual results

The errors do not wrap.

#### Screenshots

<img width="900" alt="Screen Shot 2020-10-20 at 9 35 08 PM" src="https://user-images.githubusercontent.com/4567245/96674094-d8aa8d00-131c-11eb-9c5d-fdb9acc8b231.png">

#### How to reproduce the bug

1. Go to SQL Lab
2. Run an invalid query, i.e., ``SELECT `1` `` if using Presto.
3. Reduce the width of the browser to ensure that the error overflows.

### Environment

`master`.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

N/A.

**Comment by mistercrunch** [comment]
Mmmh, this one is my bad as I brought the monospace / <pre> wrapping here. Let me see if I can fix this real quick.

**Comment by mistercrunch** [comment]
here: https://github.com/apache/incubator-superset/pull/11354

**Comment by mistercrunch** [comment]
@junlincc the action of merging the associated PR will auto-close this issue, reopening until it gets merged
