### ISSUE TITLE
 version: 0.30 Translation is not good

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#11357]
superset version: 0.30

![image](https://user-images.githubusercontent.com/20242930/96694137-a2bbe600-13ba-11eb-9e12-ed3fc9066430.png)

**Comment by junlincc** [comment]
Hi @qinzl1 We currently rely on the community to improve translations. If you are proficient in Japanese and would like to contribute to translating text strings, [contributor guide](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#add-translations) gives you all the details. Feel free to reach out to me in Slack if you have further questions.

**Comment by qinzl1** [comment]
@junlincc It doesn't show the translated content
