### ISSUE TITLE
Datasource Menu box cuts off when datasource name is long

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11378]
When datasource name is long, the menu (after use clicks the three dots) renders off - cuts off. It’s still on the screen but below the chart instead of rendering to the left.

### Expected results

Render to the left.

### Actual results

Cuts off.

#### Screenshots

<img width="513" alt="Screen Shot 2020-10-21 at 5 58 27 PM" src="https://user-images.githubusercontent.com/61221714/96805790-427f7100-13c7-11eb-8e89-d363dbb51647.png">

#### How to reproduce the bug

1. Go to 'Chart Explore' - chart with long virtual datasource name
2. Click on 'the three dots'
3. See the issue

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment]
Duplicate of #11094

**Comment by junlincc** [comment]
@zuzana-vej would you mind consolidating all the cut-off/overflow issues, including pills, metric fields, etc.? we will tackle them by category all at once.  🙏

**Comment by zuzana-vej** [comment]
I ll close this since it's duplicate, will link the other issues.
