### ISSUE TITLE
Explore Query metrics value popup does not open automatically

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11388]
### Expected results
After selecting a Metric in the Explore control panel, popup used to open automatically 
<img width="563" alt="Screen Shot 2020-10-22 at 6 59 37 AM" src="https://user-images.githubusercontent.com/67837651/96882513-3c73a980-1434-11eb-8613-2a10eff9574e.png">

### Actual results

![ezgif-3-ed4e36de732a](https://user-images.githubusercontent.com/67837651/96883462-4ba72700-1435-11eb-8a7a-28e14e1801d3.gif)

#### How to reproduce the bug

1. open any charts in Explore
2. Click on 'METRIC
3. Select Metric Value

**Comment by zuzana-vej** [comment]
This item is also related https://github.com/apache/incubator-superset/issues/11394

**Comment by junlincc** [comment]
@kgabryje Kamil~

**Comment by kgabryje** [comment]
I'll check it out

**Comment by junlincc** [comment]
tested, fixed. closing!
