### ISSUE TITLE
QUESTION: Pip install with Helm?

### ISSUE THREAD

**Issue by joehoeller** [apache/incubator-superset#11387]
**Is this the correct config to install the database connectors using Helm:**

```

replicaCount: 1

## These requirements are used to build a requirements file which is then applied on init
## of superset containers

additionalRequirements:
    - "psycopg2==2.8.5"
    - "redis==3.2.1"
    - "apache-superset[mssql]"
    - "apache-superset[drill]"
    - "apache-superset[postgres]"
    - "apache-superset[gsheets]"
    - "apache-superset[elasticsearch]"
    - "apache-superset[bigquery]"
    - "apache-superset[hive]"
    - "apache-superset[impala]"
    - "apache-superset[mssql]"
    - "apache-superset[teradata]"
    - "apache-superset[redshift]"
    - "apache-superset[oracle]"

```

**Comment by joehoeller** [comment]
@maxg203

**Comment by craig-rueda** [comment]
@joehoeller - Here's the related docs around DB drivers: https://superset.apache.org/docs/databases/installing-database-drivers

For instance, to install `Oracle`:

```
additionalRequirements:
  - cx_Oracle
```

**Comment by i4vijay** [comment]
Hi All,

Need some help on the complete process of enabling email scheduling in Superset. I have enabled email feature in superset but facing difficulties in configuring celery and redis. I did searched in git hub and in stackoverflow but couldn't find the solution. Could someone share some light over here.

**Comment by joehoeller** [comment]
@craig-rueda  are we supposed to provide our own configMap with config.py file?

**Comment by craig-rueda** [comment]
Yep, you'd need to create a new secret with your own keys in it, similar to this: https://github.com/apache/incubator-superset/blob/master/helm/superset/templates/secret-superset-config.yaml

You can then point the chart at it by using the prop: https://github.com/apache/incubator-superset/blob/master/helm/superset/values.yaml#L33

Lastly, here's the docs regarding email scheduling: https://superset.apache.org/docs/installation/email-reports

The config options mentioned there would need to be dropped into the new config that you create.

Hope this helps
