### ISSUE TITLE
Datasource edit doesn't save schema, only saves new dataset name

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11380]
On chart explore, when you click on change dataset, and try to edit the datasource (table) name, the table name change works as expected but unless you edit schema, the existing schema doesn't get saved causing the chart to break.

### Expected results

Both schema and table name should change.

### Actual results

Only table name changes.

#### Screenshots

Step 1: my table name (before change)
<img width="289" alt="Screen Shot 2020-10-21 at 6 38 34 PM" src="https://user-images.githubusercontent.com/61221714/96808094-0222f180-13cd-11eb-822a-5e319c1242cf.png">

Step 2: try to edit table name, schema is same - do not edit schema
<img width="716" alt="Screen Shot 2020-10-21 at 6 37 46 PM" src="https://user-images.githubusercontent.com/61221714/96808122-0f3fe080-13cd-11eb-86c0-b0d42960ead1.png">

Step 3: This is the result: New table name is displayed with NO SCHEMA. if you run chart, it breaks.
<img width="365" alt="Screen Shot 2020-10-21 at 6 37 53 PM" src="https://user-images.githubusercontent.com/61221714/96808138-1b2ba280-13cd-11eb-8530-0b7e6221ee20.png">

#### How to reproduce the bug

1. Go to 'Chart Explore'
2. Click on 'Change Dataset'
3. Enter new table name, keep same schema
4. Click on Save
5. See issue

### Environment

(please complete the following information):

- superset version: master
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
@lilykuang

**Comment by lilykuang** [comment]
I just opened for the fix https://github.com/apache/incubator-superset/pull/11396

**Comment by willbarrett** [comment]
Closing as the fix is merged.

**Comment by benceorlai** [comment]
This issue has cropped up again on our side

**Comment by lilykuang** [comment]
@benceorlai the step I tried to reproduce this issue 
https://www.loom.com/share/494cf29e697841f5b6c038c2642892bc
It doesn't seem to have issue. did i miss anything?

**Comment by lilykuang** [comment]
quick fix for this issue https://github.com/apache/incubator-superset/pull/12018
