### ISSUE TITLE
[CRUD VIEW] Dashboard / Chart list page send too many requests

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11384]
When I open dashboard or chart list page with ENABLE_REACT_CRUD_VIEWS flag:

### Actual results
![Screen_Shot_2020-10-21_at_1_22_18_PM](https://user-images.githubusercontent.com/27990562/96831408-e4b44e80-13f1-11eb-8b9f-1ef7128f873a.jpg)

- it sends 25 api calls to backend. If i have 50 items per page, then it will send 50 api calls.
- each api call is to check if dashboard/chart is favorite

### Expected results

Can this `favorite` information get loaded with other bootstrap data? 
We should keep this api in this page, so that user can fav/unfav dashboard without open it. But sending a call for each of item, this design is not optimized.

### Environment

latest master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Thanks for letting us know @graceguo-supercat - we'll take a look at this.

**Comment by mistercrunch** [comment]
Looks like the favorite/star (?)

**Comment by willbarrett** [comment]
Yup.
