### ISSUE TITLE
Superset edit filter popover disappearing on hover

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11394]
The filter UI is more sensitive than before, leading to “catch me if you can” type of experience. When adding a filter to a chart (so in Explore view, you click on  or trying to edit it, the popover containing filter settings disappears when moving the cursor from the filter to it (check out attached video). This doesn't happen all the time, but when it does, it's very frustrating. Sometimes, the popover displays, but is closed (disappears) before user clicks "save" or "cancel". 

Browser: Chrome 

### Steps to Reproduce:
1. Create or open superset chart.
2. Click filter.
3. Hover to edit filter popover.

Result: Popover disappears. 

Expected Result: Popover stays in place so I can edit the filter. Unfortunately not able to repro 100%. Happens sometimes... so planing to keep this bug open and keep checking if users encounter it again. 

Popover should only close when user clicks on save or cancel, not when user moves mouse around. This piece of the issue is reproduceable more frequently.

#### Screenshots

Step one: Click on a metric, filter box displays
<img width="325" alt="Screen Shot 2020-10-22 at 9 02 14 AM" src="https://user-images.githubusercontent.com/61221714/96899458-cbd58880-1445-11eb-92de-dd05197a3122.png">

Step two: Move mouse into the filter box - it disappears
<img width="284" alt="Screen Shot 2020-10-22 at 9 02 20 AM" src="https://user-images.githubusercontent.com/61221714/96899497-d5f78700-1445-11eb-9e1a-7298ae21a1c4.png">

### Environment

(please complete the following information):

- superset version: master 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
Related to https://github.com/apache/incubator-superset/issues/11388

**Comment by junlincc** [comment]
💔💔💔!

**Comment by junlincc** [comment]
@eschutho could you please take a look at #11394, [#11388](https://github.com/apache/incubator-superset/issues/11388) and [#11379,](https://github.com/apache/incubator-superset/issues/11379) i think they are all related. 🙏

**Comment by eschutho** [comment]
sure, I'll take a look. Do you want to assign this to me?

**Comment by junlincc** [comment]
> sure, I'll take a look. Do you want to assign this to me?

let me know how long it's gonna take you. Kamil and Kasia can help 🙏

**Comment by eschutho** [comment]
I have a quick fix, although I think the use of state vs props in the component could use some improvements. If you think it's worth pushing out a fix with the existing code, I can put up a PR now, or wait until next week.

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/11163 @kgabryje Kamil~

**Comment by zuzana-vej** [comment]
Here is another video recording when it disappears after user starts typing, if they move their mouse outside the popover area.

![popover-issue-2](https://user-images.githubusercontent.com/61221714/97034356-a1ed9600-1519-11eb-80d9-031cba92bbc2.gif)

**Comment by kgabryje** [comment]
I'll check it out
