### ISSUE TITLE
Backspaces and spaces do not work when editing simple filter value in explore chart

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11404]
### Description:
When editing the value of a simple filter in explore box, backspaces and spaces are broken. It seems like they are not being entered into the filter value text box but are instead being entered into the filter column drop down. The space problem also occurs when editing custom SQL, which majorly breaks custom sql filters. The only workaround to type a space is to type the value/custom sql elsewhere and paste it into the desired textbox.

How often can this be reproduced?
100%

### Steps to Reproduce:

1. Create a table chart
2. Click FILTERS drop down and select a column
3. Type a space and observe that the space is entered into the filters drop down instead of the value text box
4. Type a backspace and observe that the filter modal closes

### Result:
After typing space: Space does not appear in filter value text box

After typing backspace: Modal closes

### Expected Result:
After typing space: Space appears in filter value text box

After typing backspace: The character before the cursor disappears.

### Screenshots
![filter-space-issue](https://user-images.githubusercontent.com/61221714/96951332-16d0b980-14a1-11eb-9cf3-66a5fbb56e5a.gif)

### Environment

(please complete the following information):

- superset version: `master` 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
@junlincc This could be caused by the same PR as the other cosmetic issues on chart explore: https://github.com/apache/incubator-superset/issues/11394 https://github.com/apache/incubator-superset/issues/11379

**Comment by junlincc** [comment]
> @junlincc This could be caused by the same PR as the other cosmetic issues on chart explore: #11394 #11379

just tested.agreed. 👌

**Comment by mistercrunch** [comment]
@kgabryje ^^^

**Comment by kgabryje** [comment]
I'll check it out

**Comment by kgabryje** [comment]
@junlincc It's been fixed by https://github.com/apache/incubator-superset/pull/11428, I think we can close this issue

**Comment by zuzana-vej** [comment]
Yes it's fixed. thank you
