### ISSUE TITLE
Dashboards: Can't use charts that you own but didn't create

### ISSUE THREAD

**Issue by rwspielman** [apache/incubator-superset#11413]
When looking at "Your charts and filters" in Dashboard edit mode, visualizations that you are a listed 'owner' on, but didn't create, don't appear in the list.

### Expected results

Given the selection is "your charts and filters", I would expect it to include charts/filters that you own, not just charts/filters that you created. 

### Actual results

Only charts that you are the creator of appear in the list. This hinders collaborative work

#### Screenshots

Caleb Reed is creator:
![Screen Shot 2020-10-23 at 12 49 58 PM](https://user-images.githubusercontent.com/20442310/97036987-4548a600-152e-11eb-9efb-05f207508e2c.png)

Rob Spielman is owner:
![Screen Shot 2020-10-23 at 12 48 57 PM](https://user-images.githubusercontent.com/20442310/97036897-1fbb9c80-152e-11eb-9b45-250120cb9aec.png)

Not appearing in "Your charts and filters"
![Screen Shot 2020-10-23 at 12 48 08 PM](https://user-images.githubusercontent.com/20442310/97036822-031f6480-152e-11eb-9792-7ec60deb917c.png)

#### How to reproduce the bug

1. Login as User 1
1a. Create a chart
1b. Add user2 as owner in addition to User1
2. Login as User 2
2a. Go to a dashboard and edit
2b. Search for that chart name in "Your Charts and Filters"
2c. Observe it does not show up 

### Environment

(please complete the following information):

- superset version: `superset version` 0.37.2
- python version: `python --version` 3.6.9
- node.js version: `node -v` 8.10.0
- npm version: `npm -v` 3.5.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rwspielman** [comment]
If you change line 48 in here to 
`endpoint: `/sliceasync/api/read?_flt_0_owners=${userId}`,`
it should close this issue

https://github.com/apache/incubator-superset/blob/master/superset-frontend/src/dashboard/actions/sliceEntities.js

**Comment by nytai** [comment]
@rwspielman You should still be able to add the chart to the dashboard via the chart explore page as a workaround.

**Comment by rwspielman** [comment]
@nytai Thank you! somewhat unrelated to the issue, but our organization would benefit from separate permissions that allow users to use charts in a dashboard without being the owner. i.e. read-only access to a dashboard. we could just remove the filter on this query, but that sort of opens up every chart to all users which could be a very large list
