### ISSUE TITLE
Apply button gets pushed out of filter box when the filter box is small with too many filter values selected 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11419]
### Expected results
Textbox width should adjust accordingly depends on the size of the filter box. 
apply fixed height when there are many filter values selected in one field, and display only a limited number of values that fits
Apply button should always be in the box.
<img width="826" alt="Screen Shot 2020-10-25 at 10 02 50 AM" src="https://user-images.githubusercontent.com/67837651/97113687-4520e580-16a9-11eb-86a2-8249c5e2012a.png">

### Actual results

<img width="1038" alt="Screen Shot 2020-10-25 at 10 00 14 AM" src="https://user-images.githubusercontent.com/67837651/97113844-1fe0a700-16aa-11eb-9be6-879800b42ca2.png">

Tested on latest master

**Comment by junlincc** [comment]
@kkucharc 🙏

**Comment by kkucharc** [comment]
We agreed to add the vertical scroll to whole Filter block as a workaround.

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/11580 temporary solution, scroll bar for entire filter box. should revisit 
![ezgif-3-3a36512a9779](https://user-images.githubusercontent.com/67837651/101209005-dfb90080-3627-11eb-8a68-80571a643c14.gif)
