### ISSUE TITLE
Suggestion: disable caret changing directions in adhoc filters

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11434]
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/97235350-e8542680-179f-11eb-94be-05ac8edd52a6.png" width="300">

## Description

Can we disable the behavior of changing caret directions on adhoc filter/metric popover open/close? It doesn't really add any real benefits in terms of UI clarity but is kind of distracting. 

The recently added animation to the popover makes it feel even weirder because now the caret will change direction even before the popover shows up.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

Would appreciate inputs from designers and any fellow users!

**Comment by ktmud** [comment]
cc @mistercrunch since you added this behavior in #10123 .

**Comment by junlincc** [comment]
Using rotating caret when clicking on a Dropdown is quite common in design, i haven't seen many on Popover though. Different design systems also define popovers differently.  Mihir and I can do some more exploration since we will reorganize the control panel fields and see what makes the most sense.

**Comment by mistercrunch** [comment]
@ktmud I only fixed the icon display in #10123.

I don't feel like they add value either, I support removing them and I don't think we need to replace them with something else.

**Comment by mistercrunch** [comment]
The more outrageous thing in this area is the label-within-a-rectangle rendering. We should just use our `<Label />` here and bring the `x` inside of it, get rid of the rectangle container.

**Comment by junlincc** [comment]
disabled the rotating. will work on the styling along with other control panel improvements in 1.0.
