### ISSUE TITLE
Superset 0.37.2 no longer works behind a load balancer

### ISSUE THREAD

**Issue by axhza** [apache/incubator-superset#11431]
Superset 0.37.2 no longer works behind a load balancer.

### Expected results

I expect load balancing functionality to work.

### Actual results

0.37.0: I had to disable CSRF protection to get superset to _barely_ work behind a load balancer.
0.37.2: It no longer works behind a load balancer at all.

#### Screenshots

The below screenshot is the web dev log when trying to access from the load balancer:

![Screenshot_2020-10-26_14-51-18](https://user-images.githubusercontent.com/24252625/97227355-feabb380-179a-11eb-854b-6a4179089e63.png)

#### How to reproduce the bug

To confirm this is the case, I fresh installed 0.37.2 from pip; I then went to the page behind the load balancer to see pic above.

### Environment

(please complete the following information):

- superset version: `0.37.2`
- python version: `3.6.9`
- node.js version: NA
- npm version: NA

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The load balancer is an F5. Superset is serving directly using gunicorn (it's not proxied behind nginx). The gunicorn version is `20.0.4`. There are no stack traces in gunicorn. Everything works as normal when accessing directly (not through LB). Some other things I did to test:

- I ran via `superset run` and got the same error.
- I proxied from nginx to gunicorn and got the same error.

Gunicorn config:

```
bind = "0.0.0.0:8080"
workers = 2
max_requests = 5000
timeout = 120
keepalive = 30

limit_request_line = 0
limit_request_field_size = 0

forwarded_allow_ips = "x.x.x.x"
secure_scheme_headers = {'X-Forwarded-For': 'https'}
```

Superset config:
```
ROW_LIMIT = 5000

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = False
WTF_CSRF_EXEMPT_LIST = []
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24

# Proxying
ENABLE_PROXY_FIX = True
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_HTTPONLY = False
```

**Comment by nytai** [comment]
@axhza looks like the assets requests are 404ing, there's a lot that could be going on to cause this. Do those assets exist on the server? Are you serving a cached version of the page and it's requesting old assets?

**Comment by axhza** [comment]
Those specific assets do not exist, it leads me to believe that they were possibly built incorrectly?
```
# find . -iname '*welcome.*.entry.js'
./lib/python3.6/site-packages/superset/static/assets/welcome.7af8e33b4762eab4abcf.entry.js
```

Also, it's weird that going to superset directly works?

Caching is disabled via superset config.

**Comment by nytai** [comment]
Looks like you're somehow getting a cached version of the page (which is requesting assets that no longer exist on the server). If hitting gunicorn directly results in no error then the issue is likely with your load balancer config. Does a hard refresh solve it?

**Comment by axhza** [comment]
Nope, I wiped browser cache and tried in incognito. Am confirming that LB isn't caching, it may be...

**Comment by nytai** [comment]
Do you have multiple instances of superset running? Are they all running the same version and serving the same page?

**Comment by axhza** [comment]
Only a single instance.

**Comment by villebro** [comment]
@axhza the issue you are running into is what was blocking us from upgrading to the `19.9` version of `gunicorn`. My impression is that these problems were resolved long ago, and should be working without trouble in the `20.0.x` versions. Can you post your `pip list` here?

**Comment by axhza** [comment]
I don't believe it's related to `gunicorn` because `superset run` provides exact same error.

**Comment by mistercrunch** [comment]
Please share `pip freeze | grep -i gunicorn`

**Comment by axhza** [comment]
```
gunicorn==20.0.4
```

**Comment by axhza** [comment]
Closing this; cache was not properly disabled on the F5. Superset works just fine.
