### ISSUE TITLE
How do filter graphics do fuzzy queries

### ISSUE THREAD

**Issue by yu-chun-yu** [apache/incubator-superset#11440]
How do filter graphics do fuzzy queries
 There is a requirement to select criteria that meet the rules through fuzzy queries
The other thing is that Phoenix + Hbase can't show the timestamp on top of it. How do you solve that

**Comment by mistercrunch** [comment]
I reread multiple time and I don't understand the question.

**Comment by ktmud** [comment]
I think op meant to ask how to enable fuzzy filters (e.g. `name like 'Alex%'`) in FilterBox, which is not currently supported in Superset.
