### ISSUE TITLE
Apache Superset 0.37.1 : Manage Dashboard Email and Chart Email schedule do not appear 

### ISSUE THREAD

**Issue by bzmatteo72** [apache/incubator-superset#11442]
Hello,

please I'm new to Superset, We have installe version 0.37.1 on Linux OS
I have followed all the instructions at the following doc page https://superset.apache.org/docs/installation/email-reports
to set up the email and schedule reports but the following views do not appear in Chrome browser:
Manage > Dashboard Emails
Manage > Chart Email Schedules

Please could abybody provide help to resolve this issue?
Thanks
Matteo

**Comment by mistercrunch** [comment]
Flip these config flags https://github.com/apache/incubator-superset/blob/master/superset/config.py#L764-L769

**Comment by bzmatteo72** [comment]
Thnaks for your hint but I have already done these changes to config.py but it doesn't work anyway
Please do not close this issue
