### ISSUE TITLE
Time Series Chart appears broken

### ISSUE THREAD

**Issue by eschutho** [apache/incubator-superset#11451]
Time Series Chart is not displaying data. 
This was tested with a dataset that has one column of type "TIMESTAMP WITHOUT TIMEZONE"
No data appears on the chart
The tooltip shows a value (count) of 134, but the y axis only goes from 0 to 1.
Time series bar chart works as expected (shown for comparison)

### Expected results

Data points should show on chart and y axis should be in range of values

### Actual results

no data points are showing and y axis is below the range

#### Screenshots

<img width="1782" alt="Explore_-_Untitled_Query_2-nsNsrd_ct" src="https://user-images.githubusercontent.com/5186919/97366715-00da4480-1865-11eb-9b53-333c83f62bca.png">

![Explore_-_random_time_series](https://user-images.githubusercontent.com/5186919/97367085-bdcca100-1865-11eb-8d92-b3101443bd9c.png)

#### How to reproduce the bug

1. Go to the Charts tab
2. Create a new chart with a timestamp value or select an existing one
3. Change chart type to "time series chart"

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.7.3`
- node.js version: `v12.18.3`
- npm version: `6.14.8`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Found during regression testing

**Comment by mikeprior12345** [comment]
Hi, I also see this issue. Just wondered if there is a workaround/fix?

**Comment by villebro** [comment]
This is already fixed on master by #11393 (the fix was done by bumping the ECharts viz plugin module).
