### ISSUE TITLE
SSL Connection with Elasticsearch - Self signed certificate issue

### ISSUE THREAD

**Issue by mbachtell** [apache/incubator-superset#11454]
Trying to connect to cloud hosted (IBM) elasticsearch which has a self signed certificate issued for the service.  Have tried the solution suggested at https://github.com/apache/incubator-superset/issues/8709 but that is not working.  Docker logs all circle back to `urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)` . I've typically been able to go in and modify the requests.get call with a verify=False statement but that doesn't seem to be working.

### Expected results
Connection to elasticsearch on a cloud hosted environment with a self signed certificate.

### Actual results

Error/Non-connection due to rejection of a self signed certificate.

#### Screenshots
![image](https://user-images.githubusercontent.com/7209237/97437110-66781080-18f9-11eb-8e11-409b2084d2f5.png)

### Environment
Windows Subsystem Linux (Ubuntu), Windows 10

(please complete the following information):

- superset version: Docker image preset/superset
- python version: 3.7

**Comment by dpgaspar** [comment]
Hi,

test it with: `elasticsearch+http://<ES_HOST>:9200/?verify_certs=False`

For more connection parameters checkout:
https://elasticsearch-py.readthedocs.io/en/master/transports.html#requestshttpconnection

**Comment by mbachtell** [comment]
Thank you!  That was the missing piece.

**Comment by sarcoex** [comment]
for me i used https and the verify_certs=false
