### ISSUE TITLE
Multi-line chart updates based on the previous, not the current query

### ISSUE THREAD

**Issue by irwvanroosmalen** [apache/incubator-superset#11465]
I have a multi-line chart based on two different datasources. On first load the chart displays. If I change the date range to a week and run a query -> result gives me the original date range. Then I change the date range to 2 weeks -> result gives me a week. Now if I change the range to day -> result gives me 2 weeks. So essentially the chart displays based on the previous query, not the current. Also re-running the query doesn't give me the correct result, it only works if I change the query

- superset version: 0.37.2
- python version: 3.6.12

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
I'm pretty sure this was fixed by https://github.com/apache-superset/superset-ui/pull/782

should go out in the upcoming release

**Comment by irwvanroosmalen** [comment]
@nytai you're right, thanks! When do you expect this to go out?

**Comment by nytai** [comment]
0.38 is currently in RC stage, so should be out in the next couple of weeks.
