### ISSUE TITLE
Edit dashboard metadata now throws Dashboard collision warning on save

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11477]
Currently after the recent fix to editing dashboard metadata and feature to prevent dashboard edit colisions, when you edit dashboard properties, even though the edits get saved, on the 2nd save on dashboard, user gets warning that "dashboard has been changed, please reload the page". Upon reloading the page, the changes are actually propagated, but this warning is confusing to the user. 

I know there are some plans to refactor the save flows on dashboards, so raising this bug so that it can be addressed at that time.

### Expected results

Do not show the warning when dashboard has been edited by the same user.

### Actual results

Warning about "dashboard has been edited, please reload" pops up.

#### Screenshots

1. Edit dashboard metadata, Click save on Modal
<img width="1233" alt="Screen Shot 2020-10-28 at 8 01 39 PM" src="https://user-images.githubusercontent.com/61221714/97521366-b0dda980-195a-11eb-9608-a75edbc6347b.png">

2. Click save on dashboard
<img width="643" alt="Screen Shot 2020-10-28 at 8 01 51 PM" src="https://user-images.githubusercontent.com/61221714/97521409-bd620200-195a-11eb-9b9f-54af91ecd4f7.png">

#### How to reproduce the bug

1. Go to Dashboard
2. Click on Edit, Edit Dashboard properties 
3. Edit some metadata - it can be changing color scheme, or editing directly specific color in the Json
4. Save on Modal - all OK
5. Save on Dashboard - the warning wrongly displays.

### Environment

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Related past discussions: 
https://github.com/apache/incubator-superset/issues/10655
https://github.com/apache/incubator-superset/pull/10834

**Comment by junlincc** [comment]
@graceguo-supercat 

we should definitely revisit the saving flow early next year!

**Comment by eschutho** [comment]
I believe this issue was fixed in https://github.com/apache/incubator-superset/pull/10834. I wasn't able to replicate with current master, but can someone else verify?

**Comment by mistercrunch** [comment]
I hit this issue recently too editing the title of the dashboard I believe. We should make sure that all actions except for the master SAVE only affect the local redux state, and that the save button be the only action that syncs to the backend.

**Comment by zuzana-vej** [comment]
Looks like @graceguo-supercat PR fixed this issue, thanks! (the dashboard doesn't automatically refresh though, but that's separate issue, I think that's been there before as well, from a while back).
