### ISSUE TITLE
Draggable area too small for chart resizing in dashboard edit mode

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11472]
### Expected results

Drag to resize while editting dashboards should be easy and pleasant to use.

### Actual results

Drag to resize charts in Dashboard edit mode has always been funky since there's no resize indicator and the draggable area is quite unpredictable.

For example, when a chart is the tallest in the row, only Area **c** (the little rectangle below the row) is draggable.

<img src="https://user-images.githubusercontent.com/335541/97508713-8d583600-193d-11eb-8ac4-af584c479260.png" width="500">

When chart is not the tallest, only the areas outside of the chart (**b** and **c**) are draggable . 

Ideally the draggable area should be within the chart container and will have a resize indicator when hovered.

BTW, not sure if it's intentional, but it seems recent changes to filter indicators also changed the box margins around hovered charts:

##### Before

<img src="https://user-images.githubusercontent.com/335541/97510943-1b82eb00-1943-11eb-900e-43d7ff933cc0.png" width="400">

##### After

<img src="https://user-images.githubusercontent.com/335541/97508215-49186600-193c-11eb-99e2-eea38e676bf6.png" width="400">

#### How to reproduce the bug

1. Go to a dashboard
2. Enter edit mode
3. Add a chart to a row and drag it to be the tallest in the row
4. Feel the different on the draggable areas

### Environment

[Current master branch](https://github.com/apache/incubator-superset/tree/18658f45be5c9d9c6df7824ea0f2f15b523c10d8)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I think the mystery pixel(s) around the charts are my fault... I'll try to address it one way or another. 

Story goes:
• We wanted charts to show a nice blue border as a highlight when a scoped filter is in focus. Easy, right?
• If you just _add_ the border with the highlight class, the box model changes, so the chart width/height changes, and stuff redraws. Ouch.
• So I added a `transparent` border around the charts as the default state. It was _supposed_ to be a secret. :P That way only the border-color changes, without triggering any layout recalculation.

**Comment by ktmud** [comment]
fixed by #11673
