### ISSUE TITLE
[Filter Box] date range filter is still misaligned in explore view

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11492]
## Screenshot

<img width="1297" alt="Screen Shot 2020-10-29 at 10 11 58 AM" src="https://user-images.githubusercontent.com/27990562/97613161-93015a80-19d5-11eb-9e69-a45c84f143ca.png">

## Description

Recently time-range filter UI was fixed in dashboard (Thanks!), but somehow still mis-aligned in explore view.

**Comment by junlincc** [comment]
yup saw it this morning too.. will get it fixed

**Comment by kgabryje** [comment]
Hi! PR https://github.com/apache/incubator-superset/pull/11487 will fix it.

**Comment by junlincc** [comment]
issue fixed via  #11487
