### ISSUE TITLE
Anyone can now edit anyone's chart

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11490]
### Expected results

Users should only be able to edit charts they created or own.

### Actual results

When you try to edit chart properties for a chart that you don't own, there is an error message:

<img src="https://user-images.githubusercontent.com/335541/97610097-ae6a6680-19d1-11eb-9518-c25dfc42decf.png" width="500">

But when you save an existing chart that you don't own, from the "Run/Save" button, you can proceed without any blocker:

<img src="https://user-images.githubusercontent.com/335541/97610323-f7221f80-19d1-11eb-911a-eda7fa3e8e1b.png" width="500">

Previously even thought the backend API may still pass, at least "Save (Overwrite)" is disabled on the frontend.

We need backend security check anywhere the charts may be updated.

#### How to reproduce the bug

See description

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

#11381 doesn't seem to be the cause of the bug but could be related.

cc @zuzana-vej @junlincc

**Comment by ktmud** [comment]
Could be #11335 

cc @nytai @lilykuang

**Comment by nytai** [comment]
It certainly could be due to that, superset's permissions can be really confusing. I'm not sure how this would result in the button no longer being greyed out as that's a frontend change (I would think). @ktmud do you know around when (or which commit) had the behavior with the greyed out/disabled option?

**Comment by graceguo-supercat** [comment]
frontend logic depends on the can_edit flag passed in bootstrap data.

**Comment by graceguo-supercat** [comment]
this is a very dangerous bug, right now everyone can accidentally overwrite chart that has no overwrite permission.

**Comment by willbarrett** [comment]
Fixed via revert.
