### ISSUE TITLE
docker-compose install fails

### ISSUE THREAD

**Issue by jvanulden** [apache/incubator-superset#11508]
When I install on Mac using docker compose the images don't load and the default dashboard is not displayed.

### Expected results

Default dashboard with sample data is displayed

### Actual results

No default dashboard and 404 errors to images reported in Javascript console.

#### Stacktrace

superset_app             | INFO:werkzeug:172.18.0.1 - - [31/Oct/2020 02:56:26] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | 172.18.0.1 - - [31/Oct/2020 02:56:26] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app             | INFO:werkzeug:172.18.0.1 - - [31/Oct/2020 02:56:26] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -

**Comment by dpgaspar** [comment]
Hi @jvanulden,

Please post the logs from the `init` procedure, use `docker logs superset_init`

**Comment by maxcapraro** [comment]
Hi @dpgaspar, 

I am experiencing he same issue as @jvanulden on Mac OS Catalina 10.15.7 with Docker version 19.03.13 (Docker Desktop 2.4.0.0).

I attached the logs of superset init.
[superset_init.log](https://github.com/apache/incubator-superset/files/5488232/superset_init.log)
