### ISSUE TITLE
can't login via iframe in chrome (working with firefox)

### ISSUE THREAD

**Issue by ronozoro** [apache/incubator-superset#11524]
Added iframe to my application to login with iframe

what you expected to happen.

the login should be process and move to welcome dashboard page (Working with Firefox)

what actually happens.

nothing. sames like the submit request is not reaching the server from the iframe

None 

#### How to reproduce the bug
1- create i frame in simple html page
2- try to open the page and login only with chrome .. working normal in firefox
3- nothing happen even if the password is not correct
#### Changes in Config.py : 
SESSION_COOKIE_NAME = 'supeset_session'
SESSION_COOKIE_HTTPONLY = False  # Prevent cookie from being read by frontend JS?
SESSION_COOKIE_SECURE = False  # Prevent cookie from being transmitted over non-tls?
SESSION_COOKIE_SAMESITE = 'None'  # One of [None, 'Lax', 'Strict']
WTF_CSRF_ENABLED = False
PUBLIC_ROLE_LIKE_GAMMA = True
DEFAULT_HTTP_HEADERS: Dict[str, Any] = {}
OVERRIDE_HTTP_HEADERS: Dict[str, Any] = {}
HTTP_HEADERS: Dict[str, Any] = {}
#### Env : 
CentOS server
Iframe and parent application have different domains and i don't use any reverse proxy

(please complete the following information):

- superset version: `0.37.2`
- python version: `3.6`
- node.js version: `6.17.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ yes] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ yes] I have reproduced the issue with at least the latest released version of superset.
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

If the iframe and the parent application are using the same domain, it works in chrome

**Comment by lunch4jack** [comment]
the issue is rooted here - https://blog.heroku.com/chrome-changes-samesite-cookie
**disabling** 'SameSite by default cookies' using **_chrome://flags_** on Chrome browser is a temporary solution.

**Comment by ronozoro** [comment]
Yes, it was samesite problem and with samesite cookie you have to enable ssl 👍

**Comment by binodyadav6119** [comment]
HI @ronozoro what changes needed to be done to resolve above issue
