### ISSUE TITLE
Fail to load "Explore Chart" views using slice ids  in superset 0.38.0.rc2

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#11534]
I am testing the new version superset 0.38.0.rc2 and I have issues loading charts in the "Explore Chart" view. 

When I "explore" a table, it works well, and I can see in the URL the all options are passed (form_data, query_fields .... )
It also works for Big Number, Big Numbers with trendlines 

When I try to "explore" a line chart, a map ... I get an empty view. I notice it fails when the chart is specified by its slice_id in the url (e.g ` superset/explore/?form_data=%7B"slice_id"%3A1676%7D `). 

<img width="1284" alt="Screenshot 2020-11-03 at 12 50 13" src="https://user-images.githubusercontent.com/607430/97981804-20c4b780-1dd3-11eb-9606-38f27359b2c2.png">

In the console log I have the following errors: 
<img width="1098" alt="Screenshot 2020-11-03 at 12 50 59" src="https://user-images.githubusercontent.com/607430/97981875-3afe9580-1dd3-11eb-9010-74f425de22e2.png">

**Comment by bryanck** [comment]
Same problem here, getting `TypeError: Cannot read property 'id' of undefined` when loading a chart in the Chart editor, either from the "Explore chart" menu item on a dashboard, or simply from the "Charts" list. This happens with most chart types, except tables seem to be OK.

**Comment by bryanck** [comment]
This may be a backwards compatibility issue. If I create a brand new chart, then I don't seem to have this issue, it seems to happen only for charts that were created before 0.38rc2.

**Comment by villebro** [comment]
Might have something to do with default control state. Let me look into this.

**Comment by villebro** [comment]
I was finally able to reproduce 👍  Investigating

**Comment by villebro** [comment]
I have now identified the necessary fix, will start working on rc3 shortly.

**Comment by villebro** [comment]
@lilila @bryanck feel free to try out the pre-release of rc3: https://github.com/apache/incubator-superset/commits/0.38

**Comment by lilila** [comment]
@villebro it works well, you are the best!

**Comment by bryanck** [comment]
Appears to be fixed for me as well!

**Comment by junlincc** [comment]
Thank you Ville! @villebro closing this issue! 

@mistercrunch FYI

**Comment by villebro** [comment]
Awesome, thanks for confirming @lilila and @bryanck !
