### ISSUE TITLE
[dashboard filter indicator] Dashboard does not apply filter

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11542]
#### How to reproduce the bug

1. create dashboard with filters
2. open dashboard
3. open filter status, click on one of the filter field and dashboard will focus on that filter_box
4. choose a value from filter_box and click Apply

### Actual results
- Filter status disappeared
- Dashboard does not apply the selected filter

#### Screenshots

![OdvFraw0tQ](https://user-images.githubusercontent.com/27990562/98059199-64cbb280-1dfb-11eb-90d5-e2a6ef2c6b3b.gif)

### Environment

lastest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @junlincc @suddjian

**Comment by junlincc** [comment]
![ezgif-4-50cd9158b2ac](https://user-images.githubusercontent.com/67837651/98060088-9e9db880-1dfd-11eb-8d72-c02b90f06b59.gif)

I'm seeing the same behavior. @suddjian please give a quick fix, thanks!

**Comment by suddjian** [comment]
I am still working to find the source of this issue, but so far I have confirmed that it was not introduced with the new filter indicators. See recording:

![Screen Recording 2020-11-03 at 8 09 46 PM](https://user-images.githubusercontent.com/1858430/98068595-525c7380-1e11-11eb-9942-7d3b3881dfee.gif)

**Comment by suddjian** [comment]
The `TRIGGER_QUERY` action is firing correctly, but `componentDidUpdate` of `Chart.jsx` is not firing for some reason.

**Comment by rusackas** [comment]
I haven't fully diagnosed this yet, but if you delete the `shouldComponentUpdate` in `/src/dashboard/components/gridComponents/Chart.jsx` (or just `return true` at the top, the problem is gone.

**Comment by suddjian** [comment]
Nice! To narrow this down a little more, if you remove the this check from `shouldComponentUpdate`, it works

```
if (nextProps.mountedParent === null) {
  return false;
}
```
