### ISSUE TITLE
[Explore]multiple cosmetic issues in Explore popover (metrics, filters)

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11546]
![ezgif-7-88e7dc0f4ce5](https://user-images.githubusercontent.com/67837651/98078856-bb4ee600-1e27-11eb-9a4b-ce82d5678e4b.gif)

1. Text area  and buttons overlap 
Text area should have a smaller fixed height, scroll bar should stay within the text area

2. Save and Close button 
Save should be on the right, Close on the left 

3.  Resize icon 
shrink icon and enough spacing between icon and button

**Comment by junlincc** [comment]
@kgabryje 🙏

**Comment by rusackas** [comment]
@junlin I think we're good here, but I'll let you verify on master :)

Also surprised GH doesn't automatically close issues when the PR says "Fixes #xyz"

**Comment by nytai** [comment]
@rusackas The fixes syntax works only when it's in the title, commit message, or description. You can also link the issue with the little widget on the right. 

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by rusackas** [comment]
I did it in the description not long ago and it didn't seem to work there. I've never tried the manual linking widget... will do next time for fun :D

**Comment by junlincc** [comment]
all looking good! we can finally move on from popover!! 😆
