### ISSUE TITLE
Permission mess up after upgrading

### ISSUE THREAD

**Issue by blcksrx** [apache/incubator-superset#11549]
After upgrading the superset we go an issue with permissions that are messed up and users cant do their jobs with their permissions. It is important to have some integration test about upgrading to avoid such this issue.

### Environment
Superset mater branch
python 3.7

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
@blcksrx, please fill the bug issue template, don't forget to identify from what version you were upgrading from at to what version (or master SHA) you upgraded to. Also identify what permissions got messed up
