### ISSUE TITLE
[Chart]Histogram chart legend overflow 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11543]
<img width="1778" alt="Screen Shot 2020-11-03 at 6 52 46 PM" src="https://user-images.githubusercontent.com/67837651/98063891-e88a9c80-1e05-11eb-93de-cf2f69e33369.png">

#### How to reproduce the bug

1. Create a Histogram Chart in Explore 
2. Choose numeric columns
3. Choose group by columns
4. run.....

### Environment

latest master

**Comment by junlincc** [comment]
@kkucharc not top priority, get to it whenever you can. 🙏

**Comment by mayurnewase** [comment]
@junlincc this was fixed here -> https://github.com/apache-superset/superset-ui/pull/863

**Comment by junlincc** [comment]
@mayurnewase awesome! i was told that was not easy. 🙏
