### ISSUE TITLE
[Explore]control panel and chart area shift up after changing data viz type

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11541]
### Actual results
![ezgif-2-5c77e52bd5cc](https://user-images.githubusercontent.com/67837651/98057595-8034be80-1df7-11eb-8b21-a70c12424099.gif)

chart titles and all buttons are out of the view 

1. Open any chart in Explore
2. Change VISUALIZATION TYPE
3. Run query

### Environment
latest master

**Comment by junlincc** [comment]
@kgabryje could it due to the tab refactoring?

**Comment by rusackas** [comment]
> @kgabryje could it due to the tab refactoring?

I think it's the Modal, actually.

**Comment by junlincc** [comment]
> > @kgabryje could it due to the tab refactoring?
> 
> I think it's the Modal, actually.

thanks for the diagnosis! @kgabryje this is top priority 🙏

**Comment by kgabryje** [comment]
On it

**Comment by junlincc** [comment]
tested, it's all fixed! thank you both @kkucharc @kgabryje
