### ISSUE TITLE
g

### ISSUE THREAD

**Issue by yasser3399** [apache/incubator-superset#11556]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment]
What is this?

**Comment by mistercrunch** [comment]
The title reminded me of one of my favorite french cartoon character, le "concombre masqué"!
![comconbre](https://user-images.githubusercontent.com/487433/98173400-eb3dce00-1ea7-11eb-9d90-7e434052f006.jpg)
