### ISSUE TITLE
Recent Activity page is blank

### ISSUE THREAD

**Issue by guhan** [apache/incubator-superset#11568]
If you click on User settings (icon on top right) --> Profile and then navigate to the Recent Activity tab the page is blank. 
![Screenshot 2020-11-04 171027](https://user-images.githubusercontent.com/3980678/98185117-dc174a00-1ec0-11eb-9e5c-354c14bd0f40.png)
![Screenshot 2020-11-04 171146](https://user-images.githubusercontent.com/3980678/98185119-dcafe080-1ec0-11eb-9fee-4c9e0496f459.png)

**Comment by nytai** [comment]
This should be fixed by https://github.com/apache/incubator-superset/pull/11481 

@guhan if you're seeing this in a preset environment, we disabled the logs table so the activity page will always be blank

**Comment by willbarrett** [comment]
Closing as resolved.
