### ISSUE TITLE
Bump the height in MetricPopover to prevent the tiny scollbar

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11563]
## Screenshot

<img width="481" alt="Screen Shot 2020-11-04 at 3 37 38 PM" src="https://user-images.githubusercontent.com/487433/98179496-bf284a00-1eb3-11eb-9829-fbcdf1b8eeb5.png">

## Description

See title, no need for a scollbar for 10-20 pixels in a popover!

**Comment by junlincc** [comment]
closing this issue as new layout is available in latest master
