### ISSUE TITLE
[Chart]Echarts pie chart quirks in 0.38

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11562]
Describe the bug
There remain some quirks in the new Echarts-based pie chart.

If label lines are turned on and there is no label, e.g. the label is disabled for the slice because it doesn't meet the percent threshold, you have lines coming off the slices with no associated text.

The chart layout isn't automatic with the legend. If you want to fit the legend, you have to manually resize the pie chart smaller so the legend will fit. With the legend showing, the chart isn't shifted down vertically to use the unused whitespace. The chart thus needs to be smaller than before with the legend showing.

Screenshots

Example of 1st item:

![1](https://user-images.githubusercontent.com/67837651/98176205-f34c3c80-1eac-11eb-992c-2f8a85e5f479.png)

Example of 2nd item:

In 0.37 the chart size and layout was automatic and would fill available whitespace.
![2](https://user-images.githubusercontent.com/67837651/98176224-f9dab400-1eac-11eb-825e-d7d3b75a0f6c.png)

In 0.38, you need to manually size the chart to fit available white space. Also, the chart layout doesn't shift down to accomodate the legend.
![3](https://user-images.githubusercontent.com/67837651/98176238-fe06d180-1eac-11eb-8c89-839b9db46259.png)

cc @bryanck 
@eugeniamz

**Comment by Giphyn-nehboh-5qonhu** [comment]
@Hos_144

**Comment by villebro** [comment]
I looked into disabling individual lines when adding the threshold parameter, but it appears it can currently only be defined for all slices under the `series.labelLine` property. I believe we'd need to make it possible to pass a callback to `labelLine` that enables/disables it per slice, similar to how `label.formatter` currently works. At any rate the change would need to be done in ECharts.

Similarly, automatic resizing of the chart based on the legend size is currently not supported. However, I understood that the core ECharts committers are considering adding this feature in an upcoming release.

I would almost propose opening tickets on the ECharts GitHub repo, so we can continue the discussion and coordinate fixing these issues there.

**Comment by junlincc** [comment]
the more i think about this .. the more i want to hide all legend by default...

**Comment by junlincc** [comment]
new Echarts pie chart is available! check outhttps://github.com/apache-superset/superset-ui/pull/852 
closing this issue
