### ISSUE TITLE
Standalone Plots are Blank

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#11577]
In version 38.0.rc2 standalone plots are blank, I noticed the iframe links are now shortened but it is not the problem whenever I remove the tag ` standalone= True`  plots display well in iframes (within the explore chart window).

**Comment by villebro** [comment]
Did you try with the latest cherries on the `0.38` branch? I think this is related with the Explore regression in `0.38.0rc2`. I tried to repro with `0.38.0rc3` but it seems to work fine.

**Comment by villebro** [comment]
I was able to reproduce the problem in `0.38.0rc2` and can confirm that the bug is fixed in `0.38.0rc3` 👍  Closing.

**Comment by lilila** [comment]
Cool Thank you
I tried again and it worked, sorry

**Comment by villebro** [comment]
No harm done, on the contrary, thanks for testing! 🙏

**Comment by lilila** [comment]
@villebro I do not understand what is going on, sometimes it works sometimes it doesn't :/ 

When I inspect source when the plot is blank I have the following error
<img width="976" alt="Screenshot 2020-11-06 at 09 28 15" src="https://user-images.githubusercontent.com/607430/98343645-68855200-2012-11eb-9007-6671b1a02739.png">

If I click on the link I get: 
<img width="918" alt="Screenshot 2020-11-06 at 09 28 46" src="https://user-images.githubusercontent.com/607430/98343692-7aff8b80-2012-11eb-8023-44779cbfc101.png">

**Comment by villebro** [comment]
@lilila is the same chart always failing in standalone mode, or does it work occasionally?

**Comment by lilila** [comment]
I got it, it works with Chrome but is blank on Safari! 
This Isi why I had the impression it works sometimes

**Comment by villebro** [comment]
Would you mind opening a new ticket for this bug with detailed reproduction steps?

**Comment by lilila** [comment]
Yes, I will do it this week end, thank you

**Comment by lilila** [comment]
I still have this issue. 
If I open a plot on Safari in explore chart mode, it works well.  
<img width="1569" alt="Screenshot 2021-06-08 at 06 48 17" src="https://user-images.githubusercontent.com/607430/121124822-d7838d00-c825-11eb-8448-2912b9a7912e.png">
If I open the same chart in Standalone mode I get an empty page  : 
<img width="1568" alt="Screenshot 2021-06-08 at 06 51 44" src="https://user-images.githubusercontent.com/607430/121124958-0e59a300-c826-11eb-8ac2-420bd19247ba.png">
