### ISSUE TITLE
[Dashboard-Filter-Indicator] Chart title is covered by new filter indicator 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11582]
we recently implemented new dashboard filter indicator to replace the old "teeth" design, with the purpose of providing better simplicity and improving consistency in dashboard. 

Main changes as follow:
- State A No Filters Scope When no filters are scoped on the chart, there is no indicator 
- State B Filters Scoped, Not Applied When there are no applied filters, the indicator is just the filter icon 
- State C Filter Applied When filters are applied, the indicator shows the number of applied filters
- State D Some Incompatible Filters When there are incompatible filters, the indicator turns yellow and shows applied filters as well as incompatible filters. 
<img width="1425" alt="Screen Shot 2020-11-05 at 10 46 12 AM" src="https://user-images.githubusercontent.com/67837651/98283225-2a295d80-1f54-11eb-8947-8634b35a8244.png">

As we moved the indicator inside of the chart area, one minor change we made is we applied fixed height and width on the chart title to avoid title and indicator overlapping and to create better visual alignment. 

This minor change has caused some usability problems to users whose charts have long titles. Chart titles can't be entirely shown in this implementation. We are working on the enhancement currently, and as the PM of this project, I apologize for all the inconvenience.

**Comment by junlincc** [comment]
@etr2460 @graceguo-supercat

**Comment by graceguo-supercat** [comment]
the chart options list icon should use vertical dot not horizontal dot. please update your design doc to reflect reality.
