### ISSUE TITLE
SQL search `query search string` shouldn't be case sensititive

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#11585]
## Screenshot
N/A

## Description
Right now whenever users search for queries they are case sensitive. We should remove this to allow users to put in term with any cases

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by Giphyn-nehboh-5qonhu** [comment]
https://t.me/Hos_144

**Comment by willbarrett** [comment]
@nytai @dpgaspar this might be good to address in the new Query Search system.

**Comment by nytai** [comment]
I believe it's case insensitive, I'll double check though

**Comment by nytai** [comment]
Yup, should be fixed when ☝️ is merged and released
