### ISSUE TITLE
[Landing page] Recent section links don't work

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11588]
#### How to reproduce the bug

1. open Superset homepage
1. Click on any item in Recent section

### Expected results

Dashboard or chart open in the new tab.

### Actual results

Nothing happened.

#### Screenshots

<img width="1346" alt="Screen Shot 2020-11-05 at 1 59 44 PM" src="https://user-images.githubusercontent.com/27990562/98304675-48ec1c00-1f75-11eb-8061-ae5fd668dc0a.png">

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @benceorlai

**Comment by pkdotson** [comment]
should be cleared up when this pr is merged in: https://github.com/apache/incubator-superset/pull/11557

**Comment by junlincc** [comment]
tested, it's fixed! also, the entire card is clickable.
