### ISSUE TITLE
[Explore]control panel popover can't be saved

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11598]
![ezgif-7-107a12e9c510](https://user-images.githubusercontent.com/67837651/98338331-e3bd1880-1fbe-11eb-9d96-c3b8f7ae4417.gif)

started happening after #11578 is merged

**Comment by junlincc** [comment]
@kgabryje 🙏

**Comment by kgabryje** [comment]
@junlincc On it. By the way, it seems that the bug was there before, I just checked  the master before https://github.com/apache/incubator-superset/pull/11578 and it doesn't work too.

**Comment by junlincc** [comment]
> @junlincc On it. By the way, it seems that the bug was there before, I just checked the master before #11578 and it doesn't work too.

got it! thanks for clarifying it and the quick fix! please see https://github.com/apache/incubator-superset/issues/11608

**Comment by kgabryje** [comment]
@junlincc This PR fixes https://github.com/apache/incubator-superset/issues/11608 as well, sorry for that regression.
