### ISSUE TITLE
where should the discussion for the SIP take place ?

### ISSUE THREAD

**Issue by s1aw1k** [apache/incubator-superset#11595]
where should the discussion for the SIP take place ? 
I believe, it could be either the dev list or the SIP issue itself. 
- doing@fggfcff on the dev list would make be easier for people not following the SIP issue itself to follow the discussion. 

- __Originally posted by @nishantmonu51 in https://github.com/apache/incubator-superset/issues/5602#issuecomment-433194906__

**Comment by mistercrunch** [comment]
On GitHub, and notification about it should be sent to the `dev@` mailing list as a `[DISCUSS]` thread, as touched in SIP-0

> Notify the dev@ mailing list that the SIP has been created, use the subject line [DISCUSS] SIP-0 Superset Improvement Proposals, the body of the email should look something like Please discuss & subscribe here: https://github.com/apache/incubator-superset/issues/5602
