### ISSUE TITLE
Filter indicator popover cuts off selected filters

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#11591]
## Screenshot
![image](https://user-images.githubusercontent.com/7409244/98306515-dda44900-1f78-11eb-96e5-a8c5e9dca6f4.png)

## Description
The filter indicator popover cuts off the selected filters, making it harder to know what filters are selected.

## Design input
The popover should either wrap the selected filter text, or expand to fit the full selected filter

to: @suddjian

**Comment by suddjian** [comment]
should have a PR for this in a few minutes
