### ISSUE TITLE
[Date Picker] Custom date behavior is not consistent

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11601]
#### Screenshots

![lGBvre47mm](https://user-images.githubusercontent.com/27990562/98339278-4f53b580-1fc0-11eb-983f-68e1e30b52c0.gif)

#### Expected Behavior

- Find the right user input.
- CUSTOM start/end date should always automatic updated when user set DEFAULTS or relative section
(this is old behavior before recent changes)

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
we noticed this issue as well but have not been able to reproduce it consistently. will looking into it!
