### ISSUE TITLE
TimeRangeFilter popover bugs + cosmetic

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#11609]
## Screenshot

<img width="257" alt="Screen Shot 2020-11-06 at 2 21 36 PM" src="https://user-images.githubusercontent.com/487433/98420202-861ae180-203b-11eb-9567-1e62da3e0d98.png">

<img width="515" alt="Screen Shot 2020-11-06 at 2 16 27 PM" src="https://user-images.githubusercontent.com/487433/98420014-28869500-203b-11eb-8580-a9db6d3878d1.png">

## Description

There's a bug with the filter not saving when writing a date as in custom time filter. You'll just hit "Ok" and the change doesn't take effect.

+ Calendar dropdown forces a scroll, wondering if we should change the height or get it to overflow over the popover (?)

**Comment by rusackas** [comment]
@kgabryje has been working on similar issues, and can likely tackle this one, too.

**Comment by mistercrunch** [comment]
Also reported here https://github.com/apache/incubator-superset/issues/11601

**Comment by junlincc** [comment]
looking good from my end. closing 
<img width="535" alt="Screen Shot 2020-11-09 at 6 35 45 PM" src="https://user-images.githubusercontent.com/67837651/98620614-76f59700-22ba-11eb-93b4-692be3751b83.png">
