### ISSUE TITLE
caravel filter views returns invalid data

### ISSUE THREAD

**Issue by flyfatasy** [apache/incubator-superset#1161]
I have a table in druid named activate_andes. Below is the 
https://pan.baidu.com/s/1nuBrBzN
when I choose visualize type to filter, It looks like this.
https://pan.baidu.com/s/1nv8PXIL
When I deep into the http response, I found this:
{"filter": "activate_type", "text": 1473004800000, "metric": "reinstall", "id": 1473004800000}]

Why text is not the concrete value of activate_type other than timestamp? Why metric is not the value but the  activate_type?
-

**Comment by flyfatasy** [comment]
Anyone can dealing this? Thank you very much.

**Comment by xrmx** [comment]
which version of caravel is this? if not master please try again against master.

**Comment by flyfatasy** [comment]
The latest version. 0.10.0

**Comment by flyfatasy** [comment]
The latest version. 0.10.0

**Comment by flyfatasy** [comment]
Installed by pip install caravel.

**Comment by flyfatasy** [comment]
@xrmx  what should i do to validate this issue?

**Comment by xrmx** [comment]
@flyfatasy i've asked if you can reproduce the same issue on master.
You can build master by doing a git clone of the repo and then following these instructions:
https://github.com/airbnb/caravel/blob/master/docs/installation.rst#making-your-own-build

**Comment by flyfatasy** [comment]
@xrmx  recently I installed 0.11.0  and the same problem still exists. 
You can easily reappear this by applying filter type to a druid database.
Hope this problem can be solved as soon as possible.

**Comment by flyfatasy** [comment]
I installed caravel by pip install caravel. https://pypi.python.org/pypi/caravel
Last time the version is 0.9.0 and later I tried 0.10.0 and now I tried 0.11.0. The problem stays the same.

**Comment by flyfatasy** [comment]
So this problem should not be waitting for validation. It is certainly a problem.
