### ISSUE TITLE
Not able to email dashboards in superset

### ISSUE THREAD

**Issue by i4vijay** [apache/incubator-superset#11620]
I have installed superset in AWS EC2 instance which is Ubuntu. It is working fine but i have a requirement to send dashboards in email to clients. I have configured SMTP, chrome browser, chromedriver, Redis and also made correct changes to config.py file. I am able to run celery worker, celery beat but if i try to send test email i am getting **UnboundLocalError: local variable 'options' referenced before assignment** in celery worker. This is so frustrating in superset. Why is it so difficult to enable this option in superset? 
![image](https://user-images.githubusercontent.com/36433544/98555424-c6a27700-2256-11eb-8d6a-7bd1cf742325.png)
Also I tried with firefox and geckodriver and facing the same issue. All required installation are in correct path variable.
Either i get the above error or  **devtoolsactiveport file doesn't exist** error.

**What am i missing here? What is the correct way to enable email scheduling in AWS EC2 instance(Ubuntu)?**
**Did anybody faced the same issue? If so can someone please help me fix this issue**

**Comment by willbarrett** [comment]
I'm sorry, I can't help you fix this issue immediately. I can tell you that the Email Reports and Alerts functionality in Superset is currently undergoing a ground-up rewrite. We hope to provide a better experience in a future version. Neither of these features was truly ready for prime-time, and we're going to be substantially improving the quality here in the near future.

**Comment by i4vijay** [comment]
That good to hear. Thanks for the update.
