### ISSUE TITLE
[filter indicator] when chart title has line wrap

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11628]
## Screenshot

<img width="1323" alt="Screen Shot 2020-11-09 at 2 39 38 PM" src="https://user-images.githubusercontent.com/27990562/98605403-30904000-229a-11eb-8b0a-38657b0c77d7.png">

## Description

Filter status indicator should not change shape.

@junlincc @rusackas

**Comment by junlincc** [comment]
we caught it this morning and fix is coming

**Comment by rusackas** [comment]
PR Opened: https://github.com/apache/incubator-superset/pull/11631

**Comment by junlincc** [comment]
<img width="133" alt="Screen Shot 2020-11-09 at 5 14 05 PM" src="https://user-images.githubusercontent.com/67837651/98615242-fda47700-22ae-11eb-96e1-71e871bc3abb.png">
looking good!
