### ISSUE TITLE
[dashboard]menuItems antd component regression

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11645]
![98725736-6260df80-234a-11eb-8db5-4b0167d8bd8a](https://user-images.githubusercontent.com/67837651/98726608-94bf0c80-234b-11eb-8236-b8e95e1e9166.gif)

Previously the menu will automatically close whichever item you click, now it doesn't close.
 cc @kgabryje @ktmud

**Comment by ktmud** [comment]
Ref: https://github.com/apache/incubator-superset/pull/11554

Btw, @kgabryje ,  it would be nice if future PRs have more specific titles on the scope of their changes. I'm currently seeing three PRs with identical PR title. It's hard to tell which is which.

![image](https://user-images.githubusercontent.com/335541/98727753-49a5f900-234d-11eb-9553-cc962de10576.png)

**Comment by kgabryje** [comment]
@ktmud Got it, sorry for confusion.
