### ISSUE TITLE
Markdown's top menu is not visible

### ISSUE THREAD

**Issue by kkucharc** [apache/incubator-superset#11642]
Markdown's popup menu is hovered by a tab's header.

### Expected results

<img width="345" alt="Screenshot 2020-11-10 at 14 27 57" src="https://user-images.githubusercontent.com/2536609/98708823-e2566c00-2381-11eb-9df7-f937800e4a3e.png">

### Actual results

<img width="350" alt="Screenshot_2020-11-10_at_12_15_01" src="https://user-images.githubusercontent.com/2536609/98708853-eaaea700-2381-11eb-9869-1cd7ec359a80.png">

#### How to reproduce the bug

1. Go to a new dashboard
2. Add a tab to the dashboard
3. Add markdown to the tab
4. Click on the markdown to edit

### Environment

(please complete the following information):

- superset version: `superset version` 0.999.0dev
- python version: `python --version` Python 3.7.8
- node.js version: `node -v` v12.18.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kkucharc** [comment]
cc: @junlincc

**Comment by kkucharc** [comment]
cc: @kgabryje can you take a look?

**Comment by kgabryje** [comment]
Ok

**Comment by junlincc** [comment]
<img width="936" alt="Screen Shot 2020-11-16 at 8 11 30 AM" src="https://user-images.githubusercontent.com/67837651/99277980-5b6f1c80-27e3-11eb-9143-6c48cf62981d.png">

looking good~ closing
