### ISSUE TITLE
[Nav] Menu item height in Settings menu looks kind of random

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11651]
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/98748336-48d18f00-236e-11eb-884f-bc734f4cf152.png" width="200">

## Description

1. There should be more space around dividers
2. There should be space between the bottom and the last menu item

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by kgabryje** [comment]
@ktmud Do you think that looks better? I decreased margin for item group title and increased margin for the last element of item group.
![image](https://user-images.githubusercontent.com/15073128/99058035-e6120a80-259c-11eb-8c05-acf891267c6e.png)

**Comment by ktmud** [comment]
Looks good! Thanks for taking on this.
