### ISSUE TITLE
Filter Box Default Value Issue

### ISSUE THREAD

**Issue by GiannisDimitriou** [apache/incubator-superset#11664]
After adding/removing a default value in filter configuration an empty value appears on the dropdown list in dashboard

#### Screenshots

No Default Value
![image](https://user-images.githubusercontent.com/47314887/98937667-68dc8c00-24ef-11eb-8859-6615bc901c05.png)

Add a default value
![image](https://user-images.githubusercontent.com/47314887/98937707-7a259880-24ef-11eb-92a8-e178c1bc8eb9.png)

Remove the default value
![image](https://user-images.githubusercontent.com/47314887/98937740-84e02d80-24ef-11eb-95f0-ac37584e7954.png)

#### How to reproduce the bug

1. Create a filter box chart, add any column in filters and save it on a dashboard
2. Modify the filter configuration and add a default value
3. Refresh the dashboard and make sure the default value appears on the filter
4. Modify the filter configuration again and remove the default value
5. Refresh the dashboard again
6. An empty value selection appears at the top of the dropdown list

### Environment

- superset version: 0.37.2

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/10687 supposed to fix this issue by 0.37.2, but I'm still seeing it happen in master.

**Comment by willbarrett** [comment]
Closing as resolved, please re-open if the issue continues.

**Comment by OKSUchun** [comment]
I still have the same problem as @willbarrett. Does anyone know why it keeps recurring?

**Comment by juanmantelli** [comment]
same here
