### ISSUE TITLE
[dashboard] Can not remove row inside Tab

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11681]
In dashboard, user can not remove a Row component inside a Tab component. But if Row is added without Tab, it could be removed.

#### Screenshots
![MQc0JjOP2y](https://user-images.githubusercontent.com/27990562/99008833-c8d92f80-24fb-11eb-896c-540cd4354936.gif)

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Cause by #11160. CC @kgabryje  @junlincc @zuzana-vej  this is a high priority issue.

**Comment by junlincc** [comment]
got it

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/11691 @graceguo-supercat ready for you review, 8 hours from reporting, not too bad right? 😉

**Comment by junlincc** [comment]
<img width="1395" alt="Screen Shot 2020-11-16 at 8 06 40 AM" src="https://user-images.githubusercontent.com/67837651/99277512-bbb18e80-27e2-11eb-9c08-92994c793fdc.png">
tested all good. closing

fix by [#11691 ](https://github.com/apache/incubator-superset/pull/11691)
