### ISSUE TITLE
https://github.com/apache/incubator-superset not containes superset-frontend/src/visualizations/CountryMap/countries

### ISSUE THREAD

**Issue by zsellami** [apache/incubator-superset#11690]
Hello,

I want to add new countries in the country map tools.
The official documentation give a procedure to do that in https://superset.apache.org/docs/miscellaneous/country-map-tools

But I don't retrieve the folder **superset-frontend/src/visualizations/CountryMap/countries** and the file **superset-frontend/src/explore/controls.jsx** in the official github of the project.

How to do it ? I want to use the official github not a forke of the project

Regards
Zied Sellami

**Comment by zufolo441** [comment]
Hi,
maps are now in 
superset-frontend/node_modules/@superset-ui/legacy-plugin-chart-country-map/esm/countries/
you have to add them to index file:
superset-frontend/node_modules/@superset-ui/legacy-plugin-chart-country-map/esm/countries.js 
and in listbox:
superset-frontend/node_modules/@superset-ui/legacy-plugin-chart-country-map/esm/controlPanel.js
and then recompile launching:
npm run dev 
from 
superset-frontend 
folder.
