### ISSUE TITLE
[Table Viz] Duplicate Columns (Percentage Metric)

### ISSUE THREAD

**Issue by GiannisDimitriou** [apache/incubator-superset#11697]
Whenever the name of the Percentage Metric is the same as the name of the Sort By column then a duplicate column for the Percentage Metric appears

Workaround:
Change the column name of the Percentage Metric field

#### Screenshots

![image](https://user-images.githubusercontent.com/47314887/99083312-0b6b3c80-25ce-11eb-959d-6fc12f904c80.png)

#### How to reproduce the bug

1. Create a Table Viz
2. Add the same column in Percentage Metric & Sort By fields

### Environment

- superset version: 0.37.2

**Comment by junlincc** [comment]
thanks for reporting! we prioritize issues based on their severity, we may take a couple weeks to get to this one.

**Comment by lilila** [comment]
@GiannisDimitriou , as a quick workaround you can simply add a label to the sort field. 

1. Duplicate columns
<img width="864" alt="Screenshot 2020-11-15 at 06 38 34" src="https://user-images.githubusercontent.com/607430/99177830-6e172200-270d-11eb-8d94-ea9b1eaa0c93.png">

2. Add label to the field you want to use to sort 
<img width="863" alt="Screenshot 2020-11-15 at 06 38 55" src="https://user-images.githubusercontent.com/607430/99177846-8e46e100-270d-11eb-9c77-e5928f07f885.png">
 
3. "fixed"
<img width="869" alt="Screenshot 2020-11-15 at 06 39 07" src="https://user-images.githubusercontent.com/607430/99177850-9acb3980-270d-11eb-9770-e27cc30256ed.png">
