### ISSUE TITLE
Disable authentication in Superset

### ISSUE THREAD

**Issue by prb219** [apache/incubator-superset#11699]
Hi, 
I have been trying to to disable authentication from Superset as it is redundant in our situation. So far I have tried setting the below fields in the superset config file but it does not solve the issue. 

_PUBLIC_ROLE_LIKE_GAMMA = True
AUTH_ROLE_PUBLIC = 'Public'_
 
Can someone please guide me on this?

Superset version in use: 0.37.2

**Comment by willbarrett** [comment]
Superset requires user-based access roles to function. You could investigate creating a custom implementation of the SecurityManager class in order to integrate with your existing auth provider, but Superset does not support an authentication-less deployment.
