### ISSUE TITLE
Druid metadata cannot be retrieved when the whole dataset has the same timestamp

### ISSUE THREAD

**Issue by edevil** [apache/incubator-superset#1171]
My dataset has no notion of time, so when I ingested it into Druid I added a mock timestamp to all rows, as suggested in the tutorial (http://druid.io/docs/latest/tutorials/tutorial-batch.html).

Caravel tries to obtain the last segment of data for the druid metadata and works backwards from the max time. Since everything has the same date, no data is returned so no metadata is retrieved.

**Comment by optossav** [comment]
I've noticed the same issue with single day data sets.
