### ISSUE TITLE
[dashboard]filter mapping modal cosmetic issues

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11721]
<img width="693" alt="Screen Shot 2020-11-16 at 2 24 28 PM" src="https://user-images.githubusercontent.com/67837651/99315874-38ab2b00-2818-11eb-84af-600a05156cfe.png">

1. checkbox and label alignment 
2. line overflow 
3. "Collapse all" and Search bar overlap - move search bar to separate line maybe?
4. section divider 
5. button position - move both to the bottom right, change "CLOSE" to "CANCEL"

**Comment by junlincc** [comment]
<img width="1788" alt="Screen Shot 2020-11-18 at 8 04 42 AM" src="https://user-images.githubusercontent.com/67837651/99558275-69a27180-2978-11eb-86a0-895c6b470650.png">

tested, a bit too wide but is looking neat! thanks for the fix @kgabryje !!

**Comment by kgabryje** [comment]
Regarding the width, that's how it was before - 80% of screen width. Do you think we should make it a bit narrower?

**Comment by junlincc** [comment]
i think we are good for now, we are rolling out a new native configuration modal soon:) also wide modal can be good for long titles.
