### ISSUE TITLE
Jinja Templated queries not working in master branch code

### ISSUE THREAD

**Issue by abhishekkumaresan** [apache/incubator-superset#11734]
A jinja templated query is not working in superset compiled from source but is working in 0.36 version of pip installed superset

Python version:- 3.7
OS: Ubuntu 20.04
Superset Version master branch code and 0.36

I am adding  screenshots for reference. 

![dev_version](https://user-images.githubusercontent.com/10154985/99498100-ed6e5500-299c-11eb-82d4-45559de181fd.png)
![0_36](https://user-images.githubusercontent.com/10154985/99498134-f7905380-299c-11eb-9320-946f9b5fbfa8.png)

**Comment by nytai** [comment]
@abhishekkumaresan We've turned jinja templating off by default due to security concerns. You can re-enable it by setting the feature flag `ENABLE_TEMPLATE_PROCESSING`

this is covered in https://github.com/apache/incubator-superset/blob/master/UPDATING.md

**Comment by abhishekkumaresan** [comment]
Sorry for posting a new issue, Thanks
