### ISSUE TITLE
[ux]dashboard to explore to dashboard flow SAVE buttons

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11748]
![123123](https://user-images.githubusercontent.com/67837651/99692238-ef88f000-2a3e-11eb-8059-11f1df351a7b.gif)

Currently, when users explore a chart from the dashboard, after making necessary tweaks on the chart, users have to 
step 1: click the `+ SAVE` button on the top left 
step 2: `CHART NAME` and `ADD TO DASHBOARD` are filled in, `Save as... `radio button is selected automatically which are GREAT! 
step 3: but the `SAVE & GO TO DASHBOARD` button is disabled! Users have to open the dropdown, click the desired dashboard to enable the button. 

The flow from View Chart on Dashboard - Edit Chart in Explore - Save Chart to Dashboard should be more seamless, saving an edited chart to the same dashboard is more common path than saving as a new chart, so there is no reason the `SAVE & GO TO DASHBOARD` button is disabled in this modal.

**Comment by michael-s-molina** [comment]
@junlincc I'm working on this right now.

**Comment by junlincc** [comment]
> @junlincc I'm working on this right now.

awesome! i was saving this bug for myself to work on lol 😅but yea thanks for picking it up and being proactive!
