### ISSUE TITLE
x-ing out Annotation Layer type makes the page blank

### ISSUE THREAD

**Issue by benceorlai** [apache/incubator-superset#11759]
### Expected results

Layer type resets to default

### Actual results

The entire page goes blank

#### Screenshots
![image](https://user-images.githubusercontent.com/8263072/99737477-3c8bb700-2a7d-11eb-8fd6-8c2473cff99a.png)
![image](https://user-images.githubusercontent.com/8263072/99737590-6c3abf00-2a7d-11eb-9e06-e763aed9afe8.png)
![image](https://user-images.githubusercontent.com/8263072/99737439-25e56000-2a7d-11eb-8695-8e938d35f01f.png)

#### How to reproduce the bug

1. Open a Chart in Explore
1. Click + Add Annotation Layer
1. Click on the little x next to Formula in the ANNOTATION LAYER TYPE
1. See the whole page go blank

### Environment

(please complete the following information):

- superset version: master sha 676e0bb28211ec8e588abb8898924771d3dd6f32
- python version: 
- node.js version: 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
we should just kill the `x` as it's really not needed.. appreciate anyone can throw a quick fix.

**Comment by nytai** [comment]
We should also handle the fact that the explore page goes completely blank when there's an error. I think we just need to wrap the explore page in an `ErrorBoundary`

**Comment by benceorlai** [comment]
at the risk of nitpicking, i think the expected behavior of that x is to reset the value of the dropdown to its default, not to close out the popover. the real issue though is the page blankout, which I think is quite serious (although an edge case)

**Comment by junlincc** [comment]
>i think the expected behavior of that x is to reset the value of the dropdown to its default, not to close out the popover.

closing the modal is what the other Xs do in the same modal currently.

**Comment by mistercrunch** [comment]
It's also possible/easy to remove the `x` by setting the prop `clearable: false`
