### ISSUE TITLE
Can't connect to MySQL database

### ISSUE THREAD

**Issue by jvanulden** [apache/incubator-superset#11774]
I followed the instructions on the docker hub page for creating a container with mysqlclient installed. I ran the container, went through the configuration and ran init. Superset is up and running. Then I try to add a local connection to a MySQL database using a connection parameters that work in two other clients. I keep getting the following error:

    ERROR: Connection failed, please check your connection settings

Connection string is:

    mysql://admin:admin@localhost/mydb

### Expected results

Connection to the database

### Actual results

No connection

#### How to reproduce the bug

1. Extend the image on docker hub. Create a Dockerfile as follows:

 ```
    FROM apache/incubator-superset

    USER root

    RUN pip install mysqlclient

    USER superset
```

2. Build the image
3. Run the container
4. Add a new database connection
5. See the error

### Environment

- superset version: `latest`
- MacOS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
Connection failed

WARNING:superset.databases.api:Connection failed

172.17.0.1 - - [21/Nov/2020:18:20:06 +0000] "POST /api/v1/database/test_connection HTTP/1.1" 500 71 "http://localhost:8080/databaseview/list/?filters=%5B%5D&pageIndex=0&sortColumn=changed_on_delta_humanized&sortOrder=desc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
```

I also opened the container CLI and tried to confirm that mysqlclient was installed:

```
$ dpkg --get-selections | grep mysql
default-libmysqlclient-dev:amd64		install
mysql-common					install
```

```
$ pip install mysqlclient
WARNING: The directory '/home/superset/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.7/site-packages (1.4.2.post1)
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/superset'
Check the permissions.
```

**Comment by jvanulden** [comment]
Issue solved. The problem was on the database configuration side. I didn't have the domain host configured for the account that I was using to connect.

**Comment by daniel10012** [comment]
Hello Joost,
I am running into the same issue. 
Can you explain what you mean by " I didn't have the domain host configured for the account that I was using to connect." ?
Thank you !
