### ISSUE TITLE
[icon]copy icon is missing

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11807]
<img width="1725" alt="Screen Shot 2020-11-24 at 10 45 54 PM" src="https://user-images.githubusercontent.com/67837651/100192490-ec5e8b80-2ea6-11eb-8cc7-eb5b764c7146.png">

when we do fix it, please make sure the icon is centered.

**Comment by maloun96** [comment]
https://github.com/preset-io/incubator-superset/pull/49

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/pull/11847 fixed this closing
@maloun96 thanks so much!
