### ISSUE TITLE
Missing Security docs in the new docs site

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11818]
**Is your feature request related to a problem? Please describe.**

The Python docs have significantly more content in Security: https://apache-superset.readthedocs.io/en/0.36/security.html

than the current official docs: https://superset.apache.org/docs/security

**Describe the solution you'd like**

We should port these pages to the new doc site.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by junlincc** [comment]
@srinify
