### ISSUE TITLE
SESSION_COOKIE_SAMESITE not woking

### ISSUE THREAD

**Issue by keehl1213** [apache/incubator-superset#11810]
I wanted to embed dashboard to iframe, but got cross-site issue.  But I don't want to use `PUBLIC_ROLE_LIKE_GAMMA = True` and let everyone who knows the link to access my dashbaord. The solution I found was to set `SESSION_COOKIE_SAMESITE = None`.  The feature have existed after flask 1.0 [#2607](https://github.com/pallets/flask/pull/2607) [changed log](https://flask.palletsprojects.com/en/1.1.x/changelog/)

But no matter what I set, the `samesite` attribute has never shown up.

I can assure that flask and werkzung both are right version.  [#1549](https://github.com/pallets/werkzeug/issues/1549) and use the right config file.
### Expected Behavior

```http
Set-Cookie: session=<session>; Expires=Mon, 23-Nov-2020 11:58:00 GMT; Path=/; secure; samesite=<whatever I set>
```

### Actual Behavior

```http
Set-Cookie: session=<session>; Expires=Mon, 23-Nov-2020 11:58:00 GMT; Path=/; secure
```

### Example
1. Try to set `samesite=strict` and without secure.

config.py
```python
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False
```
result
![image](https://user-images.githubusercontent.com/9116623/100204291-ac4ae780-2f3e-11eb-8b1d-03a21006fd45.png)

2. Try to set `samesite=lax` and with secure.

config.py
```python
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = True
```

result
![image](https://user-images.githubusercontent.com/9116623/100205281-dea91480-2f3f-11eb-9561-90bb3a5f76ca.png)

### Environment

* Python version: 3.6
* Flask version: 1.1.2
* Werkzeug version: 1.0.1
* Superset version: 0.999.0dev

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by etr2460** [comment]
As displayed in the config comments (https://github.com/apache/incubator-superset/blob/master/superset/config.py#L918), you need to pass in `"None"` and not `None` to set the samesite attribute to "None". This is an unfortunate naming collision between Python and web standards...

Note I believe you also must set `SESSION_COOKIE_HTTPONLY` to True to set any of the samesite options as otherwise a malicious site could grab your cookie through JS and impersonate the user

**Comment by keehl1213** [comment]
> As displayed in the config comments (https://github.com/apache/incubator-superset/blob/master/superset/config.py#L918), you need to pass in `"None"` and not `None` to set the samesite attribute to "None". This is an unfortunate naming collision between Python and web standards...
> 
> Note I believe you also must set `SESSION_COOKIE_HTTPONLY` to True to set any of the samesite options as otherwise a malicious site could grab your cookie through JS and impersonate the user

It doesn't work either with `SESSION_COOKIE_SAMESITE = "None"`.  Actually, the `samesite` never showed up once in `set-cookie`, whatever the value is `"Lax"`, `"Strict"`, `"None"` or `None`.

**Comment by etr2460** [comment]
Did you set `SESSION_COOKIE_HTTPONLY` to True? I believe that's necessary

**Comment by keehl1213** [comment]
I've solved this problem.  The issue was cause by [flask-session](https://flask-session.readthedocs.io/en/latest/).  [#116](https://github.com/fengsp/flask-session/pull/116)
But the pull request haven't merged yet.  So I used the workaround from this issue [#124](https://github.com/fengsp/flask-session/issues/124)

**Comment by trepmag** [comment]
@keehl1213, I'm trying to figure the solution you are mentioning but I'm stalled as I can't find any `flask-session` package that would have been setup by the superset docker build in `/usr/local/lib/python3.7/site-packages/flask_session/`?

**Comment by colpari** [comment]
Works here if we set options keys directly in the Flask app config.

superset_config.py:
```
def __mutate(app):
    app.config.update(
        SESSION_COOKIE_HTTPONLY = True,
        SESSION_COOKIE_SECURE = True,
        SESSION_COOKIE_SAMESITE = "None"
    )

FLASK_APP_MUTATOR = __mutate
```

Just defining the values in the superset_config.py does not seem to get them anywhere.

**Comment by dscarabelliTT** [comment]
> Works here if we set options keys directly in the Flask app config.
> 
> superset_config.py:
> 
> ```
> def __mutate(app):
>     app.config.update(
>         SESSION_COOKIE_HTTPONLY = True,
>         SESSION_COOKIE_SECURE = True,
>         SESSION_COOKIE_SAMESITE = "None"
>     )
> 
> FLASK_APP_MUTATOR = __mutate
> ```
> 
> Just defining the values in the superset_config.py does not seem to get them anywhere.

This worked!
