### ISSUE TITLE
Query filters cannot be removed from saved slice

### ISSUE THREAD

**Issue by the-dcruz** [apache/incubator-superset#1181]
### Overview

If a slice is saved with some query filter specified, it is not possible to remove them from the slice.
I have verified this on master.
### Steps to recreate
1. Create new slice
2. Add any query filter
3. Save as new slice
4. Edit newly saved slice
5. Remove query filter by clicking the remove button
6. Save and overwrite
7. Reopen that slice and notice that the removed filters reappear
### Location of Issue

https://github.com/airbnb/caravel/blob/master/caravel/models.py#L273
Since the filter keys no longer exist in the request parameters, the old filter parameters are not overwritten.

**Comment by the-dcruz** [comment]
I can look into this if no one wants to pick it up soon.

**Comment by mistercrunch** [comment]
Please do!

**Comment by graceguo-supercat** [comment]
Verified this issue is fixed.
