### ISSUE TITLE
Default profile images don't have consistent text sizes

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#11813]
## Screenshot
![image](https://user-images.githubusercontent.com/7409244/100271787-eef4cb80-2f0e-11eb-84db-4495a460f8d1.png)

## Description
It looks like we're resizing the initials to fix into the circle, a good idea, but results in weirdness when characters are different widths.

## Design input
We should probably make the initials a consistent size.

I forget who was working on this, perhaps @lilykuang ?

**Comment by nytai** [comment]
This was me

**Comment by nytai** [comment]
Looks like the issue with the [antd avatar component](https://ant.design/components/avatar/) that's applying a css transform inline

**Comment by nytai** [comment]
Here's the logic behind the transform 
https://github.com/ant-design/ant-design/blob/20788d870c59aabfe218acd073d73825034f89d3/components/avatar/avatar.tsx#L61

**Comment by etr2460** [comment]
Sigh, so maybe not fixable... Unless we used a monospace font for this. But that might not look good either. Up to you if you wanna look more into this, otherwise I'd accept closing it as "won't fix" as well

**Comment by nytai** [comment]
It's probably worth opening an issue with antd and linking here for tracking purposes, this doesn't seem like desirable behavior

**Comment by etr2460** [comment]
Will do, I'll open one now

**Comment by etr2460** [comment]
Actually @nytai, I think this is because we're applying a font size to the Avatar. I can only repro the issue when I set a large fontSize on the Avatar component, as seen here: https://5udvj.csb.app/

I'd recommend for a fix that we see what the max size is for `WW` to fit inside the Avatar, and set that for all of them. Sound good?
