### ISSUE TITLE
Apache Superset Can't Find Tables

### ISSUE THREAD

**Issue by supersetdashboard** [apache/incubator-superset#11831]
I'am running apache superset and postgresSQL in docker.

I set up a database connection. and when i check the connection get the message "connection seems oke"

and in sqllab i can select the good database and schema and everything seems to work.

But if i want to add a table with the same databse, schema and table name as in sql lab i get this error.

Table [tablename] could not be found, please double check your database connection, schema, and table name

Does anyone have a idea how to fix this?

thx in advance

**Comment by zhaoyongjie** [comment]
Hi @supersetdashboard ,  Are you using "create table as" from SQLLab ? Please check if whether the database allows CTAS function.
