### ISSUE TITLE
Chart name is not updated and altered button is causing an error

### ISSUE THREAD

**Issue by adam-stasiak** [apache/incubator-superset#11835]
Name change for chart is not reflected on chart view without refresh and After click on ALTERED then we see white screen and error in the console.

### Expected results

New name should be displayed. Altered should show the difference.

### Actual results

Old name is displayed. Unhandled error after click on altered. @junlincc 
#### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25153919/100471315-54e17e80-30da-11eb-99e3-731b2da2f792.gif)

#### How to reproduce the bug

1. Go to charts
2. Click on any chart
3. edit chart title and save
4. see that name has not changed
5. click on altered
6. see that white screen is dispplayed

### Environment

(please complete the following information):

built with docker-compose up
master commit f121107bbe1f43b7e4ba8dd8e5185bf1ab1a5e75

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thanks @adam-stasiak  it's a duplicate issue https://github.com/apache/incubator-superset/issues?q=is%3Aissue+is%3Aopen+edit+chart+properties

**Comment by junlincc** [comment]
https://github.com/apache/incubator-superset/issues/11623 

thanks @adam-stasiak it's a duplicate issue
