### ISSUE TITLE
how to add echarts with 0.37.2version?

### ISSUE THREAD

**Issue by Warriorwithdreams** [apache/incubator-superset#11840]
I want to use echarts in dashboard.But I don't know how to add echarts in superset.

**Comment by villebro** [comment]
The first built-in ECharts charts have been added in the 0.38 version of Superset. I suggest upgrading to 0.38.0 which was released recently.

**Comment by Warriorwithdreams** [comment]
> The first built-in ECharts charts have been added in the 0.38 version of Superset. I suggest upgrading to 0.38.0 which was released recently.

Thanks
