### ISSUE TITLE
[Explore view] duplicated /api/v1/chart/id requests

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11864]
#### How to reproduce the bug

1. Open explore view from chart list,
2. or Explore chart from dashboard,

### Actual results

You will see 2 /api/v1/chart/_id_ requests

### Expected results

only 1 api call for each endpoint.

#### Screenshots

<img width="1172" alt="Screen Shot 2020-11-30 at 2 47 56 PM" src="https://user-images.githubusercontent.com/27990562/100675338-9f9e0900-331b-11eb-8f4d-163c6a5bcfb7.png">

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@geido 🙏
