### ISSUE TITLE
[chart]deck.gl Scatterplot Point Color option dropdown list 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11865]
<img width="1740" alt="Screen Shot 2020-11-30 at 3 03 06 PM" src="https://user-images.githubusercontent.com/67837651/100676157-2c959200-331d-11eb-8de7-468c20c971af.png">

To reproduce:
- use `long_lat` datasource to create deck.gl.Scartterplot with LON as the longitude and LAT as the latitude   
- scroll down to the Point Color section and click DIMENSION 
- There supposed to be 15 options but nothing is showing  

Version 0.38

**Comment by junlincc** [comment]
it is not easy to fix this issue, reprioritizing it and will revisit post 1.0. cc: @eugeniamz

**Comment by ktmud** [comment]
@junlincc @eugeniamz Just pushed a fix: https://github.com/apache-superset/superset-ui-plugins-deckgl/pull/21

**Comment by junlincc** [comment]
> @junlincc @eugeniamz Just pushed a fix: [apache-superset/superset-ui-plugins-deckgl#21](https://github.com/apache-superset/superset-ui-plugins-deckgl/pull/21)

🥺🥺🥺🥺🥺 thank you!
