### ISSUE TITLE
[chart]heatmap selecting metrics does not update the query results

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11866]
to reproduce:
- select `energy_usage` datasource and make a Heatmap
- select any metrics e.g. SUM(value) 
- click View Query to verify the query ✅
- click View Results to verify the query results ❌
![heatmap](https://user-images.githubusercontent.com/67837651/100677827-b430d000-3320-11eb-9ee5-d2b234292324.gif)

**Comment by mayur741** [comment]
I think query is also showing wrong.
its doing count(value) as avg(value).

**Comment by mayurnewase** [comment]
I think query displayed is wrong.
its doing count(value) as avg(value).

**Comment by villebro** [comment]
FYI: this was not limited to heatmap, but all visualizations (the bug was in the metric component).
