### ISSUE TITLE
A underline issue

### ISSUE THREAD

**Issue by eugene-belarus** [apache/incubator-superset#11874]
## Screenshot

![image](https://user-images.githubusercontent.com/71097330/100739004-86628e80-33e7-11eb-84ee-ae4bc3953921.png)
![image](https://user-images.githubusercontent.com/71097330/100739095-a4c88a00-33e7-11eb-86c6-ce7655e3ffb3.png)

## Description

When you go to SQL Lab or Query Search the cyan underline appear but when you go to Saved Query, Chart or Dashboards there's no the cyan underline.

**Comment by junlincc** [comment]
thanks for reporting! i was able to reproduce but not sure why it happens, but will get it fixed.

**Comment by junlincc** [comment]
@kgabryje Victor tried to fix this ^^ by removing the only underline showing in SQL editor, but we realized this could be a bigger issue. can you investigate and see if we can bring the background animation and underlines back? 🙏 thank you Kamil!
