### ISSUE TITLE
0.38.0界面显示有问题，无法显示source,mananger等按钮，是安装的问题，还是版本的问题

### ISSUE THREAD

**Issue by zfq314** [apache/incubator-superset#11871]
## Screenshot

[drag & drop image(s) here!]

## Description

[describe the issue here!]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by zhaoyongjie** [comment]
Hi, @zfq314. please add screenshots and more issue description.

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100822490-62f21f00-348d-11eb-9697-de39237d5229.png)
显示不全

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100822935-44405800-348e-11eb-8fc1-ac66972190ba.png)
0.37.2版本web界面显示没什么问题Source 、Security都可以显示，
![image](https://user-images.githubusercontent.com/33599707/100823034-79e54100-348e-11eb-8382-e51913882ee2.png)
0.38.0版本 web界面显示有问题Source 、Security都没显示出来，是我安装的问题，还是什么问题呀，先装的miniconda3
在这里面装的superset。希望给出方案。

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100823936-207e1180-3490-11eb-87f5-0f934d23e668.png)
![image](https://user-images.githubusercontent.com/33599707/100823950-2d026a00-3490-11eb-99d5-8c9f3bb31003.png)
无法加载数据源，创建charts的时候，无法选择数据源

**Comment by zhaoyongjie** [comment]
It may be an endpoint permissions issue. try the following command. 0.38 The manager menu is inside the setting menu item.
```
<enter to the Superset Python virtual environment>
superset init
```

试试上面这个命令。 0.38 把管理菜单放到setting子菜单里面了。

**Comment by zhaoyongjie** [comment]
"Databases and tables" is inside the DATA menu item on Superset 0.38

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100833459-f551ed00-34a4-11eb-9616-5335b5d5b5c5.png)
还是不行。

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100833735-80cb7e00-34a5-11eb-947e-0c7c65b67273.png)
setttingli'm里面的按钮点了没什么反应。0.38相关的使用说明在哪里可以看。我看了官网，没有找到说明。

**Comment by zhaoyongjie** [comment]
![image](https://user-images.githubusercontent.com/2016594/100834047-2aab0a80-34a6-11eb-9f8c-5bc9251dbe37.png)

isn't there one?

**Comment by zfq314** [comment]
Security,Manage都是灰色的，创建数据库连接了，创建Charts无法加载数据源，没有可以选择的数据源，可以降低版本吗？换成0.37.2的版本。

**Comment by zhaoyongjie** [comment]
那个灰色的意思是说： 这是个菜单。 "List Users" / "List rules" 是实际可以点的菜单项。 下面同理。 不能换成0.37.2， 除非您downgrade.
数据源需要去： Data -> Databases 加入。

**Comment by zfq314** [comment]
![image](https://user-images.githubusercontent.com/33599707/100847518-e7a76200-34ba-11eb-92c8-19064e46d714.png)
数据库是有的，charts的时候，没有数据源，这个怎么回事
![image](https://user-images.githubusercontent.com/33599707/100847675-13c2e300-34bb-11eb-88b8-8316ac3d077d.png)
数据库连接是正常的，但是你看下面的操作
![image](https://user-images.githubusercontent.com/33599707/100847766-2e955780-34bb-11eb-99b4-f9f4f5a2d927.png)
这个怎么回事？

**Comment by zfq314** [comment]
没有可选择的数据库，怎么处理？

**Comment by zfq314** [comment]
Security,Manage 这个两个按钮和List Users" / "List rules不一样的，List Users" / "List rules按钮可以点击的，但是Security,Manage是不能点击的。有个朋友和我遇到的问题是一样的。

**Comment by zfq314** [comment]
我的角色是管理员角色

**Comment by zhaoyongjie** [comment]
hi, @zfq314.

Question 1:
Superset explore flow is :
1. create a database
2. create a `dataset(datasource)`, this is a database table
3. explore this `dataset`
You only created the database but not the table.

Question 2:
Security and Manage words are 'LABLE' for menu, not menu items.

Q1:
你需要加个 db table. 你没加db table
Q2: 
安全和管理这俩玩意， 是标签， 不是菜单项不能点。

**Comment by zfq314** [comment]
OK,非常感谢，知道怎么回事了？

**Comment by zhaoyongjie** [comment]
@junlincc Please close this issue.
