### ISSUE TITLE
[chart] Multiple line chart keeps redrawing and sending multiple requests to API

### ISSUE THREAD

**Issue by kgabryje** [apache/incubator-superset#11889]
When I enter "Multi Line" chart from test data, the chart is flickering and redrawing. On the gif you can see that on each redraw, an http request to `/superset/explore_json/?form_data=...` is sent.
CC @junlincc 

### Expected results

The chart should render only once and not send API requests after that.

### Actual results

Chart is flickering and rerendering, multiple calls to `/superset/explore_json/?form_data=...` are sent.

#### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/15073128/100867866-13b2eb00-349b-11eb-8aac-672e2eb2d69d.gif)

#### How to reproduce the bug

1. `docker-compose up`
2. Go to Charts -> Multi Line
3. Observe chart's behaviour
4. Open browser console, go to Networking and see that API calls are being sent

### Environment

(please complete the following information):

- superset version: Current master (commit 44e80e)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
thank you Kamil~ looks like we spotted the same issue but thank you for reporting! ♥️ https://github.com/apache/incubator-superset/issues/11544

**Comment by rwspielman** [comment]
I'm still seeing this issue in current master

**Comment by junlincc** [comment]
hm weird, i can confirm his issue is fixed in latest master(now)..
