### ISSUE TITLE
Can't get superset to connect to mysql database

### ISSUE THREAD

**Issue by saqeria** [apache/incubator-superset#11895]
Dear,

I've tried too many methods, different docker repository's and versions but I can't get superset to work with MYSQL. I made a MYSQL container and checked if all the ports and database info is correct. When I try to add the SQLAlchemy URI and test the connection it says the "ERROR: Connection failed, please check your connection settings" error. I've read through the repository setup/confiquration. But unfortunately nothing works. I'm trying to set up superset in synology docker. If anyone could please help me out it would be very much appreciated, currently I've been searching and trying different things for 4 hours now.. I know this isn't an issue and it's probably an issue on my side, but I'm really trying my best to set it up. 

Some info:
- I didn't load a custom superset_config.py as I've read that it isn't really necessary.
- I've changed the MYSQL database port to 3309 because port 3306 was already in use by another container.
- The SQLAlchemy URI (removed personal info): mysql://User:Password@localhost:3309/database

Thanks in advance for your effort.
Sorry for being stupid, I really tried to learn and research as much as possible before opening this "issue"
Help is really much appreciated 😢

**Comment by zhaoyongjie** [comment]
Hi @saqeria . If you are using docker to deploy superset and mysql, could you show me your docker container list by follow instruction.
```
$ docker ps -a
```

**Comment by saqeria** [comment]
> 
> 
> Hi @saqeria . If you are using Docker to deploy superset and mysql, could you show me your docker container list by follow instruction.
> 
> ```
> $ docker ps -a
> ```

Thank you for responding, the outcome of the docker ps -a command is:

CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                          PORTS                                         NAMES
d5e856ebf89a        incubator/superset                "gunicorn superset.a…"   19 hours ago        Up 8 hours (healthy)            0.0.0.0:8088->8088/tcp                        superset_superset_1
75a9703bc63d        mysql                              "docker-entrypoint.s…"   19 hours ago        Up 8 hours                      3306/tcp, 33060/tcp, 0.0.0.0:3309->3309/tcp   mysql
ad148f867498        redis:latest                       "docker-entrypoint.s…"   21 hours ago        Restarting (1) 35 seconds ago                                                 redis
66d05ec12c60        linuxserver/nextcloud:latest       "/init"                  24 hours ago        Up 8 hours                      80/tcp, 0.0.0.0:8888->443/tcp                 nextcloud
874a52bbe170        onlyoffice/documentserver:latest   "/app/ds/run-documen…"   25 hours ago        Up 8 hours                      443/tcp, 0.0.0.0:7776->80/tcp                 onlyoffice
3f0eb513b619        rocketchat/rocket.chat:latest      "docker-entrypoint.s…"   5 days ago          Up 8 hours                      0.0.0.0:3000->3000/tcp                        docker_rocketchat_1
3cc1a044c58a        linuxserver/heimdall:latest        "/init"                  5 days ago          Up 8 hours                      0.0.0.0:5554->80/tcp, 0.0.0.0:5544->443/tcp   webportal
a4860321af82        mongo:4.0                          "docker-entrypoint.s…"   7 days ago          Up 8 hours                      27017/tcp                                     docker_mongo_1
1f7ae58d245f        linuxserver/calibre-web:latest     "/init"                  9 days ago          Up 8 hours                      0.0.0.0:8083->8083/tcp                        calibre
4a9b8fbff5a9        linuxserver/mariadb:latest         "/init"                  11 days ago         Up 8 hours                      0.0.0.0:3306->3306/tcp                        mariadb
796f11186ec7        containrrr/watchtower:latest       "/watchtower"            2 months ago        Up 8 hours                      8080/tcp                                      watchtower
886ece268d43        mk0x/docker-clamav:latest          "/bootstrap.sh"          2 months ago        Up 8 hours (healthy)            0.0.0.0:3310->3310/tcp                        clamav
75eb76b15427        portainer/portainer:latest         "/portainer --admin-…"   4 months ago        Up 8 hours                      0.0.0.0:9990->9000/tcp                        portainer
6f1c95227c9e        78b4116161e4                       "docker-entrypoint.s…"   5 months ago        Exited (0) 2 months ago                                                       docker_mongo-init-replica_1

**Comment by zhaoyongjie** [comment]
hi @saqeria , according to your output, MySQL container startup instruction may be Incorrect, you expect to use port 3309 as an external port, while the MySQL container internal port is always 3306. try the following command to start MySQL container

```
$ docker run -p 3309:3306 -d <mysql-image-name
```

**Comment by saqeria** [comment]
> 
> 
> hi @saqeria , according to your output, MySQL container startup instruction may be Incorrect, you expect to use port 3309 as an external port, while the MySQL container internal port is always 3306. try the following command to start MySQL container
> 
> ```
> $ docker run -p 3309:3306 -d <mysql-image-name>
> ```
> 
> Note that you have to stop the current MySQL container.

Hi @zhaoyongjie thanks again for responding. Your help is really much appreciated! I stopped the container and started a new container using your suggested option but unfortunately still without any succes. Superset still can't connect to MySQL, neither with localhost nor 127.0.0.1.. (I've tried both ports 3306 and 3309, just in case).

**Comment by zhaoyongjie** [comment]
Hi @saqeria What error does Superset appear? Could you show me the Superset log or screenshot?
