### ISSUE TITLE
Menu item to access Tables/Databases is missing

### ISSUE THREAD

**Issue by grafke** [apache/incubator-superset#11894]
The Menu item to access data sources is missing after an upgrade from 0.37.2 to 0.38.0

### Expected results

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9698688/100900415-8045de00-34cb-11eb-844b-3d2001bda4ea.png">

### Actual results

Database list is only available through a direct url: https://superset.../databaseview/list
Table list is only available through a direct url https://superset.../tablemodelview/list/ 

#### Screenshots
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9698688/100900030-17f6fc80-34cb-11eb-96f5-4d9f5e98b86a.png">

#### How to reproduce the bug

1. Use this [dockerfile](https://github.com/amancevice/docker-superset/blob/main/Dockerfile). 
2. Run superset db upgrade

### Environment

(please complete the following information):

- superset version: 0.38.0
- python version:  3.8
- node.js version: 12

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment]
Please using instruction `superset init` activate new *Data* menu items

**Comment by grafke** [comment]
My bad, I did not think of that, thanks @zhaoyongjie !
