### ISSUE TITLE
SQL Lab - Local Storage Message Appears Frequently

### ISSUE THREAD

**Issue by yousoph** [apache/incubator-superset#11905]
The error about using too much storage space is appearing more frequently. I'm seeing after running a query in SQL Lab (even if I don't have other tabs open) and when going from SQL Lab -> Explore. 

#### Screenshots

![image (2)](https://user-images.githubusercontent.com/10627051/100949912-1b38bb00-34c0-11eb-8c41-a2ae63bdbbad.png)

#### How to reproduce the bug

1. In SQL Lab, run a query with a larger result set 
2. Wait for the results to appear, and this error will appear as well 

### Environment

- superset version: lastest master 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yousoph** [comment]
Config issue - enabling SQLLAB_BACKEND_PERSISTENCE should resolve this

**Comment by pierreyves-lebrun** [comment]
Is there any reason for that feature not to be enabled by default?
