### ISSUE TITLE
Adding annotation formula to bar chart add more bars instead of line 

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#11909]
**Describe the bug**

**To Reproduce**
1. Go to explore
2. Create time-series bar chart
3. Add annotation layer
4. Set y=constant e.g. `y=100` as formula

![image](https://user-images.githubusercontent.com/1659771/99842765-4963e580-2b25-11eb-9516-bc63672ab803.png)

**Expected behavior**
A horizontal line at y 100

**Screenshots**
It adds a bar for each grouped bar instead.

<img width="922" alt="Pasted_Image_11_20_20__11_37_AM" src="https://user-images.githubusercontent.com/1659771/99842565-ec682f80-2b24-11eb-8749-b669e88b401c.png">

**Environment (please complete the following information):**
 - superset-ui version: current

**Comment by junlincc** [comment]
this issue is duplicate [here](https://github.com/apache/incubator-superset/issues/11790) and already being [fixed](https://github.com/apache/incubator-superset/pull/11876) (sort of, as bar chart does not support this annotation), waiting for your reviews~ @kristw

**Comment by junlincc** [comment]
@kristw 

issue is resolved by https://github.com/apache/incubator-superset/pull/11876
additional enhancement will come later.

**Comment by kristw** [comment]
@graceguo-supercat Please correct me if I misunderstood since you report the issue, but I thought the bar chart support this previously and this is a regression?

If the bar chart did not support this before then please re-close the ticket.

**Comment by graceguo-supercat** [comment]
No, i am not sure this is a regression. This is probably just a bug for a long time but no one reported before.

**Comment by junlincc** [comment]
@agatapst confirmed that line formula annotation was not supported in the past. @kristw do you mind opening an enhancement issue and close this one?

**Comment by kristw** [comment]
sgtm then.

**Comment by junlincc** [comment]
@kristw @graceguo-supercat try Echarts time series bar chart, it does support formula annotation line. does it work for you user cases? 

<img width="1772" alt="Screen Shot 2020-12-08 at 9 31 50 PM" src="https://user-images.githubusercontent.com/67837651/101589239-e683a280-399c-11eb-9606-2aa13d5045c9.png">

**Comment by necrodark12** [comment]
i have tried using the "y" but on the time-series bar chart and it doesnt show a horizontal line.

**Comment by oneryalcin** [comment]
Hi, I found a very weird behaviour. One of my colleague created a annotation line (y=100) in a bar chart and it did work for a day but then disappeared for no reason. I think the formula is easy and should be supported well as this is a very common case.

**Comment by rusackas** [comment]
If you can come up with a reproducible test case (preferably using example data) on Superset 3.x, I'd advice opening a new issue with that.
