### ISSUE TITLE
SQL Lab - Database Not Selected by Default

### ISSUE THREAD

**Issue by yousoph** [apache/incubator-superset#11914]
When going into SQL Lab for the first time, a database should be selected by default. Currently, the dropdown is blank and there's not clear feedback to the user that they need to select a database if they try to run a query. 

### Expected results
The first database in the list should be populated by default when the user visits SQL Lab 

### Actual results
No database is populated 

#### Screenshots

![image](https://user-images.githubusercontent.com/10627051/100978318-10e5e380-34f7-11eb-9108-79ae0d6a9f4e.png)

#### How to reproduce the bug

1. Visit SQL Lab for the first time 
2. In your left panel, see if anything is selected in the database dropdown

Alternatively: 
1. Close all your query tabs in SQL Lab
2. Visit SQL Lab again by clicking it in the header or refreshing your page 
2. In your left panel, see if anything is selected in the database dropdown

### Environment

- superset version: `master`

### Checklist

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by hughhhh** [comment]
closing with #11934
