### ISSUE TITLE
How to deploy with source code  in centos7

### ISSUE THREAD

**Issue by beepupa** [apache/incubator-superset#11925]
I successfully deployed the previous version, but found that the new version is different from the previous version. How should I deploy it and How do you compile the front-end UI
![image](https://user-images.githubusercontent.com/36186038/101131634-9923d000-3640-11eb-8219-46fbb743a54d.png)

**Comment by doublechoose** [comment]
> I successfully deployed the previous version, but found that the new version is different from the previous version. How should I deploy it and How do you compile the front-end UI
> ![image](https://user-images.githubusercontent.com/36186038/101131634-9923d000-3640-11eb-8219-46fbb743a54d.png)

hello , i just builted it today , here are my workflow ,you can follow the steps: https://zhuanlan.zhihu.com/p/329957118

**Comment by beepupa** [comment]
> > I successfully deployed the previous version, but found that the new version is different from the previous version. How should I deploy it and How do you compile the front-end UI
> > ![image](https://user-images.githubusercontent.com/36186038/101131634-9923d000-3640-11eb-8219-46fbb743a54d.png)
> 
> hello , i just builted it today , here are my workflow ,you can follow the steps: https://zhuanlan.zhihu.com/p/329957118

Good thank you  ,Can be applied to versions:0.38?

**Comment by zhaoyongjie** [comment]
Hi, @beepupa seems that your Python3.7 interpreter is Incomplete. try:
```
$ python
>>> from typing import Any
```
Do the same error happen?

**Comment by beepupa** [comment]
> 嗨，@beepupa似乎您的Python3.7解释器不完整。尝试：
> 
> ```
> $ python
> >>> from typing import Any
> ```
> 
> 是否发生相同的错误？
no
![image](https://user-images.githubusercontent.com/36186038/101134448-56b0c200-3645-11eb-8d52-83d994bdf754.png)

**Comment by zhaoyongjie** [comment]
@beepupa Could you show the run.py content, please?

**Comment by beepupa** [comment]
> @beepupa您能否显示run.py内容？

![Uploading image.png…]()

**Comment by zhaoyongjie** [comment]
@beepupa cannot see your screenshot

**Comment by villebro** [comment]
@beepupa can you check what the contents of your `PYTHONPATH` environment variable is?

**Comment by beepupa** [comment]
> > I successfully deployed the previous version, but found that the new version is different from the previous version. How should I deploy it and How do you compile the front-end UI
> > ![image](https://user-images.githubusercontent.com/36186038/101131634-9923d000-3640-11eb-8219-46fbb743a54d.png)
> 
> hello , i just builted it today , here are my workflow ,you can follow the steps: https://zhuanlan.zhihu.com/p/329957118
![image](https://user-images.githubusercontent.com/36186038/101430744-94ad2f00-3940-11eb-90c8-e21d555cee45.png)
I deployed it your way, but it went wrong. You can help me

**Comment by beepupa** [comment]
> @beepupa can you check what the contents of your `PYTHONPATH` environment variable is?

Thank you very much. I have solved it

**Comment by beepupa** [comment]
> > I successfully deployed the previous version, but found that the new version is different from the previous version. How should I deploy it and How do you compile the front-end UI
> > ![image](https://user-images.githubusercontent.com/36186038/101131634-9923d000-3640-11eb-8219-46fbb743a54d.png)
> 
> hello , i just builted it today , here are my workflow ,you can follow the steps: https://zhuanlan.zhihu.com/p/329957118

Thank you very much. I have solved it

**Comment by beepupa** [comment]
> @beepupa Could you show the run.py content, please?

Thank you very much. I have solved it

**Comment by villebro** [comment]
@beepupa please close the issue if this is resolved. It would also be very helpful for other users if you could post a summary of how you were able to solve the problem. Thanks! 🙏
