### ISSUE TITLE
[list view]user can delete items by typing 'delete'(lower case) in stead of DELETE 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11933]
![ezgif-3-ef55817ed60b](https://user-images.githubusercontent.com/67837651/101197335-d7a49500-3616-11eb-9d0b-7219d16c063e.gif)

see gif

cc: @adam-stasiak thanks for finding this issue🙏

**Comment by junlincc** [comment]
@willbarrett @lilykuang

**Comment by willbarrett** [comment]
Thanks, kicked it into our next sprint.

**Comment by ktmud** [comment]
Isn't this by design? It'd be quite annoying to have typed "delete" then realizing it doesn't work.

The goal is to have some guardrail and allowing lowercase works equally fine.

**Comment by ktmud** [comment]
What really is wrong is the autocomplete that makes typing in "delete" too easy as it defeats the purpose of adding additional hurdles to the delete action.

**Comment by nytai** [comment]
This is by design, 
https://github.com/apache/incubator-superset/blob/7e6f04fce4321cee9d69b14fa003e4c24b5cf720/superset-frontend/src/components/DeleteModal.tsx#L78

The code specifically converts the input to uppercase before comparing. The point is not to make the user jump through various hoops in order to delete something, it's just to ensure the change is intentional. 

I agree with @ktmud, though, we should remove the browser `autocomplete` to make sure the user actually types something into the input instead of clicking around a couple of times.

**Comment by nytai** [comment]
Also, looks like @mistercrunch made that change in https://github.com/apache/incubator-superset/pull/10388/files#diff-2dcfea068e611950d8898cc420b114093befdf9f5769f7c48ba2141a4e6ab284R77 so it's definitely intentional.

**Comment by willbarrett** [comment]
Agreed, this functionality is working as expected. Closing.

**Comment by junlincc** [comment]
<img width="596" alt="Screen Shot 2020-12-14 at 12 42 46 PM" src="https://user-images.githubusercontent.com/67837651/102133402-e60a6200-3e09-11eb-9bd7-8abe3bd37d7f.png">

if this is intentional, we will have to change the UI and the test case.
@mistercrunch

**Comment by nytai** [comment]
What should the UI display? It doesn’t look wrong to me. The user can delete the resource after typing DELETE

**Comment by junlincc** [comment]
as a user, i don't expect typing anything else other than what's instructed(DELETE)here will work, even if it's just the same word in lower case. it's like, if there is more than one key that can open up my door, i need to know at least who else holds the key.

**Comment by junlincc** [comment]
if you all think this is an optimized UX/UI, i don't have further comment.  @mistercrunch @ktmud @nytai

**Comment by ktmud** [comment]
I don't think this matter that much. The "DELETE" button is disabled by default, but will be enabled once users type the word "delete" (or "DeLeTe" if they want). The point is this is a guardrail and insensitive cases serve the guardrail purpose pretty well. Let's not add unnecessary hurdles or bloat the copy to make it confusing.

**Comment by ktmud** [comment]
We need a follow up PR to disable autocomplete.

**Comment by mistercrunch** [comment]
I changed it because it's confusing from the code's standpoint, because the uppercase is applied as a CSS transform
<img width="655" alt="Screen Shot 2020-12-14 at 1 32 53 PM" src="https://user-images.githubusercontent.com/487433/102138271-f3771a80-3e10-11eb-8b27-b6db39ffd57b.png">

If someone was to change the CSS, the label would become confusing.

**Comment by mistercrunch** [comment]
Happy removing the `.toUpperCase()`, but let's change the label text to `type "DELETE" to confirm` despite the CSS `text-transform: upper` effectively doing that currently. Otherwise reading the code it looks like a bug.

**Comment by junlincc** [comment]
> Isn't this by design? It'd be quite annoying to have typed "delete" then realizing it doesn't work.

After clarifying with Max, I understand that having delete work in all cases(DELETE, delete, DEleTe) is NOT by Design or intentional from a UX standpoint. The original Design was to have the user type in 'DELETE' to perform the task with extra caution. 

We probably should not make it easy for user to complete any irreversible actions in a product. I'm pretty sure users will be much more annoyed by permanently deleting an object than pressing the 'caps lock' to confirm the action. I'm also sure that if we ran a user test, most of the users would type "DELETE' to perform the task. 

The more significant concern to me is, as a user, I was instructed by the UI label to type `DELETE`, and that's what I expect will work - ONLY. I'm surprised when typing 'delete' also enables the button. Thoughts in my mind - Is this a bug? If this a bug, is this issue happening in another area of the product? Could typing a wrong password input give me access to my workspace as well? My argument may sound stupid, but that's exactly what went through in a non-technical user's mind. 
When a product fails the user's expectation in a small area, it leads them to doubt the product's overall reliability. I would rather annoy my users with requiring them to press 'caps lock' than breaking the trust. 

We have plenty of room to help our users improve efficiency and save time in Superset; this issue just should not be in that case. It may seem minor or unnecessary from an engineering standpoint, but it matters to me as a PM. 

I'd suggest 1) adding case sensitive to the label, 2) button should not be enable until the exact string is input. 

cc @ktmud @nytai @mistercrunch

**Comment by ktmud** [comment]
Why would someone type "delete" if they don't really want to delete? Just to test whether things will break? Not every user is a PM who wants to poke holes. They just want to complete their tasks and by the time they have typed "delete", the intent is pretty clear.

Surely most people would type DELETE as instructed, but it's quite a stretch to say they will start to doubt the trustworthy and reliability of the whole system when they found out "delete" also work. Even if you are surprised it enables the delete button, you wouldn't be surprised that clicking on the enabled delete button will actually delete things. The possibility of a **real** user who opened the modal, typed "delete", then clicked on the red button actually made a mistake, in my opinion, is close to zero.

I'd also like to point out this is not a case where Engineers don't care about tiny little things, but rather people having different opinions on solutions. When something matters to a PM doesn't automatically make it more important to real users. Superset is an open source project, decisions are better made collectively by the broader community. We all want Superset to become a sophisticated, high-quality product, but none of us have conducted enough user research on every little thing to have strong evidence on every argument, so let's try not to argue things with "this is important to me" or spend too much energy on the philosophical debate of "how good we want Superset (or my company) to be".

If we really want to make the changes as proposed, I'd suggest at least tell users upfront that this is going to be case sensitive. E.g., change the copy to `Type "DELETE" (case sensitive) to confirm`.

**Comment by junlincc** [comment]
Both `It'd be quite annoying to have typed "delete" then realizing it doesn't work.` and `It is important to me as a PM` to me are opinions. I am always a strong advocate for conducting user research and testing to back our opinions, regardless of whose the argument is. And I hope we can get to it at some point and revisit a few other previous discussions as well. 

> If we really want to make the changes as proposed, I'd suggest at least tell users upfront that this is going to be case sensitive. E.g., change the copy to `Type "DELETE" (case sensitive) to confirm`. 

Thanks for the suggestion, I agree.

**Comment by ktmud** [comment]
While I still believe this input should be case insensitive, I can see how the way case insensitivity was initially introduced was probably not ideal. The label text should be without CSS text-transformation in the first place, as it contains a full sentence, which is different than a regular form input label that is normally a field name. UPPERCASE should be reserved for real form labels or CTA buttons so they can really stand out.

We should probably add a `uppercase={false}` option to the `<FormLabel>` component for things like this.
