### ISSUE TITLE
When sorting by User in Query History get a strange error message 

### ISSUE THREAD

**Issue by guhan** [apache/incubator-superset#11943]
### Expected results

No error message

### Actual results

Get an error popover see screenshot

#### How to reproduce the bug

1. Go to 'Query History"
2. Click on 'Sort by user'

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
<img width="889" alt="Screen Shot 2020-12-04 at 4 51 45 PM" src="https://user-images.githubusercontent.com/3980678/101228721-c2992780-3651-11eb-8e58-007f69e95ac4.png">

- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Thank you for reporting it, this is already fixed on `master` by @nytai : https://github.com/apache/incubator-superset/pull/11897
