### ISSUE TITLE
The configuration "ENABLE_ROW_LEVEL_SECURITY = True" in config.py is not in effect.

### ISSUE THREAD

**Issue by ravens510127** [apache/incubator-superset#11948]
When we update 0.37.0 to 0.38.0 ,we find "ENABLE_ROW_LEVEL_SECURITY = True" is not effective.

### Expected results

what you expected to happen.
![图片](https://user-images.githubusercontent.com/57929615/101341768-8b7a7e80-38bc-11eb-8ad1-4ab00686bdd9.png)

### Actual results

what actually happens.
![图片](https://user-images.githubusercontent.com/57929615/101341858-acdb6a80-38bc-11eb-90de-8adfa66a4c4e.png)

#### How to reproduce the bug

1. use LDAP
2. login
3. click settings
4. you will find

### Environment

(please complete the following information):

- superset version: 0.38.0
- python version: 3.6 or 3.7
- node.js version: v8.16.1 or v14.15.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@ravens510127 Please always check `UPDATING.md` before updating. Here's a copy of the entry regarding RLS:

`The Row Level Security (RLS) config flag has been moved to a feature flag. To migrate, add ROW_LEVEL_SECURITY: True to the FEATURE_FLAGS dict in superset_config.py.`

**Comment by isunix** [comment]
@villebro if login using ldap account, the ROW_LEVEL_SECURITY does not show on the dropdown page of the settings, even though add ROW_LEVEL_SECURITY: True to the FEATURE_FLAGS dict in superset_config.py. Please test this function further

**Comment by villebro** [comment]
@isunix I wouldn't expect LDAP to affect RLS, but you never know. It's also important to remember that RLS is only available to the admin user. Are you able to confirm that RLS is working without LDAP but stops working when LDAP is enabled?
