### ISSUE TITLE
Jinja templating is broken in 0.38.0 

### ISSUE THREAD

**Issue by saurabnigam** [apache/incubator-superset#11958]
After upgrading to latest version all queries started failing which used jinja templating
![CaptureJinja](https://user-images.githubusercontent.com/20903614/101452974-9bde3800-3954-11eb-9eab-5941d50eee03.PNG)

**Comment by dpgaspar** [comment]
Hi I was not able to replicate the issue on `0.38.0`

<img width="507" alt="Screenshot 2020-12-09 at 15 29 39" src="https://user-images.githubusercontent.com/4025227/101650031-69efd300-3a33-11eb-9fc1-c936acff7028.png">

Note that on `master` Jinja templating has been disabled by default: https://github.com/apache/incubator-superset/blob/master/UPDATING.md.

Please make sure your actually on 0.38.0, or reenable Jinja2 SQL templating following the instructions on `UPDATING.md`

**Comment by zufolo441** [comment]
the instructions in UPDATING.md are not clear at all. it doesn't tell that the parameter to be enabled is "ENABLE_TEMPLATE_PROCESSING"

**Comment by dpgaspar** [comment]
Could be improved but it tells that:
```
11172: Breaking change: SQL templating is turned off by default. To turn it on set ENABLE_TEMPLATE_PROCESSING to True on FEATURE_FLAGS
```

**Comment by zufolo441** [comment]
I'm sorry, you are right. I read only 11704.

**Comment by dpgaspar** [comment]
@zufolo441, no problem at all

**Comment by saurabnigam** [comment]
Can you share the docker image tag corresponding to 0.38.0
