### ISSUE TITLE
No module named pgsanity when using Docker image

### ISSUE THREAD

**Issue by michael-s-molina** [apache/incubator-superset#11961]
When I try to start the application using docker-compose up I get the following error:

superset_init            | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_init            | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_init            |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_init            | ERROR:superset.app:Failed to create app
superset_init            | Traceback (most recent call last):
superset_init            |   File "/app/superset/app.py", line 61, in create_app
superset_init            |     app_initializer.init_app()
superset_init            |   File "/app/superset/app.py", line 526, in init_app
superset_init            |     self.init_app_in_ctx()
superset_init            |   File "/app/superset/app.py", line 498, in init_app_in_ctx
superset_init            |     self.configure_data_sources()
superset_init            |   File "/app/superset/app.py", line 542, in configure_data_sources
superset_init            |     ConnectorRegistry.register_sources(module_datasource_map)
superset_init            |   File "/app/superset/connectors/connector_registry.py", line 38, in register_sources
superset_init            |     module_obj = __import__(module_name, fromlist=class_names)
superset_init            |   File "/app/superset/connectors/sqla/__init__.py", line 17, in <module>
superset_init            |     from . import models, views
superset_init            |   File "/app/superset/connectors/sqla/views.py", line 34, in <module>
superset_init            |     from superset.connectors.base.views import DatasourceModelView
superset_init            |   File "/app/superset/connectors/base/views.py", line 24, in <module>
superset_init            |     from superset.views.base import SupersetModelView
superset_init            |   File "/app/superset/views/__init__.py", line 17, in <module>
superset_init            |     from . import (
superset_init            |   File "/app/superset/views/access_requests.py", line 22, in <module>
superset_init            |     from superset.views.core import DAR
superset_init            |   File "/app/superset/views/core.py", line 88, in <module>
superset_init            |     from superset.sql_validators import get_validator_by_name
superset_init            |   File "/app/superset/sql_validators/__init__.py", line 19, in <module>
superset_init            |     from . import base, postgres, presto_db
superset_init            |   File "/app/superset/sql_validators/postgres.py", line 21, in <module>
superset_init            |     from pgsanity.pgsanity import check_string
superset_init            | ModuleNotFoundError: No module named 'pgsanity'

### Expected results

The docker image includes this module.

### Actual results

The module is not found.

#### How to reproduce the bug

1. Use docker image to install.
2. docker-compose up

### Environment

- superset version: `master`
- python version: `3.7`
- node.js version: `15.1`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I think this is related to issue #11538

**Comment by nytai** [comment]
you need to pull the latest images `docker-compose down && docker-compose pull && docker-compose up`

**Comment by michael-s-molina** [comment]
@nytai Thanks!
