### ISSUE TITLE
How can I initialize filter value of dashboard?

### ISSUE THREAD

**Issue by alf7927** [apache/incubator-superset#1196]
let's say I have a filter on dashboard. I'd like to initialize the global filter to downsize the data size on dashboard level. is that possible?

**Comment by bkyryliuk** [comment]
what do you mean by downsize ?
by the way gitter channel is a better place for questions:
https://gitter.im/airbnb/caravel

**Comment by cactusthinking** [comment]
Maybe "downsize" here means "reduce", we wonder if it possible to set default(initial) filter value in Filter box widget
