### ISSUE TITLE
Filters with Druid datasource

### ISSUE THREAD

**Issue by optossav** [apache/incubator-superset#1198]
Hi,
I have been trying to use druid data sources to create a dashboard and all seems to work except when adding a filter. Regardless of what "filter fields" I select and then run Query, I only see what looks like a unix time stamp in the possible values when trying to set values for filter. I tried creating one from SQL table and all fields populate correctly with filters. Has anyone successfully created a filter for a druid backed dashboard. I am using version 0.10

![driud_filter_string](https://cloud.githubusercontent.com/assets/1934440/18847120/d9018600-83dd-11e6-9266-50b2581e1195.png)

**Comment by gurdeep18** [comment]
I have had the Druid filter working correctly, but had to change my "Time Granualarity" to "All"

**Comment by optossav** [comment]
That worked!
