### ISSUE TITLE
Use can't get to all his favorite dashboards from the new welcome page

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11984]
**Is your feature request related to a problem? Please describe.**
Currently the new welcome page shows 3 popular dashboards.There is a button to "view all" which takes user out of the welcome page to the CRUD view with list of all dashboards. User can filter on those they own, but can't filter on those they favorited in the past. 

**Describe the solution you'd like**
Use should be able to view all dashboards they favorited in the past (like previously they could when clicking to "Settings -> Profile). This is a workaround not many people know about. 

Ideally they should be able to see all their favorite dashboards on the welcome page - upon clicking "view all" when on the "Favorite tab"  the section would expand and show all their favorite dashboards. 
![Screen Shot 2020-12-09 at 9 13 48 AM](https://user-images.githubusercontent.com/61221714/101662867-ddc3b880-39fe-11eb-860d-797804904a15.png)

**Comment by junlincc** [comment]
agreed! we will include it in the next iteration. @zuzana-vej

**Comment by junlincc** [comment]
also we should do the same for Favorite charts, and remove Favorite tab in Saved queries @zuzana-vej any objections?
