### ISSUE TITLE
style: padding/alignement in Data submenu

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#12027]
## Screenshot

<img width="584" alt="Screen Shot 2020-12-13 at 4 28 57 PM" src="https://user-images.githubusercontent.com/487433/102028713-59f03000-3d60-11eb-81d0-e640e78a7d71.png">

## Description
The padding/alignement in the submenu looks a bit off. I think to look right we'll have to:
- pills should be lower so that they align with the `Data` title on the lef
- padding above and under those pills should be identical / symetric

**Comment by junlincc** [comment]
> * pills should be lower so that they align with the `Data` title on the lef

<img width="1585" alt="Screen Shot 2020-12-13 at 7 58 06 PM" src="https://user-images.githubusercontent.com/67837651/102039160-e8bf7580-3d7d-11eb-83e4-ff371619c1cd.png">
yea i think the pill should be lower and the nav item that should be aligned from the bottom with `Data` title.

**Comment by mihir174** [comment]
Yes, agreed. Should look like this-
<img width="699" alt="Screen Shot 2020-12-15 at 3 03 04 PM" src="https://user-images.githubusercontent.com/64227069/102283147-a49bb480-3ee6-11eb-8d2a-268d65f5dccb.png">

**Comment by mihir174** [comment]
<img width="668" alt="Screen Shot 2020-12-15 at 3 14 17 PM" src="https://user-images.githubusercontent.com/64227069/102283940-3657f180-3ee8-11eb-8ad9-3b49153b6713.png">

**Comment by junlincc** [comment]
@geido ^^^ we would like to get to pixel perfect! thank you for taking it on!! 🙏
