### ISSUE TITLE
Add Slice support for arbitrary queries (including parameterization)

### ISSUE THREAD

**Issue by Jparks2532** [apache/incubator-superset#1203]
Slice support for arbitrary queries (including parameterization) would enable all types of use cases where a materialized table or view doesn't quite work.  For instance, the following query template could serve as the source for a Slice:

query:

```
SELECT
    dim,
    SUM(cnt) AS first_moment
    SUM(cnt*cnt) AS second_moment
FROM (
    SELECT id_user, <dimension1> AS dim, COUNT(*) cnt
    FROM table1
    WHERE ds between '<date_start>' and '<date_end>'
    GROUP BY id_user, <dimension1> 
) t
GROUP BY dim;
```

Users could pass in parameters at query time.

```
date_start: date
date_end: date
dimension1: string
```

**Comment by yejianye** [comment]
Very interesting idea, how will that work with 'group by', 'metrics' parameters in various viz types?

**Comment by Jparks2532** [comment]
The "query parameters" would be completely independent of the typical "group by" and "metrics" fields.

**Comment by yejianye** [comment]
Since almost every type of visualization requires 'groupby' and 'metrics'
parameters, how could we visualize those query-based slices without them?

Jparks2532 <notifications@github.com>于2016年9月28日周三 上午10:28写道：

**Comment by Jparks2532** [comment]
Please don't get too hung up on the example that I provided.  It's mainly there to show how you can pass in parameters into an arbitrary query.

**Comment by shivaachari** [comment]
is this feature implemented in Superset?

**Comment by mistercrunch** [comment]
Yes pretty much, by following the "Visualize" button in SQL lab you're essentially running the explore view against your SQL statement as a subquery, and this SQL statement can be templated and receive url parameters.
