### ISSUE TITLE
[Cosmetic][Chart List View]: Viz type filter should use friendly names

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#12084]
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/102417064-d6c51900-3faf-11eb-8361-f236777403f8.png" width="300">

## Description

The vis type should display as user-friendly chart type names (same as viz type select when creating a chart), instead of the internal registration key.

## Design input

Not needed

**Comment by nytai** [comment]
Any pointers on how to get those names? These values are coming from the chart registry

**Comment by nytai** [comment]
We should also probably change the column display to match too
