### ISSUE TITLE
[dashboard] Filter box dropdown BROKEN for boolean values

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#12105]
User can't select value in filter box dropdown, if the value is type boolean. Other values work. This is a regression.

### Expected results

Be able to select value.

### Actual results

Can't select value - no values show up.

#### Screenshots
![filterbox-issue-boolean](https://user-images.githubusercontent.com/61221714/102561801-78b93400-408a-11eb-9891-91aaa65f2739.gif)

#### How to reproduce the bug

1. Go to Filter box which has a column with boolean values
2. Try to select a value
3. See error

### Environment

(please complete the following information):

- superset version: `master` completely up to date
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Regression introduced in the last 2 weeks.

**Comment by zuzana-vej** [comment]
Another screenshot - same issue you can see on Explore if you see the filter box there. 
![Screen Shot 2020-12-17 at 5 11 59 PM](https://user-images.githubusercontent.com/61221714/102562028-0b59d300-408b-11eb-8eb1-c511afd7bf0a.png)

**Comment by junlincc** [comment]
on it! sorry about the regression! @geido 🙏🙏
cc: @kgabryje
