### ISSUE TITLE
[explore] Data section in Explore empty for column with boolean values

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#12106]
The new Data section on chart explore is empty if the column type is boolean.

### Expected results

Display the values

### Actual results

Empty column

#### Screenshots
![Screen Shot 2020-12-17 at 4 53 37 PM](https://user-images.githubusercontent.com/61221714/102562150-51af3200-408b-11eb-84b2-5f7c4ec510c1.png)

#### How to reproduce the bug

1. Go to 'Explore'
2. Create chart which includes a boolean column
3. Scroll down to Data section

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Opened a PR with a fix that _works_ but doesn't _feel_ quite right. Tagged some others on it for help with input/review.
