### ISSUE TITLE
[dashboard] Typing text in filter box dropdown / multi select doesn't work

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#12107]
Typing text in filter box doesn't work. Previously, user could type and the filter would display those results. For multi select or dropdown with less values, user can still select what they want. But if the dropdown has many records, or even more then the default that gets loaded and dashboard producer enabled typehead search, user can't actually even get to what they might want to filter on which is a big problem. 

### Expected results

Be able to type into filter box dropdown

### Actual results

Can't type into filter box dropdown

#### Screenshots
nothing is happening in the gif, while I am trying to type a number
![cant type](https://user-images.githubusercontent.com/61221714/102564089-9341dc00-408f-11eb-8775-6f039397668b.gif)

#### How to reproduce the bug

1. Go to filter box
2. Try to type value into dropdown select
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Regression

**Comment by zuzana-vej** [comment]
Regression probably caused by same as https://github.com/apache/incubator-superset/issues/12105

**Comment by junlincc** [comment]
on it!! sorry about the regression!

**Comment by ktmud** [comment]
Fixed by #12114
