### ISSUE TITLE
[explore]time picker select dropdown and scroll

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#12140]
🗒this issue was not seen when the PR was last tested and merged. it might caused by conflicts

https://user-images.githubusercontent.com/67837651/102680719-bcd23480-416f-11eb-87e6-e2862790a659.mov

due to the conflicts with recent refactoring work, new time picker select dropdown is cutoff, scroll bar is not showing.
(not caused by the original PR)

**Comment by zhaoyongjie** [comment]
@junlincc 
I would use Antd Popover to replace the original Modal, refactor DateFilterControl, and maybe avoid this problem.

**Comment by junlincc** [comment]
<img width="1784" alt="Screen Shot 2021-01-05 at 7 30 04 AM" src="https://user-images.githubusercontent.com/67837651/103665700-94e12000-4f28-11eb-9aff-87e19d7f71ad.png">

@zhaoyongjie thanks for fix, going forward please link PR to issue so that they can close automatically when PR is merged

**Comment by zhaoyongjie** [comment]
got it. ^_^
