### ISSUE TITLE
Default location of logs

### ISSUE THREAD

**Issue by drorata** [apache/incubator-superset#1216]
I would like to run Caravel as a daemon and I'm wondering how and where can I define where the logs should be saved?

**Comment by xrmx** [comment]
AFAICS If you are using bin/caravel you need to update the code to add explicit support for the relevant gunicorn option.

**Comment by bkyryliuk** [comment]
by default I believe it pipes the logs to the stdout.

**Comment by dennisobrien** [comment]
I'm using gunicorn and explicitly sending the log output to stdout.
```
gunicorn \
  --error-logfile - \
  --access-logfile - \
  -w 8 \
  -k gevent \
  -b 0.0.0.0:8080 \
  --timeout 120 \
  --limit-request-line 0 \
  --limit-request-field_size 0 \
  --forwarded-allow-ips="*" \
  caravel:app
```
