### ISSUE TITLE
can not  execute ‘superset db upgrade’ when SQLAlchemy connection is mysql 

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#12172]
- superset version: `0.37.2`
- python version: `3.6.8`
- node.js version: `node -v`

execute ‘superset db upgrade’ error when SQLAlchemy connection is mysql 
![image](https://user-images.githubusercontent.com/20242930/102882773-e057f080-4489-11eb-9394-52c785b9c627.png)

**Comment by dpgaspar** [comment]
Hi can you please post the full migration log. Also are you doing an install from scratch or upgrading an already existing DB?

Can you verify that migration `c82ee8a39623` executed?

**Comment by qinzl1** [comment]
@dpgaspar 
upgrading an already existing DB，my Current  version 0.28.1

**Comment by dpgaspar** [comment]
That's a bit old, I'll try to help but really need the full migration log

**Comment by qinzl1** [comment]
@dpgaspar 
thx，I have another way to solve it
