### ISSUE TITLE
thetaSketch postaggregation fails

### ISSUE THREAD

**Issue by ratb3rt** [apache/incubator-superset#1217]
I have two thetaSketch metrics which work correctly, but if I add a post-aggregator (which works directly against Druid), I get a 500 error when trying a simple query.
The postaggregator is defined like this:
`{
    "type":"thetaSketchEstimate",
    "name":"thetaSketch_intersect",
    "field": {
        "type":"thetaSketchSetOp",
        "name":"thetaSketch_intersect",
        "func":"INTERSECT",
        "fields":[
            {
                "type": "fieldAccess",
                "fieldName": "thetaSketch_one"
            },
            {
                "type": "fieldAccess",
                "fieldName": "thetaSketch_two"
            }
        ]
    }
}`

and the resulting error is:
`HTTP Error 500: Internal Server Error Druid Error: Instantiation of [simple type, class io.druid.query.aggregation.post.ArithmeticPostAggregator] value failed: Illegal number of fields[%s], must be > 1 (through reference chain: java.util.ArrayList[0]) Query is: { "dimensions": [], "aggregations": [ { "filter": { "type": "selector", "dimension": "event__name", "value": "value1" }, "aggregator": { "fieldName": "environment__app_instance_id_ts", "type": "thetaSketch", "name": "thetaSketch_one" }, "type": "filtered" }, { "filter": { "type": "selector", "dimension": "event__name", "value": "value2" }, "aggregator": { "fieldName": "environment__app_instance_id_ts", "type": "thetaSketch", "name": "thetaSketch_two" }, "type": "filtered" } ], "intervals": "2016-09-22T13:12:59+00:00/2016-09-29T13:12:59+00:00", "limitSpec": { "limit": 5000, "type": "default", "columns": [ { "direction": "descending", "dimension": "thetaSketch_one" } ] }, "granularity": { "duration": 86400000.0, "type": "duration" }, "postAggregations": [ { "fields": [], "type": "arithmetic", "name": "thetaSketch_intersect", "fn": "/" } ], "queryType": "groupBy", "dataSource": "rule-engine" }`

**Comment by xrmx** [comment]
This is druid exploding, are you sure your druid postaggregator is correct?

**Comment by RichRadics** [comment]
The post-agg is definitely fine - I can post it and get results. I have just discovered that pydruid doesn't support thetaSketch post-aggregators, maybe that's related.

**Comment by nanittu** [comment]
i ran into the same issue when defining a quantile based metric. 

HTTP Error 500: Internal Server Error Druid Error: Instantiation of [simple type, class io.druid.query.aggregation.post.ArithmeticPostAggregator] value failed: Illegal number of fields[%s], must be > 1 (through reference chain: java.util.ArrayList[0]) Query is: { "queryType": "timeseries", "dataSource": "watchtower", "aggregations": [], "granularity": "all", "postAggregations": [ { "type": "arithmetic", "name": "quantile_99", "fn": "/", "fields": [] } ], "intervals": "2017-02-27T22:57:53+00:00/2017-03-06T22:57:53+00:00" }

Any thoughts ?

**Comment by mistercrunch** [comment]
We just added support for Quantile and I don't think it made 0.18.0

**Comment by nanittu** [comment]
@mistercrunch thanks for the update. Any visibility into the roadmap for future releases ?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 410 days. Feel free to comment and request for this issue to be reopened.
