### ISSUE TITLE
Add table name suggestion where adding SQL table

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#1221]
Right now when I'm adding SQL table I have to write table name.
It'll be nice to have table name completion in this view.

**Comment by invenis-paris** [comment]
Or a drop down menu with table discovered in the DB

**Comment by xrmx** [comment]
@invenis-paris a PR would be more than welcome!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 343 days. Feel free to comment and request for this issue to be reopened.
