### ISSUE TITLE
Role assignment issue 

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#12243]
Hi, 
   i am try to create a user (not a admin )only who is responsible for usermanagment ( exclude other permissions ).
i want him to create users and assign roles to them except admin permissions 

summary : creating a user who's is not able to create admin users  

Reply me the possibilites @mistercrunch 

thanks

**Comment by dpgaspar** [comment]
One possibility:

You have to custom develop a new list users views with a custom CRUD, on the edit and add form filter out the `admin` role. Then the user creator must only have permissions to this view (He can't be a full admin).

**Comment by dpgaspar** [comment]
Going to close this one here, since it's replicated on FAB: https://github.com/dpgaspar/Flask-AppBuilder/issues/1538
