### ISSUE TITLE
[explore]filter custom SQL editor is broken, adding undefined clause 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#12266]
![ezgif-4-e27b99a5cbe4](https://user-images.githubusercontent.com/67837651/103616534-79065b80-4ee1-11eb-9831-b7d68c27bd39.gif)

latest master 11pm 1/4/2021
this is a further regression of what we encountered during the holiday. 

-----------------
last week on master 
![1 (1)](https://user-images.githubusercontent.com/67837651/103616648-a8b56380-4ee1-11eb-8320-8bbd036fe6e1.gif)

@kgabryje P1 issue, release blocker. please address it asap. 🙏

**Comment by villebro** [comment]
I am unable to repro the `undefined undefined` problem on master, but did notice that writing a custom filter doesn't enable the Save button unless the simple filter has been populated (see pic below). I'll work on fixing that, now.
![image](https://user-images.githubusercontent.com/33317356/103618220-420f6480-4f38-11eb-8749-a8b9f28e6c0e.png)

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 6:38pm (UTC)

cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
