### ISSUE TITLE
Time range filter dropdown does not fit the window

### ISSUE THREAD

**Issue by adam-stasiak** [apache/incubator-superset#12276]
## Screenshot
https://user-images.githubusercontent.com/25153919/103649363-9cbbb700-4f5e-11eb-998d-9c2963b64219.mov

## Description

When I open modal to edit time range and choose no filter - I am not able to see all options in dropdown.

**Comment by zhaoyongjie** [comment]
The master branch has been fixed. thanks for your report

**Comment by junlincc** [comment]
<img width="1784" alt="Screen Shot 2021-01-05 at 7 30 04 AM" src="https://user-images.githubusercontent.com/67837651/103665106-e4731c00-4f27-11eb-927a-fc4da088b2a7.png">

thanks Adam! i can confirm this issue has been resolved in latest master.
