### ISSUE TITLE
Support for emailing reports at regular intervals?

### ISSUE THREAD

**Issue by jasonshah** [apache/incubator-superset#1231]
Hi,
I started exploring Caravel this past week, and I'm loving it. I am exploring working with my engineering team to roll it out as an enhancement/replacement to our internally-built reporting solution.

Are there any plans to support emailing a Dashboard nightly/weekly to users as PDF? While the solution is obviously more powerful when you interact with it on the web, there are a number of users who could benefit from what Dashboards offer if they could see an email with a snapshot of the Dashboard in-line or as an attached PDF. A user would be able to request a Dashboard to be emailed to them nightly or weekly on a specified date, and the admin would be able to configure the email server through which the Dashboard is sent.

This would allow us to centralize towards use of Caravel as a platform for more use cases, vs. implementing/retaining another solution that is specifically suited to this purpose.

(I would have posted this to the Google Group, but my membership is still pending.)

**Comment by williaster** [comment]
Hi @jasonshah, we're currently discussing the addition of a feature like this internally. Specifically we'd like to support an api for fetching a static image of a given chart or dashboard, which could then easily extended to send out emails automatically. 

Will post back as soon as we've settled on a technical solution for the implementation and have a better idea of the timeline. 

cc @ascott

**Comment by malleshm** [comment]
Hi Williaster,
  I have tried to implement this feature for one of the chart, I have ended up with the idea of writing response content of the "standalone endpoint" to PDF.So that we can get static charts in PDF format.

but I couldn't able to add one more option for PDF export in the "js-explore-actions".
@sidnakoppa

**Comment by williaster** [comment]
do you have a PR, or can you provide more information about how you implemented the pdf export?

we are thinking about using a headless browser to take screenshots of dashboards (so the result would be a .png) with a couple of size options. adding the ability to directly download a chart from the explore page would also be pretty cool and potentially useful.

**Comment by tjspross** [comment]
Seconded. I'm very interested in this feaure being added.

**Comment by ErikThoreson** [comment]
+1

**Comment by ssindhu3** [comment]
+1, Please update if this is going to be prioritized.

**Comment by mistercrunch** [comment]
I worked on integrating a headless browser to render chart images but never got around to finish the work:
https://github.com/mistercrunch/superset/tree/phantom

**Comment by htruongaff** [comment]
Definitely is a hotly requested feature from our userbase.

**Comment by xrmx** [comment]
@htruongaff then that's a good chance to contribute the work and make both the superset community and your userbase happy 👍

**Comment by kotharitrisha** [comment]
Any updates on this? @williaster

**Comment by deyani27** [comment]
@htruongaff , do we have any update on this post. we are also looking for the same feature.

**Comment by JImBurris** [comment]
+1

**Comment by covilpm** [comment]
Any update on this?

We're looking for a similar kind of feature, and would be keen to collaborate on its creation.

**Comment by xrmx** [comment]
@corvilpm looking forward to your pr :+1

**Comment by corvilpm** [comment]
Is there an existing fork or branch where this project as been started?

**Comment by deyani27** [comment]
+1

**Comment by Tsuki** [comment]
+1

**Comment by kuvsh** [comment]
Hello. We also need this feature badly.

**Comment by afullana** [comment]
+1

**Comment by mahendra** [comment]
I have a PR for this feature - https://github.com/apache/incubator-superset/pull/5294 

Use Firefox / Chrome headless browsers. It also works with phantomjs, if needed.

**Comment by ruchimann** [comment]
+1

**Comment by Webysther** [comment]
I switch from superset to redash because of lack of support alerts, only the pay version? sad.

**Comment by nabhosal** [comment]
We are using superset with schedule report emailing, it works great for us. In the below article, we have published steps to make deployment easy for superset with schedule report emailing.
[https://medium.com/@nileshxbhosale/apache-superset-a-cost-effective-alternative-to-quick-sight-for-data-lake-668868fe51c7](https://medium.com/@nileshxbhosale/apache-superset-a-cost-effective-alternative-to-quick-sight-for-data-lake-668868fe51c7)

**Comment by visakhmurukes** [comment]
@nabhosal  I tried your method. However I'm getting an error on docker logs when trying to schedule email reports. The message looks like this

**selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities**

What version of Firefox you've installed? Have you installed anything else other than the ones which came with docker?
