### ISSUE TITLE
Provide pivot table with date column

### ISSUE THREAD

**Issue by cuph62** [apache/incubator-superset#1239]
Currently the date column cannot take part of the pivot table view.
Feature request to add a date (or date function month, year ...) as a part of a pivot table
eg. It would be nice to have a  summary pivot table with rows by  month / cols by category with sum_consumptions  to show time evolution in a textual way.

**Comment by yehjames** [comment]
any update for this issue?

**Comment by xrmx** [comment]
@yehjames have you tried to reproduce with latest release?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. Feel free to comment and request for this issue to be reopened.
