### ISSUE TITLE
GPL licence for select2.sortable.js?

### ISSUE THREAD

**Issue by michailsal** [apache/incubator-superset#1270]
Is this intentional? Were you aware of it? I find rather complex dealing with JavaScript libs GPL licensed......

**Comment by xrmx** [comment]
Maybe not ideal but i don't see how that's a problem for a user.

**Comment by michailsal** [comment]
For a user no, indeed, but for a company that wants to offer the tools to its customers it is, unless if this not the goal/intention of the community.

**Comment by xrmx** [comment]
If you are doing SaaS GPL it is not an issue at all but thank for pointing out the issue.

**Comment by xrmx** [comment]
I think this will be superseded by #753

**Comment by mistercrunch** [comment]
Oh snap. We'll have to get rid of it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 555 days. Feel free to comment and request for this issue to be reopened.
