### ISSUE TITLE
Allow setting defaults for filters

### ISSUE THREAD

**Issue by jwthomp** [apache/incubator-superset#1280]
For many of our dashboards it would be helpful to have our filters pre-selected to certain values. 

As an example, we run internal playtests of games we are making. The data for these tests are tagged with a string value. During these tests, this is the data that everyone is looking at and we would like to have the filter set to default to that information.

**Comment by mrjadav** [comment]
This feature would be super helpful. Is this available now?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 248 days. Feel free to comment and request for this issue to be reopened.
