### ISSUE TITLE
UI controls for that expose `immune_to_filter` dashboard options

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1285]
Using 0.11

Dashboard containing:
- single filter (+ date filter)
- time series chart
- table view

Table view can be used for filtering by selecting rows (that's great). However if we perform following flow:
1. Select N rows from table view
2. Change date range /from/to

Effect: data is filtered correctly but table view instead of containing all rows with N selected, removes all rows except of those N which were previously selected - which makes it impossible to read other data or change table view filter

**Comment by DaimonPl** [comment]
Just checked that same problem happens with 2 different table views - after filtering with second one, first one displays only those N previously selected items and it's not possible to "drill up"

**Comment by mistercrunch** [comment]
I took some time to document "How to add dynamic filters to a dashboard?" in the FAQ, it's a bit burried and new, so you may not have found it.
http://airbnb.io/caravel/faq.html#how-to-add-dynamic-filters-to-a-dashboard

Depending on the behavior you want, I'd recommend using the `filter_immune_slices`or `filter_immune_slice_fields ` configuration in your dashboard.

**Comment by DaimonPl** [comment]
Thx for info i'll give it a try!

In that case this ticket could be used to somehow improve such setup - some kind of gui settings? (for people who don't feel well with any kind of markup :) )

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 525 days. Feel free to comment and request for this issue to be reopened.
