### ISSUE TITLE
Table view within dashboard displays duplicated scrollbars

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1286]
As in title, table view within dashboard displays duplicated scrollbars

![scrollbars](https://cloud.githubusercontent.com/assets/9693936/19182593/46b26c02-8c74-11e6-927d-677be5ac15fc.png)

**Comment by xrmx** [comment]
Is this 0.11?

**Comment by DaimonPl** [comment]
Yep 0.11 installed from pip.

It displays this way even when resizing to much bigger on dashboard

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 562 days. Feel free to comment and request for this issue to be reopened.
