### ISSUE TITLE
Time series "Range Filter" could perform dashboard time filtering

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1288]
There's very nice functionality in time series called "Range Filter"

It would be great if it would act as time filter on entire dashboard (in that case it should also update time filter if present)

**Comment by xionchen** [comment]
rep Time option in FilterBox #665 ?

**Comment by DaimonPl** [comment]
Time option in filter box is OK itself.

My suggestion is to enhance "Range Filter" in "time series" view to act as time filter for other slices when used on dashboard

**Comment by mistercrunch** [comment]
Any slice widget can broadcast filter events to the controller, it's just a matter of capturing the event and broadcasting the right thing.

I'm not sure how intuitive this would be but it wouldn't be hard to make it work. Say if you had 2 line charts and apply a time filter on one of the 2, user may expect no changes to the other chart, or some client-side cross filtering (which we don't and won't support).

If anyone wants to work on that feature, I'd like to have an extra boolean "Time Filtering Affects Dashboard" and have it unchecked by default.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 555 days. Feel free to comment and request for this issue to be reopened.
