### ISSUE TITLE
Slice CSV export from dashboard

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1304]
Slices have ability to export data to CSV but it's not possible to do from dashboard

It's possible to open slice from dashboard to do that, but after opening slice, all dashboard filtering is lost and has to be repeated in slice

**Comment by harryprince** [comment]
the same demand. need to export data in dashboard.

**Comment by pajachiet** [comment]
We also need this feature. It would allow to create a pure *visualization consumer role*. This role would have less permission than the gamma role : with the permission to see dashboards, to download the aggregated data, but not to explore freely the raw data on the slice view.

We did not dive in superset source code yet. Do you have an estimation of the complexity to implement it ?

**Comment by lilila** [comment]
@pajachiet : If it helps, I created an "Omega" role with the following permissions : 
can profile on Superset, can request access on Superset, menu access on Dashboards, can list on DashboardModelView, can list on DashboardModelViewAsync, can datasources on Superset, can dashboard on Superset, can slice on Superset, can explore json on Superset, can fave dashboards on Superset,can explore on Superset, can fave slices on Superset, can csv on Superset

It does more or less what you need

**Comment by sergderevyanko** [comment]
Super useful feature!

**Comment by shrutimkrishnan** [comment]
We need the same feature - anybody able to bring csv export option on to dashboard without going into explore view?

**Comment by napjon** [comment]
Same here, we need to disable "explore chart" option. We want to limit certain users to avoid all the hassle when they go to explore chart.

Export CSV is really crucial for analyst users.

**Comment by mistercrunch** [comment]
Decided to tackle this since many care about it and it's very easy
https://github.com/apache/incubator-superset/pull/3280

**Comment by napjon** [comment]
Awesome! Many thanks @mistercrunch!

**Comment by DaimonPl** [comment]
Great :)

**Comment by DaimonPl** [comment]
Unfortunately it does not work properly. Bug created in https://github.com/apache/incubator-superset/issues/3455

**Comment by solomoup** [comment]
Hello! I'm trying to export csv from dashboard. The problem appears in Public Role although i have enabled the "can csv on Superset" permission. As you can see in the image below "Export CSV" is not given as an option. As an Admin Role however the specific option is available. Do i need to do anything else in order to export CSVs from dashboard? Thanks in advance!
![image](https://user-images.githubusercontent.com/67665217/127322838-30d5b19e-f1be-44d3-bc8b-6e4452c5c9b1.png)

**Comment by solomoup** [comment]
@pateli18 Thanks for your reply. Unfortunately no. Actually Ι've noticed that Ι must log in as a user in order to be able to export data as csv. From public link of dashboard it's impossible despite the fact that Ι have enabled the "can csv on Superset" permission for the public role.

**Comment by danielramirez** [comment]
> @pateli18 Thanks for your reply. Unfortunately no. Actually Ι've noticed that Ι must log in as a user in order to be able to export data as csv. From public link of dashboard it's impossible despite the fact that Ι have enabled the "can csv on Superset" permission for the public role.

No news about this? This functionality is crucial for the platform. Currently I'm not able to do this even setting the permission to the Public role.

**Comment by jackgray** [comment]
@danielramirez  you might find my gist useful. I recently got embedded dashboards working in a react app with csv exporting with slicing

https://gist.github.com/jackgray/138c780a0a9e3a59ab51af98da322119

**Comment by rusackas** [comment]
@jackgray thanks... if you think there's a way that this can be improved by a PR (either code or docs) it would be appreciated!
