### ISSUE TITLE
Access variables for less in main.css

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#1309]
I was trying to access variables from '/stylesheets/less/cosmo/variables.less' in Sqllab's main.css, but the variables couldn't be loaded. 
The current flow is sqllab.html extends basic.html, basic.html reference css-theme.js, which requires index.less. The script for sqllab.html is sqllab.jsx, which requires main.css. But somehow variables from less files are not accessible in main.css, It could be that main.css is loaded before less file is imported?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 559 days. Feel free to comment and request for this issue to be reopened.

**Comment by sodevious** [comment]
Superset should provide either better documentation or some kind of way to override less/css files that get included with the build (as templates are easily overrideable/extendable). Essentially to theme Superset. The only way I'm seeing to do this is rolling something custom, which would be fine, except any css/less changes going forward would have to be manually applied/hard to maintain.
