### ISSUE TITLE
Date picker for time filter

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1318]
Current time filter accepts textual values like "1 year ago" and "2016-06-01"

It would be nice to have a date picker, so there's no need to type in values like "2016-06-01"

**Comment by xrmx** [comment]
Dup of #767?

**Comment by DaimonPl** [comment]
Yep looks to be the same one

**Comment by zsombor9** [comment]
It also would be great, if i could edit what i set.
e.g. if i set 2016-05-12 and I want to modify it to 2016-05-10 I have to write the whole new text again. 

thanks!

**Comment by mistercrunch** [comment]
A date picker wouldnt allow for relative dates which i think is important. Maybe eventually we can have a fancy React component that does both fixed and relative nicely.

**Comment by vschoener** [comment]
Any news about it ? Didn't find any way to write or select a date directly in the dashboard :(

**Comment by DaimonPl** [comment]
It looks that date picker is added in Slice view but dashboard date filter still does not support it

**Comment by mistercrunch** [comment]
It's in now

**Comment by jpvelsamy** [comment]
mistercrunch,
would you mind telling us which release should we check out for using this feature

**Comment by DaimonPl** [comment]
@jpvelsamy it works fine with 0.20.4

**Comment by Danielmrg** [comment]
https://github.com/apache/superset/issues/2579
