### ISSUE TITLE
Cannot connect to MySQL view

### ISSUE THREAD

**Issue by ombre04** [apache/incubator-superset#1338]
I did connected to data base. I can select table of my choosing, however when I'm trying to connect to a view in this schema it returns: 

> Table [table_name] could not be found, please double check your database connection, schema, and table name '.

I tried it on several dbs with the same result.
Any one experienced the same problem?

**Comment by rich-lloyd-judd** [comment]
Yep, I had a similar problem. I'd created a read-only MySQL account for Caravel to use but hadn't granted it the 'show view' privilege. Fixed that and Caravel happily pulled in the views.

**Comment by mistercrunch** [comment]
If you can reproduce it by providing a falling unit test I can look into it.

**Comment by ombre04** [comment]
@rich-lloyd-judd my user has privileges 'show views' and despite that it didn't recognise/load view

**Comment by ombre04** [comment]
@mistercrunch  I'm not quite sure how could I provide test for this case

**Comment by mistercrunch** [comment]
Which sqlalchemy driver are you using? Are you sure that your user has access to that view? Views work well for me using `mysqlclient`

**Comment by althorian** [comment]
I have the same issue, I am using mySQL and superset (0.23.2) connecting to the database with mysql+mysqldb. The tables I can see just fine but the view does not show up at the bottom of the database source page when I test the connection. In mySQL the user account for superset has been granted 'show view' and 'show databases'.

**Comment by ahmad27** [comment]
It worked for me when i clicked  the  SQL LAB tab and then SQL EDITOR and selected the view from there, Hope this helps

**Comment by althorian** [comment]
Excellent tip, I can see it under the SQL LAB.

thanks!

**Comment by ruffyleaf** [comment]
was unable to connect to a view as well, however, it worked ok in SQL Lab. Superset v 1.5.0
