### ISSUE TITLE
Error when creating the time line slice.

### ISSUE THREAD

**Issue by yatany** [apache/incubator-superset#1348]
I am new to Caravel and now I am trying to build the slice using the MySQL database.
When creating the time series line chart, it always prompts "{"error": "Unknown string format"}".

What is strange is that the table view is OK.

Attachment 1 is the table view, 

![screen shot 2016-10-14 at 5 00 31 pm](https://cloud.githubusercontent.com/assets/22834211/19381786/d41b1be6-922f-11e6-836b-363b1c0b8766.png)

and the attachment 2 is the time series view.

![screen shot 2016-10-14 at 5 00 57 pm](https://cloud.githubusercontent.com/assets/22834211/19381787/d4200ab6-922f-11e6-8f6b-d2bad9225149.png)

Thanks for any body's help!

**Comment by mistercrunch** [comment]
What's the database type of `BalanceDate`? If it's a string of some kind you may have to fiddle with these for your date column:
<img width="704" alt="screen shot 2016-10-14 at 8 18 02 am" src="https://cloud.githubusercontent.com/assets/487433/19392709/cfa617a8-91e6-11e6-997c-2c69d54fc040.png">

**Comment by yatany** [comment]
The datatype is DATE, please see the screen shot.
![screen shot 2016-10-17 at 10 16 02 am](https://cloud.githubusercontent.com/assets/22834211/19423418/c4b01952-9452-11e6-9774-3a7ca0fd7a25.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 553 days. Feel free to comment and request for this issue to be reopened.
