### ISSUE TITLE
Add support for markers in charts

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#1350]
Static horizontal lines can be used for targets or baselines in charts. Similarly vertical bands can be used for markers of events in time on timeseries. I can picture a new panel on the explore view with option to create these markers. 

It relates to the idea of annotations somehow. Users should be able to define one or many (horizontal, vertical, or point) markers and perhaps style them somehow (color, stroke-width, opacity). We may want to thing of markers in terms of ranges as well, where say Ramadan is a period those could be highlighted. These markers should probably have some sort of hoverable anchor with a tooltip.

**Comment by alexisrosuel** [comment]
Hi @mistercrunch !

This feature would be very useful ! Is it still planned ? 

Thanks !

**Comment by KennethEnevoldsen** [comment]
Is there an update on this thread?

**Comment by zhaoyongjie** [comment]
annotation layer work for this function
