### ISSUE TITLE
Column/Metric description tooltips missing

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#1367]
It's possible to add column/metric description in data source but it looks they are not used.

It would be great if those descriptions were displayed on visualizations (for example after mouse over column name)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 550 days. Feel free to comment and request for this issue to be reopened.

**Comment by rubypollev** [comment]
This would be really awesome!
