### ISSUE TITLE
table view viz doesn't use time grain with Sqlalchemy table

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#1370]
Hi,
I want to create table view where counts are grouped by day.
I'm setting time grain to day but this has no effect.

I'm connecting to MySQL table. 
Caravel version 0.11.0

![caravel](https://cloud.githubusercontent.com/assets/4006010/19496238/f053cb46-9586-11e6-8882-145134001c75.jpg)

**Comment by xrmx** [comment]
Only time related visualization are affected by the time settings: table view is not one of them.

**Comment by xrmx** [comment]
Said that on my pre 0.11 installation i can't use the time column as group by clause. @maver1ck do you see the same on 0.11?

**Comment by maver1ck** [comment]
@xrmx 
I don't agree with you.
When I'm using druid I can use Time Granularity.

![caravel](https://cloud.githubusercontent.com/assets/4006010/19510729/b5ff917e-95e4-11e6-97f3-abd365288bfe.png)

**Comment by xrmx** [comment]
So you agree with me with something is broken :)

**Comment by maver1ck** [comment]
Yep.
Thanks for "bug" label.

**Comment by zhaown** [comment]
We are using superset 0.13.2 with druid datasource, setting up a table viz with one day granularity since 7 days ago, but the actual query is with `granularity: all`, so no time column in the result table, is this a feature or a bug?

Thanks.

**Comment by maver1ck** [comment]
I think it's a new bug.

**Comment by fangyeqing** [comment]
I have make a merge request,https://github.com/airbnb/superset/pull/1809

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 499 days. Feel free to comment and request for this issue to be reopened.
