### ISSUE TITLE
Multiple filters on 1 dashboard - different behaviour since 0.11 ?

### ISSUE THREAD

**Issue by cuph62** [apache/incubator-superset#1374]
In 0.10:  multiple filters with different filter fields , were dependent, 
eg filter1 was applied while selecting for filter2 in 0.10.
This does not seem to be the case in 0.11 : is there an option to get the same behaviour as in 0.10 ?

**Comment by cons0l3** [comment]
I did not know that the behaviour changed, but I asked something related on the google news group. sadly no one has respondend yet: https://groups.google.com/forum/#!topic/airbnb_caravel/3x94DhRv7Zg

I have also filed a bug #1363 as the fields in a filter on a dashboard are not shown by there display name but rather there technical name...

**Comment by mistercrunch** [comment]
I just replied on that google group thread.
http://airbnb.io/caravel/faq.html#how-to-add-dynamic-filters-to-a-dashboard

**Comment by cuph62** [comment]
this did not help me in this regard, because this describes how filters can be "independent"
http://airbnb.io/caravel/faq.html#how-to-add-dynamic-filters-to-a-dashboard

Even if I use multiple filter boxes, the first filter is not applied to the second  (since I used the 0.11, it used to wrok in 0.10)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 549 days. Feel free to comment and request for this issue to be reopened.

**Comment by aleh-arol** [comment]
Dependent filters doesn't work. 

E.g. if I have one filter box with 2 filters - e.g. application and subscription where (in the data source) subscription depends from application - then if I choose certain application the list of subscriptions is not refreshed. 
Expected (subjective :) ) behaviour is multifilter filter box applies to itself.

From the viz.py looks like dynamic filters are not applied to the filter box slice or at least they're not reapplied per filtered column. E.g. in FilterBox viz query object is constructed once per run_extra_queries call from super().query_obj() where inside there's process_query_filters which is (as far as i understand) is applying dynamic filters. Later when looping over filter columns that query object is not updated.

Please advise/reopen.
superset version is ebb7fbc5f024379361f301a86b770e0cc1a932cd
