### ISSUE TITLE
Tooltip in line charts does not appear when pie chart on top in dashboard

### ISSUE THREAD

**Issue by cuph62** [apache/incubator-superset#1375]
Tooltip in line charts does not appear when pie chart on top in dashboard,
when I switch both charts (line chart on top of page in dashboard and pie underneath) , the rich tooltip is present.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 550 days. Feel free to comment and request for this issue to be reopened.
