### ISSUE TITLE
Bug with word cloud size

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#1383]
[Bug] Word cloud doesn't seem to get the right size for the corresponding metric. If a word is too large, it won't show on the viz.
[Proposed solution] Max font size needs to be lowered for word cloud viz.

**Comment by bcreusot** [comment]
Hello,

Just to add some contexts. It seems than on the Slices View it works we can see everything but when put into a dashboard some words disapear...

Thanks

**Comment by sivackrishna** [comment]
Hello,
I am getting different results even i ran the report in Slices view.  Sometimes we are missing the top records and  sometimes randomly we are missing. I thought it was a bug. Please respond anyone to resolve this issue.

Thanks

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. Feel free to comment and request for this issue to be reopened.
