### ISSUE TITLE
[Feature] Update metrics when columns are updated

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#1392]
When initially loading a datasource, metrics are created automatically based on the data type. 
When user goes in the edit metadata for the tables/columns, default metrics should be updated accordingly.
 (i.e. when metadata is changed from 'Sum' to 'Count Distinct', sum metric should be removed)
Currently there's no option to change this when connecting a new table, the user has to go back and revise the table meta-data

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 549 days. Feel free to comment and request for this issue to be reopened.
