### ISSUE TITLE
Supporting oracle

### ISSUE THREAD

**Issue by ShengyaoQian** [apache/incubator-superset#1401]
We are connecting to oracle on caravel, but we are having problems inserting into oracle db using sqlachemy, it's not auto generating primary keys. Does caravel support oracle now? Is there a way to have id auto generated for oracle?

**Comment by xrmx** [comment]
Looks like this?
http://docs.sqlalchemy.org/en/latest/dialects/oracle.html#auto-increment-behavior

**Comment by xrmx** [comment]
@ShengyaoQian One question: you are reporting having issues installing caravel on oracle right?

**Comment by mistercrunch** [comment]
This is related to how SqlAlchemy handles Oracle, it seems like it may be possible to handle it with database and/or sqlalchemy configuration.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 542 days. Feel free to comment and request for this issue to be reopened.
