### ISSUE TITLE
[sqllab] fix username to jinja context while in async mode

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#1490]

**Comment by pranavoyo** [comment]
any update on this please?

**Comment by villebro** [comment]
Attn: @pranavoyo, this is already implemented.

<img width="937" alt="screen shot 2018-04-02 at 21 24 57" src="https://user-images.githubusercontent.com/33317356/38209239-66c87c7c-36bc-11e8-9b61-f7216d34d7b2.png">

**Comment by mistercrunch** [comment]
Looks like it may not work in `async` mode though, going to hijack the issue and change the title.
