### ISSUE TITLE
WorldMap coloring makes countries invisible

### ISSUE THREAD

**Issue by mwullink** [apache/incubator-superset#1497]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the caravel logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of caravel
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
 0.11.0

### Expected results

World map with all the countries visible

### Actual results

When 1 country has a high count value it gets a very dark color, the countries with a low count value are rendered white and they not visible anymore.

### Steps to reproduce

Create set of countries with 1 country having a high count and the others with very low count. only the country with the high count and the countries without counts are visible.

**Comment by Igosuki** [comment]
Most likely there is a gradient multiplied by the value, if value is zero then it is white instead of light.
The calculation should use a base color as a threshold.

**Comment by olbapito** [comment]
This is still the behavior. Is there any workaround to alter the color scale? 
Thanks!

**Comment by Tyler-Rex** [comment]
I now how the issue of countries with a 0 being darker than countries with a 1. Using 0.25.0.

**Comment by vladnvo** [comment]
The same issue

**Comment by huntg** [comment]
Still seeing this issue
