### ISSUE TITLE
Data authority supports

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1515]
Make sure these boxes are checked before submitting your issue - thank you!

- [Yes] I have checked the caravel logs for python stacktraces and included it here as text if any
- [Yes ] I have reproduced the issue with at least the latest released version of caravel
- [Yes ] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
All taged version.

### Expected results
Data authority,for the same or dashboard slice, different roles or users can query the data of different ranges.

### Actual results
The current version does not support data authority.

### Steps to reproduce
We are going to develop the data authority for caravel.

In addition,we are a software research and Development Center of HAND(www.hand-china.com) from China.And we are going to use Caravel as our data visualization tool,but the functions of Caravel is not comprehensive compared with Oracle BIEE\SAP BO\QlikView，so later we plan to develop a number of features.

**Comment by xrmx** [comment]
Care to explain in a bit more details what do you want to implement? Thanks!

**Comment by ganshanshan** [comment]
Dear xrmx,

My goal is the same as #1498, but our idea is that ,
**First**,we build a session variable named as USER or ROLE in Caravel.
**Second**,we should have a customized database table named W_AUTH_DEPARTMENT_D,which has two core column ROLE,DEPARTMENT_ID.
**Then**,we develop a data-auth function in the Table ,with which we can join the table with W_AUTH_DEPARTMENT_D where W_AUTH_DEPARTMENT_D.DEPARTMENT_ID = table.department_id and W_AUTH_DEPARTMENT_D.ROLE =@{ROLE}.

Before the Caravel,we have implemented Oracle BIEE,SAP BO for several years,we have tried many type data-auth in BIEE or SAP ,but the above is the best one.

**Comment by ganshanshan** [comment]
Sorry xrmx.

Our goal is different from #1498.

I think his goal is to analysis the data which come from different database in the same slice .

**Comment by bkyryliuk** [comment]
@ganshanshan - will creating views solve your usecase ?
You can create views on the table with the give ranges and then grant access to the view in caravel ?

**Comment by ganshanshan** [comment]
@bkyryliuk sorry ,i think you do not have my idea.what i want is that for **the same Table** in caravel ,USER_A can query the range is different from USER_B.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 525 days. Feel free to comment and request for this issue to be reopened.
