### ISSUE TITLE
Request for a way to set default sort order in a Table View & Pivot Table View

### ISSUE THREAD

**Issue by verysmallriver** [apache/incubator-superset#1523]
- [n/a ] I have checked the caravel logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of caravel
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

I would like a way to sort Table View based on an arbitrary column and to be able to choose the order as either descending or ascending.

On April 2016, @jacopoch and @mistercrunch wrote on gitter:

> Jacopo Chiapparino @jacopoch Apr 25 21:32
> Hi guys, I was wondering if there's any way to currently sort Viz Type "table" via the "Params" in the edit slice panel? I'm looking into pre-sorting a table in a specific way when the dashboard/slice is loaded (like, first column of the table, desc). Any help appreciated! Thanks!
> 

> Maxime Beauchemin @mistercrunch Apr 27 13:43
> @jacopoch sorry about the delay, I think at the moment the default is to sort on the first metric in the table
> the row limit also applies based on that sort order
> if it's important to you, you can create a github issue

@maver1ck asked the same question on Sept 2016

> Maciej Bryński @maver1ck Sep 23 00:56
> Hi,
> I've got a question
> How can I specify sorting for table vizualization ?
> It defaults to descending on first aggregation
> Is there any option to change it ?
> 

This still doesn't seem doable.

### Caravel version
0.12

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 467 days. Feel free to comment and request for this issue to be reopened.

**Comment by darshanajr** [comment]
Is this functionality being implemented?

**Comment by darshanajr** [comment]
![ordering not working](https://user-images.githubusercontent.com/4464657/72718399-e3709f80-3b9b-11ea-9d3b-25f8c5d7151a.JPG)

If I click the ordering icon in the top right corner of the chart, it will order. Shouldn't it be the default behavior if I already set the ordering?

**Comment by mistercrunch** [comment]
Screenshots are very outdated and guessing some progress has been made. I suggest opening a fresh issue with up-to-date screenshots.
