### ISSUE TITLE
SQL Lab + datasource/table permissions

### ISSUE THREAD

**Issue by wyndhblb** [apache/incubator-superset#1531]
This is more  "feature" request then anything, but in a sense it's also kind of a bug around permissions.

The senerio

1. a user is a "Gamma" users
2. They are allowed to query a {datasource}.{table} 
3. They are given {SQLlab} permissions too.

The user goes to the sql interface some issues

1. they can see any datasource they want in the dropdown
2. in any given data source they can see an table/schema and query it

Seems like that is a violation of perms.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 536 days. Feel free to comment and request for this issue to be reopened.

**Comment by deepak-goel** [comment]
@mistercrunch This is a genuine issue and seems like a violation of permissions. Can somebody please look into this. 

User with a "gamma" + datasource role isn't able to query "main" database in SQL Lab, but is able to query other databases even without datasource/database permissions on those databases.

**Comment by deepak-goel** [comment]
Never-mind, the results were coming from cache. This is working as expected.
