### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by hustxiaofeng** [apache/incubator-superset#1533]
after npm install, then excute 'npm run dev', it throws error as follow:
============================
```
ERROR in ./~/react-map-gl/src/overlays/scatterplot.react.js
Module parse failed: /home/fwyan/caravel-master/caravel/assets/node_modules/react-map-gl/src/overlays/scatterplot.react.js Unexpected token (112:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (112:6)
```

**Comment by hustxiaofeng** [comment]
node version 6.9.1
npm version 3.10.8

**Comment by mistercrunch** [comment]
I looked at the line reference and it looks like a jsx statement is in there while the file doesn't have  `jsx` extension.  I can't recreate the issue but I'd look in the direction of how webpack supports jsx in non-jsx file.

**Comment by hustxiaofeng** [comment]
@mistercrunch ,  [browser](https://github.com/airbnb/caravel/issues/1534),  console show the error, all related about dataTable, i find that in the dist js files, for example, in dist/dashboard.xx.js, the datatable.net.bs is loaded as AMD:
![image](https://cloud.githubusercontent.com/assets/7539662/20044200/b5d1996c-a4d1-11e6-9d79-7ae57fb571a2.png)

the if statement get a true const, but in datatable.net.bs's node modules, the if statement is a express as "typeof define === 'function' && define.amd", the npm run dev replace the express as 'true' in output dist js, i attemp to modify it as false in dist js file, and then it works well, but i don't know what cause the issue. i find other js error almost the same related to datatable in webpack:
![image](https://cloud.githubusercontent.com/assets/7539662/20044263/5e64bdca-a4d2-11e6-8c84-961e3fcfd968.png)

**Comment by wo8000** [comment]
me too,
npm run prod
ERROR in ./~/.1.7.2@react-map-gl/src/overlays/scatterplot.react.js
Module parse failed: /data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.1.7.2@react-map-gl/src/overlays/scatterplot.react.js Unexpected token (112:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (112:6)

How to solve？？@hustxiaofeng

**Comment by toabey** [comment]
inside mapbox.jsx
 you can change 'react-map-gl/src/overlays/scatterplot.react.js'  to 
'react-map-gl/dist/overlays/scatterplot.react.js' and try

**Comment by huanruiqi** [comment]
can anybody solve this problem?

**Comment by dennybiasiolli** [comment]
Have you tryed "rm -rf node_modules" and then "npm install"?

**Comment by wo8000** [comment]
is it fixed??

**Comment by wo8000** [comment]
thank you!! @toabey

**Comment by TingYinHelen** [comment]
I met the same problem. @dennybiasiolli I tried many times but still not work:(

**Comment by TingYinHelen** [comment]
@toabey Thank you

**Comment by zoiew** [comment]
when "npm run dev" find Error,

ERROR in ./~/.15.3.2@react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in /Users/zoiew/Downloads/superset-master/superset/assets/node_modules/.15.3.2@react-dom
 @ ./~/.15.3.2@react-dom/index.js 3:17-46

how can i solve this problem?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 486 days. Feel free to comment and request for this issue to be reopened.
