### ISSUE TITLE
jquery is not defined

### ISSUE THREAD

**Issue by jeromecn** [apache/incubator-superset#1537]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the caravel logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of caravel
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
0.12.0

### Steps to reproduce
npm run prod

/caravel/explore/table/12/?since=1+year+ago&datasource_id=8&slice_id=139&viz_type=cal_heatmap&row_limit=50000&domain_granularity=month&until=now&json=false&slice_name=Calendar+Heatmap+multiformat+7&subdomain_granularity=day&granularity=day&datasource_name=multiformat_time_series&granularity_sqla=string3&where=&datasource_type=table

ERROR:
ReferenceError: jQuery is not defined

**Comment by jeromecn** [comment]
Reason:
 node_modules/mapbox-gl-js/js/util/browser/web_worker.js
`'use strict';

const WebWorkify = require('webworkify');
const window = require('../window');
const workerURL = **window.URL.createObjectURL(new WebWorkify(require('../../source/worker'), {bare: true}));**

module.exports = function () {
    return new window.Worker(workerURL);
};`


 webworkify:
https://github.com/substack/webworkify/blob/master/index.js
`    var blob = new Blob([src], { type: 'text/javascript' });
    if (options && options.bare) { return blob; }
    var workerUrl = URL.createObjectURL(blob);
    var worker = new Worker(workerUrl);
    worker.objectURL = workerUrl;
    return worker;`

Fix:
`'use strict';

const WebWorkify = require('webworkify');
const window = require('../window');
const workerURL = **new WebWorkify(require('../../source/worker'), {bare: true});**

module.exports = function () {
    return new window.Worker(workerURL);
};`

**Comment by mistercrunch** [comment]
Which browser is that?
