### ISSUE TITLE
Add ability to create queries using WITH statements

### ISSUE THREAD

**Issue by jefffeng** [apache/incubator-superset#1547]
Add ability to create queries using WITH statements.

The SQL WITH clause allows you to give a sub-query block a name (a process also called sub-query refactoring), which can be referenced in several places within the main SQL query. The name assigned to the sub-query is treated as though it was an inline view or table. The SQL WITH clause is basically a drop-in replacement to the normal sub-query.

**Comment by mistercrunch** [comment]
This should work as long as "Allow DML" is true
<img width="945" alt="screen shot 2016-11-06 at 7 45 35 am" src="https://cloud.githubusercontent.com/assets/487433/20039209/09b949cc-a3f5-11e6-8680-0d80b40940a0.png">

**Comment by jefffeng** [comment]
Is "Allow DML" on by default?

**Comment by mistercrunch** [comment]
Nope, all of the above checkboxes aren't checked by default

**Comment by mrshu** [comment]
I believe this should be possible in newer versions of Superset even without "Allow DML" being set. Would you find that to be accurate @mistercrunch ?

**Comment by mistercrunch** [comment]
Sounds right, it's actually not DML though, but we'd need to improve the SQL parsing to allow for CTE without that switch on. I believe CTEs on most database engine that supports them can be used in a query and DML context.
