### ISSUE TITLE
How to build a chart like this?

### ISSUE THREAD

**Issue by hisunwu** [apache/incubator-superset#1556]
![image](https://cloud.githubusercontent.com/assets/22310674/20090540/b3e15884-a5c8-11e6-882c-4a68731c5916.png)

**Comment by hisunwu** [comment]
I used Distribution - Bar Chart, but it only support me to build 2 Histogram

**Comment by hisunwu** [comment]
like this

![image](https://cloud.githubusercontent.com/assets/22310674/20090647/69feb3a0-a5c9-11e6-89ab-676e4d022b6d.png)

And how to sort by the date? it only sort by summary

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 530 days. Feel free to comment and request for this issue to be reopened.
