### ISSUE TITLE
[explore view] add a "standalnoe" that has the left side controls

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#1566]

**Comment by ascott** [comment]
@mistercrunch could you clarify this one? do you mean add a standalone arg for explore that will render without the left hand column?

**Comment by ascott** [comment]
similar to this issue: https://github.com/airbnb/superset/issues/1026. i'm partial to adding UI that allows the user to toggle the left hand column rather than using a standalone arg in the url.

**Comment by mistercrunch** [comment]
someone wanted to embed the explore view in another application with the left panel but no navbar
