### ISSUE TITLE
SQL Lab AceEditorWrapper bug

### ISSUE THREAD

**Issue by whoishu** [apache/incubator-superset#1578]
I found a bug in SqlLab,when I click the "Overwrite text in editor with a query on this table" icon of any record in query history table , the text of editor never changed.

when I overwrite AceEditorWrapper.componentWillReceiveProps and textChange as follow, the problem solved
![_20161110144910](https://cloud.githubusercontent.com/assets/6374171/20167210/ef577ae6-a754-11e6-9e50-26e1f6fd96b0.png)

- [x] I have checked the caravel logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of caravel
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
latest development

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 528 days. Feel free to comment and request for this issue to be reopened.
