### ISSUE TITLE
Metrics order in bar chart

### ISSUE THREAD

**Issue by github35** [apache/incubator-superset#1579]
I am trying to show sales, sales_last_year as metrics in one bar chart and cost, cost_last_year in another bar chart. In chart one, sales appears on the left and sales_last_year on the right while cost_last_year appears on the left and cost appears on the right in another chart. This is very confusing, so I am writing to ask if there's way to determine metrics order in bar chart -- or keep it the order I chose them? 

Many thanks!

**Comment by JImBurris** [comment]
+1

**Comment by johangarzon** [comment]
+1

**Comment by ysv** [comment]
+1

**Comment by Jielili** [comment]
+1

**Comment by eugeniamz** [comment]
@junlincc  ^^ very useful
