### ISSUE TITLE
Questions about Caravel

### ISSUE THREAD

**Issue by shamsuddeenvp** [apache/incubator-superset#1592]
Dear,

Sorry if I am posting in the forum, please direct me where to post.
I am very new to Caravel. I would like to explore the Caravel and its features for enterprise use.
Can any one gives info/article links to get clarity on the below.

It would be great if you can share any link where I can explore more.
 
-          Installation steps on Windows.

-          Mobile version or APP and other features of UI customization for mobile
- 
-         Row/data level security feature. Role level is there, needs to discuss in more detail. Integraion of Active directory accounts.
-          Data sources connectivity. Use of SQLAlchemy sql dialects (MSSQL, Oracle, Postgres,MySQL,etc.  and not SSAS database/cube? What about files like excel, CSV etc. No option to join data from tables?

-          We have to do Data cleaning/shaping wizard before loading to Caravel

-          Where does the data loaded to carvel getting stored, or it directly connects the database on the fly while doing the slice and dice from dashboard.

-          Installation: Only Linux OS has got direct installation and windows would need Docker to get it installed (As I had a chat with you)

-          Sharing and collaboration
- 
-          Learning curve: Do we need to expertise on Python to do customization

Br,
Shams

**Comment by xrmx** [comment]
Most of the questions you posted here are covered by ~~caravel~~ superset documentation. You are very encouraged to give it a read.

**Comment by mistercrunch** [comment]
1. I'm not sure why would anyone run this type of application on Windows, sounds like a world of troubles. We're not planning on supporting Windows as we can't run tests on it. You're free to play around with Superset in windows, but would advise against using Windows for production.

2. As for mobile support Caravel doesn't look too bad on mobile as we use responsive components (even the dashboard grid is responsive and dashboards can be designed where they'll look pretty good on mobile) but its definitely not the first class citizen. As lots of corporate users don't have VPN on their phones it's not been a real use case for us historically, but really like to see work in that direction.

3. Can be achieved with views at the moment. We're considering adding "forced predicate permissions" in the future, where predicates would be defined as in "sales_team_name='north-east'" and associated with related tables. Users with a role containing that "forced predicate" would see this predicated applied automatically anytime they query one of these tables 

4. SqlAlchemy works well, SSAS is a very different type of query dialect and would require a specific implementation. About CSV and external data, we recommend allowing users a path to load their own data in their analytics playground. Caravel could do that eventually through some "CSV uploader" feature. We assume you handle your joins upstream, not in Caravel. Meaning you can create views or data pipelines that prepare your data, and only then query that in Caravel. We may add a feature to define "many to one" joins in the future. 

About data storage, Caravel doesn't store anything, it queries your datasource on the fly. Note that some caching can be setup where the json behind individual view will be cached in something like memcache or redis. This allows for dashboards to load very quickly and prevent overloading the database when lots of people open dashboards with lots of slices at the same time.

About sharing, it's possible for people to share dashboards and slices to allow other people to alter them.

For customization, and depending on whether you want to alter the frontend or backend or both, you'll need an engineer fluent with modern open source workflows on Github, Python / Flask, Javascript / React / ES6 / Bootstrap.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 525 days. Feel free to comment and request for this issue to be reopened.
