### ISSUE TITLE
Dashboard Security

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1593]
Make sure these boxes are checked before submitting your issue - thank you!

- [Yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [Yes] I have reproduced the issue with at least the latest released version of superset
- [Yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.12.0

### Expected results
Different users login to the caravel system,can view different dashboards.
For example,in the system , we have 5 dashboards(DH1,DH2,DH3,DH4,DH5), USER_A login ,and can view DH1\DH2\DH3,and USER_B login can view DH3/DH4/DH5.

### Actual results
Caravel can not support the function.

**Comment by xrmx** [comment]
What is not working?

**Comment by ganshanshan** [comment]
@xrmx sorry,i can not get you mean.can you explain it again?

**Comment by xrmx** [comment]
@ganshanshan I am asking for something more specific than "can not support the function". What part of the expected result is not working? How have you configured the permissions? The "steps to reproduce" chapter is here for a reason :)

**Comment by ganshanshan** [comment]
@xrmx this is a new feature.my team want to develop it for caravel.

**Comment by xrmx** [comment]
@ganshanshan My point is that it should already work this way.

**Comment by ganshanshan** [comment]
@xrmx Great!but can you show me how to config this,i have tried lots of ways but failed.Thanks very much.

**Comment by ganshanshan** [comment]
@xrmx can you show me how to config this,i have tried lots of ways but failed.Thanks very much.

**Comment by mistercrunch** [comment]
It's in the documentation. There's a security section.

**Comment by RajkumarKadari** [comment]
I tried with help of documentation for the security setup am still facing problem with user mangment

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 446 days. Feel free to comment and request for this issue to be reopened.
