### ISSUE TITLE
Filter Box isue

### ISSUE THREAD

**Issue by kalarikkalbabu** [apache/incubator-superset#1594]
Hi, 
1. Is there any way to change the label of filterbox filter labels, I tried different ways , but it is not working , always column name is coming as filter label, please suggest

2. Can I apply filters to specific slices other than entire dashboard?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 524 days. Feel free to comment and request for this issue to be reopened.
