### ISSUE TITLE
Exception when running queries from SQL Editor

### ISSUE THREAD

**Issue by petter-memrise** [apache/incubator-superset#1595]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.12.0

### Expected results
Executing a SQL query from the query should show a table with resulting rows

### Actual results
Exception:

<html> <body> <code> <pre>MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8OI++=~~~~~~=+?IODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMD$~~~~~~~~~~~~~~~~~~~~~~~=$MMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMN8?:~~~~~~~~~~~~~~~~~~~~~~~~~~=+8NMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMO=~~~~~~~~~~~~~~~~~+I??~~~~~~~~~~~~~+DMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMNI~~~~~~~~~~~~~~~~~~IIIII=~~~~~~~~~~~~~~=NMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMM+=~~~~~~~~~~~~~~~~~~~=III+~~~~~~~~~~~~~~~~~?8MMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMM?~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+++=~~~~8MMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMI=~~~~~~~~~~~~~~~~~~~~~~~~~III?I~~~~~~~~,:++++++~~8MMMMMMMMMMMMMMM MMMMMMMMMMMMN7~~~~~~~~~~~~~~~~==+=~~~~~~=IIIII~~~~~~:. ..:=++=~=MMMMMMMMMMMMMMM MMMMMMMMMMMO=~~~~~~~~~~~~~~~~+++=~~~~~~~~??I?I~~~~~~. ...,~~~~IMMMMMMMMMMMMM MMMMMMMMMMM~~~~~~~~~~~~~~~~~+++:,~~~~~~~~~~~?=~~~~~:. ..~~~~~OMMMMMMMMMMMM MMMMMMMMM$=~~~~~~~~~~~~~~~=++:.. ..~~~~~~~~~~~~~~~~,. . . :~~~~~OMMMMMMMMMMM MMMMMMMMM~~~~~~~~~~~~~~~~+++,. .~~~~~~~~~~~~~~~.. .. . .~~~~~=OMMMMMMMMMM MMMMMMMM?~~~~~~~~~~~~~~~=+~. .~~~~~~~~~~~~~~. ,MMMMM,=~~~~~~NMMMMMMMMM MMMMMMMN~~~~~~~~~~~~~~~~~,. .,~~~~~~~~~~~~~.. ZMMM,+Z:~~~~~~$MMMMMMMMM MMMMMM8?~~~~~~~~~~~~~~~~~.. ..~~~~~~~~~~~~~:. DMMM,+D~~~~~~~~IMMMMMMMM MMMMMMI~~~~~~~~~~~~~~~~~~.. :MMMO~~~~~~~~~~~~~~~,.. ?MMMMMI~~~~~~~~~MMMMMMMM MMMMMM=~~~~~~~~~~~~~~~~~~.. MMM+=M:~~~~~~~~~~~~~:. .:IM$~~~~~~~~~~~8MMMMMMM MMMMMD~~~~~~~~~~~~~~~~~~~:. MMM:,M:~~~~~~~~~~~~~~~.......:~~~~~~~~~~$MMMMMMM MMMMMI~~~~~~~~~~~~~~~~~~~~, MMMMMM~~~~~~~~~~~~~~~~~~,..:~~~~~~~~~~~~+MMMMMMM MMMMD+~~~~~~~~~~~~~~~~~~~~~. $MMMM$~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=MMMMMMM MMMM8~~~~~~~~~~~~~~~~~~~~~~:. . .:~~~~~~,..:. .=~~~~~~~~~~~~~~~~~~~~MMMMMMM MMMMO~~~~~~~~~~~~~~~~~~~~~~~:, .:~~~~~=8.. .+ . =8ZI~~~~~~~~~~~~~~~~=MMMMMMM MMMMZ=~~~~~~~~~~~~~~~~~~~~~~~~:,,,:~~~~~~IZ8:. .O....888?~~~~~~~~~~~~~~~+MMMMMMM MMMMO=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~?888=...I~I88888O?~~~~~~~~~~~~~~7MMMMMMM MMMMO~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Z888OO88888888888O?~~~~~~~~~~~~~OMMMMMMM MMMMD+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=8888888888888888888~~~~~~~~~~~~+MMMMMMMM MMMMM7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~?8888888888888888888?~~~~~~~~~~=$MMMMMMMM MMMMMD~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=$8888888888888888888O~~~~~~~~~~8MMMMMMMMM MMMMMN=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+Z88888888888888888ZZ7=~~~~~~~~?MMMMMMMMMM MMMMMMZ=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+Z88888888Z7I===~~~~~~~~~~~~~=OMMMMMMMMMMM MMMMMMN$~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=$88888O7?=~~~~~~~~~~~~~~~~~~OMMMMMMMMMMMM MMMMMMMM?~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~I8OZ+~~~~~~~~~~~~~~~~~~~~=DMMMMMMMMMMMMMM MMMMMMMM8=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+$+=~~~~~~~~~~~~~~~~~~~~+MMMMMMMMMMMMMMMM MMMMMMMMMD7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=$DMMMMMMMMMMMMMMMMMM MMMMMMMMMMM?~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=$OMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMD7=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ZMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMZ7=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~78MMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMM8OI=~~~~~~~~~~~~~~~~~~~=+?ZDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMNDZ7?++~=~==~+?IONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ------------------------------------------------------------------------------------------------------- ======================================================================================================= ------------------------------------------------------------------------------------------------------- ___ ___ ___ ( ) ( ) ( ) .--. | |_ .---. .--. | | ___ | |_ ___ .-. .---. .--. .--. / _ \ ( __) / .-, \ / \ | | ( ) ( __) ( ) \ / .-, \ / \ / \ . .&#39; `. ; | | (__) ; | | .-. ; | | &#39; / | | | &#39; .-. ; (__) ; | | .-. ; | .-. ; | &#39; | | | | ___ .&#39;` | | |(___) | |,&#39; / | | ___ | / (___) .&#39;` | | |(___) | | | | _\_`.(___) | |( ) / .&#39;| | | | | . &#39;. | |( ) | | / .&#39;| | | | | |/ | ( ). &#39;. | | | | | / | | | | ___ | | `. \ | | | | | | | / | | | | ___ | &#39; _.&#39; | | `\ | | &#39; | | ; | ; | | &#39;( ) | | \ \ | &#39; | | | | ; | ; | | &#39;( ) | .&#39;.-. ; &#39;._,&#39; &#39; &#39; `-&#39; ; &#39; `-&#39; | &#39; `-&#39; | | | \ . &#39; `-&#39; ; | | &#39; `-&#39; | &#39; `-&#39; | &#39; `-&#39; / &#39;.___.&#39; `.__. `.__.&#39;_. `.__,&#39; (___ ) (___) `.__. (___) `.__.&#39;_. `.__,&#39; `.__.&#39; ------------------------------------------------------------------------------------------------------- ======================================================================================================= ------------------------------------------------------------------------------------------------------- Traceback (most recent call last): File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask/app.py&#34;, line 1988, in wsgi_app response = self.full_dispatch_request() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask/app.py&#34;, line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask/app.py&#34;, line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask/app.py&#34;, line 1639, in full_dispatch_request rv = self.dispatch_request() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask/app.py&#34;, line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py&#34;, line 52, in wraps return f(self, *args, **kwargs) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/caravel/models.py&#34;, line 2086, in wrapper return f(*args, **kwargs) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/caravel/views.py&#34;, line 2093, in sql_json session.commit() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 801, in commit self.transaction.commit() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 392, in commit self._prepare_impl() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 372, in _prepare_impl self.session.flush() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2019, in flush self._flush(objects) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2137, in _flush transaction.rollback(_capture_exception=True) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py&#34;, line 60, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2101, in _flush flush_context.execute() File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py&#34;, line 373, in execute rec.execute(self) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py&#34;, line 532, in execute uow File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py&#34;, line 174, in save_obj mapper, table, insert) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py&#34;, line 800, in _emit_insert_statements execute(statement, params) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 914, in execute return meth(self, multiparams, params) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/sql/elements.py&#34;, line 323, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1010, in _execute_clauseelement compiled_sql, distilled_params File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1146, in _execute_context context) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1341, in _handle_dbapi_exception exc_info File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/util/compat.py&#34;, line 202, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1139, in _execute_context context) File &#34;/Users/petter/.virtualenvs/caravel_test/lib/python2.7/site-packages/sqlalchemy/engine/default.py&#34;, line 450, in do_execute cursor.execute(statement, parameters) OperationalError: (sqlite3.OperationalError) table query has no column named results_key [SQL: u&#39;INSERT INTO &#34;query&#34; (client_id, database_id, tmp_table_name, user_id, status, tab_name, sql_editor_id, schema, sql, select_sql, executed_sql, &#34;limit&#34;, limit_used, select_as_cta, select_as_cta_used, progress, rows, error_message, results_key, start_time, end_time, changed_on) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)&#39;] [parameters: (u&#39;BJcCPLvbl&#39;, 2, u&#39;&#39;, 1, u&#39;running&#39;, u&#39;Untitled Query&#39;, u&#39;HyRKBSR1g&#39;, u&#39;ds&#39;, u&#39;SELECT \n DATE(created_on) as date, \n metric_name metric, \n count(1) number\nFROM sql_metrics\ngroup by \n DATE(created_on), \n metric_name\norder by \n DATE(created_on), \n metric_name&#39;, None, None, 1000, 0, 0, 0, 0, None, None, None, 1479137233917.839, None, &#39;2016-11-14 15:27:13.920730&#39;)] </pre> </code> </body> </html>

### Steps to reproduce
Running a simple query: 

SELECT 
    DATE(created_on) as date, 
    metric_name metric, 
    count(1) number
FROM sql_metrics
group by 
    DATE(created_on), 
    metric_name
order by 
    DATE(created_on), 
    metric_name

In SQL Lab - SQL Editor gives me the above error.

**Comment by xrmx** [comment]
Please try to reproduce with 0.13.1, remember to apply migrations when upgrading.

**Comment by NirantK** [comment]
Hey, @xrmx maybe you can close this issue if @petter-memrise has been unable to reproduce the issue?
