### ISSUE TITLE
How can I easily export charts to other platform?

### ISSUE THREAD

**Issue by kamushin** [apache/incubator-superset#1600]
These charts in superset are really awesome, but how can I *export* it to my other platform(website)? To make it not just a *Lab* or *idea* but something in production?

**Comment by mistercrunch** [comment]
You mean like an iFrame?

**Comment by kalarikkalbabu** [comment]
Regarding this I have a doubt, How to export dashboard to PDF, is there any option?

**Comment by kamushin** [comment]
@mistercrunch  How to export a dashboard as an iFrame?

**Comment by mistercrunch** [comment]
http://www.w3schools.com/TAgs/tag_iframe.asp

**Comment by sunnyakaxd** [comment]
@mistercrunch That makes every clear :D

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 278 days. Feel free to comment and request for this issue to be reopened.
