### ISSUE TITLE
On Delete table page returns to edit screen of that pk, but is a 404 as the table is deleted

### ISSUE THREAD

**Issue by wyndhblb** [apache/incubator-superset#1605]
1. go to the list of tables
2. hit the little eraser
3. click confirm
4. 404

### Superset version

master branch as of 2016-11-15

### Expected results

after delete redirect to the /tablemodelview/list/

### Actual results

reloads /tablemodelview/edit/{pk}/

### Steps to reproduce

make a table, then hit the delete icon

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 523 days. Feel free to comment and request for this issue to be reopened.
