### ISSUE TITLE
[slice-list] make search ui more clear

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1622]
- when someone clicks the search drop down menu, pre-select the "name" search filter for slices and do away with the secondary "starts with" option. 

current ux:
![superset-search-slices](https://cloud.githubusercontent.com/assets/130878/20377482/c49c726c-ac44-11e6-9c76-d575f29dfd03.gif)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 522 days. Feel free to comment and request for this issue to be reopened.
