### ISSUE TITLE
How to use explore V2?

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1677]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes ] I have reproduced the issue with at least the latest released version of superset
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.13.0

### Expected results
I want to use explore V2 to view slice.

### Actual results
Only get the explore V1

**Comment by ascott** [comment]
hi @ganshanshan! i'm glad you are eager to use explore v2. we are still in development, but very close to a release!

**Comment by ganshanshan** [comment]
@ascott Thank you very much for your hard work. 
You know that there are no so much chart types in explore V1,for example line&bar chart(time series and not time series),multiple chart,horizontal bar chart .And my team develop these charts which are not in explore V1.

I have two questions:
1. Can I contribute our code to superset?If okay,how to do it?
2. In the future,the explore V1 will be give up,and if I submit the code ,it can only work in V1,not work in V2?

Looking forward to your reply.

**Comment by gregroberts** [comment]
I see lots of discussion on Explore V2, but I've just upgraded to Superset 0.17.0, expecting shiny shiny things, but nothings changed. 

Is there yet a way to use Explore V2 on the PyPI release, or will I have to clone and build from source.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 411 days. Feel free to comment and request for this issue to be reopened.
