### ISSUE TITLE
[SQL Lab] Run SQL with Jinja in SQL Lab works very well,but fail in Slice explore.

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1678]
Make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [ yes] I have reproduced the issue with at least the latest released version of superset
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar

I use the SQL LAB with Jinja ,like that 

```
SELECT sum(c.unit_cost) as costs,
       sum(c.unit_price) as price,
       t.calendar_year
FROM costs c,
     times t
where t.calendar_year = '{{datetime.strptime("1998-09-12 21:08:12", "%Y-%m-%d %H:%M:%S").year}} ' group by t.calendar_year
```
It works very well,but when I visualize the SQL in slice explore the Jinja cannot work.

### Superset version
0.13.0

### Expected results
Run SQL in the SQL Lab with Jinja ,it works very well.

### Actual results
but when I visualize the SQL in slice explore the Jinja cannot work.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 515 days. Feel free to comment and request for this issue to be reopened.
