### ISSUE TITLE
Add new attributes into the Pie Chart

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1684]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes ] I have reproduced the issue with at least the latest released version of superset
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar

In my project , we enhance the pie viz that add three new attributes : Half circle,Pad Angle,Corner Radius.
with this attributes we can get the pie like that 

![1](https://cloud.githubusercontent.com/assets/19347709/20599803/2e7c4e2c-b28b-11e6-92d7-3acc21b7c724.jpg)
![2](https://cloud.githubusercontent.com/assets/19347709/20599804/316a0e62-b28b-11e6-8944-78b8eb954b75.jpg)
![3](https://cloud.githubusercontent.com/assets/19347709/20599806/33866650-b28b-11e6-94f4-c810e868ee1f.jpg)

### Superset version
0.13.2

### Expected results
1.Half circle
2.Pad Angle
3.Corner Radius

### Actual results
Only like that

![4](https://cloud.githubusercontent.com/assets/19347709/20599943/f3230fe0-b28b-11e6-8394-65ee2e75be03.jpg)

### Steps to reproduce
New feature.

**Comment by xrmx** [comment]
Thanks for the PR! You don't need to open an issue if you are opening a PR shortly. Issues are useful for discussing issues / features / enhancements *before* coding them.

**Comment by ganshanshan** [comment]
@xrmx thanks very much.I will follow your advice next time.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 514 days. Feel free to comment and request for this issue to be reopened.
