### ISSUE TITLE
Cannot create admin account during installation with CentOS 6.6

### ISSUE THREAD

**Issue by dkhwangbo** [apache/incubator-superset#1687]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.13.2 (latest)

### Expected results
Well done.

### Actual results
```
(test) [druid-ssd-test] hbadmin@hbase-md15b1-020:~/.virtualenvs/temp 17:05:01> fabmanager create-admin --app
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
Username [admin]:
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\
xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\x80\x81\xb0\xfa\x90\x81\xa1\xf8\x80\x81\xae\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x
96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
/home/hbadmin/.virtualenvs/test/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\
xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\xa0\x81\xb5\xf8\xb0\x81\xa9\xf9\x80\x81\xaf\xf8\x80\x81\xa5\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x
93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
```

### Steps to reproduce

```
$ pip install superset
$ fabmanager create-admin --app superset
```

### Version info

Python 2.7.12
Pip 9.0.1
sqlite 3.15.1
```
(test) [druid-ssd-test] hbadmin@hbase-md15b1-020:~/.virtualenvs/temp 17:26:51> pip list superset --format columns 
Package          Version
---------------- --------
alembic          0.8.8
amqp             1.4.9
anyjson          0.3.3
Babel            2.3.4
billiard         3.3.0.23
celery           3.1.23
cffi             1.9.1
click            6.6
colorama         0.3.7
cryptography     1.5.3
enum34           1.1.6
Flask            0.11.1
Flask-AppBuilder 1.8.1
Flask-Babel      0.11.1
Flask-Cache      0.13.1
Flask-Login      0.2.11
Flask-Migrate    1.5.1
Flask-OpenID     1.2.5
Flask-Script     2.0.5
Flask-SQLAlchemy 2.0
Flask-Testing    0.5.0
Flask-WTF        0.13.1
future           0.16.0
gunicorn         19.6.0
humanize         0.5.1
idna             2.1
ipaddress        1.0.17
itsdangerous     0.24
Jinja2           2.8
kombu            3.0.37
Mako             1.0.6
Markdown         2.6.6
MarkupSafe       0.23
numpy            1.11.2
pandas           0.18.1
parsedatetime    2.0
pip              9.0.1
pyasn1           0.1.9
pycparser        2.17
pydruid          0.3.0
PyHive           0.2.1
python-dateutil  2.5.3
python-editor    1.0.1
python-openid    2.2.5
pytz             2016.7
requests         2.10.0
sasl             0.2.1
setuptools       28.8.0
simplejson       3.8.2
six              1.10.0
SQLAlchemy       1.0.13
SQLAlchemy-Utils 0.32.7
sqlparse         0.1.19
superset         0.13.2
thrift           0.9.3
thrift-sasl      0.2.1
Werkzeug         0.11.10
wheel            0.29.0  
WTForms          2.1   
```

**Comment by bcambel** [comment]
:+1 same issue with Ubuntu 16.04

**Comment by fangyeqing** [comment]
you can see https://github.com/airbnb/superset/issues/1557

**Comment by dkhwangbo** [comment]
Hi @fangyeqing Thanks for your comment.
I apply that solution but same problem is occurred. I think this issue is different from #1557.

**Comment by dkhwangbo** [comment]
Anyway, Finally, I can install superset with Flask-appbuilder integrated with MySQL.

**Comment by zhmg23** [comment]
I think I have a similar problem with you
Version info：
Python 2.7.12
Pip 9.0.1


# fabmanager create-admin --app superset
/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
Username [admin]: 
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 
Password: 
Repeat for confirmation: 
/usr/local/lib/python2.7/site-packages/flask_migrate/__init__.py:4: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
/usr/local/lib/python2.7/site-packages/flask_cache/jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  from flask.ext.cache import make_template_fragment_key
/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:305: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\x80\x81\xb0\xfa\x90\x81\xa1\xf8\x80\x81\xae\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:305: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\xa0\x81\xb5\xf8\xb0\x81\xa9\xf9\x80\x81\xaf\xf8\x80\x81\xa5\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 72: ordinal not in range(128)
Logged from file manager.py, line 81


Could you tell me the detailed solution?
Thank you very much.

**Comment by xrmx** [comment]
What encoding are you using?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 425 days. Feel free to comment and request for this issue to be reopened.
