### ISSUE TITLE
Cannot resolve module 'react/lib/ReactDOM'

### ISSUE THREAD

**Issue by TingYinHelen** [apache/incubator-superset#1693]
I encounter an issue.
I ran command `npm install` then I ran `npm run dev` , the iterm point out error:

**Cannot resolve module 'react/lib/ReactDOM' in /Users/helen/Downloads/study/superset/superset/superset/assets/node_modules/.15.3.2@react-dom**

So I install `react-dom` again, but it still doesn't work. 
I found this file I changed `module.exports = require('react/lib/ReactDOM');` to `module.exports = require('react/lib/react');` It doesn't have error, but the page seems have no css style.
Can anyone help me resolve this issue?

The error from browser is below:
<img width="641" alt="screen shot 2016-11-28 at 7 49 25 pm" src="https://cloud.githubusercontent.com/assets/14006826/20667559/cf6e9b98-b5a4-11e6-9d00-b57df117d52b.png">

**Comment by mistercrunch** [comment]
Did you run `npm install` while the current working directory was set in the `superset/assets` folder?

**Comment by TingYinHelen** [comment]
@mistercrunch I did. And I met a new problem when I ran `caravel runserver -p 8088` the pages looks good, when I ran `superset runserver -p 8088` the page seems have no css style. I don't know why.

**Comment by TingYinHelen** [comment]
@mistercrunch  I did. But it still have this issue:(

**Comment by lstk520** [comment]
跟你遇到一样的问题，按照你的方法改了，但是编译的时候会卡在
```
running install
running bdist_egg
running egg_info
writing superset.egg-info/PKG-INFO
writing dependency_links to superset.egg-info/dependency_links.txt
writing requirements to superset.egg-info/requires.txt
writing top-level names to superset.egg-info/top_level.txt
reading manifest file 'superset.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
```
研究了一两天没搞定，请教怎么解决？

**Comment by JessicaDuan** [comment]
@lstk520 Same problem. Remove or rename it may help. But not sure if it will cause new problem.

**Comment by mistercrunch** [comment]
What version of node/npm are you running?

**Comment by uptonking** [comment]
@lstk520 你用的ubuntu哪个版本呐，14.04，16.04？
python用的2.7还是3.5？
折腾了一天多没搞定，编译时间太长了，求分享

**Comment by eeve** [comment]
+1 

```
ERROR in ./~/.15.3.2@react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in /Users/eeve/working/python/airbnb/superset/superset/assets/node_modules/.15.3.2@react-dom
 @ ./~/.15.3.2@react-dom/index.js 3:17-46
```
env:
node : v7.0.0
npm: 3.10.8

**Comment by dnkodi** [comment]
after 15.4.0 React DOM implementation has been moved completely to the React DOM package. in the earlier versions react-dom package import the module from react/lib/ReactDOM. but now the module is itself inside the react-dom package ./lib/ReactDOM.

**Comment by starandtina** [comment]
@TingYinHelen As @dnkodi mentioned, React package and browser build no longer "secretly" includes React DOM, please refer to [Release Note for React@15.4.0](https://github.com/facebook/react/releases/tag/v15.4.0).

![image](https://cloud.githubusercontent.com/assets/613990/25562954/6cf434bc-2dc4-11e7-87b2-600b9ac98fe9.png)

Does it works for you?

**Comment by diggzhang** [comment]
Find a solution:

1. Switch using `cnpm` instead of `npm`
2. Delete the entire `node_modules` directory
3. Re-download all dependencies by `cnpm`

**Comment by mistercrunch** [comment]
That's an old issue that I'm pretty sure got resolved somehow, closing.
