### ISSUE TITLE
Enable user to choose time granularity from filter slice

### ISSUE THREAD

**Issue by AxelDelmas** [apache/incubator-superset#1718]
Filter slices are very useful to apply filters to all slices of a dashboard.
Time filters already enable to set `from` and `to` parameters, but there is currently no possibility to change the `time granularity`. 
It would be very useful to add that option as well, as the only way for now is to explore each graph individually (which defeats the purpose of dashboards)

**Comment by Csnigs** [comment]
:+1:

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 508 days. Feel free to comment and request for this issue to be reopened.

**Comment by SWoto** [comment]
+1. I do think it would be pretty good to let the user choose the time granularity.
