### ISSUE TITLE
Connecting to MSSQL server Database

### ISSUE THREAD

**Issue by shamsuddeenvp** [apache/incubator-superset#1719]
Dear,

I am new to Superset.

I am trying to connect MSSQL database, however no success. I tried the below in in SQL alchemy area.

        mssql://Server IP/Testing?password=****&user=********
        mssql://Server IP:1433/Testing?password=****&user=********

Could you please let me know hwat is wrong here?

Thanks!
Shams

**Comment by xrmx** [comment]
@shamsuddeenvp how can we possibly know? Look at superset logs, the error is written there.

**Comment by hodzanassredin** [comment]
This ticket is first on google for "superset mssql" and I decided to add short instructions here: First of all you have to install superset as described in manual and after that (inside venv) do next steps:
pip uninstall pymssql
sudo apt-get install libssl-dev
wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.tar.gz
tar -xvzf freetds-0.95.tar.gz
cd freetds-0.95
./configure --with-openssl=/usr/include/openssl --with-tdsver=7.3
make
sudo make install
pip install --no-binary pymssql pymssql
sudo ln -s /usr/local/lib/libsybdb.so.5 /usr/lib/libsybdb.so.5
sudo ldconfig

Now you have to create mssql connection URL: it should look like that:
mssql+pymssql://USER%40SERVER:PASSWORD@SERVER.database.windows.net:1433/DATABASE

**Comment by davidgreenshtein** [comment]
@hodzanassredin very helpful instructions, thank you. Connection is working for me after downgrading the pymssql to 2.1.1
sudo pip install pymssql==2.1.1

**Comment by vladkras** [comment]
I use
```
mssql+pymssql://name:password@db_host:1433/db_name
```
be careful! <db_name> is case sensitive
