### ISSUE TITLE
Not support data access with different user assess to different data from the same slice

### ISSUE THREAD

**Issue by ThunderYY** [apache/incubator-superset#1729]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.14.1

### Expected results
I want the  function of data access, the report data of different users logged in to see is not the same. And expect use expression in sqlab or sqla table to get current user like this {{user}}.
For Example : 
`SELECT id,
       action,
       user_id,
       json,
       dttm,
       dashboard_id,
       slice_id,
       dt
FROM logs 
where user_id = '{{user.get_id()}}'LIMIT 100
OFFSET 0`  
 will convert into
 `SELECT id,
          action,
          user_id,
          json,
          dttm,
          dashboard_id,
          slice_id,
          dt
   FROM logs
   where user_id = '1'LIMIT 100
   OFFSET 0`

I know that the jinja supported in the SQL Lab and slice filters is only for PrestoDB,and for RDBMS e.g. mysql\oracle\SQL Server ,it is very useful too.

So,i want to do two things ,
1.develop to support flask.g.user in CONTEXT like uuid,random,time.
2.develop to support jinja in sql of tables.

### Actual results
SupertSet does not support this feature

### Steps to reproduce
New feature.

@xrmx 
@mistercrunch

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 507 days. Feel free to comment and request for this issue to be reopened.
