### ISSUE TITLE
MSSQL cannot find data and cannot find some table

### ISSUE THREAD

**Issue by yhc1990518** [apache/incubator-superset#1740]
My DB is **AdventureWorks2008** in MS Sqlserver .
There is a table in the **AdventureWorks2008** named "**Sales.CreditCard**".

I created DB source in superset and my SQL URL is "_mssql+pymssql://sa:XXXXXXXXXX@192.168.137.1:1433/adventureworks2008"_. 
when I use this DB source to create table named "**Sales.CreaditCard**", the superset told me "Table [Sales.CreditCard] could not be found".

And the other table in the  **AdventureWorks2008** named "**dbo.Product**".
I can created table with name "**dbo.Product**" in the superset. (with name "**Product**" is not working.)

When I use table **dbo.Product** as data source design chart , the design panel always shows me NO DATA.

**Comment by xrmx** [comment]
Please add the missing information per our issue template. Namely superset version and stacktraces in logs.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 506 days. Feel free to comment and request for this issue to be reopened.
