### ISSUE TITLE
Time Grain Options doesn't show for Postgres Table

### ISSUE THREAD

**Issue by stephendj** [apache/incubator-superset#1754]
![pasted image at 2016_12_03 12_55 am](https://cloud.githubusercontent.com/assets/7076735/20856869/2e808e00-b94e-11e6-9bd0-5f4349a519cb.png)

I am using Postgres table to make the visualization, but for some reason the time grain options doesn't show up (day, month, etc.). I'm using timestamp without timezone type and the problem didn't occur when I use Redshift.

**Comment by petroswork** [comment]
I had the same problem when I upgraded to Caravel 0.12. Upgrading to Superset 0.13.2 fixed it.

**Comment by stephendj** [comment]
@petroswork is it possible to upgrade caravel to superset without losing slices, etc? can you tell me how? thanks.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 498 days. Feel free to comment and request for this issue to be reopened.
