### ISSUE TITLE
Error: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by AndyPau** [apache/incubator-superset#1756]
my superset is builded by the newest source, VersionNumber  is 0.14.1. when i start the server, there is an error reported. 

Error: 'dict' object has no attribute 'iteritems'

**Comment by marklavrynenko-original** [comment]
I also had similar problem. Issue was in old version of mysqlclient (1.3.2 instead of 1.3.12)
Make sure that all your database drivers are Python3 compliant.

Hope it helps.

**Comment by mistercrunch** [comment]
That's a generic error message, without a stack trace we have no idea where it's coming from... Closing.
