### ISSUE TITLE
Load excel data to caravel

### ISSUE THREAD

**Issue by shamsuddeenvp** [apache/incubator-superset#1757]
Dear,

Is there any way to laod data from excel to caravel? if yes can you give some insight or any link for implementing the same.

Br,
Shams

**Comment by data-strategy** [comment]
Dear all, 
I am also looking for loading data from excel or txt to caravel. Any has this experience before? Thanks.

Regards,
Philbert

**Comment by CamilleMo** [comment]
Hello, you will have to upload your excel data directly in your database. To make it easy you can use python/pandas which provides nice .read_excel() and .to_sql() methods.

Regards,
Camille
