### ISSUE TITLE
After upgrade changed name to Superset, existing role's permission names were not changed

### ISSUE THREAD

**Issue by jasonshah** [apache/incubator-superset#1764]
### Superset version
Previously 0.11.x
After upgrade, 0.12.1.0

### Expected results
Existing standard roles (Admin, Alpha, Gamma) and custom roles (in our case, Client) would have their names changed from, e.g. "can welcome on Caravel" to "can welcome on Superset" as a part of the migration.

### Actual results
No roles' names have changed. We have to manually change the names either one at a time through the UI, or through database queries. Only users with Admin role continued to work. For clients on all other roles, this resulted in ERR_TOO_MANY_REDIRECTS in Chrome, and investigation into the logs to identify this as the source of the issue.

### Steps to reproduce
Perform the upgrade.

We ended up having to blow out our database and recreating it. We could not reliably upgrade.

**Comment by xrmx** [comment]
Yeah, would be very nice to have a migration for that

**Comment by bkyryliuk** [comment]
@jasonshah - have u tried `superset init` ?

**Comment by karlgrz** [comment]
@bkyryliuk yes, we followed instructions on the documentation for an upgrade.

**Comment by malleshm** [comment]
superset init should work.

**Comment by karlgrz** [comment]
@malleshm I followed the documentation provided for applying an upgrade, so yes, I did run ```superset init```. It still did not migrate the custom roles we have set up. Is it possible ```superset init``` failed in the middle of the process and just didn't log anything?

**Comment by bkyryliuk** [comment]
ah, yes - we have 0 control over the custom roles.

**Comment by asdf2014** [comment]
I meet the same problem that move the whole virtualenv files with `superset-0.15.4` into product cluster's machine for upgrading `superset-0.14.1`. And i changed the sqlite3 datasource from `/home/superset/.superset/superset.db` into `/root/.superset/superset.db`. However, those information of `superset` changed nothing about `USER`, `ROLE` etc, even the UI.
 - Expected Result:
![image](https://cloud.githubusercontent.com/assets/8108788/23154993/8d581998-f84b-11e6-8af9-19e4220b1915.png)
 - But changed nothing:
![image](https://cloud.githubusercontent.com/assets/8108788/23154999/9334c44c-f84b-11e6-88c1-4955041c1fbb.png)
@xrmx

**Comment by xrmx** [comment]
@asdf2014 completely unrelated issue, before opening a new issue double check that your config correctly points to the right db and that you are using the correct virtualenv (last time i checked virtualenv were not movable). On top of that running stuff as root is bad.

**Comment by asdf2014** [comment]
I see.
 - Config
I use the default sqlite path, and i print the value of `SQLALCHEMY_DATABASE_URI` is `/home/superset/.superset/superset.db`.
![image](https://cloud.githubusercontent.com/assets/8108788/23157860/c15cb652-f857-11e6-96fe-2798c8fbc90e.png)

 - Virtualenv
I am afraid I can not agree with your point of view that `virtualenv` is not movable. We can relocal the path of it with `virtualenv --relocatable` command.

 - User
I just put it in `/root/superset`, but it still belong to `superset` user.
![image](https://cloud.githubusercontent.com/assets/8108788/23157726/4232a850-f857-11e6-9cc0-c3132deaaf85.png)

@xrmx
