### ISSUE TITLE
[Internal Airbnb] Bug: Users logging into Superset get "Access is Denied" the first time they visit

### ISSUE THREAD

**Issue by jefffeng** [apache/incubator-superset#1807]
When internal Airbnb users use Superset for the first time, they receive an "Access is Denied" message.  Then when a user refreshes the page, they are usually able to get in.  It seems like the default role creation upon sign-in doesn't happen until after the page is loaded, causing users to have to refresh their page.  We should fix this bug.

<img width="1440" alt="screen shot 2016-12-07 at 3 26 43 pm" src="https://cloud.githubusercontent.com/assets/18297825/21041979/77fde754-bda3-11e6-8340-5f94c54ab069.png">

**Comment by jefffeng** [comment]
@mistercrunch - has this issue been resolved?

**Comment by panutat** [comment]
often the first thing everyone that uses Caravel sees.. surprised it still exists. any suggestion on how to fix? i don't mind attempting and contributing fix. thanks

**Comment by panutat** [comment]
update in __init__.py:

class MyIndexView(IndexView):
    @expose('/')
    def index(self):
        return redirect('/caravel/auth')

add in views.py:

@expose("/auth")
    def auth(self):
        """Check if user logged in"""
        if not g.user.get_id():
            return redirect('/login')
        return redirect('/caravel/welcome')
