### ISSUE TITLE
Refresh Druid Metadata

### ISSUE THREAD

**Issue by goaquin** [apache/incubator-superset#1816]
Hello,
I set a the parameters of druid cluster, but when I hit the refresh metadata I only see 1 datasource:
![image](https://cloud.githubusercontent.com/assets/3218329/21117404/3a0cfcda-c098-11e6-9399-a4de41d9063b.png)

But when I query the list of datasource in Druid I can see all of them.
```
localhost:8082/druid/v2/datasources
["wikiticker","sep"]
```
What could be the problem?

Regards,
Joaquín Silva

**Comment by mistercrunch** [comment]
We need physical segments to extract the column information, can you confirm that both datasources actually have segments?
