### ISSUE TITLE
Queries work if ended w/ `;` but viz fails

### ISSUE THREAD

**Issue by jefffeng** [apache/incubator-superset#1822]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
air/superset

### Expected results
Both the SQL query works in SQL Lab and the visualize flow should work

### Actual results
SQL query in SQL Lab works but visualize flow fails

### Steps to reproduce
Ping Lindsay Pettingill @ Airbnb for details

**Comment by jfeng15** [comment]
@ascott @mistercrunch @bkyryliuk @vera-liu - bumping priority on this bug

**Comment by erik998** [comment]
Pinged Lindsay for a sample query. This worked for me using the birth_names database table sample.

**Comment by jfeng15** [comment]
Looks like we can close this issue.  Thanks!
