### ISSUE TITLE
Queries That Run Successfully in Airpal may Fail in Airbnb

### ISSUE THREAD

**Issue by jefffeng** [apache/incubator-superset#1823]
We've encountered several SQL queries that will complete successfully in Airpal, but will fail in SQL Lab with either the Run Query or the "Run Async" button.  Here is an example query below, as well as the screenshots for Airpal

**Example 1**

create table tmp.holidaycards as 
select a.id_guest, a.id_host, a.dim_host_language, a.dim_guest_language
from (select * from magical_booking.fct_bookings_detail where ds>='2016-01-01') a
left join (select * from core_data.fct_cancellations where ds>='2016-01-01' ) b
on a.id_reservation=b.id_reservation
join (select * from core_data.fct_reviews_of_guest where ds>='2016-01-01' and dim_overall_rating in ('4','5')) c
on a.id_reservation=c.id_reservation
join (select * from core_data.fct_reviews_of_host where ds>='2016-01-01' and dim_overall_rating in ('4','5')) d
on a.id_reservation=d.id_reservation
where b.id_reservation is null

**Query works in Airpal:**

<img width="1540" alt="screen shot 2016-12-12 at 9 25 59 pm" src="https://cloud.githubusercontent.com/assets/18297825/21128969/ba9bab4c-c0b3-11e6-85bf-df66f55da3ab.png">

**Query does not work in SQL Lab:**
<img width="1541" alt="screen shot 2016-12-12 at 9 29 23 pm" src="https://cloud.githubusercontent.com/assets/18297825/21129037/1fa447b0-c0b4-11e6-8dfc-3e43c5add968.png">

**Comment by jfeng15** [comment]
Issue can be closed now.  Query now works in SQL Lab
