### ISSUE TITLE
New feature: Dashboard override granularity

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#183]
Hi there,

I'd like to start implementing granularity override.
# My notes 

Like in Grafana (http://grafana.org/) I'd like to have a time period control for the dashboard.
It will allow users to select the period (granularity) to visualize.

Todo:
- server: Allow `dashboard/id/` to receive optional parameters: since, until
- server/client: Add granularity property to dashboard: `{"granularity":{"since":"now-1d","until":"now"}}`
- client: Change `slice.querystring` to read granularity and send to the slice endpoint
  extra bonus:
- client: Add granularity-picker to dashboard (https://github.com/grafana/grafana/tree/master/public/app/features/dashboard/timepicker)
  - Modify granularity-picker to allow "Default" that means the granularity setup on each slide 
- Add new property to dashboard definition: granularity that will override slice ones.

Comments? Thanks

**Comment by gbrian** [comment]
Changes for reviewing:
https://github.com/gbrian/panoramix/pull/1/files

Let me know if they are ok to create a PR

Thanks

**Comment by mistercrunch** [comment]
You should PR against our master, that will trigger the continuous integration, linter, and all that good stuff.
