### ISSUE TITLE
[Feature] Support Mapbox features: customizable popup and filter by slider

### ISSUE THREAD

**Issue by kaiosama** [apache/incubator-superset#1847]
What Mapbox visualization does right now is only to display pins on the map. It will be useful to integrate these features when customizing a slice:

https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/
https://www.mapbox.com/mapbox-gl-js/example/timeline-animation/

**Comment by markrey** [comment]
+1 If someone working on it.

**Comment by ahsanshah** [comment]
Has there been any activity on this request?
