### ISSUE TITLE
bullet charts can't change size on dashboard, when moving the frame, can't free mouse!!!

### ISSUE THREAD

**Issue by chenxinglong** [apache/incubator-superset#1865]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15

### Expected results
can free

### Steps to reproduce
add bullet to dashboard,and  change the frame size

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 490 days. Feel free to comment and request for this issue to be reopened.
