### ISSUE TITLE
To change the color of the chart/legend

### ISSUE THREAD

**Issue by shamsuddeenvp** [apache/incubator-superset#1874]
Dear,

I am very new to Superset. Can you pls clarify the below.

- How can I change the default color of the slice (chart/legend etc)

- How to add time/date (date from and date to Or monthly,quarterly, yearly) filters in a dashboard

- Any option to share the dashboard as PDF, image vie email.

- Drill down functionality to canned reports or in the same visual?

- how to implement the feature to load the data from files (excel, csv etc)

Thanks!
Shams

**Comment by elliothimmelfarb** [comment]
+1

**Comment by shamsuddeenvp** [comment]
@elliothimmelfarb 

You have replied anything? I couldn't see anything except +1. Is this means anything?

**Comment by ProPheT777** [comment]
That simply means he have the same need/question than you, to show you are
not alone to have these questions.

Le jeu. 22 déc. 2016 09:36, shamsuddeenvp <notifications@github.com> a
écrit :

**Comment by shamsuddeenvp** [comment]
Dear Team,

Can anyone pls help on this points?

Br,
Shams

**Comment by shamsuddeenvp** [comment]
any help on this pls?

**Comment by vkjangra1209** [comment]
We are also trying for the same problem.. Any help please..

**Comment by fradeve** [comment]
https://github.com/airbnb/superset/issues/638

**Comment by renanoliveira** [comment]
+1

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 326 days. Feel free to comment and request for this issue to be reopened.
