### ISSUE TITLE
Feature Request: select latest available date

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#1875]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0

### Expected results
Some our daily data sources are delayed or not updated regularly. 
For eg: if current date is 12/23, latest daily data is available either 12/22 or 12/21 or even earlier. 
If I use relative dates like 2 days ago or 7 days ago, I'd see data for multiple dates. 

Is it possible to add special date config to select the most recent date ? 
Something like '7 days from latest'  to 'latest' would exactly show previous 7 available dates. 

Recent date can be obtained by querying /intervals API on the coordinator.

**Comment by xrmx** [comment]
Could you please expand the issue a bit? Where do you need this?
