### ISSUE TITLE
how to show cohort data in pivot table and time series lines

### ISSUE THREAD

**Issue by witwall** [apache/incubator-superset#1876]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0 

### Expected results
pivot table without column or row summary
![](https://static1.squarespace.com/static/582de92be4fcb5d9b448e96e/t/582df922e6f2e10d706da92f/1479407916441/Average+Income+For+2010+vs+2011?format=1500w)
### Actual results

mulitply line chart does not support, if want to use time series line, must use date time as column.
### Steps to reproduce

###reference,
* http://www.cohortanalysis.com/

**Comment by MartinArens** [comment]
+1

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 426 days. Feel free to comment and request for this issue to be reopened.
