### ISSUE TITLE
Superset Run Async Returns No Data

### ISSUE THREAD

**Issue by knathanieltucker** [apache/incubator-superset#1886]
### Superset version
Most recent 

### Expected results
I wanted to activate the run async ability with workers. To do so I added the following to my config file:

```
class CeleryConfig(object):
    BROKER_URL = os.environ['REDIS_URL']
    CELERY_IMPORTS = ('superset.sql_lab', )
    CELERY_RESULT_BACKEND = os.environ['REDIS_URL1']
    CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig

```

### Actual results
I click the button, and most of the time I get "The query returned no data". When I inspect the worker logs I see that they received the query, but I get no results back.

### Steps to reproduce

Add the above to the config (with two redis dbs set up).

I am not sure if this is the best place to ask this, so please point me to the appropriate place if there is a better one. But I sent a ton of time looking around for an answer to this question and did not find any. I appreciate your time!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 480 days. Feel free to comment and request for this issue to be reopened.

**Comment by Anshuldhawan007** [comment]
@mistercrunch I am still facing this issue,  while querying on superset 'The query returned no data'
