### ISSUE TITLE
"keywords must be strings" - mysql SSL connection Error 

### ISSUE THREAD

**Issue by kusumakarb** [apache/incubator-superset#1889]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
airbnb_prod.0.13.0.3

### Expected results
![okay](https://cloud.githubusercontent.com/assets/10572576/21560926/f5580f92-ce8b-11e6-953b-64666104a60d.png)

### Actual results
![notokay](https://cloud.githubusercontent.com/assets/10572576/21560933/021d7e10-ce8c-11e6-9048-e81e2c7f93ef.png)

### Steps to reproduce
1. Sources > Databases> Add
2. Enter database name, SQLAlchemy URI and Extra: 
```
 {
    "metadata_params": {},
    "engine_params": {
          "connect_args":{
              "sslmode":"require",
              "sslrootcert": "/static/cert/ca-cert.pem"
        }
     }
}
```

3. Click on 'Test Connection'

**Comment by xrmx** [comment]
Superset logs should contain more info you need to debug this,

**Comment by nambrot** [comment]
I ran into the same issue

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 437 days. Feel free to comment and request for this issue to be reopened.
