### ISSUE TITLE
Jinja problem:Template rendering failed: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dantezhao** [apache/incubator-superset#1891]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I use Jinja to point to the latest partition key , the sql engine is presto, but it's not work well.

The error message is : Template rendering failed: argument of type 'NoneType' is not iterable

The sql is : 
SELECT count(1)
FROM some_table
WHERE patrition_key = '{{presto.latest_partition('some_table')}}'

### Superset version
0.15
### Expected results

result 

### Actual results

Template rendering failed: argument of type 'NoneType' is not iterable

**Comment by xrmx** [comment]
Please post the full backtrace and while at it give a try to 0.15.1

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 474 days. Feel free to comment and request for this issue to be reopened.
