### ISSUE TITLE
Bypassing the login for Supreset iframe in Webpage

### ISSUE THREAD

**Issue by Sarrae1406** [apache/incubator-superset#1901]
I am using Superset version 0.15.1.  I create a slice and use its iframe to embed into my webpage. When I do so, it directs me to superset login on the webpage. 

Is there some way I can bypass the login or may be pass the credentials through iFrame in advance ?

I have tried removing the slice owner name, but that doesn't quite work.

My Iframe is as follows :

```
      <iframe
        src="http://ServerIP:PortNo/superset/explore/table/8/?goto_dash=false&bottom_margin=auto&force=false&new_dashboard_name=&slice_name=User+Registration&y_axis_zero=false&y_axis_label=Users+Registered&resample_fillmethod=&save_to_dashboard_id=&line_interpolation=linear&add_to_dash=false&reduce_x_ticks=false&rolling_periods=&show_controls=false&granularity_sqla=registration_date&x_axis_label=&rolling_type=None&datasource_type=table&new_slice_name=&flt_op_0=in&viz_type=bar&since=100+years+ago&y_log_scale=false&time_compare=&rdo_save=overwrite&until=now&collapsed_fieldsets=&show_bar_value=false&resample_rule=&datasource_id=8&period_ratio_type=growth&show_brush=false&y_axis_format=.3s&x_axis_showminmax=y&x_axis_showminmax=false&metrics=sum__count&show_legend=false&flt_eq_0=&flt_col_0=&timeseries_limit_metric=&resample_how=&standalone=true&where=&num_period_compare=&userid=1&previous_viz_type=bar&groupby=count&rich_tooltip=y&rich_tooltip=false&limit=50&x_axis_format=smart_date&datasource_name=User+Registration&contribution=false&time_grain_sqla=Time+Column&having=&bar_stacked=false"
        width="600"
        height="400"
        seamless frameBorder="0" scrolling="no">
      </iframe>
```

**Comment by songyanho** [comment]
@Sarrae1406 I am working on workaround for this issue.

My use case is I want to make dashboard available to anyone with secured URL.
1. I added the permissions required to Public role, which is can dashboard on Superset.
2. I bypass the security check at particular endpoint so that whenever it receives and verifies a hash from frontend, it bypass the check and vice versa.

**Comment by steffenbrand** [comment]
I'm very interested in this feature. Are you still working on it, @songyanho ?

**Comment by pascaldls** [comment]
Very interested in this feature

**Comment by ripoul** [comment]
Any news ?

**Comment by deadlocks** [comment]
@songyanho This feature will be awesome once released. Any updates on this? I can also jump in and help if you have started working on this.

**Comment by joseph-luketelo** [comment]
Any updates on this issue?

**Comment by romens96** [comment]
Hi guys,
You may find this article helpful

https://medium.com/@sairamkrish/apache-superset-custom-authentication-and-integrate-with-other-micro-services-8217956273c1

**Comment by falgunifb** [comment]
can anyone please tell how to fetch value of guest token in superset_config.py file ...as in url am passing token and that token need to verify in config file so it bypass the login screen of superset for user.
http:/localhost.com:8080/login?token=1234&next=/superset/dashboard/11?standalone=true

Thanks in advance!!!!!!
