### ISSUE TITLE
Filters fail to refresh

### ISSUE THREAD

**Issue by szmate1618** [apache/incubator-superset#1906]
Hi Superset people! I think I ran into a little bug. Could you please give me some pointers how to fix it?

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0 and 0.14.1 (I've yet to try it with 0.15.1 - UPDATE: I tried it, see below)

### Expected results
I have a table with a few columns and I have 2 separate filters for columns A and B respectively. The filters also affect eachother e.g. if the table contains records a1|b1|c, a1|b2|c and a2|b3|c and I filter for a2 then the only available value for filterB will be b3 (this seems to be related to the issue, since I can't reproduce it with 1 filter only).
I expect the filters to... well... to work. I need to be able to remove any filtercolumn and add any availabe column.

### Actual results
Sometimes one or both filters 'crash'. There are 2 types of crashes:
- can't remove filtercolumn, I keep clicking on the x, but nothing happens
- can't add new filtercolumn except for one speific column, e.g. a1 (even if the other filter seem to be empty)

When a crash happens or I reload a crashed page (the filterstate is encoded in the url, so reloading also seems to reload the error), I get this errormessage on the javascript console:
`Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
Making the filters immune to eachother doesn't solve the problem.
**Refreshing the crashed filter by clicking on the refresh button in its upper right corner does solve the problem.**

### Steps to reproduce
I admit I'm not 100% sure about what exactly triggers this bug, but if I keep adding and removing filters I always stumble into it, sooner or later.

Thank you in advance!

**Comment by szmate1618** [comment]
Ok, I tested it in 0.15.1, and it's the same. So, this is either a bug in Superset/React or it is caused by some really special constellation of data in my superset.db.
Any advice is greatly appreciated.

**Comment by szmate1618** [comment]
For anyone interested: fortunately, it seems there is a simple workaround: just make the filters immune to themselves.
Good enough for me.

**Comment by heaven00** [comment]
Facing the same issue, @szmate1618 do you have a possible fix implementation for this ?

**Comment by szmate1618** [comment]
No, unfortunately. That workaround was good enough for me, so I never dug into this any deeper, sorry.

**Comment by heaven00** [comment]
I have tried digging but I ain't much of a react dev so what I went with finally is: `turn off instant filtering` 

Multiple filters work the way I intend them to with this.
