### ISSUE TITLE
Actions not stored in logs

### ISSUE THREAD

**Issue by GlombSt** [apache/incubator-superset#1924]
found logs not the be working

### Superset version
0.15.1 against postgres and sqlite3

### Steps to reproduce
start with a clean database in file
load examples
view dashboards
see action log

### Expected results
explore and dashboard activity stored in log and visible

### Actual results
rollback when inserting

from logs when setting logging to debug on sqlalchemy

`>INFO:sqlalchemy.engine.base.Engine:INSERT INTO logs (action, user_id, dashboard_id, slice_id, json, dttm, dt, duration_ms, referrer) VALUES (%(action)s, %(user_id)s, %(dashboard_id)s, %(slice_id)s, %(json)s, %(dttm)s, %(dt)s, %(duration_ms)s, %(referrer)s) RETURNING logs.id
INFO:sqlalchemy.engine.base.Engine:{'json': '{"pandas_aggfunc": "min", "flt_eq_0": "", "datasource_type": "table", "datasource_name": "bi_mark_users", "slice_name": "Users (Accepted - revoked)", "flt_col_0": "", "having": "", "groupby": "cohort", "where": "", "json": "true", "collapsed_fieldsets": "", "force": "false", "viz_type": "pivot_table", "datasource_id": "12", "extra_filters": "{}", "metrics": "Users", "columns": "period", "flt_op_0": "in"}', 'dt': datetime.date(2017, 1, 8), 'slice_id': 0, 'dashboard_id': None, 'dttm': datetime.datetime(2017, 1, 8, 15, 48, 22, 213793), 'action': 'explore_json', 'user_id': '30', 'duration_ms': 669.881, 'referrer': 'https://*********.clark.de/superset/dashboard/76/'}
DEBUG:sqlalchemy.engine.base.Engine:Col ('id',)
DEBUG:sqlalchemy.engine.base.Engine:Row (70066,)
INFO:sqlalchemy.engine.base.Engine:ROLLBACK`

hope I am not missing anything

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 469 days. Feel free to comment and request for this issue to be reopened.
