### ISSUE TITLE
file not found when browsing the portal

### ISSUE THREAD

**Issue by BardiaAfshin** [apache/incubator-superset#1925]
the latest version of superset, when browsing from the browser there are two asset files missing

```
/static/assets/dist/css-theme.0.15.1.entry.js 
/static/assets/dist/common.0.15.1.entry.js 
```

**Comment by BardiaAfshin** [comment]
superset@0.15.1 is the current version.

**Comment by BardiaAfshin** [comment]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar


### Superset version
0.15.1

### Expected results
goto http://localhost:8088/
login

### Actual results
there are missing asset files, page renders without css and files mentioned in the first post to the issue


### Steps to reproduce
on ubuntu install it via

```bash
sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip libsasl2-dev libldap2-dev python-numpy

sudo pip install numpy --proxy=$HTTP_PROXY
sudo pip install pandas --proxy=$HTTP_PROXY
sudo pip install cffi --proxy=$HTTP_PROXY
sudo pip install superset --proxy=$HTTP_PROXY

sudo pip install flask-migrate flask-script flask-testing flask-sqlalchemy humanize gunicorn markdown pandas parsedatetime pydruid PyHive python-dateutil requests simplejson six sqlalchemy sqlalchemy-utils sqlparse thrift thrift-sasl werkzeug  --proxy=$HTTP_PROXY --upgrade

```

bring up the server
```bash
# Create an admin user with credentials (admin/admin)
sudo fabmanager create-admin --app superset


# Initialize the database
sudo superset db upgrade

# Load some data to play with
sudo superset load_examples

# Create default roles and permissions
sudo superset init

# Start the web server on port 8088
sudo superset runserver -p 8088
```

**Comment by BardiaAfshin** [comment]
I can just use a older release of the codebase 0.15.0 to see if it still has this issue.

**Comment by xrmx** [comment]
@BardiaAfshin missing static files usually is matter of compiling your own build and and forget to build them. Since it's not your case to rule out a misconfigured proxy just point to 8088 and see if it loads fine.
BTW If you are using sudo to install superset you are doing something wrong, no need to run superset with privileges, expecially if it's proxied.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 467 days. Feel free to comment and request for this issue to be reopened.
