### ISSUE TITLE
Configuration variables in superset_config.py ignored after PR #1713

### ISSUE THREAD

**Issue by plumbeo** [apache/incubator-superset#1939]
After PR #1713 ("Support running superset via pex") the configuration variables SUPERSET_WORKERS, SUPERSET_WEBSERVER_ADDRESS, SUPERSET_WEBSERVER_PORT and SUPERSET_WEBSERVER_TIMEOUT are silently ignored, with the consequence that the webserver always tries to bind to port 8088 on all available interfaces (incidentally, the default is supposed to be 127.0.0.1 so I think there's something else going wrong, other than ignoring the config variables).

Launching superset with the appropriate command line parameters still works, but it's obviously cumbersome and risk-prone when multiple instances of superset run on the same server or if the server is shared with other services.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 467 days. Feel free to comment and request for this issue to be reopened.
