### ISSUE TITLE
[dashboard] js errors on dashboards

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1957]
- nv.d3.js error on dashboard load
![screenshot 2017-01-11 23 15 32](https://cloud.githubusercontent.com/assets/130878/21880615/c447f246-d854-11e6-99d3-4023e7e931e0.png)

- js error on css icon click
![screenshot 2017-01-11 23 15 40](https://cloud.githubusercontent.com/assets/130878/21880642/e245de2a-d854-11e6-99ee-5cfd30a378a2.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 465 days. Feel free to comment and request for this issue to be reopened.
