### ISSUE TITLE
[explore] time series - line chart is not showing correct time frame reflected in since/until options

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1973]
<img width="1439" alt="screenshot 2017-01-13 12 44 50" src="https://cloud.githubusercontent.com/assets/130878/21945087/3dea8d68-d98e-11e6-8097-de905e843c17.png">

<img width="1440" alt="screenshot 2017-01-26 21 57 47" src="https://cloud.githubusercontent.com/assets/130878/22361850/87941cf2-e412-11e6-9c65-899ca33fb96b.png">

**Comment by ascott** [comment]
looks like the since/until options are working correctly however when the since/until options are given a year input like `1965`, the query is run with the following where clause
`WHERE ds >= '1965-01-31 00:00:00.000000'`. seems like this should be `WHERE ds >= '1965-01-01 00:00:00.000000'`. seems like a small edge case to me since the full date can be entered into the since option as `1965-01-01`. going to unassign myself, if someone else wants to grab this one. feel free.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 446 days. Feel free to comment and request for this issue to be reopened.
