### ISSUE TITLE
Table view in explore v1 generates corrupted query

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#1974]
Steps to reproduce:
1. open long_lat table in the table view
query generated:
```
SELECT
FROM long_lat
WHERE date >= STR_TO_DATE('2017-01-06 13:08:40', '%%Y-%%m-%%d %%H:%%i:%%s')
  AND date <= STR_TO_DATE('2017-01-13 13:08:40', '%%Y-%%m-%%d %%H:%%i:%%s') LIMIT 50000
```

screenshot:
<img width="1424" alt="screen shot 2017-01-13 at 1 08 48 pm" src="https://cloud.githubusercontent.com/assets/5727938/21945703/968124f2-d991-11e6-8726-f58be92ed1a8.png">

**Comment by ascott** [comment]
this screenshot looks like v1. does the issue happen in v2 as well?

**Comment by ascott** [comment]
this is failing in v2 as well

<img width="1440" alt="screenshot 2017-01-13 17 56 56" src="https://cloud.githubusercontent.com/assets/130878/21951340/c9216c78-d9b9-11e6-842d-77463f8b83ff.png">

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 464 days. Feel free to comment and request for this issue to be reopened.
