### ISSUE TITLE
How to disable login/out system

### ISSUE THREAD

**Issue by auroralinan** [apache/incubator-superset#1988]
I know it may be a stupid question, but I still want to know if I can disable login/out system (from flask-appbuilder) and use my own sso system.

Thanks if anyone gives my some suggestions.

**Comment by xrmx** [comment]
I think it would be better to change flask-app-builder to use your sso system instead, i don't know if fab security is extensible or you may have to use your own fork.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 461 days. Feel free to comment and request for this issue to be reopened.
