### ISSUE TITLE
Edit record option getting 404 Error 

### ISSUE THREAD

**Issue by RajkumarKadari** [apache/incubator-superset#2003]
Am getting error when opening through List Sqla Table(show record)

Below error: 

**Not Found**

**The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.**

**Comment by xrmx** [comment]
Please use the template for reporting issues, this is missing too many information to be actionable.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 456 days. Feel free to comment and request for this issue to be reopened.
