### ISSUE TITLE
XSS issue on Welcome page

### ISSUE THREAD

**Issue by deyani27** [apache/incubator-superset#2007]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
I am using old Caravel 0.10.0

### Expected results
I have created one dashboard with this name "test<script>alert(document.cookie)</script>" . 
When opening the welcome page, expected output is to be able to view the dashboard name.

### Actual results
But instead of only viewing it, the alert() is getting triggered.

### Steps to reproduce

Created a dashboard with "test<script>alert(document.cookie)</script>" . 
Go back to Welcome page.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 456 days. Feel free to comment and request for this issue to be reopened.
