### ISSUE TITLE
fail use sql_lab run query when connect to sap hana database

### ISSUE THREAD

**Issue by shen18666080988** [apache/incubator-superset#2022]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.15.0 
### Expected results
run sql 
SELECT * from system.log

### Actual results
(pyhdb.exceptions.ProgrammingError) Prepared statement parameters expected 0 supplied 1.

### Steps to reproduce
install A pure Python client for the SAP HANA Database  use https://github.com/SAP/pyhdb/
install SQLAlchemy dialect for SAP HANA use https://github.com/SAP/sqlalchemy-hana
add  database 'myhana' on superset datasource 's database,salalchemy 's url use  "hana://SYSTEM:XXXXXXXXXX@10.76.11.3:30015" and test ok
define  a query on sql lab 's sql editor use "select * from system.log"  with database selected myhana without schema.

**Comment by mistercrunch** [comment]
It would help to have the full stack trace, though I doubt I can help much without an SAP Hana instance laying around.

**Comment by shen18666080988** [comment]
programingError: (pyhdb.exceptions.ProgrammingError) Prepared statement parameters expected 0 supplied 1. [SQL: u'SELECT id, "USER", date, adress,\n                         name,\n                         remark,\n                         ipadress\nFROM log LIMIT 100'] [parameters: {'schema': None}]
2017-01-25 11:03:16,231:ERROR:root:(pyhdb.exceptions.ProgrammingError) Prepared statement parameters expected 0 supplied 1.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/superset/views.py", line 2500, in sql_json
    data = sql_lab.get_sql_results(query_id, return_results=True)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/superset/sql_lab.py", line 132, in get_sql_results
    handle_error(utils.error_msg_from_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/superset/sql_lab.py", line 88, in handle_error
    raise Exception(query.error_message)
Exception: (pyhdb.exceptions.ProgrammingError) Prepared statement parameters expected 0 supplied 1.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 453 days. Feel free to comment and request for this issue to be reopened.
