### ISSUE TITLE
Question: Pivot Tables and Time

### ISSUE THREAD

**Issue by mearroyo** [apache/incubator-superset#2029]
### Superset version
0.15.1

When using a pivot table, is there a way to pivot using the time column, at the time grain set for the slice?

For example:

![image](https://cloud.githubusercontent.com/assets/15230944/22259339/f3d69db8-e232-11e6-9dd2-841780fda8ea.png)

As an example, I'd like to have every column aggregate the Sum of the IDs that are created in that month (I know, not super sensical to add IDs, just an examples) instead of on each specific date.

Thanks!

**Comment by RichRadics** [comment]
There's a multi-step way of doing this - first, generate a Time Series Bar Chart, with your required time granularity and grouping. Next, take the generated SQL (from the JSON), run that into SQL Lab to create a table source based on the query, and then create a pivot based on that. Clunky, but it works for one-offs. The permanent solution would be a Time-Pivot viz, but someone would need to write it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 451 days. Feel free to comment and request for this issue to be reopened.
