### ISSUE TITLE
Condition never met for having_filters (Druid query)

### ISSUE THREAD

**Issue by 0x0ece** [apache/incubator-superset#2035]
I noticed that here:
https://github.com/airbnb/superset/blob/master/superset/models.py#L2385
the condition `or having_filters` is never met, meaning that you can enter in this branch only when len(groupby) > 1, independently from the value of `having_filters`.
Is this intended?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 303 days. Feel free to comment and request for this issue to be reopened.
