### ISSUE TITLE
Druid datasource table view ignores granularity

### ISSUE THREAD

**Issue by 0x0ece** [apache/incubator-superset#2039]
If I click on a Druid datasource, it opens a default table view, where the time granularity is default to 1 day.

In older versions, such as 0.10.x, the result was 7 records, with a timestamp and a count per each time window.

In newer versions, tested on 0.15.2 and master, there's only 1 single global counter, and all the parameters related to granularity are ignored.

Digging into the code, TableView has is_timeseries=False, and this commit:
https://github.com/airbnb/superset/commit/ea189790f160dc6419ac97d8f6740afa62ba6e78
imposes that is_timeseries==False => granularity="all".

Is this intended, or sort of a regression while fixing something else?

**Comment by dene14** [comment]
Looks like regression, we cannot use granularity selectors with 0.15.x :(

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 303 days. Feel free to comment and request for this issue to be reopened.
