### ISSUE TITLE
Editing table record results in "Not Found"

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#2052]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

The installation was upgraded today from 0.15.1, following the steps advised in the upgrade manual.
The DB both used for superset itself and the data tables is Postgres 9.5

### Expected results
Table editing page loads when clicking "edit record" in Sources → Tables overview.

### Actual results
Whatever table is selected — existing one or freshly created —,  I only get

```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```
The console log doesn't provide any help as well, as this is the only message when clicking the "edit record" button:

```
/opt/apps/superset/venv_2.7/lib/python2.7/site-packages/flask_appbuilder/forms.py:245: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = self(obj=obj)
```

### Steps to reproduce
Click the "edit record" button.

**Comment by rumbin** [comment]
I just noticed that this issue had already been reported in #462.

Not sure whether this bug can be closed as well.

For anyone else running into this trouble:
Clearing the cookies seems to be a suitable workaround.

**Comment by bkyryliuk** [comment]
@rumbin did clearing cookies help you?

**Comment by rumbin** [comment]
Well, sorry for being ambiguous about this.
Yes! After clearing the cookies, everything is back to normal.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 451 days. Feel free to comment and request for this issue to be reopened.
