### ISSUE TITLE
405 error when trying to Visualize query results

### ISSUE THREAD

**Issue by CoryChaplin** [apache/incubator-superset#2071]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
Open Slice view from the query results

### Actual results
405 error

<img width="1423" alt="superset 2" src="https://cloud.githubusercontent.com/assets/5139669/22395587/1adf4afa-e543-11e6-96e1-11bb1d2eb4d3.png">

### Steps to reproduce
Clic "Visualize" from the results of a query.

<img width="594" alt="superset" src="https://cloud.githubusercontent.com/assets/5139669/22395583/133ef1f6-e543-11e6-9115-6d8538445e79.png">

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 450 days. Feel free to comment and request for this issue to be reopened.
