### ISSUE TITLE
Add a link to go to slice view from slice editor

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2089]
add  link from slice model edit page(/slicemodelview/edit/{id}) to corresponding explore/view page (/explore/table/2806/?goto_dash=false&new_dashboard_name=&slice_name=Mobile+Product+Feedback+-+Raw+Submissions&....)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 409 days. Feel free to comment and request for this issue to be reopened.
