### ISSUE TITLE
Use column [d3] formatting in table/pivot on both explore and dashboard views

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2099]
I think this never worked on Pivot viz, and there may be a regression on Table in Dashboard view after deprecating explorev1

**Comment by yileic** [comment]
#2058

**Comment by macfly1202** [comment]
1/ I think I have the same issue with Druid as I understand here :  
d3 units are well displayed on 'slices view' (D3 '.2f' -)> a basic eCPM as an example 
![capture d ecran_2017-03-17_09-35-46](https://cloud.githubusercontent.com/assets/6387630/24049673/048504d8-0b2d-11e7-8e9a-790619ae9696.png)
On 'dashboard view' the same data appear : 
![capture d ecran_2017-03-17_09-35-25](https://cloud.githubusercontent.com/assets/6387630/24049713/252d86a6-0b2d-11e7-95cd-e7006058fe2a.png)

2/ Is there a way to force formats/units with JSON Metadata specific parameter of Dashboard ?  

Thanks

**Comment by mistercrunch** [comment]
It requires a bit of work to be fixed

**Comment by macfly1202** [comment]
Thanks for answer and all the great work here. Hope it will arrive soon. My boss think he has the best eCPM in the world lol ...

**Comment by LoYoPP** [comment]
same issue too .
I changed the default column d3 format to  'fix' this issue.

+ superset/static/assets/javascripts/modules/utils.js

 `
 //format = format || '.3s';`
`format = format || '.2f';`

+ superset/static/assets/javascripts/modules/superset.js

 `
//format = format || '.3s';`
 `format = format || '.2f';`

+ and then [rebuild ](https://github.com/airbnb/superset/blob/master/docs/installation.rst#making-your-own-build) the files

**Comment by macfly1202** [comment]
Hi, I still encounter this issue I write on 17th March with d3 formatting. Has it been planned on the roadmap to be definitely fixed? It's very annoying to have for example 0.257 in the first column and 257m (for the same numeric value)  in the second column of the same table.
Thank you very much for the answer.

**Comment by Stevie337** [comment]
Is there any plan on adding formatting abilities for tables in the future? Would like to format it as f0 for example, but there is no possibility in the slice editor
