### ISSUE TITLE
[sql-lab] disable run query button if sql editor is empty

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2102]
<img width="746" alt="screenshot 2017-02-02 18 25 58" src="https://cloud.githubusercontent.com/assets/130878/22577209/1cd43b3c-e975-11e6-8008-7f745334c7f7.png">

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.
