### ISSUE TITLE
Add an option to filter using like / not like statements in explore view

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2108]

**Comment by mistercrunch** [comment]
@bkyryliuk I'm not sure if I understand this. Is it fixed?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 418 days. Feel free to comment and request for this issue to be reopened.

**Comment by gdoron** [comment]
@mistercrunch I think there is still no way to do "NOT LIKE" in table filters, unless I'm missing something.
