### ISSUE TITLE
NVD3 Bar Labels don't respect field formats

### ISSUE THREAD

**Issue by alanmcruickshank** [apache/incubator-superset#2128]
### Superset version
0.15.1 - examining `superset/assets/visualizations/nvd3_vis.js` this appears to be still hard coded on master

### Expected results
Bar labels should inherit formats as follows:
1. y-axis label d3 formatting
2. metric d3 formatting 
3. fallback onto `.3s` if neither found

### Actual results
d3 formatting of `.3s` is hard coded into the `addTotalBarValues ` function in `nvd3_vis.js` and so regardless of other formatting signals, the value is always displayed as `.3s`

screenshot:
![image](https://cloud.githubusercontent.com/assets/4670904/22698021/3957a986-ed4b-11e6-86d6-2015a212b426.png)

code showing hard codedness
```
const addTotalBarValues = function (chart, data, stacked) {
  const svg = d3.select('svg');
  const format = d3.format('.3s');
  const countSeriesDisplayed = data.length;
```

### Steps to reproduce
Bar Chart Viz, turn bar labels on, pick a data source with very small values and set the y axis format to `.2f`. The bar labels will not respect that formatting string.

**Comment by valyabarboy** [comment]
Seconding this need, pretty please!

**Comment by jbot5000** [comment]
Did this ever get sorted?
