### ISSUE TITLE
Is it support Deepgreen?

### ISSUE THREAD

**Issue by lujianmei** [apache/incubator-superset#2144]
Checked that Greenplum has been supported, but what about Deep Green? Thanks

**Comment by xrmx** [comment]
Any chance you can try and tell us?

**Comment by mistercrunch** [comment]
is Deep Green a Postgres derivative like green plum?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 437 days. Feel free to comment and request for this issue to be reopened.

**Comment by pankajsoni22** [comment]
> 

How to connect to greenplum, not able to figure out ?
