### ISSUE TITLE
How to paging data in Distribution Bar Chart?

### ISSUE THREAD

**Issue by wuwanjie** [apache/incubator-superset#2149]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.15.4

### Expected results

when i use Distribution Bar Chart，I just can row limit 50000.
can i paging data，every page just have 100 items,

**Comment by mistercrunch** [comment]
the reason why we limit to 50k is we don't want to crush people's browser, 50k is already pretty massive.

Who can look at 50k bars and make sense of them anyways? You may want to use ranges.

But to answer your question I believe you can bump ROW_LIMIT in your `superset_config.py`.

**Comment by wuwanjie** [comment]
I kown that browser will crush when loaded lots of datas.    ROW_LIMIT just control top N items. It may be different from paging all items.

how to use ranges ? can you give me url.

**Comment by mistercrunch** [comment]
Use a calculated column with a `CASE WHEN` statement, as in `CASE WHEN age <= 10 THEN '<10' WHEN age <= 20 THEN '10-20' ELSE '>20' END`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 433 days. Feel free to comment and request for this issue to be reopened.
