### ISSUE TITLE
SQLAlchemy Sphinx

### ISSUE THREAD

**Issue by vyuldashev** [apache/incubator-superset#2150]
Installed https://github.com/conversant/sqlalchemy-sphinx.

Adding database:

SQLAlchemy URI: sphinx://*ip*:*port*

IP and port are correct.

Pressing "Test Connection" button gives:

ERROR: Connection failed!

The error message returned was:
'NoneType' object has no attribute 'replace'

**Comment by xrmx** [comment]
What does the superset logs say?

**Comment by vladimir-yuldashev** [comment]
@xrmx nothing

**Comment by xrmx** [comment]
@vladimir-yuldashev strange there should be an interesting backtrace

**Comment by vladimir-yuldashev** [comment]
@xrmx Any ideas?

**Comment by mistercrunch** [comment]
Seems like a bug in that library, a full stacktrace would help making that clear. Are you able to use SQLAlchemy against that DB with that connection string using that dialect in a simple script?

A step by step approach to debugging this:
* clone the sqlalchemy-sphinx repo
* install it from source by running `python setup.py develop` in the root of that repo
* write a simple script that creates a SQLAlchemy connection using your connection string
* hopefully get a stack trace coming from somewhere in sqlalchemy-sphinx, debug
* if no stack trace, look in that library for `try:` blocks that silence error, add a logging.exception(e) line in the `except:` block
* fix bug
* send PR to sqlalchemy-sphinx

**Comment by vladimir-yuldashev** [comment]
@mistercrunch 

wrote a simple script:

	from sqlalchemy import create_engine, Column, Integer, String, BigInteger, Unicode, Enum
	from sqlalchemy.ext.declarative import declarative_base
	from sqlalchemy.orm import deferred, sessionmaker

	engine = create_engine('sphinx://192.168.1.10:9306')
	connection = engine.connect()

	result = connection.execute("select count(*) from users")

	for row in result:
	        print(row)

	connection.close()

And it works. So it seems like there is no bug in library.

**Comment by mistercrunch** [comment]
We'll it's not like you battle tested the entire lib here. Try `engine.table_names()`

**Comment by vladimir-yuldashev** [comment]
@mistercrunch 

Got the error with `engine.table_names()`:

	Traceback (most recent call last):
	  File "test.py", line 8, in <module>
	    engine.table_names()
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2119, in table_names
	    return self.dialect.get_table_names(conn, schema)
	  File "<string>", line 2, in get_table_names
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py", line 42, in cache
	    return fn(self, con, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1707, in get_table_names
	    self.identifier_preparer.quote_identifier(current_schema))
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py", line 2875, in quote_identifier
	    self._escape_identifier(value) + \
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 78, in _escape_identifier
	    value = value.replace(self.escape_quote, self.escape_to_quote)
	AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by xrmx** [comment]
@vladimir-yuldashev puzzled on why mysql dialect is used for reflection

**Comment by vladimir-yuldashev** [comment]
@xrmx Yes, it's strange because Sphinx does not have tables.

**Comment by mistercrunch** [comment]
I'm guessing that Sphinx sqla dialect must inherit or be copied over from the mysql one. I don't know anything about Sphinx but if it doesn't have tables I'm not sure how this is going to work...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 433 days. Feel free to comment and request for this issue to be reopened.
