### ISSUE TITLE
Superset MySQL Queries taking a long time

### ISSUE THREAD

**Issue by chebu** [apache/incubator-superset#2155]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
when I run queries using Superset against MySQL database on my local machine it takes significantly longer than running the same query from a mysql command line. A simple query like "SELECT count(*) FROM table_a" takes less than 1 second when executed from a mysql command line while taking more than 20 sec when I run it from Superset which is running on the same machine. Is there any way to fix that?

**Comment by xrmx** [comment]
Where is the time spent? Are you measuring the exact same query?

**Comment by chebu** [comment]
I am using exactly the same query and comparing the time of the timer on the right in SQL Editor and the time given when executing the query from mysql command line. The same queries from SQL Editor in Superset take about 20 sec longer.

"Where is the time spent? " is also my question.

**Comment by Georgepentaho** [comment]
I have meet the same problem, waiting for the solution.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 434 days. Feel free to comment and request for this issue to be reopened.

**Comment by aleks-walker** [comment]
The problem is still there. For some reason, queries inside superset are much slower than the same queries from the console.

**Comment by vikm2o** [comment]
I see the same issue with clickhouse . Clickouse query takes 1 sec but the same query with sql lab takes 8-9 sec.
