### ISSUE TITLE
[sqllab] Multiple Statement Queries

### ISSUE THREAD

**Issue by chebu** [apache/incubator-superset#2156]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
Is there a way to run multiple statement queries in Superset? For example "SET @x= (SELECT count(*) FROM table_a) ; SELECT column_1/@x, column_2 FROM table_b"
When I try to run something similar I get "(_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")"

**Comment by kumarit** [comment]
after establish the connection between kylin and superset, i am trying to use sqllab for fetching the table from kylin to do visualization in superset!
here is my sql query:
SELECT *
FROM
KYLIN_SALES

i am getting this error, pls help me , thanks in advance!!:

{"status": "failed", "query_id": 21, "error_essage": "Error when requesting: \"query\", exception: \"Project name should not be empty.\""}
![screenshot from 2017-08-09 16 03 03](https://user-images.githubusercontent.com/30621931/29125530-47524c42-7d1c-11e7-9509-7df9dd4a43e6.png)

**Comment by mistercrunch** [comment]
@kumarit this seems unrelated to this issue. You should open another issue.

**Comment by zhaoyongjie** [comment]
This response is from kylin REST api, that means you must specify Kylin project name when you query.

Please use this Sqlalchemy Dialect:
```
https://github.com/Kyligence/kylinpy
```
