### ISSUE TITLE
Full screen support for dashboard

### ISSUE THREAD

**Issue by fritzwijaya** [apache/incubator-superset#2167]
Dashboard could be present on full screen mode. The dashboard would be perfect to show on larger screen (i.e. tv)

**Comment by xrmx** [comment]
Isn't full screen mode a browser feature? What's not working?

**Comment by steffenbrand** [comment]
It would be a nice feature if you could hide the navigation and maybe hide or shrink the dashboard title. So I can use the dashboard for a big screen in the office.

**Comment by DaanNusman** [comment]
You could add some CSS to the board that removes the top navigantion bar, i.e.,

```
.top 
{
    display : none;
}

```

I suppose the other changes can be done this way as well.

**Comment by mistercrunch** [comment]
This used to work by adding a get parameter `?standalone=true` in the URL, fix here:
https://github.com/apache/incubator-superset/pull/3284
