### ISSUE TITLE
flasher is not working properly

### ISSUE THREAD

**Issue by yileic** [apache/incubator-superset#2183]
When using "flasher", need to refresh the page to see the message displayed by flasher.
If we modified "models.py", and want to display a warning message without raising exception in models.py, what is a good way to achieve that, since flasher is not working properly. Thank you very much for your attention!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 431 days. Feel free to comment and request for this issue to be reopened.
