### ISSUE TITLE
SAWarning: Can't resolve label reference 'username asc'

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2186]
sueprset-0.15.4

http://10.27.199.57:8888/userstatschartview/chart/0
```
2017-02-16 15:26:59,939:INFO:flask_appbuilder.security.sqla.manager:Updated user superset jinjy
/root/superset/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:575: SAWarning: Can't resolve label reference 'username asc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
```

![image](https://cloud.githubusercontent.com/assets/8108788/23011591/d15c7bcc-f45c-11e6-9ca0-30f80dd0892a.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 430 days. Feel free to comment and request for this issue to be reopened.
