### ISSUE TITLE
./superset/static/assets should be a symbolic link to `../assets`

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2187]
superset-0.15.4
cat /root/env/code/superset/static/assets
`../assets`
There should be a symbolic link file, why we don't note it in Doc or wiki?
![image](https://cloud.githubusercontent.com/assets/8108788/23011724/81187fca-f45d-11e6-8a2f-9c422bb3a02d.png)

**Comment by xrmx** [comment]
Uhm i have it in my checkout

**Comment by asdf2014** [comment]
Nice! Look forward to :-)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 430 days. Feel free to comment and request for this issue to be reopened.
