### ISSUE TITLE
Permission not work in dashbroad

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2204]
superset==0.15.4

Why the `gamma` user own the access permission of `birth_names` datasource, however superset still report the problem:
```
This endpoint requires the datasource birth_names, database or `all_datasource_access` permission
```

![image](https://cloud.githubusercontent.com/assets/8108788/23120051/bf4177a8-f795-11e6-9cbc-732b7c056fd0.png)

![image](https://cloud.githubusercontent.com/assets/8108788/23120085/eb0f2d4e-f795-11e6-9297-1f41293a0455.png)

![image](https://cloud.githubusercontent.com/assets/8108788/23120090/f1e37cce-f795-11e6-9362-a3d38a4c3f4f.png)

Slices on dashbroad:
![image](https://cloud.githubusercontent.com/assets/8108788/23120152/3587b152-f796-11e6-879b-a2440c6fc6da.png)

**Comment by xrmx** [comment]
@asdf2014 i think you can have the skills to debug this easily :) Also please replicate with latest master or 0.16.0 tag, 0.15.4 is a month old, issues may have been fixed already.

**Comment by asdf2014** [comment]
Alright... I will try it. @xrmx

**Comment by vitolipari** [comment]
I have the same issue, @asdf2014 have you fixed it?

**Comment by asdf2014** [comment]
@vitolipari  Yep, you should try the latest version of superset. BTW, you can get more details from my blog [[yuzhouwan.com](https://yuzhouwan.com/posts/743/)].
