### ISSUE TITLE
Can't find dependencies to install (libsasl2-devel & python-wheel)

### ISSUE THREAD

**Issue by kaiosama** [apache/incubator-superset#2205]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
Trying to install dependencies on CentOS 6.6 according to the installation instruction:
```
sudo yum install gcc libffi-devel python-devel python-pip python-wheel openssl-devel libsasl2-devel openldap-devel
```

### Actual results
yum cannot find packages: libsasl2-devel and python-wheel

### Steps to reproduce
run the yum installation cmd

### Note
I then installed cyrus-sasl-devel in place of what is supposed to be libsasl2-devel. I was then able to install and run Superset. However there is something wrong with the LDAP auth login under python 2.7 (but works under python 3.5), so I wonder if it is the right thing to do. Please advice and thanks in advance!

p.s.
I have these python sasl libs:
pure-sasl (0.3.0)
sasl (0.2.1)
thrift-sasl (0.2.1)

**Comment by gumho** [comment]
I'm running into this issue too. This is occurring on CentOS 6.8.

**Comment by bcondron** [comment]
SASL2 is something pretty strange in RH/CentOS land.

I want to say it's cyrus sasl or something like that.
Alternately, you can always build from source.

http://www.cyrusimap.org/sasl/sasl/installation.html#tarball-installation

**Comment by bcondron** [comment]
This isn't really an issue with superset.

You can try pointing your yum to a different repo set, but you're probably best off just building from source. Cyrus sasl meets the need for libsasl2-devel.

For python-wheel, you need to enable EPEL first. 

Alternately, you can download the rpm and do a yum localinstall, or of course you can build from source.

**Comment by mistercrunch** [comment]
Would love to get someone to update the docs with a solution though!

**Comment by yogeshak** [comment]
I installed cyrus-sasl-devel.x86_64 package on Fedora as libsasl2-devel is not available in repo.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 306 days. Feel free to comment and request for this issue to be reopened.

**Comment by okcomputerik** [comment]
I know this issue was posted and closed long ago, but for anybody still looking for a solution, I got over it installing python-devel and openldap-devel (from [here](https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap)).
