### ISSUE TITLE
Refresh druid process (CLI / endpoint) should create perms as it creates datasources

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2206]
May i ask a question about permission, `superset` can support assign permissions with those datasources of `druid`?

Cuz i only can find those permission options like `[datasource access on [main].[birth_names](id:3)]` about `SQLite`, `MySQL` etc, rather than `Druid`.

![image](https://cloud.githubusercontent.com/assets/8108788/23146811/1eff0708-f815-11e6-9fdc-cb5ed1cd7f00.png)

**Comment by mistercrunch** [comment]
Does running `superset init` create the missing perms? How do you currently sync Druid's metadata?

**Comment by asdf2014** [comment]
Yeah, i have been synchronized Druid's metadata with `superset refresh_druid` command.

**Comment by asdf2014** [comment]
Is the `superset init` command nessnary?

**Comment by asdf2014** [comment]
Wait a second, i try them.

**Comment by asdf2014** [comment]
It works! Thank u so much :D

![image](https://cloud.githubusercontent.com/assets/8108788/23156249/22efa96c-f851-11e6-9912-8e6266ddb7f8.png)

**Comment by asdf2014** [comment]
Should we add some notes for it in `Superset` document [Security](http://airbnb.io/superset/security.html#managing-gamma-per-data-source-access)

**Comment by nishantmonu51** [comment]
@asdf2014: it is already documented here - http://airbnb.io/superset/installation.html

**Comment by mistercrunch** [comment]
We should make it such that `superset refresh_druid` creates perms where needed. I'll hickjack this issue by renaming it.

**Comment by asdf2014** [comment]
@nishantmonu51  I see. That very good, but it just notice us to use the `superset init` command when we `Create default roles and permissions` or `Upgrade superset` rather than changing something about permission...

**Comment by ShengyaoQian** [comment]
Hi is this being worked on? We would want the view_menus to be add right after refreshing. So we can assign them to users. Also when a datasource is deleted, the associated perms should also be delete right? Right now it doesn't seem to do that. Can I get an update on this issue? If it is not being worked on, I'd like to work on a pull request.

**Comment by mistercrunch** [comment]
@ShengyaoQian please submit a PR, we have a different way of updating metadata at Airbnb that doesn't use the exposed endpoint or CLI command from Superset. It should be pretty straightforward.

**Comment by mistercrunch** [comment]
Also note that if the issue is open and there's no assignees you can assume it is not being worked on at the moment.

**Comment by ShengyaoQian** [comment]
@mistercrunch Sure. I will work on a PR. I don't think I can assign the task to myself.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 369 days. Feel free to comment and request for this issue to be reopened.
