### ISSUE TITLE
Suggest user to do sampling if result set if too large

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2211]
Example query
`SELECT * FROM users TABLESAMPLE BERNOULLI (50);`
 More: https://prestodb.io/docs/current/sql/select.html

The error message should guide user to user sampling.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 423 days. Feel free to comment and request for this issue to be reopened.
