### ISSUE TITLE
[dashboard model view] don't add admin user as owner if admin makes changes to dashboard properties

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2212]
steps to repro:
1. as admin, make and save changes to a dahboard properties: /dashboardmodelview/edit/{id}
2. view/edit dashboardmodelview and admin user is now added as an owner.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 425 days. Feel free to comment and request for this issue to be reopened.
