### ISSUE TITLE
time column doesn't recognize format with datetrunc

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#2215]
When using datetrunc in sql query, the visualize flow returns 'No data' for time series chart

Steps to reproduce:
 - run a query with datetrunc function on date column
 - visualize query results using Time Series Line Chart

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 425 days. Feel free to comment and request for this issue to be reopened.
