### ISSUE TITLE
[bar chart] fix long axis labels

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2221]
![screenshot 2017-02-22 11 20 37](https://cloud.githubusercontent.com/assets/130878/23228335/09c1ee14-f8f1-11e6-8949-edf90e0f220c.png)

**Comment by sdressler** [comment]
Actually, would you have a suggestion how it should look like once it is fixed?

**Comment by mistercrunch** [comment]
There's an "auto" option as well as a way to specify the bottom margin now, closing.
