### ISSUE TITLE
[big num] allow markdown in subheader field

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2224]
- allow markdown in subheader field
- wrap long lines

![screenshot 2017-02-22 14 31 58](https://cloud.githubusercontent.com/assets/130878/23235852/dbd2785a-f90b-11e6-9b13-ec8739b4e9d4.png)

**Comment by mistercrunch** [comment]
at the moment it's svg but I think it's possible to embed html in svg somehow, or layer it on top

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 423 days. Feel free to comment and request for this issue to be reopened.
