### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (NOT FOUND)

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2229]
superset==0.16.0

Failed to load resource: the server responded with a status of 404 (NOT FOUND)

![image](https://cloud.githubusercontent.com/assets/8108788/23247478/54309a4c-f9d5-11e6-99fc-9c647bf1732d.png)

**Comment by asdf2014** [comment]
The path of file should not be the problem...
![image](https://cloud.githubusercontent.com/assets/8108788/23247516/87f78b06-f9d5-11e6-8e5c-9d96a29c27a0.png)

**Comment by xrmx** [comment]
How did you install it? Looks like static files were not build.

**Comment by asdf2014** [comment]
Yep, it could be linked to https://github.com/airbnb/superset/issues/2187

**Comment by chengyoucai** [comment]
i use
pip install 0.16.1.tar.gz
found the same error.

**Comment by aurora5161** [comment]
@asdf2014 ,I have the same problem as you ! have you solved the problem ?

**Comment by asdf2014** [comment]
@aurora5161 Not yet. We decide use the `superset` that version is `0.15.4` in product environment. Newest version `0.16.0` `superset`'s test coverage is too low to use it as formal product. I think if you are not very anxious, you can wait a while for a more stable version of the release. :-)

**Comment by asdf2014** [comment]
@xrmx Why do you close this issues, is it already resolved? Please link the involved `PR`.

**Comment by aurora5161** [comment]
@asdf2014 ,thank you very much for your advice,the version 0.15.4 can solve the 404 problem!

**Comment by asdf2014** [comment]
@xrmx But why is `superset v0.16.0` re-importing this question? Same situation like `Gravatar` issues (www.gravatar.com), do you know if you have noticed it in `superset v0.17.0`.

**Comment by buptljy** [comment]
0.17.5 still doesn't fix it.
I uninstall superset 0.17.5 and install 0.16 and it works.

**Comment by mistercrunch** [comment]
@buptljy can you describe your issue? Somehow your server isn't serving the JavaScript files?

**Comment by buptljy** [comment]
First I installed superset-0.17.5 by following  the official site. But  when I opened http://localhost:8088 and I got exactly the same view as the screenshot shown above, which was a 404 error and no resources file(including css and js files). So I unistalled superset and turned to superset-0.16 and everything went well.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 364 days. Feel free to comment and request for this issue to be reopened.
