### ISSUE TITLE
Make sql editor box adjustable

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#2237]

**Comment by dmigo** [comment]
I would be happy to work on that, if nobody minds.

**Comment by xrmx** [comment]
@dmigo quite the opposite i think :)

**Comment by dmigo** [comment]
@xrmx is it that bad?

**Comment by xrmx** [comment]
@dmigo i mean you are more than welcome to tackle any issue :)

**Comment by dmigo** [comment]
This one may be closed =)

**Comment by mistercrunch** [comment]
Solid work @dmigo 
![img](http://reactiongifs.me/wp-content/uploads/2013/09/anchorman-yes-jumping.gif)
