### ISSUE TITLE
[sql-lab] Initial state SQL is truncated at first = character

### ISSUE THREAD

**Issue by nkconnor** [apache/incubator-superset#2296]
### Superset version
0.15.4

SQL Lab query editor is truncated at the first `=` character. First noticed this when using the Query search editor

### Steps to reproduce

http://localhost:8088/superset/sqllab?sql=SELECT%0A%20%20%20%201%20AS%20%60COLUMN%60%0AFROM%20(%20SELECT%202%20=%205%20)%20t%0AWHERE%20TRUE%20&title=Untitled%20Query

**Comment by mistercrunch** [comment]
What you wrote here could mean different things please provide more context.

**Comment by nkconnor** [comment]
The SQL Editor should be autofilled with:
```
SELECT
    1 AS `COLUMN`
FROM ( SELECT 2 = 5 ) t
WHERE TRUE
```

instead it gets truncated to:

```
SELECT
    1 AS `COLUMN`
FROM ( SELECT 2 
```
