### ISSUE TITLE
`superset` still alert `associated data exists` when i delete all related slices and dashboards

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2318]
superset==0.15.4

When I removed all the relevant slicers and dashboards, why `superset` still warns about the existence of relevant data? And i do not know what the relevant data is...

![image](https://cloud.githubusercontent.com/assets/8108788/23490365/43c59474-ff33-11e6-9f1c-56f70243747f.png)

**Comment by zhangjiajie023** [comment]
I meet this issue too.

**Comment by sithadministrator** [comment]
Why is this closed

**Comment by cscainiao** [comment]
logs or query

**Comment by hemantaggarwal** [comment]
Does anyone find solution to this? I have one user with no data associated to it but I am still getting this error.

**Comment by fremantletechnology** [comment]
I had to also clean up these records :
delete from public.url 	where created_by_fk = myUserID or  changed_by_fk = myUserID ;	
delete from public.logs where user_id = myUserID  ;
delete from public.slice_user where user_id =myUserID  ;

**Comment by ChangbingChen** [comment]
> I had to also clean up these records : delete from public.url where created_by_fk = myUserID or changed_by_fk = myUserID ; delete from public.logs where user_id = myUserID ; delete from public.slice_user where user_id =myUserID ;

Greats! It works for me. Besides the  related records of the favstar table.
