### ISSUE TITLE
Metric Restriction Not Working

### ISSUE THREAD

**Issue by jnawras** [apache/incubator-superset#2326]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

I'm able to create metric access permissions but users who do not have this permission are still able to access the metric on slices and dashboards.

### Superset version
0.17.0

### Expected results
Roles with no Metric_Access_Permission_on_Metric_XXX should not be able to view/access this metric

### Actual results
Roles with no Metric_Access_Permission_on_Metric_XXX can view/access this metric given they have Datasource_Access_Permission....

### Steps to reproduce
Click "Is Restricted" on the metric in its datasource(table), 
save, 
build slice/dashboard of containing this metric, 
re-init and re-runserver on superset
Now check if users have access to this metric via slices/dashboards.

**Comment by jnawras** [comment]
Did anyone ever tried this feature and it worked for them?

**Comment by Aung-Myint-Thein** [comment]
I tried this feature but the issue I faced is I cannot even see "metric access on xxx" permission on my permissions list. So, cannot control access and users without this access still can see all the metrics.

**Comment by Aung-Myint-Thein** [comment]
@jnawras have you solved this problem?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 250 days. Feel free to comment and request for this issue to be reopened.
