### ISSUE TITLE
[Bug]druid Approximate Histogram post-aggregations

### ISSUE THREAD

**Issue by fangyeqing** [apache/incubator-superset#2344]
@bkyryliuk  When I use this feature, I found a bug :
[Support more druid postaggregations#2235](https://github.com/airbnb/superset/pull/2235)

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
source code version: 9d8d4213840cc07d95ac971437632aeae4ff58b5

#### Step 1. At Druid's ingestion time
 "approxHistogramFold" aggregator is created as follows:
```
{
          "type" : "approxHistogramFold",
          "name" : "rsp_time",
          "fieldName" : "rsp_time",
          "resolution" : 500,
          "numBuckets" : 500,
          "lowerLimit" : 0.0
}
```
#### Step 2. Create Druid Metrics in Superset
**Metrics NO1: "approxHistogramFold" aggregator**
![metrics1](https://cloud.githubusercontent.com/assets/7553284/23606335/38284f88-029b-11e7-90a1-d1ac828fc397.PNG)

**Metrics NO.2: post-aggregators**
![metrics2](https://cloud.githubusercontent.com/assets/7553284/23606444/b7ba77e4-029b-11e7-9709-4f9c220619eb.PNG)

#### Step 3.Query in Superset
When choose both post-agg **response_0.99** and approxHistogram-aggregator **rsp_time**, you can get the right result
![resp1](https://cloud.githubusercontent.com/assets/7553284/23608726/ada6ae1c-02a5-11e7-95ac-749d50c0ce32.PNG)

But, when only choose post-agg response_0.99, 
```
HTTP Error 500: Server Error Druid Error: None Query is: { "aggregations": [], "intervals": "2017-02-27T18:40:21+00:00/2017-03-06T18:40:21+00:00", "dataSource": "adtime_stat", "granularity": "all", "postAggregations": [ { "fieldName": "rsp_time", "type": "quantile", "name": "response_0.99", "probability": 0.99 } ], "queryType": "timeseries" }
```
Because to query for results, an "approxHistogramFold" aggregator must be included in the query，we can see the official [doc](http://druid.io/docs/0.9.2/development/extensions-core/approximate-histograms.html) for details

### Bug fix
https://github.com/airbnb/superset/pull/2345

### Others
When I create a "quantiles"post-agg
![quan2](https://cloud.githubusercontent.com/assets/7553284/23610397/448d44a6-02ad-11e7-888f-10f22cbe42f2.PNG)

Then I send a query request, and I get **Object object**, it's hard to read 
![quan0](https://cloud.githubusercontent.com/assets/7553284/23610150/7de841fc-02ac-11e7-8e5f-6bedd24c43e4.PNG)

 I think the display of "quantiles"post-agg can be more readable
![resp1](https://cloud.githubusercontent.com/assets/7553284/23610151/7de87f46-02ac-11e7-942b-55ff55889179.PNG)

#### PR
https://github.com/airbnb/superset/pull/2346

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 413 days. Feel free to comment and request for this issue to be reopened.
