### ISSUE TITLE
db_engine_spec.handle_cursor exceptions are not handled

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#2349]
if query fails in presto - error message isn't displayed

**Comment by dmigo** [comment]
Do you know if there is a general plan on how to handle presto exceptions? 
ATM it just displays a huge piece of JSON with the whole stack trace inside. I'm wondering what would be the right approach on handling those.

**Comment by mistercrunch** [comment]
@dmigo https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py#L607
this code worked at Airbnb but doesn't work at Lyft. I need to fix this too.

**Comment by mistercrunch** [comment]
Closing this in favor https://github.com/apache/incubator-superset/issues/4013

**Comment by dmigo** [comment]
@mistercrunch 

> this code worked at Airbnb

Does the past tense mean that it is not known if it works now?
