### ISSUE TITLE
Why those slices don't pay attention to time zone when they display?

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2354]
superset==0.15.4

Why those slices don't pay attention to time zone when they display?

![image](https://cloud.githubusercontent.com/assets/8108788/23640760/9eb3bb7c-032a-11e7-8e1c-9a4616b96227.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 411 days. Feel free to comment and request for this issue to be reopened.
