### ISSUE TITLE
Date Filter doesn't work in the dashboard

### ISSUE THREAD

**Issue by GeorgeGuoCN** [apache/incubator-superset#2356]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y ] I have reproduced the issue with at least the latest released version of superset
- [ Y ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.0

### Steps to reproduce
on the dashboard i click the Date Filter to select some days ago or special day, it doesn't work. I check the log find the superset sents the some SQL to the database,the data range not changed.

**Comment by alian921** [comment]
I have that same problem too :(

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 405 days. Feel free to comment and request for this issue to be reopened.
