### ISSUE TITLE
table Metric automatic create the "avg_" and can't delete

### ISSUE THREAD

**Issue by GeorgeGuoCN** [apache/incubator-superset#2357]
- [ N] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [N ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.0

### Steps to reproduce
Superset automatic  create the avg_**, I don't need this Metric, I can't delete this Metric.

![image](https://cloud.githubusercontent.com/assets/19921144/23643300/dd7d4e3e-033b-11e7-9c81-5baa0ae968ea.png)

**Comment by QiXuanWang** [comment]
I saw same avg_* sum_* by default but I thought it was intended.
How can I list the metric view as you did? I can't find it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 410 days. Feel free to comment and request for this issue to be reopened.
