### ISSUE TITLE
TableModelView list render failed after pulling data from the old version db

### ISSUE THREAD

**Issue by HugoPu** [apache/incubator-superset#2359]
### Superset version
0.15.2  and   0.13.2

### Actual results
TableModelView list render failed

### Steps to reproduce
**Acutally, I am not sure if this is a bug, since I am not quite understand what caused this error.** 

1. I build Superset 0.15.2 and pull data from 0.13.2 database with the sql like `select XXX insert into XXX`, all modelviews work well, except the TableModelView list view. The error message is `TypeError: coercing to Unicode: need string or buffer, NoneType found` . If I used the demo data which is generated by 0.15.2, this error won't occur, and the data of 0.13.2 can run normally in the code of 0.13.2   
2. After debugging and searching from google, I found this [https://github.com/flask-admin/flask-admin/issues/785](url), and found that when the template generate select option(the columns property of the SqlTable) of the search widget, the error will occurs. 
3. After I override `__str__` method in TableColumn class of model.py
`def __str__(self):  `
`    return ''  `
The error won't occur anymore, so what makes this error occur, do you have any idea?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 411 days. Feel free to comment and request for this issue to be reopened.
