### ISSUE TITLE
SQL Server PyODBC URL escaped connection string not saved properly

### ISSUE THREAD

**Issue by duffn** [apache/incubator-superset#236]
Per the SQLAlchemy documentation here http://docs.sqlalchemy.org/en/rel_1_0/dialects/mssql.html#pass-through-exact-pyodbc-string, you can pass an exact PyODBC connection string, though it must be URL escaped. This works when you create a datasource and click `TEST CONNECTION`, but does not save the URL escaped connection string so does not subsequently work.
1. Enter a properly escaped connection string at `http://localhost:8088/databaseview/add`.  

```
import urllib

quoted = urllib.quote_plus(
    'DRIVER={FreeTDS};SERVER=myserver;PORT=1433;'
    'DATABASE=mydatabase;UID=myuser;PWD=mypassword;TDS_Version=8.0')
print 'mssql+pyodbc:///?odbc_connect={quoted}'.format(quoted=quoted)
# The escaped connection string to use
# mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BFreeTDS%7D%3BSERVER%3Dmyserver%3BPORT%3D1433%3BDATABASE%3Dmydatabase%3BUID%3Dmyuser%3BPWD%3Dmypassword%3BTDS_Version%3D8.0
```
1. Click `TEST CONNECTION` and the connection is successful.
2. Save the connection.
3. Now, edit the connection. The connection string is not escaped, therefore does not work

```
# Connection string after saving and reopening.
mssql+pyodbc:///?odbc_connect=DRIVER={FreeTDS};SERVER=myserver;PORT=1433;DATABASE=mydatabase;UID=myuser;PWD=mypassword;TDS_Version=8.0
```

SQL Server Enterprise 2012
caravel==0.8.4
pyodbc==3.0.10

**Comment by mistercrunch** [comment]
here's the relevant, related code:
https://github.com/airbnb/caravel/blob/master/caravel/views.py#L134

Unfortunately I probably won't have time to get to this quickly, I'm happy reviewing PRs though.

**Comment by marlesson** [comment]
I have the same problem. What was your solution @duffn ?

**Comment by duffn** [comment]
@marlesson I did not come up with a solution, I'm afraid.
