### ISSUE TITLE
Deleting a datasource should delete the related Slices

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2366]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by ascott** [comment]
i think it will be important to notify/confirm with a user that when a datasource is deleted, all related slices will be deleted as well. alternatively, could a slice be in a 'needs datasource` state, where it could still be accessed, or shown on a dashboard, but the chart wouldn't load and instead a message to the user would be displayed notifying them to update the datasource.

**Comment by mistercrunch** [comment]
It could be easy to just generally disregard or skip slices that don't have a datasource. I wish FAB had a cascading delete that list all related objects with confirm prompt like the Django Admin does...
