### ISSUE TITLE
Some questions about the index page

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2371]
superset==0.17.0

May i can ask some questions about the homepage that i would like to go directly to `a default dashboard` instead of showing `a list of dashboards` when i landed an account, is it more reasonable?

![image](https://cloud.githubusercontent.com/assets/8108788/23692769/96b25974-040b-11e7-8531-5a156c9688f7.png)

**Comment by data-strategy** [comment]
Same question about it, or it's better can redesign the landing index page.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 403 days. Feel free to comment and request for this issue to be reopened.
