### ISSUE TITLE
impala can't render element of type <class 'impala.sqlalchemy.INT'>

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#2382]
when i add table from impala ,then columns data type  string 、int can't render

:ERROR:root:Unrecognized data type in qding_report.daily_project_report.dt
2017-03-10 10:27:30,436:ERROR:root:Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f83ffcf3390> can't render element of type <class 'impala.sqlalchemy.STRING'>

### Superset version
0.17

**Comment by mistercrunch** [comment]
A full stack trace would help if it's availlable

**Comment by xrmx** [comment]
Looks related to this: https://github.com/cloudera/impyla/issues/71#issuecomment-97140747

**Comment by xrmx** [comment]
@qinzl1 Do you have latest impyla released?

**Comment by qinzl1** [comment]
@xrmx impyla version is latest

**Comment by qinzl1** [comment]
@mistercrunch 
2017-03-14 10:54:17,200:ERROR:root:Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f83ff9bc350> can't render element of type <class 'impala.sqlalchemy.STRING'>
Traceback (most recent call last):
  File "/data/superset_venv/lib/python2.7/site-packages/superset/models.py", line 1509, in fetch_metadata
    datatype = "{}".format(col.type).upper()
  File "/data/superset_venv/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 561, in __str__
    return unicode(self.compile()).\
  File "/data/superset_venv/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 548, in compile
    return dialect.type_compiler.process(self)
  File "/data/superset_venv/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/data/superset_venv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 79, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f83ff9bc350> can't render element of type <class 'impala.sqlalchemy.STRING'>

**Comment by mistercrunch** [comment]
@qinzl1 looks like an issue with the driver/dialect...

**Comment by qinzl1** [comment]
@mistercrunch 
i configure { "metadata_params": {"bind":"engine"}, "engine_params": {  }
impala can not add table ,

**Comment by elisabetao** [comment]
I am having the same  sqlalchemy compiler error triggered  for some impala types:  
impala.sqlalchemy.STRING , impala.sqlalchemy.INT,etc. I tried setting bind engine in the metadata_params, but that did not help.
@qinzl1 - were you able to get this working? Thanks

**Comment by datinho** [comment]
Into superset/connectors/sqla/models.py there is the def 'fetch_metadata' (line 577) the datatype throw Exception here
`        for col in table.columns:
             try:
                 datatype = "{}".format(col.type).upper()
             except Exception as e:
                 datatype = "UNKNOWN"
                 logging.error(
                     "Unrecognized data type in {}.{}".format(table, col.name))
                 logging.exception(e)
`
Maybe the format didn't consider impala/impyla dialect.

**Comment by mistercrunch** [comment]
Wait which lines throws? seems like the error should be handled/silenced in the code above

**Comment by datinho** [comment]
When a table is added and has type like INT or STRING the  datatype returned is 'UNKNOWN'
`datatype = "{}".format(col.type).upper()`
It seems the format don't use the 'impyla' dialect when the SQLAlchemy URI prefix is 'impala://'

**Comment by xrmx** [comment]
@datinho if the sqlalchemy backend names itself `impala` the correct engine spec would be used.

**Comment by datinho** [comment]
On thread https://github.com/zzzeek/sqlalchemy/pull/381 I've simulated the code to retrieve the 'datatype'.
I'll produce a pull request.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 216 days. Feel free to comment and request for this issue to be reopened.
