### ISSUE TITLE
SliceModelView has no show_columns[]

### ISSUE THREAD

**Issue by zhangjiajie023** [apache/incubator-superset#2383]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
slice should show ordered info.

### Actual results
slice shows disordered info. SliceModelView has no show_columns[].

### Steps to reproduce
Click `Slices`
click `Show record`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 409 days. Feel free to comment and request for this issue to be reopened.
