### ISSUE TITLE
Authentification with AUTH_DB

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#2384]
I order to get the basic flask user authentification working I had to add the following lines to superset/config,py :

MAIL_SERVER = SMTP_HOST
MAIL_PORT= SMTP_PORT
MAIL_USE_TLS = True
MAIL_USERNAME = SMTP_USER #'yourappemail@gmail.com'
MAIL_PASSWORD = SMTP_PASSWORD #'passwordformail'
MAIL_DEFAULT_SENDER = SMTP_MAIL_FROM #'fabtest10@gmail.com'

**Comment by xrmx** [comment]
Which version is this?

**Comment by lilila** [comment]
0.17

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 408 days. Feel free to comment and request for this issue to be reopened.
