### ISSUE TITLE
Permission description and meanings

### ISSUE THREAD

**Issue by shushengxing** [apache/incubator-superset#2389]
I want to know the meaning of  these permissions :

can queries on Superset
can cached key on Superset
can results on Superset
can slice on Superset
can sync druid source on Superset
can override role permissions on Superset
can all tables on Superset
can tables on Superset
can fetch datasource metadata on Superset
can checkbox on Superset
can warm up cache on Superset
can select star on Superset
can update role on Superset
can request access on Superset
can activity per day on Superset

And some permissions about Async ：

can edit on CssTemplateAsyncModelView
can delete on CssTemplateAsyncModelView

can edit on DatabaseAsync
can delete on DatabaseAsync

can edit on DatabaseTablesAsync
can delete on DatabaseTablesAsync

can edit on SliceAsync
can delete on SliceAsync

can edit on SliceAddView
can delete on SliceAddView

Do you have some documents about permission clarification?  
Thanks for your answer!

### Superset version
0.15.0

**Comment by data-strategy** [comment]
Same confusion, there are too many roles, how to make it easy understanding and modification?

**Comment by sophiedophie** [comment]
Same here, is there any documents about those fields?

**Comment by mistercrunch** [comment]
These permissions are auto-generated by Flask App Builder and correspond to either "views" or "model views". I agree we should take the time to document these.

**Comment by hirachna** [comment]
Can anyone help on this, i need to know the meaning of each permission.

**Comment by hirachna** [comment]
> I want to know the meaning of these permissions :
> 
> can queries on Superset can cached key on Superset can results on Superset can slice on Superset can sync druid source on Superset can override role permissions on Superset can all tables on Superset can tables on Superset can fetch datasource metadata on Superset can checkbox on Superset can warm up cache on Superset can select star on Superset can update role on Superset can request access on Superset can activity per day on Superset
> 
> And some permissions about Async ：
> 
> can edit on CssTemplateAsyncModelView can delete on CssTemplateAsyncModelView
> 
> can edit on DatabaseAsync can delete on DatabaseAsync
> 
> can edit on DatabaseTablesAsync can delete on DatabaseTablesAsync
> 
> can edit on SliceAsync can delete on SliceAsync
> 
> can edit on SliceAddView can delete on SliceAddView
> 
> Do you have some documents about permission clarification? Thanks for your answer!
> 
> ### Superset version
> 0.15.0

Any luck on this?
