### ISSUE TITLE
Metric should offer a new "Legend Name" attribute

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2394]
While verbose name is long and useful, sometimes there's a need to set a short name to be used in the legend and as a way to define the color scheme.

**Comment by raelmiu** [comment]
+1

**Comment by v-ek** [comment]
+1

Is this part of the current development efforts/roadmap?

**Comment by gangh** [comment]
+1 
Are there any way to change the legend in the graph?

**Comment by markanthonyGH** [comment]
+1

**Comment by JImBurris** [comment]
+1

**Comment by Ooooooog** [comment]
+1
I'm really looking forward to this option

**Comment by Lynnlan** [comment]
+1
