### ISSUE TITLE
dist_bar not working for groupby integer value

### ISSUE THREAD

**Issue by vera-liu** [apache/incubator-superset#2404]
For distribution bar chart, if series is an integer column, y axis seems to be shrunken:
![screen shot 2017-03-14 at 10 21 37 am](https://cloud.githubusercontent.com/assets/20978302/23913439/45368fcc-08a0-11e7-8283-f42f6e5a88eb.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 404 days. Feel free to comment and request for this issue to be reopened.
