### ISSUE TITLE
Create migrate script failed

### ISSUE THREAD

**Issue by zhangjiajie023** [apache/incubator-superset#2422]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
the upgrade function in `migrations/versions/xx.py` should create the tables in models.py

### Actual results
the upgrade function in `migrations/versions/xx.py' is going to drop tables` ab_xxx` in mysql

### Steps to reproduce
There are too many files in `migrations/versions/`, so i want to re-generate the migrate py.
1. `rm -r migrations/`
2. `superset db init`   
this step generates folder` migrations/` and others, and serveal tables `ab_xxx` in mysql
3. `superset db migrate -m "initial migration"`
this step generates a py in `migrations/versions/`, but its upgrade function is drop these tables `ab_`, not creating tables in `models.py`

what's wrong with my operations?

**Comment by zhangjiajie023** [comment]
And i wonder to know `superset db upgrade` execute which function, or where these tables are created ?

**Comment by xrmx** [comment]
Hopefully superset behaves like every other application that uses flask-migrate, you may want to check its documentation.

**Comment by zhangjiajie023** [comment]
@xrmx Now I want to downgrade the init state, run `superset db downgrade 4e6a06bad7a8`
this step
`Running downgrade 1226819ee0e3 -> 956a063c52b3, Fix wrong constraint on table columns`
has error:
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1091, "Can't DROP 'columns_ibfk_3'; check that column/key exists") [SQL: 'ALTER TABLE `columns` DROP FOREIGN KEY columns_ibfk_3']`

After i `add column columns_ibfk_3` to` columns`, next `downgrade` step still error for:
`(_mysql_exceptions.OperationalError) (1091, "Can't DROP 'fk_columns_datasource_name_datasources'; check that column/key exists") [SQL: 'ALTER TABLE `columns` DROP FOREIGN KEY fk_columns_datasource_name_datasources']`

upgrade works, but downgrade failed, make me puzzled

**Comment by mistercrunch** [comment]
I think FK management in Alembic has shortcomings on some DB engine.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 401 days. Feel free to comment and request for this issue to be reopened.

**Comment by gbrian** [comment]
Hi,
Having the issue:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error
[SQL: ALTER TABLE annotation ALTER COLUMN layer_id SET NOT NULL]
```
It happens without any change. 
`layer_id` column at `annotation` table is defined:

`layer_id = Column(Integer, ForeignKey('annotation_layer.id'), nullable=False)
`

Question: Is it  save to commit the generated script? If not what's the preferred DB engine for development? Currently using **sqlite3**
