### ISSUE TITLE
[sqllab] CTAS feature should be clear about the destination of the table

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2439]
When CREATE TABLE AS is allowed on a database, and that `CTAS Schema` is defined, the tables get created in that namespace. The UI should be clear about that, perhaps with a tooltip close to the CTAS input box

**Comment by linwoodc3** [comment]
Where exactly is this namespace?  I ran a query and wanted to create my own table; can't find where the table is saved.

**Comment by kevinwancw** [comment]
+1
