### ISSUE TITLE
[vis] How to select the stack order for time series data?

### ISSUE THREAD

**Issue by magnusso** [apache/incubator-superset#2442]
Any experience of using the Sort By” when stacking time series data?

Expected result: the order should change as a consequence of changing the value of "Sort By" in the web_health_population slice, i.e. the series as the bottom should change, as well as the series at the top, and the order of the series between these.

Actual results: The "Sort by" seems to have no effect I have tried with different data sets. The category with the largest count is and remains at the bottom, the second largest on top of that and so on. This leads me to suspect that the feature has not been implemented yet. If it has been implemented, please explain how to configure the data so that the "Sort by" has the desired effect.

Superset version: 0.17.0

![capture2](https://cloud.githubusercontent.com/assets/26468823/24147564/7c0931f0-0e43-11e7-99bb-96bdb08c08a0.JPG)

**Comment by daydreamer00** [comment]
Meet the same issue. "Sort by" doesn't work as expected on version 0.15.0 either. Any solution or is any other way to reorder the series?

**Comment by htruongaff** [comment]
Same issue as well.  Options listed, but only sorts by main metric.

**Comment by mistercrunch** [comment]
The sorting applies to the "Series Limit", not to the sorting of the legend or the stack itself. An example of that is if you wanted to plot the `% of rural population` for the top 10 most populated countries.

**Comment by apmfifty** [comment]
Hi mistercrunch,is there any plan to support the function to sort by legend?

**Comment by mistercrunch** [comment]
We're accepting PRs, I don't see that making the top my priority list anytime soon

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 194 days. Feel free to comment and request for this issue to be reopened.

**Comment by makshth** [comment]
I am still struggling with this issue. Stacking order is absolutetly vital for us since the order needs to be "logical", from a content point of view. Is there work around to force a stacking order?
@mistercrunch  Are there any plans to introduce this feature in the near future?

**Comment by mistercrunch** [comment]
No plans for this specifically no.

**Comment by bkarlson** [comment]
Stumbled upon this as well, and looks like the stacking is sorted by metric name in ABC order. I.e. renaming a metric will shift it's position in the stack. Worked for Bar chart, may work for other charts as well. Not optimal, but doable.

**Comment by JTLai** [comment]
+1

**Comment by konfiot** [comment]
Same issue, could it be reopened ?

**Comment by jurgisp** [comment]
+1

**Comment by kong75** [comment]
+1

**Comment by Vigano-marco** [comment]
same problem with "Area Chart " , even renaming the dimension so that the alphabetical order reflects the logical one , the legend and order of the chart remains decided only by the applied measure . 
Also for me it is vital that you can order the legend and the chart ! will this problem be fixed ? honestly it looks really bad as a bug to me .

**Comment by Vigano-marco** [comment]
same problem with "Area Chart " , even renaming the dimension so that the alphabetical order reflects the logical one , the legend and order of the chart remains decided only by the applied measure . 
Also for me it is vital that you can order the legend and the chart ! will this problem be fixed ? honestly it looks really bad as a bug to me .
