### ISSUE TITLE
can superset really support sparksql?

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#2450]
the document says that it can support  sparksql by using the jdbc+hive:// url prefix, i tried it could submit the task into the hadoop using pyhive, as i know spark has its own sql parser and interpreter and optimizition and so on , and only use the metadata from hive, i don't know how to submit the task into the spark cluster,is there any url prefix e.g spark:// supporting ?

### Superset version
the lastest version

**Comment by hungrytortoise** [comment]
your problem is been sloved? @anddyhuaa

**Comment by hungrytortoise** [comment]
i'm useing hive://xxx to connect to sparksql ,but it does not work.

**Comment by rajekra** [comment]
Can you please help me to connect SparkSQL from superset?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 211 days. Feel free to comment and request for this issue to be reopened.
