### ISSUE TITLE
[Babel] How to translate the string called by markdown

### ISSUE THREAD

**Issue by zhangjiajie023** [apache/incubator-superset#2451]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

#### example in views.py
```
'sqlalchemy_uri': utils.markdown(
            "Refer to the "
            "[SqlAlchemy docs]"
            "(http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#"
            "database-urls) "
            "for more information on how to structure your URI.", True),
```
#### I changed to 
```
'sqlalchemy_uri': utils.markdown(_(
            "Refer to the "
            "[SqlAlchemy docs]"
            "(http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#"
            "database-urls) "
            "for more information on how to structure your URI."), True),
```
#### and in message.po add:
```
msgid ""
"Refer to the [SqlAlchemy docs] "
"(http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls) "
"for more information on how to structure your URI."
msgstr ""
"Some words [SqlAlchemy docs] "
"(http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls) "
"Some words"
```
#### But don't work after `pybabel compile`. so how to translate the markdown-string ?

**Comment by xrmx** [comment]
Have you reinstalled / restarted server after compiling?

**Comment by zhangjiajie023** [comment]
@xrmx yes, restarted, and the displayed string is to be
 ```
Refer to the [SqlAlchemy docs] (http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls) 
for more information on how to structure your URI.
```
where `markdown` don't work too

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 396 days. Feel free to comment and request for this issue to be reopened.
