### ISSUE TITLE
 There is a small request to improve the functionality

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#2453]
Greetings

I really miss the function. It will be very convenient to visualize the result of sql query not only in the form of tables and digrams, but also using html + jinja2 template. For example, in order to do this:

In the sql query editor, create the query:
Select * from users

Then we send the query result to the visualization template.
```

<Ul>
{% For user in users%}
   <Li> <b> {{user}} </ b> </ li>
{% Endfor%}
</ Ul>
```

Something like Django's work templates.

And also add a 'print' button to the dashboard.

Thank you.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 397 days. Feel free to comment and request for this issue to be reopened.
