### ISSUE TITLE
"Use list instead of numpy array #2412 " on sqllab.py patch cause error on pyodbc driver 

### ISSUE THREAD

**Issue by openmax** [apache/incubator-superset#2461]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1 with pyodbc driver 

### Expected results
Return of record of db from select 

### Actual results

> **2017-03-23 15:14:41,842:ERROR:root:Shape of passed values is (1, 5), indices imply (3, 5)**
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/superset/views/core.py", line 2043, in sql_json
>     data = sql_lab.get_sql_results(query_id, return_results=True)
>   File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
>     return self._get_current_object()(*a, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
>     return self.run(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/superset/sql_lab.py", line 146, in get_sql_results
>     data, columns=column_names))
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 279, in __init__
>     copy=copy)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 432, in _init_ndarray
>     return create_block_manager_from_blocks([values], [columns, index])
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3993, in create_block_manager_from_blocks
>     construction_error(tot_items, blocks[0].shape[1:], axes, e)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3970, in construction_error
>     passed, implied))
> ValueError: Shape of passed values is (1, 5), indices imply (3, 5)
> 

### Steps to reproduce

using pyodbc on unixodbc driver on ubuntu 16.04.2 
without 0674ed8 all OK .

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 396 days. Feel free to comment and request for this issue to be reopened.
