### ISSUE TITLE
[list table columns] make checkboxes disabled

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2465]
make checkboxes disabled, since you cannot save changes from this page.

![image](https://cloud.githubusercontent.com/assets/130878/24275897/2ef55bba-0ff0-11e7-89b1-680910aa68f4.png)

**Comment by ascott** [comment]
it has been reported that it used to work to save column checkboxes on this screen, but now does not work

**Comment by xrmx** [comment]
Possibly broken because of #2437 ?

**Comment by mistercrunch** [comment]
should be fixed on master

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 393 days. Feel free to comment and request for this issue to be reopened.
