### ISSUE TITLE
[feature] HDFS interface

### ISSUE THREAD

**Issue by steremma** [apache/incubator-superset#2468]
I have started to work on providing a new datasource, targeting semi structured data residing on a distributed file system (HDFS/S3) such as:

- csv
- json
- xml

I have started to work on that by designing a spark API imitating the functionality offered by the already existing datasources.

I would be interested to know if people would appreciate the addition of such a feature.
I also have some ideas regarding the implementation, specifically I am now adding functionality in a new
module under connectors/

Any input is valuable at this point!

**Comment by mistercrunch** [comment]
You'll need an engine that can deserialize, aggregate & filter data as you implement the interface

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 392 days. Feel free to comment and request for this issue to be reopened.
