### ISSUE TITLE
Cumulative Sum Wrong Visualization in 0.17.1

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [apache/incubator-superset#2481]
Make sure these boxes are checked before submitting your issue - thank you!

[Yes] I have checked the superset logs for python stacktraces and included it here as text if any
[Yes] I have reproduced the issue with at least the latest released version of superset
[Yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1

### Expected results
The line graph will be cumulative like in previous version (0.15.4)

### Actual results
The graph is not cumulative. (The dashed line)
![superset](https://cloud.githubusercontent.com/assets/12984659/24347379/4fa14e18-1302-11e7-8ca7-bd613e8b716c.png)

### Steps to reproduce
1. Select any source of data
2. Select line chart
3. Go to Advanced Analytics Option
4. Set the time shift to more than 0. For example 3 days ago etc.
5. Set the rolling value to cumsum

**Comment by mxmzdlv** [comment]
I can confirm it is not working, version 0.19.0
