### ISSUE TITLE
database access control on SQLLAB

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#2510]
i do a  database access on database A  based on role control, and allow to expose on SQLLAB, but can't choose the database A .
i have to do a query aganist one of tables on A, and its tables shows ok, 
but 'select a database' menu still can't select the database
### Superset version
3.11
![Uploading db_access1.png…]()

**Comment by xrmx** [comment]
Pretty sure it's not superset 3.11 :)

**Comment by anddyhuaa** [comment]
so sorry about that i did provide the wrong version number
{"GIT_SHA": "", "version": "0.15.4"}

**Comment by MonkeyOnTree** [comment]
I met the same problem as you. Have you got over it?
