### ISSUE TITLE
Are there any ways to set the color for the chart specifically

### ISSUE THREAD

**Issue by ijyun** [apache/incubator-superset#2524]
Hi team,
Right now,When I refresh the dashboard the color of the chart would change automatically.I want to set the color for the chart and dont' change after refresh.
Could you please tell me are there any ways?
Thanks

**Comment by alanmcruickshank** [comment]
@ijyun - not at the moment. Could be an interesting feature to implement. I know several people have enquired about it.

**Comment by mistercrunch** [comment]
It's somewhat challenging. Currently we guarantee that metrics of the same name in a dashboard will be the same color across charts.

There's this function/object that cycles through the palette and provide a new color for new expressions and memoizes as it goes. If you ask for `Metric 1` twice it'll give you the same color.

Early on I would hash "Metric 1" and provide a color based on the hash so that "Metric 1" would ALWAYS be the same color. The problem there was that with say 8 colors, you relatively often get in situation where a chart with say 2 or 3 metrics will get the same color twice, and that's no good. A chart with "Metric 1" and "Metric 2" might have the same color for both 1 out of 8 times...

Someone in the community said they pre-populate that memoized object with an array of all their important metrics. 

For reference:
https://github.com/airbnb/superset/blob/master/superset/assets/javascripts/modules/colors.js#L51

Somehow f you call `category21` for an array of metrics, before you render the dashboard, colors for these metrics will be deterministic.

**Comment by olegIn80** [comment]
Hi mistercrunch
we are interesting in this feature, can you give an advise to understand better the mechanism how is working now and how we can implement this feature . 

Thanks

**Comment by mistercrunch** [comment]
It'd be nice to support different color schemes, and allow people to pick a default in their environment. It would also be nice to make "Colors" one of the core set of controls, cohesive across visualizations, but that's a bit more complicated.

For now the categorical colors are defined here:
https://github.com/apache/incubator-superset/blob/master/superset/assets/javascripts/modules/colors.js#L6

A first step might be to define an object with different color sets, and add a new control to most visualizations that would allow to pick the color set. And add a new `DEFAULT_COLOR_SET` variable in `superset/config.py`.

**Comment by renanoliveira** [comment]
Hello guys! 
Do you have any update about that? 

In my company different products use different colors but same superset, in my particular case I can not use unique color pallet.

**Comment by mistercrunch** [comment]
It's somewhat easy to add new palettes and set one as default but you'll have to do this in your fork.
https://github.com/apache/incubator-superset/blob/master/superset/assets/javascripts/modules/colors.js#L130

It could be nice to add an environment variable to define your default color scheme without having to alter the code and bake your own build.

**Comment by shinabarger** [comment]
Agreed, this would be a great feature to have. To be able to change colors for any chart customized for each breakdown of the Group By feature.

For example, have a pie chart with 2 different categories and custom pick which colors those categories show up in the pie chart. See below image as an example. 
![2018-06-07_9-41-35](https://user-images.githubusercontent.com/20525068/41103379-0196869c-6a37-11e8-805e-782d92467fb8.png)

**Comment by mistercrunch** [comment]
There's now a way to do this that should work in most cases:
http://superset.apache.org/faq.html#is-there-a-way-to-force-the-use-specific-colors

**Comment by mistercrunch** [comment]
There's now a way to do this that should work in most cases:
http://superset.apache.org/faq.html#is-there-a-way-to-force-the-use-specific-colors

**Comment by frischknechtna** [comment]
@mistercrunch  I tried to enforce a colors in the link described way wasn't really successful. Have you experience in defining colors in superset and maybe a more precise experience?

**Comment by dominijk** [comment]
@mistercrunch I've also tried that method as SO [question](https://stackoverflow.com/questions/54326962/where-are-label-colour-keys-stored-in-apache-superset) without success.

**Comment by mistercrunch** [comment]
<img width="1170" alt="screen shot 2019-01-31 at 9 50 16 pm" src="https://user-images.githubusercontent.com/487433/52105118-48557300-25a2-11e9-8600-c1785856c9a5.png">
<img width="908" alt="screen shot 2019-01-31 at 9 49 33 pm" src="https://user-images.githubusercontent.com/487433/52105119-48557300-25a2-11e9-8dd0-f94330ae9d57.png">


```json
{"filter_immune_slices": [], "timed_refresh_immune_slices": [], "filter_immune_slice_fields": {}, "expanded_slices": {}, "default_filters": "{}",
"label_colors": {
        "Girls": "#FF69B4",
        "Boys": "#ADD8E6"
    }
}
```

**Comment by dominijk** [comment]
I got that to work but for me the chart must also be set to the default colour scheme

**Comment by mistercrunch** [comment]
Wait do you want to set colors a specific way or do you want the default color scheme?

**Comment by dominijk** [comment]
Specific colours for keys but these persist across an entire instance of superset. Per dashboard is fine but I will test as a scheme if that can be key specific?

**Comment by mistercrunch** [comment]
I'd be nice to add a global environment setting for this, I'm not sure why this only applies to the default color scheme, but that's not the intended behavior.

**Comment by mlberg** [comment]
I can confirm you have to have this set to the default color scheme to work.

**Comment by rangerscience** [comment]
@mistercrunch How do I get to the "JSON Metadata" view from your top screenshot?

**Comment by danmdoherty** [comment]
@rangerscience viewing the dashboard, click "Edit Dashboard", then click the ▼ menu and select "edit dashboard metadata".

![Screen Shot 2019-04-01 at 10 56 17 AM](https://user-images.githubusercontent.com/4466572/55348769-caf89280-546c-11e9-8117-25a5ebe2429e.png)

**Comment by mohan770** [comment]
HI @mistercrunch  I have tried ur method but it is showing an error has occurred I have given exactly without any error can u give some  more info regarding this

**Comment by garyganyang** [comment]
How to change x,y axis label color? anyone know about this? many many thanks

**Comment by EBoisseauSierra** [comment]
> There's now a way to do this that should work in most cases:
> http://superset.apache.org/faq.html#is-there-a-way-to-force-the-use-specific-colors

Updated link: https://superset.apache.org/docs/frequently-asked-questions#is-there-a-way-to-force-the-use-specific-colors

**Comment by hosswald** [comment]
This is still broken in 1.2.0.
I found, strangely, that
``` 
  "label_colors": {
    "SUCCESS": "#2ca02c",
    "WARNING": "#ff7f0e",
    "ERROR": "#d62728"
  },
  "color_scheme": "SUPERSET_DEFAULT"
```
works, while

``` 
  "color_scheme": "SUPERSET_DEFAULT",
  "label_colors": {
    "SUCCESS": "#2ca02c",
    "WARNING": "#ff7f0e",
    "ERROR": "#d62728"
  }
```
does not, e.g. JSON metadata order matters (which does not make any sense).
