### ISSUE TITLE
cal_heatmap not working as expected

### ISSUE THREAD

**Issue by mearroyo** [apache/incubator-superset#2542]
### Superset version
0.17.0

### Expected results
Calendar to display the metric (Count, in this case) on the date associated with the metric.

### Actual results
Calendar displays the metric on the day before the date associated with the metric.

### Steps to reproduce
Default example of the calendar on the default Misc Charts dashboard. Reproduced on my own data.

![image](https://cloud.githubusercontent.com/assets/15230944/24617018/c5b4d1ca-1860-11e7-86b3-0ebff4396d39.png)
![image](https://cloud.githubusercontent.com/assets/15230944/24617023/c8c70ec8-1860-11e7-9d85-e71c30b8407e.png)
![image](https://cloud.githubusercontent.com/assets/15230944/24617026/cb196540-1860-11e7-8411-00e01f9c2cdf.png)

**Comment by vikasgupta1812** [comment]
I am facing the same issue. 


![image](https://cloud.githubusercontent.com/assets/4309626/26272920/366a928c-3cf2-11e7-916c-c6a67e7fbf21.png)

**Comment by vikasgupta1812** [comment]
I kind of figured out why this might be happening. I was using SQLite as database, which treats timestamps in GMT \ UTC timezone. But JS considers local timezone, which is EST in my case. So it ends up reducing 1 day from the date in the database.

**Comment by mistercrunch** [comment]
https://github.com/wa0x6e/cal-heatmap/issues/126

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 335 days. Feel free to comment and request for this issue to be reopened.
