### ISSUE TITLE
Feature/Bug: Add support for async backend in Explore

### ISSUE THREAD

**Issue by songyanho** [apache/incubator-superset#2551]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset v0.17

### Expected results
Superset exploreV2 uses Celery for async query, same mechanism used by Sql Lab

### Actual results
Superset exploreV2 still rely on synchronous query request until timeout

### Steps to reproduce
Use long running query type (typically with Hive as datasource)

After checking the network request, I notice that exploreV2 does not send query status request every second like what Sql Lab is doing. Hoping that same feature of Sql Lab can be transfered to exploreV2 too

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 382 days. Feel free to comment and request for this issue to be reopened.
