### ISSUE TITLE
Pivot table issues

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#2553]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.4rc1

### Expected results
- Get pivot table functionalities as great as table view
    - fix the following issues 
    - ideally :  add pagination options, row limit and allow filtering (as it is done for table view)

### Actual results

- When there is more than on "group by" column  we loose the sliders along x et y axis. 
![pivot sliders](https://cloud.githubusercontent.com/assets/607430/24693564/76d06356-19de-11e7-9c6e-739c7c467c78.gif)

- There is also an issue when choosing metrics with different types in pivot table. It is possible to have several "numeric" metrics or several "string" metrics but when you mix them there is only one type appearing. Here is an example with a mix of  string and numeric metric 

![mix_metric](https://cloud.githubusercontent.com/assets/607430/24693674/fdfbd784-19de-11e7-82a0-26f27c2a0caf.gif)

**Comment by lilila** [comment]
Am i the only person experiencing this issue ? 
Any help would be very welcome

**Comment by xrmx** [comment]
@mistercrunch looks you can close this

**Comment by ohoroyoi** [comment]
@lilila   is there way to change pivot table width and height depending on text length? I think your's table width is appropriate. may I ask What did you edit?
