### ISSUE TITLE
Login failure!

### ISSUE THREAD

**Issue by FareehaNaaz** [apache/incubator-superset#2576]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1

### Expected results
Hi! i am new for Superset and the version i use is 0.17.1, it was working fine after installation, i have created a few users, dashboards and then all of sudden i cant login with my credentials which i created while installation and also with the user credentails created within superset. i have checked the logs which returned nothing.

### Actual results
Invalid login. Please try again

### Steps to reproduce
N/A

**Comment by xrmx** [comment]
You possibly are not using the database you added your users too. Please double check that.

**Comment by FareehaNaaz** [comment]
this issue is that i cant even login through the credentials i gave while installation, it worked earlier and all of a sudden stopped working.

**Comment by xrmx** [comment]
The database by the default is in the user's home. Are you using a custom settings file? One easy mistake is to use it during the installation from the cli and not when running the runserver as a service. Or using a different user than the one you installed or so.

**Comment by innovia** [comment]
I was running superset via a process manager that is starting as root but changing the user into superset user - all I had to do is to create a symlink for that

`lrwxrwxrwx  1 superset superset    24 Jul 30 12:54 .superset -> /home/superset/.superset`

**Comment by mistercrunch** [comment]
Highly recommend using MySQL or Postgres in production or for any decent test drive.
