### ISSUE TITLE
Bar chart sortinig x label DESC and ASC

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#2578]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

Greetings to all. Is it possible to add the correct sorting to the chart?
Thank you so much.

### Superset version
{"GIT_SHA": "", "version": "0.17.4"}

### Expected results

Sorting info in x label: 1,2,3,4,5,6,7,8,910
### Actual results

Sorting info in x label: 1,10,11,....
![default](https://cloud.githubusercontent.com/assets/11568424/24862581/cd34c202-1e05-11e7-9dd6-2034d44233bb.png)

In my data, "numzan" is a number, not a string

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 377 days. Feel free to comment and request for this issue to be reopened.
