### ISSUE TITLE
Date Filter is possible to add datepicker calendar?

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#2579]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

I greet everyone. Please add a drop-down calendar to the date filter, like
![default](https://cloud.githubusercontent.com/assets/11568424/24863090/12996288-1e08-11e7-9b15-2b3c56a6786d.png)

Thank you.

**Comment by mistercrunch** [comment]
It's a bit more complicated than that as our current date dropdown allows for bot fixed dates and relative dates. Expressions like `52 weeks ago` or `4 hours ago` or `2015` currently work. We'd need a slightly more complex control with a radio button (relative or fixed) that shows a datepicker or some form for [input int] [frequency] [ago/from_now] depending...

**Comment by bbs2009** [comment]
Perhaps it will be convenient for users. Thank you

**Comment by higaxman** [comment]
We are interested in implementing this feature. @mistercrunch : could we make some proposal about which widget to use. Do you have any advice ?

**Comment by mistercrunch** [comment]
Awesome @higaxman , it's now possible to build rich controls too. Here are a few thoughts:

* the representation could be a simple text and a subtle edit icon
* if no specific time is select (`00:00:00`) I wouldn't show it, just show what is relevant.
* clicking the edit icon would pop a small bootstrap popover to the right of the text
* inside the popover a radio button for fixed/relative
* fixed would go along with the nicest react datepicker you can find, it has to allow date and time
* relative would be perhaps 3 boxes
    * an input box that validates numeric
    * a time unit dropdown (`seconds`, `minutes`, `hours`, `days`, `weeks`, `months`, `years`), default to `days`
    * dropdown for `ago` or `from now`, defaults to `ago`
* clicking the form controls in the popover flips the radio button accordingly to save a click. meaning if you click the time unit dropdown, it selects the `relative` option for the radiobutton, or if you click any part of the date picker, it chooses the `fixed` option
* [probably out of scope], an option for UTC / timezones when using fixed dates

For an example of a rich control, check out this branch (unmerged) where I'm working on a popover for the `metrics` control.
https://github.com/airbnb/superset/compare/metrics...mistercrunch:metrics?expand=1

**Comment by higaxman** [comment]
Thanks! Going to check it.

**Comment by DisposedCheese** [comment]
I am very interested in this feature. Please keep up the good work! I look forward to using a date-picker filter.

**Comment by mistercrunch** [comment]
After a quick research, I'd go with http://dev.quri.com/react-bootstrap-datetimepicker/

**Comment by xrmx** [comment]
@mistercrunch is it better than https://github.com/airbnb/react-dates ?

**Comment by mistercrunch** [comment]
@xrmx we need the component to handle time as well, not just date

**Comment by pariser** [comment]
Hey @higaxman how's your progress coming on this? I'd be happy to help

**Comment by mistercrunch** [comment]
Controls live here:
https://github.com/airbnb/superset/tree/master/superset/assets/javascripts/explore/components/controls

Create 2 instances for `since` and `until` here:
https://github.com/airbnb/superset/blob/master/superset/assets/javascripts/explore/stores/controls.jsx

Hard coded list here:
https://github.com/airbnb/superset/blob/master/superset/assets/javascripts/explore/components/Control.jsx#L21
you can move this list to an `index.jsx` if you think it's better

**Comment by vschoener** [comment]
Hi @mistercrunch, wanted to know if we can use it ? or still in progress ? :)

**Comment by mistercrunch** [comment]
No one is working on this at the moment as far as I know

**Comment by vschoener** [comment]
So sad :'(

**Comment by xrmx** [comment]
@vschoener don't be sad, that's an opportunity for you to implement it.

**Comment by Lunatictwo** [comment]
Will you add datepicker in next version? Any plans? AFAIK,datepicker is important for most developers and analysis.

**Comment by mistercrunch** [comment]
This as been done, will be in next release.
<img width="340" alt="screen shot 2017-09-15 at 8 23 07 am" src="https://user-images.githubusercontent.com/487433/30490570-2cf0d964-99ef-11e7-9749-fb1468307dd5.png">

**Comment by mistercrunch** [comment]
Yes it is

**Comment by CacheIbs** [comment]
Hey @mistercrunch will there be the ability to add the date picker as a filter to the dashboard itself such that it filters all visualizations simultaneously? I'd like to give end users the ability to readjust date ranges for the dashboard without having the ability/need to edit each chart individually. Thanks!

**Comment by Him121** [comment]
Thanks all for Apache superset contribution and s/w.

My question is. Are there any sample dashboard reports available with date filters? My team is especially looking for   having ability to switc/refresh the view based on reporting date change.

**Comment by Danielmrg** [comment]
I added a Persian Datepicker to my superset that filters all the data inside a dashboard
![01](https://user-images.githubusercontent.com/15319333/144709671-e6ecc2e1-30c3-475c-a18a-bfe7b42e49b5.png)
.

**Comment by Danielmrg** [comment]
I applied my changes in the following path:
     **superset/superset-frontend/src/visualizations/FilterBox**

**First I added my filter to the control panel with the following code:**
![02](https://user-images.githubusercontent.com/15319333/144709889-17198304-402a-42cc-bb4b-54188c7a204f.png)
**After that I changed the transform Props file:**
![03](https://user-images.githubusercontent.com/15319333/144710015-5c2fa576-da57-48dd-b409-04c918a8a1d2.png)
![04](https://user-images.githubusercontent.com/15319333/144710018-49d3edc7-379f-42ab-80c7-8171ab0fe6a2.png)
**Finally, I added my filter to the FilterBox as follows:**
![05](https://user-images.githubusercontent.com/15319333/144710195-b8cc4b1c-2275-4a88-9684-a22aeb399b14.png)
![06](https://user-images.githubusercontent.com/15319333/144710197-64e53d89-fdb9-4e30-b7b1-cd87a983e332.png)
![07](https://user-images.githubusercontent.com/15319333/144710199-1fe1bcd3-6226-457b-b54b-1cca97840078.png)
**And here is my filter file:**
![08](https://user-images.githubusercontent.com/15319333/144710251-3ba4043b-0a00-4a3e-96f5-32ef0263f0fb.png)
**And Da Dam ...**
![09](https://user-images.githubusercontent.com/15319333/144710277-b6e0d519-2502-4c52-8706-2cfe3bfb2c8d.png)

@bbs2009 @xrmx @higaxman @pariser @vschoener @mistercrunch @KingAnnihilate @felexkemboi @TheScoobyBoy

**Comment by AnettaStein** [comment]
@Danielmrg - Hello
Thank you for good idea
I did everything according to your screenshots
Tell me please the full path to install node.js and npm in SuperSet?
And also the path for jalali-react-datepicker
