### ISSUE TITLE
why webpack bundle time take so long? what computor do u got ?

### ISSUE THREAD

**Issue by youngerPlant** [apache/incubator-superset#2583]
Make sure these boxes are checked before submitting your issue - thank you!
the webpack take so long, I smoke many cigarretes during packing!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

can you optimize the frontend webpack config file

**Comment by xrmx** [comment]
It takes around 3 minutes or so on my 3 years old laptop, unless you have ideas on how to make this faster better let's close this issue.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 376 days. Feel free to comment and request for this issue to be reopened.
