### ISSUE TITLE
Date filter definitions

### ISSUE THREAD

**Issue by mearroyo** [apache/incubator-superset#2595]
Why does the From: "Today" filter generate the following SQL

WHERE `DateConfirmed` >= '2017-04-11 09:00:00'

instead of 

WHERE `DateConfirmed` >= '2017-04-11 00:00:00'

?

Is this the intended behavior?

**Comment by mistercrunch** [comment]
It's the underlying library, it does nice text-to-date decoding, but I admit that sometimes it should truncate but doesn't. I'd be open to review a PR that addresses that in a consistent way.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 376 days. Feel free to comment and request for this issue to be reopened.
