### ISSUE TITLE
Specify exact versions to be installed via npm in dependency list

### ISSUE THREAD

**Issue by nishantmonu51** [apache/incubator-superset#2601]
https://github.com/airbnb/superset/blob/master/superset/assets/package.json#L62
uses a range of semver versions to pick up latest compatible versions, this can potentially silently upgrade dependencies for those compiling from source. 
 It would be better if we can specify exact versions for these dependencies.

**Comment by mistercrunch** [comment]
will accept a PR pinning the npm deps

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 375 days. Feel free to comment and request for this issue to be reopened.
