### ISSUE TITLE
[save a slice] redirect to dashboard bug

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2607]
- when saving from the explore view, the “go to dashboard” doesn’t work if your slice is already in a dash
- handle case where slice is on multiple dashboards
- could pass a param, `ref_dashboard_id` if the slice was navigated to from a dashboard

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 311 days. Feel free to comment and request for this issue to be reopened.
