### ISSUE TITLE
[vis] big number axes

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2608]
- accommodate long axis labels, don't overlap
![screenshot 2017-04-12 14 46 28](https://cloud.githubusercontent.com/assets/130878/24980894/119cfccc-1f8f-11e7-86e4-121407a4eaa1.png)

- show first and last dates on x axis
![screenshot 2017-04-12 14 47 56](https://cloud.githubusercontent.com/assets/130878/24980896/136c5930-1f8f-11e7-8395-dfac1525ccdd.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 375 days. Feel free to comment and request for this issue to be reopened.
