### ISSUE TITLE
Add ability to modify size of query window

### ISSUE THREAD

**Issue by silashundt** [apache/incubator-superset#2609]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.4

### Expected results
See a draggable/expandable box corner.

### Actual results
There is no such draggable, expandable box corner.

### Steps to reproduce
There are 25 more lines in this query :(

![image](https://cloud.githubusercontent.com/assets/345119/24982330/d6984ada-1f95-11e7-83cc-1459d231102f.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 375 days. Feel free to comment and request for this issue to be reopened.

**Comment by charlesdguthrie** [comment]
Please reopen this issue.  The query window should be expandable so I can see more than 12 lines of code at a time.

**Comment by mistercrunch** [comment]
@charlesdguthrie this is fixed in master
