### ISSUE TITLE
Dashboard loading queries synchronously

### ISSUE THREAD

**Issue by masterlittle** [apache/incubator-superset#2622]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17

### Expected results
The dashboard while loading should run all sql queries asynchronously, eg - in Celery.

### Actual results
When I watch the output of Celery and superset on console I can see the queries being run on the superset console instead of in Celery, which causes timeouts a lot of times. If the query result is very big 
it also causes sluggish behaviour of the dashboard.
### Steps to reproduce
Just make some slices in a dashboard and watch the consoles.

**Comment by mistercrunch** [comment]
Celery is only used for the SQL Lab backend at the moment, when switched on. We may turn it on outside of SQL Lab eventually.

This is in part for historic reasons, but while we assume SQL Lab can be used for "long running queries" (minutes, even hours) in our case against Hive or Presto, these queries may create summary tables to power interactive exploring or dashboarding.

It's generally not a good experience to have long running queries in the explore view where people assume interactivity, or to have a dashboard that takes forever to load (though with caching it's a different story). 

In the meantime you may be able to crank up your web server timeouts.

**Comment by xiaochuan-du** [comment]
Looking forward to having a way to enhance dashboard loading experience.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 287 days. Feel free to comment and request for this issue to be reopened.
