### ISSUE TITLE
'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#2630]
why the default charset is asccii ,is not unicode

**Comment by xrmx** [comment]
There's this thing called python3 that improved the unicode handling in the python world. Please use it.

**Comment by qinzl1** [comment]
@xrmx  my production environment is python2.7 ,There is a risk in doing it update python version

**Comment by anddyhuaa** [comment]
the error occurs as you have submitted a query in the sqllab ?
you can create one python script under Lib\site-packages named just sitecustomize.py
src code like this: 
`# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8') `
it's ok in the sqllab ,but when visualize sqllab only surpport alpha characters and underscores.

**Comment by mistercrunch** [comment]
It's not uncommon to use virtualenv to run production py3 on top of a distro that ships with py2.7

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 339 days. Feel free to comment and request for this issue to be reopened.
