### ISSUE TITLE
[feature] superset as a datasource for machine learning

### ISSUE THREAD

**Issue by Bamieh** [apache/incubator-superset#2666]
Since superset already acts as a central for all the data from different sources, it would be nice to have a way to play with the datasets via code.

My vision is to have a place where you can write a machine learning model (using python or R for example) and use superset as its data source, it would be nice to have it as a tab from within in the dashboard. Again, since superset already gives you the datasets you need, and the authentication. Then we'd have the results fed back to superset as a data source maybe.

**Comment by Bamieh** [comment]
thinking about it, maybe we can detach the connector module from superset, so it can act as the control unit for both or potentially infinite applications.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 363 days. Feel free to comment and request for this issue to be reopened.

**Comment by kalimuthu123** [comment]
i am having tghe same idea of incorporating such ML applications via the superset

**Comment by mistercrunch** [comment]
We're planning on refactoring out our data access and expose a public API for it. That could enable Superset to act more as a data source for notebooks and such.
