### ISSUE TITLE
where is "/dashboardmodelviewasync/api/read" API

### ISSUE THREAD

**Issue by zjj796** [apache/incubator-superset#2668]
Hi superset team,
I want to edit some authority,
how can i find the api: "/dashboardmodelviewasync/api/read"?
i cant find this api in the code.
how cat i get it
thy

Superset version
0.17.4

**Comment by mistercrunch** [comment]
Look for the model view definition in views/core.py I'm on mobile so I cant paste the exact line...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 343 days. Feel free to comment and request for this issue to be reopened.
