### ISSUE TITLE
String Filtering Calling Back to Database

### ISSUE THREAD

**Issue by kmagida110** [apache/incubator-superset#2669]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.4

### Expected results
It would be great to be able to filter by a string input by the end-user. This is currently available in the table view but it will only filter off items that have already been loaded. It would be great to allow a query to go back to the database to get all items that are associated with that string.

### Actual results
I was not able to recreate this behavior or find an issue raising it in the past.

**Comment by xrmx** [comment]
Doesn't sqllab permit to do this already?

**Comment by kmagida110** [comment]
Not for end users looking at dashboards (as far as I can see), I want to be able to give the end user the ability to input the string on the dashboard and not have to know SQL or have access to SQLlab to do it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 363 days. Feel free to comment and request for this issue to be reopened.
