### ISSUE TITLE
[feature] Mapbox Polygon support

### ISSUE THREAD

**Issue by Sidlegionair** [apache/incubator-superset#2675]
I'd love to see polygon support on mapbox maps or if someone could give me some guidance on how I would go about implementing such a feature I'll try to do it myself

Uber's react-map-gl example here: https://github.com/uber/react-map-gl/blob/8f62ae6089c416c3450f6db596cb895178ee72e8/examples/main/views/style-diffing-example.js

**Comment by sosso** [comment]
working on this!

**Comment by tristix** [comment]
Sosso- anyupdate?

**Comment by kristw** [comment]
Probably can use `deck.gl` instead
