### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by desavera** [apache/incubator-superset#2679]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

{"GIT_SHA": "", "version": "0.17.4"}

### Expected results

the query editor should build the query as we interact with the drop downs

### Actual results
 
the query editor does not create the query and the error msg is given and the query HANGs forever

### Steps to reproduce

go to SQLLAB and interact with the query editor by selecting schema

**Comment by xrmx** [comment]
Stacktrace please

**Comment by desavera** [comment]
Dear xrmx,

there is no stacktrace as we are dealing with a user interface issue that triggers a job that hangs forever. Whatever combination of selection you do from the SQLLab Menu with : 

1) user login
2) select SQLLab
3) select datasource -> schema -> table
4) write down whatever query on whatever schema or table (including the ones selected)
5) the error msg : argument of type 'NoneType' is not iterable is printed
6) task hangs forever

I hope this is enough for your tracking...

+MARIO.

**Comment by xrmx** [comment]
`'NoneType' is not iterable` looks really like a python exception

**Comment by gppeixoto** [comment]
I am facing the same issue as @desavera . Initially the Python `NoneType is not iterable` exception pops up, then the query starts running and hangs forever. Looks like a SQLLab connection issue.

**Comment by desavera** [comment]
You can skip the BUG momentously by only selecting the datasource from the menu and then typing explicit queries on the editor !

**Comment by mistercrunch** [comment]
On which database engine is that happening on? Also please provide the full error stack trace from the web server logs.

**Comment by mistercrunch** [comment]
Also would be nice if you can confirm that this is still an issue on 0.17.6

**Comment by psoderberg** [comment]
I was having the same issue on 0.19.0 using Presto.  Writing explicit queries in SQLLab worked, but using the dropdowns, results shows "argument of type 'NoneType' is not iterable".  The same error occurred creating slices.

I was able to fix this with a change in my datasource SQLAlchemy URI.  Previously, I had used 'presto://hive@localhost:port/'.  I'm able to create slices after changing to 'presto://hive@localhost:<port>/<presto_catalog_name>/<hive_db_name>'

**Comment by yamyamyuo** [comment]
@psoderberg 's answer is correct. I have the same issues with connecting with presto
To connect presto catalogs, we can add this to SQLAlchemy URL: `presto://superset_user_name@presto_ip:presto_port/<presto_catalog_name>`
the `superset_user_name` will show up in your presto cluster overview dashboard presto_ip:8080
