### ISSUE TITLE
Verbose Name in List table column page is used

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#2707]
in list sql metric page Verbose Name can be used alias show in slice explor page, but Verbose Name in List table column page can not use

**Comment by desavera** [comment]
A little confusing but sounds like same as I want too ! ;) Verbose Name for aggregate columns makes no effect ... release 0.17.4

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 314 days. Feel free to comment and request for this issue to be reopened.
