### ISSUE TITLE
Support for deck.gl

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2727]
Deck.gl is a sweet mapping lib with a comprehensive API. It'd be nice to add support for it mostly as is, allowing users to bind their data to the API values and to bind the props to simple controls.

It seems like we could tackle the individual layer catalog as individual visualization and adding an extra one for a multi-layered combo of other slices. 

https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer

**Comment by Sidlegionair** [comment]
This would also solve #2675, seems awesome!

**Comment by gbayes** [comment]
yo @mistercrunch you resolved this yes?

**Comment by Fokko** [comment]
Deck.gl is supported, I think we can close down this issue.

**Comment by mistercrunch** [comment]
Note that the UI & controls are still settling at the moment and we *may* (but also may not) introduce changes that result in breaking existing charts.
