### ISSUE TITLE
how to access charts without login？

### ISSUE THREAD

**Issue by X-Mars** [apache/incubator-superset#2743]
i what to access charts(json) with ajax, but it's must be logged in。

**Comment by X-Mars** [comment]
i use pip install superset，have no superset_config.py

**Comment by X-Mars** [comment]
who can help me？

**Comment by mistercrunch** [comment]
You can set this flag to true:
https://github.com/airbnb/superset/blob/master/superset/config.py#L127

Then you can add public datasources to the Public role. You can also login programmatically, there are examples of that in the unit tests.

**Comment by qq273681448** [comment]
could you tell me how to "add public datasources to the Public role",thanks. @mistercrunch

**Comment by qq273681448** [comment]
@michellethomas  thanks,I have solved this problem

**Comment by youyou098888** [comment]
@qq273681448 Could you please tell me how you achieve  "add public datasources to the Public role" ?

**Comment by dofine** [comment]
Doesn't seem to work for me. I believe I have set the flag to True and added datasource to the Public role.
Can you help me plz @qq273681448

**Comment by qq273681448** [comment]
@dofine You can read this article,https://juejin.im/post/596702f7f265da6c23289373

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 245 days. Feel free to comment and request for this issue to be reopened.
