### ISSUE TITLE
Querying % visualizing data from Hive

### ISSUE THREAD

**Issue by markokole** [apache/incubator-superset#2744]
Im connecting to my Hive service from a remote superset server. I can connect to the Hive database and I get the list of available tables in the given schema. I can add new tables in Sqla Tables as well.
So far so good.
A couple of problems from here on:

1) When I move to SQL Lab -> SQL Editor, I do not get the created Hive database from the database dropdown. What am I missing here?

2) If I click on one of the Hive tables to get into visualization, I get the following error:

> (pyhive.exc.OperationalError) TExecuteStatementResp(status=TStatus(errorCode=-101, errorMessage=u'Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.spark.SparkTask. org/apache/spark/SparkConf', sqlState=u'08S01', infoMessages=[u'*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.spark.SparkTask. org/apache/spark/SparkConf:28:27', u'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:335', u'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:199', u'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:228', u'org.apache.hive.service.cli.operation.Operation:run:Operation.java:276', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:468', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:444', u'sun.reflect.GeneratedMethodAccessor74:invoke::-1', u'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', u'java.lang.reflect.Method:invoke:Method.java:498', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', u'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', u'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', u'java.security.AccessController:doPrivileged:AccessController.java:-2', u'javax.security.auth.Subject:doAs:Subject.java:422', u'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1724', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', u'com.sun.proxy.$Proxy41:executeStatement::-1', u'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:273', u'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:506', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1317', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1302', u'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', u'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', u'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', u'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', u'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', u'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', u'java.lang.Thread:run:Thread.java:745', u'*java.lang.NoClassDefFoundError:org/apache/spark/SparkConf:41:14', u'org.apache.hadoop.hive.ql.exec.spark.HiveSparkClientFactory:generateSparkConf:HiveSparkClientFactory.java:160', u'org.apache.hadoop.hive.ql.exec.spark.RemoteHiveSparkClient:<init>:RemoteHiveSparkClient.java:89', u'org.apache.hadoop.hive.ql.exec.spark.HiveSparkClientFactory:createHiveSparkClient:HiveSparkClientFactory.java:65', u'org.apache.hadoop.hive.ql.exec.spark.session.SparkSessionImpl:open:SparkSessionImpl.java:55', u'org.apache.hadoop.hive.ql.exec.spark.session.SparkSessionManagerImpl:getSession:SparkSessionManagerImpl.java:116', u'org.apache.hadoop.hive.ql.exec.spark.SparkUtilities:getSparkSession:SparkUtilities.java:112', u'org.apache.hadoop.hive.ql.exec.spark.SparkTask:execute:SparkTask.java:101', u'org.apache.hadoop.hive.ql.exec.Task:executeTask:Task.java:160', u'org.apache.hadoop.hive.ql.exec.TaskRunner:runSequential:TaskRunner.java:89', u'org.apache.hadoop.hive.ql.Driver:launchTask:Driver.java:1745', u'org.apache.hadoop.hive.ql.Driver:execute:Driver.java:1491', u'org.apache.hadoop.hive.ql.Driver:runInternal:Driver.java:1289', u'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1156', u'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1151', u'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:197'], statusCode=3), operationHandle=None)

Anyone has any ideas on the issue?

**Comment by mistercrunch** [comment]
1. see the "Expose in SQL Lab" checkbox in the database configuration form
<img width="943" alt="screen shot 2017-05-18 at 8 26 13 am" src="https://cloud.githubusercontent.com/assets/487433/26210176/bd0d2700-3ba3-11e7-818c-57550b536f6d.png">

2. your stack trace is full of `spark` related stuff, are you connecting to Spark SQL or HS2? We use HS2 using the pyhive lib. You should be able to connect to SparkSQL, probably using `hive+jdbc://` connection string, though I've never done that. I'm unclear if others have...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 339 days. Feel free to comment and request for this issue to be reopened.
