### ISSUE TITLE
Word Clouds do not support Unicode characters

### ISSUE THREAD

**Issue by lkozloff** [apache/incubator-superset#275]
When we create a word cloud from a mysql source we get just ????????? for any non English language data.

We're using Khmer (Cambodian), but I suspect that this would hold true for other unicode languages.

**Comment by mistercrunch** [comment]
Any clue what layer is choking on the unicode? If you have a chance, can you test in python3 and report wether the bug exists there as well?

**Comment by lkozloff** [comment]
I got it going in Python3 and I can confirm that the Japanese and Korean unicode text does render as expected... so it seems to be an issue in the python layer. Yay progress!

That said, there is another choke point here related to the correct rendering of Indic scripts: some of the complex vowels and subscripts aren't being displayed correctly, which probably deserves its own issue. I'll try and do some more research about where the rendering issue is coming for before I open that though. This a pretty common issue: it turns out complex scripts are complex to render!

**Comment by threecifanggen** [comment]
Me too.

**Comment by mistercrunch** [comment]
Can we close this?

**Comment by corselia** [comment]
@lkozloff 

You use `MySQL` as database?
If so, set up `SQLAlchemy URI` as below.

```
mysql://username:password@127.0.0.1:3306/mysql_database_name?charset=utf8
```

The suffix '?charset=utf8` is important. I confirmed correct characters (Japanese) showed by this descripition :-)

**Comment by mistercrunch** [comment]
This is fixed, closing
