### ISSUE TITLE
[explore] disable "granularity" control for non-timeseries visualizations

### ISSUE THREAD

**Issue by petroswork** [apache/incubator-superset#2750]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.6

### Expected results
Using the timestamp column for the series, I would expect the time grain to apply, so that the series is e.g. weekly.

### Actual results
The query executed does not include any statement regarding the time grain and this is visible in the visualization.

### Steps to reproduce
Create a distribution bar chart with timestamp series.

**Comment by mistercrunch** [comment]
You may want to use the time series bar chart. We should hide the `granularity` selector on visualizations that are not time series...

**Comment by petroswork** [comment]
I used the time series bar chart instead. Wouldn't it be better if there were only one bar chart visualization and the type would change depending on whether the time grain has a value or not?

**Comment by mistercrunch** [comment]
Perhaps, though some of the form elements as they exist should get enabled/disabled based on whether granularity is specified or not, and the change management around this change (a database migration script that would alter slices to the new scheme) would be significant.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 340 days. Feel free to comment and request for this issue to be reopened.

**Comment by john-bodley** [comment]
I think this is a valid issue, we should only show granularities for charts types which group-by time (time-series).  Having this displayed for non-time-series based charts is misleading.
