### ISSUE TITLE
thrift connection error

### ISSUE THREAD

**Issue by xyhc** [apache/incubator-superset#2754]
Superset version
0.17.6
Superset use Postgresql version:
9.6.2
Superset connect impala happen error:
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(exceptions.AttributeError) 'TBufferedTransport' object has no attribute 'trans' [SQL: u'SHOW TABLES IN default']"}

Superset connect hive is seems ok!

How can I solve this problem???

**Comment by xrmx** [comment]
Looks like this https://github.com/cloudera/impyla/issues/235

**Comment by mistercrunch** [comment]
Are you using pyhive? which version? I just bumped the pyhive>=0.3.0 (from memory) in an open PR.

I don't think impyla works for SQLAlchemy at the moment

**Comment by anddyhuaa** [comment]
i met the same problem, and it seems ok using the thrift==0.9.3

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 340 days. Feel free to comment and request for this issue to be reopened.
