### ISSUE TITLE
Cant connect to Impala with Kerberos

### ISSUE THREAD

**Issue by jrburris** [apache/incubator-superset#2762]
Can anyone point me to some documentation that shows me what connect args I need to connect to Impala with Kerberos?

**Comment by mistercrunch** [comment]
Here's something (might not be the whole story):
http://docs.ibis-project.org/configuration.html#working-with-secure-clusters-kerberos

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 342 days. Feel free to comment and request for this issue to be reopened.

**Comment by CamiloRueda** [comment]
Hi ! I'm working with Superset  0.25.6
an I'm trying to connect with Kerberized cloudera cluster
with impala connector.

my connection is 
![connection](https://user-images.githubusercontent.com/17951727/42661260-431475a2-85f3-11e8-8aa6-bb191c690f39.png)

and this is my error: 
![error](https://user-images.githubusercontent.com/17951727/42661416-bde83fc0-85f3-11e8-82b0-d18f2784764b.png)


I already can do the connection with 
this URI 
![succes](https://user-images.githubusercontent.com/17951727/42662635-ed266a92-85f7-11e8-81a0-339d21b62c11.png)

but I need to do the impala connection, also this connection generates semantic errors when running certain queries.

**Comment by 1federico1** [comment]
Hi, I am facing the same issue, do you were able to solve it ?
