### ISSUE TITLE
Separate manually configured tables from those auto-generated

### ISSUE THREAD

**Issue by tonyjiang** [apache/incubator-superset#2775]
### Superset version
superset (0.17.5)

### Expected results
This is a suggestion, not a bug report. I often go to tables I manually set up, but don't look at those generated by the system. It'd be nice to have them in separate places. It's not very friendly to have them all mixed together.

### Steps to reproduce
Just click on **Tables** from the menu.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 340 days. Feel free to comment and request for this issue to be reopened.
