### ISSUE TITLE
[dashboard] improve flash messaging

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2780]
When saving a slice and adding it to a dashboard, we use Flask's `flash()` method which is then showned by the template at the top of the page.
<img width="446" alt="screen shot 2017-05-18 at 9 37 13 am" src="https://cloud.githubusercontent.com/assets/487433/26213428/dbc8b0ba-3bad-11e7-883b-e39a72f74063.png">

It'd be nice use the `notify` scheme instead somehow and to reduce the message to a single message.

Maybe the flash messages should be put as a payload for the frontend to pickup or along with the bootstrap data, and then the frontend can use `notify` to display them.

**Comment by higaxman** [comment]
Can i work on this ?

**Comment by mistercrunch** [comment]
Sure yes. That's what the `starter_task` label is for
