### ISSUE TITLE
[/sqllab#search] better defaults

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2782]
On Query Search page
- default search to "1 hour ago" rather than "28 days ago" (to view most recent searches by default)
- default to current user's queries 

<img width="1438" alt="screenshot 2017-05-18 13 59 41" src="https://cloud.githubusercontent.com/assets/130878/26223270/44feca50-3bd2-11e7-9022-af13050917d2.png">

**Comment by aayushshah15** [comment]
Can I work on this?

**Comment by ascott** [comment]
@aayushshah15 yes, please do!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 338 days. Feel free to comment and request for this issue to be reopened.
