### ISSUE TITLE
Extending db_engine_specs

### ISSUE THREAD

**Issue by mxmzdlv** [apache/incubator-superset#2789]
What's the best way to extend db_engine_specs? I am currently extending it by adding wrapt hook in superset_config.py, but that is very hacky:

```
@wrapt.when_imported('superset.db_engine_specs')
def hook(db):
    class CustomEngineSpec(db.BaseEngineSpec):
        ...
    db.engines['bq'] = CustomEngineSpec
```

**Comment by xrmx** [comment]
The best and easiest way would to be to contribute upstream your EngineSpec :)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 337 days. Feel free to comment and request for this issue to be reopened.
