### ISSUE TITLE
[permissions] when a user creates a table from sql-lab, make them an owner

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2798]
currently, the user doesn't get added as an owner after they create a datasource via the visualize flow in sql lab. 

![create-datasource-from-sql-lab-flow](https://cloud.githubusercontent.com/assets/130878/26326559/91cf2584-3ef0-11e7-9def-4d53b1ac857b.gif)

expected behavior is that the user be added as an owner on that new table.

**Comment by ascott** [comment]
@mistercrunch could this be as east as adding something like `table.owner = g.user.get_id()`
[here](https://github.com/airbnb/superset/blob/master/superset/views/core.py#L1757)?

**Comment by jfeng15** [comment]
@ascott - I'm so happy to see that we're launching a PR for this use case!

**Comment by mistercrunch** [comment]
Currently there's no notion of ownership for tables. We need to add a many to many relationship between a new `SqlaTable.owners` and `User` and get rid of the unique constraint on db_id/schema/table_name and manage ownership on the ModelView update/delete events like we do for Slice and Dashboard.

**Comment by timifasubaa** [comment]
Related https://github.com/apache/incubator-superset/issues/911

**Comment by qyoz** [comment]
this is a big issue for us.
we have multiple teams who can't have access to eachothers datasources, but they also have to work with sql lab because of joins. the only way to let them work is giving everyone `all_datasource_access` so they can create an sql datasource and slice it. 
this can't work in an enterprise environment.

**Comment by qin4zhang** [comment]
How to solve it？

**Comment by mistercrunch** [comment]
Here: https://github.com/apache/incubator-superset/pull/5119

**Comment by qin4zhang** [comment]
@mistercrunch It's not merged yet. Which version could it be released?

**Comment by mistercrunch** [comment]
If you want recent commits I suggest you make your own releases/build. It's well documented and gives you the freedom to use any base and pick your 🍒 on top.

We don't have a super clear release cadence at the moment, but it's likely to take weeks as this didn't make the boat for `0.26.0`
