### ISSUE TITLE
"static\assets" link causes repository management issues working under windows

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#281]
Hi there,

Don't know if anybody else has managed building caravel under windows.
It took me a while but I did but I always have a problem when switching between branches as I had to delete "assets" link file and create a windows symlink instead.

Is there any way to make this folder to be physically created by setup and remove the "assets" from repository, the folder will be added to the ignore list ofc.

I'm digging into webpack to check if we can create the folder while generating the files but don't know if there are other files needed (maybe from de node_modules).
Thanks

**Comment by mistercrunch** [comment]
It seems like firing up a Linux VM for development might be the way to go.

**Comment by feixialong** [comment]
why not try to delete "static"  in the setup.py. change PACKAGE_DIR = os.path.join(BASE_DIR, 'superset','static', 'assets') as PACKAGE_DIR = os.path.join(BASE_DIR, 'superset', 'assets')

**Comment by mistercrunch** [comment]
@feixialong I will approve that PR if you send it
