### ISSUE TITLE
[explore, usability] filter drop-down lists are cut off

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#2821]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2

### Expected results
All buttons and lists are fully visible and accessible.

### Actual results
The `Add filter` button as well as the expanded drop-down selectors for the column name, the operator and the filter values are cut off at the bottom of the page, as long as there are more than just a couple of options present.

This behavior can also be observed in the animation shown in #2330 and does not seem to depend much on the employed web browser, as tested with Firefox and Vivaldi.

### Steps to reproduce
* Add a new filter in explore view, preferably for a column that has many distinct options.

With every added filter, one needs to scroll within the left panel and then within the drop-down lists which are cut off and thus hiding some options.

For power users this is probably not a big deal, as they would just start typing; however, to those that are less familiar with the underlying table, the option lists are very helpful.

### Thoughts on a possible approach
Maybe it would make sense (if possible) to add some padding at the bottom of the left panel's bounding box. This padding should always be present and still be included when more filters are added.

The size of the padding should be large enough to accommodate the maximum size of the filter selectors (assuming that there is a limit set somewhere).

**Comment by joshwalters** [comment]
I have also seen this issue, it can make it very hard to apply filters.

**Comment by graceguo-supercat** [comment]
fixed in #3279.
