### ISSUE TITLE
how to connect impala via socks5

### ISSUE THREAD

**Issue by zhouzach** [apache/incubator-superset#2822]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by zhouzach** [comment]
I expect some code just like :
{
    "metadata_params": {},
    "engine_params": {
		"connect_args": {
		"socksProxyHost": "127.0.0.1",
		"socksProxyPort" : "1080",
		"socksProxyVersion" : "5" }
    }
}

**Comment by xrmx** [comment]
Pretty hard to help you without showing the actual error.

**Comment by c0b** [comment]
should have a general policy to close if NEEDS INFO from issue reporter but no longer responding for a certain amount of time? since @zhouzach not responding for 6 months, is it long enough to close it
