### ISSUE TITLE
swap out FilterableTable.jsx for @data-ui/data-table

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#2834]
swap out javascripts/components/FilterableTable/FilterableTable.jsx for [data-ui/data-table](https://www.npmjs.com/package/@data-ui/data-table)

**Comment by kelchm** [comment]
This would be great -- the FilterableTable component chokes quite badly with larger sets of data.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 305 days. Feel free to comment and request for this issue to be reopened.
