### ISSUE TITLE
Add axis customization on slice view

### ISSUE THREAD

**Issue by napjon** [apache/incubator-superset#2872]
This more of a feature request rather than a bug. 

Is there a way from to customize axes in the iframe itself?

For example if I determine that this slice would be a Buble Chart, user can interactively define metrics name for x-axis, y-axis, and size respectively, but not necessarily have to go to "edit slice".

Something like this from Plotly

![](http://i.imgur.com/d3y4nwm.gif)

I'm using Superset 0.18.2

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 327 days. Feel free to comment and request for this issue to be reopened.
