### ISSUE TITLE
Connect to Openedge Progress Database

### ISSUE THREAD

**Issue by mauriciozambretti** [apache/incubator-superset#2874]
Is it possible to conect to a Openedge Progress Database? Thanks.

**Comment by mauriciozambretti** [comment]
I found this https://code.activestate.com/pypm/progress-sa/ and installed it but I don't know what is the dialect for it! I'm not a developer and there isn't docs...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 321 days. Feel free to comment and request for this issue to be reopened.
