### ISSUE TITLE
[dashboard] use POST instead of GET to fetch `explore_json`

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2885]
the explore_json endpoint should already accept POST

**Comment by HumairAK** [comment]
Hello, this is my first issue I've decided to tackle :) 
I was wondering if this is what you are expecting:

![post_fix](https://user-images.githubusercontent.com/10904967/27965066-76674b32-6308-11e7-8a65-ff7dfb1bea68.png)

I.e. When rendering each slice, POST is used in the calls to explore_json. Thanks!
