### ISSUE TITLE
New endpoint for Slice without redirect

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2887]
In an effort to get rid of long URLs with endoded JSON, create a new endpoint @ `/superset/slice/<slice_id>/`. Might need to refactor out what is common between `/superset/explore` and this new endpoint.

Should support overriding of slices `formData` in the form `URLEndode(`/superset/slice/<slice_id>/?form_data={"foo": "bar"}`)`

**Comment by JImBurris** [comment]
This would be very helpful
