### ISSUE TITLE
Logo image replacement

### ISSUE THREAD

**Issue by jerryhall** [apache/incubator-superset#2898]
This pains me to write but, when I try to change the App Icon image - even when using the same name, the image appears as broken. I've been doing sites since 1994 so I have some idea of what's going on. This one is killing me. Any clues would be helpful. 

My setup is on an AWS/EC2 Centos 6. I can't say definitively because I'm not certain where to check but, think my version is 0.17

**Comment by SalehHindi** [comment]
By App Icon image, do you mean the logo that appears on the top left when you log into superset? Or do you mean the favicon icon? I was able to change the logo by going into `superset/assets/images` within my superset install and replacing `superset-logo@2x.png` with a random .png file. I had to clear my browsing cache for this to work. But after doing so the new logo appeared. Try that and let me know if that works.

**Comment by gurpreet19** [comment]
For windows location is venv\Lib\site-packages\superset\static\assets\images

**Comment by sedhha** [comment]
> This pains me to write but, when I try to change the App Icon image - even when using the same name, the image appears as broken. I've been doing sites since 1994 so I have some idea of what's going on. This one is killing me. Any clues would be helpful.
> 
> My setup is on an AWS/EC2 Centos 6. I can't say definitively because I'm not certain where to check but, think my version is 0.17

Were you able to solve it?

**Comment by AHAn555** [comment]
> > This pains me to write but, when I try to change the App Icon image - even when using the same name, the image appears as broken. I've been doing sites since 1994 so I have some idea of what's going on. This one is killing me. Any clues would be helpful.
> > My setup is on an AWS/EC2 Centos 6. I can't say definitively because I'm not certain where to check but, think my version is 0.17
> 
> Were you able to solve it?

u need to place your png image in superset_app container. Thats worked for me.
command: docker cp your_file.png superset_app:/app/superset/static/assets/images/
