### ISSUE TITLE
No way to remove/exclude GROUP BY section while saving slices

### ISSUE THREAD

**Issue by kartha01** [apache/incubator-superset#291]
I am using Caravel 0.8.5 and looks like there is no way to create a simple table slice without the GROUP BY section. 
While after  removing the entries from the GROUP BY section and hitting the QUERY button retrieves the data but saving the slice the default COUNT() gets added to the Metrics text box and as a result it fails with 
Exception: Choose either fields to [Group By] and [Metrics] or [Columns], not both

We need a DELETE or OFF button for the GROUP BY section and for that matter even for the TIME section.

**Comment by mistercrunch** [comment]
if you have field(s) in columns, you can't have one in metrics or groupby. Is metrics empty?

**Comment by kartha01** [comment]
Thanks for responding.
I am trying to create a table view without any groupby/aggregations and selecting some the columns in the 'NOT GROUPED BY' section . 
As I mentioned in my prev note, I can run the query and view the data during Edit, but the moment I save it, some default Metrics gets added and the columns that I selected before are gone.

Looks like while saving the left hand section is filling up with defaults and not persisting my selection.

**Comment by jacopoch** [comment]
I can reproduce this also in **0.8.8**, can't debug it right now, but will do tomorrow unless solved by then!

**Comment by jacopoch** [comment]
@kartha01 you can kinda go around the problem at the moment by setting up the columns you want to use in the edit slicer view, then your slicer will be saved in the correct way and should show up nicely again.

If I have time I'll figure out a fix, please @mistercrunch promote this to bug 👍 

<img width="550" alt="columns" src="https://cloud.githubusercontent.com/assets/1187497/14699343/a66d324e-079f-11e6-8852-fb8f78ffa062.png">

**Comment by stage2012** [comment]
The only workaround I found is to groupby all colums and have a unique key.
Still the same bug as Kartha01 described, doing something equivqwlent to 'Select Colum1, Column2,... from table" workds in edit mode but when I want to save some default metrics gets added causing the error choose between Group by and metric or not group by
