### ISSUE TITLE
[Dashboard] Nested scroll bars using table views after upgrading to 0.18.4

### ISSUE THREAD

**Issue by olbapito** [apache/incubator-superset#2913]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
version	"0.18.4"

### Expected results
Using a "table view" into a dashboard, just have the vertical scroll bar. 

### Actual results
there are nested scroll bars. I have the vertical scroll bar, and two more unexpected scroll bars.
![imagen](https://cloud.githubusercontent.com/assets/28396794/26814878/159c708c-4a5f-11e7-9832-98b957eed51e.png)

### Steps to reproduce
just put a table view into a dashboard and you will see the nested scroll bars. I started happening since the 0.18.4 upgrade.

Thanks!

**Comment by olbapito** [comment]
I did a fully fresh install and I´m facing the same behavior with the included examples :(

![imagen](https://user-images.githubusercontent.com/28396794/26851945-e6b934e2-4ae2-11e7-943f-24a77d71cbe0.png)

**Comment by olbapito** [comment]
Hi,
I´m trying to find why it happens rolling back the latest changes on tableview files (./static/assets/visualizations/table.js|.css) in a separate environment, but I can´t see changes in the behavior of my superset installation after making changes. Am I missing something? 

thanks

**Comment by xrmx** [comment]
Upgrading from which version?

**Comment by olbapito** [comment]
I'LL check the previous version on monday. I Think I was two versions delayed. So it would be 0.18.1 or 2. But anyway. I was able to reproduce the issue installing a fresh superset (0.18.4) via pip in a new debian (installed just for this purpose).

**Comment by xrmx** [comment]
Have you verified it still happens in 0.18.5?

**Comment by olbapito** [comment]
I did the pip upgrade last friday and saw the same behavior. But i'm not sure if superset was upgraded. Let me check it tomorrow.

**Comment by olbapito** [comment]
upgraded via pip (+ init, + db upgrate)
![imagen](https://user-images.githubusercontent.com/28396794/27539259-30ba80cc-5a52-11e7-9d0c-67a40018a1c7.png)

Superset´s version info still says 0.18.4 (is this ok?)
![imagen](https://user-images.githubusercontent.com/28396794/27539360-ab2f1354-5a52-11e7-8a39-cfcdc8e5f884.png)

I go to the "Births" example dashboard
![imagen](https://user-images.githubusercontent.com/28396794/27539543-54bc5a94-5a53-11e7-83bc-7f6d4ddaa590.png)

Girls or Boys slices and the scroll bars are still there
![imagen](https://user-images.githubusercontent.com/28396794/27539646-aa522218-5a53-11e7-9b13-2eaf5e5f353d.png)

**Comment by xrmx** [comment]
@olbapito have you forget to restart the server?

**Comment by olbapito** [comment]
I have restarted the Linux. but it still says .018.4

**Comment by olbapito** [comment]
pip uninstall superset
pip install superset. (and the other steps) and now I can read 0.18.5. :)

the bad side is that I still have the nested scroll bars.

![imagen](https://user-images.githubusercontent.com/28396794/27541728-66c4b328-5a5b-11e7-8e79-49fad898c0b5.png)

**Comment by olbapito** [comment]
@xrmx previous version was 0.17.3

**Comment by olbapito** [comment]
It seems that #3069 is having the same issue.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 284 days. Feel free to comment and request for this issue to be reopened.
