### ISSUE TITLE
Local datetime are converted as GMT timestamps by dttm_sql_literal

### ISSUE THREAD

**Issue by rogeriobp** [apache/incubator-superset#2915]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
"version": "0.18.3-alpha.1"

### Expected results
"now" should return timestamp in UTC to the query.
Exemple: 2017-06-06 09:50 local time (GMT -03:00) should be 1496753400000 timestamp, or 2017-06-06 12:50 GMT.

### Actual results
<img width="712" alt="screen 20shot 202017-06-06 20at 2009 52 46" src="https://cloud.githubusercontent.com/assets/21210483/26830452/50d49176-4a9f-11e7-8726-3c1feaa7944c.png">
<img width="1328" alt="screen 20shot 202017-06-06 20at 2009 52 02" src="https://cloud.githubusercontent.com/assets/21210483/26830445/4ad407a2-4a9f-11e7-8d51-2143c1eb5d74.png">

As you can see, the actual timestamp returned by the dttm_sql_literal is 3 hours behind (in my case), causing some data to be excluded in the query, specifically those that the timestamp used as Time Column is in this range.

### Steps to reproduce
Use multiformat-time-series as datasource, select epoch_ms or epoch_s as time_column, hit query and visualize the generated query. Check the timestamp, it will be in local time as UTC.

### Fix
So, as a fix, we included the function gmtime() from the time module, and passed as a parameter for dttm_from_timtuple() inside of parse_human_datetime.
We made this way because, apparently, the problem is only with the since and until dates and when using timestamp columns.

Since I don't know much about python, I thought it was better to send you guys this instead of making a PR, as I don't know if there is a problem including modules or if this change would cause a problem somewhere else.

Here is what we did:
<img width="314" alt="screen 20shot 202017-06-06 20at 2010 22 09" src="https://cloud.githubusercontent.com/assets/21210483/26831328/6234cc9e-4aa2-11e7-9f83-3db5ba9ed9de.png">
<img width="633" alt="screen 20shot 202017-06-06 20at 2010 23 00" src="https://cloud.githubusercontent.com/assets/21210483/26831330/64b3e144-4aa2-11e7-8a30-b555b2782447.png">

These were the only changes, and it seems that it has solved the problem.
<img width="682" alt="screen 20shot 202017-06-06 20at 2010 27 22" src="https://cloud.githubusercontent.com/assets/21210483/26831678/6c8b23d6-4aa3-11e7-9ae6-0b577c6e1d75.png">
<img width="1347" alt="screen 20shot 202017-06-06 20at 2010 27 00" src="https://cloud.githubusercontent.com/assets/21210483/26831681/6f2ac132-4aa3-11e7-885e-73a4898a8c68.png">

Thank you very much for this amazing tool and all your efforts to make it better.

**Comment by SalehHindi** [comment]
I'm just a community contributor but I can try to help. Just so I am on the same page, @rogeriobp, are you saying that because the now button uses GMT, you are getting query results that are different than you expect because of time zone differences? Are you also suggesting to use UTC instead of GMT for the now button as a solution to this problem?

**Comment by rogeriobp** [comment]
hi @SalehHindi , thank you for your reply!
I'm gonna try to do a step by step to make this clearer.
You set your Time filters and let's say you put "now" on the Until field.
On viz.py `to_dttm = utils.parse_human_datetime("now")` is called and, since `dttm = parse(s)` will result in a exception, it will try `cal = parsedatetime.Calendar() dttm = dttm_from_timtuple(cal.parse(s)[0])`, that will result in `datetime.now()` object.
The problem is, as we are using a timestamp column in Time Column, when get_time_filter receives start_dttm and end_dttm it will pass to dttm_sql_literal this object (in local time, since it is datetime.now()) and it will return a timestamp that is in UTC, but in local time (see screenshot).

Example:
In my timezone it is 13:53. Hit query, I get 1.497016382e+12, or GMT: Friday, 9 of June 2017 13:53:02, wich is wrong, since my timezone is 3 hours behind. The expected result should be GMT: Friday, 9 of June 2017 16:53:02.

My sugestion is to use the function gmtime() as a sourceTime for cal.parse, so that the timestamp returned is in UTC, not in localtime. I know that GMT and UTC are not the same, but I didn't find on parsedatetime a seemingly function.

I don't know if this is the best solution, but it worked, at least to the human readeble strings, but we later realized that the problem still persists when using expressions that are parsed by the dateutil.parser.

Hope it helps and thank you again.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 317 days. Feel free to comment and request for this issue to be reopened.
