### ISSUE TITLE
Jinja templated markdown viz

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2919]
In the markdown visualization, it would be nice to be able to fetch data through a jinja macro and embed it.

You can imagine a jinja macro that would fetch a single cell through a sql query and embed it in the markdown somehow

**Comment by JImBurris** [comment]
+1

**Comment by kartikshanbhag3333** [comment]
Is this possible? or it is still a Work in Progress?

Thanks,
Kartik

**Comment by bbs2009** [comment]
+1

**Comment by kalium99** [comment]
Personally, I would like to see access to the Pandas dataframe accessible in the template for two main reasons.

1. It's easy to implement
2. It's very powerful.

Of course it requires you to know how to handle a dataframe. I created #5747 for this purpose, and if you feel it is a dupe of this then please close it as such. If this ticket though is more of a 'fetch a single cell' (as per @mistercrunch original comment) then I'd rather keep #5747 open as a separate issue.

**Comment by monkevlar** [comment]
Just wanted to re-open the issue because i found a code snippet posted from @ankoh in #5747 which could be integrated in the master branch:

https://github.com/apache/incubator-superset/issues/5747#issuecomment-425669720

**Comment by micimize** [comment]
Latest incarnation #6771 was closed as a `#wont-fix`
