### ISSUE TITLE
How to configure multiple brokers for druid in superset

### ISSUE THREAD

**Issue by kumgaurav** [apache/incubator-superset#2920]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5-alpha.1

### Expected results
if multiple users are using superset, queries needs to distributed among multiple brokers

### Actual results
Putting multiple hostname in broker host is breaking the druid query

### Steps to reproduce

put multiple host by comma seperated value in supserset

**Comment by xrmx** [comment]
Are you sure you need multiple brokers? Do you need a router then? http://druid.io/docs/latest/development/router.html

**Comment by kumgaurav** [comment]
thanks for the reply. Still learning the technology. I read the
documentation of router but I do not see how it will know hosts of multiple
broker.
Can you please provide some guidance.

thank you

**Comment by kumgaurav** [comment]
Also How much simultaneous queries a broker can handle. we are seeing
superset is freezing if multiple people are utilizing it.

**Comment by nishantmonu51** [comment]
@kumgaurav: Druid brokers announces themselves in zookeeper and router discovers them through zookeeper.

**Comment by kumgaurav** [comment]
thanks for clarification, I will try to change in superset today from
broker to router and see the performance .

**Comment by mistercrunch** [comment]
At Airbnb our service discovery system does load balancing on our brokers.

**Comment by abhijain1351** [comment]
I'm trying to set up a druid router that sends queries to brokers that belong to different tiers based on query time interval. How does router figure out which tier that query should go to?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 212 days. Feel free to comment and request for this issue to be reopened.
