### ISSUE TITLE
Access to datasource needed to be re-granted after datasource is renamed

### ISSUE THREAD

**Issue by fufjvnvnf** [apache/incubator-superset#2925]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2

### Expected results
Access to datasource stays the same after datasource is renamed.

### Actual results
Gamma user loses access to datasource once it's renamed. Is this supposed to be the case by the design? Also, after changing the name of table in the client side as admin, I am not able to explore the table either since the table name in mysql is still the same. 

### Steps to reproduce
Should be straightforward.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 319 days. Feel free to comment and request for this issue to be reopened.
