### ISSUE TITLE
[SQL Lab] polling should give up on long dead running queries 

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2926]
Currently if there's some query that is flagged as `running`, SQL lab will poll forever. It should give up at some point. 24 hours maybe? Local state should go to `timeout`

**Comment by dsoukhov** [comment]
Hi,

This is my first issue I'm tackling so I'd like a few clarifications please.  When you say "Local state should go to timeout" do you mean the state of the long running query in question? Finally should the user have the option to re enable the query (via an enable button perhaps) once in the timeout state? 
Thanks

**Comment by dsoukhov** [comment]
Also, where should the timeout state be set? For example should the ui detect when a running query exceeds 24hrs and send a post request similar to stop or should it be done elsewhere?
