### ISSUE TITLE
druid.query.groupBy.maxMergingDictionarySize, or druid.processing.buffer.sizeBytes

### ISSUE THREAD

**Issue by wangbokun** [apache/incubator-superset#2948]
我用Superset对接druid，查询时候报一下错误，maxMergingDictionarySize
io.druid.query.QueryInterruptedException: Not enough resources to execute this query. Try increasing druid.query.groupBy.maxOnDiskStorage, druid.query.groupBy.maxMergingDictionarySize, or druid.processing.buffer.sizeBytes.

那里可以配置query参数？

**Comment by timfeirg** [comment]
it's unlikely to get any answers since you are using languages that superset maintainers probably don't understand, and didn't follow [the guidelines](https://github.com/airbnb/superset/blob/master/CONTRIBUTING.md) when raising this issue.

**Comment by wangbokun** [comment]
hi, I use superset connection druid datasource，select data err msg is：


**### _maxMergingDictionarySize
io.druid.query.QueryInterruptedException: Not enough resources to execute this query. Try increasing druid.query.groupBy.maxOnDiskStorage, druid.query.groupBy.maxMergingDictionarySize, or druid.processing.buffer.sizeBytes._**



But i don‘t fond  configure  maxMergingDictionarySize  for superset  druid query，can you help me？

**Comment by wangbokun** [comment]
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/groupby/GroupByQueryConfig.java

this  is  maxMergingDictionarySize  default size，i think this too  small，query  change this confgure。
  private long maxMergingDictionarySize = 100_000_000L;

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 314 days. Feel free to comment and request for this issue to be reopened.
