### ISSUE TITLE
Set autorefresh timer for a specific chart, not the whole Dashboard

### ISSUE THREAD

**Issue by DylanCa** [apache/incubator-superset#2958]
Hey,

I was wondering if this is possible, and if yes, how ? I got a lot of Dashboards with a lot of charts ( nearly 30+ per dashboard ), I just need a few of them to autorefresh every xx minutes. If you have an idea on how to do that, I'll take it ! 

NB : I can't move the charts to a special Dashboard in order to set the whole Dashboard to autorefresh itself.

**Comment by RichRadics** [comment]
I've submitted a solution for this - see the latest docs for refresh_immune_slices

**Comment by dmigo** [comment]
@mistercrunch this one seems to be resolved
