### ISSUE TITLE
Support for non-integer timezone Offset in the UI.

### ISSUE THREAD

**Issue by manurana** [apache/incubator-superset#296]
In the table details, there is a field called Offset. Currently, you cannot set a non-integer value for this. India (IST) has a 5hr 30 min offset. Need a way to configure this in the field.

**Comment by sid88in** [comment]
@manurana looks like you are requesting similar feature to this : https://github.com/airbnb/caravel/issues/299 ?
I am planning to add timezone filter in the UI to convert data between timezones.

**Comment by manurana** [comment]
@sid88in : these settings can be at a system level, source level, table level, or UI level (report)
The current implementation is at a table level. System level would be the best. An override at a report level would be a nice to have.

**Comment by sid88in** [comment]
@manurana for my use case it makes more sense to have a timezone parameter (UTC, EST, PST, IST..etc) on the UI so that multiple users can see the results as they want.

**Comment by sid88in** [comment]
We can certainly discuss the pros/cons of having such parameter at system level, source level, table level, or UI level (report).

**Comment by manurana** [comment]
In most cases, the user does not need to go into the details of the TZ. The admin sets this once (at a system level) and thats it. You might have a specific use case where the user needs to change this often during the course of his work, but its not common.

**Comment by sid88in** [comment]
agree - depends on the use case ;)

**Comment by liuluxyz** [comment]
@sid88in   Hi, you mentioned that you plan to add timezone filter. May I know what is the progress?

**Comment by mistercrunch** [comment]
It would make sense to have a timezone feature in the time-related section of the explore view.

**Comment by anilvpatel21** [comment]
@mistercrunch Any update on this? Hour Offset still supports integer value. Using 0.38.0 version of superset.

**Comment by varunvora** [comment]
Waiting for this feature. Would prefer IANA timezone support..
