### ISSUE TITLE
[explore] User can't see the complete dropdown list

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#2960]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce
<img width="1135" alt="screen_shot_2017-06-13_at_2_41_15_pm" src="https://user-images.githubusercontent.com/27990562/27106098-ca11b9c2-5046-11e7-8355-a44fa5b58299.png">

**Comment by rumbin** [comment]
It seems, this is a duplicate of #2821

**Comment by kelchm** [comment]
I think ideally this would just get fixed upstream in `react-select`. I haven't tested it yet, but [this](https://github.com/JedWatson/react-select/pull/1677) looks like it would work.

**Comment by graceguo-supercat** [comment]
fixed in #3279.
