### ISSUE TITLE
superset Single Sign On（单点登录）

### ISSUE THREAD

**Issue by yuzhijun2** [apache/incubator-superset#2965]
How to implement superset single sign on？
 Not validated, Log in directly to superset from the web project。

**Comment by xrmx** [comment]
Authentication is handled by flask-appBuilder, you should look at its documentation.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.
