### ISSUE TITLE
Sharing queries between slices, caching, and other hard things.

### ISSUE THREAD

**Issue by JohnOmernik** [apache/incubator-superset#2967]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X]I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Current

### Expected results
Cached Data, reduced number of quiries, quick response time initially; rainbows and unicorns strategically. 

### Actual results
Confusion and Pain

### Steps to reproduce
Running a Dashboard with lots of queries and thinking of my poor database. 

I am enjoying Superset, and I have a dashboard created and working. I've noticed that when  I run queries it seems I could be "saving" trips if I could find a way to materialize certain queries and share the data between slices. 

For example,  I may do a query that shows sales for items (number of items) grouped for a given data in a pie chart, but also want to show a total of all sales... I suppose one is a select itemnum, count(*) the other is just just count(*)  But I guess, I could think of other potential items where the data could be shared between slices (showing different visualizations of the same data).   

So that led me to searching the issues, and I found Caching, however... call me naive, call me ignorant, call me maybe, but when I read it, it seemed more to be caching the web presentation layer (I.e. FLASK is a web thing right?) or does this actually cache data request too?  This is where I got super confused, and started on the path of the dark side.   I guess, is caching the right way for reduce the number of queries?   Sharing between slices even possible?  Is 42 really the answer to life, the universe, and everything?   

Important questions for a visualization tool.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.

**Comment by SaiManojG** [comment]
@mistercrunch  

Is the above mentioned feature / request exists in superset (or) are there any plans to implement it?
can you please let us know about this feature / request.

Thanks in advance.

**Comment by SaiManojG** [comment]
@JohnOmernik 

hey john!, 
did you find any way to acheive this, i also need the same kind of implementation.

**Comment by Hekum** [comment]
Hey @JohnOmernik  and @SaiManojG , same thoughts here. Did you get anywhere with this issue? :)

Cheers,

Nikita
