### ISSUE TITLE
SQL lab doesnt  support a table that has CLOB column. 

### ISSUE THREAD

**Issue by mnemalur** [apache/incubator-superset#2969]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
 ability to see the table results

### Actual results
Editor throws a message. 

### Steps to reproduce

1.  Add any  table that has CLOB Data type columns as a data source. 
2. Go to SQL lab editior 
3. Select * from TABLE A     
this throws a message. 
![image](https://user-images.githubusercontent.com/9202429/27139198-5b372faa-50f0-11e7-9a7c-b281c5a103b9.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.
