### ISSUE TITLE
Bump Celery to latest (4.x) 

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#2971]
I tried doing this but realized it wasn't trivial as Celery deprecated support for sqlalchemy as a broker, and we rely on that for unit tests. This would require setting up Redis on travis which should be straightforward.

**Comment by rjpereira** [comment]
According to https://github.com/celery/kombu/commit/be79b3d4cdbfe80cc5400396d7d81abeb73d0136 support to SQL Alchemy, is on 4.1 too. If this is true, can requirement of celery be switched to >=3.1.25 ?

**Comment by mistercrunch** [comment]
`>=3.1.25` is a bad idea as the interface is different for >=4. For Superset we generally want to pin as Superset is a product not a library. It makes sense to pin in that context.

**Comment by hajdbo** [comment]
https://github.com/apache/incubator-superset/blob/master/setup.py shows it's done (celery >=4.2  <5).

@kristw please close.
