### ISSUE TITLE
superset can not know the string/varchar columns from impala table

### ISSUE THREAD

**Issue by zhouzach** [apache/incubator-superset#2973]
Make sure these boxes are checked before submitting your issue - thank you!

- [* ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ *] I have reproduced the issue with at least the latest released version of superset
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.4

### Expected results
when Add Sqla Table, superset can get all right columns from impala table

### Actual results
when Add Sqla Table, superset can not know the string/varchar columns from impala table

### Steps to reproduce
1.have impala table:

![image](https://user-images.githubusercontent.com/9605863/27173113-20715ce2-51ea-11e7-94bd-85283d970223.png)

2.Add Database from impala

3.Add Sqla Table
edit table->list table column, I find that the string/varchar columns can not be known by superset

![image](https://user-images.githubusercontent.com/9605863/27173298-c822fc34-51ea-11e7-886d-d9184268a0c2.png)

**Comment by xrmx** [comment]
Sure this is an issue in superset and not in the sqlalchemy dialect / plumbing?

**Comment by zhouzach** [comment]
@xrmx I am a superset beginner, no idea about the problem.Do you use superset on impala table that has the string/varchar columns and succeed？

**Comment by xiaoyugit** [comment]
i had the same issue with 0.18.5

**Comment by JImBurris** [comment]
Same issue. I'm on 0.18.5 as well. This maybe another issue, but Time Grains don't show for Impala as well.

**Comment by mistercrunch** [comment]
I wonder if the `UNKOWN` value comes out of the SQLAlchemy dialect or if it comes from us here:
https://github.com/apache/incubator-superset/blob/a141695b2b73df1d05d74c8ed8e22341e6e25edc/superset/connectors/sqla/models.py#L586

Do you see stack traces in your log when saving a Impala table? If so please paste it here. If not that means it's coming out as `UNKNOWN` out of the driver/dialect and needs to be fixed there.

**Comment by mistercrunch** [comment]
@JImBurris about time grains, they haven't been contributed yet for Impala. Someone needs to send a PR with a DBEngineSpec with time grains defined for impala, it's as simple as:
https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py#L193

**Comment by mistercrunch** [comment]
Here, can someone that has impala test this?
https://github.com/apache/incubator-superset/pull/3225

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 264 days. Feel free to comment and request for this issue to be reopened.
