### ISSUE TITLE
[feature request] Apply complex filters on queries

### ISSUE THREAD

**Issue by thaume** [apache/incubator-superset#2975]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.6

### Expected results
I would like to be able to apply complex filters to certain of my queries. For instance, I would like to be able to request based on the session of a visitor of the website (comparing track events based on the length of the session).
This SQL query is 20 lines long, and I would like to be able to filter things based on it.

Example : get the number of pageviews per session. I will get the count of pageview and then I need to apply the session SQL query.

### Actual results
Need to re-write complete queries.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 311 days. Feel free to comment and request for this issue to be reopened.
