### ISSUE TITLE
Error on case-sensitive names for table/fields/etc. in PostgreSQL

### ISSUE THREAD

**Issue by Srynetix** [apache/incubator-superset#3001]
Hello all !

I am currently running Superset 0.18.4 on Docker, connecting with a PostgreSQL database linked to a Django project, containing table names and fields with capital letters.
When executing SQL queries outside of Superset, we have to double-quote each table name with the corresponding schema and each field containing capital letters.

The problem is that PostgreSQL will lowercase every names if they are not double-quoted.
So, when exploring data and when using SQL Lab, there are errors like 'relation "my_table" does not exist'.

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar (except for #408 one year ago)

### Superset version
0.18.4 (installed via pip)

### Expected results
Working SQL queries even with case-sensitive table and field names.

### Actual results
Errors because of automatic lower-case.

### Steps to reproduce
Try to execute queries against a table and fields with capital letters in a PostgreSQL database.

**Comment by xrmx** [comment]
Please if you found the same bug no need to open a new one, just subscribe to the other one. If you have more information than the one already reported just update it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 307 days. Feel free to comment and request for this issue to be reopened.
