### ISSUE TITLE
Adding D3.Js charts  

### ISSUE THREAD

**Issue by chandupydev** [apache/incubator-superset#3003]
Hello everyone,
I would like to add all d3.js charts into superset. can anyone guide me how to do that like in case of any changes required in Redux on which I don't have enough knowledge about. Or simply changes in viz.py is enough. Looking fwd to take  quick move from here.  

Any thoughts. Please comment here :100:

**Comment by xrmx** [comment]
See the answer here
https://github.com/airbnb/superset/issues/2962

**Comment by SalehHindi** [comment]
Here (https://github.com/airbnb/superset/commit/b308a3eb4eb08de39edbff6490c06a6bef7b7ce1) is a commit where someone added the country map visualization. Probably the most important changes to observe are in `country_map.js`, `country_map.css`, 'main.js', and `viz.py`. If you want to add a specific visualization, I'd be willing to work with you but trying to add _all_ of the charts seems pretty ambitious.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 307 days. Feel free to comment and request for this issue to be reopened.

**Comment by pulinpathneja** [comment]
i need to add the following chart and superset documentation doesn't tell me much.
https://bl.ocks.org/arpitnarechania/caeba2e6579900ea12cb2a4eb157ce74

**Comment by cs-chandu** [comment]
Hi @SalehHindi 

I would like to work with you on bringing some custom Viz components into superset. How can I contact you ?
