### ISSUE TITLE
Possibility to execute a query ONLY if a filter is set ?

### ISSUE THREAD

**Issue by DylanCa** [apache/incubator-superset#3004]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

 0.18.4

### Expected results 

I've set a filter slice in order to filter a whole dashboard at once, but I need the other slices to execute themselves only if a filter is set, because there's (700*(12*10)*20)*12 records if I just run the query without any filter.

### Actual results 

No filter set at first,  (700*(12*10)*20)*12 records, huge loading time

**Comment by xrmx** [comment]
You can hack something possibly by adding a flag to the slice and then sort out how to return an error if there's not filter set in the ui. Anyway 20M rows shouldn't be something that a machine can't handle.

**Comment by DylanCa** [comment]
Yes, that's the point. If I set a filter, it goes from 20M to 250 rows, which is way better. And the point is I can't even save the query in order to do anything with it, since Superset can't fetch the data from it.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 306 days. Feel free to comment and request for this issue to be reopened.
