### ISSUE TITLE
[explore] Filtering on int or numeric column: 'list' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3005]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.4, with ProstgreSQL as both superset management DB and data warehouse.

### Expected results
Queries with applied filters on values of columns of type integer or numeric work.

### Actual results
The query fails with the following Traceback:
```
Traceback (most recent call last):
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/viz.py", line 238, in get_payload
    df = self.get_df()
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/viz.py", line 78, in get_df
    self.results = self.datasource.query(query_obj)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/connectors/sqla/models.py", line 550, in query
    sql = self.get_query_str(query_obj)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/connectors/sqla/models.py", line 322, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/connectors/sqla/models.py", line 481, in get_sqla_query
    eq = utils.string_to_num(flt['val'])
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/utils.py", line 149, in string_to_num
    if s.isdigit():
AttributeError: 'list' object has no attribute 'isdigit'
```

This behavior was _not_ present in superset==0.18.2.

I suspect #2908 and/or #2671 to be the culprit.

### Steps to reproduce
Apply a filter on a numeric or integer column and run the query.

I don't know, however, to which extent this issue is specific to the ProstgreSQL DB backend.

**Comment by rumbin** [comment]
## Possible fix (?)

In utils.py, function string_to_num, there is the following test included:
```
     if isinstance(s, (int, float)):
        return s
```
If we add just another test for numeric lists, everything seems to work again:
```
    if type(s) is list and all(isinstance(i, (int, float)) for i in s):
        return s
```

As I do not know if this approach is clean enough and whether to include the test condition into the existing test on scalar (int, float), I would appreciate if a more experienced user could step in…

**Comment by rumbin** [comment]
I noticed that there may also be lists of strings, e.g. for timestamps (without timezone).
For this reason, my suggestion for the string_to_num function is as follows:

```
def string_to_num(s):
    """Converts a string to an int/float

    Returns ``None`` if it can't be converted

    >>> string_to_num('5')
    5
    >>> string_to_num('5.2')
    5.2
    >>> string_to_num(10)
    10
    >>> string_to_num(10.1)
    10.1
    >>> string_to_num('this is not a string') is None
    True
    """
    if isinstance(s, (int, float)) or (type(s) is list and all(isinstance(i, (int, float)) for i in s)):
        return s
    if type(s) is list:
        if all(i.isdigit() for i in s):
            return [int(i) for i in s]
        try:
            return [float(i) for i in s]
        except ValueError:
            return None
    else:
        if s.isdigit():
            return int(s)
        try:
            return float(s)
        except ValueError:
            return None
```

@mistercrunch Could you please step in, as I'm not sure if any of this makes sense? Especially, I am generally confused, why in my case `s` always seems to be of type list , while tghe existing code just expects single values and why it doesn`t seem to do any harm in the further processing of the data.

**Comment by Mark-uiojxx** [comment]
I've also had this problem. Have you solved it? @rumbin

**Comment by Mark-uiojxx** [comment]
@rumbin MySQL.Sorry for late reply!

**Comment by rumbin** [comment]
In superset 0.18.5 the bug seems to be gone again. I tested it in a clean venv.
However, I do not know which commit actually fixed the issue.

@Mark-uiojxx Can I close the issue, or do you still encounter problems using the recent release?

**Comment by Mark-uiojxx** [comment]
@rumbin OK
