### ISSUE TITLE
[explore, PostgreSQL] filter values not correctly displayed for boolean columns

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3007]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I mentioned this behavior in #2814 but since this is a Postgres-specific issue, I guess it's best to file a new issue.

### Superset version
0.18.4 in combination with Postgres as DB backend

### Expected results
The drop down selector shows both existing states (false/true or 0/1) of a boolean column, allowing to select the value to be filtered on — assuming that the column actually features both states.

### Actual results
In both kinds of filtering mechanisms — within a filter slice and using filters on the explore page — the drop-down selector for the boolean column shows two rows, however, they are both not labeled.
Selecting either of them results in the corresponding filters on false or true applied, though.
So it seems that this is only an issue regarding the representation of the column values.

The following picture depicts the empty label string that is yielded if any of the values is selected for filtering.

![bool_filter_postgres](https://user-images.githubusercontent.com/1220356/27351395-823b7f9a-55fd-11e7-84cc-f50efef09994.PNG)

When doing the same with an SQLite backend, the drop-down list is correctly populated with 0 and 1.

I got the idea that the difference between SQLite's and Postgres' boolean types is that the former uses 0 and 1 as representation, while the latter employs false and true. So maybe it's all about casting these values to the strings that get printed in the selector list.

### Steps to reproduce
For simplicity, we just employ the data stored in superset's management DB, which we assume to be running on Prostgres:

* register the superset maintenance table main.ab_user in superset
* make the `active` column filterable
* create a filter slice using this column and try to select any of the available values of the drop-down selector for this field
* you may want to make sure that there are both active and non-active users present, so you get two distinct but unlabeled values in the drop-down selector

**Comment by rumbin** [comment]
Some debugging:

Talking about superset/connectors/sqla/models.py, around line 454.

The values and dtypes of the filter values _col_, _op_ and _eq_ are as follows, when a filter on a boolean column is applied:

* col: active, str
* op: in, str (to no surprise)
* eq: [False], list
* eq[0]: False, bool

So, as observed in the query results, the values are handled correctly.
However, I currently have not figured out yet, where the contents of the drop-down selectors are generated...

**Comment by rumbin** [comment]
@mistercrunch, @xrmx: Could anyone of you give me a hint, please? I actually don't know where to start digging.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 281 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen.

**Comment by mistercrunch** [comment]
This should actually be fixed since https://github.com/apache/incubator-superset/pull/4651

**Comment by brunoalano** [comment]
I've the same issue

**Comment by ecastillopki** [comment]
> 
> 
> This should actually be fixed since #4651

I'm having the same issue but with mssql DB.

**Comment by jotarada** [comment]
Hi,
This issue as mention in #2814 still exists for Impala. The drop down and tables for a boolean column appears as blanks.
I'm using impala 3.2 with superset 0.36

**Comment by bkyryliuk** [comment]
yeah same on presto for 0.37
