### ISSUE TITLE
Dashboard Filters

### ISSUE THREAD

**Issue by TheCannings** [apache/incubator-superset#3015]
When you add a dashboard filter visualization it works fantastically at filtering, however it doesn't filter itself, so if you have multiple fields, once you select a filter on a parent field, the child fields should only show available results from your filtered dataset instead of still showing the full dataset which then can result in no data for your slices.

**Comment by kelchm** [comment]
Just to add to this -- resizing the browser window after applying a filter will cause the **Filter Box** to re-render and only display the relevant subset of options in the other filters.

I think one of the issues that would be encountered here, particularly with Instant Filtering enabled, would be that further input from the user would be blocked after each selection.

**Comment by TheCannings** [comment]
ahh good spot I didn't notice that on the resize.

**Comment by mistercrunch** [comment]
We need to address all this more explicitly. The behavior that @kelchm described is a bug as far as I'm concerned. In the meantime, to fix that, you can add the slice_id of your filter box to the `filter_immune_slice_fields` as described here:
http://airbnb.io/superset/faq.html#how-to-add-dynamic-filters-to-a-dashboard

Until we improve FilberBox to allow for explicitly define "cascading filters", you can do so by using the features described in the link above. For instance you can have 2 "Filter Box" and have the first one immune to filters issued from the second one. This may not provide the layout you want but it works...

**Comment by TheCannings** [comment]
Ahh your comment also made me realise i'm dumb for putting all my filter fields in one filter box, by having a separate field in each separate slicer it works like I was aiming for, it just looks ugly lol

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 293 days. Feel free to comment and request for this issue to be reopened.

**Comment by junlincc** [comment]
#12148
dashboard native filter and cascading filter are available for testing!! thanks in advance for feedback, comments, critics, love and support!!
