### ISSUE TITLE
How move chart, edit chart, remove chart buttons are added on every chart of react?? Can anyone explain ?? 

### ISSUE THREAD

**Issue by Subhash9325** [apache/incubator-superset#3026]
Make sure these boxes are checked before submitting your issue - thank you!

- [+] I have checked the superset logs for python stacktraces and included it here as text if any
- [+] I have reproduced the issue with at least the latest released version of superset
- [+] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 304 days. Feel free to comment and request for this issue to be reopened.
