### ISSUE TITLE
Timestamp columns now displayed as epoch time

### ISSUE THREAD

**Issue by kelchm** [apache/incubator-superset#3027]
### Superset version
v0.18.5

### Expected results
Previously, timestamps were displayed in ISO8601 format. Example: 2017-06-20T02:18:26.717000

### Actual results
After updating to v0.18.5, timestamp columns are now displayed in epoch time in milliseconds.

### Steps to reproduce
I'm using a MSSQL table with a timestamp2 column. Simple create a table view slice that includes this column as one of the "NOT GROUPED BY" columns.

**Comment by xrmx** [comment]
Updating from which version?

**Comment by JImBurris** [comment]
same issue. Upgraded from  v0.18.4

**Comment by RichRadics** [comment]
I also see this issue when using a DATETIME column in the "Group by" list on 0.18.5

**Comment by johnatgh** [comment]
@mistercrunch @RichRadics I was also able to reproduce this in 0.18.5 and 0.19.0 (from pip) by using a DATETIME in the GROUP BY and without "NOT GROUPED BY". Can you please reconsider reopening this issue?

**Comment by rohanagg** [comment]
Is the issue is resolved ?

**Comment by suneet-pit** [comment]
Is the  issue resolved?

**Comment by FedericoCalonge** [comment]
Is the issue resolved?

**Comment by villebro** [comment]
TO my knowledge yes - feel free to open a new ticket if this is not the case, either latest stable release (1.0.1) or master branch.
