### ISSUE TITLE
graph in slice does not refresh at window resize

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#3028]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

The graph will refresh after a resize to take all the space available

### Actual results

Graph takes the same size as first draw

![no-repaint-on-resize](https://user-images.githubusercontent.com/12932/27485353-b28c8032-582c-11e7-9c71-972c916ca35b.png)

### Steps to reproduce

- Open a slice with the browser screen not full screen
- resize the window full screen

**Comment by xrmx** [comment]
I see there's already an implementation for the slice, any hint on where the slice is initialized in the explorer view?

**Comment by xrmx** [comment]
Something like this, completely untested, building atm:

```
diff --git a/superset/assets/javascripts/explore/components/ChartContainer.jsx b/superset/assets/javascripts/explore/components/ChartContainer.jsx
index f6da5388..dcd6f22f 100644
--- a/superset/assets/javascripts/explore/components/ChartContainer.jsx
+++ b/superset/assets/javascripts/explore/components/ChartContainer.jsx
@@ -52,6 +52,7 @@ class ChartContainer extends React.PureComponent {
       selector: `#${props.containerId}`,
       showStackTrace: false,
     };
+    this.props.slice.bindResizeToWindowResize();
   }
 
   componentDidUpdate(prevProps) {
```

**Comment by vagish1101** [comment]
Not working after browser resize
