### ISSUE TITLE
Feature Request: Display Label+Percentage in Pie Charts

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#3048]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

As of now, options in Pie chart are 
![image](https://user-images.githubusercontent.com/391567/27599600-1fdc4e4e-5b1e-11e7-9b26-72ecb1546090.png)
When the percentage is selected, It's harder to correlate the corresponding label with the legend. 
![image](https://user-images.githubusercontent.com/391567/27599736-8ea696fe-5b1e-11e7-9cb0-6f2335a11052.png)

It would be nice to display Label + % 

**Related question, can we also have an option to display percentages in Table View?**

**Comment by crazywlof** [comment]
How to percentage to retain double digits?thanks
