### ISSUE TITLE
Debug exception message not visible

### ISSUE THREAD

**Issue by prihoda** [apache/incubator-superset#305]
Hey, I was confused that I cannot see any exception message when debugging and I noticed it's white text on white background:

![whiteerror](https://cloud.githubusercontent.com/assets/2894124/14403168/90ea8d3c-fe4d-11e5-8cd2-6c3b63f0daba.jpg)

I think it can be solved by adding:
div.debugger div.traceback blockquote {
    color: #ff4146;
    padding-left: 1em;
}

I don't want to mess with your CSS :)

**Comment by sid88in** [comment]
@prihoda Ideally we don't want to see these exceptions on the UI. We should log them on console and show a pop up on the UI. I believe @williaster pushed a similar fix in another PR merged 6 days ago.

https://github.com/airbnb/caravel/commit/92f73b67ca1c6f486961962c796128f38320c3b8
Do you think we can make similar fix for this?
