### ISSUE TITLE
firefox  nav <b> position go wrong 

### ISSUE THREAD

**Issue by gzponline** [apache/incubator-superset#3054]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
17.06

### Expected results
![image](https://user-images.githubusercontent.com/12186221/27625703-12a6a3d2-5c18-11e7-9ac7-22dbf0c06795.png)
Firefox same as Chrome

### Actual results
Firefox
![image](https://user-images.githubusercontent.com/12186221/27625755-34830dec-5c18-11e7-8391-b4da8826161a.png)

### Steps to reproduce

Ｉ change the css of "b" class caret and replace the " display: inline-block" and  " margin-top : 24px" to" display: inline" ,   so problem has solved but I do not know why set "diaplay:inline-block" before and I not find where this style set , only find it in chrome dev tools so I set  "display: inline" to  cover old. but  I not find this bootswatch.less in github. why???

**Comment by xrmx** [comment]
I think this is flask-appbuilder and not superset. Also 17.06 is not a superset version...

**Comment by gzponline** [comment]
@xrmx  oh  .........0.17.06......sorry

**Comment by gzponline** [comment]
@xrmx  but this file also not find in flask-appbuilder  
path is ==> 
 /usr/local/lib/python2.7/dist-packages/superset/static/assets/stylesheets/less/cosmo/bootswatch.less

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 298 days. Feel free to comment and request for this issue to be reopened.
