### ISSUE TITLE
[Feature request] Provide option to run superset as a daemon or service

### ISSUE THREAD

**Issue by wei-hai** [apache/incubator-superset#3057]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

1. Run superset in daemon mode, for example `superset runserver -p 8088 -b` in which `-b` means background, and also provide command to stop the daemon, for example, `superset stopserver`
2. Run superset as a service in linux, `service superset start|stop|restart`
3. When running in foreground mode, make it work with supervisord. I tried to manage it with supervisord, and failed to kill the process when running `supervisorctl stop superset`, please help.

**Comment by xrmx** [comment]
1. why add more code when the init systems already handle that?
2. you can already do that now by adding proper configuration to your init system
3. superset behaves exactly like any other flask / gunicorn app out there, i suspect there's plenty of documentation on how to handle it.

**Comment by mistercrunch** [comment]
Most companies are opinionated about how to do that so it's hard to please everyone.

**Comment by fuzaro** [comment]
Take a look at :
https://github.com/apache/incubator-superset/issues/2123#issuecomment-305240815
