### ISSUE TITLE
[sqllab] query table with wildcard like '%中文%' with Chinese characters （applied to any unicode？）

### ISSUE THREAD

**Issue by STILLSHI** [apache/incubator-superset#3062]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"version": "0.18.5", "GIT_SHA": ""}
python3.5
mysql: 5.7.18-0ubuntu0.16.04.1

### Expected results
the result of the sql query should be:

中文字段1,中文字段2,中文字段3
1,1,zh中文
2,2,zh中文中文

### Actual results
unsupported format character 'z' (0x7a) at index 38

however, if you are using '=' instead of 'like'. everything works fine.

### Steps to reproduce
#table structure
create table ZYDB2.中文表名
(
	中文字段1 int null,
	中文字段2 int null,
	中文字段3 varchar(80) null
)
;
##value:
 中文字段1,中文字段2,中文字段3
1,1,zh中文
2,2,zh中文中文

add datasource in superset:
mysql://still2:XXXXXXXXXX@ipaddr/ZYDB2?charset=utf8

then run:

SELECT *
FROM 中文表名 where 中文字段3 like '%zh中文%'

**Comment by xrmx** [comment]
Full stacktrace please.

**Comment by STILLSHI** [comment]
Hi xrmx,

sorry I don't know where exactly can i find the stacktrace by looking through the google results. so i switched the mode to -d and here are the output on the console, hope this helps:

2017-06-30 16:44:59,994:INFO:root:Set query to 'running'
2017-06-30 16:45:00,007:INFO:root:Running query: 
SELECT *
FROM 中文表名 where 中文字段3 like '%zh中文%'
2017-06-30 16:45:00,008:INFO:root:SELECT *
FROM 中文表名 where 中文字段3 like '%zh中文%'
2017-06-30 16:45:00,008:ERROR:root:unsupported format character 'z' (0x7a) at index 38
Traceback (most recent call last):
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_lab.py", line 180, in execute_sql
    query.executed_sql, **db_engine_spec.cursor_execute_kwargs)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 238, in execute
    query = query % args
ValueError: unsupported format character 'z' (0x7a) at index 38
2017-06-30 16:45:00,057:INFO:werkzeug:104.237.91.133 - - [30/Jun/2017 16:45:00] "POST /superset/sql_json/ HTTP/1.1" 500 -

**Comment by asdf2014** [comment]
Hi, @STILLSHI. It's due to `django.db.backends.sqlite3.base.SQLiteCursorWrapper`, maybe you should try `%%zh` instead of `%zh`.

**Comment by STILLSHI** [comment]
@asdf2014 thank you for your advice. I tried with '%%中文%' but no luck.

**Comment by asdf2014** [comment]
@STILLSHI Okay, could you please show some new log messages in comment?

**Comment by STILLSHI** [comment]
@asdf2014, sorry I should provide log earlier. here is the log:

2017-07-03 13:38:55,693:INFO:root:Running query: 
select * from 中文表名 where 中文字段3 like '%%zh中文%'
2017-07-03 13:38:55,693:INFO:root:select * from 中文表名 where 中文字段3 like '%%zh中文%'
2017-07-03 13:38:55,694:ERROR:root:unsupported format character ''' (0x27) at index 44
Traceback (most recent call last):
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_lab.py", line 180, in execute_sql
    query.executed_sql, **db_engine_spec.cursor_execute_kwargs)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 238, in execute
    query = query % args
ValueError: unsupported format character ''' (0x27) at index 44

**Comment by STILLSHI** [comment]
I have added 2 lines to print query and args: here is the output

2017-07-03 14:00:33,669:INFO:root:Parsing with sqlparse statement select * from 中文表名 where 中文字段3 like '%%zh中文%'
2017-07-03 14:00:33,684:INFO:root:Set query to 'running'
======query=======
SHOW VARIABLES LIKE 'sql_mode'
======args========
()
======query=======
SELECT DATABASE()
======args========
()
======query=======
show collation where `Charset` = 'utf8' and `Collation` = 'utf8_bin'
======args========
()
======query=======
SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
======args========
()
======query=======
SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
======args========
()
======query=======
SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8) COLLATE utf8_bin AS anon_1
======args========
()
2017-07-03 14:00:33,698:INFO:root:Running query: 
select * from 中文表名 where 中文字段3 like '%%zh中文%'
2017-07-03 14:00:33,698:INFO:root:select * from 中文表名 where 中文字段3 like '%%zh中文%'
======query=======
select * from 中文表名 where 中文字段3 like '%%zh中文%'
======args========
{}
2017-07-03 14:00:33,699:ERROR:root:unsupported format character ''' (0x27) at index 44
Traceback (most recent call last):
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_lab.py", line 180, in execute_sql
    query.executed_sql, **db_engine_spec.cursor_execute_kwargs)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 242, in execute
    query = query % args
ValueError: unsupported format character ''' (0x27) at index 44

**Comment by asdf2014** [comment]
@STILLSHI You see, the error message is changed into `unsupported format character ''' (0x27)`. Then you do not realize that this new log message is telling us that should change the `'%%zh中文%'` into `'%%zh中文%%'`?

**Comment by asdf2014** [comment]
@STILLSHI Actually, we shouldn't use the chinese as the name of database tables, because it will bring too many problems and looks not professional ;)

**Comment by STILLSHI** [comment]
@asdf2014 it is very embarrassing that I have missed the matching %...  
yes, I can't agree more that people should use ascii letters only for table names for maximum compatibility. 
Thank you very much. I think so far we have a solution for this "issue".

best regards
Still.

**Comment by asdf2014** [comment]
@STILLSHI You are welcome :D

**Comment by lynnfi** [comment]
@STILLSHI @asdf2014  Hi，I meet  a problem about Chinese charset . when I query a table, if it has Chinese word, it can`t display correctly. Just Like This:
id   name   pid
1      ??      89
2    ????    1407
3    ????    3769

I don`t know how to solve this problem, do you have any idea, thanks~

**Comment by john-bodley** [comment]
Note I think SQL Lab has an issue rendering UTF-8 characters in the results table, i.e., `SELECT '中文'` returns `??` regardless of database.

**Comment by john-bodley** [comment]
@lynnfi can you check what the character encoding is for the query table?

**Comment by jackpgao** [comment]
@lynnfi,  use MySQL like this 'mysql://superset:XXXXXXXXXX@mysql:3306/superset?charset=utf8' may solve you problem.

**Comment by lynnfi** [comment]
@jackpgao @john-bodley thanks for help,I have solved this problem by changing the character encoding.
I edit the connection Extra setting, add something like below:
{
    "metadata_params": {},
    "engine_params": {"connect_args": { "charset": "utf8" }}
}
and the character display is ok.
Thanks again, have a nice day~

**Comment by lynnfi** [comment]
@jackpgao your method may also work well~
