### ISSUE TITLE
How to make the translation take effect?

### ISSUE THREAD

**Issue by wei-hai** [apache/incubator-superset#3068]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

I checked the messages.po file under translations/zh/LC_MESSAGES and I found that there are more translated strings than what I see in the latest release, so how to make the translation in messages.po or messages.mo files take effect when I build and run the server?

**Comment by akfdgg** [comment]
1、download the .mo .po file and remove it under the superset dir

2、under the superset dir:mkdir -p translations/zh/LC_MESSAGES 

3、Finally I run $ pybabel compile -d translations. This generate the /tranlations/zh_CN/LC_MESSAGES/messages.mo successfully.

have a try!
thank you.

**Comment by wei-hai** [comment]
@akfdgg Can you be more specific? Why do you remove the .mo and .po files at step 1 and re-generate them at step 3?

**Comment by karkhaneei** [comment]
See, this page https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#translations
