### ISSUE TITLE
Ability to set default dashboard filters

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#3071]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version  0.18.5

Is there anyway by which I Can set default values for the filter box on superset dashboard? Is there a parameter available in dashboard JSON metadata to do this?

Thanks.

**Comment by LeeSanity** [comment]
I want to know this too.

**Comment by macfly1202** [comment]
I've got the same question. thanks

**Comment by xrmx** [comment]
@LeeSanity @macfly1202 subscribe to the issue or use the gihub reactions, please don't spam with "me too" messages

**Comment by vibinsv09** [comment]
This will be useful if we can define it in the JSON metadata where we can add preselect_filters and hence define default filter set.

**Comment by mistercrunch** [comment]
@vibinsv09 you're right, it should be easy to squeeze that feature into the dashboard's JSON metadata as `default_filter` or something

**Comment by vibinsv09** [comment]
resolved with #3183 
Thanks you 👍

**Comment by ashish1807** [comment]
@mistercrunch how we can edit dashboard's JSON metadata and where to find it?
