### ISSUE TITLE
[sql lab] add ability to schedule queries

### ISSUE THREAD

**Issue by masterlittle** [apache/incubator-superset#3078]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Could you please be more verbose about your use case?

**Comment by masterlittle** [comment]
So, I was thinking that maybe we could schedule the queries at regular intervals so that whenever I see the result of these queries after some time it is always updated. i.e- I don't have to manually run my queries every time that I want to see the result of the query.  Espaecially for regular rerunning queries.

**Comment by manishkhorgade** [comment]
Hi, we are also interested in this feature. Any updates on this?

**Comment by mistercrunch** [comment]
It looks like this feature may make it into Lyft's Q2 roadmap. It's likely that the approach is going to focus on collecting scheduling requirement metadata from users leveraging FAB's CRUD, and exposing that to an orchestrator (in our case Apache Airflow) through a JSON endpoint.

Information gathered from user:
* saved query code
* schedule interval / cron statement
* dependencies (partitioned tables we should wait for, if any, other scheduled queries)
* scheduled until (we not allow users to set that too far in the future, forcing them to push a button to re-schedule their query, trying to prevent abuse / accumulation of useless compute)
* ...

**Comment by mmuru** [comment]
@mistercrunch: Is there PR for this? Any updates on this?

**Comment by manishkhorgade** [comment]
This is great! Does 'this quarter' mean by the end of June? We are working on a feature and would love to have this by end f June.

**Comment by manishkhorgade** [comment]
Thanks, @mistercrunch.

**Comment by manishkhorgade** [comment]
Any updates on this?

**Comment by mistercrunch** [comment]
It's still on the roadmap, haven't made progress at this point in time.

**Comment by sivaprakashkollana** [comment]
@mistercrunch Can we expect this feature anytime soon

**Comment by CoryChaplin** [comment]
👍 would love it

**Comment by mistercrunch** [comment]
Still on the roadmap, lots going on...

**Comment by lokeshlal** [comment]
Hello, any update on this feature. Planning to use superset as an alternate to other cep engines on top of druid.

Thanks

**Comment by Andrew-Tan** [comment]
+1
Another use case for this query is, for query engines that make use of Hive and leveraging data partitioning, `MSCK REPAIR TABLE` needs to be executed on a scheduled basis to ask Hive to import new data.

For example, AWS Athena: https://docs.aws.amazon.com/athena/latest/ug/msck-repair-table.html
