### ISSUE TITLE
how to clustering superset

### ISSUE THREAD

**Issue by kym498** [apache/incubator-superset#3080]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

There are two server redhat os I want to try a distributed processing by clustering the superset.
Is there a way to configure it?

### Superset version
superset 0.18.5
 python 2.7

**Comment by desavera** [comment]
Use a Presto cluster

Em 04/07/2017 23:51, "kym498" <notifications@github.com> escreveu:

**Comment by xrmx** [comment]
What do you want to cluster?

**Comment by kym498** [comment]
I resolve issues sharing setting config.py  (Configuration behind a load balancer)
Thanks
