### ISSUE TITLE
[permissions] database_access does not grant access to datasources

### ISSUE THREAD

**Issue by pajachiet** [apache/incubator-superset#3085]
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
From the [documentation](http://superset.incubator.apache.org/security.html#permissions) _"Granting access to a database allows for the user to access all data sources within that database"_

- a _database_access on [DATABASE].(id:DB_ID)_ permission should exists
- when granting this permission to a Gamma user, it should give him access to all data sources within that database (hence tables, slices and dashboards based on this database)

### Actual results
- The _database_access on [DATABASE].(id:DB_ID)_ permission does not exits, except for _main_ database
- When creating it and granting it to a Gamma user, it gives him access to the database in SQL Lab, but does not give him access to data sources within that database (slices/dashboards).
- a data**source**_access on [DATABASE].(id:DB_ID) exists, but it does not seems to work

### Steps to reproduce
- Create a database
- Add a role and look for permission _database_access on [DATABASE].(id:DB_ID)_ => it does not exists
- Create this permission programatically in Superset Backend, with the following query on SQL Lab ('Allow DML' on main database before hand)

INSERT INTO ab_permission_view (permission_id, view_menu_id)
    SELECT ab_permission.id, ab_view_menu.id
    FROM 
        ab_permission,
        dbs  LEFT JOIN ab_view_menu ON ab_view_menu.name = dbs.perm
        WHERE 
            ab_permission.name = 'database_access' AND
            NOT ((ab_permission.id, ab_view_menu.id) IN (SELECT permission_id, view_menu_id FROM ab_permission_view))

- Add a role with this newly created permission. Add this role to a Gamma user
- Create tables, slices and dashboard based on this database (or import dashboards from a .pickle)
- Log as the Gamma user => it does not have access to tables, slices and dashboards from the database. 
- Add sql_lab to your Gamma user => the database_acces gives him access to the database in SQL Lab

### Temporary hack
We created a script [gist](https://gist.github.com/pajachiet/62eb85805cee55053d208521e0bdaf13#file-init_superset_user_role-py) that create a role for each database with 
- the database_access on it (for SQL lab), 
- datasource access on all tables based on it.

This script also add this role to users, as defined in an external csv file with header _email;roles_, roles being comma ',' separated. Cf this other issue https://github.com/apache/incubator-superset/issues/3083, with a script that creates users based on the same CSV file.

Another related issue https://github.com/apache/incubator-superset/issues/3084 with scripting on Superset backend

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.

**Comment by yamyamyuo** [comment]
Do you have plans to do datasource access control on catalog / schema level? @mistercrunch 
It is highly useful when controlling permissions. I don't need to grant all datasource access to many people and if I have highly secure data then I can put it to other schema.

**Comment by pbr0ck3r** [comment]
@pajachiet can confirm this issue. Any user can return all database names and ids. Even if they don't have a role for database access.
