### ISSUE TITLE
Superset tutorial documentation page images are mislinked

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3089]
https://github.com/apache/incubator-superset/blob/master/docs/tutorial.rst
https://github.com/apache/incubator-superset/blob/master/docs/gallery.rst
https://github.com/apache/incubator-superset/blob/master/docs/index.rst

### Actual results
<img width="1317" alt="screen shot 2017-07-05 at 3 24 36 pm" src="https://user-images.githubusercontent.com/27990562/27887558-239d8d30-6196-11e7-96d7-dc5933881ac5.png">

**Comment by markderry** [comment]
Should this be merged with #1846

**Comment by mistercrunch** [comment]
those rst files are the source code that power this:
http://superset.apache.org/tutorial.html

It just happens that github tries to generate it.

There's most likely a way to set up the rst so that both the html and the rst files on github look good
