### ISSUE TITLE
[header] Superset landing page and logo link

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3090]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Should redesign the target page for default landing page /,  clicking on Superset logo, and Profile link in the header.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.

**Comment by LeonanCarvalho** [comment]
This issue still happens with the current master branch, 
The superset logo link redirects to profile page, which is empty if the access is anonymous.
```
http://localhost:8080/superset/profile//
```
It should redirect to the main page or something else instead.

![image](https://user-images.githubusercontent.com/3593706/63527137-eb39f400-c4d6-11e9-89ed-de583b29d843.png)
