### ISSUE TITLE
[Add Dashboard] Loading all available slices from dropdown

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3091]
### Superset version
0.18.5

In Add Dashboard view, click on Slices dropdown list to choose slice to add into new dashboard:

### Expected results
probably first display slices owned by the same user, which should be true in most cases?

### Actual results
Too many slices to load, cause browser hanging.

### Steps to reproduce
![screen shot 2017-07-05 at 4 40 33 pm](https://user-images.githubusercontent.com/27990562/27889395-00c20420-61a1-11e7-81be-34b623057c8f.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.
