### ISSUE TITLE
[Dashboard] Create new slice in adding-slice-to-dashboard flow

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3092]
### Superset version
0.18.5

### Expected results
Currently only allow to add existing slices to dashboard, would be convenient to allow both create and add a new slice to dashboard, otherwise, users need to switch between “Slices” and “Dashboards” back and force

### Steps to reproduce

<img width="1152" alt="screen shot 2017-07-05 at 4 54 41 pm" src="https://user-images.githubusercontent.com/27990562/27889700-be1e4c44-61a2-11e7-8f4c-a49fd32a7391.png">

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.
