### ISSUE TITLE
[Dashboard] After done editting chart, should go back to current dashboard

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3093]
### Superset version
0.18.5

In any dashboard view, click “Edit chart”, making some changes and clicking “Save”. 
### Expected results
it goes to the dashboard list view

### Actual results
going back to the current dashboard

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.
