### ISSUE TITLE
[Dashboard] After done exploring chart, should go back to current dashboard

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3094]
### Superset version
0.18.5

In any dashboard view, click “Explore chart”. making some changes and clicking “Save” (overwrite and save).

### Expected results
going back to the current dashboard

### Actual results
it will reload the page but still stay in the “explore chart” page

**Comment by jfeng15** [comment]
love this!  thanks for creating an issue for this @graceguo-supercat - this issue has bugged me for months

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 291 days. Feel free to comment and request for this issue to be reopened.
