### ISSUE TITLE
how to change list table column property by default?

### ISSUE THREAD

**Issue by kym498** [apache/incubator-superset#3096]
Make sure these boxes are checked before submitting your issue - thank you!

- [* ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ *] I have reproduced the issue with at least the latest released version of superset
- [ *] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset 0.18.5
python 2.7

###
It is used by connecting superset and redshift.
When you import the table from redshift, it automatically displays the "column name" and "type" in the list table column. Can I make all of the other items groupable, filterable, sum, min, max .. all checked by default?

![superset_sample](https://user-images.githubusercontent.com/29906677/27896888-d3251bee-6257-11e7-8517-9b05bb8d2114.png)

Where does "count distinct" field affect?
As you look through the items in the table view, you can not see anything different about checking with count distinct.

**Comment by xrmx** [comment]
You really want to control what your user can do on the platform. Since this is a one time configuration you do when adding the datasource i don't see it as particularly costly. BTW you screenshotted only varchar where sum, min, max does not make any sense.
