### ISSUE TITLE
how to superset loadbanlancing when multiple users connect..?

### ISSUE THREAD

**Issue by kym498** [apache/incubator-superset#3097]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### 

I  installed the superset on one server(redhat os ) and connecting to redshift to perform a query.
I superseded that superset server might be slow when several users connect and use ... 
Is there a way to install superset on multiple servers and load balancing when users connect?

**Comment by xrmx** [comment]
Am pretty sure nobody is holding you to install superset on multiple server and put a load balancer before them. Please close this and #3080 since they are 1) not issues 2) duplicated.

**Comment by kym498** [comment]
reading after Configuration behind a load balancer , I resolve issues

**Comment by Neeraj0506** [comment]
can we scaleout the apache superset one single node server to multi node.

**Comment by akshay-aggarwal** [comment]
In a multi-server deployment, will the ELB have to support sticky-ness? And if my ELB doesn't support sticky-ness, is there a way to configure superset to store sessions in a backend store?
