### ISSUE TITLE
multi language in react

### ISSUE THREAD

**Issue by lxzhangchao** [apache/incubator-superset#3098]
Make sure these boxes are checked before submitting your issue - thank you!

- [ √] I have checked the superset logs for python stacktraces and included it here as text if any
- [ √] I have reproduced the issue with at least the latest released version of superset
- [√ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
multi language in react

### Actual results
multi language in react

I have use react-intl-universal to improve multi language in react page.you can see Pull request #3082.

**Comment by xrmx** [comment]
No need to open a a new issue for your PR, please close.
