### ISSUE TITLE
Sorting by Slice Name in Slice Model View Causes 500 Server Error

### ISSUE THREAD

**Issue by gene-telligent** [apache/incubator-superset#3100]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5 (MySQL Backend)

### Expected results
Clicking on the "Sort by name" (The arrow next to "Slice" on the Slice Model View) should order the slices by name.

### Actual results
A 500 error is thrown, with the root cause appearing to be:
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'slice_link' in 'order clause'") [SQL: u'SELECT slices.created_on AS slices_created_on, slices.changed_on AS slices_changed_on, slices.id AS slices_id, slices.slice_name AS slices_slice_name, slices.datasource_id AS slices_datasource_id, slices.datasource_type AS slices_datasource_type, slices.datasource_name AS slices_datasource_name, slices.viz_type AS slices_viz_type, slices.params AS slices_params, slices.description AS slices_description, slices.cache_timeout AS slices_cache_timeout, slices.perm AS slices_perm, slices.changed_by_fk AS slices_changed_by_fk, slices.created_by_fk AS slices_created_by_fk \nFROM slices ORDER BY slice_link desc \n LIMIT %s'] [parameters: (100,)]

### Steps to reproduce
In the slice model view, click on either the link "Slices" or the arrow next to it.
The link being used is https://superset-url.com/slicemodelview/list/?_od_SliceModelView=desc&_oc_SliceModelView=slice_link

**Comment by xrmx** [comment]
Looks like a dup of #3074, please close.

**Comment by gloryballet** [comment]
Hi @gene-telligent ,

Try to add "@renders('slice_name')" on method slice_link in class Slice.

Best Regards

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 277 days. Feel free to comment and request for this issue to be reopened.
