### ISSUE TITLE
superset connect to hive

### ISSUE THREAD

**Issue by kym498** [apache/incubator-superset#3106]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset 0.18.5
python 2.7
pyhive latest

### Expected results

connect well to hive
### Actual results
![error1](https://user-images.githubusercontent.com/29906677/28063725-24146780-666d-11e7-858d-bb6456627aa4.PNG)

### Steps to reproduce

After installing superset on  server(RHEL-7.3), I try to connect to another hive server and bring the table
(The redshift connection has already succeeded. slice works well. but the hive connection does not work well.)

I downloaded pyhive latest.
>>telnet ip(hive server) 10000, it is connected.
I configure hiveserver2 in hive server.

Source> Database >create ...write SQLAlchemy URI as hive://ip:10000/default.
Connection error occurs .
![error1](https://user-images.githubusercontent.com/29906677/28063725-24146780-666d-11e7-858d-bb6456627aa4.PNG)

when I connect to hive, I need to insert id and passwd. where can I put id and passwd in SQLAlchemy URI  (hive://ip:10000/default.)

1) Hive://id:passwd@ip:10000
2) hive: //user@host:10000/database

Is there any idea?

**Comment by xrmx** [comment]
One idea would be to look into your hive logs where there's probably more information on why it refuses your login.

**Comment by mistercrunch** [comment]
Related:
https://github.com/dropbox/PyHive/issues/40
