### ISSUE TITLE
ability to plot multiple metrics on same slice

### ISSUE THREAD

**Issue by Gauravshah** [apache/incubator-superset#3108]
Not sure if its the right place. 

Looking for ability to plot more than one metric on the same chart. Its very common to see number of orders vs number of signups on the same chart by day. 
It sounds similar to JOIN but it is slightly different Join is at the event level. Here I am looking for join at the metrics level.

I looked at couple of other issues related to join and it is pointed that we can materialise a view and the make use of superset over the view. But that is not always possible, given that superset is an amazing exploratory tool it hinders Analytics user to be able to explore data in such fashion requiring DBA to create views for each of the things that they want to explore.

Also backend might not support such joins, in our case we are using druid which doesn't support views/JOINS.

**Comment by xrmx** [comment]
I'm pretty sure that we have some kind of visualization that can display more than one metric at once, e.g time series - time chart.

**Comment by Gauravshah** [comment]
thanks @xrmx 
time series & table lets me select 2 metrics yes. But it wouldn't let me select 2 queries.
So lets say sign_ups & orders are two tables then I can't do it.

In our case we have one data source where I can say event_type='order' count(*)== orders
and event_type='sign_up' count(*) == signups. But I couldn't find a way to plot/show this on one slice

**Comment by xrmx** [comment]
Thanks for clarifing, metrics in the slice context means what you call events :)

**Comment by Gauravshah** [comment]
Not sure if I explained it correctly. Lets say we have two data sources in druid "orders" and "signups" and I would like to plot these two by time on a table / graph. I am not sure of a simple way to do it.

**Comment by Gauravshah** [comment]
or lets say I want to plot page_views/active_users

**Comment by Gauravshah** [comment]
In simple terms if My active_users count require no filter and had to count distinct users & I had page views on numerator which I had to couple of filters I could not plot it on one slice.
looking for something like what grafana provides
<img width="1430" alt="screen shot 2017-07-13 at 10 36 57 pm" src="https://user-images.githubusercontent.com/620559/28178394-ef27d7ae-681b-11e7-9285-0fae4707d043.png">

**Comment by mistercrunch** [comment]
No easy solution for this apart from:
* changing your Druid datasource to have the superset of both (or more) datasources 
* showing two different charts one bellow another
* request support for views (or something similar) in Druid

**Comment by Gauravshah** [comment]
Thanks @mistercrunch

**Comment by bondarchukd** [comment]
Hi everyone! What is right decicison of issue of topicstarter?
