### ISSUE TITLE
can not explore data

### ISSUE THREAD

**Issue by stjacob** [apache/incubator-superset#3113]
I deploy superset using default setting and visit the web site via port forwarding. But I can not explore sample data and the layout of dashboard seems broken.

I visited http://127.0.0.1:8088/superset/explore/table/7 and got this:
![default](https://user-images.githubusercontent.com/10614931/28104342-2a61a990-670d-11e7-96a9-07b818100e1b.png)

and the log says:

/home/ad/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'changed_on desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
no manifest file found at /home/ad/anaconda2/lib/python2.7/site-packages/superset/static/assets/dist/manifest.json
2017-07-12 14:15:05,764:INFO:root:[stats_logger] (incr) explore
no manifest file found at /home/ad/anaconda2/lib/python2.7/site-packages/superset/static/assets/dist/manifest.json

help plz

**Comment by fufjvnvnf** [comment]
`cd superset/assets`
`npm install`
`npm run build`

**Comment by stjacob** [comment]
@fufjvnvnf it works for me. Thanks.
