### ISSUE TITLE
"TypeError: null is not an object (evaluating 'd3.event.target')" error thrown to console whenever I click on heatmap

### ISSUE THREAD

**Issue by fufjvnvnf** [apache/incubator-superset#3114]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
No error

### Actual results
TypeError

### Steps to reproduce
Install superset, got to the example `Heatmap` slice, open and click on anywhere on the heatmap, and open your browser's console to view the error.

**Comment by xrmx** [comment]
Full stracktrace from logs please.

**Comment by fufjvnvnf** [comment]
[Error] TypeError: null is not an object (evaluating 'e.event.target')
	g (explore.b6de5de2770a780d469e.entry.js:115:88843)
	o (explore.b6de5de2770a780d469e.entry.js:115:87887)
	show (explore.b6de5de2770a780d469e.entry.js:115:89811)
	（Anonymous Function） (explore.b6de5de2770a780d469e.entry.js:20:21685)

**Comment by xrmx** [comment]
Could you help debug the issue? Like figuring out what line breaks.

**Comment by fufjvnvnf** [comment]
Does it show the same error when you click on the heatmap on your own superset application?

**Comment by fufjvnvnf** [comment]
I copied the entire `heatmap.js` from the official github repo and replaced in my own application, but it still shows the same error.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 284 days. Feel free to comment and request for this issue to be reopened.
