### ISSUE TITLE
Cannot build latest fails with gulp sourcemap error

### ISSUE THREAD

**Issue by nlighteneddesign** [apache/incubator-superset#3115]
Make sure these boxes are checked before submitting your issue - thank you!

- [ * ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ * ] I have reproduced the issue with at least the latest released version of superset
- [ * ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest HEAD

### Expected results
npm install would install superset

### Actual results
npm ERR! fetch failed https://registry.npmjs.org/gulp-sourcemaps/-/gulp-sourcemaps-1.7.0.tgz

### Steps to reproduce
clone repository
`cd incubator-superset/superset/assets`
`npm install`

**Comment by xrmx** [comment]
Uhm, we don't have a dependency on gulp-sourcemaps or use gulp either.

**Comment by nlighteneddesign** [comment]
Looks like it's a subdependency, I am trying to track it down now.

**Comment by xrmx** [comment]
FYI I don't have in in my yarn.lock.

**Comment by sreeramvuppala** [comment]
getting the same on a fresh installation..

**Comment by sreeramvuppala** [comment]
changed the version on these two dependencies
"mapbox-gl": "^0.26.0" - "mapbox-gl": "^0.27.0"
"react-map-gl": "^1.7.0" - "react-map-gl": "^2.0.0".
Now I was able to successfully execute npm install.. I haven't tested the app with these two new versions. 

Just preliminary check. Will check the repos of two libraries above mapbox and uber.

**Comment by STILLSHI** [comment]
@sreeramvuppala 
thanks, how long you finishing running the npm install? it looks forever...

**Comment by nlighteneddesign** [comment]
It took a few minutes the first time.
