### ISSUE TITLE
sql-lab cannot create a visualice

### ISSUE THREAD

**Issue by xiao321** [apache/incubator-superset#3117]
i run the demo in the SQL Lab 

select viz_type,count(*) as num 
from slices 
GROUP BY viz_type

when i click the visualize button , it will alter me the info "creating a datatsource and poping a new tab"
it do not create a view.
why?

**Comment by mistercrunch** [comment]
Any error messages in logs, or javascript console errors?

**Comment by xiao321** [comment]
console error 
sqllab.f6dbd0d….entry.js:29 POST http://192.168.3.123:7777/superset/sqllab_viz/ 400 (BAD REQUEST)

**Comment by xiao321** [comment]
oh , i know where it is wrong

**Comment by nangzi** [comment]
@xiao321 how did you solve this? I met the same problem.

**Comment by chinadiaosi** [comment]
Can you share the solution?It also happened to me......
