### ISSUE TITLE
When adding new database in webui, error occurs said "/lib64/libssl.so.10: version `OPENSSL_1.0.2' not found"

### ISSUE THREAD

**Issue by collinmazb** [apache/incubator-superset#3121]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
should be success to add new database in webui

### Actual results
failed to add new database due to error: "/lib64/libssl.so.10: version `OPENSSL_1.0.2' not found"

### Steps to reproduce
- download superset and its dependencies using pip in another machine
- copy the packages to target machine( which is a customed distribution based on centos, the kernel version is 3.10.104-1)
- create venv(python2.7) and install superset in offline mode(just because the target machine couldn't connect to internet)
- start superset and add new database in webui, and get the error, detailed in attachment. The error can be briefed as when executing the statement  "from cryptography.hazmat.bindings._openssl import ffi as _ffi", there's an import error "ImportError: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /data/home/tbds/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so)". Try much but couldn't find the reason. Also didn't find similar answers in google.

[error.txt](https://github.com/apache/incubator-superset/files/1144670/error.txt)

**Comment by xrmx** [comment]
You have built cryptography for openssl 1.0 but it's not there anymore. Have you upgraded distribution in the mean time? Also unrelated to superset, please close.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 283 days. Feel free to comment and request for this issue to be reopened.
