### ISSUE TITLE
Starting Superset with clickhouse fails

### ISSUE THREAD

**Issue by tobad357** [apache/incubator-superset#3123]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Start Superset connected Clickhouse and it should work

### Actual results
```
2017-07-14 00:01:49,644:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 43 (line 3, col 13): NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
)
```

### Steps to reproduce
Run the Docker Compose setup from here
https://github.com/amancevice/superset/tree/master/examples/postgres

But change the connection string to connect to a Clickhouse DB instance with default username and password.
Connection string we used is 
clickhouse://default:@clickhouse-1.clickhouse.dev.svc.dev-cluster:8123/default

It seems like the setup is running create table which is incompatible with Clickhouse

**Comment by xrmx** [comment]
You can query clickhouse you cannot use it as storage for superset itself. Please close.
