### ISSUE TITLE
Table Timestamp Format not working on version 0.18.5

### ISSUE THREAD

**Issue by Visitante** [apache/incubator-superset#3128]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Table Timestamp Format should be converting dates to appropriate format.

### Actual results
Date is kept on timestamp format. Ex: 1499794560000

### Steps to reproduce
Create a new slice using a datetime column. The datetime column is shown as timestamp even with formating.
There is no errors on the logs or stacktrace.
![image](https://user-images.githubusercontent.com/6034855/28216808-46ca7f44-6889-11e7-895c-dd67be7cd226.png)

**Comment by xrmx** [comment]
Dup of #3027? If so please close.

**Comment by umesh11111** [comment]
Any update on the above issue,even i am facing the same issue in .34 version,i could not able to use the dropdown value
