### ISSUE TITLE
[SQLLab] CSV download row limit set to 1000

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3139]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
CSVs downloaded in SQLLab contain all rows defined by the query. 

### Actual results
Regardless of the row limit set in the SQL statement, the CSVs only contain 1000 rows of data.

### Steps to reproduce
Download the CSV from a query that returns more than 1000 rows and count the number of rows in the resulting CSV.

### Investigation
It seems that QUERY_SEARCH_LIMIT and DISPLAY_SQL_MAX_ROW don't influence this behavior.

**Comment by rumbin** [comment]
It turned out that the behavior was caused by `SQL_MAX_ROW` which at some point after superset 0.15.4 got split into `SQL_MAX_ROW` and `DISPLAY_SQL_MAX_ROW`.

In my custom config I had the former set to 1000 and didn't notice that in more recent versions this is now set in the latter...

**Comment by chengang2** [comment]
Row_Limit
