### ISSUE TITLE
[Explore] row limit of 50000 is implicitly set

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3140]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
The _Row limit_ field reflects the actually set row limit.
![row_limit0](https://user-images.githubusercontent.com/1220356/28246203-f19dd9e8-6a14-11e7-995f-495afe01a232.PNG)
![row_limit1](https://user-images.githubusercontent.com/1220356/28246205-f74bcb70-6a14-11e7-9d12-6ab55fbda011.PNG)

### Actual results
If no _Row limit_ is set, the query still is executed allpying a row limit of 50000.
Imho, the _Row limit_ field should by default be set to 50000, or when no value is entered, then there should be no row limit applied in the query.

**Comment by rumbin** [comment]
OK, the observed limit is caused by the `ROW_LIMIT` parameter from config.py.

From an admin point of view this is pretty much obvious. A user, however, might expect that not selecting any _Row limit_ in Explore leads to no row limit at all.

A clean but maybe rather complex solution would be:

* populate the _Row limit_ selector with only the options up to including `ROW_LIMIT`
* pre-select the `ROW_LIMIT` value in the selector right from the start and enforce that at all times the _Row limit_ field may not be empty.
* Maybe an option: the _Row limit_ field may be chosen empty, if `ROW_LIMIT = None`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 278 days. Feel free to comment and request for this issue to be reopened.

**Comment by CrashLaker** [comment]
#7440 having trouble with it here bacause sybase doesn't accept limit clauses https://stackoverflow.com/questions/1587135/how-do-i-limit-the-amount-of-results-returned-in-sybase

**Comment by mistercrunch** [comment]
Seems like a SQLAlchemy dialect issue

**Comment by hashhar** [comment]
If there can be some consensus from the maintainers about the approaches that can be followed for implementing this - I'll be happy to implement a patch.

**Comment by GregNas** [comment]
Any chance to add an option in the dropdown to disable the row limit? 
Some workaround to disable it?
I'm trying to query Sybase DB that doesn't support LIMIT in dialect.

**Comment by GeorgePearse** [comment]
Any progress on this? My DB performance is great, I want to disable the row limit for vizualizations.

**Comment by alexamy** [comment]
@GeorgePearse I think you should open a new issue about that :disappointed:

**Comment by amiyabasak** [comment]
a) Go to ssuperset_config.py or  value.yml if using helm
b) add 
     SQLLAB_ASYNC_TIME_LIMIT_SEC = 60 * 60 * 6 # 6 hours
     SUPERSET_WEBSERVER_TIMEOUT = 3600
     ROW_LIMIT = 50000000
     VIZ_ROW_LIMIT = 50000000
     SAMPLES_ROW_LIMIT = 50000000
     FILTER_SELECT_ROW_LIMIT = 50000000
     QUERY_SEARCH_LIMIT = 50000000
     SQL_MAX_ROW = 500000000
     DISPLAY_MAX_ROW = 50000000
     DEFAULT_SQLLAB_LIMIT = 50000000
c) Go to Chart and SET ROW LIMIT to 0. ) will not come in drop down but you need to write it. Check the View query and you can see it is taking ROW_LIMIT 50000000
