### ISSUE TITLE
[Explore] No reshuffling of group-by columns via drag-and-drop

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3141]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
The order of columns in the _Group by_ field can be reshuffled by dragging them to a different position.
This worked, e.g., in superset 0.15.4.

![drag_n_drop](https://user-images.githubusercontent.com/1220356/28246260-0ab70b56-6a16-11e7-9b64-32657301b1d8.PNG)

### Actual results
There is only one clickable area on each tab in the list of selected _Group by_ columns and this is the _×_ for removing the column. The tabs are not otherwise clickable and thus not draggable to a different position.

### Steps to reproduce
Select more than one _Group by_ column and try to drag either of them onto the position of another one.

**Comment by mistercrunch** [comment]
We used a different component before the move to React. Unfortunately the `react-select` lib we use does not offer that feature, so that means that for now, the solution is to remove/re-add the columns in the right order.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 280 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen. It still is a regression of what once used to work...

**Comment by mistercrunch** [comment]
The new `react-select` component doesn't support reordering. It would be a pre-req for this feature to be added to `react-select` for us to enable it.

**Comment by victornoel** [comment]
@mistercrunch for the record I opened an issue at react-virtualized-select for this feature: https://github.com/bvaughn/react-virtualized-select/issues/129

Basically, it is not really maintained anymore, but it should not impossible to implement :)

**Comment by mrkcohen** [comment]
The lack of this feature is brutal
