### ISSUE TITLE
[dashboard, time-series bar chart] scrollbars always visible, regardless of slice dimensions

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3142]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset 0.18.5, but the issue exists at least since 0.18.2.

### Expected results
By defining a slice area large enough to accommodate the entire plot, the scroll bars dissappear.
This worked in superset 0.15.4.

### Actual results
Regardness how large the slice dimensions are chosen, there are always scrollbars shown, when a _Time-series bar chart_ is included into a dashboard. The _Bottom margin_ parameter doesn't seem to influence this behavior.

![scroll_bars](https://user-images.githubusercontent.com/1220356/28246352-6628fb64-6a18-11e7-8cf3-a318161f938b.PNG)

### Steps to reproduce
Create a _Time-series bar chart_ slice and add it to a dashboard. Then try to resize it until the scrollbars are gone. This is futile...

**Comment by mistercrunch** [comment]
Browser? OS?

**Comment by xrmx** [comment]
Dup of #3124, which already a dup...

**Comment by rumbin** [comment]
* OS: Windows 7
* Browsers:
    * Vivaldi 1.10.867.38: both scrollbars
    * Firefox 52.1.1 (32-Bit): both scrollbars
    * IE 11.0.9600: no vertical scrollbar, but horizontal is never gone, even if slice is expanded over two screens

**Comment by rumbin** [comment]
@xrmx: I am eagerly following the github pulse and employed the search function before submitting the issue. However, it seems that I failed with both attempts. Sorry…

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 279 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen unless reported to be solved. I cannot evaluate the latest version at the moment, though...

**Comment by sveint** [comment]
This is still a problem on 0.26.3.
