### ISSUE TITLE
[SQLLab] wide Results tables: redundant and non-functional outer scrollbar present when horizontal scrollbar is present

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3143]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Regardless of the width of the _Results_ table in SQLLab, the whole table can be scrolled though vertically using the scrollbar handle.

### Actual results
Depending on whether the table width requires a _horizontal_ scroll bar or not, the _vertical_ scroll bar has much different length and thus much different travel.

When the horizontal scroll bar is shown, the vertical bar hanlde is very long, resulting on a tiny travel that makes manual scrolling to the bottom of the table impossible. Only by using the mouse scroll wheel, all rows can be scrolled through.

### Steps to reproduce
Taking the _url_ table from superset's _main_ database as example:

* Small width of _Results_ table:
![sqllab_scroll0](https://user-images.githubusercontent.com/1220356/28246597-16b15706-6a1e-11e7-88d9-1ca2277792e0.PNG)

* Larger width by including the _url_ field:
![sqllab_scroll1](https://user-images.githubusercontent.com/1220356/28246604-42f1e100-6a1e-11e7-967d-10b976a674c4.PNG)

**Comment by rumbin** [comment]
Issue is still present in 0.19.1.

Actually, a functioning vertical scrollbar is there, however, it is only visible when scrolling to the far right of the horizontal scroll range.

![sqllab_scroll2](https://user-images.githubusercontent.com/1220356/29868783-a1d4478c-8d80-11e7-97b9-9f0e0893a43b.PNG)

So, as soon as there is a horizontal scrollbar present, we happen to have _two_ vertical scrollbars, of which the outer one ist the one which is always visible, but the inner one ist the one that actually works.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 235 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen
