### ISSUE TITLE
[SQL Lab] - Can't run query from Postgres database, get stacktrace instead

### ISSUE THREAD

**Issue by kfk** [apache/incubator-superset#3144]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

Query Results

### Actual results

`<html> <body> <h1>Sorry, something went wrong</h1> <h3>500 - Internal Server Error</h3> <hr> <h2>Stacktrace</h2> <hr> <code> <pre> Traceback (most recent call last): File &#34;/root/env/local/lib/python2.7/site-packages/flask/app.py&#34;, line 1982, in wsgi_app response = self.full_dispatch_request() File &#34;/root/env/local/lib/python2.7/site-packages/flask/app.py&#34;, line 1614, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;/root/env/local/lib/python2.7/site-packages/flask/app.py&#34;, line 1517, in handle_user_exception reraise(exc_type, exc_value, tb) File &#34;/root/env/local/lib/python2.7/site-packages/flask/app.py&#34;, line 1612, in full_dispatch_request rv = self.dispatch_request() File &#34;/root/env/local/lib/python2.7/site-packages/flask/app.py&#34;, line 1598, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File &#34;/root/env/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py&#34;, line 52, in wraps return f(self, *args, **kwargs) File &#34;/root/env/local/lib/python2.7/site-packages/superset/models/core.py&#34;, line 759, in wrapper value = f(*args, **kwargs) File &#34;/root/env/local/lib/python2.7/site-packages/superset/views/core.py&#34;, line 2055, in sql_json if data.get(&#39;status&#39;) == QueryStatus.FAILED: AttributeError: &#39;NoneType&#39; object has no attribute &#39;get&#39; </pre> </code> </body> </html>
`

### Steps to reproduce

Connect to a Postgres database.
Create a query in SQL Lab.
Click "Run Query".

**Comment by mistercrunch** [comment]
What does you SQLAlchemy URI look like?

**Comment by xrmx** [comment]
I think i fixed this in https://github.com/apache/incubator-superset/pull/3111

**Comment by kfk** [comment]
postgresql://postgres:XXXXXXXXXX@localhost/shopify_test

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 279 days. Feel free to comment and request for this issue to be reopened.
