### ISSUE TITLE
Export Dashboard failed (redirected to another page and came back without any result)

### ISSUE THREAD

**Issue by Aleyasen** [apache/incubator-superset#3145]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

I used the latest [docker image](https://hub.docker.com/r/amancevice/superset/) for installation. By running `./bash.sh mysql` from [here](https://github.com/amancevice/superset/tree/master/examples).

### Expected results
Generate the export dashboard file when clicking on the Export button on `http://localhost:8088/dashboardmodelview/list/` page. 

### Actual results
It redirected to another page and come back to the current page quickly without generating any result. The page URL is `http://localhost:8088/dashboardmodelview/export_dashboards_form?id=3`.  I used curl to find out the content of the page. The content is:
```
<script>
    window.onload = function() {
        window.open(window.location += '&action=go');
        window.location = '/dashboardmodelview/list';
    };
</script>
```

### Steps to reproduce
- Visit Dashboard's List page (http://localhost:8088/dashboardmodelview/list/)
- Select a dashboard and click on Export button from the Action list.

### python stacktraces 
I checked the docker logs but nothing added there during this process.

**Comment by xrmx** [comment]
Please post the full stacktrace found in superset server logs.

**Comment by Aleyasen** [comment]
Thanks for your reply @xrmx. The issue was related to blocking the pop-up by the default browser configuration. I'll close the issue.
