### ISSUE TITLE
React dependency disallowed by Apache

### ISSUE THREAD

**Issue by robert-digit** [apache/incubator-superset#3148]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

As per https://issues.apache.org/jira/browse/LEGAL-319 
(more discussion at https://issues.apache.org/jira/browse/LEGAL-303 and https://news.ycombinator.com/item?id=14779881) - our use of React appears to violate Apache rules. We should consider another toolset if possible.

### Superset version
All

### Expected results
We are unencumbered by software patents

### Actual results
We are encumbered by software patents, as prohibited by the Apache foundation

### Steps to reproduce
N/A

**Comment by xrmx** [comment]
The interesting issue is this https://github.com/facebook/react/issues/10191, last update https://github.com/facebook/react/issues/10191#issuecomment-315707719

**Comment by robert-digit** [comment]
Not a lot happening on this but it looks like we have two options:

* Don't be associated with Apache
* Don't use React.

Is there a better venue for this than a github issue? Seems like it merits discussion. This might actually be a decent chance to pare things down, using flask and appbuilder and node and React makes it hard to get started on development.

**Comment by busbey** [comment]
> Is there a better venue for this than a github issue? Seems like it merits discussion. This might actually be a decent chance to pare things down, using flask and appbuilder and node and React makes it hard to get started on development.

your project dev list would be the traditional place for these kinds of discussions. There's no reason it can't be on a github issue like this one, if it works for the community.

**Comment by mistercrunch** [comment]
We're absolutely not ripping React out of this project, and PReact is not a viable option. So that leaves:
* FB does the right thing and issues a clean BSD license in a timely fashion
* We move this project out of the ASF and into another foundation (Cloud Native perhaps?) that is fine with React
* Move the IP back to Airbnb?

We should have the conversation on the mailing list. In the meantime I'm keeping an eye on https://github.com/facebook/react/issues/10191 and hoping for the best

**Comment by xrmx** [comment]
React 16 is out under MIT
