### ISSUE TITLE
Word Cloud losing the top result

### ISSUE THREAD

**Issue by jlkokko** [apache/incubator-superset#3149]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 279 days. Feel free to comment and request for this issue to be reopened.

**Comment by kchrideq** [comment]
I had the same problem, it's a font size problem. In "options", you have to put a max size compatible with the size of the iframe
