### ISSUE TITLE
Install superset in one server. Change http://localhost:8088 to server ip

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-superset#3151]

**Comment by xrmx** [comment]
Could you please explain what the issue is?

**Comment by amoussoubaruch** [comment]
It resolve. 

Thanks

**Comment by xrmx** [comment]
Then please close the issue.

**Comment by amoussoubaruch** [comment]
I have a proxy problem that i solved

**Comment by amoussoubaruch** [comment]
I have a proxy prblem that i solve

**Comment by 369488685** [comment]
how did you solve it?

**Comment by amoussoubaruch** [comment]
Before run superset do unset proxy in your server
