### ISSUE TITLE
Pie chart Label Type

### ISSUE THREAD

**Issue by jackpgao** [apache/incubator-superset#3154]
When use Pie chart, I can use Catetory Name, Value or Percentage.

Can I use the Category Name and Percentage at the same time?

![image](https://user-images.githubusercontent.com/3423412/28320303-cc3987e8-6c02-11e7-9242-1573c2fa6fce.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 278 days. Feel free to comment and request for this issue to be reopened.
