### ISSUE TITLE
How to access the dashboard in my new project without anthentication issues?

### ISSUE THREAD

**Issue by youyou098888** [apache/incubator-superset#3156]
I follow the instructions here 

> http://superset.incubator.apache.org/security.html

 and create a role called 'Public Tables' with the same set of permissions as for the GAMMA role.

However, when I request a ajax to url 'http://localhost:8088/csstemplateasyncmodelview/api/read', I still got 401.
And when I open the link 

> http://localhost:8088/superset/dashboard/4/

in browser I got this:
<img width="783" alt="qq20170719-104025 2x" src="https://user-images.githubusercontent.com/5766819/28348273-b3edaedc-6c6e-11e7-9c38-52bfdb09b0f4.png">

How can I use superset apis in my new project without authentication issues?
Any help will be appreciated.

**Comment by youyou098888** [comment]
I solved it.

**Comment by bpinaya** [comment]
Any tips on how you did this?

**Comment by harshKotadiya** [comment]
Please, can you suggest any solution for that?

**Comment by yx383492322** [comment]
Here is the solution: Explicit grant on specific datasets is still required.
when you got error like this :this endpoint requires the datasource .....
you may edit the Role, add permission like  datasource access on [the table name mention in the error]
