### ISSUE TITLE
I added a new database in the platform, but only in the sql lab mian database.

### ISSUE THREAD

**Issue by qq273681448** [apache/incubator-superset#3158]
![1](https://user-images.githubusercontent.com/13308942/28354875-2cfd0f3c-6c94-11e7-891e-903e7660b5a9.jpg)

**Comment by xrmx** [comment]
Can't understand what the issue is.

**Comment by uptonking** [comment]
@xrmx 
same issue here.    

when I build your latest master branch, the default database set to `main`  in  SQL Lab cannot be changed.  
  
besides, all tables in `Sources -> Tables` page  default click-in view is `[undefined] - untitled` as shown below
![sust_db_error.png](https://uptonking.github.io/assets/issues/superset/sust_db_error.png)

there is *no error only warnings* in both cases.

**Comment by uptonking** [comment]
@qq273681448 
@xrmx 
It seems to be the problem of `Chrome` and the  `autocomplete dropdown textfield `. 

When I switched to Firefox, it works well. query works fine, but the title is still `[undefined] - untitled`.
the autocomplete dropdown textfield doesn't work in Chrome of version 58 on the two pages I mentioned above.
My develop environment is CentOS 7 + Chrome 58.

@xrmx  maybe you need to update the component.

**Comment by xrmx** [comment]
@uptonking yours looks like a completely different issue than the reporter one 🤔

**Comment by mistercrunch** [comment]
Did you check "Expose in SQL Lab"?
<img width="1073" alt="screen shot 2017-07-19 at 9 47 35 am" src="https://user-images.githubusercontent.com/487433/28630614-918582fe-71df-11e7-90ec-3b2e7671a1d2.png">

**Comment by uptonking** [comment]
@xrmx  the same issue.  For me, default database in SQL Editor cannot be changed either.  pic is  shown  below.   when I click on the text field component on the left panel, nothing happens in Chrome.
![main db cannot be changed](https://uptonking.github.io/assets/issues/superset/superset_main_db2.png)
    

@mistercrunch of course it's exposed. query works well in  firefox, not for Chrome. but the title both are `[undefined] - untitled`.  

To sum up, there are two  problems for me : 
1.  default database in SQL Editor cannot be changed.  when I click on the text field component, nothing happens in Chrome.
*problem only in Chrome. firefox works well.* 
 It  seems  the problem of  `autocomplete dropdown textfield` react component with Chrome 58.0.3.  

2. on the table view page as shown in `http://localhost:8899/superset/explore/table/11/`, the  `autocomplete dropdown textfield` react component for  `Time`, `Group By`, `Not Grouped By`, `Options`, `SQL`  all don't work in Chrome.   this component  works well again in firefox.
besides, on this page, the table title all is `[undefined] - untitled` as shown below.
![superset db error](https://uptonking.github.io/assets/issues/superset/sust_db_error.png)

**Comment by mistercrunch** [comment]
I think those are two different issue as @qq273681448 's drop down does drop but only shows main. I'm guessing he didn't check the box in the config.

@uptonking looks like all your dropdowns aren't working. Do you have this issue on the pypi release also, or only on your build? Are you building on Windows? For the record most users use Chrome at Airbnb and I'm surprised this is the first report of dropdowns not droppin'. Are you using Yarn to collect the deps? Mind nuking your node_modules folder and running `yarn` clean on the latest master?

**Comment by uptonking** [comment]
@mistercrunch 
finally solve the problem by disable a chrome extension of Tampermonkey called `remove-web-limits`  :confounded:   

there is no problem for me now. all works fine. I love your superset :flushed:

**Comment by mistercrunch** [comment]
Nice! Thanks for letting everyone know. Someone might hit the same problem in the future.
