### ISSUE TITLE
'Range Filter'  doesn't work in 'Time Series - Bar Chart' and 'Time Series - Stacked' 

### ISSUE THREAD

**Issue by roganw** [apache/incubator-superset#3165]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Display the time range interactive selector when 'Range Filter'  is checked in 'Time Series - Bar Chart' and 'Time Series - Stacked' Slice.

### Actual results
There is no time range interactive selector appears when  'Range Filter'  is checked.

### Steps to reproduce
Select  'Range Filter'  in the slice type of 'Time Series - Bar Chart' or 'Time Series - Stacked'.

### Code issue
It seems `show_brush` only processed when `vizType`==`line` in `nvd3_vis.js`, but listed both in the `controlSetRows` of line, bar, and area in `visTypes.js` .

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 277 days. Feel free to comment and request for this issue to be reopened.
