### ISSUE TITLE
How to assign induvidual dashboards creeated by themselves in superset for Alpha and Gamma users

### ISSUE THREAD

**Issue by saipratap-ip** [apache/incubator-superset#3167]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
  User1 creates a dashboard of D1, D2, D3... and User2 creates dashboards D4, D5...  In Alpha or Gamma Roles.

But ,,,,, the created Dashboards by User1, and User2 .       Dashboards can see be seen other users. Like it is coming overall Dashboards for Alpha and Gamma.  What i need is Individual created dashboards should be visible for themselves only.

### Actual results

It is showing overall dashboards created by all and visible all dashboards to others.

**Comment by xrmx** [comment]
It really depends on the type of the other users and their permission, You need to be more specific.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 276 days. Feel free to comment and request for this issue to be reopened.
