### ISSUE TITLE
Adding dashboard filters, then exploring doesn't carry over filters

### ISSUE THREAD

**Issue by joshwalters** [apache/incubator-superset#3172]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

If filters are applied in a dashboard with a filter slice, and a slice in the dashboard is `explored`, the filter from the dashboard should carry over.

Users will investigate data changes by adding filters to the dashboard, then they should be able to dig into any slice and still have all the filters applied.

### Actual results

The slice the user `explores` does not carry over the dashboard filters, it reverts to the default filters for that slice.

### Steps to reproduce

Make a dashboard with a filter and another slice (time series chart for example). Add a filter in the dashboard via the filter slice. Then click on `explore` in the time series slice. The filter will not carry over.

**Comment by joshwalters** [comment]
It looks like this idea has been mentioned before in other issues, but never raised as a enhancement:

https://github.com/apache/incubator-superset/issues/2890#issuecomment-305984506

**Comment by fufjvnvnf** [comment]
I don't think the filters should be carried over. Slices should be viewed as individuals objects. Suppose you have another dashboard that uses the same slice, and it has its own filters; would you want filters from each dashboards be applied to the slice? In that case it's likely that all data are filtered out and you don't even get to see your chart.

**Comment by mistercrunch** [comment]
Yes it's one of those where people might disagree on the expected outcome.

I agree with @joshwalters and think that clicking "explore" should preserve the context of the filtered dashboard, but perhaps make it clear that you're in a "mutated" slice.

**Comment by joshwalters** [comment]
This was fixed with the merge of https://github.com/apache/incubator-superset/pull/3461
