### ISSUE TITLE
Building error with EventFlow visualization (#3102)

### ISSUE THREAD

**Issue by macfly1202** [apache/incubator-superset#3173]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
1.8.5

### Expected results
build without issues (that was previoulsy ok, 24hour ago) 

### Actual results
ERROR in ./visualizations/EventFlow.jsx
Module not found: Error: Can't resolve '@data-ui/event-flow' in '/*/*/*/superset/incubator-superset/superset/assets/visualizations'
 @ ./visualizations/EventFlow.jsx 13:17-47
 @ ./visualizations/main.js
 @ ./javascripts/modules/superset.js
 @ ./javascripts/dashboard/Dashboard.jsx
 @ multi babel-polyfill ./javascripts/dashboard/Dashboard.jsx

### Steps to reproduce
npm run build

### npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@2.15.11
3 info using node@v4.8.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild superset@0.18.5
6 info build superset@0.18.5
7 verbose unsafe-perm in lifecycle true
8 info superset@0.18.5 Failed to exec build script
9 verbose stack Error: superset@0.18.5 build: `NODE_ENV=production webpack --colors --progress`
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid superset@0.18.5
11 verbose cwd /home/jmp2/GIT/superset/incubator-superset/superset/assets
12 error Linux 4.4.0-83-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
14 error node v4.8.4
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error superset@0.18.5 build: `NODE_ENV=production webpack --colors --progress`
17 error Exit status 2
18 error Failed at the superset@0.18.5 build script 'NODE_ENV=production webpack --colors --progress'.
18 error This is most likely a problem with the superset package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=production webpack --colors --progress
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs superset
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls superset
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by xrmx** [comment]
Hi a couples of notes:
- please quote errors with proper markdown (triple backslash)
- if your compiling from master the version is not 0.1.8.5, but a git hash
- you are building with a very old node / npm, please upgrade to something more modern

Here node 6 and yarn build superset just fine.

**Comment by macfly1202** [comment]
Thanks @xrmx for your advice about markdown and git hash.
I'm only data analyst so not use to build software.
I succeed built with last stable node@8.2.1 and npm@5.3.0.

Event flow is absolutely amazing! thanks for this great visualisation ...  

I close the issue
