### ISSUE TITLE
discuss q

### ISSUE THREAD

**Issue by andyComeOn** [apache/incubator-superset#3175]
"~\incubator-superset\superset\assets\js_build.sh" says 'cd "$(dirname "$0")"',what`s the path?

**Comment by xrmx** [comment]
Hi, why opening an issue if you can run the command yourself and find out?

**Comment by andyComeOn** [comment]
i don`t know i do "npm install" should in "~\incubator-superset\superset\assets\js_build.sh" or in root path.

**Comment by andyComeOn** [comment]
my English is soso, i don`t know i say clear.

**Comment by xrmx** [comment]
You shouldn't run js_build.sh at all, just follow the documentation https://superset.incubator.apache.org/installation.html#making-your-own-build

**Comment by andyComeOn** [comment]
Thank u very much.

**Comment by xrmx** [comment]
Please close the bug.

**Comment by andyComeOn** [comment]
OK , I am a Chinese , now it is late at night. i close right now .
