### ISSUE TITLE
cannot to yarn

### ISSUE THREAD

**Issue by hd19861028** [apache/incubator-superset#3176]
as bellow:

$ yarn
yarn install v0.24.5
info No lockfile found.
[1/4] Resolving packages...
warning mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead

warning mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning mapbox-gl > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry ins
tead
warning mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox
/geojson-area instead
error Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: C:\Users\Administrator\AppData\Local\Yarn\cache\v1\.tmp\ab318f7de3e197529489fbe3b021bfb6
Output:
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by xrmx** [comment]
Hello, this is interesting because it looks like the failure on travis but still we don't support windows.

**Comment by railings** [comment]
The yarn build is broken on all supported platforms due to the ssh github mapbox dependency issue.

**Comment by ciwei100000** [comment]
I encountered the same issue, followed by yarn build error.

**Comment by xrmx** [comment]
Please give it a try to latest master.

**Comment by ciwei100000** [comment]
Hi! I tried the lastest #3179. It does work for me although the warning as in this thread still shows up.  Thanks!

**Comment by mistercrunch** [comment]
We should be good here, maybe clear your yarn cache?

**Comment by caixiao-1123** [comment]
run command : yarn cache clean

clean yarn cache resolve my question

**Comment by BigKongfuPanda** [comment]
> run command : yarn cache clean
> 
> clean yarn cache resolve my question

thanks, it works!

**Comment by ktmud** [comment]
`incubator-superset` has moved from using `yarn` to `npm`. Please don't use `yarn` on `incubator-superset`. (`superset-ui` still uses `yarn` though.)
