### ISSUE TITLE
Question: Basic line chart - setting the x axis

### ISSUE THREAD

**Issue by JImBurris** [apache/incubator-superset#3184]
Is it possible to do a simple line chart with something other than a time series on the x axis?

**Comment by xrmx** [comment]
Looks more like a question for gitter or the mailing list than an issue to me.

**Comment by rumbin** [comment]
@fabianmenges, referring to your comment in#3769:

Do you also consider a scatter plot option, maybe even with non-aggregated values? I know that this can partly be achieved with the bubble chart, but not quite intuitively, though...

**Comment by mistercrunch** [comment]
Dup of https://github.com/apache/incubator-superset/issues/3769, closing
