### ISSUE TITLE
Please use verbose_name in TreeMap visualization

### ISSUE THREAD

**Issue by sandeeps74** [apache/incubator-superset#3185]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Tree map chart top header shows metric names (ex: sum___packet_rate) instead of verbose name (Packet Rate)

### Actual results
Treemap header shows sql/developer like string (sum__packet_rate). Verbose name display will be more user friendly.

### Steps to reproduce
Create a database table   with columns metric and packet_reate.  Change sum__packet_rate verbose name to "Packet Rate".  Create a TreeMap visualization, group by metric. The Chart header will show sum__packet_rate instead of "Packet Rate".

![image](https://user-images.githubusercontent.com/25699059/28633744-d3ba5244-7202-11e7-9ab1-2d7f93602ca9.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 270 days. Feel free to comment and request for this issue to be reopened.
