### ISSUE TITLE
[sqllab] query  result  is  not accurate

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3188]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5
0.17.6

### Python version
2.7

### Expected results
return the accurate bigint field
### Actual results

the last two bits in the bigint is wrong

### Steps to reproduce
I use sqllab to query mysql tables. My sql statement is :
_select * from ec_order_main where main_order_no = 401501121320267725_.
"main_order_no" is the primary key of ec_order_main table,its data type is BIGINT.

Sqllab can find the record,but the 'main_order_no' is 401501121320267700. I expected the "main_order_no"  should be "401501121320267725" instead of "401501121320267700".
Am I missing something and how can I address this issue?
![1](https://user-images.githubusercontent.com/16470564/28653711-b572d580-72c1-11e7-9dd9-b2a0524aa234.png)

**Comment by xrmx** [comment]
Which database is this? Have you tried doing the same query with the database cli?

**Comment by luciuschina** [comment]
This is mysql, and I use other clients, it shows OK!
![1](https://user-images.githubusercontent.com/16470564/28659169-ff93c2e0-72e0-11e7-911d-ba154695b88e.png)

**Comment by xrmx** [comment]
Next step is to try the query in pandas, if it's still wrong here then the issue is in pandas.

**Comment by luciuschina** [comment]
OK , I am not very familiar with python and pandas, but I will have a try.

**Comment by xrmx** [comment]
This looks like a good start https://stackoverflow.com/a/25030617/4470501

**Comment by luciuschina** [comment]
A colleague of mine is familiar with pythin and pandas，he tested this query in pandas：
![111](https://user-images.githubusercontent.com/16470564/28663413-e161e748-72ef-11e7-9287-89e5cfd09eee.jpg)
So it seemed that  the pandas has no problems。

**Comment by xrmx** [comment]
Thanks for checking! Maybe is this just javascript? On my browser console `Number.MAX_SAFE_INTEGER < 401501121320267725` returns true

**Comment by luciuschina** [comment]
So is this a bug ？

**Comment by mistercrunch** [comment]
That is a weird bug. :/

**Comment by xrmx** [comment]
If it's only a visualization bug the sql lab api can cast everything to string?

**Comment by mistercrunch** [comment]
Is the value ok in the json ?

**Comment by luciuschina** [comment]
@mistercrunch I use fiddler to get the result json。It seems the value in json is OK。
![1](https://user-images.githubusercontent.com/16470564/28759584-ab40a336-75d1-11e7-9675-4f413f7d9c59.png)

**Comment by mistercrunch** [comment]
Seems like a JS/JSON.parse limitation:
https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint

**Comment by rumbin** [comment]
Most simple way to reproduce:
```
SELECT 401501121320267725 as test
```
in SQLLab

**Comment by dmigo** [comment]
[here](https://www.w3schools.com/js/js_numbers.asp) it states that any number longer than 15 digits is going to be imprecise in javascript.

**Comment by jargnar** [comment]
JS stores numbers as double precision 64 bit format IEEE 754 values.

I'm guessing this needs to be wrapped in some kind of string format.

**Comment by mistercrunch** [comment]
Seems like this is what this does:
https://www.npmjs.com/package/json-bigint-string

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 264 days. Feel free to comment and request for this issue to be reopened.
