### ISSUE TITLE
install superset on ubuntu fails 

### ISSUE THREAD

**Issue by shafaq** [apache/incubator-superset#3189]
I have seen issues [643](https://github.com/apache/incubator-superset/issues/643) and 
[683](https://github.com/apache/incubator-superset/issues/683)

I have ubuntu with all the dependencies installed. 
No matter I install through `pip` or `git`, I get the error see https://gist.github.com/shafaq/84c8dc9491c3ae2cdfad890d6bf8fef5

Any suggestion? 

Thanks

**Comment by xrmx** [comment]
You don't have python headers installed, see https://superset.incubator.apache.org/installation.html#os-dependencies . In your case the package should probably be python3-dev.

**Comment by shafaq** [comment]
Yes.

Thanks.

**Comment by xrmx** [comment]
Please close the issue if it's resolved, thanks.
