### ISSUE TITLE
[druid] add support for "NOT GROUPED BY "

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3190]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5
0.17.6

### Expected results
Disaply the atomic rows of Druid

### Actual results
It shows "No data"

### Steps to reproduce
The time ranges is from 90 days ago to now.And I am sure that in this time range,Druid has data. When I use the " GROUPED BY " functuion, superset return the results,But when use "NOT GROUPED BY",It shows "No data".
I also test the mysql database,the "NOT GROUPED BY" function is OK !
Below is driud datasource use  "NOT GROUPED BY"
![1](https://user-images.githubusercontent.com/16470564/28660425-6d2f9d48-72e5-11e7-90ce-9c58b8e558c1.png)
the query statment is :  

![22](https://user-images.githubusercontent.com/16470564/28661542-90385e3e-72e9-11e7-868d-4aa5ad41d103.png)

As far as I know ,druid can use  "select" queryType to disaply atomic rows : 
 {
   "queryType": "select",
   "dataSource": "wiki3",
   "descending": "false",
   "dimensions":[],
   "metrics":[],
   "granularity": "all",
   "intervals": [
     "2013-01-01/2017-07-30"
   ],
   "pagingSpec":{"pagingIdentifiers": {}, "threshold":100}
 }
So, I think superset should support this functions.
Am I missing something in my config or environment?

**Comment by tatototino** [comment]
I got the same problem, I would like to make a graph to get raw data from a specific dimension but I can´t do it cause the field aggregation is required.

**Comment by mistercrunch** [comment]
I made this issue a feature request.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 207 days. Feel free to comment and request for this issue to be reopened.

**Comment by CamiloRueda** [comment]
Hi ! I have  the issue, the error that report each time that I try a query with "NOT group by" is
![imagen](https://user-images.githubusercontent.com/17951727/39771417-c11d6a9a-52b7-11e8-9f81-3c8d92a8c825.png)
Nevertheless with querys with "GROUP BY" works perfect.
![imagen](https://user-images.githubusercontent.com/17951727/39771532-29857d5c-52b8-11e8-9952-6312076f4edb.png)
