### ISSUE TITLE
Unknown column 'created_by' in 'order clause'

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3199]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Meta database
MySQL

### Expected results
No error

### Actual results
Has an error

### Steps to reproduce
![1](https://user-images.githubusercontent.com/16470564/28707152-ca45643a-73a9-11e7-8b9b-5df98f6d476f.png)
![2](https://user-images.githubusercontent.com/16470564/28707159-d2057962-73a9-11e7-88c9-7b42509189ff.png)
The error is:
_OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'created_by' in 'order clause'") [SQL: u'SELECT dashboards.created_on AS dashboards_created_on, dashboards.changed_on AS dashboards_changed_on, dashboards.id AS dashboards_id, dashboards.dashboard_title AS dashboards_dashboard_title, dashboards.position_json AS dashboards_position_json, dashboards.description AS dashboards_description, dashboards.css AS dashboards_css, dashboards.json_metadata AS dashboards_json_metadata, dashboards.slug AS dashboards_slug, dashboards.changed_by_fk AS dashboards_changed_by_fk, dashboards.created_by_fk AS dashboards_created_by_fk \nFROM dashboards ORDER BY created_by asc \n LIMIT %s'] [parameters: (100,)]_

My tested result :
 "ORDER BY **created_on**" is work。
“dbs” table has “created_on” field instead of “created_by”.

**Comment by xrmx** [comment]
Looks like a dup of #3074

**Comment by luciuschina** [comment]
yes，the same issue
