### ISSUE TITLE
Reusable React Components timeline

### ISSUE THREAD

**Issue by lunasabs** [apache/incubator-superset#3201]
I'm not sure if this is the correct place to ask. If not, please lead me to the correct location.

In this article: https://medium.com/airbnb-engineering/caravel-airbnb-s-data-exploration-platform-15a72aa610e5
It is stated: 

> We’re planning on releasing the data visualizations and controls exposed in Superset as reusable React components. This modular approach will make these building blocks available to application developers. At Airbnb, we have many use cases for rich and interactive visualizations as part of of internal applications; for example, our A/B testing framework, anomaly detection framework and user session explorer. It would be great to share the same components across all of these applications.

When do you plan on releasing React reusable components? Or at least when is it planned to have the ability to embed without the use of iframes. This limitation is one of the only things stopping me from using this library right now.

**Comment by mistercrunch** [comment]
We're hoping sometime in H2 this year. Keep in mind that the vision is to assume and leverage an existing Superset backend.

**Comment by robert-digit** [comment]
So, just wondering here - how exactly will this happen when React is cat-x'ed by Apache foundation?

**Comment by xrmx** [comment]
@robert-digit you have already opened an issue for that, no need to discuss it again here.

**Comment by mg1075** [comment]
Wouldn't it be beneficial for more developers to make components with a framework agnostic approach, using a tool like [Stencil](https://github.com/ionic-team/stencil)?

> ... Stencil is also a solution to organizations and library authors struggling to build reusable components across a diverse spectrum of frontend frameworks, each with their own component system. Stencil components work in Angular, React, Ember, and Vue as well as they work with jQuery or with no framework at all, because they are just plain HTML elements.

**Comment by aaronhayes** [comment]
@mistercrunch any update on the time frame or progress?

**Comment by tkaklam** [comment]
@mistercrunch also, if the feature is no longer prioritised, who could provide enough input to get others started on the topic? We're very interested!

**Comment by aaronhayes** [comment]
@mistercrunch thanks for the update. Are you looking for outside contributions on this feature? Hopefully next quarter will be able to help out.

**Comment by mistercrunch** [comment]
I think this runs pretty deep and would rather have seasoned committers to attack this. You can help by tackling simpler issues and features, and freeing core committers to work on more ambitious things.

We welcome all contributions of course but prefer new contributors to ramp up before taking on large efforts.

**Comment by TimHeckel** [comment]
@mistercrunch - hi! I'm simply wondering if there is an update on this functionality?

**Comment by mistercrunch** [comment]
Check out the issues with the `Superset Improvement Proposal` label

**Comment by kristw** [comment]
Please checkout [@superset-ui](https://github.com/apache-superset/superset-ui) and [@superset-ui/plugins-*](https://github.com/apache-superset/superset-ui-plugins)
