### ISSUE TITLE
How to set the fonts on the X axis no rotate and in center

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3206]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
Set the fonts in the dist_bar no rotate and in center

### Actual results
I can set the fonts in the dist_bar no rotate, but the fonts **not in center**

### Steps to reproduce
I use the CSS template to change the style,and add 
_text {
  transform: rotate(0)!important;
}_
can dispaly the fonts horizontal. but the fonts not in center. I have tested many CSS styles, but it doesn't work ! Who can help me, very appreciated.
![2](https://user-images.githubusercontent.com/16470564/28772064-9d158c5e-7617-11e7-9651-82aa759432b7.png)

**Comment by mistercrunch** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor
