### ISSUE TITLE
Quoting column names in time series line charts

### ISSUE THREAD

**Issue by jan-schulz-k24** [apache/incubator-superset#3208]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "b'219f33f0d1fcd05db1807f5b95caea8b0edd92f7\\n'", "version": "0.18.5"} (master from 2 hours ago)

### Expected results
Referencing Capitalized columns in time series line charts works

### Actual results
It doesn't work the generated SQL is not quoting the selected column

### Steps to reproduce
* Have a postgres data source, where the time column name needs quotes (Capitalized or with spaces in them)
* Try to build a time series chart where that column is used as time dimension

The problem is that the generated SQL is not quoting the selected columns:

```
(psycopg2.ProgrammingError) column "bestelldatum" does not exist LINE 1: SELECT Bestelldatum AS __timestamp, ^ HINT: Perhaps you meant to reference the column "bestellartikel_data_set.Bestelldatum". [SQL: 'SELECT Bestelldatum AS __timestamp,\n SUM(ds.bestellartikel_data_set."Bruttobestellwert") AS "sum__Bruttobestellwert"\nFROM ds.bestellartikel_data_set\nWHERE "Bestelldatum" >= \'2017-07-24 12:45:22\'\n AND "Bestelldatum" <= \'2017-07-31 12:45:22\'\nGROUP BY Bestelldatum\nLIMIT 5000']
```
In the WHERE, it's quoted, but not in the SELECT part and not in the GROUP BY part .

**Comment by Ryanthegiantlion** [comment]
Having the same issue.

Did you find any workaround @jan-schulz-k24

**Comment by Ryanthegiantlion** [comment]
Btw, this is replicated in #3001 and #408

**Comment by Ryanthegiantlion** [comment]
I believe the issue is here: https://github.com/apache/incubator-superset/blob/e121a8585e753e0e659f52da2bec6b5bc7f79444/superset/db_engine_specs.py#L216-L217

Notice that the column is not correctly escaped.

A workaround is to define a time column on the table and then select 'Time Column' as the grain.

**Comment by jan-schulz-k24** [comment]
as I only had a glance at Superset, I didn't try to find a workaround. Probably adding a view with sanitized names would be a way.
