### ISSUE TITLE
IndexError: list index out of range  Traceback

### ISSUE THREAD

**Issue by arunkjn** [apache/incubator-superset#321]
I installed the latest version of caravel using pip

using mysql as backend by creating a caravel_config.py file in $PYTHONPATH with the following content-
SQLALCHEMY_DATABASE_URI = 'mysql://root:root@localhost:3306/caravel'

followed these steps-
- pip install caravel
- fabmanager create-admin --app caravel
- caravel db upgrade
- caravel init
- caravel load_examples
- caravel runserver -d

The app works fine except when I open a particular slice eg. 
`http://localhost:8088/caravel/explore/table/3/?since=100+years+ago&datasource_id=1&slice_id=19&viz_type=pivot_table&row_limit=5000&metric=sum__num&groupby=name&datasource_type=table&metrics=sum__num&markup_type=markdown&compare_lag=10&limit=25&until=now&granularity=ds&datasource_name=birth_names&flt_op_1=in&slice_name=Pivot+Table&where=&compare_suffix=o10Y&columns=state`

I get the following error-

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
>     return f(self, _args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/caravel/models.py", line 1152, in wrapper
>     return f(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/caravel/views.py", line 481, in explore
>     slice=slc)
>   File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 58, in **init**
>     ff = FormFactory(self)
>   File "/usr/local/lib/python2.7/dist-packages/caravel/forms.py", line 112, in **init**
>     default_metric = datasource.metrics_combo[0][0]
> IndexError: list index out of range

**Comment by scophotog** [comment]
I've followed the same steps since doing a fresh install to 0.8.6. I'm using a sqlite DB and have the same being thrown when trying to access the table I'm trying to slice on:

```
2016-04-13 17:26:49,227:INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 17:26:49] "GET /caravel/explore/table/5/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/caravel/models.py", line 1152, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/caravel/views.py", line 481, in explore
    slice=slc)
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 58, in __init__
    ff = FormFactory(self)
  File "/usr/local/lib/python2.7/site-packages/caravel/forms.py", line 113, in __init__
    default_groupby = datasource.groupby_column_names[0]
IndexError: list index out of range
```

**Comment by coursera-ds** [comment]
Same issue here with Druid 0.9 and their sample wiki dataset.

**Comment by scophotog** [comment]
v0.8.7 came out and I just upgraded. This error has disappeared and I can create slices again.

Looks like this one is fixed?

**Comment by mistercrunch** [comment]
From the stack trace, this looks like your datasource had no columns flagged as "groupable by". This view:
![img](http://airbnb.io/caravel/_images/matrix.png)

Sometimes we see the the process that pulls the Druid metadata returns tables with no columns, I'm not sure why. Maybe it's realtime tables before the first segment landed? Maybe it takes two passes for that script to do things properly?

**Comment by arunkjn** [comment]
In my case, I was using the built in examples using caravel load_examples

**Comment by mistercrunch** [comment]
What does the matrix look like for you?

To clarify, this line in the stacktrace:
``` 
File "/usr/local/lib/python2.7/site-packages/caravel/forms.py", line 113, in __init__
    default_groupby = datasource.groupby_column_names[0]
```

Means that no groupby columns are defined for the table. The root cause is around how the examples got loaded, either the columns are missing or the groupby flag didn't get checked properly automatically.

**Comment by arunkjn** [comment]
I just checked the database. The slice definition seems to be okay, with a group by clause present in a JSON object under 'params' column. The 'tables'  table is also defined. But I see that 'table_columns' table is empty. And I get this view on editing the 'birth_names' table. Could this be a issue related to migrations? I am using mysql.

![asd](https://cloud.githubusercontent.com/assets/2032329/14598512/1aba7e04-0570-11e6-85ac-3d3a638be3c9.png)

**Comment by Miserlou** [comment]
+1 on this issue with latest Caravel and SQLite. The DB loads find into SQL Explorer, but the List Table Columns never load properly, so nothing after that works and it cascades to that index error.
<img width="1168" alt="screen shot 2016-04-23 at 1 03 34 pm" src="https://cloud.githubusercontent.com/assets/139987/14762893/e8862c3e-0953-11e6-9a26-226c911cc571.png">
