### ISSUE TITLE
superset 0.17.0 can not update 

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#3215]
when i excute 
superset db upgrade
ImportError: No module named '_sqlite3'

when i change then config.py DB connet
  File "/data/py3_superset_env/bin/superset", line 12, in <module>
    from superset.cli import manager
  File "/data/py3_superset_env/lib/python3.4/site-packages/superset/__init__.py", line 50, in <module>
    for bp in conf.get('BLUEPRINTS'):
TypeError: 'NoneType' object is not iterable

**Comment by xrmx** [comment]
Your python does not have sqlite3, not a superset issue, please close.

**Comment by mistercrunch** [comment]
https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by mistercrunch** [comment]
`0.17.0` is old, we can only afford to pay attention to bugs that can be reproduced on the latest release.
