### ISSUE TITLE
Cassandra

### ISSUE THREAD

**Issue by sherubhu** [apache/incubator-superset#3228]
Does superset support integration with Cassandra or Mongo?

**Comment by mistercrunch** [comment]
Not at the moment but we have a connector interface that could be implemented.

**Comment by sherubhu** [comment]
SQLAlchemy or something else?

**Comment by mistercrunch** [comment]
I doubt Cassandra and Mongo support any form of SQL. You'd have to implement the connector using whatever query interface they have. I'm assuming Cassandra and Mongo can both do group by and filtering operation.

**Comment by FrederichCheng** [comment]
@sherubhu Have you ever considered using Presto as the query engine for Cassandra and MongoDB? There is a Presto SQLAlchemy connector developed by Dropbox: https://github.com/dropbox/PyHive

**Comment by mistercrunch** [comment]
It's all about the amount of pushdown that is supported on the Presto connectors, you want for the connector to support predicate pushdown, and ideally grouping pushdown (though that's less likely)

**Comment by sherubhu** [comment]
Thanks @FrederichCheng - looks promising - let me work on this and get back to you with the outcome.

**Comment by iwechen** [comment]
Where is the interface to the Mongo database？

**Comment by mistercrunch** [comment]
@iwechen I'm not aware of any.

**Comment by mhsekhavat** [comment]
@sherubhu Have you tried Presto? Any advice?
