### ISSUE TITLE
Dashboard tabs

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#3245]
I would be interested in a feature to add tabs to dashboards. This would help in easy grouping of similar views in a dashboard to separate groups and also reduce the number of queries triggered on the backend.
Any quick pointers to add this feature would be really helpful.

**Comment by mistercrunch** [comment]
This should be easy after we refactor the dashboard to be 100% React

**Comment by mistercrunch** [comment]
Refactor https://github.com/apache/incubator-superset/pull/3581 has landed, which unblocks this.

I'm thinking the way to model this in the Redux store is to add a `tabs` array to the dashboard object. The shape of the element in the array should include a list of slice ids and their positions, a tab title and rich optional tooltip (markdown). The slice objects themselves can stay where they are (normalize) and not fall under the tabs object hierarchy.

**Comment by rumbin** [comment]
I like the idea of using tabs for structuring large dashboards, but there might be some pitfalls:

How would filter slices be treated in a way that is transparent to the user?
Technically, I would expect them to affect all tabs. However, on a different tab the filter slices may/will not be visible any more and users may forget about the applied filters or even expect the filters to only work on a per-tab basis.

Maybe there would also be a need to limit a filter's scope to the current tab, e.g., in a similar manner as it currently is done for individual slices.
