### ISSUE TITLE
Change the axis direction for Heatmap visualization

### ISSUE THREAD

**Issue by khotkevych** [apache/incubator-superset#3250]
Is there any way to change the direction of X and Y axis on the heatmap visualization? 
I would be nice if the axis may cross at the 0 point.
At the moment they are crossing at maximum. 
Ordering doesn't change the situation. 
![selection_014](https://user-images.githubusercontent.com/13405635/29030642-71981222-7b94-11e7-8458-08a0d4a3da37.png)

Also is there any way to add legend and axis labels for heatmap?

## Superset version
0.18.4

**Comment by mistercrunch** [comment]
Not at the moment, the heatmap clearly needs some work...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 258 days. Feel free to comment and request for this issue to be reopened.
