### ISSUE TITLE
Filtering Top N values 

### ISSUE THREAD

**Issue by shyam2794** [apache/incubator-superset#3251]
Currently i am using the superset version 0.18.5 . My source Database is Mysql , one of my requirement is to display the top '5' departments by revenue across years , months and quarter . Is there any way to do this in superset . Also I would like to know whether we can use the custom queries as input to the visualization .

**Comment by mistercrunch** [comment]
It's unclear to me what you mean by "display the top '5' departments by revenue across years , months and quarter". What type of visualization? time series? a table?

And yes you can use custom queries as input. The easiest way is to click [Visualize] from a SQL Lab result set.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 258 days. Feel free to comment and request for this issue to be reopened.

**Comment by kalimuthu123** [comment]
Hi , 
  i am having same concern for filtering the top 5 values based on metrics
