### ISSUE TITLE
[sqllab] recognize JSON columns and display nicely

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3253]
Often times a column contains JSON as a string. It would be awesome to recognize valid json strings and give the option to display in some more readable form.

Could be as simple as looking for whether the string starts with `{` and attempt to parse it if that's the case. Maybe allow display in a modal with nice syntax highlighting.

**Comment by rumbin** [comment]
Alternatively, it could as well be required to define the table column __Type__ in Superset's table definition to be _JSON_ (or in case of Postgres also _JSONB_) . This way there wouldn't be any logic necessary for determining whether it's a JSON column.

**Comment by tswast** [comment]
The BigQuery connector can return JSON columns. These values are actually parsed into dictionaries in the SQLAlchemy connector, so no JSON parsing would be needed.

See https://github.com/mxmzdlv/pybigquery/issues/17#issuecomment-413960156 for context. I think the request is that it detect nested scalar values within the JSON objects.

**Comment by sumedhsakdeo** [comment]
My thinking is that if superset can get the data from bigquery in pandas dataframe format it can use it directly https://github.com/apache/incubator-superset/blob/5eff7a8d6ccfefabad77f9704521959f14be530d/superset/dataframe.py#L54

pybigquery could be extended to exposes wrappers for pandas_gbq library just like it exposes for bigquery apis.

Thoughts @tswast @mxmzdlv @mistercrunch

**Comment by tswast** [comment]
pandas doesn't handle JSON types well, either, so I'm not sure that would help. Apache Arrow does have support for nested types, so that may be more useful for this issue.

**Comment by mistercrunch** [comment]
My original thinking was just around our "data table" component being smarter and instead of showing super large column width when encountering JSON (or python dicts/array for that matter), it would show a summary in the cell and allow expanding it (in place? modal?)

**Comment by tswast** [comment]
@mistercrunch Should we open up a separate issue for @sumedhsakdeo's request to be able to flatten JSON columns to visualize the scalar values within them?

**Comment by mistercrunch** [comment]
@tswast I'm not sure how to best deal with this, somehow I feel like it's a driver feature.
