### ISSUE TITLE
Allow for multiple color schemes

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3258]
* new sets of hardcoded colors where bnbColors now lives
* new dropdown control that shows scheme name and colors
* set an environment default for DEFAULT_COLOR_SCHEME in `config.py`

**Comment by graceguo-supercat** [comment]
This feature is requested from https://github.com/apache/incubator-superset/issues/1874, https://github.com/apache/incubator-superset/issues/638

**Comment by mistercrunch** [comment]
For reference:
https://bl.ocks.org/mbostock/5577023
http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d

**Comment by mistercrunch** [comment]
Also perhaps in scope, using the same new control component for linear colors:
https://github.com/apache/incubator-superset/blob/master/superset/assets/javascripts/explore/stores/controls.jsx#L157
