### ISSUE TITLE
"Select all" checkbox doesn't work in add slices modal

### ISSUE THREAD

**Issue by nick-zhu** [apache/incubator-superset#3259]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest code, master branch

### Browser
Chrome 59.0.3071.115 (Official Build) (64-bit)

### Steps to reproduce
1. Create a dashboard and open it
2. Click on the settings gear icon then click on "+" icon to add slices
3. Click on select all checkbox

### Expected results
All slices are selected and "add slices" button is enabled

### Actual results
"add slices" button is disabled all the time

### Reason 
SliceAdder.jsx doesn't handle onSelectAll. Therefore when users click on "check all" box, selectionMap is not updated

**Comment by xrmx** [comment]
Which version of superset is this? Please use the template issue.

**Comment by nick-zhu** [comment]
@xrmx, thanks for your feedback. I have updated the ticket. I also have a fix for it, I can submit a pull request

**Comment by NaukhaizAhmad** [comment]
I am facing the same issue #3260.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 249 days. Feel free to comment and request for this issue to be reopened.
