### ISSUE TITLE
Add slice to dashboard: unchecking slices doesn't work

### ISSUE THREAD

**Issue by nick-zhu** [apache/incubator-superset#3260]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest code, master branch

### Browser
Chrome 59.0.3071.115 (Official Build) (64-bit)

### Steps to reproduce
1. User creates the dashboard and opens it. User clicks on Settings> + sign to add slices
2. Select multiple slices
3. Uncheck some of selected slices
4. Click add slice button

### Expected results
Only selected slices are added to the dashboard

### Actual results
Previously selected slices, even though they are unchecked, are still added to the dashboard

### Reason
selectionMap should be filtered by state.

**Comment by xrmx** [comment]
Please add the same missing information as #3259

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 250 days. Feel free to comment and request for this issue to be reopened.
