### ISSUE TITLE
Refresh table definition

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#3265]
Does superset allow to refresh table definition?
If I add new columns to the table in Database, how do I refresh the definition to import the new columns without adding them manually?

**Comment by vibinsv09** [comment]
I realized now that simply editing and saving it again refreshes the definition.
A refresh button to do it would be more helpful

**Comment by robert-digit** [comment]
It does? I've tried that numerous times and have never seen any kind of refresh. I still need to add columns and metrics (i.e. AVG) manually.

**Comment by mistercrunch** [comment]
Editing and saving the table should merge new columns in.
