### ISSUE TITLE
Put filters in an array instead of filters on strings only on Dashboard

### ISSUE THREAD

**Issue by shrutimkrishnan** [apache/incubator-superset#3269]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.0

### Expected results
Want the ability to filter the dashboard with an array rather than string values only. Example:
![image](https://user-images.githubusercontent.com/11141144/29151699-f3e848b8-7d7a-11e7-8a5b-241f76250b43.png)

### Actual results
Only able to filter based on set string values
![image](https://user-images.githubusercontent.com/11141144/29151710-ffcc238e-7d7a-11e7-86f9-7d152c18ec37.png)

### Steps to reproduce
As shown above

**Comment by mistercrunch** [comment]
You can probably write a WHERE clause that would do that can't you?

**Comment by shrutimkrishnan** [comment]
Need to give the user the ability to filter A1 or A2 on their own from the filter slice... Otherwise we end up having to duplicate rows of data to both A1 and A2 just to make it work with a defined string.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mistercrunch** [comment]
there's a `like` option in the dropdown, what about picking that and writing `%A1%`?

**Comment by shrutimkrishnan** [comment]
Gives an error message - _'dict' object does not support indexing_

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 254 days. Feel free to comment and request for this issue to be reopened.

**Comment by applechip** [comment]
Any chance this issue can be reopened? I know there is a workaround using Jinja templating but that is inconvenient.

**Comment by matheusbsilva** [comment]
UP I'm facing the same issue on version 3.0.0. I can't filter a field of type string array by searching for a value inside of the array, I know I can write a custom SQL query to filter the chart but I can't do the same in dashboards. Is there any workaround for this?
