### ISSUE TITLE
date type field display error

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#3271]
date type column in table  display timestamp in superset ,in database the value is '2017-08-08' but in superset display look like '1500324543543',how convert is correct

**Comment by foodspect** [comment]
We have the same issue.

**Comment by foodspect** [comment]
@mistercrunch which build can't you reproduce this bug on? Here is our setup:

Table designer setup for our date field:
<img width="518" alt="screen shot 2017-08-13 at 9 41 50 am" src="https://user-images.githubusercontent.com/18358703/29251567-c59aa86e-800b-11e7-982c-296f7ee2ef3f.png">

What the date looks like:
<img width="119" alt="screen shot 2017-08-13 at 9 42 09 am" src="https://user-images.githubusercontent.com/18358703/29251568-c59ab76e-800b-11e7-9429-6ac9cfcb409d.png">

How our TableView slice is configured:
<img width="568" alt="screen shot 2017-08-13 at 9 41 13 am" src="https://user-images.githubusercontent.com/18358703/29251569-c59dded0-800b-11e7-9d43-a33b4bd97f2e.png">

What our TableView slice looks like:
<img width="395" alt="screen shot 2017-08-13 at 9 40 40 am" src="https://user-images.githubusercontent.com/18358703/29251570-c59e05ae-800b-11e7-8b20-3b9dc8262009.png">

Looks like it's a known bug for 0.18.5:
https://stackoverflow.com/questions/45248010/date-formatting-in-superset-with-mysql/45570314#45570314

**Comment by amancevice** [comment]
Seeing the same behavior in `0.19.0`

**Comment by JessicaDuan** [comment]
Same problem in the latest master :(

**Comment by JessicaDuan** [comment]
Hi, I've compared the differences between 0.19.1 and 0.15.2, and found that:
class TableViz => def json_dumps()
=> return json.dumps(obj, default=utils.json_int_dttm_ser, ignore_nan=True)
In 0.15.2, it was: return json.dumps(obj, default=utils.json_int_dttm_ser)

**Comment by vnnw** [comment]
Any progress in fixing this bug?

**Comment by amancevice** [comment]
The workaround for me was to create a column that casts the date/timestamp to a string. Not great, but works.

**Comment by macfly1202** [comment]
I've got the same issue exactly on mysql and superset 0.19.1

**Comment by Nina07** [comment]
Getting the same error for 0.20.6
Database - Clickhouse.

**Comment by JohnOmernik** [comment]
I am seeing this error as well. It looks like on output, if the field looks "datish" it converts it. I created a DB level view that added a d: in front of my YYYY-MM-DD and it stop showing this as a date then (nothing else changed). The infered type shows VARCHAR, etc.

**Comment by felexkemboi** [comment]
Actually this is the exact problem   i am facing.How am  i suppose to get out of it?

**Comment by felexkemboi** [comment]
> ![dateissue](https://user-images.githubusercontent.com/6196797/34202328-78cf57c6-e59d-11e7-941d-6aa64fff0fde.png)
> Getting the same error for 0.20.6
> Database - Clickhouse, column type: Date
> Date comes properly when in Pivot Table view. Is messed up with Table View and in Time Dashboard Filter, when using the date column in Filter Column.

Any solution to this?

**Comment by felexkemboi** [comment]
Anybody` still facing this challenge,i solved it by  `DATE_FORMAT(pay.created_at, '%Y-%m-%d %H:%m:%s' ) 'DateCreated',` in my date column.Basically you change the format of your column during querying the database, that is if you are using mysql like for my case

**Comment by Riskatri** [comment]
i have same issue for pie chart. any solution to this??

**Comment by 0101Unkown0101** [comment]
Honestly I'm not that good in coding I'm just a beginner
