### ISSUE TITLE
Filter box should also allow custom order

### ISSUE THREAD

**Issue by 360d-io-labs** [apache/incubator-superset#3272]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19

### Expected results
Filter Box currently sort the results based on a metric (which is fine). However if you build small dimension table to be able to get a list of elements to filter the metrics order doesn't make sense. It will be great to be able to put no metric at all and add a standard SQL ORDER BY to the request to sort result by alphabetical order.

###Potential Solution

Add in the SQL menu for filter an ORDER BY clause

**Comment by vnnw** [comment]
Strongly agreed!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 213 days. Feel free to comment and request for this issue to be reopened.
