### ISSUE TITLE
Microsoft SQL Analysis Services support?

### ISSUE THREAD

**Issue by rogercorrea** [apache/incubator-superset#3273]
Please,

Do with the SQL Server support include the Analyse Services integration?
I have a environment that we use many cubes but I don't know if Superset support it.

If not, what solution of cube I would can use with the Superset?
Thanks!

**Comment by xrmx** [comment]
What about trying it and report back?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 249 days. Feel free to comment and request for this issue to be reopened.
