### ISSUE TITLE
AUTH_USER_REGISTRATION_ROLE for Multiple Roles

### ISSUE THREAD

**Issue by behanjc** [apache/incubator-superset#3276]
I see that multiple roles are supported when I look at Users when logged in an Admin account.
Given this, I am wondering if it's possible to configure the AUTH_USER_REGISTRATION_ROLE to assign multiple roles to the account upon registration (e.g. "Gamma","sql_lab"), as I haven't been able to figure it out.

I just want to confirm whether this is possible, otherwise I know a workaround would be to create my own single role with the appropriate permissions from the multiple roles.

**Comment by mistercrunch** [comment]
It's not too hard to customize the authentication in FAB. Here's an example of what we do at Airbnb. You can create and assign roles when user first login.
https://gist.github.com/mistercrunch/6d31af4a11c47edcedc1ba6ceb5f5fab

**Comment by enzo-dechaene** [comment]
Hi @behanjc have you figure it out if it is possible to configure multiple role ?
