### ISSUE TITLE
LOG_FORMAT is not applied to TimedRotatingFileHandler

### ISSUE THREAD

**Issue by io-german** [apache/incubator-superset#3294]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

If you enable *TimedRotatingFileHandler* the logs written to file are not properly formatted. On the other hand, console logs continue to use custom log format defined by **LOG_FORMAT** variable. 

As far as I can see custom handlers require formatters to be explicitly set. They don't use the one set in * basicConfig*.

### Superset version
0.19.0

### Python version
3.6.1

### Expected results
Logs in the log file should be formatted the same way as they are formatted in the console

### Actual results
Log files contain plain messages without timestamps, severity marks etc.

### Steps to reproduce

1. Enable file logging
```
ENABLE_TIME_ROTATE = True
TIME_ROTATE_LOG_LEVEL = 'DEBUG'
FILENAME = "path/to/log.file"
ROLLOVER = "midnight"
INTERVAL = 1
BACKUP_COUNT = 30
```
2. Start application
3. Check the log file

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 250 days. Feel free to comment and request for this issue to be reopened.

**Comment by konfusator** [comment]
Hello,

this is still the case in 1.3.0 and can be fixed via

```
@@ -62,6 +62,7 @@
                 interval=app_config["INTERVAL"],
                 backupCount=app_config["BACKUP_COUNT"],
             )
+            handler.setFormatter(logging.Formatter(app_config["LOG_FORMAT"]))
             logging.getLogger().addHandler(handler)
 
         logger.info("logging was configured successfully")
```
in utils/logging_configurator.py

**Comment by redwards101** [comment]
> handler.setFormatter(logging.Formatter(app_config["LOG_FORMAT"]))

Thanks for the fix.
I'm confused why a pull request has never been created for this obvious bug.
