### ISSUE TITLE
How can I build superset development environment in  windows 7？

### ISSUE THREAD

**Issue by l496749096** [apache/incubator-superset#3297]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
As stated in the documentation windows is not a supported platform.

**Comment by asdf2014** [comment]
Hi, @l496749096 . Sure, you can. There is my blog that noted how to build a development environment in windows. And how to remote debug superset. Hope that will help you. BTW, look forward to a new contributor. :D

[Development](http://yuzhouwan.com/posts/743#%e5%bc%80%e5%8f%91%e7%8e%af%e5%a2%83%e6%90%ad%e5%bb%ba) & [Remote Debug](http://yuzhouwan.com/posts/43687#%e5%ae%9e%e6%88%98%e6%8a%80%e5%b7%a7)

**Comment by mingchau** [comment]
@asdf2014 
我现在尝试在windows上对superset进行二次开发，跟随着官方文档一步一步的操作https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-a-python-development-environment

Start the Flask dev web server from inside your virtualenv.这一步的时候，文档中给的命令是
`FLASK_ENV=development superset run -p 8088 --with-threads --reload --debugger`

我是先在环境变量中设置了FALSK_ENV，然后在虚拟python环境中执行的
`python superset run -p 8088 --with-threads --reload --debugger`

但是返回的是
can't find '__main__' module in 'superset'

您能帮忙看看这个是什么问题吗?

**Comment by mingchau** [comment]
> @asdf2014
> 我现在尝试在windows上对superset进行二次开发，跟随着官方文档一步一步的操作https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-a-python-development-environment
> 
> Start the Flask dev web server from inside your virtualenv.这一步的时候，文档中给的命令是
> `FLASK_ENV=development superset run -p 8088 --with-threads --reload --debugger`
> 
> 我是先在环境变量中设置了FALSK_ENV，然后在虚拟python环境中执行的
> `python superset run -p 8088 --with-threads --reload --debugger`
> 
> 但是返回的是
> can't find '**main**' module in 'superset'
> 
> 您能帮忙看看这个是什么问题吗?
with command 
`flask superset run -p 8088 --with-threads --reload --debugger`
solved my problem.
