### ISSUE TITLE
How to create slices using Redshift Spectrum?

### ISSUE THREAD

**Issue by masterlittle** [apache/incubator-superset#3316]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Hi, I was wondering how to expose the redshift spectrum schemas to superset because I am unable to create slices as it requires a table name beforehand.
### Superset version
0.18.5

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 248 days. Feel free to comment and request for this issue to be reopened.
