### ISSUE TITLE
How can i get sqlalchmey query time logs ? Please mention the complete procedure.

### ISSUE THREAD

**Issue by AbrarMalik** [apache/incubator-superset#3317]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
For sql lab you they are stored in the Query object. For the superset vizualizations you have to add that tracking to the code yourself as i don't think we are tracking them. There's infrastrcture for tracking things in superset/stats_logger.py

**Comment by AbrarMalik** [comment]
What I have to change in superset/stats_logger.py ? I need these logs on in .txt file or terminal.

**Comment by xrmx** [comment]
I mentioned stats_logger.py  because if you want to make a generic thing a patch adding that could be applied to superset and you can just add your backend. If you need something quick and dirty just add prints...

**Comment by AbrarMalik** [comment]
I am tester not a developer so please provide the procedure how can i take profiling?

**Comment by xrmx** [comment]
@AbrarMalik you have to write code, find a developer :)

**Comment by mistercrunch** [comment]
Actually we log most page views in the "logs" table in the metadata database. We should ship a "Superset usage" dashboard along with the app. We have one internally that looks pretty neat. We also have one for Sql Lab usage as well.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 248 days. Feel free to comment and request for this issue to be reopened.

**Comment by CoryChaplin** [comment]
@mistercrunch any chance we could get this rolling with your sponsorship ?
