### ISSUE TITLE
the setup.py  file need to fix. 

### ISSUE THREAD

**Issue by feixialong** [apache/incubator-superset#3318]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

it is a litle problem,i find someone change the path static/assets,but the path in setup.py is also using.so,i think you need to fix it.
in the setup.py :
PACKAGE_DIR = os.path.join(BASE_DIR, 'superset', 'static', 'assets')
need to change as:
PACKAGE_DIR = os.path.join(BASE_DIR, 'superset', 'assets')

**Comment by xrmx** [comment]
static/assets is a link to assets. Are you on windows?

**Comment by feixialong** [comment]
i am on ubuntu14.04,the link can not work

**Comment by feixialong** [comment]
im wrong,when i delete the static,i can compile it. but ,superset can not running . some file depend on it
