### ISSUE TITLE
Already added slice(s) should be available/visible as checked in the 'Add Slices to dashboard' GUI.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3319]
### Superset version
Latest Version (0.19.0)

### Expected results
If a slice has been already added to a dashboard, then upon opening the add slice popup that added slice would be coming as selected.

### Actual results
currently, all the slices in the add slices popup GUI are coming as deselected or unchecked. 

### Steps to reproduce
- Create a dashboard 
- Go to add slices popup GUI 
- Add single or multiple slice(s) to the dashboard 
- Now again open the add slice pop up GUI, this time all the slices would be coming as unchecked/deselected.

**Comment by xrmx** [comment]
What's latest version? Please use a release or a git hash

**Comment by NaukhaizAhmad** [comment]
It's 0.18.2
Thanks.

**Comment by xrmx** [comment]
Then 0.18.2 is not the latest version as now.

**Comment by NaukhaizAhmad** [comment]
So, should i test it on the latest one first?

**Comment by xrmx** [comment]
It's better to report bugs againt latest release or latest master because they can be already be fixed.

**Comment by NaukhaizAhmad** [comment]
Thanks, i'll verify this issue on the latest release.

**Comment by NaukhaizAhmad** [comment]
This issue is still producing on version 0.19.0
Thanks.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 248 days. Feel free to comment and request for this issue to be reopened.

**Comment by NaukhaizAhmad** [comment]
This is a valid ticket, so please change its state to 'open'
