### ISSUE TITLE
Select all checkbox will make the show,delete and edit record buttons blank/white.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3321]
### Superset version
0.19.0

### Expected results
these buttons should not get blank/white, they should display the icons.

### Actual results
these buttons would come as blank/white (screen shot is attached)
![selection](https://user-images.githubusercontent.com/29655292/29408212-c8a8ef36-8360-11e7-8538-4f55302c2900.png)

### Steps to reproduce
go to list roles tab 
and select/check the select all checkbox
all the buttons would become blank/white (screen shot is attached)
This issue is observing across the application.

**Comment by xrmx** [comment]
Any error in the browser? How have you installed superset?

**Comment by NaukhaizAhmad** [comment]
Thanks for your reply.
There is no error on the browsers console.
I am using python 2.7 and have a development setup.
here is the installation link ,
https://superset.incubator.apache.org/installation.html

Please feel free let me know in case of any confusion.
