### ISSUE TITLE
Legends for m1 and m2 in sunburst 

### ISSUE THREAD

**Issue by shyam2794** [apache/incubator-superset#3323]
Hi All , in the sunburst chart is there anyway to provide legends for the m1 and m2 parameters . we are able to see the metrics provided for m1 and m2 only when we explore slice and not in the dashboard.I will be very usefull if we have the legend . 
### Superset version
version - 0.18.5

### Expected results
The metrics which we have specied  in the m1 and m2 parameter must appear  as legend .eg if i have chosen the m1 value as metric revenue and m2 value as patient volume . In the sunburst i expect it to appear as a legend in the bottom as ( m1:revenue and m2:patient Volume )  

### Actual results
I think there is no option to display the m1 and m2 parameters as legends in the sunburst . 

### Steps to reproduce
Try creating a suburst chart in the slice and provide two metric for m1 and m2 . Save the slice to the dashboard .

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 247 days. Feel free to comment and request for this issue to be reopened.
