### ISSUE TITLE
Error when group or breakdown by dimensions with Unicode characters

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3325]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.19.0

### Expected results
Grouping or breakdown shows the dimension values in Unicode

### Actual results
Error 'ascii' codec can't encode characters in position 473-474: ordinal not in range(128) happen

### Steps to reproduce

1) create a bar chart diagram
2) add breakdowns a dimensions with any Unicode value

--- OR ---

2) make a grouping by dimensions with any Unicode value

Error happen:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/viz.py", line 239, in get_payload
    df = self.get_df()
  File "/usr/local/lib/python2.7/site-packages/superset/viz.py", line 79, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 554, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 326, in get_query_str
    compile_kwargs={"literal_binds": True}
UnicodeEncodeError: 'ascii' codec can't encode characters in position 473-474: ordinal not in range(128)

**Comment by xrmx** [comment]
No need to report two times the same issue :)

**Comment by izetex** [comment]
For me it is not the same issue, as this first was related to metadata, while this one with data in storage

**Comment by xrmx** [comment]
The stacktrace is the very same, please close this one.
