### ISSUE TITLE
Inconsistency with the timezone in time graphs versus calendar

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3326]
Make sure these boxes are checked before submitting your issue - thank you!

### Superset version
Superset 0.19.0

### Expected results
Shows results in the timezone, provided in response

### Actual results
In time graphs it shows the results in the timezone, provided in response
However, in calendar heatmap view it converts the time to local time zone

### Steps to reproduce

Create the slice with temporar column
Compare visaualizations in time series versus calendar heat map

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 248 days. Feel free to comment and request for this issue to be reopened.
