### ISSUE TITLE
Select all checkbox won't work correctly, if browser's 'go back' button is pressed.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3334]
### Superset version
0.19.0

### Browser
Chrome 60 & 61

### Expected results
Select all checkbox should work properly, as it was before pressing the browsers go back button.

### Actual results
select all check box starts behaving abnormally.

### Steps to reproduce
go to dashboards tab 
click the select all check box
all the dashboards would get selected 
now open any individual dashboard for edit/show
now from this dashboard configuration window, press the browser 'go back' button
the check boxes would be coming as checked, but rows selection won't be visible
now try checking/unchecking the select all checkbox
select all checkbox would start behaving abnormally.
screen shot is attached , displaying both the behavior.
![selectall_behavior](https://user-images.githubusercontent.com/29655292/29446229-835d4f36-8404-11e7-9db0-824e82f84692.png)
 
This issue is producing across the application.

**Comment by xrmx** [comment]
Isn't this the very same issue you reported earlier in #3321?

**Comment by NaukhaizAhmad** [comment]
No No!
It's related to functionality of the select all feature.
Select all checkbox behaves abnormally if repeated the above mentioned scenario.
see the screen shot displaying the same i.e. misbehaving select all checkbox.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 247 days. Feel free to comment and request for this issue to be reopened.
