### ISSUE TITLE
Unable to directly create table from query ( feature request)

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3336]
This is a feature request
I really like the idea of SQL editor embedded in Superset and like the idea of table.slices
However the way how they are related in UI makes very hard to operate them

### Superset version
Superset 0.19.0

### Expected results
Table is created from query with the name of query

### Actual results

1) Need a lot of unnesseary steps
2) No direct way to create a table from query
3) Inconsistency around saved queries - unnamed queries are not 'named'
4) No way to manage table from query view. For example, adding a new result column does not automatically add column to table, and i have to manually add it.
5) re-saving query will create a new query instead of overwriting existing one

### Steps to reproduce
1) Go to SQL editor and compose a query
2) Save it. The first issue here is that the Tab for query is NOT renamed to the name i gave a query.
However, if i open a query from Saved query view, the same query appears with the correct name. 
3) Click Visualize on results. Here there is another inconsistency - the name of data source again does not reflect the name of saved query.
4) Options for visualization is very limited. However rename the datasource (again!) and press OK
5) now table is created and you can create slices from it

Too many steps, and they are not evident. The direct way of creating table (through "new table") does not save time, as i have to manually generate all columns

If you have such a great instrument as SQL query, why not use it to manage tables?

**Comment by xrmx** [comment]
PR welcome of course!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 247 days. Feel free to comment and request for this issue to be reopened.

**Comment by manoloah** [comment]
ISSUE: 
Table is created from query with the name of query

Please can we reopen this issues. Currently it is a pain to have to save the query, then go to saved tables and open it again. It should automatically rename the table in the query viewer as the name saved for the query.

**Comment by mikaandria** [comment]
Hi,
Can we reopen this issue, it is still a pain to create a table from a query (when performing join for instance).

**Comment by bkarlson** [comment]
Anyone considered using SQL views for this purpose? This removes many limitations (such as column names with special characters) makes it very easy to change query without need to re-create chart etc, much easier workflow imho.
