### ISSUE TITLE
Calendar Heatmap callout hidden on dashboard

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3340]
Make sure these boxes are checked before submitting your issue - thank you!

### Expected results
I see the callout is visible

### Actual results
It is overlayed when placed on dashboard ( see attachment screen )

### Steps to reproduce

1) Create calendar heat map and place on dashboard.
2) click on cell
![cal](https://user-images.githubusercontent.com/30741870/29485497-91e77040-84db-11e7-994a-cfba58a825ec.png)

**Comment by lethe3000** [comment]
any update?
is there a way to set top margin?

**Comment by graceguo-supercat** [comment]
#4268 fixed this issue.
