### ISSUE TITLE
Chord popups sometimes not opening on dashboard

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3343]
### Superset version
Superset 0.19.0

### Expected results
When click ( or mouse over ) the chord diagram i see information in popup about underlying beam

### Actual results
When placed on dashboard, it almost never work as expected

### Steps to reproduce

Create chord diagram, place on dashboard and mouse over it

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 246 days. Feel free to comment and request for this issue to be reopened.

**Comment by alvaropc** [comment]
Hi!
I'm having exactly the same problem.
No popup is being showed anytime.
Also I have no legends and some label names are not being showed in the base of the diagram just exactly like in your gallery example:
![image](https://user-images.githubusercontent.com/25221111/41921512-517663c2-7963-11e8-8a19-7f324b4f72e6.png)
