### ISSUE TITLE
[Dashboard/Slices] Upon just clicking on the 'move chart' option of a slice, informative prompt appears saying "You have unsaved changes. Click the save button on the top right to save your changes."  

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3348]
### Superset version

0.19.0

### Expected results
Nothing should happen, no prompt should appear for saving the dashboard as there is no changes made.

### Actual results

upon just clicking the 'move chart' option of a slice , a prompt is appearing saying,
"You have unsaved changes. Click the save button on the top right to save your changes."

### Steps to reproduce
[Dashboard/Slices] Upon just clicking on the 'move chart' option of a slice, informative prompt appears saying "You have unsaved changes. Click the save button on the top right to save your changes."  

Create a dashboard having any slice 
now open the saved dashboard 
click on the 'move chart' option of the slice
upon clicking the mentioned prompt would appear.
![movechart](https://user-images.githubusercontent.com/29655292/29517877-8293ca38-8690-11e7-80ff-16bc8fbe857b.png)

**Comment by mistercrunch** [comment]
This assumes you move the layout [even though maybe you didn't really]. I guess we **could** compare the positioning before and after and only show the message if it has changed. I doubt this will make to the top of anyone's priority list as it's pretty minor...

**Comment by NaukhaizAhmad** [comment]
Yeah! it would be of lowest priority, BUT a bug is a bug :)
'Save' prompt should only appear if any change(s) is made.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 243 days. Feel free to comment and request for this issue to be reopened.

**Comment by NaukhaizAhmad** [comment]
This is a valid ticket, so please change its state to 'open'
