### ISSUE TITLE
Is Jun 22 Release The Latest Release?

### ISSUE THREAD

**Issue by April-Xue** [apache/incubator-superset#3350]
I noticed that there is no new release after Jun 22, which is quite unusual. After Jun 22, there are still lots of new merged pull requests. And previously a new version will be released every two/three weeks. Is Jun 22 release the real latest one? Thanks.

**Comment by mistercrunch** [comment]
https://pypi.python.org/pypi/superset
`0.19.0` was released on 2017-08-02
