### ISSUE TITLE
(Feature request) allowing for top X and Others

### ISSUE THREAD

**Issue by maartenvanwauwe** [apache/incubator-superset#3359]
in the series limit (for a slicer) it would be great to have the option to thick the "and others" button. To allow for top X and have all others put in 1 "others" group. Very handy when you have a lot of series that are close to each other (because only top X would could lead to wrong interpretations in this case).

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 242 days. Feel free to comment and request for this issue to be reopened.

**Comment by maartenvanwauwe** [comment]
to be honest, this is something that is often requested for management slides. so if you want to convince managers that look at data this is a must have...
