### ISSUE TITLE
Superset In-memory engine

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#3361]
An in-memory engine on superset would be super helpful in reducing the number of queries that gets fired concurrently on the back end database. This in memory engine can be used to keep data in memory and run queries against it. This will improve speed and efficiency.

**Comment by xrmx** [comment]
Well you can use in memory sqlite right now :) jokes aside see @mistercrunch comment in #3302 . Unless you are going to write a connector please close, maybe we can rename #3302.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 242 days. Feel free to comment and request for this issue to be reopened.
