### ISSUE TITLE
Dashboard ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by pjalleda** [apache/incubator-superset#3370]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.0

### Expected results
to be able to open the http:x.x.x.x:8088 dashboard

### Actual results
timing out when i tried to open. I started the superset with -t 300 as well, still not working.

### Steps to reproduce

installed it on my local desktop vm and followed installation process as in the apache website.

**Comment by xrmx** [comment]
Looks you have missed something in the setup of your vm like forwarding ports...

**Comment by pjalleda** [comment]
I enabled 
# Controls IP packet forwarding
net.ipv4.ip_forward = 1
 still not working ... do you think i missed anything else?

**Comment by xrmx** [comment]
I didn't meant you need to enable port forwarding, just to check that the ip:port you type in the browser is reachable. To make things clear: is it just the dashboard or you cannot reach anything?

**Comment by pjalleda** [comment]
Sorry my bad.. yes I am able to open the centos test page from my desktop and i see the port open when i do netstat: 
# netstat -na | grep 8088
tcp        0      0 0.0.0.0:8088                0.0.0.0:*                   LISTEN
am i checking it right?

**Comment by pjalleda** [comment]
When i removed firewall, it worked. this is just for testing, so i am fine with that. Thanks

**Comment by xrmx** [comment]
Then close it.
