### ISSUE TITLE
Advanced analytics processing is not applied to the comparison time series.

### ISSUE THREAD

**Issue by mxmzdlv** [apache/incubator-superset#3372]
Selected options in advanced analytics section are not applied to the "time shifted" time series, making it impossible to do any comparison. E.g., see https://github.com/apache/incubator-superset/issues/2481

I am not sure if it is intended, but if it is a bug – I've created a pull request.

**Comment by xrmx** [comment]
If you are going to open a PR after two minutes, there's no need to open an issue too. Especially if you already fixing an open bug :)

**Comment by mxmzdlv** [comment]
Sorry, just thought it might need more clarification

**Comment by xrmx** [comment]
Commit messages are usually a good place to write where things needs clarification
