### ISSUE TITLE
Add ability to custom order bars on a bar chart

### ISSUE THREAD

**Issue by jfeng15** [apache/incubator-superset#3380]
Users have requested the ability to custom order the bars on a bar chart.  Seems like a reasonable request.

Airbnb Jira: https://jira.airbnb.biz/browse/PRODUCT-19523

**Comment by mistercrunch** [comment]
@jfeng15 as in user-specified or as in either sorted by height or by name?

**Comment by jfeng15** [comment]
@mistercrunch, in this case the user request was user-specified.  that said, in order of priority from highest to lowest, it should be:
1. "sort ascending" and "sort descending" by value for bar charts 
2. "sort ascending" and "sort descending" by name for bar charts 
3. custom order for bar charts

**Comment by mistercrunch** [comment]
Let's leave `3.` out of scope of this specific task.

**Comment by Towhid1** [comment]
Is there any hack to do bar chart using ascending sort?

**Comment by vylc** [comment]
By default, bar chart sorts descending by value, and there is a way to sort alphabetically by label on x-axis. 
Seems like we are missing
1. Sort ascending by Y-axis
2. Sort descending by x-axis
@mistercrunch

**Comment by jagyei** [comment]
Has this issue duplicated elsewhere, or is this ticket just stale?

This really should be included on Superset Bar Chart.
