### ISSUE TITLE
Support Elasticsearch and HBase?

### ISSUE THREAD

**Issue by iboumedien** [apache/incubator-superset#3381]
Guys, what an awesome project. Are you planning to support Elasticsearch or HBase?
Best regrads

**Comment by xrmx** [comment]
The github issues is not the better format for open ended questions. Anyway there's a PR for ElasticSearch and you should be able to connect to hbase trough hive. If we don't have specific in the wiki you are very welcome to try and report back what you have found.

**Comment by mistercrunch** [comment]
I'm hoping I'll find time to add elastic support soon-ish.

**Comment by tothandor** [comment]
It may help, there's an ES-SQL interface available [here](https://github.com/NLPchina/elasticsearch-sql/).
