### ISSUE TITLE
[Hive]slice edit: invalid function from_iso8601_date

### ISSUE THREAD

**Issue by fycoopery** [apache/incubator-superset#3383]
Hi everyone!
    I'm using Hive as my database, superset 0.19.1 from pip install and the connection is fine. But when I edit the slice and selected the time as below:
     
![image](https://user-images.githubusercontent.com/17850925/29800060-6d0e4d86-8c9a-11e7-9ccb-8600f61a388f.png)

and

then the query shows as:

![image](https://user-images.githubusercontent.com/17850925/29800094-941023e6-8c9a-11e7-9768-380ae0113fa7.png)

the error goes like this:

![image](https://user-images.githubusercontent.com/17850925/29800112-a74c5cf4-8c9a-11e7-8be8-87a3b01df0ab.png)

can anyone fix this?
thank you all.

**Comment by mistercrunch** [comment]
What does your connection string look like ?`from_iso8601_date` should only come out when using Presto or Athena.

**Comment by fycoopery** [comment]
@mistercrunch 
My connection string looks like this:
![image](https://user-images.githubusercontent.com/17850925/29806191-795623ae-8cc0-11e7-98a2-2b8f32cb28be.png)

**Comment by pjalleda** [comment]
@fycoopery 
i am having same issue. Were you able to resolve?

**Comment by pjalleda** [comment]
@xrmx 
So, do you have a solution for this? or is this a bug?

**Comment by fycoopery** [comment]
@pjalleda 
Quick fix for hive:

Since hive is my only data source , I don't have to connect to presto.
So I hard-coded the /superset/db_engine_specs.py in my python lib path, changed the convert_dttm function to this:
![image](https://user-images.githubusercontent.com/17850925/29851267-c771acde-8d65-11e7-808a-a27a9b65f960.png)
from_iso9601_date(timestamp) deleted.
and it works fine for hive now. 

But when it comes to presto, should cause some other problem.

**Comment by mistercrunch** [comment]
#3394 should fix it. We typically only use Presto in the "explore view" at Airbnb since our old hive is just way to slow  and would probably timeout even if we just ran `SELECT 1`. For those with faster hive (Tez?) this fix should do it

**Comment by fycoopery** [comment]
Thanks @mistercrunch , tested, this will do.
![image](https://user-images.githubusercontent.com/17850925/29853599-716d280a-8d73-11e7-8028-1260ed7c366d.png)
