### ISSUE TITLE
[SqlLab] chose Schema ERROR WHILE FETCHING TABLE LIST

### ISSUE THREAD

**Issue by Jonecmnn** [apache/incubator-superset#3385]
When I chose Schema, it was C##_BIGDATE 
Page UI will Report errors
ERROR WHILE FETCHING TABLE LIST
Found Schema have ## Symbol will Report errors
Is there any way to solve it?

![image](https://user-images.githubusercontent.com/23417964/29814458-f2da8cfa-8cdf-11e7-81ca-5327da25b5bf.png)

**Comment by xrmx** [comment]
Could you please fill the issue template as requested?
