### ISSUE TITLE
 Invalid function 'from_iso8601_timestamp'

### ISSUE THREAD

**Issue by pjalleda** [apache/incubator-superset#3386]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

I am trying to create a time series graph. source is hive table with time column as "timestamp" type... it is giving me below error..
the table output looks like this:   
2017-08-27 00:00:00

### Superset version
0.19.0

pyhive.exc.OperationalError) TExecuteStatementResp(status=TStatus(errorCode=10011, errorMessage=u"Error while compiling statement: FAILED: SemanticException [Error 10011]: Line 4:27 Invalid function 'from_iso8601_timestamp'", sqlState=u'42000', infoMessages=[u"*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException [Error 10011]: Line 4:27 Invalid function 'from_iso8601_timestamp':28:27", u'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:335', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:148', u'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:226', u'org.apache.hive.service.cli.operation.Operation:run:Operation.java:276', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:468', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:444', u'sun.reflect.GeneratedMethodAccessor295:invoke::-1', u'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', u'java.lang.reflect.Method:invoke:Method.java:498', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', u'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', u'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', u'java.security.AccessController:doPrivileged:AccessController.java:-2', u'javax.security.auth.Subject:doAs:Subject.java:422', u'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1724', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', u'com.sun.proxy.$Proxy38:executeStatement::-1', u'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:273', u'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:506', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1317', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1302', u'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', u'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', u'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', u'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', u'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', u'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', u'java.lang.Thread:run:Thread.java:745', u"*org.apache.hadoop.hive.ql.parse.SemanticException:Line 4:27 Invalid function 'from_iso8601_timestamp':53:26", u'org.apache.hadoop.hive.ql.parse.TypeCheckProcFactory$DefaultExprProcessor:getXpathOrFuncExprNodeDesc:TypeCheckProcFactory.java:936', u'org.apache.hadoop.hive.ql.parse.TypeCheckProcFactory$DefaultExprProcessor:process:TypeCheckProcFactory.java:1276', u'org.apache.hadoop.hive.ql.lib.DefaultRuleDispatcher:dispatch:DefaultRuleDispatcher.java:90', u'org.apache.hadoop.hive.ql.lib.DefaultGraphWalker:dispatchAndReturn:DefaultGraphWalker.java:95', u'org.apache.hadoop.hive.ql.lib.DefaultGraphWalker:dispatch:DefaultGraphWalker.java:79', u'org.apache.hadoop.hive.ql.lib.DefaultGraphWalker:walk:DefaultGraphWalker.java:133', u'org.apache.hadoop.hive.ql.lib.DefaultGraphWalker:startWalking:DefaultGraphWalker.java:110', u'org.apache.hadoop.hive.ql.parse.TypeCheckProcFactory:genExprNode:TypeCheckProcFactory.java:214', u'org.apache.hadoop.hive.ql.parse.TypeCheckProcFactory:genExprNode:TypeCheckProcFactory.java:158', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genAllExprNodeDesc:SemanticAnalyzer.java:10812', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:10768', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:10736', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genFilterPlan:SemanticAnalyzer.java:2892', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genFilterPlan:SemanticAnalyzer.java:2873', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genBodyPlan:SemanticAnalyzer.java:8937', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:9869', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:9748', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genOPTree:SemanticAnalyzer.java:10395', u'org.apache.hadoop.hive.ql.parse.CalcitePlanner:genOPTree:CalcitePlanner.java:334', u'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:10406', u'org.apache.hadoop.hive.ql.parse.CalcitePlanner:analyzeInternal:CalcitePlanner.java:216', u'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:230', u'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:464', u'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:320', u'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1219', u'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1213', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:146'], statusCode=3), operationHandle=None)

Thanks..

**Comment by xrmx** [comment]
This is a dup of #3383, please close.
