### ISSUE TITLE
SQL Injection flaw fixed in new Flask-AppBuilder v1.9.4

### ISSUE THREAD

**Issue by JherekCorn** [apache/incubator-superset#3388]
This is a request to update incubator-superset with the new Flask-AppBuilder v1.9.4 to correct a sql injection issue. details can be found here https://github.com/dpgaspar/Flask-AppBuilder/issues/544

**Comment by xrmx** [comment]
And 0.19.1 has already been released with that fixed. Please close.

**Comment by JherekCorn** [comment]
Thanks for the info, appreciate it
