### ISSUE TITLE
Can this repo's releases be tagged again?

### ISSUE THREAD

**Issue by amancevice** [apache/incubator-superset#3400]
since `0.18.5` this repo hasn't been tagged with a release. It makes it difficult to pin down what is going in each version without tags. Thanks.

**Comment by mistercrunch** [comment]
I added the missing tags

**Comment by amancevice** [comment]
Thanks, @mistercrunch

**Comment by amancevice** [comment]
@mistercrunch fyi, the tags you created disappeared and `0.20.0` is missing as well.
