### ISSUE TITLE
Allow changing the visualization timeout from within Superset's settings

### ISSUE THREAD

**Issue by h5rdly** [apache/incubator-superset#3410]
Hi,

First of all - Awesome project, cheers.

The issue: 
Though the timeout message suggests that one is to compact his data further, it may still come handy to be able to allow a visualization to take another minute. 
A client using Superset shouldn't have to dig into js files, find the build script, install node, recompile etc. just to let his visualization run a bit longer.  
I was wondering whether it would agreeable to add this timeout setting to a relevant Superset panel, instead of having one wander through Supersets' entrails and use compilers and build tools to modify it.

Thanks,
Eli

**Comment by xrmx** [comment]
I don't think superset has clients, it has users. The ui timeout has been synced to the backed, i think this is a dup of #3030 https://github.com/apache/incubator-superset/issues/3030

**Comment by mistercrunch** [comment]
It's a configuration element in `superset_config.py` now

**Comment by h5rdly** [comment]
Awesome, thank you!  For those stumgling on this post, the flags (with default values) are  - 
SUPERSET_WEBSERVER_TIMEOUT = 60
SQLLAB_TIMEOUT = 30

For async queries - 
SQLLAB_ASYNC_TIME_LIMIT_SEC = 60 * 60 * 6

full list of flags - 
https://github.com/apache/incubator-superset/blob/master/superset/config.py

**Comment by pwolter** [comment]
Those are deprecated as the referred file mentions. You have to change:

_SQLLAB_TIMEOUT = config.get('SQLLAB_ASYNC_TIME_LIMIT_SEC', 600)_

In **sql_lab.py** if you want to increase the 60 secs timeout for the visualizations.
