### ISSUE TITLE
Add ability to custom set colors in charts

### ISSUE THREAD

**Issue by jfeng15** [apache/incubator-superset#3420]
We recently launched a new feature enabling users to select certain color schemes for charts based on categorical colors (http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d).  

A follow on feature that would be useful is the ability to custom set the color of individual values (bars, lines, etc.) within charts.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 228 days. Feel free to comment and request for this issue to be reopened.
