### ISSUE TITLE
Make it possible to add description to a slice during creation

### ISSUE THREAD

**Issue by timifasubaa** [apache/incubator-superset#3421]
It is difficult to understand what a slice is trying to convey when the title or the header is often jargon. The way around this is to add a description to the slice so it's more accessible to people who do not understand the jargon. While this feature currently exists, users cannot add description while creating the slice. They have to edit after creation if they want to add a description. (and they often don't). This PR should make it very easy to do so slices are more accessible across boar. 

Assigned to: @timifasubaa

**Comment by xrmx** [comment]
If you are going to do a PR shortly there's no need to open an issue. If people don't add a description I can't see how you can force them do so though.
