### ISSUE TITLE
There is no data to drill down，Request to add

### ISSUE THREAD

**Issue by tzc920823** [apache/incubator-superset#3426]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Steps to reproduce

There is no data to drill down，Request to add

**Comment by xrmx** [comment]
The issue template should be filled not left empty :)

**Comment by tzc920823** [comment]
There is no data to drill down，Request to add

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 227 days. Feel free to comment and request for this issue to be reopened.
