### ISSUE TITLE
When a dimension have 'NULL', error throw "unorderable types: str() > int()" 

### ISSUE THREAD

**Issue by ToonoW** [apache/incubator-superset#3432]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Superset 0.19.1

### Expected results

A normal  Time Series - Line Chart.
Like this
![](https://ws4.sinaimg.cn/large/006tNc79gy1fjc51ljywaj31kw0o57da.jpg)

### Actual results

![](https://ws2.sinaimg.cn/large/006tNc79gy1fjc52l92kej31kw0mn422.jpg)

### Steps to reproduce

1. I have a dimension have 'NULL'. What I mean is not all row have value.
2. Use this dimension as Group By.
3. Query.

### More
I add a Filters into this form. The Filters is same dimension is 'event_name', relation is '!=', **but the value I did not input anything.**

Then, I can see the expected results.

I guess the reason is that default fill 0 into NULL, but my dimension is TEXT. Then occur `unorderable types: str() > int()`.

And this is similar issue.
[#3029](https://github.com/apache/incubator-superset/issues/3029)

**Comment by xrmx** [comment]
This is exactly the same issue, no need to duplicate it please close.

**Comment by ToonoW** [comment]
@xrmx get it.

**Comment by ToonoW** [comment]
@xrmx I think we only can use Filters to avoidance this error.
