### ISSUE TITLE
'twophase' is an invalid keyword errors connecting to Oracle

### ISSUE THREAD

**Issue by zerodf** [apache/incubator-superset#3447]
I had an error installing and configuring Superset.  

The error was attributable to issues with [sqlalchemy](https://github.com/zzzeek/sqlalchemy) and cx_Oracle.  So, feel free to close this issue.  However, I felt it was worth documenting here, so that people could see the work around.  

### Superset version
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.19.1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

```
sqlalchemy.__version__
'1.1.9'
```

```
cx_Oracle.version
'6.0.2'
```

### Expected results
When I entered an Oracle connection string with the following format: 
oracle://**USER**:**PASSWORD**@**HOST**:**PORT**/**SID**
I expected to be able to connect to Oracle

### Actual results
Errors:
```
'twophase' is an invalid keyword argument for this function
```

### Temporary Work around
I was able to install cx_Oracle version 5.1.3 and these errors were resolved.  I believe you are refactoring for cx_Oracle 6+, so reverting to the older version of cx_Oracle is a temporary measure.

**Comment by xrmx** [comment]
Am pretty sure this is unrelated to superset, more of a sqlalchemy backend issue. Please post the full backtrace though.

**Comment by wei167** [comment]
update the sqlalchemy

**Comment by mistercrunch** [comment]
Closing for now, as it's unrelated but please feel welcome to post work around or to document which lib version are compatible/incompatible

**Comment by zerodf** [comment]
@mistercrunch, 

No problem.  Documenting a temporary work around was my original intent behind opening this thread.  

Our installation is currently working with:
cx_Oracle version 5.1.3
sqlalchemy version 1.1.9

If I have time, I'll see if I can get some other combinations working per @wei167's suggestion

**Comment by akash213** [comment]
is this issue have any resolution ? I am still getting the error. see below -
"ERROR:root:'twophase' is an invalid keyword argument for this function"
I am using cx-oracle 6+
Any help?

**Comment by rahulsingh303** [comment]
use this and it works for us :) 
oracle+cx_oracle://<user>:<pwd>@<host>:<port>/<schema>?allow_twophase=false

Regards
Rahul Singh

**Comment by syzuhdi** [comment]
rahul,
what is your cx_Oracle version ?

**Comment by pradeepsurya2010** [comment]
I have got the same issues, I found two SQL Alchemy installations in the Python PATH. Remove one of the installation and tested, it is working as expected.
