### ISSUE TITLE
CSV export from dashboard does not use filtering

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#3455]
- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

### Expected results
When exporting slice directly from dashboard, dashboard filtering should be applied to CSV

### Actual results
Dashboard filter does not apply to exported CSV

### Steps to reproduce
1. Create dashboard
2. Add filter visualisation
3. Add any other visualisation
4. Open dashboard, apply filtering
5. Export CSV from dashboard

Looks like fix applied in https://github.com/apache/incubator-superset/issues/1304 does not use dashboard filtering

**Comment by JulieRossi** [comment]
Hi ! We have noticed this problem too and it would be really helpful if it was solved. 
The dashboard filter does not apply either when you `explore` the slice from the dashboard view. I guess they are related matters.

**Comment by mistercrunch** [comment]
It should be fixed as of https://github.com/apache/incubator-superset/pull/3461
