### ISSUE TITLE
Sort By Creator crashed for dashboards, slices, databases panel

### ISSUE THREAD

**Issue by Jie-Yang** [apache/incubator-superset#3462]
### Superset version
0.19.0 & 1.9.1

### Expected results
items can be sorted asc or desc by columns

### Actual results
page crashed, and error as below:
![image](https://user-images.githubusercontent.com/2885095/30431989-345c99dc-9958-11e7-8f9a-2e23f736d079.png)

### Steps to reproduce
click 'Creator' to sort results in any table of dashboards, slices, or database.

columns having the same error:
slices panel: slice, creator
database panel: backend, creator
dashboard panel: creator

**Comment by xrmx** [comment]
Please reproduce with latest version.

**Comment by Jie-Yang** [comment]
Thanks. I have just tried with 1.9.1, and still have the same problem.

beside sorting by creator, there are other columns also have the same problem:
slices panel: slices, creator
database panel: backend, creator
dashboard panel: creator

**Comment by mistercrunch** [comment]
Seems like a new bug with the `@renders` decorator in FAB documented here:
http://flask-appbuilder.readthedocs.io/en/latest/advanced.html#custom-fields

Would you mind opening an issue on the Flask-AppBuiler repo referencing this issue?

**Comment by Jie-Yang** [comment]
@mistercrunch 
Thanks, and I have put it on FAB.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 219 days. Feel free to comment and request for this issue to be reopened.
