### ISSUE TITLE
Fab manager issue.

### ISSUE THREAD

**Issue by niranjanfall2017** [apache/incubator-superset#3465]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results

Is there any tutorial video where I can see how to install superset on windows? I am not able to do it. It is hard.
### Steps to reproduce
i typed fabmanager create-admin --app superset in my command prompt.
Then I received the message: 
fabmanager is not recognized as an internal or external command.

**Comment by xrmx** [comment]
Superset is not supported on windows, on top of this fabmanager is a flask appbuilder tool not a superset one.

**Comment by niranjanfall2017** [comment]
thanks. Could you please tell me if I could use it any other platform other Ubuntu? If so is there any tutorial video to download. Any inputs would be highly helpful.
