### ISSUE TITLE
Feature: Drill down

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#347]
Hi,

Is there any entry on the roadmap to add drill down functionality to existing vizs (maybe table, map, ..) ?
Like:
![image](https://cloud.githubusercontent.com/assets/767180/14518051/327ed5a8-0214-11e6-9ba9-1e1215f2e7c1.png)

Thanks

**Comment by mistercrunch** [comment]
The framework could provide hooks for contextual menus on metrics and dimensions, individual visualizations would have to implement them individually. 

There's definitely a lot rich interactive features that move the needle towards a more complex contract between the framework and individual visualizations. While this is nice, it makes it harder to add new visualization to the framework. 

Maybe individual visualization can have different level of support for the framework's more advanced features (like contextual menus), and grow that over time. The downside of that is an uneven user experience across visualizations, where you might expect to be able to right click on the treemap, but the contextual menu hasn't been implemented for that specific visualization yet...

It's important for me to keep the contract simple so that we can grow a wide array of visualizations. 

@williaster

**Comment by gbrian** [comment]
Yep, it's a big challenge, I think clear JS API (https://github.com/airbnb/caravel/issues/216#issuecomment-204276738) will help. Any advance on this ? 
Here's how Microstrategy's HTML5 viz API works it is a good example IMO: https://lw.microstrategy.com/msdz/MSDL/10/docs/DevLib/sdk_viz_HTML5/index.html

**Comment by daniloaburto** [comment]
+1

**Comment by whoishu** [comment]
+1

**Comment by kingo55** [comment]
Wouldn't the Pivot table be a good starting point?

e.g. Use some pre-defined columns - click an expand button to go slice by the next level.

**Comment by gregroberts** [comment]
+1 for this :D even if only for a subset of viz types.

**Comment by axelbellec** [comment]
+1 Really interesting feature

**Comment by gehuazhen** [comment]
+1 iwe really need it

**Comment by XavierDeLapeyre** [comment]
+1 we really need it.
Any visibility on its implementation?

**Comment by xrmx** [comment]
If you people really need it nobody is stopping you to do the work, thanks!

**Comment by mistercrunch** [comment]
This is complex enough that it would require starting with a design proposal.

**Comment by claycrosby** [comment]
+1 we need it

**Comment by godois** [comment]
+1 we really need it

**Comment by celaviaa** [comment]
+1 And we need it too

**Comment by rpwils** [comment]
to @mistercrunch comment, what would a design look like. We would be happy to help on parts of this feature if we could get input on the design

**Comment by yuhai1023** [comment]
+1 we need it  too

**Comment by rjazhenka** [comment]
+1

**Comment by beankylla** [comment]
+10!

**Comment by rpwils** [comment]
Can someone explain how they would want this feature to work?  We have thought about add the ability to select a attribute on one slice and then right click and select drill and have it open up a difference slice filtered on the value selected in the original slice.  make sense? this would require someone pre building both slices and how they connect.

**Comment by mistercrunch** [comment]
To support this and "cascading filters", Superset needs to know about dimension hierarchies. I suspect hierarchies for cascading filter will become a reality before the in-chart right-click context menu with a drill down option.

**Comment by rpwils** [comment]
Is anyone actively working on cascading filters

**Comment by beankylla** [comment]
@csc5k this is exaaactly what is needed.

**Comment by rzlmma** [comment]
+1

**Comment by cloga** [comment]
+1

**Comment by fabiorhs** [comment]
+1

**Comment by zpanderson** [comment]
+1

**Comment by razakpm** [comment]
+1

**Comment by devon-cliqz** [comment]
+1

**Comment by vinaybabunaidu** [comment]
+1

**Comment by gogitub** [comment]
Any inputs on Drilldown option? Appreciate if any references as well..

**Comment by junlincc** [comment]
#12148
dashboard native filter and cascading filter are available for testing!! thanks in advance for feedback, comments, critics, love and support!! 

drilldown is coming soon too

**Comment by laveenamurjani789** [comment]
Hi Team, Is drill down functionality available now?

**Comment by zpanderson** [comment]
@junlincc Looking at the public roadmap I don't see anything that specifically references drilldown support. Do you have any link to design proposal or roadmap item for drilldown?
