### ISSUE TITLE
NVD3 chart tooltips do not disappear when changing viz

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3471]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

### Expected results
Tooltips displayed when hovering over NVD3 charts (e.g. Time Series - Percent Change, Dual Axis Line Chart) should always disappear after switching to another visualization.

### Actual results
When switching to some visualizations, e.g. Calendar Heatmap or Treemap, the tooltip will not disappear and remain stuck to the screen:
![image](https://user-images.githubusercontent.com/15016832/30495224-0f4ded96-9a00-11e7-95ac-396f74aff9e8.png)
The tooltip __does disappear__ when switching to Pivot Table or Table View.

### Steps to reproduce
- Open, for instance, a Time Series - Line Chart
- Click the viz tag to open up the visualization selection modal
- Select, for instance, Treemap and immediately mouse over the line chart before the switch is made
- The mouseover tooltip remains on the screen

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 219 days. Feel free to comment and request for this issue to be reopened.
