### ISSUE TITLE
Feature: Allow update of columns via dashboard

### ISSUE THREAD

**Issue by jgbolger** [apache/incubator-superset#3472]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

I am considering Superset for a project whereby we present business users with a dashboard of records the need to review and either approve or reject.

I am therefore wondering if there is any facility for such an ability to approve/reject a record from within the dashboard and to have this update the database.

We could tell them to use the SQL Lab but I don't really want them anywhere near SQL.

Is this something that is supported / on the roadmap / not envisaged as a valid usage of SS?

Thanks,
John

**Comment by xrmx** [comment]
Doesn't look like a great fit to me

**Comment by mistercrunch** [comment]
I don't think that's in scope
