### ISSUE TITLE
hi,i cannot  pip install pymssql on windows ,please help me ,thanks a lot .

### ISSUE THREAD

**Issue by 1401062808** [apache/incubator-superset#3479]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

![image](https://user-images.githubusercontent.com/23295996/30526789-181e8818-9c53-11e7-9358-f9756b018eda.png)

**Comment by xrmx** [comment]
You should ask to the pymssql people, not here. FYI superset is not supported on windows.
