### ISSUE TITLE
dashboard is missing in the dashboards list, but accessible via link.

### ISSUE THREAD

**Issue by Jie-Yang** [apache/incubator-superset#3481]
A dashboard is missing in the dashboard list, but user can access via the dashboard link.

I have config a user in Superset only have access to certain dashboards, but these dashboards are not listed out in the dashboard lists, even the user can access via link. I must do something wrong, but have no clue where?

### Superset version
0.19.1

### Expected results
Dashboard appears in the dashboards list

### Actual results
One dashboard is missing from the list, but user can access it by hitting the link of the dashboard directly. 

I have no clue how this happen, please let me know if you have any recommendations?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 216 days. Feel free to comment and request for this issue to be reopened.
