### ISSUE TITLE
ImportError: cannot import TableModelView from superset.connectors.sqla.views in superset.views.core.py

### ISSUE THREAD

**Issue by Yuanmu93** [apache/incubator-superset#3485]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

### Content
I am going to import TableModelView from **superset.connectors.sqla.views** in **superset.views.core.py**. However, I get a ImportError: can not import name 'TableModelView'. How can I fix it, Thanks a lot!

### Expected results
Should import TableModelView.

### Actual results
Getting ImportError: can not import name TableModelView.

**Comment by xrmx** [comment]
What are you trying to do?

**Comment by Yuanmu93** [comment]
@xrmx 
Thank you for your reply!


I'm trying to cteate a MultipleView class with TableModelView and DashboardModelView.The MultipleView can render them on the same page.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 216 days. Feel free to comment and request for this issue to be reopened.
