### ISSUE TITLE
Publish Superset dashboard online and remote login

### ISSUE THREAD

**Issue by alex-ji-repo** [apache/incubator-superset#3489]
- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

### Expected results
from localhost:8088 to 192.xxx.x.x

### Explaination
Hi Superset team,

I apologize in advance if this seems to be a silly question to ask. I have superset running on my local linux (centos) and I would like to host it on this machine. Ideally, I would like to create an IP address, so people could remotely login to the superset dashboard that I published. I am really new at this and would appreciate any help or guidance.

Thanks in advance.

**Comment by xrmx** [comment]
You have to bind superset to something else than localhost (see superset runserver --help), or better put an http proxy like nginx before it. There should be plenty of examples of nginx proxying a flask application on the internet.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 216 days. Feel free to comment and request for this issue to be reopened.

**Comment by hemantaggarwal** [comment]
I know this is closed but I have similar issue and I tried binding superset to different IP using option "-a" but after running command it says "no such option -a".
I tried to run following command:

superset run -a "192.168.89.107" -p 8088 --with-threads --reload --debugger

Superset version: 0.28.1
