### ISSUE TITLE
Pivot table. Unable to limit row numbers for groups

### ISSUE THREAD

**Issue by vasiliy-kiryukhin** [apache/incubator-superset#350]
![image](https://cloud.githubusercontent.com/assets/2155501/14533470/e2a095bc-026d-11e6-9aa4-4629af296a83.png)

It would be extremly nice to have option to select top N for each group and set default to 5 for instance.

Currently caravel query all values and hangs trying to render huge output from druid datasource.

**Comment by mistercrunch** [comment]
Oh like cascading topN queries? I think that's what Pivot does, essentially running one query per group in a cascading fashion. Druid is good at that, traditional SQL DBs probably not as much.

We may want to look into plywood for that.

**Comment by ohoroyoi** [comment]
@vasiliy-kiryukhin  is there way to change pivot table width and height depending on text length? I think your's table column width is appropriate. may I ask What did you edit?
