### ISSUE TITLE
Internal server error when sorting databases by backend and creator

### ISSUE THREAD

**Issue by timifasubaa** [apache/incubator-superset#3501]
Superset errors out when I try to sort the databases by endpoint. Precisely an Internal server error. The end points are below. 

/databaseview/list/?_oc_DatabaseView=backend&_od_DatabaseView=asc

/databaseview/list/?_oc_DatabaseView=creator&_od_DatabaseView=asc

assigned to @timifasubaa

**Comment by mistercrunch** [comment]
related: https://github.com/dpgaspar/Flask-AppBuilder/issues/610

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 215 days. Feel free to comment and request for this issue to be reopened.
