### ISSUE TITLE
Time Series Annotation Layer

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3502]
![vudfmdwhhs](https://user-images.githubusercontent.com/27990562/30837001-ad00b3ca-a216-11e7-9e24-f65f85658158.gif)

Time series annotations should work with Rich Tooltips
![zjdejpvy0c](https://user-images.githubusercontent.com/27990562/30882132-ec14328e-a2bc-11e7-88cd-9d9b19fa54e0.gif)

- User can define a series of time point or time intervals, and save as an "Annotation Layer".
- User can apply one or more annotation layers to any time-series chart, so that they can find time-correlated patterns inside data.
- Mouse over annotation layer will see short and long description for that annotation.

**Comment by benvogan** [comment]
This would be a pretty awesome feature.  We are currently using Metric Insights for this kind of use case.  What we do is put events on a Google Calendar and associate that to an "annotation layer".  People can then see these things in both their calendar app and overlayed on any visualization.  The way it is done in Metric Insights are little triangles at the top of the chart (or bars depending on the event timeframe) and mousing over them shows the text entered into the event.

**Comment by fabianmenges** [comment]
I'm working on something like this. I'll keep you posted.

**Comment by mistercrunch** [comment]
@benvogan we eventually could have different styling for surfacing these annotations. Also could be possible to serve the backend data as "calendar entries" (iCal?) to make Superset more of an "annotation service"

**Comment by wenchma** [comment]
Is there the usage guide for annotation and layer?

**Comment by ali-bahjati** [comment]
Any update on previous question?

**Comment by fabianmenges** [comment]
Check out this commit #3518

**Comment by ali-bahjati** [comment]
Wow, thank you so much.
