### ISSUE TITLE
Feature: Dashboard filters: datepicker and time granularity

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3503]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

When checking "Date" under options in the dashboard filter explore view, only the default time options for `since` and `until` are available, with no ability to set time granularity.
<img width="981" alt="filters" src="https://user-images.githubusercontent.com/15016832/30620809-70bd251a-9d5c-11e7-802a-4fe1d8ab2b99.png">

The time granularity option and datepicker should be available for dashboard filters.

### Superset version
0.19.3

### Expected results
Dashboard date filters should have time granularity and datepicker.

### Actual results
Dashboard date filters only allow the default time options

**Comment by gsemyonov** [comment]
Why did you close this item? I have the same problem.

**Comment by Mogball** [comment]
Huh that's odd, I must've hit it by accident. Anyway I did make a PR for this https://github.com/apache/incubator-superset/pull/3508

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 206 days. Feel free to comment and request for this issue to be reopened.

**Comment by sh0gg0th** [comment]
Not stale
