### ISSUE TITLE
Customizable and simplified interface for non-developers as a new dashboard

### ISSUE THREAD

**Issue by bauchgefuhl** [apache/incubator-superset#3514]
I found out that Superset lacks one feature - creating dashboards with simplified SQL Lab-like interface in them so a person with absolutely no coding skills (e.g. sales managers) could use it themselves. 

For example, they might choose a predefined table (maybe joined in a specific way) with understandable name (a developer can create them) and type, for example, the range of dates, choose a company to list information about it in this time range. I mean, I want a tool for a developer to create specific interface with fields with customizable names. Kind of interface constructor with ability to connect specific field to specific column of specific table. We can't give access to SQL-Lab to sales team and anyway the interface they use should be in Russian.

We're very satisfied with Superset possibilities, though this feature is not presented though we really need it.
Unfortunately, I only have an idea but not a suitable experience to insert this feature in the app architecture myself, 'cause my coding expertise differs from web development :)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 212 days. Feel free to comment and request for this issue to be reopened.
