### ISSUE TITLE
More control over Druid metadata refresh features

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3515]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.3

Periodic metadata refreshing was mentioned in https://github.com/apache/incubator-superset/issues/619.

There should also be a feature to only check for new Druid datasources, instead of only being able to force refresh everything. A small `refresh` button next to each datasource and cluster would also be nice.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 212 days. Feel free to comment and request for this issue to be reopened.
