### ISSUE TITLE
How to make Table View/ Pivot Table order by time?

### ISSUE THREAD

**Issue by vnnw** [apache/incubator-superset#3516]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1

### Expected results
Table View displays data table order by _timestamp instead of metrics[0] by default, or allow us to customize it.

### Actual results
order by metrics[0] and no options to change it.

### Steps to reproduce
Create a table view/ pivot table, and in GROUP BY section check Include Time. See an example as below (I have to click on __timestamp to make the chart order by time):

The default display:
![image](https://user-images.githubusercontent.com/4979571/30769073-6cd674d8-9fd7-11e7-9125-237ee16ce437.png)

What I expect:

![image](https://user-images.githubusercontent.com/4979571/30769044-ef3a3690-9fd6-11e7-8a0b-a341aa3cb028.png)

**Comment by gangh** [comment]
good idea.
i also want to order table by selected metrics column.

**Comment by vnnw** [comment]
@gangh Seems V 0.20 has already provided the options you want.
But I can't still find a way to sort the table by __timestamp.

**Comment by Jemteddy** [comment]
+1 for the feature but I just found a little work around in the meantime, add a metric in your table like `max(orderdate)` for example and use it to order your table. It'll do the job.

**Comment by vnnw** [comment]
@Jemteddy Good idea. Why I haven't thought of that? But I do hope there will be a option instead of working around.

**Comment by chengwei1231** [comment]
1 Like Pivot table, can Table View also choose the Number Format?
2 Table View/ Pivot Table can choose columns to order by?

**Comment by gregroberts** [comment]
+1 for this, ordering table / pivot table by any metric OR dimension would be an absolute killer feature.

**Comment by aleh-arol** [comment]
Up. Pivot table is not sorted even on the first metric. In particular - query has valid ORDER BY, but visualization doesn't obey.
Superset version is ebb7fbc5f024379361f301a86b770e0cc1a932cd.

**Comment by Teeeto** [comment]
Up. We need configurable sort order setting for tables. 
Pivot comes up sorted in random order while I would like to be able to have first column sorted by default. Having users click the first column every time is bad.

**Comment by kyle0r** [comment]
+1 for ability order table charts by __time / __timestamp

> Having users click the first column every time is bad.

100% agree on that.
