### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by sanshanxiashi** [apache/incubator-superset#3517]
sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: dbs.impersonate_user [SQL: 'SELECT dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.allow_run_sync AS dbs_allow_run_sync, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.extra AS dbs_extra, dbs.perm AS dbs_perm, dbs.impersonate_user AS dbs_impersonate_user, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk \nFROM dbs \nWHERE dbs.id = ?'] [parameters: (1,)]

maybe the code is not synchronized with data database？
When I update the version from 0.18 to 0.19.1, I delete the file ~/.superset 
and the follow the following steps:
（1）fabmanager create-admin --app superset
（2）superset db upgrade
（3）superset load_examples
（4）superset init
（5）superset runserver

I get sqlalchemy.exc.OperationalError when I click the dashboard.
How can I deal with the error?
 
### Superset version
Superset 0.19.1

**Comment by xrmx** [comment]
Why are not you following the instruction in the documentation? https://superset.incubator.apache.org/installation.html#upgrading

**Comment by sanshanxiashi** [comment]
sorry,maybe the latest version of superset 0.19.1 has something wrong.
After I follow the the instruction in the documentation "https://superset.incubator.apache.org/installation.html#upgrading", the error is still.
And I found the path "/superset/superset/migrations/versions/" lack of some files,for example 'a9c47e2c1547_add_impersonate_user_to_dbs.py'.
So I download all the files of '/migrations/versions/' from github branch Master,and replace the local path '/migrations/versions/'.Then run the command 'superset db upgrade', errors have disppeared.

**Comment by xrmx** [comment]
/superset/superset/migrations/versions/ does not look like a path of an installed version of superset but a git checkout. Again that's not how the documentation tell you to install superset.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 210 days. Feel free to comment and request for this issue to be reopened.
