### ISSUE TITLE
Where is technical document

### ISSUE THREAD

**Issue by tuantmtb** [apache/incubator-superset#3519]
I'm very excited about superset project. I want to contribute new features. I have a some question:
Where is technical document?
How can I understand overview architecture of superset?
Thank you very much !

**Comment by xrmx** [comment]
I don't think there's such a document, what are you interested in?

**Comment by tuantmtb** [comment]
I'd like to understand flow of process and architecture, component layers.
How to integrate database and notify when metric abnormal.

**Comment by xiaohanyu** [comment]
This is the official documentation: https://superset.incubator.apache.org/

This is an example PR about how to add a new visualization type: https://github.com/apache/incubator-superset/pull/3013

**Comment by CrystalSun1992** [comment]
@xiaohanyu  it does not work on version 0.24.0
