### ISSUE TITLE
Druid metrics are not automatically detected in Superset

### ISSUE THREAD

**Issue by moscowart** [apache/incubator-superset#3520]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1

### Expected results
Metrics specified in Druid spec are automatically detected in Superset.

### Actual results
Metrics specified in Druid spec are not automatically detected in Superset so I had to add enable them manually. With more than 70 dimensions, 20 of which are metrics this process was very tedious. For Druid datasources it cannot be done with matrix-like view, so I had to enter every metric and edit it there.

### Steps to reproduce
Ingest any batch or real-time Druid data via Tranquility.

**Comment by xrmx** [comment]
FYI 0.17.1 is not the latest release

**Comment by joshwalters** [comment]
This has been fixed for newer versions of Superset, metrics columns should (mostly) auto-populate.

**Comment by moscowart** [comment]
My bad. I really had to try it with latest version. However it still behaves not as expected. It now adds too many metrics: every type (max, min, sum) for every numeric column. Even if they are not specified in dataspec. Anyway this is another issue. I close this one. Thank you guys for help.
