### ISSUE TITLE
Date Filter is not working on dashboard.

### ISSUE THREAD

**Issue by thakur00mayank** [apache/incubator-superset#3522]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Git Hash: 255ea699770a98b8406a516d44fc7eac47d45ab6

### Expected results
When we change the date filter, other slices in the dashboard should be updated according to date filter.

### Actual results
When we change the date filter, other slices in the dashboard doesn't get updated according to date filter.

### Steps to reproduce
1. Create the date filter slice, enable the Date Filter inside options. Select the proper time column inside Time section, let's say it is Date.
2. Now create another slice whose datasource contains the Date column. 

    2.1. Select the proper datasource.

    2.2. Select chart type as distributed bar chart.

    2.3. Select the proper Time Column, lets say it is Date.

    2.4 Select the other options of the chart.

3. Add these two slices in a dashboard.
4. Change the date filter with valid from and to.
5. Other slices on the dashboard don't get updated according to Date filter.

**Comment by thakur00mayank** [comment]
This has been generated due to [this commit](https://github.com/apache/incubator-superset/commit/745784fc973741c5d1cc4a5e10b6c92a8833e8a3).

**Comment by xrmx** [comment]
@thakur00mayank  Next time if you are not using a release please mention the git hash you are using, thanks.

**Comment by thakur00mayank** [comment]
@xrmx Thanks for the suggestion. I have mentioned the git hash in the reported issue.

**Comment by DaimonPl** [comment]
We are having same problem after upgrading to 0.20.0

**Comment by xrmx** [comment]
@Mogball any chance you can take a look at this?

**Comment by Mogball** [comment]
That would be my fault, but this should be fixed in https://github.com/apache/incubator-superset/pull/3508

**Comment by xrmx** [comment]
@Mogball Thanks for the update!

**Comment by DaimonPl** [comment]
@Mogball @xrmx great there's fix for that :) any chance to have it merged and released as 0.20.1 ? It's quite critical bug as all dashboards with date filters stopped working with 0.20.0

**Comment by satishbhor** [comment]
@Mogball Same issue for me, any idea when #3508 will be released?

**Comment by DaimonPl** [comment]
With 0.20.4 it works fine for us
