### ISSUE TITLE
Marking slices/dashboards as Favorite ?

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3535]
What's the purpose behind marking the dashboard/slice as favorite?
Where can i use this information? From where i can get the list of all my favorites dashboard/slice?
Is there any way to view the said information. I guess this information should be available, if not.

**Comment by graceguo-supercat** [comment]
It's not intuitive... but try click Superset logo on the top left corner.

**Comment by NaukhaizAhmad** [comment]
Thanks!
