### ISSUE TITLE
QUERY_TIMEOUT_THRESHOLD change not working

### ISSUE THREAD

**Issue by Manju106** [apache/incubator-superset#3536]
I tried changing the QUERY_TIMEOUT_THRESHOLD from 45000 to 120000, I have tried changing both in code and through export before starting the superset.

But again I am getting time out error in 45 sec . Is there any idea why the issue is ? And what is the possible way to increase my query timing

**Comment by xrmx** [comment]
QUERY_TIMEOUT_THRESHOLD has been removed, the client timeout is synced with the backend one SUPERSET_WEBSERVER_TIMEOUT in superset_config.py
