### ISSUE TITLE
build_sphinx missing urlparse module

### ISSUE THREAD

**Issue by diggzhang** [apache/incubator-superset#3539]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

`"version": "0.19.1"`

### Expected results

When users wanna build the docs follow `CONTRIBUTING.md`, execute command `python setup.py build_sphinx` hope to build the docs success.

### Actual results

```shell
$ python setup.py build_sphinx
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
VERSION: 0.19.1
GIT SHA: b'255ea699770a98b8406a516d44fc7eac47d45ab6\n'
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
running build_sphinx
creating /path/to/incubator-superset/docs/_build
creating /path/to/incubator-superset/docs/_build/doctrees
creating /path/to/incubator-superset/docs/_build/html
Running Sphinx v1.6.3

Exception occurred:
  File "/path/to/superset-dev/lib/python3.6/site-packages/sphinxcontrib/youtube/youtube.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
The full traceback has been saved in /tmp/sphinx-err-wvwlr926.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The reason is: 

> The urlparse module is renamed to urllib.parse in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3. 

Accces to [sphinxcontrib-youtub on pypi](https://pypi.python.org/simple/sphinxcontrib-youtube/) the latest package is `0.12`, but the latest code version is `0.2.0` and fixed the url parse module. pip can't install the right package now.

### Steps to reproduce

1. create one clean virtulenv
2. clone superset code from github
3. run command to prepare sphinx packages `pip install -r dev-reqs-for-docs.txt`
3. run command to build docs `python setup.py build_sphinx`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 207 days. Feel free to comment and request for this issue to be reopened.

**Comment by leehwmj-junta** [comment]
This problem occurs because your python version is 3.x.
The urlparse module is renamed to urllib.parse in Python 3.

 Lower the python version, or replace import urlparse with import urllib.parse.

**Comment by arthurkhlghatyan** [comment]
Hi,
just had the same issue on my end and seems suggested solution from @leehwmj-junta doesn't work because error appears to be from package dependencies.

Thanks.
