### ISSUE TITLE
forward to original url after loggin in

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#3549]
currently when a user who is not singed in who clicks a link to a dashboard is then redirected to login. After they login it goes to the list of dashboards vs the original dashboard link.

**Comment by doctording** [comment]
Is this question solved?

**Comment by rpwils** [comment]
I did not see any movement on this from flask app builder so I implemented it in our own AuthOAuthView and AuthDBView.

**Comment by xrmx** [comment]
@rpwils If it's a generic issue a PR for flask app builder would be more than welcome, thanks.

**Comment by rpwils** [comment]
@xrmx I'll see what i can do, I see @bkyryliuk attempted to contribute back changes that i assume were not accepted. In that implementation the requested url went onto the request, I changed it to go into the session. This way it would be available after the Oauth Redirected back from the providers.

**Comment by rumbin** [comment]
So, is this fixed upstream now or why is the issue closed now? I'm a bit confused...
