### ISSUE TITLE
"Create Option" is not working in Filter Box

### ISSUE THREAD

**Issue by SuperCobra2017** [apache/incubator-superset#3551]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Custom option to appear as it appears in Filters inside the Slice

### Actual results
Nothing.
Demo-gif:  https://gyazo.com/7ea0175593663b0aee7ad579f43126c7

### Steps to reproduce
Create Filter Box Slice with some Filter controls, 
add it to Dashboard, 
click on drop-down box,
type-in anything,
click on it or press Enter

**Comment by xrmx** [comment]
Please reproduce it ith 0.20.0

**Comment by SuperCobra2017** [comment]
same issue in 0.20

**Comment by xrmx** [comment]
Fixed in #3584
