### ISSUE TITLE
Grant Permission in same dashbord by datasource and by user

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-superset#3552]
Make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [ yes] I have reproduced the issue with at least the latest released version of superset
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.19.1

Is it possible to grant permission in same dashbord by datasource and by user? 

I try this solution but it's not easy to maintain: . 

- I create datasource for each group users and dashbord for specif datasource.Then grant permission on datasource. 

Is it possible to have one dashboard.?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 205 days. Feel free to comment and request for this issue to be reopened.
