### ISSUE TITLE
Adding Superset charts to existing Play Framework Web Application

### ISSUE THREAD

**Issue by manavbagai** [apache/incubator-superset#3554]
I am having a web application. I want to display superset charts on that application. Is it possible to add the superset charts from server side without using IFrames.

**Comment by xrmx** [comment]
How do you want to integrate them without an iframe?

**Comment by manavbagai** [comment]
I have a particular page in my Play framework(scala framework) application with react UI and i want to integrate superset charts in one such react page without using iframes.

**Comment by mistercrunch** [comment]
It's not possible at the moment. Iframe is the only way. We may release React component in the future that would assume being able to talk to an existing Superset backend.

**Comment by NikhilOO7** [comment]
Hi @mistercrunch . I want to use superset to render visualizations from the api calls of django server. How to do that?
