### ISSUE TITLE
Date Picker OK button position

### ISSUE THREAD

**Issue by fabianmenges** [apache/incubator-superset#3556]
I really don't like the OK button of the date picker being located on the left. I'm happy to implement the change but I wanted to see what you guys are thinking, pretty much any software has the OK on the right hand side.
Any objections moving it to the right?

**Comment by mistercrunch** [comment]
I don't feel strongly about it personally

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 201 days. Feel free to comment and request for this issue to be reopened.

**Comment by fabianmenges** [comment]
👍
