### ISSUE TITLE
Request for Comments : Tableau-like data extracts feature

### ISSUE THREAD

**Issue by rjpereira** [apache/incubator-superset#3564]
My team is about to start implementing a functionality in Superset which I believe could have a general use. So while, we may have to cut some corners to get it working soon rather than later, would welcome your suggestions.

This feature implements the Tableau-like TDE extracts (or to some extent Quicksight's SPICEs). The feature doesn't assume any "optimized-storage-magic" : it just intends to materialise views of other databases in a Superset owned storage, most probably living in the same server as Superset's own metadata. For now calling it tentatively QDE : Query Data Extract.

My idea is to extend the schema of Saved Queries, to have attributes to flag query as "to be extracted", "extract name" and crontab frequency of refresh. This would extend the saved_query table and the UI that edits the queries.

A working setup of QDE, would require the launch of celery beat, with a configurable polling frequency (say 5 mins). The worker task already supported by superset workers, would scan the list of saved queries that were due a refresh. For this they would expand the crontab expression stored in the db, together with the last extraction time also stored on saved_query, and if there was a new "run time" between last run and now, the query would be executed (with code similar to SQL Lab), but the results would then be uploaded to the QDE database, rather than to Werkzeug cache as Async queries. This code would of course, create or replace schemas if the schema of the query didn't match that on QDE. With time, this should have a "smart sync logic" but that is more difficult to generalise. The extracts would be saved in QDE with the "Extract name" added to Saved Query.

The use of extracts was as per normal use of a database, i.e. we would have QDE as a source of "materialisations" of all the "slow sources" we would normally use in SQL Lab.

Additionally to this, we will be refreshing slice caches that are due to expire in workers. Two separate ideas here:
a) We could check all the slices that are based on QDE extracts, and after a refresh of an extract, we would run in a worker the query of the slice, forcing the execution, to extend the cache time.
b) Even those not supported on QDE we could check those with less than X hours to expiry, and re-run them in the background.

Those last two options, I understand do not apply to everyone. Lazy caching is different than active caching, which is what we need, but maybe not everyone else. Some more UI would be required to give an option to "Actively refresh slices".

As mentioned, we've already started this for our own use, but any ideas are welcome.

**Comment by mistercrunch** [comment]
Just curious, what would you use or allow as the "QDE" backend? Some other, faster database? I don't think it's reasonable to use Superset's metadata DB as we don't want mixed workloads (OLTP & OLAP) on that DB. We want that metadata DB to serve the app predictably and reliably.

**Comment by rjpereira** [comment]
The deployment in same or separate and different DB would always be left as
a configuration decision. My requirements are mostly to stage slow engines
as Athena or materialize big joins in DBs that don't support materialised
views as redshift.

**Comment by mistercrunch** [comment]
Not sure if I want Superset to become another data-pipeline scheduler... Have you checked out Apache Airflow? :)

**Comment by rjpereira** [comment]
Didn't know it. Thanks for the link. A bit on overkill for my need to stage "async queries" for dashboards. I understand that this staging may be better addressed by a separate tool. So let's leave it at that.
What about the possibility to refresh slices in the background, to have the fastest response time for interactive users ?
The use case I see would be to optionally add a cron expression to tables, to define a schedule at which tables are either changed or should trigger a refresh of caches. A worker would then simply transverse all the slices dependent on table, invoking them with force=True to refresh cache.

To some extent we could see this as extending the concept of async queries beyond SQL Lab.

**Comment by mistercrunch** [comment]
Scheduling cache warmup seems reasonable, and this recent PR seems like it does most of the work in that direction:
https://github.com/apache/incubator-superset/pull/3575

Though typically in case of batch-populated tables you'd want to trigger the cache warmup after the batch job is done. That's we have a SupersetCacheWarmupOperator in Airflow at Airbnb. After the pipeline has loaded the table, we can warmup the Superset cache.

I see the use case for scheduling data transfers, but that makes Superset becomes much more of a piece of infrastructure that needs to be monitored, capped and that can be abused in intricate ways. Being on-call for Superset I'd rather people use a tool designed for that purpose. I'd be ok with it if it can be turned on and off globally.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 200 days. Feel free to comment and request for this issue to be reopened.

**Comment by edolimbat** [comment]
Hi, anybody know how to create extract data in superset, like tableau's functionality?

**Comment by mistercrunch** [comment]
Let's open a fresh issue and reference this one. The landscape has changed somewhat and premisses are slightly different than they used to be. The proposal can go deeper into the specifics of what it would do.
