### ISSUE TITLE
Heatmap Tooltip disappears under the slice's header.

### ISSUE THREAD

**Issue by vinay87** [apache/incubator-superset#3573]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.0 Python 3.6

### Expected results
I wanted to look at the heatmap values, so I assumed that the tooltip would appear over the header bar.

### Actual results

It appears under it, I've attached a screenshot here.

### Steps to reproduce
![superset_heatmap_tooltip](https://user-images.githubusercontent.com/11478411/31109230-21355aba-a81c-11e7-8d0d-0b63dd146c57.png)

**Comment by abotero** [comment]
Fixed in https://github.com/apache/incubator-superset/pull/4268
