### ISSUE TITLE
Problem with symlink dist

### ISSUE THREAD

**Issue by rjpereira** [apache/incubator-superset#3574]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Head of master (+macOS,Latest version of Docker running CentOS-based version, anaconda 4.2.12)

### Expected results

Running superset

### Actual results

Missing static/assets/dist, crippling website.

### Steps to reproduce

I'm sure this is a simple one, but can't really understand what is wrong.
By both git cloning and pip installing from local, or from pip install directly from git, the final deployment of superset after running it runserver, seems to have not created the symlink under "static/assets", crippling website as per picture below. Not exactly sure what I can do differently, but also not clear why it doesn't seem to affect anyone else...

/opt/anaconda/lib/python3.5/site-packages/superset/static/assets/dist
![image](https://user-images.githubusercontent.com/643219/31110491-cd66b8de-a807-11e7-95ef-827c40253c68.png)

Errors as 

no manifest file found at /opt/anaconda/lib/python3.5/site-packages/superset/static/assets/dist/manifest.json

Any hints ?

**Comment by mistercrunch** [comment]
Did you follow the instructions here?
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment

**Comment by rjpereira** [comment]
Thanks. Sorry, but have been working only with the pypi package and wasn't aware there was a more intricate npm build. Closing.
