### ISSUE TITLE
SelectControl switch to react-virtualized-select for large lists

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3580]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.1

Sometimes `SelectControl` components are populated with a very large list of choices:

<img width="233" alt="screen shot 2017-10-03 at 2 35 29 pm" src="https://user-images.githubusercontent.com/15016832/31150469-80c4b8aa-a848-11e7-8f4c-5140f1becabe.png">

Performance suffers and the component becomes really laggy. Might consider silently switching to `SelectVirtualized` (https://github.com/bvaughn/react-virtualized-select/) when list size exceeds a certain limit.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 201 days. Feel free to comment and request for this issue to be reopened.
