### ISSUE TITLE
label for first group by clause in time series - bar chart is always undefined 

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#3590]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.1

### Expected results

the first label in the legend is the same as the group clause

### Actual results

the first group by clause label is undefined

### Steps to reproduce

Create a time series bar chart with multiple group by clauses, the first will have an undefined label

**Comment by xrmx** [comment]
Looks like a regression from 8efcaeb76 cc @fabianmenges

**Comment by fabianmenges** [comment]
looking at it

**Comment by xrmx** [comment]
@fabianmenges thanks a lot!

**Comment by fabianmenges** [comment]
no problem
