### ISSUE TITLE
[Explore] Regression: Chart Options missing in Distribution - Bar Chart

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3593]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.1

### Expected results
Chart Options are visible on the left tool bar, allowing for setting axis labels, bottom margin, legend, etc.

Taking _Time Series - Bar Chart_ as an example:

![missing_chart_options_0](https://user-images.githubusercontent.com/1220356/31174743-e0a1c168-a90c-11e7-8eb9-21385ade4252.PNG)

It is worth noting that this is a regression, since in 0.15.4 the graph could be configured this way — although not with the tabbed interface.

### Actual results
The query settings are displayed within the _Chart Options_ tab and not within the _Query_ tab, which is missing entirely.
On the other hand, everything that I'd expect to find in _Chart Options_ is just missing:

![missing_chart_options_1](https://user-images.githubusercontent.com/1220356/31174750-ea2c49a6-a90c-11e7-8af6-5bf311667c95.PNG)

### Steps to reproduce
Create a slice of visualization type _Distribution - Bar Chart_ and try to set, e.g., the x-axis title.

**Comment by rumbin** [comment]
I tracked down the issue:

The regression took place from 0.20.0 to 0.20.1.
I.e. in 0.20.0 all options were nicely in place:

![missing_chart_options_0_19_1](https://user-images.githubusercontent.com/1220356/31219192-d5ae80c4-a9bc-11e7-9428-ebac3fd2f3f7.PNG)

**Comment by mistercrunch** [comment]
Thanks for reporting this high-visibility bug, here's the fix:
https://github.com/apache/incubator-superset/pull/3606
