### ISSUE TITLE
No Time Grains for Redshift tables

### ISSUE THREAD

**Issue by CyrilLeMat** [apache/incubator-superset#3595]
I got a redshift db. For all the table from this db, I'm unable to use the Time Grain of the graph editor.

### Superset version
0.20.1

### Expected results
Display Time Grain in the explore/table view

### Actual results
Time grain selection is empty (displaying "Select 0")

### Steps to reproduce
Adding a redshift database

Thanks,

**Comment by xrmx** [comment]
Please give it a try to latest master

**Comment by mistercrunch** [comment]
Please share your connection string. [though scrub any password/hostname that may be in there]

**Comment by mistercrunch** [comment]
A few pointer around the mechanism where a database gets its "db_engine_spec" (where time grains are defined):
https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L682
https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L580

I'm guessing that in your case the mechanics here don't work for some reason.

**Comment by CyrilLeMat** [comment]
here is my connection string : 
postgres://hostnfly:XXXXXXXXXX@YYYYY.eu-west-1.redshift.amazonaws.com:5439/hostnfly
I updated superset in 0.23 but I have still the issue.

**Comment by CyrilLeMat** [comment]
It was indeed a connection issue on my side. It's fixed with 'postgresql+psycopg2'
