### ISSUE TITLE
'Null' value is being displayed as '0' in the data retrieved.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3603]
'Null' value is being displayed as '0' in the data retrieved (Slices).

What's the difference between the 'Null' value being displayed as '0' and an integer column with a '0' value?
Isn't it false reporting?

Is there any background history against this implementation?

**Comment by mistercrunch** [comment]
Which visualization?

**Comment by davidhassan** [comment]
I get this same issue in the table view.

**Comment by NaukhaizAhmad** [comment]
Thanks for your response, You can test it for Table view, histogram etc.

**Comment by jeffreythewang** [comment]
Correct me if I'm wrong, but I believe this issue is fixed with https://github.com/apache/incubator-superset/pull/4358

Are you still seeing the issue on the latest version?

**Comment by NaukhaizAhmad** [comment]
Thanks @jeffreythewang, I have tested this ticket against the mentioned PR and found that this issue seems to be fixed for string type of columns.
But for integer type of columns, the _Null_ values are being displayed as '0'.
This issue is required to be FIXED for all type of columns.
![nullvalue](https://user-images.githubusercontent.com/29655292/37448533-918588f6-2848-11e8-9730-fa80eaf1d8c2.png)

**Comment by davidhassan** [comment]
This issue was fixed in 0.27 but is now back in 0.29.rc07
