### ISSUE TITLE
How can i disable float bar for the chart in dashboard?

### ISSUE THREAD

**Issue by Yuanmu93** [apache/incubator-superset#3605]
- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

![default](https://user-images.githubusercontent.com/20705403/31225977-012b51ce-aa07-11e7-8226-fefe3db6b480.jpg)

I want to disable float bar for the chart in dashboard like above, to make dashboard look better.But I can not find the related codes. How can I do it?

### Superset version
0.19.1

**Comment by xrmx** [comment]
Please report bugs only against latest version. Looks it has already been fixed.

**Comment by mistercrunch** [comment]
Will reopen if you comment saying you can reproduce on `0.20.1`

**Comment by Yuanmu93** [comment]
Thanks a lot.
I tried this version for 0.20.1 just now. The problem remains unfixed and same as 0.19.1.
![_20171006091323](https://user-images.githubusercontent.com/20705403/31259179-64ad4228-aa77-11e7-8060-dc7c8748b21c.jpg)

**Comment by mistercrunch** [comment]
What browser are you using? what's your zoom level?

**Comment by Yuanmu93** [comment]
My browser is Firefox 55.0.2, my zoom level is 100% and my OS is Ubuntu 14.04.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 194 days. Feel free to comment and request for this issue to be reopened.
