### ISSUE TITLE
Dashboard filter UI unresponsive

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3610]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

I seems that a combination of https://github.com/apache/incubator-superset/pull/3584 and https://github.com/apache/incubator-superset/pull/3508, although work correctly on their own, has created a new bug in the dashboard filter with the latest version.. ;_;

https://github.com/apache/incubator-superset/pull/3584 fixed a bug where created filter options were not updated, but https://github.com/apache/incubator-superset/pull/3508 replaced the date dropdowns with datepickers, which did not have predetermined options. This causes an index error when updating new options.

Modifying the date filter will cause the filter box UI to freeze up. Will have a hotfix PR soon.

**Comment by rumbin** [comment]
I'm not quite sure if the behavior I observed belongs to this bug or whether it would require to file a new issue.

In my case, the time filter slice does perform the filtering, but does not show the currently selected values:

![time_filter_bug](https://user-images.githubusercontent.com/1220356/31297444-4af6fd64-aae6-11e7-8ede-2b11f4f86240.PNG)

**Comment by Mogball** [comment]
Yeah that's part of it, the UI doesn't update basically
