### ISSUE TITLE
Time Series Table: Difference calculation has wrong sign

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3612]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
The calculated result of a _Time Comparison_ → _Difference_ column reflects the value change of the chosen time lag interval.

E.g., if the time lag is, say, one week and the value of the observed metric has decreased within the last week, then the sign of the calculated difference has to be negative.

### Actual results
The sign of the calculated difference is twisted.

Example:
![time_series_table_diff_bug](https://user-images.githubusercontent.com/1220356/31297701-61f6b526-aae7-11e7-8302-c829288ce072.PNG)

### Steps to reproduce
E.g.:
![time_filter_bug1](https://user-images.githubusercontent.com/1220356/31297754-8c5ce3f8-aae7-11e7-9168-d6721da27ac4.PNG)

--------

PS: @mistercrunch: Thanks for releasing 0.20.3 so quickly!

**Comment by mistercrunch** [comment]
Addressed here: https://github.com/apache/incubator-superset/pull/3597

**Comment by rumbin** [comment]
@mistercrunch Could you please revisit this issue?
I had a look at #3597 and don't see the diff calculation modified there.
I'm my understanding, `v -= recent;` needs to be changed to `v = recent - v;`.
