### ISSUE TITLE
Time Series Table: group-by keys must be strings

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3613]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
Any groupable column or combination of columns can be used to group by, when creating a Time Series Table slice

### Actual results
Rendering the slice fails if…
* …more than one groupable column is selected; error: 'keys must be a string'
* …only one column is selected for grouping but the column is of type int instead of str

### Steps to reproduce
…self explanatory, I suppose…

**Comment by scott-retair** [comment]
I met the same issue

**Comment by SpyderRivera** [comment]
If you are grouping by an int, is it really an int? Or is it an id that can be cast as a string?

**Comment by mistercrunch** [comment]
Could not reproduce on `master` can you confirm?

**Comment by tvorogme** [comment]
Same issue
