### ISSUE TITLE
Time Series Line Chart: Markers disappear on fade-out/fade-in

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3614]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3, but already observed, e.g., in 0.15.4

Browsers tested: Firefox, Vivaldi

### Expected results
Fading out and back in of series — by clicking the markers in the legend — in a Time Series Line Chart preserves the markers.

### Actual results
Once a series is faded out and back in, the markers of the series is gone until reload of the slice.

If all but the clicked series are deselected (via double-click) and then back in, all of them have lost their markers

### Steps to reproduce
Create a Time Series Line Chart slice, check _Show Markers_ and render the slice.
Then deselect and re-select any of the shown series. The markers are gone then.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 198 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen, as this can lead to missed data points, which in my eyes is pretty severe.

**Comment by mistercrunch** [comment]
Looks like an nvd3 bug to me.
