### ISSUE TITLE
Feature Request : drop down for possible table name

### ISSUE THREAD

**Issue by hc000** [apache/incubator-superset#3615]
### Superset version
.20.1

### Steps to reproduce
on the page /tablemodelview/add
in the table name box, there should be a drop down to show the possible tables in the database.

**Comment by NaukhaizAhmad** [comment]
This should also be fixed for the case of editing a table source.
The 'Table Name' field in the detail section should display a drop down list of all the available tables within the selected database.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 194 days. Feel free to comment and request for this issue to be reopened.

**Comment by NaukhaizAhmad** [comment]
This is a valid ticket, so please change its state to 'open'
