### ISSUE TITLE
Carry over dashboard filters to explore: empty fields transferred

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3616]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

This issue is addressing the changes introduced by #3461

### Expected results
Only currently active dashboard filters are transferred to the explore view and added to the already existing filters of the corresponding slice.

### Actual results
Dashboard filters that were previously applied and then dropped again leave empty entries in the URL parameters which are then carried over to the explore view of the slice. This results in filter entries with empty arguments.

Furthermore, any time filters set on the dashboard result in entries in the filter list in explore view with empty column selection.
However, I guess due to #3610, I cannot currently reproduce this behavior. Nevertheless, I wanted you to be aware that this may also happen.

### Steps to reproduce
Apply time filters on a dashboard; apply and then drop and other filter and afterwards click _Explore chart_ on any slice.

**Comment by Mogball** [comment]
> Furthermore, any time filters set on the dashboard result in entries in the filter list in explore view with empty column selection.
I cannot seem to reproduce this. I am applying one of each time filter, hitting 'Apply' and then 'explore'.

Can you confirm that this is still an issue/send a screenshot?

**Comment by rumbin** [comment]
@Mogball No, actually, the time filters are now (0.20.4) carried over nicely, including time column and time grain. So there are no empty filters entries created any more.

However, any column filters that have been previously applied and then cleared again still leave empty fields whern carried over to Explore.
