### ISSUE TITLE
Carry over dashboard filters to explore: conflicting use cases

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3617]
### Preface
This is about the changes introduced by virtue of #3461 (Superset version 0.20.3).

### Description
In my understanding there are at least two use cases for the _Explore chart_ functionality of a dashboard's slice. Without respection any order of importance, these are:

1. Analyze the currently displayed chart data in more detail, maybe for applying more filters or adding some more grouping criteria. In this case the transfer of currently set dashboard filters to the expolre view is a behavior that is expected by (less experienced) users. I.e. the currently implemented behavior is — apart from issue #3616 — highly welcome.
2. Alter/fix something on the slice _permanently, like maybe a missing axis label, a badly chosen bottom margin or whatever. So after altering the slice, the changes are made permanent by overwriting the current slice. In this use case, the user has te be very careful and find out if there are any filters in explore view that exist _only_ due to the transfer of the dashboard filters and then remove these filters. Otherwise they _introduce unwanted filters_ without even knowing.

I can perfectly understand both use cases. In both use cases we risk unexpected behavior. However, in the second one there is a high risk of concealed degradation, as especially routined superset users may not expect this change in behavior. Even if thy were aware of it, they would be required to know their slices very well, in order to understand which of the applied filters in explore view have been there before opening the slice from a filtered dashboard. Furthermore, together with issue #3616, this may become fairly annoying.

### Solution
To be honest, I don't see any other option than maybe asking the user whether they want to transfer the filters when clicking _Explore chart_. I must admit, however, that this is not an elegant solution.

What do you think about this issue?

**Comment by Mogball** [comment]
What if exploring a slice from the dashboard that has filters would display these filters in a separate `Dashboard Filters` section that do not save with the slice?

**Comment by rumbin** [comment]
@Mogball This may be a useful approach. Maybe the user could then drag and drop (or transfer otherwise) filters to the section where the permanent filters reside.

Another feasible way might be to only ask on saving the slice, whether the filters carried over from the dashboard should be permanently included into the slice. This approach would postpone this decision  until it is eventually required.

**Comment by mistercrunch** [comment]
related: https://github.com/apache/incubator-superset/issues/3609

I have some thoughts on this. First the dashboard view should be upfront about which dashboard filters are applied / not applied to each widget.

I'm thinking a `text-primary` colored filter icon on the widget header (should be always visible, not only on-hover like other widget-header icons), by hovering we'd show which filters are applied and which ones are disregarded.

Now about the explore view. When the explore view derives from the original slice, we should be very clear about this. So say the slice has a certain metric, and I change that metric to another one, then we need to surface that this is an altered version of this slice, and ideally provide context as to the exact diff between the original slice and the current view. This could be done with an `altered` style="danger" label right of slice title, and with a tooltip on that label with the diff list or control name, and value-before, value-after.

In the case where we'd come from a filtered dashboard, you'd land on the explore view with that `altered` label showing loud and clear.

Grace is "reactiforing" the dashboard view here https://github.com/apache/incubator-superset/pull/3581 and wouldn't start the dashboard view changes until that's landed. The work for the `altered` tag on the explore view could probably start anytime though.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 197 days. Feel free to comment and request for this issue to be reopened.
