### ISSUE TITLE
Bottom padding of Separator slice (Markdown) too large

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3619]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Regression somewhere in between 0.15.4 to 0.20.3

### Expected results
The screen's real estate is economically used, just the way it used to be in 0.15.4

Consider a Separator slice, containing simply a horizontal line and a header:
```
--------------------
##Element
```

I'd expect his to fit into the smallest possible vertical space on a dashboard, as it did in 0.15.4:
![separator_bug0](https://user-images.githubusercontent.com/1220356/31305727-f1f9a30a-ab40-11e7-89e4-af6a5612cfba.PNG)

### Actual results
In 0.20.3 the bottom margin/padding of the separator slice is that large, that the sontent gets gut off and a vertical scroll bar is required, if the vertical size of the slice is not increased:
![separator_bug1](https://user-images.githubusercontent.com/1220356/31305750-6733e8ce-ab41-11e7-8f26-e15fc07e641a.PNG)

Expanding the slice vertically facilitates far more than enough space, though, resulting in a rather massive waste of real-estate:
![separator_bug2](https://user-images.githubusercontent.com/1220356/31305753-6cff7714-ab41-11e7-8089-fcf534990218.PNG)

Side remark: In my eyes the horizontal line now is rendered too pale, as it has become nearly invisible, but that is certainly a different story…

### Steps to reproduce
See example above…

**Comment by rumbin** [comment]
## Debugging
Comparing the HTML of this element:

### Version 0.15.4
```
<div id="slice_84" class="react-grid-item widget separator cssTransforms react-resizable" data-slice-id="84" style="width: 1781px; height: 100px; position: absolute; touch-action: none; transform: translate(20px, 2780px);">
<div id="token_25540099-cell" class="slice-cell">
<div class="chart-header">
<div class="row">
<div class="col-md-12 header">
<div class="col-md-12 chart-controls" style="display: block; opacity: 0.433663;">
</div>
</div>
<div class="slice_description bs-callout bs-callout-default" style="display: none;"></div>
<div class="row chart-container">
<input value="false" type="hidden">
<div id="token_25540099" class="token col-md-12">
<img class="loading" src="/static/assets/images/loading.gif" alt="loading" style="display: none;">
<div id="token_25540099_con" class="slice_container" style="opacity: 1; height: 65px;">
<hr>
<h2>Element</h2>
</div>
</div>
</div>
</div>
<span class="react-resizable-handle" style="touch-action: none;"></span>
</div>
```
### Version 0.20.3
```
<div id="slice_84" class="react-grid-item widget separator react-draggable cssTransforms react-resizable" data-slice-id="84" style="width: 1781px; height: 100px; position: absolute; touch-action: none; transform: translate(20px, 2780px);">
<div id="84-cell" class="slice-cell">
<div class="row chart-header">
<div class="col-md-12">
<div class="header">
<span class="editable-title">
<input required="" value="Text: Element" type="button">
</span>
</div>
<div class="chart-controls" style="display: none;">
</div>
</div>
<div class="slice_description bs-callout bs-callout-default" style="display: none;"></div>
<div class="row chart-container">
<input value="false" type="hidden">
<div id="token_84" class="token col-md-12">
<img class="loading" src="/static/assets/images/loading.gif" alt="loading" style="display: none;">
<div id="con_84" class="slice_container separator" style="opacity: 1; height: 56.15px; overflow: auto;">
<iframe id="if__con_84" sandbox="allow-scripts" srcdoc=" <html> <head> <link rel="stylesheet" type="text/css" href="/static/assets/dist/theme.c87a4fa1df501b3a6ccf.css" /> </head> <body style="background-color: transparent;"> <hr /> <h2>Element</h2> </body> </html>" frameborder="0" height="56.15000915527344">
</div>
</div>
</div>
</div>
<span class="react-resizable-handle" style="touch-action: none;"></span>
</div>
```

**Comment by xrmx** [comment]
Care to open a PR?

**Comment by rumbin** [comment]
@xrmx I'm afraid I am not the right person for this job, as I'm not at all a skilled programmer. I have zero knowledge in JavaScript and never even tried to build superset by myself. I wouldn't even know where to start tackling this issue.

If I had the skills, I'd rather start with #3007, as this one bothers me even more. However, the overhead of trying to get myself into this business is not currently not bearable for me :-(

**Comment by mistercrunch** [comment]
One related thing that I've been thinking about is adding more grain to the grid dashboard snapping grid.

**Comment by mjdepalma** [comment]
In comparing a diff of the HTML provided by @rumbin, two things are apparent:
(1) The height of the slice_container changes from 65px down to 56.15px.  (Why?)
(2) The 20.5 version is using an iframe whose srcdoc appears to contain quotes that are not escaped.  The srcdoc has a quote before and after the <html> and </html> tags, but all the code in between is also using quotes.   Seems like all those should either be changed to single quotes, or escaped via &quot;, right?

@mistercrunch - I like the idea of adding more grain (which would provide more flexibility in positioning and better viewability), but it does not seem that would address the root of this problem which is that even if there is enough space to show the text, it gets clipped.
