### ISSUE TITLE
Always got 45 seconds timeout when loading graphs

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [apache/incubator-superset#3620]
Make sure these boxes are checked before submitting your issue - thank you!
<img width="845" alt="screen shot 2017-10-07 at 10 13 19 pm" src="https://user-images.githubusercontent.com/12984659/31309221-f1d4f03e-abac-11e7-99e5-e61b77ee599d.png">

### Superset version
0.18.5

### Expected results
The data is shown up

### Actual results
Always got 45 seconds timeout

### Steps to reproduce
Querying large dataset

### Questions
Is there any specific way to control the timeout threshold from the config file?

**Comment by rumbin** [comment]
This has been fixed in #3329. Just upgrade to the most recent superset version (currently 0.20.3).
