### ISSUE TITLE
What sort of technology required to customize superset

### ISSUE THREAD

**Issue by ajaiswal595** [apache/incubator-superset#3622]
Hi, i want to customize superset. But I have knowledge around javascript, angular, java, HTML ,CSS .

I am exploring python.

**What sort of technology required to customize superset.**

**Like removing the credential page, bookmarking dashboard page so directly can be rendered, and removing user role option.
Last but not the least  Adding custom visualization.**

I want to integrate superset in one of my product. Which actually running on Angular2 and Node.js.

Please respond, And any threads available for my requirement please add in you reply so i can refer.

**Comment by mistercrunch** [comment]
Look at the setup.py and package.json files to see all of the python and js libs that we use.
