### ISSUE TITLE
Add Session Timeout

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#3623]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version - 19.1

Would like to have the ability to set the user session timeout in the the config.  Would  adding something like this to the __Init__.py file to an acceptable way? Maybe this can be added to the project.

from datetime import timedelta 

@app.before_request
def make_session_permanent():
      appbuilder.get_session.permanent = True
      app.permanent_session_lifetime = timedelta(minutes=USER_SESSION_TIMEOUT)

**Comment by mistercrunch** [comment]
Would accept a PR adding this feature. I wonder if we could have a more generic `FLASK_APP_MUTATOR` config element that would spec out a function that receives the `app` object and can mutate it in whatever way people need to.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 196 days. Feel free to comment and request for this issue to be reopened.
