### ISSUE TITLE
Click-House Dataase Connection Error 

### ISSUE THREAD

**Issue by attahkhan016** [apache/incubator-superset#3624]
Hello ,
I am new to Superset and have been trying to connect Clickhouse database to Superset. 

My database test connection is OK! it seems to be working and i am able to see the tables from the Clickhouse database. But when i try to save it , its showing me the  below error : 
"Code: 192, e.displayText() = DB::Exception: Unknown user test, e.what() = DB::Exception"
Can you let me know howto resolve this error .

**Comment by xrmx** [comment]
Looks something way down in the stack than superset. Can you post the full stacktrace you have in your logs?

**Comment by vladimirjk** [comment]
This is CH response, you're trying to connect to clickhouse with user "test"
1. Check if this user exists in CH with password you've provided, and login access in CH is opened from IP you're trying to connect
2. Try to check that option in superset, when creating datasource "Impersonate the logged on user" isn't marked - it shouldn't be selected
