### ISSUE TITLE
 Feature Request : jinja template tags in "Visualization Type" "Markup"

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#3627]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar
#2919 

### Superset version
{"GIT_SHA": "", "version": "0.20.1"}

### Steps to reproduce

Good afternoon. There is a possibility in "Visualization Type" "Markup" "Markup Type" "html" use macros jinja like this?
`<p>My string: {{my_string}}</p>`

`      <ul>
        {% for n in my_list %}
        <li>{{n}}</li>
        {% endfor %}
      </ul>
`

If so, you can sample how to get data from Datasource

We want to use this feature to generate reports using html formatting

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 195 days. Feel free to comment and request for this issue to be reopened.
