### ISSUE TITLE
Regression: No line wrapping in slice title

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3628]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
Long slice titles are wrapped to make them fit into the slice.

This it the way it used to be in 0.15.4:
![bug_slice_title_break0](https://user-images.githubusercontent.com/1220356/31328169-e0e886be-acd3-11e7-934d-58741e67e85c.PNG)

### Actual results
The slice title is not wrapped and — depending on the Visialization Type — either overlap the slice boundaries or are hidden within a horizontal scroll range.
![bug_slice_title_break1](https://user-images.githubusercontent.com/1220356/31328172-e47c0242-acd3-11e7-8fea-25e1404d6fd0.PNG)

### Steps to reproduce
Create a slice with a long title and try to fit it into a narrow area on a dashboard.

**Comment by rumbin** [comment]
Please also notice, that the legend in the Distribution Bar Chart is also entirely gone, unless the slice is given at least one more step in width than the minimal one.

**Comment by mistercrunch** [comment]
@graceguo-supercat I think this is a regression caused by https://github.com/apache/incubator-superset/pull/3467
