### ISSUE TITLE
[Explore] Regression: Main Datetime Column not chosen automatically

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3629]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
When creating a new slice, the _Time Column_ is automatically set to the one that is defined as _Main Datetime Column_ for the respective Datasource table.

This was the behavior in superset 0.15.4

### Actual results
A time column different from the Main Datetime Column is chosen. I don't exactly know by which criterion, though.

### Steps to reproduce
Explore a table which features several time columns and which has a _Main Datetime Column_ set. You may have to alter the setting of _Main Datetime Column_, maybe, as it may happen, that the right column is picked in Explore view just by chance...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 195 days. Feel free to comment and request for this issue to be reopened.

**Comment by rumbin** [comment]
@mistercrunch please reopen, as it is a regression of what once used to work. In my eyes this is the main purpose of having a default time column defined in the table definition.
