### ISSUE TITLE
pls. add docs for dashboard filtering

### ISSUE THREAD

**Issue by philippfrenzel** [apache/incubator-superset#363]
Hi,

I tried to build a dashboard that i can filter on time and a list of sites. I didn't find any guide how to do it and didn't get it to work by trial and error. Can you pls. provide a short guide how to do someting like this?

Thanks Philipp

![image](https://cloud.githubusercontent.com/assets/2319890/14579887/06f6c8a2-03bb-11e6-9101-0c8ff3c4f60d.png)

**Comment by sid88in** [comment]
@philippfrenzel I am planning to add some tutorial videos this week for various features. For now you can add filters as a slice.

**Comment by philippfrenzel** [comment]
Hi, I tried to add them as a slice - as you can see in the picture - but it's not beeing applied :/

**Comment by panxinyang2014** [comment]
@sid88in Can I  filter a time scope? just as select a begin date and a end date then filter the slice?

**Comment by sid88in** [comment]
@panxinyang2014 You can control time start and end date from slice model view (query form). You might be able to query on time scope if you add filter on time dimension (but I have not yet tested it). I do think there is lot of scope for improvement in time filters in current versions of caravel.

**Comment by mistercrunch** [comment]
@panxinyang2014, we have yet to add a time filter.

I was thinking of adding a `show time filter` boolean option in FilterBox that would show as two datepickers at the top of the widget

**Comment by philippfrenzel** [comment]
@mistercrunch - selecting timeranges by datepickers is an option but not really sexy;)
Within all analysis, time is always a fixed dimension, that's why most BI tools have already prebuild calenders that allow to group, filter, sort by this special dimension.

I think what would be a possible option - is like an filter sidebar that you can open and then make your time pick ;)

if you like I can make a quick mockup ;)

Best Philipp

**Comment by tiffyangel89** [comment]
Wtf???? What the hell is this

**Comment by vminc** [comment]
I really appreciate it if this feature is supported and in the datepicker, it is possible to easily select preconfigured period like "Last month", "Month to date", etc. Thanks!

**Comment by vminc** [comment]
I guess I mean something similar to the Google Analytics's date picker below: ![screen shot 2016-05-09 at 9 44 01 am](https://cloud.githubusercontent.com/assets/5211799/15120465/b18b76ca-15ca-11e6-8b82-8eb008132b9a.png)

**Comment by yuxf** [comment]
I would like to vote for adding time scope filter, so that I am able to select a begin date and an end date on my dashboard. Thanks.

**Comment by abodacs** [comment]
@sid88in any new news about  tutorial videos ??

**Comment by vschoener** [comment]
Hi, any news about it ?

**Comment by mistercrunch** [comment]
http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 264 days. Feel free to comment and request for this issue to be reopened.
