### ISSUE TITLE
Incorrect Range Filter and DATE_FORMAT() conversion introduce in 0.20.3

### ISSUE THREAD

**Issue by macfly1202** [apache/incubator-superset#3630]
Make sure these boxes are checked before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if any
- [v] I have reproduced the issue with at least the latest released version of superset
- [v] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
[0.20.3]

### Expected results
Having correct MYSQL DATE_FORMAT() conversion on dedicated dimension and range filter From/To. 

### Actual results
The behavior was correct in superset 0.20.1.
The sql query add one more %. Date_Format() is false and range filter too.  

```
SELECT status AS status,
       DATE_FORMAT(dateProcess, '%%Y-%%m-%%d %%h:%%m:%%s') AS `dateProcess_string`,
       dateProcess AS __timestamp,
       COUNT(*) AS count
FROM synchro_es_prod
WHERE `dateProcess` >= STR_TO_DATE('2017-10-02 00:00:00', '%%Y-%%m-%%d %%H:%%i:%%s')
  AND `dateProcess` <= STR_TO_DATE('2017-10-09 08:49:31', '%%Y-%%m-%%d %%H:%%i:%%s')
GROUP BY status,
         DATE_FORMAT(dateProcess, '%%Y-%%m-%%d %%h:%%m:%%s'),
         dateProcess
ORDER BY count DESC
LIMIT 50000`
```

![capture d ecran_2017-10-09_10-50-14](https://user-images.githubusercontent.com/6387630/31330900-879c3a08-ace0-11e7-876f-7eea0bc99816.png)

### Steps to reproduce
Add an expression DATE_FORMAT() conversion on top of datetime dimension. Inspect query on Table View visualization.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 195 days. Feel free to comment and request for this issue to be reopened.
