### ISSUE TITLE
Unable to create a scatter plot using a column as x-axis and another as y-axis

### ISSUE THREAD

**Issue by arunnatva** [apache/incubator-superset#3640]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0

### Expected results
Need to be able to generate a scatter plot using two variables (x-axis, y-axis). Superset does not have a visualization for scatter plot. I am using it with Druid and Druid is always forcing me to choose metrics variables for x & y axes. But I want to use the variables as x & y axes without aggregating them. I am kind of stuck with this issue. can you please help me out

### Actual results

I have tried bubble chart but it didnt help
### Steps to reproduce
load data into druid where you just have two columns along with time series xvar, yvar. Try to plot a scatter plot with xvar & yvar

**Comment by xrmx** [comment]
If you work at Hortonworks am pretty sure you can sort out what version of superset you are shipping :)

**Comment by arunnatva** [comment]
@xrmx sorry for being lazy.. the version of HDP I am using ships SUPERSET v 0.15.0

**Comment by TryHarder01** [comment]
I'd like to 2nd this as a feature request. Creating a basic scatter plot would be tremendously helpful.

**Comment by zezuladp** [comment]
how in the world is this not built in

**Comment by xrmx** [comment]
@zezuladp please show some respect, that kind of comments are not appreciated.

**Comment by tristix** [comment]
+1
