### ISSUE TITLE
Dashboard date filter "TypeError: Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#3649]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
Dashboard date filter should work

### Actual results
Error occurs on filter slice:

An error occurred while rendering the visualization: TypeError: Cannot read property 'map' of undefined

### Steps to reproduce

1. Create dashboard
2. Add filter to dashboard
3. Apply date filtering
4. Refresh dashboard

**Comment by xrmx** [comment]
Am pretty sure you haven't posted the full stacktrace from your server logs

**Comment by DaimonPl** [comment]
I did not see anything in server logs (stdout from superset process). I used tail -f during dashboard testing and that error was not visible there

**Comment by xrmx** [comment]
Ah! sorry, that's a js error :)

**Comment by DaimonPl** [comment]
Yeah,

I managed to get log in console but it looks like minified code so probably not useful anyway

> Uncaught TypeError: Cannot read property 'map' of undefined
    at t.e (dashboard.5181d5d45936098fa409.entry.js:135)
    at f._renderValidatedComponentWithoutOwnerOrContext (dashboard.5181d5d45936098fa409.entry.js:61)
    at f._renderValidatedComponent (dashboard.5181d5d45936098fa409.entry.js:61)
    at f._updateRenderedComponent (dashboard.5181d5d45936098fa409.entry.js:61)
    at f._performComponentUpdate (dashboard.5181d5d45936098fa409.entry.js:61)
    at f.updateComponent (dashboard.5181d5d45936098fa409.entry.js:61)
    at f.performUpdateIfNecessary (dashboard.5181d5d45936098fa409.entry.js:61)
    at Object.performUpdateIfNecessary (dashboard.5181d5d45936098fa409.entry.js:29)
    at k (dashboard.5181d5d45936098fa409.entry.js:29)
    at m.perform (dashboard.5181d5d45936098fa409.entry.js:34)

**Comment by DaimonPl** [comment]
And image as well

![filter_error](https://user-images.githubusercontent.com/9693936/31438398-49492ec4-ae88-11e7-9e0c-6387bfeefa87.png)

**Comment by DaimonPl** [comment]
Not sure if it matters but we've got cache enabled for that datasource

**Comment by Mogball** [comment]
https://github.com/apache/incubator-superset/issues/3650 is a result of this issue

**Comment by DaimonPl** [comment]
So when can we expect 0.20.4 with this fix? :)

**Comment by famasya** [comment]
I am experiencing this again in the 0.28.1 version when I applied date filter. Any fix?

**Comment by nuria** [comment]
Same here, we are seeing this error in javascript on 0.28.1

**Comment by garima301984** [comment]
Getting this error while trying to use mapbox in superset
An error occurred while rendering the visualization: TypeError: e.filter is not a function

**Comment by sudeshmu** [comment]
@nuria I can see this error is fixed on in 0.29.0rc7 version, I was facing the same issue I upgraded to 0.29.0rc7 version and I can see this is resolved for me.

Reference,
https://www.aimks.com/superset-filter-box-error-cannot-read-property-map-of-undefined-solution.html

**Comment by hemantaggarwal** [comment]
@sudeshmu I am also facing same issue. I am trying to upgrade superset 0.28.1 to latest version by running command 
"pip install superset --upgrade" but it is not upgrading to latest version. It is saying "requirement already satisfied".
