### ISSUE TITLE
[SQLLab] Regression: "share query" is broken behind https-only proxy

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3655]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
Selecting _share query_ from a tab's context menu copies the link for this very query.
This worked in superset 0.15.4, generating a link of the syntax `http(s)://host/r/123`

### Actual results
Trying the same in 0.20.4 copies a link of the syntax `http(s)://host/superset/sqllab?id=5`.
Accessing the link yields a message _THE QUERY COULDN'T BE LOADED_

The workaround of first saving the query and then copying the link in the _Saved Queries_ overview table works, but this is probably not the best way of quickly sharing a query.

### Steps to reproduce
Selecting _share query_ from a tab's context menu and try to access the copied URL.

**Comment by rumbin** [comment]
Interestingly, it may also happen, that simply nothing at all gets copied into the paste buffer. I haven't found a pattern, though.

**Comment by mistercrunch** [comment]
Tried to reproduce but couldn't. Maybe it's related to something in your application state? To confirm you can try to recreate in incognito mode.

**Comment by rumbin** [comment]
What I tried so far:
* browsers: Firefox, IE, Vivaldi
* Clearing browser history, cookies and cache in Vivaldi
* incognito mode in FF
* rebooting Windows7

None of this had any effect. What else could I try for debugging?
Is the URL pattern as it was in 0.15.4 still the one that is supposed to be generated in 0.20.4?

**Comment by rumbin** [comment]
Just tried it on a different client PC and got the same result.

I'd like to mention that the superset instance is running in an _entirely fresh python 3.4 venv_. I.e., the only part that has been migrated (`superset db upgrade && superset init`) was the superset database.

For this reason I'm particularly puzzled why you guys don't face the same issue...

**Comment by rumbin** [comment]
A little bit of debugging:

* When selecting _share query_ from the tab's context menu, the action is confirmed by a _Copied!_ popup. The console output changes from `[stats_logger] (incr) queries` (1 entry per second, BTW) to `[stats_logger] (incr) store` once.
* However, there is no new entry created in the superset's `url` table.
* Sharing of slices is working as it used to. So the creation of the entry in the `url` table is not an issue, apparently.

**Comment by mistercrunch** [comment]
But you get a url with an id don't you?
<img width="769" alt="screen shot 2017-10-12 at 8 37 10 am" src="https://user-images.githubusercontent.com/487433/31504953-96c477da-af28-11e7-812e-dc22b9ff7dfd.png">

There should be an entry in the `keyvalue` table.

**Comment by rumbin** [comment]
* I do get an URL (most of the time), which is built like this one: `
https://hostname/superset/sqllab?id=17`.
* And I do get an entry in the `keyvalue` table which carries this id and the corresponding SQL string .

However, when I try to load this URL again, superset claims:
![grafik](https://user-images.githubusercontent.com/1220356/31512448-480a7398-af8b-11e7-8256-66a690280c71.png)

Unfortunately, there is not the tiniest hint in the console log when calling this URL.

Hust in case that this may be the cause: we are using Postgres as OLTP database for superset.

**Comment by rumbin** [comment]
OK, it's not the DB's problem. It rather seems to be caused by our reverse-proxy configuration. SSH-ing to the machine and tunnelling port 8088 provided the full functionality.

I'll try to get this issue tackled with our beautiful™ IT dept, but would like to keep it open just in case someone could give me a hint why we observe this behavior when being behind the reverse proxy...

**Comment by rumbin** [comment]
Our IT found the issue being caused by the fact that the `hostname/kv/[\d]*` URL is called as http link, not as https. In our configuration http is not allowed though, but redirected to https. This is where the resolution fails somehow.

@mistercrunch: In my understanding this really seems to be a bug, as http should be used, if the rest of superset is served via https. Or is there anything wrong in our configuration, where we fail to tell superset that only https links should be generated?

**Comment by xrmx** [comment]
@rumbin a patch from your IT department is very welcome :)

**Comment by rumbin** [comment]
@xrmx Well they just checked their logs, not the source code. They are not developers. Neither am I, but I can have a look, if anyone gave me a hint to where to start looking....

**Comment by rumbin** [comment]
Our IT department got the issue sorted. The following Apache settings did the trick:
```
ProxyAddHeaders On
RequestHeader set X-Forwarded-Proto "https"
ProxyAddHeaders
```

This ensures the following flags are set: X-Forwarded-For, X-Forwarded-Host and X-Forwarded-Server.

**Comment by xrmx** [comment]
@rumbin Please add it to the documentation

**Comment by rumbin** [comment]
reopening, until documantation task is done;

BTW: Adding `RequestHeader set X-Forwarded-Proto "https"` is sufficient.
