### ISSUE TITLE
Export Dashboard doesn't work

### ISSUE THREAD

**Issue by ponomar** [apache/incubator-superset#3656]
Version 0.20.4 (the latest)
It's just reloading the page and nothing happens after.

**Hot fix**
```
# superset/views/core.py

- '/dashboardmodelview/export_dashboards_form?{}'
+ '/dashboardmodelview/export_dashboards_form?action=go&{}'
```

**Comment by liuzn4ever** [comment]
A page is intercepted by the browser ,you can use the Edge of win10，then you can download the dashboard file,and its suffix name is .pickle

**Comment by patrick-michelberger** [comment]
ponomar's hotfix worked for me. the problem still exsits in the current superset version. @ponomar any plan's to create a pull request for that?

**Comment by mistercrunch** [comment]
Turn off your popup blockers

**Comment by yamyamyuo** [comment]
you can follow this steps https://www.asus.com/us/support/FAQ/1007483/ to turn off your pop up blockers, and in the meanwhile, you should set your  `config.py`
```
# Add endpoints that need to be exempt from CSRF protection
WTF_CSRF_EXEMPT_LIST = ['http://localhost:8080']

```

**Comment by DungLai** [comment]
> Enabling the popup solved this issue.
> 
> But exporting a table as a csv works without enabling the popups. Exporting dashboards should also work this way.

Same, it doesn't work
