### ISSUE TITLE
Choose language is brocken

### ISSUE THREAD

**Issue by invenis-paris** [apache/incubator-superset#3657]
### Superset version
0.20.3

### How to reproduce
When you click on a flag to change language there is no text modification when the page is reloaded

**Comment by Mogball** [comment]
Check this out https://github.com/apache/incubator-superset/pull/3645

**Comment by invenis-paris** [comment]
This PR restore some translation but this issue is because language does not change when you change it with the tiny flag

**Comment by mistercrunch** [comment]
Closing as this should be fixed in the next release

**Comment by xrmx** [comment]
Has it been fixed really? AFAIK switching language has never worked for me too.
