### ISSUE TITLE
failed to add oracle view as superset table.

### ISSUE THREAD

**Issue by modastyle** [apache/incubator-superset#3658]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
2.0.3

### Expected results
Failed to add oracle view as superset table, while it works normal at the vresion of 1.9.1.

### Steps to reproduce
Open the tablemodelview list page, click add table button, then go to the add table page, try to add an oracle view, it will fail.

**Comment by xrmx** [comment]
Check the superset logs and include any stacktrace please.

**Comment by hidetoshiito** [comment]
Hi  

I also have the same problem.  

I worked after fixing it like this.  
It is workaround.  
I do not understand the implementation of it, so I can not fix it.  

/superset/connectors/sqla/views.py
L.237  
```diff
         # Fail before adding if the table can't be found
-        if not table.database.has_table(table):  
+       try:
+           table.get_sqla_table_object()         
+       except Exception as e:
             raise Exception(_( 
```

### Superset version
0.20.5

### Actual results
An error message  
`Table [OracleScheme.ViewName] could not be found please double check your database connection, schema, and table name`
