### ISSUE TITLE
Integer values displayed as decimal

### ISSUE THREAD

**Issue by invenis-paris** [apache/incubator-superset#3659]
### Superset version
0.20.3

### Expected results
Pivot table column headline should display integer when the column in DB is BIGINT

### Actual results
Column headlines in pivot table are displayed in decimal (1.0, 2.0, etc.) 

### Steps to reproduce
A table with 
Name(VARCHAR);Days(BIGINT)
a;1
b;1
c;2

A Pivot table slice:
GroupBy: Name
Columns: Days
Metrics: count(*)
Columns should be 1 and 2 but are 1.0 and 2.0

**Comment by xrmx** [comment]
What database is this? Is this a regression?

**Comment by invenis-paris** [comment]
The database is a mysql (mariaDB). What do you mean by regression ?

**Comment by xrmx** [comment]
Regression means it used to work in a version and on a later version it stopped working or behaves differently.

**Comment by invenis-paris** [comment]
OK. First time I try this so i cannot say and I only have 0.20.3 actually

**Comment by zz22394** [comment]
I tried in 0.20.5, and got the same problem.
DB:MySQL
there is a column ``count(1) as cnt`` and it displayed like ``2.00``

**Comment by RunningPM** [comment]
for bar chart Y axis, we can choose .1s format to show int instead of decimal. but i dont know how to solve it for a table view
