### ISSUE TITLE
"Time Series Table" is missing hyphen

### ISSUE THREAD

**Issue by Mogball** [apache/incubator-superset#3669]
### Superset version
0.20.4

Just to be consistent with the rest of the time series vis labels, it should be "Time Series - Table"

### Steps to reproduce
In explore view, click the viz control, read the display label for "Time Series Table"

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 191 days. Feel free to comment and request for this issue to be reopened.
