### ISSUE TITLE
Postgres - Allowed characters in column names 

### ISSUE THREAD

**Issue by GlombSt** [apache/incubator-superset#367]
Hi there, on views we define, we try to use names that are meaningful for the average user.

For example:
`SELECT ....        AS "% Conversion of mandate users that become buyers"
`

When defining a slice for a view with such a column it seems the column names are not wrapped in quotes and it leads to a syntax error. Can you guys fix this?

**Comment by mistercrunch** [comment]
It would help if someone could provide a failing unit test as a PR

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
