### ISSUE TITLE
URL link to parent or blank does not work within Markup or Separator widget

### ISSUE THREAD

**Issue by SeanPreusse** [apache/incubator-superset#3672]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest version

### Expected results
Link opens new window or within existing

### Actual results
Link does not execute
These widgets are helpful in creating an additional context for dashboards and natural flow through.

### Steps to reproduce
Code: <a href="http://www.google.com" target="_Parent">Link Text</a>

**Comment by xrmx** [comment]
What version is latest version? steps to reproduce should contain the procedure to replicate the issue, i don't think clicking a link to google is a superset issue.

**Comment by SeanPreusse** [comment]
Version .20.4

Sorry for not being clear. Not sure if the markup slices are intended for this, but it would be great to create a landing page and use the 'markup' slices to navigate to key dashboards. Users can still use the dashboard main page, but the landing page can have other helpful information such as image/icons and a description of the dashboard a user would navigate to.

1. Create new slice with visualisation type 'Markup'.
2. Add title, image and url to link to another dashboard, description.
'<a href="../1/" target="_target">Link Text</a>'
3. Create dashboard with 'markup' widgets navigating to key dashboards
4. When you click on the link, nothing happens.
![image](https://user-images.githubusercontent.com/15626895/31582852-7c78e726-b1da-11e7-8d32-de7075624e51.png)

**Comment by jaylindquist** [comment]
@xrmx PR #3702 opened to fix this. The issue was the iframe was sandboxing and preventing links from opening outside of the iframe.
