### ISSUE TITLE
How can I change the visualization? Changes are not displayed in the browser.

### ISSUE THREAD

**Issue by Oxystin** [apache/incubator-superset#3675]
Developers please help. I have been suffering for two days. I need to change the visualization of some graphs. Superset installed via Docker. I am modifying the container for the files _nvd3_vis.js_ and _chord.jsx_. But my changes are not displayed in the browser. There is a feeling that the * .js (x) files are cached. I reset the cache in browsers, restarted the container and even deleted the file nvd3_viz.js. This did not help me. Everything works without changes. Tell me what you need to do to see the changes, after editing the files in the folder ... / superset / assets / visualizations /?

And tell me the development environment, in which it will be convenient to debug the project?

**Comment by xrmx** [comment]
We're in 2017 where the frontend is built. You have to modify the source and then rebuild the whole thing. Next time looking at the documentation may save you two days of suffering  https://superset.incubator.apache.org/installation.html#making-your-own-build

**Comment by Oxystin** [comment]
@xrmx Hello. Thanks for the reply. The documentation I have read. Unfortunately I'm not advanced user to understand. I need to change only the angle of the label graphics. This can be done by removing a couple of lines in the source. I thought it can be done quickly. It turned out that it is more difficult. I'll try to understand. 

Do you find it difficult to write a procedure or give a link? I can enter these commands in a Docker container? Sorry for the stupid questions.

**Comment by Oxystin** [comment]
@xrmx Hello. Thanks for the reply. The documentation I have read. Unfortunately I'm not advanced user to understand. I need to change only the angle of the label graphics. This can be done by removing a couple of lines in the source. I thought it can be done quickly. It turned out that it is more difficult. I'll try to understand.

**Comment by Oxystin** [comment]
@xrmx act according to instructions. Throws the error:

root@ubuntu:/superset/superset/assets# yarn
yarn install v1.2.1
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
info No lockfile found.
[1/4] Resolving packages...
warning brfs > static-module > through2 > xtend > object-keys@0.4.0:
warning react-map-gl > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning react-map-gl > mapbox-gl > vt-pbf > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning react-map-gl > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning react-map-gl > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning react-map-gl > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
warning github-changes > parse-link-header > xtend > object-keys@0.2.0: Please update to the latest object-keys
warning github-changes > github-commit-stream > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
**error mapbox-gl@0.38.0: The engine "node" is incompatible with this module. Expected version ">=6.4.0".**
**error Found incompatible module**

root@ubuntu:/superset/superset/assets# yarn run build
yarn run v1.2.1
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ NODE_ENV=production webpack --colors --progress
**error Couldn't find the binary NODE_ENV=production webpack --colors --progress**

Tell me, this procedure must be run after each edit of the sources?

**Comment by Oxystin** [comment]
@xrmx thank you for the tip! It worked for me!
Tell me, this procedure must be run after each edit of the sources?
It is long enough. How then to debug your code?

**Comment by mistercrunch** [comment]
`npm run dev` will watch the files for modifications and re-compile as you edit

**Comment by brentEich** [comment]
@mistercrunch I'm attempting to edit files such as **static/assets/src/actions.js**, just simple edits such as success alerts. I've rebuilt and cleared my cache, but the changes still don't register in the browser. You mentioned **npm run dev** is this a prerequisite to seeing the changes or does this just make it quicker to view the changes?
