### ISSUE TITLE
The Dashboard's chart can't export to other document(Excel, PDF ....)

### ISSUE THREAD

**Issue by baocaiwang** [apache/incubator-superset#3677]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
the charts in Dashboard can export into Excel or PDF document

### Actual results
I can't find the way to complete this function

**Comment by xrmx** [comment]
Dup of #2995 please close
