### ISSUE TITLE
Parameter issue in MYSQL query

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [apache/incubator-superset#3682]
Hi, I just installed superset and tried to connect to my mysql datasource.  This is the error I was keep getting

```
ERROR:root:execute() got an unexpected keyword argument 'args'
Traceback (most recent call last):
  File "/Users/jeeva/anaconda/lib/python2.7/site-packages/superset/sql_lab.py", line 179, in execute_sql
    **db_engine_spec.cursor_execute_kwargs)
TypeError: execute() got an unexpected keyword argument 'args'
```

Here is what i am using to connect to the source - its a mysql connector driver.

`mysql+mysqlconnector://root:XXXXXXXXXX@127.0.0.1:3306/databasename`

This line is what causing this issue,

https://github.com/apache/incubator-superset/blob/d0b5b449b281022d497f2079f83b103602c7077c/superset/sql_lab.py#L178

After I commented this line and changed it to 

        #cursor.execute(query.executed_sql,
        #               **db_engine_spec.cursor_execute_kwargs)
        cursor.execute(query.executed_sql)

It worked, posting it here for two reason, one is to share if anyone is facing the same issue and searching for the reason, second one is to know, is there anything wrong with my approach, do I have to install different mysql driver or something?

**Superset version**
superset-0.20.4

Thanks.

**Comment by mistercrunch** [comment]
We  recommend using the `mysqlclient` lib and just `mysql://` connection strings. If you need to use another driver (mysqlconnector?) then you may need to touch the code up a bit.

**Comment by Jeeva-Ganesan** [comment]
All good. Thanks.

**Comment by fordguo** [comment]
with mysqlconnector ,I got the same error.
superset version 0.25.5
