### ISSUE TITLE
Feature proposal: trim for the bar chart labels

### ISSUE THREAD

**Issue by dmigo** [apache/incubator-superset#3700]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 0.20.1

Sometimes users have labels that are quite long.
Would this kind of trim be a useful feature for superset?
I would start a PR, but just want to know your opinion first.

### Expected results
![image](https://user-images.githubusercontent.com/7461607/31662282-0493e5a2-b33e-11e7-8ee7-6f40388da696.png)

### Actual results

![image](https://user-images.githubusercontent.com/7461607/31662237-d9829c0a-b33d-11e7-8d1f-b0c65d3cecd7.png)

**Comment by xrmx** [comment]
Maybe ut's easier to do that as sql expression, i think it would be quite hard to please everyone.

**Comment by dmigo** [comment]
@xrmx it might be that after trim in SQL several different categories will end up in one. 
e.g. `abcde1` and `abcde2` gonna be trimmed to `abcde`.
An alternative could be just to hide those labels, tooltips would be sufficient.

**Comment by williaster** [comment]
horizontal bar charts handle variable-length text much better than vertical bar charts.

**Comment by dmigo** [comment]
@williaster can't find those. Where can I configure the layout of a barchart?

**Comment by williaster** [comment]
currently horizontal bars are not supported, I just meant as a solution horizontal bars will likely be better than other options with vertical bar labels because there are only so many options (truncate or rotate).

we are ramping up to do a big pass at visual design consistency across charts and will likely add this at that time.
