### ISSUE TITLE
Show continuous timeline on x-axis for Time Series plots

### ISSUE THREAD

**Issue by qeorqe** [apache/incubator-superset#3708]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
When I display my data on time series plot, I want to see the **continuous timeline** with objects (bars or points) on it. 
If there are any gaps between the objects, I want to see all the gaps on the timeline.

### Actual results
Look at the timestamps below the plot for the Time Series Bat Chart. 
All the objects are arranged side-by-side, so I don't see the gaps between them.
The same is for Time Series Line Chart. 

![continuous timeline](https://user-images.githubusercontent.com/15161073/31896424-660aa540-b81c-11e7-8457-690ab9d93452.png)

**Comment by layzerar** [comment]
Is there any plan for this?

If inserting zeros for missing time series is acceptable, I can submit a PR for this.

**Comment by rumbin** [comment]
I think, this behavior is all the same with other time series representations. Effectively, it gets plotted what the DB query returns. If there is no data present for a certain interval step, then the DB does not return any row.

I guess, the way superset is designed, you are supposed to resample the data via the Advanced Analytics tab in Explore in order to fill missing values.

Personally, I would not favor to have the timeline generally filled with zeros, as often enough I am only interested in the real events.

**Comment by rumbin** [comment]
I agree, though, that this is counter intuitive to fresh users...

**Comment by SpyderRivera** [comment]
Could it be an option to fill in missing data with zeros? Like a tick box?

**Comment by lgellis** [comment]
Can we please re-open this issue?  If superset didn't specialize in time-series data, I could maybe see that it might not need to fill in missing time periods with 0 values.  This would just be plotting the data as-is with time being like any other category.

However, superset does specialize in time-series data.  And so it should handle the effective plotting of missing data for time frames.  In time series analysis you need to represent all time intervals that you are plotting across.  This is industry standard for time focused plots and it's what data viz viewers are expecting.

**Comment by zheya08** [comment]
Can we please re-open this issue +1. It's very easy to ignore the missing 0 value if the timeline is not continuous. I think we can add a function like 'padding timeline' in "Advanced Analytics".  If user enable the function ,   a continuous pandas datetime series  will be left join the queried dataframe and fill na with 0.
