### ISSUE TITLE
Intall Superset same instance in different server

### ISSUE THREAD

**Issue by annusri** [apache/incubator-superset#3709]
I installed Superset few months back on Server A. I created few Slices/Dashboard.

Now I'm trying to install Superset on Server B. But I want all the config, slice, dashboard which exists on Server A to be copied to Server B.

In other words, Server A and Server B, should be ditto copy of each other. Can I do this.

Superset Version on Server A-
{"GIT_SHA": "", "version": "0.20.0"}

**Comment by xrmx** [comment]
It's everything in the db

**Comment by annusri** [comment]
@xrmx  - ok. so everything is in the superset.db.

I'm getting the below error after following this steps.

Here is what I did on the new server -

# Install superset
pip install superset

# Create an admin user (you will be prompted to set username, first and last name before setting a password)
fabmanager create-admin --app superset

# Initialize the database
superset db upgrade

# Load some data to play with
superset load_examples

# Create default roles and permissions
superset init

##########
Here I copied the superset.db  and superset_config.py from Server A to Server B and started the superset server as below

# Start the web server on port 8088, use -p to bind to another port
superset runserver

when I try to access the bashboard, got the below error
OperationalError: (sqlite3.OperationalError) no such column: sql_metrics.warning_text [SQL: u'SELECT sql_metrics.created_on AS sql_metrics_created_on, sql_metrics.changed_on AS sql_metrics_changed_on, sql_metrics.id AS sql_metrics_id, sql_metrics.metric_name AS sql_metrics_metric_name, sql_metrics.verbose_name AS sql_metrics_verbose_name, sql_metrics.metric_type AS sql_metrics_metric_type, sql_metrics.description AS sql_metrics_description, sql_metrics.is_restricted AS sql_metrics_is_restricted, sql_metrics.d3format AS sql_metrics_d3format, sql_metrics.warning_text AS sql_metrics_warning_text, sql_metrics.table_id AS sql_metrics_table_id, sql_metrics.expression AS sql_metrics_expression, sql_metrics.changed_by_fk AS sql_metrics_changed_by_fk, sql_metrics.created_by_fk AS sql_metrics_created_by_fk \nFROM sql_metrics \nWHERE ? = sql_metrics.table_id'] [parameters: (3,)]

**Comment by mistercrunch** [comment]
https://superset.incubator.apache.org/installation.html#upgrading
