### ISSUE TITLE
Beginner question: Installation verification

### ISSUE THREAD

**Issue by T0MK4T** [apache/incubator-superset#3719]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
reach example data via browser

### Actual results
timeout

### Steps to reproduce
I followed the install instructions with no errors on https://superset.incubator.apache.org/installation.html
running on Centos 7 remote server.

The one difference is I'm using Miniconda3 and created an environment in there rather than virtualenv.  Once I attempt to 'superset runserver' I get the following:
![capture](https://user-images.githubusercontent.com/935982/32019925-42d320ba-b994-11e7-8382-d82796b8b949.PNG)

However when I go to that server's IP at the designated port 8088 on my windows computer, I get a timeout error.  I am able to access other files off the server fine from my windows PC.

**Comment by xrmx** [comment]
Check the firewall
