### ISSUE TITLE
Documentation: Python docs for how to programmatically create slices and datasources

### ISSUE THREAD

**Issue by frankfarrell** [apache/incubator-superset#3725]
Hi, 

We would like to pull database config for our datasources from a source dynamically on startup and create the datasources and slices at startup. We would like to script this in python as you have done in the load_examples script. We are planning to have multiple environments dev/staging/prod etc and this would be easier than configuring each time through the UI. 
Could you document how to do this?

Thanks!

Frank

**Comment by mistercrunch** [comment]
Would be great if someone would document some simple examples, but as you said it's basically just using the `sqlalchemy` ORM using Superset's models. As you said there are great examples in `superset/data/__init__.py`

**Comment by mistercrunch** [comment]
Leaving open if someone wants to pick this up.

**Comment by moscowart** [comment]
@mistercrunch can I also add Druid cluster this way? I think I could document at least this example then.

**Comment by mistercrunch** [comment]
Sure yes. SqlAlchemy acts as a neat CRUD api. Also note that if in another language it's possible to use the crud REST API exposed as part of each model.

Check out `/slicemodelview/api` for Slices for example.

**Comment by moscowart** [comment]
@mistercrunch I tried using APIs but I always get `The CSRF token is missing.` I tried to google it but found solutions only for JS and HTML forms. I also tried to intercept POST request in Chrome and figured out that there is `csrf_token` parameter passed. But I don't understand where its value is taken from. Is there something I'm missing?

**Comment by mrsowmya** [comment]
Can you please provide the rest api documentation link.

**Comment by mistercrunch** [comment]
http://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html#rest-api
