### ISSUE TITLE
warning "@data-ui/event-flow@0.0.11" has unmet peer dependency "aphrodite@^1.2.0"

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3727]
@williaster can you help fixing this error msg?

**Comment by williaster** [comment]
@mistercrunch yeah this should be fixable by adding `aphrodite` as a dependency. That's a bit heavy to bring in, though, would be ideal if we could factor that out but it would take longer to do that 🤔 . 

do you have an opinion on which route we go?

**Comment by mistercrunch** [comment]
So that's an optional dependency then?

**Comment by williaster** [comment]
no a peer dependency is a required dependency, but it is different from other dependencies in that it must be a singleton, i.e., across _all_ packages you are using, you must only have a single instance (and version) of that package. `React` is an example of this. 

so the options were either 
- add `aphrodite@^1.2.0` as a dependency in superset or (fast, but new dependency)
- factor it out of `@data-ui/event-flow` (slower, but removes the package as a dependency)

or do the first for now and remove it once it's gone from `@data-ui`

**Comment by mistercrunch** [comment]
So how are things working now with the missing dep?

**Comment by williaster** [comment]
^good question, will dig in further
