### ISSUE TITLE
Bug: Users page does not render rows after selecting higher pagination size

### ISSUE THREAD

**Issue by afernandez** [apache/incubator-superset#3731]
In the Users page, filter for a subset of users, e.g., users whose first name is John shows 34 results.
Then select a higher pagination size; when I select 100 it fails to render any results and the pagination button disappears, but 50 works.

In the DOM, `<div class="table-responsive">
        <table class="table table-bordered table-hover">` only contains a header but no rows.
See screenshots

- [y] I have checked the superset logs for python stacktraces and included it here as text if any
- [y] I have reproduced the issue with at least the latest released version of superset
- [y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.1
6a2a11af7685c9377697a660c2da4829bc9f294b

### Expected results
Show render the result rows.

### Actual results
No rows are shown.
![screen shot 2017-10-27 at 11 16 13 am](https://user-images.githubusercontent.com/225711/32119850-55539cf6-bb0b-11e7-99ae-246046ea98c6.png)

### Steps to reproduce
See above

**Comment by mistercrunch** [comment]
This may be a FAB bug, haven't dug in though.

**Comment by baldoalessandro** [comment]
Yes this looks like a FAB bug.
These are the steps to reproduce it:

- Assuming 34 results and a pagination size of 25 (default)
- Go to the last page, in this case page 1
- Switch to page size 50
- the URL is still requiring page 1 but this page no longer exist `page_UserDBModelView=1&psize_UserDBModelView=50`
