### ISSUE TITLE
Clean up translations

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3745]
Per this line in this PR https://github.com/apache/incubator-superset/pull/3740/files#diff-21213919e9d7699522fc8d0fcabdc63fR157  it looks like the translations have changed locations, or at least in parts.

I think everything used to be in `babel/` but now it looks like some of it moved to `superset/translations` and some files have stayed where the were.

Should we just move everything under `superset/translations/`?

@graceguo-supercat

**Comment by alanmcruickshank** [comment]
Given I've been in this bit of the code recently, I'm happy to do some testing and submit PR if we think this is a good idea.

**Comment by graceguo-supercat** [comment]
I am not sure how it was long time ago, but when we make Chinese translations, only
`babel.cfg` and `messages.pot` are in `babel/`. According to CONTRIBUTING.md we can set translation target.

**Comment by mistercrunch** [comment]
@alanmcruickshank perfect if you want to change this up. I think we should do as much as possible under `superset/translations` and get rid of `babel/`.

Also we should probably remove all of the generated files out of the repo, that includes the `.mo` files, `message.json` and maybe more files.

Another nice thing would be to wrap translation processing inside a superset CLI command.

**Comment by alanmcruickshank** [comment]
@mistercrunch - for the generated files - if we move them out of the repo - do you see that generating them is then part of setting up your dev environment? Likewise do we have to make that a build step for the final deployment version?

Happy to wrap it into the cli - sounds like a good idea.
