### ISSUE TITLE
Data Source Creation error for Oracle client connection

### ISSUE THREAD

**Issue by subrahmpatel** [apache/incubator-superset#3752]
Hi Team,

We are trying to connect a new data source for oracle in the SQL Alchemy URL section using below detail.

oracle://rpt_rdonly_user:password@xx.xxx.xx.xxx:1521/JID

On executing the same on the super set we are receiving the below error. Kindly suggest.

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(cx_Oracle.DatabaseError) DPI-1047: 64-bit Oracle Client library cannot be loaded: \"libclntsh.so: cannot open shared object file: No such file or directory\". See https://oracle.github.io/odpi/doc/installation.html#linux for help"}

Below Are the Server Detail:-
1) RHEL(red hat linux) 6.6 
2) Python 2.7.5
3) Oracle Client version 12c on Apache Server

Regards,
Subrahm Patel

**Comment by xrmx** [comment]
This and #3754 looks like your oracle client / access is not properly setup. Does not look related to superset.
