### ISSUE TITLE
Data Source Creation Error for Oracle client

### ISSUE THREAD

**Issue by subrahmpatel** [apache/incubator-superset#3754]
Hi Team,

We are trying to connect a new data source for oracle in the SQL Alchemy URL section using below detail.

oracle://rpt_rdonly_user:password@xx.xxx.xx.xxx:1521/JID

On executing the same on the super set we are receiving the below error. Kindly suggest.

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n'twophase' is an invalid keyword argument for this function"}

Below Are the Server Detail:-
1.RHEL(red hat linux) 6.6
2.Python 2.7.5
3.Oracle Client version 12c on Apache Server

Regards,
Subrahm Patel

**Comment by nikitathampi** [comment]
cx_Oracle 6.0b1 is in beta. Try using the official release which is 5.3. That worked for me

**Comment by TryHarder01** [comment]
do a `pip freeze` to see what version cx_oracle you have...

install 5.3 specifically by running

`pip install cx_oracle==5.3`

**Comment by mistercrunch** [comment]
@subrahmpatel please confirm the fix and close

**Comment by TryHarder01** [comment]
Even if you get the Oracle DB to work... there's a known issue with visualizing data from an Oracle DB.

Please see issue: #953 

There are a few solutions in development, but nothing as of release 20.4
