### ISSUE TITLE
Table metadata autoload does not work on UTF-8 MySQL databases

### ISSUE THREAD

**Issue by Timester** [apache/incubator-superset#3755]
### Superset version
0.20.4

### Expected results
When I add a new table from a database that uses UTF-8 encoding, columns and metrics should be auto loaded.

### Actual results
Adding a table is somewhat successful. It shows up on the tables list screen (but the 2 colored info banners are missing from the top (new row added, and I should edit the table now)). When I go to edit the table the columns and metrics lists are empty.

After the table shows up on the tables list screen there are 3 rows in the logs:

```
2017-11-01 08:51:28,586:ERROR:root:Expecting value: line 3 column 68 (char 94)
2017-11-01 08:51:28,617:ERROR:root:Expecting value: line 3 column 68 (char 94)
2017-11-01 08:51:28,617:ERROR:root:Expecting value: line 3 column 68 (char 94)
 ```
Adding tables from non utf8 schemas are working fine.

### Steps to reproduce
Install Superset
Add a new MySQL database that has a schema created like this:

`CREATE DATABASE mydatabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

Connection string:

`mysql://root:XXXXXXXXXX@mysql:3306/mydatabase?charset=utf8mb4`

I have also tried to use just utf8 (for connection string), same results.

**Comment by xrmx** [comment]
Which version of python?

**Comment by Timester** [comment]
3.5

**Comment by mistercrunch** [comment]
Is that an issue in 3.5 only?

**Comment by KennethEnevoldsen** [comment]
Any update on this? I have similar issue?
