### ISSUE TITLE
Data Source Creation Error for Oracle client

### ISSUE THREAD

**Issue by subrahmpatel** [apache/incubator-superset#3757]
Hi Team,

We are trying to connect a new data source for oracle in the SQL Alchemy URL section using below detail.

oracle://rpt_rdonly_user:password@xx.xxx.xx.xxx:1521/JID

On executing the same on the super set we are receiving the below error. Kindly suggest.

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n'twophase' is an invalid keyword argument for this function"}

Below Are the Server Detail:-
 1.RHEL(red hat linux) 6.6
 2.Python 2.7.5
 3.Oracle Client version 12c on Apache Server

Regards,
Subrahm Patel

**Comment by xrmx** [comment]
This is the third issue you open because you can't query oracle. That's annoying, please stop.
