### ISSUE TITLE
Stackoverflow tag

### ISSUE THREAD

**Issue by dmigo** [apache/incubator-superset#3762]
I know, it is a bit weird feature request, but having a stackoverflow tag should provide a better platform for the community to ask/answer questions. 
As a bonus it might also decrease the amount of issues here.

**Comment by xrmx** [comment]
*a bit of googling* Do you know someone who has 1500 reputation points? I don't :)
https://stackoverflow.com/help/privileges/create-tags

**Comment by dmigo** [comment]
https://stackoverflow.com/questions/tagged/apache-superset
It is here =)

**Comment by xrmx** [comment]
We may want to add some hints on the README.md or CONTRIBUTING.md

**Comment by dmigo** [comment]
The PR is created.
In the meantime I found out that there is another [superset tag](https://stackoverflow.com/questions/tagged/superset) already. So, right now we have two.
However the `superset` tag is misused heavily. Would it make sense to migrate to `apache-superset` tag?

**Comment by xjrk58** [comment]
@dmigo Now you need somebody with 2500 reputation points to create synonym :) https://stackoverflow.com/help/privileges/suggest-tag-synonyms

**Comment by dmigo** [comment]
@xjrk58 
![giphy](https://user-images.githubusercontent.com/7461607/32333529-7c6b563a-bfe8-11e7-8472-39187227fbb0.gif)
