### ISSUE TITLE
broken images for "Tutorial for Superset Administrators"

### ISSUE THREAD

**Issue by sayoub** [apache/incubator-superset#3765]
All image links in "Tutorial for Superset Administrators" are broken, can you please update them.
https://github.com/apache/incubator-superset/blob/master/docs/tutorial.rst
e.g. _static/img/tutorial/tutorial_01_sources_database.png

**Comment by mistercrunch** [comment]
That RST is the source code to create this: http://superset.apache.org/tutorial.html

There's probably a way to insure that both the rendered and GH version both work...
