### ISSUE TITLE
on windows in superset sql lab error "module object has no attribute sigalrm"

### ISSUE THREAD

**Issue by davidwxy** [apache/incubator-superset#3766]
on windows in superset sql lab error "module object has no attribute sigalrm"

there is one solution on internet that edit utils.py ,plus# before the two sentences below and plus another sentence "pass"

#signal.signal(signal.SIGALRM, self.handle_timeout)
 #signal.alarm(self.seconds)
 pass

but above can't solve problem and report another error can't connect the datebase, who know why? and how to solve?

**Comment by xrmx** [comment]
I think you have missed that superset is not supported on Windows. The internet should really stop to provide bad advice.

**Comment by fredtong** [comment]
modify this file:utils.py.
the issue has solved follow up the guide of Mr. guylando @guylando

**Comment by mcmauro** [comment]
Hello fredtong,
could you pls tell me which utils.py file did you modify?

I have just listed more then 30 files for this name under the path : C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts\venv\Lib\site-packages\*.
different subfolders content such files.  
Here below I am reporting just three paths for example:
1. C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts\venv\Lib\site-packages\pip\_vendor\pytoml

2. C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts\venv\Lib\site-packages\setuptools\_vendor\packaging

3. C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts\venv\Lib\site-packages\pip\_vendor\requests
....
Many thanks in advance!

**Comment by leesonwei** [comment]
> modify this file:utils.py.
> the issue has solved follow up the guide of Mr. guylando @guylando

superset version=0.35.1
modify this file `utils/core.py`
