### ISSUE TITLE
Opening Druid datasource shows "No data was returned."

### ISSUE THREAD

**Issue by gaborhermann** [apache/incubator-superset#3768]
### Superset version
0.20.0, 0.20.4

### Druid version
0.10.1

### Expected results
Some raw data shown.

### Actual results
Shows the error "No data was returned.":

```
Traceback (most recent call last):
  File "/Users/ghermann/reporting/venv/lib/python2.7/site-packages/superset/viz.py", line 274, in get_payload
    df = self.get_df()
  File "/Users/ghermann/reporting/venv/lib/python2.7/site-packages/superset/viz.py", line 97, in get_df
    self.results = self.datasource.query(query_obj)
  File "/Users/ghermann/reporting/venv/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 1073, in query
    raise Exception(_("No data was returned."))
Exception: No data was returned.
```

### Steps to reproduce
Opening the "wikiticker" datasource (as ingested in the Druid 0.10.1 tutorial).

**Comment by mistercrunch** [comment]
Is the time filter range outside of what's in the datasource?

**Comment by SanjayJosh** [comment]
I have been trying to get a Table View on wikiticker data source provided by default in Druid (v 0.11.) with result as 
`"No data was returned".`
This is a similar issue as the one mentioned here.  
@mistercrunch I did try changing filter range to 100000 days for this. No difference.

**Comment by SanjayJosh** [comment]
Ok @mistercrunch . You were right .. I changed the filter range to 2015-09-12  : 2015-09-13 and it worked.

**Comment by usopan** [comment]
We are also facing the same issue any solution or workaround available yet.

**Comment by mistercrunch** [comment]
If the default filter (past 7 days) doesn't work for you when clicking on the datasource, you can always change the datasource's default URL to point to a specific chart as shown here:

<img width="582" alt="Screen Shot 2019-03-11 at 10 39 03 PM" src="https://user-images.githubusercontent.com/487433/54177154-7dc96800-444e-11e9-92cd-344cb8204551.png">
