### ISSUE TITLE
[TimeSeries-BarChart] Upon adding multiple metrics, the legend bar disappears.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3781]
### Superset version
"version": "0.20.3"

### Expected results
Upon adding multiple metrics, the legend bar should not get disappeared.

### Actual results
Upon adding multiple metrics, the legend bar disappears.

### Steps to reproduce
create a slice i.e. Time Series - Bar Chart 
add multiple metrics to plot 
enable the legends
query to view the data 
the legends bar won't be visible

![legend_barchart](https://user-images.githubusercontent.com/29655292/32430513-65105db2-c2f1-11e7-8303-a7bd1ffb183e.png)

screen shot is attached.

**Comment by shyam2794** [comment]
@NaukhaizAhmad you have to scroll to the right end to view the legends .
