### ISSUE TITLE
Add or modify visualisation type

### ISSUE THREAD

**Issue by mehaddiklimane** [apache/incubator-superset#3782]
Last Superset version

Hi, 
How to add a metrics button when using mapbox visualisation type with druid datasource.
I add ['metrics'] in static/assets/javascripts/explore/stores/visType.js, at line 1035 but i can get it.  
```
  mapbox: {
    label: t('Mapbox'),
    controlPanelSections: [
      {
        label: t('Query'),
        expanded: true,
        controlSetRows: [
          ['all_columns_x', 'all_columns_y'],
          ['clustering_radius'],
          ['row_limit'],
          ['metrics'], # line added
          ['groupby'],
        ],
      },
```

**Comment by mistercrunch** [comment]
This question is confusing. Checkout the CONTRIBUTING.md file

**Comment by mehaddiklimane** [comment]
I just want add Metrics <select > <select> . Where have i to change for this. See my screen short for better understanding.


![query_with_metrics](https://user-images.githubusercontent.com/31927091/32484980-0244b0be-c3a2-11e7-838a-fcf39d1510cf.png)
![query_without_metrics](https://user-images.githubusercontent.com/31927091/32484981-025d557e-c3a2-11e7-89ec-6ba53ff36c66.png)
