### ISSUE TITLE
does superset support any other map platform except mapbox 

### ISSUE THREAD

**Issue by matt90luo** [apache/incubator-superset#3790]
is it possible to make superset work with other Map platform like google map, Amap, BaiduMap?
if possible I'd like to know more details

**Comment by xrmx** [comment]
Not at the moment, but feel free to submit your own visualization.

**Comment by mistercrunch** [comment]
@matt90luo moving forward we'll be building on top of deck.gl's layers. It appears deck.gl can in theory be used with other map apis, so feasibility depends on that.

If it's somewhat trivial to support other apis we'll be happy to review/merge PRs, though I wouldn't want to bring in too much complexity or face any common-denominator problematics along with that.
