### ISSUE TITLE
yarn install failing in the latest release

### ISSUE THREAD

**Issue by ishpreet-singh** [apache/incubator-superset#3791]
### Superset version
0.20.5

### Expected results
yarn install should work properly, as it was working in previous versions

### Actual results
An unexpected error occurred: "https://registry.yarnpkg.com/brfs: ETIMEDOUT"

### Slacktrace
    yarn install v0.27.5
    info No lockfile found.
    [1/4] Resolving packages...
    error An unexpected error occurred: "https://registry.yarnpkg.com/brfs: ETIMEDOUT".
    info If you think this is a bug, please open a bug report with the information provided in 
    "/home/hp1/Desktop/Ishpreet/super_set/superset/assets/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by xrmx** [comment]
I don't think people here run the yarnpkg registry, if it's down just wait until it's up again. Please close.

**Comment by ishpreet-singh** [comment]
@xrmx  I am using superset for development, and without **yarn** I can't run the application in development mode.
