### ISSUE TITLE
Apache2

### ISSUE THREAD

**Issue by dajor** [apache/incubator-superset#3792]
Sorry - I know this not an issue form superset but is there a howto how to config Apache2 special the **superset.wsgi**

<IfModule mod_ssl.c>
<VirtualHost *:443>
	# The ServerName directive sets the request scheme, hostname and port that

        WSGIDaemonProcess supersetn user=www-data group=www-data threads=5
        WSGIScriptAlias / /var/www/superset/superset.wsgi

        <Directory /var/www/superset>
           WSGIProcessGroup superset 
           WSGIApplicationGroup %{GLOBAL}
           Order deny,allow
           Allow from all
       </Directory>

**Comment by xrmx** [comment]
the wsgi callable should be app in superset/__init__.py

**Comment by dajor** [comment]
Sorry but now i change the config to 
<VirtualHost *:443>
        # The ServerName directive sets the request scheme, hostname and port that
        WSGIDaemonProcess app user=www-data group=www-data threads=5
        WSGIScriptAlias / /var/www/superset/__init__.py

        <Directory /var/www/superset>
           WSGIProcessGroup app
           WSGIApplicationGroup %{GLOBAL}
           Order deny,allow
           Allow from all
       </Directory>

and now i have the error
Target WSGI script '/var/www/superset/__init__.py' does not contain WSGI application 'application'.

**Comment by kalimuthu123** [comment]
i am facing the same error any solution for it
