### ISSUE TITLE
error in npm install -d(babel-plugin-transform-es2015-literals)

### ISSUE THREAD

**Issue by defineus** [apache/incubator-superset#3798]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20
Mac OS 10.12.3
Python 2.7.10
npm@5.5.1

### Expected results
execute command npm install -d in superset/assets

### Actual results
Output:
`
npm http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-es2015-literals 17ms (from cache)
npm ERR! Unexpected end of JSON input while parsing near '..."sha512-Zc+kpYJymHtHo'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gdl/.npm/_logs/2017-11-08T03_28_17_044Z-debug.log

`

2017-11-08T03_28_17_044Z-debug.log:
```
3701 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."sha512-Zc+kpYJymHtHo'
3701 verbose stack     at JSON.parse (<anonymous>)
3701 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
3701 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
3701 verbose stack     at <anonymous>
3701 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
3702 verbose cwd /Users/gdl/Desktop/pyVirtualEnv/superset/superset/assets
3703 verbose Darwin 16.4.0
3704 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "install" "-d"
3705 verbose node v8.2.1
3706 verbose npm  v5.5.1
3707 error Unexpected end of JSON input while parsing near '..."sha512-Zc+kpYJymHtHo'
3708 verbose exit [ 1, true ]
```

### Steps to reproduce
git clone -b 0.20 https://github.com/airbnb/superset superset
cd superset/assets
npm -d install

**Comment by mistercrunch** [comment]
Upgrade npm and node and use `yarn` as specified in CONTRIBUTING.md

**Comment by defineus** [comment]
Thanks a lot
