### ISSUE TITLE
Time Series Table can't be scrollable

### ISSUE THREAD

**Issue by vnnw** [apache/incubator-superset#3802]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
Time Series Table should be scrollable if there is a large number of group-by dimensions.

### Actual results
Unscrollable.

### Steps to reproduce
Make a Time Series Table with a large number of group-by dimensions.

![snapshot](https://user-images.githubusercontent.com/4979571/32541732-8fe55d42-c4ab-11e7-9e01-b84867691331.png)

**Comment by michellethomas** [comment]
Thanks for bringing this up, I can take a look
