### ISSUE TITLE
[Dashboard][Slug] Spaces and hyphens are being ignored.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [apache/incubator-superset#3803]
### Superset version
0.20.3

### Expected results
- Spaces should be replaced by hyphens or underscores.
- Hyphens shouldn't be ignored.

### Actual results
Spaces and hyphens are being ignored.

### Steps to reproduce

open the dashboard configuration GUI 
add slug with spaces and hyphens 
save the dashboard configurations.
Re-open the dashboard configurations again to review the previously saved state 
the Spaces and hyphens would be missing from the slug.

P.S. All special characters are also being ignored (except underscore _).
![slug-2](https://user-images.githubusercontent.com/29655292/32551348-0cafd1bc-c4b2-11e7-91b1-ba12e728e338.png)

**Comment by xrmx** [comment]
That's exactly the purpose of the slug https://en.wikipedia.org/wiki/Slug_(publishing)

**Comment by rumbin** [comment]
Well, I don't fully agree with @xrmx. In the link provided it is clearly stated _whitespace characters [are] replaced by a dash or an underscore to avoid being encoded_. So the hyphens/dashes being dropped and the white spaces not being replaced by dashes or underscores may be regarded as unexpected behavior.

**Comment by xrmx** [comment]
Yeah the implementation of this slug is buggy (`\W+` in the re.sub matches `-`) but unless anyone cares enough to open a  PR that's not really an issue.

**Comment by TryHarder01** [comment]
It sounds like the "expected results" aren't exactly on point.

The expected result is that spaces are replaced, but dashes and hyphens stays.

**Comment by rumbin** [comment]
The _awesome-slugify_ package seems to do the job quite simply.

**Comment by NaukhaizAhmad** [comment]
I second @rumbin comments about the link shared by @xrmx .
1- Spaces has to be replaced with dashes or underscores. 
2- Dropping the hyphens/dashes is not the intended behavior.
