### ISSUE TITLE
Unable to connect to postgresql

### ISSUE THREAD

**Issue by Germanaz0** [apache/incubator-superset#3804]
- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
I am using the docker instance from https://hub.docker.com/r/amancevice/superset/ 

`Version: 0.20.5`

### Expected results
Connect to postgresql dataset

### Actual results
Not possible

### Steps to reproduce

I have an RDS postgres instance, when I try to test the connection using the SqlAlchemy url like this

`postgresql+psycopg2://user:pass@host:5432/myTable`

I have the following error:

```
Connection failed!↵↵The error message returned was:↵'NoneType' object has no attribute 'get_password_masked_url_from_uri'
```

**Comment by xrmx** [comment]
Please post the relevant exception is your logs. Otherwise there's not much we can do.

**Comment by xrmx** [comment]
Also good chances it's a dup of #3799

**Comment by Germanaz0** [comment]
Yes think so, it could be a dupe, is the same error, weird that I did not find it before, was searching for this error on issue tracker

**Comment by xrmx** [comment]
The close this one and post whatever you have in your superset logs to the other.

**Comment by xrmx** [comment]
It depends on where you log them, by default are not written to a file. If you are starting it with system you have them in the journal for the unit.
