### ISSUE TITLE
What's the easiest way to keep track of all the changes in the newest release?

### ISSUE THREAD

**Issue by TryHarder01** [apache/incubator-superset#3806]
I know there's a changelog, but that's for 20.0

Is this something where the community could help manage or is there an easy way to do it via Github?

**Comment by mistercrunch** [comment]
I need to automate this as part of the release process. This will become more formal for Apache releases in the future. 

In the meantime you can diff the release git tags.

Ill upade the changelog when I have à minute.

**Comment by TryHarder01** [comment]
Thanks. don't mean to put more work on you.
