### ISSUE TITLE
Installing on non-internet connected host

### ISSUE THREAD

**Issue by ipflowss** [apache/incubator-superset#3807]
Hope you are well. I am getting docker errors when I migrate a docker that is saved or exported. Is there an easy migration path to a non-internet connected host?

Here is the error when importing an exported
`$ zcat superset.tar.gz | sudo docker import - superset FATA[0014] Error response from daemon: Driver devicemapper failed to create image rootfs 779e3c08e38a2fc93be9a6f7dcb2fe73c273a8bf5ce71dc574e1afc2a77ad298: Error running DeviceCreate (createSnapDevice) dm_task_run failed`

Here is the error I see when I am loading from a saved docker
`$ sudo docker load -i superset.tar FATA[0085] Error response from daemon: Driver devicemapper failed to create image rootfs 911f74f3e3709ee47bd4a2d6375509ddb961ad27e20f066a661dc2b4c8d3b573: Error running DeviceCreate (createSnapDevice) dm_task_run failed`

**Comment by xrmx** [comment]
The docker are provided by external contributors. Also looks like more a general docker issue so before reporting this better google a bit to understand where the issues is.
