### ISSUE TITLE
Error connecting to Oracle DB

### ISSUE THREAD

**Issue by UTTARANB** [apache/incubator-superset#3820]
Hi,

I am trying to create a connection to an Oracle DB using the following URI

oracle://USER1:PASSWORD1@HOST-SCAN:1521/SRVN.

Test Connection shows the following error
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n'NoneType' object has no attribute 'get_password_masked_url_from_uri'"}
```
2017-11-09 13:19:47,109:INFO:werkzeug:127.0.0.1 - - [09/Nov/2017 13:19:47] "POST /superset/testconn HTTP/1.1" 500 -
2017-11-09 13:20:04,154:ERROR:root:'NoneType' object has no attribute 'get_password_masked_url_from_uri'
Traceback (most recent call last):
  File "c:\Users\49426\venv\lib\site-packages\superset\views\core.py", line 1452, in testconn
    masked_url = database.get_password_masked_url_from_uri(uri)
AttributeError: 'NoneType' object has no attribute 'get_password_masked_url_from_uri'
2017-11-09 13:20:04,157:INFO:werkzeug:127.0.0.1 - - [09/Nov/2017 13:20:04] "POST /superset/testconn HTTP/1.1" 500 -
```
What could I be doing incorrectly? PLease Help.

**Comment by mistercrunch** [comment]
Could this be related to [unsupported] Windows?

**Comment by xrmx** [comment]
Nope, dup of #3799 which should be open and has a hint of a patch. Looks like the test connection code is broken.

**Comment by UTTARANB** [comment]
Thanks Mistercrunch and xrmx for your inputs. 

I am using Windows and this issue is only with the test connection. 

While trying to directly save the connection I got the following message

'twophase' is an invalid keyword argument for this function

which was resolved by installing pip install cx_Oracle==5.1.3

**Comment by xrmx** [comment]
This may have been fixed in master in b059506afad33611664aa62b3ef43175828e6764 where we are checking for database being null.

**Comment by xrmx** [comment]
Opened a PR fixing this here https://github.com/apache/incubator-superset/pull/3828

**Comment by ctenix** [comment]
Hi, I had the same problem when I was trying to connect to MySQL database in ubuntu 16.04 in amazon instance.
python3.5+Ubuntu 16.04.3+MySQL5.7

**Comment by jkokatjuhha** [comment]
Have the same problem when connecting to SQLite in Mac locally.sqlite:////Users/me/Documents/eventlogging.db

**Comment by xrmx** [comment]
Friendly reminder that me too comments are not useful especially if there's a link to an already merged PR that should fix the issue.
An useful thing would be instead to test that the `0.20` branch works fine for you so the next release would work out of the box.
