### ISSUE TITLE
Permissions to tables

### ISSUE THREAD

**Issue by sjq597** [apache/incubator-superset#3826]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
I want a restricting access to a table, not only on datasource. for example, when i add a mysql database, I want Role A can see parts of tables in the database,and Role B can see the different parts of tables.Does superset support this? I only found permission on datasource or slice.

**Comment by xrmx** [comment]
Aren't table datasources?

**Comment by sjq597** [comment]
Thanks a lot, according to your answer, I resolve the problem. Just in Datasource-->Tables, add table can create a view, awesome!
