### ISSUE TITLE
Bullet Chart erroring out

### ISSUE THREAD

**Issue by kmagida110** [apache/incubator-superset#3827]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X ] I have reproduced the issue with at least the latest released version of superset
- [ X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.5

### Expected results

Rendering of bullet chart 

### Actual results

Chart creation fails with error message: An error occurred while rendering the visualization: TypeError: t.data.map is not a function. This is failing on all bullet chart creations.

**Comment by cartershanklin** [comment]
I get the same error with bullet charts in 0.22.1

**Comment by SpyderRivera** [comment]
same for 0.24.0rc1

**Comment by grafke** [comment]
same for 0.24.0
