### ISSUE TITLE
Severe regression: Slices with calculated time(?) columns stopped working, due to quoting of the column expression

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#3844]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5, regression from 0.20.4

### Expected results
All slices can be loaded.

### Actual results
Slices that contain calculated columns (defined via the _Expression_ field of _Add Column_) fail to load.
I observed this issue for a time column (_Is temporal = [x]_) and by have not checked if other calculated/virtual columns are affected, too. I can do that, if it would be helpful for debugging.

### Steps to reproduce
I hope you don't mind the German column names. If they distury you, I can translate them…

The calculated column `auftrag_ende_projiziert` in my case is defined as
```
auftrag_ende + (date_trunc('year',current_date) - date_trunc('year', auftrag_ende))
```

In superset 0.20.4 the resulting query looks somewhat like this
```
SELECT to_char(auftrag_ende::date, 'IYYY') AS auftrag_ende_jahr,
       DATE_TRUNC('week', auftrag_ende + (date_trunc('year',current_date) - date_trunc('year', auftrag_ende))) AS __timestamp,
       sum(anzahl) AS sum__anzahl
FROM …
```

In superset 0.20.5 the expression of the calculated column now is quoted, which obviously causes the query to fail:
```
SELECT to_char(auftrag_ende::date, 'IYYY') AS auftrag_ende_jahr,
       DATE_TRUNC('week', "auftrag_ende + (date_trunc('year',current_date) - date_trunc('year', auftrag_ende))") AS __timestamp,
       sum(anzahl) AS sum__anzahl
FROM …
```

Unfortunately I don't know which PR introduced the quoting, as I don't know which PRs to take into account, as I suffer from the same ignorance as #3806…

**Comment by xrmx** [comment]
@rumbin All you need is git log and optionally git blame. Even the github ui will do as the changelog is not curated but generated from git commits.

**Comment by xrmx** [comment]
Assuming  you are using postgres this should be it
https://github.com/apache/incubator-superset/commit/814b70ffd87750c8416d0f541504d8a854e82ec1

**Comment by rumbin** [comment]
Thanks @xrmx for pointing me to this PR.
Bugfix #3736 definitely is the culprit of this issue.

I'm not sure how to handle this situation, as simply reverting #3736 would of course bring back #3208.
I guess, the cleanes approach would be to distinguish if the time column provided is an existing table column, or if there is an _Expression_ behind it.

Ideas would be welcome; @Ryanthegiantlion, what do you think about this?

**Comment by rumbin** [comment]
Providing a MWE:

Take an arbitrary table and add a calculated column with, e.g., the following _Expression_
```
now()::timestamp
```

Then try to create a time series line chart with time grain of, e.g. _week_.

**Comment by Ryanthegiantlion** [comment]
@rumbin It seems a problem that at query time we cannot tell if a column is indeed a database column or a database expression. Unfortunately I am not familiar with sql alchemy to know how to handle this offhand. There is a meta data prop on the baseclass: https://github.com/apache/incubator-superset/blob/500455fc72dc58f9c0bd32d2b3b4da9a915bfb8c/superset/db_engine_specs.py#L72, so perhaps that can be used.

I will have a go at creating a PR that can handle both cases this week. If a fix cannot be provided it probably makes sense to revert the change. There is a workaround for #3208 - just create a view with properties cased correctly. It is a tedious workaround though, especially if every timestamp in the DB is cased 'createdAt', so it would be nice to keep the fix . . .

**Comment by mistercrunch** [comment]
Let me know if you think I should revert + release quickly

**Comment by rumbin** [comment]
I'd welcome if you reverted #3736, as ot breaks existing slices.

Users who suffer from #3208 may — until a permanent solution has been found — may be advised to work around the issue by introducing a calculated column with lowercased name, that simply contains the originally capitalized column name in quotes as _Expression_.

**Comment by Ryanthegiantlion** [comment]
Good point @rumbin. That sounds like a better workaround then doing it through a view.
