### ISSUE TITLE
Adding Database times out

### ISSUE THREAD

**Issue by abd5ge** [apache/incubator-superset#3853]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

Is there a way to tunnel ssh into my database connection?

### Superset version
0.20.5

### Expected results
Database get's added as a source

### Actual results
On save the request times out and safari states "safari server unexpectedly dropped the connection"

**Comment by xrmx** [comment]
Looks at superset logs there should be hints on what's wrong.
