### ISSUE TITLE
Superset does not display foreign tables.

### ISSUE THREAD

**Issue by mike-schiller** [apache/incubator-superset#3854]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
PostgreSQL foreign tables should be available for selection in SQL Lab.

### Actual results
Foreign tables are not shown in SQL Lab.

### Steps to reproduce
Connect to a PostgreSQL database with foreign tables, choose the correct schema, note that the foreign tables are not present.

I have a branch that modifies the PostgresEngineSpec to resolve this issue.

**Comment by mistercrunch** [comment]
Merged related PR
