### ISSUE TITLE
Bug in version v-0.20.5 : Metric names having capital letter like "GMV" is not rendering and throwing error

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#3859]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
V-0.20.5
It is proving to be prod-blocker for us.

### Expected results
Slices should render and plot graphs

### Actual results
Following error is shown whenever we try to plot any graph (such as time series or pie chart) with metric name in capital letterl (such as "Take Rate", "GMV" etc.)
```
Traceback (most recent call last):
  File "/home/ubuntu/sherlock/lib/python3.5/site-packages/superset/viz.py", line 277, in get_payload
    data = self.get_data(df)
  File "/home/ubuntu/sherlock/lib/python3.5/site-packages/superset/viz.py", line 1036, in get_data
    df = self.process_data(df)
  File "/home/ubuntu/sherlock/lib/python3.5/site-packages/superset/viz.py", line 972, in process_data
    values=fd.get('metrics'))
  File "/home/ubuntu/sherlock/lib/python3.5/site-packages/pandas/core/reshape/pivot.py", line 112, in pivot_table
    raise KeyError(i)
KeyError: 'L2A'
```
### Steps to reproduce
Just change name of metric in capital letter.

**Comment by xrmx** [comment]
What database is this?

**Comment by dataneta** [comment]
Underlying database where data is stored is redshift.
And backend of SuperSet is Postgersql.

**Comment by dataneta** [comment]
@xrmx did I answer your question?
What could be issue here?

**Comment by vmoranvargas** [comment]
i have the same issue. The workaround Works correctly tho
db: Oracle 10g

**Comment by dataneta** [comment]
@vmoranvargas what workaround you have applied here?
