### ISSUE TITLE
set default "refreshFrequency" via JSON Metadata

### ISSUE THREAD

**Issue by steffenbrand** [apache/incubator-superset#3860]
Feature Request:
I'd like to see a feature that sets the default refresh interval for a dashboard, when it's being opened. I think the JSON Metadata would be a good way to configure this individually for each dashboard.

The name could be "initialRefreshFrequency" or just "refreshFrequency".
It's named like that in RefreshIntervalModal.jsx.

Value could be interval in seconds.

```
{
    "refreshFrequency": 60,
    "filter_immune_slices": [], 
    "timed_refresh_immune_slices": [], 
    "expanded_slices": {}, 
    "filter_immune_slice_fields": {}, 
    "default_filters": "{}"
}
```

**Comment by mistercrunch** [comment]
+1 would happily review this PR
