### ISSUE TITLE
UK GeoJson not ISO 3166-2 Compliant

### ISSUE THREAD

**Issue by alanmcruickshank** [apache/incubator-superset#3863]
### Superset version
0.20.5

### Issue
In the currently packaged uk.geojson file not all ISO 3166-2 Regions are represented. Currently for the Metropolitan areas of the UK, the uk.geojson file included with superset includes the county codes (e.g. `GB-WY`, `GB-TAW`, etc...) which aren't part of ISO 3166-2, they should instead have the metropolitan area codes (e.g. `GB-BRD`, `GB-LDS`, `GB-NET`, etc...), which are the next level of subdivision to be compliant.

This means on correctly formatted data, you get a map with blank bits in the Country Map Viz.

The affected areas correspond exactly to this picture from wikipedia: https://upload.wikimedia.org/wikipedia/commons/9/92/English_metropolitan_boroughs_2009.svg

To fix this we would need to update the current geojson file to have the right entities in it. Any idea where the current ones came from? There's an up to date version of most of the dataset available from data.gov.uk [here](https://data.gov.uk/dataset/counties-and-unitary-authorities-december-2015-ultra-generalised-clipped-boundaries-in-england-2).

**Comment by xrmx** [comment]
@alanmcruickshank source is listed here https://superset.incubator.apache.org/visualization.html#you-need-to-add-a-new-country
