### ISSUE TITLE
Number Formatting for Pie Charts

### ISSUE THREAD

**Issue by valyabarboy** [apache/incubator-superset#3867]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.1

### Expected results
When I add number formatting to the JSON of any slice, I'd expect the numbers in that slice to format. 

### Actual results
This only works for those slices that have a number format drop down (ex. Big Number, Bar Chart). It doesn't seem to work for pie charts (for example). 

### Steps to reproduce
Make a pie chart slice. Add `"y_axis_format": ","` (or whatever format you prefer). The pie chart number formatting does not change. 

Am I doing something incorrectly? Is there a different way to format these? And if not, can we please add some way to control this? Thank you!

**Comment by xrmx** [comment]
Looks like a dup of #2128

**Comment by valyabarboy** [comment]
Yep, you're right. Sorry, I didn't find it. I'll follow that instead. Thank you!
