### ISSUE TITLE
[DatePicker] onChange is triggered too quick

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#3868]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

![dgracknjej](https://user-images.githubusercontent.com/27990562/32812184-a5842ffa-c958-11e7-8e5f-963ebbf89dae.gif)

### Superset version
0.21dev

### Actual results
When user changes input in Date picker, onChange event is triggered right away. In dashboard, this will cause new query send out for each slice.

### Expected results
Can we trigger onChange only after user clicks "OK"?

@mistercrunch

**Comment by mistercrunch** [comment]
Yes we should wait for `Ok` to call onchange

**Comment by betodealmeida** [comment]
@mistercrunch, can you assign this to me? I have a working fix.

**Comment by mistercrunch** [comment]
It appears it's not possible to assign to people who don't have write access.
