### ISSUE TITLE
Superset integration with NewRelic

### ISSUE THREAD

**Issue by riteshapatel** [apache/incubator-superset#3870]
Hi,

Trying to integrate Superset with NewRelic. As per NewRelic Python agent configuration, commands to start the app must be wrapped as below. Let's say if I am to integrate a python application with NewRelic it should be,

```shell
newrelic-admin run-program python -m main.py
```

Any ideas how it should be done for Superset? We have dockerized Superset. In the DockerFile we have setup ENTRYPOINT to be "superset" and CMD to be "runserver". Which turns on each container as below.

```shell
superset runserver 
superset worker
```

### Superset version
0.20.5

**Comment by mistercrunch** [comment]
From memory, something like `newrelic-admin run-program superset runserver`. Worked well at Airbnb.

**Comment by riteshapatel** [comment]
@mistercrunch thanks for a quick turnaround. I will give it a try. I will have to tweak the Dockerfile at my end to send just one command rather than prefixing commands with ENTRYPOINT.
