### ISSUE TITLE
Is there a Drill through alternative now?

### ISSUE THREAD

**Issue by XavierDeLapeyre** [apache/incubator-superset#3871]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

I know that there are no drill through feature right now.
I want to know if there are any alternatives out there to display additional info on/for a slice?

I saw several issues created that asked for the feature dating back in 2016

**Comment by xrmx** [comment]
Please use the mailing list or gitter for open ended questions. Also why opening a new issue if you already commented less than 20 minutes ago on #347?

**Comment by XavierDeLapeyre** [comment]
New to github and everything around it ( yes there are people new to github ) so did not know about that.
Where is the mailing list?
I got the gitter thnks
