### ISSUE TITLE
word cloud series limit is in invalid

### ISSUE THREAD

**Issue by dqzgzjhzjbhzl** [apache/incubator-superset#3882]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
the drop-down box named series limit  is working

### Actual results
the drop-down box seems like doing nothing

### Steps to reproduce
just select different value in the drop-down box

**Comment by amoussoubaruch** [comment]
@dqzgzjhzjbhzl  what did you mean by drop-down box? Which dataviz type did you want to use?

**Comment by dqzgzjhzjbhzl** [comment]
@amoussoubaruch i want to use Word Cloud.  
![word cloud](https://github.com/dqzgzjhzjbhzl/test/blob/master/word%20cloud.png)

**Comment by amoussoubaruch** [comment]
@dqzgzjhzjbhzl  Change your metric and test

**Comment by dqzgzjhzjbhzl** [comment]
@amoussoubaruch  in the red box , i select 5, then  the number of name in the Word Cloud  should be 5.   is it right?

**Comment by amoussoubaruch** [comment]
I thinks that series limit parameter is like select topN. So i select only 5 row in your dataset

**Comment by dqzgzjhzjbhzl** [comment]
@mistercrunch so this is a bug

**Comment by mistercrunch** [comment]
a squashed bug
