### ISSUE TITLE
Please add one column in the “add Slices to Dashboard” Pop-up window

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3884]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
![1](https://user-images.githubusercontent.com/16470564/32886677-660c4dee-cafc-11e7-9282-4304289539ac.png)

### Steps to reproduce
![1](https://user-images.githubusercontent.com/16470564/32886176-d3c44000-cafa-11e7-9519-ca9923c534ad.png)

![1](https://user-images.githubusercontent.com/16470564/32886250-12f48938-cafb-11e7-9337-41510a4344d9.png)

![1](https://user-images.githubusercontent.com/16470564/32886551-030979a6-cafc-11e7-9320-c8ba8fc83a6d.png)

**Comment by alanmcruickshank** [comment]
@luciuschina  - I can have a crack at this one.

**Comment by luciuschina** [comment]
Thank you very much!
