### ISSUE TITLE
How to use a count metric in Superset?

### ISSUE THREAD

**Issue by masterlittle** [apache/incubator-superset#3898]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I am using Superset and have a column with only two unique values. I want to create a bar chart with the counts of those two values. But I cannot see a count metric, only a count distinct which does not serve the purpose. Is there a workaround or am I  missing something?

### Superset version
0.20.6

**Comment by vnnw** [comment]
I think you have to add the metric you want by manually writing a valid sql expression.

**Comment by masterlittle** [comment]
Yeah figured that out. But do I have do that for every table. Is there some way to add a metric as a global metric, available for each table?

**Comment by xrmx** [comment]
Nope, you do it manually or you script it.
