### ISSUE TITLE
Pivot table can not sort by names of metrics in custom order

### ISSUE THREAD

**Issue by luciuschina** [apache/incubator-superset#3905]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

![1](https://user-images.githubusercontent.com/16470564/32998273-a678a97e-cdd4-11e7-8aef-8cc616122b50.png)

**Comment by rumbin** [comment]
I suppose they are sorted alphabetically. However, the behavior is counterintuitive in my eyes.

**Comment by luciuschina** [comment]
Yes,the 'Pivot Table' are sorted alphabetically. But the 'Table View' can sorted in custom order. In our business，some fields are more important,so I want put these fields in front  or some fields are more closely related，so I put these together。Table View can do that ， but Pivot Table can not 。So I always use  'Table View' as much as possible instead of 'Pivot Table'。So who can help add this feature，very appreciated！

**Comment by anthonymhho** [comment]
You can consider renaming the metrics when editing the table. For example, we'll use:
a. Revenue, b. Costs, c. Profit, for example to force each metric to appear in a certain order.

**Comment by luciuschina** [comment]
I had try this way. However, it is not perfect。 If I rename the metrics from 1.X to 5.X 。It seemed OK in the pivot table。But when I want to reuse  some of these metrics in other slices, it  looks like odd, for example:
![1](https://user-images.githubusercontent.com/16470564/33070067-b66bd144-cef1-11e7-9c06-fc50fbfcd153.png)
Obviously，in the above picture the 1. and 3. is unnecessary in the first diagram。
One of my e-pal also mentioned this problem。Superset is one of the best free software I had use，and I hope it will be better and better。_(with the help of google translation， cost 30 min to write these )_

**Comment by gregroberts** [comment]
+1 Here. producing a pivot table showing for example Leads, Bookings, Conversion, it seems absurd I should have to rename my metrics 1. Leads, 2. Bookings 3. Conversion just to make this work. What if I wanted to make another report from the same data showing Bookings, Repeat Bookings & New Bookings? I'd have to define new metrics for the new order!

**Comment by mistercrunch** [comment]
Side note: we need to re-write the table and pivot table visulizations to move away from the current "datatables" library and into a React lib, probably react-virtualized to support large result sets.
