### ISSUE TITLE
Where to change the export CSV SQL ?

### ISSUE THREAD

**Issue by XavierDeLapeyre** [apache/incubator-superset#3914]
Make sure these boxes are checked before submitting your issue - thank you!
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
Any idea where I can override the SQL used to generate the CSV to add additional fields or change the fields from the SELECT section ?

Ideally I would just want to change the 
SELECT x,y,z FROM mytable
Into 
SELECT * FROM mytable 
just for the CSV export

I already have a python code :
sql = "SELECT x, y, z FROM asd WHERE etc etc etc"
sql_arr = sql.split( 'FROM')
newsql = "SELECT * FROM "+sql_arr[1]

I just need to find where to change the SQL ( new to python and having difficulties with the superset architecture )

**Comment by vnnw** [comment]
https://github.com/apache/incubator-superset/blob/eb0f3970cfdef64ca932ddd72f817a82075b35a2/superset/views/core.py#L2192

**Comment by XavierDeLapeyre** [comment]
Hi vnmw,
Nopes it does not seem to be this location.
There is already a logging.info("Exporting CSV file [{}]... etc )
but its not being logged when I generated the CSV from a slice.

I tried the code anyway but no changes occured : 

def csv(self, client_id):
      """Download the query results as csv."""
      logging.info(blablablabla)
      **query_arr = Query.split('FROM')
      Query = "SELECT * FROM "+query_arr[1]**
      query = (
            db.session.query(Query)
            blablablabla

( The indentation is not appearing in the wysiwyg but its present in the file )

**Comment by XavierDeLapeyre** [comment]
Arf... Dunnot what I clicked but it closed by error.

incubator-superset/superset/views/core.py
 def csv(self, client_id):

does not seem to be called when I click on export CSV

Its this button : 
![image](https://user-images.githubusercontent.com/8424411/33062977-6e3eb972-ceba-11e7-8343-745a90c7cafa.png)

**Comment by alanmcruickshank** [comment]
@XavierDeLapeyre 

What are you trying to achieve?

The code you included:
```
sql = "SELECT x, y, z FROM asd WHERE etc etc etc"
sql_arr = sql.split( 'FROM')
newsql = "SELECT * FROM "+sql_arr[1]
```

...would be unstable for queries will multiple sub-selects, and so wouldn't be suitable for the standard export button.

If you just want a one-off export then I'd recommend using the SQL Lab functionality

**Comment by XavierDeLapeyre** [comment]
@alanmcruickshank 
My need is to change the content of the CSV file generated for the slices when the user clicks on the "Export CSV" button. 

I need to find this location, I will do the necessary adjustments ( regarding sub-selects, group by, order by etc )

And the code provided is just an example. The sql queries generated in my case are pretty straight forward.


Ideally, I would want to create a new field within the edit slice view.
Add a text zone to enter my own sql CSV generate query 
and when I click on generate CSV, it just overrides whatever SQL is has and uses the CSV query inputed.

But the quickest action for me right now is just to override the sql for the demo graphs I have in hand.

**Comment by alanmcruickshank** [comment]
That specific button you're looking at calls this endpoint:
https://github.com/apache/incubator-superset/blob/eb0f3970cfdef64ca932ddd72f817a82075b35a2/superset/views/core.py#L997-L1000

it calls it with the `csv` parameter set to `True` so that it eventually calls:
https://github.com/apache/incubator-superset/blob/eb0f3970cfdef64ca932ddd72f817a82075b35a2/superset/views/core.py#L1015-L1020

If you ever need to find out things like this you can use the "Inspect" feature of most modern browsers by right clicking on something. That will then show you the HTML which represents that object and you'll see the link within it.

**Comment by XavierDeLapeyre** [comment]
@alanmcruickshank thanks!
