### ISSUE TITLE
Activating new user results with InvalidRequestError: SQL expression, column, or mapped entity expected - got 'None'  

### ISSUE THREAD

**Issue by mnrozhkov** [apache/incubator-superset#392]
System details:  MacOSX/10.11.4, SQLite, run under development mode
Go to Security/List users menu. 
Create user and try to activate him: 
![image](https://cloud.githubusercontent.com/assets/11489539/14743520/8eb6b3da-08aa-11e6-992d-ad41693d5f95.png)

Selecting checkbox "Is Active?" for new user results with _InvalidRequestError: SQL expression, column, or mapped entity expected - got 'None' _ 

The request "GET /caravel/checkbox/UserDBModelView/2/active/false HTTP/1.1"  results with status 500  (Full traceback is here: https://gist.github.com/mnrozhkov/35c702c892fcbeb9b2683d042dc6c48f  )

This url is exposed in view.caravel.checkbox method 
(code sample is here: https://gist.github.com/mnrozhkov/d2a597eed823b6e2df810b505206ebcf) 

The UserDBModelView is note recognized by view.caravel.checkbox method. This leads to model = 'None' . So, have you encountered this issue?  Any suggestions to solve this?

**Comment by mnrozhkov** [comment]
It seems I could solve this... 

**First**, create security module 'mysec.py' to store custom MyUser model, MyUserDBModelView and  MySecurityManager. For experimenting purpose I've add a column field named 'app_access'
See here: https://gist.github.com/mnrozhkov/3658bbea6b8f6cf93d5fafb0713c0aba 

**Second**, update view.caravel.checkbox method: 
Add two strings: 
```
        elif model_view == 'MyUserDBModelView':
            model = mysec.MyUser
```
See here: https://gist.github.com/mnrozhkov/781b7d78972e37f9b53d71747805d836 

**Third,** update config.py 
`from caravel.mysec import MySecurityManager  `
...
`CUSTOM_SECURITY_MANAGER = MySecurityManager`

**Last**, migrate DB using Alembic and that's it!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 727 days. Feel free to comment and request for this issue to be reopened.
