### ISSUE TITLE
Feel Puzzled at Structure 

### ISSUE THREAD

**Issue by HugoPu** [apache/incubator-superset#3930]
### Superset version
0.20.5 

### Python version
2.7.5

### Question
Actually, this is not a bug, but it make me confuced.
The connectors, models and views are placed on different packages, I think you want to load them separately. but when Superset is run, `ConnectorRegistry.register_sources(module_datasource_map)` in `Superset.__init__` will call `Superset.connectors.base.views`, then `Superset.connectors.base.views` will call `from superset.views.base import SupersetModelView`. All `Superset.views` will be loaded at that time, since `Superset.views.__init__` call 
```
from . import base  # noqa  
from . import core  # noqa  
from . import sql_lab  # noqa  
from . import annotations # noqa  
```
Acutally,`from superset import views` in `Superset.__init__` is no used.

Never mind if you think what I wrote is normal.

**Comment by xrmx** [comment]
I'm not sure i understood what is the issue.

**Comment by HugoPu** [comment]
I mean every view files are loaded when `ConnectorRegistry.register_sources(module_datasource_map)` is run, is it normal?

**Comment by mistercrunch** [comment]
I don't think that this is an issue. If my memory is right I think originally people at yahoo contributed the connector registry so that they could import connectors that are only relevant to them internally. You can imagine that they have some 3rd connector on their internal fork.
