### ISSUE TITLE
Can't login after upgrade

### ISSUE THREAD

**Issue by prettyGitty** [apache/incubator-superset#3931]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
v0.18.2

### Expected results
Upgrade to newest version (v0.20.1) via pip

### Actual results
Superset has been upgraded, but users (included admin) can't login anymore

### Steps to reproduce
- Superset is running with MySQL Database
- Superset is running via /etc/mod_wsgi-express-80
- My upgrade steps:
     pip install superset --upgrade
     superset db upgrade
     superset init

I also tried to create a new admin via fabmanager. No errors being caught while doing this, but I can't login with the new admin as well

**Comment by prettyGitty** [comment]
Yes you are right. It is v0.20.6

I checked the error.log in /etc/mod_wsgi-express-80/. Because of the unclean shutdown I stoped superset from running, deleted httpd.pid and restarted the service. Still I can't log in. No other hint here and in /var/log/

[Thu Nov 23 14:18:28.075532 2017] [core:warn] [pid 2457:tid 139831834888064] AH00098: pid file /etc/mod_wsgi-express-80/httpd.pid overwritten -- Unclean shutdown of previous Apache run?

[Thu Nov 23 14:18:28.076777 2017] [mpm_event:notice] [pid 2457:tid 139831834888064] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.5.15 Python/3.5 configured -- resuming normal operations

[Thu Nov 23 14:18:28.076817 2017] [core:notice] [pid 2457:tid 139831834888064] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /etc/mod_wsgi-express-80/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE'

[Thu Nov 23 14:18:32.580830 2017] [mpm_event:notice] [pid 2457:tid 139831834888064] AH00494: SIGHUP received.  Attempting to restart

[Thu Nov 23 14:18:35.637404 2017] [mpm_event:notice] [pid 2457:tid 139831834888064] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.5.15 Python/3.5 configured -- resuming normal operations

[Thu Nov 23 14:18:35.637466 2017] [core:notice] [pid 2457:tid 139831834888064] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /etc/mod_wsgi-express-80/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE'

[Thu Nov 23 14:36:49.797922 2017] [mpm_event:notice] [pid 2457:tid 139831834888064] AH00491: caught SIGTERM, shutting down

[Thu Nov 23 14:38:02.080797 2017] [mpm_event:notice] [pid 2593:tid 139888849241984] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.5.15 Python/3.5 configured -- resuming normal operations

[Thu Nov 23 14:38:02.080942 2017] [core:notice] [pid 2593:tid 139888849241984] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /etc/mod_wsgi-express-80/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE'

[Thu Nov 23 14:38:05.585103 2017] [mpm_event:notice] [pid 2593:tid 139888849241984] AH00494: SIGHUP received.  Attempting to restart

[Thu Nov 23 14:38:06.355675 2017] [mpm_event:notice] [pid 2593:tid 139888849241984] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.5.15 Python/3.5 configured -- resuming normal operations

[Thu Nov 23 14:38:06.355732 2017] [core:notice] [pid 2593:tid 139888849241984] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /etc/mod_wsgi-express-80/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE'

**Comment by xrmx** [comment]
You have to check the superset logs

**Comment by prettyGitty** [comment]
Ok I am sorry, but I need to ask that question, because I was searching for the log file all at the wrong places it seems
I checked:
/usr/local/lib/python3.5/dist-packages/superset/
/usr/lib/python3.5/
/var/www/.superset/
/var/lib/mysql/superset/

and of course
/etc/mod_wsgi-express-80/

**Comment by prettyGitty** [comment]
Ok I am turning in circles right now.
In superset config.py it says in line 235:
FILENAME = os.path.join(DATA_DIR, 'superset.log')

so I typed into the python3 bash:
>>> from superset.config import DATA_DIR
>>> DATA_DIR
'/root/.superset'

but when I list the content of my home root folder it shows no superset.log file
~/.superset# ls -a
.  ..  superset  superset_corrupted.db  superset.db

also none in ~/.superset/superset

**Comment by luciuschina** [comment]
I upgraded the supersest from 0.18.5 to 0.20.5 successfully. My superset is also running with MySQL Database, some tables has been changed,so I upgrade mysql database manually.

**Comment by prettyGitty** [comment]
@luciuschina 
so you were able to log in with every old user? Which tables did you need to upgrade?

**Comment by luciuschina** [comment]
Yes I can  log in with every old user. The new tables add some other fields, you can create a new database for the new superset version。 Compare with them，and copy the old data to the new database manually。

**Comment by prettyGitty** [comment]
@ luciuschina. Ok this sounds like a solution to make it work with my old accounts. Thank you for that

Regarding the log file still can't find it. Not even `find / -iname "superset.log"` is able to find the mention error log from superset config.py. Could it be that there is something wrong with it or am I just on the wrong track? I would desperately like to read the error log

**Comment by prettyGitty** [comment]
Can someone please tell me where to find the superset.log

**Comment by mistercrunch** [comment]
@prettyGitty your log location depend on your setup (how you daemonize the application).

You really shouldn't have to do anything special with the database other than running the database migrations when upgrading.

@luciuschina you really shouldn't have to create a new database and diff it. Just run `superset db upgrade`

**Comment by luciuschina** [comment]
OK,I will have a try next time, thank you!

**Comment by hajdbo** [comment]
@kristw please close: obsolete.

**Comment by kristw** [comment]
Thank you @hajdbo !
