### ISSUE TITLE
Set permissions at slices and dashboard level

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#3932]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

I would like to assist with developing a way to restrict access to dashboards and slices. First MVP I was thinking of creating a simple flag of private. This would only allow admins and the user who created it access to the dashboard. We could do that same with slices. Any additional thoughts would be welcomed.  Maybe we can get a list of conditions we need to think about?

**Comment by SpyderRivera** [comment]
https://superset.incubator.apache.org/security.html?highlight=permission

**Comment by yamyamyuo** [comment]
see #538
