### ISSUE TITLE
Run query in SQL Lab raise up error "Shape of passed values is (1, y), indices imply (x, y)"

### ISSUE THREAD

**Issue by AI-CN** [apache/incubator-superset#3934]
Make sure these boxes are checked before submitting your issue - thank you!

- [√ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6 on windows 10 x64

### Expected results
When run query in SQL Lab, the Results returns correct data.

### Actual results
Raise up error "Shape of passed values is (1, y), indices imply (x, y)"

### Steps to reproduce
1.Open "SQL Lab"
2.Create a new query like "SELECT * FROM Table_Name;"
3.Run Query

### Bug fixing process
This bug was caused by:
[Use list instead of numpy array. Hotfix. #2412](https://github.com/apache/incubator-superset/pull/2412/commits/15b2ad3d2d96641736914db2df2b98286f597086)

As refer to the pandas doc:
**pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)**
data : numpy ndarray (structured or homogeneous), dict, or DataFrame
Dict can contain Series, arrays, constants, or list-like objects

the data should not be a list.

When changed the code:
cdf = dataframe.SupersetDataFrame(
    pd.DataFrame(list(data), columns=column_names))

to:
import numpy as np
cdf = dataframe.SupersetDataFrame(
        pd.DataFrame(np.array(data), columns=column_names))

the bug was fixed.

**Comment by marcusianlevine** [comment]
Also experiencing this issue on Debian Stretch running Superset 0.22.1
