### ISSUE TITLE
Autologin on an existing user account?

### ISSUE THREAD

**Issue by XavierDeLapeyre** [apache/incubator-superset#3935]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
Hi all,
If I want to add a token to my URL to autologin to a specific user
superset/dashboard/3?standalone=true&token=123456789

Where in the codes should I add a check on the token to login and force a user login action?
something like :
if request.args.get('token') == '123456789':
login user xxx

How can I autologin ?
I see lots of g.user being called but I don't see where the actual login process is being made.
Where did the username/password/csrf_token get used to authenticate the user?

**Comment by mistercrunch** [comment]
It's provided by Flask Appbuilder.
http://flask-appbuilder.readthedocs.io/en/latest/security.html#supported-authentication-types

**Comment by XavierDeLapeyre** [comment]
Thanks,
I will have to go though one of the four types of authentication methods supported.

Closing this issue
