### ISSUE TITLE
Restricting the access to some metrics don't work

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-superset#3938]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.20.4

### Expected results
User don't have access to my metric can find and visualize it

### Actual results
Don't find this permission : "metric access on [cluster1].[datasource1].[my metric]"

### Steps to reproduce

- Edit the datasource (Menu -> Source -> Druid datasources -> edit the record "datasource1") and go to the tab List Druid Metric. Check the checkbox Is Restricted in the row of the metric revenue

- Edit the role (Menu -> Security -> List Roles -> edit the record “Admin”), in the permissions field, type-and-search the permission metric access on [cluster1].[datasource1].[revenue] (id: 1), then click the Save button on the bottom of the page.

**Comment by csc5k** [comment]
+1 I don't find the security point in 2 separate Superset instances I have set up
