### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by jjdblast** [apache/incubator-superset#394]
Find some bug, if i create "Time Series - Bar Chart" and use "Group by" - field containing Chinese utf-8 chars i get error "UnicodeDecodeError", but if create simple "pivot table", it's show's some  unreadable code.

Found a related issues [https://github.com/airbnb/caravel/issues/235](https://github.com/airbnb/caravel/issues/235) 

And my error report is here:

> UnicodeDecodeError
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 4: ordinal not in range(128)
> 
> Traceback (most recent call last)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
> response = self.make_response(self.handle_exception(e))
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
> Open an interactive python shell in this framereturn f(self, _args, *_kwargs)
> File "/usr/local/lib/python2.7/dist-packages/caravel/models.py", line 1164, in wrapper
> return f(_args, *_kwargs)
> File "/usr/local/lib/python2.7/dist-packages/caravel/views.py", line 504, in explore
> raise e
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 4: ordinal not in range(128)
> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

here's screenshot:

![Time Series - Bar Chart](https://cloud.githubusercontent.com/assets/3394810/14776432/3493b582-0af9-11e6-905b-3b933e47ea8f.png)

![Pivot Table](https://cloud.githubusercontent.com/assets/3394810/14776437/3cfa24a4-0af9-11e6-9a74-4c79882df38e.png)

**Comment by jjdblast** [comment]
I've tried the latest version of Caravel, which contains `from __future__ import unicode_literals` in viz.py and view.py, but still failed.

**Comment by mistercrunch** [comment]
It'd be nice if someone could provide a new example dataset with unicode in it that we could load as an example in `data/__init__.py` and write unit tests against.
