### ISSUE TITLE
Removing Count(*) from a Druid datasource selects a random metric by default

### ISSUE THREAD

**Issue by ghulands** [apache/incubator-superset#3944]
In our use of superset, we don’t want users using Count(*) as a metric as it only represents the number of rows in druid, not the number of rows before being aggregated on ingestion to druid. We define a metric row_count as 

{"type": "longSum", "name": "row_count", "fieldName": "count”}

Now that we have removed the Count(*) metric from the datasource, another metric is being automatically selected on the explore datasource (which in this case is  a quantile based one) which causes an exception to be thrown as it expects certain dimensions in the group by to be selected.

We would like a way to either set the default metric when browsing a datasource, or be able to manually order the metrics so the most popular ones are a the top of the list.

**Comment by kkalyan** [comment]
Same with Max and Min metrics for each dimension- they would not make sense if the data is aggregated.

**Comment by mistercrunch** [comment]
The `COUNT(*)` is not completely irrelevant and is a decent fallback default metric. I don't think we can assume that there will always be a `count` field to sum up either though.

I agree that users should be able to define a default metric other than `COUNT(*)`. That applies to both SQLAlchemy and Druid.
