### ISSUE TITLE
Import tables with column type MONEY default setting

### ISSUE THREAD

**Issue by sebastianwindeck** [apache/incubator-superset#3953]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

superset -0.20.6

### Expected results

When importing a new table from a database with column type MONEY
Column settings for SUM, MIN, MAX are set by default. 
Metrics settings similar sum__, min__, max__, avg__. 

### Actual results

Column setting SUM, MIN, MAX for columns with type MONEY are not set by default.
Metrics settings similar. 

### Steps to reproduce

Import a table with column type MONEY --> Go To Edit Table --> Go To List Columns
--> Column setting for MONEY columns are not set by default.

**Comment by xrmx** [comment]
which database is this?

**Comment by sebastianwindeck** [comment]
mssql
