### ISSUE TITLE
setup issue - default config uses postgresql vs sqlite

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#3954]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

Does anyone know how to resolve the following issue when is execute "fabmanager create-admin --app superset"

2017-11-29 08:11:58,879:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  role "root" does not exist

I am running this setup in a clean virtual environment. 

any help would be much appreciated.

**Comment by xrmx** [comment]
Your connection string to postgres is wrong, please close.

**Comment by rpwils** [comment]
ok, i was thinking in a python virtual environment superset would create a new db. guess not.

**Comment by rpwils** [comment]
I see the last check-in changed the config.py file so now postgres db setting is the active one. Do you really want this to be the case?

https://github.com/apache/incubator-superset/commit/268edcfedd0eae0dcb33bdd1e14795f602ab4532#diff-21213919e9d7699522fc8d0fcabdc63f

**Comment by rpwils** [comment]
thanks
