### ISSUE TITLE
Improve Save Slice dialog

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#3960]
<img width="651" alt="screen shot 2017-11-29 at 10 17 41 pm" src="https://user-images.githubusercontent.com/487433/33416785-320e43a6-d553-11e7-8ff3-83d5c6c003aa.png">

* make dashboard dropdown sticky (use cookie?)
* when overwriting a slice that is already associated to a dash, save & go should take you to the dash

**Comment by rumbin** [comment]
Some thoughts on your second item:

If a slice is already associated to more than one dashboard, what is the user's expectation?

* only take into account the dashboards that he owns?
* ask which one to forward to?
* take the most recently changed one?
* or the one which the user last accessed, and which maybe led him to editing this slice?

**Comment by mistercrunch** [comment]
I thought about this as I was writing the issue...

From my experience it's pretty rare that one slice is in two dashboards, but we should still handle it. I'd say prefer one that the user owns, otherwise pick one at random. Could also include the title in the button [Save & go to "My Dashboard"]
