### ISSUE TITLE
Sql lab queries not working

### ISSUE THREAD

**Issue by masterlittle** [apache/incubator-superset#3963]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I'm trying to run query in async mode using celery and redis. But I'm getting this error::
ERROR/Worker-1] Query with id `16` could not be retrieved

This is my celery config-
```
class CeleryConfig(object):
  BROKER_URL = 'redis://localhost:6379/1'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
  CELERYD_LOG_LEVEL = 'DEBUG'
  CELERYD_PREFETCH_MULTIPLIER = 1
  CELERY_ACKS_LATE = True
CELERY_CONFIG = CeleryConfig

SQL_CELERY_DB_FILE_PATH = os.path.join(DATA_DIR, 'celerydb.sqlite')
SQL_CELERY_RESULTS_DB_FILE_PATH = os.path.join(DATA_DIR, 'celery_results.sqlite')
```
redis --
```
from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')
```
### Superset version
0.20.6

### Expected results
The sql lab query should run in celery in async mode

### Actual results
Celery giving an error:
ERROR/Worker-1] Query with id `16` could not be retrieved

**Comment by mistercrunch** [comment]
Are you sure your worker is pointing to the same metadata database? My guess is that your `superset_config` is different or not in effect (not in your PYTHONPATH perhaps) on your worker.

For this to work the web server and worker need to share the same metadata db.

**Comment by masterlittle** [comment]
I'm using the same superset config. I'm using sqlite as the db. 
I tested the config. Its the custom config I'm using.

**Comment by masterlittle** [comment]
How do I check if I'm using the same metadata db?

**Comment by mistercrunch** [comment]
Well SQLLite won't work here as it's a poor man's database that's on the local file system. It has limited support for concurrency, you should use MySQL or Postgres.
