### ISSUE TITLE
Feature Request: Ability to specify SQL query in Filter 

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#3968]
I'd like to specify a SELECT query (typically from a database) in the Filter selection (typically on a Druid data source). 

Mock: 
![image](https://user-images.githubusercontent.com/391567/33462764-58a247a6-d5ee-11e7-8c1d-a6035f46e83a.png)

Here is the query I want to execute
```
select SUM(revenue) from impression_druid where line_id in 
    (select line_id from mysql_line where feature_x=1)
```
Execution would be 2 step process
* run MySQL query to get a list of values
* use these values as a filter in druid query and run it. 

I've not thought through enough about corner cases (like dashboard filtering and passing time to inner query), posting here to get some feedback.

**Comment by mistercrunch** [comment]
I like this idea! Though I think we probably want to support Druid SQL in general first. 

I spoke with folks from the Druid core team at a meetup Tuesday and they said that we should move Superset to use SQL against Druid in the near future. As we get Druid setup at Lyft we may write the SQLAlchemy and DBAPI driver required for that.
