### ISSUE TITLE
Docs: List of all supported databases seems to be missing

### ISSUE THREAD

**Issue by ehx-v1** [apache/incubator-superset#3992]
I've been searching through the whole docs page and can't seem to find anything like a complete list. A few tables on the page list a whole bunch of classical relational databases, and it mentions Druid is supported, however I've also seen issues related to connecting with Redis over here, which I know is a NoSQL database. The authors of those issues didn't get told Redis isn't supported, which I assume they would have been if that were the case. I also have the impression that the tables (mostly related to SQLAlchemy connections) don't list all supported relational databases either.

A complete list of all supported databases would be very helpful for people with any database for which you currently can't tell whether it's supported, for example, graph databases, as well as for explaining Superset in a bachelor thesis or a comparable report document.

**Comment by xrmx** [comment]
They are listed in the README and in https://superset.incubator.apache.org/installation.html#database-dependencies

**Comment by ehx-v1** [comment]
From these sources, it would follow that Superset supports relational databases and Druid, and nothing else. That kind of contradicts the fact that it seems to support Redis.

**Comment by xrmx** [comment]
Exactly, there's no such thing as redis support

**Comment by mistercrunch** [comment]
References to Redis in the docs would be around the use of Redis by Superset as a caching backend, results backend for SQL Lab or as the broker for Celery (which we use for SQL Lab in async mode (optional)).

**Comment by ehx-v1** [comment]
Alright, now I understand better. It had seemed that users were trying to connect with Redis using Superset without being told it's not supported, which was confusing. Thanks for explaining that!
