### ISSUE TITLE
MySQL connection when requiring ssl fails.

### ISSUE THREAD

**Issue by Hochen97** [apache/incubator-superset#3994]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
The latest version on docker.
0.20.5 on Debian/python3

### Expected results
I am trying to connect to a mysql database which requires the connector to require SSL but does not require an ssl ca. This should just work and has worked before, but I moved to a new host computer and did not remember the work around I had found before.

### Actual results
The installation guide shows a snippet for the "connect_args" which should do such, however whenever i enter anything in the connect_args section, all I get is this error:

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n'sslmode' is an invalid keyword argument for this function"}

### Steps to reproduce

SQLAlchemy URI: mysql://<user>:<password>@<installation>.sftp.wpengine.com:13306/<database>

Extra section:
{
    "metadata_params": {},
    "engine_params": {
        "connect_args":{
            "sslmode":"require"
        }
    }
}

**Comment by mistercrunch** [comment]
Looks like this isn't a Superset problem. Can you connect to your database using SQLAlchemy outside of Superset?

**Comment by pecuchet** [comment]
For superset version 0.28.1 it worked for me with:
```
"engine_params": {
  connect_args":{
    "ssl": "require"
  }
}
```

**Comment by muraiki** [comment]
I needed to use a custom CA, so I did the following:

1. `pip install mysqlconnector`
2. Use a SQLAlchemy URI that uses mysqlconnector (`mysql+mysqlconnector://...`)
3. In the Extra JSON block:
```json
{
    "metadata_params": {},
    "engine_params": {
        "connect_args": {
            "ssl_ca": "/path/to/ca.chain.cert"
        }
    },
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
```
