### ISSUE TITLE
Doctype missing

### ISSUE THREAD

**Issue by minuz** [apache/incubator-superset#3995]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

I'm embedding Superset into my application, which has a HTML 5 doctype. 
If I remove the doctype from my App, the explore configuration panel appears, when placing the doctype back, it doesn't render the panel anymore.
No exception is thrown on the browser console.

In addition, having the doctype removed from my app, it breaks styling in many places and create inconsistent behavior cross-browser. 

### Superset version
0.20.4 and 0.21.rc2

### Expected results
The explore panel to configure a slice should render normally. 

### Actual results
Explore configuration panel disappears

### Steps to reproduce
Add 
`<!DOCTYPE html>`
on basic.html

**Comment by xrmx** [comment]
I think you need to define what do you mean by "embedding superset".

**Comment by minuz** [comment]
Hi @xrmx, regardless the definition of "embedding superset", the issue occurs even using the standalone version. If you add the **doctype** on the `basic.html`, recompile and re-run, you should be able to reproduce the issue.
In regards to the requested clarification, we have an internal application written in Angular 5. We wanted to use some functionality from Superset so we build and bundle Superset and wrap some pieces into Angular components. It works fine, except in some places where things disappear due to the existence of the **doctype** on our `index.html`.
Is there a reason for not adding the **doctype** on the application?

**Comment by xrmx** [comment]
From the bug report i understood what adding a doctype breaks and not fix things. Steps to reproduce means how to reproduce the issue not how to fix it :) Feel free to open a PR adding the doctype.

**Comment by minuz** [comment]
@xrmx your first understanding was correct. I wasn't trying to tell how to fix... :p  Adding the doctype breaks. I was just informing that my initial statement was incorrect as it actually renders the html, but it's not being displayed for other reasons. Also I thought that giving some of the information of how far I dug into this might give you guys a good start :D 

Adding the doctype will break the explore panel, also will affect some popovers reported by some of my users.
