### ISSUE TITLE
Redshift Table import error

### ISSUE THREAD

**Issue by arpitkapoor** [apache/incubator-superset#400]
I am getting attached IOError when clicking on table name to create a Slice from Table using Redshift connection.

<img width="1270" alt="screen shot 2016-04-26 at 5 11 27 pm" src="https://cloud.githubusercontent.com/assets/9108308/14817047/0055d082-0bd2-11e6-9640-4d421b1ff814.png">

**Comment by mistercrunch** [comment]
Does that happen consistently?

**Comment by arpitkapoor** [comment]
I am getting this error every-time and unable to proceed with visualisation where my data is from Redshift.

**Comment by arpitkapoor** [comment]
Can anyone provide inputs on what can be the issue.Any pointers are appreciated.

**Comment by stephenrenault** [comment]
We are using presto to get redshift connection
