### ISSUE TITLE
Deleting metrics does not work 

### ISSUE THREAD

**Issue by michailsal** [apache/incubator-superset#4008]
Make sure these boxes are checked before submitting your issue - thank you!

- [v] I have checked the superset logs for python stacktraces and included it here as text if any
- [v] I have reproduced the issue with at least the latest released version of superset
- [v] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Expected results
A slice metric to be deleted

### Steps to reproduce
Add a metric to a slice (sum or avg of a column) and then delete it. Next click save button and go back to metrics view, the metric is still there

**Comment by Mogball** [comment]
@michailsal I'm able to reproduce this behaviour. Could you add more details to reproduce?

**Comment by michailsal** [comment]
I don't know what else to add here, when I delete a metric from a slice it shows as being deleted, but when I save the action afterwards by clicking save, the same metric comes back to the slice. It looks like the delete action is cached somewhere and not applied..

**Comment by likhitha04** [comment]
yes, i'm also facing the same issue.Any help how to fix this in superset dashboards?
