### ISSUE TITLE
Put 'Save' Button on 'List Table Column' Tab

### ISSUE THREAD

**Issue by Miserlou** [apache/incubator-superset#401]
It's annoying that the check boxes don't autosave, and that you have to scroll up and go to the other tab just to be able to save. Please make sure that the save button is visible on all edit table views!

**Comment by mistercrunch** [comment]
Yeah that's from FAB (flask appbuilder), the project needs a little bit of love. We may enhance the CRUD feature or eventually write our own forms...

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 726 days. Feel free to comment and request for this issue to be reopened.
