### ISSUE TITLE
[sql lab] Presto & Hive errors shows as big unreadable messages

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4013]
The code that handles error message formatting for Hive and Presto
https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py#L607 worked at Airbnb but don't work properly in at Lyft. We should handle this in a way that work in all environments.

related: https://github.com/apache/incubator-superset/issues/2349

**Comment by dmigo** [comment]
@mistercrunch 

> worked at Airbnb

Does the past tense mean that it is not known if it works now?
