### ISSUE TITLE
Make dashboard grid more granular

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4014]
Currently the dashboard view has 12 columns and a certain fix height matching this. We should at the very least double this, maybe go to 48.

There needs to be a database migration script that will multiply the current positioning.

**Comment by bernarde01** [comment]
Has this change been implemented? I'm running Superset in a test environment (version 0.35.2). My dashboard view has 12 columns, but I do not see a way of increasing this.
