### ISSUE TITLE
Enforce New Table Name Must Match Table Name in Selected Database

### ISSUE THREAD

**Issue by Miserlou** [apache/incubator-superset#402]
When adding a 'table', it isn't clear that the table name must match the database table. Because this isn't stated explicitly, I thought I was _naming_ a NEW "table" object inside of Caravel, not mapping to a table in my existing database.

Ideally, Caravel shouldn't even accept an answer that isn't in the selected database. Currently, if you do put in a name that isn't in the DB, it causes a massive cascade of errors - I'm quite certain that this UI problem is the source of this error, for instance, and likely others: https://github.com/airbnb/caravel/issues/321

PS, I wrote up my experience as a first time Caravel user here, if you're interested in more usability feedback: https://github.com/FOIA-data-hackathon/MuckRock-Caravel

Thanks for the awesome product! It was fun to play with, and I was able to uncover/visualize some interesting insights in our dataset because of Caravel.

**Comment by mistercrunch** [comment]
Nice, thanks for taking the time to make this writeup and reporting this issue. 

It's one of those that's just so obvious if you have written the tool but potentially unclear if your new to it.

**Comment by alanmcruickshank** [comment]
I think this is a great user experience improvement, especially given this flow is pretty early in people using the tool. It certainly stumped me the first few times I came through the setup process.

Simple validation on the table page would be sufficient. Helper text combined with then polling the DB to check that the name is valid when unfocussing from the field and then providing a helpful error message would be sufficient.

**Comment by Miserlou** [comment]
"Flow" is the right way I think about it. There isn't really an "onboarding" process for adding new data. If you look at my walkthrough, there are a lot of steps that say "ok, now go back to the [..]" which could happen automatically as redirects when the form is saved, etc. That can be improved upon even further - for instance, if there is only one table, automatically create that as the default, if there are fields with "date_" in the name, automatically mark those as date fields. Little stuff like that would go a really long way.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 726 days. Feel free to comment and request for this issue to be reopened.
