### ISSUE TITLE
How to restrict between two users of same role??

### ISSUE THREAD

**Issue by AnithaMurugesan** [apache/incubator-superset#4025]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Expected results
I want to use two users with same role.
But the database,tables,slice and dashboard created by one user should not be visible to other user and vice versa.

### Actual results
One user can see all datas (database,tables,slices and dashboards) created by another user.

This result is due to adding this permission:
all datasource access on all_datasource_access
all database access on all_database_access

### Steps to reproduce
Is this type of permission is possible in superset.
If yes, What are the permissions to be added for that role.
Thanks in advance.

**Comment by xrmx** [comment]
If you don't want a user to see evertyhing, avoid the all_*_access permissions. Am i misisng something?

**Comment by AnithaMurugesan** [comment]
Thanks..
But how can we make one user's datas(including database,tables,slices and dashboards ) invisible to other user??

**Comment by xrmx** [comment]
They should not be accessible to other users until you give other users permissions to do so. Have you read the permissions related documentation?

**Comment by xrmx** [comment]
They should not be accessible to other users until you give other users permissions to do so. Have you read the permissions related documentation?

**Comment by AnithaMurugesan** [comment]
Yes...I have seen that permissions like : datasource access on [XXX].(id:2) 
This permissions will be set by higher level user like admin to lower level user say, alpha.
But how to make datas hide between users of same role(like within alpha users).

**Comment by mistercrunch** [comment]
Just create 2 different roles. User 1 can have "gamma" + "set of tables 1" and user 2 can have "gamma" + "set of tables 2"

**Comment by AnithaMurugesan** [comment]
Thanks...
I will try this...

**Comment by AnithaMurugesan** [comment]
I can find 'menu access on sources' and 'menu access on tables' are enabled in 'alpha' role.
But why the sources tab is not available to the alpha user.
Do we want to enable some other permission to the alpha user to get access to sources ??

**Comment by mistercrunch** [comment]
Gamma should be able to see the datasources, if that's not the case it's a bug.

**Comment by nancykyo** [comment]
does anyone feel that the auth model of superset is too hard to use? 
can we stop using flask_appbuilder, and choose another RBAC framework?

**Comment by mistercrunch** [comment]
RBAC in FAB is fine, plus it's baked deeply in the web framework, can't change that. The missing element in the FAB model is "group".

**Comment by AnithaMurugesan** [comment]
Hi...
In Add Slice button in Slices Tab, I can find an option "Choose a datasource" 
In this option, I want to display only the datasources that the user has access to.
(Right now all datasources are visible there..But on clicking the datasource that the user has no access gives error message..Here the user has gamma role)..How can I hide the other datasources in this option..
Which permission is to be removed...I tried it..But can't find the solution...
Thanks in Advance...

**Comment by AnithaMurugesan** [comment]
Is there any roles documentation for superset?

**Comment by SahanaHandyal** [comment]
@AnithaMurugesan +1

Did you find a solution to this?
