### ISSUE TITLE
can't use mysql DATE_FORMAT function

### ISSUE THREAD

**Issue by dengshaochun** [apache/incubator-superset#4026]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
![image](https://user-images.githubusercontent.com/29160619/33707303-f09d9dca-db71-11e7-80d1-5f1942ba28d7.png)

### Actual results
![image](https://user-images.githubusercontent.com/29160619/33707334-018656cc-db72-11e7-8417-b79b9d621b0e.png)

### Steps to reproduce
```
select DATE_FORMAT(now(), '%h%i%s');
```

### other
It looks like confusion with python syntax

**Comment by tanjxyz** [comment]
double %, i usually do this

**Comment by dengshaochun** [comment]
@tanjxyz thanks,when i use double % , it's work.

**Comment by dengshaochun** [comment]
how to fix 
if i query like is
```sql
select indb_time, TotalFiles, BlocksTotal 
from hdfs_info_logs 
where statis_date>=20171101 
and DATE_FORMAT(indb_time, '%%H%%i%%S') = '000000';
```
and use Visualize , it will auto add double % in my query
![image](https://user-images.githubusercontent.com/29160619/33711736-fc127b04-db7f-11e7-97e2-81d781185dfa.png)

**Comment by mistercrunch** [comment]
I tried to fix this in the past and it was more tricky than expected. It has to do with the fact that different drivers behave differently in this case, and even the same driver can behave differently based on how it's called. We should iron this out in the future, in the meantime double your `%%`...
