### ISSUE TITLE
Newly added field in database table doesn't reflect automatically in SuperSet tables

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#4033]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
Newly added field in database table doesn't reflect automatically in SuperSet tables however it should automatically be available there.

### Actual results
Newly added field in database table doesn't reflect automatically in SuperSet. We have to add those fields manually in table.

### Steps to reproduce
Add new columns in database table and check if these column are available in existing superset tables.

**Comment by xrmx** [comment]
It's already documented in the FAQ https://superset.incubator.apache.org/faq.html#how-do-i-add-new-columns-to-an-existing-table
