### ISSUE TITLE
Feature Request: Gantt charts

### ISSUE THREAD

**Issue by xeijin** [apache/incubator-superset#4035]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Is there any way to do this currently with the existing visualisations, or any plans to implement this? (a search did not bring up anything).

Looks like there is an existing Gantt chart library for D3 if that is of any interest:

https://github.com/dk8996/Gantt-Chart

**Comment by mistercrunch** [comment]
Yes, it's one of the supported chart types

**Comment by redanium** [comment]
With help of cursor and some tweakings I got it working 
![Image](https://github.com/user-attachments/assets/686814e3-952f-48af-b6af-a72ebfd99bbe)

**Comment by mistercrunch** [comment]
Oh this looks nice!!!
