### ISSUE TITLE
`filter_immune_slices` in dashboard JSON metadata breaks on import

### ISSUE THREAD

**Issue by circld** [apache/incubator-superset#4036]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.5

### Expected results
Exporting a dashboard with filter_immune_slices defined should still have these filter immunity settings in working order upon import into a different superset instance.

### Actual results
The `slice_id`s in the JSON metadata do not appear to correspond to the `silce_id`s upon import (rather, they remain unchanged at the values from the original/exported dashboard).

### Steps to reproduce
1. Create a dashboard
2. edit JSON metadata to define dynamic filtering using [these instructions](https://github.com/apache/incubator-superset/blob/0.20/docs/faq.rst#how-to-add-dynamic-filters-to-a-dashboard).
3. Export dashboard
4. Import dashboard in another instance of superset
5. Apply filter on dashboard; filter immune slices will change

### Additional context
Ideally, exporting a dashboard should preserve its functionality such that deploying to a QA environment doesn't break anything. We have also looked into perhaps using the API to update the metadata field, but AFAIK this doesn't seem to be possible.

Any suggestions towards workarounds or other considerations would be warmly welcomed.

And thanks for building an awesome application!

**Comment by aman101097** [comment]
I m also facing same issue, please help
