### ISSUE TITLE
table view pagination 

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#4037]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Expected results
Has implemented pagination to the table view? To pull back 10k records takes about 50 seconds.  If not, would this be a big task based on the overall architecture?

**Comment by jaylindquist** [comment]
+1 We are pulling in a 4000 entry table which will only be growing in the future. The table takes 30 seconds to render in the browser which will cause an alert in Firefox.

**Comment by mistercrunch** [comment]
SQL Lab might do a better job at rendering larger datasets as we used a "virtualized" table component which only renders what is in the viewport. Maybe you can limit your results in the context of the dashboard, and link out to a superset query using the chart description feature.

**Comment by johnsks** [comment]
Hello all,

We are currently using 0.23.0dev, and have quite a few table views in our implementation. The lack of pagination is impacting the performance of the dashboards, which I am sure are all aware of.

I have funding to get the table view pagination changes done, and a resource available.  We will gladly contribute all the changes back to product.

However, it will be helpful if any of you who have looked into the issue can share your thought son the changes needed.  For example to table.js, viz.py etc.

Your insights into how we can go about making the changes is  much appreciated.

Thank you in advance.

John

**Comment by RobertLowe** [comment]
Neither superset nor metabase have simple pagination, what gives!
