### ISSUE TITLE
Installing on Ubuntu 16.04 LTS fails

### ISSUE THREAD

**Issue by xocasdashdash** [apache/incubator-superset#4038]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.21.0

### Expected results
Succesful installation

### Actual results
Fails

### Steps to reproduce

pip install superset

Hi!
I'm trying to install superset on an Ubuntu 16.04 sytem but it's giving me a lot of issues. For some reason the published package on pypi (https://pypi.python.org/pypi/superset) is missing the assets folder and that breaks the install on my system.

This PR https://github.com/apache/incubator-superset/pull/3510/files is the one that introduced the change. 

It might not even be that, but that there's something that's deleting the assets dir and keeping everything in static. 

If someone reads this downgrading to v0.20.6 is a workaround.

**Comment by kkalyan** [comment]
similar issues on Mac.

```
$ pip install superset --upgrade
Collecting superset
  Downloading superset-0.21.0.tar.gz (58.3MB)
    100% |████████████████████████████████| 58.3MB 25kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/23/qdb10g0s6977v_y15y214spw0000gp/T/pip-build-LJhyKg/superset/setup.py", line 10, in <module>
        with open(PACKAGE_FILE) as package_file:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/23/qdb10g0s6977v_y15y214spw0000gp/T/pip-build-LJhyKg/superset/superset/assets/package.json'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/23/qdb10g0s6977v_y15y214spw0000gp/T/pip-build-LJhyKg/superset/
```

**Comment by edengol** [comment]
Same with @kkalyan - could not install using `pip install superset` on osx after hours of fooling with python, pip, and setuptools. Got a successful install using `pip install superset==0.20.6` per @xocasdashdash's suggestion (thanks!)

**Comment by mistercrunch** [comment]
Blame https://github.com/apache/incubator-superset/pull/3739

**Comment by mistercrunch** [comment]
Blame https://github.com/apache/incubator-superset/pull/3510

**Comment by mistercrunch** [comment]
0.21.1 is baking now, should be up in a moment.

**Comment by kkalyan** [comment]
Thanks, @mistercrunch, install went through.
Filed a issue for dashboard filtering -  https://github.com/apache/incubator-superset/issues/4039

**Comment by xocasdashdash** [comment]
Just tested 0.21.1 and it works so we can close it!
