### ISSUE TITLE
slow performance with initial dashboard load

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#4051]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X ] I have reproduced the issue with at least the latest released version of superset
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.21.1

This is a question - after clearing the browser cache , the first load of any dashboard seems really long, takes a good 45 seconds.  We noticed this after going from 0.20.x  to 0.21.x.  I anyone else noticing this?

**Comment by tianhanfangyan** [comment]
I recommand you use the newest version.

**Comment by graceguo-supercat** [comment]
I'd like to investigate performance issue, but i need more details. Do you have video/gif with some sample data?

**Comment by mistercrunch** [comment]
First load after clearing browser cache suggest low bandwidth to download the JS bundles. I get that while on the train.

Now did the JS bundle sizes increase significantly between 0.20 and 0.21, I doubt it, though I don't have evidence either way. It could be good to track our bundle sizes overtime though if someone wanted to do the analysis.

**Comment by rpwils** [comment]
you were correct, we had bloated the js files in our build. Thank you for the input.

**Comment by AnsHPaTeL2927** [comment]
I faced same problem. I'm using the version 5 of Superset. When I load the dashboard for first time It took 1 minute to load entirely.
