### ISSUE TITLE
I dont't want to use ORDER BY,Your default sql always with it .

### ISSUE THREAD

**Issue by tianhanfangyan** [apache/incubator-superset#4052]
Make sure these boxes are checked before submitting your issue - thank you!

- [1 ] I have checked the superset logs for python stacktraces and included it here as text if any
- [1] I have reproduced the issue with at least the latest released version of superset
- [1 ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results

SELECT name AS name,
       SUM(birth_names.num) AS sum__num
FROM birth_names
WHERE ds >= '1917-12-13 00:00:00.000000'
  AND ds <= '2017-12-13 11:48:59.000000'
  AND gender IN ('boy')
GROUP BY name
LIMIT 50
OFFSET 0

### Actual results

SELECT name AS name,
       SUM(birth_names.num) AS sum__num
FROM birth_names
WHERE ds >= '1917-12-13 00:00:00.000000'
  AND ds <= '2017-12-13 11:48:59.000000'
  AND gender IN ('boy')
GROUP BY name
ORDER BY sum__num DESC
LIMIT 50
OFFSET 0

**Comment by tianhanfangyan** [comment]
Is there anybody can solve this problem.

**Comment by Towhid1** [comment]
I try to visualize bad performing products using the bar chart. But it is not possible because of this default "ORDER BY sum__num DESC". 

Is there any hack to do "ORDER BY sum__num ASC"?
