### ISSUE TITLE
[VIS] Big Number with Trendline: I can choose aggregation type separately for trendline and big number

### ISSUE THREAD

**Issue by pongacm** [apache/incubator-superset#4053]
Make sure these boxes are checked before submitting your issue - thank you!

- [ +] I have checked the superset logs for python stacktraces and included it here as text if any
- [ +] I have reproduced the issue with at least the latest released version of superset
- [ +] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
I have possibility to choose granularity for trendline and separately for big number or I can change aggregation type for big number. For example: I can present trendline in week granularity and show sum for all chosen period on big number at the same time.
<img width="602" alt="superset - big number with trendline" src="https://user-images.githubusercontent.com/9414453/33934470-416b1828-dff9-11e7-96e2-c31b2a8004fc.png">

### Actual results
Big Number with Trendline shows the last data point value in the time series
https://github.com/apache/incubator-superset/issues/2807

**Comment by MakremHammali** [comment]
is there any solution for that ?
