### ISSUE TITLE
Feature Request : currently we can't summarize pivot table/ table as % value of row total/ column total/ grand total

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#4054]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

Can we add a feature in visualization type "treemap", "pivot table","table" and "partition" which enable us to summarize data by  % total of row total or column total or grand total

**Comment by Mogball** [comment]
How does this compare to the existing `Percent Metrics` feature in the table vis?

**Comment by dataneta** [comment]
Is "percent metric" option is available in "pivot table" also?

**Comment by dataneta** [comment]
Is "percent metric" option is available in "pivot table" also?

**Comment by Mogball** [comment]
Not currently

**Comment by circld** [comment]
This would be a useful feature to greatly extend the expressiveness of the pivot table chart, i.e., to represent "wide" vs "long" data.

To illustrate, suppose have data for school students with a letter grade for each subject. Further suppose that we would like to calculate the count by subject and grade. In this case, we can use either visualization type:

### Table View
|subject|grade|count|
|-|-|-|
|English|A|50|
|English|B|85|
|English|C|39|
|English|D|12|
|English|F|0|
|Math|A|44|
|...|...|...|

### Pivot Table
|subject|A|B|C|D|F|all|
|-|-|-|-|-|-|-|
|English|50|85|39|12|0|186|
|Math|44|...|...|...|...|...|
|...|...|...|...|...|...|...|...|

If we now would like to see the percentage by subject for each grade, we are out of luck. `Table View` exposes "Percentage Metrics", but the percentages use the number of students across all subjects and letter grades as the denominator.

If, on the other hand, "Percentage Metrics" were implemented for `Pivot Table` and this added a percentage for each column calculated over the row total, we would be able to express the ask.

In any case, this would be a useful feature (although I'm sure there are design/implementation details to nail down), and hopefully the example above illustrates how such a feature would extend Superset's expressiveness in tabular "visualizations" even further.

**Comment by hannanshaikh** [comment]
Is anyone working on this,is there a way to implement "Percentage Metrics" .i am new to superset so i need help.

**Comment by 94ksunny** [comment]
Is anyone working on this?

**Comment by sahildoshi013** [comment]
Anyone found way to do this?

**Comment by sahildoshi013** [comment]
@villebro Thanks, I am able to calculate percentages. but is there any way I can plot sum and percentage both at same time. just like normal table?

**Comment by villebro** [comment]
@sahildoshi013 unfortunately it's not yet possible to apply this logic per metric. However, in the meantime, you can create a secondary metric where you apply a window function where you divide your aggregate expression with the total for that row (feel free to customize the window function to your use case):
1. First metric: `COUNT(*)`
2. Second metric: `1.0 * COUNT(*) / SUM(COUNT(*)) OVER ()`

<img width="644" alt="image" src="https://user-images.githubusercontent.com/33317356/156127975-a54f1efe-a573-44eb-ba66-b3f8b716e7ed.png">

**Comment by robjuffermans** [comment]
perfect! For the percentage column - for example profit - I used the expression below for percentages:

100 * sum(profit) / sum(sum(profit)) OVER ()

**Comment by moksh-enf** [comment]
As the values in the cells grow larger and larger, having a percentage metric with the count would be very helpful for analysis.
