### ISSUE TITLE
Feature Request :- Folder structure for dashboard and slice

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#4055]
Make sure these boxes are checked before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

Can we have a feature in SuperSet where we can organize slices or dashboard in folder structure?
Even to start with, having a folder based on user-logged in and saving his/her work in that folder would solve very big problem.

**Comment by mistercrunch** [comment]
I think we'll go with Tags instead of folders.

**Comment by dataneta** [comment]
Thanks, this would also suffice our use case.

**Comment by LeoDiep** [comment]
+1 is there any update on this cause we are needing it so desperately

**Comment by olivierRse** [comment]
+1 any update ?

**Comment by LeoDiep** [comment]
While waiting, we designed a landing page on Wordpress with folder structure and attach links to Superset dashboards to it.
The problem is solved temporarily.
