### ISSUE TITLE
Can't select newly add database in role permission list

### ISSUE THREAD

**Issue by MonkeyOnTree** [apache/incubator-superset#4060]
I want to control the users access to an database say DB1 in SQLLAB, so I add an new role say A. But when I edit the A's permission, I just can't find the database access on DB1. I'm sure i have selected 'expose in sqllab' when I add the datasource DB1. I can see it in SQLLAB as administrator.

### Superset version
0.18.5

### Expected results
When add a new datasource, I can select 'database access on' it in the role's permisson list.

### Actual results
I can't see it

### Steps to reproduce
1/Add a new datasource and be sure 'expose in sqllab' is selected. 
2/Add a new role, and edit the permissions.
3/You cant see the newly added database

**Comment by xrmx** [comment]
Reproduce against latest release please
