### ISSUE TITLE
Time Grain in Version 0.22.1 and 0.20.4

### ISSUE THREAD

**Issue by baocaiwang** [apache/incubator-superset#4061]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
In Version 0.22.1 Time Grain Function less then in Version 0.20.4

### Expected results
in Version 0.20.4 , the Time Grain is Like this 
day,week,month,year,hour,week_start_monday,quarter....
I want to say,  this Time Grain is Perfect for me!!!!

But, in Version 0.22.1，the Time Grain is Like this
day,week,month
Why? 

### Actual results
we have develeped reports contain the Time Grain , If we update Version, the report will not be use.

**Comment by mistercrunch** [comment]
For which database backend is this? Grains are defined on a per-database engine basis

**Comment by baocaiwang** [comment]
@mistercrunch Oh, I Understand，I try it again, Thank you!
