### ISSUE TITLE
SQL Lab + Postgres  bug with quotes (psycopg2.ProgrammingError)

### ISSUE THREAD

**Issue by Oxystin** [apache/incubator-superset#4064]
[Make]sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Expected results

Workable visualization

### Actual results

1) Simple Query

```
SELECT "SCHEDULED_ARRIVAL",
       "COUNTRY"
FROM public.flights
WHERE "DAY_OF_WEEK"='4'
```

<img width="598" alt="screen shot 2017-12-15 at 05 09 57" src="https://user-images.githubusercontent.com/16529413/34023696-67327358-e157-11e7-8c0d-8c19314372a1.png">

2) Click "Visualize"and get the error "**psycopg2.ProgrammingError** column "scheduled_arrival" does not exist"

<img width="1067" alt="screen shot 2017-12-15 at 05 10 59" src="https://user-images.githubusercontent.com/16529413/34023888-5fd7d6e2-e158-11e7-9c72-007d3785c496.png">

SUM value without quotes is passed to the query:

<img width="825" alt="screen shot 2017-12-15 at 05 34 17" src="https://user-images.githubusercontent.com/16529413/34024126-a1ee38b8-e159-11e7-8f3a-fc6380d384a1.png">

Tell me how it can be quickly fixed? 
Thank you.

### Steps to reproduce

**Comment by rumbin** [comment]
When it comes to fixing this issue, I'd like to remind that - if quotes were to be generally introduced for column names -
 we'll risk the same kind of regression that once was observed for quoted temporal column names: #3844

**Comment by rumbin** [comment]
As a quick workaround, it may work if you simply specify the capitalized column name in the Expression field of the column's definition.

**Comment by Oxystin** [comment]
@rumbin Thanks for the answer. I'll try your recipe.
