### ISSUE TITLE
There are some break/conflict when importing/exporting dashboard between different superset instances

### ISSUE THREAD

**Issue by seniordev555** [apache/incubator-superset#4070]
We have 2 superset instances running on live production.
One is for our developers to design/implement the awesome dashboards and slices, and providing them to customers.
The other one is for customers to add, update and view their slices and dashboards.

What we are going to do is that once we develop new slice and dashboard, we want to export these resources from developer superset and import them to customer superset without conflict.

### Superset version
0.22.0

### Expected results
We want to import dashboards and slices without any break of existing resources in running superset.

### Actual results
With our research, while importing them, superset is checking the remote id.
For example, there is a export file from developer superset and the other export file from customer superset.
Unfortunately dashboards of these 2 export files have same remote id.
If we are going to import these 2 files to customer superset, it will totally be conflict.

We really want to know:
1. How can we import/export dashboards and slices from/to different superset without any break or conflict?
2. We are thinking that it is because of remote id (it is coming from original id of dashboard and slice). So what if we change all ids from id(integer) to uuid-type?
If it is possible, how can we implement(customize) it?

We'd like to hear good news from you soon.

**Comment by servomac** [comment]
Its related with the database primary key id, as you say. When importing, it overwrites the dashboard in the same id of the table dashboards on the destination superset. Migrating to uuids seems a good and simple solution.

**Comment by jcontesti** [comment]
The same has happened to me. When importing a dashboard, if the primary key dashboards.id value exists in the superset database, then the operation becomes an update. On the other hand, if the dashboards.id value doesn't exist, then it is converted into a normal insert with a new id value. 

By the way, the same happens with the slices.id. 

A possible workaround until the bug is solved is to change the ids directly in the database, selecting a value not used in the destination database.

**Comment by mistercrunch** [comment]
Agreed, should have been uuids from the get go...

**Comment by lorenzo-latta** [comment]
There is any progress of this issue?
We are dealing with dev and prod environment, and this became a blocking point for our company.
There is any documentation about the behaviour

**Comment by FedericoCalonge** [comment]
I am dealing with the same problem working in 2 env.
It's a bit confusing the import/export behaviour when I am looking to overwrite an existing dashboard with charts.
There is any update?
