### ISSUE TITLE
Bug: Date is coming as epoch format in pivot table not in regular date format ("YYYY-MM-DD")

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#4077]
Make sure these boxes are checked before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.21.1

### Expected results
Date should be in regular format which is readable by any user.

### Actual results
Data is coming in epoch format.

### Steps to reproduce
Create pivot table and put date in group by for any metric. Date is coming in epoch format which is not the desired format  as user can't understand it.

**Comment by dataneta** [comment]
Same issue in 0.22 versions also.

**Comment by dataneta** [comment]
Is there any update on it? 
As it is proving to be prod blocker for us and we are not able to upgrade our SuperSet.

**Comment by rumbin** [comment]
Follow-up: #4145

**Comment by saqibmujtaba** [comment]
do you guys has an update for this?
