### ISSUE TITLE
capital letter in varnames of a postgres table

### ISSUE THREAD

**Issue by ssoulier** [apache/incubator-superset#408]
If there is a capital letter in a table varname, the sql request failed without quote around the varname
<img width="612" alt="screen shot 2016-04-28 at 11 34 07" src="https://cloud.githubusercontent.com/assets/8398369/14881651/45f6cb64-0d35-11e6-9b05-3988003fa6a0.png">

**Comment by mistercrunch** [comment]
This must be specific to the WHERE clause and likely an easy-to-fix bug, I'll take a look when I have a chance.

**Comment by ssoulier** [comment]
I renamed my column 'created_at' and it works now.
I do not know if the bug is specific to my postgres databse or it's the same for all postgres database.
But the bug is not only specific to the WHERE clause. Everywhere you refer to this column it should raise an error if you do not put quote "createdAt".

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 721 days. Feel free to comment and request for this issue to be reopened.
