### ISSUE TITLE
How to use in applications

### ISSUE THREAD

**Issue by kartikgill96** [apache/incubator-superset#4092]
Hi ,
I was exploring superset and it's great. I have created some dashboards, but Now I want to use them in a web application .How Can I load these dashboards in application interface.
Thanks

**Comment by mistercrunch** [comment]
if you add a url parameter `&standalone=true` the menu bar won't show up at the top, so you can then `<iframe>` that.

There's been talks of shipping superset charts and dashboards as React components, it should happen in the first half of 2018.

**Comment by kartikgill96** [comment]
Thanks :)
