### ISSUE TITLE
Set SQLALCHEMY_DATABASE_URI='mysql://myapp@localhost/myapp', Could not get data via Queries(SQL)

### ISSUE THREAD

**Issue by robinwb129** [apache/incubator-superset#4099]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22

### Expected results
could get datas via queries[including join sql]

### Actual results
![image](https://user-images.githubusercontent.com/15103822/34202771-b6964112-e5b3-11e7-8660-4d5519845363.png)

![image](https://user-images.githubusercontent.com/15103822/34202757-afef2e1e-e5b3-11e7-8c0e-c1eed7f0abe0.png)
![image](https://user-images.githubusercontent.com/15103822/34202761-b25bf916-e5b3-11e7-8f23-af9302099745.png)

### Steps to reproduce

 vim /usr/local/python3/supersetvenv/lib/python3.5/site-packages/superset/config.py

SQLALCHEMY_DATABASE_URI = 'mysql://user:pwd@host/superset?charset=utf8'

**Comment by xrmx** [comment]
The errors looks more about not being able to connect to statsd than about connecting to your database. Also you are doing superset configuration wrong, please read the documentation.

**Comment by mistercrunch** [comment]
Do you have a statsd daemon running on that box?

**Comment by hajdbo** [comment]
@kristw please close: no answer from op, and this is unlikely to be a superset-related problem.
