### ISSUE TITLE
In dashboard edit mode, the slice delete buttons cannot be clicked.

### ISSUE THREAD

**Issue by vinay87** [apache/incubator-superset#4103]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Steps to reproduce

Open any dashboard, switch to edit mode. Try deleting a slice.

**Comment by xrmx** [comment]
Does it work after you have removed it from the dashboard?

**Comment by vinay87** [comment]
I think I wasn't clear. I meant I'm unable to click the "remove" slice button to try and remove a slice from the dashboard. What works is going to the slice properties and removing the dashboard from the assigned dashboards field.

**Comment by xrmx** [comment]
Thanks for the clarification :)
