### ISSUE TITLE
[P00 - sql lab] data results view truncates integers at 16 digits

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4107]
Integers greater than 16 digits get replaced with 0s

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
You really have to fill the missing information to help people helping you.

**Comment by fabianmenges** [comment]
My guess is you running into the max integer JavaScript issue. I pushed a fix here a couple weeks ago: #4005

**Comment by hughhhh** [comment]
@mistercrunch can we close?

**Comment by vylc** [comment]
@mistercrunch @hughhhh  with more and more ppl using SQL Lab, can we get this pushed?

**Comment by hughhhh** [comment]
Yea i'll rope it in

**Comment by mistercrunch** [comment]
Ok I merged https://github.com/apache/incubator-superset/pull/4005 . Thanks @fabianmenges for the fix.
