### ISSUE TITLE
/dist error

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#4110]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [ ]X I have checked the issue tracker for the same issue and I haven't found one similar

I wanted to see if anyone would be able to help me out with this issue i am having when i add a new view in Superset. I created a html doc and added the following code to core.py.  When i goto the page it displays fine but it produces an error trying to find dist/. And none of the menus that have drop downs work. Any ideas?

@expose('/version')
    def version(self):
        """Personalized welcome page"""
        if not g.user or not g.user.get_id():
            return redirect(appbuilder.get_url_for_login)

        return self.render_template(
            'superset/version.html', entry='version', utils=utils, user=g.user.first_name)

**Comment by xrmx** [comment]
Are you following the documentation for building from source? If so please looks at the browser console for errors. Then please quote the code correctly.
