### ISSUE TITLE
How to view all the registered workers

### ISSUE THREAD

**Issue by xocasdashdash** [apache/incubator-superset#4111]
Make sure these boxes are checked before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results

I'm trying to set up a pool of superset workers that would scale up or down depending on load using an auto scaling group from AWS. I've managed to get the worker running but I haven't been able to check that it's getting tasks assigned. I've setup flower on the "master" node and it shows only one worker, and I've set flower on the worker node and i don't see the master node either. 
Both nodes have connectivity with the redis node but I just want to be able to check how many workers are registered on superset. Is there a way to do this?

**Comment by xrmx** [comment]
Superset workers are gunicorn processes not celery ones. Also this looks like a celery question more than a superset one.

**Comment by xocasdashdash** [comment]
@xrmx mmm Well, i just have one configuration that is shared between the workers and the web node, the thing is I'm just not sure if the configuration i'm using is the correct one. 

Basically my question is regarding how would you configure superset to work with multiple servers all sharing the same broker and how can i see that this configuration is working as I expect it. 

The other issue i have is that if i start flower from the command line it binds to localhost by default and that is not reachable unless i proxy with nginx or something.

Here's the celery config that's shared between workers and web:

>  class CeleryConfig(object):
> BROKER_URL = 'redis://' + \
>         os.environ['SUPERSET_REDISHOST'] + ':6379/0'
>     CELERY_IMPORTS = ('superset.sql_lab', )
>     CELERY_RESULT_BACKEND = 'redis://' + \
>         os.environ['SUPERSET_REDISHOST'] + ':6379/0'
>     CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}

**Comment by xocasdashdash** [comment]
Ok, I've managed to partially fixed my issue, the new node was not working correctly because of a unicode issue when tasks where serialized (at least it seemed like that). It does seem that the issue is in flower not showing all the workers that are registered on the broker. So I think this issue can be closed, but I do believe some more information should be available in the docs about scaling out superset!

**Comment by xrmx** [comment]
If you report the issue there's more chances of it being fixed 👍
