### ISSUE TITLE
[country map] Country Map updates from #3946 broke USA map 

### ISSUE THREAD

**Issue by mjdepalma** [apache/incubator-superset#4112]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22 and latest build

### Expected results
USA map shows data

### Actual results
no data shown

### Steps to reproduce
1. git checkout 0.22 or latest on master, build and run
2. Upload attached .csv data
3. Generate country_map chart using user_region for query parameter, and sum_pageviews as metric
4. Observe no data shown on map
5. git revert 16ab696d7ceb7a66e34ff3088ebcb95681a87b70
6. build and run
7. Observe that map data is shown on map

[country_map_usa_sample_data.csv.gz](https://github.com/apache/incubator-superset/files/1583754/country_map_usa_sample_data.csv.gz)

**Comment by xrmx** [comment]
Maybe unrelated but US-VLI does not match https://en.wikipedia.org/wiki/ISO_3166-2:US

**Comment by xrmx** [comment]
Any warning / error  in the browser console log?

**Comment by mjdepalma** [comment]
No exceptions are seen in the browser console.   I also find that if I view the data in bar chart form (which works fine with the data), the same output is seen in the console as with the country map.
