### ISSUE TITLE
"No Data" message shown when run visualization query

### ISSUE THREAD

**Issue by romulomadu** [apache/incubator-superset#4113]
Hi,

I'm trying to run some visualizations with my data, but when I run a query it always exhibits the msg "No Data" and no visualization is shown.

The db is connected, I can make queries in SQL Lab with no problems.
I've tried to create the table by importing a .CSV file instead, but still no visualization is shown.

I've edited the columns permissions with no success too.

Could you help me?

**Comment by xrmx** [comment]
Please add all the missing information from the bug report template.

**Comment by romulomadu** [comment]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar


### Superset version
0.22.1

### Expected results
line charts

### Actual results
"No Data" msg

### Steps to reproduce

Visualization config:

{
cache_key: "c5aa133ca092660aadde8026a5cbaff1",
cache_timeout: 86400,
data: null,
error: "No data.",
form_data: {
datasource: "9__table",
viz_type: "table",
granularity_sqla: "Horario",
time_grain_sqla: null,
since: "7 days ago",
until: "now",
groupby: [
"Ativo"
],
metrics: [
"sum__Volume"
],
include_time: false,
timeseries_limit_metric: null,
order_desc: true,
all_columns: [ ],
order_by_cols: [ ],
table_timestamp_format: "%Y-%m-%d %H:%M:%S",
row_limit: null,
page_length: 0,
include_search: false,
table_filter: false,
where: "",
having: "",
filters: [ ]
},
query: "SELECT "Ativo" AS "Ativo", SUM(ofertas."Volume") AS "sum__Volume" FROM ofertas WHERE "Horario" >= '2017-12-17 00:00:00.000000' AND "Horario" <= '2017-12-24 11:50:55.000000' GROUP BY "Ativo" ORDER BY "sum__Volume" DESC LIMIT 50000 OFFSET 0",
status: "failed",
stacktrace: null,
annotations: [ ],
cached_dttm: "2017-12-24T13:50:55",
is_cached: false
}

**Comment by xrmx** [comment]
Does your query returns something?

**Comment by romulomadu** [comment]
Hi, I resolved the problem, my date column was not setted as datetime type correctly, and all visualization querys use some range of time...so, this issue can be closed.
