### ISSUE TITLE
Dashboard rendering error on Dual Axis line chart

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#4115]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "f905726c24b1d1f65a55b38592cb51c0f45deb15", "version": "0.23.0dev"}

### Steps to reproduce
Create a dashboard with two dual axis line charts.
One of them renders fine, other slice and rest of the dashboard does not work. 

### Actual results
![image](https://user-images.githubusercontent.com/391567/34343720-a1ef6354-e98e-11e7-8426-d3408004e024.png)

on Refresh (random slice has the error)
![image](https://user-images.githubusercontent.com/391567/34347151-d1200004-e9b4-11e7-88cd-9e89f1350283.png)

```
nvd3_vis.js:556 Uncaught TypeError: chart.xScale is not a function
    at Object.drawGraph [as generate] (nvd3_vis.js:556)
    at renderLoop (nv.d3.js:99)
```

@Mogball

**Comment by Mogball** [comment]
`nv.models.multiChart` which is used for the Dual Axis Line Chart does not expose `xScale` in the latest release `1.8.6`, although there is https://github.com/novus/nvd3/commit/2dd8024e8a782a06f9e4e7387e899619642adb2d.

**Comment by mistercrunch** [comment]
Merged related PR
