### ISSUE TITLE
/static/assets/dist/ 404 error

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#4120]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
http://superset:8088/static/assets/dist/ return 200 HTTP code

### Actual results
![image](https://user-images.githubusercontent.com/8108788/34349720-c233962a-ea4d-11e7-857d-0cb91750f3ad.png)

### Steps to reproduce
```bash
$ python setup.py install
$ fabmanager create-admin --app superset
$ superset db upgrade
$ superset load_examples
$ superset init

$ nohup superset runserver -a 0.0.0.0 -p 8088 2>&1 > /home/superset/logs/superset.log &
```
Then, visit [http://superset:8088/static/assets/dist/](http://superset:8088/static/assets/dist/) url.

**Comment by mistercrunch** [comment]
Why do you expect `http://superset:8088/static/assets/dist/` not to 404?

**Comment by asdf2014** [comment]
Hi, @mistercrunch . It's been a long time.

Because i visit the welcome page after i installed the latest version `Superset`, then i found some urls report `404` http code...

![image](https://user-images.githubusercontent.com/8108788/34351948-9c701370-ea5a-11e7-82aa-f81bdaffadb0.png)

**Comment by xrmx** [comment]
@asdf2014 Please follow the documentation https://superset.incubator.apache.org/installation.html#making-your-own-build

**Comment by asdf2014** [comment]
@xrmx Thx a lot.

**Comment by asdf2014** [comment]
Seems the `yarn` command dosen't work...

![image](https://user-images.githubusercontent.com/8108788/34356163-98226f18-ea76-11e7-9a0d-3a81669426a1.png)

**Comment by xrmx** [comment]
@asdf2014 If yarn does not work because it's not accessible / slow / whatever from your country we cannot do anything.

**Comment by asdf2014** [comment]
@xrmx Indeed. Anyway, thanks again.
