### ISSUE TITLE
Setting up Super set on google app engine

### ISSUE THREAD

**Issue by jeffrey-d-lipkowitz** [apache/incubator-superset#4129]
I was wondering if there was a way to setup super set on the google app engine.

**Comment by ankitchiplunkar** [comment]
I am interested in this task as well.

**Comment by feroult** [comment]
@jeffrey-d-lipkowitz I had the same wish... And I ended up creating a guide on how to deploy Superset to App Engine.

https://medium.com/@feroult/serverless-superset-on-google-cloud-87d3cf324845

**Comment by str028** [comment]
> @jeffrey-d-lipkowitz I had the same wish... And I ended up creating a guide on how to deploy Superset to App Engine.
> 
> https://medium.com/@feroult/serverless-superset-on-google-cloud-87d3cf324845

@feroult how did you manage the background worker ? i know the superset package has its backgroud worker for celery but in app engine there is no option to run this service separately. If i try to migrate celery to cloud tasks i dont have an idea how since cloud tasks works only for http request handler.

**Comment by brantian** [comment]
> > @jeffrey-d-lipkowitz I had the same wish... And I ended up creating a guide on how to deploy Superset to App Engine.
> > https://medium.com/@feroult/serverless-superset-on-google-cloud-87d3cf324845
> 
> @feroult how did you manage the background worker ? i know the superset package has its backgroud worker for celery but in app engine there is no option to run this service separately. If i try to migrate celery to cloud tasks i dont have an idea how since cloud tasks works only for http request handler.

@str028 did you manage to accomplish that? I'm running Superset on Cloud Run and I'm trying to figure out a way for deploying the background workers on a separate service
