### ISSUE TITLE
In Pivot Sort order - 1M is considered less than 100K

### ISSUE THREAD

**Issue by manoc** [apache/incubator-superset#4132]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
In Pivot when we sort ascending by any measure, it supposed to show 100K above and 1M below.

### Actual results
It considered 1.07M is less than 100K
![image](https://user-images.githubusercontent.com/3863780/34400440-6293c0c6-ebb7-11e7-922a-7bbf0314c8db.png)

### Steps to reproduce
Open Births dashboard -> navigate to last Pivot chart -> Sort all filed Ascendingly

**Comment by zancos** [comment]
Same here. When sorting, 1.02k is smaller that 2.00 if using .3s number format.
We are using version | "0.25.6"

![pivot_sorting_error](https://user-images.githubusercontent.com/7394266/41363692-da43a1bc-6f34-11e8-96b9-4e05ca7fe52d.png)

**Comment by tristix** [comment]
This is still an issue.

When sorting, 900 is > 1.2k apparently.

We migrated from v0.20 -> v0.26 this morning and it was noticeable straight away

**Comment by rumbin** [comment]
Please do not close this bug unless ist has been fixed

**Comment by mistercrunch** [comment]
It's been fixed:
<img width="122" alt="Screen Shot 2019-06-17 at 10 41 25 PM" src="https://user-images.githubusercontent.com/487433/59655999-10199000-9151-11e9-9f57-20161f0719f9.png">

**Comment by tristix** [comment]
Amazing thank you!
