### ISSUE TITLE
filter box can't support between and filter on the field

### ISSUE THREAD

**Issue by baocaiwang** [apache/incubator-superset#4137]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Version 0.20.4

### Expected results
 In our case, we want filter some value on a field，by the between and , I mean this way like the Time Filter, But this field is not a time field,  How can completed function in FilterBox in Slice?

**Comment by hushaoqing** [comment]
Any plan to support this? @mistercrunch
