### ISSUE TITLE
Tutorial for Superset Administrators: tutorial doesn't match the current interface

### ISSUE THREAD

**Issue by shakhova** [apache/incubator-superset#4138]
Hi Superset Team!

I follow Tutorial for Superset Administrators [here](https://superset.incubator.apache.org/tutorial.html) and was confused about adding a new database (same as adding new table).

On the page it is described as 

> On the resulting page, click on the green plus sign, near the top left:

But in current version of interface there is now button near "Actions". Now this button placed near the top right without any label. The button is not intuitive so it took some time to find adding action on page. Please, keep this helpful and detailed tutorial up to date.

**Comment by mistercrunch** [comment]
PRs welcomed

**Comment by zhaoyongjie** [comment]
please assignee to me, I can do it.

**Comment by graceguo-supercat** [comment]
@zhaoyongjie github don't allow me to assign issue to non-collaborators. You can commit a new PR and we can review it, and link your PR to this issue. Thank you!

**Comment by zhaoyongjie** [comment]
@graceguo-supercat this is a minor fix.
