### ISSUE TITLE
Change port of Superset 8088

### ISSUE THREAD

**Issue by mayanksrivastav84** [apache/incubator-superset#4140]
How can we change the default port of the superset ? 8088 is being used by another application.

**Comment by xrmx** [comment]
You can find it by reading the documentation or the help of superset command. Please close.

**Comment by zhaoyongjie** [comment]
you can get Superset start help from:
```
superset runserver --help
```
and start Superset use port 9000 
```
superset runserver -p 9000
```

**Comment by haokaibo** [comment]
how to set the customized port in the docker environment?

**Comment by dro248** [comment]
If you're running in docker compose using the `docker-compose-non-dev.yml` file, under the **superset**, change the ports section from `8088:8088` to `9000:8088` (assuming you want to use port 9000). Restart superset via docker-compose.
