### ISSUE TITLE
We recently open sourced a superset kylin Sqlalchemy Dialect.

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/incubator-superset#4141]
If you have any issues between Superset and Kylin let me know your feedback.

You can download this Sqlalchemy Dialect from Pypi
```
pip install kylinpy
```

You may read more from this repository: 
https://github.com/Kyligence/kylinpy

**Comment by mistercrunch** [comment]
Once someone confirms this works well we can add it to the list of supported data sources

**Comment by shaofengshi** [comment]
Hello Maxime, this is Shaofeng Shi, I'm one of Apache Kylin committer & PMC member. We noticed Superset since it was named as caravel, and some Kylin users have already adopted Kylin + Caravel for some time. I confirm this plugin works well. We will add a document to Kylin's website soon.

**Comment by mistercrunch** [comment]
Awesome @shaofengshi, would be nice if you or someone else can add Kylin to this list:
https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#database-dependencies

**Comment by shaofengshi** [comment]
Thanks Yongjie and Maxime!
