### ISSUE TITLE
react-datetime The Chinese calendar

### ISSUE THREAD

**Issue by zhizunbao514** [apache/incubator-superset#4144]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23

### Expected results
I want him to show Chinese calendar, but I set the locale="zh-ch", he did not achieve the effect.
incubator-superset-master/superset/static/assets/javascripts/explore/components/controls/DateFilterControl.jsx :105
### Steps to reproduce
<Datetime
locale="zh-ch"
 inputProps={{ className: 'form-control input-sm' }}
dateFormat="YYYY-MM-DD"
defaultValue={this.state.dttm}
onFocus={this.setType.bind(this, 'fix')}
onChange={this.setDatetime.bind(this)}
timeFormat="h:mm:ss"
/>

**Comment by xrmx** [comment]
Not sure that's the right place to report issues with react-datetime (have you read its i18n documentation?) but yes we may want to have it localized.

**Comment by zhizunbao514** [comment]
@xrmx I set the wrong?On the calendar, should how to set up correctly.

**Comment by zhizunbao514** [comment]
Where should set the localization of the calendar?
