### ISSUE TITLE
Feature Request:- Rearranging fields on "Group By" and/or on "Metrics"

### ISSUE THREAD

**Issue by dataneta** [apache/incubator-superset#4146]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
Rearranging fields on "group by" and "metrics" should be easy. Using drag and drop, we should be able to rearrange it.

### Actual results
I am not able to rearrange fields on fields chosen on "Group by" and "Metrics". To rearrange it, I have to delete all chosen fields and then arrange it in required order.

### Steps to reproduce
Rearrange the fields chosen on "group by" or "metrics"

**Comment by rumbin** [comment]
More or less a duplicate of #3141.

Would be really nice to have this feature back...

**Comment by mrkcohen** [comment]
Please reopen this

**Comment by tgibbons** [comment]
+1 to re-open this
