### ISSUE TITLE
specify blureprints can't import modules from superset

### ISSUE THREAD

**Issue by shuxiang** [apache/incubator-superset#4149]
### Steps to reproduce

according to https://superset.incubator.apache.org/installation.html#blueprints , i specify my blueprints
superset_config.py:
```
from simple_mod import simple_page
BLUEPRINTS = [simple_page]

simple_mod:
from flask import Blueprint
from superset.models.core import KeyValue


simple_page = Blueprint('simple_page', __name__,
                                template_folder='templates')
@simple_page.route('/', defaults={'page': 'index'})
@simple_page.route('/<page>')
def show(page):
    return 'ok'
```
the problem is when I try to import some modules from superset, blueprints load in superset/__init__.py but when import, superset/__init__.py will execute. 

What i want to do is customizing some functions, add new api. Is there any way to solve this problem?

**Comment by zhaoyongjie** [comment]
Please make sure your **superset_config.py** is working

**Comment by shuxiang** [comment]
superset_config.py is working
simple_mod.py:
`from flask import Blueprint

simple_page = Blueprint('simple_page', name,
template_folder='templates')
@simple_page.route('/', defaults={'page': 'index'})
@simple_page.route('/')
def show(page):
    return 'ok'

`
http visit shows 'ok'
but, when i try to import modules from superset, it doesn't work
new simple_mod.py:
`from flask import Blueprint
from superset.models.core import KeyValue

simple_page = Blueprint('simple_page', name,
template_folder='templates')
@simple_page.route('/', defaults={'page': 'index'})
@simple_page.route('/')
def show(page):
    return 'ok'

`

**Comment by zhaoyongjie** [comment]
Post more errors message.  and this script can run it?
```
import superset
print(superset.__path__)
```

**Comment by mistercrunch** [comment]
I'm guessing circular imports issues. If that's the case, a quick workaround can be to move `from superset.models.core import KeyValue` inside the view function where you need it.
