### ISSUE TITLE
Mapbox maps not rendering

### ISSUE THREAD

**Issue by tcollier1975** [apache/incubator-superset#4151]
Not sure if anyone else is having this problem.  

By the way I DO have a valid mapbox token

I've built the client using  
`yarn run prod` and `npm run prod` in separate attempts and the still the mapbox maps does **not**  render.

 I ran `npm update` to make sure the node packages were up to date.

Browser Console error
`Uncaught ReferenceError: t is not defined`

Any suggestions?  

Versions
Superset  **v0.22.1**
Node        **v9.3.0**
Yarn         **v1.3.2**
NPM         **v5.6.0**

**Comment by xrmx** [comment]
You have read the FAQ right?
https://superset.incubator.apache.org/faq.html#why-is-the-map-not-visible-in-the-mapbox-visualization

**Comment by tcollier1975** [comment]
Yes, i have a key.
the maps render fine in dev mode `yarn run dev`

**Comment by xrmx** [comment]
Any error in the browser console?

**Comment by tcollier1975** [comment]
browser console ` Uncaught ReferenceError: t is not defined`

**Comment by tcollier1975** [comment]
`yarn run build` versus `yarn run prod` seems to have done the trick.

**Comment by marslhx** [comment]
I meet this problem in another occasion.

I added my registered API token of Mapbox in superset_config.py.

And add path of it to .bash_profile, then _source ~  .bash_profile_, then _superset runserver_

However the map don't render yet.

What's the matter?
