### ISSUE TITLE
incubator-superset/docs/tutorial.rst image links are broken

### ISSUE THREAD

**Issue by mircsicz** [apache/incubator-superset#4152]
I'ld love to follow that tut, but on the current state it's quite a challenge.

Hope one of you find's the time to upload new or reupload the correspending screenshot's

### Expected results
the tutorial being fixed

**Comment by xrmx** [comment]
What's broken here? https://superset.incubator.apache.org/tutorial.html

**Comment by mircsicz** [comment]
Arggghhh, I tried to work with the *.rst file!

THX for pushing me in the right direction...

**Comment by xrmx** [comment]
FYI .rst are the sources in ReST format :)
