### ISSUE TITLE
Get error when connect to mssql

### ISSUE THREAD

**Issue by P0064546** [apache/incubator-superset#4158]
I tried to add database and set the url as below:
sqlmssql://username:password@server IP/servername
But I got below error:

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:sqlmssql"}

Anyone who know how to solve this issue?

Thanks in advance,
Mila

**Comment by xrmx** [comment]
Please read the documentation before opening issue:
https://superset.incubator.apache.org/installation.html#database-dependencies

**Comment by P0064546** [comment]
Does it mean that I didn't config the mssql or the url which I write is wrong？

**Comment by mistercrunch** [comment]
That means you haven't installed the required python driver for MSSQL

**Comment by P0064546** [comment]
Got you point , thank you so much!
