### ISSUE TITLE
Integrity error, probably unique constraint

### ISSUE THREAD

**Issue by jerowe** [apache/incubator-superset#4161]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

I have seen similar issues, but they are closed.

### Superset version
Superset 0.22.1

I have 2 mysql databases that have some of the same tables shared between them.

database1: table1
database2: table1 

I can add database1:table1 when I add database2:table1 I get an error that says 'Integrity error, probably unique constraint'

### Expected results

Add tables with the same name and structure from different databases.

**Comment by xrmx** [comment]
Dup of #3829, please close.

**Comment by jerowe** [comment]
Will do. Thanks!
