### ISSUE TITLE
Hope to modify SQL statements in the slice page

### ISSUE THREAD

**Issue by cyaolong** [apache/incubator-superset#4165]
### Superset version
0.22.1

### Expected results
Could modify the SQL statements in the slices page.
After I created a slice which is used in the dashboard, I wan to make some changes and I need to modify the SQL statements. But I counldn't find any way but the SQLLab to write a new SQL statement and visualize it. 
If I could do the stuff in the slice that would be much more convenient.

### Actual results
could not modify the SQL statments in the slices page.

**Comment by zhaoyongjie** [comment]
What do you want to modify in the slices page? every slice can edit some parameters in slice edit page.

**Comment by graceguo-supercat** [comment]
Click 'Edit datasource's configuration':

<img width="532" alt="screen shot 2018-01-10 at 8 53 42 pm" src="https://user-images.githubusercontent.com/27990562/34809197-5fca2f6a-f648-11e7-8939-65e070072641.png">

**Comment by cyaolong** [comment]
@graceguo-supercat Thanks a lot! 
It seems I have got into this page before but I have forgot where to get in.

**Comment by cyaolong** [comment]
This issue could be closed.
