### ISSUE TITLE
Is Python directly supported?

### ISSUE THREAD

**Issue by dclong** [apache/incubator-superset#4166]
Can I use Python pandas for data manipulation? And can I use Python visualization libraries?

**Comment by xrmx** [comment]
The aim of superset is being code free but being open source you can do whatever you want.

**Comment by dclong** [comment]
@xrmx Do you have any example of using Python code for data manipulation and visualization?

**Comment by mistercrunch** [comment]
Check out `viz.py` and look around for `df` (pandas dataframe) variables, they're everywhere. We tend to python for crunching (interacting with datastores, preparing the right JSON for the frontend) and Javascript for visualization.
