### ISSUE TITLE
npm run prod (or yarn run prod) hangs at 91% additional asset processing

### ISSUE THREAD

**Issue by am-kram** [apache/incubator-superset#4175]
### Superset version
0.23.0-dev

### Expected results
npm run prod should complete and produce a  minified bundle

### Actual results
it just hangs at 91% processing

### Steps to reproduce
npm -v 
5.5.1

npm run prod

> superset@0.23.0-dev prod ~/incubator-superset/superset/assets
> NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress

clean-webpack-plugin: ~/incubator-superset/superset/assets/dist has been removed.
 91% additional asset processing

**Comment by zhaoyongjie** [comment]
Did you try to delete the node_modules directory, and then npm run again?

**Comment by am-kram** [comment]
that worked - unsure why it kept hanging for a while there! 👍
