### ISSUE TITLE
New Map Not Showing in List

### ISSUE THREAD

**Issue by claycrosby** [apache/incubator-superset#4177]
I created a map of Mozambique in geojson format with the ISO codes per the instructions here: 
https://superset.incubator.apache.org/visualization.html#you-need-to-add-a-new-country 

I added the file mozambique.geojson to the path here: superset/assets/visualizations/countries

and updated the "select_country" component of this file to include "Mozambique" superset/assets/javascripts/explorev2/stores/controls.jsx

But I do not see Mozambique as an option when I view the list of maps.

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.20.4"}

### Expected results
I see Mozambique as a country to select with the Country Map visualization type

### Actual results
I do not see Mozambique as a country to select with the Country Map visualization type

**Comment by xrmx** [comment]
Have you rebuilt the javascript frontend (or using num run dev) ?

**Comment by claycrosby** [comment]
Disclaimer: I don't know much about technical things. We have not run num run dev, where do we run it?

Thanks for your reply and help
