### ISSUE TITLE
Apache Superset - Filtering in Subqueries

### ISSUE THREAD

**Issue by kartikshanbhag3333** [apache/incubator-superset#4181]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.22.1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

### Expected results

So, I have a table with following 
userWeight and have to define a metric called Reach(%). Now Reach for a service is defined as 

SUM(userWeights for the service)/SUM(All userWeights for Distinct Users)

The workaround I found out was 
SUM(DISTINCT userWeights)/(SELECT SUM(DISTINCT userWeights) FROM Table_Name)

Now this works great at the Overall Level, But I have a Filter Box for Age Group, Gender, and City. So, Ideally, I would want 

SUM(DISTINCT userWeights) / (SELECT SUM(DISTINCT userWeights) FROM Table_Name
WHERE [Conditions From Filter Box])

### Actual results

What is happening is 
SELECT service,SUM(DISTINCT userWeights) / (SELECT SUM(DISTINCT userWeights) FROM Table_name) WHERE gender = "Male" and age_group =  "24 - 30 yrs"

Which Produces Wrong results for the required Metric. I know I can do it Via SQL Lab from Jinja Templating. But I don't know how to do it

1. I am less aware of Jinja templating and particularly how do we do it for Superset.

2. I am getting following stacktrace while running a query

<html> <body> <h1>Sorry, something went wrong</h1> <h3>500 - Internal Server Error</h3> <hr> <h2>Stacktrace</h2> <hr> <code> <pre> Traceback (most recent call last): File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask/app.py&#34;, line 1982, in wsgi_app response = self.full_dispatch_request() File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask/app.py&#34;, line 1614, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask/app.py&#34;, line 1517, in handle_user_exception reraise(exc_type, exc_value, tb) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask/app.py&#34;, line 1612, in full_dispatch_request rv = self.dispatch_request() File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask/app.py&#34;, line 1598, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py&#34;, line 52, in wraps return f(self, *args, **kwargs) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/superset/models/core.py&#34;, line 870, in wrapper value = f(*args, **kwargs) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/superset/views/core.py&#34;, line 2145, in sql_json session.flush() File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2139, in flush self._flush(objects) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2259, in _flush transaction.rollback(_capture_exception=True) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py&#34;, line 66, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py&#34;, line 2223, in _flush flush_context.execute() File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py&#34;, line 389, in execute rec.execute(self) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py&#34;, line 548, in execute uow File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py&#34;, line 181, in save_obj mapper, table, insert) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py&#34;, line 835, in _emit_insert_statements execute(statement, params) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 945, in execute return meth(self, multiparams, params) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/elements.py&#34;, line 263, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1053, in _execute_clauseelement compiled_sql, distilled_params File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1189, in _execute_context context) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1402, in _handle_dbapi_exception exc_info File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/compat.py&#34;, line 203, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py&#34;, line 1182, in _execute_context context) File &#34;/usr/local/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/default.py&#34;, line 470, in do_execute cursor.execute(statement, parameters) IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: query.client_id [SQL: u&#39;INSERT INTO &#34;query&#34; (client_id, database_id, tmp_table_name, user_id, status, tab_name, sql_editor_id, schema, sql, select_sql, executed_sql, &#34;limit&#34;, limit_used, select_as_cta, select_as_cta_used, progress, rows, error_message, results_key, start_time, start_running_time, end_time, end_result_backend_time, tracking_url, changed_on) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)&#39;] [parameters: (u&#39;SkQME9zNf&#39;, 12, u&#39;&#39;, 5, u&#39;pending&#39;, u&#39;Untitled Query&#39;, u&#39;By60eA-EG&#39;, u&#39;smartmeter_pbi_dot11&#39;, u&#39;SELECT `userId`,\r\n `DPD`,\r\n `SPD`,\r\n `Weights`,\r\n `primaryCategory`,\r\n `secondaryCategory`,\r\n `terti ... (9 characters truncated) ... ry`,\r\n `Gender`,\r\n `AgeGroup`,\r\n `City`,\r\n `AmazonPref`\r\nFROM smartmeter_pbi_dot11.AmazonTestDashboard\r\nLIMIT 100&#39;, None, None, 1000000, 0, 0, 0, 0, None, None, None, 1515524970267.271, None, None, None, None, &#39;2018-01-09 19:09:30.270338&#39;)] </pre> </code> </body> </html>

Please help me because its kinda a SOS situation.

**Comment by xrmx** [comment]
You have to post the full stacktrace

**Comment by kartikshanbhag3333** [comment]
@xrmx Sorry for the trouble, but I have fixed it by using Jinja Templating, Following is the code for your or anyone's reference.  Let me know the thoughts on this.


SELECT COUNT(DISTINCT userId)/
  (SELECT COUNT(DISTINCT userId)
   FROM AppUsageFactSuperset
   WHERE 0=0
   {% set filters = form_data.get('filters') %}
   
   {% if filters %}
		{% for eachFilter in filters %}
			{% if eachFilter %}
				{% set column_name = eachFilter.get('col') %}
				{% set values = eachFilter.get('val') %}
				{% set operator = eachFilter.get('op') %}
				{% set joined_values = "'" + "','".join(values) + "'" %}
				
				AND {{ column_name }} {{ operator }} ( {{ joined_values }} )
			
		   {% endif %}
		   {% endfor %}
		   {% endif %}
   ) AS `Reach_Temp`
FROM smartmeter_pbi_dot11.`AppUsageFactSuperset`
WHERE 0 = 0
{% set filters = form_data.get('filters') %}
   
   {% if filters %}
		{% for eachFilter in filters %}
			{% if eachFilter %}
				{% set column_name = eachFilter.get('col') %}
				{% set values = eachFilter.get('val') %}
				{% set operator = eachFilter.get('op') %}
				{% set joined_values = "'" + "','".join(values) + "'" %}
				
				AND {{ column_name }} {{ operator }} ( {{ joined_values }} ) 
			
		   {% endif %}
		   {% endfor %}
		   {% endif %}
ORDER BY `Reach_Temp` DESC
LIMIT 50000

**Comment by saurabh1-singh** [comment]
Hey @kartikshanbhag3333 can you help me it in this, I am too trying to use jinja template but so far have not succeeded. The problem is i create a view just like yours but when i apply filters the values are filled correctly but it also tries to apply the filter after wrapping up the query in an query.

**Comment by abhishekkumaresan** [comment]
@xrmx  Hi, My SQL query for a chart involves subqueries, I need the filter values chosen in the filter box (in the dashboard) in the subquery also, can I pass it by any means like Jinja templating, pls explain.
