### ISSUE TITLE
sql_lab in mariadb-10.2.11: reserved words rows

### ISSUE THREAD

**Issue by potato2010** [apache/incubator-superset#4188]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset==0.22.1

### Actual results

sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows, error_message, results_key, start_time, start_running_time, end_time, end_' at line 1 [SQL: 'INSERT INTO query (client_id, database_id, tmp_table_name, user_id, status, tab_name, sql_editor_id, `schema`, `sql`, select_sql, executed_sql, `limit`, limit_used, select_as_cta, select_as_cta_used, progress, rows, error_message, results_key, start_time, start_running_time, end_time, end_result_backend_time, tracking_url, changed_on) VALUES (%(client_id)s, %(database_id)s, %(tmp_table_name)s, %(user_id)s, %(status)s, %(tab_name)s, %(sql_editor_id)s, %(schema)s, %(sql)s, %(select_sql)s, %(executed_sql)s, %(limit)s, %(limit_used)s, %(select_as_cta)s, %(select_as_cta_used)s, %(progress)s, %(rows)s, %(error_message)s, %(results_key)s, %(start_time)s, %(start_running_time)s, %(end_time)s, %(end_result_backend_time)s, %(tracking_url)s, %(changed_on)s)'] [parameters: {'client_id': 'Bkx3o-mNf', 'database_id': 1, 'tmp_table_name': '', 'user_id': 1, 'status': 'running', 'tab_name': 'Untitled Query 2', 'sql_editor_id': 'SJjPqZmVf', 'schema': 'alert_nagios', 'sql': 'SELECT 1', 'select_sql': None, 'executed_sql': None, 'limit': 1000000, 'limit_used': 0, 'select_as_cta': 0, 'select_as_cta_used': 0, 'progress': 0, 'rows': None, 'error_message': None, 'results_key': None, 'start_time': 1515555752063.365, 'start_running_time': None, 'end_time': None, 'end_result_backend_time': None, 'tracking_url': None, 'changed_on': datetime.datetime(2018, 1, 10, 3, 42, 32, 74340)}]

### 
https://mariadb.com/kb/en/library/reserved-words/

reserved words: ROWS

superset/models/sql_lab.py
`rows = Column(Integer)`

**Comment by xrmx** [comment]
Looks like something that is handled in sqlalchemy

**Comment by xrmx** [comment]
Opened PR here:
https://github.com/zzzeek/sqlalchemy/pull/414

**Comment by potato2010** [comment]
thanks，it works
