### ISSUE TITLE
A set of queries.

### ISSUE THREAD

**Issue by kartikgill96** [apache/incubator-superset#4189]
Hi ,
I was exploring superset and it is awesome. You guys have done a great job. There are a set of features I want included, or Please tell me if there is trick to make that work. Please tell me what is possible ,and what not. 
The desired features are:
1) Trend Line charts or pie charts: Taking Pie chart example(for gender distribution): Lets say I click on Male, then slice tells me only males in the pie chart,  What I want is , everything on that dashboard should be filtered according to selection in a single slice.(Frankly slices should be interlinked, I know filter slice is a way but I want graph clicks to filter things).

2) A way to add generic filter slice , where I could choose filterable columns and filter data in the dashboard.

3) Search text feature: let's say I have added one table view on dashboard , there should be search text feature where I could see desired row in that visualization).

4) Dynamic word clouds: If I click on that word it should show me search results on corresponding table.

5) A way to edit LIMIT of queries.

Please tell me what is possible and what is not and what is the cost for these features.
Thanks in advance.

**Comment by mistercrunch** [comment]
1. It'd be somewhat possible to implement this. One little challenge is that your pie chart may be a set of metrics with no dimension (filters shouldn't work), or one dimension and one metric (should work here). That'd be pretty easy to do as the dashboard controller already supports filtering (but only Table and Filter Box viz implement it)
2. Isn't this exactly what the Filter Box does?
3. There's a checkbox on the Table viz to add a full-text search
4. Word cloud could be altered to cast filtering event (much like Table does)
5. Not sure what you mean here, but most visualization offer a way to limit results, and there's an envrionment setting as a higher level limit.

**Comment by kartikgill** [comment]
Thanks for the quick response  @mistercrunch , I really appreciate it. There are somethings I couldn't explain correctly , so here is my output to your answers. thanks.
1. I am actually using one dimension one metric in pie chart, How can I make controller perform this type of filtering.
2. Actually when we add filter box, we define some filterable column (like: gender). I am having more than 10 filterable columns, I don't want to add 10 filter slices, I want a generic filter where first I choose which column I want and then it automatically adds one filter using that column.
3. Sorry my bad, search box is actually there. There is but one concern, it doesn't highlight searched text.
4. And how is that possible.
5. Like in word cloud I want only 20 top frequent words every time , if I apply filter than also top 20 top frequent words from filtered table.(unable to do it using where and having).

**Comment by mistercrunch** [comment]
1. here's how the table viz does it https://github.com/apache/incubator-superset/blob/master/superset/assets/visualizations/table.js#L137
2. isn't that what filter box does? you can pick many dimensions and you'll get one dropdown per dimension
3. sounds more like a nice to have than a concern to me
5. mmh, sounds like you may have to use some subquery in the Custom WHERE clause across many slices where you want your top 20

**Comment by rumbin** [comment]
Regarding the misunderstanding on No.2:

I understand that @kartikgill does not want to have a huge filter slice with many drop-downs but only a small one with maybe 2 of them, where the first one serves as selector for the dimension to be filterable in the second drop-down.

In other words, the first one would be a filter for the dimensions to be filtered on.

Right?

**Comment by kartikgill96** [comment]
yes @rumbin  that's exactly what I want. @mistercrunch

**Comment by mistercrunch** [comment]
It's not ideal to have many issues into one. Someone should break down this issue into many issues.
