### ISSUE TITLE
sql_lab.py is using the raw dbapi connection object and not SQLAlchemy dialect

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#4192]
Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
data = db_engine_spec.fetch_data(cursor, query.limit) should return a list of "sqlalchemy.engine.result.RowProxy"

### Actual results
returns a list of "pyodbc.Row"

### Steps to reproduce
Create a DB connection to using the mssql dialect. 

I would like to get your input on this issue. I was creating a new dialect using the pyodbc and ran into this issue. According to a conversation i have had on Google Groups we might not want to be using the raw_connection.
(https://groups.google.com/forum/#!searchin/sqlalchemy/pyodbc.Row$20%7Csort:date/sqlalchemy/wtLwkQr2xSY/SDvVbOySAAAJ)
Should this be a change in superset or will it impact 

with engine.connect() as conn: 
    result = conn.execute("SELECT * FROM ADV.MYTABLE") 
    result.fetchmany(limit)

vs what is in superset  (https://github.com/apache/incubator-superset/blob/e182f7f96227ef699c1e55c43bb97f8df2fa5f12/superset/sql_lab.py#L188)

        conn = engine.raw_connection()
        cursor = conn.cursor()
        cursor.fetchmany(limit)

**Comment by xrmx** [comment]
Does superset crash? What's wrong with the current type returned?

**Comment by rpwils** [comment]
Yes sorry I forgot to add the error. It see the results as just one column of data. 

2018-01-10 10:16:00,075:ERROR:root:Shape of passed values is (1, 100), indices imply (20, 100)
Traceback (most recent call last):
  File "/projects/incubator-superset/superset/views/core.py", line 2191, in sql_json
    query_id=query_id, return_results=True)
  File "/ss_python_venv/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/ss_python_venv/lib/python2.7/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/projects/incubator-superset/superset/sql_lab.py", line 94, in get_sql_results
    ctask, query_id, return_results, store_results, user_name)
  File "/projects/incubator-superset/superset/sql_lab.py", line 236, in execute_sql
    pd.DataFrame(data=data, columns=column_names)
  File "/ss_python_venv/lib/python2.7/site-packages/pandas/core/frame.py", line 330, in __init__
    copy=copy)
  File "/ss_python_venv/lib/python2.7/site-packages/pandas/core/frame.py", line 483, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/ss_python_venv/lib/python2.7/site-packages/pandas/core/internals.py", line 4303, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/ss_python_venv/lib/python2.7/site-packages/pandas/core/internals.py", line 4280, in construction_error
    passed, implied))

**Comment by mistercrunch** [comment]
Note that it's pretty tricky to write code that works across all DBAPIs. The spec itself isn't super formal on certain things and implementations diverge from the spec pretty often. SQLAlchemy doesn't always succeed at lining things up either.

To deal with this we have the `db_engine_spec` module to try and align everything. 

What does your connection string look like? Which db engine is this?

**Comment by rpwils** [comment]
You can test out the mssql one using the msql+pyodb.   
mssql+pyodbc://DB_USER:DB_PASSWORD@sIP:1433/schema?driver=FreeTDS

I am working on a dialect to use Dremio.

**Comment by rpwils** [comment]
@mistercrunch @xrmx  is there something you would like me to tackle on this?  It feels like a moderately bigger challenge as this would need to be abstracted out. Thoughts?

 engine = database.get_sqla_engine(
            schema=query.schema,
            nullpool=not ctask.request.called_directly,
            user_name=user_name,
        )
        conn = engine.raw_connection()
        cursor = conn.cursor()

**Comment by timkessler** [comment]
@tomasienrbc  I've got this working for me.  I'm dumping my full notes here.  Pay special attention to "MODIFY SUPERSET CODE FILES" section.  This section reshapes values to fit in superset.  If I understand correctly, the changes that I made to dataframe.py may need to be refactored into db_engines_spec.py


# *************** Install DREMIO connectors on Ubuntu ***************
# Install unixodbc - prerequisite to dremio-odbc
sudo apt-get install unixodbc-dev unixodbc-bin unixodbc

# Install dremio-odbc 
curl -o dremio-odbc-1.3.19.1052-1.x86_64.rpm https://download.dremio.com/odbc-driver/1.3.19.1052/dremio-odbc-1.3.19.1052-1.x86_64.rpm
sudo apt-get install alien
sudo alien -i dremio-odbc-1.3.19.1052-1.x86_64.rpm 

# *************** Build sqlalchemy_dremio ***************

# clone sqlalchemy_dremio dialect repository:
git clone https://github.com/sqggles/sqlalchemy_dremio.git
cd sqlalchemy 
make clean

# builds source and wheel package.  The make file referenced python2, so I pulled the commands out and changed to python3:
python3 setup.py sdist
python3 setup.py bdist_wheel
ls -l dist

# run tests
python3 sqlalchemy_dremio/tests/conftest.py 


# install the package to the active python3's site-packages
python3 setup.py install


# *************** MODIFY SUPERSET CODE FILES *************

superset/sql_lab.py:  
import sqlalchemy_dremio.pyodbc #add this line below import sqlalchemy

superset/dataframe.py:

Change from:
        self.column_names = dedup(
            db_engine_spec.get_normalized_column_names(cursor_description))

        data = data or []

        self.df = (
            pd.DataFrame(list(data), columns=column_names).infer_objects())

Change to:
        self.column_names = dedup(
            db_engine_spec.get_normalized_column_names(cursor_description))

        data = data or []

        #customized:
        colcount = len(column_names)
        rowcount = len(data)
        data = np.reshape(data, (rowcount, colcount))

        self.df = (
            pd.DataFrame(list(data), columns=column_names).infer_objects())

# *************** RESTART SUPERSET ***************
# Restart superset
systemctl restart superset.service

# *************** DREMIO ADMIN ***************
# Login to dremio
# Create user in dremio

# *************** Create Datasource in Superset ***************
# Create database connection with URI example below.  See sqlalchem_dremio/tests/test_sql_alchemy_dremio.py for more info.
# I used:
dremio+pyodbc://user:password@dremioipaddress:31010/mydremiodatasourcename

**Comment by tomasienrbc** [comment]
@timkessler badass, will be checking this out this weekend

**Comment by gigaclood** [comment]
@timkessler Which version of Dremio are you using? 
I'm using Dremio 2.0.5 and I get "Server message: [30007]Handshake failed because the server killed the connection. Expected RPC version 5. (30) (SQLDriverConnect)')" 
Superset is installed on Centos 7 

Thank you
Claudio

**Comment by davidswaven** [comment]
@timkessler  is this still working for you ? 
I am on Dremio 3.1.1 and could successfully query Dremio using Superset SQL Lab, but I've not been able to add a table on Superset.

**Comment by Eedupuganti** [comment]
Installed Dremio 4.x version and Superset 0.23 while trying to integrate i am getting pyodbc dialect plugin cant be loaded.Need to do anything. Thanks in advance

**Comment by kunaldawn** [comment]
FYI : https://github.com/kunaldawn/foss-lake/blob/master/superset/dremio.py
