### ISSUE TITLE
Running Stored Procedures from Superset

### ISSUE THREAD

**Issue by aabdin01** [apache/incubator-superset#4195]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Hello,

I have created a stored procedure(SP) in my db, lets call it "test". Whenever I try running the stored procedure, I get the error "(2014, "Commands out of sync; you can't run this command now")". I have looked up online and haven't found any solution in regards to running SP in superset. I am not sure if superset supports execution of SPs. Please let me know how to resolve this issue. 

### Superset version
Superset 0.20.6. 

### Expected results
Data generated from running the SP.

### Actual results
(2014, "Commands out of sync; you can't run this command now")

### Steps to reproduce
call test()

**Comment by xrmx** [comment]
Isn't there a backtrace or something in the logs?

**Comment by mistercrunch** [comment]
Which database engine is that?

**Comment by aabdin01** [comment]
@mistercrunch, I am using InnoDB as my database engine. @xrmx, the logs don’t mention anything more helpful than the error I mentioned.

**Comment by aabdin01** [comment]
Any comment on this yet?

**Comment by aabdin01** [comment]
@mistercrunch, could you please comment on this?

**Comment by balanemate2** [comment]
I'm having same issue with Superset 0.25.5 and MySQL. Event simplest MySQL procedures (like SELECT 1 in statement) returns same error - (2014, "Commands out of sync; you can't run this command now")

**Comment by mistercrunch** [comment]
We never explicitly supported sprocs as a data source. I'm unclear what it would take to make that happen or even whether it's possible. 

I took 30 seconds to google "mysql stored procedure as subquery", maybe this helps:
https://stackoverflow.com/questions/23071752/using-a-stored-procedure-as-subquery

**Comment by Manik0917** [comment]
Dear All, I had faced the issue hence I have made Stored procedure to insert the final results into physical table in MySQL and created a view to fetch the data from the physical table. Finally I have called view in Superset to visualize it in Dashboard. Hope this helps.

**Comment by NonLinearThinking** [comment]
> Dear All, I had faced the issue hence I have made Stored procedure to insert the final results into physical table in MySQL and created a view to fetch the data from the physical table. Finally I have called view in Superset to visualize it in Dashboard. Hope this helps.

This is not a dynamic solution! It can't be serious solution if you have to manually run the SP every time that we have different parameters!! Are you kidding me?
