### ISSUE TITLE
Adding new visualizations

### ISSUE THREAD

**Issue by kartikshanbhag3333** [apache/incubator-superset#4199]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.X
### Expected results
Adding new type of visualizations, what are the steps to do it? I need a funnel chart to be added

Thanks

**Comment by kartikshanbhag3333** [comment]
This one from d3js 
https://github.com/jakezatecky/d3-funnel/blob/master/README.md

**Comment by xrmx** [comment]
As written in the FAQ https://superset.incubator.apache.org/faq.html#how-do-i-create-my-own-visualization

**Comment by mistercrunch** [comment]
I looked at funnel libs in the past and most of them don't do a good job at showing proportions. Bar chart is way more clear and easy to get a sense of proportions from than trapezoids.

**Comment by CrystalSun1992** [comment]
I try to add a new funnel charts reference this url:https://zhuanlan.zhihu.com/p/35255207 . But mine does not work ,because i use the version 0.24.0, it's different between this page . u can have a try. please share it when u succeed.

**Comment by MK0820** [comment]
Hi,
I try to add some new visualizations, but the project structure has changed in version 0.28.1.Would you please update some samples?That will be very helpful.
Thank you.

**Comment by mistercrunch** [comment]
This hasn't fully settled yet but the plugin system is well under way, you can follow progress here:
https://github.com/apache-superset/superset-ui

**Comment by xwydq** [comment]
I use the version 0.32.0rc1 and want add new type of visualization, the project structure has changed much, there is a tutorial for do this? tks

**Comment by Smilebags** [comment]
+1 for the request for updated documentation on adding a visualisation. If there is any updated docs it would be great to know about them.

**Comment by arjunsalva** [comment]
Hi Team,
please guide, how to add custom visualization using chart.js and plotly.js in apache superset?

**Comment by tobiasdirksen** [comment]
Would be great to be able to code visualations in python directly.

**Comment by rusackas** [comment]
I just randomly stumbled across this thread... but just in case anyone still wants to build a plugin, here's [the current approach](https://preset.io/blog/2020-07-02-hello-world/).
