### ISSUE TITLE
Ability to save default values to Dashboard filter

### ISSUE THREAD

**Issue by phanipeddi2831** [apache/incubator-superset#4205]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
"0.22.1"

### Expected results
To save default values to a filter box placed in a dashboard. I want to set default values in filter box and add that slice to a dashboard, When I go to that dashboard , I want the dashboard to run it for the default values I have set it on filter box. 

Or is there a way to set default values on a filter box from Dashboard properties. 

Referred the below links but did not find a solution. 
https://github.com/apache/incubator-superset/issues/3071
https://github.com/apache/incubator-superset/pull/3183
https://github.com/apache/incubator-superset/issues/3618
https://github.com/apache/incubator-superset/issues/665

### Actual results
No Feature available. 

### Steps to reproduce
Steps explained in expected results.

**Comment by graceguo-supercat** [comment]
I am not sure if i understand the issue. Superset dashboard can save default filter value like this:
![rn9krstyzf](https://user-images.githubusercontent.com/27990562/34899319-ffafdfb0-f7ac-11e7-885c-f1c3677a64ca.gif)

**Comment by phanipeddi2831** [comment]
Thanks This helped. It was not clear in the issues I referred on how to save the dashboard. But I am good now. Thanks.

**Comment by sevalo8** [comment]
Hi @graceguo-supercat , 
i try as the animation that you share, but why the filter still not set as when i klik di save.
when i open the dashboard it's always show blank filter.
Anything that i need to set before?

Thanks,


Steven

**Comment by mistercrunch** [comment]
@sevalo8 are you using an old version?
