### ISSUE TITLE
Superset Default Dashboard Filter using jinja templating

### ISSUE THREAD

**Issue by aabdin01** [apache/incubator-superset#4214]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar
Hello,

I have been playing around superset, and I am just curious whether there is a support for default dashboard filter using jinja template functions. A use case would be to show stats for a user in a dashboard. Whenever the user logs in, there current stats are shown. This could be achieved by using current_username() function. I have tried to add this in the json metadata for the dashboard with no success. 

### Superset version
Superset 0.20.6

### Expected results
Stats with current user information

### Actual results
Feature not supported

**Comment by xiaohanyu** [comment]
Why would you to show current user information on dashboard?
