### ISSUE TITLE
Add support for deck.gl "polygon" layer

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#4216]
Add support for Polygon layer in Superset
https://uber.github.io/deck.gl/#/documentation/layer-catalog/polygon-layer

**Comment by moriryota** [comment]
I'd like to create a choropleth map using polygon data in units of municipalities. 
What type of data should I use?
If there is a table containing geojson in the column, can I visualize it?
I would like to know sample data and how to set up queries.
