### ISSUE TITLE
Pie Chart from Plotly

### ISSUE THREAD

**Issue by rahimramezanian** [apache/incubator-superset#4218]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest one at the moment. 2018/01/16

### Steps to reproduce
I used some guides in previous issues to create a plotly pie chart.
first I create a `p_pie.js` files in `superset/assets/visualizations/`

[p_pie.txt](https://github.com/apache/incubator-superset/files/1634949/p_pie.txt)

then I edit `superset/assets/javascripts/explore/stores/controls.jsx` by adding:
```
  pie_label_type_plotly: {
    type: 'SelectControl',
    label: t('Label Type'),
    default: 'key',
    choices: [
      ['key', 'Category Name'],
      ['value', 'Value'],
      ['percent', 'Percentage'],
      ['key_value', 'Category and Value'],
      ['key_percent', 'Category and Percentage'],
    ],
    description: t('What should be shown on the label?'),
  },
```
and `superset/assets/javascripts/explore/stores/visTypes.js` by adding:
```
  p_pie: {
    label: t('Pie Chart - Plotly'),
    showOnExplore: true,
    controlPanelSections: [
      {
        label: t('Query'),
        expanded: true,
        controlSetRows: [
          ['metrics', 'groupby'],
          ['limit'],
        ],
      },
      {
        label: t('Chart Options'),
        controlSetRows: [
          ['pie_label_type'],
          ['donut', 'show_legend'],
          ['labels_outside'],
          ['color_scheme'],
        ],
      },
    ],
  },
```
add to `superset/data/__init__.py`:
```
        Slice(
            slice_name="GendersPlotly",
            viz_type='p_pie',
            datasource_type='table',
            datasource_id=tbl.id,
            params=get_slice_json(
                defaults,
                viz_type="p_pie", groupby=['gender'])),
```
add to `superset/viz.py`:
```
class PiePlotlyViz(NVD3Viz):

    """Annoy visualization snobs with this controversial pie chart"""

    viz_type = 'p_pie'
    verbose_name = _('Distribution - Plotly - Pie Chart')
    is_timeseries = False

    def get_data(self, df):
        df = df.pivot_table(
            index=self.groupby,
            values=[self.metrics[0]])
        df.sort_values(by=self.metrics[0], ascending=False, inplace=True)
        df = df.reset_index()
        df.columns = ['x', 'y']
        return df.to_dict(orient='records')
```
add to `superset/assets/visualizations/main.js`:
```
  p_pie: 'p_pie', 
```
and 
```
  [VIZ_TYPES.p_pie]: require('./p_pie.js'),
```

Now when I am trying to execute `yarn run build`

I get two similar errors
```
ERROR in dashboard.be55626a4dddad6eed81.entry.js from UglifyJs
Unexpected token: name (ARRAY_TYPE) [dashboard.be55626a4dddad6eed81.entry.js:76869,4]

ERROR in explore.332aa2868b37b6962d8d.entry.js from UglifyJs
Unexpected token: name (ARRAY_TYPE) [explore.332aa2868b37b6962d8d.entry.js:76764,4]
```

beside the error could you please tell me if there are other files that I should change?

**Comment by xrmx** [comment]
"Last one at the moment" is not a version number. I think that support for plotly may be interesting for other, what about opening a PR and get review there?

**Comment by mistercrunch** [comment]
Looks like a syntax error in your JS. I'd suggest using `yarn run dev`, you'll a proper source map pointing to the right line numbers.

**Comment by ahsanshah** [comment]
You may want to look at the input parameters required by plotly and ensure it maps to the correct classes

For a Plotly "Time Series"  you can use the NVD3TimeSeries which has the relevant payload formats.
For a Plotly Pie Chart, you may want to use the BaseViz and format the inputs correctly 

I was able to get a base Plotly Pie/Bar as well as a TimeSeries plot working.  However, this was more for understanding how to customize Superset.  Given a lot of the functionality exists in the existing charts, it would seem redundant to add this to Superset. I do like the zooming and export options from Plotly though.

**Comment by mistercrunch** [comment]
We're looking into making visualizations work as plugins eventually and hoping people would create their own and share them. Closing since this has been stale for a while.
