### ISSUE TITLE
Ability to Filter on float, int type columns 

### ISSUE THREAD

**Issue by phanipeddi2831** [apache/incubator-superset#4228]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
 "0.22.1"}

### Expected results
I am not able add float,int data type columns into a filter box for me to filter on a dashboard. For ex : I have a column called duration (type int). I would like to add this column to filter box on a dashboard and apply filters like duration =5 or duration <=100 . 

I am not able to see a way to get this done with 'filter box' visualization type.  Please let me know if I am missing anything. 

### Actual results
Not able to add filters on float, int data type columns. 

### Steps to reproduce
Explained in Expected results.

**Comment by kartikshanbhag3333** [comment]
Its very easy

1. Edit the desired table and click on List Columns tab.
2. There are 2 rows, "Groupable" and "Filterable"... Click on them 
3. Save the table and then you will be able to add the filters.
