### ISSUE TITLE
build master branch failed

### ISSUE THREAD

**Issue by hupangpang** [apache/incubator-superset#4245]
Make sure these boxes are checked before submitting your issue - thank you!

- [ok] I have checked the superset logs for python stacktraces and included it here as text if any
- [ok] I have reproduced the issue with at least the latest released version of superset
- [ok] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
build superset from source code with success

### Actual results
no success, stuck at exec "python setup.py install"

### Steps to reproduce
build as the Make your own build .
cd $superset-master/superset/assets
yarn
yarn run build
cd $superset-master
python setup.py install

GET STUCK every time when exec python setup.py install
error: can't copy 'superset/static/assets': doesn't exist or not a regular file

superset/static/assets is a Symbolic Link of ../assets

yarn & yarn run build just work success, but i got the error on master branch everytime. 
any helps?!!

**Comment by xrmx** [comment]
What operating system / python version is this?

**Comment by hupangpang** [comment]
i use ubuntu trusty and python version is 2.7.6

**Comment by mistercrunch** [comment]
Same issue with `pip install .` from the root of the repo?

**Comment by hupangpang** [comment]
but when i install other release branch like 0.23 and 0.22, run `python setup.py install ` cmd just work OK,
am i do something wrong or miss some steps with master branch?

**Comment by hupangpang** [comment]
superset  isn’t officially supported on Windows, and the kombu module needed by superset is not supported on Windows, so, you better try linux OS

**Comment by mistercrunch** [comment]
I have no idea...

**Comment by timifasubaa** [comment]
If you're cmofortable with Docker, you can try to see if this works for you : https://hub.docker.com/r/amancevice/superset/

**Comment by suwenkun1126** [comment]
how to sovle this problem,I have same issue
