### ISSUE TITLE
typo related to SUPERSET_WEBSERVER_TIMEOUT

### ISSUE THREAD

**Issue by andreineculau** [apache/incubator-superset#4247]
### Superset version

0.22.1..master

### Actual

https://github.com/apache/incubator-superset/blob/18e9640d9976664b7e5681562cd2cbd5cc00055e/superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx#L297

### Expected

isn't `state.common.SUPERSET_WEBSERVER_TIMEOUT` supposed to be `state.common.conf.SUPERSET_WEBSERVER_TIMEOUT` ?

Possibly related to https://github.com/apache/incubator-superset/issues/3886

**Comment by mistercrunch** [comment]
Thanks for reporting this, the fix is out for review
