### ISSUE TITLE
'PyDruid' object has no attribute 'scan'

### ISSUE THREAD

**Issue by rorovic** [apache/incubator-superset#4248]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

When i use Histogram with Druid datasource , i encounter this exception:
'PyDruid' object has no attribute 'scan'

### Superset version
0.22.1

### Expected results
46 2018-01-19 17:17:27,633:ERROR:root:'PyDruid' object has no attribute 'scan'
47 Traceback (most recent call last):
48 File "/home/dujinyuan02/superset/superset/viz.py", line 267, in get_payload
49 df = self.get_df()
50 File "/home/dujinyuan02/superset/superset/viz.py", line 102, in get_df
51 self.results = self.datasource.query(query_obj)
52 File "/home/dujinyuan02/superset/superset/connectors/druid/models.py", line 1212, in query
53 client=client, query_obj=query_obj, phase=2)
54 File "/home/dujinyuan02/superset/superset/connectors/druid/models.py", line 943, in get_query_str
55 return self.run_query(client=client, phase=phase, **query_obj)
56 File "/home/dujinyuan02/superset/superset/connectors/druid/models.py", line 1092, in run_query
57 client.scan(**qry)
58 AttributeError: 'PyDruid' object has no attribute 'scan'

### Actual results
![image](https://user-images.githubusercontent.com/12078430/35144456-8b16b9b0-fd3f-11e7-8fb1-ac7a69732036.png)

**Comment by mistercrunch** [comment]
I don't think you're running `0.22.1`, current trunk depends on a yet-to-be-released version of pydruid. I've been waiting to get a pydruid release in order to package a new version of Superset.

In the meantime you can  `pip install git+https://github.com/mistercrunch/pydruid.git@0.3.2beta#egg=pydruid-0.3.2beta`

**Comment by rorovic** [comment]
Thank you very much! @mistercrunch  when i upgrade pydruid to pydruid-0.3.2beta , i solved this problem!
