### ISSUE TITLE
[geo] deck.gl vizs only; error when creating new slice from druid datasource

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4253]
When exploring a druid datasource via a deck.gl visualization (creating new), get an error message:
{'NoneType' object has no attribute 'get'}

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.23.0rc1
### Expected results
Visualization should be shown

### Actual results
Error message - see attached image

### Steps to reproduce
1. Go to Sources->Druid datasources
2. Choose one
3. Change viz type to deck.gl viz
4. Error message appears

**Comment by vylc** [comment]
<img width="1353" alt="screen shot 2018-01-19 at 11 58 46 am" src="https://user-images.githubusercontent.com/33429480/35173340-fa463c2c-fd1f-11e7-8d7a-45d9dbf1e0e8.png">

**Comment by hughhhh** [comment]
Picking this one up 💯

**Comment by mistercrunch** [comment]
@hughhhh oops I think I fixed this one already, didn't realized you had claimed it...
