### ISSUE TITLE
 http to https mistakes

### ISSUE THREAD

**Issue by zhizunbao514** [apache/incubator-superset#4256]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
When I want  http to https,ngingx already rewrite,The browser will display many of the mistakes:
"was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxx.com/superset/favstar/slice/10/count/'. This request has been blocked; the content must be served over HTTPS."

I think it should be here has a problem, or other jquery request, but I don't know how to modify them。
/incubator-superset-master/superset/assets/javascripts/explore/actions/exploreActions.js 104

Thank you very much for your help

**Comment by donbowman** [comment]
This can be reproduced on any dashboard (just opening it).
The environment is:
https ingress proxy (e.g. kubernetes setup w/ nginx) so that the browser sees https://... and then superset is running http on e.g. default port.

I'm not sure if `ENABLE_PROXY_FIX` impacts?

**Comment by chenhaiyan** [comment]
@zhizunbao514 can you handle this？ I have the same problm！！！

**Comment by donbowman** [comment]
still occurring on the favourites

**Comment by ImmortalLotus** [comment]
this is still happening
