### ISSUE TITLE
Line Chart lines are not continuos

### ISSUE THREAD

**Issue by Ooooooog** [apache/incubator-superset#4257]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I'm trying to draw 'Time Series - Line Chart' with by data with time granurality 5 minutes.
I'm using metrics 'count'.
I'm seeing these wierd cut lines whenever the value goes to 0, or jumps from 0.
Is this a bug or am I missing something?

### Superset version
0.22.1

### Expected results
lines should be connected to 0 values

### Actual results
![image](https://user-images.githubusercontent.com/20537368/35207727-eb4d239c-ff87-11e7-9d77-22ffee7e4923.png)
![image](https://user-images.githubusercontent.com/20537368/35207930-ebcaaa0a-ff88-11e7-927c-77bbc5fe3021.png)

### Steps to reproduce
It doesn't happen if all the data value is higher than 1.

**Comment by rumbin** [comment]
Are you sure that real data points exist within the gaps at zero level? If the series is not completely contiguous the lines won't be drawn unless you resample the data in order to interpolate missing data points.

I'd suggest to filter on one of the questionable series an then export the CSV or just display the data as table. So you can see if the query returns contiguous data.

**Comment by Ooooooog** [comment]
You were right about that some data is missing at certain time. 
I realized that count cannot have value of 0.

The problem still relies that the lines are not continuous..
I found out that this happens only when I use group by.
When I do not use group by, than the graph is continuous even if there is missing data.

**Comment by Ooooooog** [comment]
When not using group by
![image](https://user-images.githubusercontent.com/20537368/35319004-4e093a30-0121-11e8-963f-02f26a5295f4.png)

When using group by
![image](https://user-images.githubusercontent.com/20537368/35319035-6c3c25bc-0121-11e8-946b-f6196ffbc04e.png)

**Comment by mistercrunch** [comment]
Check out the "resample" option

**Comment by Ooooooog** [comment]
Thank you. The line is smooth now!
