### ISSUE TITLE
How superset to support SPA?

### ISSUE THREAD

**Issue by 738623786** [apache/incubator-superset#4258]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
What is SPA?

**Comment by rumbin** [comment]
Just a guess:
https://en.wikipedia.org/wiki/Single-page_application
