### ISSUE TITLE
Weekly time grain: ticks and markers not aligned

### ISSUE THREAD

**Issue by nbonnotte** [apache/incubator-superset#4267]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Expected results

On a line chart or percent-change chart, with a PostgreSQL backend and a weekly time grain, I would expect the x-axis ticks to match the markers, which are set on Mondays 

### Actual results

Markers are aligned on Mondays. Because that's what PostgreSQL sends, I guess, since `DATE_TRUNC` follows the ISO standard, and `DATE_TRUNC('week', '2018-01-23')` returns Monday 24.

X-ticks are aligned on Sundays. This is wrong.

### Steps to reproduce

Do a line chart with a weekly time grain on a PostgreSQL backend

**Comment by xrmx** [comment]
Related? https://github.com/apache/incubator-superset/issues/971

**Comment by nbonnotte** [comment]
Close, but no. This is a front-end issue only

**Comment by StephTruong** [comment]
I have this issue but with a MySQL database. When I am selecting the time grain to be week_start_monday on a time series graph, the markers show Mondays but the xticks show Sundays.

**Comment by fikriabror** [comment]
Hi I got the same issue, the difference only in the chart the X-axis not show any particular days just random days. How to make the weekly time grain X-axis matches with the markers. 
<img width="1431" alt="Screen Shot 2022-04-04 at 16 37 50" src="https://user-images.githubusercontent.com/11493699/161517967-295885e8-70d4-4436-ae8c-e04bd4e535d8.png">

**Comment by Pedrowach** [comment]
> Hi I got the same issue, the difference only in the chart the X-axis not show any particular days just random days. How to make the weekly time grain X-axis matches with the markers. <img alt="Screen Shot 2022-04-04 at 16 37 50" width="1431" src="https://user-images.githubusercontent.com/11493699/161517967-295885e8-70d4-4436-ae8c-e04bd4e535d8.png">

Did you get any solutions here?
