### ISSUE TITLE
Adding new Query

### ISSUE THREAD

**Issue by olokedeomotayo** [apache/incubator-superset#4269]
Good Morning,

I am new to Apache Superset and i have successfully connected MYSQL Db to Superset and the following was my set back;

1. Unable to Join to table together due to the fact that i can not locate where to add my query.
2. I tried using SQL LAB but my database is not LISTED.

Please any help on these.

Thank you.

**Comment by olokedeomotayo** [comment]
Good Morning,

I am new to Apache Superset and i have successfully connected MYSQL Db to Superset and the following was my set back;

    Unable to Join to table together due to the fact that i can not locate where to add my query.
    I tried using SQL LAB but my database is not LISTED.

Please any help on these.

Thank you.

**Comment by olokedeomotayo** [comment]
Thank You @shyam2794 this makes me view and work with my Database.... 

How do i now convert the SQL Script there to Dashboard?

Any Help Please

**Comment by shyam2794** [comment]
@olokedeomotayo  In the Sql lab after writing your query -> click run query -> click visualise .

**Comment by olokedeomotayo** [comment]
Thank You once again.  i would like you to take a look at the SQL Script below;
SELECT name AS name,
       (`tabSales Invoice Item`.item_group) AS item_group,
       (`tabSales Invoice Item`.item_name) AS item_name,
       SUM(`tabSales Invoice Item`.amount) AS sum__amount
       (`tabSales Invoice Item'.customer_name) AS customer_name,
       SUM(`tabSales Invoice`.total) AS sum__total
FROM (`tabSales Invoice Item`) 
LEFT JOIN `tabSales Invoice` ON `tabSales Invoice`.name = `tabSales Invoice Item`.name
WHERE creation >= '2016-09-10 00:00:00'
  AND creation <= '2018-01-23 11:41:34'
GROUP BY name,
         item_group,
         item_name,
         customer_name
ORDER BY sum__amount DESC
LIMIT 50000

the table is returning only for the first table ignoring the other table.

Any Help Also

**Comment by shyam2794** [comment]
You can have a look at this thread 
https://github.com/apache/incubator-superset/issues/875

**Comment by olokedeomotayo** [comment]
Dear @alanmcruickshank i tried Inserting the Row just like you explained  in Isues #875 but i seems not to be getting the correct results. 
I have a two tables i want to join like that, i have a Column in one but not in the other table which i want to Insert into the Other table, how do i go about this any help Please.

**Comment by Saranya411** [comment]
Hi All,

Can someone help me to connect Netezza from Superset. I'm new to superset and not sure how to connect Netezza from Superset
