### ISSUE TITLE
Should we add `yarn.lock` file?

### ISSUE THREAD

**Issue by xiaohanyu** [apache/incubator-superset#4274]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

master version

### Expected results

Should add a `yarn.lock` file to main repo to make build reproducible

### Actual results

No `yarn.lock` or `packge-lock.json` right now.

### Steps to reproduce

When I try to build my own superset, some times the build may be occationally failed. Then I found that there's no `yarn.lock` file in main repo, so different build may get different version of the same js packages.

Should we add the `yarn.lock` to main repo and do a monthly upgrade to this `yarn.lock` file?

Thanks.

**Comment by mistercrunch** [comment]
I'm open to it. PRs welcomed. Please update `CONTRIBUTING.md` to let people how it affects the build process.

**Comment by xiaohanyu** [comment]
@mistercrunch OK, thanks. I'll do a stable build and pick a work `yarn.lock`, and update the documentation.
