### ISSUE TITLE
Is there any way for Tuning Superset??

### ISSUE THREAD

**Issue by AnithaMurugesan** [apache/incubator-superset#4281]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Actual results
Hi,
Is there any way to tune the superset??
Most of the times, Superset in taking over 15 sec to load every page in it.
I have also enabled redis cache in it.
I am using postgres for storing the superset metadata in another instance.
What would be the reason??

Thanks in Advance.

**Comment by xrmx** [comment]
If *every page* takes 15 seconds you probably have a misconfigured http proxy before superset that is timing out :)

**Comment by AnithaMurugesan** [comment]
Thanks...
Sorry...I can't get it...What do you mean by misconfigured http proxy before superset...I just started service like "superset runserver"

**Comment by kingo55** [comment]
I agree, it's very much unrelated to Superset because it's configuration you should be making in your upstream proxy server. E.g.

- Cache control headers on static content
- Gzipping content
- HTTP2 for multiplexing requests through it

Very similar to improving page speed on a typical WordPress site or other CMS. Just as you don't want every hit running PHP, you don't want every hit running Python code in Superset, because it's way more efficient to access static content through Nginx / Apache.

ROugh primer here: https://varvy.com/pagespeed/improve-server-response.html

**Comment by AnithaMurugesan** [comment]
Hi...
Sorry...just now I figured this...
In logs, I can see 'loaded from cache' only in case of loading repeated slices and dashboards.
The superset pages are not loading from cache.
I have used the configuration as:
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',  
    'CACHE_KEY_PREFIX': 'superset_results',
    'CACHE_REDIS_HOST': 'localhost',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
    'CACHE_REDIS_URL': 'redis://localhost:6379/0'
   }
TABLE_NAMES_CACHE_CONFIG = {'CACHE_TYPE': 'redis'}
from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')

What else do I need to add in this configuration to make the pages also to load from cache...??
Thanks in advance..

**Comment by SyamprasadNakka** [comment]
Hello @AnithaMurugesan ,

We are facing the same issue and loading the page is taking 15-20 sec, did you resolve the issue. 
If yes, could you please provide the configuration to overcome the issue.

Regards,
Syam

**Comment by hariv1990** [comment]
Hello @AnithaMurugesan , @SyamprasadNakka  , We too face the issue of loading the superset pages  in 15-20 secs . While the query elapsed time is just under 5 seconds , the superset chart appears much late . Are there superset level configurations which can make this improved  ?  Thanks
