### ISSUE TITLE
No data on the Deck.gl map

### ISSUE THREAD

**Issue by Fokko** [apache/incubator-superset#4282]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results

When doing a query in deck.gl, I expect markers on the map:
![image](https://user-images.githubusercontent.com/1134248/35334996-79a181aa-0114-11e8-8b52-6e38d1b11525.png)

### Actual results
I don't have any markers on the map, but when I hit the `json` button on the top-right, I do get data:

![image](https://user-images.githubusercontent.com/1134248/35335062-aa53080a-0114-11e8-9252-0918d04db879.png)

**Comment by mistercrunch** [comment]
Mmmmh. Have you tried zooming in all the way to where the data points to? Maybe increase the grid size to something real big to help find the data?

You also may want to try against `master` as we've done a lot of work on geospatial since `0.22.1`

**Comment by srimalj** [comment]
I still have same issue in  0.24.0

Did anyone get the markers to show after that?

**Comment by mistercrunch** [comment]
How's the `Deck.gl Scatterplot` looking in `0.25.0` ?

**Comment by zeebonk** [comment]
@Fokko Just did some tests, and in general it seems to be working! 

Some issues that we noticed but haven't investigated further:
* With the 3d graphs, the pitch and bear kept being reset to 0, so we haven't seen anything 3d yet
* Time/animation didn't seem properly pick up the available hours (perhaps caused by having more than MAX ROWS rows in a single hour)

**Comment by mistercrunch** [comment]
Uncheck `Autozoom` otherwise the viewport will be changed at each query.

**Comment by zeebonk** [comment]
Thanks @mistercrunch, that solved it! Works really nice!

**Comment by mistercrunch** [comment]
I'm hoping we deprecate the original `Mapbox` chart in favor of the deck.gl ones eventually.

**Comment by hemantaggarwal** [comment]
@mistercrunch: I am facing this same issue. Just empty map without any markers. I am using superset 0.30
I tried disabling auto zoom, still no effect. What can be the solution?
@Fokko : Did you find solution to this
