### ISSUE TITLE
[FilterBox] Select single value

### ISSUE THREAD

**Issue by raffas** [apache/incubator-superset#4283]
### Superset version 0.22.1

Hello, is there the possibility to allow the selection of only a single option in the filter box?
The actual behaviour is to allow multiple select option.

Can this be a feature-request ?

**Comment by mistercrunch** [comment]
There's a need to re-write Filter Box to allow individual filter to be configurable independently. For instance each filter may or may not allow multiple selection or may be sorted based on a metric or alphabetically.

**Comment by ahsanshah** [comment]
This would be great.  We sometimes have cases where having a multi select results in double counting values so the ability to independently configure a filterbox would match most standard BI requirements.  

Any workaround for this in the meantime?
