### ISSUE TITLE
Maps in Apache Superset

### ISSUE THREAD

**Issue by criscod** [apache/incubator-superset#4286]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X ] I have reproduced the issue with at least the latest released version of superset
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
Create Maps with Superset's basic features

### Actual results
Depending on Mapbox

### Steps to reproduce
Added a map for Switzerland. 

Hi, 

Isn't there a way to create map-based slices in Apache Superset, without needing to pay for Mapbox? The key feature that made us use Apache Superset is because it is open source and we can extend it. So, we expected it to allow to create map visualizations without having to pay extra.

Cristina

**Comment by xrmx** [comment]
@criscod since you recognize that you can extend superset to do what you need, what's stopping you from contributing a map that does not use mapbox tiles? Then FYI mapbox has a free tier and nobody is forcing you to pay anything. And we also have a different map visualization.

**Comment by criscod** [comment]
> Then FYI Mapbox has a free tier and nobody is forcing you to pay anything.

a free tier with limited to 50,000 views per map.

> And we also have a different map visualization.

Great! Could you please share a link, or give more details about it?
