### ISSUE TITLE
Query starting with jinja2 statement is rejected because "it's not a select"

### ISSUE THREAD

**Issue by memeplex** [apache/incubator-superset#4288]
Superset version: 0.22.1

# Steps to reproduce

Run the following query:

```
{% set x = 1 %}
select {{x}}
```

and I will get `Only SELECT statements are allowed against this database`.

Of course this will work:

```
--{% set x = 1 %}
select {{x}}
```

But superset should recognize the first one as valid input too.

**Comment by memeplex** [comment]
Probably related to https://github.com/apache/incubator-superset/issues/3998

**Comment by villebro** [comment]
Implementing this change seems pretty straight forward, but seems to require some additional refactoring to be able to implement a decent test case. Will take a stab at this in the coming days.
