### ISSUE TITLE
CSV upload feature errors out

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4289]
Getting `Not a valid choice` on the database field, what am I missing @timifasubaa ?

<img width="973" alt="screen shot 2018-01-25 at 10 58 41 am" src="https://user-images.githubusercontent.com/487433/35406818-ca61af70-01be-11e8-8658-590a7b5f654a.png">

**Comment by timifasubaa** [comment]
Looking into this. 
It appears the dynamic drop down doesn't reload when there is an error.
I'll send out a PR shortly to remedy the issue.

**Comment by xrmx** [comment]
@timifasubaa while at it please take a look at #4285 and #4287

**Comment by timifasubaa** [comment]
I've seen a number of things that could have been done better. I'm refactoring the whole thing.
