### ISSUE TITLE
[Explore View] Make Time selections more usable

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4292]
Updates to make filtering on time more efficient:
(1) Default to 'Relative' tab. Allow the user choose commonly used time frames (ie. last week, last month, etc.) 
(2) After clicking on either Since or Until, there should be affordances to modify both Since and Until values at the same time
(3) Freeform and Fixed can be combined. Get to these options by clicking on the tab.
(4) Once the date/time has been selected on the calendar popup, it should close to avoid multiple windows showing up 
(5) OK button to be moved to lower right corner as standard UI design pattern (not shown, but 'Cancel' should be to the left of OK and should be a white button, black/grey text.
(6) Allow type in for fixed dates - currently limited to just being able to select from calendar popup
   
<img width="620" alt="screen shot 2018-01-25 at 2 38 57 pm" src="https://user-images.githubusercontent.com/33429480/35416411-dd370f86-01dd-11e8-9853-fde548f43581.png">
<img width="702" alt="screen shot 2018-01-25 at 2 39 05 pm" src="https://user-images.githubusercontent.com/33429480/35416412-dd4f3cfa-01dd-11e8-8f4f-15b8d92f9a18.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.0rc1

**Comment by betodealmeida** [comment]
@vylc, a few questions about this:

I understand that in this new design the relative tab sets both the since and until fields. How does this work? If I select "last week" will this set since to `-7 days` and until to `now`?

What happens if I click until and make a new selection, say, "last day"? Will this set since to `-1 day` and until to `now`? Or is the time range now from `-7 days` to `-1 day`?

**Comment by vylc** [comment]
Done
