### ISSUE TITLE
[Cache] - If cache is unavailable for some reason, requests time out

### ISSUE THREAD

**Issue by frankfarrell** [apache/incubator-superset#4300]
Requests time out after 1 minute if the cache is unavailable. 

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
Call to cache should timeout after some conventional or configurable duration, eg 10s

### Actual results
The call to the cache hangs and the http request times out

### Steps to reproduce
Start superset with cache config pointing to redis. Stop redis. Make a request that would hit the cache. 

I guess the solution is to wrap all calls to cache such that they time out. 
It doesnt't seem that flask-cache or werkzeug.RedisCache which it uses supports calls with a timeout. It may be that updating to this library could help, https://github.com/sh4nks/flask-caching but I havent looked too much at it. 

Cheers, thanks for a great project

**Comment by mistercrunch** [comment]
We have a timeout decorator we could use to wrap that `cache.get` call.
