### ISSUE TITLE
Join query is not executing

### ISSUE THREAD

**Issue by vijayashok** [apache/incubator-superset#4306]
while executing join query its throwing 30 secs time out error. kindly assists us

**Comment by xrmx** [comment]
We have an issue template, please use it and add the needed information

**Comment by vijayashok** [comment]
Hi Riccardo,

We are using superset, In that, while executing the joint query it is
throwing an error of 30 sec timeout. Can you please assist us to resolve it.

Thanks & Regards
Vijayaraghavan.K
Platform Engineer
Magellanix Technology Solutions Private Limited
Mobile : +91-8681871303 / 9003030204

**Comment by hajdbo** [comment]
@kristw please close: answered in the documentation: 
https://superset.incubator.apache.org/faq.html#why-are-my-queries-timing-out
