### ISSUE TITLE
Adaptative Formatting month and Quarter 

### ISSUE THREAD

**Issue by shyam2794** [apache/incubator-superset#4307]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
20.5

### Expected results
In the time grain filter on choosing month and selecting the months (jan-17 , Dec -17 , jan-18) . The result should show something like this . 

![screenshot from 2018-01-29 16-32-22](https://user-images.githubusercontent.com/30238125/35507282-37435994-0512-11e8-91a5-55d98ea7085f.png)

### Actual results
 But if we use adaptative formatting and choose the same time period as above , we are able to see that Jan-2017 as (2017) and jan-2018 as (2018) . This sometimes misleads the end user on what they are looking at whether year data or month wise data .

Time Grain - Month 
 
![screenshot from 2018-01-29 16-43-01](https://user-images.githubusercontent.com/30238125/35507648-81d6c602-0513-11e8-83e2-a8bca61d383a.png)

 Similarly choosing quarter on time grain produces the correct results but the x-axis is still displayed in months instead of quarter . The ' X - axis  ' to be displayed in quarter instead of month will be very helpfull . 

Time Grain - Quarter 
![screenshot from 2018-01-29 16-45-06](https://user-images.githubusercontent.com/30238125/35507742-cb9d4a54-0513-11e8-999d-1e5f7a1ba0e8.png)

### Steps to reproduce

In the time series charts , choose 
1. date field in time column 
2. under time grain choose Month 
3. Apply Filter for the month January .
4. Under time grain choose Quarter .  

Thanks

**Comment by xrmx** [comment]
Not that i think this changed but 0.20.5 is quite old, please reproduce against a newer release

**Comment by shyam2794** [comment]
@xrmx Thanks for the quick response . I have reproduced the same in version 22.1 , but still seeing the same results .

**Comment by shyam2794** [comment]
@xrmx @mistercrunch any update regarding this issue .

**Comment by mistercrunch** [comment]
I agree that adaptative formatting could perform better, in the meantime you can specify the exact time format you want.

**Comment by shyam2794** [comment]
@mistercrunch yes i tried specifying the x-axis format which i require . But the issue is if i choose %B-%Y which will give january 2018 , this works fine when the time grain is specified as month , but when the time grain is choosen as year , this over-rides the format where all the year data are displayed as january 2017 , january 2018 instead of 2017 , 2018 . Again this misleads the visualization .

**Comment by amancevice** [comment]
The only way I was able to find to get month-to-date results was to use the string: `one day after last month eom`, which is hilarious but seems to have worked.

**Comment by mistercrunch** [comment]
Ideally the formatting would be aware of the time granularity and pick a default based on that.
