### ISSUE TITLE
Rebuild the table editor

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4308]
<img width="848" alt="screen shot 2018-01-29 at 3 08 40 pm" src="https://user-images.githubusercontent.com/487433/35539440-5b4d6f7a-0506-11e8-9f69-d4a2467c6644.png">

**Comment by rumbin** [comment]
I'd love the column headers to be visible upon scrolling, as I often end up scrolling to the top of the table again, just for finding out which checkbox column to choose.

**Comment by mistercrunch** [comment]
Agreed, I think it means I have to use another component (`reactable` doesn't offer this feature...)
