### ISSUE TITLE
Sqllab query results remaining the same for every user login

### ISSUE THREAD

**Issue by MANUVILAKUNNATHU** [apache/incubator-superset#4312]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

20.4

### Expected results
The results must not be there.

### Actual results
The query results will be remains for the new user even if the user did not have the permission for the selected database.

### Steps to reproduce
1.Login to superset.
 2.Run a query in sqllab.
 3.Logout.
 4.Login to superset as another user.
The query results will be remains for the new user even if the user did not have the permission for the selected database.

**Comment by xrmx** [comment]
Please reproduce with latest stable, 0.20.4 is old.

**Comment by MANUVILAKUNNATHU** [comment]
Tried with version 22.1.Issue still remains.

**Comment by mistercrunch** [comment]
This is due to the fact that we use localstorage to store the application state of SQL Lab. We should probably attach it to the session somehow and make sure one user cannot access another user's localstorage.

**Comment by MANUVILAKUNNATHU** [comment]
I need to clear the query results each time a new user login. what code changes should I do for it.

**Comment by andrewsali** [comment]
Adding a removal of the local storage with the logout button might solve the issue when the user explicitly clicks the logout button?

`<a href="{{appbuilder.get_url_for_logout}}" onclick="localStorage.removeItem('redux');">`

https://github.com/apache/incubator-superset/blob/0511d1f38d99d98bcc0d179e0578d20f4d4c2985/superset/templates/appbuilder/navbar_right.html#L42

**Comment by MANUVILAKUNNATHU** [comment]
@andrewsali  sorry for the late comment and finally its working for me.. thanks for the suggestion
