### ISSUE TITLE
Dashboard with multiple database 

### ISSUE THREAD

**Issue by sanoopmm** [apache/incubator-superset#4318]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
20.4

### Expected results
Can I add two slices to dashboard with different data source and table. I need to filter the data of one slice with another(filter box) . Is this possible If the field name and data is same in both the slices. 

### Actual results
Once I try to add two different slices with different database and table and try to filter one slice data with another filter slice. But the filtering not worked. 

### Steps to reproduce

1. Create new database as db1
2. Create another database db2
3. Create a new table tbl1 with db1
4. Create new table tbl2 with db2
5. Add new slice slice1 with tbl1 and visualization types as table view
6. Add new slice slice2 with tbl2  and visualization types as filter box
7. There must be a common field for both the tables
8. Add the common filed as filter control in slice2
9. Create a new dashboard with the two slices
10. Then try to filter the data in slice1 with the common filed using slice2 filter.
11. The filtering not worked even if the data is same for the field.

**Comment by mistercrunch** [comment]
Is the field set as "Filterable" in the table editor for both tables?

**Comment by sanoopmm** [comment]
Thank you for the suggestion. The feature correctly worked.
