### ISSUE TITLE
How do I setup superset on google app engine

### ISSUE THREAD

**Issue by jeffrey-d-lipkowitz** [apache/incubator-superset#4320]
Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Any

### Expected results
Setup app engine on google engine

**Comment by xrmx** [comment]
Like other python applications?

**Comment by jeffrey-d-lipkowitz** [comment]
can you please open it up. It's still a real quetion.

**Comment by feroult** [comment]
@jeffrey-d-lipkowitz I had the same wish... And I ended up creating a guide on how to deploy Superset to App Engine.

https://medium.com/@feroult/serverless-superset-on-google-cloud-87d3cf324845
