### ISSUE TITLE
Hive queries run at least 5 * some_number seconds 

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#4323]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
Queries on hive should get results as fast as they can

### Actual results
Queries on hive are getting results every 5 seconds.

### Steps to reproduce

Read the source code:
https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py#L951

**Comment by mistercrunch** [comment]
5 seconds seems like a pretty reasonable amount of time for polling against a Hive query. If you want to make it a configuration setting and set it to some other value in your environment, I'll happily  approve the PR.

**Comment by maver1ck** [comment]
Here you are.
https://github.com/apache/incubator-superset/pull/4353

**Comment by maver1ck** [comment]
Closing as PR is merged
