### ISSUE TITLE
Cannot create a visualisation given a nested query

### ISSUE THREAD

**Issue by javiesm8** [apache/incubator-superset#4324]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
View this output as a big number visualisation. 
<img width="570" alt="issue" src="https://user-images.githubusercontent.com/30013839/35709652-3eafc9f2-07ff-11e8-915c-0f0ea648981b.png">

### Actual results
I am attempting to create a single count column that is the aggregate of a unique and non unique column, and then aggregate the new count column to give an average. 

I am unable to transfer this to a visualisation. I am unable to create a new table on superset either. I am assuming this is because of a timeout limit - I have only been able to see a pending swirl.

Is there a way around this?

**Comment by xrmx** [comment]
A bit puzzled by the fact you are posting a picture with the query executed :)

**Comment by javiesm8** [comment]
Hi @xrmx if you can elaborate on what aspect of the fact, then I would be happy to explain. I assumed as much information as possible would help others help me.

**Comment by rumbin** [comment]
I understand @javiesm8 in trying to visualize the result of this SQLLab query as a Big Number slice.

While the query works for SQLLab, the transfer to Visualize is failing somehow.

**Comment by mistercrunch** [comment]
Stack trace / error msg / which database engine was used would help.

**Comment by javiesm8** [comment]
Firstly there is no option to create as a big number visual. When I click visualise, I get a syntax error. The think the issue is I can't query on a view or table that doesn't exist, which is represented by the subquery. I am wondering if this is just not a feature of apache superset, or if someone has encountered this issue and knows how to get around it. 

I'm using Athena (so built on Presto). 

Error Msg
(pyathenajdbc.error.DatabaseError) java.sql.SQLException: SYNTAX_ERROR: line 1:12: Column 'Pages per User per Day' cannot be resolved

**Comment by mistercrunch** [comment]
Seems like a bug related to using spaces in column names, it could have to do with the dialect. The easy workaround would be to go use `_` instead os spaces.

**Comment by javiesm8** [comment]
That doesn't work I'm afraid. IMO it cannot be resolved because the data point only exists within the subquery. I can't create a table of the subquery in superset as it times out, nor can I create a metric for a column that cannot exist without being grouped by two data points. So unfortunately I think the only way to fix this is to shift the DB off athena and create a table or view on the backend and query that.

**Comment by villebro** [comment]
Can you post the contents of "View Query" on the explore page where you are getting the error message? This should help in understanding what's going wrong. I assume it has something to do with the the original query being wrapped in the expr_qry subquery.
