### ISSUE TITLE
Filter box doesnot applies to mapbox

### ISSUE THREAD

**Issue by AnithaMurugesan** [apache/incubator-superset#4328]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Expected results
Filtering should applies to mapbox. So that particular state is zoomed when selecting it from filterbox.

### Actual results
Does filter box can be applied to mapbox??
Or is there any configuration/procedure that I am missing??

Thanks in Advance.

**Comment by mistercrunch** [comment]
The columns need to be checked as "Filtereable" in the table editor.

**Comment by AnithaMurugesan** [comment]
Thanks...Working fine
