### ISSUE TITLE
Simple, automatic install option(s)

### ISSUE THREAD

**Issue by brylie** [apache/incubator-superset#4331]
Currently, the [Superset installation instructions](https://superset.incubator.apache.org/installation.html) are several pages long, including many manual steps. This may be reasonable for people with a background in managing systems, but is likely to discourage adoption by a wider audience. Taking examples from other projects other projects, such as Re:dash, it would be worthwhile to provide one or more 'automated' installation packages, such as:

- Docker image
- Helm chart
- AWS installation script
- Linux package (deb, rpm, etc.)

**Comment by mistercrunch** [comment]
If people in the community can share and maintain those it would be great. It's already a considerable amount of work to handle the PyPI and eventually the Apache releases.

**Comment by brylie** [comment]
As those installation options were examples, what about settling on a single one? I.e. the goal would be for someone to be able to install Superset with a single command. To that end, I propose we consider a Docker Compose image (which can also be converted for Kubernetes).

**Comment by brylie** [comment]
> If people in the community can share and maintain those it would be great.

Taking note of the [Re:dash Docker image](https://hub.docker.com/r/redash/redash/), it looks like they update the installers as part of a CI build.

**Comment by cychiang** [comment]
Hi, 
Currently, I am promoting superset to our company. As a result, I have sent a PR #4923 that contains helm chart to help people install superset into their Kubernetes with helm. This is a simple version of helm chart, and I am working on it to make it suitable for production work.
