### ISSUE TITLE
Filter Box: "No Data" although filterbox slice and time series slice in dashboard have same source

### ISSUE THREAD

**Issue by FloPit** [apache/incubator-superset#4332]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"version": "0.21.1", "GIT_SHA": ""}

### Expected results
Data is displayed in the time series line chart slice.

### Actual results
Time series line chart slice says "No data".

### Steps to reproduce
1. use a table X as data source (in my case, maria DB is underlying DB, and a View from Maria DB is used)
2. create a filter box slice (column "machine_name" for sorting), based on that data source
3. create a time series line chart slice (this has no filter, displays data in preview), based on that data source
4. Use both the filter box slice (from 2) and the time series line chart slice (from 3) in a dashboard
5. Open dashboard, choose one machine_name (or more) from the filter box slice
6. In the dashboard in the time series line chart, it says "No data."

The count(*) indicates that there are some records for specific machine_name selected!

**Comment by xrmx** [comment]
Friendly reminder to always reproduce with latest release which unfortunately 0.21.1 is not.

**Comment by FloPit** [comment]
Hi,
Update: with 0.22.1, it is now working!
