### ISSUE TITLE
Week granularity accumulates values over a week

### ISSUE THREAD

**Issue by aabdin01** [apache/incubator-superset#4342]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
When time granularity is changed to week, I should only see values of the last processed date from that week. Same with month, and year. For example:
 
D1: 5 issues, D2: 5 issues, D3: 7 issues, D4: 5 issues, D5: 6 issues, D6: 9 issues. 

When time granularity is Day then all 6 days are shown, but when time granularity is changed to week, I should only see D6: 9 issues since it is the last run of the week. 

### Actual results
I get the sum of all the issues in the week or month. For the example above, I am getting 37 issues because of D1 + D2 + D3 + D4 + D5 + D6.

**Comment by rumbin** [comment]
This is exactly what it is supposed to do. The aggregation method, however, depends on the metric you chose. In this case it seems that a sum metric was selected.

If you just want to have one day per week and ignore the other 6 days, you may succeed by choosing daily time grain, but apply weekly resampling in the Advanced Analytics section. 

Another way would be to implement a filter on a specific weekday in your SQL metric...

**Comment by mistercrunch** [comment]
Yes. That's the expected behavior. Go for a WHERE clause like `DAYOFWEEK(datetime_column) = 1` or something like that, depending on the date function on the database you use
