### ISSUE TITLE
[Druid] Explore view throws error when group by is applied

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4347]
Chart: Line/Time series
Datasource: Druid

Unsure what is going on--cryptic error is thrown when I try visualizing the dataset as a line chart with a group by on a single dimension. Works fine on the non-Druid datasource
<img width="1468" alt="screen shot 2018-02-05 at 9 58 56 pm" src="https://user-images.githubusercontent.com/33429480/35843994-fa257098-0abf-11e8-8a69-0ca802410100.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Should be fixed in master
