### ISSUE TITLE
Newly created datasource should be accessible be creator

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#4352]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
When user without all datasource access is creating datasource (using visualize button in SQL Lab) the datasource should be accessible to this user.

### Actual results
```
This endpoint requires the datasource test-hadoop-Untitled Query 2-HJG51B-DUf, database or `all_datasource_access` permission
You do not have permissions to access the datasource(s): test-hadoop-Untitled Query 2-HJG51B-DUf.
```

### Steps to reproduce

1) Create user with Gamma and sql_lab roles
2) Run query in SQL Lab
3) Click Visualize button then Visualize
4) Watch No Access! page

**Comment by maver1ck** [comment]
I don't really know how to fix this bug. I see two options.
1) Datasources are always accessible by owner (using check_ownership)
But this makes a lot of changes in code
2) We're creating one special role per user for situations like that.

What do you think ?

**Comment by timifasubaa** [comment]
see https://github.com/apache/incubator-superset/issues/2798

**Comment by maver1ck** [comment]
Thank for pointing that.
I think we have really mess with permission and I don't know how this should work.

**Comment by timifasubaa** [comment]
I tried replicating this error as I'm currently doing some permissions cleanup but I was unable to run queries despite having sql_lab permissions. 

how were you able to run the query?

**Comment by qin4zhang** [comment]
How to solve it? Help, please.

**Comment by mistercrunch** [comment]
@timifasubaa you need to have `Gamma` + `SQL Lab` + some sort of database, schema, or table permission
