### ISSUE TITLE
Filtering extractionFunction-custom extension

### ISSUE THREAD

**Issue by chirpy2291** [apache/incubator-superset#4357]
Unable to  filter custom extensions created through dimension specs in superset.
I am able to filter them through Result Filters only.

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.21

### Expected results

should be able to filter through Filters

### Actual results

No effect with filters.

### Steps to reproduce

create a dimension with dimension spec of extractionFn:

For ex:
{
      "type" : "extraction",
      "dimension": "oldDimension",
      "outputName": "newDimension",
      "outputType": "STRING",
      "extractionFn": {
        "type": "javascript",
        "function": "function(value) { return value.split('-', 1)[0]; }"
      }
    }

And try to filter the same after grouping it.We can only filter via Result Filters.Please provide a fix.

**Comment by xrmx** [comment]
Please reproduce with latest version

**Comment by ghulands** [comment]
@chirpy2291 cherry pick #4740 for this.
