### ISSUE TITLE
Add filters to dashboard in single slice without filter box view - interactive filters

### ISSUE THREAD

**Issue by sanoopmm** [apache/incubator-superset#4366]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

20.4

### Expected results
Can I add filters to dashboard without filter box. That is I need filter the the values in a dashboard by add the filters from slice. I need interactive filters to dashboard.

### Actual results

Now we can only filter values using a separate filter box view

**Comment by raffas** [comment]
If you use a Table View, you can make it filterable.

If you click on a row, the other slices will be filtered using this value for the property associated for the cell you have selected.

Otherwise, explain better the expected behaviour.

**Comment by sanoopmm** [comment]
I need to add  filter drop downs in the existing visualizations like table view, bar chart, pie chart etc.
Now it is possible only through an additional slice that is filter box. Also I need to get these filter drop downs from different tables and databases. I mean that I want to use multiple tables from different databases in a single slice.

**Comment by claycrosby** [comment]
+1 would like to embed filters within individual slices

**Comment by LanDeQuHuXi** [comment]
+1

**Comment by claycrosby** [comment]
Is there a design document that explains this feature in more detail?

**Comment by mistercrunch** [comment]
@graceguo-supercat and @williaster are working on a branch with the new drag&drop dashboard editor. I'm not sure whether they've documented their approach to dashboard-native filters
