### ISSUE TITLE
Two user profile pages - let's make it one

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#4370]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
I'd like to have:
- one user profile page
- welcome page when clicking on Superset logo

### Actual results
There is two profile pages:
1) when clicking on superset logo:
/superset/profile/admin/
2) when clicking on user icon / profile
/users/userinfo/

What's the recommendation ?

**Comment by SpyderRivera** [comment]
I would say the `/users/userinfo/` page should be linked to on `/superset/profile/admin/` as a tab. Similar to the recent activity and security & access.

**Comment by mistercrunch** [comment]
`/users/userinfo/` is the page we get out of the web framework we use. It'd be hard to customize, the vision is to improve the other profile page, we should probably make it the welcome page as well.

**Comment by maver1ck** [comment]
So idea is to merge information from /superset/profile/admin/ to /welcome ?

**Comment by SpyderRivera** [comment]
@mistercrunch Maybe then not use `/users/userinfo` and put that information on the other page ignoring `/users/userinfo` altogether..?
