### ISSUE TITLE
Landing Page for Superset

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4376]
Improve usability and discovery by re-organizing landing page for when users land on Superset. With the current layout, it's hard to find what data to start exploring

(1) Too many menus at the top - collapse administrative menus into "Manage" section
(2) Make  "Search" box global
(3) Default to a "Recently Viewed" tab that has all types of data artifacts
(4) Card view with sample images of dashboard, chart, etc.

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Related: https://github.com/apache/incubator-superset/pull/4381

**Comment by maver1ck** [comment]
I think also related.
https://github.com/apache/incubator-superset/issues/4370

**Comment by hughhhh** [comment]
@vylc So i started on the new welcome page, but had some questions for you before I continue.
1) What data do you want to be shown under the `datasource` and `queries` tabs? 
- I'm assuming all datasources available to the user, and queries would be all the user's saved queries from sqllab.

Here's what I have now with some boilerplate. Also need to cleanup the recently viewed to match dashboards this is good op in creating a base class for all new views to follow.

![superset_new_welcome](https://user-images.githubusercontent.com/27827808/36363917-d82638d4-14f5-11e8-8a6f-40cc69ff3a3b.gif)

**Comment by hughhhh** [comment]
@mistercrunch @timifasubaa ^^^

**Comment by mistercrunch** [comment]
I'd go with something very much like the profile page without the left pane.

The profile page has tabs for Favorites, Created Content, Recent Activity, & Security / Access. Maybe removing `Security / Access` and  adding `Popular Dashboards` or something like that.

**Comment by vylc** [comment]
Yes on datasources - any available to user
For queries, i'd list in order of recently run queries - doesn't have to be saved. i'd limit it to about 30 or so...
in general, we don't need an exhaustive list for the landing page. in fact, too much information clutters the view. 
any way you can get the card style in? or are we stuck with the CRUD view?

**Comment by hughhhh** [comment]
@vylc "any way you can get the card style in?" 
- Are you talking about your mocks? I can definitely put them :)
