### ISSUE TITLE
[Histogram] Add default to row limit

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4378]
Add a default to the row limit. When viz is loaded up, error is thrown, this is fixed when a row limit is enforced.
Datasource used was Druid
<img width="1574" alt="screen shot 2018-02-07 at 4 50 31 pm" src="https://user-images.githubusercontent.com/33429480/35949614-4eeef564-0c27-11e8-9954-562289def2b0.png">

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
fixed by https://github.com/apache/incubator-superset/pull/4372
