### ISSUE TITLE
Chart stickiness - saved state

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4379]
Persist visualization settings during save.
Use case: User goes and plays around with chart, and gets to a point where they have enabled 2-3 series on the chart via clicking the legend. When they click save, the expectation is that the exact view that user has customized will be persisted, such that when they share this view, everything is intact.

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
I agree it'd be nice to save the state of the legend filters in the nvd3 charts specifically.

**Comment by betodealmeida** [comment]
I can take this.

**Comment by mistercrunch** [comment]
@betodealmeida thinking about this, maybe the slice object that's available in the visualization exposes a `setExtraState` method and an `extraState` object as the generic api for this feature. Somehow this `extraState` would need to make it into the `formData` object.

Another option would be to use individual `HiddenControl`s and use `setControlValue`.

**Comment by betodealmeida** [comment]
@mistercrunch, I was planning to do this in 2-steps. I noticed that the ⚡ controls that trigger the render on change (with `renderTrigger = true`) do not persist their state in the URL, ie, the `form_data` parameter is not updated on the fly, only with a new query.

I thought of first fixing that first, and then make changes to the nvd3 legend so that is also updates the URL. This way the share button should be able to include the legend state, right?

**Comment by mistercrunch** [comment]
Yes lets fix the URL state getting out of sync. 

For the state to be saved in the slice it needs to make its way in the form data. As you know form data is a collection of control values. So either you add hidden controls or we add a new generic state key in form data.

The url is built from the form form data of the slice.

**Comment by betodealmeida** [comment]
https://github.com/apache/incubator-superset/pull/4449 sets the foundation.
