### ISSUE TITLE
Time filter - remove infinity for end date

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4387]
Default infinity to now for time filter end date. Also, time shift does not work when end date is infinity

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by betodealmeida** [comment]
@vylc, I can't repro this — @mistercrunch, do you know if this was changed recently?
