### ISSUE TITLE
Bypassing the login for Supreset using iframe 

### ISSUE THREAD

**Issue by goldymanikoth** [apache/incubator-superset#4393]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I am using Superset version 0.22.1. I create a slice and use its iframe to embed into my webpage. When I do so, it directs me to superset login on the webpage. Is there a way I can pass the username and credentials using iframe as a parameter if yes please let me know the iframe parameter name for that?

### Superset version
0.22.1

### Expected results
bypass authentication

### Actual results
asking for authentication

**Comment by hughhhh** [comment]
I think you might need to leverage the Public role to allow others to see this dashboard without logging in. Checkout this doc http://superset.apache.org/security.html#public for more information.

**Comment by goldymanikoth** [comment]
thanks for your response , I could see from the documentation 
http://superset.apache.org/security.html#public

"Public- It’s possible to allow logged out users to access some Superset features.By setting PUBLIC_ROLE_LIKE_GAMMA = True in your superset_config.py"

so my next set of doubts -- 
1) where is this superset_config.py location ? can i create this file and add this to export PYTHONPATH="/home/user/superset/:$PYTHONPATH" ... please help 
2)also struggling to find the super set installation location ?

**Comment by mistercrunch** [comment]
`pip/setuptools/python` manages your pypi packages, no need to worry about that. `superset_config.py` can live anywhere, but you need to `export PYTHONPATH=/wherever/your/superset_config/lives`. As you fire up the `superset` command, you should see something like:
`Loaded your LOCAL configuration at [/wherever/your/superset_config/lives/superset_config.pyc]`

**Comment by goldymanikoth** [comment]
I got some reference to locate the superset install path and I figure out the location and updated the superset/config.py  and edited the "PUBLIC_ROLE_LIKE_GAMMA = True" and add the data sources to the role manually to bypass the user login, it is working now , thanks for the support.

**Comment by mistercrunch** [comment]
You probably want to avoid changing `superset/config.py` (which means you're modifying the Superset package) and use `superset_config.py` which is intended to be the way to override the defaults in the configuration.

**Comment by goldymanikoth** [comment]
got it, I will do that. Thanks

**Comment by girishteja** [comment]
Hi @goldymanikoth  and @mistercrunch , I have been into the same issue i modified  "PUBLIC_ROLE_LIKE_GAMMA = True" in both superset/config.py and superset_config.py . Added the datasource to PUBLIC as per the link suggested.But still getting the AUTH login page while accessing th iframe .Can anyone explain me in more detail please

**Comment by mistercrunch** [comment]
did you run `superset init` ? `Public` should then be like Gamma, to which you can start adding tables / databases

**Comment by girishteja** [comment]
@mistercrunch You mean to say ,should run superset init before adding the role PUBLIC .Can you please ellaborate as i am new to superset and needed to achieve it badly

**Comment by girishteja** [comment]
Thank you so much @mistercrunch , superset init command did the magic we want!I could able to access the chart without authentication prompt now.

**Comment by raoofnaushad** [comment]
I am facing the same issue. But in my case Superset is installed via HDP. I am not able to find the superset location (config.py). And I am not sure where is it.? Help is very much appreciated.

**Comment by falgunifb** [comment]
can anyone please tell how to fetch value of guest token in superset_config.py file ...as in url am passing token and that token need to verify in config file so it bypass the login screen of superset for user.
http:/localhost.com:8080/login?token=1234&next=/superset/dashboard/11?standalone=true

Thanks in advance!!!!!!

**Comment by krishanthvs** [comment]
@falgunifb were you able to resolve this issue

**Comment by 4ahul** [comment]
why no one is talking about login by-pass? 
i want to embedd superset in my application ( not onlydashboard ) , and use the superset as it works normally in my website ,but it asks for login and all , how can this be resolved ?

**Comment by 4ahul** [comment]
> can anyone please tell how to fetch value of guest token in superset_config.py file ...as in url am passing token and that token need to verify in config file so it bypass the login screen of superset for user. http:/localhost.com:8080/login?token=1234&next=/superset/dashboard/11?standalone=true
> 
> Thanks in advance!!!!!!

 CODE : 

``

`class TokenManager:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(TokenManager, cls).__new__(cls)
            cls._instance.auth_token = None
            cls._instance.csrf_token = None
        return cls._instance

    def set_auth_token(self, token):
        self.auth_token = token
    
    def get_auth_token(self):
        return self.auth_token
    
    def set_csrf_token(self, token):
        self.csrf_token = token

    def get_csrf_token(self):
        return self.csrf_token

token_manager = TokenManager()`

`@csrf_exempt 
def getGuestToken(request):

    headers = {
        "Authorization":f"Bearer {token_manager.get_auth_token()}",
    }

    try:
        body = json.loads(request.body)
        GuestTokenPayload = getGuestTokenRequest(**body)

        api_instance = API()

        try:
            response = api_instance.post(request,endpoint=GUEST_TOKEN, headers=headers, body=asdict(GuestTokenPayload))
            return response
        
        except requests.RequestException as e:
            return Response({"error": str(e)}, status = 500)
    
    except requests.RequestException as e:
        return Response({"error": str(e)}, status= 500)
 `


get access token from login response and pass it in header while calling guest token api 


example body for guest token : 

`{
    "resources": [
        {
            "type": "dashboard",
            "id": "c9a79243-1d31-4fe3-afc0-5302b8b7546a"
        }
    ],
    "rls": [],
    "user": {
        "username": "admin",
        "first_name": "admin",
        "last_name": "user"
    }
}`
