### ISSUE TITLE
Edit Table  - need to add the ability to multi select and delete

### ISSUE THREAD

**Issue by darylerwin** [apache/incubator-superset#4402]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
very latest

### Expected results
Requested feature

### Steps to reproduce
Add a new data source / table. Then click edit table. I want to remove a lot of fields in the List Columns. Currently it is a one column per operation command. Really handy if there was a check box then a with selected option to delete them.

Same for List Metrics.

**Comment by xrmx** [comment]
FYI Very latest is not a version, a release number and a git hash are. If you want to open a PR it should be easy to do http://flask-appbuilder.readthedocs.io/en/latest/actions.html

**Comment by darylerwin** [comment]
Sorry 0.22.1 - I realize now that is not the latest - latest I can get with pip install --upgrade
