### ISSUE TITLE
Test case not passing when callbacks are used in DateFilterControl_spec.jsx + a repeated test case

### ISSUE THREAD

**Issue by daphne-jr** [apache/incubator-superset#4403]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.0rc2

### Problem
1. I added callbacks to enable debugging of the tests, but 4 of the test-cases ended up failing. I wonder if anyone would know the reason why or how to fix this?
2. My colleague noticed that this 2 test-cases are identical / repeated.
<img width="538" alt="screen shot 2018-02-12 at 12 04 21 am" src="https://user-images.githubusercontent.com/35248123/36075829-fb3a4888-0f4b-11e8-85b2-532067f76bda.png">

### Expected results
<img width="243" alt="screen shot 2018-02-12 at 12 49 36 am" src="https://user-images.githubusercontent.com/35248123/36075795-951b8f9e-0f4b-11e8-8123-efa353a5c6f4.png">

### Actual results
<img width="378" alt="screen shot 2018-02-12 at 12 46 49 am" src="https://user-images.githubusercontent.com/35248123/36075766-5233a77a-0f4b-11e8-88b3-055049a8b536.png">

### Steps to reproduce
For 1., added callback to all the test-cases.

Example:

```
  it('test something', () => {

    const label = wrapper.find('.now').first();

    label.simulate('click');

    setTimeout(() => {

      expect(wrapper.state().free).to.equal('now');

      expect(wrapper.find('.popover')).to.have.length(0);

    }, 10);

  });
```

to

```
  it('test something', (done) => {

    const label = wrapper.find('.now').first();

    label.simulate('click');

    setTimeout(() => {

      expect(wrapper.state().free).to.equal('now');

      expect(wrapper.find('.popover')).to.have.length(0);

      done();

    }, 10);

  });
```

### References
- https://stackoverflow.com/questions/32730169/how-can-i-use-settimeout-functions-within-mocha-test-cases/32733040#32733040

Thank You!

**Comment by daphne-jr** [comment]
After trying for some time today, this is my crude solution. Hope it helps someone and perhaps someone else would have a better solution.
```
import React from 'react';
import sinon from 'sinon';
import { expect } from 'chai';
import { describe, it, beforeEach } from 'mocha';
import { mount } from 'enzyme';

import DateFilterControl from '../../../../javascripts/explore/components/controls/DateFilterControl';
import ControlHeader from '../../../../javascripts/explore/components/ControlHeader';

const defaultProps = {
  animation: false,
  name: 'date',
  onChange: sinon.spy(),
  value: '90 days ago',
  label: 'date',
};

describe('DateFilterControl', () => {
  let wrapper;

  beforeEach(() => {
    wrapper = mount(<DateFilterControl {...defaultProps} />);
  });

  afterEach(() => {
    wrapper.unmount();
  })

  it('renders a ControlHeader', () => {
    const controlHeader = wrapper.find(ControlHeader);
    expect(controlHeader).to.have.lengthOf(1);
  });

  it('renders 3 Buttons', () => {
    const label = wrapper.find(OverlayTrigger).first();
    label.simulate('click');
    expect(document.getElementsByTagName("Button").length).to.be.equal(3);
  });

  it('loads the right state', () => {
    const label = wrapper.find('.label').first();
    label.simulate('click');
    expect(wrapper.state().num).to.equal('90');
  });

  it('renders 2 dimmed sections', () => {
    const label = wrapper.find('.label').first();
    expect(document.getElementsByClassName('PopoverSection dimmed').length).to.be.equal(0);
    label.simulate('click');
    expect(document.getElementsByClassName('PopoverSection dimmed').length).to.be.equal(2);
  });

  it('opens and closes', (done) => {
    const label = wrapper.find('.label').first();
    label.simulate('click');
    expect(document.getElementsByClassName('popover').length).to.be.equal(1);
    document.getElementsByClassName('ok')[0].click();
    setTimeout(() => {
      expect(document.getElementsByClassName('popover').length).to.be.equal(0);
      done();
    }, 10);
  });

});
```

**Comment by xiaohanyu** [comment]
+1, confirmed with the bugs in a47a51280, code inside `setTimeout()` are not running during test, need a fast fix.
