### ISSUE TITLE
Need to use more than table in a slice and able to make List of values(LOVs) for filtering   

### ISSUE THREAD

**Issue by sanoopmm** [apache/incubator-superset#4406]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results

We are trying to create slice with one table and we need a list of values from different table in the slice. Also we are trying to to add filters into a slice without filter box visualization. 

### Actual results

Now we can use only one table for a slice. Each field will come from that table. Not able to add a field from a different table.
Please Note:- We are able to achieve this by creating entirely different slice(filter box) and dashboard doing an in memory filter.

**Comment by rumbin** [comment]
Assuming that the second table resides within the same DB, you have at least three options:

* create a view in the source DB where the second table is joined in
* do virtually the same thing via visualizing an SQLLab query where you perform the join
* define a new column for the first table that is defined by a correlated subquery on the second column

When the second table is from a different DB, I don't see any options other than integrating the two DBs via external tools like dremio.com.

**Comment by sanoopmm** [comment]
How can I introduce this multiple DB feature? Any possible ways ? If I try to make some code changes, Does it works and which files are related to this ? Also please help me to introduce this feature with minimum code change.

**Comment by rumbin** [comment]
As said, I'd consider dremio.com. however. I am not sure about how well dremio can be accessedbin superset via the odbc connector of dremio.

Alternatively, you could use a PostgreSQL DB in combination with Foreign Data Wrappers (FDW) which connect to the various DBs to be integrated.

The latter approach definitely does not require any code change in sqlalchemy or superset, but requires the FDWs for your DBs to be available.

The former one is more generalized, but I cannot tell you if superset and/or sqlalchemy do need any adjustments for it to work.
