### ISSUE TITLE
Feature request: please add Y min to Dual Axis chart type

### ISSUE THREAD

**Issue by kahernandez** [apache/incubator-superset#4415]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 
0.19.1

### Expected results 
I'd like to be able to set Y min = 0 (or other value) for one or both Ys on the Dual Axis chart

### Actual results 
Currently, I can only set Y min on Time Series- Line Chart

### Steps to reproduce 
Create slice with Dual Axis chart type- you will see no option to set Y min for either Y 

Thank you!

**Comment by xrmx** [comment]
Please reproduce with latest superset version.
