### ISSUE TITLE
[Explore] Stop button for queries doesn't work?

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4417]
Stop button functionality, when pressed:
(1) Cancel query on DB side
(2) Reset explore view to state before query was run
(3) Currently, when query is running, user is allowed to modify selections on left hand nav
(a) When stop button is depressed, should stop current query and persist these selections
(b) Could also not allow user to change selections when query is being run (ie. grey out selectors)
I think a is preferable, but both are acceptable.

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
fixed here:
https://github.com/apache/incubator-superset/pull/4301

**Comment by graceguo-supercat** [comment]
#4301 only stop query in front-end, the query is still running in DB side (but browser won't wait for response). It will be good feature to stop query on DB side.

**Comment by dpnsh** [comment]
@vylc were you able to solve this issue ?

**Comment by saurabh3091** [comment]
@dpnsh I figured the issue. You can fix this issue by adding 
`session.refresh(query)`
inside this while loop. I will create a PR for that in superset.
https://github.com/apache/superset/blob/398a01f7dc0579599b927ffa1af545bff1e5d2ba/superset/db_engine_specs/hive.py#L335
