### ISSUE TITLE
Unclear on how to migrate metadata across Superset versions

### ISSUE THREAD

**Issue by ahsanshah** [apache/incubator-superset#4419]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

Hi All,

I am a bit confused on how you can "migrate" metadata (dashboards, reports, UI content) from one version of Superset to another?  I tried the following:

1.  Upgrading the superset db upgrade on a v19.0 version of superset and copy the file to a v22 version.
2.  Tried the Import/Export feature...ERRORs out on a pickle error even though my data source was properly defined.

So my questions are:

1. How do we migrate content across versions?  We currently use Docker images so this is very relevant that we can do a clean build versus an in-place upgrade.  As our content grows we cannot "redo" everything and we certainly want to be agile in using newer releases.

2.  Would moving from sqllite to mySQL make this more standard as a "central" metadata store?  How do upgrades work if we do this?  We plan to move to mySQL eventually but want to confirm.

Any thoughts here are appreciated.

**Comment by mistercrunch** [comment]
https://superset.incubator.apache.org/installation.html#upgrading

I would not recommend using sqlite in a production environment. Use mysql or postgres.

There's no easy way to migrate dashboards / charts outside of the Import/Export feature, which is limited and depends on you managing / migrating your databases manually.

**Comment by ahsanshah** [comment]
Got it.  Thanks.
