### ISSUE TITLE
Pivot table - ability to specify row limit

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#4423]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
When defining "pivot table" slice it should be possible to configure row limit

### Actual results
Currently row limit in query is hardcoded (or maybe taken from ROW_LIMIT superset configuration):

`  "limitSpec": {
    "limit": 5000, 
    "type": "default"
  },`

It is very unexpected as row limit is not configurable but result is limited to that number

**Comment by yamyamyuo** [comment]
same here

**Comment by mistercrunch** [comment]
This is fixed in more recent versions
