### ISSUE TITLE
Error on compiles the production / optimized js & css with npm run prod

### ISSUE THREAD

**Issue by XavierDeLapeyre** [apache/incubator-superset#4425]
### Superset version
{"GIT_SHA": "", "version": "0.21.1"}

Background info : 
SuperSet v0.21.1
Setup in a VirtEnv
I modified VirtEnv/lib/python2.7/site-packages/superset/static/assets/visualizations/nvd3_vis.js

But the modifications did not show up on the browser.
After researching a bit, found that I needed to recompile the ../assets/build

Found the command line in https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#npm-packages
# Compiles the production / optimized js & css
npm run prod

after running that commande I got this error : 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle superset@0.21.1~preprod: superset@0.21.1
6 silly lifecycle superset@0.21.1~preprod: no script for preprod, continuing
7 info lifecycle superset@0.21.1~prod: superset@0.21.1
8 verbose lifecycle superset@0.21.1~prod: unsafe-perm in lifecycle true
9 verbose lifecycle superset@0.21.1~prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/xxxx/xxxx/xxxx/lib/python2.7/site-packages/superset/static/assets/node_modules/.bin:/usr/bin:/var/www/xxxx/xxxx/xxxx/bin:/usr/local/bin:/usr/bin:/bin:/usr/games
10 verbose lifecycle superset@0.21.1~prod: CWD: /var/www/xxxx/xxxx/xxxx/lib/python2.7/site-packages/superset/static/assets
11 silly lifecycle superset@0.21.1~prod: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress' ]
12 silly lifecycle superset@0.21.1~prod: Returned: code: 1  signal: null
13 info lifecycle superset@0.21.1~prod: Failed to exec prod script
14 verbose stack Error: superset@0.21.1 prod: `NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid superset@0.21.1
16 verbose cwd /var/www/xxxx/xxxx/xxxx/lib/python2.7/site-packages/superset/static/assets
17 error Linux 3.2.0-4-amd64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prod"
19 error node v5.12.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error superset@0.21.1 prod: `NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress`
22 error Exit status 1
23 error Failed at the superset@0.21.1 prod script 'NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the superset package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs superset
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls superset
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

The cmd :  npm bugs superset
gave me this info 

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "superset"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by xrmx** [comment]
Please report bugs against latest release and not old ones.

**Comment by XavierDeLapeyre** [comment]
Hi @xrmx ,
I'm not reporting a bug,
I'm asking for some hints on how to debug this gibberish.
What is wrong here?

**Comment by mistercrunch** [comment]
Your node and npm versions are ancient. Upgrading should fix things.
