### ISSUE TITLE
[TimeSeries-BarChart] x axis dates are not visible

### ISSUE THREAD

**Issue by SpyderRivera** [apache/incubator-superset#4429]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
23 rc2
08b88fd4d2eb5ef065a55cb75b9f67875ad4bea1

### Expected results
TimeSeries BarChart with visible dates

### Actual results
![screen shot 2018-02-14 at 9 04 32 am](https://user-images.githubusercontent.com/3988262/36215033-2bdd60ce-1168-11e8-8114-d0ea52393aea.png)
![screen shot 2018-02-14 at 8 35 25 am](https://user-images.githubusercontent.com/3988262/36215034-2bef76b0-1168-11e8-845d-b0df6845f0bf.png)

### Steps to reproduce
Create a time series bar chart with a druid data source. Metric doesn't matter.

**Comment by darylerwin** [comment]
There is a chart option "Bottom Margin" that is available to tweak this.. just an FYI.

**Comment by SpyderRivera** [comment]
Bottom margin is available in the latest 👍
