### ISSUE TITLE
Is there any way to run the "apache superset" in high availability environment like if I add a database in one superset instance and it automatically gets added in other instances of superset.

### ISSUE THREAD

**Issue by devJamdagni** [apache/incubator-superset#4453]
Make sure these boxes are checked before submitting your issue - thank you!

- [N/A] I have checked the superset logs for python stacktraces and included it here as text if any
- [N/A] I have reproduced the issue with at least the latest released version of superset
- [N/A] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Data is saved on a database so if is shared between instances, their data is shared too.

**Comment by devJamdagni** [comment]
Hi, Actually i dont want to add database to the other superset instance manually. Is there any configuration like if i add a new database on one instance the same database is automatically added on the other instance. 
For example I have one instance of a superset running on one server and i add a database on it.
I have one other superset on a other server. If i open this second instance i could see the database which i  added in the first server automatically reflecting on the second server.

Hope i made my query understandable

**Comment by xrmx** [comment]
@devJamdagni I was talking about the database used by superset to store the metadata.

**Comment by devJamdagni** [comment]
Ok.. sorry i am new to suerset. Can you please tell me where can i see this database in superset?
