### ISSUE TITLE
How to export CSV data with 200k+ rows

### ISSUE THREAD

**Issue by hnahak87** [apache/incubator-superset#4458]
We've an use case, where query produce 200k+ rows but while exporting query results it only export 10K rows. How can I increase the export row limit?

**Comment by Amarchetan** [comment]
We have a similar requirement - is there a way to increase the export limit?

**Comment by SpyderRivera** [comment]
Have you tried changing your config?
<img width="571" alt="screen shot 2018-04-12 at 12 18 51 pm" src="https://user-images.githubusercontent.com/3988262/38696190-b0e58dcc-3e4b-11e8-922f-a2a703667bb9.png">

**Comment by hajdbo** [comment]
@kristw please close: solution provided, no word from op
