### ISSUE TITLE
[Tooltip] Option to display or ignore 0 or null values

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4462]
Charts with a lot of series (particularly time series), the tooltip gets to be too heavy and overwhelms the chart (ie. blocks entire chart pretty much)
Options:
(1) Allow option to configure tooltip (only with series user is interested in)
(2) Omit 0 or null series for particular time point
(3)
<img width="250" alt="screen shot 2018-02-21 at 4 55 15 pm" src="https://user-images.githubusercontent.com/33429480/36514335-caa48bd6-1728-11e8-8bdc-0cb027f4898b.png">

***Note: this is also an issue when a filter is applied to a query, even though the filter has excluded a bunch of values, the tooltip and the legend still shows these series as a 0 value

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by krishna9626** [comment]
1+

**Comment by akyenze** [comment]
Or if null/nan values have to be included, the labels to be N/A. When 0 is displayed in place of missing data, it conveys a different message.

**Comment by berkbulten** [comment]
+1
