### ISSUE TITLE
Integrate Jupyter model to superset

### ISSUE THREAD

**Issue by vimalgoyal** [apache/incubator-superset#4464]
Hi,

First of all thanks to everyone who is contributing on Apache Superset, a really beautiful data visualization tool with the rich features.

Currently, I am working on a project where I have a situation where I need some guidance.

I have three systems, one has the database, another has jupyter notebook and third has superset.

First, we create the data model in R/Python using jupyter nb. Now we would like to run these data model on the database via superset so that we can visualize the data. And each time when we run the data model on data it should visualize the latest data from the database.

We know that;

1. We can directly connect superset with database and play with data.
2. or can run data model manually at the backend and generate the output data as csv and can visualize the result on the superset.

We can not go with the 1st approach because we have the separate users for both Jupyter and superset. Jupiter user cannot access superset to create the data model, slices, and dashboard. Also, we do not want to expose raw data with superset user and superset user should able to only see the graphs/charts generated from the output of the data models.

We can also not go with 2nd approach because every time when we want to see the latest data, we have to first run data model manually.

So is there any solution to my problem where I can run data models in the background whenever I reload the dashboard and I can see refreshed data.

Any lead/suggestion will be highly appreciated.

Thanks!

**Comment by TryHarder01** [comment]
What if at the end of your model running you INSERT back into your DB the info you'd want visualized?

If I'm not understanding exactly, could you give some idea about what you've visualizing in the notebook.

**Comment by akrabawi** [comment]
Using pandas to_sql() function you can directly sync your df to a database which is connected to superset.

**Comment by tooptoop4** [comment]
reopen

**Comment by petacube** [comment]
this should not be closed. its important feature to have

**Comment by cw1427** [comment]
Have an idea to use jupyter lite as one of superset module like sqllab. But it's hard to integrate them.
