### ISSUE TITLE
Table Filter in Table View is not working

### ISSUE THREAD

**Issue by ChiLunHuang** [apache/incubator-superset#4481]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Expected results

Filter all others visualization types if table view(Table Filter in option was be chosen) click by a user in dashboard.

### Actual results

Nothing happened if list in table view is chosen.

### Steps to reproduce

In version 0.18.2 is working smoothly. But after upgrading to this version, the situation is happened.

**Comment by dattatrey93** [comment]
@ChiLunHuang have you set selected column as groupby in table view property???

**Comment by ChiLunHuang** [comment]
@dattatrey93  thanks for reply. And yes, this table in db only have tow column: uid and description.
Following script is from button View Query
`SELECT uid AS uid,
              description AS description
FROM customers
GROUP BY uid,
         description
ORDER BY COUNT(*) DESC
LIMIT 50000`

and in slice I selected column as groupBy.

![selected column as groupby](https://user-images.githubusercontent.com/18207517/36704993-e0bdb1bc-1b9d-11e8-872c-a4c8831ea669.png)

**Comment by fenlon** [comment]
i have the same problem ....

**Comment by SabarishR** [comment]
where I can enable following option

Make sure these boxes are checked before submitting your issue - thank you!

  I have checked the superset logs for python stacktraces and included it here as text if any
  I have reproduced the issue with at least the latest released version of superset
  I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
The fix in the PR above can be used as a workaround while we fix it in the visualization plugin.
