### ISSUE TITLE
Front End Design

### ISSUE THREAD

**Issue by arshadzohran** [apache/incubator-superset#4483]
Hello

I want to work on web site of Superset, I need to make some changes on the page.
Example: Change the logo, Create new tabs after SQL LABS tab etc.
However I am unable to get the main page where I have to make changes. If anyone can help me on this that would be a great help. Thank you

**Comment by Oeufhp** [comment]
If you want to change logo you have to change it at superset/config.py and change at APP_ICON variable. If you want to add new tab you have to add it in core.py in folder superset/views

**Comment by mistercrunch** [comment]
Read about `Flask-Appbuilder`, it's not that different from Django, and check out our CONTRIBUTING.md file to get instructions as to how to set up a dev envrionment. Good luck!
