### ISSUE TITLE
How can slice not be controlled by filter_box in dashboard?

### ISSUE THREAD

**Issue by sunyongmofang** [apache/incubator-superset#4489]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23

I have some slice that don't want to be controlled by filter_box in dashboard. What should I do?

**Comment by raffas** [comment]
Check 
https://superset.incubator.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

You can use ``filter_immune_slices`` in the dashboard properties.
