### ISSUE TITLE
New feature consideration: use python datashader package

### ISSUE THREAD

**Issue by ariejdl** [apache/incubator-superset#4492]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar
- [x] I have checked the superset logs for python stacktraces and included it here as text if any

### Superset version

0.23

### Feature Request

The impressive [datashader](http://datashader.org/) python package (easier to install with conda) allows real-time visualisation of billions of rows of in memory pandas/numpy data (it uses [numba](https://numba.pydata.org/) JIT-ted optimised rasterisation routines), it's conceivable that it could be integrated with superset since superset nicely manages expensive query operations through celery tasks.

Here's a demonstration video of datashader <https://www.youtube.com/watch?v=6m3CFbKmK_c>

**Comment by xrmx** [comment]
Superset does the visualization part in js on the client so not sure that datashader will fit in the picture.

**Comment by ariejdl** [comment]
If you were to consider it as a new back-end it would work, sending the front-end static renders, it's a big feature I'll admit, but for 2+ years from now you could find it very valuable, it would then compete with mapD https://www.mapd.com/demos/
