### ISSUE TITLE
support cratedb

### ISSUE THREAD

**Issue by cmdares** [apache/incubator-superset#4494]
cratedb is the newsql database for iot data.
make superset support to cratedb.
thanks.

**Comment by on99** [comment]
+1

**Comment by cmdares** [comment]
+1

**Comment by mistercrunch** [comment]
Can one of you with cratedb setup in their env try this and report how whether it works?

**Comment by cmdares** [comment]
+1

**Comment by hajdbo** [comment]
CrateDB works, with the limitations described here: https://github.com/crate/crate-python/issues/307

**Comment by hajdbo** [comment]
@kristw please close: CrateDB is (somewhat) supported.
