### ISSUE TITLE
Table view bar chart does now show negative values

### ISSUE THREAD

**Issue by tanvach** [apache/incubator-superset#4495]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
When choosing table view, the visualization show bar chart for metrics that's proportional to the value being displayed (growing from right to left). The bar chart should also display negative value (maybe from left to right).

### Actual results
The bar chart does not get rendered for negative metrics.

### Steps to reproduce
Visualize any data with negative metrics using table view.

UPDATE: https://github.com/apache/incubator-superset/pull/4570

**Comment by jeffreythewang** [comment]
Since #4570 is now merged, is this issue resolvable?

**Comment by tanvach** [comment]
It's resolved, closing now.
