### ISSUE TITLE
Grouping by day of week

### ISSUE THREAD

**Issue by mcampana** [apache/incubator-superset#4499]
I have a time serie data set related to the occuppancy level of our library (almost two years,
with a granularity of 15 min). I'm  trying to use superset for analyzing the data.
I wonder if it is possible to make a slice chart showing aggregated metrics per day of week?
In particular, I would like to display the typical occupancy level for a week, by averaging the
the data collected during 108 weeks (almost two years).

I have tried to add a new column to my datatable, defining a new column named wday as srtftime('%w',date), and try to group by that column... but with  no success.

date is the timestamp column in my data set, in format YYYYMMDD, which I parsed as %Y%m%d

Any help? Has anyone tried to display something similar?

Best regards

Manuel Alvarez-Campana

**Comment by mistercrunch** [comment]
`srtftime('%w',date)` looks like python to me, you'll have to write a SQL expression specific to your database engine in the column expression, set that column as groupable, and that should work.

**Comment by mcampana** [comment]
Well, I'm using sqlite, which in theory supports strftimehttps://www.sqlite.org/lang_datefunc.htmlEl 28 feb. 2018 19:16, Maxime Beauchemin <notifications@github.com> escribió:srtftime('%w',date) looks like python to me, you'll have to write a SQL expression specific to your database engine in the column expression, set that column as groupable, and that should work.
