### ISSUE TITLE
No columns imported from table from MSSQL-DB 

### ISSUE THREAD

**Issue by sebastianwindeck** [apache/incubator-superset#4501]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Superset 0.22.1

### Expected results

Import of Table with Column, Column_types, Metrics from Database (**MSSQL**)

### Actual results

For some tables of the database the import works properly and all columns are recognized, for others it doesn't work.
Even though the table got recognized and the table is shown as imported, but does not contain any columns/metrics.  

![image](https://user-images.githubusercontent.com/28544726/36787138-4fdea966-1c89-11e8-952a-d704a0708bce.png)

### Steps to reproduce

Python 2.7
MSSQL Database
Import of table with different column_types

**Comment by jcoelho-pt** [comment]
Same problem here, with MySQL Percona database. We had no such problems with standard MySQL database, with the same tables/datasources...

**Comment by mistercrunch** [comment]
That's a SQLAlchemy dialect issue, not a Superset issue. We just call the dialect's `get_columns` method.

**Comment by sebastianwindeck** [comment]
Thanks for the reply. I **checked SQLAlchemy** and and the **driver 'pymssql'** separately and it works.
Rather I checked the same query in the SQLLab and there I got an Error for the tables I could not import properly for the others there is no issues.

![grafik](https://user-images.githubusercontent.com/28544726/36847903-ff73f170-1d5f-11e8-9ddf-374f258adfc2.png)
And the following error msg:
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 14: ordinal not in range(128)

I've checked the issues tagged "unicode"
Is there a fix? 
Would you recommend to switch from Py2 to Py3 like mentioned in #2554 ?

**Comment by jcoelho-pt** [comment]
Hello Sebastian. Were you hable to fix it?

**Comment by sebastianwindeck** [comment]
Hey @jcoelho-pt, the fix for me to solve the Unicode issue was the shipping to superset from Py2 to Py3.

**Comment by jcoelho-pt** [comment]
Thanks @sebastianwindeck!
