### ISSUE TITLE
How to use two filter_box to control two slice, and not to be interfered on the same dashboard?(divide and rule)

### ISSUE THREAD

**Issue by sunyongmofang** [apache/incubator-superset#4502]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22

### explain:

slice_A can be controlled by filter_box_A
slice_B can be controlled by filter_box_B
slice_A can't be controlled by filter_box_B
slice_B can't be controlled by filter_box_A

**Comment by mistercrunch** [comment]
http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

There's work taking place with a much better dashboard app allowing for a notion of "scoped filters".
