### ISSUE TITLE
Improve histogram viz

### ISSUE THREAD

**Issue by ArielStv** [apache/incubator-superset#4512]
_This issue aims to encapsulate issues #3674, #988 (and in a larger sense #989 and PR #3777)._

As it is, the histogram feature doesn't look good with large numbers of bins: the x-ticks, y-ticks, colors and annotations make it unintelligible, and even with a small number of bins, it's not great (in my opinion). It seems to have been an ongoing concern when looking at previous open issues.

I'd like to change that, and take advantage of the opportunity to improve the histogram further.

The thing is, I'm not sure how much the histogram viz is used at the moment. I couldn't find any examples from Superset (or anywhere else) so I'm assuming not much? I'd be interested to know how people are actually using it, since I couldn't find a good use case for it.

If that's the case, we can most likely go on and make changes and improvements on the current histogram feature without worrying too much about breaking stuff for users.
Otherwise, maybe it'd be better to create a new visualization?

I assumed the former for a first pass. I'm going to make 2 pull requests (that I will link below):
- the first one only fixes the basic issues: color, ticks, x-axis label, normalization option, get rid of text on bars
- the second one (based on the first) goes further and is more involved: it allows for multiple histograms in one chart through selecting multiple numeric columns or through a group by (or both). I've also added legends and an opacity option.

**Comment by ArielStv** [comment]
First pull request: #4513 

![superset_pr_screenshot](https://user-images.githubusercontent.com/17909133/36871692-ec0e0222-1d57-11e8-84db-4e0bd3c00d47.png)

**Comment by williaster** [comment]
if you're considering updating the vis a lot, you might consider `@data-ui/histogram` which supports some of the features you've mentioned out of the box (we have some interest in using `@data-ui` for other charts)

**Comment by ArielStv** [comment]
Looks great! I'll look into it

**Comment by ArielStv** [comment]
#4513 being merged, I opened a new pull request: #4525. Let me know what you think!

![screen shot 2018-03-02 at 5 50 51 pm](https://user-images.githubusercontent.com/17909133/36929328-e71b83ec-1e43-11e8-8989-cba756d7ab1b.png)

**Comment by nicholasgcoles** [comment]
@ArielStv I am struggling to find current documentation to implement this graph.

Was it deprecated? Or is there some custom work that needs to be done to use this kind of visualisation?
