### ISSUE TITLE
How to configure superset on Apache http ?

### ISSUE THREAD

**Issue by syzuhdi** [apache/incubator-superset#4516]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23

**Comment by xrmx** [comment]
Like any other flask project, see flask documentation

**Comment by hajdbo** [comment]
This can probably help you: http://flask.pocoo.org/docs/1.0/deploying/mod_wsgi/

@kristw please close
