### ISSUE TITLE
Add Admin Reset Password Capability

### ISSUE THREAD

**Issue by claycrosby** [apache/incubator-superset#4518]
Administrators should be able to reset users' passwords

**Comment by xrmx** [comment]
You should be able to do that from the fabmanager cli.

**Comment by claycrosby** [comment]
OK - administrators should be able to reset users' passwords in Superset's UI

**Comment by xrmx** [comment]
Shouldn't users be able to reset that on their own?

**Comment by claycrosby** [comment]
If a user forgets their password, an admin should be able to reset it via the UI

**Comment by evgenyfadeev** [comment]
Would be great to be able to change user's passwords via the UI. Admins can create users with new passwords via the UI and it would make sense to allow creating a new password as well.

**Comment by mistercrunch** [comment]
The best place for these features would be in Flask App Builder itself, we regularly update our dependencies to use the latest FAB.
