### ISSUE TITLE
Can someone explain Login flow for apache Superset and the files involved

### ISSUE THREAD

**Issue by devJamdagni** [apache/incubator-superset#4529]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Authentication and authorization is implemented by flask app builder.
