### ISSUE TITLE
help!!! has data but no line shown

### ISSUE THREAD

**Issue by tttMelody** [apache/incubator-superset#453]
![image](https://cloud.githubusercontent.com/assets/15643702/15140794/5b8218aa-16cf-11e6-8dc5-fadd3476bf88.png)

has data but no line shown
i tiried every thing...
i tried merge ip and port into one mysql field but still faild
![image](https://cloud.githubusercontent.com/assets/15643702/15141327/28d59744-16d2-11e6-85b2-ddab889ebcad.png)

![image](https://cloud.githubusercontent.com/assets/15643702/15141385/56ce2cec-16d2-11e6-9ea1-cf9868f411e2.png)

![image](https://cloud.githubusercontent.com/assets/15643702/15141388/5b1846c0-16d2-11e6-9d3c-b32b2f9e13e6.png)

![image](https://cloud.githubusercontent.com/assets/15643702/15141399/637ae7aa-16d2-11e6-80c9-7d3698297950.png)

but percent can show...but still has little wrong
![image](https://cloud.githubusercontent.com/assets/15643702/15141401/696abad2-16d2-11e6-8647-80995c2db45d.png)

is it a bug?

**Comment by tttMelody** [comment]
![image](https://cloud.githubusercontent.com/assets/15643702/15141684/d78df118-16d3-11e6-8faa-152208b0c687.png)
the value is the final result,i want display
![image](https://cloud.githubusercontent.com/assets/15643702/15141692/e55fd522-16d3-11e6-8297-e9acfbe5a305.png)
![image](https://cloud.githubusercontent.com/assets/15643702/15141699/eca3750a-16d3-11e6-9ee6-823dfaa3b266.png)

**Comment by mistercrunch** [comment]
Can you click the query button, take that SQL query and run it in your SQL editor? Do you have multiple dates in the results there?

**Comment by mistercrunch** [comment]
Oh maybe the issue is that you use a random time stamp field? Can you try changing the "Time Grain"?

**Comment by tttMelody** [comment]
i can execute the SQL query in my sql editor and it's all right...and i don't think i use a random time stamp field.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 706 days. Feel free to comment and request for this issue to be reopened.
