### ISSUE TITLE
Can't create two tables from differents bases but where same schema / tablename

### ISSUE THREAD

**Issue by asyd** [apache/incubator-superset#4546]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.22.1

### Expected results

Possibility to add two tables with the same schema / table name but with different sources

### Actual results

`Integrity error, probably unique constraint`

### Steps to reproduce

Create a database named 'UAT', create a database named 'PROD'. Create two tables with the same schema and same table name but using different databases.

**Comment by xrmx** [comment]
I think this is already reported, possibly more than one time

**Comment by asyd** [comment]
ahh my bad, I searched only in opened issues. 

dup of #3829
