### ISSUE TITLE
Dashboard cannot de displayed - TypeError: i.position_json.map is not a function

### ISSUE THREAD

**Issue by grzegorz8** [apache/incubator-superset#4547]
### Superset version
0.23.2

### Expected results
Created dashboard should be shown and all its charts.

### Actual results
Dashboard is now shown.
![empty-dashboard](https://user-images.githubusercontent.com/2642097/37042761-6658eb68-215f-11e8-9dd8-d9d548145cc3.png)

The browser console shows:
![dashboard-fail](https://user-images.githubusercontent.com/2642097/37042653-2d256ad8-215f-11e8-8de1-3b51660ceb91.png)

There are no errors / stacktraces from python code.

### Steps to reproduce
1. Create a chart.
2. Create a dashboard.
3. Add the chart to the dashboard.
4. Open the dashboard.

**Comment by graceguo-supercat** [comment]
#4485 is the fix.

**Comment by grzegorz8** [comment]
It works. Thanks!
