### ISSUE TITLE
Vegalite charts

### ISSUE THREAD

**Issue by kfk** [apache/incubator-superset#4558]
I have been looking into vega lite charts: https://vega.github.io/vega-lite/examples/

And the corresponding Python library: https://altair-viz.github.io/

I was wondering if somebody was looking into this too. Vega charts are configured in json. This means that with the right setup in Superset we open up endless possibilities for creating new charts or change existing ones.

Some ideas for creating the slice could come from here: http://vega.github.io/voyager/

**Comment by ktmud** [comment]
I've implemented this for [Redash](https://github.com/getredash/redash/pull/3931). Wouldn't mind working on it for Superset if that's inline with the Roadmap.

**Comment by mostaphaRoudsari** [comment]
Is there any plans for integrating Vega or Vega-lite at any time soon? This will be a very useful addition.
