### ISSUE TITLE
Thrift-sasl install problem

### ISSUE THREAD

**Issue by danatvzw** [apache/incubator-superset#4569]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar
Need help getting thrift-sasl-0.2.1 installed. The superset installation is not able to find the package. The website shows the file to be named "thrift_sasl-0.2.1.tar.gz" and not "thrift-sasl-0.2.1.tar.gz". Attempts to install just the thrift-sasl package independently also fail.

### Superset version
0.23.0

### Expected results
Clean installation of Superset

### Actual results
Receiving a message that reads, "Searching for thrift-sasl>=0.2.1
Reading https://pypi.python.org/simple/thrift-sasl/
Download error on https://pypi.python.org/simple/thrift-sasl/: [Errno 128] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'thrift-sasl' (maybe misspelled?)"

### Steps to reproduce
Either run the install using "python setup.py install" or
install independently using "pip install thrift-sasl==0.2.1"

**Comment by xrmx** [comment]
How have you installed superset? What does `pip freeze | grep superset` return?

**Comment by danatvzw** [comment]
superset==0.23.0.dev0

**Comment by xrmx** [comment]
Then as the error suggests it may have been a network problem. If you retry it should work.
