### ISSUE TITLE
Chrome warns for unsafe script when switching languages while running under HTTPS

### ISSUE THREAD

**Issue by Andrew-Tan** [apache/incubator-superset#4571]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
HTTPS work as usual

### Actual results
When clicked on any of a language, Chrome warns for "Insecure content blocked". If I continue with "load unsafe script", then the HTTPS secure mark will turns into unsecure (Red). Language can be switched successfully, but cannot automatically reload the page. (If you manually refresh the page, you can see language displayed changed)

### Steps to reproduce
1. Host Superset on a domain with HTTPS enabled
2. Visit Superset via the HTTPS enabled domain
3. Try switching to another language

**Comment by MAliNaqvi** [comment]
We are using version 0.25.5 of superset over https and there is no issue with switching languages. @Andrew-Tan have you tried updating superset?
