### ISSUE TITLE
Feature Request - Additional Color Gradients

### ISSUE THREAD

**Issue by jerowe** [apache/incubator-superset#4574]
This is not a bug, but a feature request, or a point me towards code so I can do it request. ;-)

I would like to have some additional color gradient options, specifically for the heatmap. I have several heatmaps with thresholds, which leads to empty cells. These cells are white, but white is also a color in the gradient.

Please see attached. It is impossible to tell if values are empty, they did not make the cutoff, or if they are '1' (in this case).

![heatmap-white-gradient](https://user-images.githubusercontent.com/5555526/37140550-8b3a1dcc-22cb-11e8-8747-d39dcef480a0.png)

Thanks!

**Comment by BLiu1** [comment]
I have the same problem/interest in seeing this developed. A color palette creator would be appreciated.

**Comment by mistercrunch** [comment]
Here's the source for the color spectrums:
https://github.com/apache/incubator-superset/blob/master/superset/assets/src/modules/colors.js#L94

References can be added here:
https://github.com/apache/incubator-superset/blob/8c822f1e9b566247ec94c368b45e36e7d767e90e/superset/assets/src/explore/controls.jsx#L314

This is a great resource, notice the "colorblind safe" option: 
http://colorbrewer2.org/

Maybe we also need an "Empty Cell Color" colorpicker control to be added to the Heatmap viz.

**Comment by jerowe** [comment]
Since d3 is already imported could I just use the d3 scales? I like those.

**Comment by mistercrunch** [comment]
We use d3 scales behind the scene. The interface is an array of color though.

**Comment by jerowe** [comment]
I have a script on my side that does a data dump of the d3 scales, so no need anymore.
