### ISSUE TITLE
Upload a csv via gui points to non existing folder: '.../superset/app/static/uploads/data.csv'

### ISSUE THREAD

**Issue by TMorville** [apache/incubator-superset#4576]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version: 
superset==0.23.2

### Expected results: 
being able to upload a .csv file

### Actual results: 
Throws error `[Errno 2] No such file or directory: '/anaconda3/lib/python3.6/site-packages/superset/app/static/uploads/data.csv'`

This is not the path where the data is stored. 

### Steps to reproduce: 
Trying to upload a .csv file via the gui.

**Comment by EricDiepeveen** [comment]
Same happens here. Added the folder and set the permissions. That fixed the issue.

**Comment by marslhx** [comment]
Add which folder to where? 
How to set the permission. 
Thanks!

**Comment by mistercrunch** [comment]
@timifasubaa

**Comment by timifasubaa** [comment]
Seen. I'll send out a PR to fix this case.

**Comment by welshamy** [comment]
I had the same problem and solved it properly by changing the path where Superset uploads the CSV.

Here is [Stackoverflow answer][1] that worked for me.

[1]: https://stackoverflow.com/questions/51412090/apache-superset-errno-13-permission-denied-usr-local-lib-python3-5-site-pac
