### ISSUE TITLE
Problem installing sasl

### ISSUE THREAD

**Issue by danatvzw** [apache/incubator-superset#4589]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar
Receiving the following error when attempting to install:
"Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-enrh6u/sasl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qb9oVE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-enrh6u/sasl/"

### Superset version
superset-0.23.2
setuptools-38.5.2
pip-9.0.1
sasl-0.2.1
python 2.7
OS: solaris 2.11
### Expected results
Successful installation

### Actual results
'cc' command failed with exit status 1

### Steps to reproduce
python setup.py install 
or
pip install sasl==0.2.1

**Comment by raffas** [comment]
Solaris 2.11 ... 1993 version? Seems quite old... 

If instead is Solaris 11, maybe try to install sasl_dev package from here: https://www.opencsw.org/packages/sasl_dev/

The dependencies are listed here: https://superset.incubator.apache.org/installation.html#os-dependencies.
Try to find the equivalent package for your OS.
