### ISSUE TITLE
sqllab: preview should quote table name

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#4595]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

master @ f9881101ee9cd447f7ccb2d38bc7563f31f686c5

### Expected results

Can preview a table with spaces in its name

### Actual results

With a table named  `bandi e gare 2017` i get:
```
near "gare": syntax error
```

### Steps to reproduce

Create a table with spaces in its name
Click to the table in sql lab
Click on the Preview for label

**Comment by xrmx** [comment]
If someone can give me an hint at where the query is sent to the frontend i can give take a look at fixing it.

**Comment by gbates101** [comment]
+1 on this. From what I can tell, a custom template processor will be needed for whatever database engine you're using. I believe it will require adding a new template processor class in the ` jinja_context` module by extending this class:
https://github.com/apache/incubator-superset/blob/502b617310e2f133ecd8626e0ed3d9ef4f0bf9cd/superset/jinja_context.py#L64

Looks like the template processor is invoked in the 'sql_json' endpoint, here:
https://github.com/apache/incubator-superset/blob/7f30b48955e249f972b1764697893aa54a43fb4c/superset/views/core.py#L2416-L2424
