### ISSUE TITLE
[Bug] Resizing widgets problem

### ISSUE THREAD

**Issue by oxydash** [apache/incubator-superset#4596]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

master
0.23.2

### Expected results

The possibility to change widgets' sizes without destroying the while order

### Actual results

I am facing a problem which lasts about 5 days. After compiling the project about 5 days ago, resizing of some widgets leads now to random order of all other widgets, in other words it’s impossible to change size of some widgets without destroying the whole order, as it is shown in video. The problem concerns also stable branches, that didn’t happen earlier. I suppose, that this may be caused by the third-party framework update.

![bug resize widget](https://user-images.githubusercontent.com/36365249/37256612-48d8a4ee-256e-11e8-8553-a4350d270ccd.gif)

### Steps to reproduce

1. Compile project  (branch: master or 0.23.2) (yarn & yarn run prod)
2. Try to change the widgets' sizes in the existing dashboards

**Comment by mistercrunch** [comment]
@williaster and @graceguo-supercat are working on a completely new layout scheme for the dashboards that uses drag and drop and moves us away from the current `react-grid-layout`.

From my understanding the issue you describe are specific to `react-grid-layout` and could be handled there, though as I said we're moving away from that library.

The new dashboard layout will have native support for dashboard-specific constructs like tabs, sections, rows, filters and more. I'm excited for scoped-filters that will apply only within their context (global, tab, section, chart, ...)

**Comment by oxydash** [comment]
Thanks for the help! The package react-grid-layout ver.0.16.6 is to blame. I'm looking forward to the new dashboard.
