### ISSUE TITLE
the size of slices in dashboard is too small 

### ISSUE THREAD

**Issue by geekSnails** [apache/incubator-superset#4600]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.2

when superset upgraded to 0.23.2, the dashboard shows not normally.
for the example, the World's Bank Date Dashboard:
### Expected results
![image](https://user-images.githubusercontent.com/26055737/37281567-77659ff6-262c-11e8-9bbc-190da9a83d4b.png)

### Actual results
![image](https://user-images.githubusercontent.com/26055737/37281522-46c10f3e-262c-11e8-8f3d-16464448437a.png)

### Steps to reproduce
when upgraded to 0.23.2,
the older version shows ok, and the new version shows not normally

**Comment by BigFaceFish** [comment]
I also met the same question when upgraded from 0.22.1 to 0.23.2 .  All the slices in my more than 50 dashboards are all zoomed after upgraded as yours. Expect this will be solved as soon as possible.

**Comment by mistercrunch** [comment]
Run the database migration scripts. It's in the upgrade instructions:
https://superset.incubator.apache.org/installation.html#upgrading
