### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by wangqi19940304** [apache/incubator-superset#4613]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.2

### Expected results
When I open the dashboard I created, I can see it.

### Actual results
I can see nothing, but:
dashboard.b21ed8e6fe6a55e3a492.entry.js:326 Uncaught TypeError: Cannot read property 'map' of null
    at b (dashboard.b21ed8e6fe6a55e3a492.entry.js:326)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1
b @ dashboard.b21ed8e6fe6a55e3a492.entry.js:326
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:305
n @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:305
n @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1

### Steps to reproduce
1、Click the dashboards.
2、Choose my dashboard.

**Comment by xrmx** [comment]
Please add all the missing information from the issue template

**Comment by amishyn** [comment]
Having the same issue, curious how did you fix it ?

**Comment by pranavoyo** [comment]
same issue, please suggest solution. @wangqi19940304 @xrmx

**Comment by amishyn** [comment]
What worked out for me, is to add custom config file `superset_config.py` with
`UPLOAD_FOLDER='/tmp/'`

**Comment by pranavoyo** [comment]
doesn't work for me,
dashboard.b21ed8e6fe6a55e3a492.entry.js:326 Uncaught TypeError: Cannot read property 'map' of null
    at b (dashboard.b21ed8e6fe6a55e3a492.entry.js:326)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1

**Comment by amishyn** [comment]
Oh, I'm sorry, suggested fix for the another issue of uploading csv.

For this one, I've added '[]' as a value for 'Position JSON'

**Comment by mistercrunch** [comment]
If you've seen this > `0.24.0` let me know and I'll reopen

**Comment by Jemteddy** [comment]
It came back with 0.28.1, issue is there : https://github.com/apache/incubator-superset/issues/6165

**Comment by TTD1993** [comment]
1EcH7pHYTHLo3cbdXfkf6e6Zh5JzCPGumc

**Comment by mistercrunch** [comment]
Actually @Jemteddy that error message is pretty generic, can you open another issue providing more details?
