### ISSUE TITLE
how to get superset‘s version

### ISSUE THREAD

**Issue by NZHEzreal** [apache/incubator-superset#4634]
now, I have a project, this project is builded by ex-colleague, project install into virtualenv, I can't enter into virtualenv.

So, how can I get the superset's version that under the condition of not enter the virtualenv.

If no way to get the version, how can I use exsiting code to deploy the project .

Thank you very much!

**Comment by xrmx** [comment]
There's  a button on the top right of the header called "version info".

**Comment by NZHEzreal** [comment]
@xrmx Thank you for your reply. I can't run the project , so I can't see the page of project.
Do you konw which file can get information about the project?

**Comment by john-bodley** [comment]
It’s defined in the package.json [file](https://github.com/apache/incubator-superset/blob/master/superset/assets/package.json).

**Comment by mistercrunch** [comment]
For the specific SHA as of the last time `setup.py` ran, you may be able to rely on `superset/assets/version_info.json`

**Comment by csc5k** [comment]
Why did the "version info" button get removed?

**Comment by GiannisDimitriou** [comment]
You can find the version in this file `superset/assets/package.json`
