### ISSUE TITLE
[superset 0.23.2] bug no default charts position in dashboard, dashboard is empty

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#4635]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.2

### Expected results
when create a new dashboard with some slice, we can view the slice(charts) in dashboard without addtional position json configuration like this: 
```
[
    {
        "col": 1, 
        "row": 0, 
        "size_x": 8, 
        "size_y": 3, 
        "slice_id": "49"
    }, 
    {
        "col": 5, 
        "row": 3, 
        "size_x": 8, 
        "size_y": 3, 
        "slice_id": "50"
    }
]
```
### Actual results
However in superset 0.23.2 version,  the dashboard is totally empty after adding some slice(charts) in the dashboard. And if I fill in the position json in dashboard edition page as above, the slices could be shown.

### Steps to reproduce
install superset 0.23.2
create a dashboard, add some slices and click into the newly added dashboard, you will see nothing.

<img width="861" alt="screen shot 2018-03-17 at 11 24 54 pm" src="https://user-images.githubusercontent.com/8351385/37557120-df91a25c-2a3a-11e8-8029-5d6f0e7cc864.png">

<img width="1178" alt="screen shot 2018-03-17 at 11 25 09 pm" src="https://user-images.githubusercontent.com/8351385/37557121-dfcdd114-2a3a-11e8-8dda-7c8c75715bbe.png">

**Comment by jonathortense** [comment]
+1

**Comment by mistercrunch** [comment]
Would suggest passing on `0.23.*` at this point. Hopefully we can get back to some good stable releases. It's been harder since the maintainer cutting the releases (me) doesn't have direct access to a big user base anymore :/

Hoping we can get back on solid grounds with `0.24.0`. Please try the rc1 tag if you can

**Comment by napjon** [comment]
@mistercrunch: Wish I knew this sooner. Wasted a good 4 hours trying to debug the issue.

**Comment by mistercrunch** [comment]
Sorry as we're ironing out our release process. Part of the Apache process will force us to come up with steady solid releases. It probably won't make you feel better but I spent much more than 4 hours working on trying to come up with solid releases lately :(

**Comment by mistercrunch** [comment]
Knowing that `0.24.0rc1` is better than `0.23.*` and the unlikelyhood of the community to really test and RC at this point (I'm assuming that the processes just aren't in place externally), maybe I should just launch it as `0.24.0`.

**Comment by cah-jeffgraham** [comment]
+1 for stable release as we're evaluating Superset and initially discouraged when basic dashboard functionality is nonfunctional.

**Comment by yamyamyuo** [comment]
> Wish I knew this sooner. Wasted a good 4 hours trying to debug the issue.
@napjon 
Me too. I would recommend not to upgrade superset too rough. LOL

**Comment by napjon** [comment]
>Sorry as we're ironing out our release process. Part of the Apache process will force us to come up with steady solid releases. It probably won't make you feel better but I spent much more than 4 hours working on trying to come up with solid releases lately :(

No need to apologize! Bug happens. Probably a good principle to sort through GitHub issues after spending 1 hour debugging cryptic bug.

Thank you for your hard work on creating such an immensely useful tool. Been using it to speed up all of my report/summary.

**Comment by cah-jeffgraham** [comment]
Agree with @napjon on appreciating all the hard work thats been put into tool.  We're hoping this will help our data discovery teams.

**Comment by mistercrunch** [comment]
`0.24.0` is out, closing
