### ISSUE TITLE
[help wanted]How to use mapbox chart view when longitude and latitude are in postgis point format

### ISSUE THREAD

**Issue by fareshan** [apache/incubator-superset#4640]
Hi,
I am trying to create a chart with mapbox view.
I am using a postrgres database with postgis. So, altitude and longitude are merged in the same column. But superset seems to require them to be in different columns.
Normally, an sql query can be like this:
`SELECT ST_X(location) AS lon, ST_Y(location) AS lat FROM Address`

I did not get an answer on stackoverflow:
https://stackoverflow.com/questions/49347294/how-to-use-supersets-mapbox-view-when-longitude-and-latitude-are-in-postgis-poi

**Comment by xrmx** [comment]
Columns that you have in the superset tables may not be real columns but sql expression. Just add a new column with that sql expression.

**Comment by fareshan** [comment]
Thanks,
Now, I get this error: An error occurred while rendering the visualization: TypeError: Cannot call a class as a function
I think it is related to this issue:
https://github.com/apache/incubator-superset/pull/4621
