### ISSUE TITLE
Dashboard not coming up 

### ISSUE THREAD

**Issue by praveenrajjogi** [apache/incubator-superset#4642]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Expected results
When I open the dashboard I created, I can see it.

Actual results
I can see nothing, but:
dashboard.b21ed8e6fe6a55e3a492.entry.js:326 Uncaught TypeError: Cannot read property 'map' of null
    at b (dashboard.b21ed8e6fe6a55e3a492.entry.js:326)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at Object.<anonymous> (dashboard.b21ed8e6fe6a55e3a492.entry.js:305)
    at n (dashboard.b21ed8e6fe6a55e3a492.entry.js:1)
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1
    at dashboard.b21ed8e6fe6a55e3a492.entry.js:1
b @ dashboard.b21ed8e6fe6a55e3a492.entry.js:326
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:305
n @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:305
n @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1
(anonymous) @ dashboard.b21ed8e6fe6a55e3a492.entry.js:1

cmd prompt

2018-03-19 11:07:35,427:DEBUG:root:[36m[stats_logger] (incr) dashboard[0m
2018-03-19 11:07:35,911:INFO:werkzeug:127.0.0.1 - - [19/Mar/2018 11:07:35] "GET /superset/dashboard/test/ HTTP/1.1" 200 -

Steps to reproduce
1.created new chart
2.save it to dashboard
3.Click the dashboards.
4.Choose my dashboard.

**Comment by mlambolla** [comment]
Yes, same error was logged days ago https://github.com/apache/incubator-superset/issues/4619

I experienced the same error as well, and I'm waiting for the fix. I wish I could help --I'm learning how to do it :-)

**Comment by SpyderRivera** [comment]
This is fixed in master

**Comment by mlambolla** [comment]
@SpyderRivera  Could you please guide me on the steps to install a cloned version? I compiled the code and generated easy_install but I got stuck there.
I'm not an expert, still learning on this
I'll appreciate if you guide me on steps

**Comment by mistercrunch** [comment]
https://superset.incubator.apache.org/installation.html#making-your-own-build

**Comment by mistercrunch** [comment]
Working on a stable release ATM, hopefully can make it out soon.

**Comment by SpyderRivera** [comment]
this is fixed in the latest release (0.24.0rc1)
