### ISSUE TITLE
Superset has no plain number format for Table chart type

### ISSUE THREAD

**Issue by theikkila** [apache/incubator-superset#4644]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.1

### Expected results
Have a plain number format ie.
number: 123838372871263
display:  123838372871264

### Actual results
display: 1238300000000

### Steps to reproduce
Create any dataset with big enough numbers, you can't find any representation format for displaying them correctly with full granularity.

PR #4545 seems to fix this so it probably just needs to merge.

**Comment by xrmx** [comment]
Then why opening an issue if there's already a PR? Please give the PR a try instead.

**Comment by theikkila** [comment]
This issue is for boosting the PR. This can be closed after the merge happens.

**Comment by darylerwin** [comment]
New to all this github stuff but what are the steps to getting a PR into the released code - seems like there are lots in there waiting to merge. Loving all the releases - seems like weekly 👍
