### ISSUE TITLE
Use one library for table components

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#4649]
For table components we are currently using Reactable, our own FilterableTable, and datatables. Reactable hasn't merged any code since Nov 2016. We are seeing an issue with sorting columns in reactable and I submitted an issue in reactable in Oct that no one has responded to. I was going to evaluate different options for other react table components we could use, and thought it might be an opportunity to consolidate on one.

I made a list of the different places we are using tables (let me know if there's anything I've missed). 

## Reactable

javascripts/SqlLab/components/QueryTable.jsx
javascripts/SqlLab/components/VisualizeModal.jsx
javascripts/components/AlteredSliceTag.jsx
javascripts/explore/components/controls/DatasourceControl.jsx
javascripts/profile/components/TableLoader.jsx
javascripts/welcome/DashboardTable.jsx
visualizations/time_table.jsx
visualizations/paired_ttest.js

## FilterableTable

javascripts/SqlLab/components/ResultSet.jsx

## datatables

visualizations/table.js
visualizations/pivot_table.js

If / when I get a chance to work on this, I'll update this thread with more info. Let me know if anyone has any objections to moving away from reactable and trying to consolidate.

cc: @williaster @mistercrunch

**Comment by mistercrunch** [comment]
FilterableTable is a wrapper around `react-virtualized` which plays nice tricks to only render what's in the viewport, allowing to render (fake-render really) large datasets which was a requirement for SQL Lab. It's one of those who fake a table (it's not an html `<table>`) so it doesn't know how to scale the width of columns like the normal html `<table>` do. We have to provide hard coded widths somehow for this to work. There's code somewhere that figure out pixels width given a html snippet which is a bit borderline hacky but there are no ways around that I can think of.

Personally I like the `reactable` api, allowing to just `<Table data={data} />` but also going down to `Tr` `Td` where/when needed. It's also proper html `<table>` which have good properties and style properly when passing the proper bootstrap classes (`table table-bordered table-condensed ...`).

I think we may need both of these ^^^

Now you missed `react-bootstrap-table` which can be replaced by `reactable`. This should be pretty easy to do. Here: `javascripts/dashboard/components/SliceAdder.jsx`

Clearly datatables is the non-react weird old jQuery one here that we should kill. It's also pretty big in our bundles, I did some work around removing the dependency, but there's still the `table` and `pivot_table` visualizations that we need to fix up.

**Comment by michellethomas** [comment]
Thanks for the information Max. This is super useful.

**Comment by graceguo-supercat** [comment]
<img width="403" alt="screen shot 2018-03-21 at 2 25 15 pm" src="https://user-images.githubusercontent.com/27990562/37739507-86c1c640-2d17-11e8-875b-c9808250a735.png">

Dashboard v2 will use this UI to show list of available charts, will not use `BootstrapTable`.

**Comment by williaster** [comment]
yeah I'm not sure there's a way around needing both a virtualized table for very large amounts of data as well as another more simple one.

the first component in `@data-ui` was `@data-ui/data-table`, which uses `react-virtualized` and was meant to replace the sql lab table because both dataportal and superset needed it, but alanna never refactored it in superset.

**Comment by mistercrunch** [comment]
I'm open to replace `react-virtualized` with `@data-ui/data-table` as long as we agree they'll be growing in the same direction. Things like the JSON inference/handling in there is nice, I guess we just need to be able to pass react nodes down where we need.

Could be nice to grow in the direction of more profiling (histogram in sub-header), perhaps showing the type icons, per column filtering (as in MS Excel auto filter) and things of that nature.

The distinction there becomes very clear, one is data-table and the other an html table. Sucks that reactable isn't well supported (or is it just feature complete?!)

**Comment by michellethomas** [comment]
After talking with Chris a bit more about this, for now I think we are just going to use `react-virtualized` until there's a clear need to use something within `data-ui/data-table`.

I'm going to start by moving the Table viz over to react-virtualized.

**Comment by mistercrunch** [comment]
If visual consistency (before and after) is a requirement it will be much harder to achieve with `react-virtualized`.  With `reactable` it will be fairly easy to get the same effective html `<Table>`. 

With  `react-virtualized` you'll have to mimic dynamic column sizing based on content, and will either have to overflow or do guesswork to force proportions and wrapping based on column content.

**Comment by michellethomas** [comment]
We have users adding tables with large amounts of data to dashboards (that then freeze or slow down the dashboard), I'm hoping we see some performance improvements moving to `react-virtualized`, but if I can't get it to work I'll use reactable.

**Comment by williaster** [comment]
it seems like most entries in these tables are simple enough to have equal column widths and wrap if they overflow? also `react-virtualized` exports a utility component to measure cells (still requires fixed width or height) that you could try to leverage.

**Comment by mistercrunch** [comment]
We have a cell-measuring utils function somewhere on our side too. 

I think it gets tricky. Picture a report with a wide HDFS folder locations as in `/hive/warehouse/default/fact_rides/20180101/file234872948298` and one metric (say `megabytes`). You clearly don't want a wrapped `HDFS folder` to accommodate a 50% width metric.

Though I like the idea of having consistently sized metrics where one metric doesn't look arbitrarily more important than another one just because the label is wider. It could be interesting to see how browsers do it (proportion based on max(width)? proportion based on avg(wdith)?). I'm guessing it's a bit fuzzy and might generally look better than a simpler `width/num_columns`.
