### ISSUE TITLE
Feature Request: Kill Long Running Query

### ISSUE THREAD

**Issue by beja0502** [apache/incubator-superset#465]
I am new to Caravel and often times when trying out some of the Visualization Types I don't get them to work correctly.  If I accidentally misplace Fields in the wrong Group By or Metrics area it can cause the query to run forever, eventually causing the window to freeze and hang completely.  I would like to have a feature that allows you to Kill the Query if it is taking too long or appears like it will hang.

**Comment by Dumbleboar** [comment]
same here
a kill-option would be very handy

**Comment by b-abb** [comment]
Ditto

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
