### ISSUE TITLE
Have to repeat build and install each time when I modify and test jsx in superset/assets/javascript

### ISSUE THREAD

**Issue by leehwmj-junta** [apache/incubator-superset#4650]
Make sure these boxes are checked before submitting your issue - thank you!

- [o ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ o] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.0

### Steps to reproduce

The 0.22.0 version of superset is currently in development.

I am looking for a handy way to change the code in the jsx file and see how it actually works and works.

For example, line 59 of $ SUPERSET_HOME / superset / assets / javascript / addSlice / AddSliceContainer.jsx file looks like this:

<p> {t ('Choose a datasource')} </ p>

I want to change this as follows.
<p> {t ('Choose a DATABASE')} </ p>

 And when I save and refresh it, the changes do not take effect. Restarting superset runserver does not work either.
 In order to apply this, I did the following.
1. Go to the $ SUPERSET_HOME / superset / assets folder
2. Run the yarn run build again
3. Go to $ SUPERSET_HOME folder
4. Run python setup.py install again
5. Run the superset runserver again

I was able to verify that my jsx changes were applied after I did the above.
But I think this process is too inefficient and time consuming. And I believe there will be a good way to check my changes without repeating the above process.
But I have no idea about it.

I am concerned that it may be related to configuration files such as webpack or package.json, but I do not know for sure.

So I ask for help here.

Thank you

**Comment by mistercrunch** [comment]
Did you follow https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-a-python-development-environment ?

**Comment by leehwmj-junta** [comment]
@mistercrunch 

Umm...  I have missed "pip install -e"

### So, I did "pip install -e"  after you answered.
Then I change the code, and start "superset runserver -d"

### but not work it
Should I repeat clone codes and setting up?

I had stepped...
1. Fork the incubator-superset
2. git clone
3. checkout to version 0.22.0 and make new branch
4. Do virtualenv on Parent folder (The env folder and the superset folder are in the same parent folder)
5. source env/bin/activate
6. fabmanager create-admin --app superset
7. superset db upgrade
8. superset load_examples
9. superset init
10. superset runserver -d

Run the runserver again to test the * .py file, and the * .html file was just a browser refresh.
However, only jsx files had to be rebuilt with builds and setups.

**Comment by leehwmj-junta** [comment]
@mistercrunch , I tried with the suggested method.

But there was a new problem. When I check git to 0.22 and proceed to the proposed protocol, the layout will be displayed as 0.23.0dev.
<img width="691" alt="2018-03-20 5 32 12" src="https://user-images.githubusercontent.com/36018781/37643688-ba346e6e-2c64-11e8-8e12-79ae0dcdf9e9.png">

However, the code is clearly marked as 0.22.
![2018-03-20 5 32 18](https://user-images.githubusercontent.com/36018781/37643713-cdced4c8-2c64-11e8-8af2-1396abc25ec2.png)

And css is not applied properly.
<img width="708" alt="2018-03-20 5 34 13" src="https://user-images.githubusercontent.com/36018781/37643770-f1e031d6-2c64-11e8-94f8-970727f469db.png">

This problem only occurs when you use this method (https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-a-python-development-environment).

On the other hand, when I proceeded to this method (https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization), I constantly reaffirmed that the 0.22 version of the layout worked well.

**Comment by SpyderRivera** [comment]
Did you hard refresh? In case, the changes are there, but the cache persists.

**Comment by mistercrunch** [comment]
`npm run dev`

**Comment by darylerwin** [comment]
I get that problem with css as well when I try to install a git branch. should I run "npm run dev" or something similar? [what exactly to I run]

**Comment by mistercrunch** [comment]
Please read and follow the `CONTRIBUTING.md` file, both sections:
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-a-python-development-environment
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment

**Comment by leehwmj-junta** [comment]
Right!
I have success set up.

I followed up all of the both section
(but did not use "Copies a conf file from the frontend to the backend", "Compiles the production / optimized js & css". I do not know the purpose of them.)

Then I tried
$ superset runserver -d -p 8081
$ npm run dev

So my problem is cleaned up! Thank you a lot!
I will close this Issue
Thanks!
