### ISSUE TITLE
add group by parameters into filter box

### ISSUE THREAD

**Issue by ccl0326** [apache/incubator-superset#4652]
now we can use filter box to filter fields, but if we can make filter box control group by parameters we can make it more free. we can select some fields for group by in dashboard.

**Comment by masr** [comment]
It is very useful for us to manage the group by combination in the dashboard. It enables users to do multiple dimension analytics freely.

**Comment by LKronecker** [comment]
Is there a plan to develop this feature further? Thanks! :)

**Comment by vikramsinghchandel** [comment]
Any plans for this feature?

**Comment by Volodymyrk** [comment]
this is the first dealbreaker we encountered to adopt superset. This feature would be super useful, indeed.
