### ISSUE TITLE
the schema of short url is hard code to http

### ISSUE THREAD

**Issue by ktong** [apache/incubator-superset#4656]
https://github.com/apache/incubator-superset/blob/93ec76f7570dcd53d110498cc18ec0f15dd9854b/superset/views/core.py#L750

**Comment by ripoul** [comment]
this code should do the work :

`scheme = request.scheme
 return Response(
            '{scheme}://{request.headers[Host]}/{directory}?r={obj.id}'.format(
             scheme = scheme, request=request, directory=directory, obj=obj),
            mimetype='text/plain')
`

**Comment by mistercrunch** [comment]
@ripoul mind submitting a PR ?

**Comment by ripoul** [comment]
@mistercrunch done and merge! Close?
