### ISSUE TITLE
Error datetime convert

### ISSUE THREAD

**Issue by deatheyes** [apache/incubator-superset#4657]
this line results wrong date time：
https://github.com/apache/incubator-superset/blob/fc47729233e7ce44e225edbeb628f6a5f0376eda/superset/viz.py#L158

the proper way is:
pd.to_datetime(df[DTTM_ALIAS], utc=False, unit="s")  and df[DTTM_ALIAS] = pd.to_datatime(df[DTTM_ALIAS], utc=False, unit="ms")

**Comment by xrmx** [comment]
Care to open a PR with a bit of explanation why the current code is wrong please?

**Comment by deatheyes** [comment]
@xrmx this my test case an output:
>>> pd.to_datetime(1521475500, utc=False)
Timestamp('1970-01-01 00:00:01.521475500')

>>> pd.to_datetime(1521475500, utc=False, unit="s")
Timestamp('2018-03-19 16:05:00')

**Comment by mistercrunch** [comment]
Please open a PR with the proposed changes
