### ISSUE TITLE
Question: How to convert timestamp field represented as text in ISO8601 format to datetime - superset evaluation

### ISSUE THREAD

**Issue by varaga** [apache/incubator-superset#4658]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

I'm trying to evaluate DRUID and superset as exploratory tool. Our dataset stores a timestamp column, an ISO 8601 format, represented as TEXT(string). I'm not sure how to convert this into a DATETIME field that superset need for performing queries.

```2017-09-30T22:02:24Z ``` - Here is a sample of timestamp as text.

### Superset version
0.23

**Comment by mistercrunch** [comment]
Is this an alternate time field as a Druid dimension?

Superset works well on the time index that Druid enforces, but there's little support for using another dimension as time.

**Comment by SpyderRivera** [comment]
I have not had issues with this. Any format of a timestamp that works in Druid has worked in Superset for me. If you data is loading into druid with errors, then I would suggest the druid community. In your ingestion spec you can specify the timestamp format.

**Comment by AneeqYusuf** [comment]
I am having the same issue. So the main problem is that if I am directly using the druid table for charts the __time column automatically is detected as timestamp. However, if we run a query, using the same __time field as the timestamp, the data in charts is automatically typecasted to string, which is weird.

@varaga, did you have any success in solving this?
