### ISSUE TITLE
Inconsistent inclusion of a footer template

### ISSUE THREAD

**Issue by b881659b** [apache/incubator-superset#4665]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.23.3

### Expected results

Adding a file `superset/templates/appbuilder/footer.html` as per the appbuilder documentation should include the same fragment on all pages.

### Actual results

The templates defined in superset do not reference the footer template and are thus not included. Others such as those directly from appbuilder still support this giving inconsistent results. 

Footer included in, for example, `login/`, `databaseview/list/` but not included in `superset/dashboard/...`, `superset/welcome`. 

### Steps to reproduce

Include a file `superset/templates/appbuilder/footer.html` with any content that would be visible when rendered such as `<div>Hello, World</div>` and open the views indicated above.

### Possible solutions

Some method of adding end-of-view content without patching a large set of templates would be great. I am thinking of internal/external support links, legal notices here. Other mechanisms would be fine too though I am reluctant to use JS to add it dynamically to pages, which may or may not work for all users.

As a possible alternative, a documented way of including a notice on the login page only (but for all authentication mechanisms) may work but I cannot be sure this covers all such use cases (e.g. anonymous access).

**Comment by mistercrunch** [comment]
Sounds like you want to add `footer.html` to the `basic.html` template (or whatever what the base template for React apps is). Keep in mind this is not a public api, we're not explicitly supporting people forking Superset to change the templates or that kind of things.

**Comment by b881659b** [comment]
Thanks. For the benefit of anyone else looking for a similar solution: I replaced my existing patches with one adding the footer inclusion code to the `basic.html` file as suggested. It appears to be sufficient but I have not had a chance to test all sections. 

I am happy for the issue to be closed if you do not intend to implement footer support in project-specific templates.

**Comment by mistercrunch** [comment]
Happy to review if you want to upstream your change.

**Comment by guptaraul89** [comment]
@b881659b I have a similar situation. Could you please share your footer inclusion code?

**Comment by b881659b** [comment]
> @b881659b I have a similar situation. Could you please share your footer inclusion code?

@guptaraul89: I do not have access to that code anymore. From what I recall replicating the footer inclusion `<div>` section to basic.html was sufficient to get this to work but the original templates did more than just include the footer template. They added a little formatting, which you could find in the appbuilder templates. This would ensure consistent margins across pages. 

An alternative I explored at the time, which may be easier but not applicable in all cases, was to include javascript in the header. The header appeared to be handled more consistently. This could dynamically add content to the end of the page or in the margins such as a support button. We solved our problems in different ways so I not know how much this part of superset has changed since and if the above still works.
