### ISSUE TITLE
Remove and Re-align the Bar values on clicking the legend 

### ISSUE THREAD

**Issue by shyam2794** [apache/incubator-superset#4667]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
23.3

### Actual Results

Hi Team , when trying to uncheck the legend in the time series bar chart , The bar values does not clean up . This appear for both grouped and stacked chart . 

Before unchecking the legend 

![screenshot from 2018-03-22 21-10-19](https://user-images.githubusercontent.com/30238125/37780770-750a42de-2e15-11e8-85de-c997d834fa21.png)

After unchecking the legend , i have unchecked (IPD) in the legend , But still the bar values appear . 

![screenshot from 2018-03-22 21-11-13](https://user-images.githubusercontent.com/30238125/37780844-984910cc-2e15-11e8-8b57-44111e4562c3.png)

### Expected Results

When the legend(s) is/are unchecked the bar values for that legend(s) should not be visible and the bar values for the remaining bars should be re-aligned . 

### Steps to Reproduce

1. create a chart with time series bar as visualisation type 
2. choose a metric and choose a column under group by 
3. check the legends and bar values check box 
4. Now in the chart click on the legend to uncheck it .

**Comment by shyam2794** [comment]
Hi Team , 
Any update on this ..

**Comment by jeffreythewang** [comment]
We are also having a similar issue in our use case of showing markers in line charts, where unchecking/rechecking a legend renders the new line without markers.

Steps to reproduce:

1. Create a line chart with a metric and multiple groups
2. Check the "Show Markers" option in Style
3. Uncheck and recheck a group via the legend

Before uncheck/recheck:
<img width="1005" alt="screen shot 2018-06-07 at 10 08 16 am" src="https://user-images.githubusercontent.com/3317634/41105160-04c4a2aa-6a3b-11e8-8eaa-97a4ef3b936f.png">

After uncheck/recheck:
<img width="1007" alt="screen shot 2018-06-07 at 10 08 33 am" src="https://user-images.githubusercontent.com/3317634/41105168-0a9b65ec-6a3b-11e8-886f-9a0e48da75c3.png">

**Comment by zhihaozhang** [comment]
I also met this bug. I fix it by adding following code to NVD3VIs.js file:

find 
{
case 'dist_bar':
        chart = nv.models.multiBarChart()
          .showControls(showControls)
          .reduceXTicks(reduceXTicks)
          .groupSpacing(0.1); // Distance between each group of bars.
}
add the following code:
chart.legend.dispatch.on('legendClick',function (evt) {
              svg.selectAll('.bar-chart-label').remove();
              setTimeout(function () {
                  if(!fd.show_bar_value){
                      svg.selectAll('.bar-chart-label').remove();
                  }
                  addTotalBarValues(svg, chart, data, stacked, fd.y_axis_format);

              }, animationTime + 1);


<img width="1190" alt="wechatimg482" src="https://user-images.githubusercontent.com/4500659/47212283-594eef80-d3ca-11e8-8331-90ab5abf8616.png">

**Comment by KennethEnevoldsen** [comment]
This seems like a valid thing to add, no?
