### ISSUE TITLE
Slice level cache_timeout isn't taken into consideration

### ISSUE THREAD

**Issue by daoready** [apache/incubator-superset#4672]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.23.0.dev0

### Expected results

when i set cache timeout for slice, it should take precedence over the database / table timeouts.

### Actual results

Slice timeout setting is never used

### Steps to reproduce

Set slice timeout to value other than for table and test

This was broken on commit: a7a6678d5ca535e29e6e021b7404c2e5c3599fdb

**Comment by rahimramezanian** [comment]
I have a similar problem with cache_timeout

### **Superset version**
0.23.0dev

### **Expected results**
It seems setting cached timeout means to get data again from datasource and rebuild the slice too. 

### **Actual results**
Slice timeout setting is never used

### **Steps to reproduce**
I set cache timeout for the data source equal to 1 seconds and in `NVD3TimeSeriesViz` I add a line 
`cache_timeout=5`
Then I created a table in an SQLite database that is updating every 5 seconds and I also create a slice with type `Time Series - Line Chart`. The slice cannot update itself every 5 seconds. I have to press **run query** button to update it.
