### ISSUE TITLE
superset dashboard is blank 

### ISSUE THREAD

**Issue by ManojKumarMaurya** [apache/incubator-superset#4685]
Make sure these boxes are checked before submitting your issue - thank you!

/home/ubuntu/code/superset/local/lib/python2.7/site-packages/flask_appbuilder/fields.py:152: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  warnings.warn('allow_blank=True does not do anything for QuerySelectMultipleField.')

- [x] I have checked the superset logs for python stack traces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.3

### Expected results
superset should work 

### Actual results
dashboard blank 
/home/ubuntu/code/superset/local/lib/python2.7/site-packages/flask_appbuilder/fields.py:152: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  warnings.warn('allow_blank=True does not do anything for QuerySelectMultipleField.')

### Steps to reproduce

/home/ubuntu/code/superset/local/lib/python2.7/site-packages/flask_appbuilder/fields.py:152: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  warnings.warn('allow_blank=True does not do anything for QuerySelectMultipleField.')

<img width="1268" alt="screen shot 2018-03-23 at 6 22 10 pm" src="https://user-images.githubusercontent.com/5546605/37859853-7f10e3f6-2f40-11e8-8443-5d047e774d43.png">
<img width="1240" alt="screen shot 2018-03-23 at 6 16 04 pm" src="https://user-images.githubusercontent.com/5546605/37859854-7f4abf5e-2f40-11e8-960c-8d1473fd4198.png">

**Comment by xrmx** [comment]
This was already reported and fixed. Please close!

**Comment by ManojKumarMaurya** [comment]
how can I get the fix issue  really helpful if any suggestion

**Comment by shashanksingh** [comment]
@xrmx I am facing the same issue,  can you please point us to right P.R.. Would be really helpfull.

**Comment by shashanksingh** [comment]
@xrmx @ManojKumarMaurya nevermind got it https://github.com/apache/incubator-superset/issues/4642 , we have to use the new Release candiate build for this to solve (0.24.0rc1)

**Comment by SpyderRivera** [comment]
#4619

**Comment by mistercrunch** [comment]
`0.24.0` is out and should address this

**Comment by ManojKumarMaurya** [comment]
0.24.0 is working   thanks

**Comment by pixdrift** [comment]
I just had this error occur in 0.27.0, trying to track down why.

**Comment by sahiljain001** [comment]
0.36.rc1 is not working. Blank login page
