### ISSUE TITLE
css not loading at "http://0.0.0.0:8088/superset/welcome" 

### ISSUE THREAD

**Issue by Sidhartha03** [apache/incubator-superset#4690]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
You haven't written how you installed superset, if you have installed it from a git checkout it looks like you haven't followed instructions on how to do your own build as written in the documentation.

**Comment by jdnurmi** [comment]
Not reporter, but similar experience, using the community docker image as a base, but shifting to version 0.24.0 (direct pull from github releases as it wasn't available on pypi this morning)

HTML Fails to pull a reference in the header:
`<link rel="stylesheet" type="text/css" href="/static/assets/dist/" />
` 

Which to source is 
      <link rel="stylesheet" type="text/css" href="{{ js_manifest('theme.css') }}" />

in templates/superset/basic.html.

I started to try to trace js_manifest, but couldn't find a generated manifest that it was trying to read, or how to generate one, so I started checking in the issues list here on github, and here I am 😄

**Comment by jdnurmi** [comment]
Approximate patch, will likely need fuzzy to apply

`
diff --git a/docker/superset/Dockerfile b/docker/superset/Dockerfile
index d0d1e0a..b573aa4 100644
--- a/docker/superset/Dockerfile
+++ b/docker/superset/Dockerfile
@@ -3,3 +3,3 @@ FROM registry.internal.sano.co/sano/sano-python3:latest
 # Superset version
-ARG SUPERSET_VERSION=0.23.3
+ARG SUPERSET_VERSION=0.24.0
 
@@ -49,3 +49,3 @@ RUN useradd -U -m superset && \
         Werkzeug==0.12.1 \
-        superset==${SUPERSET_VERSION}
+        https://github.com/apache/incubator-superset/archive/${SUPERSET_VERSION}.tar.gz
`

**Comment by xrmx** [comment]
@jdnurmi That would mean that the packaged uploaded to pypi is broken.

**Comment by jdnurmi** [comment]
Sorry, to be clear, there isn't a 0.24.0 on pypi yet - this is using the version in the github releases directly via pip install that looks to have shipped late last week.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment

**Comment by mistercrunch** [comment]
I just pushed `0.24.0` to pypi and a PR with the changelog

**Comment by JulieRossi** [comment]
Hi !

As I would like a version that includes the commit with `flask_caching` I tried to pip install superset from the last commit and I get the same issue (css not loading at "http://0.0.0.0:8088/superset/welcome").

If I understand well, this is normal so I would like to know if you plan on issuing a new version soon ?

**Comment by mistercrunch** [comment]
@JulieRossi follow the instructions in the CONTRIBUTING.md to make your own build

**Comment by JulieRossi** [comment]
Thank you for your answer @mistercrunch. I have seen the contributing but I was hoping you would issue a new version soon enough so we don't have to do it. 
It would required the production team to review their deployment scripts and they are quite busy currently.
But of course, if you don't plan to have the next version soon (in the coming weeks), we'll do that.

**Comment by JulieRossi** [comment]
Actually, I see that you just did, sorry for the trouble

**Comment by mistercrunch** [comment]
@JulieRossi check out 0.25.2

**Comment by Tyler-Rex** [comment]
I'm having this issue in 0.25.6. I am not using a development build. I followed all the installation steps and had it working just fine on 0.25.0.

**Comment by mistercrunch** [comment]
Did you restart the webserver? The js bundles hash change on upgrade and the web server needs to be restarted.

**Comment by Tyler-Rex** [comment]
I now understand this issue much better and I am using a git checkout. I understand that I would be need to follow the "Making your own build" step to continue. But I am not able to get yarn on my instance. Is 0.25.2 a version that I wouldn't have to do this? Are there others? If not I'll just stick with pypi downloads and not contribute.

**Comment by CraigChaffee** [comment]
I'm seeing exactly this problem with the latest docker version (28.1).

**Comment by haokaibo** [comment]
Is there anyone find the root cause? This is quite an annoyance to me. Please help. Thanks in advance.

**Comment by mistercrunch** [comment]
CSS is missing is a bit of a catchall, it means you have failed at building the JS/CSS. Let's re-open more specific issues. 

@CraigChaffee & @haokaibo it seems there are issues around the `contrib/` Docker build. This was community contributed and is not really maintained by the core committers...

**Comment by haokaibo** [comment]
Thanks. @mistercrunch . I got it. Currently I use the repo below for temp solution. The one who try to count on the docker version of superset please try it. : ) 

https://github.com/abhioncbr/docker-superset

BR.

**Comment by vehbisurem** [comment]
> `
#11611 
Duplicate of #
`
