### ISSUE TITLE
dashboard empty

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#4692]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
23.3

### Expected results
Dashboard with chart inside

### Actual results
When I create a new dashboard it appears empty, to circumvent this problem I have to add manually [] in the "Position JSON" field.

### Steps to reproduce
Create a new dashboard or create a new chart and add to a new dashboard

**Comment by xrmx** [comment]
This has already been fixed in a released version and there's already a duplicate issue #4685 open. Please close.
