### ISSUE TITLE
Email Validation check does not happen in RegisterUserDBForm

### ISSUE THREAD

**Issue by nihalbtq8** [apache/incubator-superset#4698]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset-0.22.1

### Expected results
Expect to throw an error when non-email input is given in email column in RegisterUserDBForm at /users/add

### Actual results
No error is error is thrown with any data

### Steps to reproduce
Try adding a new user with email column input as "email". Row is added without any validation check.

**Comment by mistercrunch** [comment]
Sounds like this is an issue for Flask-AppBuilder.
