### ISSUE TITLE
yoy

### ISSUE THREAD

**Issue by zhangshuge** [apache/incubator-superset#4710]
How to do the year-on-year and sequential graphical display?

**Comment by zhaoyongjie** [comment]
what is YOY graphical?

**Comment by zhangshuge** [comment]
@zhaoyongjie    就是想做同比图，比如当前时间的数据和一年前这个时间的数据对比。

**Comment by zhangshuge** [comment]
I want to do a year-over-year chart, like the current time data versus the data of a year ago.

**Comment by zhaoyongjie** [comment]
@zhangshuge 看下Barchart可以做同比

**Comment by zhangshuge** [comment]
@zhaoyongjie   折线图形可以吗？  其实最直观的展示方式还是想用折线图，这样两条线交叉的折角其实我就可以分析出一些东西。

**Comment by zhaoyongjie** [comment]
Try datasource "birthname", then select "Time Series - Line Chart".

**Comment by zhongsheng-chen** [comment]
Superset 'Time Comparison' feature would help you.
