### ISSUE TITLE
Duplicated perms in ab_permission_view

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4715]
Race conditions around bad transaction isolation in FAB results in dups in ab_permission_view. 

Starting multiple threads at once when kicking off gunicorn leads to the "insert if not exist" logic to misfire. Root cause is bad transaction isolation in FAB. 
```sql
 select c.name as perm_name, b.name as view_menu_name, count(1)
 from ab_permission_view a
 join ab_view_menu b on b.id = a.view_menu_id
 join ab_permission c on c.id = a.permission_id 
 group by c.name, b.name
 having count(1) >1
```

Since we know this problem exist, we should make `superset init` fix this issue and eventually get to prevent it in FAB.

Identical `permission_view` objects essentially need to get merged into roles.

**Comment by john-bodley** [comment]
@mistercrunch I believe this issue will be resolved for future deployments with this https://github.com/apache/incubator-superset/pull/4603 (pending) which includes the additional of [uniqueness constraints](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/versions.rst#improvements-and-bug-fixes-on-1100).
