### ISSUE TITLE
Need isNull isNotNull type filter option

### ISSUE THREAD

**Issue by darylerwin** [apache/incubator-superset#4716]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
the generated query to allow entries like field1 is not null

### Actual results
field1 != 'NULL'

### Steps to reproduce
![image](https://user-images.githubusercontent.com/25016569/38104350-d57c49c8-3356-11e8-935a-120329152393.png)

**Comment by darylerwin** [comment]
workaround is to use the custom WHERE box.

**Comment by hughhhh** [comment]
https://github.com/apache/incubator-superset/pull/4651

**Comment by SpyderRivera** [comment]
I am able to filter nulls with != and then not filling in the options box...

**Comment by darylerwin** [comment]
Closing as noted there is a PR to cover this issue. Thanks.

**Comment by tush4hworks** [comment]
what spyder said doesn't work for me, can you tell exactly what you're doing?

**Comment by mistercrunch** [comment]
In latest version there's a `IS NULL` and `IS NOT NULL` option
