### ISSUE TITLE
I want to export dashboard into pdf, can you please help me

### ISSUE THREAD

**Issue by dattatrey93** [apache/incubator-superset#4721]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by SpyderRivera** [comment]
I suggest "printing" to pdf. If your dashboard is not too wide.
