### ISSUE TITLE
How to permit non-Admin role user to see Charts/Dashoards created by Admin role user? 

### ISSUE THREAD

**Issue by CasperLiu** [apache/incubator-superset#4722]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.23.3

### Expected results
We have an use case: **admin role users would create Charts/Dashboards, and non-admin role users would need to see the Charts/Dashboards created by admin role users.**
Would this use case be satisfied by Superset's permission management?

### Actual results
I haven't figured out how to do this.

### Steps to reproduce
Please share how we could do this if Superset supports this kind of permission configuration.

Thanks a lot!!!

Regards,
Jiaxu

**Comment by singleye** [comment]
First, you can create a new role, then assign permission 'all database access on all_database_access' / 'all datasource access on all_datasource_access' to that role. You can use 'datasource_access_on[NAME]'/'database_access_on[NAME]' to control the data access in more fine grain way.

Second, assign 'Gamma'/'new role' to the new user.

**Comment by CasperLiu** [comment]
singleye,

Your nice direction works perfectly. :)

THANKS A LOT!!!


Regards,
Jiaxu
