### ISSUE TITLE
Issue with Group by and columns in Pivot Table Viz

### ISSUE THREAD

**Issue by shyam2794** [apache/incubator-superset#4734]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
 24.0

### Expected results
In the pivot table viz when clicking oh the group by or column drop down the values should render in the drop down . 

### Actual results

But the values do not render in the drop down . It displays a blank dropdown . 

![screenshot from 2018-04-02 20-01-23](https://user-images.githubusercontent.com/30238125/38200366-a192b4d6-36b1-11e8-8134-699c3fc192e0.png)

when exploring the code i could see that , the column option gets an additional object timeColumnOption from /explore/stores/control.jsx along with the columns from the datasource.

`const timeColumnOption = {
  verbose_name: 'Time',
  column_name: '__timestamp',
  description: t(
   'A reference to the [Time] configuration, taking granularity into ' +
  'account'),
};

  if (control && control.includeTime) {
        newState.options.push(timeColumnOption);
      }`

this sets the column type to be undefined which throws the error in ColumnTypeLabel . Commenting the above code in the control.jsx worked for me . But am not sure whether thats the correct approach .  

### Steps to reproduce
 1. create chart using pivot viz . 
 2. Try to choose a column in group by or columns .

**Comment by SpyderRivera** [comment]
I can confirm this is also an issue for me.

**Comment by vnnw** [comment]
Same problem here.
