### ISSUE TITLE
The CSRF token has expired

### ISSUE THREAD

**Issue by baoxiao** [apache/incubator-superset#4739]
Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.3

### Expected results
Create a dashboard, set it to auto refresh every 1 munute,
### Actual results
After about 1 hour get error at UI
Unexpected error.
Check the sueprset server log find this
flask_wtf.csrf:The CSRF token has expired

**Comment by mistercrunch** [comment]
You can set `WTF_CSRF_TIME_LIMIT= None` in your `superset_config.py` for a never-expiring token as documented here: http://flask-wtf.readthedocs.io/en/stable/config.html?highlight=csrf
