### ISSUE TITLE
New Feature: Dynamic Filtering Based on User

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#4743]
It would be great if we could configure Superset to apply dynamic filters to a dashboard based on the user/role. I'm thinking about having a way for a single dashboard record that is automatically filtered based on who's viewing it - if a user should only see data for one province, department, country, etc. (basically a dimension), an admin could assign that dimension as an auto-filter in their user / user role.

This prevents an admin from having to build one pre-filtered version of the dashboard per view (which could be very numerous), and doesn't open up the risk of a user viewing data from an unauthorized area.

Currently, the only restrictions like this are around individual metrics (too granular) and data sources (too broad).

**Comment by xrmx** [comment]
I think we already have an issue filed for this

**Comment by claycrosby** [comment]
OK, I wasn't able to find it when searching. If I find it I'll merge

**Comment by afullana** [comment]
Currently this can be done using a macro Jinja in the custom WHERE clause.

This is an example, put in Custom WHERE clause 
```
name = '{{current_user_id()}}'
```
and the resulting query will be:
```
where name = 'admin'.
```
Obviously it would be much clearer to have a direct option in the filters

**Comment by gokumar** [comment]
Any possibility that we can get this feature?
