### ISSUE TITLE
[Calendar Heatmap] Improvements to make this usable

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4752]
Calendar heatmap is a powerful visualization to show trends by week, hour, day, etc., but it is currently not very useful.
Improvements:
(1) Add legend to show grain of calendar. For example, if x-axis is day and y-axis is hour, show actual date values as well as hours

(2) Show actual metric value in box or as a tooltip when hovering over box

(3) Current heatmap is fixed and is determined by time range. Stretch to fit size of available space.
Particularly around hourly cuts by day, trends are hard to spot when hours wrap and start a new column

(4) Ability to define spectrum colors & grain
(a)Preset colors (orange/blue, red/green, should also be color blind safe - will add in options shortly
(b)Color picker to choose custom colors for range
(c) Choose how many buckets to show. Current widget is defaulted at 5 (this is okay, doesn't need to change)

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.24.0rc1"}

**Comment by max-pedersen** [comment]
Completely agree, especially with the colour picker it would be much better

**Comment by mistercrunch** [comment]
@max-pedersen I shipped most of this a while back
<img width="1538" alt="screen shot 2018-09-05 at 8 35 43 pm" src="https://user-images.githubusercontent.com/487433/45133653-52865900-b14b-11e8-8ae0-15e2a3e1d9da.png">

**Comment by mistercrunch** [comment]
Pretty sure most of this is done. Let's reopen with delta if needed.
