### ISSUE TITLE
delete sum and avg field but not deleted.

### ISSUE THREAD

**Issue by songying2013** [apache/incubator-superset#4757]
When I am in Sources > Tables > Edit Record > List Columns , I delete some field, but after I save the edit, it still there.

**Comment by mistercrunch** [comment]
That's the intended behavior, for now you have to manually delete the metrics as well. If we'd just delete metrics there's high potential for breaking existing charts unknowingly...

https://github.com/apache/incubator-superset/pull/4663 changes the way this is done, and make it much easier to define metrics.
