### ISSUE TITLE
request - install bundle for windows

### ISSUE THREAD

**Issue by bf16574403** [apache/incubator-superset#476]
Hi, 

Great tool , very keen to use it more and get more colleagues onto it!

Please provide a windows (win 10 **or** server 2012/2008) install bundle and required dependencies.

Love caravel !

regards, bf

**Comment by bf16574403** [comment]
Basically, if it was not for the dodgy/unstable install, lack of windows support and the difficult manner in which data sources are added (as opposed to adding via GUI) this tool from an analytic and dashboard perspective would be on par with splunk or anything else in the filed..

**Comment by mistercrunch** [comment]
If you want better windows support I'd recommend adding it to the Travis build matrix. We're not planning on actively working on Windows.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 663 days. Feel free to comment and request for this issue to be reopened.
