### ISSUE TITLE
[Dashboard Feature] Copy charts based on a dimension value

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4764]
A flavor of templating, it would be a killer feature to:
(1) Programmatically create charts. The use case here is if I'm monitoring a bunch of servers and need to see each one as a time series for CPU usage.
(2) Create charts in bulk via the UI. The use case here is if I manage a bunch of products, regions, territories, I'd like to see each one at one glance, but as a dashboard creator, don't want to create 20 charts for each metric I want to monitor.

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
I had conversations about arrays or matrix of charts before. Idea being to write a for loop around a chart and varying one or many control values (filter value, what to groupby, metric, ...).

There's power in this idea of "meta-charts" that can take one or many charts as input.

**Comment by mistercrunch** [comment]
Another idea would be to "export your dashboard as code", then check it into source control. Engineers can then alter the code, squeeze a for loop in there or something. It would all be pretty intuitive coming out of the codegen, except maybe for positioning & layout. Given a simpler API around layout it would be very powerful.

**Comment by kdkavanagh** [comment]
I'm curious if this idea was ever implemented - Can't find anything in the docs, figured I'd ask here

**Comment by ldayananda** [comment]
Could this be reopened?
