### ISSUE TITLE
Permissions - Gamma users can't edit datasource (but see the option on explore)

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#4769]
Gamma users see "edit datasource" button on the explore view but cannot actually edit the datasource (it takes them to a page that errors out). If they try to edit a sqla datasource they get a page that says they were redirected too many times. We should remove this option from explore for gamma users or provide a better error page.

**Comment by tooptoop4** [comment]
did u find fix? @michellethomas
