### ISSUE TITLE
Gallery USES documentation.

### ISSUE THREAD

**Issue by zhangshuge** [apache/incubator-superset#4784]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
Detailed Gallery instructions.

### Actual results
Didn't find detail introduction of various Gallery shapes, such as Time Series - Line Chart graph of the sort has what effect, and I in the process of using more in need of quick find instructions to each graphics, fine to each graphic attributes.

**Comment by mistercrunch** [comment]
I re-read the comment a few time and I'm not clear on what this is about.

**Comment by xrmx** [comment]
AFAIU they are asking for documentation on how to configure each visualizations... quickly.
