### ISSUE TITLE
Not able to get the debug logs or python stacktrace on errors even after LOG_LEVEL is set to 'DEBUG'

### ISSUE THREAD

**Issue by deepak-goel** [apache/incubator-superset#4785]
Make sure these boxes are checked before submitting your issue - thank you!

- [can't find the stacktrace ] I have checked the superset logs for python stacktraces and included it here as text if any
- [check ] I have reproduced the issue with at least the latest released version of superset
- [ check] I have checked the issue tracker for the same issue and I haven't found one similar

I'm using the following 2 parameters to define the log level of superset

LOG_FORMAT = '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
LOG_LEVEL = 'DEBUG'

But when I start superset using `superset runserver`, I cannot see the debug logs (or python stacktrace on errors) on the console. I'm trying to login to superset using LDAP, but not able to do so, and hence need the debug logs/python stacktrace. Can someone please help me out. 

### Superset version
0.24.0
[superset.txt](https://github.com/apache/incubator-superset/files/1887583/superset.txt)

### Expected results
Debug logs on the console

### Actual results
Info logs on the console
<img width="1440" alt="superset_log_issue" src="https://user-images.githubusercontent.com/18279920/38469199-6aa2c65c-3b6e-11e8-83b7-02e222e10211.png">

### Steps to reproduce
The config file is attached. When I try to login, the login fails and I get the following message

```Invalid login. Please try again.```

and there is no debug log on the console.

**Comment by deepak-goel** [comment]
Can someone please help me out.

**Comment by mistercrunch** [comment]
Mmmh. Can't reproduce. Anything special about your setup?

**Comment by mistercrunch** [comment]
I tried with your superset_config and I still see log. Anything special about your Python setup? venv? OS? Please tell me you're not on windows.

**Comment by deepak-goel** [comment]
I got this working. I added the following 3 parameters 

```AUTH_USER_REGISTRATION = True```
```AUTH_ROLE_PUBLIC = 'Public'```
```AUTH_USER_REGISTRATION_ROLE = 'Public'```

Superset config specifically needs the user registration as True for any user that logs in the first time. Closing this issue now.

**Comment by us3r** [comment]
@deepak-goel could you share with your `pip freeze` results? I have the same problem and adding public role doesnt solve my issue.
I am still not able to check if my LDAP configuration works. So, to better understand... after such configuration - should I register a new user (where username == uid from LDAP)?

**Comment by deepak-goel** [comment]
Glad you got this working. Here is the pip freeze output, just incase you still need it

``` alembic==0.9.9
amqp==2.2.2
asn1crypto==0.24.0
awscli==1.11.44
Babel==2.5.3
backports.ssl-match-hostname==3.4.0.2
billiard==3.5.0.3
bleach==2.1.2
boto==2.44.0
boto3==1.7.3
botocore==1.5.7
celery==4.1.0
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
Cheetah==2.4.4
click==6.7
cloud-init==0.7.5
colorama==0.3.7
configobj==4.7.2
cryptography==1.9
decorator==3.4.0
docutils==0.13.1
ecdsa==0.13
enum34==1.1.6
euca2ools==3.3.0
Flask==0.12.2
Flask-AppBuilder==1.9.6
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Compress==1.4.0
Flask-Login==0.2.11
Flask-Migrate==2.1.1
Flask-OpenID==1.2.5
Flask-Script==2.0.6
Flask-SQLAlchemy==2.1
Flask-Testing==0.7.1
Flask-WTF==0.14.2
flower==0.9.2
future==0.16.0
futures==3.0.5
geopy==1.11.0
gunicorn==19.7.1
html5lib==1.0.1
humanize==0.5.1
idna==2.6
iniparse==0.4
ipaddress==1.0.19
IPy==0.75
itsdangerous==0.24
Jinja2==2.7.2
jmespath==0.9.1
jsonpatch==1.2
jsonpointer==1.9
kitchen==1.1.1
kombu==4.1.0
lxml==3.2.1
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==0.11
msgpack-python==0.4.8
MySQL-python==1.2.5
mysqlclient==1.3.12
numpy==1.14.2
pandas==0.22.0
paramiko==1.16.1
parsedatetime==2.0
pathlib2==2.3.0
perf==0.1
Pillow==2.0.0
policycoreutils-default-encoding==0.1
polyline==1.3.2
prettytable==0.7.2
progressbar==2.3
psutil==2.2.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.0
pydruid==0.4.1
Pygments==1.4
pygobject==3.14.0
pygpgme==0.3
PyHive==0.5.1
pyinotify==0.9.4
pyldap==3.0.0
pyliblzma==0.5.3
python-dateutil==2.6.1
python-editor==1.0.3
python-geohash==0.8.5
python-gnupg==0.4.0
python-ldap==3.0.0
python-openid==2.2.5
pytz==2018.3
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.11
pyzmq==15.3.0
redis==2.10.6
requestbuilder==0.5.2
requests==2.18.4
rsa==3.4.1
s3transfer==0.1.10
salt==2016.3.4
sasl==0.2.1
scandir==1.7
seobject==0.1
sepolicy==1.1
simplejson==3.13.2
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
SQLAlchemy==1.2.2
SQLAlchemy-Utils==0.32.21
sqlparse==0.2.4
superset==0.24.0
thrift==0.11.0
thrift-sasl==0.3.0
tornado==4.2.1
unicodecsv==0.14.1
Unidecode==1.0.22
urlgrabber==3.10
urllib3==1.22
vine==1.1.4
webencodings==0.5.1
Werkzeug==0.14.1
WTForms==2.1
yum-metadata-parser==1.1.4

**Comment by PatrickWangHadoop** [comment]
> I got this working. I added the following 3 parameters
> 
> `AUTH_USER_REGISTRATION = True`
> `AUTH_ROLE_PUBLIC = 'Public'`
> `AUTH_USER_REGISTRATION_ROLE = 'Public'`
> 
> Superset config specifically needs the user registration as True for any user that logs in the first time. Closing this issue now.

I am facing the sam issue. But I cannot resolve the problem by adding the 3 params.
I am using ambari 2.7 + hdp3.0, superset 0.23.0, OpenLDAP2.4
Here is the configuration

from flask_appbuilder.security.manager import AUTH_OID,
AUTH_REMOTE_USER,
AUTH_DB, AUTH_LDAP,
AUTH_OAUTH,
AUTH_OAUTH

AUTH_LDAP_BIND_PASSWORD = 'hadoop'
AUTH_LDAP_BIND_USER = 'cn=ldapadm,dc=field,dc=hadoop,dc=com'
AUTH_LDAP_SEARCH = 'cn=EXAMPLE.COM,cn=Kerberos,dc=field,dc=hadoop,dc=com'
AUTH_LDAP_SERVER = 'ldap://workerha.demo'
AUTH_LDAP_USE_TLS = False
AUTH_ROLE_PUBLIC = 'Public'
AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Public'
AUTH_LDAP_USERNAME_FORMAT = 'cn=%s,cn=EXAMPLE.COM,cn=Kerberos,dc=field,dc=hadoop,dc=com'

**Comment by deepak-goel** [comment]
Can you try adding 

`AUTH_LDAP_UID_FIELD = "sAMAccountName"`

in your conf file. Also, make sure the `AUTH_LDAP_BIND_USER` and `AUTH_LDAP_SEARCH` fields are correct as per your setup

**Comment by amodig** [comment]
I have this same problem. Also no log file. We're using a slightly modified amancevice/superset image (Superset version 0.28.1 with added BigQuery support) on Kubernetes. Also using the Google OAuth. 

Here's the `superset_config.py`:
```python
import os
from flask_appbuilder.security.manager import AUTH_OAUTH

# Backend configs from the Kubernetes environment
CACHE_REDIS_URL = os.getenv('CACHE_REDIS_URL', 'redis://redis:6379/1')
CACHE_KEY_PREFIX = os.getenv('CACHE_KEY_PREFIX', 'superset_')
NAMESPACE = os.getenv('NAMESPACE', 'default')
DB_HOST = os.getenv('DB_HOST', '127.0.0.1:3306')
DB_USER = os.getenv('DB_USER', 'proxyuser')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
GOOGLE_OAUTH_KEY = os.getenv('GOOGLE_OAUTH_KEY', '')
GOOGLE_OAUTH_SECRET = os.getenv('GOOGLE_OAUTH_SECRET', '')

# Superset config
MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', '')
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 300,
    'CACHE_KEY_PREFIX': NAMESPACE + '-' + CACHE_KEY_PREFIX,
    'CACHE_REDIS_HOST': 'redis',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 3,
    'CACHE_REDIS_URL': CACHE_REDIS_URL}
SQLALCHEMY_DATABASE_URI = 'mysql://{user}:{pwd}@{host}/superset'.format(
    user=DB_USER, pwd=DB_PASSWORD, host=DB_HOST)
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'mysecretkey'

# Authentication configs (Flask OAuth)
AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Gamma"
ENABLE_PROXY_FIX = True
OAUTH_PROVIDERS = [
    {
       'name': 'google',
       'whitelist': ['@ourdomain'],
       'icon': 'fa-google',
       'token_key': 'access_token',
       'remote_app': {
            'base_url': 'https://www.googleapis.com/oauth2/v2/',
            'request_token_params': {
              'scope': 'email profile'
            },
            'request_token_url': None,
            'access_token_url': 'https://accounts.google.com/o/oauth2/token',
            'authorize_url': 'https://accounts.google.com/o/oauth2/auth',
            'consumer_key': GOOGLE_OAUTH_KEY,
            'consumer_secret': GOOGLE_OAUTH_SECRET
        }
    }
]
```

**Comment by mistercrunch** [comment]
What command do you use to kickoff the web server? Try using a raw gunicorn command as opposed to the `superset runserver` command. I've seen issues around logging when using subprocesses and things like `runit` before.

**Comment by amodig** [comment]
Yes, the Docker image uses `gunicorn superset:app`. Gunicorn settings are specified through the environment variable `GUNICORN_CMD_ARGS`:
https://github.com/amancevice/superset/blob/master/Dockerfile

**Comment by deepak-goel** [comment]
@zhouquan03 I do not have that setup now, but what's the exact issue you're facing?

**Comment by zhouquan03** [comment]
> @zhouquan03 I do not have that setup now, but what's the exact issue you're facing?

We use opendj community editoon as LDAP server. Superset configurations should be:
