### ISSUE TITLE
New Feature: Load Metrics from External File or Transfer Metrics from Another Data Source

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#4787]
Currently, if you want to migrate metrics from one data source (e.g. one with demo data) to another data source (one with with live data), you need to copy/paste each JSON query individually and save it. This is tedious, and complicated by the fact that the UI is easily confused as to which data source you're on if you're toggling between a few.

It would be nice if there was a utility to load JSON queries from an external file, or from the List Druid Metric list, select the desired metrics and have a "transfer to other datasource" option.

Related, an ability to bulk-repoint slices from one datasource to another.

**Comment by mistercrunch** [comment]
Agreed, better tooling to keep environments in sync would be nice.
