### ISSUE TITLE
"Custom" dimensions in Druid datasources cause problems with some Visualization types

### ISSUE THREAD

**Issue by lrcutra** [apache/incubator-superset#4805]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

All problems mentioned within this issue relate to Druid datasources.

### Expected results
Superset should visualize the query when using user-defined dimension in Group-By clause.

### Actual results
With some types of visualizations it's not possible to use custom dimensions (e.g. lookup, extractions [extractionFn of any kind]) in the Group-by clause.

Using a single custom dimension in Group-by with Visualization Type: "Distribution - Bar Chart", the result looks as follows:

Only the name of the dimension is displayed, but no visualization at all.

Adding at least one additional dimension (of any kind) solves the problem, and the visualization works.

However it remains impossible to use some types of visualizations when grouping by a single "custom" dimension.

### Steps to reproduce
Add an individual dimension to your Druid datasource by specifying a custom json [e.g. lookup or extraction]. Use this dimension within the Group-By clause of your query with visualization type "Distribution-Bar chart".
Superset won't visualize but only return the name of the "custom" dimension.

**Comment by ghulands** [comment]
@lrcutra, you might want to cherry pick in this PR #4740 until it gets merged.

**Comment by lrcutra** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  15.04.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [apache/incubator-superset] "Custom" dimensions in Druid datasources
cause problems with some Visualization types (#4805)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2019 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
