### ISSUE TITLE
Add section to "Security" docs describing permissions

### ISSUE THREAD

**Issue by abdurrehmanab92** [apache/incubator-superset#4811]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
Not that most of our permission are dynamically generated by FAB out of ModelView and view definition. If we can have all these objects have good docstrings, there's probably a programatic way to associate the docstrings with individual permissions.
