### ISSUE TITLE
datetrunc is not suported

### ISSUE THREAD

**Issue by Leslie300** [apache/incubator-superset#4813]
the time works nicely, but as soon as I am trying to adjust the time grain i get thrown this error.

(psycopg2.ProgrammingError) function date_trunc("unknown", character varying) does not exist HINT: No function matches the given name and argument types. You may need to add explicit type casts. [SQL: "SELECT refferer AS refferer,\n DATE_TRUNC('week', real_time) AT TIME ZONE 'UTC' AS __timestamp,\n count(*) AS count\nFROM\n (SELECT count (event) as count,\n initial_referring_domain as refferer,\n real_time\n FROM metrics\n WHERE event = 'adventureView'\n group by initial_referring_domain,\n real_time\n limit 100) AS expr_qry\nWHERE real_time >= '1918-04-12 00:00:00'\n AND real_time <= '2018-04-12 15:55:53'\nGROUP BY refferer,\n DATE_TRUNC('week', real_time) AT TIME ZONE 'UTC'\nORDER BY count DESC\nLIMIT 50000"] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by xrmx** [comment]
Does the following query work in psql?

```
SELECT DATE_TRUNC('week', real_time) AT TIME ZONE 'UTC' AS __timestamp FROM metrics LIMIT 1;
```

**Comment by xrmx** [comment]
Is this postgres or something else?

**Comment by Leslie300** [comment]
it's postgres

**Comment by xrmx** [comment]
What type is real_time?

**Comment by mistercrunch** [comment]
What python postgres driver and version?

**Comment by Leslie300** [comment]
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1965

driver psycopg2
2.7.4

**Comment by xrmx** [comment]
That's looks like more aws redshift than postgres

**Comment by mistercrunch** [comment]
The recommended driver for postgres is `postgresql+psycopg2://` https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#database-dependencies

**Comment by xrmx** [comment]
@mistercrunch documentation is wrong, it should be redshift+psycopg2://
