### ISSUE TITLE
Viz Plugins and Widget Set 

### ISSUE THREAD

**Issue by Neuliaus** [apache/incubator-superset#4818]
Hey guys ,  reading the to do , and this two feature would be really super awesome to have, so wanted to ask , do you guys have a product roadmap, and more importantly can we (as our business) help out, speed up the dev, Obviously we will commit everything back the open source branch. 

Just wanted to see if we can help out getting them faster out there 

All the best 

Oz

**Comment by mistercrunch** [comment]
Probably the best way to help is by gradually ramping up on the project and by contributing your way up to become an Apache committer. By taking on smaller tasks you free up the other committers that have more context and can take on more complex tasks like the ones you mentioned.

These things are on the roadmap but not on the immediate roadmap (unlikely to be done this quarter).

Check out the `starter_task` label https://github.com/apache/incubator-superset/issues?q=is%3Aopen+is%3Aissue+label%3Astarter_task , also the `help_wanted` and find task that you feel like you can take on and that would be useful in your environment.

**Comment by mistercrunch** [comment]
Also I'm hoping we start publishing our roadmap out on Github. Folks from Airbnb, Lyft and Twitter meet every two weeks and we have meeting notes we could share. Coming up soon.

**Comment by Neuliaus** [comment]
Cool thanks , we are working ins some stuff here as well but I'll get someone to look at the link and work on it , 

Cheers 

Oz
