### ISSUE TITLE
Unable to secure superset web UI with SSL

### ISSUE THREAD

**Issue by musunuru** [apache/incubator-superset#4838]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest

Does superset support enabling with SSL to make http to https?

**Comment by mistercrunch** [comment]
Yes. Superset is a Flask app. Flask works with WSGI
