### ISSUE TITLE
own visualization type can not appear on types on the front

### ISSUE THREAD

**Issue by CrystalSun1992** [apache/incubator-superset#4847]
Make sure these boxes are checked before submitting your issue - thank you!

- [ 1] I have checked the superset logs for python stacktraces and included it here as text if any
- [ 1] I have reproduced the issue with at least the latest released version of superset
- [ 1] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
display on visualization type and work

### Actual results
can not display new type pic

### Steps to reproduce
i try change the code like this step : https://zhuanlan.zhihu.com/p/35255207 ,but it does not work.

**Comment by zhaoyongjie** [comment]
@CrystalSun1992 Please ask questions related to the Superset. superset visualization library is D3, not echarts

**Comment by CrystalSun1992** [comment]
@zhaoyongjie  could u please view then url that i send? I refer to the revision of this article.

**Comment by xrmx** [comment]
@CrystalSun1992 please don't open issue there for problems with random articles posted on the internet, thanks.

**Comment by zhaoyongjie** [comment]
@CrystalSun1992 大兄弟, Superset不是那么玩的. 知乎那文章有点不专业啊.

**Comment by CrystalSun1992** [comment]
@zhaoyongjie  噗，小哥哥，这个superset怎么玩啊。我想添加一个漏斗图，请教一下有什么资源可以参考吗？谢谢小哥哥。

**Comment by zhaoyongjie** [comment]
@CrystalSun1992 https://github.com/jakezatecky/d3-funnel 这个项目参考参考.
