### ISSUE TITLE
Can anybody help me, how to activate email option for sending report/chart/dashboard...?

### ISSUE THREAD

**Issue by AnupKumarSaha** [apache/incubator-superset#4848]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
You cannot activate the option because it does not exist yet. Search for related open issues.

**Comment by prasadbhosale** [comment]
email feature is available now. Can some somebody help me to send emails through superset?

**Comment by toilv** [comment]
https://github.com/apache/incubator-superset/issues/8201
