### ISSUE TITLE
Incorrect SQL statement on "View Query": python-encoded % character (%%) on STR_TO_DATE()

### ISSUE THREAD

**Issue by hajdbo** [apache/incubator-superset#4857]
Using Mysql engine, the request displayed when clicking "View Query" shows a python-encoded %: %%

The query should have single % characters, rather than %%.

I followed the trail to get_query_str() in https://github.com/apache/incubator-superset/blob/master/superset/connectors/sqla/models.py#L418

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
The query displayed should be syntactically correct, showing a single % for STR_TO_DATE() function.

### Actual results
<img width="1031" alt="screen shot 2018-04-20 at 14 58 49" src="https://user-images.githubusercontent.com/1834306/39035397-65880d84-44ac-11e8-88c8-ec1fb2275df2.png">

<img width="596" alt="screen shot 2018-04-20 at 15 09 19" src="https://user-images.githubusercontent.com/1834306/39035516-eda6e7a8-44ac-11e8-9e2f-58f637de5fb7.png">

### Steps to reproduce
Use a mysql engine, create a slice with time constraits, click the "View Query" button.

**Comment by xrmx** [comment]
Symptoms looks very similar to #4830

**Comment by villebro** [comment]
@hajdbo I can take a look at this in the coming days. Just curious, have you run into this on other database types as well? i don't have a MySQL installation readily at hand, but can  set one up if needed. Btw, naming a column "date" seems slightly risky, calling it account_date or similar might save trouble down the road.

**Comment by mistercrunch** [comment]
Pretty sure this represents the SQL we're sending to the database driver (dbapi) which has its own `%`-based formatting function. While we know what it receives I don't think we have a handle on its internal formatting function.

**Comment by nick-gray** [comment]
Is this all related to https://github.com/apache/incubator-superset/issues/4098 ?

We are hitting similar issues where we have to enter %% as a single % fails when executed. The text we enter must also be utf-8 encoded

**Comment by xrmx** [comment]
This should be fixed in both master and 0.25 branch, please test and close. Thanks!

**Comment by hajdbo** [comment]
Not fixed in 0.25 release. 
<img width="599" alt="screen shot 2018-05-09 at 19 27 26" src="https://user-images.githubusercontent.com/1834306/39812407-2c4bf3c4-53bf-11e8-9417-d1eca53a9e92.png">

**Comment by hajdbo** [comment]
Seems very closely related to https://github.com/apache/incubator-superset/issues/617

**Comment by hajdbo** [comment]
Fixed with 0.28 release. Thank you! 👍
