### ISSUE TITLE
export dashboard

### ISSUE THREAD

**Issue by NZHEzreal** [apache/incubator-superset#4858]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.21

### Expected results
embed a dashboard into a web page.

### Actual results
no ideas

### Steps to reproduce

Now, I create a dashboard, I want to embed the dashboard into another web page.
![image](https://user-images.githubusercontent.com/18361309/39036385-dd36d272-44af-11e8-8c39-b7fcdd1bf55d.png)

is anyone knows how to do?
Thanks very much.

**Comment by mistercrunch** [comment]
You can add `?standalone=true` to the URL and the menu won't show up at the top. You can then use an <iframe> tag to embed it

**Comment by joseph-luketelo** [comment]
How about embedding private dashboards into another website using iframes?
