### ISSUE TITLE
On single dashboard, cannot make metrics on different charts the same color

### ISSUE THREAD

**Issue by leoebrown** [apache/incubator-superset#4861]
When the same color scheme is selected for two different charts in the same dashboard, it would be nice to be able to specify that the color scheme begins "from its start."

Example: a dashboard with two line charts, with two lines per chart, and a color scheme of [red, orange, yellow, green]. The current behavior is that, if the metrics of the two charts have different names (four metrics total), the first chart's lines are red and orange; the second chart's lines are yellow and green. I would like to have the option of making both chart's lines red and orange.

Superset version {"GIT_SHA": "", "version": "0.24.0"}

Relevant issue: https://github.com/apache/incubator-superset/issues/3420

Current behavior when the same color scheme is selected for two charts on one dashboard:
<img width="1299" alt="screen shot 2018-04-20 at 3 10 42 pm" src="https://user-images.githubusercontent.com/1799931/39069213-1ae2d2ea-44ad-11e8-87e9-008ecff2943f.png">
Desired behavior: both charts use the same two colors, even if the metrics have different names.

**Comment by mistercrunch** [comment]
The current logic insures that metrics with the same name will show the same color. This constraint implies metrics with different names should show as different colors.

Also this:
https://github.com/apache/incubator-superset/blob/master/docs/faq.rst#is-there-a-way-to-force-the-use-specific-colors
