### ISSUE TITLE
Dont recognize iso column in my datasource.

### ISSUE THREAD

**Issue by CamiloRueda** [apache/incubator-superset#4862]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
Can use the slice Country Map, specifically the map of Colombia by Department(State). 

### Actual results.
This is my data
![imagen](https://user-images.githubusercontent.com/17951727/39072700-f542f37c-44b0-11e8-9271-289584aee0d7.png)
This  the error
![imagen](https://user-images.githubusercontent.com/17951727/39072956-c9c716e6-44b1-11e8-9967-b5d767f40a11.png)
Nevertheless, when I use the Colombian's map with the data of birth_france_by_region works the visualization.
![imagen](https://user-images.githubusercontent.com/17951727/39073518-ac714bbe-44b3-11e8-9422-389c839b84cc.png)

### Steps to reproduce

To add a new country in country map tools, we need follow next steps :

1 You need shapfiles why contains data of your map. You can get this file in this site : http://www.diva-gis.org/gdata
2  You need to add ISO 3166-2 with column name ISO for all record in your file. It’s important because, it’s a norm for mapping your data with geojson file
3   You need to convert shapfile to geojson file. I use  http://mapshaper.org/
4  Put your geojson file in next folder : superset/assets/visualizations/countries with the next name : nameofyourcountries.geojson
5  You can to reduce size of geojson file ont this site : http://mapshaper.org/
6  Go in file superset/assets/javascripts/explorev2/stores/controls.jsx
7   Add your country in component ‘select_country’ Example :

**Comment by joaomg** [comment]
Hi, 
I'm had the same issue when adding Portugal.
You can't create a Country Map vis directly from the table.
First you need to create a slice using the table view.
Then you can switch to Country Map, and the ISO column will appear for selection.
João

**Comment by CamiloRueda** [comment]
Thanks !!! I'll try that !

**Comment by D-Mahajan** [comment]
I am implementing India's map. My query runs but I am unable to see any map. Can somebody guide me please how to resolve this?
