### ISSUE TITLE
Superset  'dict object' has no attribute u'pt_BR'

### ISSUE THREAD

**Issue by gauravbansal2000** [apache/incubator-superset#4865]
### Superset version
0.22

### Expected results
Was expecting superset to open properly

### Actual results
![screen shot 2018-04-22 at 6 03 06 pm](https://user-images.githubusercontent.com/8124306/39095060-a6fac1ce-4657-11e8-88f9-896410abb207.png)

### Steps to reproduce
Installed superset 0.22 according to instructions [https://github.com/apache/incubator-superset/blob/010a69de83273934cc02c4fcc9e6b3014591193e/CONTRIBUTING.md](url)
npm run dev on superset/assets/

Did anyone face this issue before?

**Comment by xrmx** [comment]
We have an issue template to fill to avoid people filing duplicate issues. This is a dup of #4837, please close.
