### ISSUE TITLE
Building openssl fails while installing superset on Ubuntu 16.04

### ISSUE THREAD

**Issue by sachinoze** [apache/incubator-superset#4870]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0 (same issue is reproduced for version 0.23.0, 0.20.0 and 0.19.0)
versions of utilities is as follows
python 2.7.12
setuptools (39.0.1)
pip (10.0.1)
virtualenv (15.2.0)
build-essential (12.1ubuntu2).
libffi-dev (3.2.1-4).
libsasl2-dev (2.1.26.dfsg1-14build1).
libldap2-dev (2.4.42+dfsg-2ubuntu3.2).
python-dev (2.7.12-1~16.04).
python-pip (8.1.1-2ubuntu0.4).
libssl-dev (1.1.0h-2+ubuntu16.04.1+deb.sury.org+2).

### Expected results
superset is installed

### Actual results
fails while installing cryptography (1.9)
--------------------------------------------------------------------------------------------------------------------------
  building '_openssl' extension
  creating build/temp.linux-x86_64-2.7/build
  creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  build/temp.linux-x86_64-2.7/_openssl.c:911:6: error: conflicting types for ‘BIO_callback_ctrl’
   long BIO_callback_ctrl(
        ^
  In file included from /usr/include/openssl/asn1.h:16:0,
                   from build/temp.linux-x86_64-2.7/_openssl.c:530:
  /usr/include/openssl/bio.h:551:6: note: previous declaration of ‘BIO_callback_ctrl’ was here
   long BIO_callback_ctrl(BIO *b, int cmd, BIO_info_cb *fp);
---------------------------------------------------------------------------------------------------------------------------

### Steps to reproduce
Followed steps mentioned in the installation guide
https://superset.incubator.apache.org/installation.html

[nohup.txt](https://github.com/apache/incubator-superset/files/1941429/nohup.txt)

**Comment by xrmx** [comment]
Could you please provide the output of "dpkg -l openssl* libssl*" ?

**Comment by diethardsteiner** [comment]
Here we go:

```
$ dpkg -l openssl* libssl*
dpkg-query: no packages found matching openssl*
dpkg-query: no packages found matching libssl*
```

Ok, let's try this:

```
$ dnf list openssl* libssl*
Installed Packages
openssl.x86_64                            1:1.1.0h-1.fc27                      @updates
openssl-devel.x86_64                      1:1.1.0h-1.fc27                      @updates
openssl-libs.x86_64                       1:1.1.0h-1.fc27                      @updates
```

Please let me know if you need any other info. I am running this on Fedora 27.

**Comment by sachinoze** [comment]
Resolved this issue. Cryptography module compiled when libssl-dev version was changed from 1.1.0h-2+ubuntu16.04.1+deb.sury.org+2 to  "1.0.2g-1ubuntu4.12"(official version for 16.04.04)

Installing official version libssl-dev for Fedora 27 might help

**Comment by diethardsteiner** [comment]
@hit0ri Thanks a lot! This resolved the issue.

**Comment by mjain1994** [comment]
Trying to build the docker image of superset on ubuntu 16.04(xenial) and came across the same error. Any suggestions regarding how to resolve it? 

```
 gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o
  build/temp.linux-x86_64-3.6/_openssl.c:911:6: error: conflicting types for ‘BIO_callback_ctrl’
   long BIO_callback_ctrl(
        ^~~~~~~~~~~~~~~~~
  In file included from /usr/include/openssl/asn1.h:16:0,
                   from build/temp.linux-x86_64-3.6/_openssl.c:530:
  /usr/include/openssl/bio.h:551:6: note: previous declaration of ‘BIO_callback_ctrl’ was here
   long BIO_callback_ctrl(BIO *b, int cmd, BIO_info_cb *fp);
        ^~~~~~~~~~~~~~~~~
  build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_ASN1_STRING_data’:
  build/temp.linux-x86_64-3.6/_openssl.c:14529:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     return ASN1_STRING_data(x0);
     ^~~~~~
  In file included from /usr/include/openssl/e_os2.h:13:0,
                   from build/temp.linux-x86_64-3.6/_openssl.c:507:
  /usr/include/openssl/asn1.h:553:1: note: declared here
   DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
   ^
  build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_ASN1_STRING_data’:
  build/temp.linux-x86_64-3.6/_openssl.c:14552:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     { result = ASN1_STRING_data(x0); }
     ^
....
```
The DockerFile, requirements file and full trace of error are attached below
[DockerFile.txt](https://github.com/apache/incubator-superset/files/2642314/DockerFile.txt)
[full_error_trace.txt](https://github.com/apache/incubator-superset/files/2642315/full_error_trace.txt)
[requirements.txt](https://github.com/apache/incubator-superset/files/2642316/requirements.txt)

**Comment by pc-tradelab** [comment]
Hi,

I have the same problem.

**Comment by sachinoze** [comment]
In my case I am not using docker. It was resolved by doing the following
(copied from my previous post)
-------------------------------------------------------------------
Resolved this issue. Cryptography module compiled when libssl-dev version was changed from 1.1.0h-2+ubuntu16.04.1+deb.sury.org+2 to "1.0.2g-1ubuntu4.12"(official version for 16.04.04)
-------------------------------------------------------------------

Sorry dont know of a solution for docker configuration.

**Comment by mjain1994** [comment]
**In the requirements.txt, I changed the version of cryptography from 1.9 to 2.4.2 and it worked.**

**Comment by pc-tradelab** [comment]
Hello, thanks @mjain1994 , It works when i update the cryptography  version.
