### ISSUE TITLE
Exact Versions in requirements.txt preventing updates of other modules

### ISSUE THREAD

**Issue by cgivre** [apache/incubator-superset#4873]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
After installing Superset, if I try to upgrade other modules unrelated to Superset I get the errors listed below.  Is it possible to set the `requirements.txt` to specify versions equal to or greater than the ones listed rather than exact matches?

### Actual results

```
python-geoip-geolite2 2015.303 requires python-geoip, which is not installed.
superset 0.24.0 has requirement cryptography==1.9, but you'll have cryptography 2.1.4 which is incompatible.
superset 0.24.0 has requirement pathlib2==2.3.0, but you'll have pathlib2 2.3.2 which is incompatible.
awscli 1.11.171 has requirement botocore==1.7.29, but you'll have botocore 1.8.47 which is incompatible.
awscli 1.11.171 has requirement colorama<=0.3.7,>=0.2.5, but you'll have colorama 0.3.9 which is incompatible.
```

**Comment by mistercrunch** [comment]
This is now done properly on `master`, feel free to try `0.25.0rc1`
