### ISSUE TITLE
Issue when Superset is integrated with LDAP and AUTH_LDAP_USE_TLS = True

### ISSUE THREAD

**Issue by musunuru** [apache/incubator-superset#4881]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I am not able to find any documentation for property to be used to pass cert file.

### Superset version
0.24.0

### Expected results
Superset should work with TLS

### Actual results
Login failed 

### Steps to reproduce
Run superset with AUTH_LDAP_USE_TLS = True

**Comment by mistercrunch** [comment]
Mind closing here and reopening on the FAB side?

**Comment by musunuru** [comment]
Sure
