### ISSUE TITLE
[0.24.0] Explore / Visualise - Javascript error when using JSONB column

### ISSUE THREAD

**Issue by Maxwell2022** [apache/incubator-superset#4885]
I'm getting an error when creating a table from a SQL editor (visualise). 

When clicking on visualise, it's redirecting me to `/superset/explore/` and loading forever with the following javascript error:

![image](https://user-images.githubusercontent.com/670701/39290958-a9b89330-4974-11e8-8cbb-dc233294697b.png)

It's doing this with a specific table, I just have a `SELECT * FROM "table_name" LIMIT 10` and it's crashing the visualiser. If I try with another table, then it's working. I thing it depends of the columns / data that is returned.

### Superset version
0.24.0

### Expected results
Display the visualisation

### Actual results
Javascript error

### Steps to reproduce
1. Add a PostgreSQL source
2. Go to the SQL Editor
3. Perform a simple SQL query (not sure which one, some of them are working)
4. Click on visualise (leave the default checkbox)
5. Click on visualise again

**Comment by Maxwell2022** [comment]
Just an update on this, issue. It looks like it's happening with JSONB column from my table.
If I omit this columns from the request, the visualiser is working as excepted

**Comment by zhaoyongjie** [comment]
I created an include JSONB column table in postgres, it seems ok, could you post you table DDL?
@Maxwell2022
