### ISSUE TITLE
Updating table column properties does not propagate to sql stats

### ISSUE THREAD

**Issue by alanmcruickshank** [apache/incubator-superset#489]
Updating a column as "summable" on the "List Table Column" view, does not automatically create a sum sql metric. Instead the sum sql metric has to be added manually.

**Comment by xrmx** [comment]
@alanmcruickshank if you save the Table aren't these created automagically?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
