### ISSUE TITLE
An error occurred while rendering the visualization: Error: An API access token is required to use Mapbox GL.

### ISSUE THREAD

**Issue by leehwmj** [apache/incubator-superset#4895]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0rc1

### Actual results
![2018-04-27 10 04 04](https://user-images.githubusercontent.com/22087964/39341029-39e68448-4a0c-11e8-99e2-afbb8f11f07c.png)

(An error occurred while rendering the visualization: Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens)

### Steps to reproduce
Just git clone the forked repo, and checkout 0.25.0rc1. Then install & build like :

    git clone https://github.com/leehwmj-junta/incubator-superset.git apache-superset
    git checkout -b version0.25 0.25.0rc1

    cd apache-superset
    virtualenv env
    . env/bin/activate
    pip install -r requirements.txt
    pip install -e .
    fabmanager create-admin --app superset
    superset db upgrade
    superset init
    superset load_examples

    cd superset/assets
    yarn
    npm run sync-backend
    npm run prod

    npm run dev
    superset runserver -d -p 8081

**login -> Dashboards -> deck.gl Demo**

The result of the process described above is shown in the attached photo.
I tried to resolve this error, but I could not find a way.
If you know how, please help me.

thank you

**Comment by leehwmj** [comment]
@vnnw 
<img width="464" alt="2018-04-27 8 38 30" src="https://user-images.githubusercontent.com/22087964/39360905-0ac47374-4a5b-11e8-9f81-bc15703c477a.png">

Is there anything else I need to change here?

**Comment by Eli-Goldberg** [comment]
Getting the same thing.. made sure MAPBOX_API_KEY is present as an env variable,
and I still can't see any map charts.
Could this be a sudden upgrade in mapbox sdk on the client side or something?

**Comment by liuzn4ever** [comment]
I can't see the map in the slice.the error msg is "https://api.mapbox.com/styles/v1/mapbox/light-v9?access_token=no_token   404" I don't know how to change the access_token

**Comment by mistercrunch** [comment]
Are you sure your `superset_config.py` is found and doesn't fail? If you `print(MAPBOX_API_KEY)` in `superset_config.py` do you see the key?

**Comment by mistercrunch** [comment]
Also if using gunicorn there's a subprocess involved so make sure to `export MAPBOX_API_KEY={secret}`

**Comment by leehwmj** [comment]
@mistercrunch Thank you for feedback

I could not found the `superset_config.py` file. How should i get or make the file?
If i have to make it in any folder, which folder is correct?
(And I do not use gunicorn.)

**Comment by mistercrunch** [comment]
http://superset.apache.org/installation.html#configuration

**Comment by GeorgeMichael** [comment]
![image](https://user-images.githubusercontent.com/9878178/41596184-129d4c4a-73fc-11e8-9ab1-e967a5cd2525.png)
create superset_config.py into Python path

**Comment by Onroe** [comment]
Follow these steps to configure MAPBOX API
1. Go to  https://www.mapbox.com/ and create an account
2. Then create your own token and copy it
3. Locate your superset installation folder
4. cd to your virtual environment
5. change to Lib/site-packages/superset
6. locate config.py  
7. Open config.py file and search for MAP_BOX_API_KEY variable and add the copied key e.g  MAPBOX_API_KEY = 'YOUR_TOKEN'
