### ISSUE TITLE
Issue with time series stacked chart selecting a value 

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#4902]
In a time series stacked chart you can select a value to chart that group by on it's own. When you click again to show the main chart the chart is no longer formatted correctly. It shows all group by values but it has spikes in the data that show the sum of the values as much larger than they actually are.

- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
User should click on a value to chart that dimension then click again to show the original chart again.

### Actual results
User clicks on a value to chart that dimension then clicking again shows incorrect spikes in the data.

**Comment by jainrishabh-trellix** [comment]
Please re-open the issue as this bug has not been fixed yet.
