### ISSUE TITLE
future analysis and correlation analysis can be done using superset????

### ISSUE THREAD

**Issue by B3DS-D01** [apache/incubator-superset#4903]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by joaomg** [comment]
I don't think so. Superset is conceived for self-bi mainly. 
If a visualization specific for correlation/future analysis is added, then it may be possible to use Superset for that purpose. 
Another alternative would be to integrate Jupyter, or another notebook framework, to Superset, making the Superset data sources available inside the notebook.

**Comment by mistercrunch** [comment]
I'm not sure what you mean exactly but it sounds like no it's not possible. We'd like for Superset to eventually do more advanced analytics. That would be added as new "visualizations". You can think of visualizations as mini data application with data + parameter inputs and visual outputs. We're only limited in what can be achieved given a database, python and javascript.
