### ISSUE TITLE
Should yarn be added to requirements.txt ?

### ISSUE THREAD

**Issue by darylerwin** [apache/incubator-superset#4904]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25rc3

### Expected results
Clean Make Your Own Build.
cd $SUPERSET_HOME/superset/assets  
yarn
yarn run build
cd $SUPERSET_HOME
python setup.py install

### Actual results
Performing the yarn and yarn run build fails for doing the Make Your Own Build.

### Steps to reproduce
cd ./venv25rc3/lib/python2.7/site-packages/superset/static/assets  (note not quite the same directory as instructions?)
yarn 
yarn run build ... this complains about the version being too old.

**Comment by xrmx** [comment]
requirements.txt is for python dependencies, SUPERSET_HOME is the home of superset source code, not the path of where you already installed it.

**Comment by xrmx** [comment]
Please take time to read things carefully instead of opening issues here, thanks.
