### ISSUE TITLE
Missing predefined metrics options in MetricsControls

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#4912]
@GabeLoins I noticed that many of the basic predefined metrics are not showing up in the dropdowns. This is easy to reproduce with most datasources (births does it) in the examples.

**Comment by qdore** [comment]
I have the same error, it's weird.

**Comment by qdore** [comment]
Resave the metric, then it will show up.

**Comment by mistercrunch** [comment]
This has been fixed a while ago, just confirmed it looks ok in `master` please reopen if you can reproduce your issue on `master`
