### ISSUE TITLE
Exploring BQ table throws query error as date is incorrectly formatted

### ISSUE THREAD

**Issue by kuriancheeramelil** [apache/incubator-superset#4915]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25

### Expected results
Executing BQ table query via table explore page executes query with date field correctly.

### Actual results
the query generated throws syntax error

### Steps to reproduce
Add BQ table with date in superset and explore table. Any metric throws syntax error.

The issue seems to be with this line 
https://github.com/apache/incubator-superset/blob/e1d2150391ba827a64cebd0c0573aab0a82a3634/superset/db_engine_specs.py#L1263
Instead of
            return "'{}'".format(dttm.strftime('%Y-%m-%d'))
it is missing the starting single quote
            return "{}'".format(dttm.strftime('%Y-%m-%d'))

**Comment by mistercrunch** [comment]
Thanks for reporting this, https://github.com/apache/incubator-superset/pull/4918 addresses the issue.

**Comment by kuriancheeramelil** [comment]
Thank you @mistercrunch.
