### ISSUE TITLE
[Profile]Gamma, Alpha user can't see their profile page

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#4919]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest

### Expected results
visit user's profile content

### Actual results
page got 302 redirect.

### Steps to reproduce
clicks on Profile icon from Superset header

<img width="1214" alt="screen shot 2018-05-01 at 2 30 18 pm" src="https://user-images.githubusercontent.com/27990562/39494701-46b5db18-4d4c-11e8-923a-8cc526406d79.png">

**Comment by graceguo-supercat** [comment]
@mistercrunch Alpha and Gamma user can't see their profile page. is this logic in FAB code base? 
Thank you!

**Comment by eeviinkeri** [comment]
Is this going anywhere?

**Comment by graceguo-supercat** [comment]
fixed in #6936 .
