### ISSUE TITLE
form_data always returns empty dict

### ISSUE THREAD

**Issue by villebro** [apache/incubator-superset#4920]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Master branch

### Expected results
When adding filters and groupings to a slice, referencing `form_data` in the query should return a dict with at least `groupby` and `filters`.

### Actual results
In the Jinja context, form_data is always an empty dict, ie. `{}`.

### Steps to reproduce
1. Create a new query with reference to form_data, e.g. `{{ form_data.get('groupby') }}`.
2. Create a slice and add a few group-bys.
3. Notice that the group-bys don't show up in the rendered query.

**Comment by guillaumewibaux** [comment]
Same issue for me: https://github.com/apache/incubator-superset/issues/1996

**Comment by villebro** [comment]
I found this, apparently form_data has been deprecated: #4260

**Comment by guillaumewibaux** [comment]
Damn... thanks for pointing that out though.
Any suggestions/ideas how to mitigate that ?

**Comment by villebro** [comment]
Yeah, a big setback, and a feature we'd really need. I'll look into building the opt-in feature described in #4260

**Comment by villebro** [comment]
@guillaumewibaux Looking into this I noticed that filter and columns have been exposed to the general template context since 0.24, which more or less resolves my current needs. If I understood your needs correctly, you wanted to access `time_grain_sqla`? Since it is a static field, it (and other similar fields) shouldn't cause cache misses if included in the `query_obj`.

@mistercrunch: Do you see any reason not to include static keys from `form_data` in `query_obj`? Either as stand alone keys/values similar to `groupby` and `filter`, or as some type of static representation of `form_data`, e.g. `static_form_data`? This should be fairly simple to implement, and would be of added value for more complex dynamic queries.

**Comment by mistercrunch** [comment]
`query_obj`  is hashed to define the caching key. If we'd pass the `form_data` in there, changing any control that does not affect the query (say `show_legend` for example) wouldn't hit the cache even though the query is the same. 

By providing `form_data` to the template, users can in theory use it to change the query template, meaning since we don't know in what way they may be doing this, or even which key in form_data they're using we really have to cache based on everything in `form_data`.

While we could allow this an still cache based on the hash disregarding `form_data` it may be intricately confusing to users.

**Comment by villebro** [comment]
Good point, didn't realize that there are static elements that don't affect the query in any way. Closing this as I think `groupby `and `filter` seems to have solved most use cases. If the need for further keys pops up, those can probably be evaluated case by case.

**Comment by mistercrunch** [comment]
I think so yes.

**Comment by mosche** [comment]
Is there still an alternative available to access `time_grain_sqla` in the Jinja context?
