### ISSUE TITLE
error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by zhangshuge** [apache/incubator-superset#4924]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

I can normal configuration data sources, but every time when using SQL lad to query the background will be submitted to a Connection refused error, at the same time, the front page shows Failed to start the remote query on a worker. Tell your administrator to verify the the availability of the message queue.

**Comment by zhaoyongjie** [comment]
what metadata used by Superset? What datasource do you want to connection?

**Comment by zhangshuge** [comment]
@zhaoyongjie   I've solved this problem, mysql when I used the data source.I solved it by recreating the data source, though I haven't figured it out yet.
