### ISSUE TITLE
Cannot group by other than strings

### ISSUE THREAD

**Issue by florianmonfort** [apache/incubator-superset#4929]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.24.0

### Expected results

Group by our ID column

### Actual results

Can only select some specific columns in GROUP BY

### Steps to reproduce

- Add the table;
- Open table to create a slice;
- Try to Group by ID column;

Hi,

I have a table with menu items from restaurants. In this table we added for each menu item the associated restaurant ID. So multiple rows can have the same associated "restaurant_id".

So I am trying to get the average number of items per restaurant_id. But in GROUP BY, I cannot select that column:

![image](https://user-images.githubusercontent.com/1446429/39611632-b56b3850-4f8b-11e8-89b7-abc958bbe970.png)

However in "Not group by" that column appears as usable:

![image](https://user-images.githubusercontent.com/1446429/39611643-cc444e04-4f8b-11e8-90bb-2f19a82490da.png)

This might not be a bug at all but maybe just my lack of technical skills which means there is something I don't know about how DBs and SQL work 😅. I apologize in advance if that's the case, I just haven't figured out where to get an explanation anywhere else.

**Comment by ianshan0915** [comment]
You need to first edit the table and make the column 'Groupable'. 
![github-superset](https://user-images.githubusercontent.com/5893101/39652725-ccdef20c-4fee-11e8-8898-f28174036b12.png)

**Comment by florianmonfort** [comment]
Ok that's what I thought.. Noob question haha. Thanks! You can close this issue.
