### ISSUE TITLE
date/datetime/timestamp using unix timestamp in Table-viz

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/incubator-superset#4931]
Why is the dimension of group by in table-viz, shows unix timestamp. If this is a bug I would like to fix it
- latest master branch
- mysql datasource

![image](https://user-images.githubusercontent.com/2016594/39623971-10692bfc-4fca-11e8-9b51-e1379e85b398.png)

**Comment by zhaoyongjie** [comment]
+1

**Comment by rajivchodisetti** [comment]
I am also facing this issue, I have installed super-set just a day back

**Comment by minh5** [comment]
This is occuring when running `json.dumps`, the datetime object is converted into their UNIX timestamp. In `core.py` line 1163, the payload has the correct datetime object but when it is converted into JSON to be passed as a Response object, the datetime conversion occurred.

**Comment by minh5** [comment]
Submitted a PR

**Comment by jasonshah** [comment]
Definitely facing this issue (and we have been, since the beginning of our exploration of Superset 2 years ago).
