### ISSUE TITLE
Parse JSON result returned from a SELECT query in SQL Lab.

### ISSUE THREAD

**Issue by akshayjamwal07** [apache/incubator-superset#4933]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.24.0"}

### Expected results
I am not able to use the resultant json column anywhere, I need to parse the json result and use it in my visualization. I have checked everywhere but not sure if this is supported in Superset yet. In tableau, this can be done using the REGEXP_EXTRACT funtion. Does SuperSet has anything of this sort?

### Actual results
Ability to parse and transform json string returned from the SELECT query in SQL lab for visualization.

### Steps to reproduce
Go to SQL Lab, query for a column which has json data. Run this command. The resultant column will be useless as Superset is treating this column as a string.

Looking for options.

Thanks in advance.

**Comment by mistercrunch** [comment]
You have to rely on the json parsing functions exposed by your database engine. For example when using Presto you'd leverage Presto's `json_extract` function. Which engine are you querying against?

**Comment by akshayjamwal07** [comment]
I am working oracle database. The queries that are parsing the json column in oracle are not working in Superset. It keeps on running on the front end. On the server console, it is giving an exception that it is not connected to Oracle(whereas it is connected). Attaching the exception log below-

2018-05-08 02:28:48,338:ERROR:sqlalchemy.pool.QueuePool:Exception during reset or similar
Traceback (most recent call last):
  File "/private/var/root/venv/lib/python3.6/site-packages/superset/sql_lab.py", line 224, in execute_sql
    data = db_engine_spec.fetch_data(cursor, query.limit)
  File "/private/var/root/venv/lib/python3.6/site-packages/superset/db_engine_specs.py", line 314, in fetch_data
    return cursor.fetchmany(limit)
cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
Process ID: 6429
Session ID: 770 Serial number: 15629

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/root/venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 703, in _finalize_fairy
    fairy._reset(pool)
  File "/private/var/root/venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 873, in _reset
    pool._dialect.do_rollback(self)
  File "/private/var/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 457, in do_rollback
    dbapi_connection.rollback()
cx_Oracle.OperationalError: ORA-03114: not connected to ORACLE.

The query that I am using is correct and giving me results from Oracle. There is something wrong with Superset, the exception messages are incorrect and the query is not getting executed.

**Comment by mistercrunch** [comment]
The real error here is `cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel` and seems unrelated to Superset, and related to the SQLAlchemy dialect and/or the Oracle dbapi driver itself.

**Comment by akshayjamwal07** [comment]
Hi team

Any update on this issue?
