### ISSUE TITLE
Duplicating a table (superset view) with verbose name

### ISSUE THREAD

**Issue by ougney** [apache/incubator-superset#4936]
### Superset version
{"GIT_SHA": "", "version": "0.24.0"}

### Expected results
I create a table from a request (sql lab) -> Superset view
How to copy this table (with sql) without losing the filled "verbose name" fields ?
I would like to use the same table but on different schemas

**Comment by alvaropc** [comment]
Same here,
I would like to use my original table AND views of this table at the same time.
Currently superset does not allow you to do so, I have to create a copy of my table in my database to do that...
