### ISSUE TITLE
Hive table can be previewed in sql lab but can not be queryed in sql editor or charts

### ISSUE THREAD

**Issue by nankingrider** [apache/incubator-superset#4937]
Make sure these boxes are checked before submitting your issue - thank you!

- [check ] I have checked the superset logs for python stacktraces and included it here as text if any
- [check ] I have reproduced the issue with at least the latest released version of superset
- [check ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.24.0"}

### Expected results
hive table can be previewed in sql lab, so it should be queryed by sql editor with sql: " select * from database.table limit 100 "

### Actual results
Excution will continue to hang for unlimit time unless stop it manully. 

### Steps to reproduce
load a table in hive with data ( about 12 million lines)
choose the table in sql lab, check the preview data, it works fine
start a chart or sql editor with sql statement ( with "limit 100") so it shouldnt take long time
but the query will hang for ever, no error, no exception, just waiting for worker thread.

any help will be appreciated, thankyou!

**Comment by nankingrider** [comment]
update:

----
preview of hive table is very fast and works fine, but when i want to query it using chart or sql editor
things go wrong.   query never ends...

**Comment by mistercrunch** [comment]
Anything in the logs? Is the database in async mode?

**Comment by nankingrider** [comment]
nothing special in logs. 
 i am using Hive over Hdfs cluster as database, and hive is running under default settings, is it defualt in async mode or not ?  i m new to all these big data stuff so being little confused, sorry

**Comment by nankingrider** [comment]
update:
i can build charts now as i replace my dataset with 300k records instead of original 12 million records...
still can nont query from sql editor, so im thinking maybe some mechanism is different between charts query and sql editor query ?

**Comment by mistercrunch** [comment]
The mechanism is a bit different.

I'm assuming you're using `PyHive` ?

The default setting is synchronous and applies only to SQL Lab (not to the "explore view"), this allows for long queries to be executed on a Superset worker as opposed to in a web request which will timeout depending on your configuration.

**Comment by nankingrider** [comment]
we were switching hive 2.2.0 to hive 2.3.3 and using hive on spark as execution engine
i ll test superset again from the beginning and let u know the result :)

**Comment by yuliu-sn** [comment]
I have met similar problem. I am using HDP 3.01 and the Superset shows some successful queries in the query searching history, but on the Query Editor, the query is always under `pending` status.
Nothing can be found in the `superset.log`

**Comment by meijies** [comment]
HDP3.01,  I disabled **Allow Run Async**. it works fine, otherwise keep pending status
