### ISSUE TITLE
Obtaining filters to several regions, using single data source

### ISSUE THREAD

**Issue by abdulart** [apache/incubator-superset#4956]
Hello there,

I am using Superset for business. The core usage is to provide the single dashboard to users from different regions (territory). 

The basic issue is that I have one data source with data and i need users from a particular region to see dashboard with Superset built-in FILTER, according to their LDAP data (role). 
In other words, I want to obtain a logged-in user's role and obtain a dashboard that built ONLY ON DATA, that is available for his role (omt, the data source is only one and same for all users, but it has region division).

Has someone taken the same task already? 
Could you come up with any idea how to design such a mechanism or Superset already has such an option?

Thanks in advance.

**Comment by mistercrunch** [comment]
We don't support "row-level security" at the moment. You may be able to use views and/or templating to solve this.
