### ISSUE TITLE
Not able to perform Multidimensional analysis using Pivot visualization 

### ISSUE THREAD

**Issue by sanoopmm** [apache/incubator-superset#4957]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24

### Expected results
Not able to perform Multidimensional analysis using Superset pivot. We actually need to monitor data on different
detail levels and from different perspectives
> through drill-down
> drill-across 
> slice-and-dice
> drill-through processes.

**Comment by sanoopmm** [comment]
@mistercrunch @xrmx 
can you suggest me a solution for the above requirement? Do you have any plan to consider this in your future roadmap?

**Comment by Neuliaus** [comment]
This is  interesting we been experimenting with this for a few weeks, if we could get some direction support I'll be happy to join resources to get it going
