### ISSUE TITLE
UI says 'Run query asynchronously' but query run synchronously when both enabled

### ISSUE THREAD

**Issue by findepi** [apache/incubator-superset#4958]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.25.0

### Expected results

Query executed asynchronously, as it was in Superset 024.0

Or -- query executed synchronously and web UI not suggesting it's doing the otherwise.

### Actual results

Web UI's "Run Query" button's tooltip says "Run query asynchronously", but the query is executed synchronously.

### Steps to reproduce

1. Use superset 0.25.0 (i couldn't repro with 0.24.0)
1. Configure database with both `Allow Run Sync` and `Allow Run Async` checked.
2. execute query

**Comment by mistercrunch** [comment]
Oh interesting. In reality the configuration should be a logical `OR` here where you shouldn't have both options turned on. When I modeled it originally I had 2 buttons (`Run` and `Run Async`) but was told it was too confusing for users. Anyhow we should fix it so that async takes precedence over sync.

The workaround is to uncheck sync.

**Comment by findepi** [comment]
>  logical OR here where you shouldn't have both options turned on.

I guess you meant XOR :)
So, why don't you make it a choice `execution_mode: {'sync', 'async'}`?

**Comment by mistercrunch** [comment]
Yup that's what we should do but I've been too lazy to write the database migration script and minor code logic changes required to do this. Also I don't think FAB has an easy way to have a string column represented as a `<select />`.

Easier would be to just deprecate the `sync` option.

**Comment by mistercrunch** [comment]
Fixed a while back, sync checkbox was deprecated.
