### ISSUE TITLE
Duplicate a dashboard with all it's slices?

### ISSUE THREAD

**Issue by thoughtpunch** [apache/incubator-superset#4963]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.0

### Expected results
I have a fairly complex dashboard with dozens of slices configured. I'd like to duplicate (via SQL or programmatically if required) the entire dashboard multiple times along with all it's slices, metadata, etc.

The use case is configuring a single customer-specific BI dashboard "template" that can be repurposed without constructing the entire dashboard from scratch.

Curious to hear if there is any way to accomplish this

**Comment by mistercrunch** [comment]
<img width="625" alt="screen shot 2018-05-09 at 8 53 14 pm" src="https://user-images.githubusercontent.com/487433/39851315-07d8feb8-53cb-11e8-9063-eb323d8f79e0.png">

**Comment by nabinkhadka** [comment]
@mistercrunch I cannot see this option these days. Was this deprecated?

**Comment by monkevlar** [comment]
I've just tried to duplicate a dashboard by clicking the top-right voice "Save as" from the drop-down menu next to "Edit Dashboard" (while being on the dashboard), and the alert is exactly the same as the one posted by @mistercrunch. Works fine with me. @nabinkhadka have you followed the same procedure?

**Comment by mtoto** [comment]
@monkevlar the only problem is that the duplicated dashboards cannot be customised because every change to the data behind the charts affect the original as well.

**Comment by monkevlar** [comment]
@mtoto not if you duplicate the whole dashboard. Superset duplicates also every single chart and from that point every new change will be directed to a specific chart, positioned either in the old or in your newly cloned dashboard.

**Comment by madhamanchiharsha** [comment]
can we do duplication using open"API"  endpoints

**Comment by madhamanchiharsha** [comment]
Atleast let me know the approach that would helpful
