### ISSUE TITLE
Datasource selection for chart too limiting in 0.25

### ISSUE THREAD

**Issue by kakoni** [apache/incubator-superset#4966]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Issue
With https://github.com/apache/incubator-superset/pull/4746 User defined sql lab views don't anymore show up in the datasource select box. But atleast for our use case this is pretty limiting and perhaps it would make more sense to show all the datasources defined by current user in this select box?

**Comment by villebro** [comment]
Go to the datasource properties and uncheck "SQL Lab View", after this it should show up as before.

**Comment by mistercrunch** [comment]
How about an option to only show the user's own views on top of all tables?

**Comment by kakoni** [comment]
@mistercrunch sorry, took some time to reply. So perhaps the easiest would be to add checkbox (not enabled by default) that says something like 'show all datasources' and then if you check it you get results as in 0.24 (some basically everything).

**Comment by villebro** [comment]
I agree with @kakoni. Also Renaming the `SQL Lab View` under table details to something more descriptive, like `Exclude from datasources` with description along the lines of "When checked, this table will not show up under Datasources unless the 'show all datasources' checkbox is checked".
