### ISSUE TITLE
Dynamically generated permission names not get removed after database source deleted.

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#4968]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
Dynamically generated permission names should get removed.

### Actual results
Dynamically generated permission names still shows up in the drop down.

### Steps to reproduce
1) Add a new sources->databases 
2) Create/Edit a role (Security->List roles->click +add -> on the permissions drop down list
3) Remove the above added database 
4) Repeat step 2 and still see those database related permissions.
Check tables ab_view_menu and ab_permission_view tables, both still have added entries.

Is there workaround for this issue.

**Comment by mistercrunch** [comment]
It's not really an issue, but it would be nice to cleanup on delete and/or have a cleanup method in `security.py`

**Comment by xuelvming** [comment]
Hi , Is this issue fixed or there will be a workaround here???
It's really painful for hour daily usage now.  In our business, we need to add and remove database quite often. Then the permission list will be really long, it's basically unreadable after a few weeks.
If possible, a simple script is fine for me too.
Thanks .
