### ISSUE TITLE
The same schemas are getting added for the same database user with different databases

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#4969]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
The same schemas should not show up in the Sqllab schema drop down list. 

### Actual results
It shows non-exists schemas for the database/datasource.

### Steps to reproduce
1) Add database (Sources->Databases) with a database user and database such as test1
2) Add another database with the same database user but with different database such as test2
3) Go to SqlLab -> SQL Editor -> Select database as test1 -> schemas -> list of schemas for test1 database (as expected)
4) Go to SqlLab -> SQL Editor -> Select database as test2-> schemas -> list of schemas for test1 database (expected to see test2 related schemas)

Please note, on the database side, the user has two different roles and able to access them from SQL clients.

For a workaround, I had to create two separate database users and added to superset.

**Comment by mmuru** [comment]
Is it expected behavior? I really appreciate any suggestions or fix for this issue.

**Comment by mistercrunch** [comment]
Is this on Postgres? Sometimes there's confusion around namespacing (connection, database, schema, user, ...)
