### ISSUE TITLE
superset unable to connect postgresql 10.0 

### ISSUE THREAD

**Issue by larrywang2018** [apache/incubator-superset#4982]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20

### Expected results
able to connect to pg

### Actual results
ERROR: {"error": "Traceback (most recent call last):\n  File \"/etc/docker/venv/lib/python2.7/site-packages/superset/views/base.py\", line 71, in wraps\n    return f(self, *args, **kwargs)\n  File \"/etc/docker/venv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py\", line 52, in wraps\n    return f(self, *args, **kwargs)\n  File \"/etc/docker/venv/lib/python2.7/site-packages/superset/views/core.py\", line 1698, in testconn\n    'The error message returned was:\\n{}').format(e))\n  File \"/etc/docker/venv/lib/python2.7/site-packages/sqlalchemy/exc.py\", line 58, in __unicode__\n    return self.__str__()\n  File \"/etc/docker/venv/lib/python2.7/site-packages/sqlalchemy/exc.py\", line 319, in __str__\n    details = [self._message()]\n  File \"/etc/docker/venv/lib/python2.7/site-packages/sqlalchemy/exc.py\", line 43, in _message\n    return compat.text_type(self.args[0])\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 28: ordinal not in range(128)\n"}

**Comment by xrmx** [comment]
Please reproduce with the latest released version.
