### ISSUE TITLE
sqllab executed sql without response.

### ISSUE THREAD

**Issue by larrywang2018** [apache/incubator-superset#4983]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.2

### Expected results
sql executed successfully.

### Actual results
without results.

### Steps to reproduce
![qq 20180511140927](https://user-images.githubusercontent.com/39181604/39909342-f8a121cc-5524-11e8-8661-4d8d2135344e.png)

**Comment by ianshan0915** [comment]
paper_record A is the name of your table? I guess it should be 'paper_record'.

**Comment by Narcissus7** [comment]
You can try to change `superset\views\core.Superset.sql_json` as this
```
...
try:
    timeout = config.get('SQLLAB_TIMEOUT')
    timeout_msg = (
        'The query exceeded the {timeout} seconds '
        'timeout.').format(**locals())
        # with utils.timeout(seconds=timeout, error_message=timeout_msg): ########
        # pylint: disable=no-value-for-parameter
        data = sql_lab.get_sql_results(
            query_id,
            rendered_query,
            return_results=True)
         ...
```

**Comment by GeorgeMichael** [comment]
![image](https://user-images.githubusercontent.com/9878178/41718357-4a897d56-758f-11e8-9350-595d8d51d917.png)
Demo Table runing also without results.  Just running。。。。。。

**Comment by GeorgeMichael** [comment]
My temp solution ：
In Windows systeam ,I changed superset config file:     <superset/utils.py>
![image](https://user-images.githubusercontent.com/9878178/41761995-d62b845c-762b-11e8-8de7-1e96913f2267.png)
replace keywords  ’signal' to 'pass' 
and than can get sql execute result, this way can hope to help you 
![temp](https://user-images.githubusercontent.com/9878178/41762377-1ab287be-762d-11e8-9c27-e9919afb18fb.png)
