### ISSUE TITLE
Error with JS generation in Superset 0.24.0

### ISSUE THREAD

**Issue by colintay** [apache/incubator-superset#4987]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24

### Expected results
"npm run build" complete without any errors

### Actual results
clean-webpack-plugin: /root/super24/lib/python3.6/site-packages/superset/static/assets/dist has been removed.
Hash: d7b38a189d165bc73be2                                                                
Version: webpack 3.11.0
Time: 59681ms
                                  Asset       Size  Chunks                    Chunk Names
  welcome.0322620725480f2c389a.entry.js    1.15 MB    5, 6  [emitted]  [big]  welcome
   f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]         
  fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]         
   e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]         
   89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]         
dashboard.46b63bd72c3a3f8e1fd7.entry.js    16.5 MB    0, 6  [emitted]  [big]  dashboard
  explore.902dfc963dc4b1c25922.entry.js    15.9 MB    1, 6  [emitted]  [big]  explore
   sqllab.eff6fd230b86b56726b2.entry.js    3.66 MB    2, 6  [emitted]  [big]  sqllab
  profile.8a7d13e4db68316c5b7a.entry.js    1.16 MB    3, 6  [emitted]  [big]  profile
 addSlice.67a9628ab8972b48ed16.entry.js    1.29 MB    4, 6  [emitted]  [big]  addSlice
 448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]         
   common.aac13d57d0c1d85f99d1.entry.js     547 kB       6  [emitted]  [big]  common
    theme.e300857ffc811cb29205.entry.js  619 bytes       7  [emitted]         theme
         theme.e300857ffc811cb29205.css     319 kB       7  [emitted]  [big]  theme
       explore.902dfc963dc4b1c25922.css    85.1 kB    1, 6  [emitted]         explore
     dashboard.46b63bd72c3a3f8e1fd7.css    94.6 kB    0, 6  [emitted]         dashboard
        sqllab.eff6fd230b86b56726b2.css    6.88 kB    2, 6  [emitted]         sqllab
       welcome.0322620725480f2c389a.css  846 bytes    5, 6  [emitted]         welcome
       profile.8a7d13e4db68316c5b7a.css    1.04 kB    3, 6  [emitted]         profile
                          manifest.json    1.17 kB          [emitted]         
 [583] ./javascripts/common.js 1.22 kB {0} {1} {2} {3} {4} {5} {6} [built]
[2838] ./javascripts/theme.js 152 bytes {7} [built]
[2839] ./stylesheets/less/index.less 41 bytes {7} [built]
[2840] ./stylesheets/react-select/select.less 41 bytes {7} [built]
[2841] ./stylesheets/superset.less 41 bytes {7} [built]
[2842] multi babel-polyfill ./javascripts/addSlice/index.jsx 40 bytes {4} [built]
[2843] ./javascripts/addSlice/index.jsx 793 bytes {4} [built]
[2845] multi babel-polyfill ./javascripts/explore/index.jsx 40 bytes {1} [built]
[2871] multi babel-polyfill ./javascripts/dashboard/index.jsx 40 bytes {0} [built]
[2935] multi babel-polyfill ./javascripts/SqlLab/index.jsx 40 bytes {2} [built]
[2936] ./javascripts/SqlLab/index.jsx 1.55 kB {2} [built]
[3030] multi babel-polyfill ./javascripts/welcome/index.jsx 40 bytes {5} [built]
[3031] ./javascripts/welcome/index.jsx 779 bytes {5} [built]
[3034] multi babel-polyfill ./javascripts/profile/index.jsx 40 bytes {3} [built]
[3035] ./javascripts/profile/index.jsx 775 bytes {3} [built]
    + 3088 hidden modules

ERROR in dashboard.46b63bd72c3a3f8e1fd7.entry.js from UglifyJs
Unexpected token: name (Viewport) [dashboard.46b63bd72c3a3f8e1fd7.entry.js:39987,6]

ERROR in explore.902dfc963dc4b1c25922.entry.js from UglifyJs
Unexpected token: name (Viewport) [explore.902dfc963dc4b1c25922.entry.js:39987,6]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/cal-heatmap/cal-heatmap.css:
       2 modules

### Steps to reproduce
1) Follow the installation steps at https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md and run 'npm run build'

One observation is that this error does not happen to superset 0.25.0. Could someone provide some insight on the error and the resolution.

**Comment by xrmx** [comment]
Why are you reporting a bug for an old version?

**Comment by colintay** [comment]
@xrmx Thanks for the comment. I just to find out what is the problems that caused version 0.24.0 javascript build to fail.

**Comment by colintay** [comment]
I guess the spirit here should be finding out what are the issues and the resolution to each issue so that developers could learn and apply onto other projects.
