### ISSUE TITLE
Was unable to import superset Error: No module named '_sqlite3'

### ISSUE THREAD

**Issue by AnupKumarSaha** [apache/incubator-superset#4995]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

[cloudera@quickstart ~]$ fabmanager create-admin --app superset
Username [admin]: admin3
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 
Password: 
Repeat for confirmation: 
Was unable to import superset Error: No module named '_sqlite3'

**Comment by mistercrunch** [comment]
Have you tried googling your error message?
https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by Runninghcm** [comment]
Was unable to import superset Error: No module named 'sqlparse'
