### ISSUE TITLE
Issue in superset/connectors/druid/models.py

### ISSUE THREAD

**Issue by ashukhira** [apache/incubator-superset#4998]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0
## Druid Version
0.10.1

### Expected results
I have defined druid mertics as doubleSum  inside my druidDatSource. Inside /druiddatasourcemodelview/edit  , it is visible like
{"type": "doubleSum", "name": "sum__Impressions", "fieldName": "Impressions"} ,

while i am making query it is giving error this:--
HTTP Error 500: Internal Server Error Druid Error: Internal Server Error Query is: { "aggregations": [ { "name": "count", "type": "count" }, { "fieldName": "Revenue", "fieldNames": [ "Revenue" ], "name": "SUM(Revenue)", "type": "floatSum" } ], "dataSource": "<myDataSource>", "granularity": "all", "intervals": "2018-05-07T00:00:00+00:00/2018-05-14T11:37:16+00:00", "postAggregations": [], "queryType": "timeseries" }

It is taking doubleSum to floatSum during query time.
 

### Actual results
During querytime column type of doubleSum should be doubleSum instead of floatSum.

### Bug line:--
1. go to line number 1035 of  superset druid connector model file /root/anaconda3/envs/my_env/lib/python3.6/site-packages/superset/connectors/druid/models.py

replace line of
'type': DruidDatasource.druid_type_from_adhoc_metric(adhoc_metric),

above line print output
'type':'floatSum' // it should be doubleSum 

Thanks
Ashutosh Khira

**Comment by ashukhira** [comment]
**correction on Expected results**

I have defined druid mertics as doubleSum inside my druidDatSource. Inside /druiddatasourcemodelview/edit , it is visible like
{"type": "doubleSum", "name": "sum__Revenue", "fieldName": "Revenue"} ,

while i am making query it is giving error this:--
HTTP Error 500: Internal Server Error Druid Error: Internal Server Error Query is: { "aggregations": [ { "name": "count", "type": "count" }, { "fieldName": "Revenue", "fieldNames": [ "Revenue" ], "name": "SUM(Revenue)", "type": "floatSum" } ], "dataSource": "", "granularity": "all", "intervals": "2018-05-07T00:00:00+00:00/2018-05-14T11:37:16+00:00", "postAggregations": [], "queryType": "timeseries" }

It is taking doubleSum to floatSum during query time.

**Comment by ashukhira** [comment]
Can someone update here

**Comment by mistercrunch** [comment]
I don't think it's changing anything at query time or anything like that, you're probably just referencing another existing metric. Maybe you have multiple metrics defined with the same name?
