### ISSUE TITLE
superset presto database support editing `X-Presto-Source`

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#5002]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
I am using presto as a database and query engine. I have been finding ways to change the headers to {'X-Presto-Source': 'superset@ip'} each time we call the presto API. 
I have searched the SQLAlchemy uri and extra parameters. Both of these seems not applicable.

I just hope the source in the following figure could be modified to customized name but not `pyhive`
 
<img width="557" alt="screen shot 2018-05-15 at 1 02 04 pm" src="https://user-images.githubusercontent.com/8351385/40037737-5edfb74a-5841-11e8-8f11-a95fae801315.png">

### Actual results
The source is `pyhive`

### Steps to reproduce
setup Superset and add a presto database. Go to the presto's web pages e.g. http://prestohost:8080
Run some query in Superset and you will see the above figure in presto page.

**Comment by mistercrunch** [comment]
In the newer version you can use the impersonation feature or the `DB_CONNECTION_MUTATOR` config key:  https://github.com/apache/incubator-superset/blob/master/superset/config.py#L401

**Comment by tooptoop4** [comment]
fixed when adding new datasource , in Extra section -->


 {
    "metadata_params": {},
    "engine_params": {"connect_args": { "protocol": "https", "source": "superset", "requests_kwargs": {"verify": "/home/ec2-user/query-nonprd.pem"}}},
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
