### ISSUE TITLE
Date formating lost when selecting MAX(date)

### ISSUE THREAD

**Issue by sbarlock** [apache/incubator-superset#5003]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.2

### Expected results
Trying to display as a 'Big Number' the MAX value of a TIMESTAMP WITHOUT TIME ZONE date in a PostgresDB (V10).

### Actual results
The date formating is lost.
![image](https://user-images.githubusercontent.com/26203907/40042598-46800e80-5822-11e8-9509-69430410af5c.png)

### Steps to reproduce
Display the MAX of a time column from a PostgresDB.

Cheers!

**Comment by aaronbannin** [comment]
@sbarlock What happens when you add an explicit type `MAX(departure_date_time)::date`? This may be expected behavior based on the type being returned by the query.

**Comment by sbarlock** [comment]
Hi @aaronbannin,
Thanks for your answer.

Using MAX(departure_date_time)::DATE or MAX(departure_date_time)::TIMESTAMP does not change the behaviour.

The only difference is that MAX(departure_date_time)::DATE displays 1.51T instead of 1.51E.

Thanks.

**Comment by mistercrunch** [comment]
What's happening here is that a date isn't really a metric. Big number assumes a number, not a date.

**Comment by sbarlock** [comment]
@mistercrunch Thanks.
So is there a way to display to a user, e.g. the last date a report was submitted?

**Comment by mistercrunch** [comment]
For now I think you'll have to use a `Table` visualization.

In the future I'd like to have `Markup` visualization support templating so that you could fetch data from within that context.
```
## Days since last refresh
{{ fetch_sql_results("SELECT ...") }}
```

**Comment by sbarlock** [comment]
Ok Thanks!
