### ISSUE TITLE
ImportError: No module named 'flask.exthook'

### ISSUE THREAD

**Issue by JulieRossi** [apache/incubator-superset#5006]
Hello !
I ran into an error while running `superset db upgrade` : 
```
File "/usr/local/bin/superset", line 9, in <module>
    from flask.exthook import ExtDeprecationWarning
ImportError: No module named 'flask.exthook'
```
For what I can see, superset uses (or can use) flask==1.0 (`https://github.com/apache/incubator-superset/blob/master/setup.py#L58`) that no longer has a `exthook` module (https://github.com/pallets/flask/releases/tag/1.0).
This causes a ImportError on superset here : https://github.com/apache/incubator-superset/blob/master/superset/bin/superset#L9

When I install flask==0.12.2 before I install superset I no longer have the Error.

Maybe `flask<1.0.0` would work better? Or do you think I may be doing something wrong ?

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.2

### Expected results
There should be no error

### Actual results
ImportError is raised

### Steps to reproduce
`pip install superset==0.25.2`
(by the way, at this point we get a warning `flask-appbuilder 1.10.0 has requirement Flask<0.12.99,>=0.12.1, but you'll have flask 1.0 which is incompatible.`)
`pip freeze`

**Comment by xrmx** [comment]
Dup of #4953, please close

**Comment by JulieRossi** [comment]
Indeed, it mentions the same issue but the discussion says the exthook ImportError is fixed in superset v0.25.1 by forcing flask<1.0 (https://github.com/apache/incubator-superset/issues/4953#issuecomment-388873802) but actually, in superset v0.25.1, the setup forces flask<=1.0, hence the version 1.0 in installed.
In #4953 they now talk about EncryptedType ImportError.
Should I still close this issue and talk about it in #4953 ?

**Comment by xrmx** [comment]
You should probably open a  PR fixing the issue :)

**Comment by mistercrunch** [comment]
Ooops, my bad, fixing in 0.25.4 (pushing this out now)

**Comment by JulieRossi** [comment]
Thanks !!
