### ISSUE TITLE
Existing histogram slices are broken

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#5011]
Testing what's on master, I noticed that all of our existing histogram slices are broken with the error message `Must have at least one numeric column specified`. This error shows up when there's no data in `all_columns_x (Numeric Columns)`. In the params they all have `all_columns_x` set as a string. It looks like in the PR [here](https://github.com/apache/incubator-superset/pull/4525) this was changed to a multi field where the value would be a list. 

@mistercrunch would changing a SelectControl to multi: true break existing slices? Do we need a db migration for this or is there some other way we can catch this?

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Existing histograms load correctly

### Actual results
Existing histograms load with the error 

### Steps to reproduce
Load a histogram created before [this](https://github.com/apache/incubator-superset/pull/4525) PR was introduced. 

@mistercrunch @ArielStv

**Comment by michellethomas** [comment]
@mistercrunch thoughts on this? do we need a db migration to handle this case where a single value select was changed to multi: true?

**Comment by mistercrunch** [comment]
I should have caught this in code review. So either we do a db migration or do some magic around `SelectControl` that would wrap `value` if it's not an array and `multi: true`
