### ISSUE TITLE
Connecting MySQL and PostgreSQL into SQLAlchemy URI 

### ISSUE THREAD

**Issue by miloradkrstevski** [apache/incubator-superset#5013]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24

### Expected results
Connection to db in MySQL and another db in PostgreSQL

### Actual results
Can not connect either to MySQL or PostgreSQL db. The error on MySQL is: ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nNo module named MySQLdb"}.

Can you please point me out:
1. What I need to have installed on Ubuntu and on Windows?
2. What is the correct syntax in connections since the ones provided in SqlAlchemy docs are givinig me error?
3. What is your suggestion on MySQL or PostgreSQL db for Superset?

### Steps to reproduce
//

**Comment by miloradkrstevski** [comment]
@xrmx I followed the docs but can not still connect. Can you please point me out what to install (either in Ubuntu or Windows)? The syntax for (2) user / pass / db after the (1) mysql+mysqldb (2) scott:tiger@localhost/foo, is clear, but the (1) is the problem I can not solve.

**Comment by miloradkrstevski** [comment]
@mistercrunch Can you please help me on this issue?

**Comment by TianyangLi** [comment]
@miloradkrstevski assuming your language of choice is python you need a python driver for mysql as superset uses SQLAlchemy to process SQL related queries in the back-end.

Do you have that python driver installed??

**Comment by miloradkrstevski** [comment]
@TianyangLi Yes, I will take for example Windows. I installed MySQL with all add-ons (https://dev.mysql.com/downloads/windows/installer/8.0.html), Python 2.7.15 x86 (https://www.python.org/downloads/release/python-2715/), Microsoft Visual C++ Compiler for Python 2.7 (https://www.microsoft.com/en-us/download/details.aspx?id=44266) and https://www.microsoft.com/en-us/download/details.aspx?id=48145).

With these installations, I still get an error either on mysql+mysqldb or mysql+mysqlconnector.

What should I do next? Thanks.

**Comment by TianyangLi** [comment]
@miloradkrstevski 

The error itself is a very straight forward fix. On ubuntu its as straight forward as:
sudo apt-get install python-mysqldb

If you have a alternative linux set-up that might just do it.

let me know how you go...

**Comment by miloradkrstevski** [comment]
@TianyangLi Does not work. Here is the info (from Windows): (in Ubuntu will try next)

> Traceback (most recent call last):
  File "C:\venv\lib\site-packages\superset\views\core.py", line 1691, in testconn
    engine = create_engine(uri, connect_args=connect_args)
  File "C:\venv\lib\site-packages\sqlalchemy\engine\__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "C:\venv\lib\site-packages\sqlalchemy\dialects\mysql\mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
2018-05-16 15:08:43,316:INFO:werkzeug:127.0.0.1 - - [16/May/2018 15:08:43] "POST /superset/testconn HTTP/1.1" 500 -

Something else comes to mind for a solution?

**Comment by xrmx** [comment]
@miloradkrstevski if you had read the documentation you'll have see that 1) windows is not supported, 2) the docs suggests another driver for mysql

**Comment by miloradkrstevski** [comment]
@xrmx Dude, I read the docs. And somehow it was working in Windows with some previous version of Superset and conn with MySQL. The thing is that I did not write it down what I have installed to work, but I know it was searching for solution pretty well, like now.

Now, I will test as @TianyangLi suggests and will find you. BTW, do you have any possible solution in mind?

Thanks.

**Comment by miloradkrstevski** [comment]
@TianyangLi I have tried with sudo apt-get install python-mysqldb, but still no success. It gives me error:

> ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nNo module named MySQLdb"}

And in the terminal it is the following info:

> Traceback (most recent call last):
  File "/home/miki/venv/local/lib/python2.7/site-packages/superset/views/core.py", line 1691, in testconn
    engine = create_engine(uri, connect_args=connect_args)
  File "/home/miki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/miki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/miki/venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb

I am using Superset==0.24, because 0.25 (or latest) gives me problem with flask.

Anyone any idea? Thanks.

**Comment by mistercrunch** [comment]
`pip install mysqlclient`

**Comment by miloradkrstevski** [comment]
@mistercrunch When I try to install `pip install mysqlclient`, it goes me the following error:

> Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 735kB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WdyxRX/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WdyxRX/mysqlclient/

What does this mean? Can anyone please explain me? I am novice in this and using only Superset. Thank you.

**Comment by miloradkrstevski** [comment]
@mistercrunch Can you please reopen the issue so someone could help me? Anyone any solution: @xrmx , @TianyangLi , @mistercrunch , ...
The details are above this comment. Thank you.

**Comment by TianyangLi** [comment]
@miloradkrstevski 

Are you sure you're in the right virtual venv? have you deployed your venv in a python3 environment? its unclear from your steps..

python defaults 2.7. So its possible that you've installed python3-mysqldev library, but when you type 'pip install mysql' you're actually calling the wrong python version. Check that..

**Comment by miloradkrstevski** [comment]
@TianyangLi How to check this? And more important, how to solve it?

**Comment by miloradkrstevski** [comment]
Thank you very much @TianyangLi. That was the problem. I install all in python3, pip3, and venv is correct now. The connection to MySQL is established.

**Comment by bernarde01** [comment]
> Thank you very much @TianyangLi. That was the problem. I install all in python3, pip3, and venv is correct now. The connection to MySQL is established.

Hi @sohelsarder. I'm sitting with the same error. I installed Superset via docker (as per the installation documantation). I not get the "Unexpected error No module named 'MySQLdb'" problem when I try to connect a MySQL database. Can you offer any advice here?

Thanks

**Comment by bernarde01** [comment]
I just tried the install again, this time going through all the steps manually and not making use of docker. This solved the problem. 

I think the issue with docker was that the mysqlclient installation wasn't in the correct virtual environment, however I do not know docker well enough to understand how this works exactly.

**Comment by bkarlson** [comment]
Folks, proper solution for Ubuntu:
```sh
cd /var/lib/superset
source venv/bin/activate
pip install mysqlclient
```

Done.

Explanation: superset runs in virtual environment and globally (system-wide) installed modules are not reachable from venv. Hence you'd need to dive into venv and install the module there.
