### ISSUE TITLE
Hi All I am very new with superset, i tired to add a mysql database, all connection tested result seem OK with the list of the tables at the bottom of page, but when I tried to save it present the error: General Error <class 'sqlalchemy.exc.OperationalError'>. Any one have faced this before?

### ISSUE THREAD

**Issue by zkenstein** [apache/incubator-superset#5016]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Please close.
