### ISSUE TITLE
feature request: keycloak support 

### ISSUE THREAD

**Issue by tianlinzx** [apache/incubator-superset#5024]
feature request: keycloak support 

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25

### Expected results
Keycloak is a standalone authentication provider, it use openid connection protocal, a community implematation is done in this post 
https://stackoverflow.com/questions/47678321/using-openid-keycloak-with-superset

### Actual results
would it be integrated into official release ?

**Comment by mistercrunch** [comment]
From my understanding that's a feature request for Flask-AppBuilder
