### ISSUE TITLE
Which db is best with Superset 0.24 and later (0.25+)?

### ISSUE THREAD

**Issue by miloradkrstevski** [apache/incubator-superset#5036]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25

### Expected results
Real-time situations with Superset and back-end db

### Actual results
Have been testing MySQL and PostgreSQL

### Steps to reproduce
//

Hey guys, can anyone point out which of the db solutions MySQL / PostgreSQL is best for Superset for versions > 0.24?

I have tested with both, and can not decide which is best taking into account speed and long run.

Thank you.

**Comment by villebro** [comment]
They're both fine, as should be most other SQL Alchemy databases.

**Comment by miloradkrstevski** [comment]
Regarding speed in showing data in Superset, which one do you prefer?

**Comment by villebro** [comment]
I wouldn't expect a significant difference between those two. But if you want my personal opinion, I would personally use Postgres if offered those two options.
