### ISSUE TITLE
Permission to enable / disable CSV export on chart / slice

### ISSUE THREAD

**Issue by miloradkrstevski** [apache/incubator-superset#5041]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25

### Expected results
To have permission to enable / disable CSV export on chart / slice

### Actual results
The permission for CSV export on chart / slice is enabled by default and there is no permission to disable it.

### Steps to reproduce
//

@mistercrunch Hi there, is there a possibility to put a permission on CSV export on chart / slice? Now it is enabled by default for all charts / slices and there is no permission in roles to disabled it.

Thank you.

**Comment by miloradkrstevski** [comment]
@TianyangLi I am a little new in this Python and venv thing. Could you please point me out something more? I check the file but found nothing in correlation with CSV export on chart / slice?

**Comment by zkenstein** [comment]
I think on this line CSV_EXPORT = {
    'encoding': 'utf-8',
}

around line 197?

**Comment by TianyangLi** [comment]
@miloradkrstevski @zkenstein 

Close, but i think its jus a matter of commenting out the following:

![csv_](https://user-images.githubusercontent.com/12669464/40329771-bea3e248-5d9e-11e8-8f15-16b22dad4954.PNG)

**Comment by miloradkrstevski** [comment]
@TianyangLi What do I need to do here in order to delete the permission for CSV export? Can you help me please?
