### ISSUE TITLE
[Filter Box] [Bug] The filter doesn’t spread on the second level filter data

### ISSUE THREAD

**Issue by oxydash** [apache/incubator-superset#5043]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.23.2 & 0.25

### Actual results

The filter doesn’t spread on the second level filter data.  For example, if we choose «North America» as a region, countries still include other continents («China», «India»...)

<img width="232" alt="screen shot 2018-05-19 at 15 17 54" src="https://user-images.githubusercontent.com/36365249/40268791-fc2f9176-5b7c-11e8-9d66-f7c5c3e4b12d.png">

### Expected results

Chosen region must influence on the second level filter data (all other filter levels). After choosing «North America» for the region we should have Canada, USA... in the subfilter/second level filter.

**Comment by thoughtpunch** [comment]
@oxydash I encountered the same thing. I was able to get around this partially by adding multiple filter boxes for the same dataset to my dashboard, one-per-level. They you can see the cascading filters queries applied to the other filter boxes in real time

Looking for a better way to achieve this of course, so 👍

**Comment by ahsanshah** [comment]
I believe this worked as expected in prior versions. E.g. Selecting a Region constrained the prompts in other filters inside the same slice. It would make sense that within a single slice the values would constrain. Could this be a bug with the more recent releases?

**Comment by mistercrunch** [comment]
@ahsanshah I'm pretty sure it never worked the way you described.

@thoughtpunch I've done that same hack to make it work (multiple filter boxes). One drawback is you don't want that selecting a country to filter the continent dropdown, to prevent that you can use the tricks described here: http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

It becomes possible to have cascading filters.

In the future filters will become a dashboard construct (as opposed to a special chart like it is now). The dashboard filters will be "scoped" meaning that your dashboard can have dashboard-level filters, tab-level-filter, section-level fitlers, ... It should make it possible to have more options around cascading filters.

**Comment by ahsanshah** [comment]
you are correct @mistercrunch , confirmed it works only with different filter boxes. I think the new grid layout (which allows finer grained sizing of slices) makes it easier to use this hack to stack filterboxes but Filters in general could use enhancements.  For instance, we are trying to extend filterbox to force a single select but bit unclear how to do this or of it would be forward compatible.  While a multi select allows for single select, depending on the user base, we sometimes do need to prevent a multi select.  Is FilterBox enhancements actively in the works by any chance on any PR?

**Comment by mistercrunch** [comment]
Not in the works as far as I know. It shouldn't be too hard to have per-column configuration.

**Comment by ahsanshah** [comment]
We were able to use the OOTB FilterBox as a baseline to create a single select variant.  One item to note is that this required removal of the code that does a "Creatable" and set of multi = false.  This is not a per column configr

**Comment by mistercrunch** [comment]
`multi` as well as metrics and ordering should be per-filter configuration

**Comment by cdmikechen** [comment]
Really want to know how the problem is going?
