### ISSUE TITLE
Can't select the table's other metrics when explore the chart expect the count(*) metric

### ISSUE THREAD

**Issue by zhangjian0111** [apache/incubator-superset#5045]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

![default](https://user-images.githubusercontent.com/24623/40274684-856942f6-5c0f-11e8-9e04-e9ef63deb37a.png)

**Comment by mistercrunch** [comment]
@GabeLoins

**Comment by GabeLoins** [comment]
@zhangjian0111 we recently updated how the Metrics Control is used, refer to https://github.com/apache/incubator-superset/pull/4736 and https://github.com/apache/incubator-superset/pull/4663 for examples of how to add metrics.

**Comment by zhangjian0111** [comment]
@GabeLoins Good Idea.if it can suport both fetures is perfect.

**Comment by YHGui** [comment]
@GabeLoins  we can't select the table's other metrics when explore the chart expect the count(*) metric like the picture in this issue. And selecting some metrics show errors about unhashable type: 'dict', such as Word Count with metrics SUM(num) show errors about unhashable type: 'dict'

**Comment by congdanh8391** [comment]
I'm using superset 0.25.6

In table view, after you set your metric, the number can not be formatted as image. How can I fix this? I tried to change d3 format  on edit table but it doesn't work
![screen shot 2018-09-12 at 12 12 47 pm](https://user-images.githubusercontent.com/38421401/45403558-44719480-b685-11e8-9b47-ac09e3c2264d.png)
