### ISSUE TITLE
Number Format not changed

### ISSUE THREAD

**Issue by zkenstein** [apache/incubator-superset#5046]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Expected results
Number Value will be kin the currency format in the Table and Chart View
eg: 337.000.000.000

### Actual results
337000000000

### Steps to reproduce
Generate the custom sql from SQL Lab Editor, tap the visualize button. Already  change the d3 format in the metrics using this: .3s (12345.432 => 12.3k) but not changed. Maybe I did something wrong?

**Comment by wangshihan513** [comment]
I have the same issue, change d3 format in metrics configuration form doesn't seem work. DId you figure out this problem?

**Comment by Sriramtap** [comment]
Having the same issue with the currency. Did you solve this issue?

**Comment by tollerr** [comment]
having the same issue. Did this format ever work?

**Comment by mistercrunch** [comment]
I think at the moment it only affects the table visualization. The intent is to support it in more visualization types.
