### ISSUE TITLE
Slices with new Adhoc Filters break dashboards

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#5049]
Currently on master adding a slice with an adhoc filter breaks the dashboard page.

`Cannot read property 'concat' of undefined at eval (eval at getFormDataExtra (Dashboard.jsx?623f:546), <anonymous>:1:23)`

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Slices with adhoc filters display correctly

### Actual results
Slices with adhoc filters break dashboard pages

### Steps to reproduce
Create a slice with an adhoc filter and add it to a dashboard

**Comment by mistercrunch** [comment]
@GabeLoins

**Comment by michellethomas** [comment]
Fixed in pr #5056
