### ISSUE TITLE
Database Permission for version 0.25.0

### ISSUE THREAD

**Issue by qin4zhang** [apache/incubator-superset#5053]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Expected results
 Granting access to a database allows for the user to access all data sources within that database, and will enable the user to query that database in SQL Lab, provided that the SQL Lab specific permission have been granted to the user

### Actual results
Adding a new db(postgres),I can't grant  database access on [dbname] to user for a new role. But I can grant **schema** access on [dbname].[schema]. I can't get access all data sources within database.

### Steps to reproduce

1. Adding a new db.
2. Adding a new role.
3. Editing the role to grant access.
4. Common user with Gamma and the new role with access on db(actually schema).
5. There is nothing for datasources as a common user.

How could I grant access database to the role？

**Comment by TianyangLi** [comment]
@qin4zhang I can't replicate that issue in 0.25.5

**Comment by qin4zhang** [comment]
@TianyangLi I wil try to use 0.25.5

**Comment by qin4zhang** [comment]
@TianyangLi I try to upgrade to 0.25.5. Adding a postgres db, however I can't grant database access on [dbname]. I just want to grant database access to user, then datasources within database can be reached. Or I should grant datasources access to user one by one?

**Comment by mistercrunch** [comment]
What's keeping you from granting database access? Is the perm missing? it should show as `database access on [{dbname}].(id:{id})` or something like close to that. `superset init` may create missing perms if that's the case, though the perm should have been created as the db got created.

**Comment by qin4zhang** [comment]
@mistercrunch Great! I can find database access on [{dbname}].(id:{id}). When I grant a new role with the permission to a common user.  All data sources within that database are still limited to the common user. 
![image](https://user-images.githubusercontent.com/10649428/40463140-0bc795d0-5f46-11e8-9b56-6731d0e4d168.png)
How could I grant access to a database allows for the user to access all data sources within that database?

**Comment by yamyamyuo** [comment]
@mistercrunch I have the same confusion. I assumes that `database` access control will provide all the datasource access if tables were within that `database`. If a slice's datasource is from this specific database, then I will be able to access this slice. If a dashboard's datasources are within this specific `database`, then I will be able to access this dashboard.

**Comment by jaroli** [comment]
I have Superset version 0.28.1 and have the same problem.
Granting access to a database (e.g. database access on [test_db].(id:2)) does NOT give access to any tables within the database.

I have to manually give access to all tables with e.g.: datasource access on [test_db].[test_table](id:13)
