### ISSUE TITLE
Security vulnerability for 0.25.0

### ISSUE THREAD

**Issue by qin4zhang** [apache/incubator-superset#5054]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Expected results
Common users with Gamma could't get user list, when they reach ip:port/users/list/.

### Actual results
Common user with Gamma remember the url ip:port/users/list/,they can reach the url ,then edit users role to get Admins.

### Steps to reproduce

1. Login in common user with Gamma role.
2. Reach url ip:port/users/list/
3. Choosing the user, edit the role to Admin. Get it.

**Comment by sebastianwindeck** [comment]
Sorry, I can't reproduce this issue for 0.25.5

**Comment by qin4zhang** [comment]
I will try to use 0.25.5

**Comment by qin4zhang** [comment]
@sebastianwindeck Same thing happened in version 0.25.5. As a common user with Gamma, I can get url /users/list/. Let's see picture following.
![image](https://user-images.githubusercontent.com/10649428/40416971-3fe2dcc0-5eb1-11e8-8238-55af94b5b43a.png).
Login from LDAP, default role is Gamma.

**Comment by sebastianwindeck** [comment]
@qin4zhang Ok, I used simple users, within the fab-manager of the flask-app. 
- Maybe check which user superset identifies for accessing the mentioned page, 
- And ensure whether you used the command to update the version `superset init`

**Comment by mistercrunch** [comment]
Have you run `superset init` since upgrade? The provided roles are updated/synced when running `supreset init`, perhaps `Gamma` role was altered at some point, or perhaps that endpoint wasn't secured at the last time you ran `superset init`

**Comment by qin4zhang** [comment]
@sebastianwindeck @mistercrunch Get it. I forget to run superset init after upgrading. I will try to check it.
