### ISSUE TITLE
Add option for 24h dashboard refresh frequency

### ISSUE THREAD

**Issue by aok1425** [apache/incubator-superset#5058]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
The latest one, I'm pretty sure

### Expected results
I would like to have the option to refresh all charts on a dashboard every 24h. The best option I have so far is 5 mins.

### Actual results
![](https://i.imgur.com/P8YZTSo.png)
![](https://i.imgur.com/EGo50nX.png)

### Steps to reproduce
- From a dashboard, click Actions on the top-right.

**Comment by mistercrunch** [comment]
Should be a simple PR, add more entries here:
https://github.com/apache/incubator-superset/blob/c0db6dbb57ee562da83afb715203a9e8705eb437/superset/assets/src/dashboard/components/RefreshIntervalModal.jsx#L23

**Comment by aok1425** [comment]
Amazing! I will do that--thanks
