### ISSUE TITLE
Add horizontal bar chart 

### ISSUE THREAD

**Issue by aok1425** [apache/incubator-superset#5059]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest one, I'm pretty sure

### Expected results
- There is no horizontal bar chart visualization type. I was thinking it would be nice to add a "Transpose" checkbox under the Style tab to do this.

### Actual results
No horizontal bar chart option:
![](https://i.imgur.com/3hGSaxo.png)

Where I suggest putting the Transpose option:
![](https://i.imgur.com/lSkNZKc.png)

### Steps to reproduce
- Go to a chart, then see screenshots above

**Comment by qin4zhang** [comment]
That sounds good.

**Comment by hughhhh** [comment]
How to do it with nvd3:
https://github.com/novus/nvd3/issues/357

Example:
http://nvd3.org/examples/multiBarHorizontal.html

**Comment by d84-n1nj4** [comment]
Has this feature been added?

**Comment by andrewm4894** [comment]
I'm new to superset and just wondering if there is any way to do this since issue was opened?

**Comment by bashyroger** [comment]
We have interest in this, can it be re-opened?

**Comment by chaeron** [comment]
Horizontal bar charts are important vlsualizations. Please re-open this ticket!

**Comment by shubhamn21** [comment]
This is definitely needed.

**Comment by xuduo18** [comment]
Yes. It is very needed!

**Comment by anhhd** [comment]
Yes, it is definitely needed. The horizontal bar chart is very essential when we have many categories

**Comment by manavjaiswal** [comment]
+ 1

**Comment by ChengzhiZhao** [comment]
+1 to support horizontal bar chart

**Comment by chaeron** [comment]
I've given up on Superset, which is sad, since I've always been a fan and supported of Apache projects.

There has not been an official response to this request since I made it over 7 months ago. Every other decent BI tool out there supports horizontal bar charts.  But not Superset.

Recently I tried to get Superset running again for a critical BI demo.....no dice. Kept crashing, and besides, the install process is labourious, too lengthy and complicated.  Put up a good BI demo using Metabase in an hour from a standing start knowing nothing about the product.....and that was talking to a Snowflake data warehouse.

So unfortunately you can close this request, since I think Superset is pretty much hopeless at this point, given the lack of attention to a key feature request (a pretty basic one) and abysmal recent experience.

**Comment by maxilirator** [comment]
I am in the process of evaluating different open source BI plattforms and one of the criteria is a dashboard with horizontal bar charts. This is really something which is needed if you want his project to be competitive.

**Comment by yashk1** [comment]
We need horizontal bar chart

**Comment by sfirke** [comment]
This is implemented in Superset 2.0.0, out now.  Use the Time Series Bar Chart v2 eChart and there's a tab to control orientation.  Implementation and details here: https://github.com/apache/superset/pull/19918.

**Comment by ainfeld** [comment]
When will this be available on the normal bar charts as well? Not just the time series ones

**Comment by Vicinius** [comment]
@sfirke I just want to do a horizontal bar chart without a time column (regular bar chart), is there a way? Or it was only implemented on time-series bar chart v2?

**Comment by sfirke** [comment]
You would enable the GENERIC_CHART_AXES flag in your configuration, then use the Bar Chart v2 chart type and then yes you can do a horizontal bar chart without a time column.

Unfortunately I don't believe you'll be able to control the sort order of the bars as of now, that's discussed here: https://github.com/apache/superset/discussions/20885

**Comment by olga-pliuta** [comment]
Please reopen the issue

**Comment by sfirke** [comment]
> Please reopen the issue

@olga-pliuta can you say more?  This was implemented a while ago.

**Comment by eliezerhilario** [comment]
> You would enable the GENERIC_CHART_AXES flag in your configuration, then use the Bar Chart v2 chart type and then yes you can do a horizontal bar chart without a time column.
> 
> Unfortunately I don't believe you'll be able to control the sort order of the bars as of now, that's discussed here: #20885

Thanks. I was able to solve with these instructions

**Comment by eliezerhilario** [comment]
> This is implemented in Superset 2.0.0, out now. Use the Time Series Bar Chart v2 eChart and there's a tab to control orientation. Implementation and details here: #19918.

Thanks. I was able to solve with these instructions

**Comment by davidalbertonogueira** [comment]
only possible with time series? what if the main axis is a category and not time buckets?
