### ISSUE TITLE
Support Multi charts

### ISSUE THREAD

**Issue by anju-jsl** [apache/incubator-superset#5061]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
I need to show dual axis char but with line and bar chart. Not able to create that in superset

### Actual results
It should support multi charts

### Steps to reproduce
Need to see the correlation between 2 variables, but one of them is not continuous, so cannot use a line chart and need a bar chart for its trending.

**Comment by anju-jsl** [comment]
Duplicate to  #1768 
The issue has been closed, but the requirement still remains the same

**Comment by mistercrunch** [comment]
Reopened the original issue
