### ISSUE TITLE
Apache superset - Error retrive db2 table information 

### ISSUE THREAD

**Issue by mariomarf** [apache/incubator-superset#5063]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
Table/column information

### Actual results
"Error occurred while fetching table metadata".

### Steps to reproduce
in "SQL Lab", select a db2 database --> Schema --> Table

### LOG

> 2018-05-23 22:43:22,945:INFO:werkzeug:192.168.158.1 - - [23/May/2018 22:43:22] "GET /superset/table/2/ttis11_ms_od_gio/TISA%20%20%20%20/ HTTP/1.1" 500 -
> Traceback (most recent call last):
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in call
> return self.wsgi_app(environ, start_response)
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
> return self.view_functionsrule.endpoint
> File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
> return f(self, *args, **kwargs)
> File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 905, in wrapper
> value = f(*args, **kwargs)
> File "/usr/lib/python2.7/site-packages/superset/views/core.py", line 2253, in table
> cols=columns, latest_partition=False),
> File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 722, in select_star
> indent=indent, latest_partition=latest_partition, cols=cols)
> File "/usr/lib/python2.7/site-packages/superset/db_engine_specs.py", line 256, in select_star
> sql = my_db.compile_sqla_query(qry)
> File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 713, in compile_sqla_query
> compiled = qry.compile(eng, compile_kwargs={'literal_binds': True})
> File "", line 1, in
> 
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
> return self._compiler(dialect, bind=bind, **kw)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
> return dialect.statement_compiler(dialect, self, **kw)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 453, in init
> Compiled.init(self, dialect, statement, **kwargs)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 219, in init
> self.string = self.process(self.statement, **compile_kwargs)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
> return obj._compiler_dispatch(self, **kwargs)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
> return meth(self, **kw)
> File "/usr/lib/python2.7/site-packages/ibm_db_sa-0.3.2-py2.7.egg/ibm_db_sa/base.py", line 351, in visit_select
> sql_ori = compiler.SQLCompiler.visit_select(self, select, **kwargs)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 1791, in visit_select
> text += self.get_select_precolumns(select, **kwargs)
> TypeError: get_select_precolumns() got an unexpected keyword argument 'literal_binds'

I hope that can help me.
Best regards
Mario

**Comment by mistercrunch** [comment]
This is likely an issue with the SQLAlchemy dialect for db2

**Comment by mariomarf** [comment]
Ok, thank. I have open a new issue in ibm_db group.

**Comment by mistercrunch** [comment]
You may want to tweak `apply_limit_to_sql` in `superset.db_engine_spec` to make it work with db2.

**Comment by benjaminsingleton** [comment]
That function definitely seems to be the culprit. I can make the change to suit my needs, but do you think it would be helpful to create a separate issue to address this? Right now, Superset markets that it [supports DB2](https://github.com/apache/incubator-superset#database-support), but this issue seems to stand in the way of that really being true.

**Comment by mistercrunch** [comment]
@benjaminsingleton so was the `FIRST 100 ROWS ONLY` coming from the query text you wrote in SQL Lab itself, or was Superset applying both that and `LIMIT 1000000`?

Could it just be that the SQLAlchemy dialect for DB2 just doesn't work around `.limit()` and just generates SQL that db2 can't process?

**Comment by mariomarf** [comment]
@benjaminsingleton my problem persists but in this period I do not have much time to test it :-(

**Comment by benjaminsingleton** [comment]
@mistercrunch if I write `select * from table` in SQL Lab, there is no error. If I write `select * from table fetch first 100 rows only`, I get the error:

`ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N An unexpected token "LIMIT 1000000" was found following "first 100 rows only". Expected tokens may include: "<space>". SQLSTATE=42601 SQLCODE=-104`

When I click on the "Preview for tablename" tabs that appear in SQL Lab, I get the following error:

`ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N An unexpected token "LIMIT 1000000" was found following "FIRST 100 ROWS ONLY". Expected tokens may include: "<space>". SQLSTATE=42601 SQLCODE=-104`

If you're interested in reproducing the problem, the [DB2 Express-C](https://hub.docker.com/r/ibmcom/db2express-c/) docker image is a quick way to get a DB2 database up and running with sample data and then you'll need to `pip install ibm_db` and `easy_install ibm_db_sa`. The SqlAlchemy URI for the default database will be `db2+ibm_db://db2inst1:db2inst1-pwd@0.0.0.0:50000/SAMPLE`.

**Comment by mistercrunch** [comment]
Which version is this? Looks like it may have been fixed here https://github.com/apache/incubator-superset/commit/b839608c3#diff-6519edc75f2440a575cb22492f401100R428

**Comment by sorieux** [comment]
I have the same problem. I think the engine variable in DB2EngineSpec is wrong. I proposed a PR (fix: Update db2.py #10523
)

**Comment by cabo40** [comment]
as pointed by https://github.com/apache/superset/pull/10523#issuecomment-670583336 , one needs to change the connection prefix from `db2+ibm_db` to `ibm_db_sa`.
Thanks for the fix @sorieux !!! (I know its also you, but for future reference while the docs get corrected)
