### ISSUE TITLE
ConnectionRefusedError in runlog

### ISSUE THREAD

**Issue by forvendettaw** [apache/incubator-superset#5069]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/instrument/statsd.py", line 121, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by JulieRossi** [comment]
Hello @forvendettaw, we are having the same error, did you finally managed to understand it ?

**Comment by adnanshussain** [comment]
I'm getting the exact same error while running gunicorn and statsd on the same machine.. However I'm being able to send messages to statsd via command line !

**Comment by adnanshussain** [comment]
OK. Found the issue. I was trying to send stats to port 8126 which is a TCP port, I was supposed to send them to 8125 which is a UDP port.

**Comment by syafiqdante** [comment]
> OK. Found the issue. I was trying to send stats to port 8126 which is a TCP port, I was supposed to send them to 8125 which is a UDP port.

I have the exact same problem... do you have any solution..?
I am new with this superset...

**Comment by cryptorevizor** [comment]
Any who solve this problem?

**Comment by tuhinsharma121** [comment]
@adnanshussain how did you solve this? I am having the same error while running on aws.

**Comment by fccoelho** [comment]
Mine is configured to send stats to 8125, but I still get this error

```bash
--statsd-host localhost:8125
```

**Comment by MarcosVn** [comment]
Has anyone solved this problem?

**Comment by yaroshoris** [comment]
Hi there, 
If you have faced with the same issue:
 ```
File "/usr/local/lib/python3.10/site-packages/gunicorn/instrument/statsd.py", line 121, in _sock_send
self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
``` 

after running next command from https://superset.apache.org/docs/installation/configuring-superset/#running-on-a-wsgi-http-server

```
      gunicorn -w 10 \
      -k gevent \
      --worker-connections 1000 \
      --timeout 120 \
      -b  0.0.0.0:6666 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      --statsd-host localhost:8125 \
      "superset.app:create_app()"
```
     


Just use next command:

gunicorn -w 10 \
      -k gevent \
      --worker-connections 1000 \
      --timeout 120 \
      -b  0.0.0.0:8080 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      "superset.app:create_app()"
      

Line "--statsd-host localhost:8125 \" needs to be removed.
Enjoy:)

**Comment by challenger009** [comment]
I am having the same issue

**Comment by cbrianbet** [comment]
Any solution 
Im getting the same error
