### ISSUE TITLE
Limit in "Upload CSV data"

### ISSUE THREAD

**Issue by LoicSan** [apache/incubator-superset#5072]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset 0.25.5

### Expected results
Import the 27000 lines from my csv input data. I

### Actual results
superset/lib/python2.7/site-packages/werkzeug/wrappers.py:1116: UserWarning: The "session" cookie is too large: the value was 275662 bytes but the header required 26 extra bytes. The final size was 275688 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
  samesite=samesite
[24/May/2018 10:39:13] "POST /csvtodatabaseview/form HTTP/1.1" 302 -
2018-05-24 10:39:17,241:INFO:werkzeug:XX.XX.XX.XX - - [24/May/2018 10:39:17] "GET /csvtodatabaseview/form HTTP/1.1" 200 -

### Steps to reproduce
This problem occurs when you try to upload a large csv file. It's annoying because most of the time we do not connect directly to the database but load an extraction of it.
How can we get around this ?

Regards.

**Comment by miloradkrstevski** [comment]
The solution should be looked in the browser that you are using (that is the answer on the same question I got). I am having the same issue with Superset==0.25, but with previous ==0.24, everything was fine. Taking this into account, I am not sure that the problem is in the browser, but in the new version of Superset (possibly some restrictions).

**Comment by LoicSan** [comment]
Hello,

thanks for your interest in this subject.
I also thought at first that it could come from a limitation in superset configuration.
I looked in werzeug conf as it appears in the log message (see above my first post).

So i tried to change the sset/lib/python2.7/site-packages/werkzeug/wrappers.py value from 4093 to 0 as explained in the comments but it does not work either.

    #: Warn if a cookie header exceeds this size. The default, 4093, should be
    #: safely `supported by most browsers <cookie_>`_. A cookie larger than
    #: this size will still be sent, but it may be ignored or handled
    #: incorrectly by some browsers. Set to 0 to disable this check.
    #:
    #: .. versionadded:: 0.13
    #:
    #: .. _`cookie`: http://browsercookielimits.squawky.net/
    max_cookie_size = 0

**Comment by henan715** [comment]
meet the same question:

Superset version
superset 0.25.5

Expected results
Import the 10000 lines from my csv input data. 

Actual results
```
UserWarning: The "b'session'" cookie is too large: the value was 640742 bytes but the header required 26 extra bytes. The final size was 640768 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
  samesite=samesite
```

Steps to reproduce
This problem occurs when you try to upload a large csv file.  my csv file is about 1GB, i cut part of it(about 2MB) ,first, when i upload the file,  the web page shows:
```
ERR_RESPONSE_HEADERS_TOO_BIG
``` 
then the console log shows:
```
UserWarning: The "b'session'" cookie is too large: the value was 640742 bytes but the header required 26 extra bytes. The final size was 640768 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
```
Has anyone met this before? what is your solution? please help me ,thanks~
Regards.

**Comment by MAliNaqvi** [comment]
Not this exact cookie error that others are getting, but I get 504/502 Bad Gateway errors when uploading a large csv file. I saw that the Gunicorn worker was terminating:

```
[2018-10-24 16:45:45 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:93)
/usr/local/lib/python3.5/dist-packages/superset/db_engine_specs.py:148: DtypeWarning: Columns (158,236,357,366,483,498,499,550,584) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.concat(chunk for chunk in chunks)
/usr/local/lib/python3.5/dist-packages/superset/db_engine_specs.py:148: DtypeWarning: Columns (17,158,236,366,483,498,550,583,584) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.concat(chunk for chunk in chunks)
Loaded your LOCAL configuration at [/etc/superset/superset_config.py]
/usr/local/lib/python3.5/dist-packages/superset/db_engine_specs.py:148: DtypeWarning: Columns (158,236,353,354,357,366,483,498,550,583,584) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.concat(chunk for chunk in chunks)
/usr/local/lib/python3.5/dist-packages/superset/db_engine_specs.py:148: DtypeWarning: Columns (9,158,236,260,288,366,483,498,547,550,583,584,599) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.concat(chunk for chunk in chunks)
[2018-10-24 16:45:45 +0000] [93] [INFO] Worker exiting (pid: 93)
[2018-10-24 16:45:46 +0000] [102] [INFO] Booting worker with pid: 102
```

So I increased the timeout via 

```
superset gunicorn \
              -w 3 \
              -k gevent \
              --timeout 120 \
              -b 0.0.0.0:8088 \
              --limit-request-line 0 \
              --limit-request-field_size 0 \
              superset:app
```

to 600s and now I can upload 21mb files. But unfortunately we have to keep increasing this timeout for larger files.

**Comment by Hisssy** [comment]
I've encountered this problem recently in Superset v1.5.0. In my case, the root cause seems to be encoding incompatibility.

The size of csv file to be uploaded was about 2.1MB (12000 rows) and the error log looked the same as others: 

> /home/me/venv38/lib64/python3.8/site-packages/werkzeug/wrappers/[base_response.py:468](http://base_response.py:468/): UserWarning: The "b'session'" cookie is too large: the value was 19232 bytes but the header required 40 extra bytes. The final size was 19272 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.

There's something wrong with the size of the file (2M is not large enough), so I tried to upload a small csv with only 10 lines in it to shrink the cookie size and got the real error in the response:
> (1366, "Incorrect string value: '\\xE4\\xBD\\xA0\\xE5\\xA5\\xBD' for column 'name' at row 1")

With a little googling, this error might be related to inserting rows containing non-latin charater into latin encoding backend MySQL db. After changing default charset, csv upload worked like a charm.
