### ISSUE TITLE
Translation does not work in add new chart

### ISSUE THREAD

**Issue by rahimramezanian** [apache/incubator-superset#5074]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.0dev
### Expected results
Translated page for French.
### Actual results
Default English page.
### Steps to reproduce

Add translation for page Add new chart
  `http://0.0.0.0:8088/slicemodelview/add`
both for .json and .po in _fr_ path

`"Create a new chart":["Créer un nouveau graphique"]`

```
msgid "Create new chart"
msgstr "Créer un nouveau graphique"
```
I also did 

```
Superset_Home$  pybabel compile -d ./superset/translations/
Superset_Home$  python setup.py install
```

![screenshot from 2018-05-24 16-32-08](https://user-images.githubusercontent.com/15890835/40484222-13695dd0-5f70-11e8-875e-5e2aa396896c.png)

**Comment by mistercrunch** [comment]
Mind rebasing/retrying, I think a recent PR fixed this: https://github.com/apache/incubator-superset/pull/5008
