### ISSUE TITLE
Add params to URL in IFrame chart type

### ISSUE THREAD

**Issue by anju-jsl** [apache/incubator-superset#5075]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
Need to append the URL with a parameter list, so that URL is dynamically generated on the basis of the filter

### Actual results
Not able to add parameters to the URL string.
the json for the iframe chart shows "{"url_params": {},
But how do we access this from the Superset front end?

### Steps to reproduce
I have a table with a list of domain names, I would want to open the URL as mentioned in the table

**Comment by yneha** [comment]
Is there any solution for this?

**Comment by ranggarppb** [comment]
bump

**Comment by scubed2010** [comment]
> bump

@ranggarppb I second your bump
