### ISSUE TITLE
superset doesn't load or use   VIEWS  from mysql , it loads TABLES normally after testing connection to database  but not VIEWS

### ISSUE THREAD

**Issue by ahmad27** [apache/incubator-superset#5079]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by ahmad27** [comment]
okay i tried a couple of things , it worked for me when i selected the VIEW from SQL LAB tab and then SQL EDITOR   and selected the view from there

**Comment by anoop151** [comment]
Hi, i m trying access a view from mysql in superset , but superset inform that "view could not be found, please double check your database connection, schema, and table name" . Is ther a way to access the mysql view.
