### ISSUE TITLE
Column name rename ability for Tabular reports

### ISSUE THREAD

**Issue by mohanguruswamy** [apache/incubator-superset#508]
Hi

Could you please let us know in a tabluar report can i rename the column name.
if yes please let me know.

Thanks
Mohan

**Comment by verydxz** [comment]
Similar to this, an enhancement proposal: column renamed in data source (table), can it automatically reflect in slices using this dim / metric?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
