### ISSUE TITLE
Improve export functionnalities on charts (png for instance)

### ISSUE THREAD

**Issue by LoicSan** [apache/incubator-superset#5081]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
It would be great if we dispose export functionnalities for charts to png files

### Actual results
No export button available to image format (only csv, json are available)

### Steps to reproduce
Try from a chart panel

**Comment by qin4zhang** [comment]
That's a good idea.

**Comment by kate-91** [comment]
That would be great!
