### ISSUE TITLE
Somthing broken around datasource access permissions

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#5092]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.4 and 0.25.5

### Expected results

User with specific datasource access can access the datasource

### Actual results

When trying to call both explore and dashboard endpoints i get:

```
 This endpoint requires the datasource mydatasource, database or `all_datasource_access` permission 
```

Requesting the permission and granting it from an admin user does not make the datasource accessible. It prints the emails content and the following error:

```
ERROR:flask_appbuilder.security.sqla.manager:Add Permission to Role Error: Can't flush None value found in collection Role.permissions
```

On user profile i see correctly the roles and the datasource it has access too. If I add to the user the can access all datasource access it can access the datasource.

**Comment by xrmx** [comment]
does the  `email/datasource_access` in core/views.py around line 951 makes sense?

```
                perm_view = security_manager.find_permission_view_menu(
                    'email/datasource_access', datasource.perm)
```

**Comment by xrmx** [comment]
Uhm ok, the issue was that for some reason the datasource.perm columns was empty.

**Comment by lhyundeadsoul** [comment]
> Uhm ok, the issue was that for some reason the datasource.perm columns were empty.

Hi @xrmx ,
I have a similar problem,  someone creates a table using SQL Lab, but they will get a permission error
>This endpoint requires the datasource null.ting ai-海外导航热门起终点-fdKqdl6vI, database or `all_datasource_access` permission.

Can u help me to solve this ? Thanks .
