### ISSUE TITLE
RPM installation package for superset?

### ISSUE THREAD

**Issue by saurabh1207** [apache/incubator-superset#5113]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Is there a way to create rpm build package of superset so that it can be installed as an rpm package?

E.g.
- use 'rpmbuild' to create .rpm package of superset.
- use 'rpm' to install above created package.

**Comment by mistercrunch** [comment]
There clearly has ways to do this.

The core team only provides pypi releases, github tags, and build instructions. Eventually proper Apache releases. Others have provided docker builds and other resources in the past. Refer to the rpm docs for more information.

**Comment by realXuJiang** [comment]
> Make sure these boxes are checked before submitting your issue - thank you!
> 
> * [x]  I have checked the superset logs for python stacktraces and included it here as text if any
> * [x]  I have reproduced the issue with at least the latest released version of superset
> * [x]  I have checked the issue tracker for the same issue and I haven't found one similar
> 
> Is there a way to create rpm build package of superset so that it can be installed as an rpm package?
> 
> E.g.
> 
> * use 'rpmbuild' to create .rpm package of superset.
> * use 'rpm' to install above created package.

supserset rpm build reference：
* https://github.com/fuslab/jdp-package/blob/develop/bigtop-packages/src/rpm/superset/SPECS/superset.spec
