### ISSUE TITLE
Displaying 0's instead of NULL in Table View and Line Chart

### ISSUE THREAD

**Issue by davidhassan** [apache/incubator-superset#5116]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
25.5

### Expected results
Do not display NULLS as 0's in Table View and Time Series - Line Chart

### Actual results
Displaying NULLS as 0's in Table View and Time Series - Line Chart

### Steps to reproduce
Have data that contains NULLS in between non NULL data. Display data in Table View or Line Chart and see 0's.

This makes graphs look awful when the data suddenly drops to 0 because of NULLS.
When looking at financial data in a table view it is misleading to 0 instead of NULL. Especially when dealing with prices, sales, etc.

![image](https://user-images.githubusercontent.com/1705367/40784790-a191cc02-64b4-11e8-8139-094bf05cc479.png)

The below row in a table view only contains data in the first estimate column. The other columns are NULL but displays 0's.

![image](https://user-images.githubusercontent.com/1705367/40785010-4b16a608-64b5-11e8-87c4-155ec7cbbb7c.png)

**Comment by davidhassan** [comment]
Looks like this is related to #4905. This is my update to say it is still not fixed. Anyone have a workaround?

**Comment by xrmx** [comment]
@davidhassan If it's a dup, close this one and add subscribe to the other one.

**Comment by davidhassan** [comment]
Closing it now thanks.
