### ISSUE TITLE
Need help with saml 2.0 integration.

### ISSUE THREAD

**Issue by RameshByndoor** [apache/incubator-superset#5123]
Make sure these boxes are checked before submitting your issue - thank you!

- ✅ I have checked the superset logs for python stacktraces and included it here as text if any
- ✅ I have reproduced the issue with at least the latest released version of superset
- ✅ I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25:master 
Hi, is superset supports saml2.0(ex: OpenSSL,Okta) auth for login method?. 
Or do I have to use flask-oidc as mentioned  here:
https://stackoverflow.com/questions/47678321/using-openid-keycloak-with-superset

**Comment by mistercrunch** [comment]
We support what FAB (flask-app-builder) supports, and SAML isn't on the list. We'd like to add it to the list at some point though as it's our preferred method at Lyft, but have been using oauth in the meantime.

I'm a committer on FAB and would be happy reviewing a PR that adds SAML integration there.

**Comment by mistercrunch** [comment]
No timeline no. I don't think we'll take this on.

**Comment by ktmud** [comment]
If you just need Superset to work with Okta, here's a quick workaround: https://gist.github.com/ktmud/2475282a166893e5d17039c308cbe50d

OpenID Connect is basically just OAuth 2.0, so `AUTH_OAUTH` from Flask-Appbuilder should already work.

**Comment by Bonifacio-Oliveira** [comment]
You might also want to take a look at this: https://stackoverflow.com/questions/67076134/apache-superset-with-okta-integration/67906688#67906688

**Comment by rohitpawar2811** [comment]
Hello now saml2 sso is supported or not.

**Comment by imakecodes** [comment]
I have the same question as @rohitpawar2811

**Comment by irbian** [comment]
2026, is SAML2 supported or planned?
