### ISSUE TITLE
Embed Chart to iframe

### ISSUE THREAD

**Issue by Belalm** [apache/incubator-superset#5137]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
When i take the iframe code from the chart and put it in a webpage, the url is reloading to the login page.
Could anyone help me on how to make the chart public (and please be very specific, i read a lot of stuff online and didn't reach any result)

Thanks

### Expected results
chart is viewed in iframe.

**Comment by zkenstein** [comment]
To enable public view you can set by change the PUBLIC_ROLE_LIKE_GAMMA = False to "True" in the config.py file line 151
