### ISSUE TITLE
Filter Box to update only a subset of slices in a dashboard

### ISSUE THREAD

**Issue by meghnakayam** [apache/incubator-superset#5139]
Make sure these boxes are checked before submitting your issue - thank you!

-  I have checked the superset logs for python stacktraces and included it here as text if any
-  I have reproduced the issue with at least the latest released version of superset
-  I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
Selecting a filter criteria should update only some of the chart slices in a dashboard.

### Actual results
Selecting a filter criteria is impacting all the charts in the dashboard.

### Steps to reproduce
Not a bug/issue; feature request if the functionality is not already available.

**Comment by mistercrunch** [comment]
The feature exists, if anything we need to document it better:
http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

**Comment by mistercrunch** [comment]
It's likely we'll have a way to do this through the UI at some point.
