### ISSUE TITLE
Change iframe result based on selection in the filterbox

### ISSUE THREAD

**Issue by MAliNaqvi** [apache/incubator-superset#5147]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
The logo should change with the filterbox

### Actual results
The logo doesn't change

### Steps to reproduce

I want to update an iframe, based on the selection in the filterbox like so:
https://www.dropbox.com/s/904llkwhxi0h17q/Screenshot%202018-05-29%2019.11.09.png?dl=0
![image](https://user-images.githubusercontent.com/13531332/41033413-751b9df2-6954-11e8-9239-f5a15e76e6d2.png)

The iframe chart only has the option of having a url like so
https://www.dropbox.com/s/p9pjtfvuyn9wi6l/Screenshot%202018-05-29%2019.09.54.png?dl=0
![image](https://user-images.githubusercontent.com/13531332/41033432-7efe5aa8-6954-11e8-8082-9908d950468a.png)

How can I get the selection in the filterbox and use it to update the url in the iframe?

**Comment by lilila** [comment]
same as #5075

**Comment by yneha** [comment]
Is there any solution for this? Can I pass dynamic parameters to the iframe URL to load the charts

**Comment by bianxintong** [comment]
same. can we reopen this issu
