### ISSUE TITLE
[Session] How to set session timeout?

### ISSUE THREAD

**Issue by qin4zhang** [apache/incubator-superset#5149]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
I could set session timeout in config.py, and when the time is out , user should login again.

### Actual results
I don't know how to set it

### Steps to reproduce
What's your advice?

**Comment by mistercrunch** [comment]
We use flask-appbuilder which uses flask-login, so all you have to do is add these configurations to your `superset_config.py`:
https://flask-login.readthedocs.io/en/latest/#cookie-settings

If you have time please add an FAQ entry in the docs!

**Comment by qin4zhang** [comment]
@mistercrunch OK!

**Comment by hushaoqing** [comment]
set PERMANENT_SESSION_LIFETIME in the Superset config file

**Comment by Ritesh205** [comment]
Is there a way where we can set some alerts before the session timeout ?

**Comment by Ritesh205** [comment]
> set `PERMANENT_SESSION_LIFETIME` in the Superset config file

Is there a way where we can set some alerts before the session timeout ?

**Comment by shawnzhu** [comment]
See context from https://stackoverflow.com/questions/34118093/flask-permanent-session-where-to-define-them

In superset, you can use `FLASK_APP_MUTATOR` to enable `session.permanent = True` to make Flask setup session expiration time. see my PR #16286
