### ISSUE TITLE
Initialize superset on Windows machine

### ISSUE THREAD

**Issue by Kenyatha** [apache/incubator-superset#5158]
Make sure these boxes are checked before submitting your issue - thank you!

- [/] I have checked the superset logs for python stacktraces and included it here as text if any
- [/] I have reproduced the issue with at least the latest released version of superset
- [/] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

Hello.  New to Superset and python environments.  Working in Windows 8.1.  Installed and operated superset yesterday.  Fantastic program; thanks!  Not sure how to restart/initialize superset.  Do I need to reinstall superset every time I use the program, or is there some other way?  Thanks.

**Comment by mistercrunch** [comment]
FYI we don't really support windows.

Superset is a web application and should probably run on a web server outside of your laptop. Though if you want to just run it on your laptop it's probably fine. To start/restart the web server you have to run the `superset runserver` command
