### ISSUE TITLE
How to disable preview data feature?

### ISSUE THREAD

**Issue by lynch0227** [apache/incubator-superset#5169]
Hi Guys,

How can I disable the preview data feature in sqllab?
Because some tables are very huge and have partition columns, when preview data automatically, I'm afraid that the sqllab will be crash.
Normally, we only need to check the table structure, don't need to get the data.

Thank you.

**Comment by mistercrunch** [comment]
Preview data only brings 100 rows by running a `LIMIT 100` query

**Comment by lynch0227** [comment]
OK, I got it. Thanks for your explanation.
