### ISSUE TITLE
Missing Metric names that were created on Superset

### ISSUE THREAD

**Issue by rohanagg** [apache/incubator-superset#5170]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results
I had upgraded the superset from 0.17.6 to 0.25.6. Upon upgrading, I didn't find the metrics that were created within superset in version 0.17.6.

![image](https://user-images.githubusercontent.com/30650330/41232504-34ce16e0-6da4-11e8-8676-6fa20b256987.png)  from Version 0.25.6

### Actual results
The results which I m getting in version 0.17.6 is attached below with the missing created metrics

![image](https://user-images.githubusercontent.com/30650330/41232575-72416b26-6da4-11e8-84ea-fbe4f9b4f18b.png)

**Comment by mistercrunch** [comment]
I can't think of any piece of logic or database migration that would delete metrics.

**Comment by rohanagg** [comment]
Issue is resolved. I had again updated the superset version
