### ISSUE TITLE
Metrics not saved when datasource changed

### ISSUE THREAD

**Issue by jasnovak** [apache/incubator-superset#5173]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
In explore view, when the datasource is switched, any metrics that occur in both datasources are preserved.

### Actual results
If metrics are selected, and the datasource is changed, all metrics are deleted. This is a problem if you have several datasources with the same fields and you are wanting to create the same chart on all of them.

### Steps to reproduce
Create a chart
Add some metrics
Change the datasource
Metrics are deleted

**Comment by JoenZhu** [comment]
I will say if you change datasource, metrics options won't change if datasource have different options.
that's an issue, too.
