### ISSUE TITLE
Superset demos not working on Debian and Installed by Pip

### ISSUE THREAD

**Issue by heoa** [apache/incubator-superset#5198]
The demos won't get rendered and the inital layout is broken, installed on Debian with pip. I tried initially to install the Superset from Source but flask error, then I tried pip which I get loading but no demos. How to resolve this? 

![Error](https://i.stack.imgur.com/qDo0s.png)

### Superset version

$ superset version
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.999.0dev
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

### Expected results

Working demo.

### Actual results

No demo.

### Steps to reproduce

```
# Install superset
pip install superset

# Create an admin user (you will be prompted to set username, first and last name before setting a password)
fabmanager create-admin --app superset

# Initialize the database
superset db upgrade

# Load some data to play with
superset load_examples

# Create default roles and permissions
superset init

# To start a development web server on port 8088, use -p to bind to another port
superset runserver -d

http://0.0.0.0:8088 to see login in and then go to the demos where I get no demo working, same template problem?
```

**Comment by mistercrunch** [comment]
The fact that you have version `0.999.0dev` makes it seems like you're running off of the repo, no a pip-installed version. What does `$ which superset` outputs?

**Comment by rageshpillai** [comment]
Same issue for me also. I tried "npm run bulild" and "npm run Dev" inside assets folder but it stuck after 95 per.
 Kindly help me resolve this issue

**Comment by mistercrunch** [comment]
If you're trying to make your own build: read the CONTRIBUTING.md

If you're installing from PyPI, follow the installation docs:
http://superset.apache.org/installation.html
