### ISSUE TITLE
Joining druid datasources?

### ISSUE THREAD

**Issue by MTShannon** [apache/incubator-superset#5209]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results

Like the title states, is it possible to combine two druid datasources to use in a visualization? I've read that you can use views to join tables, but I couldn't find anything regarding Druid datasources.

Thanks

**Comment by ahsanshah** [comment]
I dont believe you can do "joins" per se in Druid. However, these may be potential options to consider:

1. You can always use slices across Druid datasources on a dashboard and having a common Dimension Column name will allow filtering across those sources

2.  Superset recently has support for Multi-Line Chart which allows overlay of line charts which can indeed be across Druid data sources assuming a common Time Grain.  

3.  Annotations across 2 charts. this is similar to #2 but down side is that you cannot filter across the annotation as far as I am aware.

If you really do need tight integration you would have to either do it in the ETL pre-Druid ingestion or perhaps customize the SQL Alchemy engine to meet your needs.
