### ISSUE TITLE
Superset Meetup in SF on July 17th

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5239]
[not an issue, intended for repo watchers] xposting from the Apache mailing list (please subscribe if you haven't already)

---------------

Hey all,

We're happy to announce the first Apache Superset meetup in SF at Lyft HQ on July 17th.

Find all the information and RSVP at the link bellow.
https://superset.splashthat.com/

Hoping to see you there,

Max

**Comment by villebro** [comment]
Here's one vote for putting the talks up on youtube 👍

**Comment by vylc** [comment]
Meetup will be recorded and we'll post afterwards. Thx!

**Comment by rpwils** [comment]
did the talks make it to youtube?
