### ISSUE TITLE
How to create a similar dashboard based on an existing dashboard

### ISSUE THREAD

**Issue by hyjlqt** [apache/incubator-superset#5242]
I created a dashboard, how to quickly create a similar one.
For example, I created a dashboard about the Pacific Ocean.
Then I want to create another dashboard about the Atlantic Ocean,
With the same indicator, similar query, the only difference is that this dashboard is about the Atlantic.
Is there a quick way to create it.

**Comment by mistercrunch** [comment]
<img width="633" alt="screen shot 2018-06-18 at 9 38 47 pm" src="https://user-images.githubusercontent.com/487433/41577142-03f7deb0-7340-11e8-827b-dd9df254b324.png">

**Comment by hyjlqt** [comment]
Using this method, I can get the same dashboard.
Is there a way to quickly get a similar dashboard ?
All corresponding slices in these two dashboards have similar queries that contain different "where type = {0}".

**Comment by mtoto** [comment]
It should be possible to change jinja parameters in the duplicate dashboard, without it affecting the original dashboard.

**Comment by saq88** [comment]
I would also like to know how to efficiently go about this.
