### ISSUE TITLE
World map doesn't allow metrics that I have created. Unhashable type error with other options.

### ISSUE THREAD

**Issue by Tyler-Rex** [apache/incubator-superset#5247]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Expected results
I believe I should be able to choose metrics in the drop-down menu titled 'metric for color'.

### Actual results
The only option that works is COUNT(*). Any other option results in "unhashable type: 'dict'".
The metrics that I want to use do show up on the drop-down list for "Bubble size" but not "Metric for color".  I've compared my world map data set with that of the per-loaded 'wb_health_population" and found no differences. I also analyzed the world map titled "% Rural" and found that if I remove the preset metric for color ("sum__SP_RUR_TOTL_ZS"), I am not able to find it in the options or type it back in. This last piece of evidence suggests to me that this isn't user error in the GUI.

### Steps to reproduce
Upload excel sheet as CSV and create a world map using CIOC control. Check the sum option for the metric you want to use. Try to find that option in the list for "Metric for color" of the world map.

I realize this is kind of two errors in one issue, but I believe they are related. 

additional note: I can build just fine when choosing COUNT(*) as the metric for color, but that doesn't show what I need it to.

**Comment by mistercrunch** [comment]
Fixed here: https://github.com/apache/incubator-superset/pull/5080
