### ISSUE TITLE
SQLlab - Visualize the query results 

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#5255]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
Able to see the report

### Actual results
Incorrect report

### Steps to reproduce
Execute query in SQL lab and Click on Visualize.

SELECT year AS year,
               count(*) AS count
FROM
  (SELECT date_part('year',created_date) as year,
          count(*) as total_apps
   from application
   GROUP by 1
   order by 1) AS expr_qry
GROUP BY year
ORDER BY count DESC
LIMIT 10000;

How do I get rid of outer grouping?  Otherwise, how do I visualize the query results?

**Comment by mmuru** [comment]
I appreciate any help or pointer here.

**Comment by mistercrunch** [comment]
For now the easiest path for your specific chart is to simply add `application` as a table and not go through SQL Lab. The SQL Lab "Visualize" flow allows using your query as a logical view to slice/dice on top of it.

In the near future we'll be working on charting/visualizations inside SQL Lab that do not require going to the "explore view".

We're well aware that the "Visualize" flow is confusing and far from what it needs to be.

**Comment by mmuru** [comment]
@mistercrunch: Thanks for the information. Yes, I totally agreed, SQL Lab "Visualize" is very confusing flow. Since, I was able to create a dashboard through add table interface and thought it should be similar in SQL Lab interface. Only other option is to save results in a table and visualize it. 
 
Is there a workaround via config or db to disable "Visualize" in SQL Lab?

**Comment by YHGui** [comment]
@mistercrunch Is there any difference between about sql query process between sql lab and exploring chart, I find the time consumings of same sql statment in two places  are totally different, and some sql statment in sql lab is time-out.

**Comment by agabardo** [comment]
Does anyone know where to find a simple tutorial on how to create a chart from a query using multiple tables with inner join?
