### ISSUE TITLE
Error on creating a Druid datasource

### ISSUE THREAD

**Issue by ardlema** [apache/incubator-superset#5259]
### Superset version

0.15.0 (Using a PostgreSQL database as the metadata storage)

### Expected results

Create a Druid datasource

### Actual results

Getting the following error:

```
(pg.ProgrammingError) ERROR: operator does not exist: character varying = integer LINE 3: ...datasource_name = 'DruidDS' AND datasources.cluster_name = 1 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. [SQL: 'SELECT count(%(count_2)s) AS count_1 \nFROM datasources \nWHERE datasources.datasource_name = %(datasource_name_1)s AND datasources.cluster_name = %(cluster_name_1)s'] [parameters: {'datasource_name_1': 'DruidDS', 'cluster_name_1': 1, 'count_2': '*'}] (Background on this error at: http://sqlalche.me/e/f405)
```

### Steps to reproduce

Try to create a Druid datasource with the following inputs (see attached screenshot)
![adddruiddatasource](https://user-images.githubusercontent.com/1173286/41705980-e51fbe7a-753a-11e8-8c1e-0f8bba0bbfe8.png)

**Comment by mistercrunch** [comment]
Is this really on `0.15` version?  For druid we typically never create datasources manually. People just go Menu -> Sources -> Refresh Druid Metadata

**Comment by ardlema** [comment]
Yes, I'm installing Superset in a Hortonworks Data Platform cluster, the version is 0.15.0:
![supersetversion](https://user-images.githubusercontent.com/1173286/41760462-d6ea6efe-75f3-11e8-9dd5-55ed75a607a9.png)

**Comment by dfsklar** [comment]
This is definitely still an issue!
However, as noted, if the user simply lets Superset find the datasources via its scan feature, all is well.  The defect regards users who want to explicitly add a datasource.
