### ISSUE TITLE
91% additional asset processing Connection closed by remote host

### ISSUE THREAD

**Issue by jouharo** [apache/incubator-superset#5261]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Superset 0.999.0dev

### Expected results

100% asset processing

### Actual results

91% additional asset processing Connection closed by remote host. 

### Steps to reproduce

Our requirement is to deploy our own superset build on one of our cloud platform which is a ubuntu machine.

1. Follow the steps in this [url](https://superset.incubator.apache.org/installation.html#making-your-own-build) 

2. When we execute **yarn run build** command, asset processing started and after sometime everything stopped.

3. Getting "Connection closed by remote host." error message.

Can anyone please help me to understand the issue here. 

Thanks

**Comment by ahsanshah** [comment]
Depending on the machine specs this step can take some time and it does indeed hang for a bit at 91%.  You may just be getting timed out or connection closed.  I would just run a nohup so you can run in background.
