### ISSUE TITLE
superset_config.py not being picked up for db upgrade

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#5270]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results
Database upgrade script completes

### Actual results
It is upgrading the sqlite db and not our postgres db. 
we get this error in the upgrade - /opt/superset-venv/local/lib64/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '(u'datasource_name', u'datasources', u'datasource_name')' could not be located in PRAGMA foreign_keys for table metrics

### Steps to reproduce

create a superset_config.py and set the db to a different database other than the sqllite
Run superset db upgrade
you will see - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.

**Comment by mmuru** [comment]
Just make sure superset_config.py in PYTHONPATH environment variable.

**Comment by mistercrunch** [comment]
Also make sure `superset_config` is "interpretable". To test that you can fire up a python shell and `import superset_config` from the same shell you'd be launching the application.

**Comment by rpwils** [comment]
Yes superset runs fine with our config...its when we do the db upgrade this issue occurs

**Comment by mistercrunch** [comment]
Is it an issue with lacking the proper supporting library like `myqlclient` for mysql?

**Comment by kedargn** [comment]
I am facing the same issue. Migration is running on sqlite instead of mysql db. PYTHONPATH variable is set to superset_config.py. Using superset 0.25.6 version.

**Comment by mmuru** [comment]
PYTHONPATH environment variable should point to the location of the config file. Don't specify the file name.

**Comment by kedargn** [comment]
Thanks @mmuru. My PYTHONPATH environment was set to the correct path. However, I was running the migration as sudo and the environment variables were not getting inherited. Running the migration with sudo -E fixed it.
