### ISSUE TITLE
Dual Axis Line Chart: Inconsistent Metric Tool

### ISSUE THREAD

**Issue by teewhyli** [apache/incubator-superset#5284]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.25.5

### Expected results

I'm expecting when i click on the metrics selected for both the _Y_ & _X_ - axis to have a metric tool drop-down option.

Like this:
![image](https://user-images.githubusercontent.com/12669464/41887769-37aa7878-7956-11e8-8677-903880da8165.png)

### Actual results

Instead the _Y_ axis metric does produce the same way to customize agg:

![image](https://user-images.githubusercontent.com/12669464/41887853-a83c57b4-7956-11e8-9063-37ffb03051fe.png)

### Steps to reproduce

1.  Create a Dual Line Axis Chart.
2.  Select and Customize _Y_ axis option..

Is this intended? feels like it isn't and i think its the reason why i'm getting a unhash'd:dict

**Comment by hessam-shm** [comment]
This is a must needed feature for a dual axis line chart. For example in my case I have to have two charts overlayed for comparison purpose (they must be filterable so annotation layer is out of question) but inconsistent metric ruins it all.
![sc](https://user-images.githubusercontent.com/2587500/53795140-931e2e00-3f46-11e9-838c-2bb7ea3fa063.png)

**Comment by ebauch** [comment]
can confirm that this is fixed in 0.34
