### ISSUE TITLE
How can I setup CI/CD for SuperSet? A detailed guideline will be very helpful. Thanks in advance.

### ISSUE THREAD

**Issue by VinayMateLabs** [apache/incubator-superset#5298]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
CI/CD is very specific to your environment/company, and not to Superset. There are lots of different techs for running tests/builds/deploys and it's out of scope for Superset to provide a guide on how to do this. Ask your devops team.

We do provide CONTRIBUTING.md which explains how to properly build Superset from the repo though, you probably want to refer to that.
