### ISSUE TITLE
Chinese encoding error shows ???

### ISSUE THREAD

**Issue by zh6340521** [apache/incubator-superset#5299]
I used Oracle database, and the datasource uri is 'oracle://apps:XXXXXXXXXX@172.20.24.15:1571/TEST?charset=utf8'.

But the sql results still shows '???'.

Need help,tks.

**Comment by zh6340521** [comment]
![image](https://user-images.githubusercontent.com/25817048/41972292-048e0c40-7a44-11e8-8553-aad0ff42bca9.png)

**Comment by mistercrunch** [comment]
`?charset=utf8` is mysql thing AFAIK, you might have to find some equivalent for Oracle

**Comment by mistercrunch** [comment]
Also, maybe try py3 if you can as unicode is more native and tends to just work in py3.

**Comment by zh6340521** [comment]
?charset=utf8 is mysql thing AFAIK, you might have to find some equivalent for Oracle
-------------------
Tks very much,I think you are right ,do you know how to set the charset for oracle db?

**Comment by xuShine** [comment]
> I used Oracle database, and the datasource uri is 'oracle://apps:XXXXXXXXXX@172.20.24.15:1571/TEST?charset=utf8'.
> 
> But the sql results still shows '???'.
> 
> Need help,tks.

Do you have a solution? I have the same problem.

**Comment by wuhuanyan** [comment]
> > I used Oracle database, and the datasource uri is 'oracle://apps:XXXXXXXXXX@172.20.24.15:1571/TEST?charset=utf8'.
> > But the sql results still shows '???'.
> > Need help,tks.
> 
> Do you have a solution? I have the same problem.

I use this code to fix
`
import os
os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'
`

**Comment by xuShine** [comment]
> > > I used Oracle database, and the datasource uri is 'oracle://apps:XXXXXXXXXX@172.20.24.15:1571/TEST?charset=utf8'.
> > > But the sql results still shows '???'.
> > > Need help,tks.
> > 
> > 
> > Do you have a solution? I have the same problem.
> 
> I use this code to fix
> `import os os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'`

Thank you. this way is not good in a project. Use py3+ env.

**Comment by xuShine** [comment]
> Also, maybe try py3 if you can as unicode is more native and tends to just work in py3.

As you said, use py3,the problem won't appear. thks.

**Comment by lianyuteng** [comment]
I want to ask where the above code needs to be added ？

**Comment by lianyuteng** [comment]
I'm using the docker container
