### ISSUE TITLE
Feature Request: Prediction

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#5300]
Looking for feedback about integrating with a library like [facebook prophet](https://github.com/facebook/prophet) to predict the future values on a time series line chart. 
![image](https://user-images.githubusercontent.com/391567/42000116-86b71426-7a14-11e8-9e7a-cdb7582a9de7.png)

**Comment by mistercrunch** [comment]
Any good python libs for this?

**Comment by kkalyan** [comment]
Prophet has Python API. 
https://facebook.github.io/prophet/docs/quick_start.html#python-api

`scikit-learn` is another option but may be little heavy for this purpose.

**Comment by villebro** [comment]
Instead of implementing a single prediction library, providing a general API to plug any model into would give more freedom to end users. Perhaps registering the model(s) in superset_config.py and then being able to implement those in charts via the UI could be a good way of starting out.

**Comment by lihan** [comment]
Any updates on this?

**Comment by kkalyan** [comment]
its now available: https://github.com/apache/incubator-superset/pull/10324
