### ISSUE TITLE
How to create a linked drop-down list

### ISSUE THREAD

**Issue by sunyongmofang** [apache/incubator-superset#5304]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.0

### Expected results
How to create a linked drop-down list in filter box？Thanks a million.

**Comment by mistercrunch** [comment]
You can get to this using multiple "Filter Boxes" and using the features documented here http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

We're redesigning the filters in dashbaordv2 as a dashboard primitive as opposed to as a special visualization type. More about it here:
https://github.com/apache/incubator-superset/issues/5269
