### ISSUE TITLE
Can't load plugin sqlalchemy.dialects:druid

### ISSUE THREAD

**Issue by jmcorreia** [apache/incubator-superset#5307]
Hello all! 
I'm trying to create a datasource in superset, using pydruid. I can use pydruid cli successfully, but when I try to create a superset datasource, pointing to druid I'm getting this error: "Can't load plugin sqlalchemy.dialects:druid".

Any idea how to solve this?

Best regards.

### Superset version
0.15.0 integrated with hadoop

### Expected results
Integrate Druid with SQL lab

### Actual results
Unable to integrate Druid with SQL lab

### Steps to reproduce
Install pydruid and try to create a database using this plugin

**Comment by mistercrunch** [comment]
0.15.0 is super old. But my guess is pydruid is not installed in the context in which you run Superset (virtualenv? specific version of python?)

**Comment by jmcorreia** [comment]
@mistercrunch I'm using python 2.7.5. I tried to install pyhive and it worked perfectly.

**Comment by stevenlevey** [comment]
I have the same issue running the stock standard docker container. Does anyone have a solution to this?
