### ISSUE TITLE
When the user name have unicode characters, the datasources rest service produces a string exception.

### ISSUE THREAD

**Issue by Tonhiohouse** [apache/incubator-superset#5310]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.0

### Expected results
Get the datasources list

### Actual results
String Exception

### Steps to reproduce
1. Add a new datasource and get the datasource list (the name of the user in the session should contain unicode characters)
2. http://.../superset/datasources/

### Suggestion
-> Class BaseDatasource (superset/connectors/base/models.py)
--> property short_data

The "creator" key in the returned dictionary could be defined as: self.created_by.get_full_name()

**Comment by yamyamyuo** [comment]
did you configure the superset db charset? e.g.
`mysql://{user}:{passwd}@{host}:{port}/{db}?charset=utf8`
