### ISSUE TITLE
Refresh slice doesn't work for filter slices

### ISSUE THREAD

**Issue by LAlbertalli** [apache/incubator-superset#532]
I've noticed that forcing the refresh of a filter slice when a filter is applied cause the filter to display a wrong list of elements.
## Tested on:
- Caravel 0.9 (run with gunicorn on CentOs 6.3 and sqlite be, no cache)
- Caravel Master @ 7d27692 (run with Apache httpd + mod_wsgi on CentOs 7.2, memcache)
## Step to reproduce:
- Create a dashboard with a filter slice
- Select one (or more) value in the filter field
- Click on "Force refresh" icon
## Results
- The item selected in the filter are no more selected
- The graph in the dashboard are not updated (correct behavior)
- Trying to apply new filters, only the filters selected are available
## Expected results
- The filter configuration is retained
- The drop down selector displays all the available values
## Workaround
- After the select add again all the selected filters
- Remove all the selected filters
- Refresh again

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
