### ISSUE TITLE
Node ID for Dashboard automatically set 

### ISSUE THREAD

**Issue by natashamathur** [apache/incubator-superset#5326]
I am creating a set of dashboards that I expect to be able to be used with a variety of web pages. Since the same dashboard has to be used on multiple pages I have a "filter box" created where you should be able to choose which node_id you want to see the metrics for. 

Instead, even if you filter the page, a certain random node is always one of the filters. 

I checked and when you look at that metric through the 'Charts' part, there are no filters. 

Any idea what would cause a random default filter?

**Comment by mistercrunch** [comment]
The URL should capture the state (current filter) of the dashboard. If you save a dashboard while a filter is selected, it should persist if you follow the dashboard link from the "Dashboards" page.

It certainly should not be random though, seems very unlikely.

**Comment by natashamathur** [comment]
The issue ended up being that there was a default node_id set in the JSON metadata for the dashboard. Once I cleared that out this issue did not persist
