### ISSUE TITLE
"Metric Access On..." Permission not available

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#5331]
Make sure these boxes are checked before submitting your issue - thank you!

  I have checked the superset logs for python stacktraces and included it here as text if any
  I have reproduced the issue with at least the latest released version of superset
  I have checked the issue tracker for the same issue and I haven't found one similar

Superset version
Superset 0.25.6

Expected results
User don't have access to my metric can find and visualize it. This is true across 2 separate Superset instances I have set up

Actual results
Don't find this permission : "metric access on [cluster1].[datasource1].[my metric]"

Steps to reproduce
Edit the datasource (Menu -> Source -> Druid datasources -> edit the record "datasource1") and go to the tab List Druid Metric. Check the checkbox Is Restricted in the row of the metric revenue

Edit the role (Menu -> Security -> List Roles -> edit the record “Admin”), in the permissions field, type-and-search the permission metric access on [cluster1].[datasource1].[revenue] (id: 1), then click the Save button on the bottom of the page.

**Comment by mistercrunch** [comment]
The feature was community contributed and apparently not well covered by tests. AFAIK Airbnb and Lyft don't use that feature. The feature may be broken.
