### ISSUE TITLE
Install Apache Superset on Windows OS : I am not able to install superset on my windows OS. Can you please asist?

### ISSUE THREAD

**Issue by abendigiri** [apache/incubator-superset#5332]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by abendigiri** [comment]
Install Apache Superset on windows OS : I need help in installing apache superset on windows OS.

**Comment by mistercrunch** [comment]
Windows is not officially supported though people have succeeded running it.

**Comment by abendigiri** [comment]
I would need help in installing superset on windows os. Any help would be
appreciated.
I would also request you to please help me with:

1. Developer Licensing cost or is it free?
2. OEM licensing cost for superset?

Thanks,
Abhijit.

**Comment by mistercrunch** [comment]
We don't support Windows. License is Apache. Superset is free open source software.

**Comment by faifaifai** [comment]
Not sure if it is appropriate to answer here because Windows installation is not officially supported, so it is not an issue. 
I have succeeded installing it. Just follow the installation guide. 
However, I would recommend installing with Python 3.6 for windows for the time being, there is an issue about the compatibility between 3.7 and MS C++ Build Tools. other parts just follow the installation guide and worked fine. 

Hope this helps.

**Comment by subhsaha** [comment]
I have tried multiple time installing super-set and it failed and error is error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools i also tried installing but same error

**Comment by wanjus** [comment]
Apache Superset-How to Install in Windows 8.1
https://youtu.be/0zhQ52BQQ5s
For Windows 10 I just followed the installation guide and succeeded.
Hope this helps everyone.

**Comment by richdevboston** [comment]
WINDOWS 10 Python 3.6 INSTALLATION ISSUE STILL OPEN !!    

Geohash build fails.  Superset package build fails.  It appears that all the other packages build successfully.  

(demo) (base) c:\superset\demo\Scripts>pip install python-geohash
Collecting python-geohash
Using cached https://files.pythonhosted.org/packages/9c/e2/1a3507af7c8f91f8a4975d651d4aeb6a846dfdf74713954186ade4205850/python-geohash-0.8.5.tar.gz
Building wheels for collected packages: python-geohash
Building wheel for python-geohash (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-8f2vkeqi' --python-tag cp37
cwd: C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash
Complete output (22 lines):
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying geohash.py -> build\lib.win-amd64-3.7
copying quadtree.py -> build\lib.win-amd64-3.7
copying jpgrid.py -> build\lib.win-amd64-3.7
copying jpiarea.py -> build\lib.win-amd64-3.7
running build_ext
building '_geohash' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON_MODULE=1 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpsrc/geohash.cpp /Fobuild\temp.win-amd64-3.7\Release\src/geohash.obj
geohash.cpp
src/geohash.cpp(383): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(428): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(429): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(528): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\programdata\anaconda3\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
ERROR: Failed building wheel for python-geohash
Running setup.py clean for python-geohash
Failed to build python-geohash
Installing collected packages: python-geohash
Running setup.py install for python-geohash ... error
ERROR: Command errored out with exit status 1:
command: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\lysak\AppData\Local\Temp\pip-record-i3ibyuj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\superset\demo\include\site\python3.7\python-geohash'
cwd: C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash
Complete output (22 lines):
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying geohash.py -> build\lib.win-amd64-3.7
copying quadtree.py -> build\lib.win-amd64-3.7
copying jpgrid.py -> build\lib.win-amd64-3.7
copying jpiarea.py -> build\lib.win-amd64-3.7
running build_ext
building '_geohash' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON_MODULE=1 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpsrc/geohash.cpp /Fobuild\temp.win-amd64-3.7\Release\src/geohash.obj
geohash.cpp
src/geohash.cpp(383): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(428): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(429): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(528): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\programdata\anaconda3\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\lysak\AppData\Local\Temp\pip-record-i3ibyuj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\superset\demo\include\site\python3.7\python-geohash' Check the logs for full command output.

(demo) (base) c:\superset\demo\Scripts>

**Comment by wanjus** [comment]
> 
> 
> WINDOWS 10 Python 3.6 INSTALLATION ISSUE STILL OPEN !!
> 
> Geohash build fails. Superset package build fails. It appears that all the other packages build successfully.
> ## (demo) (base) c:\superset\demo\Scripts>pip install python-geohash
> Collecting python-geohash
> Using cached https://files.pythonhosted.org/packages/9c/e2/1a3507af7c8f91f8a4975d651d4aeb6a846dfdf74713954186ade4205850/python-geohash-0.8.5.tar.gz
> Building wheels for collected packages: python-geohash
> Building wheel for python-geohash (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-8f2vkeqi' --python-tag cp37
> cwd: C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash
> Complete output (22 lines):
> running bdist_wheel
on-geohash' Check the logs for full command output.

> 
Hi richdevboston,

please tray: pip install wheel 
(setuptool and command line tool for wheel files) [](https://pypi.org/project/wheel/   )

pip install python-geohash

and remember the video i mentioned 

step by step

Happy Coding
wanjus

**Comment by ivansocket** [comment]
I am trying to install SuperSet with Docker (Following the "Start with docker" instructions: https://superset.incubator.apache.org/installation.html)
After the command: docker-compose run --rm superset ./docker-init.sh

The following output appears in terminal and it fails to install.


clean-webpack-plugin: /home/superset/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/superset/.npm/_logs/2019-09-10T16_43_28_302Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd superset/assets     && npm ci     && npm run build     && rm -rf node_modules' returned a non-zero code: 1

**Comment by ricky-bhatia** [comment]
> I have tried multiple time installing super-set and it failed and error is error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools i also tried installing but same error

I was also getting the same errors even after installing Visual C++ build tools. I was then able to resolve the issue by doing following steps:

1. pip install wheel
2. Download the below file from [https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-geohash](url)
    python_geohash‑0.8.5‑cp37‑cp37m‑win32.whl
3. pip install _path-to-above-downloaded-file_
4. pip install superset

**Comment by karunbkk** [comment]
I have tried to installing super-set and it failed and error is error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools":

![thumbnail_image001](https://user-images.githubusercontent.com/47136705/80061231-53514600-854e-11ea-9e1c-b93a9d81c4d0.png)

Could any one please help me on this issue

**Comment by ricky-bhatia** [comment]
Please see the workaround that worked for me in comment
https://github.com/apache/incubator-superset/issues/5332#issuecomment-554288012
.

**Comment by karunbkk** [comment]
Hi Team,

I'm unable to add MySQL connection in database on superset and getting the error
![image](https://user-images.githubusercontent.com/47136705/80524173-d50cfd80-89ac-11ea-9283-900f7d676f19.png)

can anyone help me on this

How can I add Database on sources and also how can i create new dashboard using the data

**Comment by PBPE** [comment]
Windows 10 22h2 and superset 2.4.1 Intalation

based on https://www.youtube.com/watch?v=Sb_At33QPfw
install : 
	- cmder https://cmder.net
	- Python https://www.python.org/downloads/
	- notepad++
	- Virtual studio c++ community

python -m pip install --upgrade setuptools pip

pip install cryptography

pip install virtualenv

# Test Folder creation
Md c:\test
cd c:\test

# virtual environnment Creation
Python -m venv devzone


# virtual environment activation
c:\Test\devzone\Scripts\Activate.bat

# update pip in virtual environnment
python -m pip install --upgrade setuptools pip

# install superset
pip install apache-superset

# to prevents "Flags" error sql_parse.py Modification
c:\test\devzone\lib\site-packages\superset\sql_parse.py ligne 67
sqlparse.keywords.FLAGS -> .IGNORECASE | re.UNICODE).match

# to prevents Security stop
Variable d'environnement
SUPERSET_SECRET_KEY = avec openssl rand -base64 42
FLASK_APP = superset
c:\test\devzone\lib\site-packages\superset\config.py ligne 191


#M Superset DB upgrade
superset db upgrade

# Admin user creation
flask fab create-admin

# Load examples in DB
superset load_examples

# Superset init
superset init

# Launch Superset test
superset run -p 8088 --with-threads --reload --debugger
