### ISSUE TITLE
0.26.0 upgrade fails - looks to be a change in the setup.py throwing this error

### ISSUE THREAD

**Issue by darylerwin** [apache/incubator-superset#5339]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.0 upgrade

### Expected results
perform the update

### Actual results
. ./venv25rc3/bin/activate
python -V
Python 2.7.12
pip -V
pip 10.0.1 from /home/derwin/venv25rc3/local/lib/python2.7/site-packages/pip (python 2.7

pip install superset --upgrade
Collecting superset
  Using cached https://files.pythonhosted.org/packages/89/36/3dcf6e8e9ab80e94af0bc4e6ddf296d8ece737f52b39f721e0296267a9e8/superset-0.26.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-liolni/superset/setup.py", line 19, in <module>
        with open('README.md', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

### Steps to reproduce
pip install superset --upgrade

I see that setup.py was just updated to include this encoding code - did that change the requirements to install/update setup from 2.7 to 3.x?

Also tried running 
wget https://raw.githubusercontent.com/apache/incubator-superset/master/requirements.txt
pip install -r requirements.txt

**Comment by xrmx** [comment]
Fixed in #5338

**Comment by xrmx** [comment]
This has been fixed in 0.26.1, please close.

**Comment by aleksi75** [comment]
It seems that the newest distribution 0.26.1 ist not available at pypi.

pip list --outdated --trusted-host pypi.python.org
==> 
superset         0.25.6  0.26.0  sdist

**Comment by aleksi75** [comment]
0.26.2 is working. thx
