### ISSUE TITLE
Disable (Export to CSV, Explore Chart) from Dashboard Permission.

### ISSUE THREAD

**Issue by nihalbtq8** [apache/incubator-superset#5340]
Is there any permission that disable the export to csv option in a Slice from within the Dashboard?

I couldnt find any in documentation.

I also tried editing commenting out the relevant part in /static/assets/javascripts/dashboard/components/SliceHeader.jsx

`                  tooltip={t('Edit chart')} 
                > 
                  <i className="fa fa-pencil" /> 
                </TooltipWrapper> 
              </a> 
/*              <a className="exportCSV" href={this.props.exportCSVUrl}> 
                <TooltipWrapper 
                  placement="top" 
                  label="exportCSV" 
                  tooltip={t('Export CSV')} 
                > 
                  <i className="fa fa-table" /> 
                </TooltipWrapper> 
              </a> */ 
              <a className="exploreChart" href={this.props.exploreChartUrl} target="_blank">
`

Why doesnt this work?

**Comment by amitboutiqaat** [comment]
Any update
