### ISSUE TITLE
Superset 0.24 and MySQL db - Can not create / refresh charts because of big db

### ISSUE THREAD

**Issue by miloradkrstevski** [apache/incubator-superset#5342]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24

### Expected results
Faster creation (refresh) of charts

### Actual results
Almost all of my charts can no be created (refreshed) because the creation time goes over 60 sec.

### Steps to reproduce
I work on Superset 0.24 with MySQL db connection. My db is 31.4GB from which 17.6GB is data and 13.8 is index on some of the most used columns. The records are in total 45.7M rows with 44 columns. The final results are not pointed to show more than 50k records (usually a lot less).

1. Can someone please help me is it possible to work with this big db in Superset?
2. What HW is needed for this Superset and db (they are on the same machine)? My config is virtual machine on SSD disk with 4x CPU(at)2.6GHz and 32GB RAM.
3. Do I need to split Superset (as app virtual) and MySQL db (as db virtual) in order to succeed in visualization?

Thank you very much in advance.

**Comment by aaronbannin** [comment]
@miloradkrstevski The first step would be to profile the queries Superset is submitting to the db. It sounds like Superset may not be using any of your indexes. The specific indexes and configurations needed will depend on your schema and integration, but a great place to start is looking at the `where` clause of Superset queries.

**Comment by miloradkrstevski** [comment]
Thank you @aaronbannin. Any other suggestion?

**Comment by miloradkrstevski** [comment]
I solved pretty much of the speed migrating from MySQL to PostgreSQL.
