### ISSUE TITLE
'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by wgzhao** [apache/incubator-superset#535]
When i use timeseries-based charts. and the groupable column include chinese ,it occurred.

the output in console is the following:

```
Traceback (most recent call last):
  File "/Users/wgzhao/Codes/caravel/caravel/views.py", line 674, in explore
    payload = obj.get_json()
  File "/Users/wgzhao/Codes/caravel/caravel/viz.py", line 260, in get_json
    'data': self.get_data(),
  File "/Users/wgzhao/Codes/caravel/caravel/viz.py", line 1020, in get_data
    chart_data = self.to_series(df)
  File "/Users/wgzhao/Codes/caravel/caravel/viz.py", line 999, in to_series
    name = ["{}".format(s) for s in name]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

environment:

OS: Mac OSX 10.11.4
Python: python 2.7
database: MySQL.
<img width="1062" alt="2016-05-29 1 17 50" src="https://cloud.githubusercontent.com/assets/1001616/15631499/cb6d8cec-259f-11e6-91b6-f13660e5847c.png">

When I use python3.x ,it works!

**Comment by Qt7mira** [comment]
Because the default str encoding of Python2.7 is ascii, it conflicts with unicode.
The python3 distinguishes the unicode str and byte arrary, and the default encoding is no longer ascii.

**Comment by chejinye** [comment]
in  : caravel/_init_.py 
import sys
reload(sys)
sys.setdefaultencoding('utf8')
@wgzhao

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 562 days. Feel free to comment and request for this issue to be reopened.
