### ISSUE TITLE
Installation on Cygwin fails

### ISSUE THREAD

**Issue by xgadjhe** [apache/incubator-superset#5351]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.1

### Expected results
Installation should succeed.

### Actual results
Installation fails with this error message:

IOError: [Errno 20] Not a directory: u'/cygdrive/c/Users/xgadjhe/AppData/Local/Temp/pip-req-build-W9rpfe/superset/static/assets/package.json'

I use Python 2.7.14
Seems that the problem is the "Cygwin"-format of the path ... 

### Steps to reproduce
Open babun-shell and run 
`pip install https://github.com/apache/incubator-superset/archive/0.26.1.zip --verbose`

**Comment by mistercrunch** [comment]
Windows/Cygwin are not supported.

**Comment by ctivanovich** [comment]
This is so odd. One major reason for using a docker container should be to make superset cross platform compatible. Why are 80% of the world's computers not supported in building this tool and deploying it?

**Comment by mistercrunch** [comment]
Seems like docker should work on Windows. If that's not the case that's a problem with docker/windows. Is Cygwin production worthy?

Also what % of the world's web server run linux/windows?
