### ISSUE TITLE
Columns with NULL data throw "Unexpected Error" in Table View Chart

### ISSUE THREAD

**Issue by davidhassan** [apache/incubator-superset#5353]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
Table View chart to load when column data contains NULL's. In previous versions it would display NULL's as 0's.

### Actual results
Unexpected Error is thrown and subsequently the table did not load.

### Steps to reproduce
1. Create a table view with a data set that has a column that contains some data and the rest NULL.
2. Select column with NULL data in NOT GROUPED BY section.
3. Run Query and see "Unexpected Error"

It seems this problem only exists with multiple rows of a column containing NULL data.  I can load one row with NULL  data in columns. As soon as I load more rows I get "Unexpected Error".

**Comment by calve** [comment]
We experience this on 0.26.0 aswell. I can see that the CSV export work as expected

**Comment by calve** [comment]
I failed to reproduce the behaviour by setting NULL values to the embedded `superset.db` sqlite database, so maybe this as to do with the database engine ? All of my affected backend are postgreql

**Comment by davidhassan** [comment]
My backend is MS SQL Server. Could be a db issue.

**Comment by aladyeva-bmc** [comment]
The same problem appears with PostgreSQL backend

**Comment by villebro** [comment]
Could not reproduce in master, so this seems to be resolved.

**Comment by yamyamyuo** [comment]
@villebro Same problems here. It seems the frontend could not handle NULL value. We use Presto as the query engine, does this #5487 also covers the presto's return data?

**Comment by villebro** [comment]
Not sure it's related, but I'm getting weird behavior in `NOT GROUPED BY` tables, for some cases it seems to be dropping off the last column from the table even though it's available in the query result. Will investigate.

**Comment by villebro** [comment]
The weird behaviour was caused by some tweaking I had done, aka I am still unable to replicate this in `master` branch.

**Comment by yamyamyuo** [comment]
@villebro this can be reporduced in release 0.26.2 version

**Comment by davidhassan** [comment]
This has been resolved in later versions.
