### ISSUE TITLE
Need to fully refresh dashboard once a slice encounters an error 

### ISSUE THREAD

**Issue by IljaKroonen** [apache/incubator-superset#537]
What I do:
I fill in two filter fields so that no data passes. At the point, the visualizations show a "No data, review your incantations" error.
I remove the filter values.

What happens:
The error is still displayed in place of the visualizations.

What should have happened:
The error disappears and the visualizations come back up

Context: I tested this scenario with the normal line chart and the latest version of caravel on master.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
