### ISSUE TITLE
Random column order with Table View

### ISSUE THREAD

**Issue by nbonnotte** [apache/incubator-superset#5373]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

`{"GIT_SHA": "b480cb344433d58d41594dca171e90287c57dc4a", "version": "0.26.3"}`

### Expected results

The order of columns should match the order set in the `GROUP BY` section

It used to be like this with version <0.26

### Actual results

The order is random, and changes completely when new columns are added. 

It seems though that the same columns will always be in the same random order. But that order changed when upgrading from 0.26.0 to 0.26.3, so my users start complaining :(

![image](https://user-images.githubusercontent.com/9929982/42561889-9e80271e-84fa-11e8-9868-6c86ea60e45d.png)

**Comment by yamyamyuo** [comment]
FYI, I have fixed this issue in #5566 , and I have pushed this to our production environment. The metrics column order finally work well.
