### ISSUE TITLE
Datasource Dropdown in "New Chart" empty after Migration

### ISSUE THREAD

**Issue by LStampf** [apache/incubator-superset#5381]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Superset 0.26.3
Python 2.7.5 / 3.5
Postgres 10.4

### Expected results

Dropdown containing my tables

### Actual results

Dropdown empty. 

![tables](https://user-images.githubusercontent.com/445299/42639621-b8244c12-85f0-11e8-9214-c3238f1d2aa7.png)

### Steps to reproduce

I cloned the superset metadata DB from postgres 9 to 10 (data looks the same, dont think the problem lies here), and migrated superset from 0.24 to 0.26.3. I can still open my datasources and existing charts, but when I try to create a new one, the dropdown to select the datasource is empty.

**Comment by mistercrunch** [comment]
Could it be that the user doesn't have access to all data or some databases?

**Comment by LStampf** [comment]
I don't think so. I can see my tables in the tables view, and the charts I migrated are all accessing the same DB and those are working. It's really strange.

**Comment by hectorgimenez** [comment]
Same problem here. I'm using MySQL 8.0, after upgrading from superset 0.25.6 to 0.26.3 the datasource dropdown from new chart page is empty. But I can open and manage all my existing datasources and my current charts are still linked to the existing datasources. 🧐

**Comment by LStampf** [comment]
Quick update: The problem also exists in a python 3.5 installation.
