### ISSUE TITLE
[bug] big number with trend line's tooltip renders in the upper left of the page

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5382]
Applies to both the dashboard and the explore view
<img width="445" alt="screen shot 2018-07-12 at 10 11 14 am" src="https://user-images.githubusercontent.com/487433/42638572-fbec2b7a-85bb-11e8-92a2-53837572bb56.png">

**Comment by hughhhh** [comment]
I think we should focus on the new big number!
https://github.com/apache/incubator-superset/pull/4313

**Comment by hughhhh** [comment]
@williaster thoughts on this?

**Comment by williaster** [comment]
ooooO I think the new one would be dope!

**Comment by hughhhh** [comment]
@williaster do you have bandwidth to close this out?

**Comment by williaster** [comment]
webpack 4 is higher pri for me but will try to get to it next week.
