### ISSUE TITLE
Integration points? REST, SPARQL,ODATA,GRAPHQL others

### ISSUE THREAD

**Issue by vromero** [apache/incubator-superset#5389]
Is there or is it planned to have integration points so the community can write its own data sources?

I'm thinking of SPARQL or REST services.

It would be very interesting for me and I would be probably interested in writing the integration for at least one of the two.

**Comment by mistercrunch** [comment]
The preferred way is to go through SQLAlchemy when possible, otherwise you can look at what's under `connectors/` there's a set of base classes you'd need to implement, and 2 implementations for `druid/` and `sqla/`

**Comment by graphadvantage** [comment]
Love to see GraphQL to connect to Neo4j...

**Comment by metaperl** [comment]
> Love to see GraphQL to connect to Neo4j...

All datasources ready for Superset consumption are single-table. In thinking about how an "OLTP" Neo4j database could be pre-queried down into a single-table OLAP datastore, one wonders if this has ever been done and if the target database was Neo4j.

**Comment by cancan101** [comment]
I put together a SQLAlchemy Dialect for connecting to a GraphQL API ([GitHub](https://github.com/cancan101/graphql-db-api)) which in turn allows Superset to connect to a GraphQL API. I did a writeup of my approach here: https://blog.alexrothberg.com/2022/03/09/running-superset-against-graphql/

**Comment by brandonjjon** [comment]
Late to the party here but for anyone looking for OData support, I built a dialect and adapter that connects Superset to any OData v4 API: https://github.com/brandonjjon/sqlalchemy-odata

Same approach @cancan101 took, but for OData. It uses https://github.com/betodealmeida/shillelagh to expose OData entity sets as SQL tables, with SQLite handling all query operations locally. Hopefully this helps!
