### ISSUE TITLE
Convert Distribution/Bar Charts into percentages

### ISSUE THREAD

**Issue by hang15** [apache/incubator-superset#539]
In bar charts, when using the stacked distribution option, I cannot expand the charts to compare the percentages of each sector within the stacked distribution.

Also no way to convert y-scale as percentages for bar chart rather than raw numbers.

**Comment by mistercrunch** [comment]
The key is to hook up this feature:
https://github.com/novus/nvd3/pull/235/files

**Comment by optossav** [comment]
This would be a really nice addition. Contribution toggle sort of does this but being able to get the actual data in percentages would be great.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 619 days. Feel free to comment and request for this issue to be reopened.
