### ISSUE TITLE
Change HotKeys to Cmd + Enter

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#5391]
As a user, I would like to run a query using Cmd + Enter in Sqllab

**Comment by aok1425** [comment]
It used to be ctrl + enter up until recently. How do you feel about ctrl + enter instead?

**Comment by hughhhh** [comment]
ctrl + enter is fine

**Comment by ofirz** [comment]
This should have been open to align with client platform config; Windows typically use CTRL+Enter, Mac typically use CMD+Enter. Superset should allow this to be configured for the installation default and for the individual users, if they wish to override it.
