### ISSUE TITLE
DeckGL Polygon Tooltip?

### ISSUE THREAD

**Issue by ahsanshah** [apache/incubator-superset#5396]
Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
25.5

### Expected results
Expect the Advanced Deck GL option for "Javascript tooltip generator" to allow for hover/tooltip JS

### Actual results
Unable to use the tooltip generator.  Get a "This functionality has been disabled for security reasons"

### Steps to reproduce

Is this functionality available or still in the works?  Should we be able to use for example a Deck GL Polygon and allow hover over tooltips?  The documentation is unclear on this feature but I am able to see the Controls section for this under Advanced.

**Comment by mistercrunch** [comment]
Set `ENABLE_JAVASCRIPT_CONTROLS  = True` in your `superset_config.py`
https://github.com/apache/incubator-superset/blob/master/superset/config.py#L388

**Comment by alldoami** [comment]
@ahsanshah did you get anything to come up from using the tooptip generator?

**Comment by ahsanshah** [comment]
@alldoami yes per the config change and bounce of the environment it works.  We are currently having our security evaluate the potential risk of XSS.

**Comment by alldoami** [comment]
@ahsanshah how were you able to display the extraProps? I'm unfamiliar with Javascript, but haven't been able to find many resources on how to use Deck GL and Superset

**Comment by alldoami** [comment]
I've tried that, but for some reason, it thinks there is a "title" for every long, lat, which is not true. It continues to display a different "title" each time I move the mouse even though it should only be displaying on locations that have a title. In Screen grid, the only valid locations are the ones that are the populated squares. Did you have any problems like this?

**Comment by alldoami** [comment]
I think there are two axes that aren't aligning with each other and isn't producing the correct titles. The lat long that I inputted isn't being aligned with the lat long in the map.

**Comment by ahsanshah** [comment]
We did not seem to have that issue.  We are using a DeckGL Scatter and it works fine and only shows the tooltip upon hover of a point in your dataset (there should not be any hover unless it exists).  What version are you on? Maybe worth opening a separate issue as this one is closed?   

If you mean you are showing NULL titles when they are indeed NULL and want to "hide" just use some logic llike this: https://codepen.io/vis-gl/pen/pLLQpN

  if (object) {
    tooltip.style.top = `${y}px`;
    tooltip.style.left = `${x}px`;
    tooltip.innerHTML = `
<div><b>Average Property Value &nbsp;</b></div>
<div><div>${object.properties.valuePerSqm} / m<sup>2</sup></div></div>
<div><b>Growth</b></div>
<div>${Math.round(object.properties.growth * 100)}%</div>
`;
  } else { 
    tooltip.innerHTML = '';
  }

**Comment by alldoami** [comment]
Ya I opened a ticket, but no one has responded to it yet. Hopefully someone will! It's very frustrating. Thanks for the help!

**Comment by syazwan0913** [comment]
> After you enable the extraProps, you can just write a JS function, here is a rough skeleton.
> 
> function updateTooltip(object) {
> title = object.object.extraProps.amenities.replace(/,/g , ", ");
> return (
> '
> 
> Title:
> '+ object.object.extraProps.title'
> );
> }
> You should be able to see the hover and add whatever elements as needed in the function.
> 
> One item we want to do is dynamically position the tooltip. I assume there is a way but unsure. For instance, as you go to the edges of the slice and your tooltip is verbose, can we dynamically position the tooltip based on the location in the slice?

@ahsanshah Hi there. I'm unfamiliar with javascript and I tried the function but when I run the query, it show "ReferenceError : $ is not defined". What is the correct way to put the script?
