### ISSUE TITLE
[dashboard v2] Creation of new tab on existing dashboards links tabs

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#5402]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
New tab should create a blank tab

### Actual results
New tab creates a duplicate of the original tab. (ok, can live with this) But then once you start editing the new tab (ie. removing a chart), it makes the same edit to the original tab.

### Steps to reproduce
(1) Convert existing dashboard to V2 dash
(2) Edit dashboard
(3) Click on + for new tab
(4) Remove a chart from new tab

**Comment by vylc** [comment]
@graceguo-supercat @williaster any chance this will get fixed soon?

**Comment by williaster** [comment]
Hmm this sounds like a regression, I've never seen this. @graceguo-supercat have you? Can look into it.

**Comment by vylc** [comment]
Let me know if you can view this video...
I didnt' want to post it on github since it has lyft metrics...

Thanks!
Vyl
*Vyl Chiang*
Product
650.279.1185
[image: Lyft] <http://www.lyft.com/>

**Comment by williaster** [comment]
hmm can't see any video @vylc

**Comment by williaster** [comment]
@vylc in your video your charts, are not in any tabs. you are using embedded tabs (you can read the user docs on top-level tabs vs embedded tabs [here](https://gist.github.com/williaster/bad4ac9c6a71b234cf9fc8ee629844e5#tabs)), and they have no content in either of them. So then when you "switch" tabs, you're seeing the other empty tab.

**Comment by vylc** [comment]
Got it. thanks--from a usability perspective, we should by default add all
charts to a tab when a tab is added.
*Vyl Chiang*
Product
650.279.1185
[image: Lyft] <http://www.lyft.com/>

**Comment by williaster** [comment]
I disagree with that, a user doesn't necessarily want all content added to a tab if they add it. if you want top-level tabs, that's the effect it will have.
