### ISSUE TITLE
Migration b4456560d4f3 is ignored on MySQL

### ISSUE THREAD

**Issue by LAlbertalli** [apache/incubator-superset#542]
I noticed that the migration b4456560d4f3 is not applied and fails silently on MySQL. The reason is the same that failed the tests on #531. In MySQL the constraint is called `table_name` and not `tables_table_name_key`.

**Comment by x4base** [comment]
Is b4456560d4f3 the last version in the db history?
I encountered similar problem once: the migration is actually applied to the db, but the version number in  table "alembic_version" in the database is not updated to the newest one. 
Is your problem the same as mine?

**Comment by LAlbertalli** [comment]
No, there are other migrations after this one that are correctly applied.
As I mentioned, it seems to suffer from the same problem of commit #531. They simply put a try/except to make it work on sqlite, but this swallow errors on every other db when the migration is wrongly written.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 640 days. Feel free to comment and request for this issue to be reopened.
