### ISSUE TITLE
New time filter related issues

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5423]
* if examples are loaded after db migrations have been made, the `World's bank` example dashboard shows `No data` on pretty much all charts
* no easy way to remove all time filters, maybe we need a radio button for this
* when using the calendars to put empty dates (trying completely remove filters), the query returns no data

@betodealmeida @vylc

**Comment by betodealmeida** [comment]
@mistercrunch, (1) was fixed in https://github.com/apache/incubator-superset/pull/5412. I'll modify the migration script so that the time filter is set to a value that has data (instead of "Last week").

I'll fix (2). For (3), I can't repro — emptying the dates returns `∞ : ∞` for me on master.
