### ISSUE TITLE
Dashboard V2 layout

### ISSUE THREAD

**Issue by SevenDL** [apache/incubator-superset#5429]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y ] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
dashboard V2

### Expected results
When I add some charts in one dashboard,I hope I can adjust the layout when there is enough space to make the dashboard more beautiful.

### Actual results
I can't  drag any component to the destination where seems have enough space.

### Steps to reproduce

1. Add charts or markdown in one dashboard.
2.Adjust their width and heights.
3.Drag some components  to make the layout more good.
4.Failed drag with the warning“There is not enough space for this component,Try decreasing its width, or increasing the destination width.”

![qq 20180719173657](https://user-images.githubusercontent.com/33197465/42934715-60c66164-8b7a-11e8-845d-3f6969027511.png)

**Comment by mistercrunch** [comment]
@williaster @graceguo-supercat

**Comment by williaster** [comment]
Hi @SevenDL, Row content flows left to right, and columns top to bottom. So you should be able to fix this by 
- first adding a column in the row, and then
- add the two charts into that column

![rows-cols-demo-2](https://user-images.githubusercontent.com/4496521/43104965-0c7a18e2-8e88-11e8-9e04-e86ea7b68d42.gif)

**Comment by SevenDL** [comment]
@mistercrunch   @williaster   Thank you~
