### ISSUE TITLE
Superset Druid Query Error

### ISSUE THREAD

**Issue by ashukhira** [apache/incubator-superset#5440]
Make sure these boxes are checked before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if any
- [Yes] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results
Druid query Should return proper result

### Actual results
HTTP Error 500: Internal Server Error Druid Error: Internal Server Error Query is: { "aggregations": [ { "fieldName": "impressions", "fieldNames": [ "impressions" ], "name": "SUM(impressions)", "type": "doubleSum" } ], "dataSource": "vmaxmediation", "dimensions": [ "adpartner_id", "adspot_format" ], "granularity": "all", "intervals": "2018-07-13T00:00:00+00:00/2018-07-20T14:33:05+00:00", "limitSpec": { "columns": [ { "dimension": { "aggregate": "SUM", "column": { "column_name": "impressions", "description": null, "expression": null, "filterable": false, "groupby": false, "is_dttm": null, "optionName": "_col_impressions", "type": "FLOAT", "verbose_name": null }, "expressionType": "SIMPLE", "fromFormData": false, "hasCustomLabel": false, "label": "SUM(impressions)", "optionName": "metric_6nkhk39wj0j_ym12qdvuhqa", "sqlExpression": null }, "direction": "ascending" } ], "limit": 50000, "type": "default" }, "postAggregations": [], "queryType": "groupBy" }

### Steps to reproduce
Run above query by curl call that connect to druid broker:--
curl -X POST "http://localhost:8082/druid/v2/?pretty" -H 'content-type: pplication/json' -d'{"aggregations": [{"fieldName": "impressions","fieldNames": ["impressions"],"name": "SUM(impressions)","type": "doubleSum"}],"dataSource": "vmaxmediation","dimensions": ["adpartner_id", "adspot_format"],"granularity": "all","intervals": "2018-07-13T00:00:00+00:00/2018-07-20T13:48:22+00:00","limitSpec": {"columns": [{"dimension": {"aggregate": "SUM","column": {"column_name": "impressions","description": null,"expression": null,"filterable": false,"groupby": false,"is_dttm": null,"optionName": "_col_impressions","type": "doubleSum","verbose_name": null},"expressionType": "SIMPLE","fromFormData": false,"hasCustomLabel": false,"label": "SUM(impressions)","optionName": "metric_6nkhk39wj0j_ym12qdvuhqa","sqlExpression": null},"direction": "descending"}],"limit": 10000,"type": "default"},"postAggregations": [],"queryType": "groupBy"}'

{
  "error" : "Unknown exception",
  "errorMessage" : "Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: HttpInputOverHTTP@68716b4c[c=837,q=1,[0]=EOF,s=STREAM]; line: 1, column: 814] (through reference chain: java.util.ArrayList[0])",
  "errorClass" : "com.fasterxml.jackson.databind.JsonMappingException",
  "host" : null
}

**Comment by mistercrunch** [comment]
Is this a PyDruid issue around a special type? Any funky datatype here? What's `com.fasterxml.jackson.databind.JsonMappingException`?

**Comment by ashukhira** [comment]
Hi,

1) - Above issue coming when passing following in limitSpec with Column node . Below funky limitSpec generated by superset 0.25.6 . And druid not getting to understood below funky limitSpec.  If we   remove limitSpec column then it works well. 

So here want to know why superset adding such limitSpec?? Is such limitSpec supported by druid-0.12.
"limitSpec": {"columns": [{"dimension": {"aggregate": "SUM","column": {"column_name": "impressions","description": null,"expression": null,"filterable": false,"groupby": false,"is_dttm": null,"optionName": "_col_impressions","type": "doubleSum","verbose_name": null},"expressionType": "SIMPLE","fromFormData": false,"hasCustomLabel": false,"label": "SUM(impressions)","optionName": "metric_6nkhk39wj0j_ym12qdvuhqa","sqlExpression": null},"direction": "descending"}],"limit": 10000,"type": "default"},

2)- com.fasterxml.jackson.databind.JsonMappingException :-- exception error throwing by druid.
coming when limitSpec JSON specifies an array while you're trying to deserialize into an object.

com.fasterxml.jackson.databind :-- is library , that support  General data-binding functionality for Jackson: works on core streaming API .  https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

**Comment by mistercrunch** [comment]
`0.25.6` is pretty old, can you reproduce in latest version or master?

**Comment by maver1ck** [comment]
I tried and everything is working fine. So we can close this probably.
