### ISSUE TITLE
SqlLab cannot run EXPLAIN statements without allowing DML 

### ISSUE THREAD

**Issue by asavov-quora** [apache/incubator-superset#5446]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest master branch

### Expected results
EXPLAIN results

### Actual results
Only `SELECT` statements are allowed against this database

### Steps to reproduce
Run `EXPLAIN SELECT 1`

See line https://github.com/apache/incubator-superset/blob/master/superset/sql_lab.py#L133.  Basically this does not allow EXPLAIN statements without DML access.

**Comment by mistercrunch** [comment]
I agree that we should allow EXPLAIN

**Comment by asavov-quora** [comment]
I can do the change, if you like @mistercrunch.

**Comment by mistercrunch** [comment]
Go for it!

**Comment by asavov-quora** [comment]
Requires `sqlparse` [0.3.0](https://github.com/andialbrecht/sqlparse/milestone/21) which includes a fix for [421](https://github.com/andialbrecht/sqlparse/issues/421) and which will allow me (or someone else) to fix this.
