### ISSUE TITLE
Gunicorn workers running blocking calls

### ISSUE THREAD

**Issue by abrenaut** [apache/incubator-superset#5447]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5 running on docker
gunicorn 19.9.0
Tested with eventlet or gevent workers.

### Expected results
SQL queries ran by gunicorn workers should not be blocking calls. The worker should still be able to process incoming requests.

### Actual results
If all the workers are busy running a sql query, they are not processing any incoming request.

### Steps to reproduce
I have 6 gunicorn workers.
I have a dashboard with 6 charts. Each chart runs a SQL query that takes ~30 seconds.
While the chart are loading, the workers are not processing any other incoming request (i.e trying to load the dashboard list page hangs until at least one of the chart is loaded)

**Comment by mistercrunch** [comment]
From my understanding this wasn't an issue when running Gunicorn in async mode.

**Comment by abrenaut** [comment]
I reproduced locally on the master branch running superset with the following command

```gunicorn -w 1 -k gevent --timeout 120 -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app```

If I load a chart based on a query that takes a long time to run, all the request I try to make while the chart is loading are hanging.

I managed to work around that by configuring the pg driver to run in a non-blocking style in superset_config.py (see http://initd.org/psycopg/docs/advanced.html#support-for-coroutine-libraries).

```import psycopg2
from psycopg2 import extensions

from gevent.socket import wait_read, wait_write

def make_psycopg_green():
    """Configure Psycopg to be used with gevent in non-blocking way."""
    if not hasattr(extensions, 'set_wait_callback'):
        raise ImportError(
            "support for coroutines not available in this Psycopg version (%s)"
            % psycopg2.__version__)

    extensions.set_wait_callback(gevent_wait_callback)

def gevent_wait_callback(conn, timeout=None):
    """A wait callback useful to allow gevent to work with Psycopg."""
    while 1:
        state = conn.poll()
        if state == extensions.POLL_OK:
            break
        elif state == extensions.POLL_READ:
            wait_read(conn.fileno(), timeout=timeout)
        elif state == extensions.POLL_WRITE:
            wait_write(conn.fileno(), timeout=timeout)
        else:
            raise psycopg2.OperationalError(
                "Bad result from poll: %r" % state)

make_psycopg_green()```

I still have an issue when loading multiple charts (6+) with long running queries at the same time and I'm not quite sure what's causing the workers to be blocked.

**Comment by abrenaut** [comment]
@mistercrunch you're right, the fact that loading 6 charts block subsequent request is caused by browser's limitation!

It's not a big issue and configuring the pg driver to run in a non-blocking style solves the issue I had in the first place where one worker was blocked by a long running sql query.

Thanks for your help
