### ISSUE TITLE
Add ability to customize (column specific) number formatting in Table view

### ISSUE THREAD

**Issue by mtrbean** [apache/incubator-superset#545]
Right now it defaults to [d3 SI-prefix](https://github.com/airbnb/caravel/blob/master/caravel/assets/visualizations/table.js#L11) but it would be great to have to ability to customize the formatting (https://github.com/d3/d3/wiki/Formatting#d3_format) for a specific column

**Comment by Georgepentaho** [comment]
+1 ,very useful, hope can add in this new version.

**Comment by higaxman** [comment]
About druid i see that a measure can have it's D3Format, is that possible to recover this information and apply the format on the table ? Any technical hint how to do that ?

**Comment by carolynjonesconway** [comment]
+1000 🙌Any update on if or when this will ever be supported?

**Comment by wenchma** [comment]
any update ?

**Comment by klazaj** [comment]
+1

**Comment by Grace-Dmello** [comment]
Any update on this issue?

**Comment by ktmud** [comment]
we are working on it
