### ISSUE TITLE
Way too many bundles!

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5450]
@williaster  looks like way too many bundles get loaded when loading the explore view

Here's the subset I could capture on a screenshot:
<img width="1678" alt="screen shot 2018-07-20 at 4 18 53 pm" src="https://user-images.githubusercontent.com/487433/43029098-a598d772-8c38-11e8-83c8-bde59d95d48e.png">

**Comment by williaster** [comment]
I think this is actually expected. Do you have evidence that it is slower
to load? # requests shouldn't matter if overall load time is faster.
-- 
Chris

Data Visualization
San Francisco

**Comment by mistercrunch** [comment]
I'm just confused as to what things like `.*addSlice.*` are doing in explore. All the `vendors.*` stuff seems like it shouldn't be required.
