### ISSUE TITLE
D3 format

### ISSUE THREAD

**Issue by wangshihan513** [apache/incubator-superset#5466]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
0.21

### Actual results
211m

### Steps to reproduce
I've changed D3 format in 'List Metric' form as shown in the figure. However, it does not show correctly in exploration. Is this a bug or I made mistakes. 
![issue1](https://user-images.githubusercontent.com/40997574/43075217-61c9d574-8e80-11e8-90c8-f7380780b42b.PNG)
![issue2](https://user-images.githubusercontent.com/40997574/43075224-676d607c-8e80-11e8-8f5a-9cd7c9d4d5d5.PNG)

**Comment by wangshihan513** [comment]
Any ideas how to fix it?

**Comment by wenchma** [comment]
version 0.28 also has this problem for pie chart

**Comment by hamidmahmoodnbs** [comment]
I can't see d3 format option in superset, how to expose this functionality?
