### ISSUE TITLE
[dashboard v2] cannot add chart to existing section in a dashboard

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#5475]
Even though dashboard shows blank space in an existing section that should fit this chart, cannot add and get the following error.
Also tried adding to all the charts below and moving. Doesn't work either.
<img width="600" alt="screen shot 2018-07-24 at 1 03 52 pm" src="https://user-images.githubusercontent.com/33429480/43163388-d3a8739a-8f42-11e8-8c01-9a85c256a741.png">
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by SevenDL** [comment]
@vylc  Maybe you can refer to this 
https://github.com/apache/incubator-superset/issues/5429
