### ISSUE TITLE
Can't remove time filters when exploring datasource

### ISSUE THREAD

**Issue by gbates101** [apache/incubator-superset#5476]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
6b15592d (building from source)

### Expected results
Have the ability to remove the time range when exploring a datasource.

### Actual results
Can't remove a time filter when exploring datasource. Not sure if I'm missing something, but my only option is to set a time filter that will include all of my rows. Even after unchecking "Is temporal" on all columns for my datasource, the query is choosing and applying the `TIME_STAMP` column in the explorer:

![image](https://user-images.githubusercontent.com/24995887/43163800-4367f880-8f5d-11e8-9280-6c17907c493b.png)

### Steps to reproduce

1. Add any datasource with a temporal column.
2. Explore the datasource, and note the time range is automatically applied as "Last week"
3. Edit datasource and uncheck all "Is temporal" columns.
4. Explore datasource again. Note the time range is still there, and displaying the query shows this.

**Comment by gbates101** [comment]
Apparently I'm blind, because I am now seeing a "No filter" option in the Time range dialog. I think the steps to reproduce are still valid, though I can work around the issue now.

**Comment by rvazquezglez** [comment]
The way I've found to work around this is to create a data set where the first column is not a date time.

**Comment by moming3805** [comment]
I encountered a similar issue with my version 3.0.1. When there is a time column in the dataset you selected, one of the columns that are not the desired time column will automatically be set as a filter parameter. This can affect applying Jinja time parameters to the intended time column.

Now, i used another bug solve this bug.
step 1: in database, i add anther time column, and  add this column to filter.
step 2: then back to database, and delete this time column.
step 3:   update chart and save, though the time column still show in filter, but it not work in future.
![filter](https://github.com/apache/superset/assets/34561538/56023e0c-cb8c-401d-aa09-aa075e06c80b)
