### ISSUE TITLE
calendar heatmap tips location error

### ISSUE THREAD

**Issue by fangqi179** [apache/incubator-superset#5480]
### Superset version
"version": "0.26.3"
### Expected results
put mouse cursor hover on calendar heatmap, the date tips should show around the calendar box.
### Actual results
put mouse cursor hover on calendar heatmap, the date tips is fixed on the top left conner. When I scroll the page, the tips on calendar heatmap cannot been found.
### Steps to reproduce
Add calendar heatmap chart, move mouse cursor hover on it.
![image](https://user-images.githubusercontent.com/13131131/43173427-6a1dbb7e-8fe7-11e8-9c27-59dd69cab8da.png)

**Comment by graceguo-supercat** [comment]
confirmed. i can reproduce this issue in latest build.

**Comment by Narcissus7** [comment]
you can see https://github.com/Caged/d3-tip/issues/231

**Comment by MarcusSorealheis** [comment]
Is there a reason this wasn't merged?
