### ISSUE TITLE
Need to give just dashboard view access to users in Supreset

### ISSUE THREAD

**Issue by awsiotdemo** [apache/incubator-superset#5483]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
Need to give just dashboard vieweing rights and dashboard download rights to users

### Actual results
After giving Gamma role access to users, users are not able to see any dashboard

**Comment by sebastianwindeck** [comment]
Gamma rights do NOT include access rights to datasources and tables. 

If you want a certain user group add a Role i.e. "VIEWER" with the access rights of the datasources you want them to access (in the dashboard).
Secondly, add the role "VIEWER" to the regarding users.

**Comment by awsiotdemo** [comment]
Thanks Sebastian. by adding "datasource access on all_datasource_access". Gamma users can view dashboard but my problem statement is that I have users to whom I have to give only dashboard viewing and download rights. I tried to look for the solution in previous threads, but couldn't find the right solution. Need to know what all permissions are required to achieve this functionality

**Comment by sabinegthomsen** [comment]
Any updates on this? I am in a similar position, as I want to create a role with (only) viewing permission to a single dashboard. Which permissions need to be added to this "VIEWER" role in order for them to see the specific dashboard? 

The permission "all datasource access on all_datasource_access" is not enough.

**Comment by D-Mahajan** [comment]
+1. Similar situation.

**Comment by srggrs** [comment]
@awsiotdemo you must give them permission on the table to show data and therefore download them, but you can create a role that can list and view dash board so the user will see only the dashboard of the table he can access to

**Comment by mistercrunch** [comment]
Currently you can only give access per database, schema or table. There's an open PR out there attempting to add this feature.

**Comment by orangle** [comment]
+1. Similar situation.

**Comment by agabardo** [comment]
+1. Similar situation.

**Comment by dominijk** [comment]
Same need, use case is that on dataset with 10's to hundreds of users new to dashboards there will soon be clutter it would be nice to explicitly share a dashboard to a role without assigning them as an editor. Ie. Big dashboard from which user forks Their Big dashboard version but the other users don't see that unless they are added in as editor

**Comment by GuillermoCastano** [comment]
I have the same need.

**Comment by zheya08** [comment]
Same need +1.

**Comment by ibotheperfect** [comment]
We have same need too.

**Comment by keeyong** [comment]
+1

**Comment by tommy-couzens** [comment]
+2

**Comment by essiTo** [comment]
+1 same need here !! 
actually and clearly.. I don't want to give access of all Charts based on a same DataSource, to different users who should not see all table-fileds (like price, or starting-date columns). Other than giving access of datasource, what are my options? 
let's say.. I have a major and important table in DB (datasource) which 4-5 different Charts are made on its data.. but I want to give access to only 2 charts of all, in shape of a general Dashboard to low-level users.. and other 2 more private Charts to the manager.. 
How can I restrict access to Charts and Dashboards ??  not on Datasource only.

**Comment by Ashwini7** [comment]
+1 same challenge.
Could you pls also suggest how to extend the role and permission in superset programmatically?

**Comment by amitNielsen** [comment]
@Ashwini7 @essiTo 
We are working on a final proposal after a few discussions on SIP-51
After sip is approved we can move quickly in the implementation step

**Comment by Ashwini7** [comment]
Nice! Thanks for the heads up. Looking forward to SIP-51. it looks exciting.

For now, I was able to configure the initial access as @sebastianwindeck mentioned.

**Comment by aleksarias** [comment]
Here's a reference link to SIP-51 #10408

**Comment by jinyuanlu** [comment]
+1. Looking forward to it.

**Comment by Agnoos** [comment]
+1. Looking forward to it.

**Comment by MK0820** [comment]
+1.Same need.

**Comment by jefo2k** [comment]
+1 with the same need

**Comment by zhouhanc** [comment]
+1 same here. Is there a solution now

**Comment by churchill1973** [comment]
+1 has it been solved? Thanks in advance.

**Comment by AOphagen** [comment]
+1 , need to prepare read-only dashboards for users
