### ISSUE TITLE
Feature request : Support for Druid histograms

### ISSUE THREAD

**Issue by mmcgowan** [apache/incubator-superset#55]
I'd like to see support for Druid histograms. I'm specifically interested in charts of a given percentile.

See: http://druid.io/docs/latest/development/approximate-histograms.html

Thanks for considering!

**Comment by yinzhiqiang** [comment]
@xrmx any update for this feature? the approximate histogram feature is very important for us.

**Comment by xrmx** [comment]
@yinzhiqiang If it's important for you feel free to work on this. As a general rule don't expect someone else is doing the work for you for free.

**Comment by ghulands** [comment]
@mmcgowan can you provide more info of what you are after?

At time of ingestion you create an approxHistogramFold, you can then create metrics based on that histogram in superset.

in ingestion schema:
            { "type" : "approxHistogramFold", "name" : "hist_response_time", "fieldName" : "response_time", "resolution" : 50},

metric json spec:
{ "type" : "quantile", "name" : "hist_response_time", "fieldName" : "hist_response_time",
  "probability" : 0.95 }
