### ISSUE TITLE
Unpredictable behaviour resizing and moving slices

### ISSUE THREAD

**Issue by octaviancorlade** [apache/incubator-superset#5507]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
Resizing a slice doesn't move other slices all over a dashboard.
Saving a dashboard saves the current positions.

### Actual results
Resizing or moving one slice makes other slices move unpredictably. 
Even after manually restoring the position, they won't be stored when saving the dashboard.

### Steps to reproduce
- Install superset 0.26.3 from pip or git clone following the documentation, including the sample dashboards. Open the "World's Bank data" dashboard.

- Reduce the top left "region filter" size a little. As a result, the bottom right "box plot" slice is moved.
- Move the "box plot" back to its original position at the bottom right of the dashboard.
- Restore the top left "region filter" size. The box plot is moved again, move it back one more time.
- Save the dashboard (it now looks like the original example dashboard).
- Reload the page: the box plot is again in the wrong position and there is no way to put save it in the original bottom right position.

![gridbug](https://user-images.githubusercontent.com/15089539/43309674-c06a4746-9185-11e8-8061-b41caf04b44c.gif)

It looks like this was introduced by #5122 using react-grid-layout 0.16.6.
Dashboards v2 don't rely on react-grid-layout so I'm not sure if this needs to be fixed for v1 or we just wait for v2 in superset 0.27.

**Comment by yamyamyuo** [comment]
@octaviancorlade Same problems here. BTW, what is Dashboards V2? Under what circumstances will the dashboards use v2?

**Comment by mistercrunch** [comment]
Dashboard v2 addresses all of this. The transition requires a bit of work. We need to release `0.27.0`, which offers users a flow to convert their dashboards, followed by `0.28.x` (where `master` is at now), which fully deprecates dashboard v1.

**Comment by yamyamyuo** [comment]
#4596 this is part of the solution
