### ISSUE TITLE
Update logs in superset metadata db

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#5509]
I see that we have a table called logs in superset metadata db which has interesting usage metrics by userId and dashboard. However for some reason, its not updated since last 2 weeks. Is there a sync job that runs at some 2 week intervals to update it? Anyway I can force sync to update it?

**Comment by mistercrunch** [comment]
The logs should be updated live. There must some other issue in your environment, maybe you're missing a db migration?
