### ISSUE TITLE
Sunburst and Scatter Plot issues.

### ISSUE THREAD

**Issue by zhangchenb** [apache/incubator-superset#5519]
I have 2 issues when I do visualization.
1. Sunburst can't precisely show the percentage of each part. Also, the total of each part is only 90%.
![image](https://user-images.githubusercontent.com/41887046/43381461-51bb20e8-9407-11e8-8cab-170bcb2ed758.png)
2. When I try to visualize with Scatter Plot, I want to define point size with metric. But when I click the metric button, there is nothing even though it shows 23 metrics options.
![image](https://user-images.githubusercontent.com/41887046/43381700-0f302632-9408-11e8-850a-e26773c5c026.png)

**Comment by vrenvren** [comment]
Sunburst rounds the percentages and values up to 1 significant figure (.1s), which is a rare wish for such a figure. Output formatting would be nice to have on the style tab, but reasonable defaults shouldn't hurt either. Please revert to something more useful, such as .3s .
