### ISSUE TITLE
Time shift allows freeform but only shows options

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#5520]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
Time shift accepts freeform entries but when you reload slice after freeform entry, nothing shows up (although the time_shift remains in the form_data). We should either allow freeform and make sure those entries are added to options or not allow freeform when given specific choices.

### Steps to reproduce
In advanced analytics -> Time Shift enter '364 days'
Run query
Reload the page - data stays the same but '364 days' no longer shows in time shift box

**Comment by mistercrunch** [comment]
@betodealmeida haven't looked at the code but I remember that SelectControl has extra logic to add value as an option if it happens to be missing at mount time.
