### ISSUE TITLE
[SIP-1] Split the Table visualization into two visualizations

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5528]
# SIP-1 Split the Table visualization into two visualizations

## Motivation
The current `Table` visualization is confusing as it shows 2 control sections, `GROUP BY` and `NOT GROUPED BY` that are mutually exclusive. It's not clear that they are, and if both sections are used Superset will raise and error suggesting to clear some of the controls

## Proposed Change
Split the current `table` visualization into 2 entry points: `Table - Samples` and `Table - Aggregated`. The `GROUP BY` and `NOT GROUPED BY` control sections will become a `Query` section in respective visualizations.

## New or Changed Public Interfaces
The main change to users is the 2 entries points, essentially a new visualization in the visualizations menu.

## Migration Plan and Compatibility
* a database migration re-assigning `NOT GROUPED BY` visualizations to the new type
* minor code changes introducing the new visualization

## Rejected Alternatives
N/A

@betodealmeida what do you think of this template for SIPs? Took it from here: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals

test edit

**Comment by mistercrunch** [comment]
@vylc what do you think of the template? Also what do you think about the labels: `Table - Samples` and `Table - Aggregated`?

**Comment by vylc** [comment]
lets try out the template.
With re: to naming:
Table - Samples --> Table - Data Preview, Table - Preview, Table Data
Table - Aggregated --> Table - Data Summary, Table - Summary

**Comment by mistercrunch** [comment]
@williaster @john-bodley @graceguo-supercat thoughts on this one? I'd like to start a PR doing this soon if people think it's the right approach.

**Comment by john-bodley** [comment]
@mistercrunch we agree that the current table UX is confusing, however we aren’t sure if this is really the long-term solution. The atomic vs. non-atomic issue is systemic to all visualization types, not just to the table. i.e., if you extrapolate this logic, we would have to have two time series charts, two bar charts, etc., to support both atomic tables and aggregated data sources. 

It seems like a better solution would be to extend ad-hoc metrics to understand the difference between atomic vs non-atomic, i.e., a metric could be an aggregation on a non-atomic column or merely the value of an atomic column.

**Comment by vylc** [comment]
@john-bodley do you guys have stats atomic level usage (vs agg) and on what viz types are most often used in the non-group by case?

**Comment by williaster** [comment]
@vylc no because the only way to do a non-group by on other vis's at the moment is to do a hacky group by on something like ds to force it to be an atomic level aggregation.

**Comment by mistercrunch** [comment]
This got tackled!
<img width="594" alt="Screen Shot 2020-07-30 at 5 32 09 PM" src="https://user-images.githubusercontent.com/487433/88987474-db9c6100-d28a-11ea-8e68-c4bcbd4e0322.png">

**Comment by ktmud** [comment]
Didn't know I accidentally fixed SIP No. 1!
