### ISSUE TITLE
Feature Request: Combine two or more charts

### ISSUE THREAD

**Issue by BLiu1** [apache/incubator-superset#5530]
As my team transitions from Excel to Superset, we miss the capability to represent series as different types of charts. For example, we would often combine a bar chart and a line chart.

![combined bar and line chart](https://www.microsoft.com/en-us/microsoft-365/blog/wp-content/uploads/sites/2/migrated-images/44/6545.01%20Combo%20Chart%20-%20Units%20Sold%20and%20Total%20Transactions.png)

Using simple time-series line charts and separate charts has been our workaround for the moment.

**Comment by SGSunil** [comment]
@mistercrunch  any plan to add this functionality.

**Comment by daniel10012** [comment]
@junlincc @eugeniamz this was asked for 2 times this week

**Comment by junlincc** [comment]
@daniel10012 I know Daniel😭 I really wanna have this in our gallery too!!

**Comment by HipsterZipster** [comment]
Is it possible to do something like this with an area chart and a line chart overlay?

**Comment by andrewscarani** [comment]
+1

**Comment by rsilveira7** [comment]
+1

**Comment by felipefiorini** [comment]
+1

**Comment by BLiu1** [comment]
Since there's obviously interest, I'll file an identical ticket if this isn't reopened.

**Comment by ktmud** [comment]
The amazing @villebro has added a Mixed Timeseries chart: https://github.com/apache-superset/superset-ui/pull/1027 , which should be available in `master` already.

**Comment by BLiu1** [comment]
Thanks for the update. I'm no longer with the team using Superset (the one in 2018) and I keep getting pinged, so I assumed there was nothing like this. Glad there's a solution now.

**Comment by iosivp** [comment]
Hello colleagues,
Can you please advise how can I get this feature?
I have upgraded Superset this morning. The version is 1.1.0.
I use Superset with gunicorn in venv.

Thank you very much,
Iosiv

**Comment by villebro** [comment]
@iosivp @BLiu1 this chart is introduced in the forthcoming 1.2.0 release, which I believe is going up for vote this week.

**Comment by abimael-dominguez** [comment]
I also wanted to find a combo chart. I used the "dual line chart" instead, it is not the same, but I will use it meanwhile someday someone would add this feature.

**Comment by LeoDiep** [comment]
can we have a mix but not time-serie between bar chart and line chart?
