### ISSUE TITLE
Filtered / Tiered Filters

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#5534]
It would be nice if the values that appear in a lower-level filter were filtered based upon a value entered in a higher-level filter (within the same filter box slice).

E.g.: I have a filter for "state" and a filter for "city" -- if I select "Georgia" I only see cities in Georgia, and would not see Los Angeles, New York, Chicago, appear as options

**Comment by mistercrunch** [comment]
This would require to superset to know about the one-to-many relationships across columns. It's common for BI tools to know about those hierarchies. Could be integrated to the table editor (going through review) and/or the upcoming native dashboard filters.
