### ISSUE TITLE
The annotation layer is unavailable <master>

### ISSUE THREAD

**Issue by SevenDL** [apache/incubator-superset#5535]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master
### Expected results
the annotation layer is rendered as a range successfully
### Actual results
there's some bug so the layer cann't be fetched.

### Steps to reproduce
1.Add an annotations layer named"testlayer";
2.Add an annotation,Start Dttm  1970-01-01 16:27:11,End Dttm 1975-01-01 16:27:11,select "testlayer" as the annotations layer;
![image](https://user-images.githubusercontent.com/33197465/43514945-e87d5192-95b3-11e8-9107-ad485189b6bd.png)

3.Add the annotation layer in a time_line graph, but it has some bug.
![image](https://user-images.githubusercontent.com/33197465/43516352-f01a3506-95b7-11e8-9729-8363854bf53c.png)

error1: There is an alert that
"ERROR: Only '=', '!=', 'is_()', 'isnot()', 'is_distinct_from()', 'isnot_distinct_from()' operators can be used with None/True/False"
error2： Table view as an Event or Interval annotation type can not be select.

**Comment by SevenDL** [comment]
![ezgif-2-29df60b131](https://user-images.githubusercontent.com/33197465/43529590-38ecb26a-95de-11e8-9b45-65c7f5014911.gif)

**Comment by SevenDL** [comment]
@mistercrunch

**Comment by yuguang** [comment]
Pull request for fix: https://github.com/apache/incubator-superset/pull/6047
