### ISSUE TITLE
Radar Chart and Gauge Chart visualizations request

### ISSUE THREAD

**Issue by sashank** [apache/incubator-superset#5537]
Hi there , its not really a bug rather its an enhancement request. 

Is there any plan to support radar charts and gauge charts in superset ? 
I have checked other issues and help document on adding custom visualizations but unfortunately i don't have the necessary coding skills to add them .

**Comment by CoryChaplin** [comment]
Would be awesome to integrate http://bl.ocks.org/nbremer/6506614

**Comment by mistercrunch** [comment]
@CoryChaplin I agree that spider graphs would be nice. In the meantime, "Parallel coordinates" can achieve similar things as they kind of are a flat version of the spider chart.
