### ISSUE TITLE
Creating an Omnibar

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#5551]
From any where in the app, I want to be able to hit Cmd + K and jump to another chart or dashboard based upon the name. We don't have to use blueprint, open to other libraries. Mainly want to shorthand on moving around the app.

Example:
![omnibar](https://user-images.githubusercontent.com/27827808/43614633-0d04ea06-9669-11e8-9cb2-44464b30f6f3.gif)

**Comment by mistercrunch** [comment]
Oh that'd be SWEET. 🔥 ⚡️ , I always use this on Slack.

**Comment by hughhhh** [comment]
https://github.com/vutran/omnibar
