### ISSUE TITLE
Make aggregation not mandatory

### ISSUE THREAD

**Issue by thangbn** [apache/incubator-superset#5570]
I would like to visual only the raw data WITHOUT the need of apply any kind of aggreation, as the data from the table is already pre-computed aggreated metric values.

### Superset version
0.26.3

### Expected results
There shouldn't be aggregation enforced for a metric.  There should be an option to display the raw metric WITHOUT any aggreation function

### Actual results
User must select one of six aggreation available in order to visualize data.
![image](https://user-images.githubusercontent.com/5661982/43691150-763aeea2-98cc-11e8-9efe-a27fc64bc2bd.png)

### Steps to reproduce
 - Go to **Charts**
- Create a new Timeseries Line Chart
- Under Query section
- Configure metric

**Comment by davidhassan** [comment]
I too would like this change. It would also be nice to change the legend for your metric under "Custom SQL" to rename it. Instead of AVG(metric) you could do AVG(metric) AS [my_legend_name]

**Comment by mistercrunch** [comment]
This is more complex than it may seem. The assumption that a metric is an aggregate function runs deep in Superset. The clear and easy workaround is to use a dummy aggregation function. min, max, sum should all provide the same answer in cases where dimension combinations are unique in the source data. The downside is a bit more work on the database side. Note that in some cases that can hurt quite a bit. For example for geospatial data visualizations where hundreds of thousands of data points can be surfaced, grouping by lat&long is expensive and often unnecessary.

The committers have had lengthy conversations about this, and the key may be something around the `MetricsControl` allowing users to specify not to aggregate. It may have to be coupled with validation/assertions on resulting dataframes making sure that dimension combinations are not duplicated in some cases, as that may cause problems with some of the visualizations.

I don't see this work getting prioritized anytime soon though as the work would be complex and there are clear easy workarounds.

**Comment by davidhassan** [comment]
@mistercrunch I have been using AVG or SUM as my dummy aggregations. However now in the legend it shows something like AVG(metric) as my metric name. Which is a little misleading.

Any chance to to change this in the "Custom SQL" section or elsewhere. 

Something like AVG(metric) AS [my_legend_name]

Ex: AVG(price) AS [Price (CAD$)]. Legend will now show "Price CAD$" instead of AVG(price).

**Comment by thangbn** [comment]
@mistercrunch thank you for your information, I also believe that should be discussed already but couldn't find the issue on GitHub. 
Let's consider this a place to discuss and gather people' thoughts.

**Comment by mistercrunch** [comment]
You should be able to click and edit the label of the metric, and that should show up in the legend.
<img width="297" alt="screen shot 2018-08-06 at 2 30 37 pm" src="https://user-images.githubusercontent.com/487433/43742050-54c28546-9985-11e8-8db3-78298c3e8ff1.png">

**Comment by davidhassan** [comment]
@mistercrunch greatest feature ever! Thank you for pointing this out.

**Comment by QCaudron** [comment]
I'd like to voice my support in having aggregations be optional. Like @thangbn, I have a lot of data that's already processed and aggregated, and would love to just be able to plot that.

Dummy aggregations are mostly fine but sometimes difficult. I understand that this might be difficult to disentangle from the assumptions made in the Superset backend, but I thought I'd contribute this show of support anyway. Thanks !

**Comment by WizardOfArc** [comment]
The work-around doesn't work for pre-calculated percentages.  In the pivot table does some kind of operation on them instead of just displaying the data that was pre-calculated - resulting in values like `770m` for a percent . 😱

**Comment by jkryanchou** [comment]
It should provide Custom SQL Option would convenient for us to draw the chart like Metabase. 
The options always drive us so confusion.

**Comment by sfirke** [comment]
There's more discussion in #19182.  See in particular the currently-final comment https://github.com/apache/superset/discussions/19182#discussioncomment-9215005 from a core Superset contributor.  This would be a great feature -- it's one I could really use myself -- but it would be a huge lift given how Superset currently operates and would require substantial conversation and effort to go forward.

**Comment by mistercrunch** [comment]
Personally I think what I wrote back in 2018 https://github.com/apache/superset/issues/5570#issuecomment-410773587 above still stands. 

Conceptually, in Superset as in many other BI tools, semantically and conceptually, a "Metric" IS an **aggregate expression**. The very concept of dimensions everything that relates to "dimensionality", like allowing for pivoting dimensions, applying filters and "slice and dicing" depends on this simple assumption. 

In cases where your table or view somehow happens to be at the exact grain needed for visualization, then superfluous/unecessary aggregation isn't really an issue. This conceptual model being more flexible and evolutive, it would allow you to bring new dimensions to this dataset and unlock more of that slicing/dicing .

**Comment by ggojedap** [comment]
With some basic charts, a dummy aggregation is a good work-around, but in some cases It is necessary to show a chart using the values directly from the results given by a custom Query from SQL Lab, as raw records like available for tables. I am currently working with a survey dataset and need a Box Chart (median, q1, q3, max, min, etc.) from a weighted calculation, but the available chart is configured to make its own calculations.

It will be great if more chart types could offer the raw records as an option, without aggregation.

**Comment by mistercrunch** [comment]
For this case, the Table visualization has a feature around `RAW RECORDS` that doesn't aggregate. I think the "CREATE CHART" flow from SQL Lab lands you to the table visualization in that mode.

<img width="381" alt="Screenshot 2024-07-22 at 10 17 35 AM" src="https://github.com/user-attachments/assets/bf7dc001-c206-4fe1-bcbd-14ce4fa39da2">

In theory, other visualizations could expose a similar "mode", but clearly the UX around this is confusing outside of the table use case.

**Comment by jacobhurst** [comment]
Thanks for the work round, plotting scatter plots it seems so intuitive to just have an x and y! Actually wondering about a different solution which is a shame..

**Comment by nalcabio-tom** [comment]
Bummer
