### ISSUE TITLE
The top menus with drop down are unavailable<master>

### ISSUE THREAD

**Issue by SevenDL** [apache/incubator-superset#5576]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Actual results

The top menus with drop down(security\Manege\Sources\SQL lab) are unavailable in  import_dashboards page.

### Steps to reproduce
1.Click 'manage', spread out the drop down box;
2.Click ‘Import Dashboards’，open the import page;
3.Click on the 'security'\'manage'\'sources' or 'SQL lab', there's no reaction.

![image](https://user-images.githubusercontent.com/33197465/43749483-dff5ac00-9a26-11e8-8a2a-336e80c58813.png)

**Comment by Narcissus7** [comment]
I have the same issue.
