### ISSUE TITLE
Can Superset connect with Apache Ignite ?

### ISSUE THREAD

**Issue by AnupKumarSaha** [apache/incubator-superset#5577]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
If it has decent support for SQL, all it needs on top of it is a DBAPI driver and a SQLAlchemy dialect.

**Comment by chirdeeptomar** [comment]
Superset uses SqlAlchemy supporting the JDBC driver, so technically it should be possible to connect to Ignite. Install the Oracle driver https://superset.incubator.apache.org/installation.html#database-dependencies and follow the documentation here https://apacheignite-sql.readme.io/docs/sql-tooling

**Comment by rangerzhou** [comment]
Hi everyone,
Is there SQLAlchemy dialect support JDBC? I want to connect Apache Ignite database in superset, but I do not known how to type 'SQLAlchemy URI'.
