### ISSUE TITLE
Hope superset add Data mining and  Machine learning！Thks！

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#5585]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.999.0DEV

**Comment by kalimuthu123** [comment]
i am having the idea of data mining and machine learning applications
