### ISSUE TITLE
"react-bootstrap-datetimepicker"  此插件不支持 i18n, 能否换掉

### ISSUE THREAD

**Issue by byc233518** [apache/incubator-superset#5586]
此插件github 上最新版本是0.0.22, 
![image](https://user-images.githubusercontent.com/13425815/43823493-c22640a8-9b21-11e8-9f3c-11475dbea330.png)
并且也早已宣布不再维护;
查看其提交记录及 issues , 是有关于增加 locale 支持的, 但是其没有将最新代码合并发布出来;
![image](https://user-images.githubusercontent.com/13425815/43823636-4d26056c-9b22-11e8-805f-7792a7d926be.png)
https://github.com/quri/react-bootstrap-datetimepicker/pull/184

**Comment by cupen** [comment]
Just a translation for  this issue:
- - -
About the `react-bootstrap-datetimepicker`:
  * Its latest version is  `0.0.22`.
  * It doesn't support i18n., and doesn't merge a i18n PR.
  * It was DEPRECATED.

So, could you please switch to a better replacement?

**Comment by mistercrunch** [comment]
Please keep this repo in english.
