### ISSUE TITLE
Feature Request: Influxdb support

### ISSUE THREAD

**Issue by tanner-bruce** [apache/incubator-superset#5588]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Is it possible to support influxdb with Superset? I found https://github.com/amancevice/influxalchemy but am not sure where to go from there.

**Comment by villebro** [comment]
@tanner-bruce You can start out by installing the influxalchemy package in your environment and creating a connection to your database in Superset via `Sources` - `Databases` - `Add`. I'm guesing the connection string should be something along the lines of `influxdb://user:password@hostname`. After that go to SQL Lab and try to fire a `select * from table` to see if you can get some data. If all is well you can proceed by implementing a dedicated InfluxDB specific engine specification under `superset/db_engine_spec.py`, where you can mostly copy logic from other engine implementations. Start out by implementing some time grains, and if there are any other quirks, those should be straight forward to add later, e.g. schema settings.

**Comment by tanner-bruce** [comment]
Thanks @villebro , I'll try that out!

**Comment by Rhysoshea** [comment]
hi @tanner-bruce did you try @villebro 's solution? Did this work for you? I'm having trouble connecting to the database through Superset, I was wondering if the connection string was as suggested?

**Comment by duffar12** [comment]
@tanner-bruce @Rhysoshea  @villebro  Did any of you get this to work? InfluxAlchemy is just a python package, so I don't really see how it's going to help unless you use it to create an adapter process to communicate between influxdb and superset. Am I wrong?

**Comment by villebro** [comment]
@duffar12 I took a look at influxalchemy, and apparently it's not a real SQLAlchemy connector. So I guess someone needs to implement a native SQLA connector for InfluxDB first.

**Comment by sorinmuchi** [comment]
Any plans for InfluxDB support?

**Comment by villebro** [comment]
As stated earlier, if a proper SqlAlchemy connector is created, InfluxDB support should be simple to add.

**Comment by RAFAEL-PACHECO-OLIVEIRA** [comment]
Se alguém conseguiu, avise por favor!
