### ISSUE TITLE
numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by brylie** [apache/incubator-superset#5594]
### Superset version
0.26.3

### Expected results
Setup process would not produce any warnings.

### Actual results
When creating an admin user with the command `fabmanager create-admin --app superset`, the following warning occurs:

```
.../python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```

### Steps to reproduce
1. set up empty conda environment
2. follow the instructions from [Superset installation and initialization](https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization)

**Comment by mmuru** [comment]
This warning shows up build version and runtime version of numpy differs. You can safely ignore this warning message. 
To get quiet annoying warning, add these 
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")

into your superset_configy.py file.
