### ISSUE TITLE
Bubble Size should not be required for World Map visualization

### ISSUE THREAD

**Issue by emlittleworth** [apache/incubator-superset#5599]
- [√ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ √] I have reproduced the issue with at least the latest released version of superset
- [ √] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
I should be able to use the World Map visualization without expanding the "Bubbles" section and selecting the "Bubble size" dropdown.

### Actual results
It is required even when "Show Bubbles" isn't selected. The newly added validation is useful so people don't run into issues (for example: #5171, #4371, #2361) but it doesn't make sense to enforce this when "Show Bubbles" is unchecked.

![image](https://user-images.githubusercontent.com/4187958/43928028-73119a9e-9bfd-11e8-917f-296e0b7d957f.png)

### Steps to reproduce
Use the World Map visualization.

**Comment by Manikandan25** [comment]
![solve1](https://user-images.githubusercontent.com/29278749/43950536-2c7dd596-9cae-11e8-8648-be772769230a.png)
If you unchecked Show Bubbles, it shouldn't ask for a column to represent bubble size.
If you need the bubbles of same size, you can fill in the custom sql as 1 (or some other numbers). Check the image , I have attached

**Comment by emlittleworth** [comment]
Yeah I understand the workaround but created the issue because I feel the interaction should change. It'd be ideal to not have to fill in "Bubble size" if "Show Bubbles" is unchecked. The validation error in red in the screenshot I added shows that it is being enforced regardless of the state of "Show Bubbles."
