### ISSUE TITLE
How to share chart only? No anything else like edit box on the left 

### ISSUE THREAD

**Issue by gclsoft** [apache/incubator-superset#5609]
![image](https://user-images.githubusercontent.com/1269898/44002806-83f73276-9e7b-11e8-84d3-7ac747901c7d.png)
I only want to share this. I want to display it on the web in the phone. So if the chart is small, it will good to display.
![Uploading image.png…]()

**Comment by mistercrunch** [comment]
You can use the link inside the "embed" popover
<img width="469" alt="screen shot 2018-08-12 at 9 13 05 am" src="https://user-images.githubusercontent.com/487433/44003966-fae87528-9e0f-11e8-870f-d049f200fc01.png">

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/44009636-d4719408-9edf-11e8-9d51-df69c4ef5018.png)
It display ok on PC, but it really display the unused edit boxes on the left.
My url is:
```
'https://bi.uuyimei.com/superset/explore/?form_data=%7B%22datasource%22%3A%222__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A42%2C%22granularity_sqla%22%3A%22year%22%2C%22time_grain_sqla%22%3Anull%2C%22since%22%3A%222014-01-01%22%2C%22until%22%3A%222014-01-02%22%2C%22groupby%22%3A%5B%22country_name%22%5D%2C%22metrics%22%3A%5B%22sum__SP_POP_TOTL%22%5D%2C%22percent_metrics%22%3Anull%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A50000%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3Anull%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%2C%22markup_type%22%3A%22markdown%22%2C%22show_bubbles%22%3Atrue%2C%22filters%22%3A%5B%5D%2C%22entity%22%3A%22country_code%22%2C%22metric%22%3A%22sum__SP_POP_TOTL%22%2C%22compare_lag%22%3A%2210%22%2C%22secondary_metric%22%3A%22sum__SP_POP_TOTL%22%2C%22compare_suffix%22%3A%22o10Y%22%2C%22country_fieldtype%22%3A%22cca3%22%2C%22url_params%22%3A%7B%22standalone%22%3A%22true%22%2C%22height%22%3A%22400%22%7D%2C%22where%22%3A%22%22%2C%22limit%22%3A%2225%22%7D'
```

**Comment by gclsoft** [comment]
It also display the left side on PC now, I don't know why. My setting in the security is `

Public | [all database access on all_database_access, can explore on Superset, can explore json on Superset]`
-- | --
