### ISSUE TITLE
How to make the share url no changing?

### ISSUE THREAD

**Issue by gclsoft** [apache/incubator-superset#5610]
I click the share button, it make a new url like:'http://192.168.236.128:8088/r/14', I click it again, it will be 'http://192.168.236.128:8088/r/15', then 'http://192.168.236.128:8088/r/16'. I want to display the chart on web in the phone, but the urls are changing all the time. How to make it no changing?

**Comment by mistercrunch** [comment]
Seems like in your case `r/14` will redirect to the exact same place as `r/15` will.

**Comment by yamyamyuo** [comment]
This is merely a design of [url shortening](https://en.wikipedia.org/wiki/URL_shortening).
Every time you click the share button, the url id `r/14` is auto imcrement. This design can be 1 to multiple shorten urls. This mappings was stored in superset db table `url`.
