### ISSUE TITLE
when table's explore_json form_data size is big then 1M the browser will crash

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#5615]
raw data size about 3M ,100 colums, the browser spend  2.5G memory

![image](https://user-images.githubusercontent.com/20242930/44092723-eeb89bc0-a003-11e8-8402-a0f275101936.png)
![image](https://user-images.githubusercontent.com/20242930/44092746-03963a3e-a004-11e8-82a6-587a52fe42c5.png)

firefox will spend all my memory 
![image](https://user-images.githubusercontent.com/20242930/44093021-c3360784-a004-11e8-9946-4b9f32fad74d.png)

then the browser will crash

the query look like : 
SELECT seq AS seq,
       sex AS sex,
       ip AS ip,
       age AS age,
       city AS city,
       wx_img AS wx_img,
       email AS email,
       weixin_nickname AS weixin_nickname,
       weixin_sex AS weixin_sex,
       weixin_addr AS weixin_addr,
       start AS start, 
       finish AS finish,
       browser AS browser,
       os AS os,
       status AS status,
       q1 AS q1,
       q2 AS q2,
       q3 AS q3,
       q4 AS q4,
       q5 AS q5,
       q6 AS q6,
       q7 AS q7,
       q8 AS q8,
       q9 AS q9,
       q10 AS q10,
       q12 AS q12,
       q11 AS q11,
       q13 AS q13,
       q13_open AS q13_open,
       q14 AS q14,
       q15 AS q15,
       q16 AS q16,
       q16_open AS q16_open,
       q17 AS q17,
       q18_a1 AS q18_a1,
       q18_a2 AS q18_a2,
       q18_a3 AS q18_a3,
       q18_a4 AS q18_a4,
       q19_a3 AS q19_a3,
       q19_a4 AS q19_a4,
       q19_a5 AS q19_a5,
       q19_a6 AS q19_a6,
       q20 AS q20,
       q21_a1 AS q21_a1,
       q21_a2 AS q21_a2,
       q21_a3 AS q21_a3,
       q21_a4 AS q21_a4,
       q21_a5 AS q21_a5,
       q21_a6 AS q21_a6,
       q22_a1 AS q22_a1,
       q22_a2 AS q22_a2,
       q22_a3 AS q22_a3,
       q22_a4 AS q22_a4,
       q22_a5 AS q22_a5,
       q22_a6 AS q22_a6,
       q22_a7 AS q22_a7,
       q23_a1 AS q23_a1,
       q23_a2 AS q23_a2,
       q23_a3 AS q23_a3,
       q23_a5 AS q23_a5,
       q23_a4 AS q23_a4,
       q24_a1 AS q24_a1,
       q24_a2 AS q24_a2,
       q24_a3 AS q24_a3,
       q24_a4 AS q24_a4,
       q24_a5 AS q24_a5,
       q24_a6 AS q24_a6,
       q24_a7 AS q24_a7,
       q25 AS q25,
       q26 AS q26,
       q27_a3 AS q27_a3,
       q27_a4 AS q27_a4,
       q27_a5 AS q27_a5,
       q27_a6 AS q27_a6,
       q27_a7 AS q27_a7,
       q27_a8 AS q27_a8,
       q27_a9 AS q27_a9,
       q28 AS q28,
       q29_a1 AS q29_a1,
       q29_a2 AS q29_a2,
       q29_a3 AS q29_a3,
       q29_a4 AS q29_a4,
       q29_a5 AS q29_a5,
       q30_a1 AS q30_a1,
       q30_a2 AS q30_a2,
       q30_a3 AS q30_a3,
       q30_a4 AS q30_a4,
       q30_a5 AS q30_a5,
       q31 AS q31,
       q32 AS q32,
       q33_a5 AS q33_a5,
       q33_a6 AS q33_a6,
       q33_a7 AS q33_a7,
       q33_a8 AS q33_a8,
       q34 AS q34,
       q35 AS q35,
       q36 AS q36,
       q37 AS q37,
       q38 AS q38,
       q39 AS q39,
       q40 AS q40,
       q41_a1 AS q41_a1,
       q41_a2 AS q41_a2,
       q41_a3 AS q41_a3,
       q41_a4 AS q41_a4,
       q41_a5 AS q41_a5,
       q41_a6 AS q41_a6,
       q41_a7 AS q41_a7,
       q42 AS q42,
       q43_a2 AS q43_a2,
       q43_a1 AS q43_a1,
       q43_a4 AS q43_a4,
       q43_a3 AS q43_a3,
       q43_a5 AS q43_a5,
       q43_a7 AS q43_a7,
       q43_a6 AS q43_a6,
       q44_a1_open AS q44_a1_open,
       q45_a1_open AS q45_a1_open,
       q45_a2_open AS q45_a2_open,
       q45_a4_open AS q45_a4_open,
       q45_a3_open AS q45_a3_open
FROM yxy_ods.all_data_original
GROUP BY seq,
         sex,
         ip,
         age,
         city,
         wx_img,
         email,
         weixin_nickname,
         weixin_sex,
         weixin_addr, 
         start, finish,
       browser,
       os,
       status,
       q1,
       q2,
       q3,
       q4,
       q5,
       q6,
       q7,
       q8,
       q9,
       q10,
       q12,
       q11,
       q13,
       q13_open,
       q14,
       q15,
       q16,
       q16_open,
       q17,
       q18_a1,
       q18_a2,
       q18_a3,
       q18_a4,
       q19_a3,
       q19_a4,
       q19_a5,
       q19_a6,
       q20,
       q21_a1,
       q21_a2,
       q21_a3,
       q21_a4,
       q21_a5,
       q21_a6,
       q22_a1,
       q22_a2,
       q22_a3,
       q22_a4,
       q22_a5,
       q22_a6,
       q22_a7,
       q23_a1,
       q23_a2,
       q23_a3,
       q23_a5,
       q23_a4,
       q24_a1,
       q24_a2,
       q24_a3,
       q24_a4,
       q24_a5,
       q24_a6,
       q24_a7,
       q25,
       q26,
       q27_a3,
       q27_a4,
       q27_a5,
       q27_a6,
       q27_a7,
       q27_a8,
       q27_a9,
       q28,
       q29_a1,
       q29_a2,
       q29_a3,
       q29_a4,
       q29_a5,
       q30_a1,
       q30_a2,
       q30_a3,
       q30_a4,
       q30_a5,
       q31,
       q32,
       q33_a5,
       q33_a6,
       q33_a7,
       q33_a8,
       q34,
       q35,
       q36,
       q37,
       q38,
       q39,
       q40,
       q41_a1,
       q41_a2,
       q41_a3,
       q41_a4,
       q41_a5,
       q41_a6,
       q41_a7,
       q42,
       q43_a2,
       q43_a1,
       q43_a4,
       q43_a3,
       q43_a5,
       q43_a7,
       q43_a6,
       q44_a1_open,
       q45_a1_open,
       q45_a2_open,
       q45_a4_open,
       q45_a3_open
ORDER BY COUNT(*) DESC
LIMIT 50000

**Comment by yamyamyuo** [comment]
I have also found rendering issues when `form_data` is too big(more than thousands of lines of data).
I feel disappointed about this frontend performance. It seems like the react chart not performs good with large dataset.
