### ISSUE TITLE
Pivot Table Columns Don't Show Reader-Friendly Labels

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#5616]
### Superset version
0.24.0

### Issue
Reader-friendly labels don't appear for dimensions specified as Columns in the Pivot Table:

![image](https://user-images.githubusercontent.com/33062840/44032926-5c04c1ca-9f11-11e8-911b-b1f7e91e6290.png)

**Comment by jcoelho-pt** [comment]
Only the header of the first GroupBy column displays Alias correctly. The remaining Group By column headers display the internal name of the columns (ignoring defined alias).
**Superset Version:** 0.28.1
Same as #7362
