### ISSUE TITLE
Dashboard filters do not persist on page refresh

### ISSUE THREAD

**Issue by Fingerzam** [apache/incubator-superset#5628]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
`0.27.0rc1`

### Expected results
The page reloads with the same values for filters

### Actual results
The filters reset to defaults. They used to persist.

### Steps to reproduce
Go to a dashboard, apply some filters with a filter box, refresh page.

In earlier versions all of the filter values were reflected in the url params, and hence refreshing the page would use the same filters.

**Comment by graceguo-supercat** [comment]
if your dashboard used stateful url (with filter parameters), or dashboard was saved with some default filters, dashboard will remember old settings even after page reload. But if you don't save these filters anywhere, i am not sure dashboard will remember the previous filter state.

**Comment by xqliu** [comment]
We do have a patch which will save filterbox config to dashboard meta data and then prefetch it upon opening of dashboard.

Will submit the merge request some time after next week.
