### ISSUE TITLE
Not showing count distinct, sum, min, max checkboxes in List Column

### ISSUE THREAD

**Issue by code226** [apache/incubator-superset#5639]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
the List columns page should show checkboxes for count distinct, sum, min, max, 

### Actual results
but only shows groupable filterable and temporal checkboxes

### Steps to reproduce
Click on "Tables"
Click "edit" on 1 table
Go to List Columns, the other agg columns are missing

**Comment by yamyamyuo** [comment]
Isn't it in `List Metrics`? 
<img width="485" alt="screen shot 2018-08-16 at 1 45 02 pm" src="https://user-images.githubusercontent.com/8351385/44190725-a8726d00-a15a-11e8-8aa3-b1a9a716f962.png">

**Comment by zhaoyongjie** [comment]
aggregation funciton is in ad-hoc metric selections.

**Comment by code226** [comment]
I'm expecting this, (which i saw in "version": "0.25.5")

![image](https://user-images.githubusercontent.com/7478219/44230874-3fd2c280-a151-11e8-977c-dffb09f3f5f0.png)

but am getting this instead

![image](https://user-images.githubusercontent.com/7478219/44230890-4a8d5780-a151-11e8-85c3-f2c899f4baed.png)

i've boxed up the checkboxes that i'm missing

**Comment by mistercrunch** [comment]
We removed this since now you can create those on the fly with the new `<MetricsControl />`

**Comment by timgalvin** [comment]
The tutorial still shows these columns. On the fly metrics are pretty rad, but feeling crazy for not finding the checkboxes when you've only been a Superset user for 10 minutes is less so.

**Comment by colax94** [comment]
Could we revert that ? That was very useful in order to avoid having to declare all those basic Sum, Min, Max before being able to define a post aggregation

**Comment by colax94** [comment]
Like now, to define a post aggregation sum(a) / (sum(b), we need to create an aggregator for sum(a), an aggregator for sum(b), and then build the post aggregator using `fieldAccess`  on sum_a and sum_b, which is REALLY a lot of clicks
