### ISSUE TITLE
Not able to add a table from external Redshift Spectrum schema

### ISSUE THREAD

**Issue by vldmit** [apache/incubator-superset#5650]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.26.3

### Expected results

I want to add a table from external Redshift Spectrum schema, in order to create charts based on this table. I expect the flow will be the same as with "local" Redshift schemas: 

1) Sources -> Databases -> Add (postgresql)
2) Sources -> Tables -> Add (select redshift DB, put schema name and table name)
3) Observe a table in a table list

### Actual results

Following error is displayed:

> Table [spectrum.assoc] could not be found, please double check your database connection, schema, and table name

where `spectrum` is an external schema name and `assoc` is a table name. 

### Steps to reproduce

Create Redshift cluster; create external spectrum schema; add a table to the metastore

### Notes

- I think this _might_ be a duplicate of https://github.com/apache/incubator-superset/issues/3316
- In `psql` console, you can't get a list of tables in external spectrum schema by using `\dS`, only by querying SVV_EXTERNAL_TABLES system view.
- In Superset's SQL Lab I can query external spectrum tables by using `schema.tablename` naming

**Comment by mistercrunch** [comment]
What does your connection string look like?

**Comment by vldmit** [comment]
SQLAlchemy URI: `redshift+psycopg2://superset:XXXXXXXXXX@qharvest-redshift.XXXXXXXXXXX.us-east-1.redshift.amazonaws.com:5439/ZZZZZZZZZ`; `ZZZZZZZZZ` is our DB name.

Extra parameters:

```json
{
    "metadata_params": {},
    "engine_params": {}
}
```

(I've tried to add "schema": "spectrum" parameter, it didn't help; "spectrum" is the name of external Redshift Spectrum schema in our DB)

In Superset SQL Lab's sidebar I see Redshift DB and all (local and external) schemas in this DB. For local schemas, Superset show a dropdown with the list of tables and views. For external Redshift Spectrum schema, the dropdown list is empty (`Add a table (0)`) is displayed. Typing table name manually works, I'm able to query the data via SQL Lab. But I can't add a table via "Sources -> Tables ->  Add (+)" interface.

**Comment by vldmit** [comment]
It seems the problem is lack of support for external schemas/tables in `sqlalchemy_redshift`: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/122

**Comment by everglory99** [comment]
@vldmit We encountered the same issue when adding table from external Redshift spectrum. Have you found any solution on either superset or `sqlalchemy_redshift` side?

**Comment by vldmit** [comment]
> @vldmit We encountered the same issue when adding table from external Redshift spectrum. Have you found any solution on either superset or `sqlalchemy_redshift` side?

No... You might be able to you AWS Athena instead of Redshift Spectrum as a "workaround", if your queries don't have JOINs between external and local Redshift tables.

**Comment by RodBart** [comment]
another workaround, could be create a table in a local schema whit the same structure as the table in external schema, then import the new table and finaly change the schema in superset for the external schema, 
it worked for me.

**Comment by robert-yiqiao-xin** [comment]
> another workaround, could be create a table in a local schema whit the same structure as the table in external schema, then import the new table and finaly change the schema in superset for the external schema,
> it worked for me.

Can you explain more on how you import the new table and change the schema in superset for the external echema? 
Do you mean by import the table in the local schema into superset. Then edit the dataset and change the schema to the external schema? 
Thanks!

**Comment by RodBart** [comment]
> > another workaround, could be create a table in a local schema whit the same structure as the table in external schema, then import the new table and finaly change the schema in superset for the external schema,
> > it worked for me.
> 
> Can you explain more on how you import the new table and change the schema in superset for the external echema?
> Do you mean by import the table in the local schema into superset. Then edit the dataset and change the schema to the external schema?
> Thanks!

Yes, exactly

**Comment by blackhawk28** [comment]
hi @RodBart  and @robert-yxin05  I need some clarification, where did you create the table in redshift? and in local schema? and then import that table with the local schema in superset then change its schema to external?
