### ISSUE TITLE
Dashboard can not show charts previously saved positions.

### ISSUE THREAD

**Issue by Yuanmu93** [apache/incubator-superset#5653]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
The dashboard load previously saved positions, when i saved dashboard that all the charts can be persist.

### Actual results
When I edit dashboard and saved it, the charts no have show I previously saved positions when I refresh page.

### Steps to reproduce
Create a dashboard and edit it, then, I saved it, but the charts positions has changed when I refresh the page or next time check the dashboards.

**Comment by mistercrunch** [comment]
That's an issue with react-grid-layout, which we're moving away from. It'll be all resolved in 0.28.x
