### ISSUE TITLE
Upgrade from an old version

### ISSUE THREAD

**Issue by PetitLepton** [apache/incubator-superset#5654]
Hi,
my apologies if the Issues is not the right place for this problem. I have been running Superset for a long time and - shame on me - did not update the packages. On one of my server, I am using Superset v. 0.20.4.

I installed the latest version and tried to use the existing superset.db. It seems that there has been changes in the tables schema, for example `dbs` and `tables`.

Is there a way to update the exisiting superset.db from 0.20.4 to be compatible with the new version? Or, at least, export the slices and dashboards to be imported in the new version?

Here is an example of stacktrace
```
Traceback (most recent call last):
  File "/Users/PetitLepton/miniconda3/envs/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/PetitLepton/miniconda3/envs/superset/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: tables.is_sqllab_view
```
Thanks for your help.

**Comment by PetitLepton** [comment]
My apologies again, I understood that I can run the DB migration through `superset db upgrade`.

**Comment by Rohit-pawar902** [comment]
hii were to run this cmd
