### ISSUE TITLE
auto login:AUTH_REMOTE_USER

### ISSUE THREAD

**Issue by 369488685** [apache/incubator-superset#5656]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version：0.26

Actually,when I click the link in my app,I want to redirect to superset without log in.Superset using the Flask-AppBuilder.I think I can solve it by AUTH_REMOTE_USER,but I don't know the details.I checked many docs,but didn't find any demo.

**Comment by yamyamyuo** [comment]
I have  wrote the tutorial to use AUTH_REMOTE_USER. https://github.com/yamyamyuo/superset-development. If you have any questions,  feel free to ask!

**Comment by 369488685** [comment]
@yamyamyuo 请问您有具体的联系方式吗？最近项目想二次开发权限，想咨询些问题

**Comment by yamyamyuo** [comment]
> @yamyamyuo 请问您有具体的联系方式吗？最近项目想二次开发权限，想咨询些问题

可以在简书私信我 https://www.jianshu.com/p/063ccb8e2a75
