### ISSUE TITLE
Other format support for scheduled reports 

### ISSUE THREAD

**Issue by nik-crisp** [apache/incubator-superset#5658]
Hi 
    i implemented scheduled reports successfully ( https://github.com/Affirm/incubator-superset/tree/scheduled )  , thanks to @mahedra

We need  report export in ( xls , xlsx ) and that could be scheduled .
Format could be selected from front end   #https://github.com/apache/incubator-superset/pull/5294

**Comment by mahendra** [comment]
@nik-crisp noted. I will implement this.

**Comment by nik-crisp** [comment]
Thank You @mahendra

**Comment by vk2987** [comment]
@nik-crisp  @mahendra 
Hi Nik/Mahendar,

I want to implement schedule reports but the above link got expired.  Can you guys please help me on this?

Thank you.
-Venkat
