### ISSUE TITLE
[pivot table] sorting in UI is not using numeric values

### ISSUE THREAD

**Issue by cottrell** [apache/incubator-superset#5674]
Just installed (latest version) ... just a UI thing, the sort of probably being applied in the front end.

![image](https://user-images.githubusercontent.com/223276/44301620-380e4c00-a312-11e8-950d-6ba38ca423ad.png)

**Comment by BLiu1** [comment]
If this is a pivot table, then in the visualizer, you need to go under Pivot Options, click on number format, type d (for digit), then click Create option "d". The default number format uses a fixed number of significant digits, which is not well explained in the documentation. If you want to format the number differently, they link to this: [](https://github.com/d3/d3-format)

**Comment by BLiu1** [comment]
Looking at this issue again, I realized that I completely missed the point of the bug. Consider my previous comment as a workaround.

**Comment by arpit-agarwal** [comment]
I have fixed the issue in above PR.can someone merge it
