### ISSUE TITLE
how the table veiw field order by

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#5679]
why the order dy is C D B A,
![image](https://user-images.githubusercontent.com/20242930/44351726-2032f580-a4d5-11e8-9895-633a6fe9c7d2.png)

**Comment by yamyamyuo** [comment]
#5566 do you mean the metric order problems?

**Comment by mistercrunch** [comment]
Pretty sure this is fixed on `master`

**Comment by qinzl1** [comment]
@mistercrunch metric  field still can not order  
![menu saveimg savepath20190110143614](https://user-images.githubusercontent.com/20242930/50950801-0aef4f80-14e6-11e9-91d8-ffcdededb8cc.jpg)

**Comment by qinzl1** [comment]
@yamyamyuo i see that you have fix this ,but how i config. becase in my case the metric is not order

**Comment by qinzl1** [comment]
@yamyamyuo pivot_table metric field did not order
