### ISSUE TITLE
Superset-0.26.3 Charts do not refresh after migrating the backend db to mysql

### ISSUE THREAD

**Issue by KartikTaskhuman** [apache/incubator-superset#5689]
New to the community here and already love the product. I am using superset v-0.26.3 and migrated the backend database from sqllite to mysql. After the migration, I created a few charts from a datasource (mysql). When I added few more rows on the underlying datasource, the corresponding charts did not refresh (I tried with different refresh frequencies on the dashboard). That said, when I go to the table view I do see the new rows being added.

I do see a chart "Altered sign" on the chart and when I click that to see the url_params control before and after is N/A and empty dictionary (please see the screenshots below). Started superset in debug mode (my config file pasted below) to check for any errors but no luck. Any pointers on how do I debug this issue?

![screen shot 2018-08-21 at 11 57 11 am](https://user-images.githubusercontent.com/34170284/44423367-d2e96f00-a53a-11e8-914f-0786c3e8d3e3.png)
![screen shot 2018-08-21 at 11 58 06 am](https://user-images.githubusercontent.com/34170284/44423369-d5e45f80-a53a-11e8-88d6-9a4cad969dc3.png)
![screen shot 2018-08-21 at 12 18 16 pm](https://user-images.githubusercontent.com/34170284/44423958-5c4d7100-a53c-11e8-9c06-65f213247350.png)

### Superset version
0.26.3 

### Superset Config File

ROW_LIMIT = 5000

SUPERSET_WEBSERVER_PORT = 5000
SECRET_KEY = [my app secret key]

SQLALCHEMY_DATABASE_URI = [mysql uri]

 Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True
WTF_CSRF_EXEMPT_LIST = []
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365

MAPBOX_API_KEY = ''

LOG_FORMAT = '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
LOG_LEVEL = 'DEBUG'
ENABLE_TIME_ROTATE = False
TIME_ROTATE_LOG_LEVEL = 'DEBUG'
FILENAME = os.path.join(DATA_DIR, 'log', 'superset.log')
ROLLOVER = 'midnight'
INTERVAL = 1
BACKUP_COUNT = 30

**Comment by KartikTaskhuman** [comment]
I found the issue by running the underlying SQL in the mysql console. There was an error forming the original query. Closing this as this is a non-issue.

**Comment by shekhar-joshi** [comment]
Hey @KartikTaskhuman ,
I wanted to do the mirgration from sqllite3 to Mysql. M not able to find anything promising anywhere.. could u please share anything u might have on this ??
