### ISSUE TITLE
[SIP-6] [Embeddable Charts] Migrate visualization-specific code to js plugin

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#5692]
Continued from the discussion in [SIP-5] #5680 

There is a decent amount of work to be done to make the visualization plugins are truly independent from the core superset.

### Q1: What need to be converted to JS?

> @mistercrunch : To make this frontend visualization plugin possible, we'll need to figure out how to get rid of the visualization-specific backend code in `viz.py` over time, to make sure that visualizations plugins are fully defined as Javascript. 

- > One easy step forward is to move the backend's `query_obj` code, which takes `form_data` as input and returns a query object (simple logic). 

- > The `get_data` method is probably harder to migrate to the front-end (takes a `dataframe` and returns nested objects), but it can probably be generalized quite a bit, so that it's not visualization-specific as much as ordering pandas-like operations on the result set.

### Q2: Where these new front-end methods should live?

> @mistercrunch : I'm guessing you were thinking about export the `adaptor` and using this as an the interface between chart and the visualization plugin. Now I'm thinking we may want to export a more complex object.

```js
export const visualization = {
  // Adapter from [SIP-5]
  adaptor, 
  // Convert formData into queryable format
  queryGenerator: (formData) => generateQuery(formData),
  // Convert formData into post-query operations 
  dataframeOperations: (formData) => (
    ['pivot_table',  { cols: [formData.cols], rows: formData.groupby }]
  ),
};
```

### Q3: How to actually implement these two parts?

> @mistercrunch : I'm not sure how to model the query vs dataframe operations, should it be incorporate into the query, or made into its own thing. Clearly on the backend we need two abstractions as one is used to interact with connectors (querying) and the other applies to all connectors (dataframe transformation).

> @john-bodley : I'm also perplexed as to how to best generalize this. It seems a first step is to map arbitrary data (via a query) into a somewhat generic (potentially visualization aware) form.

> @mistercrunch : I also wonder whether we could expose most of the pandas API from the frontend by doing a bit of magic, where the `dataframeOperations` above would somehow do something like `getattr(df, command)(**props)` on the backend.

**Comment by kristw** [comment]
After syncing offline with @john-bodley , it seems like we need to think more about 

### What kind of UI we have in mind on the explore page?

A. Users need to formulate query to get tabular data first, then map the columns from intermediate table to the encoding channels (color, size, length, position, etc.)

B. The controls list encoding channels, which users can put columns/metrics/aggregates from datasource and our engine translates this back into database query + post-query transformation.

### What operations should be done on back-end/front-end?

For example, group by and count should leverage database

**Comment by mistercrunch** [comment]
I was thinking solely about the shortest path to making visualizations as JS plugins, without redesigning the explore user interface.

I'm very supportive of redesigning the explore interface, but we may want to think of this as a different step or project altogether. Both these efforts are sizable on their own.

Happy to go either way, but personally I prefer smaller chunks of work.

**Comment by victornoel** [comment]
Also if you don't redesign the explore interface now, the "charts as js plugin" feature can be integrated sooner and people will start using it, which should give lots of user inputs about how the explore interface should be redesigned.

**Comment by kristw** [comment]
Here is the state of the app today. 

![viscodestructure 001](https://user-images.githubusercontent.com/1659771/44556284-dd983580-a6ed-11e8-87b5-0e4a9b54841b.jpeg)

**Comment by kristw** [comment]
The types of each field in `formDataSchema` can also be extended to be more specific than the primitive types, so we can automate some validation and post-processing. Some extra types:
- `dateFormat`: can be either string or function. If `string`, will be converted to function via `d3.format` and passed to the `Chart` as function
- `numberFormat`: can be either string or function. If `string`, will be converted to function via `d3.format` and passed to the `Chart` as function
- `jsFunction`: will be `sandboxEval` and passed to Chart as function
- `colorPalette`:

**Comment by kristw** [comment]
The interface of how to install/register components still need to be revised, but they key idea here is each chart will require `formDataSchema` and `dataSchema` that informs the implementation of the control panel or the chart itself. 
![image](https://user-images.githubusercontent.com/1659771/44676722-f3a53f00-a9e8-11e8-89d7-7263d37a082b.png)

**Comment by conglei** [comment]
Status of moving `get_data()` logic to frontend (or decouple the logic with visualization type).

| PR                                                     | Visualization | Status |
|--------------------------------------------------------|---------------|--------|
| https://github.com/apache/incubator-superset/pull/5753 | Piechart |    merged    |
|                                                        |               |        |
|                                                        |               |        |

**Comment by zhaoyongjie** [comment]
@kristw How is such a cool diagram generated?

**Comment by kristw** [comment]
@zhaoyongjie Drawn manually :)
