### ISSUE TITLE
Implement popup in custom visualization D3 components.

### ISSUE THREAD

**Issue by visshaljagtap** [apache/incubator-superset#5696]
Hi Team, Actually its not an issue. I just wanted to know how to implement popup in custom visualization D3 components.

I have created a custom visualization. As visualization components are written in pure D3. I want to implement the popup functionality on click event.

I am facing issue to write React code in D3 custom components. Also, I want to access the redux store state inside D3 component. so need help to achieve this functionality.

Thanks!

**Comment by visshaljagtap** [comment]
Can someone help me here?

**Comment by mistercrunch** [comment]
Popup is just `window.open`. What from the redux store do you need in the viz?
