### ISSUE TITLE
[Sqllab] Error: no such column When there are same fields in two tables with a join

### ISSUE THREAD

**Issue by Narcissus7** [apache/incubator-superset#5739]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Actual results
<img width="1060" alt="wx20180827-143236 2x" src="https://user-images.githubusercontent.com/25797624/44644278-201b8400-aa06-11e8-82ca-872af9f9f691.png">

but in Explore, can't get the field id__1
<img width="645" alt="wx20180827-143439 2x" src="https://user-images.githubusercontent.com/25797624/44644361-640e8900-aa06-11e8-97d8-e3e4e566a32e.png">

### Steps to reproduce

Select * [choose two tables with same fields]
Run query
Explore

**Comment by mistercrunch** [comment]
Which db engine is this? Looks like databases and drivers do different things to manage duplicated column names.

**Comment by Narcissus7** [comment]
Above db engine is SQLite. I have just tested MySQL.
<img width="566" alt="wx20180828-093939 2x" src="https://user-images.githubusercontent.com/25797624/44695786-6ffe5780-aaa7-11e8-968f-c3ffc2247505.png">
What can i do to avoid this error?

**Comment by mistercrunch** [comment]
The workaround is to alias your fields uniquely as in:

`SELECT a.id as foo_id, b.id as bar_id`

**Comment by Narcissus7** [comment]
Thanks. 
But there may be many fields. For instance:(tables and table_columns  are original tables of superset)
`SELECT * FROM tables a LEFT JOIN table_columns b ON a.id=b.table_id`
I still want to find a way to use `SELECT *`

**Comment by villebro** [comment]
@Narcissus7 As Superset wraps the SQL Lab query into a subquery, I don't think there is any way for Superset to select the deduplicated column without explicit aliases as @mistercrunch suggested. One approach would be to somehow reconstruct the the `SELECT *...` into explicit `SELECT a.col as col, b.col as col__1...`, but I don't think that's really feasible. I think it might be better to raise an Exception in SQL Lab if there are duplicates.

**Comment by Narcissus7** [comment]
@villebro I see. Thanks a lot

**Comment by mistercrunch** [comment]
We could try to detect the double underscore `__` when users click the `Explore` button and tell people to alias their columns properly.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/5778
