### ISSUE TITLE
Why we don't have other metrics but only the count(*) metric on metrics ?

### ISSUE THREAD

**Issue by sowalassane** [apache/incubator-superset#5740]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Superset version  0.26.3
### Expected results

Have all metrics that are present on my druid datasource
### Actual results

Have only count(*) metric
### Steps to reproduce

Hi all,
@mistercrunch 
I create my druid datasource from hive tables and have more than one metric.
But in superset, i see only the count(*) metric as shown on the screenshot below:

![image](https://user-images.githubusercontent.com/14936795/44648590-c608c780-a9e1-11e8-8776-86d4d5c4d5b2.png)
I know that i can compute some aggregations as sum, max or min of the metrics but i need just the values without this aggregations .
What have i to do to have all metrics in the metrics   ?

I am sorry if my questions are very basic, i am just new in superset.

Thanks in advance !

**Comment by sunnyKrystal** [comment]
@sowalassane 
I suffered the same issue. 
Maybe you can try to modified metric's SQL expression as below:
change `COUNT(xxx)` to `COUNT(xxx)/1`

or try to add metrics in this way [#4736](https://github.com/apache/incubator-superset/pull/4736)
