### ISSUE TITLE
Superset how to connect opentsdb

### ISSUE THREAD

**Issue by userxiaozhu** [apache/incubator-superset#5743]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

**Comment by mistercrunch** [comment]
Here's a recent relevant edit to the docs:
https://github.com/apache/incubator-superset/pull/5731/files
