### ISSUE TITLE
Upgrading superset

### ISSUE THREAD

**Issue by 369488685** [apache/incubator-superset#5754]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
upgrading to 0.27.0

### Actual results
still 0.26.3

### Steps to reproduce
pip install superset --upgrade
superset db upgrade
superset init

actually I want to upgrading superset from 0.26 to 0.27,I already run 
pip install superset --upgrade
superset db upgrade
superset init
but,when I finished it,the version is still 0.26

**Comment by Jemteddy** [comment]
0.26.3 is the latest actual version, there is only release candidate after that. I guess you can force the update to a release candidate but I'm not sure that it's a good idea.
