### ISSUE TITLE
Can we pass url parameters for dashboards

### ISSUE THREAD

**Issue by Geetha-LMI** [apache/incubator-superset#5755]
I want to pass the parameters from the user to dashboard. According to the user inputs i want to visualize dashboard. Can you suggest how to do that.

**Comment by xiawang** [comment]
I have the similar question, I could not find a clear and easy way to programmatically generate an iframe from the superset, or at least there is no such tutorials yet. We could either hack the iframe by passing parameters or hack the source code to provide our own api?

**Comment by wangshihan513** [comment]
If my understanding is correct, you can do that via Flask RESTAPI 
https://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html#rest-api

**Comment by mistercrunch** [comment]
@graceguo-supercat @williaster ^

**Comment by Geetha-LMI** [comment]
@mistercrunch I want to trigger the query with the dashboard ui parameters. then want to visualize that query results.

**Comment by graceguo-supercat** [comment]
Hi @Geetha-LMI for url parameters for dashboard, can you elaborate a little bit, what's input and expected results? What kind of customization you are looking for dashboard?

**Comment by graceguo-supercat** [comment]
@Geetha-LMI Superset dashboard is a set of charts, in which each chart is a sql lab query. Dashboard can organize charts nicely (defined in position_json), add default filters, inline filters and immunes, add auto refresh (and other dashboard metadata). Do you want to create related charts by API, then add them into dashboard?

**Comment by Geetha-LMI** [comment]
@graceguo-supercat  I want to pass the parameters to the sql lab query from the ui

**Comment by graceguo-supercat** [comment]
Flow like: dashboard url parameters -> map to chart parameters -> generate sql lab query -> rendered in chart in dashboard?

**Comment by Geetha-LMI** [comment]
@graceguo-supercat Yes

**Comment by renjithpaul27** [comment]
Hi..Was this functionality ever implemented in superset?

**Comment by ftwegner** [comment]
You might find the article [Apache Superset — Use URL to filter dashboards](https://www.blef.fr/superset-filters-in-url/) useful.
