### ISSUE TITLE
Unable to see more datasources when modifying a chart

### ISSUE THREAD

**Issue by manoloah** [apache/incubator-superset#5757]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

Superset version "version": "0.26.3", "GIT_SHA": ""}

For some reason when I create a new datasource via SQL Query editor this datasource cannot be found when creating a new chart. I only have the 4 datasources that come by default from the connected database. 

![captura de pantalla 2018-08-28 a las 11 27 48](https://user-images.githubusercontent.com/15304558/44736769-b490ef80-aab5-11e8-9554-e20f5eef183b.png)

### Expected results
When I click on the datasource option when creating a chart I cannot see all of the queries created from my SQL Query Editor. 

### Actual results
I just get all of the native tables from our connected database in postgres

### Steps to reproduce
Open a chart then try to add a Datasource and no tables created from the sql editor are shown as sources to use in the charting.

**Comment by Narcissus7** [comment]
Because the function get_all_datasources has filtered the datasources created from SQL Editor(/superset/connectors/connector_registry.py)
<img width="687" alt="wx20180830-115055 2x" src="https://user-images.githubusercontent.com/25797624/44828544-00c16880-ac4b-11e8-897b-28c03de11938.png">
<img width="615" alt="wx20180830-131451 2x" src="https://user-images.githubusercontent.com/25797624/44830894-b47c2580-ac56-11e8-9093-4bab3ac0add0.png">

You can comment out this

**Comment by SevenDL** [comment]
or if you are just an user, you can follow the steps:
1. Untick the not equal to SQL Lab View in the lists table and search, so the datasource created by visualize can be showed;
![image](https://user-images.githubusercontent.com/33197465/45026737-c2c0ac00-b071-11e8-94f6-be103409d9c4.png)
2.Click edit table ,untick the SQL Lab View then save.
![image](https://user-images.githubusercontent.com/33197465/45027499-264bd900-b074-11e8-97c3-f384bceb3a6a.png)
3.The tables created from the sql editor will be shown as datasources choices when you create charts.
