### ISSUE TITLE
Big Number Visualization Type bug

### ISSUE THREAD

**Issue by vnnw** [apache/incubator-superset#5779]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.0rc4

### Expected results
Big Number Viz with proper results rendered.

### Actual results
![image](https://user-images.githubusercontent.com/4979571/44836462-979d1d80-ac69-11e8-8384-672ddb0cfeec.png)

### Steps to reproduce

1. Install a new superset with sample data loaded.
2. Browse dashboard of "Birth." or explore the slices using Big Number Viz.

**Comment by kristw** [comment]
Please pull the latest from master. This issue should have been resolved in #5746 and has been merged  https://github.com/apache/incubator-superset/commit/0781cf2cfb15b49900625d705e8c484e1b956909
