### ISSUE TITLE
Improve code quality based on LGTM.com feedback

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5791]
Recently stumbled upon https://lgtm.com/projects/g/airbnb/caravel/alerts/?mode=list , and we have a bit of work to do in order to improve code quality. 

Historically we've been ignoring the `migrations/` folder when linting, and I think we should lint it all and augment the scope of the linter to include that folder.

**Comment by sturmer** [comment]
Hey there,

I'm looking into this. (Just saying in the hope to avoid duplicate efforts.)

I see that LGTM flags 5 errors but, 58 warnings and 61 recommendations. Do we want all of them in the same PR, or maybe we can split it (first errors, then warnings, then recommendations) and have smaller PRs?

Best,
Gianluca

**Comment by DiggidyDave** [comment]
Small PRs is usually better IMO. Minimizes blast radius in case of issue, easier to revert, easier to digest and properly review with rigor, etc.
