### ISSUE TITLE
Export from dashboard to CSV contains verbose names

### ISSUE THREAD

**Issue by tomsej** [apache/incubator-superset#5792]
I would like to allow users to export dashboard to CSV but they need verbose name. Could you please direct me how to do it? Thank you

**Comment by vnnw** [comment]
you may try to modify   https://github.com/apache/incubator-superset/blob/8a4b1b7c25a8234ac1641add38645a08fb338dd1/superset/views/core.py#L2493 if you know Flask.

**Comment by jhettler** [comment]
We have figured it out by adding header to pandas dataframe to_csv function 

`return df.to_csv(index=include_index, header=["test1","test2"], **config.get('CSV_EXPORT'))`

in 

https://github.com/apache/incubator-superset/blob/6b89b7f8b522e7226f3f5a61ed7f29b3e7d9013a/superset/viz.py#L486

you can find verbose_names in `self.datasource.data.verbose_map` object 

`
{'__timestamp': 'Time', 'sum__num': 'Suma čehosi', 'avg__num': 'avg__num', 'sum__sum_boys': 'sum__sum_boys', 'avg__sum_boys': 'avg__sum_boys', 'sum__sum_girls': 'sum__sum_girls', 'avg__sum_girls': 'avg__sum_girls', 'count': 'COUNT(*)', 'ds': 'ds', 'gender': 'gender', 'name': 'Jméno', 'num': 'num', 'state': 'state', 'sum_boys': 'sum_boys', 'sum_girls': 'sum_girls', 'num_california': 'num_california'}
`

and exported columns in `self.results.df.columns`

`Index(['name', 'sum__num'], dtype='object')`
