### ISSUE TITLE
Where can I find configuration help?

### ISSUE THREAD

**Issue by devcode2** [apache/incubator-superset#5799]
It's not an issue but I have tried to determine how everything works together for days without luck.  I'd like to use superset and maybe H20 to graph and analyse real-time survey results but I don't know how things tie together.

MariaDB -> Arrow -> Spark / Storm / Kafka -> Druid -> Superset ?

If arrow is an memory database, will this work?
MariaDB -> Arrow -> Superset ?  Then Zookeeper is used to configure the applications?

I have heard of Avro in this video. https://www.youtube.com/watch?v=W_Sp4jo1ACg and found Apache Nifi.

Can you please tell me where I can go to find guidance?  I have been unable to find a forum.

Thanks very much.

**Comment by mistercrunch** [comment]
Seems like you're trying to figure out how to build your realtime data pipeline. It's outside the scope of this repo/Superset to discuss this.

**Comment by devcode2** [comment]
Thanks
