### ISSUE TITLE
Add Standard Permission for Dashboard Access

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#5805]
We have permissions for datasource access and metric access (the latter is currently broken). We should add one that gives access to particular dashboards, so that, for example, a warehouse manager and a pharmacy manager only see their respective dashboards despite the fact that the dashboards are built off of the same datasource.

I understand this can probably be done in the FAB but I think it should be something standard.

**Comment by yamyamyuo** [comment]
see https://github.com/apache/incubator-superset/issues/538
