### ISSUE TITLE
uploading unicode csv

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#5807]
when I upload a utf8 based csv file I get the following error:
`'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
`

I tried to add `?charset=utf8` to my SQLALCHEMY_DATABASE_URI but still no luck

**Comment by aboganas** [comment]
I don't think it has BOM. see the attached sample file
[test.csv.zip](https://github.com/apache/incubator-superset/files/2351336/test.csv.zip)

**Comment by zhaoyongjie** [comment]
@aboganas which superset version do you use?

**Comment by aboganas** [comment]
First, I really appreciate your help. Thanks sooooo much

I'm using the latest version 0.27.0, but I'm using python 2. I will try to switch to python 3 to see if it solves the problem

**Comment by aboganas** [comment]
@zhaoyongjie just tested with python3; unfortunately still same problem. Any help, will be greatly appreciated.

**Comment by aboganas** [comment]
Thanks for the help; the problem was not sitting the correct charset that correspond to the database exactly.
