### ISSUE TITLE
Bugs in version 0.27.0

### ISSUE THREAD

**Issue by wangshihan513** [apache/incubator-superset#5808]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Actual results
![error2](https://user-images.githubusercontent.com/40997574/45033692-8da66080-b055-11e8-98fc-abf10c36c326.PNG)

### Steps to reproduce
After updated to version 0.27 whenever I would like to open dashboard or slice view, there is no css and cannot show any graph. 
Any way to go back to version 0.26.3?

**Comment by zhaoyongjie** [comment]
need rebuild frontend script
```
cd superset/asserts
npm install && npm run build
```

**Comment by wangshihan513** [comment]
I don't have superset/assests folder, shall I download the source code and put them there?

**Comment by zhaoyongjie** [comment]
how do you install superset?

**Comment by wangshihan513** [comment]
Everything was fine until I upgrade to 0.27. I did that via pip install superset --upgrade

**Comment by wangshihan513** [comment]
I just download the assets folder and copy to superset. Now it is unstable, but can show the UI sometimes after repeatedly refresh.

**Comment by mistercrunch** [comment]
Sounds like you have a zombie processes serving a previous version of Superset. Make sure to kill all web servers processes and restart clean.

**Comment by davidhassan** [comment]
Make sure to 
pip install superset --upgrade
superset db upgrade
superset init

Then make sure there are no web server processes running.
Then restart the superset web server.

Even easier just reboot the server and restart superset.
