### ISSUE TITLE
Allow import and export dashboards and charts by CLI

### ISSUE THREAD

**Issue by BrayanArrieta** [apache/incubator-superset#5821]
### Superset version
On master branch

### Description of the new feature
I think that it's a great idea allow to superset the possibility to import and export dashboards and charts by means of the command line interface (CLI). It's similar to the feature to import and export the datasources by means of the CLI .Thanks !

**Comment by Marcofeli** [comment]
Amazing idea, it will make Superset more flexible to use. Please add this to the next version 😁

**Comment by MLopezJ** [comment]
Sounds good! Will be useful for me ;)

**Comment by arpit-agarwal** [comment]
I have added a #5991 initial implementation of underlying feature. The WIP is adhere to contributing guidelines

**Comment by arpit-agarwal** [comment]
@mistercrunch  please reopen this as PR #5991 is reverted

**Comment by rashmigulhane** [comment]
While importing dashboard from cli how do i provide owners for dashboard.I am unable to find any field which has to be set in json ?
