### ISSUE TITLE
Table View - remove filter function not found

### ISSUE THREAD

**Issue by tcollier1975** [apache/incubator-superset#5824]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
ability to remove filter(s) from table view chart

### Actual results
`table.js?e418:148 Uncaught TypeError: slice.removeFilter is not a function
    at HTMLTableCellElement.eval (table.js?e418:148)
    at HTMLTableCellElement.eval [as __onclick] (VM2839 35:1120)
(anonymous) @ table.js?e418:148
(anonymous) @ d3.js?65ae:1120`

### Steps to reproduce
create table view visualization with Table Filter turned on

**Comment by kristw** [comment]
Is this from current `master`?

**Comment by tcollier1975** [comment]
0.27.0

**Comment by tokarskyibogdan** [comment]
@mistercrunch any updates here?
