### ISSUE TITLE
Y log scale labels overlap

### ISSUE THREAD

**Issue by brylie** [apache/incubator-superset#5833]
Superset version: 0.26.3

# Issue
Y-axis labels would be easy to read, with no overlap.

# Actual results
Y-axis labels overlap.

![screenshot_20180906_153127](https://user-images.githubusercontent.com/17307/45157664-79e03300-b1ea-11e8-8518-802d47d610a2.png)

# Steps to reproduce
1. create a Time Series - Line Chart
2. set Y Log Scale to `true`

# Possible improvement
In presentation graphics, we have cleaned up the y-axis, leaving only the 'orders of magnitude' labels remaining. E.g.

![screenshot_20180906_153654](https://user-images.githubusercontent.com/17307/45157763-b0b64900-b1ea-11e8-9761-f0e0d025c821.png)

**Comment by trucklos** [comment]
Have a workable hack for this, my only doubt with your proposed improvement is if the domain of your data does not cross a power of ten (say your data ranges from 200-300), then there will be no labels.  Also, should we do this for a log xAxis as well?

<img width="719" alt="screen shot 2018-09-07 at 11 45 50 pm" src="https://user-images.githubusercontent.com/200008/45250063-a6cf3b80-b2f9-11e8-8668-95e4c69e9f1c.png">

**Comment by brylie** [comment]
Looks really nice! In fact, some of our data do not cross the power threshold. I.e. a lot of it was groped in separate powers, so I used this graph to spread the data out for visibility.

**Comment by brylie** [comment]
I believe this is still a valid issue, even if it is inactive.

**Comment by suddjian** [comment]
I think this has been fixed. I'm unable to repro.

<img width="736" alt="Screen Shot 2019-11-14 at 2 30 13 PM" src="https://user-images.githubusercontent.com/1858430/68901740-59afdc00-06eb-11ea-8809-b3bce4a5a29a.png">

The inverse problem is still valid, though. The values in the following screenshot range between 0.1 and 0.9, and there are no Y-axis labels displayed at all.

<img width="738" alt="Screen Shot 2019-11-14 at 2 32 20 PM" src="https://user-images.githubusercontent.com/1858430/68901837-9a0f5a00-06eb-11ea-806e-efa775840469.png">

**Comment by junlincc** [comment]
problem resolved
