### ISSUE TITLE
Can't resolve 'gl'

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#5843]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest master
npm: 5.6.0
node: v8.11.4
yarn: 1.10.0

### Expected results
for `npm run dev-server` to run without errors

### Actual results
`WARNING in ./node_modules/luma.gl/dist/esm/webgl-context/create-headless-context.js
Module not found: Error: Can't resolve 'gl' in '/Users/####/superset/vanilla/incubator-superset/superset/assets/node_modules/luma.gl/dist/esm/webgl-context'
 @ ./node_modules/luma.gl/dist/esm/webgl-context/create-headless-context.js
 @ ./node_modules/luma.gl/dist/esm/webgl-context/index.js
 @ ./node_modules/luma.gl/dist/esm/webgl/functions.js
 @ ./node_modules/luma.gl/dist/esm/index.js
 @ ./node_modules/@deck.gl/core/dist/esm/shaderlib/index.js
 @ ./node_modules/@deck.gl/core/dist/esm/lib/init.js
 @ ./node_modules/@deck.gl/core/dist/esm/index.js
 @ ./node_modules/deck.gl/dist/esm/index.js
 @ ./src/visualizations/deckgl/layers/path.jsx
 @ ./src/visualizations/index.js
 @ ./src/modules/AnnotationTypes.js
 @ ./src/chart/chartAction.js
 @ ./src/dashboard/containers/Dashboard.jsx
 @ ./src/dashboard/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/dashboard/index.jsx

WARNING in ./node_modules/luma.gl/dist/esm/webgl-utils/webgl-types.js
Module not found: Error: Can't resolve 'gl/wrap' in '/Users/####/superset/vanilla/incubator-superset/superset/assets/node_modules/luma.gl/dist/esm/webgl-utils'
 @ ./node_modules/luma.gl/dist/esm/webgl-utils/webgl-types.js
 @ ./node_modules/luma.gl/dist/esm/webgl-utils/index.js
 @ ./node_modules/luma.gl/dist/esm/webgl/functions.js
 @ ./node_modules/luma.gl/dist/esm/index.js
 @ ./node_modules/@deck.gl/core/dist/esm/shaderlib/index.js
 @ ./node_modules/@deck.gl/core/dist/esm/lib/init.js
 @ ./node_modules/@deck.gl/core/dist/esm/index.js
 @ ./node_modules/deck.gl/dist/esm/index.js
 @ ./src/visualizations/deckgl/layers/path.jsx
 @ ./src/visualizations/index.js
 @ ./src/modules/AnnotationTypes.js
 @ ./src/chart/chartAction.js
 @ ./src/dashboard/containers/Dashboard.jsx
 @ ./src/dashboard/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/dashboard/index.jsx`

### Steps to reproduce
clone the latest master branch, and then follow the installation instructions as explained [HERE](https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md) 

**Note**: I also tried nuking `node_modules` and other lock files, but still no luck
**Note2**: if I install 'gl' manually using yarn, then the error becomes in the sort of `WARNING in ./node_modules/bindings/bindings.js 81:43-53
Critical dependency: the request of a dependency is an expression`
**Note3**: if I run `npm run build` the interface shows correctly

**Comment by botasky11** [comment]
@aboganas hi，I have also met this problem, Did you solve it ?
