### ISSUE TITLE
Any documentation on the Event Flow visualization tool?

### ISSUE THREAD

**Issue by spamula** [apache/incubator-superset#5873]
Does anyone have a link to documentation for the event flow visualization in superset? Doesn't seem to be particularly clear how to use this? Any help is appreciated!
Cheers

**Comment by gitgithan** [comment]
This has got to be the hardest visualisation I interacted with. 
No docs for me too, but I tried to click around and reason what everything does, hopefully this thread grows in helpfulness.

**Time**
1. Fill in Time Column with the column contain the timestamps at which events happen, this will be used to order the events by elapsed time (you can order by event sequence too by opening the "Controls" in the right pane).
2. Set the Time Grain to at least as small as your Time Column granularity for the most accurate viz. Coarser time grains will get DATE_TRUNC and lose/become wrong information. You can click View query and View results within top right hamburger icon to verify what your settings will run and result in.

**Event Definition**
1. Column containing entity ids
Select the categorical values to show on the y-axis 
2. Column containing event names
Select the categorical values to show on the x-axis
3. Event count limit 
Cut off point for number of vertical lines on the viz 
4. Minimum leaf node event count
Not sure, no effect on my graph

**Controls**
There are many controls here all interacting with one another. 
1. Drop down list containing DISTINCT of what you put in  "Column containing event names"
2. `+ -` button to move the reference point around
3. Pie Chart (not for controlling) to see the results of your controls
4. List of checkboxes containing items from 1. to turn on and off in the main viz and pie chart
5. Hide nodes with too little samples of a certain type of flow (gradually increase it's value from 1 to filter/clean up the viz)
6. Elapsed-Time vs Event Sequence (select the latter first before playing with controls 1,2 to help understanding the reference point shifting mechanism)

**Usage tips**
1. When moving reference point, observe where the dotted vertical line is.
2. When you move reference to the right, some flows have negative time, these negative nodes can get vertically misaligned with their positive nodes (think of the negative side as an independent y-axis)
3. When 2 events happen at exactly the same time, zoom in multiple times to see the thin vertical bar in viz so you can mouseover/click
4. Click into any event in viz to see which  "Column containing entity ids" they represent.(only after clicking the event open does the dragging of bottom pane up work)

**Problems**
1. When 2 events begin/occur at exactly the same time, the viz seems to show the event coming first in row order in the "View results". Turning on and off event filters in the Controls helps reveal the overlayed hidden events.
2. Wrong information in event bars, eg. 1st to 2nd event ~9days, 2nd to 3rd event 5minutes (notice the scale change). The 1st to 2nd event shows 8.9d 2nd to 3rd event shows 0.0d mean elapsed time.(looks like round down issue)
3. y-axis label of "# events" looks like it should mean "DISTINCT(Column containing entity ids)"

**Debugging Tips**
1. Tweak Column containing entity ids and Column containing event names to use categoricals of finer granularity (if you have/suspect you have hierarchical categoricals where 1 col represents similar information as another. eg. music--> TV, music--> Radio). Take this to the extreme but using completely unique ids in Column containing event names to trace through how exactly the event flowed through
2. Look at the # Events above the pie chart under Controls. This is less confusing than then the # events from hovering over the viz

1st week using superset for me, looks like a great tool. Anyone knows where/how can we set up a proper documentation for each time of available visualisation? I would love to learn interesting uses of other types of viz too.

**Comment by willbarrett** [comment]
Hi @gitgithan - welcome to the Superset world! Thanks for the recommendation to create documentation of the visualizations. All of our documentation for Superset exists in this folder of the repo: https://github.com/apache/incubator-superset/tree/master/docs - documentation is written in `.rst` format and submitted via pull request. I think adding a "Visualizations" section to this documentation would be a really great improvement, and also a wonderful first contribution if you're interested!

**Comment by lpatruno** [comment]
There's some documentation in the [PR](https://github.com/apache/incubator-superset/pull/3102) that introduced the visual.

**Comment by eugeniamz** [comment]
Here is a short [demo](https://www.youtube.com/watch?v=tu1lzwTr2po)
