### ISSUE TITLE
Empty "Color Scheme" dropdown

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5889]
@kristw is this related to your recent work on colors? https://github.com/apache/incubator-superset/pull/5815

<img width="330" alt="screen shot 2018-09-13 at 12 11 00 pm" src="https://user-images.githubusercontent.com/487433/45510112-23c14180-b74e-11e8-980d-e11ed64f2225.png">

**Comment by kristw** [comment]
Yes, I will take care of it. Seem like the control calls `getAllSchemes()` before schemes are registered.

**Comment by kristw** [comment]
I think this is related to #5883 . Will investigate further and fix.

**Comment by kristw** [comment]
![color_bug](https://user-images.githubusercontent.com/1659771/45511944-35f1ae80-b753-11e8-9194-f4a5bf82e103.png)

**Comment by kristw** [comment]
I will fix the `ColorSchemeControl` directly. Webpack may do something more complicated than I thought.

**Comment by mistercrunch** [comment]
Thanks for fixing this!
