### ISSUE TITLE
Paginator starts at page zero

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#5892]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
Start at page 1

### Actual results
![image](https://user-images.githubusercontent.com/1659771/45523400-fab8a500-b77d-11e8-978d-253720517080.png)

### Steps to reproduce
Go to charts or dashboards page (needs to have a lot of items so it is more than one page)

**Comment by kristw** [comment]
bump

**Comment by mistercrunch** [comment]
@dpgaspar seems like we get this from FAB, I never noticed before being so used to zero-indexed constructs.
