### ISSUE TITLE
[SQL Lab] Cannot scroll to see the entire table schema for very wide tables

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#5899]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
One should be able to scroll down to see the complete table metadata.

### Actual results
For tables with a large number of columns, if one chooses a table to see the schema, one cannot scroll to see all the columns. Note this problem can be circumvented if one already has another table schema listed.

### Steps to reproduce
1. Choose a table with a large number of columns, i.e., we're seeing this problem with a table comprising of more than 64 columns. 
2. Try scrolling to the bottom.

to: @kristw @timifasubaa

**Comment by timifasubaa** [comment]
My plan is to make only one 'card' per table clicked and prefetch only when the user clicks the preview button on the card. That should resolve this issue.

**Comment by kristw** [comment]
bump
