### ISSUE TITLE
ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//

### ISSUE THREAD

**Issue by rizplate** [apache/incubator-superset#5919]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest as of this ticket

### Expected results
local docker install should work as per docs

### Actual results
local docker install does not work

### Steps to reproduce

1. clone latest master
1. Followed , ```Start with Docker instructions``` in documentation
1. stdout shows 
```
consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds...
```

**Comment by mistercrunch** [comment]
Tag the contributor(s) who created/edited these files on this issue pls
