### ISSUE TITLE
No way to set current period as upper bound on query timeframe

### ISSUE THREAD

**Issue by jtalmi** [apache/incubator-superset#5920]
The only options for setting the upper bound of the DateFilterControl dynamically with smart date parsing are:

- last [period]
- next [period]
- today, yesterday, tomorrow

Selecting last [period] sets the upper bound as the beginning of that period, e.g. if today is Sept. 18 and I set the upper bound as "last month", the upper bound will be August 1, i.e. the beginning of last month, which makes sense semantically since the data goes up until "last month".

However, there is no way to set the upper bound as the _current period_ as far as I can tell, and this is important for creating visualizations that only include full weeks/months/etc. of data. 

Example: If today is september 18 and I want to include data up until Sept 1, i.e. the last full month of data, I need to be able to enter "This month" as the upper bound, which sets the time frame as < Sept 1.

I'd be happy to submit a PR to add a "This x" option to the [DateFilterControl](https://github.com/apache/incubator-superset/blob/6c9be9d67bc73893055f989915ec4a43e7e848c1/superset/assets/src/explore/components/controls/DateFilterControl.jsx), but I wanted to make sure I wasn't missing something first. 

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by mistercrunch** [comment]
@betodealmeida 
Also for reference, we're powered (and limited) by the python libs we use for this `parsedatetime` and `python-dateutil`

**Comment by mistercrunch** [comment]
BTW those libs are pretty powerful and can do much more than you probably think, statements like `june` or `2015` work as well.

It would be cool to show more of what's supported out of our time-parsing function, and what it currently resolves to. Maybe an info bubble with some suggestion and some label showing what relative times map to as the person types, shows an alert when it doesn't compute. We'd need to run async requests against a new endpoint here to do this.

**Comment by leakingoxide** [comment]
Just to be sure: do we still want this new endpoint? Asking because the DateFilterControl widget and related code seems to have been updated quite often "recently".

If yes, I'd like to pick this up.

@mistercrunch

**Comment by mistercrunch** [comment]
Here: https://github.com/apache/incubator-superset/issues/6360

**Comment by omkay** [comment]
I know it's been time to this issue but I would like to share the trick I found for this issue
as superset is using parsedatetime to parse smart dates I have used the following sneaky trick to get upper bound for current month and the upper bound for the current week
`one month after last month` returns the start of the current month
`three days after last week` returns the start of the current week
