### ISSUE TITLE
Surface Table "description" field as info bubble + tooltip where tables are listed / shown

### ISSUE THREAD

**Issue by rpwils** [apache/incubator-superset#5922]
## how to surface?
With a simple info bubble tooltip as shown here
<img width="261" alt="screen shot 2019-02-21 at 8 43 09 am" src="https://user-images.githubusercontent.com/487433/53185861-bf37c780-35b4-11e9-8be8-f6fef7d45b9f.png">

## where to surface?
* In the "Select a datasource" modal
<img width="859" alt="screen shot 2019-02-21 at 8 37 43 am" src="https://user-images.githubusercontent.com/487433/53185503-007ba780-35b4-11e9-9d5e-204e3bb65b3e.png">

* in the "Create a new chart" datasource dropdown
<img width="464" alt="screen shot 2019-02-21 at 8 39 12 am" src="https://user-images.githubusercontent.com/487433/53185623-391b8100-35b4-11e9-94b8-57e25d01d490.png">

**Comment by mistercrunch** [comment]
What do you mean by that?

**Comment by rpwils** [comment]
Besides going in and hitting edit on a given table, does the description form a table show up anywhere.  If not, would it be nice to add to the sql lab to give a quick way to view the information  or potentially on the table list view as am accordion view?

**Comment by mistercrunch** [comment]
Oh right, it's possible it does not show up anywhere. We should make sure it shows up wherever tables are listed / shown.
