### ISSUE TITLE
[BUG][Time Series - Bar Chart] cannot order by other selected metrics

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#5927]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.2

### Expected results
the bar can order by other metrics, not just the default `sum_active_days_user` metrics.
and when I change the sort by, the graph should render it out.

### Actual results
![2](https://user-images.githubusercontent.com/8351385/45728200-953f3b00-bbf9-11e8-8386-43d6df0cb4ea.png)
![1](https://user-images.githubusercontent.com/8351385/45728201-9b351c00-bbf9-11e8-8e80-c599f5ff6e37.png)

### Steps to reproduce
1. create new charts
2. select a datasource
3. visualization type : `Time Series - Bar Chart`
4. config the metrics, group by
5. modify the sort by to different metrics
and no mater how you change the `sort by`, in the `View Query`, the `ORDER BY` is unchanged.

**Comment by yamyamyuo** [comment]
@mistercrunch @betodealmeida @williaster does anyone has idea about this?

**Comment by bkarlson** [comment]
Stumbled upon this as well, and looks like the stacking is sorted by metric name in ABC order. I.e. renaming a metric will shift it's position in the stack. Worked for Bar chart, may work for other charts as well. Not optimal, but doable.

**Comment by wushenchao** [comment]
Is this sorting redundant? Still this is a bug？
