### ISSUE TITLE
Make dashboard dropdown sticky

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#5939]
<img width="630" alt="screen shot 2018-09-19 at 9 09 58 pm" src="https://user-images.githubusercontent.com/487433/45795410-74560480-bc50-11e8-9eca-f78016e968a8.png">

It's common to add many charts to the same dashboard one after another using the "Save a chart" modal. This modal should remember your last selection and make it sticky. Maybe using a cookie?

**Comment by jeffcarey** [comment]
Would using localStorage (or sessionStorage) be suitable?

**Comment by mistercrunch** [comment]
`sessionStorage` should work
