### ISSUE TITLE
[Bug] Sqllab -> Explore -> Bar Chart

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#5947]
When users write a query and then move to the explore view, the table view reders but once they try to click a `Bar Chart - Distribution` type viz the explore blanks out. The only way to get back the current state is copying the link and reloading the page.

Steps to Reproduce:
1. Goto sqllab
2. Run the query
3. Click `Explore` btn
4. Change viz type to 'Distribution Bar Chart`
5. Set metrics = `SUM(ride_count`) and series = 'venue_name`

StackTrack:
{“error”: “The datasource associated with this chart no longer exists”, “stacktrace”: “Traceback (most recent call last):\n  File \“/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/superset/views/core.py\“, line 1158, in explore_json\n    datasource_id, datasource_type, form_data)\n  File \“/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/superset/views/core.py\“, line 1217, in datasource_info\n    ‘The datasource associated with this chart no longer exists’)\nException: The datasource associated with this chart no longer exists\n”}

![bug-explore](https://user-images.githubusercontent.com/27827808/45851509-2395e880-bcf0-11e8-843c-3f4207871b5f.gif)

**Comment by iamnewneo** [comment]
I am also facing the same issue. How can we solve this? @hughhhh did you find any hack for this?

**Comment by mrshu** [comment]
I also ran into this today. @hughhhh @iamnewneo do you happen to have any way of mitigating this problem? Could it be in nay way related to #5019?

Thanks!
