### ISSUE TITLE
Superset creates large no. of idle connections to Postgres.

### ISSUE THREAD

**Issue by sayednazeef** [apache/incubator-superset#5953]
I have used Postgres as datasource for the charts. when dashboard is loaded connection goes from active to idle state and remains the same until restart. 
### Superset version
0.15.1 and 0.26.0
### Expected results
Idle Connections needs to be managed or released properly.

### Actual results
Idle connection are created and remains as long as the application restarts

### Postgres Version:
9.6.8

### Steps to reproduce
Just Reload the Dashboard and fire queries from sql lab:
fire following query:
select state, count(pid) from pg_stat_activity where datname = 'my_db' group by state;

**Comment by mistercrunch** [comment]
From https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Connections
Connections -> "The number of connection attempts (successful or not) to the MySQL server."

More about it here:
https://stackoverflow.com/questions/7432241/mysql-show-status-active-or-total-connections

**Comment by mistercrunch** [comment]
If you want more control over connection pooling, check out the Flask-SQLAlchemy docs here:
http://flask-sqlalchemy.pocoo.org/2.3/config/

By default, each web worker will start a connection pool with 5 slots. You can change this in your environment by tweaking the `SQLALCHEMY_POOL_SIZE`, `SQLALCHEMY_POOL_TIMEOUT` and `SQLALCHEMY_POOL_RECYCLE` in your `superset_config` to get more control over the connection pool. 

For most, the expected number of connections should we `<= [number of web servers] * [number of gunicorn workers] * [config.SQLALCHEMY_POOL_SIZE]`

**Comment by mistercrunch** [comment]
Would be great if someone could document this in `installation.rst`!

**Comment by GiannisDimitriou** [comment]
@mistercrunch 
I am experiencing the same issue on superset metadata db (postgres).
A lot of the connection are on "idle in transaction" state meaning that the handling of the transaction from Superset site is not optimal.

Another observation is that the query for all those "idle in transaction" transactions is the same as shown below, if that helps pinpoint issue.

`SELECT 
slices.created_on AS slices_created_on, 
slices.changed_on AS slices_changed_on, 
slices.id AS slices_id, 
slices.slice_name AS slices_slice_name, 
tables_1.created_on AS tables_1_created_on, 
tables_1.changed_on AS tables_1_changed_on, 
tables_1.id AS tables_1_id
....`

Superset version 0.37.0rc1

**Comment by oOhyeahh** [comment]
I have this same issue. Is there any way to release the idle connection after certain period?

**Comment by mistercrunch** [comment]
What version as this is a super old thread. Also I think there's a lot of configurability around connection pools in Flask / flask-sqlalchemy

@dosu can you share some information and pointers as to how to configure database connection pool in Flask apps like Apache Superset? Also let's provide information about implications is has based on gunicorn (or other web server) people use. I think the Flask app will create one pool per gunicorn worker (?)

**Comment by mistercrunch** [comment]
I meant to summon @dosubot

**Comment by oOhyeahh** [comment]
My current version is 3.1.1. I use PostgreSQL database. The current Superset I self-host connects to BigQuery, where I build dashboards and charts.

**Comment by mistercrunch** [comment]
@dosu can you share some information and pointers as to how to configure database connection pool in Flask apps like Apache Superset? Also let's provide information about implications is has based on gunicorn (or other web server) people use. I think the Flask app will create one pool per gunicorn worker (?)

**Comment by rusackas** [comment]
I would ask @dosu-bot for this :D
