### ISSUE TITLE
Superset + Impala get error:'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by AndyXGWang** [apache/incubator-superset#5954]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
{"error": "Connection failed!\n\nThe error message returned was:\n'NoneType' object has no attribute 'get'"}

**Comment by mistercrunch** [comment]
That's a very generic error, please share the full stack trace.
