### ISSUE TITLE
Cannot save the chart when Time Series - stacked is selected.

### ISSUE THREAD

**Issue by Saajan** [apache/incubator-superset#5956]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.999.0.dev0

### Steps to reproduce
Select the datasource 
Select Visualization Type to Time-series Stack
Select the date range
Add Metrics
Click run query 

The chart is plotted .

Now change the name of the chart from 'Undefined - undefined ' to something meaningful.
The page breaks .

Errors log in console 

Uncaught TypeError: Cannot read property 'annotationError' of undefined

react-dom.development.js?61bb:14389 The above error occurred in the <Connect(AnnotationLayerControl)> component:
    in Connect(AnnotationLayerControl) (created by Control)
    in div (created by Control)
    in Control (created by ControlPanelsContainer)
    in div (created by ControlSetRow)
    in div (created by ControlSetRow)
    in ControlSetRow (created by ControlPanelsContainer)
    in div (created by Panel)
    in div (created by Panel)
    in Transition (created by Collapse)
    in Collapse (created by Panel)
    in div (created by Panel)
    in Panel (created by ControlPanelSection)
    in ControlPanelSection (created by ControlPanelsContainer)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (created by ControlPanelsContainer)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by ControlPanelsContainer)
    in div (created by ControlPanelsContainer)
    in div (created by ControlPanelsContainer)
    in ControlPanelsContainer (created by Connect(ControlPanelsContainer))
    in Connect(ControlPanelsContainer) (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in ExploreViewContainer (created by Connect(ExploreViewContainer))
    in Connect(ExploreViewContainer) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Timer (created by ExploreChartHeader)
    in div (created by ExploreChartHeader)
    in div (created by ExploreChartHeader)
    in ExploreChartHeader (created by ExploreChartPanel)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by ExploreChartPanel)
    in div (created by ExploreChartPanel)
    in ExploreChartPanel (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in ExploreViewContainer (created by Connect(ExploreViewContainer))
    in Connect(ExploreViewContainer) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

**Comment by yamyamyuo** [comment]
> Superset version
0.999.0.dev0 

is it too old?

**Comment by Saajan** [comment]
Sorry my mistake . Its the latest build of superset. Still i have the issue.
