### ISSUE TITLE
Apache Superset Issue - Dashboards redirects to homepage

### ISSUE THREAD

**Issue by abhishek0419** [apache/incubator-superset#5968]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

work@d9ddffb256c9:~/incubator-superset$ superset --version
Loaded your LOCAL configuration at [/home/work/incubator-superset/superset/superset_config.py]
Flask 0.12.4
Python 3.6.6 (default, Sep  5 2018, 03:40:52)
[GCC 6.3.0 20170516]

### Expected results
Clicking on any charts or sample dashboards should display the same

### Actual results
Instead of showing Dashboards it directs again to the homepage. This happens for all other options 
like charts, Dashboards, Data Sources etc.

### Steps to reproduce

Attached snapshots to showcase the issue.
![homepage_on_login](https://user-images.githubusercontent.com/35740229/45999577-b2757d00-c0c3-11e8-81f7-20a617d8b6b9.JPG)
![redirect_homepage_dashboardsclick](https://user-images.githubusercontent.com/35740229/45999578-b2757d00-c0c3-11e8-953c-982dbbd5d226.JPG)

**Comment by yamyamyuo** [comment]
you can install superset through `pip install superset` then the frontend is compiled, the css will show up.
otherwise, you should compile the frontend yourself. see https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#frontend-assets

**Comment by abhishek0419** [comment]
Thanks for your response @yamyamyuo . I followed the steps as mentioned in the suggested rl. But unfortunately it didn't worked for me.

**Comment by abhishek0419** [comment]
The issue I face while running above commands is that the compilation is not totally successful. I am getting warnings when running - npm run dev-server 
Snapshot attached for reference.
![package refresh error](https://user-images.githubusercontent.com/35740229/46029311-a8c63680-c110-11e8-8906-555fb6eb760e.JPG)

**Comment by mistercrunch** [comment]
You can disregard these warning, though we may want to open another issue for that specifically. Also the title of this issue is misleading, I don't think there are redirections happening here, you just failed at building the JS bundles.

**Comment by abhishek0419** [comment]
Thanks for your response @mistercrunch . 
In summary, the issue I am facing is whenever I click any option be it Dashboards, SQLEditor, Charts, Tables etc, I see the same homepage again and again. I expect to see the object I  have clicked. 
 I am new to Superset so might have given a wrong title.

**Comment by abhishek0419** [comment]
Hi All,

Thanks for all your inputs. Apart from performing all steps as suggested by @yamyamyuo and thereafter checking on point raised by @mistercrunch , I was able to fix this issue. 
What worked for me was executing the js_build.sh script at ..incubator-superset/superset/assets .
