### ISSUE TITLE
Apache Superset Issue With Kylin - No Tables shown on successful connection

### ISSUE THREAD

**Issue by vatsalpande** [apache/incubator-superset#5969]
Make sure these boxes are checked before submitting your issue - thank you!

- [ Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y ] I have reproduced the issue with at least the latest released version of superset
- [ Y ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.27.0

### Expected results
Should show tables on Successful Connection.

### Actual results
I am trying to configure Kylin connection with Superset. I have configured kylin package and my connection seems to be ok. However, it doesn't show me any tables, at the bottom of the page.
I checked the logs and it tries to call the below Rest API - 
############################################################################
method: GET
url: http://XXXX.XXXX:80/kylin/api/tables_and_columns?project=projectName
headers: {'User-Agent': 'Kylin Python Client', 'Authorization': 'Basic someEncodedPassword'}
body: None
############################################################################
I have tried the above url with Postman, and it returns me table and column names.

Moreover, if I go to Sql Editor in Sql Lab it shows me Database name, schema & Tables. But as soon as I click on any of the table, it gives an error  " startswith first arg must be bytes or a tuple of bytes, not str"

Attached screenshots for same
<img width="1423" alt="3" src="https://user-images.githubusercontent.com/12035570/45994531-dfd11500-c048-11e8-8a67-1c75bd825873.png">
<img width="1421" alt="1" src="https://user-images.githubusercontent.com/12035570/45994532-dfd11500-c048-11e8-9f27-a8d2c1764017.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/12035570/45994533-dfd11500-c048-11e8-9560-08f135a6a7f0.png">

### Steps to reproduce

**Comment by mistercrunch** [comment]
Which version of python is this?

**Comment by vatsalpande** [comment]
@mistercrunch - Python 3.6.5

**Comment by ming2055** [comment]
How is this problem solved?

**Comment by zhaomoran** [comment]
Same problem here with  Superset 0.35.2
