### ISSUE TITLE
Filterbox Time range doesnt work

### ISSUE THREAD

**Issue by tomsej** [apache/incubator-superset#5971]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Master

### Expected results
Filter is working

### Actual results
Whenever I click on Time range the filter disappears.

![kapture 2018-09-25 at 15 49 30](https://user-images.githubusercontent.com/6624716/46018759-e90ac200-c0da-11e8-8976-6f1bf893b145.gif)

- No Error in python stacktraces
- Console Errors:

`TypeError: "t is undefined"
valuehttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/filter_box.52ca2a19348320543d3d.chunk.js:1:151430valuehttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/filter_box.52ca2a19348320543d3d.chunk.js:1:151326valuehttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/filter_box.52ca2a19348320543d3d.chunk.js:1:152701Qohttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:57803Xohttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:57647tihttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:60273Pihttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:74312Mihttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:74658fahttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:79326cahttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:78980yahttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:85217Onhttp://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:30398 vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:63271
ai
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:63271
di/n.callback
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:66681
oo
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:44937
ro
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:44741
pa
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:84172
fa
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:79364
ca
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:78980
ya
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:85217
On
http://dcall-41.prod.bi.lmc:8088/static/assets/dist/vendors-addSlice-dashboard-explore-profile-sqllab-welcome.991fc21747d02b49de6d.chunk.js:41:30398
`

### Steps to reproduce
- Build current version from master.
- Create new filter visualization
- Click on Time Range

**Comment by mistercrunch** [comment]
@betodealmeida I was able to reproduce, but on my side the Filter Box just turns blank on the latest master, nothing shows in the console.

**Comment by betodealmeida** [comment]
I can take a look.

**Comment by syazwan0913** [comment]
@mistercrunch How to fix the Filter Box turned blank when choosing time range?

**Comment by betodealmeida** [comment]
https://github.com/apache/incubator-superset/pull/6038/ fixes this, but it still need a bit more work. I'll finish it today.

**Comment by code-hipster** [comment]
my version is 0.28.1
change code:
incubator-superset/superset/assets/src/visualizations/FilterBox/FilterBox.jsx file
line number 184:
```
const choices = filtersChoices[key]; 
=> 
const choices = filtersChoices[key] || [];
```
line number 186:
```
selectedValues[key]
 =>
 (Array.isArray(selectedValues[key]) ? selectedValues[key] : [selectedValues[key]])
```
```
cd superset/assert
npm install
npm run build 
cd ../../
python setup.py install
superset runserver
```

**Comment by agabardo** [comment]
Anyone had any luck fixing this? So annoying.
