### ISSUE TITLE
Help Using Deck.gl - Polygon

### ISSUE THREAD

**Issue by pelayoarbues** [apache/incubator-superset#5976]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

We are trying to plot a cloropleth map using Deck.gl - Polygon in Superset. 

### Superset version
0.27.0

### Expected results
Cloropleth map plotting a numeric variable (VALUECOL in the example below).

### Actual results
No errors, no plot of polygons

### Steps to reproduce
We are trying to plot some data using Polygons. We have tried using both Polyline encoding (POLYLINE column) and JSON encoding (GEOJSON Column) but none of them seem to work, nor they throw any error. 

Besides passing Lines column and Lines encoding, how do we set VALUECOL as the data we want to plot?

Find a table with example data below:

|LOCATIONNAME|POLYLINE|GEOJSON|VALUECOL|
|------------|--------|------------|--------|
|Palomas|mp{uFnhcUiDZmBCmA[gBuAk@gAgFqRoCeKs@mB}@iBkAcBiAcA}HyFzG_P`GeNpB{IfD_QtAwExBoEZa@rBoBvDuBfH_AJbKDrJ@hFDd\Dtf@Zdg@{F`@|{"type":"Feature","properties":{"LOCATIONID":"0-EU-ES-28-07-001-079-16-001","LOCATIONNAME":"Palomas"},"geometry":{"type":"Polygon","coordinates":[[[-3.626482,40.4508],[-3.626626,40.45164],[-3.626607,40.452196],[-3.626465,40.452589],[-3.626035,40.453107],[-3.625674,40.45333],[-3.622549,40.454489],[-3.620595,40.455204],[-3.620043,40.455461],[-3.619513,40.455779],[-3.619014,40.456158],[-3.618672,40.456523],[-3.617425,40.458119],[-3.614706,40.456691],[-3.61228,40.455405],[-3.610539,40.454832],[-3.607656,40.453993],[-3.606572,40.45357],[-3.605536,40.452957],[-3.605367,40.452816],[-3.604804,40.45224],[-3.604218,40.451311],[-3.603894,40.449832],[-3.605833,40.449775],[-3.607698,40.449744],[-3.608866,40.449733],[-3.613533,40.449701],[-3.619886,40.449677],[-3.626318,40.449535],[-3.626482,40.4508]]]}}|4538.461538461538|
|Conde Orgaz-Piovera|ug{uFj_dUh@`Ll@lHrAbPC&#124;Hq@jKuCzZc@jE?~Fj@dG}XvReLrJgFjEMk@MsBO_GAsB?_BBcBFyMC_BUiRCo@qGsE}DeDuCkCi@g@yEkIyAgCq@mAi@sBUiBIcBBmRDiS?eCFy[@qIe@mAtK}ItBoCrE}InEcJpHjFjAbAhAdBz@bBv@tBvCbLzErQl@dAhBvAfAXtBDn@GpJu@\xV|{"type":"Feature","properties":{"LOCATIONID":"0-EU-ES-28-07-001-079-16-002","LOCATIONNAME":"Conde Orgaz-Piovera"},"geometry":{"type":"Polygon","coordinates":[[[-3.63014,40.449394],[-3.632231,40.44919],[-3.633741,40.448951],[-3.636482,40.448535],[-3.638075,40.448553],[-3.640057,40.448801],[-3.644518,40.449551],[-3.645532,40.44974],[-3.646818,40.449737],[-3.648121,40.449515],[-3.651289,40.453663],[-3.653143,40.455779],[-3.654163,40.45694],[-3.65395,40.457007],[-3.653369,40.457073],[-3.652083,40.457154],[-3.651504,40.457167],[-3.651027,40.457161],[-3.650526,40.457149],[-3.648153,40.457108],[-3.647678,40.45712],[-3.64458,40.457239],[-3.644346,40.457251],[-3.643285,40.458625],[-3.642459,40.459573],[-3.641759,40.460326],[-3.641555,40.460531],[-3.639893,40.461622],[-3.639216,40.462078],[-3.638829,40.46233],[-3.638242,40.462536],[-3.637711,40.462642],[-3.637215,40.462694],[-3.634108,40.462676],[-3.630856,40.462643],[-3.630181,40.462643],[-3.625576,40.462606],[-3.623886,40.462593],[-3.623494,40.462784],[-3.621747,40.460753],[-3.62102,40.460163],[-3.619273,40.459105],[-3.617495,40.458062],[-3.618679,40.45654],[-3.619018,40.456159],[-3.619525,40.455786],[-3.62002,40.455484],[-3.620615,40.455208],[-3.622712,40.454441],[-3.625693,40.453345],[-3.626046,40.453118],[-3.626485,40.452587],[-3.626612,40.452222],[-3.626645,40.451635],[-3.626601,40.451397],[-3.62633,40.449547],[-3.63014,40.449394]]]}}|4761.9047619047615|
|Canillas|yv&#124;uFpuhUoNbLcMnSeBvCcCwC_@g@k@[c@Eq@B[HOBOBS@S?q@NuF_H{@_Bq@wAk@eBo@qC]iC{AiVOsCy@{Ek@eDcDaRaDeRjAWHiADySrAm[MkBm@_Dj@mOf@gFVsBIyBzHqFfIyFpHmFlDsCd@lAA`FGt\?~DApHE`SA~IH`BThBf@tBx@vA~AjCpA&#124;BzB&#124;Dx@v@x@t@fAbAfElDj@`@~EjDBhBHbGJxHBhAE`GEhJ?fA?xAJlDF~BFnAPn@|{"type":"Feature","properties":{"LOCATIONID":"0-EU-ES-28-07-001-079-16-003","LOCATIONNAME":"Canillas"},"geometry":{"type":"Polygon","coordinates":[[[-3.65418,40.456939],[-3.656279,40.459412],[-3.659557,40.461671],[-3.660311,40.462181],[-3.659557,40.462845],[-3.659353,40.46301],[-3.659211,40.463229],[-3.659181,40.463409],[-3.659208,40.463659],[-3.659252,40.4638],[-3.659277,40.463877],[-3.659299,40.463951],[-3.659306,40.464058],[-3.659305,40.464157],[-3.659389,40.464404],[-3.657949,40.465632],[-3.657466,40.465936],[-3.657027,40.466181],[-3.656511,40.466404],[-3.655789,40.466649],[-3.655097,40.466797],[-3.651369,40.467252],[-3.65063,40.46734],[-3.649528,40.467623],[-3.648693,40.467845],[-3.64564,40.468666],[-3.642576,40.469477],[-3.642455,40.469097],[-3.642081,40.469049],[-3.638756,40.469011],[-3.634206,40.4686],[-3.633662,40.468661],[-3.632861,40.468898],[-3.630231,40.468674],[-3.629075,40.46847],[-3.6285,40.468357],[-3.62788,40.468402],[-3.626671,40.466821],[-3.625424,40.465182],[-3.62424,40.463657],[-3.623495,40.462786],[-3.623889,40.462596],[-3.625019,40.462605],[-3.629767,40.462643],[-3.630724,40.462644],[-3.63225,40.462659],[-3.635466,40.462687],[-3.63723,40.462696],[-3.637714,40.462647],[-3.638244,40.462537],[-3.63883,40.462333],[-3.639277,40.462043],[-3.639977,40.46157],[-3.640606,40.461157],[-3.641556,40.460534],[-3.641834,40.460247],[-3.64211,40.459951],[-3.642448,40.459592],[-3.643319,40.458592],[-3.643485,40.458374],[-3.644346,40.457254],[-3.644876,40.457232],[-3.646177,40.457181],[-3.647748,40.457121],[-3.648116,40.45711],[-3.649406,40.457131],[-3.651213,40.457169],[-3.651571,40.457168],[-3.652023,40.457162],[-3.652895,40.457106],[-3.653531,40.457064],[-3.65394,40.45702],[-3.65418,40.456939]]]}}|3024.6913580246915|

**Comment by mistercrunch** [comment]
The geo visualizations have been evolving quite a bit since 0.27.0 . Any way you can test against `master` ?

I know that a new release is overdue but we're working on improving the release process and trying to start conforming to Apache.

**Comment by pelayoarbues** [comment]
Thanks for your response. I will have to wait till amancevices's docker image catches up...

**Comment by songololo** [comment]
@mistercrunch were you able to display your data using `deckgl`? I'm also trying and failing and have no idea why it doesn't work.

**Comment by songololo** [comment]
@pelayoarbues were you able to display your data using `deckgl`? I'm also trying and failing and have no idea why it doesn't work.
