### ISSUE TITLE
Cratedb failed to add table in superset

### ISSUE THREAD

**Issue by javyxu** [apache/incubator-superset#5978]
Hi， This is an error caused by cratedb being used in superset. Please advise!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results

![image](https://user-images.githubusercontent.com/22185273/46070806-3e190780-c1b1-11e8-91ca-e557f207148c.png)

### Actual results

![image](https://user-images.githubusercontent.com/22185273/46070677-f6927b80-c1b0-11e8-94df-23bcff8278c7.png)

**Comment by javyxu** [comment]
hi，I found that simplejosn cannot convert set to json directly, but needs to convert json to list side first.

**Comment by hajdbo** [comment]
You can use Superset with CrateDB ( >=3.2) using its crate-python client.
Please note that if a source table contains timestamp columns, you would have to edit the table metadata and explicitly provide the datatime format for those columns.

See https://github.com/crate/crate-python/issues/307#issuecomment-477524259

**Comment by hajdbo** [comment]
@kristw please close: op closed the upstream crate issue.
