### ISSUE TITLE
WTF_CSRF_EXEMPT_LIST doesn't work

### ISSUE THREAD

**Issue by BrayanArrieta** [apache/incubator-superset#5981]
Hello I have last version of superset, and I need to add an exception for CSRF.  I tried with 
```
WTF_CSRF_EXEMPT_LIST = ['http://localhost:8088/login'], 
```
but doesn't work. Thanks for all.

**Comment by BrayanArrieta** [comment]
Please I need help for this, need that for a work. I just need and example or explain

**Comment by mistercrunch** [comment]
I think it's supposed to look more like `WTF_CSRF_EXEMPT_LIST = ['superset.views.core.sql_json']`.

**Comment by BrayanArrieta** [comment]
Hello thanks for the help, I tried with `WTF_CSRF_EXEMPT_LIST = ['login']` and doesn't work. Maybe you have another idea.

**Comment by kevinflaherty1** [comment]
> Hello thanks for the help, I tried with `WTF_CSRF_EXEMPT_LIST = ['login']` and doesn't work. Maybe you have another idea.

Any luck on this? Having the same issue.

**Comment by kevinflaherty1** [comment]
Realized it was the directory path to the file that was needed so in my case I had a customer_security_manager.py file alongside my superset_config.py and `WTF_CSRF_EXEMPT_LIST = ['custom_security_manager.login']` worked.
