### ISSUE TITLE
+1 to addition of Elasticsearch support.

### ISSUE THREAD

**Issue by Tipiaceraisempre** [apache/incubator-superset#5984]
_Originally posted by @rahulgagrani in https://github.com/apache/incubator-superset/issues/241#issuecomment-213809253_

**Comment by arpit-agarwal** [comment]
@Tipiaceraisempre this PR has basic ES support #5358 

We have merged this to the fork https://github.com/Guavus/incubator-superset/

We will be adding full ES  in next couple of month and propose a new PR here.

**Comment by ssozonoff** [comment]
Was wondering how this effort is going ?

**Comment by woniuxia** [comment]
I also want this feature.
Thanks to the developer.

**Comment by haiboself** [comment]
Does this implementation support access elastic-search through http proxy which provide authority control by add specific http heads?

**Comment by pbuxtonccuk** [comment]
Any update on support for ElasticSearch?

**Comment by mohadelrezk** [comment]
+1 for elasticsearch connectivity 
would you also consider sparql endpoints ?

**Comment by dbrambilla** [comment]
+1
Any update?

**Comment by raviorteja** [comment]
+1, any update on the ES support for supersets?

**Comment by swizzley** [comment]
+1

**Comment by pducic** [comment]
+1

**Comment by noelalonso** [comment]
+1

**Comment by kaykumar** [comment]
+1

**Comment by zmhassan** [comment]
So Superset can connect to Presto:
https://superset.incubator.apache.org/installation.html#database-dependencies
 
Presto | pip install pyhive | presto://
-- | -- | --

 And presto can connect to elasticsearch through a plugin/connector see:
 https://prestodb.github.io/docs/current/connector/elasticsearch.html

Has anyone tried using this setup for superset ?

ElasticSearch -> Presto -> Superset ?

**Comment by mistercrunch** [comment]
This works now, we have a blog post coming up on the topic.

**Comment by mistercrunch** [comment]
Here https://preset.io/blog/2019-12-16-elasticsearch-in-superset/, thanks @dpgaspar for the work and blog post!
