### ISSUE TITLE
renaming tables in superset

### ISSUE THREAD

**Issue by rageshpillai** [apache/incubator-superset#5989]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25

### Expected results
Should rename all the table name of superset

### Steps to reproduce
In our project we are planning to integrate superset, we are using oracle as backend. 
Functionality everything working as expected. we are following a naming convention to create tables in our db. Is there any way to rename all the table name to "App_name_table name" without braking the code base

**Comment by BrayanArrieta** [comment]
I think that it's a great idea, allow automation to superset
