### ISSUE TITLE
config.py reload

### ISSUE THREAD

**Issue by alvaropc** [apache/incubator-superset#5990]
### Superset version
0.25.6

### Expected results
Config changes do something

### Actual results

Config changes do nothing

### Steps to reproduce
Change SUPERSET_WEBSERVER_TIMEOUT  in config.py and also add it to superset_config.py but the query timeout keeps the same in 60 seconds.

Hi, I am a really begginer using superset and although I have some cool dashboards and users roles created, I am not being able to change the query timeout of superset.
I read already some github issues talking about changing the SUPERSET_WEBSERVER_TIMEOUT   flag in superset_config.py. I did it and even changed the original config.py, but the query timeout does not change at all, so I am wondering if maybe I have to make superset reload the config somehow or...
How can I make it works?

Thank you so much in advance.

**Comment by CoryChaplin** [comment]
Looks like this is related to this issue : https://github.com/apache/incubator-superset/issues/5993

**Comment by MaheshYadavalli** [comment]
+1 on this issue
