### ISSUE TITLE
path is not a directory on windows build

### ISSUE THREAD

**Issue by ThunderboltSmile** [apache/incubator-superset#5999]
https://github.com/apache/incubator-superset/blob/4868c00d6dff3c6a1f790a0da0abe854005498c1/setup.py#L15

Could change this path to where the file located not just symlink ?

**Comment by shwetanshu21** [comment]
Are you having an issue with paths while building on Windows? It is not clear. If yes, then use the following link to fix the character limit of windows on Windows 10/2016.

https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by JohnForYang** [comment]
i delete the 'static' since its only a link to assets folder
