### ISSUE TITLE
npm run prod ERROR - 0.28.0rc6

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#6010]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.0rc6

### Expected results
to generate optimized css and js for production

### Actual results
```
 superset@0.28.0-rc6 prod /root/incubator-superset/superset/assets
> node --max_old_space_size=4096 webpack --mode=production --colors --progress

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/incubator-superset/superset/assets/webpack'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.28.0-rc6 prod: `node --max_old_space_size=4096 webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.28.0-rc6 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T15_52_52_501Z-debug.log
(venv) root@ubuntu-dev-only:~/incubator-superset/superset/assets# 
```
### Steps to reproduce
- I tried with node@6, node@8, and latest node and still no luck.
- I tried on mac and also ubuntu and still same error
- `npm run dev` works fine

**Comment by aboganas** [comment]
Yes `npm run build` works fine, only troubles with `npm run prod` 
is there any difference?

**Comment by kristw** [comment]
I believe you can use `npm run build` instead of `npm run prod`. 
cc: @mistercrunch

**Comment by mistercrunch** [comment]
Yup I think we should deprecate `npm run prod`
