### ISSUE TITLE
Redshift: Cannot add tables any longer after multiple upgrades

### ISSUE THREAD

**Issue by kingo55** [apache/incubator-superset#6012]
Make sure these boxes are checked before submitting your issue - thank you!

- [ y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ y ] I have reproduced the issue with at least the latest released version of superset
- [ y ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.27.0 (Amancevice's Docker)

### Expected results

Tables should be added when Superset has access to them via the Redshift user.

### Actual results

All access to Redshift data works (including SQL Lab queries on all objects, dashboards based on Redshift data) except when we try to add tables.

### Steps to reproduce

We add a new table via the interface:

<img width="1191" alt="screen shot 2018-10-01 at 9 38 49 am" src="https://user-images.githubusercontent.com/2361388/46264256-f05c2080-c55d-11e8-9898-b36ea19c3ff6.png">

Then it throws the following error:

<img width="1190" alt="screen shot 2018-10-01 at 9 21 30 am" src="https://user-images.githubusercontent.com/2361388/46264260-feaa3c80-c55d-11e8-88d6-441e74ce41ed.png">

Nothing bad shows up in the logs and there is no stack trace available. We just see:

```
2018-09-30 23:44:37,418:INFO:root:Database.get_sqla_engine(). Masked URL: redshift+psycopg2://mojito_reports:XXXXXXXXXX@REDACTED.ap-southeast-2.redshift.amazonaws.com:5432/snowplow
```

However we are able to query the exact same object in SQL Lab, just fine:

<img width="1662" alt="screen shot 2018-10-01 at 9 24 01 am" src="https://user-images.githubusercontent.com/2361388/46264276-239eaf80-c55e-11e8-9692-45fc173f30e9.png">

And adding the table through SQL Lab also works. The issue showed up around 0.23.x (?) and I have continued upgrading ever since, hoping that the issue may have been addressed.

**Comment by mistercrunch** [comment]
We use Redshift at Lyft, and our URI looks something like `postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}`. Can you try something like it? 

I know the docs say to go `redshift+psycopg2://`, and I'm unclear why we're deviating from that, trying to help...

**Comment by kingo55** [comment]
@mistercrunch - that fixed it! Thanks for the tip...

Sounds like an issue that needs to be fixed in the Redshift driver.
