### ISSUE TITLE
 How to fix the Filter Box turned blank when choosing time range?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#6021]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
filter box working

### Actual results
filter box blank after click time range

**Comment by revathijay** [comment]
We are also facing the same issue. Has anyone found a fix for it

**Comment by syazwan0913** [comment]
#6038 there is already fix for that problem
