### ISSUE TITLE
Using API to update dashboard position

### ISSUE THREAD

**Issue by wangshihan513** [apache/incubator-superset#6025]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27

### Expected results
The charts in the dashboard change position

### Steps to reproduce
I would like to use API to update the dashboard position by using position_json. After study existed dashboard information, I realized position_json looks like this:
{
"DASHBOARD_CHART_TYPE-B1fC9gGYFX": {
"children": [],
"id": "DASHBOARD_CHART_TYPE-B1fC9gGYFX",
"meta": {
"chartId": 
"height": 
"sliceName": 
"width": 
},
"type": "DASHBOARD_CHART_TYPE"
},
"DASHBOARD_CHART_TYPE-B1ulR5gfFKX": {
"children": [],
"id": "DASHBOARD_CHART_TYPE-B1ulR5gfFKX",
"meta": {
"chartId": 
"height": 
"sliceName": 
"width": 
},
"type": "DASHBOARD_CHART_TYPE"
}
"DASHBOARD_GRID_ID": {
"children": [
"DASHBOARD_ROW_TYPE-H1G0xGFKQ",
"DASHBOARD_ROW_TYPE-H1yeR5eMKYm"
],
"id": "DASHBOARD_GRID_ID",
"type": "DASHBOARD_GRID_TYPE"
},
"DASHBOARD_HEADER_ID": {
"id": "DASHBOARD_HEADER_ID",
"meta": {
"text": 
},
"type": "DASHBOARD_HEADER_TYPE"
},
"DASHBOARD_ROW_TYPE-H1G0xGFKQ": {
"children": [
"DASHBOARD_CHART_TYPE-B1fC9gGYFX"
],
"id": "DASHBOARD_ROW_TYPE-H1G0xGFKQ",
"meta": {
"background": "BACKGROUND_TRANSPARENT"
},
"type": "DASHBOARD_ROW_TYPE"
},
"DASHBOARD_ROW_TYPE-H1yeR5eMKYm": {
"children": [
"DASHBOARD_CHART_TYPE-B1ulR5gfFKX"
],
"id": "DASHBOARD_ROW_TYPE-H1yeR5eMKYm",
"meta": {
"background": "BACKGROUND_TRANSPARENT"
},
"type": "DASHBOARD_ROW_TYPE"
},
"DASHBOARD_VERSION_KEY": "v2"
}

I am able to find chart_Id, slice_name and define height, width, however, I have no idea how can I find id for "DASHBOARD_ROW_TYPE-H1yeR5eMKYm" and so on via API?

**Comment by Praytic** [comment]
I also have the same question, how to manipulate chart positions in a dashboard?

**Comment by jgliwa** [comment]
Still an issue for me

**Comment by russellsch** [comment]
Same

**Comment by LucasKlemke** [comment]
same
