### ISSUE TITLE
Custom CSS not applied when user has no permissions to save dashboard

### ISSUE THREAD

**Issue by astudnev** [apache/incubator-superset#6026]
### Superset version

superset (0.27.0)

### Expected results

Custom CSS applied to dashboard in any case

### Actual results

It is not applied when user has no permission to save

### Steps to reproduce

1) create Public role with ability to view dashboards, but not modify them
2) create dashboard
3) add css to it - css applied
4) logout
5) load dashboard - css not applied

IMHO this happens because custom CSS is inserted by Javascript in HeaderActionsDropdown which is not rendered when user has no this permission

**Comment by rbayliss** [comment]
It looks like this issue has been fixed in 0.28 - https://github.com/apache/incubator-superset/blob/0.28/superset/assets/src/dashboard/components/Header.jsx
