### ISSUE TITLE
Sort By option is not applied for stacked Time Series chart

### ISSUE THREAD

**Issue by astudnev** [apache/incubator-superset#6052]
Make sure these boxes are checked before submitting your issue - thank you!

### Superset version

superset (0.27.0)

### Expected results

Order of series change when i configure options "Sort By" and "Sort Descending"

### Actual results

It orders ONLY by the metrics defined

### Steps to reproduce

1) create Time series - Stacked graph
2) Change option "Sort By" that should change the order of series in the stack

**Comment by hajdbo** [comment]
I suspect this is a duplicate of #2442
