### ISSUE TITLE
Metrics are not properly added in My Metric

### ISSUE THREAD

**Issue by astudnev** [apache/incubator-superset#6057]
Make sure these boxes are checked before submitting your issue - thank you!
### Superset version

superset (0.27.0)

### Expected results

I add a metric and it is appended to query and displayed on graph

### Actual results

Instead, it adds ONLY count() with different names 

In query it looks as

```
SELECT toStartOfDay(toDateTime(tx_time)) AS __timestamp,
       count() AS "COUNT_DISTINCT(tx_hash)",
```

instead of

```
SELECT toStartOfDay(toDateTime(tx_time)) AS __timestamp,
       COUNT_DISTINCT(tx_hash) AS my_metric_XXX,
```

### Steps to reproduce

Add a metric to a time series graph as shown on picture attached

<img width="595" alt="mymetri" src="https://user-images.githubusercontent.com/1385046/46603771-cde97a80-cafc-11e8-8221-2d77953e971c.png">

**Comment by trivita** [comment]
this happened to me too. superset 1.0

**Comment by rusackas** [comment]
It was closed due to the bot. It can certainly be re-opened if it's an issue. I just tried it on 1.0 and I'm not seeing the issue as described (unless I'm missing something).


https://user-images.githubusercontent.com/812905/105958065-f92a6780-602e-11eb-9355-e521ce7d07b6.mp4

**Comment by trivita** [comment]
![Snipaste_2021-01-27_15-52-34](https://user-images.githubusercontent.com/1425147/105960088-b496de80-60b7-11eb-813c-c940f50ac6be.png)
![Snipaste_2021-01-27_15-51-13](https://user-images.githubusercontent.com/1425147/105960095-b6f93880-60b7-11eb-8897-705026e460c3.png)
![Snipaste_2021-01-27_15-51-00](https://user-images.githubusercontent.com/1425147/105960103-b8c2fc00-60b7-11eb-886d-a8d316deaed0.png)
this is what happened to me
