### ISSUE TITLE
Cannot install superset on empty Centos7

### ISSUE THREAD

**Issue by funes79** [apache/incubator-superset#6060]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest
### Environment
(venv) [centos@ip-10-85-150-47 ~]$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
(venv) [centos@ip-10-85-150-47 ~]$ pip -V
pip 18.1 from /home/centos/venv/lib/python2.7/site-packages/pip (python 2.7)

### Expected results
Fabmanager create admin should create the admin user

### Actual results
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
/home/centos/venv/lib/python2.7/site-packages/superset/security.py:12: FSADeprecationWarning: "_BoundDeclarativeMeta" has been renamed to "DefaultMeta". The old name will be removed in 3.0.
  from flask_appbuilder.security.sqla import models as ab_models
Was unable to import superset Error: make_declarative_base() takes at most 2 arguments (3 given)

### Steps to reproduce
Following the tutorial https://superset.incubator.apache.org/installation.html creating virtual env, installing setuptools then installing superset (which contains one warning: pip install superset
flask-appbuilder 1.10.0 has requirement Flask-SQLAlchemy==2.1, but you'll have flask-sqlalchemy 2.3.2 which is incompatible. )

**Comment by robokaso** [comment]
I retried the installation on ubuntu 18.04 today and fortunately the error is gone:
```
# apt install build-essential libssl-dev libffi-dev python3.6-dev python3-pip libsasl2-dev libldap2-dev python3-setuptools python3-wheel
# pip3 install superset
# fabmanager create-admin --app superset                                                                        
Username [admin]:                                                                                                 
User first name [admin]:                                                                                   
User last name [user]:                                                                                     
Email [admin@fab.org]:                                                                                     
Password:                                                                                                                         
Repeat for confirmation:                                                                                   
Recognized Database Authentications.                                                                                                                                                                              
Admin User admin created.        
```
