### ISSUE TITLE
Config save to S3

### ISSUE THREAD

**Issue by hakangurel** [apache/incubator-superset#6080]
Hi,

Is it possible or is there a plan for saving the config&dashboards (current state) of superset on S3, like Zeppelin can: [https://zeppelin.apache.org/docs/0.8.0/setup/storage/storage.html#notebook-storage-in-s3](url)?
My motivation is keeping the image on kubernetes as basic as possible and keep state elsewhere on cloud.

### Superset version
0.27.0

### Expected results
Configs are saved on s3.

### Actual results
Configs can be exported as YAML.

### Steps to reproduce
N/A

**Comment by mistercrunch** [comment]
Backup your metadata database and put the backup file on s3?

**Comment by Confman** [comment]
Is there a documentation/recommendation about the best practice of exporting and importing config/dashboards/etc (current state actually)?

I can see some scripts in the images such as: dashboard_import_export_util.py, import_util.py, superset_config.py but it would be great if someone can guide me through.

Thanks a lot...
