### ISSUE TITLE
What is plan of tree category of dashboards

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#6081]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
all of them

### Expected results
The dashboards should be categorized like file system. When there are tons of dashboards, it's so hard to find the dashboards I need.

**Comment by baocaiwang** [comment]
I'm waiting for this function, too

**Comment by yamyamyuo** [comment]
I prefer the idea of TAGS https://github.com/apache/incubator-superset/issues/3821
