### ISSUE TITLE
when dose the 0.28  stable version release?

### ISSUE THREAD

**Issue by XuanmoFeng** [apache/incubator-superset#6082]

**Comment by hajdbo** [comment]
0.28 has been released, please close this issue.

**Comment by mistercrunch** [comment]
For the record we're in a tough place around releases, both Airbnb and Lyft are on forks currently, and 0.27.x started failing, so I just shipped a rough 0.28.0, and fixed big issues in 0.28.1, but 0.28.1 is far from perfect.

Airbnb and Lyft will start working together on a steady release process that should improve things a lot. It should improve the quality and frequency of releases, as well as the general state of `master`.

More about it here: https://github.com/apache/incubator-superset/issues/6131
