### ISSUE TITLE
Cache per user

### ISSUE THREAD

**Issue by us3r** [apache/incubator-superset#6092]
My users should see only their own data. I have added the table that corresponded to whole data. In the definition I have defined the view like:

`select * from data where user = {{ current_username() }}`

The result is ok. Unfortunately if users will try open cached dashboard associated with that table there is a chance that previously cached dashboard is created by different user.

Could someone share some ideas? Maybe my idea was wrong and I should use different way too achive the same result. Or maybe I should do sth with cached key?

**Comment by mistercrunch** [comment]
For now you may just have to turn off caching for that chart. I think setting a cache_timeout of `0` means "forever", so you probably want to set a very small value like "1". I'm not sure if negative value will effectively set the caching to not happen. 

On the longer run, I'm not sure how to handle this as we cannot just make a cache key based on the rendered SQL query. The only reason we cannot do this (that I can think of right now) is that relative time filters like "90 days ago" get transformed into real values, and what we want the cache key to be based on is "90 days ago", not a hard value. If it's only that, we **could** perhaps pass dummy values to the time filter and cache that along with the relative time inputs, but that assumes that the query generation is a deterministic process, which seems like a brittle/dangerous assumption.

**Comment by rtjarvis** [comment]
Did this ever get solved? I’d like to do the same.

**Comment by villebro** [comment]
Please check `cache_key_wrapper`: https://superset.apache.org/sqllab.html#superset.jinja_context.CacheKeyWrapper.cache_key_wrapper
