### ISSUE TITLE
How to get it installed somehow?

### ISSUE THREAD

**Issue by dizzydes** [apache/incubator-superset#6098]
I've tried the latest version on Heroku one-click install, Docker image, and native install on Ubuntu with a potpourri of errors, mostly related to requirements and package management clashes. 

Anyone have it working/demo instance I can somehow clone? Is there any other way for me to install? Even an older version, back when it was working...

**Comment by mistercrunch** [comment]
http://superset.apache.org/installation.html

**Comment by dizzydes** [comment]
This doesn't work this is what I tried.
Both the native and the docker install listed in that link.


Try the latest version yourself and see there are even Issues in this repo
related to it.

**Comment by dizzydes** [comment]
https://github.com/apache/incubator-superset/issues/5958 
Markdown comment from here should be added to readme or the linked site - this fixes the error. Without reading this no one can install Superset natively right now...
