### ISSUE TITLE
Dashboard conditional filter on numbers (group by)

### ISSUE THREAD

**Issue by dizzydes** [apache/incubator-superset#6099]
I know I can filter by string GROUP BYs and DATES using a filter box, is there any way, for example when viewing a table viz on a dashboard, to shortlist the rows in the table viz with a number test (e.g. "revenue > 50")? 

Thanks

**Comment by rumbin** [comment]
Still a good point imho

**Comment by vnktsh** [comment]
This is a very good feature. Solves lots of use-cases. Is this in development?

**Comment by avicenteg** [comment]
I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties. 
I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart. 
The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses... 
If someone have an idea of how to do it, I'll love discuss it.

**Comment by sedhha** [comment]
Any solutions which are up for this?

**Comment by amirsani** [comment]
Is there any effort on this?

**Comment by jsalvatore** [comment]
@aleksarias, can you fix this?

**Comment by aleksarias** [comment]
> @aleksarias, can you fix this?

I'm not good at javascript

**Comment by jsalvatore** [comment]
> I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties.
> I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart.
> The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses...
> If someone have an idea of how to do it, I'll love discuss it.

I'm happy to discuss this - we may be able to help.

**Comment by avicenteg** [comment]
> > I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties.
> > I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart.
> > The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses...
> > If someone have an idea of how to do it, I'll love discuss it.
> 
> I'm happy to discuss this - we may be able to help.

Hello @jsalvatore. 

I finally found a solution for it. I attach some screenshots. Although I haven't done any PR because I think that it is an sloppy solution but useful.
First, I added a section in the filter box chart:
![image](https://user-images.githubusercontent.com/64475023/96833242-63d07380-1440-11eb-9674-2bc285ef9685.png)
![image](https://user-images.githubusercontent.com/64475023/96833277-721e8f80-1440-11eb-9829-c6deb5ec64a1.png)
After fill this form you'll have something like this.
![image](https://user-images.githubusercontent.com/64475023/96833363-967a6c00-1440-11eb-98ba-8019ac3d6416.png)

This filter will add a "having" clause in the SQL query of the chart that it is affecting. 

I'm not sure how to share every change that have been done to get this, but if you or anyone is interested in know it, you can contact me and I'll try to find a way to share it (I prefer not upload the complete repo to github, for now).

**Comment by jsalvatore** [comment]
> > > I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties.
> > > I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart.
> > > The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses...
> > > If someone have an idea of how to do it, I'll love discuss it.
> > 
> > 
> > I'm happy to discuss this - we may be able to help.
> 
> Hello @jsalvatore.
> 
> I finally found a solution for it. I attach some screenshots. Although I haven't done any PR because I think that it is an sloppy solution but useful.
> First, I added a section in the filter box chart:
> ![image](https://user-images.githubusercontent.com/64475023/96833242-63d07380-1440-11eb-9674-2bc285ef9685.png)
> ![image](https://user-images.githubusercontent.com/64475023/96833277-721e8f80-1440-11eb-9829-c6deb5ec64a1.png)
> After fill this form you'll have something like this.
> ![image](https://user-images.githubusercontent.com/64475023/96833363-967a6c00-1440-11eb-98ba-8019ac3d6416.png)
> 
> This filter will add a "having" clause in the SQL query of the chart that it is affecting.
> 
> I'm not sure how to share every change that have been done to get this, but if you or anyone is interested in know it, you can contact me and I'll try to find a way to share it (I prefer not upload the complete repo to github, for now).

Hello @avicenteg, that would be really helpful, can you email me any relevant code so I can attempt update my version of superset? My email is joe@jsalvatore.com. Looking forward to chatting.

**Comment by tinversenorm** [comment]
@avicenteg Could you try contributing that change to superset? I think it would be really useful.

**Comment by junlincc** [comment]
range filter is available in dashboard native filter behind a feature flag, if that's what you guys are asking? @tinversenorm

**Comment by chaimch** [comment]
> > > I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties.
> > > I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart.
> > > The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses...
> > > If someone have an idea of how to do it, I'll love discuss it.
> > 
> > 
> > I'm happy to discuss this - we may be able to help.
> 
> Hello @jsalvatore.
> 
> I finally found a solution for it. I attach some screenshots. Although I haven't done any PR because I think that it is an sloppy solution but useful.
> First, I added a section in the filter box chart:
> ![image](https://user-images.githubusercontent.com/64475023/96833242-63d07380-1440-11eb-9674-2bc285ef9685.png)
> ![image](https://user-images.githubusercontent.com/64475023/96833277-721e8f80-1440-11eb-9829-c6deb5ec64a1.png)
> After fill this form you'll have something like this.
> ![image](https://user-images.githubusercontent.com/64475023/96833363-967a6c00-1440-11eb-98ba-8019ac3d6416.png)
> 
> This filter will add a "having" clause in the SQL query of the chart that it is affecting.
> 
> I'm not sure how to share every change that have been done to get this, but if you or anyone is interested in know it, you can contact me and I'll try to find a way to share it (I prefer not upload the complete repo to github, for now).

Hello @avicenteg, that would be really helpful, can you show zhe  whole steps? My email is mingch94@gmail.com. Looking forward to chatting.

**Comment by dataavader** [comment]
Surprised this isn't already implemented. Pretty fundamental for a filter on analytics datasets to be able to filter properly on floats without resorting to workarounds. Appreciate the effort getting this implemented, hopefully will be soon.

**Comment by adarbha** [comment]
I would highly appreciate any work on this. Thanks in advance!

**Comment by vamruta** [comment]
> > > I also think that it will be a great feature, I'm trying to develop it by my own, but I'm finding some difficulties.
> > > I think that a good shortcut to implement it is use the adhoc filter section of the ControlPanel as a chart.
> > > The problem of having this kind of filters is that they affect to the query below the charts, adding new "groupbys" and having clauses...
> > > If someone have an idea of how to do it, I'll love discuss it.
> > 
> > 
> > I'm happy to discuss this - we may be able to help.
> 
> Hello @jsalvatore.
> 
> I finally found a solution for it. I attach some screenshots. Although I haven't done any PR because I think that it is an sloppy solution but useful. First, I added a section in the filter box chart: ![image](https://user-images.githubusercontent.com/64475023/96833242-63d07380-1440-11eb-9674-2bc285ef9685.png) ![image](https://user-images.githubusercontent.com/64475023/96833277-721e8f80-1440-11eb-9829-c6deb5ec64a1.png) After fill this form you'll have something like this. ![image](https://user-images.githubusercontent.com/64475023/96833363-967a6c00-1440-11eb-98ba-8019ac3d6416.png)
> 
> This filter will add a "having" clause in the SQL query of the chart that it is affecting.
> 
> I'm not sure how to share every change that have been done to get this, but if you or anyone is interested in know it, you can contact me and I'll try to find a way to share it (I prefer not upload the complete repo to github, for now).

Hi  @avicenteg,  I highly apprecitate your work. So usefull. Can you please show me how to use ? My email is amrutavishwakarma58@gmail.com
