### ISSUE TITLE
How to add Highcharts to apache superset?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#6108]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

Can someone give tutorial on how to add Highcharts to superset?

**Comment by mistercrunch** [comment]
Highcharts has a not-so-permissive license and can't be bundled with Apache Superset. Much work has been done and is still ongoing around allowing new chart types as plugins though, so you could make a Highcharts plugin once that's ready.

**Comment by syazwan0913** [comment]
So for now there is now way to add Highcharts into Apache Superset?
