### ISSUE TITLE
How to turn off download/export to CSV permission?

### ISSUE THREAD

**Issue by dizzydes** [apache/incubator-superset#6110]
I created a user with Gamma permissions - is there a way to turn off the download permission both in Explore and Dashboard? 

I see _can_download_ is a base permission but then I see other more granular download permissions attached to the user.

**Comment by mistercrunch** [comment]
`can_csv` but I'm not sure if the UI will disable the button, but the csv download will fail.

**Comment by dizzydes** [comment]
Fantastic - thanks Maxime.

**Comment by mistercrunch** [comment]
Closing - reopen if it doesn't disable the button as expected
