### ISSUE TITLE
bootstrap.min.css and jquery-latest.js not found

### ISSUE THREAD

**Issue by jloeaaw** [apache/incubator-superset#6119]
### Superset version
latest just did --upgrade

### Expected results
superset running

### Actual results
when i go to the Tables - List Column Pane, javascript text  instead of html

firefox says that 2 files were not found: 

Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: http://0.0.0.0:8088/static/appbuilder/css/bootstrap.min.css
Source-Map-Adresse: bootstrap.min.css.map[Weitere Informationen]
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: http://0.0.0.0:8088/static/appbuilder/js/jquery-latest.js
Source-Map-Adresse: jquery-1.10.2.min.map[Weitere Informationen]

howerver, they are in the list of downloaded files so firefox debugger. what can it be?

<img width="1272" alt="bildschirmfoto 2018-10-16 um 15 45 54" src="https://user-images.githubusercontent.com/44201975/47021149-2ce16c00-d15b-11e8-9871-393a1fd193fc.png">
 is displayed

**Comment by localdrive** [comment]
same issue here.

**Comment by mistercrunch** [comment]
https://github.com/dpgaspar/Flask-AppBuilder/pull/828
