### ISSUE TITLE
Some toggle values in slice url don't consist with those in database

### ISSUE THREAD

**Issue by yxjames** [apache/incubator-superset#612]
I found that sometimes the toggle values in slice url are not consistent with the UI and the value stored in database.

**Comment by jgoad** [comment]
Seconded. This has occurred when I change a column name in the database.

**Comment by yxjames** [comment]
I'm afraid we are not talking about the same thing. Actually I'm talking about the url used to generate cache key. Sorry I was not clear about this issue.

**Comment by mistercrunch** [comment]
I'm not sure if I understand, can you give a more concrete example?

**Comment by yxjames** [comment]
I realized that the actual problem is that in views.py when a viz object is created to get data, sometimes a wrong toggle value will be added to the request.args. For example I have a pie chart slice. The params in db looks like this:
<img width="255" alt="screen shot 2016-06-13 at 9 51 21 pm" src="https://cloud.githubusercontent.com/assets/10016038/16031617/ecab2040-31b1-11e6-9fb5-42e76eb7aacd.png">
I print the MultiDict used to generate cache_key, and it contains two "show_legend" values. I don't know where does the 'false' value come from.
<img width="1393" alt="screen shot 2016-06-13 at 9 51 51 pm" src="https://cloud.githubusercontent.com/assets/10016038/16031636/2fd10d30-31b2-11e6-8371-deefd0da487b.png">
My print statement looks like this:
<img width="367" alt="screen shot 2016-06-13 at 9 52 02 pm" src="https://cloud.githubusercontent.com/assets/10016038/16031640/3de0bc40-31b2-11e6-92b8-b0d2331a056d.png">
