### ISSUE TITLE
Data not loading in List Columns

### ISSUE THREAD

**Issue by lahorekid** [apache/incubator-superset#6128]
### Superset version
Python 3.7.0

### Expected results
Downloaded data like World Bank dashboard is installed in Superset.
![capture](https://user-images.githubusercontent.com/20125058/47090416-51f9db80-d23c-11e8-9f9d-124dff55d9ce.PNG)

### Actual results
But data is not showing
![capture1](https://user-images.githubusercontent.com/20125058/47090431-5c1bda00-d23c-11e8-96bd-e304061927f5.PNG)

Kindly help!

**Comment by prio** [comment]
I am getting the same. Tested with Python 3.6 & 3.7. Have tried the latest git checkout , pip install version and unoffical docker image. Have also tried across three browsers: Brave, Firefox & Chrome.

**Comment by mistercrunch** [comment]
It's a problem in FAB `0.12.0` https://github.com/dpgaspar/Flask-AppBuilder/pull/828

**Comment by lahorekid** [comment]
> 
> 
> It's a problem in FAB `0.12.0` [dpgaspar/Flask-AppBuilder#828](https://github.com/dpgaspar/Flask-AppBuilder/pull/828)
> 
> Workarounds include patching FAB in your environment, using the new table editor from the explore view, or downgrading back to the previous version of Superset

downloaded flask, HTML still persists.

**Comment by prio** [comment]
@lahorekid modify the flask app builder version in setup.py 

>         'flask-appbuilder==1.12.1',

and rebuild. It will work then.

**Comment by lahorekid** [comment]
> 
> 
> @lahorekid modify the flask app builder version in setup.py
> 
> > ```
> >     'flask-appbuilder==1.12.1',
> > ```
> 
> and rebuild. It will work then.

upgrading to 1.12.1 has resolved issue thanks @prio

**Comment by lahorekid** [comment]
> 
> 
> @lahorekid modify the flask app builder version in setup.py
> 
> > ```
> >     'flask-appbuilder==1.12.1',
> > ```
> 
> and rebuild. It will work then.

upgrading to 1.12.1 has resolved issue thanks @prio

**Comment by lahorekid** [comment]
resolved
