### ISSUE TITLE
"No data" error message not getting displayed

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6152]
No error message shows up for "No data" error (likely for other errors as well but this is the one I tested). Instead the chart is blank.

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

![image](https://user-images.githubusercontent.com/817955/47241495-bafa6400-d3a0-11e8-997e-65f2c8f18756.png)

### Superset version
master

### Expected results
Error message shows up

### Actual results
No error message

### Steps to reproduce
Go to birth names slice
Filter by a name that doesn't exist in the datasource
Run query returns a blank chart with no error message

**Comment by TianyangLi** [comment]
i'm also experiencing this issue when i test the latest version (0.28.1).
