### ISSUE TITLE
Recent Refactor of db_engine_specs.py causes KeyError again on Redshift sources.

### ISSUE THREAD

**Issue by wyndhblb** [apache/incubator-superset#6162]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.28.1 (and a71e6eb0a32409f0ae9f810da20a461c52f8b09e)

### Expected results

SUM(column_name) -> sum(column_name) for redshift

### Actual results

SUM(column_name) -> SUM(column_name) for redshift

### Steps to reproduce

Any Vis using a redshift data source and a SUM/AVG/MAX/etc aggregate for values.

```
Traceback (most recent call last):
  File "/data/superset/superset/views/core.py", line 1153, in generate_json
    payload = viz_obj.get_payload()
  File "/data/superset/superset/viz.py", line 373, in get_payload
    payload['data'] = self.get_data(df)
  File "/data/superset/superset/viz.py", line 1214, in get_data
    df = self.process_data(df)
  File "/data/superset/superset/viz.py", line 1134, in process_data
    values=self.metric_labels)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 5303, in pivot_table
    margins_name=margins_name)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/pivot.py", line 61, in pivot_table
    raise KeyError(i)
KeyError: 'SUM(num_chats)'
```

Seems the fix in #5337 got recently removed by a165aec#diff-6519edc75f2440a575cb22492f401100 (#5467) due to a refactor, however, the logic to push these string column changes back to "viz.py" is now different and re-stating the "normalize_column_name" change

**Comment by slotrans** [comment]
I'm experiencing this too. It makes Redshift completely unusable since no aggregate expression ever works.

**Comment by totogo** [comment]
I got this issue in ```0.29.0rc7```
