### ISSUE TITLE
Filter option in explore chart is not working for Redshift Database Table

### ISSUE THREAD

**Issue by krishna9626** [apache/incubator-superset#6173]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.24.0

### Expected results
column values get fetched for the Filter Select drop-downs in explore view.

### Actual results
![superset](https://user-images.githubusercontent.com/36255856/47430837-1751ef00-d7b8-11e8-8c22-f5a647c9a633.png)

### Steps to reproduce
Enable Filter
explore the table and select any one of the columns for filtering

The Filter works on mysql ,mssql table but it does'nt work on the Redshift table

Thanks

**Comment by mistercrunch** [comment]
A stacktrace, ideally against a more recent version, would help here.
