### ISSUE TITLE
Allow users to pick a different datasource from the explore view

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#6175]
Currently there is no way to switch the datasource from the explore view. Users would have to go back to sqllab to build another datasource.

**Comment by michellethomas** [comment]
Is anyone planning on working on this? We've been getting a number of users requesting this feature back, so would like to see this get in soon. I can work on it if no one has plans to.

**Comment by hughhhh** [comment]
💯 @michellethomas plzzz send me the PR lol
