### ISSUE TITLE
Event Flow viz: time is only accepted as date-time, and its lowest granularity is hours

### ISSUE THREAD

**Issue by marcotama** [apache/incubator-superset#6182]
Hi all!
First of all, thanks for making this great tool!

Regarding my issue:
I would like to generate an Event Flow chart, but my data format is not supported. Specifically, the data I am analyzing is the result of simulations, and time is stored as a numeric value starting from zero, not in a date-time format. Furthermore, the time settings are only as granular as a hour, while my data has events happening at a sub-minute scale.

### Superset version
0.28.1

### Expected results
Time should accept other formats. In my data, time is expressed in minutes as a float starting from zero. Furthermore, granularity should allow to go all the way down to milliseconds (although for me seconds would be enough)

### Actual results
My time data is not parsed correctly since it is not in any date-time format. Of course, I can transform my data and work around the limitation, and I will. This is more a feature request.

Thanks again!

**Comment by mistercrunch** [comment]
@williaster ^

**Comment by williaster** [comment]
There should be no inherent limitation for these things within the EventFlow vis itself, more how it's configured in Superset (which is also addressable). 

I do think that it's reasonable for the vis to only accept Time columns, without that limitation I'd expect more people to report errors when it didn't work for non-time columns. One work around here would simply be changing the meta data for your table to set the (currently numeric column) to be a time column. After that it should show up as an option for the vis. 

I also don't think there's any limitation currently for granularity. Perhaps in the time filter section you see a granularity option? But the vis itself doesn't care and should support any event timestamp (at ms level, s level, etc.)

**Comment by marcotama** [comment]
Hi @williaster, thanks for the reply.

I read your first sentences to mean that I can bypass Superset and use the EventFlow vis itself; is this correct? How would I go about it? Sorry if this is a silly question, I am quite new to Superset.

About the granularity, your guess is correct: in the web UI, there is a setting for the granularity, and it only goes down to minutes. Unfortunately, the Superset UI freezes on my entire dataset, and has serious problems even on a slice (small enough that it should not be a size issue). I will open a ticket about this if I manage to write a minimal example that does not involve my data. This was to say that I do not know whether the vis itself would later allow me to change the granularity.

**Comment by mistercrunch** [comment]
Since the EventFlow requires atomic events, you'll probably want to sample your data based on a hash of userid. Your browser will choke if you send too many events (I'm not sure how many it is reasonable to sent to this visualization though).

Note that you can and should use the time granularity of `Time Column`, which is the raw data, unaltered here.
