### ISSUE TITLE
Not able to import dashboard in the latest version of superset

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#6197]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.999.0dev

### Steps to reproduce

I have two latest superset running on different servers. I exported the dashboard and try to import it into other superset but cannot. Please help me

**Comment by mistercrunch** [comment]
Both on python 3? Stacktrace?

**Comment by syazwan0913** [comment]
Yes both on python 3. Even I tried to import back into the same superset, I got errors.

These are the errors:

`Traceback (most recent call last):
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/syazwan/incubator-superset/superset/models/core.py", line 1037, in wrapper
    value = f(*args, **kwargs)
  File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/syazwan/incubator-superset/superset/views/core.py", line 1260, in import_dashboards
    dashboard_import_export.import_dashboards(db.session, f.stream)
  File "/home/syazwan/incubator-superset/superset/utils/dashboard_import_export.py", line 22, in import_dashboards
    type(table).import_obj(table, import_time=import_time)
AttributeError: type object 'dict' has no attribute 'import_obj'`

**Comment by srggrs** [comment]
> Yes both on python 3. Even I tried to import back into the same superset, I got errors.
> 
> These are the errors:
> 
> ```
> Traceback (most recent call last):
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/syazwan/incubator-superset/superset/models/core.py", line 1037, in wrapper
>     value = f(*args, **kwargs)
>   File "/home/syazwan/anaconda2/envs/jps2018/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
>     return f(self, *args, **kwargs)
>   File "/home/syazwan/incubator-superset/superset/views/core.py", line 1260, in import_dashboards
>     dashboard_import_export.import_dashboards(db.session, f.stream)
>   File "/home/syazwan/incubator-superset/superset/utils/dashboard_import_export.py", line 22, in import_dashboards
>     type(table).import_obj(table, import_time=import_time)
> AttributeError: type object 'dict' has no attribute 'import_obj'```
> ```

yeah same issue. I have Python 3.6 and latest superset.....

**Comment by syazwan0913** [comment]
@mistercrunch this is the error
![screenshot from 2018-11-22 10-07-35](https://user-images.githubusercontent.com/28984703/48877539-b3febf80-ee3e-11e8-8b16-3b7187124698.png)

**Comment by syazwan0913** [comment]
@mistercrunch so how to fix it?

**Comment by ReactiveCoreAmar** [comment]
+1

**Comment by MaheshYadavalli** [comment]
Same issue with me too

**Comment by pratapsingh** [comment]
same issue here.

**Comment by forestwater** [comment]
same issue here.

**Comment by forestwater** [comment]
so how to fix it? Anybody shine some light on it?

**Comment by tuhinsharma** [comment]
same issue here.

**Comment by mistercrunch** [comment]
There's some work being done on import / export recently, with a new cli utility and improved logic.

**Comment by syazwan0913** [comment]
@mistercrunch is it fixed already?

**Comment by syazwan0913** [comment]
Only dashboard with Druid datasources cannot be imported

**Comment by paula-everis** [comment]
Same issue here. 

My boss detected it.

Bug's not dead.

**Comment by arslanselcuk** [comment]
Same issue here: 

Superset version 0.30.0
Running on Windows10 

I wanted to investigate import_dashboards feature to execute DTAP pipeline.

- I saved as one of the existing dashboards. (named it "testSelcuk" )

- Then exported this new dashboard as JSON file.

- Then deleted this dashboard.

- then typed python import_dashboards -f "path of testSelcuk"

I reveive the  error : 2019-10-28 08:30:45,544:ERROR:root:(sqlite3.IntegrityError) UNIQUE constraint failed: tables.table_name
[SQL: INSERT INTO tables (created_on, changed_on, description, default_endpoint, is_featured, filter_select_enabled, "offset", cache_timeout, params, perm, table_name, main_dttm_col, database_id, fetch_values_predicate, schema, sql, is_sqllab_view, template_params, created_by_fk, changed_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2019-10-28 08:30:45.544436', '2019-10-28 08:30:45.544436', '<!--\nLicensed to the Apache Software Foundation (ASF) under one\nor more contributor license agreements.  See the NOTICE file\ndistributed with this ... (23651 characters truncated) ... L | Urban population\nSP.URB.TOTL.IN.ZS | Urban population (% of total)\nSP.UWT.TFRT | Unmet need for contraception (% of married women ages 15-49)\n', None, 0, 1, 0, None, '{"remote_id": 2, "database_name": "main", "import_time": 1572247845}', None, 'wb_health_population', 'year', 2, None, None, None, 0, None, None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj

![Untitled](https://user-images.githubusercontent.com/26799735/67660332-d78b8d80-f95e-11e9-8776-d81e9094be71.png)
)

**Comment by ITNoesis** [comment]
Any updates here please? Getting the same error.

**Comment by RishiDas001** [comment]
I was getting the same error but I found a way to avoid it by manually changing the server addresses in the dashboard json. The dashboard got imported without an error, but related charts still didn't get created. Maybe I needed to change some more things in the json?

**Comment by sonikanishk** [comment]
Same issue here.. any solutions yet??

**Comment by ITNoesis** [comment]
The issue is still there. When a dashboard or, slice or, table is created a unique id is assigned to it. A dashboard can easily be exported and if it is imported into another instance of superset, the import will be successful until and unless there are no tables/slices/dashboards with the same unique_id present in the target instance of superset.

How I got around it? Manual pain! I exported a dashboard, edited the json and appended 100 (you need to see how many objects you have in your instance of superset/ the backend db for it) to each unique_id, imported the dashboard in same instance of superset without issues.

It works but it is just a workaround not a viable solution in my opinion. The export_function should be intelligent enough to not export the unique_id and import_function should be able to assign a unique id upon import (identity column for example).

Hope this helps!

**Comment by yousoph** [comment]
The new import and export (feature flag VERSIONED_EXPORT = True) uses uuid so I believe the workaround mentioned will no longer be needed

**Comment by ITNoesis** [comment]
> The new import and export (feature flag VERSIONED_EXPORT = True) uses uuid so I believe the workaround mentioned will no longer be needed
This is awesome. Let me give it a try

**Comment by tawhidwasik08** [comment]
Can anyone help me by telling which ids to change for the workaround ? Or is there any other solution ? 
I am trying to export from 0.36 to 1.3.0

**Comment by VivekGupta97** [comment]
Can you provide me how I can we Import Dashboard in Latest Version.
