### ISSUE TITLE
Tooltip sometimes stuck

### ISSUE THREAD

**Issue by hajdbo** [apache/incubator-superset#6200]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.1
This bug did appear somewhere in the past 12 months or so. It's not recent, and is unrelated to the many changes that appeared in 0.28.

### Expected results
There should be only one tooltip instance

### Actual results
Sometimes a tooltip get "stuck". Very similar to bugs that were fixed by #2096.

<img width="686" alt="screenshot 2018-10-26 at 17 54 22" src="https://user-images.githubusercontent.com/1834306/47560404-b1e23780-d94a-11e8-8017-fde1162483a1.png">

### Steps to reproduce
I've been unable to find a recipe for consistent reproduction, but the bug happens to me multiple times per day.
Browser: Chrome on a mac.

**Comment by hajdbo** [comment]
maybe a duplicate of #2043

**Comment by hajdbo** [comment]
when stuck, the tooltip survives scrolling and scrolls with the view, keeping visible screen X,Y coords constant.

**Comment by mistercrunch** [comment]
This is the patch that's supposed to take care of hiding lingering tooltips:
https://github.com/apache/incubator-superset/blob/master/superset/assets/src/visualizations/nvd3/NVD3Vis.js#L680

From my understanding this stems from an NVD3 bug, and somehow the patch we had in place that worked well in the past stop working recently-ish.

**Comment by hajdbo** [comment]
The patch to hide the lingering tooltips often works, but not always.
Also, the DOM is polluted by all the hidden tooltips that should have been deleted.
![image](https://user-images.githubusercontent.com/1834306/48457695-8d1d0980-e7fe-11e8-9b39-e54cd8f98fdf.png)
In this instance, it worked 3 times and failed once.

**Comment by mistercrunch** [comment]
Fixed here https://github.com/apache/incubator-superset/pull/6852
