### ISSUE TITLE
Empty lists on Welcome screen after upgrade to 0.28.1

### ISSUE THREAD

**Issue by wowo** [apache/incubator-superset#6214]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.1

### Expected results
After upgrade to Superset 0.28.1 (from 0.27.0) via Pip, there's nothing on welcome screen (dashboards, recently viewed, favourites), although I have for instance 3 favourites and I see they are being returned via Ajax call (Google Developer Tools). Happens in firefox and chrome. 

![2018-10-29_0850](https://user-images.githubusercontent.com/100724/47636218-e1b25a80-db57-11e8-8088-3d8185c95bf4.png)
![2018-10-29_0851_001](https://user-images.githubusercontent.com/100724/47636219-e1b25a80-db57-11e8-8e37-9b8a712b20ab.png)
![2018-10-29_0851](https://user-images.githubusercontent.com/100724/47636220-e24af100-db57-11e8-80e0-e0365c49b345.png)

**Comment by mistercrunch** [comment]
@williaster I think this may be related to your recent `SupersetClient` refactor.

**Comment by williaster** [comment]
@mistercrunch are you saying that because you've you've debugged it and you can see that it's related to my changes?

I think this is actually due to broken `reactable` version. Basically we can **either** have a version that works in Prod, or one that works in Dev, but not both. Maybe `28.1` was cut with a version that only works for Dev? See #6142.

cc @kristw

**Comment by mistercrunch** [comment]
@williaster to be honest I have no evidence it's due to `SupersetClient` just operating on intuition here.

`0.28` was cut without much testing as an emergency fix to `0.27` that started failing, and knowing that it would be a while before we'd come up with a proper Apache release.

**Comment by kristw** [comment]
I am confident this is due to `reactable`.
I first increased the version because this behavior happens in development.
Then found that it fixes `dev` but breaks `prod` so I reported an issue (#5935).
A few weeks ago I downgraded `reactable` to make sure `production` works (#6142).

**Comment by williaster** [comment]
^That's consistent with my experience, production works right now and for dev you have to manually change the version for it to work locally.

**Comment by wowo** [comment]
I've downloaded repo from master, build assets and used them with 0.28.1 (with reactable on 1.0.02) and it works fine

**Comment by mistercrunch** [comment]
So we have no reactable version that work in both cases? :(

**Comment by williaster** [comment]
sorry about the trouble @wowo, glad you found a workaround.

I agree we should move away from this one, @kristw has noted that there are ~10 components that use this lib now, so it's not super easy. 

we could look into how hard it is to install different versions depending on dev vs prod to take away some of the urgency?

**Comment by kristw** [comment]
@mistercrunch It seems related to react 16
https://github.com/abdulrahman-khankan/reactable/issues/3
