### ISSUE TITLE
__init__() got an unexpected keyword argument 'ignore_nan'

### ISSUE THREAD

**Issue by wenxuanguan** [apache/incubator-superset#6215]
### Superset version
0.27.0

### Expected results
success

### Actual results
__init__() got an unexpected keyword argument 'ignore_nan'
<img width="939" alt="1" src="https://user-images.githubusercontent.com/7418459/47642210-0849b300-dba3-11e8-8f20-2eb121c18fad.png">

exception stack
2018-10-29 18:13:03,036:ERROR:root:__init__() got an unexpected keyword argument 'ignore_nan'
Traceback (most recent call last):
  File "superset/views/core.py", line 1105, in generate_json
    payload = viz_obj.get_payload()
  File "superset/viz.py", line 352, in get_payload
    payload = self.get_df_payload(query_obj)
  File "superset/viz.py", line 368, in get_df_payload
    cache_key = self.cache_key(query_obj) if query_obj else None
  File "superset/viz.py", line 346, in cache_key
    json_data = self.json_dumps(cache_dict, sort_keys=True)
  File "superset/viz.py", line 586, in json_dumps
    return super(TableViz, self).json_dumps(obj)
  File "superset/viz.py", line 453, in json_dumps
    sort_keys=sort_keys,
  File "simplejson/__init__.py", line 237, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'ignore_nan'
### Steps to reproduce
1. pip install mysqlclient
2. add mysql database as source
3. add mysql table
4. error in SQL Editor Results

**Comment by mistercrunch** [comment]
This should be addressed in newer versions.

**Comment by mistercrunch** [comment]
2.7 is not supported anymore in >=0.28.0

**Comment by mistercrunch** [comment]
I think that's a new error. Can you try `pip install -r requirements.txt` where requirements.txt is https://github.com/apache/incubator-superset/blob/master/requirements.txt ?

**Comment by mistercrunch** [comment]
This should also help for future releases https://github.com/apache/incubator-superset/pull/6219

**Comment by wenxuanguan** [comment]
> I think that's a new error. Can you try `pip install -r requirements.txt` where requirements.txt is https://github.com/apache/incubator-superset/blob/master/requirements.txt ?

meet same error with flower 0.9.2:
Collecting futures (from flower==0.9.2->-r requirements.txt (line 37))
  Downloading http://mirrors.aliyun.com/pypi/packages/1f/9e/7b2ff7e965fc654592269f2906ade1c7d705f1bf25b7d469fa153f7d19eb/futures-3.2.0.tar.gz
futures requires Python '>=2.6, <3' but the running Python is 3.6.4

**Comment by wenxuanguan** [comment]
> The latest master should not have `futures` as part of `requirements.txt` anymore. (since #6201)

pip install master with `pip install  https://github.com/apache/incubator-superset/zipball/master` meet error:
```bash
Collecting https://github.com/apache/incubator-superset/zipball/master
  Downloading https://github.com/apache/incubator-superset/zipball/master
     / 65.0MB 2.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-a1unz9tn-build/setup.py", line 15, in <module>
        with open(PACKAGE_FILE) as package_file:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-a1unz9tn-build/superset/static/assets/package.json'
```

**Comment by mistercrunch** [comment]
I don't think `pip install https://github.com/apache/incubator-superset/zipball/master` is supposed to work. Just `pip install -r requirements.txt` after cloning the repo or downloading just that file.

**Comment by als-sdin** [comment]
Please re-open.
I just built the latest superset from scratch following CONTRIBUTING.md and this bug appeared. 

![Screenshot_20190828_151838](https://user-images.githubusercontent.com/54429030/63827838-ed54f480-c9a7-11e9-8d9a-dddfafce23e4.png)

I have done some investigating and found the culprit. Within _superset/viz.py_ the method `json_dumps` of class `BaseViz` calls `json.dumps` with the keyword argument `ignore_nan`. It should resolve to the **simplejson** package which accepts that keyword argument. Only `json.dumps` points to the builtin **json** library not **simplejson**.

Removing the alias for **simplejson** rectifies the problem.

I'm having a hard time understanding why the error occurs at all??

**Comment by als-sdin** [comment]
Yes I just pulled the latest master. The line numbers are a few out because I was using the `inspect` module to investigate - I should have returned it to upstream before uploading the screenshot. Inspect reports:

```
<module 'json' from '/usr/lib/python3.6/json/__init__.py'>
```

I have been walking through that code path to see if simplejson is being patched by the builtin json in a different module, but I can't find anything - keep in mind I am new to Superset.

**Comment by als-sdin** [comment]
Good news! I have found the error and it is not a Superset problem. It is a problem from my end. I found a wild card import in a plugin a colleague patched that slipped up my radar. Sorry for taking up your time @mistercrunch. 
*Lesson:* Don't use wildcard imports.
