### ISSUE TITLE
API for getting image

### ISSUE THREAD

**Issue by kalu44i** [apache/incubator-superset#623]
Hi,

Is there an API which provides ability to get image of a slice?

Thanks.

**Comment by mistercrunch** [comment]
That would be sweet. Seems like it would require running a headless browser server-side or some equivalent wizardry.

**Comment by benvogan** [comment]
This would be exceedingly useful for: 1. integration with 3rd party tools (embedding a preview image), and 2. for email digests.  Would love to see this happen.

**Comment by mahendra** [comment]
you can see an implementation here - https://github.com/apache/incubator-superset/pull/5294

Easy to wrap an API around it.
