### ISSUE TITLE
When editting Druid Datasource, List Druid Column Page display html

### ISSUE THREAD

**Issue by gavinju** [apache/incubator-superset#6238]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
{"GIT_SHA": "", "version": "0.28.0"}

### Expected results
Durid column page is displayed normally。

### Actual results
Displayed HTML。I attach the attachment。

### Steps to reproduce
Step1:  Sources
Step2: Druid Clusters -> Fill Druid Cluster Info
Step3: Scanning New Datasources -> List Druid Datasource -> Edit Druid datasource -> List Druid Column
![step_1](https://user-images.githubusercontent.com/494589/47765975-8626cf00-dd07-11e8-9009-c56db3a72177.jpg)
![step_2](https://user-images.githubusercontent.com/494589/47765984-8de67380-dd07-11e8-9a74-8c253e6cb4ac.jpg)
![step_3](https://user-images.githubusercontent.com/494589/47766009-a9ea1500-dd07-11e8-8791-462142eafcf6.jpg)

**Comment by mistercrunch** [comment]
Should be fixed in `0.28.1`
