### ISSUE TITLE
sqlab + firebird 2.5 -> error

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#6242]
Greetings to all.
I'm having a problem with the firebird database.

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.
#2452

### Superset version - latest

I'm add connection:

![default](https://user-images.githubusercontent.com/11568424/47778573-d732c500-dcff-11e8-8360-ce3cee5ffc64.png)

I can see table from firebird

![default](https://user-images.githubusercontent.com/11568424/47778695-13febc00-dd00-11e8-8f4e-1c049478198e.png)

when  I tried to make a simple query in the sql lab(select * from users) but an error occurred.
![default](https://user-images.githubusercontent.com/11568424/47778795-44def100-dd00-11e8-8189-c7cb312a2425.png)

from terminal logs
`2018-10-31 09:29:23,709:INFO:root:Parsing with sqlparse statement select * from users
2018-10-31 09:29:23,718:INFO:root:Set query to 'running'
2018-10-31 09:29:23,742:INFO:root:Database.get_sqla_engine(). Masked URL: firebird+fdb://MKP:XXXXXXXXXX@192.168.2.15:3050/C:/BD/BD
2018-10-31 09:29:23,964:INFO:root:Running query:
select * from users LIMIT 100000
2018-10-31 09:29:23,965:INFO:root:select * from users LIMIT 100000
2018-10-31 09:29:24,017:ERROR:root:('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 1, column 27\n- 100000', -104, 335544569)
Traceback (most recent call last):
  File "/work/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 182, in execute_sql
    db_engine_spec.execute(cursor, query.executed_sql, async_=True)
  File "/work/superset/lib/python3.6/site-packages/superset/db_engine_specs.py", line 385, in execute
    cursor.execute(query)
  File "/work/superset/lib/python3.6/site-packages/fdb/fbcore.py", line 3626, in execute
    self._ps = PreparedStatement(operation, self, True)
  File "/work/superset/lib/python3.6/site-packages/fdb/fbcore.py", line 2254, in __init__
    "Error while preparing SQL statement:")
fdb.fbcore.DatabaseError: ('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 1, column 27\n- 100000', -104, 335544569)
`

But! I can create a table, and then a chart.

![default](https://user-images.githubusercontent.com/11568424/47779101-fbdb6c80-dd00-11e8-8114-e4021f770f5a.png)

when i click View query
![default](https://user-images.githubusercontent.com/11568424/47779270-6391b780-dd01-11e8-87a7-05289348ba64.png)

i see

`SELECT FIRST 10 u2 AS u2
FROM "USERS";`

This request returns an error
![default](https://user-images.githubusercontent.com/11568424/47779433-c1260400-dd01-11e8-8234-0545c473fbfd.png)

if a little change - an error is returned again
![default](https://user-images.githubusercontent.com/11568424/47779510-eca8ee80-dd01-11e8-8f28-229c63636ce1.png)

Have ideas how to correct it?
Thanks for the help.

**Comment by mistercrunch** [comment]
What does your connection string look like? Are you not specifying a database?

**Comment by bbs2009** [comment]
Сonnection string in page "Add Database"

name database "asu"
`firebird+fdb://MKP:XXXXXXXXXX@192.168.2.15:3050/C:/BD/BD`

database on server `192.168.2.15:3050/C:/BD/BD`

![default](https://user-images.githubusercontent.com/11568424/47896981-7e3a6c80-de78-11e8-927b-fec490f940bd.png)

 I choose a database by name asu
![default](https://user-images.githubusercontent.com/11568424/47897220-7c24dd80-de79-11e8-8760-43e67cd84f70.png)

**Comment by bbs2009** [comment]
No, that's not the problem. I can not execute any query to any table in the database firebird in sql lab. with or without quotes. I'll make a screen now

**Comment by bbs2009** [comment]
I can create a connection and connect to the database:

![gif](https://user-images.githubusercontent.com/11568424/47991393-b6e57a80-e0f2-11e8-8332-f23e3ca3568c.gif)

At the bottom of the page I see part of the tables from the database.

**Comment by bbs2009** [comment]
I can not execute any query to any table in the database firebird in sql lab. for example, I will try to select the table "ab" which contains 14052 records

![gif](https://user-images.githubusercontent.com/11568424/47992079-9c140580-e0f4-11e8-8248-4163dbb0d826.gif)

**Comment by bbs2009** [comment]
But I can create a table in a superset and then see a slice like this:
![gif](https://user-images.githubusercontent.com/11568424/47992616-ff526780-e0f5-11e8-9bad-fed84b4a5ef0.gif)
A table is created in the superset.
![gif](https://user-images.githubusercontent.com/11568424/47993002-16458980-e0f7-11e8-9f22-d8208094c403.gif)

**Comment by bbs2009** [comment]
try to look at the sql query for this slice and execute it in sql lab
![gif](https://user-images.githubusercontent.com/11568424/47993279-c0251600-e0f7-11e8-94aa-b51f1747dc6c.gif)
But unfortunately, an error occurs
@mistercrunch 
Any idea why this is so?Thank you very much

**Comment by marxxx** [comment]
Same problem here with Firebird 3.0.
SQL Lab is using "LIMIT 100000" not "FIRST  100000" with Firebird for some reason.

**Comment by mistercrunch** [comment]
I think that's a problem with the SQLAlchemy dialect then. We use the `query.limit(row_limit)` pattern when wrapping the query, SQLAlchemy is in charge or applying that using the proper dialect.

**Comment by cmenzelqlp** [comment]
@bbs2009 What drivers did you use for Firebird? and was the second BD folder the one that contained your remote rdb file? Can't get ours to connect and we're thinking it's the request URI.
