### ISSUE TITLE
[feature request] Update control to provide quick toggle for the popular chart types

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#6253]
### Description

Spinning off from #6235. 
 
@mistercrunch : 
> "Side mission would be for the control to offer a quick-toggle for the popular chart types that would not require opening the modal.
> Here's a horrible sketch of what I'm thinking, where the last button ... opens the modal :"

![image](https://user-images.githubusercontent.com/1659771/47821826-4370f100-dd1f-11e8-9f06-be6b803510e8.png)

> It would bring some common interactions to the forefront and add a nice dash of color to the explore view.

**Comment by mistercrunch** [comment]
@elibrumbaugh ^
