### ISSUE TITLE
Dialog box does not close when you click OK

### ISSUE THREAD

**Issue by timifasubaa** [apache/incubator-superset#6262]
Make sure these boxes are checked before submitting your issue - thank you!

The error messge dialog box does not close when you click on OK. 
https://github.com/apache/incubator-superset/pull/5523

@mistercrunch @betodealmeida 

### Expected results

After clicking OK, the dialog box should close

### Actual results
It doesn't. 

### Steps to reproduce

Write a query with count(*), try to visualize, then click OK on the error message dialog box.

**Comment by mistercrunch** [comment]
Confirmed, saw that too recently, thinking bumping libs may help
