### ISSUE TITLE
Chart with params since: '7 days' and 'until': now errors "From date cannot be larger than to date"

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6263]
'7 days ago' is parsed correctly but we have some charts with `since: 7 days` `until: now` and it's treated as 7 days from now not since 7 days. 

@betodealmeida @graceguo-supercat 

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
master

### Expected results
since: 7 days would be treated as 7 days ago

### Actual results
since: 7 days would be treated as 7 days ago instead of 7 days in the future.

### Steps to reproduce
create a chart with a time filter of 7 days : now

**Comment by mistercrunch** [comment]
Did that behavior change over time?

About this, I've been thinking for a while to have a clear cue in `DateFilterControl` component that would shows what relative times evaluate do. Since that parsing is done on the server, we'd have to have some new endpoint that receives a date expression and returns a fixed date, and show the result value onChange of the free-input text fields (async).

**Comment by mistercrunch** [comment]
@elibrumbaugh what do you think? Despite the tooltip, it's pretty unclear that we have pretty powerful support for relative date expressions, and what they evaluate to. You pretty much have to check the rendered SQL query (modal) to know what your relative time expression evaluated to. For instance there can be confusion around, "does `7 day ago` evals to 7 days ago at midnight or 7 days ago at the same time as now" 
<img width="350" alt="screen shot 2018-11-02 at 8 45 09 am" src="https://user-images.githubusercontent.com/487433/47925643-f0f91700-de7b-11e8-9c22-1affaa17697c.png">

**Comment by michellethomas** [comment]
@mistercrunch Yes it changed over time, I was assuming with the new time range changes. We currently have some slices working in production with since: 7 days and they are breaking when we deploy the current changes on master with "From date cannot be larger than to date"

**Comment by michellethomas** [comment]
I think I found the issue, it looks like we were previously adding 'ago' to a string like this if it didn't exist. I'll add this logic back. https://github.com/apache/incubator-superset/pull/4981/files#diff-f451672348fc6071e8d627778bdc4e96L270

**Comment by michellethomas** [comment]
@paudelsagar if relative to today isn't useful, you can use the start/end to specify a specific range. Sorry I'm not quite sure what you mean, hopefully that helps.

This issue was created to address a very specific bug with the way a range is parsed. If you have another issue or feature request you may want to open another issue.
