### ISSUE TITLE
Incubator-superset container keeps restarting and doesn't go up

### ISSUE THREAD

**Issue by UrimLimani** [apache/incubator-superset#6267]
Hello everyone,

I'm trying to install Superset with the help of Docker, but after running the following command:
`docker-compose up -d`
the status of the `apache/incubator-superset` container remains in `Restarting`, i.e. it keeps restarting again and again. Clearly some error is causing the container to fail, so the restart policy is restarting it repeatedly.
As a consequence, I can't run the next command:
`docker-compose exec superset bash`
since, the following error is thrown:
`Error response from daemon: Container fa5138... is restarting, wait until the container is running`

Does anyone has any idea where the problem could be?

EDIT: After running `docker logs` to see the outputs the container is generating, I got the following error message:
`2018-11-02T10:46:06.217791002Z standard_init_linux.go:190: exec user process caused "no such file or directory"`

Thank you in advance!

**Comment by UrimLimani** [comment]
The problem was with the Windows line endings. After changing the .ssh files to Unix line endings, the container is up and running.

**Comment by ctivanovich** [comment]
Hi I'm having this same issue, only, it's for attempting to build the container on windows. I've looked through the log, which states:
`standard_init_linux.go:207: exec user process caused "no such file or directory"`. The container is attempting to run, I think, /entrypoint.sh, but that I think exists within the container's system, not in the filesystem of incubator-superset, so I can't access it. The postgres and redis containers seem to be running fine. Do you have any idea on how I might solve this problem? I had hoped that using superset as a container would help me get around the Windows compatibility issues.

**Comment by csakaszamok** [comment]
Same error for me

**Comment by ctivanovich** [comment]
I also tried dos2unix to change the line endings using WSL, but that didn't help, the error remains the same.

**Comment by kumaranar** [comment]
Same error for me

**Comment by Mattmtech** [comment]
@inamilu which ssh files did you change the file type on? do you mean the .sh files?

**Comment by chharish** [comment]
same issue here. the health check never starts and the container keep restarting again and again.

**Comment by gaorongchao** [comment]
the same issue,Is there any solution?

**Comment by gaorongchao** [comment]
I try one possible solution.
* bulid superset by hand, `docker build -f ./contrib/docker/Dockerfile -t="supset-1" .` thie is run in root.
and You will get the build image, such like c25ef5300307
* modify `./contrib/docker/docker-compose.yml`
```
  superset:
    image: c25ef5300307
    # build:
    #   context: ../../
    #   dockerfile: contrib/docker/Dockerfile
    restart: unless-stopped
    environment:
......
```
* finally:
`cd incubator-superset/contrib/docker`
`docker-compose run --rm superset ./docker-init.sh`

**Comment by ramonankersmit** [comment]
still getting the same error.
