### ISSUE TITLE
can't export to csv if query contains case statement

### ISSUE THREAD

**Issue by ligadata-mkhalawi** [apache/incubator-superset#6268]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Expected results
If the query ran successfully, then I can export the result normally to CSV

### Actual results
Query execute successfully, but the "Export to CSV" return 
Internal Server Error

### Steps to reproduce
Write any query that contains "case statement", the query will execute successfully, but the export to csv will fail!!
ex. select case when c1 like '%somthing%' then 'somthing else 'nothing' end as c2 from table.

**Comment by jiangnight** [comment]
#6156 here may be help you
