### ISSUE TITLE
Can I add a new Drag & drop dashboard component?

### ISSUE THREAD

**Issue by zhangjunxia** [apache/incubator-superset#6281]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Master

**Comment by mistercrunch** [comment]
Please provide more information.

**Comment by zhangjunxia** [comment]
the following components have be available for dashboard composition, charts , Markdown, Rows, Columns, Headers, Tabs,Dividers. now I need some new drag & drop compontents. like dropmenu, checkbox , what should I do

**Comment by zhangjunxia** [comment]
@mistercrunch ，the following components have be available for dashboard composition, charts , Markdown, Rows, Columns, Headers, Tabs,Dividers. now I need some new drag & drop compontents. like dropmenu, checkbox , what should I do

**Comment by mistercrunch** [comment]
Very unclear what you mean by "dropmenu, checkbox". I'm assuming you're talking about filters. There are open issues discussing "Filter as native dashboards components".

**Comment by syazwan0913** [comment]
I think what @zhangjunxia meant is add another components here : 
![screenshot from 2018-11-14 09-03-09](https://user-images.githubusercontent.com/28984703/48452950-4a523600-e7ec-11e8-997d-ae18e28f6c89.png)
