### ISSUE TITLE
Slice menu option is not available superset 0.28.1

### ISSUE THREAD

**Issue by ucolina** [apache/incubator-superset#6285]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

Dear Superset dev masters recently installed superset into a Docker container in a standard way for evaluation tests, metadata is located in SQLite and test data en Postgres, the app is working as expected, I was able to create a dashboard following the tutorials, but I notice that the "Slice" menu is missing.

Superset server is running in development mode with the debugger. 

Could you provide guidance where I need to look at?, seems that is something missed with roles or views/menus (test user with admin role, created with admin std user from fabmanager command)

Appreciated your help and guidance.

### Expected results
Slice menu option is not available/visible/missing

### Actual results
Cannot test Superset's slice features

### Steps to reproduce

![2018-11-06_16-03-37](https://user-images.githubusercontent.com/44816032/48093631-e2915f00-e1dd-11e8-8882-c78c704cef20.png)

**Comment by andy-clapson** [comment]
'Slices' are now referred to as 'Charts' in the UI.

**Comment by ucolina** [comment]
Hi Andy, thanks for the clarification > I see what you mean and my mistake of course. I referred to slice and dice data to break down in smaller parts for different-angle views and analysis.

Thanks again!

Ulises.
