### ISSUE TITLE
Cannot add filter controls to Filter visualization

### ISSUE THREAD

**Issue by tomsej** [apache/incubator-superset#6295]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Master

### Expected results
When I click on adding new filter control, new filter is added.

### Actual results
When I click on adding new filter control, new filter is not added and the rest of page is blank.

![](https://media.giphy.com/media/1gdwCTA7Ncy5jX9IWG/giphy.gif)

### Steps to reproduce
- clone master
- create new filter chart

**Comment by mistercrunch** [comment]
Recently merged https://github.com/apache/incubator-superset/pull/6294 may help with these recent grey screens of death. For the record there's been major refactoring happening lately and we're in the process of stabilizing master. Hoping `0.29.0` will be a good release!
