### ISSUE TITLE
Empty favorite list

### ISSUE THREAD

**Issue by gvasquez-waypoint** [apache/incubator-superset#6343]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Favorited dashboards displayed in "home" tab/listing

### Actual results
Despite of which dashboard I mark as favorite, from the sample data (loaded using superset load_examples), no favorites are displayed at all in the listing

![captura de pantalla 2018-11-08 a la s 15 06 36](https://user-images.githubusercontent.com/14003078/48218143-f5d03600-e367-11e8-8756-49c972538f87.jpg)

### Steps to reproduce
Login as admin user, go to a specific dashboard (for example World's Bank Data), click de start next to the dashboard title, go back to home (http://<hostname>:8080/superset/welcome)
, select "Favorite" tab and, listing is empty/blank

![captura de pantalla 2018-11-08 a la s 15 07 41](https://user-images.githubusercontent.com/14003078/48218258-3a5bd180-e368-11e8-8e4c-d040a8a55777.jpg)

**Comment by aboganas** [comment]
I think this is related to react component where a certain version would work in production and not the development (and the opposite is true)

However, create your asset as production optimized using `nom run build` and it should work

**Comment by AndreNalevaiko** [comment]
I have the same problem. In your welcome page in tab "Dashboards" is showing your dashboards?
In my case is also empty.

**Comment by mistercrunch** [comment]
Has to do with Reactable issues: https://github.com/apache/incubator-superset/issues/5935

**Comment by ucolina** [comment]
Reporting the same issue with superset 0.28.1, (docker container and venv).
"Favorites", "Created Content", "Recent Activity" tabs are empty with a Dashboard created.
with the exception of "Security & Access" tab. 

Admin User roles used to create the Dashboard, chrome traces doesn't shows any visible issue, refreshed with "superset init" permissions.

Looking deep into container logs.

**Comment by us3r** [comment]
any idea how to solve it (without rebuilding) ?

**Comment by mistercrunch** [comment]
The latest release candidate should be much better than `0.28.1`.
`pip install superset==0.29.0rc7`
