### ISSUE TITLE
Mapbox dosen't show anything

### ISSUE THREAD

**Issue by jonathancardoso** [apache/incubator-superset#6348]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
LATEST

### Expected results
Mapbox, show results sum

### Actual results
Nothing

### Steps to reproduce
Setup a Mapbox Chart.

Anyone can help me? I usually have 4 charts using mapbox but now (this version) dosen't working any

**Comment by zhaoyongjie** [comment]
please check:
1. do you setup mapbox token in Superset? 
2. If you are in mainland China you can not access global mapbox api

**Comment by jonathancardoso** [comment]
Yes I did and no I don't from china.

I usually use mapbox in other versions, but stopped worked after the update.

**Comment by KWONJAE** [comment]
I met same issue while trying to upgrade superset.
In my case, "python 2.7.5 + superset 0.26.3" works fine
but "python 3.6.3 + superset 0.28.1" doesn't work(there were no error log).
So I did roll back...

Well... I used same "map box api key" and I also checked "statistics" in my Mapbox account page.
Even though there were request for "python 3.6.3 + superset 0.28.1", I couldn't see my data on map.
these are map ids in my Mapbox-statistics page
- mapbox.mapbox-terrain-v2
mapbox.mapbox-streets-v7

**Comment by Piste** [comment]
Facing the same issue here. We're stuck between working filters (latest) or working maps (0.28). Tough compromise.

**Comment by Yoone** [comment]
Still having this issue on our end. Can't make the maps work in the latest releases, but having other issues with 0.28.x that were fixed on 0.29.

**Comment by ajhodges** [comment]
+1, broken using the Docker image which is currently on Python 3.6

**Comment by sh0gg0th** [comment]
+1, broken on amancevice/superset:0.29.0rc7

**Comment by Yoone** [comment]
I keep having the issue and still no new version has been released. Please don't mark it as inactive.

**Comment by Yoone** [comment]
Again, no one's taking notice, but it's still happening...

**Comment by villebro** [comment]
@Yoone have you tried on one of the latest release candidates or master branch? If you can post a reproducible case I will be happy to help debug the issue.
