### ISSUE TITLE
Bubbles cut-off

### ISSUE THREAD

**Issue by apitts** [apache/incubator-superset#635]
Since the max and min on the x and y axes for the bubble chart are determined by the max and min x and y values bubbles are invariably cut-off. It would be nice to be able to configure the x and y axes so as to allow additional space.

**Comment by mistercrunch** [comment]
Does nvd3 offer an option for that?

**Comment by apitts** [comment]
Indeed it does. It looks like the relevant inputs are xDomain and yDomain which are both arrays with max and min that allow you to overwrite the x and y axes' max and min. The default is the max and min of the data but I think providing the ability to overwrite that for all chart types that support xDomain and yDomain would be very helpful. 
Link: http://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart

**Comment by datakingdom** [comment]
One more question regarding x axis, could we set x axis as time parameter to view the data ?
