### ISSUE TITLE
Filtering (by filterbox) for Line Chart with Time Shift slice doesn't work properly

### ISSUE THREAD

**Issue by vitalii-stepaniuk** [apache/incubator-superset#6351]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.26.3

### Expected results
Main line in Line Chart with time shift respects filter set in the filterbox on the same dashboard

### Actual results

On one dashboard we have filterbox and line chart (with time shift), which display current data and data with 1 year back time shift. On dashboard load (default settings of the filterbox) the chart shows proper results for actual data and data in the past (see image below) <img width="576" alt="chart_before_filtering" src="https://user-images.githubusercontent.com/3185935/48264524-73607880-e432-11e8-9cb9-87183fc61840.png">

When I change filter in the filterbox, only time shift line (1 year back) shows correct data, line with the actual data remains the same (see image below) <img width="569" alt="chart_after_filtering" src="https://user-images.githubusercontent.com/3185935/48264525-73607880-e432-11e8-8414-01c084867c17.png">

It seems like changes in the filterbox doesn't affect on actual (main line) data in the chart. When I explore the slice with the chart, and set the same filters there, both lines show proper results.

### Steps to reproduce

1. Create new dashboard
2. add filtebox to the dashboard (with some time range, and "show all" for other filter criterias)
3. add slice with Line Chart (with time shift) to the dashboard
4. save dashboard and open it for view
5. apply some filter on the filterbox

**Comment by vitalii-stepaniuk** [comment]
Screenshot before filtering:
<img width="576" alt="chart_before_filtering" src="https://user-images.githubusercontent.com/3185935/48264524-73607880-e432-11e8-9cb9-87183fc61840.png">
Screenshot after filtering:
<img width="569" alt="chart_after_filtering" src="https://user-images.githubusercontent.com/3185935/48264525-73607880-e432-11e8-8414-01c084867c17.png">

**Comment by mjain1994** [comment]
Were you able to solve the issue? I am facing the exact same issue.

**Comment by vitalii-stepaniuk** [comment]
Unfortunately I couldn't find a fix for this and it forced me to install 0.29 version of superset (0.29rc7). This feature works well there.

**Comment by shreya0712** [comment]
Not sure if this is the right place for this, but the red dot in the legend doesn't help recognising what the solid and the dashed lines stand for? some help would be appreciated. Is there a way i can change dots in the legend to soild and dashed lines respectively?
