### ISSUE TITLE
Unable to build docker with debian stretch

### ISSUE THREAD

**Issue by ekohlwey** [apache/incubator-superset#6353]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
master

### Expected results
Running the docker build should result in a docker container

### Actual results
The build crashes with the error:
```
E: Unable to locate package apt-transport-https
E: Package 'apt-utils' has no installation candidate
```

### Steps to reproduce
Run the docker build sequence listed in the installation of the wiki.

# Root cause/Suggested fix
It seems that the Docker library's python container recently switched to Debian Stretch for the 3.6 tag.

You can get the build to work just fine by changing the `FROM` line of the `Dockerfile` to use the `3.6-jessie` tag.

Another, possibly more desirable alternative, would be to fix the Dockerfile, however I am not aware of an installation procedure for Stretch and can't research one at the moment.

**Comment by BrayanArrieta** [comment]
Hello, you are tried modifying the docker python library to 3.6.0, it's different to latest version to the docker image. 

`FROM python:3.6.0`  in the Dockerfile

**Comment by vkzxcv** [comment]
> You can get the build to work just fine by changing the `FROM` line of the `Dockerfile` to use the `3.6-jessie` tag.

This did not work. same error.

**Comment by witekw** [comment]
The root problem "apt-get update" failing before. Debian uses CDN which is returning 404. Apt-get update reports warnings to the console.
