### ISSUE TITLE
No x-axis for bubble chart

### ISSUE THREAD

**Issue by apitts** [apache/incubator-superset#637]
There is a y-axis but no x-axis. Perhaps this is deliberate?

**Comment by mistercrunch** [comment]
I don't see that on my end, can you share a screenshot?

**Comment by apitts** [comment]
Sorry @mistercrunch...I probably was not very clear. You can actually see what I'm talking about in the standard caravel screenshots in the readme (see below). All I'm saying is that there is a dark line for the y-axis but no dark line for the x-axis. Looking here (http://nvd3.org/examples/scatter.html) it looks like a deliberate styling choice by nvd3....just jars with me for some reason. 

<img width="1144" alt="687474703a2f2f692e696d6775722e636f6d2f78637931516a4e2e706e67" src="https://cloud.githubusercontent.com/assets/4076720/16289800/a110e2f0-393b-11e6-9498-1c3f854af942.png">
.
