### ISSUE TITLE
Sort Dashboards by name by default

### ISSUE THREAD

**Issue by UZi02** [apache/incubator-superset#6371]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.27.0

### Expected results
Dashboards sorted by name

### Actual results
Dashboards sorted by last change

### Steps to reproduce
Log into Superset, at the welcome screen you see the dashboards sorted by last change date. Also when you click on the "Dashboard" menu it's the same.

Is there a configuration parameter to sort the Dashboards always by name instead of the last change date?

**Comment by zheya08** [comment]
+1

**Comment by maudrid** [comment]
+1

**Comment by juanmantelli** [comment]
+1

**Comment by GenadiEstafet** [comment]
+1
