### ISSUE TITLE
Time series charts are not working in 0.28.1

### ISSUE THREAD

**Issue by zoltantalas** [apache/incubator-superset#6372]
### Superset version

0.28.1

### Expected results

To work the same way like in 0.27

### Actual results

Simply it does not show any data for time series charts. Also when i create a filter box for the date it does not work. When you select any date it shows an empty box afterwards and you need to reload page to see date filter again. (and it does not filter data) doing the same steps in 0.27 is working correctly.

### Steps to reproduce

create any time series related chart. eg: Time Series Table or a filter box for a date field

**Comment by kaitorecca** [comment]
Same issue. Start happened from 0.28.0

**Comment by aboganas** [comment]
if You change the X Axis Format  to `adaptive formatting` does it work?

because if I use any other format, it doesn't show anything and I get the following error

```
Uncaught Error: invalid format: %d/%m/%Y
    at new s (explore.300f80d67ac07be76481.entry.js:2)
    at a (explore.300f80d67ac07be76481.entry.js:2)
    at f (explore.300f80d67ac07be76481.entry.js:2)
    at t.d3FormatPreset (explore.300f80d67ac07be76481.entry.js:2)
    at Object.generate (3.e295a71f362c7b6a4c4b.chunk.js:1)
    at e (1.af57dbf21ff83e4b75c9.chunk.js:1)

```

**Comment by joshbrooks** [comment]
With regard to the filter box disappearing, I'm experiencing the same issue and getting this console output.

![image](https://user-images.githubusercontent.com/4409570/48470442-670e5e00-e82c-11e8-9cd4-61e2a009c48e.png)

**Comment by kaitorecca** [comment]
The issues in js file name prop of Time Table Series, it's array but in declaration missing []. I see the fix in 0.29rc. If you want to fix, you can edit the js file and recompile again

**Comment by kaitorecca** [comment]
> Could it be the same problem as this issue: #5910 ?
> Caused by changes in how timezone awareness are handled.

No, it's just typo issue in coding which lead to corrup array handling

**Comment by fanguyun214** [comment]
> if You change the X Axis Format to `adaptive formatting` does it work?
> 
> because if I use any other format, it doesn't show anything and I get the following error
> 
> ```
> Uncaught Error: invalid format: %d/%m/%Y
>     at new s (explore.300f80d67ac07be76481.entry.js:2)
>     at a (explore.300f80d67ac07be76481.entry.js:2)
>     at f (explore.300f80d67ac07be76481.entry.js:2)
>     at t.d3FormatPreset (explore.300f80d67ac07be76481.entry.js:2)
>     at Object.generate (3.e295a71f362c7b6a4c4b.chunk.js:1)
>     at e (1.af57dbf21ff83e4b75c9.chunk.js:1)
> ```

Have you solved it?

**Comment by zoltantalas** [comment]
any updated when this will be corrected?

**Comment by mistercrunch** [comment]
We're kind of stuck at the moment between a bad release `0.28.1` and the ASF forcing us into proper Apache releases.

**Comment by Tutufa** [comment]
pip install superset==0.28.0rc7 didn't solve the issue

**Comment by mistercrunch** [comment]
Sorry I meant `0.29.0rc7`

**Comment by zoltantalas** [comment]
@mistercrunch 

git checkout 0.28.1
git cherry-pick b4a19833035393857b11e0aec3ce62c6e0681dd1

using the above filtering issues seems to be solved. But Time Series - Line Chart is still not working. does not show any error. simply doesn't show anything.

**Comment by muraiki** [comment]
I've found that saving the chart first, even with nothing configured, generally allows it to render.

**Comment by muraiki** [comment]
> We're kind of stuck at the moment between a bad release `0.28.1` and the ASF forcing us into proper Apache releases, which may take a moment to come up with. We should start a thread on the `dev@` mailing list as to how to mitigate

Is there an ETA for the next release?
