### ISSUE TITLE
Support WKT in Deck.gl charts

### ISSUE THREAD

**Issue by oripwk** [apache/incubator-superset#6373]
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Description
When trying to create a Deck.gl map, the only line encodings available are Polyline and JSON.
Our geospatial data is encoded in WKB/WKT.

Is it possible to use WKT line encoding? If not, will it be added in the future?
WKT is a standard and ubiquitous geo format and I believe many will benefit from such support.

**Comment by ali-bahjati** [comment]
I also agree that this feature will help many.
Please reopen this issue.

**Comment by pelayoarbues** [comment]
Yes please! It would be really helpful

**Comment by anadue** [comment]
+1 here: WKT is standard.

**Comment by jo-chemla** [comment]
Deckgl indeed has three layer types that are [points scatterplots](https://deck.gl/examples/scatterplot-layer), [lines](https://deck.gl/examples/line-layer) and [polygons](https://deck.gl/examples/geojson-layer-polygons). Parsing WKB/WKT could be done via the existing respective [WKT/WKB loaders](https://loaders.gl/docs/modules/wkt/api-reference/wkt-loader) - on top of standard geojson, shapefile, json, geopackage and kml loaders.
