### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by sontt710** [apache/incubator-superset#6379]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Access HTTPS via browsers without error in console debug.

### Actual results
This request has been blocked; the content must be served over HTTPS.

### Steps to reproduce
Access dashboard URL in UI have the errors like attachement.
![screenshot_1](https://user-images.githubusercontent.com/31494976/48398600-d2d0c800-e753-11e8-84f5-12815b996876.png)

**Comment by thoughtpunch** [comment]
possible dup of https://github.com/apache/incubator-superset/issues/4256

**Comment by chenhaiyan** [comment]
@sontt710 hello ,I have the same error,Can you tell me how you solve this ?
