### ISSUE TITLE
Date Filtering with Standard date filter Box directly into SQLab 

### ISSUE THREAD

**Issue by rmonta11** [apache/incubator-superset#6381]
Hello all,

SuperSet version : 0.28 

For a dashboard, i need to use a query with more than 10 filters and around 8 KPIs.
The query source is quite simple but need to be filtered even before execution in SQLab.

It is possible throught the filter_values() JINJA function, but this function leads to several issues :

--> how can i implement the filter_values() for the date column ? Indeed, i want to filter throught the option box "From" and "To" from the standard filter box pannel (i don't care about the automatic filters such as Last week or Last month). I need some examples in order to implement myself.

**Comment by trungtv** [comment]
I am also interested in this open question.
