### ISSUE TITLE
Dist bar legend item titles should be verbose_names not metric_names

### ISSUE THREAD

**Issue by jhettler** [apache/incubator-superset#6382]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Dist bar legend item titles should be verbose names not metrics name.

### Actual results
![image](https://user-images.githubusercontent.com/6342027/48418219-04965e80-e755-11e8-8571-144ef8d5eb66.png)

### Steps to reproduce
Just add any metric with verbose_name defined and try to graph it.

Thanks for some hints how to fix this!

**Comment by michellethomas** [comment]
I believe this is fixed in master, so it should be fixed in the next release.
