### ISSUE TITLE
Viz Flow error modal doesn't close

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6383]
The error modal when going from sqllab to visualize [here](https://github.com/apache/incubator-superset/blob/master/superset/assets/src/SqlLab/components/ExploreResultsButton.jsx#L37) doesn't close.

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
master

### Expected results
modal closes

### Actual results
need to refresh the page to get the modal to close

### Steps to reproduce
Run in sqllab:
`SELECT ds, sum(num)
FROM birth_names
group by ds`
Click visualize
Click 'ok'

@mistercrunch

**Comment by pc-jcarey** [comment]
Appears to be closed by https://github.com/apache/incubator-superset/pull/7179

**Comment by mistercrunch** [comment]
@michellethomas I wasn't able to reproduce, tried both `master` and `0.31`, made sure to run `npm ci && npm run dev` fresh on both side and ok button just worked for me. 

Can you try the same on master? `npm ci` is great as it nukes `node_modules` and makes sure you're 100% sync with `package-lock.json`

**Comment by michellethomas** [comment]
Sorry forgot to close this, fixed by #7179 

I got an email where someone tagged this as fixed but I'm not sure where that message went.
