### ISSUE TITLE
Superset Database is locked

### ISSUE THREAD

**Issue by cycy9999** [apache/incubator-superset#6389]
- [yes] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [no] I have reproduced the issue with at least the latest released version of superset.
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version: 0.25.5

Hello,
I use Superset since 6 months with success.
My problem already happened several times until this morning, when a new time, Superset was locked.
 
I stopped superset and I tried to restart it with following command:
"nohup superset runserver -d -p 8088 &"

the product did not start because the Database is locked, here is the error message:

OperationalError:

(sqlite3.OperationalError) database is locked [SQL: u'SELECT ab_user.id AS ab_user_id, ab_user.first_name AS ab_user_first_name, ab_user.last_name AS ab_user_last_name, ab_user.username AS ab_user_username, ab_user.password AS ab_user_password, ab_user.active AS ab_user_active, ab_user.email AS ab_user_email, ab_user.last_login AS ab_user_last_login, ab_user.login_count AS ab_user_login_count, ab_user.fail_login_count AS ab_user_fail_login_count, ab_user.created_on AS ab_user_created_on, ab_user.changed_on AS ab_user_changed_on, ab_user.created_by_fk AS ab_user_created_by_fk, ab_user.changed_by_fk AS ab_user_changed_by_fk \nFROM ab_user \nWHERE ab_user.id = ?'] [parameters: (1,)]

After several kill and attempts (even rebooting the server), it has finally restarted.

As said, this problem already occurred several times.

could you help me to understand better this error, and how to process correctly ?

### Expected results
Avoid to lock the Database.
Have a command / a solution to unlock the Database.

### Actual results
Superset has restarted, but I am afraid the problem occur again.

### Steps to reproduce
I don't know

Many thanks for your ideas / help

**Comment by mistercrunch** [comment]
I haven't seen that before, but use a local mysql in my dev environment. Others use SQLLite for dev and it's ok. Maybe you have zombie processes you should clean up/kill?

**Comment by aboganas** [comment]
On my Mac SQLLite always looks. now I use MariaDB for local dev and so far smooth

**Comment by cycy9999** [comment]
Superset is installed on Linux

**Comment by starsunny** [comment]
@cycy9999  Did you get any solution?

**Comment by cycy9999** [comment]
unfortunately, no :-(

**Comment by megha144** [comment]
I am getting "database is locked" error on superset version 0.36.0. I could not solve it. any ideas or help would be appreciated

**Comment by zhouhanc** [comment]
I am getting the same "database is locked" error on superset version 1.0. My system is Red Hat Enterprise Linux 8.2.

Does anyone have a good solution? Thanks!
