### ISSUE TITLE
Share dashboard url, but when clicked from powerpoint presentation it opened dashboard lists not specific dashboard

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#6394]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0dev

### Expected results
Specific dashboard is opened in browser when clicked in powerpoint

### Actual results
It opened dashboard lists in browser

**Comment by BrayanArrieta** [comment]
Hello, I tried redirect to the share dashboards url with the `v0.28.1`, and I haven't any problem like that, maybe can be fix with the version.

**Comment by syazwan0913** [comment]
I see. Thank you

**Comment by mistercrunch** [comment]
What did the URL look like?

**Comment by mistercrunch** [comment]
Could be related to an auto-login + bad redirect

**Comment by syazwan0913** [comment]
The url look like this: [http://0.0.0.0:8089/r/12](http://0.0.0.0:8089/r/12)
