### ISSUE TITLE
Problem: node version is v4 but not v8

### ISSUE THREAD

**Issue by kk580kk** [apache/incubator-superset#6395]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
https://github.com/apache/incubator-superset/tree/70327ca42c805f673ac9fb82934d8563aeb68aa8

### Expected results
Dockerfile build success

### Actual results
Docker build failed because node version is v4

### Steps to reproduce
bash -x docker-build.sh

relate to 
https://github.com/apache/incubator-superset/pull/6303
https://github.com/apache/incubator-superset/pull/6387

I don't know how to fix this problem in master branch .
I have fixed this problem by unofficial docker base images but didn't match this project requirements

**Comment by BrayanArrieta** [comment]
Hello, I have a problem today with run build with node and have the `v8.12.0`. Do you pull the last changes in the master branch, Maybe the errors could be related.

**Comment by kk580kk** [comment]
Maybe already fixed by newer version
