### ISSUE TITLE
some folders and files are missing in src folder 

### ISSUE THREAD

**Issue by krishna9626** [apache/incubator-superset#6396]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.0

### Expected results
Need to know any changes in the SRC folder 

### Actual results
In the SRC folder, some folders are missing ( modules, explore, profile etc.,) 

### Steps to reproduce

While installing 
 superset version <=0.27.0
In src Directory we can saw some files and folders  
 
![27version](https://user-images.githubusercontent.com/36255856/48542562-7e5d5200-e8e5-11e8-8448-5371ab57196a.png)

but after 0.28.0 we can see only following directories 

![28version](https://user-images.githubusercontent.com/36255856/48542605-9af98a00-e8e5-11e8-8747-2190f6c84b5a.png)

I didn't find the dates.js, utils.js file in the complete application. But when I download the superset in the zip file format. I can see those files. So, please help me to find src folder containing location or how to keep the src folder as same before 0.27.0 version.

**Comment by haojian20161987** [comment]
me too! I can't find src folder
