### ISSUE TITLE
Upload csv with replace option - error

### ISSUE THREAD

**Issue by nishanthDS** [apache/incubator-superset#6402]
Make sure these boxes are checked before submitting your issue - thank you!

- [ None] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ yes] I have reproduced the issue with at least the latest released version of superset.
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
.28
tested with the latest also

### Expected results

when I use upload csv with replace option for one of the existing tables, I expect the table is dropped first and created again.

### Actual results
I see this error instead
'Table name training already exists. Please pick another'

### Steps to reproduce
1. upload a csv as a table
2. upload the same csv and same table name with replace option 

![upload_csv_error](https://user-images.githubusercontent.com/10793114/48598493-1c562880-e989-11e8-9bf2-f948775a7a4d.png)

**Comment by lijiangwei** [comment]
I have the save problem whether the table is fail,replace or append.

**Comment by hfuthippop** [comment]
> I have the save problem whether the table exists is fail,replace or append.

Data can enter the table, but the prompt is misleading.

**Comment by suraj-raghupathi** [comment]
We are getting this prompt message wrong because of integrity error where in it is trying to insert table related information into metadata tables.
