### ISSUE TITLE
How to disable superset authentication

### ISSUE THREAD

**Issue by ayssi** [apache/incubator-superset#6404]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Access to the dashborad without authentication

### Actual results
Superset is still asking for login and password

### Steps to reproduce
In my config.py I've set AUTH_ROLE_PUBLIC to "Public" and give all the necessary grants to this Public role

**Comment by ayssi** [comment]
In my config.py I've set AUTH_ROLE_PUBLIC to "Public" and give all the necessary grants to this Public role but the application still asking for login and password
I've superset 0.28.1 version.
Thanks.

**Comment by akuckartz** [comment]
You forgot to check these boxes: "I have checked the superset logs for python stacktraces and included it here as text if there are any.
 I have reproduced the issue with at least the latest released version of superset.
 I have checked the issue tracker for the same issue and I haven't found one similar."

**Comment by ayssi** [comment]
Ok the boxe is checked
