### ISSUE TITLE
Create admin

### ISSUE THREAD

**Issue by MB-ADS** [apache/incubator-superset#6415]

**Comment by mbadrADS** [comment]
When I  tried to create an admin user I had this error:
   " Was unable to import superset Error: cannot import name 'quoted_name' "
   Anyone have an idea about this issue?
   
   Thanks

**Comment by ganesh3** [comment]
I too am getting the same error. Can someone please help?

**Comment by mistercrunch** [comment]
This Github issue has pretty much no context at all. Did you follow the installation steps?

**Comment by mistercrunch** [comment]
Actually, please reopen an issue and fill the template this time.

**Comment by DandikUnited** [comment]
@ganesh3  @MB-ADS @mistercrunch This is sqlachemy error. Updating your SQL alchemy with `pip install -U sqlalchemy` v1.1.7 > v1.3.1 solved this for me

**Comment by krehl** [comment]
General answer: Don´t use pip, but install from this repository.
