### ISSUE TITLE
CORS not working as documented

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#6418]
### Superset version
0.28.1

using docker image
with flask-cors==3.0.3

### Expected results
able to load dashboard in an iframe

### Actual results
Firefox displays : 
'Load denied by X-Frame-Options: .... '

Chrome displays :
Refused to display 'https://.....' in a frame because it set 'X-Frame-Options' to 'sameorigin'

### Steps to reproduce

I've added this option to my configuration py file :
```ENABLE_CORS = True```

I'm 100% sure the right file is in use (I also ave OAuth for instance set in the cofig file, and it is working)

I checked that `superset[cors]` IS installed in the image (I raun pip install superset[cors] inside the container, which told me eveything was already set)

I refer to this documentation : https://superset.incubator.apache.org/installation.html#cors

If something should be added in `CORS_OPTIONS` *please* at least give an example, don't throw readers to parent full documentation.

Thank you for any advice !
I'm pretty sure it's not a bug but a configuration issue on my side, but I simply can't find a configuration explanation to allow cross-origin from any url.

**Comment by squalou** [comment]
note that if I add this on top of CORS_ENABLE = True :
```
HTTP_HEADERS = {}
```
then it works

... is this expected ?

**Comment by BrayanArrieta** [comment]
Hello just change the `
HTTP_HEADERS={'X-Frame-Options':'SAMEORIGIN'} 
` in the config.py or in your custom config and set X-Frame-Options to 'Allow' for all or the origin taht you want.

**Comment by BrayanArrieta** [comment]
I want load dashboard in an iframe like you, what url you are tried @squalou ??

**Comment by squalou** [comment]
I've set this : 
```https://my-domain.com/superset/dashboard/my-dashboard/?standalone=true```

btw : I didn't dind HTTP_HEADERS= ... in my custom config file, so I suppose it's set by default (for security reasons, qould make sense).
The issue is juste that documentation is poor / misleading.

**Comment by graceguo-supercat** [comment]
See this line in config.py:
https://github.com/apache/incubator-superset/blob/0584e3629feaad17dc1391760aeb8a0cf6e8832f/superset/config.py#L316

set HTTP_HEADERS = {} is the right way for embed Superset chart in a iframe.
CORS settings are used for 3rd party website that calls Superset backend without iframe.

**Comment by squalou** [comment]
Ok !
Thanks for the clarification.

Closing this.

**Comment by giacomochiarella** [comment]
Even by using HTTP_HEADERS, DEFAULT_HTTP_HEADERS and OVERRIDE_HTTP_HEADERS, x-frame-options is still set to SAMEORIGIN. I've also tried to add Content-Security-Policy to some value but also this one is overridden somewhere. We have Superset in an ec2 instance and even using ip to directly make requests, it does not work, always headers are set different values than the ones I put in config

**Comment by rajakumar-durga** [comment]
I am using the  apache/superset:latest docker version, and override the HTTP HEADER like to disable the cross origin. when I superset in the iframe like below. But still seeing the cross origin error

<iframe src="http://localhost:8087/login/" target="_self"></iframe>

ENABLE_CORS = True
CORS_ALLOW_HEADERS = "*"

HTTP_HEADERS = {}

**Comment by loretoparisi** [comment]
> Ok ! Thanks for the clarification.
> 
> Closing this.

I'm getting the same error when the http headers override - see [here](https://github.com/apache/superset/issues/27376)

**Comment by jackgray** [comment]
Can we request more documentation on iframe embedding? I've been tracking these issues back to 2018 and they're the same as now. 

I modify superset_config.py as instructed by the official documentation, but the changes do not take effect. I am working with a clone of the git project as instructed. Requesting the page it is embedded returns with {'X-Frame-Options':'SAMEORIGIN'} even though I changed the config file and tore down and rebuilt Superset from docker compose.
