### ISSUE TITLE
Can I point chart to another datasource?

### ISSUE THREAD

**Issue by invenis-paris** [apache/incubator-superset#6420]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28

### Expected results
When exploring a Chart, i need to change the data source to another table

### Actual results
It is no ore possible to select another table

### Steps to reproduce
Create a chart, explore it, click on table name under Datasource

**Comment by pedrochavesjsl** [comment]
I believe this relates to this recent PR:

https://github.com/apache/incubator-superset/pull/6430

As an intermediate hack, you can see that the URL for a chart contains the JSON data, which you can edit:

https://superset.selectdata.com/superset/explore/?form_data={"datasource"%3A"21__table"...}

By changing the table ID, the chart's datasource will change accordingly.
