### ISSUE TITLE
Fix time range view on dashboard

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#6426]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0dev

### Steps to reproduce

I set the time range for the Filter Box in explore is "No Filter". But when on dashboard by default it will show "Last Week". So how to fix it?

![17](https://user-images.githubusercontent.com/28984703/48938136-370d3c00-ef4b-11e8-9e8c-ca708f6b4436.JPG)

**Comment by bestao88** [comment]
I have checked from 0.28 to 0.29.0RC7, this bug has not fixed.
I suggested to escalate this bug to top priority because it will lead un-using for whole Superset.

**Comment by mlboy** [comment]
+1

**Comment by xwydq** [comment]
I met the same problem

**Comment by mistercrunch** [comment]
Can't reproduce on `master`

**Comment by smith01s** [comment]
I am also having the same problem.  I also suffer from the filter box disappearing from the dashboard when selecting a new time range.

**Comment by maxniranga** [comment]
Cant we change "Relative to today" to "Relative to now"? Because Relative to today starts showing data from present day's 00:00:00 right?

**Comment by bestao88** [comment]
This bug has not been fixed, why marked as stale?

**Comment by nabinkhadka** [comment]
This issue should be solved asap because this is very very misleading.

**Comment by tmswfrk** [comment]
Can we have someone take a look at this? We've had this as a problem for a few months now and this is the most recent place I've seen any update on the subject.

**Comment by vialcollet** [comment]
Hi all
I am having the same issue.
Whatever selection I have on my filter box chart, the dashboard defaults to "last week".
Is there any plan to fix this or is there a workaround?
Maybe I am mssing something.
Thanks

**Comment by vialcollet** [comment]
I found that if we follow these steps, we can fix this issue:

- Display the dashboard
- Select the appropriate time range
- Edit the dashboard
- Fake change
- Save

**Comment by CzyerChen** [comment]
I met the same problem, not only time range.

Version: 0.38.1

Problems：
1. set up "No filter" in chart, and import into a Dashboard, the default filter has been changed(like one time range filter at one moment cached by Superset forever). 
2. I can not choose the right point, I have to choose `No filter` then `real time range` manually.
<img width="902" alt="image" src="https://github.com/apache/superset/assets/22817918/02322537-2503-4b40-9ddd-6b3a362c1c46">

How to resolve:
1. edit `Dashboard` config
2. edit `JSON Metadata`, params from `"default_filters": "{\"11\": {\"__time_range\": \"2023-10-23T00:00:00 : 2023-10-25T00:00:00\"}}` to `"default_filters": "{\"11\": {\"__time_range\": \"No filter\"}}`
3. save config, then cached time range problem fixed.

**Comment by CzyerChen** [comment]
I met the same problem, not only time range.

Version: 0.38.1

Problems：
1. set up "No filter" in chart, and import into a Dashboard, the default filter has been changed(like one time range filter at one moment cached by Superset forever). 
2. I can not choose the right point, I have to choose `No filter` then `real time range` manually.
<img width="902" alt="image" src="https://github.com/apache/superset/assets/22817918/02322537-2503-4b40-9ddd-6b3a362c1c46">

How to resolve:
1. edit `Dashboard` config
2. edit `JSON Metadata`, params from `"default_filters": "{\"11\": {\"__time_range\": \"2023-10-23T00:00:00 : 2023-10-25T00:00:00\"}}` to `"default_filters": "{\"11\": {\"__time_range\": \"No filter\"}}`
3. save config, then cached time range problem fixed.
