### ISSUE TITLE
Cannot install superset (Mac 10.14)

### ISSUE THREAD

**Issue by PushHandle** [apache/incubator-superset#6429]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if there are any.

- [√] I have reproduced the issue with at least the latest released version of superset.

- [√] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Trying to install the latest stable version on Mac OS 10.14 (Mojave).
I previously successfully installed v 25.0 but have had trouble upgrading.

### Expected results
Follow instructions here and install: https://superset.incubator.apache.org/installation.html 
I previously successfully installed v 25.0 but have had trouble upgrading on the same machine.

### Actual results

After running 'pip install superset' seeing this returned at the tail end:

  Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build python-geohash sasl cchardet
Installing collected packages: idna, six, pycparser, cffi, asn1crypto, cryptography, Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, flask, flask-caching, python-geohash, humanize, isodate, flask-compress, geographiclib, geopy, colorama, future, sqlalchemy, sqlalchemy-utils, pathlib2, docutils, jmespath, python-dateutil, botocore, s3transfer, boto3, pyhive, thrift, sasl, thrift-sasl, vine, amqp, kombu, billiard, pytz, celery, polyline, simplejson, contextlib2, numpy, pandas, chardet, certifi, urllib3, requests, pydruid, unicodecsv, parsedatetime, webencodings, bleach, gunicorn, WTForms, flask-wtf, defusedxml, python3-openid, Flask-OpenID, Flask-SQLAlchemy, Flask-Login, babel, Flask-Babel, flask-appbuilder, pyyaml, jsonschema, jsonlines, ijson, cchardet, linear-tsv, et-xmlfile, jdcal, openpyxl, xlrd, tabulator, rfc3986, tableschema, markdown, tornado, flower, unidecode, python-editor, Mako, alembic, flask-migrate, sqlparse, superset
  Running setup.py install for python-geohash ... error
    Complete output from command /Users/michaelcurry/Projects/superset/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/dx/r2gd9l9d7j19v83wqnnr2j0w0000gn/T/pip-install-nnemd12o/python-geohash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/dx/r2gd9l9d7j19v83wqnnr2j0w0000gn/T/pip-record-npgbtk5r/install-record.txt --single-version-externally-managed --compile --install-headers /Users/michaelcurry/Projects/superset/venv/bin/../include/site/python3.6/python-geohash:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    copying geohash.py -> build/lib.macosx-10.6-intel-3.6
    copying quadtree.py -> build/lib.macosx-10.6-intel-3.6
    copying jpgrid.py -> build/lib.macosx-10.6-intel-3.6
    copying jpiarea.py -> build/lib.macosx-10.6-intel-3.6
    running build_ext
    building '_geohash' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/src
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DPYTHON_MODULE=1 -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/geohash.cpp -o build/temp.macosx-10.6-intel-3.6/src/geohash.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    g++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/src/geohash.o -o build/lib.macosx-10.6-intel-3.6/_geohash.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/Users/michaelcurry/Projects/superset/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/dx/r2gd9l9d7j19v83wqnnr2j0w0000gn/T/pip-install-nnemd12o/python-geohash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/dx/r2gd9l9d7j19v83wqnnr2j0w0000gn/T/pip-record-npgbtk5r/install-record.txt --single-version-externally-managed --compile --install-headers /Users/michaelcurry/Projects/superset/venv/bin/../include/site/python3.6/python-geohash" failed with error code 1 in /private/var/folders/dx/r2gd9l9d7j19v83wqnnr2j0w0000gn/T/pip-install-nnemd12o/python-geohash/

### Steps to reproduce

1. Tried to upgrade without success
2. Uninstalled superset 
3. Created new destination to begin installation from scratch : https://superset.incubator.apache.org/installation.html 
4. Got the above error when running 'pip install superset'

**Comment by PushHandle** [comment]
Looks like the top two issues here are relevant: https://github.com/hkwi/python-geohash/issues

1. install error at python 3.6.5
2. pip install does not work with MacOS Mojave and XCode 10

**Comment by aboganas** [comment]
ensure that xcode command line tools is installed by running 
`xcode-select --install`

also make sure you open Xcode at least once to accept the agreement

finally I suggest using brew to install python 3.3.6 and then creating a python virtual environment to install and run superset within it

**Comment by PushHandle** [comment]
Thanks @aboganas for the suggestion.  

I updated xcode but I do not think I can downgrade to python 3.3.6 since: "Superset has deprecated support for Python 2.* and supports only ~=3.6 to take advantage of the newer Python features and reduce the burden of supporting previous versions. We run our test suite against 3.6, but running on 3.7 should work as well."

When trying to install from python 2.7 I get this error:

    Complete output from command python setup.py egg_info:
    Sorry, Python < 3.6 is not supported
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-MTSX_u/superset/

**Comment by aboganas** [comment]
sorry meant to say 3.6.*

you better rely on virtual environment. try the following

install brew
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
 then install pyenv 
```
brew update
brew install pyenv
brew install pyenv-virtualenv
```
then add to ~/.bash_profile the following
```
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
```
after that install build environment
```
brew install openssl readline sqlite3 xz zlib
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
then install specific python version in the virtual environment
`pyenv install 3.6.6`

then create a virtual environment
`pyenv virtualenv 3.6.6 env`

after that activate the newly create env
`pyenv activate env`

finally inside your active virtual environment you can install superset
`pip install superset`

**Comment by CloudPai** [comment]
Amazing!
I had the same problem, and solved it by your latest reply.
Thanks! @aboganas

**Comment by mcbitmex** [comment]
Thanks @aboganas I am now seeing a new error:
------
ModuleNotFoundError: No module named '_scproxy'
------

Any thoughts?

**Comment by weiqiLee** [comment]
@PushHandle I had the same question,Could you tell me how to solve the problem?

**Comment by momentsinabox** [comment]
Thanks! @aboganas

**Comment by knownact** [comment]
I have the same Issue and resolved using method by
https://blog.driftingruby.com/updated-to-mojave/

short story:
open /Library/Developer/CommandLineTools/Packages/
install macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by kadnan** [comment]
> Looks like the top two issues here are relevant: https://github.com/hkwi/python-geohash/issues
> 
> 1. install error at python 3.6.5
> 2. pip install does not work with MacOS Mojave and XCode 10

What exactly are those issues?

**Comment by kadnan** [comment]
I was able to install on Python 3.6.x with the help of `conda`. It seems `pip` does not have an updated `geohash` lib.

`conda install -c conda-forge python-geohash`

**Comment by surevs** [comment]
> conda install -c conda-forge python-geohash

`RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.` This is coming up with Anaconda - were there any other luck to move further while sticking to anaconda environment . Here are the my current  conda environment details

` active environment : base
    active env location : /Users/revanth/anaconda3
            shell level : 1
       user config file : /Users/revanth/.condarc
 populated config files : /Users/revanth/.condarc
          conda version : 4.8.0
    conda-build version : 3.18.8
         python version : 3.7.3.final.0`
