### ISSUE TITLE
error in building superset

### ISSUE THREAD

**Issue by ganesh3** [apache/incubator-superset#6440]
Hi,

I am unable to build superset because of the below error. Can someone help? 

steps followed as per: https://superset.incubator.apache.org/installation.html#python-virtualenv

error: could not create 'build\bdist.win-amd64\wheel\.\superset\static\assets\dist\vendors-deckgl\layers\arc-deckgl\layers\geojson-deckgl\layers\grid-deckgl\layers\hex-deckgl\layers\p-39b91eb9.81565bc93ff56be4e334.chunk.js': No such file or directory

  ----------------------------------------
  Failed building wheel for superset
  Running setup.py clean for superset
  Running setup.py bdist_wheel for sqlalchemy ... done
  Stored in directory: C:\Users\ganes\AppData\Local\pip\Cache\wheels\86\c8\99\8d6049a373070743a79ada4cf9798f8130cc8e2dfcd66e0e9d
  Running setup.py bdist_wheel for unicodecsv ... done
  Stored in directory: C:\Users\ganes\AppData\Local\pip\Cache\wheels\a6\09\e9\e800279c98a0a8c94543f3de6c8a562f60e51363ed26e71283
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: C:\Users\ganes\AppData\Local\pip\Cache\wheels\f2\9a\90\de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
  Running setup.py bdist_wheel for openpyxl ... done
  Stored in directory: C:\Users\ganes\AppData\Local\pip\Cache\wheels\59\44\27\63b211425501ad51d197ff8ed00e9e469e38b9e516cb69b1c2
  Running setup.py bdist_wheel for et-xmlfile ... done
  Stored in directory: C:\Users\ganes\AppData\Local\pip\Cache\wheels\2a\77\35\0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
Successfully built sqlalchemy unicodecsv pycparser openpyxl et-xmlfile
Failed to build superset

Regards
Ganesh Bhat

**Comment by mistercrunch** [comment]
We don't really support Windows, you can use a Linux VM or a remote Linux box on the cloud.

**Comment by atifahsan** [comment]
Faced a similar error. It was due to 260 character path limit. Check this [link](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) to disable this limitation.

**Comment by huyaming** [comment]
zcattacz, you are very good!

**Comment by 387712365** [comment]
my question is the same as yours. Could you tell me  how to specify a short name build directory，thank you
