### ISSUE TITLE
Clearing a metric in big number and adding a new one generates errors and a blank chart

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6447]
If you clear a metric on a big number chart, some js errors show up and when you add a new metric and run the query, the resulting chart is blank (although the response returned successfully).

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

```
Uncaught TypeError: Cannot read property 'label' of null
    at transformProps (transformProps.js?7a0c:31)
    at eval (SuperChart.jsx?6329:52)
    at eval (index.js?1b8a:70)

react-dom.development.js?61bb:14550 The above error occurred in the <LoadableComponent> component:
    in LoadableComponent (created by SuperChart)
    in div (created by SuperChart)
    in SuperChart (created by Chart)
    in div (created by Chart)
    in ErrorBoundary (created by Chart)
    in Chart (created by Connect(Chart))
    in Connect(Chart) (created by ParentSize)
    in div (created by ParentSize)
    in ParentSize (created by ExploreChartPanel)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by ExploreChartPanel)
    in div (created by ExploreChartPanel)
    in ExploreChartPanel (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in ExploreViewContainer (created by Connect(ExploreViewContainer))
    in Connect(ExploreViewContainer) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
```

### Superset version
0.29, master

### Expected results
When you clear a metric and set a new one the resulting chart is blank.

### Actual results
When you clear a metric and set a new one there are no errors. If there are errors, an error message should be displayed on the chart.

### Steps to reproduce
Create a big number chart, clear the metric, set a new one, hit run.

@kristw @graceguo-supercat

**Comment by mistercrunch** [comment]
It should be a matter of setting `clearable: false` on the control.

**Comment by michellethomas** [comment]
@mistercrunch It looks like clearable prevents you from clearing the control? Big number uses the metric control, which you should be able to clear and add a new metric.
