### ISSUE TITLE
docker-build.sh is missing

### ISSUE THREAD

**Issue by jaklan** [apache/incubator-superset#6462]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
There is **docker-build.sh** file in **contrib/docker** or there is a new installation instruction.

### Actual results
There is no **docker-build.sh** file in **contrib/docker**, so I can't install the application using these installation steps:
https://superset.incubator.apache.org/installation.html

### Steps to reproduce
Just try to install.

**Comment by emeraldbay** [comment]
Please check commit 02aa3c6395a381e59dced848df55cb1daf733e95.
Obviously the doc is not updated.

@@ -43,22 +43,29 @@ If you know docker, then you're lucky, we have shortcut road for you to
 initialize development environment: ::

     git clone https://github.com/apache/incubator-superset/
-    cd incubator-superset
-    cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
-    cp contrib/docker/superset_config.py superset/
-    bash -x docker-build.sh
-    docker-compose up -d
-    docker-compose exec superset bash
-    bash docker-init.sh
+    cd incubator-superset/contrib/docker
+    # prefix with SUPERSET_LOAD_EXAMPLES=yes to load examples:
+    docker-compose run --rm superset ./docker-init.sh
+    # you can run this command everytime you need to start superset now:
+    docker-compose up

**Comment by kakoni** [comment]
Documentation has been updated (https://github.com/apache/incubator-superset/blob/master/docs/installation.rst) but the actual page hasn't been updated yet

**Comment by rngadam** [comment]
```
rngadam-mac:docker rngadam$ docker-compose run --rm superset ./docker-init.sh
Starting superset_postgres_1 ... done
Starting superset_redis_1    ... done
Building superset
ERROR: Dockerfile parse error line 46: unknown instruction: &&
```

missing backlash in the Dockerfile

**Comment by kakoni** [comment]
https://github.com/apache/incubator-superset/pull/6567/files

**Comment by rngadam** [comment]
ended using  prebuilt https://github.com/amancevice/superset instead

**Comment by chakshu222** [comment]
While installing using the new documentation I am getting this error in the last step
```docker-compose up```
```superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 95, in find_best_app
superset_1  |     module=module.__name__
superset_1  | flask.cli.NoAppException: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.
superset_1  | 127.0.0.1 - - [02/Jan/2019 09:58:15] "GET /health HTTP/1.1" 500 -
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 95, in find_best_app
superset_1  |     module=module.__name__
superset_1  | flask.cli.NoAppException: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.
superset_1  | 127.0.0.1 - - [02/Jan/2019 09:58:46] "GET /health HTTP/1.1" 500 -
superset_1  | 127.0.0.1 - - [02/Jan/2019 09:59:16] "GET /health HTTP/1.1" 500 -
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 95, in find_best_app
superset_1  |     module=module.__name__
superset_1  | flask.cli.NoAppException: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.
superset_1  | 127.0.0.1 - - [02/Jan/2019 09:59:46] "GET /health HTTP/1.1" 500 -
superset_1  | 127.0.0.1 - - [02/Jan/2019 10:00:16] "GET /health HTTP/1.1" 500 -
superset_1  | 127.0.0.1 - - [02/Jan/2019 10:00:46] "GET /health HTTP/1.1" 500 -
superset_1  | 127.0.0.1 - - [02/Jan/2019 10:01:16] "GET /health HTTP/1.1" 500 -
```
These are first few error messages, getting same errors repeatedly

How to fix this ?

**Comment by chakshu222** [comment]
Refer this if getting above issue [https://github.com/apache/incubator-superset/issues/6543](url)
