### ISSUE TITLE
how to connect to HiveServer2 with ssl?

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#6463]
- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Superset is Able to connect to HiveServer2 with ssl options

### Actual results
Superset gets Thrift socket error

### Steps to reproduce
Install hive with ssl, verify beeline connection with ssl=false can't connect, verify beeline connection with  ssl=true;sslTrustStore=actual;trustStorePassword=actual can connect, attempt hive connection in superset as seems no way to specify ssl options on hive connection

**Comment by tooptoop4** [comment]
hey bot dont close this

**Comment by tooptoop4** [comment]
@kristw any idea on this one?

**Comment by Thoris** [comment]
Hello all, does anybody know the solution?

**Comment by tooptoop4** [comment]
@kristw any idea?
