### ISSUE TITLE
"Dashboard level access control" is really really needed !

### ISSUE THREAD

**Issue by cherrylynn** [apache/incubator-superset#6467]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.27.0

### Expected results
Add permissions at the dashboard level.

- Create permissions for each dashboard with the format "dashboard access on [dashboard_title](dash_id:x)"
- The name of the permission is updated if the dashboard title is changed.
- Add a dashboard permission to a role via the Edit Role form, or, for convenience, add a role to a dashboard via the Edit Dashboard form.
- Optionally, add a default role to be added to each new dashboard created from a slice.
- The permission "all_dashboard_access" is added to Admin, Alpha, and Gamma roles.
- To allow private dashboards, remove "all_dashboard_access" from a role. This role will then only have access to the dashboards specified. Add a dashboard's permission to a role to "publish" it.
- Note that these permissions do not apply to slices. To make the data in a dashboard truly private, use dashboard permissions with a read only role that has no slice/explore access.

Reference: https://github.com/apache/incubator-superset/pull/5099

### Actual results
Only can restrict access to a subset of data sources or some metrics.

### Steps to reproduce
None.

**Comment by csc5k** [comment]
+1 yes

**Comment by jeffcumt** [comment]
所以现在还是不能给不同的用户分配看不同的看板吗，并且不能修改

**Comment by mistercrunch** [comment]
@jeffcumt let's use english as the main language for this repo

**Comment by yuezhiling2** [comment]
@mistercrunch So what's going on this issue ? No plan or in progress ?

**Comment by roadie-james** [comment]
+1 for this feature
