### ISSUE TITLE
Make Superset Dashboard adapts layout on mobile devices

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#6472]
Superset version
0.28.1 、0.29  and 0.999dev ，in dashboard V2

Expected results
When view on mobile device or other smart screen, it makes self-adaptive UI with useable fonts, images, graphs

 Actual results
![2](https://user-images.githubusercontent.com/1625023/49325155-9e914000-f578-11e8-8b25-b0f015834118.png)

![2](https://user-images.githubusercontent.com/1625023/49325039-6852c100-f576-11e8-87dc-221d2cf5e757.jpg)

![1](https://user-images.githubusercontent.com/1625023/49325045-73a5ec80-f576-11e8-95e6-4aa1afec9b39.png)

 Steps to reproduce

chart explore and dashboard view on mobile phone or other smart screen

**Comment by toop** [comment]
Waiting for repair. Thanks!

**Comment by tahirawan4** [comment]
Any updates on this one?

**Comment by kalimuthu123** [comment]
Hi ,

Any update on this feature level.

**Comment by itsik-avidan** [comment]
+1

**Comment by tonyphong** [comment]
+1

**Comment by zzfjean** [comment]
+1 this would be super useful

**Comment by userxiaozhu** [comment]
+1

**Comment by wushancool** [comment]
+1

**Comment by amravazzi** [comment]
+1

**Comment by memes-forever** [comment]
up! +1

**Comment by rafaeldietrich** [comment]
+1

**Comment by dany-2314** [comment]
Hi, if this feature is still not implemented, my team would like to implement it. By the looks of this thread I'm assuming it was never implemented. Please let me know if we should open a new issue regarding the Mobile/responsive styling (and feature hiding) for a mobile dashboard consumption experience. 

Thank you!

**Comment by jisaitua** [comment]
Maybe PR #37141 can help?
