### ISSUE TITLE
Cannot browse superset pages on IE 8

### ISSUE THREAD

**Issue by wenchma** [apache/incubator-superset#6475]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

![image](https://user-images.githubusercontent.com/8329027/49348840-c4d2ef00-f6e2-11e8-9f6b-d6648f96190d.png)

it reports the following errors:
* syntax error
* expected identifier, string or number
* object not support properties or method

### Superset version
0.28.1

### Expected results
can browse superset pages on IE8

### Actual results
failed

### Steps to reproduce

open your superset site on IE 8

**Comment by mistercrunch** [comment]
IE8 was released in 2009

**Comment by mistercrunch** [comment]
If you know anyone who still uses IE8, it's time to have a serious conversation with them.

**Comment by wenchma** [comment]
@mistercrunch 👍
