### ISSUE TITLE
Clarify licensing of external code

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#6482]
From Alan Gates

> On the code in the `vendors` folder, do we know where that came from?  If it
was not contributed to Superset we need to 
1.  check that it's ok to have it at all (ie, we have the author's blessing)
2.  figure out what license the author released it under
3.  put the license and copyright information in the `LICENSE` and `NOTICE` files.

> Same questions apply for code in the `visualizations` folder.  With just a
quick look through there I didn't see any licenses, notices, copyright
statements, etc.

**Comment by bolkedebruin** [comment]
See #6496

**Comment by kristw** [comment]
Resolved by #6738
