### ISSUE TITLE
docker COPY command in Dockerfile not documented

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#6486]
see this：
USER superset
...
COPY --chown=superset:superset superset superset 
seemd not in docker's documentation 
ERROR: Unknown flag: chown
so I confused why using this and USER superset actually doesn't have the privilege to do this

[root@docker01 ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-84.git07f3374.el7.centos.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Fri Nov 30 02:48:45 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-84.git07f3374.el7.centos.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Fri Nov 30 02:48:45 2018
 OS/Arch:         linux

**Comment by anddyhuaa** [comment]
thanks

**Comment by hanyan007** [comment]
same promble, it`s work.  Thanks @anddyhuaa.
