### ISSUE TITLE
docker cryptography version seems old in requirements.txt

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#6487]
so how to update cryptography and ssl version to match better？if not familiar with cryptography and ssl version release----- spend much time on this everytime
e.g
txt : cryptography==1.9
latest : libssl-dev amd64 1.1.0j
**NOT MATCHED 
ERROR MSG:**
Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Building wheels for collected packages: billiard, cchardet, cryptography, et-xmlfile, flask-appbuilder, flask-babel, flask-compress, flask-login, flask-openid, flower, future, humanize, itsdangerous, linear-tsv, mako, markupsafe, openpyxl, parsedatetime, pycparser, pydruid, pyhive, python-editor, python-geohash, pyyaml, sasl, simplejson, sqlalchemy-utils, sqlalchemy, thrift-sasl, thrift, tornado, unicodecsv, flake8-quotes, ipdb, mysqlclient, wsgigzip, backcall, wrapt
  Running setup.py bdist_wheel for billiard: started
  Running setup.py bdist_wheel for billiard: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/43/a5/a3/d5513d0baa904819b2ee9c58ff594a0c834cd6fcd19d43d9ce
  Running setup.py bdist_wheel for cchardet: started
  Running setup.py bdist_wheel for cchardet: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/89/82/3c/03b5e077af1cf528321d2ef2d7d40311ba1192d17f5cc64e25
  Running setup.py bdist_wheel for cryptography: started
^[[91m  Failed building wheel for cryptography
^[[0m  Running setup.py bdist_wheel for cryptography: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dyqi7uzj/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-fkil_91x --python-tag cp36:
  warning: no previously-included files found matching 'setup.pyc'
  warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
  warning: no previously-included files matching 'lextab.*' found under directory 'tests'
  warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
  warning: no previously-included files matching 'lextab.*' found under directory 'examples'
  zip_safe flag not set; analyzing archive contents...
  pycparser.ply.__pycache__.lex.cpython-36: module references __file__
  pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
  pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
  pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
  pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
  pycparser.ply.__pycache__.ygen.cpython-36: module references __file__

  Installed /tmp/pip-install-dyqi7uzj/cryptography/.eggs/pycparser-2.19-py3.6.egg
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/cryptography
....

  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing entry points to src/cryptography.egg-info/entry_points.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files matching '*' found under directory 'vectors'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.6/_padding.c'
  creating build/temp.linux-x86_64-3.6
  generating cffi module 'build/temp.linux-x86_64-3.6/_constant_time.c'
  generating cffi module 'build/temp.linux-x86_64-3.6/_openssl.c'
  building '_openssl' extension
  creating build/temp.linux-x86_64-3.6/build
  creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o
  build/temp.linux-x86_64-3.6/_openssl.c:911:6: error: conflicting types for ‘BIO_callback_ctrl’
   long BIO_callback_ctrl(
        ^~~~~~~~~~~~~~~~~
  In file included from /usr/include/openssl/asn1.h:16:0,
                   from build/temp.linux-x86_64-3.6/_openssl.c:530:
  /usr/include/openssl/bio.h:551:6: note: previous declaration of ‘BIO_callback_ctrl’ was here
   long BIO_callback_ctrl(BIO *b, int cmd, BIO_info_cb *fp);
        ^~~~~~~~~~~~~~~~~
  build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_ASN1_STRING_data’:
  build/temp.linux-x86_64-3.6/_openssl.c:14529:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     return ASN1_STRING_data(x0);
     ^~~~~~
  In file included from /usr/include/openssl/e_os2.h:13:0,
                   from build/temp.linux-x86_64-3.6/_openssl.c:507:
  /usr/include/openssl/asn1.h:553:1: note: declared here
   DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
   ^
  build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_ASN1_STRING_data’:
  build/temp.linux-x86_64-3.6/_openssl.c:14552:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     { result = ASN1_STRING_data(x0); }

**Comment by pc-tradelab** [comment]
I solved my problem with cryptography thanks to this: https://github.com/apache/incubator-superset/issues/4870#issuecomment-444189653

**Comment by anddyhuaa** [comment]
thanks, recording versions in text I think is not good solution to docker 's building,cause it doesn't update always in no time.you should not download the ssl libs from the cloud repository for the latest version but cryptography== (not updated) in the txt file
