### ISSUE TITLE
docker build fail when using yarn

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#6488]
I wanna ask where and how to see the log details（exit code 137，what！） when superset container not started：

File /home/superset/superset/assets/src/../backendSync.json was saved!
Done in 4.81s.
yarn run v1.12.3
$ NODE_ENV=production webpack --mode=production --colors --progress
clean-webpack-plugin: /home/superset/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 92% chunk asset optimization TerserPluginKilled                                            
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
**error Command failed with exit code 137**.
ERROR: compose.cli.main.main: Service 'superset' failed to build: The command '/bin/sh -c cd superset/assets     && yarn --non-interactive --frozen-lockfile --link-duplicates     && yarn run sync-backend     && yarn run build     && rm -rf node_modules     && yarn cache clean' returned a non-zero code: 1

**Comment by anddyhuaa** [comment]
I have solved the problem myself because of lack of memory and high cpu usage when building ,so the cloud provider monitoring this will kill your programs, what! , it seems not easy but complicated

**Comment by krdeepak** [comment]
+1
