### ISSUE TITLE
docker babel-node not found

### ISSUE THREAD

**Issue by anddyhuaa** [apache/incubator-superset#6489]
/bin/sh: 1: babel-node: not found
where is the babel-node？seem like superset needs to execute the command babel-node

**Comment by anddyhuaa** [comment]
/bin/sh: 1: babel-node: not found  
where is the babel-node？seem like superset needs to execute babel-node，but it not copy to the docker

**Comment by Ryanstall** [comment]
I get the same error ,can anyone help me ?

> superset@0.999.0-dev sync-backend /home/superset/superset/assets
> babel-node --presets env src/syncBackend.js

sh: 1: babel-node: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! superset@0.999.0-dev sync-backend: `babel-node --presets env src/syncBackend.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev sync-backend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by krdeepak** [comment]
Same error on ubuntu using docker.

**Comment by manbuyun** [comment]
How to resolve this probleam?

**Comment by manbuyun** [comment]
The issue is the same as mine

**Comment by rontev** [comment]
Same error for me. 
Any help on how to fix this would be awesome.

**Comment by leogreyz** [comment]
Looks like this PR might have caused the issue: https://github.com/apache/incubator-superset/pull/6541
babel-cli got upgraded from 6.x.x to 7.x.x which doesn't include the babel-node executable any more.

**Comment by rajkumargithub** [comment]
Even after including the babel node separately, I couldn't resolve it. So i had to install @babel/preset-env, @babel/preset-react 
`npm install -- save-dev @babel/node
 npm install -- save-dev @babel/preset-env 
 npm install -- save-dev @babel/preset-react `

and change the presets on the .babelrc like below to fix the issue.
`"presets" : ["@babel/preset-env","@babel/preset-react"],`

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/6573 should help

**Comment by FahmyChaabane** [comment]
> #6573 should help

Is there a workaround for non-react dev ? I just have a node project where i am trying introducing es6+ features. 
I can just run the transpiled files, but is there anyway i can do it directly ?
