### ISSUE TITLE
Filter Box Becomes Blank after Adjusting Dates

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#6491]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
28

### Expected results
I adjust the date filter and the filter is visible and my entries are applied to the dashboard

### Actual results
The filter becomes blank and I see this in the stack trace if I hit refresh:
![image](https://user-images.githubusercontent.com/33062840/49536264-17074200-f894-11e8-9323-0c7a0a632af1.png)

### Steps to reproduce
Adjust the date range in a filter

**Comment by alucchino** [comment]
Hello,
Same operations and same bug for us. It is really breaking as those date filters are widely used

Thx

**Comment by benleibert** [comment]
Howdy,

Superset is an awesome project! We’re experience this issue, though, and it's a fairly painful one.

Kind regards,
Ben

**Comment by benleibert** [comment]
Howdy,

Superset is an awesome project! We’re also experiencing this issue, though, and it's a fairly painful one.

Kind regards,
Ben

**Comment by mistercrunch** [comment]
I recommend using the latest release candidate while we figure out the ASF release process `pip install superset==0.29.0rc7`

**Comment by damir19** [comment]
Thanks, we have the same problem too

Thanks again! 
Damir

**Comment by benleibert** [comment]
Bump in response to the stale bot.

**Comment by Stephane-Thales** [comment]
Same issue, any news or work-around ?

**Comment by quamber-ali** [comment]
Still Facing this issue. How much time is required more to resolve this issue?

**Comment by r-raghul** [comment]
I'm also facing the same issue.. is anybody working on it ?

**Comment by AlexWalker28** [comment]
Issue is still there

**Comment by snowcrash007** [comment]
Hey @Stephane-Thales @AlexWalker28 : Checking in to see if the issue is still there for you?

**Comment by Stephane-Thales** [comment]
> Hey @Stephane-Thales @AlexWalker28 : Checking in to see if the issue is still there for you?

Sorry, I stopped testing SuperSet because of few issue, this one included, so i don't have a test environment available for the moment to recheck. I was planning to test again if i received news through this post that it's fixed...

**Comment by AlexWalker28** [comment]
> Hey @Stephane-Thales @AlexWalker28 : Checking in to see if the issue is still there for you?

I'm not really using it much because of the number of frustrating bugs.

**Comment by Stephane-Thales** [comment]
Bump in response to the stale bot. Still waiting on this issue to be marked as fixed before I re-test superset again.
