### ISSUE TITLE
[Bug] superset_config.py is not working as expecting.

### ISSUE THREAD

**Issue by kk580kk** [apache/incubator-superset#6499]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
https://github.com/apache/incubator-superset/commit/fc8acf27c82ef3030d641289fa80f926f2a83b76

### Expected results
working  with settings from supset_config.py

### Actual results
```

try:
    if CONFIG_PATH_ENV_VAR in os.environ:
        # Explicitly import config module that is not in pythonpath; useful
        # for case where app is being executed via pex.
        print('Loaded your LOCAL configuration at [{}]'.format(
            os.environ[CONFIG_PATH_ENV_VAR]))
        module = sys.modules[__name__]
        override_conf = imp.load_source(
            'superset_config',
            os.environ[CONFIG_PATH_ENV_VAR])
        for key in dir(override_conf):
            if key.isupper():
                setattr(module, key, getattr(override_conf, key))

    else:
        from superset_config import *  # noqa
        import superset_config
        print('Loaded your LOCAL configuration at [{}]'.format(
            superset_config.__file__))
except ImportError:
    pass
```
there not CONFIG_PATH_ENV_VAR in os environment, and throw a exception when finding superset_config module "there is no superset_config module" .
#### Create a virtual environemnt and activate it (recommended)
virtualenv -p python3 ./venv 
#### setup a python3.6 virtualenv
source venv/bin/activate

#### Install external dependencies
pip install -r requirements.txt
pip install -r requirements-dev.txt
#### Install Superset in editable (development) mode
pip install -e .

#### Create an admin user
fabmanager create-admin --app superset

#### Initialize the database
superset db upgrade

#### Create default roles and permissions
superset init

#### Load some data to play with
superset load_examples

#### Start the Flask dev web server from inside the `superset` dir (but see below for frontend asset compilation)
cd superset
flask run -p 8080 --with-threads --reload --debugger

**Comment by mistercrunch** [comment]
If you fire up a python shell from that context and `import superset_config`, does it work?

**Comment by kk580kk** [comment]
> If you fire up a python shell from that context and `import superset_config`, does it work?

I have pycharm and suspend at that point, then run `import superset_config` , and got error ` could not find module superset_config`

**Comment by zhaoyongjie** [comment]
please check you SUPERSET_HOME env setting

**Comment by kk580kk** [comment]
> please check you SUPERSET_HOME env setting
> […](#)

Is there any document in the tutorial says how to set SUPERSET_HOME ?

**Comment by ripoul** [comment]
> SUPERSET_HOME

just add `export SUPERSET_HOME="path to config"` to your .bashrc or your .bash_profile in your home. Then restart your terminal.

**Comment by mistercrunch** [comment]
Anyone think we need to clarify the docs here http://superset.apache.org/installation.html#configuration ? It's clear enough to me, but maybe that's mostly because I probably wrote the docs on this....

**Comment by zhaoyongjie** [comment]
@kk580kk 
```
export SUPERSET_HOME=<superset home directory>
export SUPERSET_CONFIG_PATH=<overwrite superset_config.py>
```

**Comment by kk580kk** [comment]
@mistercrunch ```make sure it is in your PYTHONPATH```
I got it, but it is not a naturally expection as I had followed the tutorial but got a error. Maybe I need to read some more document before trying to run this project.

**Comment by kk580kk** [comment]
@zhaoyongjie Thanks,
