### ISSUE TITLE
flask.cli.NoAppException when building superset from master source

### ISSUE THREAD

**Issue by farzad2004** [apache/incubator-superset#6505]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

I have tried to build superset from master branch to have the filter-box disappear issue sorted. In doing so, I have carefully followed the CONTRIBUTING.MD. All the installation steps were executed successfully. Now, when I start the development server using the "flask run  8080 --with-threads --reload --debugger" command, it starts up successfully. However, the below error is shown on the browser while launching http://127.0.0.1:8080

flask.cli.NoAppException

flask.cli.NoAppException: Failed to find Flask application or factory in module "superset.app". Use "FLASK_APP=superset.app:name to specify one

I have attached the python stack-trace as well as a screenshot showing the error at the browser. I would appreciate if you could help me to resolve this issue. Thanks. 
[python-stacktrace.txt](https://github.com/apache/incubator-superset/files/2660605/python-stacktrace.txt)
![capture](https://user-images.githubusercontent.com/25187634/49698705-698d8900-fc1b-11e8-9796-0db5a376f461.PNG)

**Comment by mistercrunch** [comment]
Did you skip `pip install -r requirements-dev.txt` ? Maybe you're missing `python-dotenv`. Otherwise maybe you are running the `flask run` command from outside the repo?

**Comment by mistercrunch** [comment]
Also you might want to try the latest release candidate.

**Comment by farzad2004** [comment]
@mistercrunch Thanks a tonne dear Maxime. It finally worked. I did install the requirements-dev.txt. However, the python-dotenv module was not existing in that requirement file. I separately installed python-dotenv through "pip install python-dotenv" and the issue was fixed. The  https://pypi.org/project/superset/0.29.0rc7/ has the same python-dotenv module missing in its requirements files. Again, thank you.

**Comment by MarcusSorealheis** [comment]
only pointing out that @farzad2004 suggested a step that also worked for me: `pip install python-dotenv`

**Comment by MarcusSorealheis** [comment]
@farzad2004 @mistercrunch this one line PR should solve the problem for all users going forward. I put it together because there were a lot grumblings: (https://github.com/apache/incubator-superset/pull/6547/commits/465e490a654d6e01838100994951925a29888f0a)

**Comment by krdeepak** [comment]
I am using docker for installation and getting the same error. How do I fix this error?

**Comment by bharath0208** [comment]
> I am using docker for installation and getting the same error. How do I fix this error?

@krdeepak  Any luck with this thing. I am getting the same error now.

assword: 
Repeat for confirmation: 
Usage: flask fab create-admin [OPTIONS]

Error: A valid Flask application was not obtained from "superset:app".

**Comment by gamebusterz** [comment]
@bharath0208 I was getting the same error because an earlier version of Superset's docker  container was existing (although it was stopped). Deleting the image fixed it for me.
