### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by aquatom** [apache/incubator-superset#6509]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
latest  commit on master

### Expected results
successfully start docker container

### Actual results

`Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fa_crv71/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-chrjo_4e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-fa_crv71/cryptography/
ERROR: Service 'superset' failed to build: The command '/bin/sh -c pip install --upgrade setuptools pip     && pip install -r requirements.txt -r requirements-dev.txt     && rm -rf /root/.cache/pip' returned a non-zero code: 1
`

### Steps to reproduce
I followed these steps: https://github.com/apache/incubator-superset/blob/master/docs/installation.rst
based on that commit https://github.com/apache/incubator-superset/commit/02aa3c6395a381e59dced848df55cb1daf733e95

**Comment by haaspt** [comment]
I was able to solve by editing the cryptography package version in requirements.txt, found the solution here: https://github.com/apache/incubator-superset/issues/4870#issuecomment-444189653

**Comment by haolong7** [comment]
> I was able to solve by editing the cryptography package version in requirements.txt, found the solution here: [#4870 (comment)](https://github.com/apache/incubator-superset/issues/4870#issuecomment-444189653)

Nice. Could you make a PR?
