### ISSUE TITLE
Getting a "302 Found" error when accessing superset shared dashboard through an iframe or object-html-tag

### ISSUE THREAD

**Issue by leonardo-espinoza** [apache/incubator-superset#6514]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.20 ?
Flask 0.12.4
Python 3.7

### Expected results
When I put a shared dashboard into an IFRAME or an HTML Object tag, superset should load the dashboard or a login page.

### Actual results
When I try to embed superset into an Iframe or Object tag (HTML) a "302 Found" error (HTTP protocol) is thrown.

### Steps to reproduce
Create an html page with an Iframe or an Object html-tag, like this:

```
<iframe src="http://myhost.com:8080/r/13" height="800" width="800"></iframe>
```
or this: 

```
<object id="dashboardObj" type="text/html" data="http://myhost.com:8080/r/13" style="width: 100%; height: 800px;"></object>
```

Here "http:/myhost.com:8080/r/13" was got from SuperSet "Share dashboard" (The real URL is from an AWS EC2 server)

I've been searching this behavior in google and in this issue list but I've not found anything relevant. Maybe I'm doing something wrong, or I have superset not properly installed. If you need more 

Thank you for your help.

**Comment by leonardo-espinoza** [comment]
If you need more information I can explain more detailed or share files. Thank you.

**Comment by gitHub882000** [comment]
Hi, I'm getting the same issue, how did you solve it? Thanks in advance.
