### ISSUE TITLE
Y axis labels occasionally gets cut off at the top

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#6517]
When testing 0.30 I noticed that some of the Y Axis labels gets cut off at the top. Anyone know of a change recently that would have affected this? @mistercrunch @kristw 

Example of this happening in the birth names chart:
![image](https://user-images.githubusercontent.com/817955/49840522-9a2f0900-fd68-11e8-9a27-22aa7100f7d2.png)

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
I did some work on the bottom margin but that was a while back:
https://github.com/apache/incubator-superset/pull/6282
https://github.com/apache/incubator-superset/pull/4807

**Comment by michellethomas** [comment]
@mistercrunch it looks like [this](https://github.com/apache/incubator-superset/pull/6282/files#diff-057ea80961432c16de759f742a617436R407) line is causing a problem where previously the top was set to a value and now it's getting set to 0 and not reset anywhere. I've noticed it happening when a line chart does not have a legend. So it seems like the container in that situation is not large enough. I could just avoid setting top to 0 in that line, but do you think the problem should be solved somewhere else?
