### ISSUE TITLE
Add Hotkeys to the Explore View

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#6520]
Basic Hotkeys for all our power users:
ctrl + S = Save
ctrl + R  = Run Query
ctrl + L = Get Shortlink

More to come.....

**Comment by hughhhh** [comment]
Potential Package:
https://codesandbox.io/s/l40jjo48nl

**Comment by mistercrunch** [comment]
We use some package for SQL Lab already, works pretty well
