### ISSUE TITLE
Force-directed graph returns [object Object] after first load

### ISSUE THREAD

**Issue by us3r** [apache/incubator-superset#6525]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.29.0rc7

### Expected results

Opening tabs with force-directed graph should show me loaded graph.

### Actual results

After switching to the tab with force-directed graph I have sth like this:

![image](https://user-images.githubusercontent.com/848741/49901187-ccbc2d00-fe60-11e8-821e-783b49018185.png)

I need to force refresh to get the graph.

### Steps to reproduce

* Create tabs. 
* Add to the second tab force-directed graph. 
* Open dashboard, switch to the tab with force-directed graphs.

**Comment by mistercrunch** [comment]
Fixed in master

**Comment by dsewell** [comment]
I'm getting the same issue with the latest version 0.35.2 and master.
