### ISSUE TITLE
Please support Chinese aliases column names when explore the result set

### ISSUE THREAD

**Issue by shizidushu** [apache/incubator-superset#6529]
### Superset version
0.29.0rc7

### Expected results
Can use Chinese aliases column to expore the result set in SQL Lab

### Actual results
A alert:
Column name(s) 月份, 类型, 金额 cannot be used as a column name. Please use aliases (as in SELECT count(*)AS my_alias) limited to alphanumeric characters and underscores.

### Steps to reproduce
Run a query like `SELECT 201808 AS 月份, 'testing' AS 类型, 'unknown' AS 金额` in SQL Lab.

**Comment by SevenDL** [comment]
这个问题一直都存在，有另外一种解决办法，你可以先保存查询，然后再去数据表中找到你保存的查询进行可视化，记得取消勾选不等于SQL视图。
![image](https://user-images.githubusercontent.com/33197465/50266554-f11a9980-045e-11e9-89d3-feb466590ba6.png)

**Comment by shizidushu** [comment]
@SevenDL I just tried and it seems that saved query does not appear in the List Tables view. (刚刚试了，已保存查询不在数据表的列表之中)

**Comment by SevenDL** [comment]
是的，直接修改全称就好了，不需要修改SQL语句和字段名
