### ISSUE TITLE
Update docker installation documentation

### ISSUE THREAD

**Issue by lhyundeadsoul** [apache/incubator-superset#6535]
The [Installation & Configuration](https://superset.incubator.apache.org/installation.html#start-with-docker) page mentions the `docker-build.sh` file which was removed with this commit. It should be corrected in the documentation.

_Originally posted by @krisztianbenda in https://github.com/apache/incubator-superset/commit/02aa3c6395a381e59dced848df55cb1daf733e95#commitcomment-31537097_

**Comment by clauslor** [comment]
possible duplicate #6462

**Comment by kakoni** [comment]
Actual source for that documentation has been corrected (https://github.com/apache/incubator-superset/blob/master/docs/installation.rst) but it hasn't been updated to superset.incubator.apache.org yet
