### ISSUE TITLE
Adding slug name to chart/slice table

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#6537]
Just like dashboards, we want to be able to grab charts/slices by a slug.

- [ ] Create a mapping between slice_id and slug (adding a column table/migration)
- [ ] Open endpoint to allow us to query charts by slug. i.e superset/explore/?chart={ChartSlugName}

**Comment by hughhhh** [comment]
@xtinec

**Comment by rita-gorokhod** [comment]
Was this implemented? The docs mention chart slugs but I don't see it in the chart settings. https://www.restack.io/docs/superset-knowledge-superset-url-slug-guide
