### ISSUE TITLE
Running superset locally and see un-styled page.

### ISSUE THREAD

**Issue by subbiaht** [apache/incubator-superset#6554]
### Superset version
latest

### Expected results
Superset working locally.

### Actual results
![screenshot from 2018-12-19 15-02-27](https://user-images.githubusercontent.com/1546700/50211725-51e29d00-039f-11e9-8156-41493da6d044.png)

### Steps to reproduce
After the Running below command  welcome page not working

```
npm run dev-server
```

I followed `CONTRIBUTING.md`. When i try to build as per command, the page is breaking 

> You can run the Webpack dev server (in a separate terminal from Flask), which runs on port 9000 and proxies non-asset requests to the Flask server on port 8088. After pointing your browser to it, updates to asset sources will be reflected in-browser without a refresh.

```
# Run the dev server
npm run dev-server

# Run the dev server on a non-default port
npm run dev-server -- --port=9001

# Run the dev server proxying to a Flask server on a non-default port
npm run dev-server -- --supersetPort=8081
```

**Comment by mistercrunch** [comment]
We don't have enough information to help you out here. Did you follow the instructions in the CONTRIBUTING.md?

**Comment by kristw** [comment]
Please go to `http://localhost:9000`

**Comment by Ihebbenali95** [comment]
![image](https://github.com/user-attachments/assets/fa4b9090-bb7d-4f48-867f-4201ad4d5f51)
![image](https://github.com/user-attachments/assets/bcf2c5d3-cbe3-415b-9d45-ed450a9c5872)
![image](https://github.com/user-attachments/assets/849ceb08-9c74-405a-9ce6-cd235d8a1ca4)


Hello guys, do you have an idea why none of my 2 created custom plugins would appear?
1st plugin: i cloned hello-world from github
2nd plugin: i created it with yeoman but wont even appear in "Use Symlink source" alongside the other plugins
i appreciate your help

**Comment by rusackas** [comment]
You might want to copy/paste your error logs into GPT if they're not making sense to you, but it seems you have some dependency issues... perhaps in your custom code. We can't really troubleshoot custom code here, so you're a bit on your own, but once you get the build resolved, you'll probably see your UI again :)
