### ISSUE TITLE
"Explore" button in SQL Editor is disabled

### ISSUE THREAD

**Issue by iqrar** [apache/incubator-superset#6557]
Make sure these boxes are checked before submitting your issue - thank you!

- [✔ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✔ ] I have reproduced the issue with at least the latest released version of superset.
- [ ✔] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Visualize button 

### Actual results
disabled Explore button instead of Visualize button

### Steps to reproduce

We added druid as a sql database and ran some queries, works fine. But we are not able to visualize the result. Explore button is disabled.

**Comment by iqrar** [comment]
![superset](https://user-images.githubusercontent.com/7379436/50278620-cb35ca80-0447-11e9-8dd7-5e8b9cc0ca41.PNG)

**Comment by iqrar** [comment]
Thanks for the feedback.  Four months ago i used this feature to create charts, just wondering why cannot now.  That time it shows Visualize button instead of Explore. 

I will wait for upcoming feature  direct chart inside SQL Lab :)

**Comment by iqrar** [comment]
Yes it worked.  I created some charts to visualize ivw monthly data. We are using those charts every month by "force refresh" option to visualize new data.

**Comment by syafiqdante** [comment]
Hello, 
It seemed like I am having quite similar problem here...
superset version: 0.29.0rc7
python version: Python 3.6.8
node version: v10.16.0

the 'explore' button seems like disabled:
![explore button error 2](https://user-images.githubusercontent.com/46438728/64678261-cf10ed80-d4ab-11e9-924e-f65431bc0cf4.PNG)

There's only error shown in the console in the internet browser:
![explore button error](https://user-images.githubusercontent.com/46438728/64678384-07183080-d4ac-11e9-87dd-a76eb78d46c1.PNG)

**Comment by anshupatra** [comment]
same here ... I cant see it either - does it only work with some sources ?
