### ISSUE TITLE
Dynamically assign "user role" when using OAuth authentication with self-registration

### ISSUE THREAD

**Issue by vjsimha1** [apache/incubator-superset#6566]
Hello,

Our planned deployment scenario with SuperSet is to enable OAuth2 based login with self-registration enabled. The issue that we are running into is that there is a single line configuration for self-registration role for all incoming users -
AUTH_USER_REGISTRATION_ROLE = "XXXX"

Our goal is to modify the role that an incoming user gets registered based on the OAuth2 authentication provider. We have decorated the FAB Security Manager with our custom class, as per documentation - 

class CustomSsoSecurityManager(SupersetSecurityManager):
    def oauth_user_info(self, provider, response=None):
      ....
      ....
      return user_info object

We are able to authenticate with multiple providers and SuperSet automatically creates a new user and assigns the role of XXXX. The question is how to be alter this behavior so that user role is determined (at least in part) based on the incoming authentication provider?

Based on a review and (limited) understanding of the underlying FAB architecture, we see that the user registration role is assigned in the SecurityManager (manager.py of FAB) under function "auth_user_oauth" - but we don't see any way of customizing the default behavior with our own class / function. Any guidance on how we can achieve our desired functionality in a safe and version upgrade-able manner would be highly appreciated.

Thanks much for your kind response.

Vijay

**Comment by metaperl** [comment]
See https://github.com/apache/incubator-superset/issues/3419 for a solution to a similar problem.
