### ISSUE TITLE
How to add theme custom color to chart 

### ISSUE THREAD

**Issue by subbiaht** [apache/incubator-superset#6570]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc7

### Expected results
 
How to add custom   color scheme in this dropdown

### Steps to reproduce

![spendmap1](https://user-images.githubusercontent.com/1546700/50437578-59aac000-0910-11e9-8b62-f0512f978ba0.png)

**Comment by XuanmoFeng** [comment]
You can use superset-ui/color  or  write custom color map  like  categoricalSchemeRegistry`  color_scheme: {
    type: 'ColorSchemeControl',
    label: t('Color Scheme'),
    default: 'bnbColors',
    renderTrigger: true,
    choices: () => categoricalSchemeRegistry.keys().map(s => ([s, s])),
    description: t('The color scheme for rendering chart'),
    schemes: () => categoricalSchemeRegistry.getMap(),
  },`

**Comment by subbiaht** [comment]
> You can use superset-ui/color or write custom color map like categoricalSchemeRegistry` color_scheme: { type: 'ColorSchemeControl', label: t('Color Scheme'), default: 'bnbColors', renderTrigger: true, choices: () => categoricalSchemeRegistry.keys().map(s => ([s, s])), description: t('The color scheme for rendering chart'), schemes: () => categoricalSchemeRegistry.getMap(), },`

 i am new superset , is not clear to me , can you some brief explanation
