### ISSUE TITLE
Is there a way to add candlestick chart type, so I can plot share prices?

### ISSUE THREAD

**Issue by kuatroka** [apache/incubator-superset#6584]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by alifa98** [comment]
Up, This feature has not been completed yet.

**Comment by theodorecurtil** [comment]
any news on this issue?

**Comment by LeoDiep** [comment]
Up.
Finance is one of the fields that extensively utilizes data on a daily basis. Introducing visualization such as stock price charts and additional indicators within Superset could mark a pivotal juncture, drawing considerable user interest

**Comment by LeoDiep** [comment]
is there any update on this
