### ISSUE TITLE
Row Level Security

### ISSUE THREAD

**Issue by devbhosale** [apache/incubator-superset#660]
Is there any way to include Row Level Security with Caravel. That is, showing different slices of the data from a table to different users depending on some attribute values.
For example User A  sees Department Sales
                     User B sees  Department Accounting

**Comment by xrmx** [comment]
I think the caravel way is to pre-process your data and split it in multiple tables.

**Comment by devbhosale** [comment]
Thank you Riccardo.
Let us say the table has a column called USERID which tells which user is
authorized to see that row of data. Do you think there could be a way to
insert a "where clause" in the SQL which can insert something like
where user = USERID and Caravel will insert the currently logged in user
ID.
If this is something in the realm of a possibility which code will likely
need to be changed?

**Comment by xrmx** [comment]
Il 27/06/2016 22:37, devbhosale ha scritto:
> Thank you Riccardo.
> Let us say the table has a column called USERID which tells which user is
> authorized to see that row of data. Do you think there could be a way to
> insert a "where clause" in the SQL which can insert something like
> where user = USERID and Caravel will insert the currently logged in user
> ID.
> If this is something in the realm of a possibility which code will likely
> need to be changed?

I don't think that's a good solution sorry :)

**Comment by xqliu** [comment]
I am also curious about a solution to this requirement,
Is there any best practice here for carvel?
If we have 100 users, then to pre preprocess the data will generate 100 tables in this scenario and user might be a dynamic object and could change from time to time , how could we deal with this kind of things?
Thanks for your thoughts.
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.9.6&pv=9.3&source=email_footer_2]
On Tue, Jun 28, 2016 at 4:59 AM, Riccardo Magliocchetti <notifications@github.com> wrote:
Il 27/06/2016 22:37, devbhosale ha scritto:
> Thank you Riccardo.
> Let us say the table has a column called USERID which tells which user is
> authorized to see that row of data. Do you think there could be a way to
> insert a "where clause" in the SQL which can insert something like
> where user = USERID and Caravel will insert the currently logged in user
> ID.
> If this is something in the realm of a possibility which code will likely
> need to be changed?

I don't think that's a good solution sorry :)

**Comment by mistercrunch** [comment]
Views over tables here for sure, you don't need to materialize the data.

Another way would be to add a configuration item where you pick a role and table and define a filtering criteria. If the user has that role then you force the filtering criteria in the where clause.

**Comment by pajachiet** [comment]
We have this exact use case. We would like to implement this configuration item you talk about, with @JulieRossi 

> Another way would be to add a configuration item where you pick a role and table and define a filtering criteria. If the user has that role then you force the filtering criteria in the where clause.

@mistercrunch : Could you give us broad outlines on the steps we should take ?

**Comment by jeffrey-d-lipkowitz** [comment]
I was wondering if any features have changed to allow true row level security.

**Comment by jeffrey-d-lipkowitz** [comment]
I was wondering if anything has changed to allow true row level security. Where you can define roles on a single table and allow filtering criteria based on the the user.

**Comment by mistercrunch** [comment]
It's still not supported. I think this would require a SIP (Superset Improvement Proposal). I don't think this would be too hard to do though. 

Essentially we need a new model "RowLevelSecurityFilter" that has a many-to-one relationship to "BaseDatasource", and many-to-one to "Roles". Then we need the CRUD to manage those (UI and REST API), FAB's ModelView can provide much of this for free.

After it's a matter of forcing the filter into the `query` method of each connector.

**Comment by adriennn** [comment]
@pajachiet still interested in doing a [SIP](https://github.com/apache/incubator-superset/issues/5602)?

**Comment by pajachiet** [comment]
Sorry, not anymore. The BI project moved to another solution to deal with this issue.

**Comment by jeffrey-d-lipkowitz** [comment]
bummer. This would be great feature.

**Comment by archongum** [comment]
I tried tons of open source bi such as Metabase, Redash, CBoard, etc. and RLS only available in enterprise version and just Metabase has it. Conclusion: no money no RLS😪
