### ISSUE TITLE
cannot create new chart in 0.29.0rc7

### ISSUE THREAD

**Issue by zoltantalas** [apache/incubator-superset#6603]
### Superset version

0.29.0rc7

### Actual results

starting screen is already collapsed. (only can see the links for the menu points as a list)
When i would like to create a new chart it throws me back to the starting screen.
### Steps to reproduce

i run the following in virtualenv 3.6.4 (tried with python 2 as well)

```
pip install superset==0.29.0rc7

fabmanager create-admin --app superset
superset db upgrade
superset load_examples
superset init

pip install python-dotenv

flask run -p 8080 --with-threads --reload --debugger
```

**Comment by zoltantalas** [comment]
tried the same with python2 pyenv but it does not help

**Comment by citizenrich** [comment]
I see similar problem with painting of the main menu. I'm using the latest version running on docker-compose. 

<img width="395" alt="screen shot 2019-01-11 at 18 20 06" src="https://user-images.githubusercontent.com/2528387/51064446-aad3d880-15cd-11e9-9d2d-6b49463ea48c.png">

**Comment by satishwaghela** [comment]
> Thanks for the help. Still seeing the issue. My steps are below. I remove the previous superset image then:
> 
> ```
> git clone git@github.com:apache/incubator-superset.git
> cd incubator-superset/
> git checkout -b 0.29.0rc7
> cd contrib/docker/
> # this builds the new image
> docker-compose up -d
> docker-compose exec superset bash
> # do the config menu
> ```

I tried `sudo docker-compose exec -u 0 superset bash` instead of `sudo docker-compose exec superset bash` then it worked. Because for me non root user could not make directory in assets directory that is why it was causing issue.

**Comment by citizenrich** [comment]
Escalating permissions didn't solve it for me. Also, requiring superuser perms to build a dockerfile seems a large attack surface.
