### ISSUE TITLE
How do I resize a font in a chart

### ISSUE THREAD

**Issue by Kwxiao** [apache/incubator-superset#6613]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.28.1
### Expected results
I want to change the font size on the chart because in some cases the font is a little small.

### Actual results

But personal level is limited, I did not find modification font size configuration, or source code
### Steps to reproduce

1.I want to show the chart on the mobile phone, the chart is perfect, but the font is a little small, the font is not clear on the mobile phone.
![image](https://user-images.githubusercontent.com/41364567/50816899-fe8bbb00-135c-11e9-8d10-4d95126fea9f.png)
2.I want to change the font size, but I'm not familiar with python and don't know what code to change.

**Comment by mistercrunch** [comment]
Changing the zoom level of your browser should change the font size proportionally to the visualizations.

**Comment by kristw** [comment]
You can override css in dashboard
