### ISSUE TITLE
Chart-based alarm function

### ISSUE THREAD

**Issue by zhaoyu89730105** [apache/incubator-superset#6615]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyu89730105** [comment]
I added alarm function based on line chart to support telephone and email.
![image](https://user-images.githubusercontent.com/22310104/50821577-7dd3bb80-136a-11e9-9a7b-31f8a748a676.png)

**Comment by XuanmoFeng** [comment]
adress ？

**Comment by zhaoyu89730105** [comment]
This is an internal project of my company，no adress.Not only the superset coding is modified, but also the external alarm system is needed. How can I contribute code?

**Comment by XuanmoFeng** [comment]
Push your github ,then commit merge

**Comment by kristw** [comment]
I appreciate your effort in adding alerting system and for being thoughtful about sharing back to the community. I would put a hold on this feature for two reasons:
- External alarm system dependency. Is it open-source? Is the connection designed well enough to support other options for alarm system? 
- There is an ongoing effort to convert all charts into individual plugins, and detach the code from this main repo. This includes line chart which maybe heavily revised and redesigned, so the alarm code may be not compatible after the migration.

**Comment by lockeCucumber** [comment]
are you working in kuaishou?

**Comment by zhaoyu89730105** [comment]
@lockeCucumber yes
@kristw External 
- External  alarm system is not open-source.
- Looking forward to the charts plugins.

**Comment by mistercrunch** [comment]
@zhaoyu89730105 the "Alerts" feature looks interesting. Oh btw if you want to add Kuaishou to the list of companies who use Superset in our `README.md` that would be nice!

**Comment by zhaoyu89730105** [comment]
@mistercrunch 
 README.md Already added Kuaishou. 
https://github.com/apache/incubator-superset/pull/6630

**Comment by brachi-wernick** [comment]
So, do you have an alert ability?

**Comment by hehe-wz** [comment]
This feature looks great! Any other way to share it? @zhaoyu89730105

**Comment by ChengzhiZhao** [comment]
@zhaoyu89730105 We are looking for similar functionality in superset, we'd love to have this feature!

**Comment by WenQiangW** [comment]
@zhaoyu89730105  this is very good, do you have Blog to introduce how to achieve this feature

**Comment by wenlingyao** [comment]
@zhaoyu89730105 this looks amazing! Would you be so kind to share how you have made it possible?

**Comment by Nishi-Mehta** [comment]
@zhaoyu89730105 Can you write an article regarding this feature? I am sure it would be very helpful to lot of people
