### ISSUE TITLE
Pivot Table digital data display issue

### ISSUE THREAD

**Issue by heavencoder** [apache/incubator-superset#6622]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Hello, I met an issue about Pivot Table digital data display. If the integer number of digits reaches 9 digits, pivot table will cut the last 2 interger digit to 0.

### Superset version
0.28.1

### Expected results
![image](https://user-images.githubusercontent.com/20410090/50881030-51c44300-141b-11e9-990f-c05a7b492367.png)

### Actual results
![image](https://user-images.githubusercontent.com/20410090/50880971-24779500-141b-11e9-9ee7-6fe2a347bc13.png)

### Steps to reproduce
Just add data into Pivot table.

**Comment by mildrabbit** [comment]
Data display format can be set in pivot options, and in this case, it may be necessary to keep the integer format

**Comment by heavencoder** [comment]
> Data display format can be set in pivot options, and in this case, it may be necessary to keep the integer format

Thanks for your suggestions. But It dosen't work. And I've fix this problem already. First, in viz.py, it render query data into html by pandas's to_html() function. This function will change float numbers into 'x.xxxxxxe+07’ style by default, it omits the last two digits if there is 9 digits, and then return html string to borrowser.  And at the mean time, Js also repsent a long number as 'x.xxxxxxe+07’ style, I also need to  re-format this number.
To fix it, I add an parameter 'float_format' to to_html() function at viz.py like this:
![image](https://user-images.githubusercontent.com/20410090/54070031-f259a680-4296-11e9-8460-805c9844dc83.png)
And change src/visualizations/PivotTable/PivotTable.js like this:
![image](https://user-images.githubusercontent.com/20410090/54070105-4fedf300-4297-11e9-8ea9-a63fa0e79da0.png)
