### ISSUE TITLE
Allow users to opt out for limit on select queries

### ISSUE THREAD

**Issue by lingrong** [apache/incubator-superset#6666]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc4

### Expected results
Some ways a user can opt out the limit. Like if user adds their own limit like `LIMIT 9999999`, it won't be replaced by the default hard limit.

Hard limit is applied unless user provides a **different** limit.

### Actual results
Hard limit is always applied unless user provides a **lower** limit

### Steps to reproduce
Run a select query like `select 1` or `select 1 LIMIT 9999999` in Presto, you will see in the backend that the actual query is `select 1 LIMIT 1000000`.

**Comment by enricoberti** [comment]
Started working on this one
