### ISSUE TITLE
[Design Proposal] Add universal "New" button

### ISSUE THREAD

**Issue by dorq** [apache/incubator-superset#6668]
We would like Superset users to have a consistent, easily accessible way to jump into the creation flow for SQL Queries, Charts, and Dashboards.  Here's what we propose:

1. Add a “New” button into the nav as shown.  Allow the button to inherit padding, typography, colors as it would by default. (Despite an earlier discussion about this, we would rather reserve the dropdown hover color and padding conversation for a separate ticket which I will create in JIRA. So the hover color for this new dropdown will likely be teal.)

![superset - universal new button](https://user-images.githubusercontent.com/2992086/51066248-fc746700-15bd-11e9-82fe-c5c0f1db6c7a.png)
![superset - universal new button - dropdown](https://user-images.githubusercontent.com/2992086/51066301-33e31380-15be-11e9-8f9c-9167499e5081.png)

2. Remove the “+” button from our CRUD UI for Charts, SQL Queries, and Dashboards.  Allow the filter icon and associated text to right align into that space.

![superset - remove from crud](https://user-images.githubusercontent.com/2992086/51066304-39d8f480-15be-11e9-8440-743a30231ce6.png)

3. Update the “Add Filter” text to “Filter Results”.  Only update the copy; please leave the gray hover interaction as-is.

**Comment by dorq** [comment]
cc @elibrumbaugh

**Comment by elibrumbaugh** [comment]
This is something I've wanted to see for so long!

1. SG passing through the standard styles. Will keep an eye out on the other ticket/convo.

2. Removing the + from the CRUD UI is a huge usability improvement. Placement of this button seems pretty standard which is nice. I like the right aligned Filter action placement.

Q: Just to clarify this [new] button will persist through all pages?

3. I think "Add Filter" is a little more clear than "Filter Results". Filtering results sounds to me like I'm filtering on a search query I've already made.

**Comment by dorq** [comment]
>Q: Just to clarify this [new] button will persist through all pages?

Yes!  It will be part of the nav, so visible anywhere nav is visible.

>I think "Add Filter" is a little more clear than "Filter Results". Filtering results sounds to me like I'm filtering on a search query I've already made.

Definitely open to suggestions here!  Hopefully we'll hear input from others on this.

**Comment by mistercrunch** [comment]
Tackled `Filter Results` here https://github.com/apache/incubator-superset/pull/6670

**Comment by vylc** [comment]
How about "Advanced Search" since the action of clicking on the funnel icon forces you to do an explicit search?

**Comment by elibrumbaugh** [comment]
> "Add Filter" doesn't make sense either. How about "Advanced Search" since the action of clicking on the funnel icon forces you to do an explicit search with parameters?

I would take "Filter Results" over "Advanced Search". Describing this as a filter on search results vs another search seems more clear to me.

**Comment by dorq** [comment]
How about "Filter List" or "Filter this List"?

**Comment by thinmatt** [comment]
Seems like we are trying to nail down the _right name_ for the content on the page. _Results_ implies some kind of previous search action. List is generic and would work for any page it is on, but perhaps we need to use something specific to the content type on the page.

Would there be a way for us to dynamically name the content that needs filtering? Ala _Filter Charts_, _Filter Dashboards_, etc.

**Comment by dorq** [comment]
Each of the CRUD sections is titled with "List ___" where "___" is Charts, Dashboards, etc.  So it feels like it makes most sense to say "Filter List" since 1) it doesn't imply a previous search (like "Results" or "Search" may imply) and 2) user is actually applying the filter to that list.

Any concerns with going ahead with "Filter List" for now?

**Comment by elibrumbaugh** [comment]
I'm okay with `filter list` but if we're going to say `filter list` should we just say `filter`?

**Comment by dorq** [comment]
Agreed.  We should probably go through and review our copy for things like this.  On the same UI it also says "List Charts" which we could change at the same time.  I've created a ticket for this: #6710

**Comment by elibrumbaugh** [comment]
Thanks for writing this up @mistercrunch. Could you share screenshots?
