### ISSUE TITLE
Missing CSS file for the homepage

### ISSUE THREAD

**Issue by bkowshik** [apache/incubator-superset#6694]
### Superset version
- Latest on the `master` branch: https://github.com/apache/incubator-superset/commit/4667f0c2889ee3d7941859cbb25df6acf4ef36e8

### Actual results
![screenshot_2019-01-15 superset](https://user-images.githubusercontent.com/2899501/51197645-23ad9a00-1918-11e9-81f2-70a346a88e41.png)

### Steps to reproduce
- https://github.com/apache/incubator-superset/issues/6462#issuecomment-445546845

**Comment by bkowshik** [comment]
The following screens are having similar issues as well:
- http://localhost:8088/superset/explore/table/1/ - Sample csv file in the database
- http://localhost:8088/chart/add

**Comment by mistercrunch** [comment]
It's not a CSS issue, it's that you failed at building the javascript bundles. I you are attempting to make your own build, please follow the CONTRIBUTING.md instructions.

**Comment by bkowshik** [comment]
I am trying out `superset` for the very first time, locally on my Mac. The other screens are displayed properly, like the User Profile, etc.

**Comment by cgivre** [comment]
@mistercrunch 
I'm having similar issues.  I built all the javascript files per the instructions on `CONTRIBUTING.md` and am getting the same result.

**Comment by cgivre** [comment]
All... I'm not sure what I did, but I completely removed Superset and reinstalled and it worked (v 0.28).  I re-installed the dev version from source, followed the instructions to build the javascript files and got it to work.  I was attempting to access via `localhost:8088` whereas when you have the dev server, running you have to access it via `localhost:9000`.  IMHO, we might want to make this a little more clear in the docs.

**Comment by haokaibo** [comment]
The root cause for this is not known yet. But the this issue happens in my environment from time to time. Actually I did nothing with it and just wait for it is OK. I hope the dev team can figure out what the root cause of it as soon as possible. GL. : )

**Comment by drivenvector** [comment]
Any solution or workaround yet? I did a fresh install and ran into this issue. Please help.

**Comment by mistercrunch** [comment]
Everyone, to be clear when you see a CSS-free page like this, it means that you have failed at building the javascript. A successful `npm run build` or `npm run dev` would fix this. Note that the pypi releases ship with the already built javascript&css so when using pypi releases you shouldn't have this issue.

If you are working from sources, make sure to follow the instructions in our `CONTRIBUTING.md`

**Comment by math-g** [comment]
I am experiencing the same exact problem with the docker install.
The only warning in the log concerning the js build is (no idea if there is a link..) :
 
`''WARNING in ./node_modules/@superset-ui/connection/esm/index.js 1:42-122 superset_1  | "export 'SupersetClientInterface' was not found in './SupersetClient'`

I hope you will be able to fix it

**Comment by mechiris** [comment]
I'm seeing the same issue on a fresh docker-compose based install on OSX.

**Comment by iaperez** [comment]
I got the same issue while executing the docker instructions on the installation page, but after checking contributing.md I noticed that the entrypoint in the docker configuration starts the app in production mode, and, at least inside docker, it seems to ignores the npm run dev execution.  I think I've fixed the issue by adding a new env var in docker-compose.yml (FLASK_ENV: development) but there are probably better places to put it (like the entrypoint?, so change to prod mode is easier on the .yml file)

**Comment by mistercrunch** [comment]
If you have a fix please send a PR!

**Comment by trmanish** [comment]
Hi I am getting similar issue but only on installing Superset on ubuntu. I am using docker and it works totally fine on my mac. 

Also, I commented the Development option in .yml file

https://github.com/apache/incubator-superset/issues/7008

**Comment by trmanish** [comment]
@iaperez I commented out the Deleopment option in docker-compose.yml file and only keeping the prod version when I am installing it on ubuntu server. For mac one I don't comment out anything and it works totally fine on mac. But on ubuntu few pages like home page, sql query editor are appearing as shown in this issue 

https://github.com/apache/incubator-superset/issues/7008

**Comment by trmanish** [comment]
@iaperez The reason I had to comment out development option in docker-compose.yml in my ubuntu installation because I was getting this error if I didn't do that and based on this ans,https://github.com/apache/incubator-superset/issues/6887#issuecomment-467823566,  i commented that out and the permission denied error went away and Superset was able to launch. However I see the UI issues as referenced by me in https://github.com/apache/incubator-superset/issues/7008

**Comment by trmanish** [comment]
I just got a fix for this issue and similar issue on Ubuntu. 

In Superset assets folder change the permission to 777. It would then work and all css files will get correctly loaded. Even sql editor which was not working earlier works.

**Comment by joicejacob** [comment]
https://stackoverflow.com/questions/52867167/apache-superset-dashbaord-not-rendeing

Second Solution is working for me

**Comment by coldfault** [comment]
This is working for me .... 
    cd /home/superset/superset/static && rm assets && ln -s /home/superset/superset/assets/ assets && ls -la

https://stackoverflow.com/a/58252443/9117597
