### ISSUE TITLE
SQL update statement doesn't work in Sql Lab

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#6706]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
LATEST MASTER

### Expected results
UPDATE statement to work in SqlLap

### Actual results
I get the message `The query returned no data` without errors but changes not reflected in the table

### Steps to reproduce
run similar statement
`UPDATE table1 SET column1 = "test";`

**note all other statements work fine such as ALTER, DROP ....etc except UPDATE**

**Comment by john-bodley** [comment]
@aboganas I believe this is due to the transaction isolation level of the database.

**Comment by aboganas** [comment]
I didn't change anything on the database, it only stopped working with the latest master. I also tried with mysql, MariaDB, and sqlite all show same behavior

**Comment by aboganas** [comment]
Here is even more weird behavior.
If I run UPDATE and  SELECT statements together, it shows the values are updated, if I rerun the SELECT statement it shows the values are not updated.
Here is an example
![sqllab](https://user-images.githubusercontent.com/13873810/52777340-9a8f9d00-3054-11e9-9ec8-6919e10b4491.gif)

**Comment by mistercrunch** [comment]
`COMMIT;`
