### ISSUE TITLE
[Design] Review copy for efficiency and clarity

### ISSUE THREAD

**Issue by dorq** [apache/incubator-superset#6710]
Review the generic copy throughout our UI.

Re: CRUD UI specifically:

- As mentioned in #6668 we could say "Filter" instead of "Filter List"
- As mentioned in #6668 we could say "Charts" instead of "List Charts"

_Please keep adding items here so we can keep track of all changes needed!_

**Comment by elibrumbaugh** [comment]
Thanks for starting this Anita!

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/6725 addresses "Charts" instead -> "List Charts" and replicates the same change across other models list views.

**Comment by dorq** [comment]
@mistercrunch This ticket is just a list of design/copy items to _consider_... We haven't yet made a decision on any of them.  (I'd rather we make a system-wide decision about copy so that we can consistently make changes in all the right places at one time.) So no need to implement these until they are translated into dev tickets!

If any questions about this, please share here or on the #design Slack channel.

**Comment by mistercrunch** [comment]
This has been addressed, closing
