### ISSUE TITLE
Deck.gl - Hexagons - no more data on map with current browsers

### ISSUE THREAD

**Issue by UZi02** [apache/incubator-superset#6712]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.27.0

### Expected results
Data to be shown in a Deck.gl Hexagon slice with all current browsers

### Actual results
In Chrome 69 it's still shown.
Chrome 71 and Firefox 64 show a map without data on it.
Edge 42 is giving the error message: "An error occured while rendering the visualization: TypeError: Unable to get property 'parse' of undefined or null reference" instead of a map.
Chrome (69 and 71) give this warning in the JS console: "Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info."
Firefox gives a "DataCloneError: The object could not be cloned." in the JS console.

**Comment by Sumit12594** [comment]
I have am facing the same issue
