### ISSUE TITLE
Stacked bars no longer work with contribution

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#6714]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Latest master

### Expected results
Stacked bars to work with contribution selected

### Actual results
display fine with grouped but not with stacked
see example
![jan-17-2019 16-31-53](https://user-images.githubusercontent.com/13873810/51322147-b879da00-1a75-11e9-9f47-d70c9ba535dc.gif)

### Steps to reproduce
in bars chart activate contribution and then select style stacked bars

**Comment by mrpapini** [comment]
Does not work also when stacking bars with negative and positive values - there is a javascript exception: Error: <rect> attribute height: Expected length, "NaN".

**Comment by aboganas** [comment]
Yeah I just noticed it also doesn't work with negative and positive values. 

Even with contribution activated I get the error `Error: <rect> attribute height: Expected length, "NaN".`

it seems to be a problem with the type of data returned

**Comment by mrpapini** [comment]
That is exactly right, seems there is a problem with js data type BigNumber, somehow when doing aggregation like sum - numbers are converted to BigNumber and that causes plots to break, if you change above examples to count aggregation, it will work just fine since it will not convert to BigNumber.

**Comment by aboganas** [comment]
still not working for me even if I change aggregation to count :(

**Comment by mrpapini** [comment]
Basically I print to console data that are sent to chart and every time data type is of BigNumber chart will break. 

<img width="2368" alt="image" src="https://user-images.githubusercontent.com/11730548/52802538-27832800-304e-11e9-9d64-ef4639ee6481.png">

Selecting something else like sum will break it:

<img width="2366" alt="image" src="https://user-images.githubusercontent.com/11730548/52802744-8ba5ec00-304e-11e9-9ca8-8a8f2d1aa3fa.png">

Thinking of a fix to convert BigNumber data

**Comment by srindio** [comment]
How do we fix this?
