### ISSUE TITLE
Time Series Multi Line Chart Rendering issue

### ISSUE THREAD

**Issue by rsdpyenugula** [apache/incubator-superset#6716]
### Superset version
Superset 0.28.1
Flask 0.12.4
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

### Actual results

![screen shot 2019-01-17 at 4 17 43 pm](https://user-images.githubusercontent.com/25734842/51349704-17d6ea80-1a74-11e9-8eb7-337524ff4c34.jpg)

### Steps to reproduce
Go to the Dashboard Misc Charts in the examples

**Comment by davidhassan** [comment]
I find switching language and switching back helps it to load.

**Comment by kristw** [comment]
Could you tried `0.29`?

**Comment by rsdpyenugula** [comment]
@kristw do you mean 0.29.0rc7?

**Comment by kristw** [comment]
Yes

**Comment by rsdpyenugula** [comment]
@kristw , I am unable to run the 0.29.0rc7 server due to some flask dependence

**Comment by mistercrunch** [comment]
Looks like you have something else running on port `8080` already, may be another instance of Superset or something else. You can try identifying and killing the process hogging the port, or you can alter the command to start the server on a different port.
