### ISSUE TITLE
What is the source and license of the GeoJson in the CountryMap

### ISSUE THREAD

**Issue by bolkedebruin** [apache/incubator-superset#6724]
I wonder what the source is of the geojson files that are in superset and what their license is. I assume they were not hand crafted?

If they are generated for superset the user should be able to recreate them (idempotent to the distribution) and a script should be included as part of the build instructions. 

@kristw @sekikn @mistercrunch

**Comment by kristw** [comment]
They are not auto-generated. Some files are also contributed by community. They predate my involvement with this project though. 

p.s. One item down on the roadmap is moving the `CountryMap` and all visualizations into independent packages outside of this repo.

**Comment by kristw** [comment]
The migration to plugin is something on my mind too but will have to wait a few weeks until I have the bandwidth. There might be additional work to deal with the json to make the build work as they are not bundled with js and Superset now references to these geojson file using full path.

**Comment by sekikn** [comment]
Hi @bolkedebruin,

As for my contribution #6368, I followed the instruction described at https://superset.incubator.apache.org/visualization.html#need-to-add-a-new-country, assuming that it's already confirmed there's no license issue. If there is, I have no objection to revert it of course.

**Comment by bolkedebruin** [comment]
Thanks @sekikn . It seems that the original, if added through diva-gis is the creative commons attribution / open data 2.1 (http://geoplaza.vu.nl/data/dataset/diva-gis-open-gis-data-portal) which is fine https://www.apache.org/legal/resolved.html#cc-sa but requires attribution in the LICENSE file and licenses/LICENSE-XXX files and NOTICE files most likely

**Comment by bolkedebruin** [comment]
@mistercrunch if not a plugin system yet, a possibility could be to have a script that downloads it and have a user configurable location of where to find the geojson files.
