### ISSUE TITLE
docker-init.sh is hanging when initializing in docker

### ISSUE THREAD

**Issue by travisgu** [apache/incubator-superset#6733]
I have run docker-compose up for several times and the issue was still there. It will stuck in the same issue.

### Superset version
latest commit in master

### Expected results
Initialization was executed correctly.

### Actual results
The log prints the below info and it will stuck there forever:

INFO  [alembic.runtime.migration] Running upgrade bebcf3fed1fe, 705732c70154 -> ec1f88a35cc6, empty message
INFO  [alembic.runtime.migration] Running upgrade 4451805bbaa1, 1d9e835a84f9 -> e3970889f38e, empty message
INFO  [alembic.runtime.migration] Running upgrade 705732c70154, e3970889f38e -> 46ba6aaaac97, empty message
INFO  [alembic.runtime.migration] Running upgrade 46ba6aaaac97, ec1f88a35cc6 -> c18bd4186f15, empty message
INFO  [alembic.runtime.migration] Running upgrade c18bd4186f15 -> 7fcdcde0761c, Reduce position_json size by remove extra space and component id prefix
INFO  [alembic.runtime.migration] Running upgrade 7fcdcde0761c -> 0c5070e96b57, add user attributes table
INFO  [alembic.runtime.migration] Running upgrade 0c5070e96b57 -> 1a1d627ebd8e, position_json
INFO  [alembic.runtime.migration] Running upgrade 1a1d627ebd8e -> 55e910a74826, add_metadata_column_to_annotation_model.py
INFO  [alembic.runtime.migration] Running upgrade 55e910a74826 -> 4ce8df208545, empty message
INFO  [alembic.runtime.migration] Running upgrade 4ce8df208545 -> 46f444d8b9b7, remove_coordinator_from_druid_cluster_model.py
INFO  [alembic.runtime.migration] Running upgrade 46f444d8b9b7 -> a61b40f9f57f, remove allow_run_sync
INFO  [alembic.runtime.migration] Running upgrade a61b40f9f57f -> 6c7537a6004a, models for email reports
INFO  [alembic.runtime.migration] Running upgrade 6c7537a6004a -> 3e1b21cd94a4, change_owner_to_m2m_relation_on_datasources.py`

### Steps to reproduce
1. Run git clonne the repo
2. cd contrib/docker
3. run docker-compose up
4. run docker exec -it <<superset id>> /bin/bash
5. run ./docker-init.sh and it will hang on the above line forever.

**Comment by nick-nz** [comment]
Same here. It would be really helpful if someone could point users at a branch or revision where the docker setup works. I've never been able to get this thing running (last tried back in December and got some other error, now this).

**Comment by mistercrunch** [comment]
The docker scripts are community-contributed and not maintained by the core committers, that's reason why the files are in a `contrib/` folder. You can try tagging the people who contributed those in the git history on this issue.

**Comment by therealkevinard** [comment]
While I would _officially_ go with the "reach out to the contribs" solution, I have some insight to offer - just in the interest of getting anyone else's day going (this issue has solid seo) 

The container was fine for me in docker-compose, but I saw the identical issue when I moved to k8s. Thinking it was a simple memory usage issue, I temporarily removed limits from my cluster's superset, postgres, and redis pods. I exec in and run the init script just fine. Afterwords, I re-applied the old memory/cpu limits, and superset works like a charm. 

Looks like - at least for me, with an identical error - it's a simple memory issue. 

(for posterity: my cluster is 4 x 1cpu/2gb + 2 x 2cpu/4gp)

**Comment by trtg** [comment]
@travisgu @therealkevinard just seconding this issue- trying to get to superset working from within docker seems futile, I gave up and plodded through getting it to work outside of docker. Even without docker getting superset working is a complete pain in the ass- multiple broken python dependencies are present and incredibly finicky issues with the db upgrade/migration process exist. In the very end I was only able to get a half-working instance of superset that randomly fails, cannot load the charts page, etc. etc.

**Comment by therealkevinard** [comment]
It's working like a charm, here - with a couple of key considerations: 
- I had little luck building the image from this repo. Using https://hub.docker.com/r/amancevice/superset/ was no trouble. 
- using that image, I created a docker-compose stack. **Before** bringing it up, I use `docker-compose run 
superset superset-init` to run the migrations, THEN I run `docker-compose up`. They go without a hitch every time this way. 

The dockerfile in this repo works great for development, though. (leads me to think the migrations issue has something to do with postgre).

**Comment by trtg** [comment]
@travisgu @therealkevinard following from #6606 I was able to get the migration to complete by resetting the postgres docker container. (that thread suggested doing that killing the hanging query process). I just found #6606 a moment ago). Also this commit from a few days ago addressed an issue I ran into earlier #7359 

I guess things are looking better now

**Comment by rjurney** [comment]
This happens to me as well on `release--0.31`.
