### ISSUE TITLE
static/assets/dist resources 404 not found

### ISSUE THREAD

**Issue by leonardo-espinoza** [apache/incubator-superset#6734]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
When I fork git repo and clone into my ubuntu 18, and I follow all the instructions in "Contributing" section "Setup Local Environment for Development", I can see superset loads well and I can navigate the menu, add datasources/tables, create charts and dashboards.

### Actual results
When access Superset in my PC (http://127.0.0.1:8088/) the page loads but without all his CSS or JS, and many of the assets does not load properly (404), and nothing can be done in the app.

![image](https://user-images.githubusercontent.com/1522213/51483218-4ce68400-1d77-11e9-854a-53314df4c23d.png)

![image](https://user-images.githubusercontent.com/1522213/51483349-9b941e00-1d77-11e9-96df-6342e3237e35.png)

![image](https://user-images.githubusercontent.com/1522213/51483704-794ed000-1d78-11e9-9447-ac9f32dbfbb0.png)

Also, I've tried docker solution, but it display many errors and cannot build the docker image.

### Steps to reproduce

I followed the instructions in page "Contributing", section "Setup Local Environment for Development".
In the process some steps failed, and I had to go internet (google/stackoverflow/github-issues) to resolve it.

**Comment by leonardo-espinoza** [comment]
Adding more information: When I run "npm run dev-server", it outputs a warning:

```
WARNING in ./node_modules/@superset-ui/connection/esm/index.js 1:42-122
"export 'SupersetClientInterface' was not found in './SupersetClient'
 @ ./src/setup/setupClient.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js
 ｢wdm｣: Compiled with warnings.

```

I think this could be connected with the errors above.

**Comment by leonardo-espinoza** [comment]
Hi Marcus. Before I answer you, I just discovered that all that problems happen only when I run "npm run dev-server", but when I run "npm run dev" none of that problems happen.

The commands I wrote was:

```
% cd superset/assets
% npm ci
% npm run dev-server
```

There is no `yarn install` in the instructions in "CONTRIBUTING.md".

Thank you.

**Comment by kristw** [comment]
When using `npm run dev-server`, go to `http://localhost:9000`. 
I have recently updated the instruction to point this more clearly.
