### ISSUE TITLE
how to export chart image

### ISSUE THREAD

**Issue by wushenchao** [apache/incubator-superset#6737]
I want to export chart image, Is there anyone who can help me？thanks。

**Comment by wushenchao** [comment]
> 是要引入echarts的图表吗，同求，我看到知乎有一点点相关的二开资料

不是，我只是想把图表已图片的形式导出。

**Comment by dominijk** [comment]
+1

**Comment by Benji81** [comment]
Hi @wushenchao will you reopen this issue in a near future?

**Comment by wushenchao** [comment]
@Benji81 Not for the time being, we use the 2.9 version in the form of js screenshot, which temporarily solves this problem
