### ISSUE TITLE
Long Query does not work

### ISSUE THREAD

**Issue by Layshah25** [apache/incubator-superset#6749]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Query should return result

### Actual results
Shows pending for ever.

### Steps to reproduce
Table **Test**
Columns: Id, date, FirstName, LastName
Test has 2000000 rows.

Below query will work and returns result:

select * from Test where id in ('1','2','3','4');

If i execute below query, it shows pending forever.

select * from Test where id in ('1','2','3','4',..............,'176843');

So if input length(No of characters) of query increased, it does not work.

**Already tried**
 Database of superset:
Changed Datatype of below colums to **MEDIUMTEXT** as query is long.
Table **query** column **json**
Table **logs** column **sql**

**Comment by Layshah25** [comment]
Changed column type also for:
Table **query** column **select_sql**
Table **query** column **executed_sql**


Still not working.

**Comment by Layshah25** [comment]
On **Chrome** it gives error:

Failed to load resource: net::ERR_EMPTY_RESPONSE

sqllab.c8ece5519cdf1bb26a1f.entry.js:2 **Uncaught TypeError: Cannot read property 'indexOf' of undefined**
    at Object.error (sqllab.c8ece5519cdf1bb26a1f.entry.js:2)
    at u (vendors-addSlice-common-dashboard-profile-welcome.a9d0f0127af22fd18730.chunk.js:2)
    at Object.fireWith [as rejectWith] (vendors-addSlice-common-dashboard-profile-welcome.a9d0f0127af22fd18730.chunk.js:2)
    at b (vendors-addSlice-common-dashboard-profile-welcome.a9d0f0127af22fd18730.chunk.js:2)
    at XMLHttpRequest.<anonymous> (vendors-addSlice-common-dashboard-profile-welcome.a9d0f0127af22fd18730.chunk.js:2)

**Comment by Layshah25** [comment]
@mistercrunch Can you please look into this.

**Comment by mistercrunch** [comment]
Can you try the latest release candidate? You may have to make your own build.

**Comment by Layshah25** [comment]
Hi,
Tried with latest tag **0.29.0rc7**
Query does not even reach to celery worker.

Getting error as below.
**1 ->>>>>>>>>>>>>>>>>>**

![error-3](https://user-images.githubusercontent.com/11513580/51738187-893a1d00-20b4-11e9-99e1-0c0373dd73dc.png)


**2 ->>>>>>>>>>>>>>>>>>**

![error-2](https://user-images.githubusercontent.com/11513580/51738062-3a8c8300-20b4-11e9-8083-9315a2111f38.png)


@mistercrunch

**Comment by mistercrunch** [comment]
Log message on the web server?

**Comment by Layshah25** [comment]
No messages .. In logs it keeps printing input query in some interval.. 
Also it doesn't reach to superset mysql.

**Comment by Layshah25** [comment]
@mistercrunch  

Can browser storage be a problem?
**Unable to persist state to localStorage: DOMException: Failed to execute 'setItem' on 'Storage'**
