### ISSUE TITLE
Some issue with MSSQL SQLAlchemy Connection

### ISSUE THREAD

**Issue by Uneasy-listening** [apache/incubator-superset#6750]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc7

### Expected results
SQL connection to host DB

### Actual results
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCould not parse rfc1738 URL from string 'mssql+ pyodbc :// \"Driver={ODBC Driver 17 for SQL Server};Server=###;Database=###;UID=###;PWD=###\"'"

### Steps to reproduce
My connection looks as follows  mssql+ pyodbc :// "Driver={ODBC Driver 17 for SQL Server};Server=ourservername;Database=ourwarehousename;UID=####;PWD=####"

I cannot understand why this happens, please help

**Comment by MarcusSorealheis** [comment]
@Uneasy-listening I can help you. Let's try a different URI.

**Comment by MarcusSorealheis** [comment]
Try this in Test Connection in the Sources -> Databases: `mssql+ pyodbc ://<replace with username>:<replace with password>`@<replace with DB host>/<replace with ddatabase name>`

**Comment by Uneasy-listening** [comment]
@davidhassan  Marcus' Solution works when I replaced pyodbc with pymssql (I have both installed). Just had to remove the spaces between the words.

Tx @MarcusSorealheis
