### ISSUE TITLE
Suitable IDE for Superset 

### ISSUE THREAD

**Issue by AkhilkrishnaR** [apache/incubator-superset#6759]
I'm searching for a suitable Interactive Developement Environment(IDE) for debugging superset. I need to debug line by line code execution of JavaScript , React js and Python files.

**Comment by ariepratama** [comment]
@AkhilkrishnaR have you tried [visual code](https://code.visualstudio.com/)? It does has capability to [debug javascript] (https://code.visualstudio.com/docs/editor/debugging)

**Comment by AkhilkrishnaR** [comment]
@ariepratama What about React js and Python files? How can we debug this?
@mistercrunch @mike-schiller
