### ISSUE TITLE
Active Directory Group to Caravel Role Mapping

### ISSUE THREAD

**Issue by zombieland** [apache/incubator-superset#677]
Is there a way to perform role mapping with LDAP/Active Directory groups? I am familiar with Python LDAP, know me know if you guys need help.

**Comment by xrmx** [comment]
flask app builder supports ldap auth:
http://flask-appbuilder.readthedocs.io/en/latest/security.html

**Comment by mistercrunch** [comment]
flask app builder has no notion of group, it would be a very good thing if it did. We may want to contribute it there eventually.
