### ISSUE TITLE
[Design]Jinja2 support in Markup Viz

### ISSUE THREAD

**Issue by kartikshanbhag3333** [apache/incubator-superset#6771]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Jinja2 Templating in Markup Viz
### Actual results
![image](https://user-images.githubusercontent.com/11050610/51852237-a9cfd480-234b-11e9-9a52-4964f563da0f.png)

### Steps to reproduce

    def query_obj(self):
        return None

    def get_df(self, query_obj=None):
        return None

    def get_data(self, df):
        markup_type = self.form_data.get('markup_type')
        code = self.form_data.get('code', '')
        if markup_type == 'markdown':
            code = markdown(code)
            return dict(html=code, theme_css=get_css_manifest_files('theme'))
        else:
            print(template_processor.context["current_username"]())
            return dict(
                html=jinja2.Environment().from_string(code).render(template_processor=template_processor),
                theme_css=get_css_manifest_files('theme')
            )`

The question here is, how safe is this? **template_processor** is object of **jinja_context.BaseTemplateProcessor**

**Comment by gbrian** [comment]
Hi @mistercrunch this viz will be quite good for our project. It will give us lot of possibilities to create a rich Welcome dashboards for the user.
It will be great if we can use Jinja2 templates and query a datasource.

Using Jinja2 templates:
![image](https://user-images.githubusercontent.com/767180/61209929-4ff57800-a6fb-11e9-9282-1f61e0e77b96.png)

In my case I'm using existing `BaseTemplateProcessor`

`from superset.jinja_context import get_template_processor`

````
class MarkupViz(BaseViz):

    """Use html or markdown to create a free form widget"""

    viz_type = "markup"
    verbose_name = _("Markup")
    is_timeseries = False

    def query_obj(self):
        return None

    def get_df(self, query_obj=None):
        return None

    def get_code(self):
        code = self.form_data.get("code", "")
        processor = get_template_processor(self.datasource.database)
        return processor.process_template(code)

    def get_data(self, df):
        markup_type = self.form_data.get("markup_type")
        code = self.get_code()
        if markup_type == "markdown":
            code = markdown(code, extensions=['tables'])
        return dict(html=code, theme_css=get_css_manifest_files("theme"))
````

Let me know if this is something good/NTH in order to create a PR.

**Comment by gbrian** [comment]
Added access to data source data by just copying from `TableViz` implementation

![image](https://user-images.githubusercontent.com/767180/61211143-09098180-a6ff-11e9-9317-cdbd722522ed.png)

**Comment by micimize** [comment]
Is this just a `#wont-fix` because the `markup` viz is getting deprecated, jinja2 templating is unsafe or getting deprecated, or both? What about a slice that allows for templated html/markdown with just the query results?

**Comment by zufolo441** [comment]
Thanks to your advices I was able to enable templating in markup chart. Thanks!
