### ISSUE TITLE
Refresh Druid Metadata retrieve only COUNT metric

### ISSUE THREAD

**Issue by srggrs** [apache/incubator-superset#6780]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Latest master

### Expected results
Druid datasource metrics menu to be populated.
Metrics:
![image](https://user-images.githubusercontent.com/34258464/51954884-ff17fd00-2495-11e9-928a-b8b27bdcbe1a.png)

### Actual results
Only COUNT is populated. 
![image](https://user-images.githubusercontent.com/34258464/51953339-17851900-2490-11e9-83d4-e90ee77e9102.png)

Other metrics end up in the "Columns" table.
![image](https://user-images.githubusercontent.com/34258464/51953305-f9b7b400-248f-11e9-8fa6-de1b1b5a70f2.png)

### Steps to reproduce
* Create a Druid data source with some dimensions (e.g. country, address, ..) and some metrics (e.g. sum, min, max).
* Add the datasource to SS UI
* refresh Druid metadata

**Comment by srggrs** [comment]
Guys, 
I'm trying to fix this issue but I got a bit lost in the code, so I need some help.

My understanding is that after SS 0.29.0rc7, the Druid cluster configuration dropped the coordinator host and endpoint settings. Therefore segment discovering and schema should be retrieved through the Druid broker endpoint.

I had a look at the code for Druid models and the PR #5461 (https://github.com/apache/incubator-superset/commit/88964b7dfcc8355ef4e42b1599197bdff156e8f5) in which the 'sum', 'max', 'min' are deprecated in favour the "MetricsControl", but I don't understand how does that work.

Any help to re-direct me at any part of the code is appreciated.
Cheers,
Serg

**Comment by srggrs** [comment]
@mistercrunch could you suggest how the "MetricsControl" works? Thank you!

**Comment by colax94** [comment]
No comment here @mistercrunch please ? How can we create post-aggregations without the auto generated sum, min, max aggregations ?
