### ISSUE TITLE
Adding Korean Translation

### ISSUE THREAD

**Issue by wonjin911** [apache/incubator-superset#6784]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Steps to reproduce

Hi, I want to help adding Korean translation, which is new.
I've checked the process of adding translations and started working on it.
But it takes quite a long time to finish all of the translations, and I will have to fill the translation step by step.
Is it okay to commit my translations with some intervals?
Please leave me any suggestions.

Thank you.

**Comment by mistercrunch** [comment]
Yes that works, feel free to phase your translations as multiple pull requests. Thank you for your contribution!
