### ISSUE TITLE
Projected Release Date for 0.29

### ISSUE THREAD

**Issue by smokemonster99** [apache/incubator-superset#6785]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Steps to reproduce

This is just a question...I was wondering if there was a projected release date for 0.29. I see there have been a number of rc going back for some time. thanks.

**Comment by mistercrunch** [comment]
We're a bit stuck at the moment as we need to sort out license-related things for our first Apache release. Apache prevents us from releasing anything until this is sorted out. It represents a fair amount of work to do this, and no committer has volunteered to do that work as of yet. We're hoping it gets resolved this quarter and that we'll be able to offer clean releases from a licensing standpoint

**Comment by smokemonster99** [comment]
So 0.29 will be the first Apache release and not be released until you get the license related things done? 
We are on 0.26.3 and found 0.28 to have some known issues so we want to pickup the next stable release with those fixes. Any recommendations? We're interested in the new dashboarding features that v28 added...

**Comment by XuanmoFeng** [comment]
Will the 0.29 release  add the schedule email ?

**Comment by mistercrunch** [comment]
You'll probably want to upgrade straight to `0.31.x` by then though

**Comment by tatineni99** [comment]
@mistercrunch As you mentioned earlier, can we expect the first Apache release version 0.29 in this quarter ?

We are eagerly waiting for the next version, as it is having many fixes we are interested in. Thanks

**Comment by hajdbo** [comment]
The amount of work done since the last "pip" release is staggering.
I'm afraid that not many of us have deployed/tested the master, 0.29 or 0.30 branches, and so the risk of finding bugs very late is relatively high.
How can we help with the roadblocks that prevent the release?

**Comment by mistercrunch** [comment]
Next step is for us to push our first official source Apache release, we're planning on starting the work on this early next week. The source release is a not a `pipy` (or "convenience release" as Apache would call it) though. A `pipy` release may be fairly more complicated, especially if we want the binaries to include minified javascript bundles, which would have to detail all of the packages included (hundreds!) in a comprised LICENSE.txt file.

As we push the source release (which should be fairly straight forward at this point), we'll start the conversation with Apache mentors and champions as to how to navigate the convenience (pypi) release. This conversation should take place on the mailing list and you can partake and sign up for some of the work that will come out of it.

**Comment by mistercrunch** [comment]
In the meantime the closest thing to releases are the RC in release branches. `0.29`, `0.30`, `release--0.31`. Some of these RCs have been used in production at Airbnb and Lyft and are probably your best bets at the moment. Keep in mind those are NOT releases.

By following the Apache methodology, we should have steady, clean licensed, voted-on releases. Bear with us while we figure out the process.

**Comment by davide-malagoli** [comment]
any update on this topic?

**Comment by elukey** [comment]
As FYI for everybody subscribed in here I can see something moving in https://lists.apache.org/list.html?dev@superset.apache.org (0.31 and 0.32 currently being voted for release).

**Comment by davide-malagoli** [comment]
Seems that the vote passed, maybe in a few weeks we'll see the new release.


> **[VOTE] Release Superset 0.32.0 based on Superset 0.32.0 RC2**

> Vote passes!
> 
> +4 binding votes (Max, Alan, Jeff & Abhishek)
> +1 non-binding vote
> 
> No neutral or negative votes.

**Comment by mistercrunch** [comment]
There was a `-1` later on, thread is still going on...

**Comment by elukey** [comment]
> There was a `-1` later on, thread is still going on...

Is it a public -1 logged in the dev mailing list for 0.32rc2? I don't find it :(

**Comment by adriankrupa** [comment]
@mistercrunch Do you have any ETA? If it's long maybe you can upload 0.33rc1 to pypi?

**Comment by timalive** [comment]
Anything we can help with in this space @mistercrunch?

**Comment by davide-malagoli** [comment]
I think they encountered some License problem, they are asking for volunteering, see [this thread](https://lists.apache.org/thread.html/5ca9bef3454dfb14b0328b0303109e6bf9747c5d2c688b42939ff169@%3Cdev.superset.apache.org%3E) in  the @dev list.

>From: Alan Gates
...
Running the above on the modules in setup.py, I see that the vast majority
are BSD, MIT, Apache, or PSFL, all of which are fine. The ones that aren't
in that category are:
certifi MPL-2.0: This is ok, as it's binary
chardet LGPL Not Ok
click UNKNOWN
jsonschema UNKNOWN
python-dateutil Dual License
python-dotenv UNKNOWN
python-geohash UNKNOWN
python3-openid UNKNOWN

>The MPL one is fine since it's included in binary form. The unknown and
dual license need some digging to determine what they are. chardet, the
LGPL one, is not ok.
...

>From: Maxime Beauchemin
@community, it'd be great if someone could volunteer to do this (making
the python library "requests" an optional dependency). It appears it's used
in its simplest form in a few places (requests.get) which should be easy to
replace with urrlib2. The Druid connector uses a more advanced feature
(basic auth), but that could be made just an optional dependency, as we're
deprecating the Druid connector, to be replaced by the SQLAlchemy Druid
connector/dialect. There it's just a matter of moving `pydruid` and
`requests` to the "extra_requires" section of our setup.py, and doing late
imports.
...

**Comment by smokemonster99** [comment]
What 'release' is AirB&B using? I am currently testing containerized 0.33.0rc1 from https://dist.apache.org/repos/dist/dev/incubator/superset/ Is this considered somewhat stable?
