### ISSUE TITLE
EnvironmentError: [Errno 39] Directory not empty: 'packaging'

### ISSUE THREAD

**Issue by quydx** [apache/incubator-superset#6789]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Install with docker

### Expected results
Installation should succeed.

### Actual results
I get error in step
```
RUN pip install --upgrade setuptools pip     && pip install -r requirements.txt -r requirements-dev.txt     && rm -rf /root/.cache/pip
 ---> Running in 40f653682bad

Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/bf/ae/a23db1762646069742cc21393833577d3fa438eecaa59d11fb04fa57fcd5/setuptools-40.7.1-py2.py3-none-any.whl (574kB)
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (19.0.1)
Installing collected packages: setuptools
  Found existing installation: setuptools 40.6.3
    Uninstalling setuptools-40.6.3:
Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: 'packaging'

```

### Steps to reproduce
docker-compose run --rm superset ./docker-init.sh

**Comment by answerquest** [comment]
Hi @quydx  I was having this error while updating another package and web search showed this page. I solved the issue at my end: when I opened the target directory that pip was complaining about, found a stray `.fuse-hidden..` file that geany and maybe some other apps keeps conjuring in my folders (you press refresh and they're ususally gone). Seems this stray one was left over. I deleted it, and then the install/upgrade process ran smoothly. So do check out the actual folder at your end.
