### ISSUE TITLE
cannot use the "filter_values" variable in LIKE/ILIKE statements

### ISSUE THREAD

**Issue by yuyuhan0306** [apache/incubator-superset#6791]
Make sure these boxes are checked before submitting your issue - thank you!

- [ v] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ v] I have reproduced the issue with at least the latest released version of superset.
- [ v] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.0

### Expected results
I created a filter box and would like to pass user inputs into SQL queries. I looked up the documentation about "filter_values". https://superset.incubator.apache.org/sqllab.html However, it seems that I can only use filter_values for "IN" statements instead of LIKE or ILIKE statements.

The query I want to format is like the following: ("backpack" is user input)
SELECT parsed_search AS parsed_search,
       COUNT(*) AS count
FROM public.js_meta
WHERE (((parsed_search ilike '%+backpack+%'
         or parsed_search ilike 'backpack+%'
         or parsed_search ilike '%+backpack')
        and parsed_search <>''))
GROUP BY parsed_search
ORDER BY count DESC
LIMIT 50;

I use the UI interface to write my query.
Group by parsed_search
Metrics COUNT(*)
Filters
(parsed_search ilike {{"'%+" + "".join(filter_values(parsed_search)) + "+%'" }} or
 parsed_search ilike {{"'" + "".join(filter_values(parsed_search)) + "+%'" }} or
 parsed_search ilike {{"'%+" + "".join(filter_values(parsed_search)) + "'" }}) and parsed_search <>''

### Actual results
SELECT parsed_search AS parsed_search,
       COUNT(*) AS count
FROM public.js_meta
WHERE parsed_search IN ('backpack')
  AND (((parsed_search ilike '%++%'
         or parsed_search ilike '+%'
         or parsed_search ilike '%+')
        and parsed_search <>''))
GROUP BY parsed_search
ORDER BY count DESC
LIMIT 50;

**Comment by xavier-GitHub76** [comment]
Hello, I take the liberty of contacting you because I also want to set up a filter on a dashboard based on a like/ilike. You opened this issue but you closed it almost immediately. Did you manage to set up this type of filter ?
Thank you for your help
Regards

**Comment by arifaizin** [comment]
me too, i want to know how to make it

**Comment by Parcurcik** [comment]
Any solutions?
