### ISSUE TITLE
Building from source: npm run dev-server Error

### ISSUE THREAD

**Issue by Rijicp** [apache/incubator-superset#6798]
npm run dev-server

> superset@0.999.0-dev dev-server /usr/local/incubator-superset/superset/assets
> webpack-dev-server --mode=development --progress

sh: 1: webpack-dev-server: not found
```
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev-server"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! superset@0.999.0-dev dev-server: `webpack-dev-server --mode=development --progress`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev dev-server script 'webpack-dev-server --mode=development --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --mode=development --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/incubator-superset/superset/assets/npm-debug.log
```

**Comment by mistercrunch** [comment]
Did you run `npm ci` or `npm install` from the `superset/assets` folder prior to this?

**Comment by Rijicp** [comment]
i got following error 
# Run the dev server
npm run dev-server
Error occured while trying to proxy to: localhost:9000/

WARNING in ./node_modules/@superset-ui/connection/esm/index.js 1:42-122
"export 'SupersetClientInterface' was not found in './SupersetClient'
 @ ./src/setup/setupClient.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js
ℹ ｢wdm｣: Compiled with warnings.
[HPM] Error occurred while trying to proxy request / from 127.0.0.1:9000 to http://localhost:8088 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /favicon.ico from 127.0.0.1:9000 to http://localhost:8088 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by Rijicp** [comment]
> Did you run `npm ci` or `npm install` from the `superset/assets` folder prior to this?

Yes,But i got new error

**Comment by kristw** [comment]
Have you started the flask server?

**Comment by Rijicp** [comment]
No i didn't start flash sever

**Comment by Rijicp** [comment]
So i re-installed with same step.then run in superset/asset folder but currently i stuck 
root@ivl:/usr/local/incubator-superset/superset/assets# npm run dev-server

> superset@0.999.0-dev dev-server /usr/local/incubator-superset/superset/assets
> webpack-dev-server --mode=development --progress

clean-webpack-plugin: /usr/local/incubator-superset/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 10% building 8/8 modules 0 activeevents.js:183                              
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev-server"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! superset@0.999.0-dev dev-server: `webpack-dev-server --mode=development --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev dev-server script 'webpack-dev-server --mode=development --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --mode=development --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by Rijicp** [comment]
Now working

**Comment by coderfender** [comment]
How did you solve this issue? I am getting the same issue on my EC2 instance

**Comment by gordonfl** [comment]
> How did you solve this issue? I am getting the same issue on my EC2 instance

did you resolve it? I also have this problem

**Comment by coderfender** [comment]
I was able to resolve it

**Comment by gordonfl** [comment]
how did you resolved?

**Comment by coderfender** [comment]
Just run npm run server in a different service

**Comment by tlightsky** [comment]
meet this too today,
in docker

**Comment by Alfran007** [comment]
I was facing the same issue. Just check whether any instance is running on that port already. I was using docker and did docker-compose down. Then it worked.

**Comment by str028** [comment]
> Just run npm run server in a different service

can you tell me exactly how did you resolve this ? Thanks

**Comment by gho1b** [comment]
> > Just run npm run server in a different service
> 
> can you tell me exactly how did you resolve this ? Thanks

I had done by replace the host address to correct running superset server in `cypress.json` and `webpack-proxy-config.js`

**Comment by DuyKhanhVu** [comment]
we need to start orther services. Go to superset repo and run `docker compose -f docker-compose-non-dev.yml up`
