### ISSUE TITLE
Table view as dashboard filter - don't highlight item or clear filter 

### ISSUE THREAD

**Issue by nebengtsson** [apache/incubator-superset#6799]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Table view can be used as dashboard-wide filter if the checkbox "Emit Filter Events" is set.
Clicking an item once should filter the whole dashboard and highlight the selected items.
Clicking again should then clear that filter and un-highlight the item.

### Actual results
The filter is applied but the item is not highlighted.
Clicking a second time does not clear the filter.

**Comment by SGSunil** [comment]
same issue

**Comment by mistercrunch** [comment]
That's fixed in `master`

**Comment by koxt** [comment]
I deployed superset using docker
https://superset.incubator.apache.org/installation.html#start-with-docker
so version is `master`

It seems that 
> Clicking a second time does not clear the filter

still doesn't fixed.

Actually,
after first time clickiing - row is selected, highlighted and other charts (on the same datasource) are refreshed (see requests to server)
after second clicking - row is deselected, but other charts aren't refreshed (no requests at chrome dev tools)

**Comment by zhongjaifu** [comment]
It seems to be，highlight item is ok，but clear filter is not

**Comment by nytai** [comment]
Someone wrote in to `dev@apache.superset.org` regarding this still being an issue. We should investigate further if it's still an issue in master.
