### ISSUE TITLE
How add a new visualization in superset 0.29.0rc7 ?

### ISSUE THREAD

**Issue by Jsbejaranos1234** [apache/incubator-superset#6812]
### Superset version
0.28.0 -0.28.1-0.29.0rc7

### Actual results
The structure from superset has changed after the version 0.28.0, so how can i add a new kind of visualization like in previous versions.

**Comment by kristw** [comment]
Please see https://github.com/apache/incubator-superset/pull/6838

**Comment by cscainiao** [comment]
Can someone tell me what the latest version of superset is？
