### ISSUE TITLE
Cannot find visTypes.js

### ISSUE THREAD

**Issue by Rijicp** [apache/incubator-superset#6817]
File missing in when i install and add new visualization on this documentation https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setup-local-environment-for-development
```
superset/assets/javascripts/explore/stores/visTypes.js
```

**Comment by Rijicp** [comment]
I used to customize : https://github.com/apache/incubator-superset/pull/5144

**Comment by kristw** [comment]
It is not missing. It was deprecated and removed to prepare the repo to move towards chart plugin system.

**Comment by cscainiao** [comment]
@kristw but, now How do we add a visualization?  The previous method is not available

**Comment by hamza-iqbal-hi** [comment]
How Do we add a new Visualization now?
