### ISSUE TITLE
Superset: Get value of Grain in filter 

### ISSUE THREAD

**Issue by thuylevn** [apache/incubator-superset#6822]
Hi all,
I am using superset. Do you know how to   _**Get value of Grain in filter**_   from a query ( as a parameter  **{{ ??? }}** )?

![image](https://user-images.githubusercontent.com/24593553/52361747-f2068b00-2a0c-11e9-87ab-cc30e44f0aa1.png) 

Many thanks

**Comment by kristw** [comment]
What version is this?

**Comment by thuylevn** [comment]
Hi Kristw,
I am using  superset version  "0.26.3"

**Comment by isrkar** [comment]
I also need to pass the grain to query.
Has anyone figured out how to do this?
