### ISSUE TITLE
[question] SUPERSET_WEBSERVER_TIMEOUT deprecated but what is the alternative?

### ISSUE THREAD

**Issue by anshbansal** [apache/incubator-superset#6836]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
  Superset 0.28.1

### Expected results
Answer of the question

### Actual results
Missing answer

### Steps to reproduce
- Click on https://github.com/apache/incubator-superset/blob/master/superset/config.py#L62
- See that it says deprecated
- See that it does not say what is the alternative to be placed in superset_config.py

**Comment by mistercrunch** [comment]
Looks like this is confusing indeed, the comment comes from https://github.com/apache/incubator-superset/pull/4451 where the auto generated `gunicorn` command (started through `superset runserver`) started getting deprecation messages but appears to still work.

The config element `SUPERSET_WEBSERVER_TIMEOUT` is still used widely across the codebase. 

Timeouts are much more complicated than a sane person would expect. Let me document some things here:
* first your proxy / load balancer / envoy / kong thing may time out before your web server does. When that happen I think nothing is returned and the request is just forever lost. The webserver may still do work, and has no way to return a response.
* flask offers no way to set a timeout, but your wsgi server does (gunicorn / nginx / ...) when that happens, it does return a proper response with an error code. Without us generating the `gunicorn` command (per #4451), people have to keep the timeouts in sync manually
* we have code on the client side that gives up if it looks like it'll never get a timeout response, I'm not sure if it's implement consistently across all "requests that may time out"

Regardless, I think we should remove the " # deprecated" comment and add some notes in there. PR coming up.
