### ISSUE TITLE
WEBSERVER_THREADS from superset_config.py is not read in unless DEBUG is set to TRUE

### ISSUE THREAD

**Issue by anshbansal** [apache/incubator-superset#6841]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
- WEBSERVER_THREADS should be read in

### Actual results
- WEBSERVER_THREADS is not read in

### Steps to reproduce
- Set WEBSERVER_THREADS to something other than the default value in superset_config.py
- Set DEBUG to False in superset_config.py
- Run superset using this docker image https://github.com/tylerFowler/docker-superset
- Check number of gunicorn threads being run

**Comment by mistercrunch** [comment]
We now recommend using the `flask run` and `gunicorn` commands instead, we should deprecate the related config keys related to the `superset runserver` [deprecated] subcommand
