### ISSUE TITLE
Failed to establish a new connection to any one of the clusters throws error

### ISSUE THREAD

**Issue by coolboi567** [apache/incubator-superset#6842]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Superset 0.28.1
Flask 0.12.4
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]

### Expected results
Refreshing Druid metadata and listing latest datasources

### Actual results
Throws an error, instead of a warning for failing to connect to one of the clusters
```
Error while processing cluster 'x.x.x.x' HTTPConnectionPool(host='x.x.x.x', port=8082): Max retries exceeded with url: /druid/v2/datasources (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f414e6f9cf8>: Failed to establish a new connection: [Errno 111] Connection refused',)) 
```

### Steps to reproduce
Add an invalid druid cluster IP address along with a valid one. Then, refresh druid metadata

**Comment by coolboi567** [comment]
This issue can be easily resolved by adding logic to not throw an exception but just a set of warning for those failed Druid Clusters.

**Comment by coolboi567** [comment]
I can help if it is fine with you guys. :)

**Comment by mistercrunch** [comment]
For sure, help is always welcomed.

**Comment by coolboi567** [comment]
@mistercrunch Cool, here is the PR.

https://github.com/apache/incubator-superset/pull/6944

**Comment by AdrianSanzRodrigo** [comment]
I'm getting same error...I cannot fetch any druid cluster. Any suggestion?
