### ISSUE TITLE
Syncing mssql table schema automatically(with a sync button)

### ISSUE THREAD

**Issue by wonjin911** [apache/incubator-superset#6843]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
Sync mssql table schema automatically after table schema changes. (such as adding columns)

### Actual results
I have to manually add column in "edit record" page. (Or delete it and add again)
And even if I add wrong column name in superset, no validation happens. 
When I add a new chart and run query, it shows no column found error.

### Steps to reproduce
1. Add a mssql table in superset,
2. Adding a column to the mssql table
3. Nothing changes in superset.

I haven't check other databases.
Wouldn't it helpful to provide a sync button for syncing table schema?

**Comment by davidhassan** [comment]
I am able to sync my mssql table schema in 0.29.0rc7.

**Comment by wonjin911** [comment]
Oh, I found the "Refresh Metadata" button on "Show Record" page! Thanks david.
I've tried this, it successfully updated my new added columns.
But one thing remains, the column that I manually added in superset(which is not existing in the real mssql table) is not removed after I click the "Refresh Metadata".
Is this intended?

**Comment by davidhassan** [comment]
I can confirm I get the same results.  When I make a manual column in superset, It doesn't get deleted when i sync. I think this might be intended. It would make sense if it only synced based on the underlying table and ignored the superset changes.

**Comment by wonjin911** [comment]
Alright, if it is intended for a certain purpose, that's fine. 
I just needed a refresh meta functionality. I will close this issue. Thx David.
