### ISSUE TITLE
npm run build has WARNING

### ISSUE THREAD

**Issue by wqf1992wqf** [apache/incubator-superset#6855]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✅ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0dev

### Expected results
1. I clone the latest project.
2. yarn install
3. npm run build

### Actual results
![image](https://user-images.githubusercontent.com/7042560/52609023-c70db280-2eb6-11e9-9c16-ee412a03ed4a.png)
![image](https://user-images.githubusercontent.com/7042560/52609059-f3293380-2eb6-11e9-94db-ff8460683334.png)

### Steps to reproduce
I followed the instructions in page "Contributing", section "Setup Local Environment for Development".
In the process some steps failed

**Comment by mistercrunch** [comment]
@kristw @williaster

**Comment by williaster** [comment]
I think @kristw flagged this already (not sure if there's an issue or not). I think this is this the type warnings right Krist? I think we have a solution planned in `@superset-ui`.

**Comment by kristw** [comment]
Thanks for reporting the issue. This is related to https://github.com/apache-superset/superset-ui/issues/94

- First of all, these warnings are annoying, yes, but they *do not affect the correctness of how Superset function* so no need to panic. Don't make them scapegoats for unexplainable bugs. Totally red herring. 
- I agree that we should get rid of them for peace of mind, but given a few more bigger things on the plate such as migrating visualization code to plugins and deleting 200k lines from this repo, I think this one can wait a bit.

**Comment by williaster** [comment]
totally agree 👍

**Comment by wqf1992wqf** [comment]
When I started the latest version of the project, I also encountered the problem of homepage static resource loss, which I think may be caused by ~
![image](https://user-images.githubusercontent.com/7042560/52616870-f16e6880-2ed4-11e9-9fa6-8900d3aa71fc.png)
My steps
git clone https://github.com/apache/incubator-superset/
cd incubator-superset/contrib/docker
# prefix with SUPERSET_LOAD_EXAMPLES=yes to load examples:
docker-compose run --rm superset ./docker-init.sh
# you can run this command everytime you need to start superset now:
docker-compose up


I'm sorry that my English is poor.

**Comment by kristw** [comment]
@wqf1992wqf It is not related to the warnings. Please see 
https://github.com/apache/incubator-superset/issues/6694

**Comment by wqf1992wqf** [comment]
I've read this issues，but I can't solve this problem.
mistercrunch say：
Everyone, to be clear when you see a CSS-free page like this, it means that you have failed at building the javascript. A successful `npm run build` or `npm run dev` would fix this.
I think is right，but I built it successfully, except for these warnings
@kristw

**Comment by kristw** [comment]
How did you build. `npm run build` or `npm run dev-server`. If you use `dev-server`, go to port 9000.

**Comment by wqf1992wqf** [comment]
Both have been tried.
![image](https://user-images.githubusercontent.com/7042560/52623748-06082c00-2ee8-11e9-8267-46cbd1ce69a6.png)
@kristw

**Comment by kristw** [comment]
I suspect it is something to do with docker, which I know too little about. Again, this is not related to the warnings above. And you said you could `npm run build` successfully so it is also not about front-end code.

**Comment by wqf1992wqf** [comment]
Thank you. I'll find out why.

**Comment by lukexyz** [comment]
@wqf1992wqf Please post if you find the solution - I'm having the same issue (as well as the superset-ui npm build errors in the top post)

**Comment by Statfine** [comment]
@wqf1992wqf  npm install and npm run dev than open browser to see is right? i don't know how to start
