### ISSUE TITLE
Add Images to Graphs

### ISSUE THREAD

**Issue by Uneasy-listening** [apache/incubator-superset#6856]
- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

Hi.

Does anyone know of a easy way to add a static image into some of the graphs, like a logo in the middle of a sunburst diagram? Or a semi-transparent logo behind any other graph.

Your help will be appreciated.
Tx

**Comment by mistercrunch** [comment]
The only way to do this without touching the code at the moment would be to use the CSS editor feature on the dashboard.

**Comment by Uneasy-listening** [comment]
@mistercrunch Tx.

**Comment by mistercrunch** [comment]
<img width="401" alt="screen shot 2019-02-11 at 11 35 48 pm" src="https://user-images.githubusercontent.com/487433/52619135-c85ac300-2e55-11e9-8e0f-b6e0061ae633.png">
https://www.codecademy.com/learn/learn-css

**Comment by Uneasy-listening** [comment]
Thank you ☺
