### ISSUE TITLE
Automated Chart Filters

### ISSUE THREAD

**Issue by Mellorison** [apache/incubator-superset#6858]
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.28.1

### Expected results

To have an automated filter attached to a visualization by default

### Actual results

Filter not attached to visualization by default

### Steps to reproduce

Filter needs to be created as separate visualization and linked to dashboard charts to be filtered by.

Hi. Just making a follow up on issue #5941. With regards to having a default filter integrated with a chart.
Is any work being done on this?

**Comment by kalimuthu123** [comment]
To have an automated filter attached to a visualization by default
