### ISSUE TITLE
Dashboard Auto Refresh Efficiency (settings and caching)

### ISSUE THREAD

**Issue by alanmcruickshank** [apache/incubator-superset#686]
This is an edit that I'm happy to take a crack at but I need some guidance on how best to approach it (@mistercrunch).

I'd like the option to set some dashboards to always autorefresh. At the moment every dashboard loads as non-refreshing as standard, and I'd like to store the refresh setting (either after setting it on the dashboard view and saving it or setting it on the dashboard properties page), and then pass this through on dashboard load so that it automatically gets set.

Simply doing this will also put quite a lot of strain on out Database for some of the common dashboards if the timed refresh always does a force refresh (except for the first load):

[line 266 in dashboard.jsx](https://github.com/airbnb/caravel/blob/13095eb550efb59062975df16f5516a3eb076bcd/caravel/assets/javascripts/dashboard.jsx#L266)

``` javascript
var refreshAll = function () {
        dash.slices.forEach(function (slice) {
          var force = !dash.firstLoad;
          setTimeout(function () {
            slice.render(force);
          },
          //Randomize to prevent all widgets refreshing at the same time
          maxRandomDelay * Math.random());
        });
        dash.firstLoad = false;
```

to combat this I'd also like to be able to set something on the dashboard which disables the forced refresh on the time refreshes and allows it instead to use the cached values. This means that if multiple people are looking at the same dashboard all with autorefresh enabled that the values only get calculated once (when the cache expires) and the everyone else is served the cached values. The "Force refresh the whole dashboard" button should still actually force refresh the whole dashboard, I don't want to change the functionality there.

Where would be the most appropriate place to store the setting, and how do I pass that through on loading the dashboard so that the javascript has access to that variable? (My javascript is pretty rusty)

**Comment by mistercrunch** [comment]
Seems like you can just add is as an Integer Column to `caravel.models.Dashboard` and maybe you need an additional Boolean for `autorefresh_from_cache` or something like that. The option in the modal should be changed to allow for arbitrary Ints as seconds.
