### ISSUE TITLE
[filter box] re-word Global Filters

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6861]
Global filtering text is a little confusing.
Functionality is to limit the filter selections in the selectors by specifying a filter for the filters

Throwing out some suggestions, but definitely need input/feedback/better suggestions:

**Label**
current: Global Filters
proposed: Limit Selector Values

**Help Mouseover**
current: "These filters, like the time filter, will be applied to each individual filters as the values are populated"
proposed: "These filters apply to the values available in the dropdowns"

<img width="471" alt="screen shot 2019-02-12 at 12 33 36 pm" src="https://user-images.githubusercontent.com/33429480/52666244-97fd3e00-2ec2-11e9-97c2-19de99bbf354.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dorq** [comment]
I don't personally understand the usage of these enough to make better suggestions, but I'm really glad you're flagging this!  Please let me know if you'd like me to spend any time on it.

**Comment by MarcusSorealheis** [comment]
https://github.com/apache/incubator-superset/pull/6885

**Comment by kristw** [comment]
I am not sure about "Limit Selector Values". I personally do not understand what it means.

**Comment by vylc** [comment]
@kristw definitely looking for something better--any suggestions?

**Comment by kristw** [comment]
Perhaps tag designers for ideas @elibrumbaugh @dorq

**Comment by mistercrunch** [comment]
Suggested changes were merge, letting this open in case someone has better suggestions.
