### ISSUE TITLE
Some pages fail to load styling and the loading GIF never goes away

### ISSUE THREAD

**Issue by gabrielmip** [apache/incubator-superset#6878]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Pypi version according to the README label: `0.28.1`
Commit hash: `60d5f89faaa6e76fdfb87d3ba8d76766d268a43f`
I am running a docker-based host that was created following the steps provided [here](https://superset.incubator.apache.org/installation.html#start-with-docker).

### Expected results
The following frontend routes should open with the correct styling and designed forms:
- `/superset/welcome`
- `/chart/add`
- `/superset/sqllab`

### Actual results
Note that the CSS files load successfully. There are no errors on the `Console` tab. No errors on requests either, according to the docker-compose log.

![sqllab](https://user-images.githubusercontent.com/6828028/52798934-0fb49f80-3060-11e9-8ac8-f742c6273a86.png)

![spinner](https://user-images.githubusercontent.com/6828028/52799803-b6e60680-3061-11e9-8077-6317288905a4.png)

### Steps to reproduce
Just open the pages, either through entering the URL on the browser or clicking the menu.

**Comment by kristw** [comment]
Please see #6694

**Comment by gabrielmip** [comment]
Sorry about the duplication. I did not use good keywords when searching for older issues.
Thanks!
