### ISSUE TITLE
connect to hive with auth=ldap, error No module named 'sasl'"

### ISSUE THREAD

**Issue by yirancui** [apache/incubator-superset#6881]
### Superset version
superset (0.28.1)
python 3.6.7
thrift (0.11.0)
thrift-sasl (0.3.0)
sasl (0.2.1)

HIVE Server : CDH 5.14  HIVE1.0

### Expected results
connect to hive with auth=LDAP

### Actual results
SQLAlchemy URI :hive://username:password@vip.dsjkafai.com:10010/?auth=LDAP
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nNo module named 'sasl'"}

### Steps to reproduce
auth=Plain or auth =NOSASL show error

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nPassword should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes"}

**Comment by yirancui** [comment]
now，i try to logout the superset web console，and logon again。URI：hive://username:password@IP:10010/?auth=LDA ,when i test，it shows“seems ok”。
 
But after saved，and connect again it shows error:
![default](https://user-images.githubusercontent.com/43205412/52834778-73050700-311e-11e9-9b9c-4087d05065f9.png)

**Comment by MarcusSorealheis** [comment]
@yirancui 

1st question: what version of `PyHive` are you using? Be sure that you are on `>=0.6.1` as well.

2nd question: it is less likely to be a connection issue (and therefore not a Superset issue) if you see Seems OK & are on the correct version of `PyHive`. The console output you included above are mainly related to permissions.
