### ISSUE TITLE
windows Installation issue: ModuleNotFoundError: No module named 'click' but it is installed

### ISSUE THREAD

**Issue by mcmauro** [apache/incubator-superset#6886]
Hello there,
following up the installation procedure https://superset.incubator.apache.org/installation.html

I got into the following error "ModuleNotFoundError: No module named 'click'" when I run the cmd :" python superset db upgrade".
Pls find below the last successfully cmd  and when I triggered the problem. I tried even to pip the click but it is already available and installed as module but it seems not visible under venv ? I do not know if do I have to configure a special path for...?

from cmd shell:
(venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>fabmanager create-admin --app superset
Username [admin]: mauro
User first name [admin]: susi
User last name [user]: elisa
Email [admin@fab.org]:
Password:
Repeat for confirmation:
Recognized Database Authentications.
Admin User mauro created.

(venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>python superset db upgrade
Traceback (most recent call last):
  File "superset", line 3, in <module>
    import click
ModuleNotFoundError: No module named 'click'

(venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'click'
>>> ^Z

(venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>pip install click
Requirement already satisfied: click in c:\users\mcm\appdata\local\programs\python\python36\lib\site-packages (6.7)

(venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>python superset load_examples
Traceback (most recent call last):
  File "superset", line 3, in <module>
    import click
ModuleNotFoundError: No module named 'click'

### Superset version
superset 0.28.1

### Expected results
No error coming when I run the following cmds ( from https://superset.incubator.apache.org/installation.html) :

###- Initialize the database
superset db upgrade

###- Load some data to play with
superset load_examples

###- Create default roles and permissions
superset init

###- To start a development web server on port 8088, use -p to bind to another port
superset runserver -d
but for all of them I get the following error: " ModuleNotFoundError: No module named 'click'" even if such module is present

### Actual results
ModuleNotFoundError: No module named 'click'

### Steps to reproduce
over the Installation procedure https://superset.incubator.apache.org/installation.html 
running the cmd:  (venv) C:\Users\MCM\AppData\Local\Programs\Python\Python36\Scripts>python superset db upgrade

Many thanks in advance for your help!
Ciao,
Mauro.

**Comment by kristw** [comment]
I believe Superset is not supported on Windows.

**Comment by mcmauro** [comment]
Hello there! 
Superset it is supported on Windows I have just find a WA to install it successfully.
I did from scratch in a couple of laptop hence I am quite confident that the procedure that I am gonna share with u below is OK.
the main problem is that the installation procedure https://superset.incubator.apache.org/installation.html is missing of some important details in my opinion...
Very short I can tell you that the problem was that it is needed to pip some modules directly under the venv... If are already installed does not has any effect because the superset is installed under venv I guess...btw, the procedure below is working for me and I hope will help...

The topic is closed for me. :)


Install Python3.6

Microsoft Visual C++ 14.0 is required

google and download the Installer and then from the Interfce install the Microsoft C++ 14

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>pip install virtualenv

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>virtualenv venv

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>venv\Scripts\activate
(venv) C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>

open a new DOS shell and install the packages listed below from the path below:
C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts\venv\Scripts>
pip install --upgrade setuptools pip
pip install cryptography
pip install click
pip install flask
pip install pandas==0.23.4  ( very important do not install the latest pandas version)

Move in the DOS shell/path below and run the superset installation
(venv) C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>
pip install superset

# Create an admin user (you will be prompted to set a username, first and last name before setting a password)
fabmanager create-admin --app superset
# Initialize the database
python superset db upgrade
# Load some data to play with
python superset load_examples
# Create default roles and permissions
python superset init
# To start a development web server on port 8088, use -p to bind to another port
python  superset runserver -d
enjoy superset from:
http://localhost:8088

**Comment by mcmauro** [comment]
Hello there! 
Superset it is supported on Windows I have just find a WA to install it successfully.
I did from scratch in a couple of laptop hence I am quite confident that the procedure that I am gonna share with u below is OK.
the main problem is that the installation procedure https://superset.incubator.apache.org/installation.html is missing of some important details in my opinion...
Very short I can tell you that the problem was that it is needed to pip some modules directly under the venv... If are already installed does not has any effect because the superset is installed under venv I guess...btw, the procedure below is working for me and I hope will help...

The topic is closed for me. :)


Install Python3.6

Microsoft Visual C++ 14.0 is required

google and download the Installer and then from the Interfce install the Microsoft C++ 14

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>pip install virtualenv

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>virtualenv venv

C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>venv\Scripts\activate
(venv) C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>

open a new DOS shell and install the packages listed below from the path below:
C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts\venv\Scripts>
pip install --upgrade setuptools pip
pip install cryptography
pip install click
pip install flask
pip install pandas==0.23.4  ( very important do not install the latest pandas version)

Move in the DOS shell/path below and run the superset installation
(venv) C:\Users\MCM_1\AppData\Local\Programs\Python\Python36\Scripts>
pip install superset

# Create an admin user (you will be prompted to set a username, first and last name before setting a password)
fabmanager create-admin --app superset
# Initialize the database
python superset db upgrade
# Load some data to play with
python superset load_examples
# Create default roles and permissions
python superset init
# To start a development web server on port 8088, use -p to bind to another port
python  superset runserver -d
enjoy superset from:
http://localhost:8088
