### ISSUE TITLE
User variables

### ISSUE THREAD

**Issue by thomashs** [apache/incubator-superset#6888]
Hi. I'm interested to know if there is possibility to set user variables, such as `company_id` and then retrieve this in the SQL statement in order to segment data amongst several users. Also if there is an API to create users and set this variables. Thanks!

**Comment by mistercrunch** [comment]
Sounds like you're talking about what we've referred to as "row level security". The short answer is not yet but you can search the issues for a more detailed answer.

**Comment by Neuliaus** [comment]
To be honest this is something we would love to have as well, in the mid time we handle it in two very different ways . 
1- Query base, where the source data had the company ID and for everything we do we add WHERE company_ID = "ID" which is annoying when we are bringing data from other services , it means that you need to create a micro ETL that adds a custom company_ID value into all your tables . 
2- Full Cloud-formation pipeline per Company , which creates it's a DB with multiple tables for one company , and /or partition by company , then we fuel template dashboard from different source DB's

**Comment by mistercrunch** [comment]
Dynamically  creating views can be a way to work around the lack of row-level-security.
