### ISSUE TITLE
New button turns black on dashboard page

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6891]
New button appears teal on all other pages, but turns black when viewing dashboard
<img width="1319" alt="screen shot 2019-02-15 at 6 06 57 am" src="https://user-images.githubusercontent.com/33429480/52861691-21da2080-30e8-11e9-9d80-409f54307539.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
v.031

**Comment by vylc** [comment]
@mistercrunch

**Comment by mistercrunch** [comment]
Fixed
