### ISSUE TITLE
Chart configuration experience needs to be improved

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6892]
While user is attempting to configure a chart, Superset attempts to run query. This results in too many errors getting displayed in the chart error that are irrelevant once user correctly configures chart options.
Okay to keep error checking for required fields, but should not display data type errors when user is still configuring chart
<img width="1324" alt="screen shot 2019-02-15 at 6 16 16 am" src="https://user-images.githubusercontent.com/33429480/52862436-24d61080-30ea-11e9-8878-2550bf609ab6.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

v.031

**Comment by vylc** [comment]
@mistercrunch

**Comment by mistercrunch** [comment]
How do I repro?
