### ISSUE TITLE
[kepler.gl] entire viz disappears when mouse hovers over chart

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6893]
<img width="1333" alt="screen shot 2019-02-15 at 6 37 59 am" src="https://user-images.githubusercontent.com/33429480/52863320-68317e80-30ec-11e9-9ff9-22d3c80d92d2.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

v.031

**Comment by vylc** [comment]
@mistercrunch

**Comment by kristw** [comment]
I don't think we have kepler in Superset. Could you check the chart name again?

**Comment by vylc** [comment]
^^ this is beta-ish for @mistercrunch 's plugin for kepler as a viz type

**Comment by kristw** [comment]
oh... that one.

**Comment by mistercrunch** [comment]
not sure how to reproduce...

**Comment by vylc** [comment]
sporadic but frequent--seems to happen when I include a larger number of columns--say 10+ columns. can show you next week...

**Comment by vylc** [comment]
maybe related, but also get this after interacting w/ kepler (ie.zooming into where points are) also, autozoom seems to not be working
<img width="545" alt="Screen Shot 2019-03-30 at 7 43 02 PM" src="https://user-images.githubusercontent.com/33429480/55284073-47338e80-5324-11e9-9171-775ffb900fff.png">
