### ISSUE TITLE
the last query result data should disappear, but there is no..

### ISSUE THREAD

**Issue by mingdongcheng** [apache/incubator-superset#6896]
On the master branch，when changing the query condition and querying again, when the query result has no data, the last query result data should disappear, but there is no..

![image](https://user-images.githubusercontent.com/1491696/52895197-fe9b9800-31f1-11e9-96c0-cba5970d83b8.png)

**Comment by mistercrunch** [comment]
I also noticed this regression recently. Errors don't clear the chart's dom element
