### ISSUE TITLE
Problems encountered in superset 0.28.1 integrated echarts

### ISSUE THREAD

**Issue by Llyfighting** [apache/incubator-superset#6899]
```
ERROR in ./src/visualizations/index.js 85:19
Module parse failed: Unexpected token (85:19)
You may need an appropriate loader to handle this file type.
| var loadNvd3 = function () {
|   function loadNvd3() {
>     return loadVis(import( /* webpackChunkName: "nvd3_vis" */'./nvd3/adaptor.jsx'));
|   }
| 
 @ ./src/modules/AnnotationTypes.js 17:22-50
 @ ./src/chart/chartAction.js
 @ ./src/explore/components/ExploreViewContainer.jsx
 @ ./src/explore/App.jsx
 @ ./src/explore/index.jsx
 @ multi babel-polyfill ./src/explore/index.jsx
```
Hello, every time I run 'npm run dev' to 92% it will report this error, I would like to ask why this is, looking forward to your guidance. Thanks

**Comment by kirankumarpv** [comment]
Same here.. Getting this issue.. on 0.28.1

**Comment by Llyfighting** [comment]
I've solved this problem. It's due to the lack of packages. Go into the superset/static/assets directory and run'npm run dev'. You can see my notes for details, but it's in Chinese.https://blog.csdn.net/qq_33172735

**Comment by mildrabbit** [comment]
@Llyfighting How to contact you?  I'd like to ask you some questions,Thanks!

**Comment by Llyfighting** [comment]
You can contact me through Netease mailbox llynov17@163.com

**Comment by AaronCH5** [comment]
@Llyfighting Can you help me? when i run <npm run dev> occur an question like your blog, but i run <npm intall> can't pass it, so  i need help, can you give your  contact information. TKS
