### ISSUE TITLE
Stacked area chart shows gaps when null values present

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6906]
Chart has weird gaps when there are null values in the dataset. Expectation is that areas with null values are shaded a darker color to represent null or are not rendered (go to 0)
<img width="840" alt="screen shot 2019-02-17 at 10 56 00 pm" src="https://user-images.githubusercontent.com/33429480/52933320-d0a87780-3307-11e9-92de-21c81e21cf52.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
I think the solution for this is around when we'll move away from nvd3. Unless we expose an option to replace nulls with zeroes that addresses this.

**Comment by kristw** [comment]
@conglei Is this one fixed by your bug bash?

**Comment by conglei** [comment]
@kristw. This is a separate issue. This is a bug introduced by nvd3
