### ISSUE TITLE
surperset hive 

### ISSUE THREAD

**Issue by FelixJHuang** [apache/incubator-superset#6907]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.20.0

### Expected results
Visualization sucess

### Actual results
(pyhive.exc.OperationalError) TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask:28:27', 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:315', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:180', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:207', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:257', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:406', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:387', 'sun.reflect.GeneratedMethodAccessor164:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:606', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:415', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1672', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy27:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:258', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:490', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:285', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1145', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:615', 'java.lang.Thread:run:Thread.java:724'], sqlState='08S01', errorCode=1, errorMessage='Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask'), operationHandle=None) [SQL: "SELECT xxx"]

**Comment by anddyhuaa** [comment]
sqlState='08S01'?  i think you could check the hive server log for details

**Comment by mistercrunch** [comment]
Why running `0.20.0` ?

**Comment by anddyhuaa** [comment]
I've experienced that you have to recreate dozens of dashboards manually if do upgrade to the newest version coz actually the functions e.g.(export and import dashboards ) had not been well tested before deployed. there is little test on crossing and compatible versions,  slow step to do the upgrade.

**Comment by FelixJHuang** [comment]
> I've experienced that you have to recreate dozens of dashboards manually if do upgrade to the newest version coz actually the functions e.g.(export and import dashboards ) had not been well tested before deployed. there is little test on crossing and compatible versions, slow step to do the upgrade.

upgrade to the newest ,it is ok,thinks

**Comment by Mellorison** [comment]
Other alternative is to fork the latest version of superset then migrate your dashboards(visualizations) after connecting your database to the latest running instance.

**Comment by anddyhuaa** [comment]
yeah，that’s another way upgrading but on premise that the data model in database is not changed at least not much changed

在 2019-03-04 18:17:28，"Daniel Tumelo" <notifications@github.com> 写道：


Other alternative is to fork the latest version of superset then migrate your dashboards(visualizations) after connecting your database to the latest running instance.

**Comment by Vity01** [comment]
I got a same exception. 
Check if the user has sufficient rights to do such query.
Make sure you define that user in connection string - eg. `hive://vity@hiveserver.something.com:10000`
That helped mi to fix my problem.

**Comment by mistercrunch** [comment]
Wait why can't you just `superset db upgrade` ? `~0.27` introduced a new dashboard app, but outside of that everything should upgrade nicely.

**Comment by anddyhuaa** [comment]
ok,i will see and make sure what that command doing and push a test,thanks

在 2019-03-12 13:33:44，"Maxime Beauchemin" <notifications@github.com> 写道：


Wait why can't you just superset db upgrade ? ~0.27 introduced a new dashboard app, but outside of that everything should upgrade nicely.
