### ISSUE TITLE
large data not on SQLLAB 

### ISSUE THREAD

**Issue by ManojKumarMaurya** [apache/incubator-superset#6909]
<

large data result from giving error sqllab 

  ret = select.select(self.wait_fds, [], [], timeout)
OverflowError: timestamp too large to convert to C _PyTime_t
[2019-02-18 12:04:49 +0000] [8828] [INFO] Worker exiting (PID: 8828)
[ERROR] Exception in worker process
!--

- [* ] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [* ] I have reproduced the issue with at least the latest released version of superset.
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.28.1
### Expected results

result not showing on sqllab 
### Actual results
no output 

### Steps to reproduce

<img width="1073" alt="screen shot 2019-02-18 at 6 24 13 pm" src="https://user-images.githubusercontent.com/5546605/52952477-a9ef4d00-33aa-11e9-9d9d-de90f3943776.png">

**Comment by ManojKumarMaurya** [comment]
hi if any can help really great

**Comment by ManojKumarMaurya** [comment]
hey guys 

please help  still we are facing issue   long-running query after that browser is getting blank  after wait some its come back normal mode but query results did not get the download 
<img width="1433" alt="screenshot 2019-02-25 at 1 12 36 am" src="https://user-images.githubusercontent.com/5546605/53304389-a6703000-389a-11e9-8d9e-ebbd6f2fbe87.png">


Unable to persist state to localStorage: DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'redux' exceeded the quota.

**Comment by kknd113** [comment]
Experiencing the exact same issue

**Comment by kunwang0916** [comment]
Had the same warning in chrome console, and Can't change the tab of modify the SQLEditor's tabs anymore.

**Comment by graceguo-supercat** [comment]
Hi, this error indicates browser's localStoage is used up. 
In Sql Lab, if you open a query tab, sql lab will store queries and results in browser's localStorage. 

So you probably want to save old queries, and close query tab frequently.

<img width="399" alt="Screen Shot 2019-05-08 at 3 25 54 PM" src="https://user-images.githubusercontent.com/27990562/57412490-ad25f800-71a5-11e9-9e7a-6bc0a33f062a.png">

**Comment by kunwang0916** [comment]
Looks like the `localStorage` only allow 5MB data in Chrome, and the cached data is beyond the limitation. I briefly checked the structure of the cached data, the field `queries` has 874 items and took most of the file size. it'd better to add a limitation of the number of `queries`.

**Comment by kunwang0916** [comment]
So I found a hacky way to resolve this issue.
- Open the `setting` of Chrome.
- on `Application` tab, find the local Storage.
- Check the key of `redux`, Copy the value of `redux`
- Delete the field of `queries`, and save back.
It's works for me.

For long term, I suggest to add a limitation of the number of filed `queries`.

**Comment by kun-borderxlab** [comment]
@graceguo-supercat Thanks for your hard work to solve this issue.
