### ISSUE TITLE
Back button: error page with reverse proxy

### ISSUE THREAD

**Issue by tdemalliard** [apache/incubator-superset#6914]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1
from docker image amancevice/superset:0.28.1

### Expected results
When editing a chart, hit the 'back' arrow should display the previous page.

### Actual results
The URL it loads is wrong

### Steps to reproduce
1. Connect to superset
1. go to /chart/list/ page
1. edit a chart
1. hit arrow to go back.

### more information
Superset is behind a reverse proxy: Apache Traffic Server version 5.3.0.

Here is an example of the weird URL:
```
https://<url>/https/1.1%20buildvm-16.phx2.fedoraproject.org%5BCEA7FC91%5D%20%28ApacheTrafficServer/5.3.0%29://superset.cartagene.qc.ca/https/1.1%20buildvm-16.phx2.fedoraproject.org%5BCEA7FC91%5D%20%28ApacheTrafficServer/5.3.0%29://superset.cartagene.qc.ca/chart/list/
```

I decoded the session cookie:
```json
{  
   "_fresh":true,
   "_id":"e6f031a0c72d903bd7a6433db7972506a3f5fb29af1f743489f9a2fde5793d53afac2a93c30ba7a7e022cc06d89413d3a0413cc740979a050b7ab2b355da8723",
   "csrf_token":"a7d8bb6b1268ca0c2f411310f928bb35f294bc32",
   "locale":"en",
   "page_history":[  
      "https/1.1 buildvm-16.phx2.fedoraproject.org[CEA7FC91] (ApacheTrafficServer/5.3.0)://<url>/chart/edit/78",
      "https/1.1 buildvm-16.phx2.fedoraproject.org[CEA7FC91] (ApacheTrafficServer/5.3.0)://<url>/chart/list/",
      "https/1.1 buildvm-16.phx2.fedoraproject.org[CEA7FC91] (ApacheTrafficServer/5.3.0)://<url>/chart/edit/78"
   ],
   "user_id":"1"
}
```

So it seems that the page_history stack grab some headers from the reverse proxy.

I will carry on my investigations.

**Comment by tdemalliard** [comment]
Issue solve with my reverse proxy configuration.

The protocol was taken from the `X-Forwarded-Proto` header but this header got other strings than only 'https' or 'http'

**Comment by mistercrunch** [comment]
![concombre](https://user-images.githubusercontent.com/487433/53059061-6eb45300-346a-11e9-98c3-8014894d3de9.jpg)

**Comment by tdemalliard** [comment]
![image](https://user-images.githubusercontent.com/3911087/53060252-c614ec00-3487-11e9-8944-d692e5dcb5c9.png)
Un bon fan ici aussi ;)
