### ISSUE TITLE
Format numbers over a Billion with a 'B' instead of a 'G'

### ISSUE THREAD

**Issue by sanjoyamazon** [apache/incubator-superset#6916]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29

### Expected results
For numbers that are greater than a Billion, 10**9, we would like to suffix the number with a 'B' instead of a 'G'.

### Actual results
2.0G for 2,000,000,000

### Steps to reproduce
Use any number greater than 1,000,000,000.

**Comment by mistercrunch** [comment]
`G` is the symbol for `Giga`. The method we use is `.3s` out of `d3.format` which is somewhat standard. While switching from `G` to `B` might make it more clear to you and some subset of users, it may make it more confusing to others, or the simple fact of changing it might confuse some.

I'm not opposing this change but just mentioning that there are pro/cons.

**Comment by kristw** [comment]
@mistercrunch The `G` thing has been bugging me for quite some time. I have implemented a new adaptive formatter and propose we use this one as default instead of `.3~s`

**Comment by mistercrunch** [comment]
👍  I'm open to this change.

**Comment by anddyhuaa** [comment]
yeah,that’s the problem i think the measurement more 
flexible could never be better

**Comment by kristw** [comment]
Implemented in `@superset-ui/number-format` and integrated in #6982

**Comment by chesterxgchen** [comment]
B => billions only for certain numbers, count of files or users for example, 
G => used for storage size, can not substitute by Billion. Superset should have different format choices depends on the use case, rather interchange them

**Comment by kristw** [comment]
@chesterxgchen Yes, I can add more formatting choice. Will note that as feature request.
I believe `B` will be a better default at the moment as most cases are business reporting.
