### ISSUE TITLE
installation error on mac

### ISSUE THREAD

**Issue by ohoroyoi** [apache/incubator-superset#6918]
`git clone https://github.com/apache/incubator-superset/
cd incubator-superset/contrib/docker
docker-compose run --rm superset ./docker-init.sh
docker-compose up`

followed `start with docker` I failed.
that part is `docker-compose run --rm superset ./docker-init.sh` 
it returns 

`N18016ui-MacBookPro:docker n18016$ docker-compose run --rm superset ./docker-init.sh`
`Starting superset_redis_1    ... done`
`Starting superset_postgres_1 ... done`
`standard_init_linux.go:207: exec user process caused "permission denied"`

I make sure my directory as 777 recursively.

`N18016ui-MacBookPro:workspace n18016$ stat -f %A incubator-superset/`
`777`

`N18016ui-MacBookPro:docker n18016$ ls`
`Dockerfile              docker-compose.yml      docker-entrypoint.sh    docker-init.sh          superset_config.py`
`N18016ui-MacBookPro:docker n18016$ stat -f %A docker-init.sh `
`777`

but it still returns permission error.

**Comment by anddyhuaa** [comment]
it’s OK for your compose file coz you have already started the containers up and the problem occurs i think from Dockfile 
RUN useradd --user-group --create-home --no-log-init --shell /bin/bash superset

**Comment by ohoroyoi** [comment]
I solved this issue to remove
