### ISSUE TITLE
hive mapreduce.job.queuename

### ISSUE THREAD

**Issue by FelixJHuang** [apache/incubator-superset#6919]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.20.5

### Expected results

can you tell me how to seting hive queuname？ thinks

**Comment by anddyhuaa** [comment]
you can go  Pyhive or impyla project on github and check out the specific configuration and see how connecting to hive server.there are no other ways i think except setting hive-site.xml or adding the queue name parameter to the script before open cursor

**Comment by FelixJHuang** [comment]
> you can go Pyhive or impyla project on github and check out the specific configuration and see how connecting to hive server.there are no other ways i think except setting hive-site.xml or adding the queue name parameter to the script before open cursor

already add the queue name parameter to the script , it is ok,thinks.

**Comment by fan-code** [comment]
can you tell me how to add the queue name parameter to the script? thanks

**Comment by bkyryliuk** [comment]
add this to extra in DB
```
{
"metadata_params": {},
"engine_params": {"connect_args": {"configuration": {"mapreduce.job.queuename": "mr_queue_name", "tez.queue.name": "tez_queue_name"}}},
"metadata_cache_timeout": {},
"schemas_allowed_for_csv_upload": []
}
```
