### ISSUE TITLE
sunburst: duplicated items

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#692]
I assumed to get at most one item for each possible value. But I am getting up to 2 arcs for the same value. Arcs for the same value have different size but same color.
Tested both 0.9.0 and 0.9.1. Data is from a sqlalchemy table.

**Comment by mistercrunch** [comment]
Are they under different parents?

**Comment by xrmx** [comment]
Nope, it's the very first hierarchy. I have two hierarchy, both use count(*) as metric

**Comment by mistercrunch** [comment]
Could it be something like a trailing white space or something like that?

**Comment by xrmx** [comment]
Nope, doing a plain query "select distinct foo from table" reports no duplicates.

**Comment by xrmx** [comment]
So the problem here is that the group by clause is done with both metric at the same time. So data is not not grouped within each hierarchy but globally.
