### ISSUE TITLE
How to add add "Number format" option to the Table?

### ISSUE THREAD

**Issue by mildrabbit** [apache/incubator-superset#6924]
superset 0.28.1
Because I need to set the data format of the table view, but it's not in the view Settings, how do I add it?Change to the same data format as the PivotTable.  Add "Number format" option to the Table View。。。

**Comment by jeffcumt** [comment]
应该要二次开发，我不会，所以在SQL中就指定了数据的格式

**Comment by mildrabbit** [comment]
thanks

**Comment by mildrabbit** [comment]
@mistercrunch Why closed problems? It's really important in China

**Comment by junlincc** [comment]
> Why closed problems? It's really important in China

feel free to contribute if any features is important to your users. we will make sure it's reviewed .
