### ISSUE TITLE
Add description field to the datasource editor

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#6926]
The legacy datasource editor allowed inputing `description` field allowed inputing a Column and a Metric description that would then be surfaced in the column/groupby/metric dropdown as an info bubble.

The legacy editor still works to edit descriptions, but we're deprecating it. We should add the functionality to the new datasource editor. The fields still exist in the models, so it's a matter of adding a form control `description` to the UI and making sure it gets saved.

It should probably go right under label there:  
<img width="838" alt="screen shot 2019-02-21 at 8 44 34 am" src="https://user-images.githubusercontent.com/487433/53186144-438a4a80-35b5-11e9-9f5a-18ab6f059759.png">

**Comment by MarcusSorealheis** [comment]
can this be closed?
