### ISSUE TITLE
How to configure a datasource Extra parameter?

### ISSUE THREAD

**Issue by lhyundeadsoul** [apache/incubator-superset#6930]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0dev `more ./superset/assets/package.json``installed by docker`

### Expected results
![image](https://user-images.githubusercontent.com/5850103/53228413-1bd1da00-36bc-11e9-8402-a341ca2ecf00.png)
press save button, engine param can be configered correctly

### Actual results
Invalid argument(s) 'pool_size','max_overflow' sent to create_engine(), using configuration PGDialect_psycopg2/NullPool/Engine. Please check that the keyword arguments are appropriate for this combination of components.

### Steps to reproduce
1. go to Edit Database Page
2. config Extra section
3. save button

**Comment by zhaoyongjie** [comment]
Please try wrap arguments by "connect_args"
```
"engine_params": {"connect_args": {"pool_size": 10: "max_overflow": 20}}
```

**Comment by lhyundeadsoul** [comment]
> Please try wrap arguments by "connect_args"
> 
> ```
> "engine_params": {"connect_args": {"pool_size": 10: "max_overflow": 20}}
> ```
> reference from
> https://docs.sqlalchemy.org/en/latest/core/engines.html?highlight=create_engine#sqlalchemy.create_engine

Thanks for help!

But i got a following error 
>(psycopg2.ProgrammingError) invalid dsn: invalid connection option "pool_size" (Background on this error at: http://sqlalche.me/e/f405)

I have checked the doc out, and i supposed that the "pool_size" and "connect_args" might be in one level ,rather than "pool_size" is underlying the "connect_args"

thank you any way

**Comment by lhyundeadsoul** [comment]
@kristw hey dude, I haven't gotten the answer to this question and why u close this issue?

**Comment by kristw** [comment]
My apology. I misunstood while triaging the issues. Please feel free to reopen if this happens.

**Comment by mistercrunch** [comment]
Here's how it goes:
https://github.com/apache/incubator-superset/blob/b5d03c85c578bd12bfb99446a54543bd029361ad/superset/models/core.py#L800-L820

**Comment by jayhjha** [comment]
@lhyundeadsoul were you able to figure this out? 
I'm having the same issue on Superset v0.35.1.

When I use 
```
"engine_params": {"connect_args": {"pool_size": 10: "max_overflow": 20}}
```
I get: 
```
(psycopg2.ProgrammingError) invalid dsn: invalid connection option "pool_size" (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by jayhjha** [comment]
It seems like Superset is using `NullPool` so `pool_size` and `max_overflow` won't work for that.
