### ISSUE TITLE
fabmanager fails on install due to newer Pandas version

### ISSUE THREAD

**Issue by joshbrooks** [apache/incubator-superset#6939]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

This is because when I `pip install superset` the version of pandas is not the version specified in the reqs file (0.23.4) but a newer version which has refactored this method out.

### Superset version
0.28.1
Ubuntu 18.04

### Expected results
Following the instructions results in a working Superset installation

### Actual results
Installing Superset as per [instructions](https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization) fails with the following error

```bash
fabmanager create-admin --app superset
```
```python
Error: cannot import name '_maybe_box_datetimelike'
```

### Steps to reproduce

pip install superset
fabmanager create-admin --app superset

As a workaround, `pip install pandas==0.23.4`

**Comment by gldwolf** [comment]
Thanks, I've met this issue either!
