### ISSUE TITLE
Was unable to import superset Error: No module named 'wtforms_json'

### ISSUE THREAD

**Issue by mfirry** [apache/incubator-superset#6947]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Steps to reproduce
❯ docker-compose run --rm superset ./docker-init.sh

Creating superset_redis_1    ... done
Creating superset_postgres_1 ... done
+ '[' 1 -ne 0 ']'
+ exec ./docker-init.sh
+ fabmanager create-admin --app superset
Username [admin]:
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Password:
Password:
Repeat for confirmation:
Was unable to import superset Error: No module named 'wtforms_json'

**Comment by mfirry** [comment]
I think this is due to the the following two lines on the Dockerfile:

```
COPY requirements.txt .
COPY requirements-dev.txt .
```

both files can't be found If (as suggested https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#L46) you're in `/contrib/docker`

**Comment by mfirry** [comment]
Same for `.flaskenv`

**Comment by mistercrunch** [comment]
Are you following http://superset.apache.org/installation.html#start-with-docker ?

**Comment by mfirry** [comment]
Yes

**Comment by ganeshkrishnan1** [comment]
Same issue here. This is with the latest master branch

**Comment by bkowshik** [comment]
I am facing this issue too.

**Comment by mistercrunch** [comment]
What's the host OS?

**Comment by JanHuege** [comment]
Same issue here. Got the following versions:

HostOs is Ubuntu:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

~/incubator-superset/contrib/docker$ docker -v
Docker version 18.09.1, build 4c52b90
~/incubator-superset/contrib/docker$ docker-compose -v
docker-compose version 1.23.2, build 1110ad01

**Comment by Trabing** [comment]
bump

**Comment by KilimAnnejaro** [comment]
Hi, I resolved this issue by commenting out the lines "import wtforms_json" and "wtforms_json.init()" from superset/__init__.py. (Before this, I tried installing wtforms_json with both the pip and pip3 commands and the issue didn't get fixed.)

Hope this helps!

**Comment by rjurney** [comment]
I have also had issues with this at one point.

**Comment by qjyn1314** [comment]
我现在安装superset是最新master版本代码，遇到了  ModuleNotFoundError: No module named 'wtforms_json'  
也使用了  pip 安装了，但是问题并没有得到任何解决，python版本是3.6.7，开源人员可以帮助解决一下吗？

**Comment by rangerzhou** [comment]
Ubuntu 18.04 LTS版本，
python 3.7
Was unable to import superset Error: No module named 'wtforms_json'

**Comment by gauravencoded** [comment]
i am facing similar issues too
