### ISSUE TITLE
[table config] new metrics don't show up in explore

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6950]
After creating a new calculated column or metric from the modal table config in Explore View, the new metric/column is not available. User must manually refresh Explore view to choose newly created metric

Repro:

Click on datasource to edit

Create new metric

Save (brings back to Explore view)

Look for new metric 

Not there

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

v.031

**Comment by kate-gallo** [comment]
Same thing happen to us. 
Clicking on the datasource, `Edit datasource`, changing SQL in the advanced settings doesn't bring new metrics on the visualisation. 
On columns, `Sync columns from source` is not available.

If I click on `view query` I get something like this:

```
SELECT month AS month,
                old_metric AS old_metric
FROM
  (SELECT DATE_TRUNC('month', date_time) AS month,
          COUNT(DISTINCT column_1) AS old_metric,
          COUNT(DISTINCT column_2) AS new_metric
   FROM table
   GROUP BY 1) AS expr_qry
WHERE month >= '1919-06-13 00:00:00'
LIMIT 1000;
```

So the query is not updated with the new column in my modified SQL query.

**Comment by bryanyang0528** [comment]
+1 for this problem

<img width="891" alt="Screen Shot 2019-09-26 at 17 52 58" src="https://user-images.githubusercontent.com/5171607/65678938-c95c0000-e086-11e9-9cdc-767348ea19ea.png">

Column should be synced even if for views
