### ISSUE TITLE
hope add data mining with the pytorch and scikit-learn ！

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#6951]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999dev

### Expected results
add data mining with the pytorch and scikit-learn！

**Comment by brdhunga** [comment]
As superset is a view layer, should not those things be done in advance ? Like you have a data pipeline that processes data through models built from scikit or pytorch, writes that to db. Superset can then  connect to the datasource.

**Comment by toop** [comment]
Hope add data mining with the pytorch and scikit-learn like Orange3！
