### ISSUE TITLE
Dashboard colors - json not working

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#6961]
Instructions on how to specify consistent colors on a dashboard are here:
https://superset.incubator.apache.org/faq.html#is-there-a-way-to-force-the-use-specific-colors

However, doesn't work and gets overwritten on dashboard refresh.

https://superset.incubator.apache.org/faq.html#is-there-a-way-to-force-the-use-specific-colors

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by thunter009** [comment]
I am having the same issue and consistently getting `'NoneType' object has no attribute 'strip'` when trying to edit dashboard JSON Metadata that was previously valid--specifically I'm adding a "label_colors" object.

**Comment by xtinec** [comment]
Fixed by https://github.com/apache/incubator-superset/pull/7027
