### ISSUE TITLE
Error with bignumber.js when building docker image

### ISSUE THREAD

**Issue by JohnTheLearner** [apache/incubator-superset#6967]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0-dev - Master branch 

### Expected results
Using Mac Mojave (10.14.3) - for quick docker spin-up, expected to build properly following instructions at https://superset.incubator.apache.org/installation.html

### Actual results

When following instructions, received below `bignumber.js` error during build...
```
...
Step 16/21 : RUN cd superset/assets     && npm ci     && npm run sync-backend     && npm run build     && rm -rf node_modules
 ---> Running in bf4df5e1aba1
npm ERR! code E404
npm ERR! 404 Not Found: bignumber.js@8.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/superset/.npm/_logs/2019-03-01T22_09_22_604Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd superset/assets     && npm ci     && npm run sync-backend     && npm run build     && rm -rf node_modules' returned a non-zero code: 1
```

### Steps to reproduce
git clone https://github.com/apache/incubator-superset/
cd incubator-superset/contrib/docker
docker-compose run --rm superset ./docker-init.sh
<error occurs>

### Fix...(I'd be happy to do a PR)
It seems version 8.1.1 of bignumber.js just came out 5 days ago.  Update Dockerfile to also install a specific version of `bignumber.js` as shown here:
```
RUN cd superset/assets \
    && npm install bignumber.js@8.1.1 \
    && npm ci \
    && npm run sync-backend \
    && npm run build \
    && rm -rf node_modules
```
...this allows the build to proceed, and superset to load when doing a `docker-compose up`.

**Comment by villebro** [comment]
Hmm, `bignumber.js` in master has already been at `^8.1.1` for a few days now, are you sure you have a fresh snapshot installed?

**Comment by JohnTheLearner** [comment]
Thanks villebro, that's the first time I cloned the repo.  I blew it away locally and re-cloned and made sure I was on master and still had the issue.

**Comment by philippschw** [comment]
Had the same error and was solved by the suggestion:

```
RUN cd superset/assets \
    && npm install bignumber.js@8.1.1 \
    && npm ci \
    && npm run sync-backend \
    && npm run build \
    && rm -rf node_modules
```
The fix is not necessary for linux host, but on windows server fixed it for me!
