### ISSUE TITLE
Banner for Superset upgrade

### ISSUE THREAD

**Issue by heisenberg1205** [apache/incubator-superset#6970]
Make sure these boxes are checked before submitting your issue - thank you!

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
.27

### Expected results
Is there a possible way to put the banner on existing Superset in bright color with the text "we're upgrading Superset for better experience. Please click here" ?

**Comment by MM-Lehmann** [comment]
Would like to reopen this. 
A markdown banner like in gitlab would perfectly fit our needs to inform users of upcoming maintenance and downtimes.
Any chance to do this in javascript? (I've played around a little in the past but couldn't get anywhere near that)

**Comment by toransahu** [comment]
+1 to this feature request. We also need this.

**Comment by rusackas** [comment]
This thread is ancient, let's not pus this forward. You can start an "ideas" thread on Github Discussions if you want to start from scratch, or you can look at SIP-96 (https://github.com/apache/superset/issues/24271) if you want to support/contribute/modify that proposal.
