### ISSUE TITLE
How to change the gradient of linear color scheme so that it includes negative numbers?

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#6974]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.999.0dev

### Expected results
In the linear color scheme the negative numbers are shown as one color, and the color only starts to change when starting from 0. How can I change the range to [-1, 1]?

**Comment by kristw** [comment]
Which chart is this?

**Comment by klazaj** [comment]
@kristw it is the country map chart

**Comment by klazaj** [comment]
any updated on this bug?
