### ISSUE TITLE
BUG: unable to select column with byteb datatype

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#6981]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
It should return query result 

### Actual results
Unserializable object <memory at 0x7f93249f9ac8> of type <class 'memoryview'>

### Steps to reproduce
create a table with column datatype byteb 

Other information:
Database: Postgresql
In Preview mode, the select query gets fired and shows the result.
When you run the query (select * from table) in sqlLab, it throws
Unserializable object <memory at 0x7f93249f9ac8> of type <class 'memoryview'>

**Comment by villebro** [comment]
Do you have a use case for visualising binary/byte data? It seems the most appropriate handling of bytes would be to either throw a more understandable exception or simply replace the byte values with a `<BINARY DATA>` label or similar.

**Comment by mmuru** [comment]
As I mentioned, in sqllab table preview mode, it fetch and display data
correctly but not in SQLlab query tab. I can not modify the table data
since it is read-only production database table.

**Comment by mistercrunch** [comment]
Do you have a stacktrace by any chance? It should definitely not raise... I think we handle some other binary types. It thought this would be a catchall: https://github.com/apache/incubator-superset/blob/master/superset/utils/core.py#L344

**Comment by mmuru** [comment]
No exception raised otherwise I could have provided stacktrace. I think, the issue with decoding the binary data and surprisingly it works in preview mode.
