### ISSUE TITLE
Was unable to import superset Error: Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy. If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control).  Otherwise reinstall numpy.  Original error was: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Chungleuk** [apache/incubator-superset#6985]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Actual results
cannot be properly install

### Steps to reproduce
fabmanager create-admin --app superset
Username [admin]: test
User first name [admin]: chung
User last name [user]: 
Email [admin@fab.org]: xxx@hotmail.com
Password:
Repeat for confirmation:

Was unable to import superset Error:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mistercrunch** [comment]
`DLL`? Windows?

**Comment by Chungleuk** [comment]
Yes, Windows 10

**Comment by mistercrunch** [comment]
Windows is not supported, it may work with Docker if they've figured how to docker on Windows. Otherwise VMs.

Also this appears to be a numpy compilation error, maybe that community helps. 

It's probably wasted cycles to run software on an unsupported OS. We don't run our test suite against windows, even if it happens to work for some at a given time, there's no guarantees that it will.

**Comment by Chungleuk** [comment]
thanks for your prompt reply
