### ISSUE TITLE
Version info button missing

### ISSUE THREAD

**Issue by matkosoric** [apache/incubator-superset#6992]
I can not find find out version information because version info button in the top right corner is missing. There is only Language button, and Logout/Profile button. I am also running different Superset from Hortonworks VM (HDP 3.0), and there is a clear Version info button that returns:

{"version": "0.23.3", "GIT_SHA": "b'046fdc4f03497932d654dacb4dee5e2eafdb0b53\\n'"}

This is my top right corner:
![top_right_corner](https://user-images.githubusercontent.com/24875759/53960069-8d128380-40e5-11e9-8b93-75210011aa1f.png)

### Superset version
This is the problem. I have installed it today by following instructions from official page:
https://superset.incubator.apache.org/installation.html

**Comment by RohitK89** [comment]
This issue was introduced sometime after 0.26.3. I just installed 0.28.1 and the button is missing.
