### ISSUE TITLE
Can't reach localhost via public IP

### ISSUE THREAD

**Issue by lwallmba** [apache/incubator-superset#6994]
I installed Superset on an EC2 instance.

I run the last command `superset runserver -d`.

Then I use `http://localhost:8088` but replace `localhost` with my public IP, set-up in AWS.

I also run just `superset runserver` and get the following.

> 2019-03-07 20:55:46,877:INFO:root:The Gunicorn 'superset runserver' command is deprecated. Please use the 'gunicorn' command instead.
> Starting server with command:
> gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app
> 
> [2019-03-07 20:55:47 +0000] [1396] [INFO] Starting gunicorn 19.9.0
> [2019-03-07 20:55:47 +0000] [1396] [INFO] Listening at: http://0.0.0.0:8088 (1396)
> [2019-03-07 20:55:47 +0000] [1396] [INFO] Using worker: sync
> [2019-03-07 20:55:47 +0000] [1399] [INFO] Booting worker with pid: 1399
> [2019-03-07 20:55:47 +0000] [1400] [INFO] Booting worker with pid: 1400
> 

In any case, the connection times out.

Any help will be appreciated.

**Comment by Jordan396** [comment]
Hi @lwallmba, first check if your EC2 instance security group has been configured to allow inbound TCP traffic on port 8088. You can find details [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html#adding-security-group-rule).

Once that is done, you should be able to execute either:
  - `superset runserver -d`
  - `gunicorn -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app`

You may not be able to execute `superset runserver` if Gunicorn cannot support more than one worker (probably the reason why your connection times out). Unfortunately, I'm not too familiar with Gunicorn so I can't help much. All the best!

**Comment by loveling0608** [comment]
I have the same question, did you resolve it?

**Comment by bernarde01** [comment]
I have the same problem, but using Google Cloud platform. Anybody figured this out?

**Comment by schaurasia-quot** [comment]
superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
this option is working
