### ISSUE TITLE
Edit dashboard to insert row or column

### ISSUE THREAD

**Issue by rickywu** [apache/incubator-superset#6999]
### Superset version
latest docker image

### Expected results
Insert row or column should work in edit dashboard panel

### Actual results
Just show one blue line after drag and not updated dashboard

### Steps to reproduce
Edit dashboard and insert row/column

![image](https://user-images.githubusercontent.com/442398/54007331-18e6e700-419c-11e9-9bef-b3b900fa62f5.png)

**Comment by MarcusSorealheis** [comment]
Just to be clear, which docker-image?

**Comment by rickywu** [comment]
IMAGE ID aa7706222b78        CREATED 13 days ago
