### ISSUE TITLE
Broken link to SQLAlchemy URI

### ISSUE THREAD

**Issue by matkosoric** [apache/incubator-superset#7001]
The link for structuring SQLAlchemy URI in a form for creating database connection is broken.

### Expected results
Link to:
https://docs.sqlalchemy.org/en/latest/core/engines.html

### Actual results
http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls

### Steps to reproduce
Sources -> Databases -> Add a new record (plus sign) -> and then follow link 'SqlAlchemy docs' in this label: "Refer to the SqlAlchemy docs for more information on how to structure your URI."

**Comment by MarcusSorealheis** [comment]
I actually encountered this bug when I was fixing a different bug and was too lazy to fix it. I'll open a PR and link to the issue.

**Comment by MarcusSorealheis** [comment]
Here is the PR: [#7005](https://github.com/apache/incubator-superset/pull/7005)

**Comment by MarcusSorealheis** [comment]
We can close this one right? The correct doc link has been merged.

**Comment by matkosoric** [comment]
Great!
