### ISSUE TITLE
Getting this after login in windows 

### ISSUE THREAD

**Issue by ankit6373** [apache/incubator-superset#7004]
Why I am getting this after successful login?
![download](https://user-images.githubusercontent.com/18262572/54071874-da832200-4298-11e9-9dc4-f58eab5408ea.png)

**Comment by nanshouyong** [comment]
https://github.com/apache/incubator-superset/issues/6977

**Comment by ankit6373** [comment]
I am still getting the same error after doing this.

**Comment by ankit6373** [comment]
> #6977

I am still getting the same error after doing this.

**Comment by nanshouyong** [comment]
rerun command begin 

Python  superset db upgrade

**Comment by mistercrunch** [comment]
As mentioned in other issues we don't officially support Windows or run tests against it. Use at your own risk.

![FailingRewardingChimneyswift-max-1mb](https://user-images.githubusercontent.com/487433/54179003-c3892f00-4454-11e9-8226-0e1d28ba7af5.gif)
