### ISSUE TITLE
World map viz not working in 0.29rc7/0.31.0rc18/0.32

### ISSUE THREAD

**Issue by elukey** [apache/incubator-superset#7006]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29rc7 (the last one published via Pypi)

### Expected results
World Map has been working fine up to 0.26 (current version that we are using), but it seems not working with 0.29rc7 anymore. 

### Actual results
The graph yields errors like "Too many indexers" and the following stacktrace:

```
Mar 11 11:08:03 analytics-tool1004 superset[27831]: 2019-03-11 11:08:03,985:ERROR:root:Too many indexers
Mar 11 11:08:03 analytics-tool1004 superset[27831]: Traceback (most recent call last):
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/base.py", line 96, in wraps
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     return f(self, *args, **kwargs)
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 1211, in explore_json
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     samples=samples,
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 1142, in generate_json
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     payload = viz_obj.get_payload()
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 374, in get_payload
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     payload['data'] = self.get_data(df)
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 1745, in get_data
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     ndf['m1'] = df[metric].iloc[:,0]
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1471, in __getitem__
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     return self._getitem_tuple(key)
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 2012, in _getitem_tuple
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     self._has_valid_tuple(tup)
Mar 11 11:08:03 analytics-tool1004 superset[27831]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 219, in _has_valid_tuple
Mar 11 11:08:03 analytics-tool1004 superset[27831]:     raise IndexingError('Too many indexers')
Mar 11 11:08:03 analytics-tool1004 superset[27831]: pandas.core.indexing.IndexingError: Too many indexers
```
The same dataset works fine with 0.26.

### Steps to reproduce

Create a world map graph and add the Bubbles functionality. In my case, the graph works fine without it but adding it yields to the above error.

Note: during the migration numpy and pandas were upgraded, and I checked that the the same versions are the ones added for 0.29rc8 (I couldn't use this version since not in Pypi).

**Comment by elukey** [comment]
The following change (live hacked on the host) works fine for all our wold map graphs:

`
diff --git a/superset/viz.py b/superset/viz.py
index 068a70dc..f24f063f 100644
--- a/superset/viz.py
+++ b/superset/viz.py
@@ -1742,7 +1742,7 @@ class WorldMapViz(BaseViz):
             ndf = df[cols]
             # df[metric] will be a DataFrame
             # because there are duplicate column names
-            ndf['m1'] = df[metric].iloc[:, 0]
+            ndf['m1'] = df[metric].iloc[:]
             ndf['m2'] = ndf['m1']
         else:
             if secondary_metric:
`

**Comment by mistercrunch** [comment]
Is this an issue on `master`?

**Comment by elukey** [comment]
@mistercrunch not really super easy for me to test master but I'll try. As far as I can see though the issue seems indeed the pandas upgrade.. One thing that I noticed is that the type of `df[metric]` is `pandas.core.frame.DataFrame` in 0.26, meanwhile it is `pandas.core.series.Series` for 0.29rc7.

I also took a look to the comment about the duplicate col names, and it doesn't seem to hold anymore (an example in https://phabricator.wikimedia.org/T212243#5015335).

**Comment by elukey** [comment]
More info received from a colleague of mine: the bubble doesn't work only when the metric used for the Bubble size is also used elsewhere (like metric for color).

**Comment by elukey** [comment]
Tested it with the head of the relese--0.31 branch and I can still reproduce the problem.

**Comment by elukey** [comment]
One interesting thing that I have noticed in my use case (namely a world map displaying pageviews) is that `df` in 0.26 has the following data:

```
country_code  sum__view_count  sum__view_count
0 IT 40 40
1 ...
2 ...
```
The double sum_view_count should be the aggregations that I added for one of the axis and the bubble size IIUC. In 0.29/0.31 `df` is instead:

```
country_code  sum__view_count
0 IT 40
1 ...
2 ...
```

**Comment by mistercrunch** [comment]
Seems similar to this https://github.com/apache/incubator-superset/pull/7087

**Comment by elukey** [comment]
One thing that I have noticed only now in the 0.26's logs is the following warning:
```
Mar 26 09:14:08 analytics-tool1003 superset[21893]: /srv/deployment/analytics/superset/venv/lib/python3.5/site-packages/superset/viz.py:1742: SettingWithCopyWarning:
Mar 26 09:14:08 analytics-tool1003 superset[21893]: A value is trying to be set on a copy of a slice from a DataFrame.
Mar 26 09:14:08 analytics-tool1003 superset[21893]: Try using .loc[row_indexer,col_indexer] = value instead
Mar 26 09:14:08 analytics-tool1003 superset[21893]: See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
Mar 26 09:14:08 analytics-tool1003 superset[21893]:   ndf['m1'] = df[metric].iloc[:, 0]
```

**Comment by elukey** [comment]
The issue seems present even with pandas 0.23.0, I wasn't able to test 0.22 because I am running on Debian Buster and Python 3.7, but if the theory of pandas version change is correct there should be the culprit in:

http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.23.0.html

**Comment by elukey** [comment]
@mistercrunch would something like this work?

```
            # df[metric] will be a DataFrame
            # because there are duplicate column names
-            ndf['m1'] = df[metric].iloc[:, 0]
+            if isinstance(df[metric], pd.DataFrame):
+                ndf['m1'] = df[metric].iloc[:, 0]
+            else:
+                ndf['m1'] = df[metric]
```

Given what written in the comment I suppose that the original code was a workaround for a specific Pandas behavior, that seems to have changed. In theory the above code should be good for all pandas versions.

**Comment by elukey** [comment]
@mistercrunch hi! Any chance that the pull request could be reviewed?

**Comment by elukey** [comment]
Ping :)

**Comment by elukey** [comment]
re-ping again.. I can see 0.31 and 0.32 in the process of being released, so I suppose that this patch (if it will ever be accepted) will go on 0.33+. Now that we have clean apache releases I can build my own version of Superset from 0.31+ and cherry pick this change, but it would be nice not to do it :)

**Comment by mistercrunch** [comment]
Are you running `pip install -r requirements.txt` to insure the pinned version of libs (especially pandas/numpy?)

**Comment by mistercrunch** [comment]
```
$ pip freeze | grep pandas
pandas==0.23.4
$ cat requirements.txt | grep pandas
numpy==1.15.2             # via pandas
pandas==0.23.4
```

**Comment by elukey** [comment]
@mistercrunch we use pip wheel I am pretty sure about the versions that we deploy (pandas and numpy). The bug is clearly visible/reproducible if running those..

**Comment by elukey** [comment]
Tried 0.32rc2 today, doesn't work as well.

**Comment by elukey** [comment]
Sorry for the above mess but I had to find a way to send multiple separate patches to github :)

Is there any blocker that prevents this patch to get reviewed/merged? It has been almost two months.. I don't want to be pressing but only know what to work on to get this finally fixed :)

**Comment by elukey** [comment]
I also forgot in the past to paste the output of pip freeze:

```
(venv) elukey@analytics-tool1004:/srv/deployment/analytics/superset/venv$ pip freeze | egrep 'pandas|numpy'
numpy==1.15.2
pandas==0.23.4
```

This confirms that I am using the versions stated in requirements.txt

**Comment by elukey** [comment]
I traced back the code to this point:

https://github.com/apache/incubator-superset/blob/master/superset/connectors/druid/models.py#L1321

in 0.26 (the version that I am currently running), I can see duplicated columns name if I log `cols`, but not in more recent versions.

**Comment by elukey** [comment]
So the main problem seems to be this difference:

https://github.com/apache/incubator-superset/blob/0.26/superset/viz.py#L1725-L1729

https://github.com/apache/incubator-superset/blob/master/superset/viz.py#L1754-L1757

The diff is the following code, that applied to 0.32 makes the WorldMapViz work again correctly:

```
        qry['metrics'] = [
            self.form_data['metric'], self.form_data['secondary_metric']]
```

**Comment by elukey** [comment]
And the commit that removed it is:

**Comment by elukey** [comment]
Updated the pull request to avoid mentioning pandas and adding a reference to the commit that changed the behavior. In theory there are two possible fixes:
1) partially revert the commit that removed the qry['metrics'] etc.. bits
2) use .iloc only with a dataframe (my approach in the pull request is not 100% pythonic since I could have simply tried .iloc and caught the exception afterwards, but I believe that my version is a bit more clear).

Let me know :)

**Comment by elukey** [comment]
Update: after a bit of testing I decided to update the pull request to avoid all the conditionals logic and simply remove the use of .iloc. From my tests everything looks good, review/merge/etc.. would be really appreciated :)
