### ISSUE TITLE
Missing CSS when running via docker

### ISSUE THREAD

**Issue by trmanish** [apache/incubator-superset#7008]
Hi 

I have installed Superset via the docker containers as mentioned on the documentation page. 

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset/contrib/docker
# prefix with SUPERSET_LOAD_EXAMPLES=yes to load examples:
docker-compose run --rm superset ./docker-init.sh
# you can run this command everytime you need to start superset now:
docker-compose up)

```

I have it installed both on my local mac and on ubuntu server. My mac has 15GB memory and ubuntu server has 32GB. 

Finally after few issues on server I was able to install it. 

However I see the home page and also while clicking on Query Editor on the server Superset, it doesn't load it properly. 

![image](https://user-images.githubusercontent.com/4309723/54156176-ec80d400-4402-11e9-9cd1-ae6ff9808179.png)

This however is not the issue at all with mac superset. The UI loads fine and I am able to use the Query editor and other stuff 

![Screen Shot 2019-03-11 at 1 32 36 PM](https://user-images.githubusercontent.com/4309723/54156270-281b9e00-4403-11e9-9fa0-b0850965f5aa.png)

This happens for both homepage and Query editor. Other pages on server superset are able to load fine 

On Mac, my query editor looks like below: 
![Screen Shot 2019-03-11 at 1 28 46 PM](https://user-images.githubusercontent.com/4309723/54156453-834d9080-4403-11e9-8e52-0570fa36b3f7.png)

What could be the issue there?

Note: 

In the server installation, I have commented out the Development option in docker-compose.yml file. Reason being I was getting a Permission denied issue as per this  (https://github.com/apache/incubator-superset/issues/6887) issue and using one of the suggestion there I commented the development option. That Permission Denied issue got fixed. But I see the UI issue now. On my mac, I was not getting any permission denied error so there I don't have the Development option commented out.

**Comment by gwin-zegal** [comment]
You might have a look at [#6694](https://github.com/apache/incubator-superset/issues/6694)

**Comment by trmanish** [comment]
Mine works fine on mac . It is giving issues only with server one. I installed via docker and one thing I did on server one is comment out the Development one as suggested in this issue. I was getting the same issue and by commenting out the development mode, it got resolved. 

https://github.com/apache/incubator-superset/issues/6887

**Comment by trmanish** [comment]
I just got a fix for this issue and similar issue on Ubuntu. 

In Superset/assets folder change the permission to 777. It would then work and all css files will get correctly loaded. Even sql editor which was not working earlier on ubuntu server and ppl had issues for that also works with this solution. 

Step to do: 

`chmod ugo+rwx assets` if you are running this command under superset folder

**Comment by bwon7** [comment]
I did it, but it just stopped. 
![Screen Shot 2019-05-17 at 2 58 13 PM](https://user-images.githubusercontent.com/38637458/57950353-046a4d80-78b5-11e9-8f34-a35401da750e.png)

**Comment by Aabhusan** [comment]
i am installing the apache-superset in docker hosted in ubuntu 18.04
i have used these steps:
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
# you can run this command everytime you need to start superset now:
docker-compose up
i am stuck in 
68% building 2310/2359 modules 49 active ...ugin-chart-iframe/esm/transformProps.js
can anyone help me as soon as possible?
