### ISSUE TITLE
Npm build error 0.29.0rc8

### ISSUE THREAD

**Issue by pavitranrambo** [apache/incubator-superset#7014]
**I am getting an error everytime i try to build the assets with npm run dev or dev-server
I have tried with versions 0.29.0rc8 and 0.29.0rc7**

ERROR in ./node_modules/@superset-ui/chart/node_modules/@superset-ui/core/esm/utils/makeSingleton.js
Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.to-string' in '/home/pavitran/.local/share/Trash/files/assets.2.9/node_modules/@superset-ui/chart/node_modules/@superset-ui/core/esm/utils'
 @ ./node_modules/@superset-ui/chart/node_modules/@superset-ui/core/esm/utils/makeSingleton.js 1:0-45
 @ ./node_modules/@superset-ui/chart/node_modules/@superset-ui/core/esm/index.js
 @ ./node_modules/@superset-ui/chart/esm/registries/ChartTransformPropsRegistrySingleton.js
 @ ./node_modules/@superset-ui/chart/esm/index.js
 @ ./src/addSlice/AddSliceContainer.jsx
 @ ./src/addSlice/App.jsx
 @ ./src/addSlice/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js ./src/addSlice/index.jsx

ERROR in ./node_modules/@superset-ui/core/esm/models/ExtensibleFunction.js
Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.to-string' in '/home/pavitran/.local/share/Trash/files/assets.2.9/node_modules/@superset-ui/core/esm/models'
 @ ./node_modules/@superset-ui/core/esm/models/ExtensibleFunction.js 1:206-251
 @ ./node_modules/@superset-ui/core/esm/index.js
 @ ./src/visualizations/presets/LegacyChartPreset.js
 @ ./src/setup/setupPlugins.js
 @ ./src/addSlice/App.jsx
 @ ./src/addSlice/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js ./src/addSlice/index.jsx

**Comment by pavitranrambo** [comment]
The latest version fixes this error

**Comment by Heng0405** [comment]
I have the same error here, could you tell me the latest version of what fix this error ?
