### ISSUE TITLE
Superset single point problem

### ISSUE THREAD

**Issue by FelixJHuang** [apache/incubator-superset#7016]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
superser server 

### Steps to reproduce
Superset  runserver single point problem。

**Comment by zhaoyongjie** [comment]
@FelixJHuang Superset is a standard Python WSGI application, you can look for some distributed Python web application solution. eg: Nginx distribute request.

**Comment by mistercrunch** [comment]
Issue is unclear, please reopen with a good description of what your issue is.
