### ISSUE TITLE
[postgres] support asyncpg as an alternative to psycopg2

### ISSUE THREAD

**Issue by dominijk** [apache/incubator-superset#7018]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Latest

### Expected results
Test enhancement with alternate database connectors 

### Actual results
After reading this [post](https://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/) on async I'm interested in exploring alternate python postgres connectors, where do I start?

**Comment by mistercrunch** [comment]
Relevant https://github.com/MagicStack/asyncpg/issues/6
