### ISSUE TITLE
[filter box] filter box being filtered; error shown when no data returned

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7019]
<img width="1044" alt="Screen Shot 2019-03-12 at 2 50 31 PM" src="https://user-images.githubusercontent.com/33429480/54239166-a2b5ed80-44d7-11e9-8d5e-fa0fa6aca186.png">

Usability issues around filter boxes:
(1) If there are multiple filter boxes on a dashboard, all filter boxes receive the "filter" from the other filter boxes on the dashboard. When a user saves a dashboard with preset filters, there is an edge case where no data is returned, and the filter box shows an error as opposed to rendering a dropdown that has no values

(2) Default behavior for filter box dropdowns should be all distinct values in a table

(3) Filter boxes shouldn't receive "filters" from other filter boxes unless explicitly specified (then we run into scenario (1)) There should be an option to enable receiving filters from other filter boxes

MVP: At the very least, we should never show a filter box with an error, should just be a blank filter box.
Better: Filter box to never receive filtering actions from other filters. Allow user to specify filtering via the Global Filters section. Always show the filter box with all distinct values in the datasource
Best: Allow user to specify if filter box should receive filter actions from other filter boxes, but if no data returned, show blank filter box

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by vylc** [comment]
@mistercrunch

**Comment by mistercrunch** [comment]
About (3), people have been using this behavior to implement cascading filters. Though I understand it probably shouldn't be the default.

I think adding a new option "Receive filtering events from other filter boxes" that has a default of False, but is set to True for all existing Filter Box (for backwards compatibility reasons) seems reasonable.

**Comment by mistercrunch** [comment]
I'm not sure if I understand (2) ? Do you mean not having a time filter set by default? The danger is the full table scan can be pretty brutal depending on the table and database engine. For partitioned tables in Presto it's good to try to limit user to scan only a few partitions to fill in these values.

**Comment by shivapriyaramasamy** [comment]
![image](https://user-images.githubusercontent.com/33547853/63857812-f9e64680-c9c1-11e9-88bd-16cc91d9ad77.png)
if value is copy pasted from database fro validating rather than selecting the value from filter box drop down, the particular field seeems empty but the other charts in the dashbpard responds to the change been made.

**Comment by shivapriyaramasamy** [comment]
![image](https://user-images.githubusercontent.com/33547853/63858060-79741580-c9c2-11e9-9ab8-ebb2c23b1163.png)
If value is copy pasted from database for validating rather than selecting the value from filter box drop down, the particular field seems empty but the other charts in the dashboard responds to the change been made.
