### ISSUE TITLE
Support for Timezones

### ISSUE THREAD

**Issue by LAlbertalli** [apache/incubator-superset#703]
Hi,

We are trying to use Caravel in production against a Druid Datastore that ingests real-time data. One issue we noticed is that all the times are in UTC.

It is possible to configure a time-zone per user so that the data is converted to the local timezone when viewing the graph?

We could allocate work to contribute the feature, but I'd like to discuss the best way to implement the feature.

L.

**Comment by Igosuki** [comment]
I've recently had to do ETL using druid with a specific time zone, druid already handles time zones in the query schema so it's likely fairly easy to add. 
We need : 
- An optional time zone field in the time area of slice exploration
- Add the corresponding timezone key in the granularity spec
