### ISSUE TITLE
How do I change the datasource for a chart?

### ISSUE THREAD

**Issue by jasonshah** [apache/incubator-superset#7033]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.30

### Expected results
I should be able to pick from the list of datasources, or otherwise be able to switch to another pre-created datasource.

### Actual results
I'm taking to the confusing Datasource Editor (per [this PR](https://github.com/apache/incubator-superset/pull/6430)). What do I do from here? How do I actually switch to another datasource?

### Steps to reproduce
* Open a Chart
* Tap on the name of the Datasource

![Screen Shot 2019-03-14 at 9 10 09 AM](https://user-images.githubusercontent.com/24223/54363528-13c0e680-4639-11e9-9fc8-60faa509078d.png)

**Comment by mistercrunch** [comment]
Fixed in `master` and `0.31.0rc17`
<img width="362" alt="Screen Shot 2019-03-14 at 5 35 25 PM" src="https://user-images.githubusercontent.com/487433/54400361-a97f6480-467f-11e9-8484-0c34e97f9b74.png">
Thanks to @michellethomas !

**Comment by jasonshah** [comment]
Wonderful, thank you!

**Comment by lilila** [comment]
Is it necessary to set up some authorisations to be able to `change Datasource` . 
When I try it I get an "Access Denied" error message. 

Here is what I can see in the logs:

```
URL: https://zzz.fr/datasource/get/table/49/
Status: 401 UNAUTHORIZED
```
