### ISSUE TITLE
Access denied for user 'ETL_DEV'@'bbox.lan'

### ISSUE THREAD

**Issue by RABEB2** [apache/incubator-superset#7044]
while using Apache superset connexion with dataBase done successfully but when i'm trying to execute sql request i got this error

**(1045, "Access denied for user 'ETL_DEV'@'bbox.lan' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)**

i think that is an error of access what are the permissions required ? or How to resolve this problem?

**Comment by kristw** [comment]
Duplicate of #7042
