### ISSUE TITLE
Filter Customization According to different needs

### ISSUE THREAD

**Issue by maxniranga** [apache/incubator-superset#7049]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

Hi all, I have been working with a project for past few days using Superset. My requirement is to filter results for a time period. Please have a look at the example.

![github_question](https://user-images.githubusercontent.com/38640345/54509796-c6ae7e80-4970-11e9-8bbb-08fac08ac704.PNG)

I have several Big number charts and a bar chart as shown in the picture. 

1. Total Subscribers: Total number of subscribers as of today.
2. New Subscribers: New subscribers for today.

Lets Say I have following numbers of subscribers per month.

January  : 10
February: 15
March    : 12
April       : 8
May       : 6

Lets say I selected the time Period as 1st February to April 30th, So the requirement is as following,
Total Subscribers: 45 (10+15+12+8)
New Subscribers: 35 (15+12+8)

From What I understand following is the filter required for each charts,
Total Subscribers: **From**: ∞  **To**: 30th April
New Subscribers: **From**: 1st of February **To**: 30th April

Is there any way to customize the time filter according to this? Is there anyway to customize time filters in charts? Do i have to change the code? Any type of answers are welcome. Thank you very much in advance.

### Superset version
version": "0.29.0rc7

**Comment by mistercrunch** [comment]
The time filter is limited to what it does (each chart defines the column it uses for time, and applies the dashboard's filtering event on that column)

To work around this, it's possible to:
* design a chart that does not listen to any time filtering events http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard
* use a normal filter for your time filter 
* add columns

**Comment by maxniranga** [comment]
Thank you for the quick reply @mistercrunch . But this does not solve my problem. Please let me know if there is anything I can do to customize the code.

**Comment by Neel-rishabhsoft** [comment]
+1 on this
