### ISSUE TITLE
Black screen on sankey and heatmaps

### ISSUE THREAD

**Issue by jasonshah** [apache/incubator-superset#7058]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.99dev, commit guid 07c340cf8203f13222f16efad1e55e202deb1865

### Expected results
The heatmap and sankey charts render correctly.

### Actual results
The heatmaps show black in many places, including covering the entire screen in the second screenshot. The sankey's lines connecting the axes are black.
(Apologies about the blurring effect in both screenshots; I am trying to protect sensitive information.)
![1](https://user-images.githubusercontent.com/24223/54613297-7692f300-4a28-11e9-8aef-5c8ad6ecdd81.png)
![2](https://user-images.githubusercontent.com/24223/54613312-7d216a80-4a28-11e9-96e4-da61c617ff15.png)

### Steps to reproduce
Open a dashboard that has the sankey or heatmap defined.

**Comment by iaperez** [comment]
it seems to happen only in production mode. I can't reproduce on development mode.

**Comment by mistercrunch** [comment]
That's so weird. It also looks like the heatmap canvas is not rendering in the right spot.

**Comment by mistercrunch** [comment]
When using `npm run dev`, on the `<rect>` behind the heatmap I see:
<img width="335" alt="Screen Shot 2019-04-02 at 9 41 56 PM" src="https://user-images.githubusercontent.com/487433/55453325-37b87d80-5590-11e9-8aef-68db24a756a1.png">

But when I run `npm run build` I don't see it.

**Comment by mistercrunch** [comment]
@kristw @williaster any idea where this could be coming from? Could it be related to missing CSS when packaging the legacy vises?

**Comment by kristw** [comment]
From screenshot it looks like css

**Comment by mistercrunch** [comment]
Yes @kristw , but any idea how/why the CSS would be different on `npm run dev` and `npm run prod`

**Comment by mistercrunch** [comment]
@kristw @williaster I'd love to get input and any intuition you may have on the webpack intricacies that may be at play here before I dive into this one.

**Comment by williaster** [comment]
There's a switch statement for css loading in [`webpack.config.js`](https://github.com/apache/incubator-superset/blob/master/superset/assets/webpack.config.js#L204), I'm not sure why this would be different now that we have plugins though.

**Comment by mistercrunch** [comment]
Oh good catch, though I tried disabling as shown here and it didn't work :(
<img width="740" alt="Screen Shot 2019-04-04 at 9 52 04 PM" src="https://user-images.githubusercontent.com/487433/55604310-f0fb8c80-5723-11e9-9b93-8972360a0a86.png">

I'm not sure how to go about this one.

**Comment by kristw** [comment]
Let me see if I can reproduce.

**Comment by kristw** [comment]
I am looking at it. There are some issues with importing css from the package. Trying to figure out a clean solution.

**Comment by kristw** [comment]
One short-term remedy is to point to the `lib` output instead of using default `esm`. 
For example

```js
import CalendarChartPlugin from '../../../../superset-ui-legacy-plugin-chart-calendar/lib';
```

instead of 

```js
import CalendarChartPlugin from '../../../../superset-ui-legacy-plugin-chart-calendar';
```
