### ISSUE TITLE
[SQL Lab] autocomplete table names, auto-add to schema browser

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#7059]
Currently, autocomplete in SQL Lab's editor is limited to table and column names that have been added to the schema browser.

To that, we should add autocomplete for:
* schema names
* table names that are in the active database / schema

On the event of using a table name from autocomplete, we should add this new table to the schema browser for reference. From that point the column names from that added table should become "auto-completable"

**Comment by enricoberti** [comment]
Working on it
