### ISSUE TITLE
set auto refresh

### ISSUE THREAD

**Issue by FelixJHuang** [apache/incubator-superset#7077]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results

Close the page, still can automatically refresh data
### Actual results

 auto refresh data not work

Can you tell me why? and how to set args

**Comment by davidhassan** [comment]
It would be nice if auto fresh was already set based on how it was saved.

**Comment by zhaoyongjie** [comment]
@FelixJHuang 
on this PR: https://github.com/apache/incubator-superset/pull/5741 , fix this behavior, try rebase master branch.

**Comment by FelixJHuang** [comment]
> @FelixJHuang
> on this PR: #5741 , fix this behavior, try rebase master branch.

thinks

**Comment by FelixJHuang** [comment]
> > @FelixJHuang
> > on this PR: #5741 , fix this behavior, try rebase master branch.
> 
> thinks

**Comment by FelixJHuang** [comment]
> > > @FelixJHuang
> > > on this PR: #5741 , fix this behavior, try rebase master branch.
> > 
> > 
> > thinks

this method this not worke well
