### ISSUE TITLE
Redash vs Superset

### ISSUE THREAD

**Issue by rrjanbiah** [apache/incubator-superset#7089]
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Question

Is there any comparison available with Redash--from Superset POV? (Similar to https://github.com/getredash/redash/issues/2207 )

**Comment by kingo55** [comment]
I've only tried Superset. Works as advertised and haven't had to look further, but Redash looks quite cool.

The redash issue looks a little one-sided and perhaps outdated. Have you tried both @rrjanbiah ? Care to provide some details?

Personally I am curious to fire up a Redash docker to see what its like at least.
