### ISSUE TITLE
[word cloud] rotation option causes browser to crash

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7094]
Repro:
(1) Create word cloud
(2) Go to Visual Properties and selection rotation to Square or Random
(3) Browser window freezes

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jeffcarey** [comment]
@vylc Do you mean it froze momentarily or permanently? I tried recreating on a fresh install and it took a second but it more or less worked as I expected. Can you provide more info?

**Comment by mistercrunch** [comment]
Is this a perf issue with lots of values? What's your row limit on this one?

**Comment by MarcusSorealheis** [comment]
> @vylc Do you mean it froze momentarily or permanently? I tried recreating on a fresh install and it took a second but it more or less worked as I expected. Can you provide more info?

I have experienced this crash but only temporarily @jeffcarey I am looking into the bug with the chrome developer tools profiling.
