### ISSUE TITLE
writes to database slow - tune underlying DB

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7101]
Interactions with the superset DB are very slow:
(1) Save dashboards after edits
(2) Mapping sources to tables
(3) Querying logs table for usage information (unusable now)
 
Index tables, perhaps?

**Comment by mistercrunch** [comment]
About (3) It may be a good thing to archive the query log periodically. It probably could use an index or two. I think the most predicated columns are `user_id` and time, maybe state also.

About (1), we should profile that.

(2) What do you mean by this one? The "sync columns" button in the table editor?

**Comment by vylc** [comment]
re: 2) is creating a new datasource by mapping it to the underlying DB table

**Comment by mistercrunch** [comment]
Assuming 2) is on Presto, it could have something to do with metastore and/or driver issues.
