### ISSUE TITLE
Superset query limit

### ISSUE THREAD

**Issue by Jap8nted** [apache/incubator-superset#7112]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by enricoberti** [comment]
hi @Jap8nted ! i think you forgot to fill in the description for the issue :)

**Comment by mistercrunch** [comment]
Please re-open with more details
