### ISSUE TITLE
[Dashboard] Landing on specific tabs from URL

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#7116]
I want to be able to land on specific dashboard tab, based upon the url params. For instance, give this url superset/dashboards/2?tab=3

The user should be able to land on this specific tab after entering this link in the browser.

Problems:
- What if there is multiple tabs in a dashboard? How would know which tab to set?

**Comment by bvpillai** [comment]
If you know javascript, try to run this script after necessary modification
`function selectTab(){

	//collect your URL parameter
        var objParam = new URLSearchParams(window.location.search);
        var tabParam = objParam.get('tab');
        var tabName = "";
	//tab name is the value showing on each tab. 
        if(!tabParam) return false;

        if(tabParam =="3"){
            tabName = "Overview";
        } else if(tabParam=="k"){
            tabName = "KPI";
        } else if (tabParam == "s"){
            tabName = "Sales";
        }

            $('ul.nav.nav-tabs li a').children().find("input").each(function(){

                if($(this).val()==tabName){
                    $(this).trigger("click");
                 }

            });


   
}`

**Comment by kristw** [comment]
related to #6964
