### ISSUE TITLE
SQLA Filterbox time grain field not getting populated

### ISSUE THREAD

**Issue by agrawaldevesh** [apache/incubator-superset#7124]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

Commit ebb32101c98dbbd4f1de92e9ed3cab1c6d0c2b11 as of latest master.

### Expected results

Filterbox time grain drop down should be populated and non empty

### Actual results

Filterbox timegrain is not populated with the test dataset of World's Bank Data's region filterbox included in the example. Same bug is seen in production setting when testing with Presto, Vertica or Pinot databases. 

### Steps to reproduce

* Load examples
* Go to the dashboards and to the world bank example dashboard
* Edit the region filter filterbox 
* Check "Show SQL Granularity Dropdown", and "Show SQL time column" and click "Run Query". 
* Observe that the time grain filter is not populated on the right hand side.
* Add this filterbox to a dashboard. 
* Filterbox is still not populated.

**Comment by agrawaldevesh** [comment]
Hi @mistercrunch ... I wanted to try to fix this but I am not sure how to go about it. I am wondering if you could give me some hints on how to fix this and I can work on it. Thanks

**Comment by htruongaff** [comment]
Seeing the same issue.
