### ISSUE TITLE
onClick not working on the chart items.

### ISSUE THREAD

**Issue by ankit6373** [apache/incubator-superset#7127]
Hey, I am working on making a chart, so that when we click on a particular part of that chart, it will render a new chart with data related to that part. Example, I have a chart displaying top 4 football teams with the best winning record, so when I click on any team, it will further render a new chart related to all players of that team.I am trying to use onClick event on ChartRender.jsx, further I am trying to understand SuperChart.js but no success yet. Please help me with this.

![Sj1UG](https://user-images.githubusercontent.com/18262572/55053788-4f20d380-5083-11e9-8c83-427a47994247.png)
Something like this

**Comment by rumbin** [comment]
related: #2890, #6774

**Comment by bfmcneill** [comment]
dc.js does what you want.  I am not sure how to integrate it with this project though.  [http://dc-js.github.io/dc.js/](http://dc-js.github.io/dc.js/)

According to their web page the dashboard has 23 years of daily nasdaq data that can be cross filtered like you want.

**Comment by kalimuthu123** [comment]
any one having idea for this chart
