### ISSUE TITLE
Allow reordering of table view columns

### ISSUE THREAD

**Issue by ju4nlu** [apache/incubator-superset#7129]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Commit SHA: `b3c4bd95efd5f74e822b7ed7a2db043ba7b8c6cf`

### Problem
Columns displayed in the table view should be rearrangeable once chosen. They always follow the order in which they were selected, so that if you want the last column to be the first one, you have to remove all the columns and select them again in the correct order. An image of the current column selector is shown below:
![image](https://user-images.githubusercontent.com/16457073/55005834-03b3ea00-4fdd-11e9-90e3-34d8e41b6629.png)
This issue also happens on the `GROUP BY` columns.

### Possible solution
This could be solved by using the controller used in the Filter Box visualization to select the available filters:
![image](https://user-images.githubusercontent.com/16457073/55006353-e5022300-4fdd-11e9-917f-03e09144cfda.png)
In that case, it is possible to rearrange the filters as desired without deleting and adding them again and again.

**Comment by mistercrunch** [comment]
Ideal would be for someone to contribute the feature in `react-select` https://github.com/JedWatson/react-select/issues/3223 , please add a "thumbs up" on the issue!

**Comment by suddjian** [comment]
`react-select` added support for this [last month](https://github.com/JedWatson/react-select/pull/3792), but it looks like it hasn't been baked into a release yet.

**Comment by Grace-Dmello** [comment]
The react-select library is currently at
` `"react-select":` "1.2.1",`

Are there plans to upgrade it to solve the problem?

**Comment by ktmud** [comment]
This has been implemented in Superset.

https://github.com/apache/incubator-superset/pull/9628

If someone could help testing this PR, that'd be great!

**Comment by JunlinC** [comment]
🙏@mistercrunch this issue can be closed

**Comment by willbarrett** [comment]
Closing as completed.
