### ISSUE TITLE
login superset, action log

### ISSUE THREAD

**Issue by baocaiwang** [apache/incubator-superset#7140]
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.20.4

### Actual results
This issues refer system safe, Someone maybe not login superset, but there is action log in superset, like this picture :
![image](https://user-images.githubusercontent.com/20453143/55048654-f140bb80-5083-11e9-8b2b-5cca6ba18122.png)

Our superset login by LDAP

Please someone can explain this question , thanks very much!

**Comment by baocaiwang** [comment]
there is action log, but the "User" column is None , I find this question recently, Our superset report has some secretly data

**Comment by AaronCH5** [comment]
Recently, I also have the problem of the display of Action Log. The logs on my side were before 5.31, and then there was no logs in the middle. But yesterday, 6.10 began to show several logs. I don't know what happened at the moment. Solve the confusion, thank you.
[https://graph.baidu.com/resource/112a8001959851573350401560240315.jpg](url)
