### ISSUE TITLE
Support for custom Mapbox Style in Visualizations

### ISSUE THREAD

**Issue by hokieg3n1us** [apache/incubator-superset#7146]
In some environments, Mapbox is either not accessible, or not the best available option for base layers (on top of being a subscription based service). In this case, my company hosts it's own WMS maps that we'd like to use as the basemap within Superset. 

Is it possible to support a "Custom" Map Style option, that'd allow a user to add their own style definition? For example: 

```javascript
{
  "version": 8,
  "sources": {
    "wms-basemap": {
      "type": "raster",
      "tiles": [
        "https://ows.terrestris.de/osm/service?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&width=256&height=256&styles=&layers=OSM-WMS"
      ],
      "tileSize": 256
    }
  },
  "layers": [
    {
      "id": "wms-osm",
      "type": "raster",
      "source": "wms-basemap",
      "source-layer": "wms-osm",
      "minzoom": 1,
      "maxzoom": 20
    }
  ]
}
```

**Comment by candy4290** [comment]
I have the save question, how to fix it?

**Comment by MrApe** [comment]
Would also greatly appreciate this!

**Comment by rusackas** [comment]
There is a SIP to move from MapBox to MapLibre. If you want to make things more flexible, I'd suggest chiming in there: https://github.com/apache/superset/issues/28356
