### ISSUE TITLE
Big Number With Trendline Visualization Metric  bug

### ISSUE THREAD

**Issue by chuancyzhang** [apache/incubator-superset#7151]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1
### Expected results
![image](https://user-images.githubusercontent.com/23111194/55126466-17c82a80-5148-11e9-81bc-b4504408c4da.png)

when Metric is capital, The Big Number With Trendline  can‘t show real number.But  Metric  default is capital.

### Actual results
![image](https://user-images.githubusercontent.com/23111194/55126513-39c1ad00-5148-11e9-8db8-f26ae0c7d005.png)

### Steps to reproduce
1. choose Datasource and Visualization Type
2. click Metric , and write Custom SQL 
3. Run query

**Comment by kristw** [comment]
Could you verify if this also happens in `0.29` or latest master

**Comment by chuancyzhang** [comment]
> Could you verify if this also happens in `0.29` or latest master

yes，this  not happen in 0.29.0rc7 . But 0.29.0rc7 isn't relased?
