### ISSUE TITLE
Pie chart not rendering in the latest master release, even when data is there

### ISSUE THREAD

**Issue by agrawaldevesh** [apache/incubator-superset#7152]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

Trunk version 6e79e84b025259f5741a04f69b79360404872c5c

### Expected results

Pie chart should render

### Actual results

Pie chart does not render, while the explore_json end point does return valid x/y data. 

<img width="1440" alt="nQNgk" src="https://user-images.githubusercontent.com/20564223/55136377-76ab8680-50eb-11e9-8e99-255af2336bb3.png">

### Javascript errors in browser (Chrome 73.0.3683.86, Also repro's in Safari)

I see these errors: 

`Uncaught TypeError: Cannot read property 'tickFormat' of undefined
    at Object.generate (3.9e5517691a3754ec100e.chunk.js:2)
    at e (2.425a345ff22d808395dd.chunk.js:1)
/superset/explore/?form_data=%7B%22datasource%22%3A%22145__table%22%2C%22viz_type%22%3A%22pie%22%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3A%22secondsSinceEpoch%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22Last+week%22%2C%22metric%22%3A%22count%22%2C%22adhoc_filters%22%3A%5B%5D%2C%22groupby%22%3A%5B%22fare_insight_codes%22%5D%2C%22row_limit%22%3A1000%2C%22pie_label_type%22%3A%22key%22%2C%22number_format%22%3A%22.3s%22%2C%22donut%22%3Afalse%2C%22show_legend%22%3Atrue%2C%22show_labels%22%3Atrue%2C%22labels_outside%22%3Atrue%2C%22color_scheme%22%3A%22bnbColors%22%7D:1 Unchecked runtime.lastError: The message port closed before a response was received.`

The minified JS file above looks like this (just the portion in the console stack trace):

`Tt.x2Axis && Tt.x2Axis.tickFormat && Tt.x2Axis.tickFormat(H),
                !e(["dist_bar", "box_plot"]) && Tt.xAxis && Tt.xAxis.tickFormat ? Tt.xAxis.tickFormat(H) : Tt.xAxis.tickFormat(function(t) {
                    return t.length > k ? t.substring(0, k) + "…" : t
                })`

### Steps to reproduce

* Just group by on a column and choose a pie chart visualization. 

### Other notes

I tested that the Sunburst chart works just fine. But its troublesome that Pie chart is not working.

**Comment by agrawaldevesh** [comment]
Hi @kristw ... any idea when this might be fixed. Seems like a pretty basic bug if something like Pie Chart itself is not rendering. How do you guys work around this at AirBnb ? Is there a special branch I should be on instead of trunk ?

**Comment by kristw** [comment]
This should be fixed by
https://github.com/apache-superset/superset-ui-plugins/pull/36
which is released with `@superset-ui/legacy-preset-chart-nvd3@0.10.4`.

We need to bump the version of the chart in master.

**Comment by mistercrunch** [comment]
I think this is fixed in the `lyftga` branch

**Comment by tokarskyibogdan** [comment]
I also faced with this issue, was it fixed for you @agrawaldevesh ?

**Comment by agrawaldevesh** [comment]
I haven't updated my branch yet to test out whether it works on the latest master. I am anxiously waiting for the lyftga branch to be merged in to test then whether we have a fix for this.
