### ISSUE TITLE
How to divide two columns in apache superset

### ISSUE THREAD

**Issue by sabinegthomsen** [apache/incubator-superset#7155]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
I want to make a bar chart in apache superset that is based on relative numbers. To be more specific, I want to divide SUM(mængde i ton) / Indbyggertal, but this does not work. How do I do this? 

### Actual results
It is not working

### Steps to reproduce

![Skærmbillede 2019-03-28 kl  15 19 35](https://user-images.githubusercontent.com/49032003/55165029-f3cb1000-516c-11e9-83b9-82eff2aba492.png)

**Comment by mistercrunch** [comment]
Which database engine is that? Different ones have different ways to quote things, could be `SUM("something")` `or SUM(``something``)`

**Comment by sabinegthomsen** [comment]
Thanks, it worked
