### ISSUE TITLE
[filter box] numbers get truncated

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7157]
I think we saw this issue in SQL Lab with numeric results getting truncated. Same thing is happening in the filter box (and thus doesn't work)
<img width="600" alt="Screen Shot 2019-03-28 at 10 00 13 AM" src="https://user-images.githubusercontent.com/33429480/55177723-1cd5ab80-5141-11e9-876f-c91b3de9a6c6.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by vylc** [comment]
@mistercrunch while you are in filter box code...

**Comment by mistercrunch** [comment]
This seems related to BIGINT javascript issues.

**Comment by MarcusSorealheis** [comment]
I'm not sure I have enough insight into the problem but it seems that [BigInteger.js](https://github.com/peterolson/BigInteger.js) could help. It will eventually be a part of JavaScript, but the library is available today.

**Comment by mistercrunch** [comment]
Looks like we use `bignumber.js` and `json-bigint` in some areas of the code. I think there was a recent "revert" related to this. It seems like one of these wack-a-mole bug.

**Comment by mistercrunch** [comment]
@vylc has this been addressed?
