### ISSUE TITLE
[sql lab] BigQuery preview results errors out

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7167]
The preview / sample rows for BigQuery tables throws an error due to not specifying a WHERE clause on the time column

400 GET https://www.googleapis.com/bigquery/v2/projects/fsql-production/queries/a527d8a5-bbfe-49bb-a8cb-a81f66eb1d86?maxResults=0&location=US: Cannot query over table '<table_name>' without a filter over column(s) 'occurred_at' that can be used for partition elimination

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by enricoberti** [comment]
@vylc I tried with some very simple BigQuery tables (with or without partitions) and I cannot repro it unfortunately. Would it be possible to have the table schema and maybe a subset of the data? Thanks!

![Screenshot 2019-04-01 16 27 26](https://user-images.githubusercontent.com/751894/55335368-44a77500-549b-11e9-88f5-603f91a042ad.jpg)

**Comment by bruno-nirello** [comment]
This is indeed the same error as me, when you create in bigquery any table with:
![Screenshot from 2020-09-29 19-06-31](https://user-images.githubusercontent.com/30416677/94621607-030dab00-0287-11eb-935c-17cac8846f7f.png)
it raises the error because superset does not know wich field was required
```
Cannot query over table 'my_dataset.partitioned_table' without a filter over column(s) 'date' that can be used for partition elimination (job ID: 63d9e724-c622-4d48-8894-5c671f96aac8) -----Query Job SQL Follows----- | . | . | . | 1:SELECT date AS `date` 2:FROM `my_dataset`.`partitioned_table` 3:LIMIT 100 | . | . | . |
```

**Comment by jmilagroso** [comment]
I recommend using `FILTERS` and use the partition column using `SIMPLE` or `CUSTOM SQL`

i.e
`WHERE`
then
` _PARTITIONTIME IS NOT NULL`
