### ISSUE TITLE
[0.31] Landing page shows empty results

### ISSUE THREAD

**Issue by elukey** [apache/incubator-superset#7171]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.31.0rc18

### Expected results
The landing page should list dashboards, recently viewed, etc..

### Actual results
Empty, nothing is shown.

### Steps to reproduce
I have simply upgraded from 0.26 to 0.31 (rc18) and now I don't see anything in the landing page. Similar to https://github.com/apache/incubator-superset/issues/6500

If I inspect with Chrome tools I can see some new warnings:

```
The only possible children of <Table> are <Thead>, <Tr>, or one <Tfoot>.
```

From table.js?2268:153 -> react.production.min.js?be24:19 -> ..

Not sure if I did something wrong in building static assets or if there is a fix missing from the 0.31 branch, if you could give me an advice I'd be really grateful :)

**Comment by michellethomas** [comment]
I haven't seen those errors on the welcome page in rc18. Can you provide a more detailed stacktrace?

**Comment by elukey** [comment]
Completely my bad, I discovered that we were approximating the pypi push script with a simple webpack run and that was the source of the errors. I am testing rc20 now and all is good. Thanks!
