### ISSUE TITLE
Mapbox API_KEY not recognized

### ISSUE THREAD

**Issue by clauslor** [apache/incubator-superset#7173]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
show the underlying map

### Actual results
Notifies "A valid API access token is required to use Mapbox data"

### Steps to reproduce
1. followed https://superset.incubator.apache.org/installation.html installation instructions.
2. setup PYTHONPATH
3. obtained mapbox api key
3. created superset_config.py as in https://superset.incubator.apache.org/installation.html#configuration
4. started superset in virtualenv using superset runserver -d

I have also changed the default port to 8080 in the superset_config.py which worked fine but the api key was still not recognized.
Edit: The API key works fine in other projects.

**Comment by bllli** [comment]
you could insert a `print('superset_config.py loaded')` into your superset_config.py to test it load by flask or not.

**Comment by bllli** [comment]
do you console print some log like `Loaded your LOCAL configuration at [superset/superset_config.py]`?
if not, try to set environment  `SUPERSET_CONFIG_PATH=/path/to/your/superset/superset_config.py` to tell superset where config file it is

**Comment by clauslor** [comment]
> do you console print some log like Loaded your LOCAL configuration at [superset/superset_config.py]?

Yes, it does.

**Comment by bllli** [comment]
I guess your config file isn't successfully loaded.
try to add  `print('configuration loaded')` to the bottom of your `superset_config.py` , to make sure it loaded ok

**Comment by mistercrunch** [comment]
To test / debug, you can open an interpreter and run `import superset_config`, and see if it loads properly.

For more context, here's where it's auto-loaded:
https://github.com/apache/incubator-superset/blob/master/superset/config.py#L621-L625

**Comment by clauslor** [comment]
> I guess your config file isn't successfully loaded.
> try to add `print('configuration loaded')` to the bottom of your `superset_config.py` , to make sure it loaded ok

I did this as you suggested but it didn't help.

**Comment by garima301984** [comment]
how to obtain mapbox api key
