### ISSUE TITLE
Bringing in the tabular results from SQL lab to Dashboard

### ISSUE THREAD

**Issue by avaprincythomas** [apache/incubator-superset#7178]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Expected results
Hello I would like to bring in the tabular results from SQL lab, as such, to dashboards. I don't really want to build any visualizations on top of this like bar charts or time series etc. The results of saved queries, if they are not visualizations (bar charts etc) are not available to be selected within a dashboard in the current version of superset.

**Comment by michellethomas** [comment]
can you use the "Table" visualization for this?

**Comment by avaprincythomas** [comment]
We do not have a "Table" visualization in SQL Lab.

**Comment by avaprincythomas** [comment]
The only options under Visualize in SQL Lab are:-
1. Distribution - bar Chart
2. Pie Chart
3. Time Series - Line Chart
4. Time Series - Multiple Line Charts
5. Time Series - Periodicity Plots
6. Time Series - Bar Charts
7. Time Series - Paired t-Test
8. Time Series - Nightingale Rose Chart and 
9. Partition Diagram
