### ISSUE TITLE
Question about multi chart interaction 

### ISSUE THREAD

**Issue by qqq6301** [apache/incubator-superset#7182]
In tableau, if one click on a bar in a bar chart, than another chart in the dashboard could be affected (filtered). 
In superset, could simlimar be achieved (use chart itself as filter) 

Thanks

**Comment by zhaoyongjie** [comment]
you can refer to discussion:  https://github.com/apache/incubator-superset/issues/375
Superset can use * filterbox * do some functions for cross filtering

**Comment by kalimuthu123** [comment]
@zhaoyongjie  i need some brief explanation for this i want to include it with bar and pie chart
