### ISSUE TITLE
[SQL Lab] Required fields absent error on partitioned tables

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7184]
Unable to run any query via SQL editor for date partitioned tables (even with date specified in where clause).
Preview table seems to work just fine
<img width="1214" alt="Screen Shot 2019-03-31 at 4 57 00 PM" src="https://user-images.githubusercontent.com/33429480/55297000-085e1100-53d6-11e9-8579-230cb9c7c950.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by xtinec** [comment]
@enricoberti any chance you could help with this bug? 🙏

**Comment by enricoberti** [comment]
@xtinec yes, on it!

**Comment by enricoberti** [comment]
@xtinec sync/async? what kind of db? i just tried on a hive partitioned table in both modes and it works as expected

**Comment by mistercrunch** [comment]
We cannot reproduce this :(
