### ISSUE TITLE
explore charts

### ISSUE THREAD

**Issue by FelixJHuang** [apache/incubator-superset#7185]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
expore charts \
stop button is not woker

### Actual results
stop

**Comment by zhaoyongjie** [comment]
Need more information for you question

**Comment by FelixJHuang** [comment]
> Need more information for you question

Explore the chart function, running tasks, there is no way to click stop to stop
