### ISSUE TITLE
How do I join two tables in Superset now? I need to combine the result in order to visualize the data.

### ISSUE THREAD

**Issue by D-Mahajan** [apache/incubator-superset#7189]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by D-Mahajan** [comment]
I am new to Superset and really struggling with SQLAlchemyURl and joining of individual separate tables. Please guide.

**Comment by mistercrunch** [comment]
Materialize to a single table or create a view first.
