### ISSUE TITLE
[deck.gl] Map style change doesn't work

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7196]
Expected behavior is that map style should change instantaneously, but doesn't work at all

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Works for me on `master`... What version is this?
