### ISSUE TITLE
Do we still need syncBackend.json?

### ISSUE THREAD

**Issue by kristw** [apache/incubator-superset#7201]
### Superset version
master

### Expected results
There is a file `syncBackend.json` and script for generating it.
However, it does not seem to be used anywhere.

If there is any need for it, please comment here. Otherwise I propose we delete `syncBackend.json` and the accompanying script within a week.

**Comment by mistercrunch** [comment]
95% sure that the answer is no, and I also think we won't need it in the future. Global environment configurations live in `superset_config.py`, and we have a mean to share a subset to the frontend that works well. 

I can give a shot at killing it.

**Comment by mistercrunch** [comment]
Reading through the code, we only need the logic that is in there to support migrations from 2+ years ago (feb 2017), and provided that they would first upgrade to a bridge version (anywhere from pre 2017 to something between then and our next version) they'd be ok.

Also needed to support full bookmarks (the long ones, not shortened) from 2+ years ago versions.

I vote for pulling the plug on this one.
