### ISSUE TITLE
Upload CSV for existing table for options [replace, append]

### ISSUE THREAD

**Issue by suraj-raghupathi** [apache/incubator-superset#7202]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Cloned latest version

### Expected results
When I try to upload csv for the existing table using append option it try and append the data and when I use replace option it should completely remove the table and recreate with csv data

### Actual results
Option Append - 'Table name training already exists. Please pick another'
Option Replace - 'Table name training already exists. Please pick another'

### Error
When I use replace option the data is getting appended to the table but Integrity error is causing to get this message "Table name training already exists. Please pick another"
trying to insert metadata information again but were it already exits is causing the integrity     ####error.

### Steps to reproduce
1) upload a csv as a table
2) upload the same csv and same table name with replace or append option.

![Screenshot from 2019-04-01 21-29-04](https://user-images.githubusercontent.com/10807415/55382575-a3282e00-5543-11e9-9fe2-9c336183e64c.png)

**Comment by mamounalaoui** [comment]
bump for bot

**Comment by yatin-kapur** [comment]
This issue seems to have been resolved in this commit: https://github.com/apache/incubator-superset/commit/49ea232c3a692ba38769f0e0924e287036323887#diff-ba855df7419cb615784de08e136ed1ed
