### ISSUE TITLE
Creating a bar chart using only specific rows 

### ISSUE THREAD

**Issue by sabinegthomsen** [apache/incubator-superset#7203]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
I would like to make a bar chart in Apache Superset using only specific rows of my data. 

I want the chart to display the summed “mængde i ton” for all H02, H05 and H08-codes divided by H11-codes. I have attached an example of my data set. 

![Skærmbillede 2019-04-02 kl  11 05 31](https://user-images.githubusercontent.com/49032003/55390318-432b8a80-5537-11e9-9a92-e07e2cad2036.png)

I have tried: SUM("Mængde i ton" WHERE "H-kode" = "H02", "H05", “H08”) / SUM("Mængde i ton" WHERE "H-kode" = "H11”)

### Expected results

I want a bar chart that shows this number for each "kommune". 

### Actual results
![Skærmbillede 2019-04-02 kl  11 01 38](https://user-images.githubusercontent.com/49032003/55390152-e039f380-5536-11e9-865a-a9d75942a675.png)

### Steps to reproduce
How do I do this?

**Comment by villebro** [comment]
You might want to check a tutorial on basic SQL syntax. I think what you want to do can be achieved with the following expression:
```sql
SUM(CASE WHEN "H-kode" IN ('H02', 'H05', 'H08') THEN "Mængde i ton" ELSE NULL END) / SUM(CASE WHEN "H-kode" = 'H11' then "Mængde i ton" ELSE NULL END)
```
while at the same time grouping by `Kommune`. This should give you just three rows of data. Oh, and that might give an error if H11 is missing or zero, so you might want to check for that, too. Hope this helps, Ville.

**Comment by sabinegthomsen** [comment]
Yes, I will. Thanks a lot, it worked. 
/ Sabine
