### ISSUE TITLE
how to improvee the rendering speed

### ISSUE THREAD

**Issue by changchichung** [apache/incubator-superset#7204]
### Superset version
0.28.1

### Expected results
quick / page table

### Actual results
long time rendering , all rows in one page.

### Steps to reproduce

I wrote a query which return about 93k rows . in psql console , that query only takes few seconds to return the result.
but in superset , with different browsers , the rendering take long time from 2:24(chrome) to 3:38(firefox), and take high single core CPU loading

here is the screen recording 
firefox: https://www.youtube.com/watch?v=s_SH8U67_Dg
Braver(chrome): https://www.youtube.com/watch?v=X1WUxNrF_YA

OS: Ubuntu 18.04.2 LTS
CPU: i7-2600@3.4G
RAM: 8G
H.D.D: Pleextor M6P 128G SSD

is there anyway to improve the rendering speed ? 
maybe take 1K rows or 100 rows per page ?

I search the issues and there`s a topic talk about "limit button" in superset , but I dont see that button in my page , how to enable the limit option ?

**Comment by mistercrunch** [comment]
A few things here, first is that the term `rendering` is misleading. Assuming your database is in async mode, here's some of what's happening. You can track some of this using `statsd` logging if it's configured
* query executes:`sqllab.query.time_executing_query`
* fetching data: `sqllab.query.time_fetching_results`
* state is changed to `rendering`
* data is pushed to results backend: `sqllab.query.results_backend_write`
* client is polling
* data is available, request is sent to get the full result set
* fetching over network
* actual rendering on the browser starts

If you can just limit your query, all of this will be much faster.

The reason why the postgres client is fast, is that it doesn't fetch all the data upfront, at step 2 (fetching data), it fetches a page and shows it. The cursor is kept alive and can be used to retrieve more rows as you scroll.

We could improve all this to be more seamless/faster, but operating in async mode makes all of this more complicated. I think we'll improve this over time. One approach would be to deliver the data in two phases, with a new state `partially-delivered` or something like that.

**Comment by icoert** [comment]
Look for other sql-engine. For instance, there are some sql-engines especially for data vizualization, such as [omnisciDB](https://www.omnisci.com/). Give it a try.
