### ISSUE TITLE
[explore view] time comparison

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7209]
Syntax for time comparison is broken in explore view. Note that the query generated to compare datetime is now just a string, thus results in type comparison issue

SELECT COUNT(*) AS "count"
FROM "superset"."logs"
WHERE from_unixtime(dttm) >= '2019-03-26 00:00:00'
  AND from_unixtime(dttm) <= '2019-04-02 00:00:00'
ORDER BY "count" DESC
LIMIT 10000
<img width="1049" alt="Screen Shot 2019-04-02 at 4 44 13 PM" src="https://user-images.githubusercontent.com/33429480/55443249-e942b900-5566-11e9-8cb4-d82688b02787.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
How is `dttm` configured, I have no issue querying that table out of the box

<img width="838" alt="Screen Shot 2019-04-02 at 9 21 36 PM" src="https://user-images.githubusercontent.com/487433/55452656-5e28e980-558d-11e9-81ca-541e39fb6f38.png">

<img width="787" alt="Screen Shot 2019-04-02 at 9 22 33 PM" src="https://user-images.githubusercontent.com/487433/55452674-7567d700-558d-11e9-9451-89ed2a2a40f3.png">

**Comment by vylc** [comment]
I failed to mention--this is on Presto - we moved the logs off since queries never returned.
dttm is brought over as a bigint, and i have a calculated column converting it to a timestamp, but the time filter always errors out as it doesn't know what type to calculate

**Comment by mistercrunch** [comment]
Another way would be to try this (from the helper text in the legacy table editor):
<img width="1045" alt="Screen Shot 2019-04-02 at 9 47 31 PM" src="https://user-images.githubusercontent.com/487433/55453478-f1175300-5590-11e9-9b1c-c3baee0f07c3.png">

**Comment by mistercrunch** [comment]
As a side note, and maybe not a top priority, but would you mind reviewing the helper text in those legacy screens so that we can bring an improved version to the new table editor?

**Comment by mistercrunch** [comment]
Oh actually it's there in the new table editor, may still need review/improvement though.
<img width="405" alt="Screen Shot 2019-04-02 at 9 51 39 PM" src="https://user-images.githubusercontent.com/487433/55453660-9a5e4900-5591-11e9-8028-00fc16d53987.png">

**Comment by mistercrunch** [comment]
One general constraint for optimization that we have around this, is that we typically want to put the function/expression on the constant side of the operation, so that we can leverage partition pruning or indexes on fields.

Meaning `dttm >= 294728378` is better than `epoch_to_datetime(dttm) >= DATE('1979-07-19')`.

Database optimizers cannot leverage indexes/partitions on column altered by functions.

**Comment by mistercrunch** [comment]
One more thing, I'm surprised that in your example above, Superset isn't using `STR_TO_DATE` around the time constant. Is the column's `is temporal` checkbox checked?

**Comment by vylc** [comment]
Yeah, it's checked. i was also surprised it wasn't doing a date conversion for the timestamp, which is why i opened the issue

**Comment by mistercrunch** [comment]
What is the type you selected on the column? Hint: it should be `DATETIME`, I'm guessing you have string...
