### ISSUE TITLE
Migrating legacy filters to ad-hoc filters (Slices filter disappear after metadata DB upgrade)

### ISSUE THREAD

**Issue by heisenberg1205** [apache/incubator-superset#7214]
Make sure these boxes are checked before submitting your issue - thank you!

- [Yes] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ Yes] I have reproduced the issue with at least the latest released version of superset.
- [Yes ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.27

### Expected results
While upgraded the Superset (0.15 to 0.27) if metadata DB is same then all the filters for slices in the new Superset(Upgraded one) should retain as they were in old Superset.

Is there a way to retain the filters for all slices/dashboards while upgrading the metadata DB ?
 
### Actual results
All the filters stored in Metadata DB for slices in old version got disappear after we upgraded Superset and metadata DB from 0.15 to 0.27. 

How filter model was there in Superset 0.15 -:
    "flt_col_0": "",
    "flt_col_1": "id", 
    "flt_eq_0": "", 
    "flt_eq_1": "1", 
    "flt_op_0": "in", 
    "flt_op_1": "in",
How filters model is there in Superset 0.27 -:
"adhoc_filters": [{"comparator": "Model TV", "expressionType": "SIMPLE", "clause": "WHERE", "fromFormData": true, "sqlExpression": null, "operator": "==", "filterOptionName": "filter_c2ih6juqp56_md3q9zf1ij", "subject": "id"}]

**Comment by heisenberg1205** [comment]
Hello, 
Is there any solution exists for it ? We've lost all our filters after upgrade from 0.15 to 0.27.

**Comment by mistercrunch** [comment]
We all migrated successfully. I'm not sure what's happening on your side. Can you try upgrade beyond `0.27`? I'd recommend the latest in branch `release--0.31` or `lyftga`
