### ISSUE TITLE
FYI: Using pysqlite3 as datasource

### ISSUE THREAD

**Issue by hoehrmann** [apache/incubator-superset#7238]
I wanted to try out Superset with an sqlite3 database as data source, but I need a newer version of sqlite3 than the system library that Python uses by default. Using the `pysqlite3` module I already had statically linked to a newer version, but there was no good way to use that through SQLAlchemy in Superset. So I made https://pypi.org/project/sqlalchemy-pysqlite3/ / https://github.com/hoehrmann/sqlalchemy-pysqlite3 which makes pysqlite3 available via a connection string like `sqlite+pysqlite3://`.

**Comment by mistercrunch** [comment]
Thanks for creating this solution and letting us know. The best way to got about this is to add an entry here in the docs:
https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#database-dependencies

Just add a row for sqlite3!
