### ISSUE TITLE
Group Dashboards  folders or tags

### ISSUE THREAD

**Issue by thuylevn** [apache/incubator-superset#7239]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
 "0.26.3"
  
### Expected results
Can "Group Dashboards  folders or tags"

### Actual results
Cannot group Dashboards by folders or tags

### Steps to reproduce
_We have too much dashboards, we want to group dashboards by purposes  by create folders or tags. Then it will help us easy to manage_ 
**_Can you suggest the ways to do it?_**

**Comment by mistercrunch** [comment]
There's an open PR somewhere around tagging
