### ISSUE TITLE
Annotation Layer Tooltip transparency Issue

### ISSUE THREAD

**Issue by lucasapaixao** [apache/incubator-superset#7241]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28

### Expected results
Annotation Layer chart overlap

### Actual results
Annotation layer tooltip dont modified the background.

### Steps to reproduce
Add a annotation in any chart, on visualization the layer will not overlap the chart.

![annotation layer error](https://user-images.githubusercontent.com/48967533/55745220-1bdc2e00-5a0d-11e9-82c9-b6f03d4f95a6.png)
![annotation layer conf](https://user-images.githubusercontent.com/48967533/55745224-1ed71e80-5a0d-11e9-95fa-2939d49c9226.png)

**Comment by brachipa** [comment]
Still happened, version 0.33.0rc1

**Comment by etr2460** [comment]
This is still a legit issue and should be resolved!

**Comment by graceguo-supercat** [comment]
this issue is fixed by apache-superset/superset-ui-plugins#372 and #9203
