### ISSUE TITLE
fabmanager create-admin --app superset: Was unable to import superset Error: No module named 'retry'

### ISSUE THREAD

**Issue by rjurney** [apache/incubator-superset#7243]
Make sure these boxes are checked before submitting your issue - thank you!

Note: I can not find the superset logs nor where they are found in a web search. - [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [* ] I have reproduced the issue with at least the latest released version of superset.
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.28.1

### Expected results

retry should be installed as part of pip install

### Actual results

retry fails to install and must be installed manually

### Steps to reproduce

pip install superset

### Platform

Linux 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

**Comment by mistercrunch** [comment]
`0.28.1` has numerous issues with version ranges that had functioning release at the time it came out, but slipped in a bad place. Now we recommend installing from source and running `pip install -r requirements.txt` to get the pinned deps that we test against.
