### ISSUE TITLE
Big Number showing NaNM. But explore csv showing this result:  AVG_recency_ 12.177325053014

### ISSUE THREAD

**Issue by Towhid1** [apache/incubator-superset#7252]
### Superset version
 0.29.0rc7 

### Expected results
12.177325053014

### Actual results

![Screenshot_2019-04-09 Bank Customer Segmentation](https://user-images.githubusercontent.com/8430816/55780541-01b45580-5aca-11e9-922f-befd13ea733d.png)

### Steps to reproduce

* Connected with BigQuery 
* table added
* Big Number generated 
* Showing NanM
* I checked Json and CSV . both of them showing correct result.

Screenshot for better view: 
![Screenshot_2019-04-09 Bank Customer Segmentation(1)](https://user-images.githubusercontent.com/8430816/55780974-f7468b80-5aca-11e9-94e7-0ba1ca11a573.png)

JSON: 
![Screenshot_2019-04-09 Screenshot](https://user-images.githubusercontent.com/8430816/55780923-e39b2500-5aca-11e9-9d87-0370c909da6c.png)

CSV:
![Screenshot from 2019-04-09 13-24-35](https://user-images.githubusercontent.com/8430816/55780960-f150aa80-5aca-11e9-9e7f-b0ee8f77c235.png)

**Comment by wushenchao** [comment]
I also encountered the same problem when using impala. The reason for the problem is that the case of the field causes the data to not be displayed.

**Comment by Towhid1** [comment]
> The reason for the problem is that the case of the field causes the data to not be displayed.
Is there any solution?

**Comment by josephtyler** [comment]
I'm have the same issue here.

**Comment by josephtyler** [comment]
@Towhid1 @wushenchao any luck?

**Comment by Towhid1** [comment]
@josephtyler nope, man.

**Comment by wushenchao** [comment]
@Towhid1 @josephtyler If you haven't found a better way, you can use this solution.

Modify the viz.py

![屏幕快照 2019-04-28 上午9 26 17](https://user-images.githubusercontent.com/8774296/56856911-e08fa800-6997-11e9-86bd-faf9438ab247.png)
![屏幕快照 2019-04-28 上午9 25 55](https://user-images.githubusercontent.com/8774296/56856912-e2f20200-6997-11e9-9cde-08f34c83d1cc.png)

**Comment by imysm** [comment]
I'm have the same issue here.

**Comment by imysm** [comment]
![image](https://user-images.githubusercontent.com/48442505/56879388-15305c00-6a8b-11e9-804d-d792d0063df2.png)
