### ISSUE TITLE
Drilldown feature

### ISSUE THREAD

**Issue by bvpillai** [apache/incubator-superset#7269]
In the feature list, it is saying that it has drilldown capability. But when we explore Superset we couldn't find this feature. Any explanation appreciated.

> Easy, code-free, user flows to drill down and slice and dice the data underlying exposed dashboards. The dashboards and charts acts as a starting point for deeper analysis.

Make sure these boxes are checked before submitting your issue - thank you!

- [ *] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ *] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc8

### Expected results
Drill down feature available

### Actual results
Can't find this feature

### Steps to reproduce
Go to this URL and read the description/features
https://superset.incubator.apache.org/
https://pypi.org/project/superset/

**Comment by kalimuthu123** [comment]
any idea about this

**Comment by bvpillai** [comment]
We have achieved this feature by injecting JavaScript through front end. Not got any Superset specific solution.

**Comment by kalimuthu123** [comment]
can u explain me briefly about it

**Comment by biaogewow** [comment]
Can you share your solution? @bvpillai

**Comment by Neel-rishabhsoft** [comment]
@bvpillai please share your solution.

**Comment by binupillai305** [comment]
We have created a blank dashboard and placed a tabular element with the help of javascript to load the drill-down data. we used Ag-grid for this. 

In the actual dashboard which is showing all the charts, we have enabled the click event. Then when a user clicked on a chart, through custom Javascript we identified the chart title, id and month, etc. Then pass this to above mentioned blank dashboard's URL as a parameter and open it. In the blank dashboard, with the help of ajax we populate the drill-down data.

If you need more details, please let me know.

**Comment by Neel-rishabhsoft** [comment]
Okay thanks a ton for your insight on this. Can you suggest any tutorial or something to go through to achieve the same. Because I am fairly new to javascript and I can't seem to get javascript working on top of superset. Where exactly did you add the javascript file in the superset?

**Comment by binupillai305** [comment]
There is no specific tutorial for it. But if you have some javascript skills, you can do it.
Regarding JS file, put the file in the /static/assets/ folder.
Then include this JS file URL in the basic.html file residing in the template folder. Now it can be accessed through all the superset pages.
