### ISSUE TITLE
Filter options of NULL are displayed as 0 in slices

### ISSUE THREAD

**Issue by danield9tqh** [apache/incubator-superset#727]
When creating filters for columns with null objects, the null option in the filter is displayed as '0'. This is especially misleading for number columns because if there are both 0 values and NULL values, two categories will show up both labeled '0'. It would be better if the displayed value was something more informative like 'NULL' or 'NONE'. I've only tested this behavior with a Postgres database.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
