### ISSUE TITLE
How to create a scatter plot ?

### ISSUE THREAD

**Issue by pauliuxasz** [apache/incubator-superset#7274]
I've tried to search for an answer but could not find it anywhere. 

Just wondering whats the procedure to create a basic scatter plot and maybe adding some lines (something similar to unity plot) ? 

I've noticed there is a deck.gl scatter chart option but it does require to provide a map for it ? or am I wrong ? 

Apologies if this has been answered before but would really appreciate any help on this.

Thanks!

**Comment by john-curry871** [comment]
I second the emotion.  Would be great to see basic scatter plot in there or some clear workaround using existing charts.

**Comment by sazary** [comment]
I think it's very good (and kinda necessary IMHO) to add an explicit scatter plot type too.  
BTW, you can use the bubble chart with fixed bubble size (e.g., 1) as a workaround @john-curry871 @pauliuxasz

**Comment by pundirg** [comment]
+1

**Comment by benrii22** [comment]
Bump

**Comment by altosaar** [comment]
I agree. This is a standard feature in matplotlib seaborn etc.

**Comment by arojas314** [comment]
Any updates on this feature?

**Comment by mtsadler** [comment]
@arojas Steps that worked for me:
1. Create a graph of type `bubble chart` 
2. Set `bubble size` to a static value
3. Set `max bubble size` to the size you want the "bubbles"

Now all the points will be the same size (pics attached)

<img width="649" alt="Screen Shot 2022-11-29 at 4 45 49 AM" src="https://user-images.githubusercontent.com/17607434/204509922-57609b30-3be8-42cd-9bd3-7dfb6572d7bc.png">
<img width="324" alt="Screen Shot 2022-11-29 at 4 46 05 AM" src="https://user-images.githubusercontent.com/17607434/204509927-20b9f52f-3ffc-4aa8-93df-c5d0d475f3d9.png">
<img width="650" alt="Screen Shot 2022-11-29 at 4 46 13 AM" src="https://user-images.githubusercontent.com/17607434/204509930-915d6dff-90d7-40cd-b0bf-bc9e520cb29a.png">
<img width="645" alt="Screen Shot 2022-11-29 at 4 46 21 AM" src="https://user-images.githubusercontent.com/17607434/204509936-ffeaffcf-d1c7-4d23-b40f-d560456106a4.png">

**Comment by newpoo** [comment]
@mtsadler Thanks for sharing your solution. Any ideas to fix the issues that @aaskary mentioned about aggregated x&y dimentions?

**Comment by reuben** [comment]
According to https://github.com/apache/superset/issues/5570 Superset made some unfortunate architectural decisions early on which make aggregations required in the charting and really hard to change.
