### ISSUE TITLE
Operator Type icon in DAG Graph

### ISSUE THREAD

**Issue by brylie** [apache/incubator-superset#7275]
When viewing the DAG Graph View, it would be nice to see small icons on each graph node indicating the operator type for the node.

![Screenshot from 2019-04-10 14-25-32](https://user-images.githubusercontent.com/17307/55874983-8e2f4880-5b9c-11e9-88d1-20e704d79774.png)

The color coding is also useful, but a visual icon might provide a bit more meaning.

**Comment by mistercrunch** [comment]
Is this for Superset?

**Comment by brylie** [comment]
Ah lol. Sorry. I am using both Superset and Airflow at work and got myself confused. Apologies.
