### ISSUE TITLE
504 (Gateway Time-out) and Unexpected error with slices/SQLLAB queries.

### ISSUE THREAD

**Issue by heisenberg1205** [apache/incubator-superset#7277]
### Expected results
Heavy queries are not returning any results because -:
1. SQLLAB queries are running for long. They're throwing the errors 504 (Gateway Time-out) at 120 secs. 
2. Slices are throwing unexpected error after running for 120 secs. 
what you expected to happen.
All the SQLLAB queries and slices should return the results.
### Actual results
Throwing errors as explained above. 

I've done the following changes -:
1. running the gunicorn server with 300 secs by default it was 120 secs.
2. Changed the following parameters -:
2.1 SQLLAB_TIMEOUT to 300 secs.
2.2 SQLLAB_ASYNC_TIME_LIMIT_SEC to 60 * 5
2.3 SUPERSET_WEBSERVER_TIMEOUT to 300 secs.

Still getting the same error. Any help will be appreciated. All our Superset users got blocked because of this.
what actually happens.

### Environment

(please complete the following information):

- superset version: [v0.27]
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by BigRantLing** [comment]
Same issue

**Comment by sbbagal13** [comment]
Any solution on this ?

**Comment by praveenhalian** [comment]
i alos fasing same issu e
@
