### ISSUE TITLE
Superset logs - what do the various actions refer to

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7280]
Is there any documentation on what the actions in the logs table represent?
For example, what is the difference between 'explore' vs. 'explore_json'

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: [e.g. `v0.29`, `master`, `commit`]
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by alkragh** [comment]
Hi,
Sorry, but where can I find the explanation for the different action as asked in the question?
Br
Anders

**Comment by jaroet** [comment]
I know it is closed, but same question here.

**Comment by srozov** [comment]
???

**Comment by rusackas** [comment]
@dosu
