### ISSUE TITLE
Pie chart cannot be displayed

### ISSUE THREAD

**Issue by dingsheng999888** [apache/incubator-superset#7282]
### Expected results

Pie chart 

### Actual results

nothing

#### Screenshots

<img width="1915" alt="屏幕快照 2019-04-11 上午3 05 22" src="https://user-images.githubusercontent.com/29251725/55906422-cf5c4280-5c06-11e9-82a6-4881f2724a2f.png">

#### How to reproduce the bug

choose Visualization Type with pie chart
the run query 
see error

### Environment

- superset version: [ `v0.32.0`, `master`, `commit`]
- python version: `Python 3.6.8 :: Anaconda, Inc.`
- node.js version: `v11.7.0`
- npm version: `6.5.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lpe234** [comment]
I am sure this is caused by the front-end code.

**Comment by dingsheng999888** [comment]
I have solved this problem by changing NVD3Vis.js with this method 
(https://github.com/apache-superset/superset-ui-plugins/pull/36/files/050fa3b83a4951942c281d1a37a8661b713d23cf)
