### ISSUE TITLE
Country Map: Query executes but unable to see any map. Country Name: India

### ISSUE THREAD

**Issue by D-Mahajan** [apache/incubator-superset#7285]
I am trying to use the country map for India. I see India in the drop down menu. My query runs without any error. But for the visualization, I am unable to see any map.
Also my data has a column named 'ISO' with the codes starting with 'IN-'.
And I am working on Windows 10(venv).
### Expected results
I expect to see India's map along with the states. 

### Actual results
 Its a bank screen with no map/boundaries.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by wangxianbin1987** [comment]
we have same issue, seem like it's a frontend bug, maybe js

**Comment by TheLastSultan** [comment]
We've encountered this problem Using superset at American Express. The problem is that the ISO-Region codes are incorrect (labeled as "IN" instead of "IN-{state_name}"). I will open a PR against master with the fix.

**Comment by Jclevinson** [comment]
Hello, encountering the same issue with Malawi: I can select the country from the drop-down and we have the ISO region codes formatted 'MW-XX', which appears to be correct. Any idea what the issue might be?
