### ISSUE TITLE
Tree-View In Superset: Is this possible? If yes, please guide.

### ISSUE THREAD

**Issue by D-Mahajan** [apache/incubator-superset#7286]
I have a requirement where we want a visualization showing TREE-VIEW(Like Hierarchy). If we click on a tab, it should branch out into sub-components, looking like a tree.

**Comment by bipinkc19** [comment]
It would be useful to me too.

**Comment by dev-bin** [comment]
#metoo

**Comment by mfyuce** [comment]
count me in

**Comment by caiobelfort** [comment]
I think now it's time to some contributing from people here. Maybe I will pick that requirement and try to implement a viz plugin as a learning project.

**Comment by junlincc** [comment]
@caiobelfort we would love your contribution! if you are on slack, please reach out to me

> I think now it's time to some contributing from people here. Maybe I will pick that requirement and try to implement a viz plugin as a learning project.

@caiobelfort we would love your contribution! if you are on slack, please reach out to me

**Comment by caiobelfort** [comment]
Well, don't expected this to be fast. I will use as opportunity to reforge my javascript skills.
