### ISSUE TITLE
Multiple views under single tab

### ISSUE THREAD

**Issue by sukhpreetssekhon** [apache/incubator-superset#7295]
I have to create multiple pages under one section represented by a single tab on Superset. However, I cannot add pages under a tab and cannot have a hover over menu to guide the user to these pages. 

The screenshot below indicates the single view tabs available in Superset
<img width="295" alt="Screenshot 2019-04-13 at 12 45 32 PM" src="https://user-images.githubusercontent.com/10406319/56076108-59b0cc00-5dea-11e9-9566-fb542be8352f.png">

However, I am looking at multiple pages under each tab with a hover over menu as indicated in the screenshot below
<img width="498" alt="Screenshot 2019-04-13 at 12 50 13 PM" src="https://user-images.githubusercontent.com/10406319/56076136-c3c97100-5dea-11e9-8c2a-f72c0a790c56.png">

**Comment by mistercrunch** [comment]
It seems like what you are interested into are dropdown menus, not tabs. They're different ui elements. They could be implemented as another dashboard primitive, but it seems like tabs serve most use cases.
