### ISSUE TITLE
How to add watermark for Superset?

### ISSUE THREAD

**Issue by AaronCH5** [apache/incubator-superset#7299]
Recently, the unit began to use Superset, but the leaders felt that these charts did not have their own watermark and needed secondary development. Having seen enough echarts before, they could easily integrate the watermark, but found that Superset was very troublesome.

I wonder if Superset has some simple way to configure it in a file?
I found that the Superset front end USES nvd3 for visualization. I tried to add <text><react> directly in < SVG >, but the effect was very bad and terrible.

For Echarts, you only need to obtain CTX and use ctx.fillText(waterMarkText, 0, 0) when the front-end model is built.Can, in fact, or backgroundColor processing, then Superset can also be such a simple operation? For help

**Comment by AaronCH5** [comment]
I have dealt with it well and need to add extra code. At present, my way is to add <defs>, <text>(control transparency) and <rect> tag in < SVG > for implementation. I don't know whether there is a more appropriate and official way to deal with it. Always feel their own way of dealing with low.
eg:
For css： 
     <svg>
	<defs>
			<pattern id="polka-dots" x="-20" y="-20" width="120" height="120" patternUnits="userSpaceOnUse">          
				<text dy="1em" transform="rotate(-40 120,20)" style="filter:alpha(opacity:20); opacity:0.2; font-size: 20px;font-family:20px Microsoft Yahei;">我是水印文字哦</text>
			</pattern>
	</defs>
	<rect x="0" y="0" width="100%" height="100%" fill="url(#polka-dots)"></rect>
	...
	<g>...
	</g>
</svg>

For js： 
const defs = svg.append('defs')
     .append('pattern')
     .attr('id', 'polka-dots')
     .attr('x', -20)
     .attr('y', -20)
     .attr('width', 120)
     .attr('height', 120)
     .attr('patternUnits', 'userSpaceOnUse');

  defs.append('text')
      .attr('dy', '1em')
      .attr('transform', 'rotate(-40 120,20)')
      .style('filter', 'alpha(opacity:20)')
      .style('opacity', 0.09)
      .style('font-size', '20px')
      .style('font-family', '20px Microsoft Yahei')
      .text('我是水印文字哦')

  svg.append('rect')
     .attr('x', '0')
     .attr('y', '0')
     .attr('width', '100%')
     .attr('height', '100%')
     .style('fill', 'url(#polka-dots)');

PS: At present, the code is not functional processing, all fixed values.

**Comment by Yuanmu93** [comment]
Which file is added to this css and js?

**Comment by AaronCH5** [comment]
> Which file is added to this css and js?

Css is an intuitive display of the interface, you do not need to add it in the file, you really need to add js, add it in NVD3xxx.js, Superset actually contains two built-in charts (nvd3 and sibling folders)

**Comment by Yuanmu93** [comment]
get it,thanks a lot.
