### ISSUE TITLE
Unable to delete tabs

### ISSUE THREAD

**Issue by ishawakankar** [apache/incubator-superset#7300]
### Expected results

Tab to be deleted on clicking the delete button.

### Actual results

The page goes blank without saving changes.

#### How to reproduce the bug

1. Go to 'Dashboards/your_dashboard'
2. Click on 'Edit dashboard and try removing a tab'
3. See error

### Environment

(please complete the following information):

- superset version: `v0.29`
- python version: `3.7.2`
- node.js version: `11.10.0`
- npm version: `6.7.0`

### Additional context

I saw the previous issue which was closed and I am yet facing the same problem.
<img width="1439" alt="Screenshot 2019-04-15 at 3 42 34 PM" src="https://user-images.githubusercontent.com/40451216/56124815-1e063580-5f95-11e9-9c6c-0fc772fd7013.png">

**Comment by graceguo-supercat** [comment]
Can you try newer Superset version? I have fixed a similar issue and included in 0.29rc5
