### ISSUE TITLE
Embed dashboards with security header

### ISSUE THREAD

**Issue by mmutiso** [apache/incubator-superset#7307]
I would like to embed a dashboard by 'iframing'. There are two current approaches:-

1. Make the dashboard accessible by anyone though the public role.
2. Have the user login to superset first but this is not the best UX.

I would like to have some sort of header passed from the embedding application which superset can use to authenticate the request. Any ideas?

**Comment by zhaoyongjie** [comment]
This seems to require Superset to support a wider variety of authentication methods. For example, BasicAuth.

**Comment by mmutiso** [comment]
One of the ways that this could probably work would be implementing single sing on functionality such that superset and the embedding web functionality share the same login provider. 

Other thoughts?

**Comment by zhaoyongjie** [comment]
You can try by implementing the security_manager.lm.load_user method
