### ISSUE TITLE
Add loops to sankey viz type

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#7327]
Many flows have loops (situation where event A->event B->event C->event B, etc. When this occurs in the data, the sankey viz type throws an error and doesn't render correctly.
This happens in data often. The sankey should show directional flow back to the initiating event

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by elukey** [comment]
@mistercrunch hi :) any chance that this task could be re-opened? :)

**Comment by elukey** [comment]
As far as I got, Superset uses d3-sankey (https://www.npmjs.com/package/d3-sankey) that supports only acyclic graphs. At the same time, I also found https://www.npmjs.com/package/@superset-ui/legacy-plugin-chart-sankey-loop that explicitly mentions loop for sankey.

**Comment by daniel10012** [comment]
@rusackas
