### ISSUE TITLE
Cannot use Window functions with new install of Superset and a CSV uploaded table

### ISSUE THREAD

**Issue by msutyak** [apache/incubator-superset#7334]
I have successfully set up superset and have uploaded a table from a csv file.  I have been running some basic queries in sqllab on the table, but when I try to use window functions, I am getting the error: 

near "(": syntax error

ROW_NUMBER(), RANK(), SUM() OVER and others are not working and receive the same error.  I'm sure I'm missing something in terms of being able to use these common functions.  How do I get this to work?

**Comment by mistercrunch** [comment]
Is this in SQL Lab?

**Comment by msutyak** [comment]
Yes.

**Comment by mistercrunch** [comment]
Isn't this just a syntax error on your query then? Which database backend is it? Does it support window functions?

**Comment by msutyak** [comment]
The syntax is correct (as it worked fine in Redshift).   As far as I can see, Superset uses SQL Lite out of the box.  I see that sqllite supports window functions, so I'm confused as to why they're not working within Superset SQL Lab.
