### ISSUE TITLE
can i change the big number in Big Number with Trendline ,like in Big Number it's refers to the SUM

### ISSUE THREAD

**Issue by MakremHammali** [apache/incubator-superset#7337]
I need to change the value in chart big number with trendline that refers to the last value in the trendline with the sum of the value like in chart Big number. how can i do it with change in the code .
```python
class BigNumberViz(BaseViz):

"""Put emphasis on a single metric with this big number viz"""

viz_type = 'big_number'
verbose_name = _('Big Number with Trendline')
credits = 'a <a href="https://github.com/airbnb/superset">Superset</a> original'
is_timeseries = True

def query_obj(self):
    d = super(BigNumberViz, self).query_obj()
    metric = self.form_data.get('metric')
    if not metric:
        raise Exception(_('Pick a metric!'))
    d['metrics'] = [self.form_data.get('metric')]
    self.form_data['metric'] = metric
    return d
```
![image](https://user-images.githubusercontent.com/48314380/56456704-c6d2dd00-6367-11e9-970d-2f164e637b43.png)

**Comment by mistercrunch** [comment]
You probably just want to use a "big number" instead, maybe you complement it with a line chart.

**Comment by MakremHammali** [comment]
@mistercrunch thank you for your  reply
  i want to use big number with trendline because i need  to use Comparison Period Lag 
 is that possible to change in code viz.py  ?  when i change is_timeseries  to false i get the big number  but i need the trendline like in big number with trend line.
