### ISSUE TITLE
Unicode test example not working

### ISSUE THREAD

**Issue by connor924** [apache/incubator-superset#7339]
### Expected results

This should display a word cloud on the chart / dashboard with the different values from the unicode strings

### Actual results

The chart doesn't load with this error:
`Metric 'sum__value' is not valid`

This is the stacktrace:
```
Traceback (most recent call last):
superset_1  |   File "/home/superset/superset/viz.py", line 405, in get_df_payload
superset_1  |     df = self.get_df(query_obj)
superset_1  |   File "/home/superset/superset/viz.py", line 193, in get_df
superset_1  |     self.results = self.datasource.query(query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 835, in query
superset_1  |     query_str_ext = self.get_query_str_extended(query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 481, in get_query_str_extended
superset_1  |     sqlaq = self.get_sqla_query(**query_obj)
superset_1  |   File "/home/superset/superset/connectors/sqla/models.py", line 594, in get_sqla_query
superset_1  |     raise Exception(_("Metric '{}' is not valid".format(m)))
superset_1  | Exception: Metric 'sum__value' is not valid

```
#### How to reproduce the bug

1. Install via docker with latest version of master
2. Go to charts and select Unicode Cloud
3. 

### Environment

(please complete the following information):

- superset version: `master`
- python version: 3.6.8
- node.js version: v10.15.3
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
FYI I'm currently heavily refactoring the sample data code, I think this will get fixed at the same time.
