### ISSUE TITLE
AnaConda3  Install superset OK,but fabmanager is  error adding new user to database ,search no database file

### ISSUE THREAD

**Issue by PeterLau2019** [apache/incubator-superset#7343]
(superset) D:\Anaconda3\envs\superset>fabmanager create-admin --app superset
fabmanager is going to be deprecated in 2.2.X, you can use the same commands on the improved 'flask fab <command>'
Username [admin]: admin
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
Recognized Database Authentications.
2019-04-22 17:02:05,300:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. (sqlite3.IntegrityError) UNIQUE constraint failed: ab_user.email
[SQL: INSERT INTO ab_user (first_name, last_name, username, password, active, email, last_login, login_count, fail_login_count, created_on, changed_on, created_by_fk, changed_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('admin', 'user', 'admin', 'pbkdf2:sha256:150000$1jm1CNdP$dacad99699f448af21f8a866e508c1430c21c19c1a06c352b4ea95d3885e468b', 1, 'admin@fab.org', None, None, None, '2019-04-22 17:02:05.299670', '2019-04-22 17:02:05.299670', None, None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
No user created an error occured

**Comment by PeterLau2019** [comment]
(superset) D:\Anaconda3\envs\superset>pip list
Package                Version
---------------------- -----------
alembic                1.0.9
amqp                   2.4.2
apispec                1.2.1
asn1crypto             0.22.0
astroid                2.2.5
attrs                  19.1.0
Automat                0.7.0
Babel                  2.6.0
billiard               3.6.0.0
bleach                 3.1.0
boto3                  1.4.7
botocore               1.7.48
cchardet               2.1.4
celery                 4.3.0
certifi                2019.3.9
cffi                   1.10.0
chardet                3.0.4
click                  6.7
colorama               0.3.9
constantly             15.1.0
contextlib2            0.5.5
cryptography           1.8.1
defusedxml             0.6.0
docutils               0.14
et-xmlfile             1.0.1
Flask                  0.12.4
Flask-AppBuilder       2.0.0
Flask-Babel            0.12.2
Flask-Caching          1.7.1
Flask-Compress         1.4.0
Flask-JWT-Extended     3.18.1
Flask-Login            0.4.1
Flask-Migrate          2.4.0
Flask-OpenID           1.2.5
Flask-SQLAlchemy       2.3.2
Flask-WTF              0.14.2
flower                 0.9.3
future                 0.16.0
geographiclib          1.49
Geohash                1.0
geopy                  1.19.0
gunicorn               19.9.0
humanize               0.5.1
hyperlink              19.0.0
idna                   2.6
ijson                  2.3
incremental            17.5.0
isodate                0.6.0
isort                  4.3.16
itsdangerous           1.1.0
jdcal                  1.4
Jinja2                 2.10.1
jmespath               0.9.4
jsonlines              1.2.0
jsonschema             3.0.1
kombu                  4.5.0
lazy-object-proxy      1.3.1
linear-tsv             1.1.0
Mako                   1.0.9
Markdown               3.1
MarkupSafe             1.1.1
marshmallow            2.19.2
marshmallow-enum       1.4.1
marshmallow-sqlalchemy 0.16.2
mccabe                 0.6.1
mysqlclient            1.4.2.post1
numpy                  1.16.3
openpyxl               2.4.11
packaging              16.8
pandas                 0.23.4
parsedatetime          2.4
pathlib2               2.3.3
pip                    19.0.3
polyline               1.3.2
prison                 0.1.0
pure-sasl              0.6.1
pycparser              2.18
pydruid                0.5.2
PyHamcrest             1.9.0
PyHive                 0.6.1
PyJWT                  1.7.1
pylint                 2.3.1
pyparsing              2.2.0
pyrsistent             0.14.11
python-dateutil        2.8.0
python-editor          1.0.4
python-geohash         0.8.5
python3-openid         3.1.0
pytz                   2019.1
PyYAML                 5.1
requests               2.21.0
rfc3986                1.3.0
s3transfer             0.1.13
setuptools             41.0.0
simplejson             3.16.0
six                    1.12.0
SQLAlchemy             1.3.3
SQLAlchemy-Utils       0.33.11
sqlparse               0.3.0
superset               0.28.1
tableschema            1.4.1
tabulator              1.19.3
thrift                 0.11.0
thrift-sasl            0.3.0
tornado                5.1.1
Twisted                19.2.0
typed-ast              1.3.1
unicodecsv             0.14.1
Unidecode              1.0.23
urllib3                1.24.2
vine                   1.3.0
webencodings           0.5.1
Werkzeug               0.15.2
wheel                  0.29.0
wincertstore           0.2
wrapt                  1.11.1
WTForms                2.2.1
xlrd                   1.2.0
zope.interface         4.6.0

**Comment by mistercrunch** [comment]
Windows is not supported...
