### ISSUE TITLE
I want to create the development environment locally, which branch should I use

### ISSUE THREAD

**Issue by cscainiao** [apache/incubator-superset#7344]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cscainiao** [comment]
I'm using the master branch now

**Comment by cscainiao** [comment]
But I found that most people use 0.28

**Comment by kristw** [comment]
You should use `master`.
Not sure who are you referring to as people using 0.28.

**Comment by cscainiao** [comment]
thanks
