### ISSUE TITLE
Pivot Table  Field alias display problem

### ISSUE THREAD

**Issue by wushenchao** [apache/incubator-superset#7362]
Pivot Table  Field alias display problem

### Expected results

Both field aliases will display correctly

### Actual results

The second one hasn't changed

#### Screenshots

![屏幕快照 2019-04-24 上午10 04 22](https://user-images.githubusercontent.com/8774296/56627656-597dbf80-6679-11e9-8c18-2b28959c3ac2.png)

### Environment

(please complete the following information):

- superset version:`master`
- python version: `3.6.7`
- node.js version: `node -v` v11.1.0
- npm version: `npm -v` 6.5.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jcoelho-pt** [comment]
We have the same problem. Only the header of the first GroupBy column displays Alias correctly. The remaining Group By column headers display the internal name of the columns (ignoring defined alias).
**Superset Version:** 0.28.1

**Comment by wushenchao** [comment]
> We have the same problem. Only the header of the first GroupBy column displays Alias correctly. The remaining Group By column headers display the internal name of the columns (ignoring defined alias).
> **Superset Version:** 0.28.1
> Same as #5616

I solved the problem temporarily by replacing it,
Is there a better way?

**Comment by jcoelho-pt** [comment]
@wushenchao what did you replaced? the chart? or the table?
TThis issue affects all of my pivot tables.

**Comment by wushenchao** [comment]
> This issue affects all of my pivot tables.

 I replace with the df_html data in viz.py PivotTableViz,

the code:
group_bys = self.form_data.get('groupby')
if group_bys and len(group_bys) > 1:
    for col in group_bys:
        for column in self.datasource.columns:
            verbose_name = column.verbose_name
            if column.column_name == col and verbose_name:
                df_html = df_html.replace('<th>{}</th>'.format(col), '<th>{}</th>'.format(verbose_name), 1)

return dict(
    columns=list(df.columns),
    html=df_html,
)

**Comment by jcoelho-pt** [comment]
@wushenchao Thanks! I am going to test it.
