### ISSUE TITLE
Viz validation overrides no longer being used

### ISSUE THREAD

**Issue by jaylindquist** [apache/incubator-superset#7363]
PR #7231 updated visualization validation to take place in the exploreReducer.js `SET_FIELD_VALUE` action. This validation does not take into account any `controlOverrides` on the visualization.

Specifically, the Table viz removes any validatation from the `metrics` row control. This means attempting to create a Table with only "Not Grouped By" columns fails.

### Expected results

Be able to create a Table visualization with only "Not Grouped By" columns

### Actual results

Creating any Table without a "Metrics" results in an error

#### Screenshots

![image](https://user-images.githubusercontent.com/222699/56630031-623caa00-6615-11e9-815a-ff969664b2a2.png)

#### How to reproduce the bug

1. Create a Table Visualization
1. Delete "Group by" and "Metrics" values
1. Add "Not Grouped By" columns

### Environment

Master branch as of April 22 (commit: 845218dd88ad2fe1284dcb7427c5bff20749dc74)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

n/a

**Comment by ali-bahjati** [comment]
I think we should reopen this issue and it's important to fix.

**Comment by first-caveman** [comment]
+1 on this. I am able to skirt around the issue by first defining "Not Grouped By" columns, and then clearing the 'Metrics' field.

**Comment by axelet** [comment]
The other way to workaround is to change Vis Type to something else and change is back to Table.

**Comment by mistercrunch** [comment]
I could not reproduce on `master`. Loaded up a table chart and cleared `Metrics` field.
<img width="907" alt="Screen Shot 2020-05-21 at 8 30 23 PM" src="https://user-images.githubusercontent.com/487433/82628537-f4f5a280-9ba1-11ea-8ae5-cd6752e37cf4.png">

**Comment by axelet** [comment]
@mistercrunch I also tested on `master` and it doesn't reproduce for me either when loading from a chart. But on the other hand when going through Sources -> Tables, choosing birth_names, for example, and clearing COUNT metric, it does appear for me (tested on Chrome, Opera).
