### ISSUE TITLE
Complete python packages requirement text file with mandatory & optional packages.

### ISSUE THREAD

**Issue by abhioncbr** [apache/incubator-superset#7366]
**Is your feature request related to a problem? Please describe.**
Currently, Superset codebase consists of two requirements file i.e. (requirements.txt, requirements-dev.txt). 
* requirements.txt file contains all the mandotory packages required for Superset.
* requirements-dev.txt file contains packages needed for development purpose.

However, there are some optional packages like Flower which are needed for Superset easy usage. There is no such packages requirement file which lists all mandatory and optional packages. It makes it easier for the installation of the Superset.

**Describe the solution you'd like**
Another requirement file like 'requirement-full.txt' in the codebase.

**Additional context**
I am a maintainer of [docker-superset](https://github.com/abhioncbr/docker-superset) repository and installation of all Superset packages will be much easier.

**Comment by mistercrunch** [comment]
We should look into using `poetry`
