### ISSUE TITLE
Organising Charts List

### ISSUE THREAD

**Issue by black01h** [apache/incubator-superset#7367]
We have a large number of charts/slices within our Superset environment and struggle sorting through them quite often.

We would find it much easier if there were some sort of way to organise all the charts so they aren't just in one long list. Perhaps being able to sort into folders based on their data source or creator?

I understand there is the option to filter down to the charts you wish to see however I feel it would be a good addition to be able to sort the charts into folders without the need to filter would be ideal.

**Comment by mistercrunch** [comment]
There's been work done on tagging for dashboards and charts. I'm not sure why it's been held up. Let me dig out the PR. That tagging feature has been in production at Lyft for a while.

**Comment by mistercrunch** [comment]
@betodealmeida where can I find the frontend portion of the tags?

**Comment by 1AB9502** [comment]
@black01h ,

betodealmedia posted frontend changes today (still WIP) https://github.com/apache/incubator-superset/pull/7418
