### ISSUE TITLE
Hanging during Docker webpack build

### ISSUE THREAD

**Issue by jonlambert** [apache/incubator-superset#7381]
I'm attempting to setup Superset on an AWS t3.micro instance. When running:

```
cd incubator-superset/contrib/docker && \
  docker-compose run --rm superset ./docker-init.sh
```

The command hangs during the webpack build phase.

### Expected results

The build will complete.

### Actual results

The command hangs with the following output:

```
# ...
 > https://www.justgiving.com/refugee-support-europe

added 2514 packages in 31.406s

> superset@0.999.0-dev build /home/superset/superset/assets
> NODE_ENV=production webpack --mode=production --colors --progress

clean-webpack-plugin: /home/superset/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 90% chunk assets processing


```

#### Screenshots

N/A

#### How to reproduce the bug

1. Clone repository
1. Run: `cd incubator-superset/contrib/docker`
1. Run: `docker-compose run --rm superset ./docker-init.sh`
1. See hanging build.

### Environment

(please complete the following information):

- OS: `Ubuntu Xenial 16.04`
- superset version: `master`
- python version: `n/a`
- node.js version: `n/a`
- npm version: `n/a`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sebastianwindeck** [comment]
Hi @jonlambert :) I got the very same issue building an image with docker, how did you solved it? Did you changed something in the Dockerfile or the docker-compose.yml?

**Comment by marmikcfc** [comment]
Hi, to whomsoever it may help, I was able to get it working after increasing the total runtime memory available to docker from 2GB to 4GB.

Reference: https://docs.docker.com/docker-for-mac/

**Comment by RicksterD17** [comment]
> Hi, to whomsoever it may help, I was able to get it working after increasing the total runtime memory available to docker from 2GB to 4GB.

Yes, this did it for me.  Thanks!!!
