### ISSUE TITLE
SQL Lab cannot scroll to bottom of result set without moving the resizer

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#7384]
For a given result set (which requires scrolling) is it seems like one cannot scroll to the bottom of the result set without moving the horizontal resizer up.

### Expected results

One should be able to scroll to the bottom of the result set without having to move the horizontal resizer.

### Actual results

Without moving the horizontal resizer one cannot scroll to the bottom of the result set.

#### Screenshots

![sql-lab-scrolling-issue](https://user-images.githubusercontent.com/4567245/56756353-7207db80-6746-11e9-88ce-a7451eef26c2.gif)

#### How to reproduce the bug

1. Go to SQL Lab and run a query which results in a non-trivial number of rows (~ 100).
2. Try to scroll to the bottom of the result set.
3. Observe you can see the last record(s) without moving the resizer upwards.

### Environment

(please complete the following information):

- superset version: 0.31.0rc23 (Note this may be fixed in `master`).
- python version: 3.6.8
- node.js version: v10.15.0
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

to: @enricoberti @vylc @xtinec

**Comment by michellethomas** [comment]
this is fixed in master
