### ISSUE TITLE
SQL Lab result set page resizing issue

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#7385]
When you resize the page the height of the query box remains unchanged and the result set panel layers over the query box.

### Expected results

Either the components need to resize or there should be a vertical page level scroll bar (preferred). Note for the second approach this would create two vertical scroll bars (the second would be for the query result set) which could be problematic. 

### Actual results

The result set panel flows over the query box element.

#### Screenshots

![sql-lab-page-resize](https://user-images.githubusercontent.com/4567245/56761989-9918da00-6753-11e9-9e50-fabf05130706.gif)

#### How to reproduce the bug

1. Go to SQL Lab and run a query.
2. Resize (vertically) the page.
3. Observe that the result set panel layers over the query panel.

### Environment

(please complete the following information):

- superset version: `master`
- python version: 3.6.8
- node.js version: v10.15.0
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

to: @enricoberti @vylc @xtinec

**Comment by michellethomas** [comment]
this is fixed in master

**Comment by mistercrunch** [comment]
@michellethomas I was able to reproduce this issue in master

cc @xtinec
