### ISSUE TITLE
how to load dashboard faster 

### ISSUE THREAD

**Issue by MakremHammali** [apache/incubator-superset#7387]
i added the cache configuration with redis 
but the dashboard loading is not evolve a lot
is there any solution for that ?
`CACHE_CONFIG = {
# Specify the cache type
'CACHE_TYPE': 'redis',
'CACHE_REDIS_URL': 'redis://localhost:6379/0',
# The key prefix for the cache values stored on the server
'CACHE_KEY_PREFIX': 'superset_results'
}`

**Comment by zhaoyongjie** [comment]
This cache is a cached between the Dashboard and the datasource(Table in
Superset). When you warm up charts, all data will be provided by redis.
