### ISSUE TITLE
Error: no such option: --console-log

### ISSUE THREAD

**Issue by rjurney** [apache/incubator-superset#7389]
On branch `release--0.31` using the `--console-log` option flag with `superset` or `flask run` fails with the error: `Error: no such option: --console-log`.

The docs mention interaction with `--debug`/`--debugger` so I tried a variety of combinations of flags and all resulted in the same error listed above:

```bash
superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger --console-log
superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger --console-log --debug
superset run --console-log --debug
FLASK_DEBUG=1 superset run --console-log --debug
FLASK_DEBUG=1 flask run -p 8088 --with-threads --reload --debugger --console-log
FLASK_DEBUG=1 flask run -p 8088 --with-threads --reload --debugger --console-log --debug
FLASK_DEBUG=1 flask run -p 8088 --console-log
FLASK_DEBUG=1 flask run -p 8088 --console-log --debugger
FLASK_DEBUG=1 flask run -p 8088 --console-log --debug
flask run --console-log --debug
flask run --console-log
```

### Expected results

Something roughly like:

```bash
 * Serving Flask app "superset:app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 303-869-439
```

### Actual results

```bash
Error: no such option: --console-log
```

#### How to reproduce the bug

1. Create a virtualenv for superset and activate it
2. Install the requirements in requirements.txt, requirements-dev.txt and docs/requirements.txt
3. Run: `superset run --console-log --debug` or `flask run --console-log --debug`

### Environment

- superset version: [e.g. `release--0.31` `700cbf4f`]
- python version: `Anaconda Python 3.6.7 :: Anaconda custom (64-bit)`
- node.js version: `v11.14.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This bug also appeared on Mac OS X 10.14.4/homebrew Python 3.7.3/Anaconda 3.6.7

**Comment by MarcusSorealheis** [comment]
I have seen this issue a few times as well.

**Comment by rjurney** [comment]
Pull #7421 addresses this problem by removing `runserver` and `--console-log` until they are fixed to work with `flask run` now that `superset runserver` has been deprecated.

@betodealmeida Can you check this out and comment on whether or not you want to maintain this or let it drop from the project?

**Comment by MarcusSorealheis** [comment]
@rjurney Is the reason we cannot fix it to work with flask run?
That's a more constructive pull request in my view.

**Comment by rjurney** [comment]
@MarcusSorealheis That's what I'm hoping will happen but in lieu of that, there is PR #7421

**Comment by MarcusSorealheis** [comment]
@rjurney I'm going to see if I can get it to work

**Comment by rjurney** [comment]
@MarcusSorealheis See https://github.com/apache/incubator-superset/pull/7428

**Comment by MarcusSorealheis** [comment]
can we close this one @rjurney

**Comment by rjurney** [comment]
Yup
