### ISSUE TITLE
Chart Options showing up in explore under "Data" tab

### ISSUE THREAD

**Issue by michellethomas** [apache/incubator-superset#7393]
In explore the "Chart Options" section is showing up under the `data` tab which looks confusing because it contains controls for the color, legend (things that don't affect the data). The section is moved to the data tab if any of the controls don't have renderTrigger true, the new label_colors control doesn't have renderTrigger set. 

@khtruong Can renderTrigger be set to true for label_colors? Render trigger will make the visualization be re-rendered when the control is changed. If so the "Chart Options" goes back to the Visual tab.

I started to make this change, but noticed that there isn't a control showing up in the UI, it's more of a hidden control, so I'm not sure if it's right to re-render the visualization when the control is changed. If it's a hidden control that can't be set to renderTrigger true, maybe we can put it in the controlSetRow with the other hidden controls (like slice_id, url_params)?

### Expected results

Chart options section shows up on the "Visual Properties" tab

### Actual results

Chart options section shows up on the "Data" tab

#### How to reproduce the bug

1. Go to a line chart
2. On the left side panel see "Chart Options"

### Environment

- superset version: master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

@khtruong 
cc: @graceguo-supercat

**Comment by khtruong** [comment]
Hey Michelle. At the moment, label_colors is a hidden control. Once we enable color consistency for charts, it will not be a hidden control. It's should be safe to set rengerTrigger as true even if it is a hidden control. The only time it changes is when the color scheme changes, which also re-renders.

**Comment by khtruong** [comment]
Btw, I totally agree with your proposal. It is a bit confusing to have controls that aren't related to data under the data tab. So I am all for these changes.
