### ISSUE TITLE
CONTRIBUTING.md is missing mysql_config command being a developer dependency

### ISSUE THREAD

**Issue by rjurney** [apache/incubator-superset#7399]
[`requirements-dev.txt`](requirements-dev.txt) requires `mysqlclient` which requires the OS dependency the `mysql_config` command. CONTRIBUTING.md does not let the new developer know this.

### Expected results

```bash
pip install -r requirements-dev.txt
```

Expect: success!

### Actual results

mysql_config not found!

#### How to reproduce the bug

1. Have a system without the `mysql_config` command on it
2. Run: `pip install -r requirements-dev.txt`

### Environment

- OS: Ubuntu 18.04 and OS X 10.14.4
- superset version: [`release--0.31`, `b3aa5633`]
- python version: `3.6.7`, `3.6.8`, `3.7.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
I found that `pip install mysqlclient` installs a newer version that works. I think we just need to bump the version in `requirements-dev.txt`

```bash
$ pip freeze | grep -i mysql
mysqlclient==1.4.2.post1
```

**Comment by rjurney** [comment]
@mistercrunch Updated so in https://github.com/apache/incubator-superset/pull/7426

**Comment by zhaoyongjie** [comment]
`mysql_config` missing, is a common environmental dependency issue. because
mysqlclient need MySQLConnector/c. if we use pymysql instead of
mysqlclient,these
problems may be avoided. pymysql is a pure python mysql client.
