### ISSUE TITLE
How to share queries with a parameter

### ISSUE THREAD

**Issue by kate-gallo** [apache/incubator-superset#7404]
I want to create a url so that I can access a Superset query from documentation. 

For example, I'd like to share this query:
```
SELECT *
FROM {{ url_param('table_name') }}
LIMIT 100;
```
Assume the saved query has a `savedQueryId=1234`.

Is there any way to add parameters in the sharable link, as for example:
```https://localhost/superset/sqllab?savedQueryId=1234&table_name=sales```
so that when I open the link the parameter is kept?

Is there any other way to create link to superset queries programmatically?

**Comment by arpit-agarwal** [comment]
Which version of superset you are using?
"PoP Tab link" is the one you are asking for. copy the link address.
SQLLAB=> Saved Query
<img width="1365" alt="Screenshot 2019-05-08 at 10 22 12 AM" src="https://user-images.githubusercontent.com/13412230/57350354-6de2b180-717b-11e9-9104-d2b3ee93405c.png">

**Comment by kate-gallo** [comment]
Hi
I am using version `0.25.6`

I copied the link you said, so I have something like 
`https://superset.internal.intercom.io/superset/sqllab?savedQueryId=1234`.

If I add a parameter to this link, as 
`https://superset.internal.intercom.io/superset/sqllab?savedQueryId=1234&table_name=sales` and enter it to the browser, the parameter is not preserved, and when I run the query I get
`relation "none" does not exist`. 

If I add the parameter from Superset once I already opened the query
`https://superset.internal.intercom.io/superset/sqllab?table_name=sales`, 
it works fine.

**Comment by kate-gallo** [comment]
Closest documentation I found that could be helpful is [on Amundsen](https://github.com/lyft/amundsenfrontendlibrary/blob/7a3bdcd661adbcb54e993cdae775c832cddcd44c/docs/examples/superset_preview_client.md)

particularly [this example](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/base/examples/example_superset_preview_client.py)

**Comment by kate-gallo** [comment]
Anyone has an answer for this?

**Comment by marshell0** [comment]
Same question on superset version 1.4.1
