### ISSUE TITLE
Pivot table null values in columns

### ISSUE THREAD

**Issue by srikanth-reddy-m** [apache/incubator-superset#7406]
After setup and upgrade of old DB in the superset, I am facing issue related to pivot table columns showing as null.

### Expected results

It should show 0 as per the previous superset and also Show totals should display actual sum instead of null.

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
![Screenshot_2019-04-29 BU Not Assigned by Destination](https://user-images.githubusercontent.com/46744980/56913621-bfca6e00-6acf-11e9-888c-8f4bfececb56.png)

### Environment

(please complete the following information):

- superset version: [e.g. `v0.29`, `master`, `commit`]
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ngritsuk** [comment]
I've faced with the same issue on the superset docker instance builded from git. All values in pivot table are null, except totals. Totals values are correct.
**Environment**
_commit ebb7fbc5f024379361f301a86b770e0cc1a932cd (origin/master, origin/HEAD, master)_
Author: Ville Brofeldt <33317356+villebro@users.noreply.github.com>
Date:   Wed Jun 26 08:56:19 2019 +0300

I have another superset installation (0.29.0rc7), it shows correct values in pivot table with the same data source and with the same query. 
Screenshot with problem table attached
![superset_screen](https://user-images.githubusercontent.com/10799069/60498265-f171d800-9cbe-11e9-8b2a-b6c892806a56.jpg)

**Comment by ngritsuk** [comment]
Update: to fix my issue it's neccessary in PivotTableViz  class (superset/viz.py) 
`
df = df.pivot_table(
            index=self.form_data.get("groupby"),
            columns=self.form_data.get("columns"),
            values=[utils.get_metric_name(m) for m in self.form_data.get("metrics")],
            aggfunc=aggfunc,
            margins=self.form_data.get("pivot_margins"),
            dropna=False
        )
`
assign True to dropna option

**Comment by sebastianwindeck** [comment]
Would it be possible to add **dropna**  in the pivot table options? or in the chart json ?

**Comment by squalou** [comment]
@ngritsuk  : since #8040 , apparently the `dropna = False` option disappears enirely from viz.py

You may want to check with master's HEAD after August 16, and see what happens.

I'm also interested if these NaN "issues" in pivot table, so your feedback would be welcome

**Comment by squalou** [comment]
I have a workaround : I added `"fill_values=0,`" parameter in viz.py (in the get_data function of ivotTable class).

So ideally, the PivotTable would be greatly enhanced by having more options made available by the GUI : 
- dropna
- fill_values
- maybe others

**Comment by rumbin** [comment]
The issue is also known and being worked on upstream at Pandas:
   * https://github.com/pandas-dev/pandas/issues/18030
   * https://github.com/pandas-dev/pandas/pull/28540

**Comment by i2cute** [comment]
> I have a workaround : I added `"fill_values=0,`" parameter in viz.py (in the get_data function of ivotTable class).
> 
> So ideally, the PivotTable would be greatly enhanced by having more options made available by the GUI :
> 
> * dropna
> * fill_values
> * maybe others

Hi, do i need to recompile after changed this? Or just save the viz.py will do? Sorry I am new to superset

**Comment by squalou** [comment]
Hi,
personnally I overwrite the initial file in a docker image, so my file is taken into account whenever syperset starts.

Maybe in your case you may have to remove __pycache__ if you change the file after superset is started.
(look around the file viz.py, next to parent folder probably, removing __pycache__ will force the use of the patched file / recompile it)

**Comment by eugeniamz** [comment]
@junlincc  can you please take a look at this. Is close by the bot not because the issue was resolved
