### ISSUE TITLE
Can't edit table "List columns"

### ISSUE THREAD

**Issue by josephtyler** [apache/incubator-superset#7424]
There is no save button on the "List Columns" tab when editing a table.

### Expected results

I expected to be able to save the form by clicking a save button.

### Actual results

There is no save button to click.

#### Screenshots

![image](https://user-images.githubusercontent.com/436729/57020344-db239f00-6bdd-11e9-9ac3-6d6a1b08b22d.png)

#### How to reproduce the bug

1. Go to Sources -> Tables
2. Click "Edit record" for a table.
3.  Click "List Columns" tab.
4. Look for a save button.

### Environment

(please complete the following information):

- superset version: 0.29.0rc7
- python version:  3.6.8
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
We're deprecating this view, but I think checking boxes saves automatically. Also the save button is on the `Detail` tab.
