### ISSUE TITLE
how can i use more than 7 tabs

### ISSUE THREAD

**Issue by MakremHammali** [apache/incubator-superset#7432]

**Comment by MakremHammali** [comment]
it is solved by  add another tabs in the dashboard and  drag and drop tab next the other tab
![image](https://user-images.githubusercontent.com/48314380/57090330-7d3aa880-6cfe-11e9-84d6-fc79a8b1ef12.png)

**Comment by elukey** [comment]
@MakremHammali hi! Can this issue be closed?

**Comment by EwertonDCSilv** [comment]
Problema ainda persiste, qual o sentido de limitar o número de tabs ?
