### ISSUE TITLE
How to use “email report”?

### ISSUE THREAD

**Issue by IanXie** [apache/incubator-superset#7454]
The document for email report is too simple so that I can not follow the steps. Could you give a step-by-step doc?

**Comment by sandy-ha** [comment]
The documentation need more Details. I can't follow the steps.

**Comment by christophlingg** [comment]
the documentation is the toughest on superset in general. we should all make an effort (aka pull requests) to improve it. I will do that for the email reporting soon.

**Comment by devesharora90** [comment]
> the documentation is the toughest on superset in general. we should all make an effort (aka pull requests) to improve it. I will do that for the email reporting soon.

I am facing issues to send an email from superset. Config part is done SMTP configured but still, I am not able send an email
