### ISSUE TITLE
Superset initialization error reported 

### ISSUE THREAD

**Issue by cscainiao** [apache/incubator-superset#7456]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: [e.g. `v0.29`, `master`, `commit`]
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cscainiao** [comment]
'AppBuilder' object has no attribute 'add_permissions'

**Comment by cscainiao** [comment]
I think maybe we should remove "appbuilder.add_permissions()"

**Comment by mistercrunch** [comment]
Your FAB version is out-of-sync, anytime you pull from master, in theory you may have to 
```bash
pip install -r requirements.txt
pip install -e .
```

**Comment by elukey** [comment]
@cscainiao Could you please either close this issue or add meaningful data about how to repro in the description? It is really difficult otherwise to help :)
