### ISSUE TITLE
Dashboards View on welcome page shows loading gears if there is no dashboards available in the list 

### ISSUE THREAD

**Issue by bipinsoniguavus** [apache/incubator-superset#7457]
Dashboards View on welcome page shows loading gears if there is no dashboards available in the list 

### Expected results

In case of no dashboards available, there should be no loading gears visible on the dashboard view on welcome page. 

### Actual results

When there are no dashboard on dashboard welcome page, then loading gears are still visible.

#### Screenshots

![Empty_Dashboard_Loading_Bug](https://user-images.githubusercontent.com/18305698/57204648-c3318e00-6fd6-11e9-80eb-72ed86d6ec92.gif)

#### How to reproduce the bug

1. Login into superset with any credentials
2. On Dashboard view on welcome page, it keeps showing loading gears until you add one dashboard.

### Environment

- superset version: `master`
- python version: `3.6.5`
- node.js version: `8.9.4`
- npm version: `6.9.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by doctording** [comment]
should `/welcome` page be deleted, it should be replaced by `/profile/<username> page`. we just need a personal page(namely `/profile/<username>`).

**Comment by doctording** [comment]
details at `superset/assets/src/welcome/DashboardTable.jsx`
