### ISSUE TITLE
Set custom formats other than d3 only

### ISSUE THREAD

**Issue by CrashLaker** [apache/incubator-superset#7470]
Hi all,

I'm wondering If we could setup our custom data output format besides D3's

My problem is. When aggregating columns using pivot tables what I get is a result like this:
![image](https://user-images.githubusercontent.com/4432491/57338935-b52e5b00-7105-11e9-9d4b-43c79ab848ac.png)

For the image above superset's actually using d3.format(".3s") to print it but I actually want it to be divided by a factor of 1024.

I would be awesome if we could pass Superset some sort of javascript function for it to work on.

![image](https://user-images.githubusercontent.com/4432491/57339078-5fa67e00-7106-11e9-9e5d-299a5cc3a3d9.png)

**Comment by doctording** [comment]
in excel, there are many formats
![image](https://user-images.githubusercontent.com/11834821/57361876-0b57d880-71b0-11e9-8443-57cf42df53e1.png)

we change the style(we do not like d3, we think it's not friendly) to make it like in excel
![image](https://user-images.githubusercontent.com/11834821/57362208-e021b900-71b0-11e9-829a-9194d7cd7db2.png)

this feature can be set at all charts, eg

![image](https://user-images.githubusercontent.com/11834821/57363200-27a94480-71b3-11e9-8058-36a2877f11c9.png)

**Comment by CrashLaker** [comment]
Hi @doctording,

thank you for your reply.

Even in excel I couldn't get it to work.
In excel I'm using this custom format "[<1000000]0," GB";[<1000000000]0,," TB";0,,," PB"" but that's really not converting it to TiB or GiB (dividing by 1024).. but again that's another issue.

If I'm to convert it directly in Superset my thought was to add some custom formats other than D3's just like the image you've sent.
I don't have that on my superset
![image](https://user-images.githubusercontent.com/4432491/57388111-f10d0300-718d-11e9-9e96-c56f346c81a3.png)

did you build it yourself or is it from a recent version?
I'm  using version 0.31.0rc18.

I'd be extremely glad if you could share it :)

**Comment by doctording** [comment]
oh, it's a secondary development in my company

**Comment by CrashLaker** [comment]
Any chance on sharing it?

At least the steps, files..

**Comment by sfirke** [comment]
@doctording - would you be interested in sharing this code back to the main Superset project?
