### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by pbalaguer19** [apache/incubator-superset#7479]
Hello! It has been a lot of months since the last stable release (0.28.1, on October) and I am very interested on some new features from some release candidates.

Is there any expectation of publishing a new stable version soon?

**Comment by CoryChaplin** [comment]
0.32rc2 has been voted as future 0.32 release here https://lists.apache.org/thread.html/7adea26358c73ba1d7aab1d354f2f9218040c910ec13ae8d666da493@%3Cdev.superset.apache.org%3E
It's now supposed to be validated by Apache IPMC before official release. I guess that process is in progress.

**Comment by muraiki** [comment]
Maxime said that there was a later -1 vote that has resulted in more discussion: https://github.com/apache/incubator-superset/issues/6785#issuecomment-490748920

I've previously suggested that this project really needs a single place to go to for status updates, but was met with silence. I think Superset as a product is great, but the poor communication in this project drives me nuts, and is the #1 reason why I tell people not to adopt it yet.

**Comment by ShalbafZadeh** [comment]
Any news on a new stable release ?

**Comment by mistercrunch** [comment]
Find the latest information on the dev@ mailing list
