### ISSUE TITLE
Save database record fails

### ISSUE THREAD

**Issue by kleiven** [apache/incubator-superset#7503]
Error message when trying to save a database record. The database record is not saved and an error mesage is displayed. It is not possible to save a new database record or save changes in an existing record.

### Expected results

- I Expected that changes in the database record would be saved and changes shown in supersets list of added databases.
- If I try to save a new database record, I expect the record to be created and the new database shown in the list of added databases.

### Actual results

After pressing "Save" in the "Add database" view (/databaseview/add) I am redirected to /databaseview/list/ and the following error is displayed on top of the page:
"Error 111 connecting to localhost:6379. Connection refused."

The SQLAlchemy URI I am trying to add is of type: presto://
However, the same error was given when trying to add a postgres url as well.

In the add database form I only filled in the follwing two form inputs: 
- Database
- SQLAlchemy URL.
All other form fields were unaltered from their initial state.

#### How to reproduce the bug

1. Go to '/databaseview/add'
2. Fill in 'Test' to the form field 'Database'
3. Fill in a url in the 'SQLAlchemy URI'
3. Click on the "Save" button
4. See error on top of page after redirect to /databaseview/list/

### Environment

- superset version: 0.32.0rc2
- python version: 3.6.8
- node.js version: v8.16.0
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Other context
Superset runs in a kubernetes pod

**Comment by kentore82** [comment]
Im also getting this. Attaching error message for context:
![image](https://user-images.githubusercontent.com/15376838/57693536-c4536280-7649-11e9-9616-4e9822b69640.png)

Ive tested with both Postgres and Presto, both with `Asynchronous Query Execution = false`. 
From the port number `6379` this looks related to Redis and async query execution, however this is stange since I dont have this configured, neither in superset config or in the datasources Im trying to add. 

Have worked around this for now by adding the datasource directly to the superset backend db.

Any advice?

**Comment by mistercrunch** [comment]
Is there a stack trace on the web server logs?

**Comment by villebro** [comment]
I am unable to replicate on 0.32rc2. Any additional info would be helpful.

**Comment by new2itall** [comment]
I think I'm confused....what are yoir tryong to figire out

**Comment by kentore82** [comment]
Sorry for the missing logging info, but I dont see any. No errorlog or stacktrace in the webserver logs. (logging mode DEBUG). :/

**Comment by ravens510127** [comment]
I'm also getting this.
superset version: 3.7.2

**Comment by ravens510127** [comment]
Hi @kleiven  do you fix it?
