### ISSUE TITLE
There is ONLY ONE metric in Filter Box, why NOT support multiple metries 'Metric' field? 

### ISSUE THREAD

**Issue by CasperLiu** [apache/incubator-superset#7513]
### Expected results
Thanks a lot for your nice help in advance!

Metric in Filter Box Visualization Type should be able to have multiple metris.

### Actual results

So far, I could choose ONLY ONE metric in the "Metric" filed.

#### Screenshots
See the picture below:

![image](https://user-images.githubusercontent.com/6135084/57785937-340a4000-7765-11e9-9a55-adc71a4dc081.png)

#### How to reproduce the bug

1. Go to 'Charts', choose below 'Region Filter' with type of filter_box:
![image](https://user-images.githubusercontent.com/6135084/57786061-6a47bf80-7765-11e9-9721-b98e0863807b.png)

2. Click on Query section, Metric field, and however I tried to add a second metric, I always failed.

![image](https://user-images.githubusercontent.com/6135084/57786253-c01c6780-7765-11e9-835b-f80049534d2b.png)

My question here is WHY there is ONLY ONE metric?
Is this by design or a bug/limitation?
Thanks!
### Environment

(please complete the following information):

- superset version: [e.g. `v0.29`, `master`, `commit`]
0.28.1

- python version: `python --version`
(venv) [root@rrswljg003 superset]# python3 --version
Python 3.7.3

- node.js version: `node -v`
Not installed.

- npm version: `npm -v`
Not intsalled.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Thanks a lot again!

**Comment by mistercrunch** [comment]
In newer version it's possible to use different metrics for different filters:
<img width="648" alt="Screen Shot 2019-05-15 at 9 44 12 AM" src="https://user-images.githubusercontent.com/487433/57793375-05a14c00-76f6-11e9-84d5-770f17cfe5ac.png">

**Comment by CasperLiu** [comment]
Maxime,

Thanks a lot for your quick reply!

Which rc version has this feature?

When would this feature be merged into official release, and which release ?

Regards,
Jiaxu
