### ISSUE TITLE
Table headers mis-aligned across tabs after filter application/removal

### ISSUE THREAD

**Issue by thenooz** [apache/incubator-superset#7524]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

## **Superset version**
0.29.0rc7

### 1. Must have multiple tabs in the dashboard
![image](https://user-images.githubusercontent.com/16484838/57844440-af173900-77ed-11e9-983a-7cf229a38d19.png)

### 2. Apply any filter and observe that the headers in table are correctly aligned in the tab you were on at the time of application of filter.
![image](https://user-images.githubusercontent.com/16484838/57844485-c6eebd00-77ed-11e9-880c-007e732f09c7.png)

### 3. Switch to a different tab and you will see the headers are mis-aligned in all the tables.
![image](https://user-images.githubusercontent.com/16484838/57844506-cfdf8e80-77ed-11e9-8d03-090dec209eaf.png)

Any action that forces the visualization to refresh resets the header alignment. As of now I am able to see this bug while applying filters and then switching to another tab.

**Comment by thenooz** [comment]
Hi @mistercrunch , can you please look into this? Sorry to "bug" you.

**Comment by Ryouku** [comment]
Hello, would like to re-open it, cause it appears to be reproducible in the latest version of the Superset.

**Comment by Ryouku** [comment]
@dpgaspar @graceguo-supercat @mistercrunch @rusackas
