### ISSUE TITLE
Fix scrolling list (SQL Lab Query Search)

### ISSUE THREAD

**Issue by tomdewildt** [apache/incubator-superset#7526]
When the content in the Query Search table is larger than the viewport no scrollbar appears. Leaving the user unable to scroll.

### Expected results

A scrollbar appears and the user is able to scroll.

### Actual results

No scrollbar appears and the user is unable to scroll.

#### Screenshots

![superset-sqllab-query-search-no-scrollbar](https://user-images.githubusercontent.com/32359630/57866479-ba736000-77ff-11e9-8452-d956b9c211f6.png)

#### How to reproduce the bug

1. Create 15 or more querries.
2. Visit the Query Search page.

### Environment

- superset version: ```master```
- python version: ```3.6.7```
- node.js version: ```v9.11.2```
- npm version: ```5.6.0```

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by margrathea** [comment]
If you add overflow: auto to the scrollbar-container div in your browser than you're able to scroll again...

**Comment by gerard-witvliet** [comment]
> If you add overflow: auto to the scrollbar-container div in your browser than you're able to scroll again...

This is just a quick hack, this needs to be fixed somewhere in the stylesheets.

**Comment by tomdewildt** [comment]
> If you add overflow: auto to the scrollbar-container div in your browser than you're able to scroll again...

This breaks other UI elements
