### ISSUE TITLE
[SIP-20] Proposal for Implementing Chart Level Custom Calculations

### ISSUE THREAD

**Issue by 1AB9502** [apache/incubator-superset#7530]
Currently at Spotx we are working on adding chart level custom calculations (aka custom formulas). The purpose of this SIP is to gauge the interest in the feature and whether we should push it upstream

### Motivation

A subset of Superset users at SpotX has requested the ability to make chart level calculations.
By chart level we mean in contrast to postagg calculations that are already supported to an extent by Druid. While postaggs are fine for some purposes, they add overhead to the druid cluster and are created via JSON that general users don’t have access to. The users also might be interested in creating one off calculations that do not warrant creating a dedicated postagg field or calculations that involve if/then statements

### Proposed Change

While researching possible solutions, we came across formulas.py library https://pypi.org/project/formulas/ 
which implements an interpreter for Excel style formulas. 
As an example of how this works, during chart creation we select clicks impressions as metrics,  add an excel like formula ( example =SUM(clicks/impressions*100) ). Once the results are sent from druid and pandas creates a df, we can perform the requested calculation and append a new column to the df.  

### New or Changed Public Interfaces

The proposed changes are the following:

- Integrate formulas.py library into Superset
- Implement formula validation endpoint
- Expose Custom Formulas React Component in the chart creation page where users are able to select predefined formulas or enter a new custom formula  
- Add new custom_formulas table
- Add new link under the Manage tab in order to allow custom formulas to be added on an individual datasource basis

### New dependencies

Formulas.py PyPI package has been actively maintained since Feb 2017 https://pypi.org/project/formulas/#history
The library is currently under EUPL text (1.1 & 1.2) license and its compatible with the Apache License https://joinup.ec.europa.eu/collection/eupl/eupl-compatible-open-source-licences

### Migration Plan and Compatibility

The feature will require a database migration (new table will be added)

Some screenshots:
![Screen Shot 2019-05-16 at 12 17 37 PM (2)](https://user-images.githubusercontent.com/22640110/57886745-2e573d80-77eb-11e9-8e91-efc73cae066e.png)

![Screen Shot 2019-05-16 at 12 32 23 PM (2)](https://user-images.githubusercontent.com/22640110/57886748-31522e00-77eb-11e9-9e9e-661bb7d55ef4.png)

**Comment by jdbertron** [comment]
I would love to see this added.

**Comment by mistercrunch** [comment]
I'm not sure if https://github.com/vinci1it2000/formulas is the right choice (though I haven't done any research). It has limited traction. On the license side, we'd also have to make sure that the ASF is ok with it as I don't see it on the approved license list https://apache.org/legal/resolved.html#category-a . I'd hate for the next person to push an Apache release to have to deal with clearing that.

Implementation-wise, I agree this should be backend code as the dataframe is probably the right place to apply this (as opposed to viz-specific code), though I think we have code doing similar things on the frontend for "Annotations" as formulas (I think it's using `math.js`?).

As to where this should be defined: could this be a metric parameter instead? By that I mean your metric definition may [optionally] be a formula and/or reference other metrics?

**Comment by SpyderRivera** [comment]
This would be very useful and frankly powerful for my team of users!

**Comment by 1AB9502** [comment]
Thanks for the feedback @mistercrunch!
We are going to take a look into your suggestions. Closing this for now

**Comment by jdbertron** [comment]
I asked the owner of formulas to see if he could change the license: This is his response (https://github.com/vinci1it2000/formulas/issues/33):

Unfortunately, I cannot change the license. But you have two options:

The Apache license is one of the upstream compatible licenses of the EUPL. Hence, the "derivative work" has to be redistributed under the EUPL.

If you don't want to use the EUPL, you can use the functionality of formulas as it is (i.e., without merging the source code), following the example of chapter 5.6 of the EUPL guidelines. Therefore, if you need extra functionalities, you can propose those through pull requests with the changes and/or the features that you want to integrate into formulas.

**Comment by jdbertron** [comment]
I don't see why we should block on this, since we're not merging the formulas library into superset, we're just using the library. Am I reading this wrong ?

**Comment by rusackas** [comment]
Since this issue is closed due to inactivity, we'll also consider the SIP/proposal process closed as well. If you want to rekindle this proposal, please re-open this Issue, and send a new [DISCUSS] thread to the dev@ mailing list. Thank you!
