### ISSUE TITLE
superset db upgrade fails on upgrading to new superset version with Oracle

### ISSUE THREAD

**Issue by cluttrell** [apache/incubator-superset#7534]
When trying to upgrade on existing instance with an oracle backend, superset db upgrade fails on the existing objects already in the database. It tries to do a create instead of alter on existing objects
### Expected results

what you expected to happen.
db upgrade should just update db as needed
### Actual results

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/6579219/57901044-e7883880-7828-11e9-9a18-240d663f06b0.png)

### Environment

(please complete the following information):

- superset version: .32
- python version: 3.6.8

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by elukey** [comment]
Question: what version are you trying to upgrade?
