### ISSUE TITLE
master branch run problems, can I add a run.py

### ISSUE THREAD

**Issue by doctording** [apache/incubator-superset#7537]
this issue is about when `git clone https://github.com/apache/incubator-superset`, how to run the master branch project instead of `pip install superset`.

----

my environment to run master branch project
* ubuntu18.04.1 x86_64 GNU/Linux
* Python 3.6.7
* node 8.10.0

when I use `superset runserver -d` as introduced at https://superset.incubator.apache.org/installation.html, the error occur

```python
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Starting Superset server in DEBUG mode
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[DEPRECATED] As of Flask >=1.0.0, this command is no longer supported, please use `flask run` instead, as documented in our CONTRIBUTING.md
[example]
flask run -p 8080 --with-threads --reload --debugger
```
it's right, it's a flask version problem

In fact I use `pycharm`(https://www.jetbrains.com/pycharm/) and a `run.py`

![image](https://user-images.githubusercontent.com/11834821/57937181-fd186380-78f7-11e9-8157-dadd76c213b3.png)

the content of `run.py`

```python
from superset import app
app.run(debug=True, host='0.0.0.0', port=8080)
```

![image](https://user-images.githubusercontent.com/11834821/57937363-5da7a080-78f8-11e9-826b-232091f21c88.png)

it works well, so can I add the `run.py` file to master branch, may be some developers do like this.

**Comment by 1AB9502** [comment]
Did you try **pip install -e .** ?

**Comment by doctording** [comment]
> Did you try **pip install -e .** ?

a robot ？ I just introduce my way to run branch master , not `pip install`

**Comment by 1AB9502** [comment]
Not a robot. 

Just to confirm it seems like you are talking about **pip install superset** being inconvenient, not **pip install -e .** 

-e (--editable) flag installs superset in editable mode from a local path.

**Comment by doctording** [comment]
> Not a robot.
> 
> Just to confirm it seems like you are talking about **pip install superset** being inconvenient, not **pip install -e .**
> 
> -e (--editable) flag installs superset in editable mode from a local path.

oh， I'm so sorry for it.
