### ISSUE TITLE
docker-compose up just stop

### ISSUE THREAD

**Issue by bwon7** [apache/incubator-superset#7542]
I am trying to running docker-compose up. Before I did, I change the line  SUPERSET_ENV: production #SUPERSET_ENV: development in docker compose.yml for warning from rpm installation. And then, I also commented out   #- ../../superset:/home/superset/superset in volume. It is also in the docker-compose.yml. 
However, docker-compose up just stop here as below the picture. 
![Screen Shot 2019-05-17 at 2 57 35 PM](https://user-images.githubusercontent.com/38637458/57950088-434bd380-78b4-11e9-93f8-7df655463de3.png)
![Screen Shot 2019-05-17 at 2 57 52 PM](https://user-images.githubusercontent.com/38637458/57950089-434bd380-78b4-11e9-99ec-364ef124daee.png)
![Screen Shot 2019-05-17 at 2 58 04 PM](https://user-images.githubusercontent.com/38637458/57950090-434bd380-78b4-11e9-9eaa-b68866068ea4.png)
![Screen Shot 2019-05-17 at 2 58 13 PM](https://user-images.githubusercontent.com/38637458/57950091-434bd380-78b4-11e9-8c99-41fa258cb632.png)

How to fix this problem?

**Comment by lrosenman** [comment]
gevent is missing from the requirements.txt file.

**Comment by mistercrunch** [comment]
`gevent` should be optional though, it's really only used if you happen to use `gunicorn` in async mode, trying to keep the main package lean... Maybe add an extra `requirements-docker.txt` in `contrib/docker/` and an extra `RUN` in the `Dockerfile`?

**Comment by bwon7** [comment]
how to add requirements-docker.txt? you mean requirements.txt?

**Comment by bwon7** [comment]
> `gevent` should be optional though, it's really only used if you happen to use `gunicorn` in async mode, trying to keep the main package lean... Maybe add an extra `requirements-docker.txt` in `contrib/docker/` and an extra `RUN` in the `Dockerfile`?

The requirements-docker.txt is requirements.txt in incubator-superset folder?
