### ISSUE TITLE
superset 启动

### ISSUE THREAD

**Issue by rockyCheung** [apache/incubator-superset#7551]
在官方提供启动指令superset runserver -d，但执行该指令提示异常：无runserver指令。通过--help查看才知道，运行指令是superset run。
执行fabmanager create-admin --app superset设置了用户和密码，但是登录时报：密码错误～

**Comment by rockyCheung** [comment]
采用superset fab create-admin指令代替fabmanager create-admin --app superset可解决用户登录问题～
启动程序要采用superset run指令，只是superset_congif.py中配置的端口未起作用，启动后要通过5000端口访问～

**Comment by mistercrunch** [comment]
This repo operates in english, please re-open your issue

**Comment by rockyCheung** [comment]
1、create a file (module) superset_config.py
#---------------------------------------------------------
# Superset specific config
#---------------------------------------------------------
ROW_LIMIT = 5000

SUPERSET_WEBSERVER_PORT = 8088
#---------------------------------------------------------

#---------------------------------------------------------
# Flask App Builder configuration
#---------------------------------------------------------
# Your App secret key
SECRET_KEY = '\2\1thisismyscretkey\1\2\e\y\y\h'

# The SQLAlchemy connection string to your database backend
# This connection defines the path to the database that stores your
# superset metadata (slices, connections, tables, dashboards, ...).
# Note that the connection information to connect to the datasources
# you want to explore are managed directly in the web UI
SQLALCHEMY_DATABASE_URI = 'sqlite:////path/to/superset.db'

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True
# Add endpoints that need to be exempt from CSRF protection
WTF_CSRF_EXEMPT_LIST = []
# A CSRF token that expires in 1 year
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365

# Set this API key to enable Mapbox visualizations
MAPBOX_API_KEY = ''
2、Create app
superset fab create-app --name superset --engine SQLAlchemy
3、Create an admin user
superset fab create-admin
4、Initialize the database
superset db upgrade
5、Load some data to play with
superset load_examples
6、Create default roles and permissions
superset init
7、To start a development web server on port 8088, use -p to bind to another port
superset runserver -d
[详细环境搭建方法可参见](http://www.pathcurve.cn/topic/144/bi-superset的安装使用)
