### ISSUE TITLE
Superset on pip is not up to date

### ISSUE THREAD

**Issue by chintanparikh** [apache/incubator-superset#7562]
The latest version on pip is 0.29.0rc7 while on github it is 0.33.0rc1. Can we get the version on pip updated?

**Comment by mistercrunch** [comment]
We're not allowed to push to Pypi per Apache Software Foundation rules, there's more information about it on the mailing list, we're currently working on our first official ASF release

**Comment by chintanparikh** [comment]
@mistercrunch Gotcha, thanks for the info!

**Comment by chintanparikh** [comment]
Is there a recommended way to install a version higher than 0.29.0rc7? I'm trying to use Superset with Snowflake and getting a conflict with the cryptography package

**Comment by mistercrunch** [comment]
If you want to be future-proof and build from source you can try the latest Apache RC, here's the [non-optimized] Dockerfile (for reference). If you don't want to use docker you can still use the Dockerfile as guidelines as to how to turn the source release into something that works.

https://github.com/apache/incubator-superset/pull/7539/files#diff-64c3b7e25d5ff6ff077e2a4263aa865dR1

**Comment by chintanparikh** [comment]
@mistercrunch Exactly what I was looking for, thank you!
