### ISSUE TITLE
Annotation layer doesn`t work with Time-series Bar Chart

### ISSUE THREAD

**Issue by rattlesnake2478** [apache/incubator-superset#7566]
If you try to add an annotation layer to the time series bar chart - it brokes the script and chart became inaccessible. Browser console contains next error:
```
Uncaught TypeError: Cannot read property 'dispatch' of undefined
    at 3.2f2d46f….chunk.js:1
    at Array.forEach (<anonymous>)
    at Object.generate (3.2f2d46f….chunk.js:1)
    at e (1.e5a4a22….chunk.js:1)
```
### Expected results
Annotation layer added successfully. There are no errors in the browser console, the main chart remains on the page.

### Actual results
Annotation layer added successfully. There are errors in the browser console. 

#### How to reproduce the bug
1. Create time series bar chart
2. Add annotation layer
3. See error in the browser console.

### Environment
superset version `0.29.0rc7` from docker repo 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sharpyfox** [comment]
please do not close it
