### ISSUE TITLE
Setting up superset using docker

### ISSUE THREAD

**Issue by ali-bahjati** [apache/incubator-superset#7578]
This post is for everyone who wants to set up superset using docker since they are some problems which are differently listed as issues here but may be hard to find.

 
First add gevent to python requirements.
Second add user: root:root to your superset service in docker-compose.

And then you can follow the instructions on doc. However if you want to load the examples you should instead of running:
`SUPERSET_LOAD_EXAMPLES=yes docker-compose run --rm superset ./docker-init.sh`
run this:
`docker-compose run --rm -e SUPERSET_LOAD_EXAMPLES=yes superset ./docker-init.sh`

**Comment by ali-bahjati** [comment]
Also if you want to connect to hive you should install these packages too:
libsasl2-modules-gssapi-mit libsasl2-modules libsasl2-2 sasl2-bin
and in pip you should install pyhive and thrift_sasl 

Beware that in my experience working with SparkSQL using thrift server you should use `hive://addr:port(default: 10000)` and SQL Lab couldn't discover tables correctly.

**Comment by hieast** [comment]
how to add user: `root:root` to in docker-compose?
I am new to docker and don't understand where to add the user, in the  `docker-compose` command-line or the `docker-compose.yml` file?
thanks.

**Comment by ali-bahjati** [comment]
In `docker-compose.yml` in superset service with the same indention as `volumes:` add `user: root:root`

**Comment by forbiddenvoid** [comment]
There are a couple of other docker issues that need to be addressed related to the Flask AppBuilder CLI update. But, there's not much to do to create a PR that makes the docker instructions actually functional: 

* adding gevent 1.4.0 to the requirements.txt file
* adding a root:root user to the superset service in `docker-compose.yml`
* correcting the bash instructions for initializing the examples
* adding the `FLASK_APP` env variable to `docker-init.sh` and removing the `--app` argument from  the `flask fab` command. 
* looks like the instructions in `CONTRIBUTING.md` also have the `--app` argument as well.

More than happy to put up a PR to fix those issues.
