### ISSUE TITLE
cal_heatmap hover window blocked by the title of slice in a dashboard

### ISSUE THREAD

**Issue by izzyleung** [apache/incubator-superset#758]
Example: ![image](https://cloud.githubusercontent.com/assets/4300850/16813762/e0c8a598-48e7-11e6-8219-528377ad4667.png)

The cal_heatmap visualization does not have this problem in the home page of caravel, because it can overlay the hover window on the outside content.

Maybe we can move the cal_heatmap in the middle or enable content overlay.

**Comment by georgeke** [comment]
Took a quick look at this, I'm leaning towards the centering since the issue right now is that there is `overflow: auto` on the container which we need but contradicts the `overflow: visible` the tooltip (child) needs.

**Comment by poppop0911** [comment]
Version 0.15.1 still have this problem, 
whether can through lift height of container, 
place the heatmap below the container to solve this problem?

**Comment by abotero** [comment]
Fixed in https://github.com/apache/incubator-superset/pull/4268
