### ISSUE TITLE
Queries using current_username() method do not run properly when caching is enabled

### ISSUE THREAD

**Issue by duffar12** [apache/incubator-superset#7580]
OS - Ubuntu 16.04

When a query is defined using a function. For example 
         SELECT * FROM user WHERE username '{{current_username()}}' 
this will run only run as expected the first time it is run. If another user runs the exact same query from his or her account, the result will be pulled from the cache rather than running the query again with a different username. The problem disappears if caching is disabled

### Expected results

When caching is enabled, queries using the current_username() method, should not produce the same results for different users even if all other query parameters are the same.

### Actual results

When caching is enabled, queries using the current_username() method, DO produce the same results for different users if all other query parameters are the sam

#### How to reproduce the bug

1. Enable a redis cache
2. Create 2 different users with admin role e.g 'user1' and 'user2'
3. Create a Users table with fields username and metric
4. Add 2 records to the Users table 'user1, 1' and 'user2, 2'
5. login to superset as user1 and create a table chart to view the Users table. Specify a filter of username = '{{current_username()}}'
6. On a different browser login to superset as user2. Create the exact same table as you created for user1. 
7. Notice that the table presented on user2 account actually shows the data for user1
8. Disable the redis cache and repeat steps 1-7. Notice that the problem is not present when caching is disabled

### Environment

(please complete the following information):

- superset version: 0.33.0
- python version: 3.6.8

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Hmm, a quick fix that comes to mind is to search the query string with a regex along the lines of
`\{\{(.|\n)*current_username\(\)(.|\n)*\}\}`, and if there is a match, add the username to the query object so it gets baked into the hash. This should be easy to implement, but feels slightly hackish at first glance..

**Comment by mistercrunch** [comment]
I think you'll  have to disable the cache on that chart.

**Comment by duffar12** [comment]
I'm not sure how the caching mechanism works under the hood. But, I feel like the variables in a query should be resolved before checking the cache for results of that query. Otherwise your queries return garbage

**Comment by RameshByndoor** [comment]
Any update on this.? @mistercrunch can you shed some lights on this behaviour.

**Comment by villebro** [comment]
I propose the following: we add a function `cache_key_wrapper(key: Any) -> Any`  to the template processor, to which one can pass any value, which behind the scenes adds values to an `extra_keys` list, and finally returns the original key. This list is then added to the `query_obj`, which is used to calculate the cache key. So instead of writing

```sql
SELECT * FROM user WHERE username = '{{ current_username() }}'
```

One would write

```sql
SELECT * FROM user WHERE username = '{{ cache_key_wrapper(current_username()) }}'
```

This should be fairly easy to implement, is very straight forward to use, and gives the end user full freedom of which keys will be passed to the cache key. Thoughts?

**Comment by mistercrunch** [comment]
@duffar12 unfortunately we cannot use the `SQL` of the query directly as the basis for the cache key. The main issue has to do with relative time filters (ie `24 hours ago`) being different at each run. Here's what we do now:
https://github.com/apache/incubator-superset/blob/master/superset/viz.py#L347-L369

We use the query_object's key/values, and inject the raw time filter as opposed to the "rendered" one.

Given that context, it seems like @villebro 's solution may work. Unclear to me how `cache_key_wrapper` gets scoped to the template object only though, but there should be a way to implement something like that.

**Comment by villebro** [comment]
@mistercrunch I have a working prototype that fixes this problem. The idea is to keep the `query_object` unchanged, but run it through the query compilation phase to catch any keys from the template processor (any values that have been fed to `cache_key_wrapper`), and then add those to a list that goes into `cache_dict` that's used for calculating the hash. I'll clean up the code and add unit tests and should be able to put through a PR later this week.
