### ISSUE TITLE
SQL Lab fetches incorrect result set

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#7582]
Sometimes when run a SQL Lab query from a new tab/window it fetches the wrong result set. 

### Expected results

The result set should be associated with the correct query.

### Actual results

The result set is associated with the incorrect query. The `queryId` associated with the `sql_json/` request is not the same as the `queryId` in the result set.

#### Screenshots

![Screen Shot 2019-05-22 at 11 42 10 AM](https://user-images.githubusercontent.com/4567245/58200212-241fbe00-7c87-11e9-9137-95b507265920.png)
![Screen Shot 2019-05-22 at 11 42 25 AM](https://user-images.githubusercontent.com/4567245/58200214-241fbe00-7c87-11e9-8301-3b8d6b4b5c71.png)

#### How to reproduce the bug

1. Go to SQL Lab and run a query.
2. Go to SQL Lab via a new tab/window and run another query. 
3. Note that the result set for (2) is associated with (1).

### Environment

(please complete the following information):

- superset version: 0.31.0rc23.dev1
- python version: 3.6.8
- node.js version: v10.15.0
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

to: @graceguo-supercat

**Comment by graceguo-supercat** [comment]
@john-bodley you may have multiple query running, in different sql lab query tab, or in different browser window.

**Comment by john-bodley** [comment]
@graceguo-supercat that is correct I did have multiple SQL Lab tabs and/or browser windows. Regardless I would except SQL Lab to fetch the correct result set. The current behavior erodes trust in the tool.

**Comment by graceguo-supercat** [comment]
did results show in the wrong query tab? if so that is bug. 
otherwise, this is just `asynchronous` way of handling requests.

**Comment by mistercrunch** [comment]
There's a single process that polls for all active queries, are you saying the result sets get rewired wrong and end up in the wrong tab?

**Comment by john-bodley** [comment]
Yes that seems to be the case. I’ll try to attach some video/screenshots.
