### ISSUE TITLE
Not getting scheduled chat/dashboard emails

### ISSUE THREAD

**Issue by starsunny** [apache/incubator-superset#7588]
I've recently installed 0.31 superset version,
I can see the email scheduling options in "Manage" tab, I've made changes in config.py for SMTP
Ran Celery worker and beat also , but getting following error:
time limit (250s) exceeded for email_reports.send
I've changed it to 500s also, and changed CELERYD_PREFETCH_MULTIPLIER = 10
, but still not getting any emails, Am I missing something?
@mahendra
<img width="1509" alt="Screenshot 2019-05-23 at 4 06 03 PM" src="https://user-images.githubusercontent.com/20131173/58246439-b487fc80-7d74-11e9-93f8-90cacaa2570d.png">

**Comment by niharikay** [comment]
Hi, @starsunny were you running on HTTPS webservers and were you able to find a solution?

**Comment by mahendra** [comment]
@starsunny can you please post the output from celery logs?

Are you using Firefox or Chrome driver?
Are you running it locally on your machine or on a server? If local, I may have some additional tricks to find out what is happening.

**Comment by devops-tech-rivigo** [comment]
Thanks, @mahendra  I've been using an older version of gecko driver with firefox, as well as somehow selenium version and celery version got changed too,
I've debugged it and fixed.

@niharikay Yes, I've been running on HTTPs.

**Comment by starsunny** [comment]
Thanks, @mahendra   I've been using an older version of gecko driver with firefox, as well as somehow selenium version and celery version got changed too,
I've debugged it and fixed.

@niharikay Yes, I've been running on HTTPs. but how it's related to this?

**Comment by priyankadadlani** [comment]
Hi @starsunny @mahendra, I made the required changes in config.py and installed Firefox and geckodriver. I don't see any errors but still not getting the scheduled emails. It may be because of version incompatibilities. I have installed geckodriver 24 and Firefox 41(I know versions older than 47 do not need Geckodriver but RHEL 6 systems only support Firefox versions 41 or older.) Any suggestions on steps to debug or get the scheduled emails working on RHEL 6?

**Comment by starsunny** [comment]
@priyankadadlani please share celery logs,
You can try to install celery flower to monitor celery activity,
Or you can redirect logs to specific file while running the command,

Or also you can share the config.py.

**Comment by bohlian** [comment]
Hi guys, I am having troubles getting the menu options to show. I am using the docker version and I have set the following in config.py:

`ENABLE_SCHEDULED_EMAIL_REPORTS = True

EMAIL_NOTIFICATIONS = True
SMTP_HOST = "somehost"
SMTP_STARTTLS = True
SMTP_SSL = True
SMTP_USER = "someemail"
SMTP_PORT = 25
SMTP_PASSWORD = "somepassword"
SMTP_MAIL_FROM = "somemailfrom"`

Is there something that I am missing? Thanks guys

**Comment by toilv** [comment]
Have you install the  geckodriver and Firefox yet ?
Then run 2 following command  :
`celery worker --app=superset.tasks.celery_app:app --pool=prefork -Ofair -c 4
celery beat --app=superset.tasks.celery_app:app`

**Comment by Jarvis173** [comment]
i have enabled the email service in my config.py but getting below error when trying to create the email report :
![Screenshot from 2020-01-26 11-36-33](https://user-images.githubusercontent.com/17108885/73131386-287b5280-4030-11ea-88f9-3d7202a99c91.png)
Can anyone please guide ?

**Comment by mahendra** [comment]
> i have enabled the email service in my config.py but getting below error when trying to create the email report. Can anyone please guide ?

@Jarvis173 could you please post an error message from the log files? will help with debugging

**Comment by Jarvis173** [comment]
> > i have enabled the email service in my config.py but getting below error when trying to create the email report. Can anyone please guide ?
> 
> @Jarvis173 could you please post an error message from the log files? will help with debugging

There is no error that i can see in the logs.

**Comment by Niteesh** [comment]
https://github.com/apache/incubator-superset/issues/8201

**Comment by sankonale** [comment]
i have configured mail parameter into config file, but still we are unable to send report to the email.
ENV ENABLE_SCHEDULED_EMAIL_REPORTS True
ENV SMTP_HOST testmail.sersec.com
ENV SMTP_STARTTLS True
ENV SMTP_SSL False
ENV SMTP_USER admin
ENV SMTP_PORT 25
ENV SMTP_PASSWORD superset
ENV MTP_MAIL_FROM superset@sersec.com
ENV EMAIL_REPORTS_USER admin

is there any other configuration ?

**Comment by DRavikanth** [comment]
@mahendra, @starsunny , I am running into issues setting up the emailing dashboard as well. Here is a link to the ticket where I posted the details, logs. Any pointers in the right direction will be of great help. https://github.com/apache/incubator-superset/issues/11507
