### ISSUE TITLE
How to pass in a cert for SSL access to a Druid

### ISSUE THREAD

**Issue by brachi-wernick** [apache/incubator-superset#7596]
Fail with that error:
Max retries exceeded with url: /druid/v2/datasources (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

How can I set certificate to druid?

**Comment by brachipa** [comment]
I found how to do it, I changed the DockerFile. and added these lines: (before changing user to be superset)

```
RUN apt-get install -y ca-certificates
COPY contrib/docker/imply-crt-new.crt /usr/local/share/ca-certificates/mycert.crt
RUN update-ca-certificates

ENV REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/mycert.crt
```
