### ISSUE TITLE
World Map ISO Codes in APACHE SUPERSET

### ISSUE THREAD

**Issue by Dikshant2597** [apache/incubator-superset#7601]
I am trying to use the country map for India. I see India in the drop down menu. My query runs without any error. But for the visualization, I am unable to see any map.
Also my data has a column named 'ISO' with the codes starting with 'IN-'.
And I am working on Windows 10(venv).

Expected results
I expect to see India's map along with the states.

Actual results
Its a bank screen with no map/boundaries.

Checklist
Make sure these boxes are checked before submitting your issue - thank you!

  I have checked the superset logs for python stacktraces and included it here as text if there are any.
  I have reproduced the issue with at least the latest released version of superset.
  I have checked the issue tracker for the same issue and I haven't found one similar.
Additional context

**Comment by TheLastSultan** [comment]
Noticed the problem at American Express with India Maps as well. Will link a simple PR to solve this issue.

**Comment by pratibhapeshwa1** [comment]
I am facing the same issue, done all the said changes, added India, but unable to see the map.
