### ISSUE TITLE
Time Series - Line Chart: changing format on axis

### ISSUE THREAD

**Issue by lisa-bob** [apache/incubator-superset#7607]
Hi there, 

I am using the Apache Superset interface and unfortunately I'm limited to it.
I'm getting the data for the temperature like this: 230 but I need it to be displayed like 23.0. Is there any way to add a personal format just with the interface? The given formats for the "Y Axis Format" are not suitable for me. 

If not, can you tell me where do I have to write my own formatting function in the code?
![valueformattig_superset](https://user-images.githubusercontent.com/49370404/58556608-b5110f00-821c-11e9-84f0-ddb17967b5ce.png)

**Comment by francishemingway** [comment]
It's not exactly what you're asking for, but have you considered creating a new calculated column? 

To do this, click on the datasource within the explore chart view, then add an item in the third tab of this dialogue (Calculated Columns). You'll have to enter an SQL expression to do the division.
