### ISSUE TITLE
Getting the following error while loading dashboard - TypeError: Failed to fetch

### ISSUE THREAD

**Issue by hijju** [apache/incubator-superset#7613]
Hello There, I have been using superset on docker for sometime now. Recently I am coming across this particular error when loading the dashboards. If I refresh the page sometime it goes away and sometime it take multiple tries. I am trying to figure out what causes this error. I am using superset on docker, postgres db for metadata and the actual data is on memsql. All these resources are on AWS. 

Error:
Unexpected error: (no description, click to see stack trace)
TypeError: Failed to fetch

Did anyone come across the same error? Really appreciate any thoughts on this.

**Comment by elukey** [comment]
@hijju it might be a timeout of some sort, but in order to help we'd need the stacktrace of the exception.. Usually you can click on the error in the UI to retrieve it, or check in the Python logs.
