### ISSUE TITLE
SESSION_REFRESH_EACH_REQUEST parameter is not working with sql queries run in sqllab

### ISSUE THREAD

**Issue by dejv13** [apache/incubator-superset#7619]
SESSION_REFRESH_EACH_REQUEST parameter is not working with sql queries run in sqllab.
We have setup SESSION_REFRESH_EACH_REQUEST in superset config to True to renew PERMANENT_SESSION_LIFETIME after each query in Sqllab.

*Expected results*
We expect that via setup SESSION_REFRESH_EACH_REQUEST = True , the session lifetime will be *renewed* with each sql query action in sql lab.

*Actual results*
At this moment we have *configured*
PERMANENT_SESSION_LIFETIME = 1800
and SESSION_REFRESH_EACH_REQUEST = True but these two parameters are working together when *(in the 30 min time window) we e.g. change the tab in superset. When we are working in SQL Lab the session expires after 30 mins no matter how many queries are executed.*

### Environment

(please complete the following information):

- superset version: [0.28.1]
- python version: Python 3.6.8

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by shawnzhu** [comment]
It still doesn't work under superset 1.2.0. expected expiration time for cookie `session` after using `PERMANENT_SESSION_LIFETIME` and `SESSION_REFRESH_EACH_REQUEST`

I saw the code from Flask where it must make `session.permanent = True` to get expiration time. see https://github.com/pallets/flask/blob/a430c43736ab029b472c9641aa0b6203638391c2/src/flask/sessions.py#L264-L274

So I wonder if this is something can be done in superset codebase

**Comment by shawnzhu** [comment]
commented in https://github.com/apache/superset/issues/5149#issuecomment-899942147 and please checkout #16286 to see how to setup `session.permanent` by using `FLASK_APP_MUTATOR`.
