### ISSUE TITLE
Make Requests library an optional dependency

### ISSUE THREAD

**Issue by sturmer** [apache/incubator-superset#7620]
The Requests library seems to be legally problematic so it was suggested to get rid of it as a dependency.

Quoting @mistercrunch :

> It appears it's used
in its simplest form in a few places (requests.get) which should be easy to
replace with urrlib2. The Druid connector uses a more advanced feature
(basic auth), but that could be made just an optional dependency, as we're
deprecating the Druid connector, to be replaced by the SQLAlchemy Druid
connector/dialect. There it's just a matter of moving `pydruid` and
`requests` to the "extra_requires" section of our setup.py, and doing late
imports.

CC: @villebro

**Comment by sturmer** [comment]
As stated in the dev mailing list, I proposed to write a PR for this issue.

**Comment by mistercrunch** [comment]
Related, I added a bit of code to conditionally run unit tests based on whether a package is installed or not:
https://github.com/apache/incubator-superset/pull/7605/files#diff-a3e90139d93a6d9706419011538cdcd2R178

It's likely you'll need something similar if making `pydruid` and `requests` optional
