### ISSUE TITLE
Send email reports for Scheduled queries from SQL Lab

### ISSUE THREAD

**Issue by Mengsuper** [apache/incubator-superset#7626]
**Is your feature request related to a problem? Please describe.**
This request related to Scheduled Query in SQL Lab.

**Describe the solution you'd like**
I'm working on a project using Superset. Basically I would like to use the Scheduled Query to setup some SQL query periodically (hourly, daily etc). Based on the query results, I want to send the result as a report (queried table result) to other users via email. For current features, as far as I know, there is no such emailing functionality for Scheduled Query. I was wondering whether there is anyone working or planning to work on this feature. If not, does anyone can share any thought on this feature development so I can start to work on? Thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by miloradkrstevski** [comment]
Load the results in lets say mysql table, then use data connection to load the table from mysql into excel and finally VBS to send the table as XLSX, CSV, PDF ...
