### ISSUE TITLE
Off by one in time series bar chart

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#763]
It looks like there's an off by one in the month visualization. If i do this kind of query:

```
select foo, COUNT(distinct bar) from baz and EXTRACT(month FROM "date") =2 and EXTRACT(year FROM "date") = 2015 group by foobar;
```

I see the count numbers to match the "2015-01" column while i expect it to be "2015-02" instead. If i export the csv i see data correctly with a "2015-02-01" timestamp.

Reproduced both in 0.9.1 and 0.10.0.

**Comment by rotten** [comment]
If the timezone for the command line client and caravel installation are different it could change the counts (this is a common issue).  To ensure that isn't the problem, try adding "at time zone" to the query :

`select foo, COUNT(distinct bar) from baz and EXTRACT(month FROM "date") at time zone 'America/New_York'  and EXTRACT(year FROM "date") at time zone 'America/New_York' = 2015 group by foobar;`

**Comment by xrmx** [comment]
@rotten the count given by caravel matches what i can extract from the db it's just a visualization problem

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
