### ISSUE TITLE
Connection fails to Amazon Athena from superset on EC2 environment

### ISSUE THREAD

**Issue by tanmaya26** [apache/incubator-superset#7631]
I am trying to run superset on an EC2 instance but the URI for Athena fails. I see version conflict for EC2 machine's s3transfer library and the s3transfer version that superset uses. 

### Expected results
The connection should be successful. I am using python 3.6.8. 

### Actual results
Here, is the stack trace:
ERROR:root:(s3transfer 0.2.0 (/home/ec2-user/.local/lib/python3.6/site-packages), Requirement.parse('s3transfer<0.2.0,>=0.1.10'), {'boto3'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 1779, in testconn
    engine = create_engine(uri, **engine_params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/url.py", line 168, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 229, in load
    return impl.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (s3transfer 0.2.0 (/home/ec2-user/.local/lib/python3.6/site-packages), Requirement.parse('s3transfer<0.2.0,>=0.1.10'), {'boto3'})

#### How to reproduce the bug

1. Go to terminal
2. Connect to EC2 instance via ssh
3. Run superset
4. Open superset on browser and enter URI in 'New Data source' page.

### Environment

(please complete the following information):

- superset version: `0.28.1`
- python version: 3.6.8
- node.js version: not found
- npm version: not found

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [checkbox:checked] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [checkbox:checked] I have reproduced the issue with at least the latest released version of superset.
- [checkbox:checked ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by tanmaya26** [comment]
Sudo pip freeze:

alembic==1.0.10
amqp==2.5.0
apispec==1.3.3
asn1crypto==0.24.0
attrs==19.1.0
Babel==2.7.0
billiard==3.6.0.0
bleach==3.1.0
boto3==1.4.7
botocore==1.7.0
cchardet==2.1.4
celery==4.3.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
click==6.7
colorama==0.3.9
contextlib2==0.5.5
cryptography==2.7
defusedxml==0.6.0
docutils==0.14
et-xmlfile==1.0.1
Flask==0.12.4
Flask-AppBuilder==2.1.3
Flask-Babel==0.12.2
Flask-Caching==1.7.2
Flask-Compress==1.4.0
Flask-JWT-Extended==3.18.2
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
flower==0.9.3
future==0.16.0
geographiclib==1.49
geopy==1.20.0
gunicorn==19.9.0
humanize==0.5.1
idna==2.8
ijson==2.3
isodate==0.6.0
itsdangerous==1.1.0
jdcal==1.4.1
Jinja2==2.10.1
jmespath==0.9.4
jsonlines==1.2.0
jsonschema==3.0.1
kombu==4.6.0
linear-tsv==1.1.0
Mako==1.0.10
Markdown==3.1.1
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.3
numpy==1.16.4
openpyxl==2.4.11
pandas==0.23.4
parsedatetime==2.4
pathlib2==2.3.3
polyline==1.3.2
prison==0.1.1
pyasn1==0.4.5
PyAthena==1.4.4
pycparser==2.19
pydruid==0.5.3
PyHive==0.6.1
PyJWT==1.7.1
pyrsistent==0.15.2
python-dateutil==2.8.0
python-editor==1.0.4
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2019.1
PyYAML==3.12
requests==2.22.0
rfc3986==1.3.2
rsa==3.4.2
s3transfer==0.1.10
sasl==0.2.1
simplejson==3.16.0
six==1.12.0
SQLAlchemy==1.2.18
SQLAlchemy-Utils==0.33.11
sqlparse==0.3.0
superset==0.28.1
tableschema==1.5.0
tabulator==1.21.0
tenacity==5.0.4
thrift==0.11.0
thrift-sasl==0.3.0
tornado==5.1.1
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.25.3
vine==1.3.0
virtualenv==16.6.0
webencodings==0.5.1
Werkzeug==0.15.4
WTForms==2.2.1
xlrd==1.2.0

**Comment by dpgaspar** [comment]
Hi @tanmaya26 

Superset by itself does not impose any boto3 dependency. This may be a conflict between boto3 and PyAthena. On a test environment upgrade boto3, latest 1.9.X requires s3transfer >= 0.2.0.

**Comment by tanmaya26** [comment]
Issue fixed by installing and running superset in virtualenv.
