### ISSUE TITLE
Add New button visible for users without permissions

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#7644]
The "Add New" buttom appears when user has no permissions.
Superset shows the "Add New" button for users without permissions.

### Expected results

Visible if the user has permissions on one or more options

### Actual results

User clicks and gets back to main page

#### Screenshots

![image](https://user-images.githubusercontent.com/767180/58878080-bc2f9580-86d2-11e9-8bc0-8ff0734f56ab.png)

#### How to reproduce the bug

1. Create a user without any permissions
2. Log in superset

### Environment

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.7.2`
- node.js version: `v10.15.0`
- npm version: `6.4.1`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ohoroyoi** [comment]
I think this feature is really needed
