### ISSUE TITLE
treemap Color Scheme not working，Get the same color

### ISSUE THREAD

**Issue by cscainiao** [apache/incubator-superset#7649]
### Expected results
Get multiple colors
what you expected to happen.

### Actual results
Get the same color
what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`   master
- python version: `python --version`     3.7
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cscainiao** [comment]
![image](https://user-images.githubusercontent.com/38780513/58937168-3714b100-87a4-11e9-829e-697caff4a3fe.png)

**Comment by amerinoo** [comment]
Hi @cscainiao , I've tried to reproduce your issue but everything works as expected. Can you check if your case is also working at this moment? If it works you could close this issue.

**Comment by syafiqdante** [comment]
I seem to face the same problem as well:

![treemap error 10 10 2019](https://user-images.githubusercontent.com/46438728/66544736-882a1c80-eb6b-11e9-81bf-5d4d2c96a9cc.PNG)

Environment :-
superset version: `0.34.0`
python version: `Python 3.6.8`
node.js version: `v10.16.0`
npm version: `6.9.0`

Does anyone knows the solution..?

**Comment by elukey** [comment]
I am running 0.35.2 and I can still see the issue, can somebody re-open the task?

**Comment by grzegorzzyla** [comment]
same problem in 0.36

**Comment by cande1gut** [comment]
Same issue in 0.38

**Comment by Austin-AM** [comment]
same issue in 0.38 and 1.0.0

**Comment by shalnice** [comment]
same issue with
Environment :
superset version: 1.4.2
python version: Python 3.9

![image](https://user-images.githubusercontent.com/98736099/163184488-e1b83769-fae6-4658-a0e8-5a29685d8295.png)
