### ISSUE TITLE
d3 formatting not working

### ISSUE THREAD

**Issue by duffar12** [apache/incubator-superset#7650]
### Expected results

Number formatting on dashboard should change according to d3 format specified in metrics

### Actual results
Specifying a d3 format works on the COUNT(*) metric. But has no affect on any other metric as far as I can tell

#### Screenshots

![image](https://user-images.githubusercontent.com/7714673/58973271-74366e80-87b7-11e9-80fc-44a90be9cad4.png)

In the image above COUNT(*) and SUM(count) have the same d3 format configured. However, the configuration is not being applied to SUM(count)

#### How to reproduce the bug

1. Change the d3 format of COUNT(*) and any other metric for one of your tables
2. Create a table view of these two metrics. 
3. Notice that d3 formatting is only applied to the COUNT(*) metric

### Environment

*superset version: 0.33.0
*python version: 3.6.8

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have seen a number of other Issues raised around d3 formatting dating back to 2017. As far as I can tell those issues were fixed in this PR https://github.com/apache/incubator-superset/pull/2598
So I believe this must be a new bug

**Comment by duffar12** [comment]
@kristw any ideas about how to fix this?

**Comment by Orchild** [comment]
Same problem on Pie Chart, D3 Format not work
![TLPic_20190708202346](https://user-images.githubusercontent.com/3110230/60809958-87759900-a1be-11e9-9c22-f41beb4eda44.png)

**Comment by crazyplum** [comment]
@kristw 
same issues here.
please don't close this issue.

**Comment by rusackas** [comment]
FWIW, I managed to get D3 formatting to work in the Table component for other metrics besides COUNT(*) as you can see in this (admittedly odd looking) example:

![image](https://user-images.githubusercontent.com/812905/68816930-e64b9300-0634-11ea-989b-f2d81d646004.png)

Nonetheless, I also see/confirm that this formatting value is not represented in the Pie chart (or probably other NVD3-derived chart types).

**Comment by kristw** [comment]
@rusackas There is an incomplete PR, which maybe related, if anybody feels like picking up. 
https://github.com/apache-superset/superset-ui-plugins/pull/171

**Comment by rusackas** [comment]
PRs to respect the metrics' `D3 Format` value submitted here: 
https://github.com/apache-superset/superset-ui-plugins/pull/280
and here:
https://github.com/apache-superset/superset-ui-plugins/pull/282
