### ISSUE TITLE
error: Error: Item with key "deck_scatter" is not registered.

### ISSUE THREAD

**Issue by KirillYoYo** [apache/incubator-superset#7658]
![image](https://user-images.githubusercontent.com/26794095/59022190-f37a7f80-8855-11e9-9688-53876495ab74.png)

Try to start dashboard, but happing this error:
`message: "Item with key "deck_screengrid" is not registered."
stack: "Error: Item with key "deck_screengrid" is not registered.↵    at b.getAsPromise (webpack-internal:///./node_modules/@superset-ui/core/esm/models/Registry.js:14:1977)↵    at Chart (webpack-internal:///./node_modules/@superset-ui/chart/esm/components/SuperChart.js:12:1951)↵ ..."`

### Environment

- superset version: `superset version` 0.32.0rc2.dev2
- python version: `python --version` 3.6.7
- node.js version: `node -v` v8.16.0
- npm version: `npm -v` 6.4.1

**Comment by kristw** [comment]
Did you modify anything or this is clean master? 
Try deleting your `node_modules` directory then `npm install` and try again.
