### ISSUE TITLE
Warn the users about duplicate countries in the Worldmap

### ISSUE THREAD

**Issue by x4base** [apache/incubator-superset#766]
In our system, the country names are in lower case in some records while the others are in upper cases (i.e. There are "us" and "US") . But in world map, they are all converted to upper case ("USA"). As the result, there will be two records labeled "USA" in the http response. In the frontend, the latter will overwrite the first one, resulting in unexpected behaviors. I know it's our fault to allow inconsistent cases to exist. But if we really want to warn the user when such problem exist, what's the best way? We can't simply sum the us metric and US metric up, because we can't be sure the metric is linear and can be summed up. Should we just throw an error?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
