### ISSUE TITLE
Indian currency format Like ₹ 5.00 Cr and ₹ 5.22 Lac

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#7661]
**Is your feature request related to a problem? Please describe.**
      i TRIED THIS INDIAN CURRENT FORMAT  AND NOW ITS WORKING WITH ME 

**Describe alternatives you've considered**
nOW I AM ABLE TO SHOWN IT IN INDIAN CURRENCY FORMAT ₹ 5.00 Cr and ₹ 5.22 Lac

**Additional context**
₹ 5.00 Cr and ₹ 5.22 Lac

**Comment by kalimuthu123** [comment]
![Screenshot from 2019-06-03 16-36-58](https://user-images.githubusercontent.com/42966797/59032581-45d29500-8884-11e9-9be5-9edac833caf2.png)

**Comment by kalimuthu123** [comment]
![image](https://user-images.githubusercontent.com/42966797/59034269-4f5dfc00-8888-11e9-9d2c-a5d5115a5660.png)

**Comment by kingo55** [comment]
Cool - would you be able to mark this closed @kalimuthu123 ?

**Comment by kalimuthu123** [comment]
i cannot get your words

**Comment by MuraliSTT** [comment]
Hii @kalimuthu123 how did you achieve this?. i want to add this functionality to my project

**Comment by DivyaRevealer** [comment]
can anyone let me know how can we accommodate in our application

**Comment by prasanjeetdas** [comment]
Can you please tell how you solve this issue.
