### ISSUE TITLE
Test connection doesn't use DB_CONNECTION_MUTATOR 

### ISSUE THREAD

**Issue by thoralf-gutierrez** [apache/incubator-superset#7668]
### Expected results

We use [`DB_CONNECTION_MUTATOR`](https://github.com/apache/incubator-superset/blob/master/superset/config.py#L519-L534) to modify some of the `connect_args` passed to the `create_engine` function, and I expect those modifications to be applied whenever connections are created.

### Actual results

But unfortunately, the "Test Connection" button doesn't use `DB_CONNECTION_MUTATOR`, which mean the connections aren't set up properly and users get a pop up telling that the connection doesn't work, even though just clicking on "Save" would actually work.
See https://github.com/apache/incubator-superset/blob/master/superset/views/core.py#L1821-L1830

### More context

We use `DB_CONNECTION_MUTATOR` to add additional user information to authenticate with the database.

Do you agree "Test Connection" should use `DB_CONNECTION_MUTATOR`? If yes, I can push a PR to fix it.

**Comment by mistercrunch** [comment]
Good catch @thoralf-gutierrez, it seems like `testconn` should just instantiate a Database object and call `get_sqla_engine`

**Comment by thoralf-gutierrez** [comment]
Cool - I'll push a PR in the few next days.
