### ISSUE TITLE
Error Whilst Adding Database

### ISSUE THREAD

**Issue by cgivre** [apache/incubator-superset#7669]
When attempting to add a database to Superset on Ubuntu 18 I get the following error: 
```
TypeError: Object of type int64 is not JSON serializable
```
This was caused here:  
https://github.com/apache/incubator-superset/blob/d62c37b8958fe89aa69df8f1d582460abef548d1/superset/views/core.py#L1833

What is happening is that to test the connection, Superset is issuing the query, the result coming back is a numPy int64.  

### Expected results
I expected the connection to be added

### Actual results
```
TypeError: Object of type int64 is not JSON serializable
```

### Environment
Ubuntu v. 18
(please complete the following information):

- superset version: `0.999.0dev`
- python version: `3.6.8 :: Anaconda custom (64-bit)`
- node.js version: `10.16.0`
- npm version: `6.8.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This can be fixed by modifying the line as follows:
```
return json_success(json.dumps(int(conn.scalar(select([1])))))
```

**Comment by mistercrunch** [comment]
@john-bodley looks like this came from recent https://github.com/apache/incubator-superset/pull/7570

**Comment by mistercrunch** [comment]
@cgivre how about `return json_success(json.dumps(conn.scalar(select(['a'])))) ` or how about `return json_success(json.dumps(int(conn.scalar(select([1]))))) `

**Comment by cgivre** [comment]
@mistercrunch I think either of those would work.  I tried the `int` version that you listed there, and it worked for me.  

I can submit a PR if you'd like tomorrow.

**Comment by mistercrunch** [comment]
Surprised it didn't get caught by https://github.com/apache/incubator-superset/blob/36a219da7f81c0e65a259049896bb77fd66edbe2/tests/core_tests.py#L354

What db engine are you connecting to? From the test we know mysql/postgres/sqlite should work...

**Comment by cgivre** [comment]
It was Drill.  I originally thought it was a problem with the sqlalchemy dialect.

**Comment by mistercrunch** [comment]
Shouldn't the DBAPI driver return native types? What type is `int64` here?

**Comment by cgivre** [comment]
This is a very strange error because this works fine on my Mac.  It was only when I tried this on an Ubuntu machine that it caused problems.  The issue is that the `int64` is a `numpy` data type. 
@JohnOmernik, any ideas?

**Comment by mistercrunch** [comment]
Would approve solutions suggested in my comment here: https://github.com/apache/incubator-superset/issues/7669#issuecomment-499756804

**Comment by cgivre** [comment]
@mistercrunch  I'll submit a PR this weekend.

**Comment by john-bodley** [comment]
Sorry wouldn’t a simpler solution be:

```
conn.scalar(select([1]))
return json_success(‘“OK”’)
```

i.e., we really don’t care what the JSON response is but rather that the status code is `200`. The try/except handles the failed connection case.
