### ISSUE TITLE
cann't open file'superset ' when I setup 'superset db upgrade' no such file

### ISSUE THREAD

**Issue by sherry9393** [apache/incubator-superset#7683]
![image](https://user-images.githubusercontent.com/41997508/59242908-1d5de880-8c40-11e9-9603-c29404a7098b.png)

**Comment by dpgaspar** [comment]
Hi, did not tested it, but follow this guide:

https://www.youtube.com/watch?v=0zhQ52BQQ5s&feature=youtu.be
