### ISSUE TITLE
[doco] - persisting connection information to connect to the datasources

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#7694]
homepage mentions this:

# Note that the connection information to connect to the datasources
# you want to explore are managed directly in the web UI

how is it managed directly in the web UI?
what options are there to persist this? ie if running superset on EC2 and the EC2 machine auto-heals and restarts on a different machine

**Comment by dpgaspar** [comment]
Hi @tooptoop4,

Connection information is managed on "Sources" -> "Databases", and this meta information is kept on Superset's DB. So you must setup your DB outside of your EC2 instances
