### ISSUE TITLE
'NoneType' object has no attribute 'strip' error when editing the dashboard setting

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7695]
### Expected results

Dashboard title changed

### Actual results

'NoneType' object has no attribute 'strip' appear

#### Screenshots

![Screenshot from 2019-06-12 15-39-29](https://user-images.githubusercontent.com/28984703/59332220-4e194d00-8d28-11e9-8678-1791659edddb.png)

#### How to reproduce the bug

1. Go to 'Dashboard' section
2. Click on 'Edit record' on dashboard
3. Edit the dashboard title and save 

or 

1. Go to 'Dashboard' section
2. Click on '+' button which is 'Add a new record'
3. Save without content

### Environment

(please complete the following information):

- superset version: `0.28.1`
- python version: `Python 3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @syazwan0913,

Please fill out the issue template, thank you

**Comment by dpgaspar** [comment]
Thanks @syazwan0913, can you fill the "How to reproduce the bug" steps

**Comment by dpgaspar** [comment]
Replicated your steps and got no errors. Can you post the server log?

**Comment by syazwan0913** [comment]
Is it on superset version `0.28.1` ?

**Comment by syazwan0913** [comment]
Fixed it already

**Comment by AasthaPoddar** [comment]
> Fixed it already
How did you fix it?

**Comment by syazwan0913** [comment]
@AasthaPoddar use the latest version
