### ISSUE TITLE
error on "refresh druid metadata": Duplicate entry for key 'uq_columns_column_name'

### ISSUE THREAD

**Issue by leo4work** [apache/incubator-superset#7697]
### Expected results

after add druid cluster, I click "refresh druid metadata" button, I wish the databases of druid cluster can merge into database.

### Actual results

erro log:

Error while processing cluster 'zjy' (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'industrylevel2-2022' for key 'uq_columns_column_name'") [SQL: 'INSERT INTO `columns` (created_on, changed_on, column_name, verbose_name, is_active, type, groupby, count_distinct, sum, avg, max, min, filterable, description, datasource_id, dimension_spec_json, created_by_fk, changed_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 6, 12, 15, 18, 13, 148434), datetime.datetime(2019, 6, 12, 15, 18, 13, 148443), 'industrylevel2', None, 1, 'STRING', 1, 0, 0, 0, 0, 0, 1, None, 2022, None, 1, 1)] (Background on this error at: http://sqlalche.me/e/gkpj)

#### Screenshots
- my druid cluster conf:

![image](https://user-images.githubusercontent.com/19853623/59337276-d43a9100-8d32-11e9-9a64-7ccd49b03d18.png)

- superset view : 
![image](https://user-images.githubusercontent.com/19853623/59337352-01873f00-8d33-11e9-8311-dc7e4d763361.png)

superset log:
![image](https://user-images.githubusercontent.com/19853623/59337168-9b022100-8d32-11e9-914c-639ef3d42906.png)

### Environment

(please complete the following information):
CentoOS 6.3
- superset version: `superset version` === 0.28.1
- python version: `python --version` === 3.6.8
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michellethomas** [comment]
Based on that error it looks like you may already have a column in the table `2022` called `industrylevel2`, check your underlying datasource to make sure you aren't trying to create another column with the same name.
