### ISSUE TITLE
Can I set headers for SupersetClient requests?

### ISSUE THREAD

**Issue by KirillYoYo** [apache/incubator-superset#7698]
Can I set headers for SupersetClient requests?
![image](https://user-images.githubusercontent.com/26794095/59341014-bb6cb400-8d0f-11e9-9b2c-0075059eb1a5.png)

**Comment by mistercrunch** [comment]
@kristw may have an answer

**Comment by graceguo-supercat** [comment]
@KirillYoYo did you try something like this line: `mode: 'cors'`

https://github.com/apache/incubator-superset/blob/929fb6bbb8fdc5c03ba4f88898c91183ab2bad11/superset/assets/src/chart/chartAction.js#L190
