### ISSUE TITLE
Superset Real Time Visualization

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#7704]
I have a mariadb database connected to apache superset for real time visualization, however the dashboards are a day behind so they are only showing data up to 23:59 the previous day. I have checked the timezone and it is correct, I have also tried auto-refreshing after 5 minutes and 'force refresh' but the dashboards remain the same. I have tried opening the slices' queries in mysql lab but it is impossible to edit them to fetch real time data. Does anyone know how to get real time visualization using superset?

**Comment by davidhassan** [comment]
Try setting your date time range on your chart to be one day ahead. 

Example: 14-June-2019 to 15-June-2019 will only display data within June 14th. It will not include any data in June 15th.

If you set your date range to be 14-June-2019 to 1 day from now you will see 15-June-2019 data in realtime assuming you are auto-refreshing every 5 minutes.

**Comment by mistercrunch** [comment]
Inspect the generated SQL on the explore view and make sure it looks as expected

**Comment by villebro** [comment]
@mashciku if you want charts to default to showing all datapoints today instead of yesterday 23:59, set 
`DEFAULT_RELATIVE_END_TIME = 'now'` in `superset_config.py`: https://github.com/apache/incubator-superset/blob/0d122431b287b1a34f006d91717d1b4e09136869/superset/config.py#L615

**Comment by mashciku** [comment]
@villebro I have added DEFAULT_RELATIVE_END_TIME = 'now'  to the config.py and made it executable but nothing has changed. It's still showing 23:59.

**Comment by mashciku** [comment]
@villebro Actually, it has worked. Thank you.
