### ISSUE TITLE
Could not locate a Flask application

### ISSUE THREAD

**Issue by ralsouza** [apache/incubator-superset#7707]
After running the image with Docker and entering the admin user information the error below is displayed.

### Expected results
Confirm admin user creation and start Superset.

### Actual results
After entering admin user data, the error is displayed.
```
+ '[' 1 -ne 0 ']'
+ exec ./docker-init.sh
+ flask fab create-admin
Username [admin]: admin
User first name [admin]: admin
User last name [user]: user 
Email [admin@fab.org]: admin@fab.org
Password: 
Repeat for confirmation: 
Usage: flask fab create-admin [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
```
#### Screenshots
NA.
#### How to reproduce the bug
1. git clone https://github.com/apache/incubator-superset/
2. cd incubator-superset/contrib/docker
3. docker-compose run --rm superset ./docker-init.sh

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
```Ubuntu 19.04```

**Comment by Haks1** [comment]
Yup, I wrote about it yesterday, but the issue was closed https://github.com/apache/incubator-superset/issues/7689#issuecomment-501470532

Also, if you try to change the create admin call in `docker-init.sh:`
> I've tried with `fabmanager create-admin --app superset` and I got this error:
> `"There is no appbuilder var on your package, you can use appbuilder parameter to config"`
> 
> (I got also this same error if I try to compose on branch `0.30`)

**Comment by axcarlin** [comment]
Download the package a couple of minutes ago, same issue after completing the admin user credentials prompts

`Was unable to import superset Error: No module named 'flask_talisman'`

**Comment by Orchild** [comment]
I have the same problem

`Error: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.`

**Comment by dpgaspar** [comment]
Hi,

This works: `sudo docker-compose run -e FLASK_APP=superset:app ./docker-init.sh`

I'll submit a PR to solve it or on `docker-init.sh` or on README.md

**Comment by ralsouza** [comment]
> Hi,
> 
> This works: `sudo docker-compose run -e FLASK_APP=superset:app --rm superset ./docker-init.sh`
> 
> I'll submit a PR to solve it or on `docker-init.sh` or on README.md

It worked very well, thank you !!!
Starting my journey on Superset!

**Comment by dpgaspar** [comment]
Great! Have a nice journey then ;)

**Comment by ryaneid** [comment]
@dpgaspar I'm getting a new error when I run that
jinja2.exceptions.TemplateNotFound: superset/base.html
when I launch localhost

**Comment by mdZhuang** [comment]
> Downloaded the package a couple of minutes ago, same issue after completing the admin user credentials prompts
> 
> `Was unable to import superset Error: No module named 'flask_talisman'`

I had the exact same problem with the new version. Did you manage to fix it? Thank you!

**Comment by littlepea** [comment]
I still have an issue with `Was unable to import superset Error: No module named 'flask_talisman'` and `sudo docker-compose run -e FLASK_APP=superset:app --rm superset ./docker-init.sh` doesn't help

**Comment by visakhmurukes** [comment]
I'm also getting the same issue 

Was unable to import superset Error: No module named 'flask_talisman'

**Comment by mrchan123** [comment]
fabmanager create-admin --app superset until this is fixed

**Comment by haoyang1024** [comment]
> Hi,
> 
> This works: `sudo docker-compose run -e FLASK_APP=superset:app --rm superset ./docker-init.sh`
> 
> I'll submit a PR to solve it or on `docker-init.sh` or on README.md

How should I use this command on Windows
