### ISSUE TITLE
Receive "Bad request The CSRF session token is missing." when try to login into superset that has been published viaiframe

### ISSUE THREAD

**Issue by mshemadarshini** [apache/incubator-superset#7708]
### Expected results

To Able to Access into Dashbaord and work with the web page via iframe

### Actual results

Receive Error "Bad request The CSRF session token is missing." upon logging into the web page

#### Screenshots
![Screen Shot 2019-06-14 at 4 41 11 PM](https://user-images.githubusercontent.com/5733901/59496145-67a2cc00-8ec3-11e9-9915-298d5d83b948.png)

Screenshot available as attached 

#### How to reproduce the bug

1. Launch Apache Superset via flask Python.
2. Connect the link via iframe into another separate webpage

### Environment

(please complete the following information):

- superset version: `superset Flask 0.12.4`
- python version: `Python 3.6.6 `
- node.js version: `node -v = v10.16.0`
- npm version: `npm -v = 6.9.0 `

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ /] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ /] I have reproduced the issue with at least the latest released version of superset.
- [ /] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
What version of Superset is this?

**Comment by mshemadarshini** [comment]
> What version of Superset is this?

superset version: superset Flask 0.12.4

**Comment by dpgaspar** [comment]
`Flask 0.12.4` is the Flask version
Run `superset version` or check your python env and check for apache-superset

**Comment by scatmanoleg** [comment]
It is an actual master
