### ISSUE TITLE
jinja2.exceptions.TemplateNotFound on Superset Instillation 

### ISSUE THREAD

**Issue by ryaneid** [apache/incubator-superset#7711]
Had same issue as #7707 when trying to install superset. Tried suggested fix, got new error when launching localhost.

#### How to reproduce the bug

1. git clone https://github.com/apache/incubator-superset/
2. cd incubator-superset/contrib/docker
3. sudo docker-compose run -e FLASK_APP=superset:app --rm superset ./docker-init.sh
4. view http://localhost:8088

Getting jinja2.exceptions.TemplateNotFound
<img width="628" alt="Screen Shot 2019-06-14 at 3 02 19 PM" src="https://user-images.githubusercontent.com/39681242/59535032-784c4580-8eb5-11e9-91e1-a2201220a0ef.png">
Even though I do have the file in the correct directory.

**Comment by ryaneid** [comment]
uninstalled python3, reinstalled. No longer receiving this error.

**Comment by yravindra** [comment]
still i am having same issue .even i followed above steps.
