### ISSUE TITLE
[docker] Flask fab error: module 'superset' has no attribute 'app'

### ISSUE THREAD

**Issue by Haks1** [apache/incubator-superset#7713]
Installation fail on create-admin.

Next to https://github.com/apache/incubator-superset/issues/7689 and https://github.com/apache/incubator-superset/issues/7707 , I've already tried https://github.com/apache/incubator-superset/pull/7709/commits/2fefed793c6fc69e9d3a484000ada5d0ea48040f (cf: https://github.com/apache/incubator-superset/issues/7689#issuecomment-501470532) with no success.
Same bug on actual master, tried `docker-compose run -e FLASK_APP=` too (on the version before https://github.com/apache/incubator-superset/pull/7709/commits/2fefed793c6fc69e9d3a484000ada5d0ea48040f).

### Expected results

Superset ready on Docker

### Actual results

```
Usage: flask fab create-admin [OPTIONS]

Error: module 'superset' has no attribute 'app'
```

#### How to reproduce the bug

```
clean:
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
	docker rmi $(docker images -q)
	(restart Docker deamon)

main:
	git clone https://github.com/apache/incubator-superset/
	cd incubator-superset/contrib/docker/
	SUPERSET_LOAD_EXAMPLES=yes docker-compose run --rm superset ./docker-init.sh
```

### Environment

Docker inside
(18.09.2 - Docker for Windows via Ubuntu 18.04 on Win 10 WSL)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I've tried `FLASK_APP=superset`
result: `Error: Failed to find Flask application or factory in module "superset". Use "FLASK_APP=superset:name to specify one.`

and also `FLASK_APP=app` 
result: `Error: Could not import "app".`

**Comment by dpgaspar** [comment]
Hi,

@Haks1, I've just rebuilt the image and works great. 
Post the output of (from contrib/docker):

$ pwd
$ cat docker-init.sh
$ docker images
$ docker-compose run --rm superset ./docker-init.sh

**Comment by Haks1** [comment]
Hi @dpgaspar,

Thank you for your test, it confirms what I think of my problem, my docker (for windows via WSL) doesn't copy the superset folder as asked in the Dockerfile:
`COPY --chown=superset:superset superset superset`

When I do a `ls` of this folder in the `docker-init.sh`, I find only the `superset_config.py` mount.

It's not a superset bug, I suspect an access issue of my environment (WSL+Docker for windows), I close this ticket, I'll retry in a pure VM on Hyper-V.

Thanks again,
