### ISSUE TITLE
Related tables

### ISSUE THREAD

**Issue by asheem** [apache/incubator-superset#7715]
**Is your feature request related to a problem? Please describe.**
Would it be possible to join tables so that selections made in one or more fields displays possible values in related tables? 

**Describe the solution you'd like**
When fields are selected in related tables, resulting values are displayed in either tabular or chart format. 

**Describe alternatives you've considered**
Available in other data visualization tools. 

**Additional context**
Can be provided if required.

**Comment by mistercrunch** [comment]
The only way to do this at the moment is by using views as a datasource (where the view is making the join). We understand that there's performance impacts and in general we recommend denormalizing/materializing.

We may add support for joins in the future, where you could define many-to-one relationship to dimension tables (in the datasource editor) and define the join criteria there. Then the columns coming from these tables would show up under the "columns" tab. Presumably the SQL-generation logic would only join as needed.

**Comment by asheem** [comment]
Thanks! The ability to view results based on selected values in multiple tables would be very helpful.

**Comment by runningdata** [comment]
> The only way to do this at the moment is by using views as a datasource (where the view is making the join). We understand that there's performance impacts and in general we recommend denormalizing/materializing.
> 
> We may add support for joins in the future, where you could define many-to-one relationship to dimension tables (in the datasource editor) and define the join criteria there. Then the columns coming from these tables would show up under the "columns" tab. Presumably the SQL-generation logic would only join as needed.

So what's the plan?
