### ISSUE TITLE
AttributeError: type object 'dict' has no attribute 'import_obj'

### ISSUE THREAD

**Issue by bivav** [apache/incubator-superset#7727]
I exported Dashboard that was created using Druid Datasource. When I try to import it again I get the following AttributeError.

### Expected results

Supposed to import dashboard. 

### Actual results

`AttributeError: type object 'dict' has no attribute 'import_obj'`

#### Screenshots

![Error](https://user-images.githubusercontent.com/7812911/59703790-4ec64d80-9218-11e9-865f-94ec6d408930.png)

#### How to reproduce the bug

1. Go to Manage in the Menu
2. Click on Import Dashboard
3. Select the exported dashboard created using Druid Datasource
4. Upload and see error

### Environment

- superset version: `0.28.1`
- python version: `3.7.3`
- node.js version: `12.4.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x ]  It works with csv files but doesn't work with druid datasource dashboards.
- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I have found similar but not related to druid datasource.

**Comment by syazwan0913** [comment]
@mistercrunch any fix?

**Comment by Mastimind** [comment]
I have found a workaround, I'm connected to druid cluster . By seeing the dashboard json I have to import I have edited my druid cluster verbose and cluster_name in my superset configuration. Then I have made data sources section in json file empty and then tried to upload. It got uploaded and im able to see the imported dashboard

**Comment by syazwan0913** [comment]
@Mastimind so you export the dashboard created using druid datasources and edit the exported json file?

**Comment by Mastimind** [comment]
Yes I have edited the exported json file.
Catch here is if you are using the same druid cluster and name given to druid data source in your superset portal are same then just editing the data source section in exported json is enough

**Comment by syazwan0913** [comment]
Also I need to edit the datasource id right? Let say on json file of imported superset A have datasource id : 3, but the druid data source on superset B with same druid cluster in superset A, the datasource id is 5. So I need to edit data source id in json file to 5 right?

**Comment by Mastimind** [comment]
That's right if the data source name of in superset is different then you have to edit those setting as well...

**Comment by Mastimind** [comment]
That's right if the data source name of in superset is different then you have to edit those setting as well...

**Comment by syazwan0913** [comment]
I tried to change datesource_name, datsource_id but the problem still exists
