### ISSUE TITLE
drilldown feature

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#7732]
In the feature list, it is saying that it has drilldown capability. But when we explore Superset we couldn't find this feature. Any explanation appreciated.

Easy, code-free, user flows to drill down and slice and dice the data underlying exposed dashboards. The dashboards and charts acts as a starting point for deeper analysis.

Make sure these boxes are checked before submitting your issue - thank you!

[ *] I have checked the superset logs for python stacktraces and included it here as text if there are any.
 I have reproduced the issue with at least the latest released version of superset.
[ *] I have checked the issue tracker for the same issue and I haven't found one similar.
Superset version
0.29.0rc8

Expected results
Drill down feature available

Actual results
Can't find this feature

Steps to reproduce
Go to this URL and read the description/features
https://superset.incubator.apache.org/
https://pypi.org/project/superset/

**Comment by bipinsoniguavus** [comment]
Please have a look here:
https://github.com/apache/incubator-superset/issues/7512

**Comment by kalimuthu123** [comment]
can you please tell me in briefly

**Comment by buzzware** [comment]
This issue shouldn't be closed - the feature claim "Easy, code-free, user flows to drill down..." on the front page is misleading and should be removed.

**Comment by mikepollitt** [comment]
Agree, I can't find this functionality in the product as it stands today, does it exist?

**Comment by jhult** [comment]
Looks like it doesn't exist quite yet but is getting close with this PR: https://github.com/apache/superset/pull/14688

**Comment by cue-parashar** [comment]
Misleading info on the front-page, Issue should not be closed!
