### ISSUE TITLE
Export csv  AttributeError: 'NoneType' object has no attribute 'index'

### ISSUE THREAD

**Issue by bjtthao** [apache/incubator-superset#7734]
### Expected results

Successfully export CSV data

### Actual results

AttributeError: 'NoneType' object has no attribute 'index'
After re-login, it can be exported normally.

#### Screenshots

 
![image](https://user-images.githubusercontent.com/50398273/59754466-bdf37e80-92b8-11e9-9656-c1946ba83a9f.png)

 
#### How to reproduce the bug

 Click on dashboard 
Click on Export csv 

### Environment
 
- superset version:  0.24
- python version: 3.5.5
- node.js version: 0.10.48
- npm version: 1.3.6

**Comment by sandy-ha** [comment]
I have the same Problem.

**Comment by jerwen** [comment]
I'd like to reopen this issue because it's still happening on Export CSV for filter box
