### ISSUE TITLE
Custom OAuth issue

### ISSUE THREAD

**Issue by victortony** [apache/incubator-superset#7739]
hi, i configure my oauth login according to http://superset.apache.org/installation.html#custom-oauth2-configuration.  Everything is right, but it turns wrong when the code runs at "oauth_authorized" method in views.py. The problem is all the args in functions "redirect" may be wrong, such as "redirect("login")", "redirect(next_url)". I think it would be "redirect(self.appbuilder.get_url_for_login)". And another question is the value of  "nex_url" which is empty, and the correct value maybe "/superset/welcome". Would you please help me to solve this problem? Thank you.

### Expected results
When success, rediect to "/superset/welcome".Otherwise, redirect to "self.appbuilder.get_url_for_login".
what you expected to happen.

### Actual results
When success/failed, rediect to "/oauth-authorized/login"
what actually happens.

### Environment

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `3.6.6`

### How to reproduce the bug
click oauth login

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

2019-06-20 10:00:39,487:INFO:werkzeug:127.0.0.1 - - [20/Jun/2019 10:00:39] "GET /oauth-authorized/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/src/superset/superset/venv/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'

**Comment by victortony** [comment]
my config is :
` {'name': 'egaSSO',
     'token_key': 'access_token',  # Name of the token in the response of access_token_url
     'icon': 'fa-address-card',  # Icon for the provider
     'remote_app': {
         'consumer_key': 'xxxx',  # Client Id (Identify Superset application)
         'consumer_secret': 'xxxx',  # Secret for this Client Id (Identify Superset application)
         'request_token_params': {
             'scope': 'read'  # Scope for the Authorization
         },
         'access_token_method': 'POST',  # HTTP Method to call access_token_url
         'access_token_params': {  # Additional parameters for calls to access_token_url
             'client_id': 'xxxx'
         },
         'access_token_headers': {  # Additional headers for calls to access_token_url
             'Authorization': 'Basic Base64EncodedClientIdAndSecret'
         },
         'base_url': 'xxx',            
         'access_token_url': 'xxx',
         'authorize_url': 'xxxx'
     }
   }`

and 
`from superset.security import SupersetSecurityManager
import logging
class CustomSsoSecurityManager(SupersetSecurityManager):
    logger = logging.getLogger("CustomSsoSecurityManager")
    def oauth_user_info(self, provider, response=None):
        if provider == 'egaSSO':
            # As example, this line request a GET to base_url + '/' + userDetails with Bearer  Authentication,
    # and expects that authorization server checks the token, and response with user details
            me = self.appbuilder.sm.oauth_remotes[provider].get('/oauth2.0/profile').data
            arrs = me['attributes']
            email = ""
            for obj in arrs:
                if 'email' in obj:
                    email = obj['email']

            logging.debug("user_data: {0}".format(me))
            retObj = { 'name' : me['id'], 'email' : email, 'username' : me['id'], 'first_name':me['id'], 'last_name':me['id']}
            logging.debug("obj1:{0}".format(retObj))
            return retObj`

**Comment by colax94** [comment]
I have the same issue after upgrading to 0.28.1, please help

**Comment by jtzl** [comment]
Same here, also 0.28.1. Also please help :)

Sorry, something went wrong
500 - Internal Server Error
Stacktrace
         Traceback (most recent call last):
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/superset/venv/lib64/python3.6/dist-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'

**Comment by ali-bahjati** [comment]
I'm facing same issue after updating my superset (last version was from more than a month ago)

**Comment by ericandrewmeadows** [comment]
OAuth is working properly on v0.33.0rc1.  Have you tried?

**Comment by squalou** [comment]
Juste tried 0.34 rc : facing the same issue.
(used to work fine with 0.28)

**Comment by squalou** [comment]
Note : I did a quick and really dirty as I'm running all this in a docker container.
I changed /usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py

around line 677

- hardcoded 'provider' to 'google'  (its value is 'login' which is what causes the KeyError)
- hardcoded next_url to "/superset/welcome"

Does the job until something better fixes it.

**Comment by paulvic** [comment]
I'm seeing this too on 0.33.0rc1. I did a little digging today and found this PR https://github.com/dpgaspar/Flask-AppBuilder/pull/910 which introduced redirects after login. I noticed that the `next` value on the login screen is set as follows:

**Comment by squalou** [comment]
Sorry but, I just tested master branch, and problem still exists.

Could someone confirm it's fixed or not, and maybe reopen this issue  ?

I may be missing something , but I'm still getting 

```        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'```

**Comment by thunter009** [comment]
Experiencing the same issue even after the FAB upgrade to 2.1.13. Seems like an issue on the FAB side.

**Comment by thunter009** [comment]
> I've seen a few comments here suggesting the fix didn't work for them. I don't see them any longer so hopefully they were just config/setup problems. It would great if anyone could give this a comment a 👍 or just add a comment if they've confirmed the issue is now resolved.
> 
> Thanks!

I deleted my comment because I was able to get it working. It seems like the change added a new issue of re-directing `/users/list` and `/registeruser/list` to the oauth login endpoint for some reason. I will open an issue in the FAB repo after a bit further investigation.

**Comment by tomklapka** [comment]
I'm getting the same error, using https://github.com/apache/incubator-superset/commit/c566141f251ab8b59449428bf92f21fc20e45858

Sorry, something went wrong
500 - Internal Server Error
Stacktrace
        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'


```python
#Gitlab oauth2 configuration.
from flask_appbuilder.security.manager import AUTH_OAUTH
from custom_sso_security_manager import CustomSsoSecurityManager
CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
CSRF_ENABLED = True
AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Public'
OAUTH_PROVIDERS = [{
       'name': 'gitlab',
       'icon': 'fa-gitlab',
       'token_key': get_env_variable('GITLAB_TOKEN_KEY'),
       'remote_app': {
               'base_url': 'https://gitlab.com/api/v4/user',
               'request_token_params': {
                       'scope': 'openid read_user'
               },
               'access_token_url': 'https://gitlab.com/oauth/token',
               'authorize_url': 'https://gitlab.com/oauth/authorize',
               'request_token_method': 'GET',
               'access_token_method': 'POST',
               'consumer_key': get_env_variable('GITLAB_CONSUMER_KEY'),
               'consumer_secret': get_env_variable('GITLAB_CONSUMER_SECRET')
       }
}]
```
Not 100% sure about this custom oauth user info with regard to gitlab:
```python
from superset.security import SupersetSecurityManager

class CustomSsoSecurityManager(SupersetSecurityManager):

    def oauth_user_info(self, provider, response=None):
        logging.debug("Oauth2 provider: {0}.".format(provider))
        if provider == 'gitlab':
            # As example, this line request a GET to base_url + '/' + userDetails with Bearer  Authentication,
            # and expects that authorization server checks the token, and response with user details
            me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
            logging.debug("user_data: {0}".format(me))
            return { 'name' : me['name'], 'email' : me['email'], 'id' : me['user_name'], 'username' : me['user_name'], 'first_name':'', 'last_name':''}
```

**Comment by sreedharmb** [comment]
I'm still getting this issue with the latest code in master

**Comment by amodig** [comment]
This issue seems to still exist. Just upgraded from 0.28.1 to 0.34.0.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'
```

The most relevant part of `superset_config.py`:
```
AUTH_TYPE = AUTH_OAUTH
AUTH_ROLE_PUBLIC = 'Public'
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Gamma'
CSRF_ENABLED = True
ENABLE_PROXY_FIX = True
PREFERRED_URL_SCHEME = 'https'
OAUTH_PROVIDERS = [
    {
       'name': 'google',
       'whitelist': ['@armadainteractive.com'],
       'icon': 'fa-google',
       'token_key': 'access_token',
       'remote_app': {
            'base_url': 'https://www.googleapis.com/oauth2/v2/',
            'request_token_params': {
              'scope': 'email profile'
            },
            'request_token_url': None,
            'access_token_url': 'https://accounts.google.com/o/oauth2/token',
            'authorize_url': 'https://accounts.google.com/o/oauth2/auth',
            'consumer_key': GOOGLE_OAUTH_KEY,
            'consumer_secret': GOOGLE_OAUTH_SECRET
        }
    }
]
```

**Comment by paulvic** [comment]
Just to be clear, the fix wasn't in the 0.34 release so you'll have to wait for the next release or deploy the latest source.

**Comment by amodig** [comment]
Sorry I wasn't clear. I bumped FAB to version `2.1.13` which didn't help. Was there any other commits to solve the issue?

There's also another login problem (maybe related?), the login redirects to http instead of https:
![superset_login_error](https://user-images.githubusercontent.com/1047344/65580857-21114300-df83-11e9-9142-2fae412b0ad7.png)

**Comment by tomklapka** [comment]
> Just to be clear, the fix wasn't in the 0.34 release so you'll have to wait for the next release or deploy the latest source.

We're running it from latest master and issue still persists...

**Comment by dpgaspar** [comment]
Hi just made a simple test on flask-appbuilder with google oauth and it worked fine, I would say that this is more of a flask-appbuilder question/issue so feel free to open an issue there.

The above error seems more of a configuration issue setting your google oauth credentials

**Comment by tomklapka** [comment]
Could you share with us your working configuration? Thanks

**Comment by amodig** [comment]
> The above error seems more of a configuration issue setting your google oauth credentials

Yeah, I know how it looks, but my Google OAuth config worked just fine with PyPI release 0.29.0rc7...

**Comment by dpgaspar** [comment]
@tomklapka, https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/oauth/config.py#L42

I've removed the twitter and azure definitions and exported google OAuth secrets to the required env vars. One more this is a flask-appbuilder issue/question, feel free to open an issue over there

**Comment by jackyq2015** [comment]
The same for master today:  ### 0.35.0 (2019/10/31 11:12 +00:00)
Stack trace:
```
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 677, in oauth_authorized
resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
```

**Comment by paulvic** [comment]
@jackyq2015 just want to be sure that the issue you're seeing is the same underlying problem as the one reported in this GH issue. 

Can you confirm that logging in at `https://<your_domain>/login/` results in a `KeyError: 'login'` error but logging in at `https://<your_domain>/login/?next=/superset/sqllab` does *not* result in an error.

**Comment by jackyq2015** [comment]
Yes. I saw the  KeyError: 'login' error but logging in at https://<your_domain>/login/?next=/superset/sqllab does not result in an error. I am using the docker come with the git(on top try to add the oauth)

**Comment by paulvic** [comment]
And you definitely have Flask_AppBuilder 2.1.13 in `/usr/local/lib/python3.6/site-packages/` in the container? If so, then I'm out of ideas as I can't repro.

**Comment by jackyq2015** [comment]
Yes. I am sure:
```
root@36259bfbf85e:/home/superset# ls /usr/local/lib/python3.6/site-packages/Flask* -d
/usr/local/lib/python3.6/site-packages/Flask-1.1.1.dist-info                /usr/local/lib/python3.6/site-packages/Flask_Login-0.4.1.dist-info
/usr/local/lib/python3.6/site-packages/Flask_AppBuilder-2.1.13.dist-info    /usr/local/lib/python3.6/site-packages/Flask_Migrate-2.5.2.dist-info
/usr/local/lib/python3.6/site-packages/Flask_Babel-0.12.2.dist-info         /usr/local/lib/python3.6/site-packages/Flask_OAuthlib-0.9.5.dist-info
/usr/local/lib/python3.6/site-packages/Flask_Caching-1.7.2.dist-info        /usr/local/lib/python3.6/site-packages/Flask_OpenID-1.2.5.dist-info
/usr/local/lib/python3.6/site-packages/Flask_Compress-1.4.0.dist-info       /usr/local/lib/python3.6/site-packages/Flask_SQLAlchemy-2.4.0.dist-info
/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.7.dist-info           /usr/local/lib/python3.6/site-packages/Flask_WTF-0.14.2.dist-info
/usr/local/lib/python3.6/site-packages/Flask_JWT_Extended-3.20.0.dist-info
root@36259bfbf85e:/home/superset# ls /usr/local/lib/python3.6/site-packages/Flask_AppBuilder* -d
/usr/local/lib/python3.6/site-packages/Flask_AppBuilder-2.1.13.dist-info
root@36259bfbf85e:/home/superset# uname -a
Linux 36259bfbf85e 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 GNU/Linux
root@36259bfbf85e:/home/superset# ^C
root@36259bfbf85e:/home/superset#
```

**Comment by vivekpradhan** [comment]
I ran into this issue. The problem was a typo. I had this:
```
OAUTH_PROVIDERS = [
    {
        'name': 'Google',
        ...
}
]
```
instead of this:
```
OAUTH_PROVIDERS = [
    {
        'name': 'google',
        ...
}
]
```
Hope this helps someone.

**Comment by intostern** [comment]
`AUTH_USER_REGISTRATION = True` 
solved the issue. 
In fact, after you sign in with your google account, a new record added to ab_user table.

**Comment by vikramsinghchandel** [comment]
> > I've seen a few comments here suggesting the fix didn't work for them. I don't see them any longer so hopefully they were just config/setup problems. It would great if anyone could give this a comment a 👍 or just add a comment if they've confirmed the issue is now resolved.
> > Thanks!
> 
> I deleted my comment because I was able to get it working. It seems like the change added a new issue of re-directing `/users/list` and `/registeruser/list` to the oauth login endpoint for some reason. I will open an issue in the FAB repo after a bit further investigation.

Were you able to find a solution for /user/list redirection issue

**Comment by ghosalya** [comment]
I ran into this issue when I had the following OAuth config:
```
base_url="https://www.google.com/accounts/"
```

After I changed to the following, I no longer have this issue:
```
base_url="https://www.googleapis.com/oauth2/v2/"
```

**Comment by manmeetkaur-kin** [comment]
@intostern could you please advise how you set the SQLALCHEMY_DATABASE_URI ? We are on airflow 1.10.10 and trying to integrate Google OAUTH and RBAC. Google login is working but everytime we click on DAGs or Profile, it logs out and again brings to login screen. And there is no entry in ab_user table. Webserver logs say that SQLALCHEMY_DATABASE_URI is not set! I tried to set in webserver_config.py but still same WARNING message.

**Comment by parth-pb** [comment]
I am unable to log in to Apache Superset using Microsoft Azure AD. Here is my configuration. I am also able to see the Microsoft login page, but when I submit the button, Superset throws an error: 'Invalid login. Please try again

```
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
{
    "name": "azure",
    "icon": "fa-windows",
    "token_key": "access_token",
    "remote_app": {
        "client_id": os.environ.get("CLIENT_ID", ""),
        "client_secret": os.environ.get("CLIENT_SECRET", ""),
        "api_base_url": os.environ.get("API_BASE_URL", ""),
        "client_kwargs": {
            "scope": "User.read name preferred_username email profile upn",
            "resource": "client_id",
        },
        "request_token_url": None,
        "access_token_url": os.environ.get("ACCESS_TOKEN_URL", ""),
        "authorize_url": os.environ.get("AUTHORIZE_URL", ""),
    },

},
]
```
