### ISSUE TITLE
Which the version of the nodejs and npm？

### ISSUE THREAD

**Issue by shaohk** [apache/incubator-superset#7746]
Hi：
   Which the version of the nodejs and npm？I used the node version v8.16.0 on windows, and i want to build the superset ui. But there are some ERROR when i try to exec 'npm install'.

**Comment by mistercrunch** [comment]
Windows is not supported. Anecdotally I'm on node `v12.1.0`

**Comment by shaohk** [comment]
> Windows is not supported. Anecdotally I'm on node `v12.1.0`

thks!
