### ISSUE TITLE
Where is the project's route?

### ISSUE THREAD

**Issue by shaohk** [apache/incubator-superset#7760]
HI
    I want to develop the project by myself,but I didn't found the URL route. And       how the react model called by python.
Thks!

**Comment by zhaoyongjie** [comment]
@shaohk please use flask command, query project routers use here command
```
flask routes
or
superset routes
```
code can find out ``superset/views`` dir

**Comment by shaohk** [comment]
> @shaohk please use flask command, query project routers use here command
> 
> ```
> flask routes
> or
> superset routes
> ```
> 
> code can find out `superset/views` dir

thank u very mach!
but there is nothing of the command.

![image](https://user-images.githubusercontent.com/16531687/59999944-cc191480-9695-11e9-9c6a-0a632b57f9b9.png)

**Comment by zhaoyongjie** [comment]
@shaohk you should install superset dependency before, 
```
## in virtualenvs
pip install requirements.txt
superset routes
```
