### ISSUE TITLE
Cannot enable anonymous users to view dashboards

### ISSUE THREAD

**Issue by ecamellini** [apache/incubator-superset#7763]
I have a dashboard that I want to share publicly. I followed the related steps from the documentation, also linked in https://github.com/apache/incubator-superset/issues/4102:
https://superset.incubator.apache.org/security.html#public

Specifically, what I did was:
1. Set `PUBLIC_ROLE_LIKE_GAMMA = True` in `superset_config.py`
2. Added `datasource access` permissions to the `Public` role, for the datasource from where data in the dashboard is retrieved

### Expected results

Anonymous (i.e., not logged in) users shall be able to see the dashboard by opening its URL in a web browser.

### Actual results

Anonymous (i.e., not logged in) users are not able to see the dashboard by opening its URL in a web browser: they are redirected to the login page showing an `Access Denied` error.

I also tried to add some more permissions to the `Public` user (see screenshots) and managed to display the dashboard, but not the charts in it. However I don't think it's the right way to do it, it should work as documented.

#### Screenshots

Access denied error:
![image](https://user-images.githubusercontent.com/6418684/60006878-8c403600-9671-11e9-8b4f-9d4f733235da.png)

Permissions that I tried to add to `Public`, together with the datasource access:
![image](https://user-images.githubusercontent.com/6418684/60006584-09b77680-9671-11e9-9b6b-f56924607f2a.png)

What I saw after adding such permissions:
<img width="1909" alt="Screenshot 2019-06-24 at 11 21 06 1" src="https://user-images.githubusercontent.com/6418684/60007369-754e1380-9672-11e9-9532-2cc16ddce098.png">

### Environment

- superset version: built from `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi,

Can you please post a **text** list with all the permissions included on the `Public` role?

**Comment by yahwang** [comment]
In my case...

After Setting PUBLIC_ROLE_LIKE_GAMMA = True in superset_config.py,  
execute " superset init  " command.

Then public roles may be changed like this

![screenshot_8](https://user-images.githubusercontent.com/12381530/60205674-c5a0bd80-988c-11e9-992e-080ce58c5939.png)

Finally, ADD permissions to Public according to your database LIKE THIS.

![screenshot_7](https://user-images.githubusercontent.com/12381530/60205806-17e1de80-988d-11e9-9726-17fcc21dca7c.png)

THEN WORK!!

**Comment by yahwang** [comment]
@ecamellini In my case, 
I could read dashboard with 6 permissions

datasource permission should indicate table

but my version is 0.28.1... may be different from master 

reference : https://stackoverflow.com/questions/50295010/is-there-a-way-to-create-read-only-dashboard-in-apache-superset
![screenshot_6](https://user-images.githubusercontent.com/12381530/60267752-e79a4e80-9925-11e9-91cc-337556ed6196.png)

**Comment by ecamellini** [comment]
I think I managed to solve the issue: for `PUBLIC_ROLE_LIKE_GAMMA = True` to take effect I had to re-launch `superset_init.sh`, and now `Public` actually has all the gamma permissions and adding the datasource access is sufficient to make the dashboard visible publicly.

If someone can confirm that this is the right way to do it, I'll update the documentation accordingly.

**Comment by LeonanCarvalho** [comment]
`[can dashboard on Superset, can explorev2 on Superset, can explore json on Superset, can csrf token on Superset, can csv on Superset, menu access on Dashboards, all datasource access on all_datasource_access, all database access on all_database_access, can list on DashboardModelViewAsync, can list on DashboardModelView]`

You just need to replace all_database_access and all_datasource_access for the public datasource and database.

**Comment by trepmag** [comment]
I followed the instruction in the link mentioned above (https://superset.apache.org/security.html#public) and now the `public` role is filled with the same permission as the Gamma one plus all the `datasource`. But still, the system return "Access is Denied"!

**Comment by Porthos81** [comment]
> I followed the instruction in the link mentioned above (https://superset.apache.org/security.html#public) and now the `public` role is filled with the same permission as the Gamma one plus all the `datasource`. But still, the system return "Access is Denied"!

Hi, did you solve this issue??? I have the same problem, and I don't know how to fix it

**Comment by Porthos81** [comment]
@trepmag  Did you solve this issue??? I have the very same problem and I don't know how to fix it...

**Comment by Green-Angry-Bird** [comment]
@trepmag @Porthos81 Same issue here. How did you resolve?

**Comment by ecamellini** [comment]
@Porthos81 @Green-Angry-Bird if I remember correctly, what worked for me is what I described in this comment above: https://github.com/apache/incubator-superset/issues/7763#issuecomment-506656337 

Re-running `superset_init.sh` after performing the changes described in the issue resulted in the permission change to actually happen.

**Comment by Green-Angry-Bird** [comment]
To follow up on this, I was able to get this working.

I had to enable a bunch of permission on Public role, specifically:
`[all datasource access on all_datasource_access, all database access on all_database_access, can explore json on Superset, can explore on Superset, can csrf token on Superset, can dashboard on Superset, can explorev2 on Superset, can fave dashboards on Superset, can fave dashboards by username on Superset, can favstar on Superset, can fave slices on Superset, can show on CssTemplateModelView, can download on CssTemplateModelView, can delete on CssTemplateModelView, can list on CssTemplateModelView, can add on CssTemplateModelView, can edit on CssTemplateModelView, muldelete on CssTemplateModelView, can show on CssTemplateAsyncModelView, can download on CssTemplateAsyncModelView, can delete on CssTemplateAsyncModelView, can list on CssTemplateAsyncModelView, can add on CssTemplateAsyncModelView, can edit on CssTemplateAsyncModelView, muldelete on CssTemplateAsyncModelView, menu access on CSS Templates]`

**Comment by ecamellini** [comment]
Yep, I think you did manually what happens by doing this: https://github.com/apache/incubator-superset/issues/7763#issuecomment-635843718

In the and, this just adds permissions from Gamma to the Public group.

Glad you solved it ;)

**Comment by trepmag** [comment]
@Porthos81 @Green-Angry-Bird I re-runned `superset-init` as mentioned by @ecamellini and finally the related dashboard/charrt were accessible...

**Comment by tingkai-zhang** [comment]
Hi, can anyone tell me where is `superset_init.sh`?
I start the superset by 
```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset

docker-compose up
```
The superset is up. 
Then, where should I execute the `superset_init.sh` and where should I create `superset_config.py`?

**Comment by romeokienzler** [comment]
I've got a working version now using the documentation posted above [https://superset.apache.org/security.html#public](https://superset.apache.org/security.html#public
)

before executing `docker-compose up` just edit the file ./docker/pythonpath_dev/superset_config.py as described in the link above

for me the file then looks like

> ...
> DATABASE_DIALECT = get_env_variable("DATABASE_DIALECT")
> DATABASE_USER = get_env_variable("DATABASE_USER")
> DATABASE_PASSWORD = get_env_variable("DATABASE_PASSWORD")
> DATABASE_HOST = get_env_variable("DATABASE_HOST")
> DATABASE_PORT = get_env_variable("DATABASE_PORT")
> DATABASE_DB = get_env_variable("DATABASE_DB")
> PUBLIC_ROLE_LIKE_GAMMA = True
> 
> SQLALCHEMY_DATABASE_URI = "%s://%s:%s@%s:%s/%s" % (
>     DATABASE_DIALECT,
>     DATABASE_USER,
>     DATABASE_PASSWORD,
>     DATABASE_HOST,
>     DATABASE_PORT,
>     DATABASE_DB,
> )
> ...

Then you can fire `docker-compose up`

And yes, you need to add permissions to the "public" role, otherwise the dashboards are not shown

**Comment by fccoelho** [comment]
Could someone update the needed permissions on version 1.2? I upgraded, and my public role users can no longer view dashboards.

**Comment by akelai** [comment]
> What worked for me in the end, was to move to the latest release, 1.3 (I guess), running
> 
> ```shell
> superset update db
> superset init 
> ```
> 
> and the permissions got fixed.

I believe you mean "`superset db upgrade`" (not "`superset update db`").

**Comment by fccoelho** [comment]
> > What worked for me in the end, was to move to the latest release, 1.3 (I guess), running
> > ```shell
> > superset update db
> > superset init 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the permissions got fixed.
> 
> I believe you mean "`superset db upgrade`" (not "`superset update db`").

Yes. sorry for the confusion.

**Comment by jinyangzhen** [comment]
In my case (v2.0 + k8s deployment from superset helm), rerun 

Add 

`        PUBLIC_ROLE_LIKE = "Gamma" `

to superset_config.py
and rerun in superset pod
`       superset init `
works for me.

**Comment by JakobMiksch** [comment]
this docs are useful https://dev.joget.org/community/display/marketplace/Apache+Superset+Userview+Menu+Plugin#ApacheSupersetUserviewMenuPlugin-ConfigureAllDashboardtobePublic
but it still did not work for me

**Comment by Habeeb556** [comment]
I would like to point out a security concern: granting the `Gamma` role the same privileges as the `Public` role.

You no longer need to set `PUBLIC_ROLE_LIKE = 'Gamma'`. Go with the [Joget documentation](https://dev.joget.org/community/display/marketplace/Apache+Superset+Userview+Menu+Plugin#ApacheSupersetUserviewMenuPlugin-ConfigureAllDashboardtobePublic) and add the following permissions to be working:

- `can read DashboardPermalinkRestApi`
- `can dashboard permalink on Superset`

Also, no need to `superset init` as this will reset all permissions on `Gamma`, `Alpha`, `sql_lab`, `Admin` if you have custom it before.

**Superset version:** `4.1.1`

**Comment by diraneyya** [comment]
@Habeeb556 Hey Ahmed I would like to wholeheartedly thank you for the comment you added to this thread, I found it to be incredibly helpful for multiple reasons. One reason I want to talk about is that it paid my attention to Joget, a truly interesting project that is very similar to what I have been looking for, for months now. The fact it integrates with Apache Superset via an open-source plugin is also crucially what I needed for a prototype I am building so thank you.

One more thing which many people might not realise (myself included), is that after adding all the permissions as indicated by the article linked by @Habeeb556, there is still one trivial step that one must do in order to allow the dashboard to appear on user's dashboard after granting them the permissions via the custom role created.

This trivial, though important step, is to "publish" the dashboard. This got me scratching my head for hours. Just click edit the dashboard and then click the draft field to publish the dashboard:

<img width="1508" alt="Image" src="https://github.com/user-attachments/assets/066c5c46-254b-4dbb-9aa1-d6882b433060" />
