### ISSUE TITLE
Create a column that is editable by user via a dashboard

### ISSUE THREAD

**Issue by bzeeeb** [apache/incubator-superset#7766]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to create a column users could edit in a dashboard based on the data contained within the other columns, which could then be updated in the database itself.  

Example: they could approve / reject the data in the dashboard.  

Is this possible today in superset?

**Describe alternatives you've considered**
None

**Additional context**

**Comment by bzeeeb** [comment]
Actually I found this post about a similar feature, doesn't look like its on your roadmap.

Can we pass a clickable URL into a column?  We could simulate the approve reject function that way as well.

**Comment by ericandrewmeadows** [comment]
@bzeeeb - can you not create a view that using SQL Lab that accomplishes this?

**Comment by aristeidismoustakas** [comment]
@ericandrewmeadows could you give some more details about what you mean when you are saying "create a view that using SQL Lab"?
