### ISSUE TITLE
Superset Upgrade and Dashboard Migration Procedure Recommendations

### ISSUE THREAD

**Issue by smokemonster99** [apache/incubator-superset#7771]
Hi,
We need to upgrade from 0.26.3 to 0.33.0 and have built many dashboards on 0.26.3.

Is the recommended procedure the following (of course using https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization instructions)?

1. upgrade to 0.27.0, run superset db upgrade
2. upgrade to 0.28.0 (python 3.6 required), run superset db upgrade
3. upgrade to 0.29rc7, run superset db upgrade
4. No 0.30.x 'release'...do not know what to do here!!
5. upgrade to 0.31rc18, run superset db upgrade
6. upgrade to 0.32.rc2, run superset db upgrade
7. upgrade to 0.33.0, run superset db upgrade

i.e. does the superset db upgrade only take you from the prior release? Or can I go straight from 0.26.3 to 0.33.0 and run 'superset db upgrade' and it can handle the jump in releases?

If I have to go release by release, there is no 0.30 release so I am confused here. (ref https://github.com/apache/incubator-superset/releases)

Also, FYI - I am aware of https://github.com/apache/incubator-superset/blob/master/UPDATING.md and am taking that into consideration, my question is more procedural.

thanks!

**Comment by dpgaspar** [comment]
Hi,

Yes the migration procedure will take you directly to your current release, and apply all steps needed.
Yet while reading the `UPDATING.md` you should probably be careful on 0.27 and 0.28 regarding the dashboards, although the migration procedures is automatic and done by `db migration`.

Has always minimal procedures should be: test and validate on staging env, and always take a previous backup of the db.

**Comment by smokemonster99** [comment]
Thanks for the response @dpgaspar this will save me a lot of time. I am doing a side by side so will be able to do thorough testing.
