### ISSUE TITLE
bokeh seaborn charts  python embedding

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#7774]
**Is your feature request related to a problem? Please describe.**
bokeh charts are needed to embed 
**Describe the solution you'd like**
seaborn charts are needed to  join

**Describe alternatives you've considered**
opensource libraries of python are needed to fix inside 

**Additional context**
bokeh seaborn matplotlib featurse to added inside superset

**Comment by ericandrewmeadows** [comment]
@kalimuthu123 - can you point out missing visualizations that are not present in https://github.com/d3/d3/wiki/gallery - every visualization here should be usable in Superset.

**Comment by kalimuthu123** [comment]
@ericandrewmeadows hi i am trying the python scripts and r scripts for visualisation
