### ISSUE TITLE
Extra Controls || Area Chart || Visualisation Chart

### ISSUE THREAD

**Issue by rohanagg** [apache/incubator-superset#7779]
When we check extra control features in Area Graph, switch from expanded to stacked or stacked to expanded, Y-axis doesn't align accordingly which results in No Graph

### Expected results
Y-axis should align accordingly

### Actual results
Y-axis is not aligned when switched from expanded to stacked or vice-versa

#### Screenshots

![superset_area_graph_original](https://user-images.githubusercontent.com/30650330/60162183-a109fe80-9816-11e9-80a3-0c7dbd437d1e.PNG)
![superset_area_graph_issue](https://user-images.githubusercontent.com/30650330/60162188-a404ef00-9816-11e9-8cf2-0fa1cb27fbd9.PNG)

#### How to reproduce the bug

1. Go to Slice 
2. Click on Area Graph, select date, dimension and metrics, please tick the extra controls feature
3. By default, let say Area Graph is on Stacked mode
4. Click on the expanded section in extra controls
5. See the error

### Environment

(please complete the following information):

- superset version: `0.32.0rc1`
- python version: `python --3.6.7`
- node.js version: `node -v11.14.0`
- npm version: `npm -6.7.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- 

- [ ]  I have checked the superset logs for python stacktraces and included it here as text if there are any.

- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by aboganas** [comment]
can confirm the bug

**Comment by rohanagg** [comment]
any update here, as this is hampering the business in one or other form

**Comment by mistercrunch** [comment]
I think this is fixed in `master`. Visual evidence of it working:

<img width="1659" alt="Screen Shot 2019-07-28 at 10 22 12 PM" src="https://user-images.githubusercontent.com/487433/62023533-2cfca680-b186-11e9-8969-a6baf0fd9222.png">

**Comment by srikanth-reddy-m** [comment]
Verified with master code. still not working.
