### ISSUE TITLE
Need to embed superset dashboard in iframe..

### ISSUE THREAD

**Issue by yashica-yashu** [apache/incubator-superset#7780]
im very new to superset and python.
i need to embed superset into my application. 
i tried using iframe.
just tried a basic html code for sample.
 
<html>
<head>
<title>demo</title>
</head>
<body>
<iframe
  width="1600"
  height="1600"
  seamless
  frameBorder="0"
  scrolling="yes"
  src="http://192.168.xx.xxx:8088/superset/dashboard/world_health/">
</iframe>
</body>
</html>

I'm getting the error as - refused to connect.

i did change the following in config.py file in c:\incubator-superset\superset loaction.
ENABLE_CORS = True 
HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'} 

still no change.
also i added a pythonpath in the environment variable. 

PYTHONPATH - C:\incubator-superset\superset\config.py

still not able to view the page..

pls provide your inputs.

**Comment by kalimuthu123** [comment]
For Cross-Origin Resource Sharing (CORS) problem use the both application in https
