### ISSUE TITLE
Filterbox spinner stays active when clearing filters

### ISSUE THREAD

**Issue by villebro** [apache/incubator-superset#7789]
After having selected filters on a Filterbox, clearing all filters should disable the spinner after everything clears. However, clearing all filters leaves the spinner active.

### Screenshots

![spinner](https://user-images.githubusercontent.com/33317356/60301311-b75cab00-9939-11e9-9abf-7747e8e17a75.gif)

#### How to reproduce the bug

1. Add a Filterbox to a dashboard with at least one filter.
2. Choose one filter.
3. Clear all filters.
4. See the spinner stay active.

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@etr2460 @graceguo-supercat Are you able to reproduce this bug? I tried to check the filterbox sources, but was unsuccessful finding what's causing this behaviour. Any hints on where to look would be appreciated..

**Comment by villebro** [comment]
Not seeing this anymore in `master`, closing.

**Comment by graceguo-supercat** [comment]
@villebro I cannot reproduce this either. I would still keep an eye on it, please let me know next time you see it. thanks!
