### ISSUE TITLE
How to migrate superset in docker images, container and volume including all charts and dashboards into another host/machine?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7790]
### Expected results

Can migrate superset in docker including charts and dashboards into another machine

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `0.28.1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sebastianwindeck** [comment]
@syazwan0913 have you found a solution ?

--> I also want to change also from the pip versions to the docker image, but got the issues:
migrating the flask users and the charts and dashboards from the database

**Comment by syazwan0913** [comment]
@sebastianwindeck you just need to go to docker volume and copy postgres folder and transfer it to new volume. that's all.

**Comment by lrosenman** [comment]
Or point to an external PostgreSQL server :)

**Comment by sebastianwindeck** [comment]
@lrosenman  @syazwan0913  thanks for your replies. :)
