### ISSUE TITLE
Superset seems to be ignoring few frontend translations

### ISSUE THREAD

**Issue by NickStarlight** [apache/incubator-superset#7792]
Superset internationalization does not seem to be working on few components at the frontend.
The 'Add new slice' menu @ superset/assets/src/addSlice/AddSliceContainer.jsx is one example, even if the @superset-ui module has been called.

`import { t } from '@superset-ui/translation';`
`t('Choose a datasource')`

### Expected results

All UI elements should be translated.

### Actual results

Few frontend elements seem to ignore the translation, i couldn't reproduce the issue on backend rendered components like tables.

#### How to reproduce the bug

Download the current main branch, or 0.32.0rc2, haven't tested on other releases.

### Environment

(please complete the following information):

- superset version: 0.32.0rc2
- python version: 3.6
- node.js version: 12.0

### Checklist

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by NickStarlight** [comment]
Replicating the exact same code as descibred on [here](https://github.com/apache/incubator-superset/pull/5008#issuecomment-400260731), fixes the issue partially.

**Comment by mistercrunch** [comment]
Could it be that some of the translations have not been "compiled"?
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#creating-a-new-language-dictionary

**Comment by NickStarlight** [comment]
@mistercrunch No, they are just absent, even for existing languages, the add-slice-container itself has no translations being piped to the view, so it's an easy task(As described above), however, most parts of the code do not have translations mechanisms whatsoever.

1. Tables are using the [humanize](https://github.com/jmoiron/humanize) Python lib for human readable time frames(x days ago, x hours ago), i've managed to fix this by globally setting the language for humanize:

`humanize.i18n.activate('code', path='path/to/my/translation/')`

We do need to 'compile' new translations for all currently supported languages, since humanize is an abandonware.

2. Datetime on Python does not seem to print the localized dates, setting the locale globally with `locale.setlocale(locale.LC_ALL, 'i18n_code')` can lead to troubles, so more investigations on how properly do it on Superset is required.

3.  Moment.js also is absent of any internationalization, importing the locale in preamble.js does fix that.
`import locale from 'moment/locale/i18n_code';`


My use case is very specific(One single language support) so all measures above work, but unfortunatelly i can't open a PR with those changes since they do not match the code quality required on Superset and can lead to trouble in the future.
