### ISSUE TITLE
Official release is delayed for so long, how can community help development team?

### ISSUE THREAD

**Issue by kaitorecca** [apache/incubator-superset#7793]
If it's not confidential, can you give some issues that take time of development team in releasing new official version?  

Superset is a good product and many people want to maintain it :)

**Comment by NickStarlight** [comment]
0.33.0rc1 seems to be the last proposed release candidate.

https://lists.apache.org/thread.html/5ca9bef3454dfb14b0328b0303109e6bf9747c5d2c688b42939ff169@%3Cdev.superset.apache.org%3E

**Comment by cgivre** [comment]
I'll throw my name into the hat here... I'm on the PMC for Apache Drill, and would be willing to help organize the release process.

**Comment by mistercrunch** [comment]
0.34.0 is out! It's just not on Pypi yet though
