### ISSUE TITLE
How to auto refresh a chart without flashing?

### ISSUE THREAD

**Issue by Kiddinglife** [apache/incubator-superset#7794]
Hi folks,
I setup auto refresh interval to 5 seconds. 
but when refreshing, the chart flashes, dispearing and then appearing again.  
Is there a way to refresh a chart without flashing as Grafana does?
thanks.

**Comment by jaimee07** [comment]
Hi guys, any workaround for this? I dont want the flashing of charts whenever it refreshes too. 

Thanks.

**Comment by ktmud** [comment]
It depends on the chart. Some charts are more well-written and can update without re-render the whole chart, some cannot.

**Comment by maltoze** [comment]
@ktmud any examples?

**Comment by maltoze** [comment]
https://github.com/apache-superset/superset-ui/blob/93d7fb478b067d029a07d0733b7d48a4c348b4c3/plugins/plugin-chart-echarts/src/components/Echart.tsx#L51

It should be work by removing this line if using echarts.

**Comment by ktmud** [comment]
@villebro do you remember why echarts had to call `clear()` very time it re-renders?

**Comment by villebro** [comment]
It seems to be a regression caused by https://github.com/apache-superset/superset-ui/pull/1010 and appears to be necessary to refresh the selection. I'll see if I can remove `clear()` and implement the redraw some other way.

**Comment by villebro** [comment]
@ktmud @maltoze see https://github.com/apache-superset/superset-ui/pull/1044 for a fix to this problem.
