### ISSUE TITLE
Notify user if physical table is missing

### ISSUE THREAD

**Issue by khtruong** [apache/incubator-superset#7798]
**Describe the solution you'd like**
When a user goes to edit the datasource in a chart, we should 1) Point to a physical table if the chart is based off a query or 2) notify the user with a red bang and/or tooltip letting the user know the physical table is missing.

**Additional context**
<img width="377" alt="Screen Shot 2019-06-28 at 11 20 46 AM" src="https://user-images.githubusercontent.com/47833996/60363119-84490480-9997-11e9-85cc-acc8bf4d2c2a.png">

**Comment by ericandrewmeadows** [comment]
@khtruong - this seems valuable, but costly.  This could be a feature that is enabled on a per-database level, because you are issuing a query against the information schema of the given database during this request.  What are your thoughts?

**Comment by khtruong** [comment]
I think in general the experience needs to be improved. If the table is based off a query, then the UI states that the table is the query name. Second, if the table does not exist, then it silently fails. So anything to alleviate the confusion is a step in the right direction.
