### ISSUE TITLE
Docker installation error due to existing local Postgres instance on Port 5432

### ISSUE THREAD

**Issue by iamraybao** [apache/incubator-superset#7800]
### Expected results

I followed directions to install via `docker` here: https://superset.incubator.apache.org/installation.html#start-with-docker

### Actual results

I got the following error: 

```
> contrib/docker docker-compose run --rm superset ./docker-init.sh
Starting superset_redis_1    ... done
Starting superset_postgres_1 ... error

ERROR: for superset_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint superset_postgres_1 (3380fb75092993fee17b68c6e9a314defed16efb8fdbbe79fd02541462c46ff0): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint superset_postgres_1 (3380fb75092993fee17b68c6e9a314defed16efb8fdbbe79fd02541462c46ff0): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```

I have a local instance of `postgres` running that supports a `airflow` deployment. Thus, when I run `sudo lsof -i :5432`, I get the following output:

```
sudo lsof -i :5432
COMMAND    PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
postgres 25876 postgres    6u  IPv4 1437703      0t0  TCP localhost:postgresql (LISTEN)

```

I updated my `docker-compose.yml` file to this (per these instructions: https://stackoverflow.com/questions/55115080/how-to-specify-different-port-for-a-docker-postgres-instance):

```
< ... cut from above ... >

      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - "5444:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  superset:
    build:
      context: ../../
      dockerfile: contrib/docker/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # If using production, comment development volume below
      #SUPERSET_ENV: production
      SUPERSET_ENV: development

```

But I am still getting an error when I run `docker-compose run --rm superset ./docker-init.sh`

What am I doing wrong?

#### How to reproduce the bug

See above.

### Environment

(please complete the following information): N/A for installation

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X]  I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by raman325** [comment]
You changed the port that Postgres maps to outside of the container in the postgres container block, but in your superset container block, you are still referencing the old port when setting `POSTGRES_PORT`. Try updating that port to point to your new port (5344)

**Comment by raman325** [comment]
Just confirmed. If I were to redo this, I would:

- First update the docker-compose.yaml files in the two places (the one you referred to and the one I referred to)
- Next I'd run the initialization docker-compose command which would build the images, containers, and attempt to set up superset but fail
- Then I'd update `postgresql.conf` (I made this easy by changing the volume references to be on the host system so data could persist)
- Then I'd rerun the initialization docker-compose command which would succeed and finish setting up the DB
- Then I'd run `docker-compose up` and if I extracted all of the clean steps correctly out of my messy process I used to get to a running system, you should be good to go

**Comment by icoert** [comment]
You shoud find the PID of the process with the local address that you are looking for. 

> netstat -a -n -o

Then, it remains to kill the process.

> taskkill /F /PID <PID_NUMBER>

It's possible to not work without an administrative command prompt.

**Comment by jnthnvctr** [comment]
Hi - I'm running into this issue as well, not sure if I'm doing something totally insane. 

I'm trying to follow the instructions for setting up superset with some sample data using the steps provided in the tutorial. 

I locally installed postgres and have gotten all the weather data loaded per [this](https://github.com/dylburger/noaa-ghcn-weather-data). When I try running docker-compose up I get errors from superset saying the port is in use. 

I tried running @raman325 's steps, but still seem to have an issue. To confirm that I'm running the steps correctly: 
1) In the locally installed postgresql.conf I should uncomment and edit the port parameter to be 5344 ( or any number really). 

2) In the docker-compose.yml, I should edit the port parameter so the local port matches the number choice in (1). If I picked 5344 above, I use that as the first number here. The internal mapping number for docker (the second number should be 5342). 

3) If I had edited the second number to be something other than 5342, I should make sure the POSTGRES PORT parameter in the superset block is the same as the second number I've chosen. 

4) If I've done the above correctly, I should be able to have my local postgres running, as well as superset and connect the two, right?

**Comment by raman325** [comment]
For step 2, you need to use 5344 for the second number/port too. The second port is the container port, and by changing postgresql.conf, you've changed the port that postgres is listening to within the container.

The POSTGRES PORT in the superset block should be the same port as the first number, as that is the one exposed to the world (e.g. outside the container)

**Comment by mona-mk** [comment]
Trying to do what  @jnthnvctr is doing:
* weather db running locally on the default port 5432 (i.e. following these two tutorials: [weather-db](https://github.com/dylburger/noaa-ghcn-weather-data) & [superset-tutorial](https://superset.apache.org/docs/creating-charts-dashboards/first-dashboard)
* Running superset locally (& planning to connect the weather db to superset later)

The only change I made:
* in docker-compose.yml, changed the host port to sth else (here 5433 - see attached). Superset is now running locally fine, and connected fine also to the locally running weather db 

I am running superset version 0.38.0, and btw there is no more `POSTGRES_PORT` variable in current version, so no need for this step.
<img width="304" alt="Screenshot 2021-01-10 at 20 23 33" src="https://user-images.githubusercontent.com/59080347/104131903-3bdb1700-5382-11eb-8990-0e1899045ed7.png">
