### ISSUE TITLE
关于python3中celery不支持带中文的sql问题

### ISSUE THREAD

**Issue by pokyu** [apache/incubator-superset#7803]
在sqllab中，带中文就不能使用celery来查询，查询就处于pengding状态，请遇到过的朋友讲讲。
之前python2.7中是正常的，现在python3之后就不行了

**Comment by zhaoyongjie** [comment]
@chris, please show detail superset logs / celery logs

**Comment by pokyu** [comment]
就是没有日志中没有任何错误
there is no error in the logs;

**Comment by zhaoyongjie** [comment]
I can not reproduce this issue, SQLLab performs async querie normally in Chinese. I checked master branch

**Comment by cscainiao** [comment]
@pokyu 请问下在superset中怎么配置celery的呢
