### ISSUE TITLE
[Tagging] Save_as dashboard is very slow because of tagged_object table updates

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#7807]
In airbnb we have around 9000 dashboards and over 100,000 slices.

### Expected results

When user save_as a copy of a dashboard, the action should finish in a couple of seconds.

### Actual results

It took 90 seconds to copy a dashboard with 90+ slices.

#### Screenshots

When calling /copy_dash API, I found following db operation is very slow:
`SELECT tagged_object.id AS tagged_object_id 
FROM tagged_object INNER JOIN tag ON tag.id = tagged_object.tag_id 
WHERE tagged_object.object_type = 'chart' AND tagged_object.object_id = 150283 AND tag.type = 'owner' `

#### How to reproduce the bug

1. Create a large dashboard
2. Click `Save as` button from dashboard header dropdown menu
3. Choose `Save as`

### Environment

(please complete the following information):

- superset version: lastest 
- python version: Python 3.6.1
- node.js version: v10.15.3
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@betodealmeida

**Comment by mistercrunch** [comment]
Adding an index on `TaggedObject.object_id` should really help.

**Comment by michellethomas** [comment]
@mistercrunch @betodealmeida we have the tags feature turned off but this query is still executing, if this feature is behind a feature flag it should ideally not be affecting us. It's timing out when saving large dashboards, so some users are unable to save dashboards.

**Comment by michellethomas** [comment]
This is happening because of the event listeners [here](https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L1280) right? I don't know the feature very well, can we put these behind the feature flag and create a script in cli to update the tags tables if someone wants to turn the feature on in the future? @betodealmeida

**Comment by betodealmeida** [comment]
@michellethomas you're right. I'm working on a fix, sorry for the trouble.
