### ISSUE TITLE
Is it possible to change a React view file without having to rebuild?

### ISSUE THREAD

**Issue by sjmeyer** [apache/incubator-superset#7814]
I'm using superset 0.26.3

I want to add functionality to the Ajax calls made from the dashboard view. Can I simply add my change and replace the existing file, or do I have to rebuild with ```npm build```?

I have superset installed in a Docker container, just a simple ```pip install superset```. I want to add a ```COPY``` to the Dockerfile and replace the file I made changes to. IS this possible, or do I have to install node and npm and rebuild?

**Comment by mistercrunch** [comment]
`npm run dev` will continuously rebuild as you edit the files. More about it here:
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md
