### ISSUE TITLE
[Jinja] How render html from a postgres database?

### ISSUE THREAD

**Issue by bzeeeb** [apache/incubator-superset#7815]
**Is your feature request related to a problem? Please describe.**
I was trying SELECT '{{' || approve || '|safe}}' in SQL Lab where approve is the name of the column I want to make it display my anchor tag in safe html, but it just displays '|| approve ||'.  How do I do this properly via jinja in SQL Lab?  Is there a better way to?
https://superset.incubator.apache.org/sqllab.html

**Describe the solution you'd like**
Can we pass a clickable URL anchor tag into a column via jinja in SQL Lab?  

**Describe alternatives you've considered**
Editable columns, but found that wasn't on your roadmap.

**Additional context**
Using Superset version -0.29.0rc7

**Comment by bzeeeb** [comment]
Bump anyone know if this is possible?  Or a way to achieve what I am looking for (render html from postgres to appear in table in superset)

**Comment by mistercrunch** [comment]
I think the table visualization allows for this, meaning you can make it work in dashboards. You have to write a SQL expression like `CONCAT("<a href=\"http://superset.com\">", mycol, "</a>")`

**Comment by EwertonDCSilv** [comment]
Isso ainda funciona ?

**Comment by moksh-enf** [comment]
@mistercrunch Why does the Pivot table not allow the same?
