### ISSUE TITLE
How to run superset over https?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7823]
### Expected results

can run superset over https

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `0.28.1
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Yes, it's more about how you configure your web server (nginx, apache, gunicorn, ...) then about Superset itself. You can refer to the Flask or web server docs
