### ISSUE TITLE
How can I start a Superset web server rather than development server in this project?

### ISSUE THREAD

**Issue by Robinub** [apache/incubator-superset#7828]
Question : When I type superset --help , there is no option for "runserver " but only "run" . Who knows how to deal with it? Thank you ! #question

**Comment by mistercrunch** [comment]
https://apache-superset.readthedocs.io/en/latest/installation.html#a-proper-wsgi-http-server

**Comment by Demonya** [comment]
have you solved this?I get the same question like you.Hope you can help,Thanks a lot!

**Comment by Robinub** [comment]
> have you solved this?I get the same question like you.Hope you can help,Thanks a lot!

sorry , I just get your question.....the link above tells us the great way, you can run "gunicorn \
      -w 10 \
      -k gevent \
      --timeout 120 \
      -b  0.0.0.0:6666 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      --statsd-host localhost:8125 \
      superset:app",
