### ISSUE TITLE
Top 5 product on revenue basis issue in chart

### ISSUE THREAD

**Issue by saikannan** [apache/incubator-superset#7831]
**I am trying to display a chart with the Top 5 product on revenue basis in time series chart (apache superset). I can obtain this for a single month but when I try to display that for 3 months in the same chart it shows the Top 5 aggregated for all three months instead of the Top 5 for each month separately.

![top5](https://user-images.githubusercontent.com/39995393/60799130-32bb2980-a190-11e9-9cb8-a0d6596d5395.png)
![top5issue](https://user-images.githubusercontent.com/39995393/60799139-377fdd80-a190-11e9-88b4-3b45dca278e2.png)

In the first chart I got correct Top 5 in specialty whereas in the second chart I got the aggregate of those three months specialty. I want the specific Top 5 for every month.

How can I resolve this?

**

**Comment by amerinoo** [comment]
From my expercience, I think you should create 3 different charts and then in the dashboard put it together. You should have in account that the top 5 products may change in the 3 different charts as they are in 3 different periods.

**Comment by mistercrunch** [comment]
There's some SQL you can write to get to that exact result, probably using `UNION ALL` to union 3 different queries, one for each month. Each query will need some relative date filters.

You can create a VIEW in the database and use that as a datasource, or author in SQL Lab and follow the visualize flow. 

It's not super easy or intuitive, but it's doable.

**Comment by mistercrunch** [comment]
Oh and for context, the "Series Limit" concept works as intended, though it may be a bit confusing. That feature makes more sense in the context of the line chart itself, where you don't want to "break the lines" and see the whole time series for the OVERALL top entities. But I do understand that in the context of the bar chart time series, you expect something else...

**Comment by e3133d3** [comment]
What is the SQL query for the top 5 products?

**Comment by kalimuthu123** [comment]
this is the query i expected to do : 

the aim of the query is to display top 5 of every month 

select * from (SELECT Month , Revenue, City, Financial_Year, Financial_Quarter,InvoiceDate, dense_rank()
OVER ( partition by Month order by Revenue desc )
AS 'dense_rank' FROM table ) t where t.dense_rank<6
