### ISSUE TITLE
modify chart vizualisation in source code

### ISSUE THREAD

**Issue by lisa-bob** [apache/incubator-superset#7838]
Hello,
i am struggeling with the chart called "Word Cloud". As ist should (because of my query) it displays only one word. Like usually this "word cloud" positions the word randomly in a "white container". I would like to fix the position of the word 
Is there a way to edit the source code of charts, especially this chart, "word cloud"? If yes, where in the source code do I have to look for an answer?
Thanks for answers! 
Lisa

**Comment by derpepe** [comment]
I have this issue too.

Would prefer to see this as a bug report, because coloring as described in #2524 does not work.

**Comment by mistercrunch** [comment]
Source for visualization plugins are here:
https://github.com/apache-superset/superset-ui-plugins/tree/master/packages

You have to use `npm link` to do this. I think it may be documented here https://github.com/apache-superset/superset-ui-plugins#installation
