### ISSUE TITLE
deck.gl Multiple layers

### ISSUE THREAD

**Issue by milenioz** [apache/incubator-superset#7841]
I am m creating multiple layers map with 2 already created scatterplots.
Seem that the data is there, but cannot zoom in like in any other single layer map slice.
Even if I increase the default zoom, the map cannot be dragged.

![image](https://user-images.githubusercontent.com/37159591/60925511-976ba680-a2ac-11e9-9abb-3f6fc486887f.png)

**Comment by drunkenmyno** [comment]
There is stilla Bug inside which not refresh The Viewport im trying to to create a bounding box of the first or last layer and then refresh it but this viewport did not get used correctly :( any idea to fix?
