### ISSUE TITLE
logout is not working in superset

### ISSUE THREAD

**Issue by SeLvAKuMaR-007** [apache/incubator-superset#7846]
When i click logout option in dropdown i couldn't able to logout.  Again the same user dashboard was still i can able to see and the user was logged in. Session was not clearing while logout option click.

i have tried using localstorage.clear() was not working. any other way to make it work will be helpful thanks  

### Expected results
User should able to logout.

### Actual results
User once logged in. He can't logout.

#### How to reproduce the bug

1. Go to 'Right side top dropdown
2. Click on 'logout'
3. User will not able to logout

**Comment by ericandrewmeadows** [comment]
@SeLvAKuMaR-007 - which version are you running?  I end up having this work properly with my Custom Security Manager using Okta as the OAuth source on v0.33.0rc1.

**Comment by dtzampanakis** [comment]
Any infos for this? I cannot logout either. I am redirected to login and then superset/welcome and i am still loggin.
