### ISSUE TITLE
in superset==0.281 How to configure the celery asynchronous query?

### ISSUE THREAD

**Issue by cscainiao** [apache/incubator-superset#7847]

**Comment by cscainiao** [comment]
class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/1'
    CELERY_IMPORTS = ('superset.sql_lab','superset.tasks', 'superset.charts', 'superset.dashboards')
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
    CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True

CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379,
    key_prefix="superset_results:")

**Comment by cscainiao** [comment]
i run this comand celery worker --app=superset.tasks.celery_app:app --pool=prefork -Ofair -c 4
but say no model named superset.tasks

**Comment by cscainiao** [comment]
superset master branch have the model superset.tasks, but other branch have no model named superset.tasks

**Comment by cscainiao** [comment]
how can i start the celery?

**Comment by dpgaspar** [comment]
Do you have superset installed on your environment?

command:
```
celery worker --app=superset.tasks.celery_app:app --pool=prefork -Ofair -c 4
```

**Comment by dpgaspar** [comment]
Do you have superset installed on your environment?

command:
```
celery worker --app=superset.tasks.celery_app:app --pool=prefork -Ofair -c 4
```

[](url)

**Comment by cscainiao** [comment]
celery worker --app=superset.sql_lab:celery_app --pool=prefork -Ofair -c 4

I run this command, it's work

**Comment by dpgaspar** [comment]
If it works, can you close the issue?
