### ISSUE TITLE
Explore button is disabled for Druid in SQL lab 

### ISSUE THREAD

**Issue by michalmisiewicz** [apache/incubator-superset#7849]
Explore button is disabled for Druid in SQL lab. In #6557 it is said, that button is blocked because Druid does not support subqueries but this not true - Druid supports subqueries. Is there any other blocker for enabling this option ?

### Expected results

Superset should enable user to create visualization for druid in SQL lab.

### Actual results

Explore button is disabled for Druid in SQL lab

### Environment
superset - master (97ffb762d0216e745fb1d946b4b1a4beeb66bfdf)

**Comment by chrisngene** [comment]
same issue on druid visualize on the SQL Lab
