### ISSUE TITLE
Auto load the html changes

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#785]
Npm run dev reloads the js changes, but ignores the changes in the HTML.

**Comment by ascott** [comment]
steps to repro:
- run `caravel runserver -d -p 8081` and load http://localhost:8081/caravel/dashboard/world_health/
- make a change to `caravel/templates/caravel/dashboard.html`
- reload http://localhost:8081/caravel/dashboard/world_health/
- change is not loaded
- stop server and rerun `caravel runserver -d -p 8081`
- change is loaded

@mistercrunch is this something you would be willing to look into?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 640 days. Feel free to comment and request for this issue to be reopened.

**Comment by napjon** [comment]
The problem still exist even in the new version. We have some complex calculator html and hook it into the superset dashboard by iframe. Everytime a person readjust their browser window, superset refresh and all input gone.

**Comment by mistercrunch** [comment]
@napjon I don't think the problem you are describing is related. This is related to Jinja templates in the  `superset/templates/` folder.
