### ISSUE TITLE
Writing a CASE statement in Custom SQL Lab with Filter Box

### ISSUE THREAD

**Issue by mukund14** [apache/incubator-superset#7851]
Hi,

I am trying to write a Custom SQL CASE statement in SQL Lab in Apache Superset. The table I am using is the result of a Custom Query. 

How do I go about it?

![image](https://user-images.githubusercontent.com/8313154/61077572-91bcb080-a3d3-11e9-848f-f5b5f7f82ae3.png)

**Comment by villebro** [comment]
@mukund14 the Custom SQL in a metric should only correspond to one aggregation function, not the entire query. I suspect the following should work in your use case:
```sql
AVG(CASE WHEN l1_bacteria_name IN ('Firmicutes', 'Bacteroidetes') THEN value ELSE NULL END)
```

**Comment by KoomeKiriinya** [comment]
Hey How do I go about a custom metric that requires me to AVF when a certain selection is chosen on the filter and SUM otherwise
e.g CASE WHEN columnA = "Price" THEN SUM(columnA) ELSE AVG(columnA) end

**Comment by KoomeKiriinya** [comment]
AVG*
