### ISSUE TITLE
Error while importing dashboard with druid datasource

### ISSUE THREAD

**Issue by Ujwala92** [apache/incubator-superset#7857]
Expected results
Successfully Import dashboard with druid datasource

Actual results

AttributeError: type object 'dict' has no attribute 'import_obj'

#### How to reproduce the bug

1. Go to 'Manage'
2. Click on 'Import Dashboard'
3. Choose file
4.Click on Upload Button
5. See error

### Environment

(please complete the following information):

- superset version: `superset 0.28.1`
- python version: `python 3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

Additional context

Import dashboard with druid datasource but there is error of type object 'dict' has no attribute 'import_obj'.Please help me why this error occur and what settings need to do for solve this problem. Thanks in advance.

**Comment by syazwan0913** [comment]
Same issue here

**Comment by tuhangdi** [comment]
same problem
