### ISSUE TITLE
Superset Metrics count_distinct peo

### ISSUE THREAD

**Issue by alex601049502** [apache/incubator-superset#7860]
When I use Superset to show data,I find the count_distinct in Metrics always has Decimal.So I think it's a BUG. I hope I can get a reply soon，Thanks.
![superset count_distinct](https://user-images.githubusercontent.com/31439782/61115166-72518080-a4c4-11e9-93c0-8c5c093a71b7.png)

**Comment by xiaomo1104** [comment]
遇到同样的问题，找不到解决方案

**Comment by xiaomo1104** [comment]
Meet the same problem, can't find the solution
