### ISSUE TITLE
Unclear how to build non-npm front end assets

### ISSUE THREAD

**Issue by alisterpino** [apache/incubator-superset#7862]
I'm trying to edit some of the non-npm assets to develop on the front-end. When as per `CONTRIBUTING.md` I run `npm run dev-server` and make edits to the variables.less file the changes are not reflected in my browser.

`CONTRIBUTING.md` states "Note that there are additional frontend assets bundled with Flask-Appbuilder (e.g. jQuery and bootstrap); these are not managed by NPM, and may be phased out in the future." Do these additional assets require a separate build for changes to be reflected?

#question #doc

**Comment by alisterpino** [comment]
@mistercrunch Could you point me in the right direction? I've read through many previous issues about building the front end but none of what I've tried has made my edits to variables.less reflected in the browser

**Comment by mistercrunch** [comment]
Mmmh, so your issue is that you don't see the changes you make? `npm run dev` works and compile as expected?

Maybe you didn't `pip install -e .`  properly, meaning you might be serving off another python package installation (site-packages) as opposed to the python files in the repo. `which superset` should point to our bin in the repo.

**Comment by alisterpino** [comment]
That was the issue! Thank you so much. Now npm run dev works as expected, but npm ci and npm run prod both generate errors. I've pulled the latest version of superset and have have npm v6.9.0, node v12.6.0, and nvm v0.34.0 installed and  have tried running the commands both in a python 3.7.4 virtual environment and on my local machine (running OS X). Any ideas why npm ci and npm run prod are failing?

**Comment by kristw** [comment]
Have you `npm install`?
