### ISSUE TITLE
Tables from MSSQL not showing on Table View

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7870]
### Expected results

MSSQL database tables showing on Table View

### Actual results

No MSSQL tables showed

#### Screenshots
1. Database configuration
![Screenshot from 2019-07-15 10-55-24](https://user-images.githubusercontent.com/28984703/61193859-94c7e180-a6f0-11e9-87cc-4687e47a3ec9.png)
2. Tables detected
![Screenshot from 2019-07-15 10-55-41](https://user-images.githubusercontent.com/28984703/61193863-97c2d200-a6f0-11e9-9617-9196ba20f911.png)
3. Table view
![Screenshot from 2019-07-15 10-56-36](https://user-images.githubusercontent.com/28984703/61193865-9a252c00-a6f0-11e9-9292-1fedda9b14e0.png)

### Environment

- superset version: `0.28.1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
You need to add each table, they are not automatically added (click the button on the upper right hand corner on the tables page). There has been a few important fixes for MSSQL after version 0.28, so you might want to try one of the more recent versions if you run into trouble.

**Comment by syazwan0913** [comment]
I tried with more recent version which is `0.33.0rc1`, but still got the same output.

**Comment by villebro** [comment]
Every table has to be manually added to Superset; on the tables page, click the plus sign on the to right hand corner of the page to create a datasource referencing the table in your database.

**Comment by syazwan0913** [comment]
Alright thanks.

**Comment by villebro** [comment]
@syazwan0913 was there still something that required help/fixing, or can this issue be closed?

**Comment by syazwan0913** [comment]
I already add manually the table from MSSQL database
Schema: dbo
Table: Main
![Screenshot from 2019-07-18 08-09-26](https://user-images.githubusercontent.com/28984703/61420099-a1884780-a933-11e9-8632-ea1b47fe7852.png)

But when I tried to refresh metadata, this error appeared,
![Screenshot from 2019-07-18 08-10-17](https://user-images.githubusercontent.com/28984703/61420122-b8c73500-a933-11e9-8a89-faa01c0212b2.png)

**Comment by syazwan0913** [comment]
@villebro @mistercrunch So any way to fix that?

**Comment by vitorbellini** [comment]
Same error here

**Comment by vitorbellini** [comment]
Solution here https://github.com/apache/incubator-superset/issues/4271 thanks to @googlerobot

Run query below at the Superset Metabase

```
ALTER TABLE public.table_columns
ALTER COLUMN "type" TYPE varchar(128);
```

**Comment by syazwan0913** [comment]
@vitorbellini So I need to run the query on SQL Server database right?

**Comment by syazwan0913** [comment]
@vitorbellini I already can add the sql server tables. Thank you so much

**Comment by syazwan0913** [comment]
@vitorbellini I can already add the sql server tables. But for the column "name" there is "COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS" ?

![Screenshot from 2019-08-01 16-38-21](https://user-images.githubusercontent.com/28984703/62278516-ce337780-b47a-11e9-864b-2034b0cbad8c.png)

**Comment by syazwan0913** [comment]
@vitorbellini Thanks. I already can add sql server table. Btw, is there any way to fix this bug by changing the source code?

**Comment by villebro** [comment]
@syazwan0913 are you able to test #7963 which should fix this problem?

**Comment by syazwan0913** [comment]
I already tested it with `master` branch and it is okay.
