### ISSUE TITLE
How to run Superset with gunicorn in virtualenv?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7890]
### Expected results

Can run Superset in production mode in virtualenv 

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `0.28.1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Please refer to the gunicorn docs.
