### ISSUE TITLE
Can't find the navbar_menu.html file

### ISSUE THREAD

**Issue by a81884855** [apache/incubator-superset#7901]
### Expected results

I expect I can find the navbar_menu.html in the appbuilder folder

### Actual results

There are not a file call navbar_menu.html in the appbuilder folder.

But in the navbar.html file, it includes navbar_menu.html.

I don't think how it work?

#### Screenshots

<img width="1431" alt="Screen Shot 2019-07-19 at 10 30 07 AM" src="https://user-images.githubusercontent.com/29695107/61553976-ab33ad00-aa10-11e9-9be6-2c20c8fe7fab.png">

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
It's in the Flask-AppBulilder package and can be overridden in `templates/` folder on the Superset side

**Comment by a81884855** [comment]
Thank you so much! I create a file and named navbar_menu.html, but it doesn't work. But I renamed it as navbar_menu1.html and it works!!

But thx anyway
