### ISSUE TITLE
Superset db upgrade hangs for a custom alembic script

### ISSUE THREAD

**Issue by rahul-srivastava-sp** [apache/incubator-superset#7902]
The superset db upgrade command hangs when trying to run a custom alembic script to increase the length of username column in the ab_user table. Once the upgrade runs, it creates an idle sleep connection with the database which `supposedly` creates a lock on the ab_user table which prevents the alter command to run. We are using a 10.1.19-MariaDB as the database which is hosted in AWS RDS. 

For the first time installation, the upgrade works fine and deployment completes successfully. But when we create a new alembic script, build and restart the server the hoping the db upgrade should result

Not able to figure out how a sleep command is getting generated internally before the upgrade process. Has it to do with FAB or alembic in general?

### Expected results
The db upgrade process should complete successfully

### Actual results
The upgrade process hangs during 

#### Screenshots
The list of all the process for the db. The second last row is the one which prevents the ALTER command to be executed. The time for the command is same so it seems it just go triggered during the upgrade process
![AllProcessList](https://user-images.githubusercontent.com/43594455/61559248-d9c08080-aa2e-11e9-88d5-013debca9660.jpg)

The lock on ab_user table
![ab_user_LOCK](https://user-images.githubusercontent.com/43594455/61559360-1ee4b280-aa2f-11e9-8a03-19408b7d721a.png)

#### How to reproduce the bug

1. Have an installed version of superset running with db up and running.
2. Write a custom alembic migrate script to increase the username length
3. Build the project and restart the server.
4. The `db upgrade` process should get stuck

### Environment

- superset version: `0.999.0dev`
- python version: `3.7.2`
- node.js version: `10.15.0`
- npm version: `6.9.0`

### Additional context

**Generated alembic script**
```
revision = 'c088a7201375'
down_revision = 'c82ee8a39623'

from alembic import op
import sqlalchemy as sa


def upgrade():
    with op.batch_alter_table('ab_user') as batch_op:
        batch_op.alter_column(
            'username',
            nullable=False,
            type_=sa.String(length=256),
            existing_type=sa.String(length=64),
            existing_server_default=None, 
            existing_nullable=False)


def downgrade():
    with op.batch_alter_table('ab_user') as batch_op:
        batch_op.alter_column(
            'username',
            nullable=False,
            type_=sa.String(length=64),
            existing_type=sa.String(length=256),
            existing_server_default=None, 
            existing_nullable=False)
```

**Below are the logs from the console when the db gets stuck**
```
xxx-superset             | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
xxx-superset             | INFO  [alembic.runtime.migration] Will assume transactional DDL.
xxx-superset             | INFO  [alembic.runtime.migration] Running upgrade c82ee8a39623 -> c088a7201375, increase username length
```

The upgrade process gets stuck for ~ 8 hours as the sleep command times out after that time as per the default db configuration time for time_wait_timeout and wait_timeout of 28800 seconds. After the time out, the ALTER command gets executed. Also, if we manually KILL the thread, the ALTER gets executed and the upgrade finishes successfully.

**Comment by rahul-srivastava-sp** [comment]
@mistercrunch Do you have any thoughts on this?

**Comment by mistercrunch** [comment]
Looks like there's some lingering lock on the user table. With the right MySQL DBA commands you should be able to figure out which transaction/command is locking out the ALTER TABLE which should give a pointer as to what is going on.

If you just want to get your migration through, you could try stopping the app and re-running the migration.

**Comment by rahul-srivastava-sp** [comment]
@mistercrunch The lock only seems to appear only when we start the deployment process (which kicks off the alembic upgrade process). For an already running app, the database does not show any locks. I am finding it really hard to figure it out as to which transaction internally kicks off the *sleep* command which prevents the ALTER command to be executed. Do you any pointers on this?

Our app is already running in the production environment (using AWS) so an instance is always up and running so we ideally the app does not stop. Contrary, we the migration is run from scratch, this lock never happens and migration completes successfully.
