### ISSUE TITLE
Export .csv API to Excel, Google Sheets, etc.

### ISSUE THREAD

**Issue by robertdefilippi** [apache/incubator-superset#7904]
**Is your feature request related to a problem? Please describe.**
There was a ticket made [here](https://github.com/apache/incubator-superset/issues/6796) but it has gone stale, so I'm making it again. The issue is, 'exporting to csv' creates issues with 100s of csv files being created against many queries with no single source of truth.

**Describe the solution you'd like**
The ability to export live queries directly into Google Sheets via an api. Similar to what reDash has. So I can use the `=IMPORTDATA('foo.csv')` function in spreadsheets. Now, the source of truth is this query, which has version and history information available in Superset.

![image](https://user-images.githubusercontent.com/9288605/61567179-ac82cb00-aa4c-11e9-9428-e073c275cfcb.png)

**Describe alternatives you've considered**
I currently use ReDash for this, however I would like to move to Superset.

**Comment by rahilahmed** [comment]
Did someone managed to find a possibility of sending SQL Editor results to Google sheets without copy pasting the data ? Is there any way that could help ?

**Comment by robertdefilippi** [comment]
Hey @rahilahmed I never found a solution to this, and I have not fully implemented Superset at my organization. I'm not going to be able to help you. Sorry 😞
