### ISSUE TITLE
Support for PrestoSQL (https://prestosql.io) instead of PrestoDB

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#7914]
**Is your feature request related to a problem? Please describe.**
PrestoSQL (https://prestosql.io) has some much-needed security fixes

**Describe the solution you'd like**
Superset able to retrieve data from PrestoSQL even though v1/statement endpoint has changed

**Comment by findepi** [comment]
@tooptoop4 could you please DM me on Presto Community Slack (https://prestosql.io/community.html)?

**Comment by rschlussel** [comment]
@tooptoop4 is this the issue you were talking about https://github.com/prestodb/presto/pull/13110?  We're putting the fix in prestodb too! Also, are there other security issues you think should be addressed? Please let us know, so we can fix them.
