### ISSUE TITLE
The error Control labeled "Metrics" cannot be empty should not appear on the first time goes to chart screen by pressing table name

### ISSUE THREAD

**Issue by vinhenouvo** [apache/incubator-superset#7916]
The validation works unexpected with my below steps to reproduce

### Expected results

The error "Control labeled "Metrics" cannot be empty" should not appear when delete Metrics

### Actual results

The error "Control labeled "Metrics" cannot be empty" appears when delete Metrics, but it not happens after refresh page

#### Screenshots

<img width="812" alt="Screen Shot 2019-07-23 at 5 39 08 PM" src="https://user-images.githubusercontent.com/50986096/61705858-dbf94680-ad70-11e9-8c56-cba0c17dd09e.png">
#### How to reproduce the bug

1. Go to 'Sources/Tables'
2. Click on 'a table name'
3. It goes to chart screen, with Table type
4. Delete Metrics COUNT(*)
=> It's show the error similar to attachment.
5. Try to select Columns on NOT GROUP BY or anything
=> The error not disappear

6. Refresh page, and try to delete Metrics COUNT(*) again
=> The error does not appear

### Environment

- superset version: Master branch on 2019, July 23
- python version: 3.7.3
- node.js version: 8.16.0
- npm version: 6.4.1

**Comment by jaylindquist** [comment]
This looks like a duplicate of #7363 which has a hint of why this is happening, but was closed due to inactivity

**Comment by first-caveman** [comment]
+1 on this. I am able to skirt around the issue by first defining "Not Grouped By" columns, and then clearing the 'Metrics' field.

**Comment by tuhinsharma121** [comment]
> +1 on this. I am able to skirt around the issue by first defining "Not Grouped By" columns, and then clearing the 'Metrics' field.

It did not work for me.

**Comment by tuhinsharma121** [comment]
Any update on the issue?

**Comment by first-caveman** [comment]
> > +1 on this. I am able to skirt around the issue by first defining "Not Grouped By" columns, and then clearing the 'Metrics' field.
> 
> It did not work for me.

@tuhinsharma121 - Try saving first. I have to deal with this on a regular basis. I find saving the chart with the wrong 'metrics' set, then coming back and clearing it sometimes works. I just fiddle around until I get there...

**Comment by Hchiker** [comment]
the workaround I found is the following:
1) In the Section "Group By":
fill in the fields
 1.a)  "Group By" with any available value
 1.b)  "Metrics" with any available value
2) In the Section "NOT GROUPED BY":
fill in the fields that you target to use ( as "Columns")
3) Click on the button "Run Query" --> error message indicating that you can´t combine both "Group by " and "NOT GROUPED BY" fields
4) Clear the fields of the section "Group by" --> keep only the target fields 
5) Click on the button "Run Query" --> OK

**Comment by axelet** [comment]
I found out that changing Visualization Type forth and back to Table clear the error for me.

**Comment by rabinnh** [comment]
This bug makes Superset unusable for me.  I have simple SQL that that reads 3 columns; a timestamp and 2 values.  I can't create a simple line chart and I have no idea how to proceed.
