### ISSUE TITLE
Title garbled in Time-series Table

### ISSUE THREAD

**Issue by Ethan-Ma** [apache/incubator-superset#7921]
### Expected results

the title of Time-series Table displayed correctly.

### Actual results

Title of Time-series Table garbled.

#### Screenshots

<img width="1207" alt="屏幕快照 2019-07-25 上午10 12 10" src="https://user-images.githubusercontent.com/8022562/61841191-7c14b400-aec6-11e9-8d75-c784c1ccc7db.png">
<img width="1331" alt="屏幕快照 2019-07-25 上午10 13 27" src="https://user-images.githubusercontent.com/8022562/61841215-89ca3980-aec6-11e9-832f-54fd1cb04ea9.png">

#### How to reproduce the bug

1. create a Time-series Table
2. See error

### Environment

(please complete the following information):

- superset version: 0.28.1
- python version: Python 3.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x]  I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x]  I have reproduced the issue with at least the latest released version of superset.
- [x]  I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bianxintong** [comment]
is this issue fixed? we are using superset version built from the master branch of july, same issue

**Comment by fazhang** [comment]
same issue  +1

**Comment by fazhang** [comment]
1. chart edit  
2.  http://yourhostname/chart/edit/{chart_id}
3.  edit Parameters   `key`    

![image](https://user-images.githubusercontent.com/2740367/69929664-c522e780-14fa-11ea-9628-a9a510e52e79.png)

**Comment by kalimuthu123** [comment]
Hi ,
@fazhang  the problem is you have to compile production build
npm run build

**Comment by zheya08** [comment]
same issue +1
