### ISSUE TITLE
[Sql Lab] Auto completion for table name/schema/columns in sql editor is not working

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#7925]
Since #7633, Sql Lab sql editor can't auto complete table/schema/column names.

#### How to reproduce the bug

1. Go to sql lab
2. choose main database
3. typing `select ds, id from dashb`
4. sql lab should auto complete dashb to dashboards

@mistercrunch

**Comment by cgivre** [comment]
I've replicated this.  I thought this was a flaw in my installation, but apparently not.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/7926 closes this
