### ISSUE TITLE
Superset export .csv format cell type erro

### ISSUE THREAD

**Issue by alex601049502** [apache/incubator-superset#7927]
When I use charts to export .csv format,I find the excel cell type is automatically recognized，so my data is erro.For example，my data has like （number type data， number type data）,this
kind data is thought currency type,but it's just text type.If I want to change all excel cell type to text type,what should I do?

**Comment by alex601049502** [comment]
@ryw @moonboots @jeremi @edevil

**Comment by nld-8832** [comment]
@PayneZx Hi, did you find any solution to this problem?

**Comment by PayneZx** [comment]
> 

We used .xlsx file to export

**Comment by Habeeb556** [comment]
Hello @PayneZx , how did you used .xlsx file to export? as the only open in sql lab is csv.
