### ISSUE TITLE
Run Async in SQL lab is not working..

### ISSUE THREAD

**Issue by wooram1125** [apache/incubator-superset#7928]
### Expected results

query success..

### Actual results

error message, `The query exceeded the 30 seconds timeout.`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

I found missing column `allow_run_async`, when `/api/v1/database` is called.
So, I temporarily modified it as below,
```js
dataEndpoint={
          '/api/v1/database/?q=' +
          '(keys:!(none),' +
          'columns:!(id,database_name,backend,allow_run_async),' +
          'filters:!((col:expose_in_sqllab,opr:eq,value:!t)),' +
          'order_columns:database_name,order_direction:asc)'
        }
```
Then it worked well. Please check it. :smile:

**Comment by dpgaspar** [comment]
Hi @wooram1125,

I'll submit a fix for it.
