### ISSUE TITLE
Add a post-init extension point for blueprints, etc

### ISSUE THREAD

**Issue by micimize** [apache/incubator-superset#7934]
**Problem:**
#4149 - you have to do hacky in-function imports to import from superset in blueprints to avoid circular imports.

**Solution:**
We add a generic extension point post-init, such as an optional `superset_post_init.py` with a `post_init(app) -> app`, that handles extensions

**Alternatives:**
* Rework the way the config or internal library structure is loaded so that imports are not an issue
* Make a specific entry point `blueprints.py`
* Do nothing and tell users to deal with it and use the workaround

**Comment by micimize** [comment]
I believe this also means `CUSTOM_SECURITY_MANAGER` is unusable, as it has to extend from a superset import

**Comment by ericandrewmeadows** [comment]
@micimize - I have `CUSTOM_SECURITY_MANAGER` working on v0.33.0rc1 - can you clarify?

**Comment by micimize** [comment]
@ericandrewmeadows I might be wrong there. Basically, I was having issues importing from superset directly for blueprints due to circular imports issues, and figured the same would happen with importing the security manager for extension.

With #8004 solved diagnosing exactly what's going on will be much easier

**Comment by ericandrewmeadows** [comment]
👍 - sounds good.  I was dealing with CSM in v0.34.0rc1, so I just wanted to confirm that it was something else.

**Comment by micimize** [comment]
I think the simplest way to implement this would be
```python
# config.py
def post_init(app):
    return app
```
```python
# believe this will work in __init__.py
post_init = conf.get("post_init")
if post_init:
    app = post_init(app) or app
```
