### ISSUE TITLE
Remove tooltip from the Table View chart

### ISSUE THREAD

**Issue by nabinkhadka** [apache/incubator-superset#7938]
I have a Table View with two columns. When I hover over a string value, then I get "NaN" tooltip. Is there a way to remove it?

<img width="218" alt="Screen Shot 2019-07-27 at 10 29 13 PM" src="https://user-images.githubusercontent.com/6050613/61997239-5e11a400-b0be-11e9-8591-0e06cab1aaf1.png">

**Comment by MarcusSorealheis** [comment]
@nabinkhadka Can you provide more details about the Table? Is column two expecting an integer?

**Comment by nabinkhadka** [comment]
> @nabinkhadka Can you provide more details about the Table? Is column two expecting an integer?

No. It is a string value.
