### ISSUE TITLE
Superset api to get a Chart's JSON data 

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#7941]
Does Superset have an API to expose a Chart's JSON data? #4708

**Comment by kalimuthu123** [comment]
i need to connect the superset chart to my ionic app for this i need the urls of the chart data

**Comment by mmutiso** [comment]
Yes, an example for the wold bank data examples is given below
http://localhost:8088/superset/explore_json/?form_data=%7B%22slice_id%22%3A45%7D

Although it would be a bit counter productive to pull data in the format as it means you have to build your own charts from scratch.

**Comment by kalimuthu123** [comment]
but how to pass security login authentication

**Comment by mmutiso** [comment]
Bypassing the security login is a slightly different issue. 

One of the approaches is to add the necessary permissions to the "Public" role so that the endpoint is accessible without the need to login.

**Comment by ericandrewmeadows** [comment]
Agreed, @mmutiso - I would take that same approach.  @kalimuthu123 - did you do this?

**Comment by kalimuthu123** [comment]
i tried with this but unable to get curently into it
![danger](https://user-images.githubusercontent.com/42966797/63334874-f74c7700-c359-11e9-8b39-8e9843fdff4b.png)

**Comment by vadivelselvaraj** [comment]
For anyone who ended up here, [this](https://github.com/apache/superset/pull/15827) PR creates a new **chart/{CHART_ID}/data** endpoint to fetch a chart's JSON data.
