### ISSUE TITLE
Landing page and dashboards fail to render

### ISSUE THREAD

**Issue by paritoshjchandran** [apache/incubator-superset#7944]
Certain pages fail to render.
First, the landing page after the login.
Second, all the dashboards.
Thirdly, all the charts.

### Expected results

See a proper page after login

### Actual results

Few pages with only menus on them open fine.
Like 'Dashboards', 'Databases' etc.
Dashboards themselves fail to render properly.

#### Screenshots

![Screenshot from 2019-07-30 01-08-12](https://user-images.githubusercontent.com/33488873/62077059-d5823780-b266-11e9-9922-fa655d49551d.png)

#### How to reproduce the bug

1. Install incubator-superset-0.32.0.rc2
2. Follow the install procedures
3. Login with admin you created in step 2

### Environment

(please complete the following information):

- superset version: 0.32.0.rc2
- python version: 3.6
- node.js version: 8.10.0
- npm version: 3.5.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

No additional context.

**Comment by blcksrx** [comment]
You should build the front-end layer! go to the **assets** directory and run this:
```
npm ci && npm run build
```

**Comment by ericandrewmeadows** [comment]
@paritoshjchandran - can you please confirm this resolves your issue & then close it?  Thanks!

**Comment by joicejacob** [comment]
https://stackoverflow.com/questions/52867167/apache-superset-dashbaord-not-rendeing

Second Solution is working for me

**Comment by paritoshjchandran** [comment]
I have been on the road for a while now and haven't got the time to test this.
So, I'll close this as of now and if I do not find a fix, I'll reopen this.
