### ISSUE TITLE
Import role or copy paste role permissions

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#7948]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but handy when dealing with environments

**Describe the solution you'd like**
I'd like to be able to paset CSV list of permissions into permissions selector

Current workaround I'm using from console:

```
var perms = "can list on DashboardModelView, can download dashboards on DashboardModelView, can download on DashboardModelView, can show on DashboardModelView, can list on DashboardModelViewAsync, can download dashboards on DashboardModelViewAsync, can download on DashboardModelViewAsync, can show on DashboardModelViewAsync, can list on DashboardAddView, can download dashboards on DashboardAddView, can download on DashboardAddView, can show on DashboardAddView, can dashboard on Superset, can fave dashboards by username on Superset, can csrf token on Superset, can recent activity on Superset, can fave dashboards on Superset, menu access on Dashboards";

var sel = $('.my_select2.form-control[name="permissions"]');
var options = sel.find("option");

sel.val(perms.split(",")
			.map(p => p.trim())
			.map(p => $(options.filter((i, o) => $(o).text() == p)[0]).attr("value")))
	.trigger('change');

```

**Comment by ericandrewmeadows** [comment]
@gbrian - This makes sense, but would it be better to do a "copy permissions from <group x>" as a drop-down for the basis?
<img width="1170" alt="Screen Shot 2019-08-18 at 8 24 00 PM" src="https://user-images.githubusercontent.com/19596182/63237279-2944c880-c1f6-11e9-8dd6-db2fe16bc5bd.png">
The proposal to accomplish this is as follows:
* Enable multi-selection in the drop-down for other Groups whose roles you wish you include
* If a user deselects a given permission from said role, the Groups will re-evaluate, and only show those whose Groups are reflected in the current group
* If a permission from a group has been removed, but then the given group has been re-added, only the missing permissions will be re-added; all existing permissions will remain.

**Comment by akshayramakrishnanfk** [comment]
@gbrian , I'm facing a similar problem now. I have set up my superset using docker and I'm unable to export the roles information. Has this issue been resolved?
