### ISSUE TITLE
Authenticate Apache Superset webserver with Oracle Database users

### ISSUE THREAD

**Issue by ganesh8614** [apache/incubator-superset#7957]
Hello,

We have requirement to Authenticate Apache Superset webserver with Oracle Database users instead of Flask/db authentication, can anyone please share your inputs if any configuration/documentation available.

Appreciate your quick response.

**Comment by mmutiso** [comment]
This is possible with a little bit of code and configuration on your part. All you need to do is extend the SupersetSecurityManager class as follows. 

1. Create a superset class named CustomSecurityManager
2. On the superset_config.py file import that class as shown in the image below.
![image](https://user-images.githubusercontent.com/6734562/62290289-ae478800-b469-11e9-9f4c-a01549b282aa.png)


Override the AuthDBView to include your own implementation. 
https://flask-appbuilder.readthedocs.io/en/latest/_modules/flask_appbuilder/security/views.html

This medium link provides a good way to get started linking everything together. 
https://medium.com/@sairamkrish/apache-superset-custom-authentication-and-integrate-with-other-micro-services-8217956273c1

**Comment by mmutiso** [comment]
You can also read more here https://medium.com/@mmutiso/authenticate-apache-superset-with-a-custom-user-store-c4511ab0f798
