### ISSUE TITLE
Scheduled email reports for Slices / Dashboards

### ISSUE THREAD

**Issue by ganesh8614** [apache/incubator-superset#7960]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ericandrewmeadows** [comment]
I believe this is at worst in v0.33.0rc1 - which version are you running that is incapable of this?

**Comment by ganesh8614** [comment]
We are on v.033
