### ISSUE TITLE
Dashboard Security

### ISSUE THREAD

**Issue by ganesh8614** [apache/incubator-superset#7961]
We have Two Dashboards, Dashboard A and Dashboard B and Groups like Group A, Group B, Group C and Group D

We have requirement to implement the below:

Group A should have access to Dashboard A
Group B should have access to Dashboard B
Group C should have access to both Dashboard A & Dashboard B
Group D should not have access to any Dashboards

Also we are unable to assign a Role to the Dashboard permissions

Appreciate your quick response

**Comment by miloradkrstevski** [comment]
You ll need to gain access do the correspoding data sources for each group.

**Comment by hinzinho** [comment]
I also wish they add permissions to Charts. This way, we can reuse the charts in other dashboards without recreating the same charts.

**Comment by miloradkrstevski** [comment]
Add the chart to other dash but gain access to data source.

**Comment by mistercrunch** [comment]
Per-dashboard permissions is likely to get implemented in the future, meaning you could have access to a certain dashboard, but not to the underlying datasource(s), and couldn't go and "explore" deeper from the dashboard.

It's also likely that we'll implement row-level security in the future, which would force certain predicates (aka filters) based on perms.

The reason why it is the way it is currently is:
* we wanted a [somewhat] simple security model
* we wanted users to be able to drill in or explore deeper and answer their own questions as a core flow

Currently all perms (datasource, database, schema) are implemented as different types of FAB (flask app builder) permissions that can be composed into FAB roles.  In the future, we *may* want to overload FAB roles to have to many-to-many relationships to these other models, to get a more comprehensive / structured roles management form.
