### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by ganesh8614** [apache/incubator-superset#7962]
Currently we are able to export the report to .CSV format, is there any other download options like .pdf,.txt etc

**Comment by miloradkrstevski** [comment]
What will you achieve with PDF (txt is same as csv)? See the CSV, it shows the message itself.

**Comment by ganesh8614** [comment]
> What will you achieve with PDF (txt is same as csv)? See the CSV, it shows the message itself.

we have client requirement - export to PDF & Excel :)

**Comment by miloradkrstevski** [comment]
Than export in CSV, use VBS to convert into XLSX or PDF in Excel.
