### ISSUE TITLE
mssql connection - issue 

### ISSUE THREAD

**Issue by santoshdvn** [apache/incubator-superset#7970]
Trying to connect the mssql server using below connection string 

mssql+pymssql://test_superset:#superset123@<ipaddress>:1433/stagedb

getting below error while testing the connection 

**ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nNo module named 'pymssql'", "stacktrace": "Traceback (most recent call last):\n  File \"/home/superset/superset/views/core.py\", line 2070, in testconn\n    engine = database.get_sqla_engine(user_name=username)\n  File \"/home/superset/superset/utils/core.py\", line 111, in __call__\n    value = self.func(*args, **kwargs)\n  File \"/home/superset/superset/models/core.py\", line 900, in get_sqla_engine\n    return create_engine(url, **params)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py\", line 435, in create_engine\n    return strategy.create(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 87, in create\n    dbapi = dialect_cls.dbapi(**dbapi_args)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/pymssql.py\", line 61, in dbapi\n    module = __import__(\"pymssql\")\nModuleNotFoundError: No module named 'pymssql'\n"}**

**Comment by mistercrunch** [comment]
`No module named 'pymssql'`

**Comment by santoshdvn** [comment]
installed the pymssql module . still facing same issue

**Comment by santoshdvn** [comment]
installed and restarted server

**Comment by SWoto** [comment]
@santoshdvn, did u manage to solve this problem? I'm facing the same issue
