### ISSUE TITLE
Row Limit in Filter Box

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#7971]
How can I change the row limit in filter box? In the rc-32.2 version it seems the list of options appearing in the drop down menu is limited to 1000 items. 

I found : FILTER_SELECT_ROW_LIMIT in the config file but it only affects the auto complete filter. 

### Environment

- superset version: superset-rc-32.2
- python version: Python 3.7.3
- node.js version: v8.11.1
- npm version: 5.8.0

**Comment by gbrian** [comment]
Currently hard coded

![image](https://user-images.githubusercontent.com/767180/63521695-3c59e000-c4f7-11e9-8b83-b42dbc01606b.png)

`config.get("FILTER_SELECT_ROW_LIMIT", 10000)` will do the trick
