### ISSUE TITLE
Unblocking the release process

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#7974]
This issue gathers information about blockers and progress towards our first ASF release.

# Licenses
Superset has a super wide, deep, and dynamic dependency tree. Bumping a single library can create licensing issues that are hard to catch.

FOSSA seems like the perfect tooling to do this, yet the ASF infra team won't let us install it. https://issues.apache.org/jira/browse/INFRA-18719 . Here's FOSSA pointing to my fork of Superset.
https://app.fossa.com/projects/git%2Bgithub.com%2Fmistercrunch%2Fsuperset/refs/branch/master/78d46fa18d6acf9823261678ba9a16b1aad3e451/browse/licenses

Note that FOSSA offers a CLI (haven't dug into it yet) that we may be able to leverage in CI. Also note that other projects at the ASF use Fossology, which doesn't seem to be as modern / GH-integrated

Some previous work I did on licenses, to help with the eventual "convenience release" which would package minified JS, and thus would need a dynamically generated LICENSE file. 
https://github.com/apache/incubator-superset/pull/5801

## TO RESOLVE
* pillow lib: https://github.com/python-pillow/Pillow/blob/master/LICENSE, we can make optional or figure out if it's an ok license

# Attempts

See the [barely usage] archives https://mail-archives.apache.org/mod_mbox/superset-dev/201905.mbox/browser for previous attempts. 

# Related work
* https://github.com/apache/incubator-superset/pull/7539
* https://github.com/apache/incubator-superset/pull/7643

**Comment by davidhassan** [comment]
_"FOSSA seems like the perfect tooling to do this, yet the ASF infra team won't let us install it."_;
 For the sake of the community can ASF not make an exception for FOSSA. We have been without an official release for way too long.

_"Unfortunately, this requires permissions we can't allow, namely repo:write and webhook/service:write"_; Is there a work around here to not break what I assume is some internal; guideline/process?

**Comment by mistercrunch** [comment]
Found and implemented a solution to use the FOSSA cli.

**Comment by cgivre** [comment]
I'll email legal and follow up with the PIL licensing issue.  I did some research and it appears that the PIL license is virtually identical to the BSD 0 clause license.  I created a JIRA ticket (https://issues.apache.org/jira/browse/LEGAL-472) and will follow up about that.

**Comment by cgivre** [comment]
UPDATE:  The Apache legal team accepted the PIL license as a CatA license which means that it CAN be included in an Apache project.

https://issues.apache.org/jira/browse/LEGAL-472

**Comment by mistercrunch** [comment]
Oh nice! Pushed a release candidate to the mailing list this AM!

**Comment by cgivre** [comment]
I saw!  So if the licensing issue with `PIL` is resolved, what other issues can I assist with?

**Comment by RichardAnaya-ML** [comment]
Is my understanding correct from this PR that an official release might be around the corner?
