### ISSUE TITLE
sqllab : Results backend isn’t configured

### ISSUE THREAD

**Issue by santoshdvn** [apache/incubator-superset#7978]
Hi All,
I am running superset on docker and created new mssql database connection and able to view schemas , tables and preview the table in SQLlab
however , now able to run the sql queries . I am getting following error “Results backend isn’t configured.”
can anyone help me on this ?

 python version: Python 3.6.9
 node.js version:v10.16.0
-npm version: 6.9.0

![image](https://user-images.githubusercontent.com/292629/62407629-759ed000-b589-11e9-9b92-98470e42781e.png)

**Comment by ericandrewmeadows** [comment]
Which version of Superset are you running?  This works well on v0.33.0rc1; I haven't been able to work on v0.34.0rc1 yet due to other issues with that build.
