### ISSUE TITLE
Dashboard Export/Download to PDF will be introduced?

### ISSUE THREAD

**Issue by RajuKevda** [apache/incubator-superset#7979]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarcusSorealheis** [comment]
@RajuKevda Can you complete the template? You left the descriptions there.

**Comment by ericandrewmeadows** [comment]
@RajuKevda - 2nding @MarcusSorealheis .  You need to fill out the template.

From what you are describing, you would like to have a rendering of the page with your charts in PDF, similar to a print command, without the header/navbar present - is that correct?

**Comment by RajuKevda** [comment]
> @RajuKevda - 2nding @MarcusSorealheis . You need to fill out the template.
> 
> From what you are describing, you would like to have a rendering of the page with your charts in PDF, similar to a print command, without the header/navbar present - is that correct?

Yes Eric,
I need to save the tabular/paginated reports as PDF, also save a dashboard view as PDF
