### ISSUE TITLE
Better Visualization and Sorting for NULL values

### ISSUE THREAD

**Issue by semantiDan** [apache/incubator-superset#7983]
### Motivation

While working with a large, non-curated and diverse database consisting of many columns and rows per table I found myself **painfully**  trying to distinguish null values from actual strings/numbers. 

Whatsmore, by sorting columns that were supposed to be numerical, **the null values sometimes took precedence over the order** when I was trying to sort said columns.

### Proposed Change

- If the value of a cell is null, it shows as NULL (italic and light gray) to easily distinguish it from other values in the results table.
- When sorting a column with NULL values, NULL values always come last regardless of the sorting order.

The change described above is already implemented in a forked local version we have of Apache Superset.

This change does not affect exporting CSV files.

### New or Changed Public Interfaces

No change needed for any model, REST endpoint, deployment, or backend.

The only change is in the React Component **FilterableTable** 
The file can be found in 

`<root>/superset/assets/src/components/filterabletable/FilterableTable.jsx `

The component generates the results table in SQL Lab queries and other visualizations where SQL tables are present.

### New dependencies

No new dependencies

### Migration Plan and Compatibility

No migration plan needed

### Rejected Alternatives

Alternatives to better solutions are welcome.

**Comment by etr2460** [comment]
This seems like a pretty small change, if you already have the code written on a forked version, I think just opening a PR and including screenshots of the changes would reach more people than this issue

**Comment by mistercrunch** [comment]
No need for a SIP here, see SIP-0 for more details about SIPs

**Comment by semantiDan** [comment]
@etr2460 , @mistercrunch 
Thank you for your comments and for contributing/creating this awesome open-source repository.
As you can probably see, I've created a PR and referenced this ISSUE.

We have a bunch of other features we plan to add at a later time.
