### ISSUE TITLE
Remove TOP 50000 Big Number chart

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#7984]
### Expected results

Superset query all records in table when creating the `Big Number` chart

### Actual results

Number of records to return is `50000`

#### Screenshots

![Screenshot from 2019-08-05 12-54-58](https://user-images.githubusercontent.com/28984703/62439952-954c1900-b780-11e9-8847-8f89f86c5c77.png)

#### How to reproduce the bug

1. Go to 'Add new chart'
2. Choose 'Big Number'
3. View query

### Environment

- superset version: `0.28.1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`
- database: `SQL Server`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Oh does the top actually limits the number of rows that are scanned in SQL Server, making your `COUNT` == 50000?

The equivalent `LIMIT` in most other databases limits what is returned, not what is scanned.

**Comment by syazwan0913** [comment]
Thanks for the fix

**Comment by villebro** [comment]
Out of curiosity I tested this on an old MSSQL 2008R2 instance, and it did **not** limit the number of scanned rows, only the result. @syazwan0913 what version of MSSQL are you on? And are you sure your table doesn't happen to have 50,000 rows?

**Comment by mistercrunch** [comment]
Sounds like this shouldn't affect the query plan's or perf in any important way.

**Comment by syazwan0913** [comment]
@villebro @mistercrunch Actually it's don't affect the query at all. It is just showing `TOP 50000` eventhough the query is correct. So, everything is okay :)
