### ISSUE TITLE
Apache Superset Installation - Ubuntu 18.04, unable to load/run superset error

### ISSUE THREAD

**Issue by RajuKevda** [apache/incubator-superset#7990]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by RajuKevda** [comment]
Adding error message

![image](https://user-images.githubusercontent.com/31248199/62515709-b5dba800-b840-11e9-9042-09347be33994.png)

**Comment by ShalbafZadeh** [comment]
@RajuKevda use runserver instead of run
