### ISSUE TITLE
can't add clickhouse database (allways connecting as default user)

### ISSUE THREAD

**Issue by janantos** [apache/incubator-superset#7991]
Can't add ClickHouse database under databases. when pressing Test Connection button receiving error message that User default is not allowerd to connect. there is set another user in SQLAlchemy URI (user name containing dash "-")

### Expected results

receive successful status 

### Actual results

receive error message

#### Screenshots

![image](https://user-images.githubusercontent.com/19323286/62519066-896d5f00-b833-11e9-8e44-8341e046984a.png)

#### How to reproduce the bug

1. Go to Sources -> Databases
2. Click on '+' button 
3. fill Database and URI
4. press Test Connection

### Environment

(please complete the following information):

- superset version: 0.28.14
- python version: 3.6.8 
- sqlalchemy-clickhouse version: 0.1.5.post0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

also tested using clickhouse-sqlalchemy 0.0.10 it does not fails during check connection but after clicking save button, I receive error "Could not locate column in row for column 'name' "
![image](https://user-images.githubusercontent.com/19323286/62519670-bcfcb900-b834-11e9-8805-86acb76a3c4a.png)

**Comment by ericandrewmeadows** [comment]
Have you tried this on 0.33.0rc1?  I believe this may help.

**Comment by ognemuh** [comment]
We've tried this on version 0.34 (python/alchemy are the same) - still doesn't work.

**Comment by villebro** [comment]
I was able to reproduce the `Could not locate column in row for column 'name'` error - will investigate.

**Comment by villebro** [comment]
The problem with saving a database seems to be in `clickhouse-sqlalchemy`. Please see the following ticket: https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/64 On the other hand `sqlalchemy-clickhouse` seemed to work better (was able to add the engine), so you might want to try that out.

**Comment by janantos** [comment]
I have found solution.
You need to downgrade infi.clickhouse_orm to version 1.0.4 and then it will
work.

Also you will be receiving errors about decimal data types, his can be
solved with installing sqlalchemy-clickhouse from GitHub and not from PIP.
You can install it using pip command.

Also in superset 0.34 the SQL Lab save as table functionality will not
work, as Clickhouse does not use standard SQL.

**Comment by villebro** [comment]
FYI, I have a fix in the works for clickhouse (bug in how connection string is constructed), will put through a PR later today.

**Comment by janantos** [comment]
I do not understand why this bug does not exhibit on infi.clickhouse_orm <=1.04. what has changed in higher versions?

**Comment by villebro** [comment]
This got messier than expected, mostly due to poor standardization in the python dbapi spec, hence my issues were mostly unrelated to clickhouse. Will be looking at those later. However, while I was able to get SqlLab working with clickhouse, I was unable to add tables using the stable version from `PyPI` or the bleeding edge version from github. Were you successful with that?

**Comment by janantos** [comment]
yes I have been successful, as mentioned earlier.
I have found solution. You need to downgrade infi.clickhouse_orm to version 1.0.4 and then it will work.  Also you will be receiving errors about decimal data types, his can be solved with installing sqlalchemy-clickhouse from GitHub and not from PIP. You can install it using pip command.  Also in superset 0.34 the SQL Lab save as table functionality will not work, as Clickhouse does not use standard SQL.

**Comment by janantos** [comment]
Both of this has been tested using 0.29b7 from PIP and 0.34 from GitHub

**Comment by ameyd12** [comment]
I think I have run into a similar issue here as the connection string to Clickhouse looks to be broken
<img width="1680" alt="Screen Shot 2020-05-11 at 12 41 23 PM" src="https://user-images.githubusercontent.com/64430183/81604563-ef6bb180-9384-11ea-8943-8f4f74ca36ec.png">
