### ISSUE TITLE
time grain missing in filter

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#8009]
![timegrain problem](https://user-images.githubusercontent.com/42966797/62771508-ffcfc280-baba-11e9-8ebb-c2af4843c2c1.png)

### Expected results
filter options are showing 

### Actual results

filter options are not showing 

### Environment

(please complete the following information):

- superset version: `superset 0.32rc2`
- python version: `python 3.6`
- node.js version: `v10.15.1`
- npm version: `npm 6.9.0`

### Checklist

when i am loading the filter it does not showing time grain filter please check with the following pic

**Comment by kalimuthu123** [comment]
i am also having problem when using time series visualisation
it does not find the metrics of the visualisation 

Environment
superset version: superset 0.32rc2 dev2
![timeseries table](https://user-images.githubusercontent.com/42966797/62706699-b1b0b580-ba0d-11e9-846c-e726e011564d.png)

python version: python 3.6
node.js version: v10.15.1
npm version: npm 6.9.0

Expected results
time series table working in the system

Actual results
time series table not working in the system

**Comment by villebro** [comment]
What database is this? And are you able to test on `master`?

**Comment by kalimuthu123** [comment]
it is mysql database

**Comment by KKcorps** [comment]
Hi,
Can you give the steps to reproduce the issue?
