### ISSUE TITLE
`HiveEngineSpec.get_view_names` returns empty list even if corresponding function is available for hive dialect

### ISSUE THREAD

**Issue by se7entyse7en** [apache/incubator-superset#8010]
**Is your feature request related to a problem? Please describe.**

The `HiveEngineSpec.get_view_names` returns empty list because `HiveEngineSpec` inherits from `PrestoEngineSpec` where `get_view_names` is set to return empty list. This is because https://github.com/dropbox/PyHive/blob/v0.6.1/pyhive/sqlalchemy_presto.py doesn't have a `get_view_names` function. But this function is available for https://github.com/dropbox/PyHive/blob/v0.6.1/pyhive/sqlalchemy_hive.py so it should make sense to call it. This prevents showing the list of the views in the SQL Editor tab.

**Describe the solution you'd like**

Add the following method to `HiveEngineSpec`:

```
    @classmethod
    def get_view_names(cls, inspector, schema):
        return BaseEngineSpec.get_view_names(inspector, schema)
```

**Describe alternatives you've considered**

None.

**Additional context**

I was able to actually test it in a [project](https://github.com/src-d/sourced-ui) that is based on superset. This project uses a [fork of PyHive](https://github.com/src-d/PyHive/) in order to support SparkSQL, and has an engine spec for SparkSQL (open PR at the time of writing) which is simply defined as follows:

```
class SparkSQLEngineSpec(HiveEngineSpec):
    """Reuses HiveEngineSpec functionality."""

    engine = "sparksql"
```

**Comment by villebro** [comment]
It seems for Hive `get_view_names()` calls `get_table_names()`, which leads me to conclude that tables would show up twice: https://github.com/dropbox/PyHive/blob/v0.6.1/pyhive/sqlalchemy_hive.py#L267_L270 Or am I missing something?

**Comment by se7entyse7en** [comment]
Honestly, I don't know Hive much, but AFAIU with the SQLAlchemy Hive dialect you cannot distinguish views and tables, so calling `get_view_names` or `get_table_names` will return both views and tables. I don't even know whether it will return both internal and external ones in addition to views.

Maybe @erizocosmico or @ajnavarro you can help with this? Please also have a look at [this references PR](https://github.com/src-d/sourced-ui/pull/244).
