### ISSUE TITLE
Issues after connecting to SQL Server database

### ISSUE THREAD

**Issue by pljabe** [apache/incubator-superset#8017]
After successfully(?) connecting to our SQL Server database and adding a Table, no columns are automatically detected (in contrast to doing the same with our Oracle database)
Trying to create a chart after manually adding columns produces an empty query

### Expected results

Columns are automatically detected, able to create a chart

### Actual results

No columns detected, unable to create chart
Logs of the latter problem:

ERROR:root:Empty query?
Traceback (most recent call last):
  File "/home/superset/superset/views/base.py", line 121, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/home/superset/superset/views/core.py", line 1119, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/home/superset/superset/views/core.py", line 1046, in generate_json
    payload = viz_obj.get_payload()
  File "/home/superset/superset/viz.py", line 372, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/home/superset/superset/viz.py", line 388, in get_df_payload
    cache_key = self.cache_key(query_obj, **kwargs) if query_obj else None
  File "/home/superset/superset/viz.py", line 365, in cache_key
    cache_dict["extra_cache_keys"] = self.datasource.get_extra_cache_keys(query_obj)
  File "/home/superset/superset/connectors/sqla/models.py", line 1071, in get_extra_cache_keys
    sqla_query = self.get_sqla_query(**query_obj)
  File "/home/superset/superset/connectors/sqla/models.py", line 657, in get_sqla_query
    raise Exception(_("Empty query?"))
Exception: Empty query?

#### How to reproduce the bug

1. Go to 'Sources -> Databases'
2. Click on 'Add a new record'
3. Enter your SQLAlchemy URL
4. Click on 'Test Connection' -> 'Seems OK!'
5. Go to 'Sources -> Tables'
6. Click on 'Add a new record'
7. Enter the name of a table present on your database
8. No columns are present

### Environment

(please complete the following information):

- superset version: Superset 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.16.0
- npm version: 6.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I can query all columns using the SQL Lab editor, yet I can't manage to create a chart even if I manually add the columns in 'Sources -> Tables'
Everything works fine for my Oracle database

**Comment by villebro** [comment]
There seems to be several problems with MSSQL right now, will look into this and others shortly.

**Comment by villebro** [comment]
I am unable to reproduce this. What MSSQL connector are you using? It seems like this might be a problem with permissions.

**Comment by pljabe** [comment]
I am using pymssql, which permissions do you suggest I check? SQL Lab is able to get all the table/column information I would expect it to get

**Comment by pljabe** [comment]
My user has the permissions "CONNECT SQL", "VIEW ANY DATABASE" and "VIEW ANY DEFINITION"
