### ISSUE TITLE
No module named superset.__main__ when using "superset db upgrade"command

### ISSUE THREAD

**Issue by KevalShah10** [apache/incubator-superset#8019]
When I am using this command, it isnt working right. And it is showing the following error.

![image](https://user-images.githubusercontent.com/8938655/62809874-d4c88b80-bb19-11e9-970b-f3e2874f715d.png)

### Expected results

This command should run.

### Actual results

This error shows: 

E:\KevTest\venv\Scripts\python.exe: No module named superset.\__main__; 'superset' is a package and cannot be directly executed

### Environment

- superset version: `28.1`
- python version: `3.6.3`
- Windows 10

**Comment by etr2460** [comment]
Try just running `superset db upgrade` without the `python -m` part?

**Comment by KevalShah10** [comment]
> 
> 
> Try just running `superset db upgrade` without the `python -m` part?

@etr2460,
That doesn't work either. It shows "superset" is not recognized as a command. It comes up with the following error:

_'superset' is not recognized as an internal or external command,
operable program or batch file._

**Comment by SamerAlrantawy** [comment]
try to type python before any superset command 
ex : python superset db upgrade

**Comment by sedhha** [comment]
> try to type python before any superset command
> ex : python superset db upgrade

This works! Thanks man
