### ISSUE TITLE
feat: Add row level security

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#8023]
Superset need Row Level Security！！！
    In issues, this problem has been raised many times. It seems that it is a common problem for all of us and needs to be solved urgently. This will allow superset to grow rapidly and reach the product.
    Hope the Superset have Permission manage （access rule，action rule，model rule，field rule，record rule，view rule and menu rule）like Odoo（erp），example:

![rule](https://user-images.githubusercontent.com/1625023/62828342-61587400-bc16-11e9-8cde-8100afb2724d.png)

![QQ图片20190811085122](https://user-images.githubusercontent.com/1625023/62828378-6f5ac480-bc17-11e9-888a-42a165cebdb8.png)

![QQ图片20190811085122](https://user-images.githubusercontent.com/1625023/62828348-a11f5b80-bc16-11e9-9d98-4f3bf7c9b37e.png)

![object-rule](https://user-images.githubusercontent.com/1625023/62828365-2571de80-bc17-11e9-8a45-7221617da7af.png)

**Comment by toop** [comment]
@mistercrunch

**Comment by toop** [comment]
superset need row level permission ！

**Comment by cyw233** [comment]
superset need row level permission!

**Comment by toop** [comment]
superset need row level permission!

**Comment by toop** [comment]
Thank U！！！

**Comment by toop** [comment]
@justin-barton :
There are security problems in this plan: Use query filters to allow access to attribute values ,The current login user can delete the filter conditions in the query. If you do not give explore permission, the current user will lack the explore interaction function.

**Comment by mistercrunch** [comment]
Check out https://github.com/apache/incubator-superset/pull/8699
