### ISSUE TITLE
hive/impala  can't show table schema

### ISSUE THREAD

**Issue by shadowera** [apache/incubator-superset#8027]
I use url  impala://host:port/   like this to connect to hive database , the connect is ok , and I can execute sql in the sql lab . But  'See table schema' don't seem right , it shows the databaseName not the tabels.See the screenshot for detail.

## Screenshots

See table schema should show tables but actually the databaseName.And the
![image](https://user-images.githubusercontent.com/16278112/62843654-0abe6900-bcee-11e9-8808-a5f9a8cc7499.png)
And when clicked  at  the item ,it comes out the error
![image](https://user-images.githubusercontent.com/16278112/62843816-75bc6f80-bcef-11e9-9b3c-f47ea33a20f3.png)
#### the console:
impala.hiveserver2:GetOperationStatus: resp=TGetOperationStatusResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), operationState=5, sqlState=None, errorCode=0, errorMessage="org.apache.spark.sql.AnalysisException: Table or view not found: `scannetwork`.`scannetwork`; line 1 pos 14;\n'GlobalLimit 0\n+- 'LocalLimit 0\n   +- 'Project [*]\n      +- 'UnresolvedRelation `scannetwork`.`scannetwork`\n")

#### when I excute ' show tables', it shows the right result as follows
![image](https://user-images.githubusercontent.com/16278112/62843689-55d87c00-bcee-11e9-8bbb-49e80eed4333.png)

##Environment:

Superset 0.28.1
node.js  v10.15.0
npm 6.4.1
impyla  0.15.0+2.ge4f2146
SQLAlchemy  1.2.7

**Comment by shadowera** [comment]
I guess the 'See table schema' just take the 1st row as tableName .However here turns out to be the databaseName ...
What can I do to fix it .

**Comment by villebro** [comment]
Hmm, according to the docs `SHOW TABLES` should only return the table name in the first column, not what you're seeing. Perhaps the fact that you're mixing Hive with Impala might be the cause?

https://www.cloudera.com/documentation/enterprise/5-8-x/topics/impala_show.html#show_tables

**Comment by shadowera** [comment]
well, it's a matter about sparksql .
it's finally solved by 
edit site-packages/impala/sqlalchemy.py 
from 
```
def get_table_names(self, connection, schema=None, **kw):
    query = 'SHOW TABLES'
    if schema is not None:
        query += ' IN %s' % schema
    rreturn [tup[0] for tup in connection.execute(query).fetchall()]
```
to 
```
    def get_table_names(self, connection, schema=None, **kw):
        query = 'SHOW TABLES'
        if schema is not None:
            query += ' IN %s' % schema
        return [t[1] if len(t) >1  else t[0] for t in connection.execute(query).fetchall()]
```

**Comment by fan-code** [comment]
> well, it's a matter about sparksql .
> it's finally solved by
> edit site-packages/impala/sqlalchemy.py
> from
> 
> ```
> def get_table_names(self, connection, schema=None, **kw):
>     query = 'SHOW TABLES'
>     if schema is not None:
>         query += ' IN %s' % schema
>     rreturn [tup[0] for tup in connection.execute(query).fetchall()]
> ```
> 
> to
> 
> ```
>     def get_table_names(self, connection, schema=None, **kw):
>         query = 'SHOW TABLES'
>         if schema is not None:
>             query += ' IN %s' % schema
>         return [t[1] if len(t) >1  else t[0] for t in connection.execute(query).fetchall()]
> ```

 the path 'site-packages/impala/sqlalchemy.py'  doesn't exsit if you just install pyhive,. So how to edit it?
