### ISSUE TITLE
histogram must be str not list

### ISSUE THREAD

**Issue by Foristkirito** [apache/incubator-superset#8028]
I want to use a table to generate his graph, but get the below error: 

```text
Traceback (most recent call last):
  File "/home/superset/superset/views/base.py", line 122, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/home/superset/superset/views/core.py", line 1417, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/home/superset/superset/views/core.py", line 1349, in generate_json
    payload = viz_obj.get_payload()
  File "/home/superset/superset/viz.py", line 374, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/home/superset/superset/viz.py", line 389, in get_df_payload
    query_obj = self.query_obj()
  File "/home/superset/superset/viz.py", line 1468, in query_obj
    d["columns"] = numeric_columns + self.groupby
TypeError: must be str, not list
```

here is my example table

![image](https://user-images.githubusercontent.com/13299109/62844977-9f799480-bcf7-11e9-89f1-8a9fd0f46df1.png)

and my config:

![image](https://user-images.githubusercontent.com/13299109/62845010-c59f3480-bcf7-11e9-9f6d-841df2c32710.png)

**Comment by kuckjwi0928** [comment]
I think the HistogramViz class needs to be modified to the format below.

https://github.com/kuckjwi0928/incubator-superset/commit/c9b1c110a09873212a953299f798662eacbc4f44

**Comment by Foristkirito** [comment]
> I think the HistogramViz class needs to be modified to the format below.
> 
> [kuckjwi0928@c9b1c11](https://github.com/kuckjwi0928/incubator-superset/commit/c9b1c110a09873212a953299f798662eacbc4f44)

this retrieved the data, but caused another exception when rendering the chart:

![image](https://user-images.githubusercontent.com/13299109/63395885-d470a000-c3f7-11e9-8823-d23666f8e703.png)

**Comment by kuckjwi0928** [comment]
> > I think the HistogramViz class needs to be modified to the format below.
> > [kuckjwi0928@c9b1c11](https://github.com/kuckjwi0928/incubator-superset/commit/c9b1c110a09873212a953299f798662eacbc4f44)
> 
> this retrieved the data, but caused another exception when rendering the chart:
> 
> ![image](https://user-images.githubusercontent.com/13299109/63395885-d470a000-c3f7-11e9-8823-d23666f8e703.png)

I've reviewed it, When visualization type change occurs after refresh, chart rendering is executed even though no query is set.

From the second try, it will work normally.

This requires checking not only the histogram but also other charts.

**Comment by Foristkirito** [comment]
> > > I think the HistogramViz class needs to be modified to the format below.
> > > [kuckjwi0928@c9b1c11](https://github.com/kuckjwi0928/incubator-superset/commit/c9b1c110a09873212a953299f798662eacbc4f44)
> > 
> > 
> > this retrieved the data, but caused another exception when rendering the chart:
> > ![image](https://user-images.githubusercontent.com/13299109/63395885-d470a000-c3f7-11e9-8823-d23666f8e703.png)
> 
> I've reviewed it, When visualization type change occurs after refresh, chart rendering is executed even though no query is set.
> 
> From the second try, it will work normally.
> 
> This requires checking not only the histogram but also other charts.

I figure it out that no need to do anything, just refresh the site. thx for your help
