### ISSUE TITLE
superset db upgrade pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by babybear1992** [apache/incubator-superset#8036]
I follow the [instructions](https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization) to install superset. After installation, I execute the command `superset db upgrade`, the following error occurs:
`pkg_resources.ContextualVersionConflict: (Flask 0.12.4 (/root/miniconda3/envs/ss/lib/python3.6/site-packages), Requirement.parse('Flask>=1.0'), {'Flask-JWT-Extended'})`
I am confused and don't know how to slove this issue. Is there any guidance that I can reference to? 

### Screenshots
The screenshot is as below
![Screen Shot 2019-08-13 at 5 03 08 PM](https://user-images.githubusercontent.com/9087918/62929091-52c3b580-bdec-11e9-817c-98921668b7e8.png)

### Environment
- superset version: `0.28.1`
- python version: `3.6.7`
- Flask version: `0.12.4`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [-] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [-] I have reproduced the issue with at least the latest released version of superset.
- [-] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mikefab** [comment]
Solved this with:
pip install flask==1.0.0

Ran into second problem, forgot what the error was. Solved with:
pip install sqlalchemy==1.2.18

**Comment by babybear1992** [comment]
> Solved this with:
> pip install flask==1.0.0
> 
> Then ran into: "Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity."
> Solved with:
> 
> pip install sqlalchemy==1.2.18
> thanks to: [#6977 (comment)](https://github.com/apache/incubator-superset/issues/6977#issuecomment-469636503)

Thanks, it worked finally!
