### ISSUE TITLE
Chart on dashboard still showing even "No data"

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#8043]
#### Expected results

Chart not showing when `No data` displayed

### Actual results

Chart still showing on dashboard

#### Screenshots

![Screenshot from 2019-08-14 08-54-54](https://user-images.githubusercontent.com/28984703/62987333-d2e02e80-be71-11e9-9dc0-df584f6e89bf.png)

#### How to reproduce the bug

1. Create chart on dashboard
2. Filter chart based on Time range `Last day`
3. Chart will show `No data` but the chart is still there

### Environment

- superset version: `0.28.1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by MarcusSorealheis** [comment]
@syazwan0913 I will try to reproduce and fix
