### ISSUE TITLE
Dashboard emails/chart emails schedules menu not showing up with master branch code

### ISSUE THREAD

**Issue by suvarnaC** [apache/incubator-superset#8048]
The Dashboard emails/Chart emails schedule menu is not showing up even after config file is edited with email specific settings. Only seen in latest master branch code that i deployed.
### Expected results
The menu should be visibile if we enable email in the config.py file

### Actual results
No menus showsn

#### Screenshots

![image](https://user-images.githubusercontent.com/51064489/63052060-73534480-beac-11e9-9729-681f4d361c40.png)

#### How to reproduce the bug

1. get latest master code from github and deploy it
2. Edit config.py and enable email
3. Login to superset and Click on manage menu
4. No email specific menus shown

### Environment

(please complete the following information):

- superset version: master
- python version: 3.6.8
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ericandrewmeadows** [comment]
@suvarnaC - this feature is working properly in v0.33.0rc1 - please use that, as I have been using it in production and it is stable.

**Comment by suvarnaC** [comment]
@ericandrewmeadows 
Does v0.33.0rc1 also have publish feature included?

**Comment by ericandrewmeadows** [comment]
Yes, and it seems to work perfectly.

**Comment by bzmatteo72** [comment]
I have the same issue with version 0.37.1
Please anyboby can provide help with this problem?
Thanks
Regards
Matteo
