### ISSUE TITLE
Some pages are missing <!doctype html> causing css to fail

### ISSUE THREAD

**Issue by REmango** [apache/incubator-superset#8050]
This bug has appeared in previous versions, but it has not been fixed.

### Superset version
0.28.1

### Performance on Chrome
In the project, missing <!DOCTYPE html> will cause ‘line-height’ to fail in some cases.

###  Affected page
sqllab, dashboard, explore, addSlice  etc.

### fix bug
Add <!DOCTYPE html> on basic.html

**Comment by MarcusSorealheis** [comment]
@REmango Which cases? Can you be more specific?
