### ISSUE TITLE
How to build custom color scheme in @superset-ui/color?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#8064]
#### Environment

- superset version: `0.34.0rc1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

**Comment by LilianXie** [comment]
superset\static\assets\src\modules\colorSchemes   add your schemes
superset\static\assets\src\common.js   register your color schemes
superset\static\assets\src\controls.jsx set default color scheme
hope can help you

**Comment by syazwan0913** [comment]
Thanks but I am using version `0.34.0rc1`. 
All of the path don't have in that version

> superset\static\assets\src\modules\colorSchemes add your schemes
> superset\static\assets\src\common.js register your color schemes
> superset\static\assets\src\controls.jsx set default color scheme
> hope can help you

**Comment by LilianXie** [comment]
Actually I get the src folder from github one month ago, can you find the src folder? Maybe it is in superset/assets/

**Comment by LilianXie** [comment]
superset\static\assets\src\explore\common.js register your color schemes
superset\static\assets\src\explore\controls.jsx set default color scheme
sorry miss the explore

**Comment by syazwan0913** [comment]
Actually color scheme is bundled in the node modules
![Screenshot from 2019-08-19 16-35-59](https://user-images.githubusercontent.com/28984703/63251003-716bf580-c29f-11e9-98e8-984424c8b0f4.png)

Not in the path you mentioned
