### ISSUE TITLE
Time filter in dashboard take effect on all slices

### ISSUE THREAD

**Issue by LilianXie** [apache/incubator-superset#8065]
Time filter in dashboard take effect on all slices even though slices have different datasources.
How can I let the filter take effect on the particular slices which used the same datasource?

**Comment by justin-tomlinson** [comment]
Im not sure about limiting it on a datasource basis but you can make certain slices on a dashboard immune from certain filters. The FAQ section of the docs covers the details of this. https://superset.incubator.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard
