### ISSUE TITLE
Editing a saved query  in the sql_lab generate the new one instead of overwrite it!

### ISSUE THREAD

**Issue by blcksrx** [apache/incubator-superset#8068]
When you want to edit a saved query with sql_lab and when you edit the query and click on the save query button in the sql_lab to save the query, superset makes a new query instead of overwriting the query!
So here is the bug! when I want to edit a saved query and make changes on it, I will get to the  Saved Queries pages and I will click on the pop-up link to route the sql_lab to modify the query instead of using the edit button on the saved query page. 
why should I or other users do this? here are the reasons:

1. Users create and develop the queries on the sql_lab page, so when a user wants
   to modify the query the user habit is to modify it on the sql_lab!
2. Users want to run and test the query when they are modifying it, so the edit page of the saved query is no absolutely sufficient!
3. sql_lab provides more functionality than the edit the record on the saved queries.
  
So my approach to solving this issue is that the saved query will be able to modify on the sql_lab, it's simple!

### Expected results

overwrite the edited query

### Actual results

Create the new record(query)

#### How to reproduce the bug

1. Go to the saved query page. 
2. Click on the pop-up link of any query that you want
3. modify the query and click on the save query button
4. See the saved queries page again.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rubypollev** [comment]
Yeah, this one is quite difficult to work with. Is this a feature or a bug? Hoping it's a bug.

**Comment by blcksrx** [comment]
I think it's absolutely a bug! and I'm currently  waiting for commiters response

**Comment by blcksrx** [comment]
Thanks! I was waiting for the commiters to approve this issue and then make a PR!
