### ISSUE TITLE
Unable to grant per datasource/schema access with 0.34.0rc1

### ISSUE THREAD

**Issue by bobelev** [apache/incubator-superset#8081]
Original issue.
https://github.com/apache/incubator-superset/issues/7554

You can't use SQL Lab if you don't grant `database` permission to user. It makes superset unusable with `per datasource` access model. You can still see dashboards, but you can't manually query any data.

If you add `database` permission, user can access all tables in database which is not acceptable.

### Expected results

See all available database/schema/table in SQL Lab based on granted datasource access.

### Actual results

SQL Lab dropdowns are empty.

#### How to reproduce the bug

- create user
- grant it only datasource permission without database access.

**Comment by bkyryliuk** [comment]
Looks like it was introduced here: https://github.com/apache/incubator-superset/commit/b65ab51b63200139947d9ee4b3ba80ef263a3e88

Database filter ignores user schema / datasource permissions: https://github.com/apache/incubator-superset/blame/d58dbad076f61cfd05fa8280ad13442d29360873/superset/views/database/__init__.py#L34

**Comment by Wuyl-matt** [comment]
I had the same problem:
![15_15_12__09_06_2019](https://user-images.githubusercontent.com/28914440/64408392-3c420e80-d0b9-11e9-8032-e51bce912b27.jpg)

grant the user only datasource permission without database access.
How to change the permission of user?

**Comment by dpgaspar** [comment]
@bkyryliuk on a quick check, seems unrelated with the commit you reference since I used the same existing filter that was applied before.

**Comment by nabhosal** [comment]
Any updates on this issue. 
Instead of the database, we gave permission on the schema. Still, all tables under a schema are accessible.
