### ISSUE TITLE
504 gateway time-out for long running presto queries

### ISSUE THREAD

**Issue by rohanmonga** [apache/incubator-superset#809]
After 50 seconds our queries timeout ( see screenshot ). Is there a configuration that i can change to keep waiting until the query finishes?
![504](https://cloud.githubusercontent.com/assets/4732481/17064677/9debc284-4ff2-11e6-8468-1888c56798e1.png)

**Comment by xrmx** [comment]
*caravel --help* may give you some hints on how to fix that.

**Comment by rohanmonga** [comment]
if you mean  `caravel runserver --timeout` then i've already set that to 3000

**Comment by xrmx** [comment]
@rohanmonga if it's not gunicorn, do you have any backtrace in caravel logs?

**Comment by mistercrunch** [comment]
There's a timeout flag in the runserver command. Try:
`caravel runserver -t 600`

**Comment by rohanmonga** [comment]
@mistercrunch I am running it with `-t 3000`. the query is still running and when it finishes it gets cached as well. the frontend seems to be timing out

@xrmx there is nothing in caravel logs

**Comment by rohanmonga** [comment]
can i help figure out this issue in anyway ?

**Comment by desavera** [comment]
Hey Folks, I am getting the same error ... is it a Presto issue or Superset ???

**Comment by mistercrunch** [comment]
Do you have a proxy in front of gunicorn? If so your proxy is timing out.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 325 days. Feel free to comment and request for this issue to be reopened.
