### ISSUE TITLE
I want to change title of charts

### ISSUE THREAD

**Issue by sandy-ha** [apache/incubator-superset#8090]
**Is your feature request related to a problem? Please describe.**
I can't change or hide the title of the title. It bothers me that the name of the chart is used. I would like to name the charts after my convention. For example, if I need the same dashboard in different languages, I could use a language specific title but I could name the charts with a part that is the same for all identical charts and the unique part for the language. 

**Describe the solution you'd like**
I need an additional field for the title of the chart.

**Describe alternatives you've considered**
The ability to use a data table to get the language-specific titles and descriptions for the set language of the dashboard.

**Additional context**

**Comment by tcopple** [comment]
+1 Any ability to delineate between the convention I use to name my charts in the application and the title of the chart on a dashboard would be valuable.

**Comment by OrwaRebootMob** [comment]
This is currently possible and easily achieved by clicking on the title in the dashboard and renaming it there, which does not effect the actual name of the chart which appears in the list of charts:
![image](https://github.com/apache/superset/assets/158479183/778b9863-54a8-4bbc-9681-897de8c4fdfc)
