### ISSUE TITLE
Write custom backend logic for visualizing superset graphs

### ISSUE THREAD

**Issue by uchihaabhijit** [apache/incubator-superset#8092]
Is there a way I can write some custom logics on my data coming from HIVE database and then visualizing the output in superset. My application demands writing some logics with libraries like numby/scipy and then doing some calculations. I am very new to superset. 

Thanks

**Comment by bilalaayush** [comment]
@uchihaabhijit  I would suggest pre-aggregate your data, using your custom Python logic, into a materialized view and then query the view from superset. Let me know if this helps.

**Comment by uchihaabhijit** [comment]
@ayushbilala That is what I am currently struggling at. Where do I put the python code, the route and the view inside the superset directories ??
