### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by mcdallas** [apache/incubator-superset#8095]
setup.py requires flask <1.0.0 while flask-appbuilder requires Flask-JWT-Extended which requires flask >=1.0.0

as a result `pipenv install superset` fails with 

```
ERROR: Could not find a version that matches flask<1.0.0,<2,>=0.10,>=0.10.1,>=0.12,>=0.9,>=1.0
Tried: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11, 0.11.1, 0.11.1, 0.12, 0.12, 0.12.1, 0.12.1, 0.12.2, 0.12.2, 0.12.3, 0.12.3, 0.12.4, 0.12.4, 1.0, 1.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.1.0, 1.1.0, 1.1.1, 1.1.1
```

related #4953

### Environment

Tried on MacOS with python 3.7.4 and 3.6.5

**Comment by mistercrunch** [comment]
Did you install from the repo or from pypi?

**Comment by mcdallas** [comment]
I installed from pypi using pipenv which is a wrapper around pip

**Comment by dmitrypol** [comment]
workaround:
```
```
