### ISSUE TITLE
User flow to request Acces to Dashboard

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#810]
It's a bit tricky / heavy for content creators to provide access to Dashboards.

When users open a link to a dashboard or slice they don't have access to, here are a few things that could happen:
- Error message
- Request access button, maybe a field to specify which Admin user should get notified
- A row is added in a AccessRequest model
- Admins can go to the crud view for AccessRequest and see a list of request, filter to requests meant for them (or not), check a bunch of boxes of what they want to approve, and approve a set

There's a choice on whether the datasource perm should be added to one of the user's role, or if a new role that has the datasource should be added to the user's profile...

**Comment by aibati2008** [comment]
it's a wondeful feature if it can complete, then the access management can be more easily..

**Comment by shashvattrip** [comment]
Is anyone working on this? Would be wonderful to be able to give access to single/multiple dashboards to different users!
