### ISSUE TITLE
Investigate broken Custom Security Manager

### ISSUE THREAD

**Issue by ericandrewmeadows** [apache/incubator-superset#8110]
I have made sufficient comments, and instead of sweeping this under the rug, it should be looked at - CSM is broken because redirection does not work properly - it works in 0.33.0rc1, but not 0.34!

https://github.com/apache/incubator-superset/issues/8062

**Comment by ericandrewmeadows** [comment]
I would put the version tag in, but the issue creator does not let me tag - FYI.

**Comment by MarcusSorealheis** [comment]
can you elaborate on what you mean by "redirection doesn't work properly" and what are the steps to reproduce?

**Comment by ericandrewmeadows** [comment]
@MarcusSorealheis - I posted the other ticket.

When you attempt to use a Custom Security Manager, it goes direct to the Welcome page, bypassing the login page.  Since the user in my CSM is neither logged-in nor authorized, the page is unreachable.

On 0.33.0rc1 all redirections work as expected - when you navigate to the root url, it redirects to the login, attempts to auth, and then once authenticated, redirects to welcome.
