### ISSUE TITLE
Time Series Bars Visualization not decending when set

### ISSUE THREAD

**Issue by hughhhh** [apache/incubator-superset#8112]
Bar chart timeseries visalization order descending control doesn't work

### Expected results

All bars in the chart should be sorted descending with the control set

### Actual results

The bar orderings don't change at all

#### Screenshots

<img width="1584" alt="Screen Shot 2019-08-24 at 10 59 19 PM" src="https://user-images.githubusercontent.com/27827808/63646154-d4f08b80-c6c2-11e9-82a6-b370c59c103f.png">

#### How to reproduce the bug

1. Go to an explore view
2. Click on 'visualization type' and pick timeseries bar chart
3. Select sort descending on the controls to the left.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by MarcusSorealheis** [comment]
@hughhhh Can you answer the version questions?
