### ISSUE TITLE
superset conn hive faied

### ISSUE THREAD

**Issue by celestewang1026** [apache/incubator-superset#8114]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `0.30`
- python version: `3.7.2`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

python                3.7.2
PyHive                 0.6.1
impyla                 0.14.1

superset conn impala is good,but when conn is wrong ,have the below quetsion

source-->databases-->
![image](https://user-images.githubusercontent.com/16298783/63680308-e900ce00-c825-11e9-8f5a-b0cd0a4d5f1e.png)

the question is TCLIService confict,but how to fix it

**Comment by MarcusSorealheis** [comment]
@celestewang1026 you need to provide a bit more information. Can you share the connection string (URI) you used? Also, are you certain that you are using version 0.6.1 in the case of PyHive? Depending on you have started that version you may not be.

**Comment by celestewang1026** [comment]
> @celestewang1026 you need to provide a bit more information. Can you share the connection string (URI) you used? Also, are you certain that you are using version 0.6.1 in the case of PyHive? Depending on you have started that version you may not be.

yes,I'm sure then version of PyHive is  0.6.1。Before connect hive,I have been connect impala successfuly.the uri is [hive://root@192.168.44.131:10000/tmp?]

**Comment by zhaoyongjie** [comment]
@celestewang1026 please show more superset.log, and double check restart Superset service

**Comment by celestewang1026** [comment]
> @celestewang1026 please show more superset.log, and double check restart Superset service

![image](https://user-images.githubusercontent.com/16298783/64951163-cbb4a200-d8af-11e9-983b-beff4ab36a2f.png)

**Comment by celestewang1026** [comment]
> @celestewang1026 please show more superset.log, and double check restart Superset service

the log is that when run on the sql lab

**Comment by zhaoyongjie** [comment]
@celestewang1026  Try this steps
1.  stop Superset process
2. activate virtual environment if you use it
3. pip uninstall pyhive
4. pip install --force-reinstall --no-cache-dir --upgrade pyhive
5. restart Superset process

**Comment by celestewang1026** [comment]
> @celestewang1026 Try this steps
> 
> 1. stop Superset process
> 2. activate virtual environment if you use it
> 3. pip uninstall pyhive
> 4. pip install --force-reinstall --no-cache-dir --upgrade pyhive
> 5. restart Superset process

sorry to say it's not work unless pip uninstall impyla.

Another question the table has a column that's type is array,but it can not show
![image](https://user-images.githubusercontent.com/16298783/65007818-d156ca00-d939-11e9-9e3f-2640b3d88493.png)



![image](https://user-images.githubusercontent.com/16298783/65007853-f0edf280-d939-11e9-854e-db761b34775b.png)

**Comment by celestewang1026** [comment]
> > @celestewang1026 Try this steps
> > 
> > 1. stop Superset process
> > 2. activate virtual environment if you use it
> > 3. pip uninstall pyhive
> > 4. pip install --force-reinstall --no-cache-dir --upgrade pyhive
> > 5. restart Superset process
> 
> sorry to say it's not work unless pip uninstall impyla.
> 
> Another question the table has a column that's type is array,but it can not show
> ![image](https://user-images.githubusercontent.com/16298783/65007818-d156ca00-d939-11e9-9e3f-2640b3d88493.png)
> 
> ![image](https://user-images.githubusercontent.com/16298783/65007853-f0edf280-d939-11e9-854e-db761b34775b.png)

Is it convenient for you to provide wechat ?
