### ISSUE TITLE
pypi repo is outdated

### ISSUE THREAD

**Issue by AntonyLeons** [apache/incubator-superset#8120]
### Motivation

pip currently installs superset 28.1 which is outdated, 
https://pypi.org/project/superset/#history
with the last update being a pre-release in 2018
The older version has bugs which have been fixed in newer releases, this causes issues as you would expect the pypi repo to be maintained as it is part of the documentation.

### Proposed Change

update the pypi repo to the latest release or update documentation to reflect that pip installs version 28.1.

**Comment by francishemingway** [comment]
PyPI now has the latest version :-) 
https://pypi.org/project/apache-superset/
