### ISSUE TITLE
Error 401 : There was an issue fetching the favorite status of this dashboard

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#8121]
When opening a dashboard, "There was an issue fetching the favorite status of this dashboard" appears at the bottom.

Looks like issue #6824 : same message displayed, but different "cause" : web console shows a 401 error (unauthorized), whereas in 6824 there was a https->http redirect which is now fixed. 

### Expected results

No warning message when opening a dashboard, favorite status managed without issue

### Actual results

"There was an issue fetching the favorite status of this dashboard" appears at the bottom.

Error 401 in console.

#### Screenshots

![superset-2019-08-27 12-05-46 screenshot](https://user-images.githubusercontent.com/4623644/63762460-19e31080-c8c3-11e9-854a-3c4882782c91.png)

#### How to reproduce the bug

1. Go to Dashoboard page
2. Click on any dashboard
3. See error

### Environment

- superset version: master branch as of 2019 08 27  9 AM GMT
- python version: 3.6
- node.js version: 12.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Running from a docker container, built using Dockerfile essentially identical to  amancevice:superset one.

**Comment by kuckjwi0928** [comment]
Did you run the superset init command?

If you do not, you must execute the following command before running

`superset init`

**Comment by squalou** [comment]
Damn ! indeed.
Must have forgotten it. (spent so long restarting different versions, obviously forgot it).

Thank you !

Additionally : would it be safe to run 'superset init' at each startup of any occurrence of running container ? (lke, by putting it in entrypoint or something ?)

**Comment by kuckjwi0928** [comment]
Default permissions will be created when superset init is performed.
~~~python
def init():
   """Inits the Superset application""
    utils.get_or_create_main_db()
    utils.get_example_database()
    appbuilder.add_permissions(update_perms=True)
    security_manager.sync_role_definitions()
~~~

If you are using a single DB, have you modified the SQLALCHEMY_DATABASE_URI setting?

**Comment by squalou** [comment]
indeed, SQLALCHEMY_DATABASE_URI points to an external DB, but each superset instances points to the same.
Is there anything else I should pay attention to, when using this setup?

(these superset instances are behind a load balancer, for redundancy, since sometimes they crash)

**Comment by squalou** [comment]
Closing this, as anyway it's no more related to the initial issue.
Fix works great.
