### ISSUE TITLE
Pivot Table Time Column  Time Grain not working 

### ISSUE THREAD

**Issue by 77creating** [apache/incubator-superset#8131]
Version: 0.28.1
DB       :Oracle

hi all 
       i meet a problem is the Time Grain not working on Visualization Type Pivot Table ,but on Type Time Seriese is working. 

<img width="942" alt="57BE7039-E75B-410a-8567-E967D01E72AF" src="https://user-images.githubusercontent.com/3654679/63822960-af92a480-c984-11e9-962d-c3356a9496cc.png">

I found that the pivot table is different from the SQL of the Time Series on time column.
the pivote table is create_time 
the Time Series is trunc(create_time,'DD')

**Comment by 77creating** [comment]
Issue Has been resolved by Generate a new column where copy from time column

**Comment by Hchiker** [comment]
> 
> 
> Issue Has been resolved by Generate a new column where copy from time column

Hello, I am encountering the same problem ( with the pivot visualization, it does not apply the defined time grain period ) and I tried to use your workaround but it does not seem to work in my case. May you please give more details about your solution?

Many thanks!
