### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#8132]
### Expected results

Chart from Highcharts showing on dashboard. 

### Actual results

TypeError: Cannot read property '0' of undefined

#### Screenshots

Chart on Dashboard
![2](https://user-images.githubusercontent.com/28984703/63832554-9a793e00-c9a3-11e9-81d0-ab9ce1f51955.PNG)

From inspect element:
![inspect](https://user-images.githubusercontent.com/28984703/63832646-d7453500-c9a3-11e9-9553-cc590c0014cc.PNG)

### Environment

- superset version: `0.34.0rc1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`
- highcharts version: `7.1.1`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Before this, Highcharts is implemented on superset `0.28.1` and no problem with the Highcharts. I tried to migrate the Highcharts into superset version `0.34.0rc1`.

**Comment by always-busy** [comment]
I have the same probelm "TypeError: Cannot read property '1' of undefined"
