### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by nisjojo** [apache/incubator-superset#8133]
when  I install the superset ,  
the error is 
ERROR: flask-jwt-extended 3.21.0 has requirement Flask>=1.0, but you'll have flask 0.12.4 which is incompatible.

when 
  superset db upgrade
ERROR: superset 0.28.1 has requirement flask<1.0.0, but you'll have flask 1.0 which is incompatible.

so can you agree on the same version?

**Comment by 17602558849** [comment]
Try this command : pip install Flask-JWT-Extended==3.20.0
i have tried,and it is useful.

**Comment by dpgaspar** [comment]
You should use the pinned dependencies from `requirements.txt`, update/recreate using `pip install -r requirements.txt`
