### ISSUE TITLE
No module named 'msgpack'

### ISSUE THREAD

**Issue by suooly** [apache/incubator-superset#8134]
superset/views/core.py， 43 lines of this file, No module named'msgpack'。

![image](https://user-images.githubusercontent.com/8542132/63844696-33678380-c9bb-11e9-8e1a-099d135ff42a.png)

**Comment by dpgaspar** [comment]
Hi @suooly,

This dependency is referenced on `requirements.txt` and `setup.py`
- https://github.com/apache/incubator-superset/blob/master/setup.py#L87
- https://github.com/apache/incubator-superset/blob/master/requirements.txt#L52

You can update your virtualenv by: `pip install -r requirements.txt`

**Comment by suooly** [comment]
> * https://github.com/apache/incubator-superset/blob/master/requirements.txt#L52

Thanks♪(･ω･)ﾉ
