### ISSUE TITLE
log retention / deletion

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#8155]
**Is your feature request related to a problem? Please describe.**

'logs' tables may be useful, but tend to grow up. I need an easy way to clean them regularly

NOTE : maybe the feature exists, in which cas I'm really sorry to have overlooked it.

**Describe the solution you'd like**

Ideally, in superset administration GUI, a rule to delete logs after x days

**Describe alternatives you've considered**

cron job on my server to delete data ... which is a bad workaround in a serverless setup

**Additional context**

**Comment by ramyarajasekaran** [comment]
any update on this?

**Comment by Deninc** [comment]
+1 @squalou how did

**Comment by matschaffer-roblox** [comment]
Incase it helps anyone I ended up just doing this after taking a backup:

```
while true; do
  TZ=UTC date
  echo starting batch
  mysql (connection info) -e 'DELETE FROM logs WHERE `dttm` < (NOW() - INTERVAL 90 DAY) LIMIT 1000000;'
  echo sleeping 5min
  sleep 300
done
```

The downside is that this doesn't really _free_ space but it should (I think) allow new logs to reuse the blocks left open from the deletions.

For our DB each deletion of 1 million took about 1 minute to complete. I tested a select & insert while running and they worked fine, so I don't think this will cause locking issues since nothing (afaik) is attempting to update rows in the logs table.

**Comment by matschaffer-roblox** [comment]
I suspect a better way to do this would to include monthly partitioning on the logs table so you could periodically truncate all older month partitions.

**Comment by LeoDiep** [comment]
+1 
please show me how to delete the log table, where is it?

**Comment by gugacavalieri** [comment]
Hi! Found another alternative to move the logs to another destination.

https://github.com/apache/superset/issues/15548#issuecomment-2315956101

**Comment by squalou** [comment]
there still is this usecase where ... I do want my logs in a table (so, no json workaround possible), and still have no native solution to rotate / clean the logs.  That's weird.

**Comment by gugacavalieri** [comment]
Agreed @squalou, without a native solution to clean up logs there could be a big risk for downtime when that table gets full. I still personally believe that logs should not be written to the DB but if that is an use case for anyone, the solution should be shipped (by default) with more reliability in mind.
