### ISSUE TITLE
standalone cause blank screen (within 'explore' endpoint)

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#8159]
When using an "explore" url with &standalone=true, the display is blank on master (used to work on 0.28 and 0.34)

see additional context for a manual investigation/css trick workaround.

### Expected results

display the chart without menu on top. Ideal for iframe embedding for instance.

### Actual results

Superset 'infinite icon' animation is shown, then stops when query ends, then the display is completely blank

#### Screenshots

completely white area, no need of a screenshot I guess :)

#### How to reproduce the bug

1. Go to a chart
2. Click on url bar
3. add `&standalone=true` and hit enter
4. get a blank screen

### Environment

- superset version: master build on 2019-08-27
- python version: 3.6
- node.js version: 3.12

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

In my browser , if I open the web console then type `$("#app div div").css({height:"100px"})` after the superset icon animation has ended, this causes the chart to reveal itself as expected.

**Comment by kaspergaj** [comment]
I think you should grant your public user some more permissions:
 can explore on superset 
explore json on superset 
datasource access 
csrf token

If it still does not work you can try putting
PUBLIC_ROLE_LIKE_GAMMA = True
in the superset_config.py file.

**Comment by squalou** [comment]
Good news  ..... works again on master built on 2019-09-11
No idea what broke and what fixed it again, but it works :)

Closing.

**Comment by maltoze** [comment]
Perhaps this is the reason.
https://github.com/apache/incubator-superset/commit/96f21d3cb642ce7b2417d6b2b9ac24b433bc5947
