### ISSUE TITLE
In HTTPS Change of data source not working on Table and Dashboards

### ISSUE THREAD

**Issue by srikanth-reddy-m** [apache/incubator-superset#8160]
![supersetImage](https://user-images.githubusercontent.com/46744980/64159413-d7d44480-ce57-11e9-8a22-cd953d2b9574.png)

CodeBase: Master Branch

When trying to change superset data source from HTTPS it is trying to open Url in HTTP in which it is creating the error.

Error: Unsafe attempt to load URL, Domains, protocols, and ports must match

### Expected results
It should load URL's with only HTTps
what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
![supersetImage](
![supersetImage](https://user-images.githubusercontent.com/46744980/64159453-e91d5100-ce57-11e9-8e54-fd0f76947446.png)

)

#### How to reproduce the bug

1. Go to  Superset sources and select Tables.
2. Click on any source this will open that source
3. Now click on Data Source drop-down and select change data source and select any data source.
4. This will show error 

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srikanth-reddy-m** [comment]
This issue is solved, I have missed  roxy_set_header X-Forwarded-Proto 'https' header setting in nginx.
If we are using nginx as a reverse proxy with https we have to add this header to flask-app builder to know schema information.

**Comment by syazwan0913** [comment]
@srikanth-reddy-m  Can you share your nginx conf setting?

**Comment by syazwan0913** [comment]
@srikanth-reddy-m Do you have problem when selecting the datasource?

**Comment by maltoze** [comment]
@syazwan0913 This worked for me.
```python
# superset/config.py
ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 1, "x_prefix": 1
```

**Comment by syazwan0913** [comment]
@maltoze what is the version of superset you are using?

**Comment by maltoze** [comment]
@syazwan0913 I'm using 0.29.

I also change this in my code.
```python
# superset/__init__.py
if app.config.get("ENABLE_PROXY_FIX"):
    from werkzeug.middleware.proxy_fix import ProxyFix

    app.wsgi_app = ProxyFix(app.wsgi_app, **app.config.get("PROXY_FIX_CONFIG"))
```
related  #8117

**Comment by syazwan0913** [comment]
@maltoze alright I got it. Thanks

**Comment by CaptainHoangLe** [comment]
I am using superset ver 0.36 and having the same problem when i creat an api get user info below
![image](https://user-images.githubusercontent.com/53038465/116389528-3cbb8a00-a847-11eb-81cf-922cb7798500.png)
![image](https://user-images.githubusercontent.com/53038465/116389568-4e9d2d00-a847-11eb-9287-cdde235a5483.png)
i have used all solutions of you but it don't work :(. Someone help me  , thanks all

**Comment by syazwan0913** [comment]
@CaptainHoangLe are you using Nginx? can share your configuration?

**Comment by CaptainHoangLe** [comment]
> @CaptainHoangLe are you using Nginx? can share your configuration?

Dear bro ,this is my config nginx
![image](https://user-images.githubusercontent.com/53038465/116493053-0e31c380-a8c8-11eb-9ce3-e4e970c47c71.png)

**Comment by syazwan0913** [comment]
You need to add this line inside your Nginx config
`proxy_set_header X-Forwarded-Proto https;`

Also in `superset_config.py` you must enable this:
```
ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 1, "x_prefix": 1
```

**Comment by CaptainHoangLe** [comment]
> You need to add this line inside your Nginx config
> `proxy_set_header X-Forwarded-Proto https;`
> 
> Also in `superset_config.py` you must enable this:
> 
> ```
> ENABLE_PROXY_FIX = True
> PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 1, "x_prefix": 1
> ```

i have just done that but it can't help me to sloving this problem .i don't know how where the error came from

**Comment by CaptainHoangLe** [comment]
![image](https://user-images.githubusercontent.com/53038465/116528494-190b4900-a906-11eb-80c2-6a2df1342711.png)
it send request to https but response location is http

**Comment by syazwan0913** [comment]
I think it is because of your Nginx config, `proxy_set_header Host $http_host;`

**Comment by syazwan0913** [comment]
> > @CaptainHoangLe are you using Nginx? can share your configuration?
> 
> Dear bro ,this is my config nginx
> ![image](https://user-images.githubusercontent.com/53038465/116493053-0e31c380-a8c8-11eb-9ce3-e4e970c47c71.png)

Have you try to run without `proxy_set_header X-Forwarded-For $remote_addr` and `proxy_set_header Host $http_host` ?

Because mine having same problem as yours if using that config.

**Comment by CaptainHoangLe** [comment]
> > > @CaptainHoangLe are you using Nginx? can share your configuration?
> > 
> > 
> > Dear bro ,this is my config nginx
> > ![image](https://user-images.githubusercontent.com/53038465/116493053-0e31c380-a8c8-11eb-9ce3-e4e970c47c71.png)
> 
> Have you try to run without `proxy_set_header X-Forwarded-For $remote_addr` and `proxy_set_header Host $http_host` ?
> 
> Because mine having same problem as yours if using that config.

i have tried but nothing changed. Can i see your nginx config? thanks

**Comment by syazwan0913** [comment]
Here is my working nginx config
```
worker_processes auto;

error_log /var/log/nginx/error.log error;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent"';

    access_log /var/log/nginx/access.log main;

    client_header_timeout 3m;
    client_body_timeout 3m;
    send_timeout 3m;

    client_header_buffer_size 1k;
    large_client_header_buffers 4 4k;

    gzip on;
    gzip_min_length 1100;
    gzip_buffers 4 8k;
    gzip_types text/plain;

    output_buffers 1 32k;
    postpone_output 1460;

    sendfile on;
    tcp_nopush on;

    tcp_nodelay on;

    client_max_body_size 200M;

    server_tokens off;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    upstream backend {
        server IP;
    }

    server {
        listen 80;
        server_name _;
        return 301 https://$server_name$request_uri;
    }

    server {
        listen 443 ssl;
        server_name analytics.local;
        ssl_certificate /etc/nginx/ssl/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl/ssl.key;

        underscores_in_headers on;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_pass http://backend;
            proxy_max_temp_file_size 0;
        }
    }
}

```

**Comment by CaptainHoangLe** [comment]
> Here is my working nginx config
> 
> ```
> worker_processes auto;
> 
> error_log /var/log/nginx/error.log error;
> 
> events {
>     worker_connections 1024;
> }
> 
> http {
>     include /etc/nginx/mime.types;
>     default_type application/octet-stream;
> 
>     log_format main '$remote_addr - $remote_user [$time_local] $status '
>     '"$request" $body_bytes_sent "$http_referer" '
>     '"$http_user_agent"';
> 
>     access_log /var/log/nginx/access.log main;
> 
>     client_header_timeout 3m;
>     client_body_timeout 3m;
>     send_timeout 3m;
> 
>     client_header_buffer_size 1k;
>     large_client_header_buffers 4 4k;
> 
>     gzip on;
>     gzip_min_length 1100;
>     gzip_buffers 4 8k;
>     gzip_types text/plain;
> 
>     output_buffers 1 32k;
>     postpone_output 1460;
> 
>     sendfile on;
>     tcp_nopush on;
> 
>     tcp_nodelay on;
> 
>     client_max_body_size 200M;
> 
>     server_tokens off;
>     add_header X-Frame-Options SAMEORIGIN;
>     add_header X-Content-Type-Options nosniff;
>     add_header X-XSS-Protection "1; mode=block";
> 
>     upstream backend {
>         server IP;
>     }
> 
>     server {
>         listen 80;
>         server_name _;
>         return 301 https://$server_name$request_uri;
>     }
> 
>     server {
>         listen 443 ssl;
>         server_name analytics.local;
>         ssl_certificate /etc/nginx/ssl/ssl.crt;
>         ssl_certificate_key /etc/nginx/ssl/ssl.key;
> 
>         underscores_in_headers on;
> 
>         location / {
>             proxy_http_version 1.1;
>             proxy_set_header Connection "";
>             proxy_read_timeout 300s;
>             proxy_connect_timeout 300s;
>             proxy_send_timeout 300s;
>             proxy_pass http://backend;
>             proxy_max_temp_file_size 0;
>         }
>     }
> }
> ```

thank you, i got it. this reason is config in nginx not apply when i change.Once again I thank you very much for your help
