### ISSUE TITLE
 TIME_GRAIN_ADDON_FUNCTIONS not working in superset 0.34

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#8162]
I changed from superset 0.32.0rc2 to 0.34 and the time grains added in the config file are not working anymore. 

I have set up : 

```
TIME_GRAIN_ADDONS = {"1969-12-31T00:00:00Z/P1W": 'week_start_wednesday'}
TIME_GRAIN_ADDON_FUNCTIONS = {
        'mysql':
        {"1969-12-31T00:00:00Z/P1W": 
                'DATE(DATE_SUB({col}, ''INTERVAL DAYOFWEEK(DATE_SUB({col}, INTERVAL 3 DAY)) - 1 DAY))'}
            }
```

And when I select `week_start_wednesday` as time grain I get the following error : 

> No grain spec for 1969-12-31T00:00:00Z/P1W for database mysql

Note : the same config was working well in superset 0.32.0rc2

**Comment by villebro** [comment]
Will look into this
