### ISSUE TITLE
Where to find superset.log file?

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#8169]
### Expected results

can find superset.log file

### Actual results

cannot find it

#### Screenshots

This is my config.py file
![10](https://user-images.githubusercontent.com/28984703/64238114-5bf9fb00-cf30-11e9-84a6-a319039bd3d4.PNG)

#### How to reproduce the bug

1. Go to 'superset/config.py'
2. See configuration of log console

### Environment

- superset version: `0.34.0rc1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I am running superset in Docker enviornment.

**Comment by kuckjwi0928** [comment]
You must modify the settings.
~~~python
# config.py
ENABLE_TIME_ROTATE = True
~~~
If you make the above corrections and restart as above You can check the path ~/superset/superset.log

**Comment by zhaoyongjie** [comment]
```
cat $SUPERSET_HOME/superset.log
```

**Comment by syazwan0913** [comment]
Alright thanks

**Comment by n15902179169** [comment]
Is there no log type in the generated log file？how can i know the type in log files?

**Comment by Moosheimer** [comment]
@JoanSebasMartinez 
Same for me.

**Comment by rusackas** [comment]
@dosu
