### ISSUE TITLE
drill not work in superset when create table

### ISSUE THREAD

**Issue by zachary124** [apache/incubator-superset#8170]
hello， I want to use drill in superset and create table then create charts。
first I use drill+sadrill and I can create databases and can use in Sql Lab ，but don't create table。
then I use drill+jdbc (thanks @cgivre's help) in superset and I have two problems。
1. when I direct input drill+jdbc://admin:password@test-n01:31010 It get a error 
Can't load plugin: sqlalchemy.dialects:drill.jdbc
and I input drill+sadrill://test-n01:8047/mongo?use_ssl=False  and click 'test Connection'  then retry drill+jdbc://admin:password@test-n01:31010 is ok。this is a bug？
2. I input drill+jdbc://admin:password@test-n01:31010 and click 'test Connection' is ok，but click 'save' I  get a error :

ERROR:root:java.sql.SQLException: No suitable driver found for jdbc:drill:drillbit=test-n01:31010

thanks 

my  environment is:
macOS
superset 0.34.0
sqlalchemy_drill-0.9.dev0
drill-jdbc-all-1.16.0.jar

drill+jdbc attach the log about:

2019-09-04 16:21:28,382:INFO:root:Database.get_sqla_engine(). Masked URL: drill+jdbc://admin:XXXXXXXXXX@test-n01:31010
2019-09-04 16:21:28,383:INFO:root:Cargs:('org.apache.drill.jdbc.Driver', 'jdbc:drill:drillbit=test-n01:31010', ['admin', 'password'], '/Users/zachary/software/drill/jars/jdbc-driver/drill-jdbc-all-1.16.0.jar')
Cargs:('org.apache.drill.jdbc.Driver', 'jdbc:drill:drillbit=test-n01:31010', ['admin', 'password'], '/Users/zachary/software/drill/jars/jdbc-driver/drill-jdbc-all-1.16.0.jar')
2019-09-04 16:21:28,383:INFO:root:Cparams{}
Cparams{}

**Comment by zachary124** [comment]
Can you give me some help ？Looking forward to reply，thanks

**Comment by cgivre** [comment]
Hi @zachary124 I did some digging and found that there is actually a bug in `JayDeBeApi` which is causing the JDBC issue.  (https://github.com/baztian/jaydebeapi/pull/114)   I tried fixing this directly in the sqlalchemy dialect to no avail.  Once this issue is resolved, I will update the Drill sqlalchemy dialect and it *should* work.

**Comment by zachary124** [comment]
@cgivre  thanks
