### ISSUE TITLE
wrong "backquotes" around datasource when "Explorer  in SQL Lab" from a Chart

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#8178]
From a Chart editor using a datasource, when clicking on 'datasource' then choosing 'explore in SQL Lab', the query filled in SQLLab contains wrong chars around datasource name. 

### Expected results

for instance : SQL Lab should contain ```select * from schema.table limite 100```

### Actual results

```select * from `schema.table` limite 100```

=> this causes the query to fail.

#### Screenshots

![2019-09-05 11-13-49 screenshot](https://user-images.githubusercontent.com/4623644/64328765-58b54c80-cfce-11e9-9d16-757b51b22e6e.png)

#### How to reproduce the bug

1. Go to any chart based no a table datasource
2. Click on datasource
3. Scroll to "ezxplore in SQL Lab"

### Environment

(please complete the following information):

- superset version: 0.34 and master HEAD from 2019-08-27
- python version: 3.6
- node.js version: 12.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by squalou** [comment]
I must be missing something.
With the same test case, now I get these errors. But no table at all....


![image](https://user-images.githubusercontent.com/4623644/64684717-e806a800-d485-11e9-9921-c54e41723c2c.png)

**Comment by villebro** [comment]
Very strange, I double checked that everything is working properly for me on master. Can you redo all steps, verify that the datasource still exists and post the steps here so I can verify I'm not doing something differently.

**Comment by squalou** [comment]
Daaammn ! sorry
I was pretty sure I deleted this post.

After another full check, It was an issue on my side, incorrect docker build / deploy.

It's fixed.

Deeply sorry.

**Comment by villebro** [comment]
No sweat @squalou ! Double checking this actually uncovered another unrelated issue, so net positive false positive 😄
