### ISSUE TITLE
How to pass time filters to SQL Lab queries

### ISSUE THREAD

**Issue by cachafla** [apache/incubator-superset#8183]
Is there a way to pass `[from, to]` date filters to an SQL query?

I've been looking everywhere in documentation and source code and haven't found a solution to passing date filters to custom SQL queries. I'm working on some advanced multi-join aggregations from existing tables/views.

As a very simple example of the issue I'm trying solve, consider this SQL query:

```sql
SELECT COUNT(*)
FROM sessions
WHERE timestamp <= {{ something }} AND timestamp >= {{ something_else }}
```

I'd like to be able to access the date filters that are propagated through a `Filter Box` widget. in a dashboard. I've found that the values of these filters are available as these variables (thanks to https://superset.incubator.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard): https://github.com/apache/incubator-superset/blob/40776bd547166b6975574e815ec02add04781248/superset/assets/src/visualizations/FilterBox/FilterBox.jsx#L38-L44

With that in mind, I could make use of `__time_range` inside my SQL filter via `filter_values('__time_range')`, but `__time_range` is always giving me the literal time range selected, not a parsed `[from, to]` couple of date objects. I get values such as:

- 'Last quarter'
- '2019-09-02T00:00:00 : 2019-09-03T00:00:00'

These variations are very difficult to deal with inside an SQL query.

I'd like to know if this is all I get or if there's an undocumented solution to my problem I don't know about. In its simplest from, I'd like to have filters available in the SQL as template params so that I can do things like:

```sql
timestamp >= {{ from }} AND timestamp <= {{ to }}
```

**Comment by als-sdin** [comment]
I managed to solve this with the BETWEEN SQL command. For example:

```
SELECT 'some_column'
WHERE ("time_column' BETWEEN '2019-08-30T16:00:00.0Z' AND '2019-09-5T8:00:00.0Z')
```

Keep in mind this was in the SQL Lab. Hope this helps.

**Comment by rubypollev** [comment]
@cachafla I've written a Jinja addon with the `get_since_until` utility function to do just this. If there's interest in this I'd be happy to make a PR. 

**Usage**

A query on a dashboard with my addon directly preceding the time field:
```
SELECT *
FROM table
WHERE changed_on {{ time_filter() }}
``` 

With this dashboard filter set: 
![Screen Shot 2019-09-06 at 4 24 43 PM](https://user-images.githubusercontent.com/45610410/64465682-e3777380-d0c2-11e9-9fd1-beca221f031b.png)

Results in SQL like this:

```
SELECT *
FROM table
WHERE changed_on BETWEEN "2018-09-06T00:00:00" AND "2019-09-06T00:00:00"
```

**Comment by cachafla** [comment]
> I managed to solve this with the BETWEEN SQL command. For example:
> 
> ```
> SELECT 'some_column'
> WHERE ('time_column' BETWEEN '2019-08-30T16:00:00.0Z' AND '2019-09-5T8:00:00.0Z')
> ```
> 
> Keep in mind this was in the SQL Lab. Hope this helps.

The issue I have is that the value of `time_column` could be "Last year" or something like "2019-08-30T16:00:00.0Z : 2019-09-5T8:00:00.0Z" when a time range is selected. It makes it so either use `BETWEEN` or have to parse the relative date string.

**Comment by cachafla** [comment]
> @cachafla I've written a Jinja addon with the `get_since_until` utility function to do just this. If there's interest in this I'd be happy to make a PR.
> 
> **Usage**
> 
> A query on a dashboard with my addon directly preceding the time field:
> 
> ```
> SELECT *
> FROM table
> WHERE changed_on {{ time_filter() }}
> ```
> 
> With this dashboard filter set:
> ![Screen Shot 2019-09-06 at 4 24 43 PM](https://user-images.githubusercontent.com/45610410/64465682-e3777380-d0c2-11e9-9fd1-beca221f031b.png)
> 
> Results in SQL like this:
> 
> ```
> SELECT *
> FROM table
> WHERE changed_on BETWEEN "2018-09-06T00:00:00" AND "2019-09-06T00:00:00"
> ```

That's amazing 😄 . Looks very similar to how Periscope implements the same feature: https://doc.periscopedata.com/article/date-range-filters

A PR would be great. I'm not sure why this feature has not been requested before but it will be very useful for anyone who is building advanced SQL aggregations that cannot be built from the Charts UI.

**Comment by villebro** [comment]
There's a few things that could be done. One is adding more comprehensive builtin jinja functions that autogenerate where clauses like @rubypollev proposes. The problem with this approach is that the query can become quite messy and difficult to read/maintain.

Another approach would be adding full CTE support, where one could in essence write the join as a CTE, which would then expose a flattened view of the complex query. In this approach any where clauses should be pushed down into the complex queries automatically without any jinja trickery. Adding full CTE support should be quite doable, and something I'd like to do at some point if people would find it valuable.

**Comment by rubypollev** [comment]
@villebro That's interesting; would you mind writing an example query? 

In my case, my datasources are on MySQL 5.X which does not have CTE support. I'd still need some way to build timestamp filters with Jinja. I don't think I'm the only one, either.

**Comment by villebro** [comment]
Oh wow, I thought CTEs have been available in MySQL since forever.. I'll elaborate with an example in the coming days.

**Comment by villebro** [comment]
Ok, so I was thinking the following. Say you have a join as follows:
```sql
SELECT fo.dte,
       fc.id,
       fc.name,
       fo.product
FROM fact_customer fc
INNER JOIN fact_orders fo ON fc.id = fo.customer_id
```
normally Superset would push this into a subquery and perform filtering/grouping/etc on that as follows:
```sql
SELECT dte,
       count(*) AS "count(*)"
FROM
  (SELECT fo.dte,
          fc.id,
          fc.name,
          fo.product
   FROM fact_customer fc
   INNER JOIN fact_orders fo ON fc.id = fo.customer_id) AS expr_qry
WHERE dte >= '2019-01-01'
  AND dte <= '2019-12-31'
GROUP BY dte
```
Some engines will not push the where clause into the subquery, resulting in unnecessarily expensive queries when materializing the subquery. To get around this I would propose wrapping the original query in a CTE:
```sql
WITH cte_qry AS
  (SELECT fo.dte,
          fc.id,
          fc.name,
          fo.product
   FROM fact_customer fc
   INNER JOIN fact_orders fo ON fc.id = fo.customer_id)
SELECT dte,
       count(*) AS "count(*)"
FROM cte_qry
GROUP BY dte
WHERE dte >= '2019-01-01'
  AND dte <= '2019-12-31'
```
Mind you, the majority of modern SQL engines treat subqueries and CTEs equally, i.e. will not impose a performance penalty on the query, but this may not always be the case. Also, some engines don't support wrapping CTEs in subqueries, causing any CTEs to fail when wrapped in a subquery. Especially for CTEs it would be more preferable to wrap the final query of the CTE in a CTE of it's own, and then let Superset build a query on that. Say, for example, that you would write the following query in Sql Lab:
```sql
WITH a AS
  (SELECT 1 AS a
   FROM tbl),
     b AS
  (SELECT 1 AS a,
          'a' AS b
   FROM tbl)
SELECT a.a,
       b.b
FROM a
INNER JOIN b ON a.a = b.a
````
This would then become
```sql
WITH a AS
  (SELECT 1 AS a
   FROM tbl),
     b AS
  (SELECT 1 AS a,
          'a' AS b
   FROM tbl),
     cte_qry AS
  (SELECT a.a,
          b.b
   FROM a
   INNER JOIN b ON a.a = b.a)
SELECT a,
       count(*) AS "count(*)"
FROM cte_qry
GROUP BY a
```
when Superset constructs a query, as opposed to the current behaviour of wrapping the CTE in a subquery.

**Comment by rubypollev** [comment]
That's a nice way of providing separation between the datasource SQL and the visual query builder's additional filtering / grouping. For databases that support CTE it'd make sense.

I don't see how this along would solve the issue of propagating human-readable date filters to SQL. You'd still need to access a utility to transform `__time_range` from the form data in the query predicate. Am I missing something?

**Comment by villebro** [comment]
Can you post a case where a jinja-based date filter needs to be used? I'm not saying there isn't one, but as the majority of modern engines are able to do predicate pushdown into the subquery, the need for injecting date filters should be very uncommon. If I understood your example correctly, the original query
```sql
SELECT *
FROM table
```
should turn into
```sql
SELECT cols
FROM
(SELECT *
FROM table) AS expr_qry
WHERE <time filters>
```
when a filter box emits a time filter, i.e. the time filter will be appended to the query without the need for jinja trickery.

**Comment by rubypollev** [comment]
@villebro MySQL 5.6 does not do predicate pushdown for derived tables. ☹️ 

https://mysqlserverteam.com/derived-tables-in-mysql-5-7/

**Comment by villebro** [comment]
Ok, I didn't know that, very interesting. Is there any particular reason for not upgrading? Given this restriction, it feels there would be a lot to gain by migrating to a newer version.

**Comment by suvarnaC** [comment]
> 
> 
> @cachafla I've written a Jinja addon with the `get_since_until` utility function to do just this. If there's interest in this I'd be happy to make a PR.
> 
> **Usage**
> 
> A query on a dashboard with my addon directly preceding the time field:
> 
> ```
> SELECT *
> FROM table
> WHERE changed_on {{ time_filter() }}
> ```
> 
> With this dashboard filter set:
> ![Screen Shot 2019-09-06 at 4 24 43 PM](https://user-images.githubusercontent.com/45610410/64465682-e3777380-d0c2-11e9-9fd1-beca221f031b.png)
> 
> Results in SQL like this:
> 
> ```
> SELECT *
> FROM table
> WHERE changed_on BETWEEN "2018-09-06T00:00:00" AND "2019-09-06T00:00:00"
> ```

I am interested in this capability, did you create a PR?

**Comment by cachafla** [comment]
> Can you post a case where a jinja-based date filter needs to be used? I'm not saying there isn't one, but as the majority of modern engines are able to do predicate pushdown into the subquery, the need for injecting date filters should be very uncommon. If I understood your example correctly, the original query
> 
> ```sql
> SELECT *
> FROM table
> ```
> 
> should turn into
> 
> ```sql
> SELECT cols
> FROM
> (SELECT *
> FROM table) AS expr_qry
> WHERE <time filters>
> ```
> 
> when a filter box emits a time filter, i.e. the time filter will be appended to the query without the need for jinja trickery.

Correct @villebro, this solves the issue whenever `timestamp` is a column returned by the query. My current struggle is that I have more complex aggregations that can return, say, a single number. Example: get the average time it takes for users to do X. The `timestamp` filters would need to be applied somewhere inside the original SQL because the query would return a single row of aggregated data.

Does that make sense?

**Comment by GiannisDimitriou** [comment]
@rubypollev 
We would be very interested for this as well.
Could you share somehow how we can do it since the PR may take some time until its approved?

**Comment by rubypollev** [comment]
@GiannisDimitriou Sure. 
```
from superset.utils import core as utils
...

def time_filter(default: Optional[str] = None) -> Optional[Any]:
    form_data = request.form.get("form_data")

    if isinstance(form_data, str):
        form_data = json.loads(form_data)
        extra_filters = form_data.get("extra_filters") or {}
        time_range = [f["val"] for f in extra_filters if f["col"] == "__time_range"]
        time_range = time_range[0] if time_range else None

        since, until = utils.get_since_until(time_range)
        time_format = '%Y-%m-%d %H:%M:%S'

        until = until.strftime(time_format)
        if not since:
            return '<= \'{}\''.format(until)
        since = since.strftime(time_format)
        return 'BETWEEN \'{}\' AND \'{}\''.format(since, until)
    return default


JINJA_CONTEXT_ADDONS = {
    'time_filter': time_filter
}
```

This is what I do, and it works for me. I do make some assumptions (taking the first time range filter if there are multiple, for example). 

@villebro & other maintainers: do we want this? I can open a PR with `time_filter` as a default Jinja function if we do.

**Comment by villebro** [comment]
@rubypollev the proposed approach makes sense, especially reusing existing code from `utils.core`. However, if memory serves me right, `BETWEEN` might mean different things depending on the dialect; sometimes inclusive, sometimes not (I might be wrong, though). Anyway, In `connectors/sqla/models.py`, `get_time_filter()` creates `<=` and/or `<=` where clauses, so probably a good idea to stick to that logic. While it might be difficult to leverage SqlAlchemy Core functionality in this case (might be feasible, not sure), I think it makes sense to try to diverge from the default logic as much as possible. So prior to submitting a PR I would advise to at least change the `BETWEEN` operator to `<=` and/or `>=` operator(s), with additional bonus for utilizing any existing code.

**Comment by suvarnaC** [comment]
Thank you @rubypollev . I did similar implementation taking hint from your first comment on this issue. I choose to return both since and until dates.
Agree with @villebro suggestion as it gives us flexibility to choose different SQL operators in SQL Lab queries.

**Comment by kameltigh** [comment]
@rubypollev thanks a lot for your solution. Have you created the PR ?

**Comment by smic-datalabs-von** [comment]
@rubypollev would appreciate if you can provide the code snippet or created the PR :)

**Comment by dengshaochun** [comment]
> @GiannisDimitriou Sure.
> 
> ```
> from superset.utils import core as utils
> ...
> 
> def time_filter(default: Optional[str] = None) -> Optional[Any]:
>     form_data = request.form.get("form_data")
> 
>     if isinstance(form_data, str):
>         form_data = json.loads(form_data)
>         extra_filters = form_data.get("extra_filters") or {}
>         time_range = [f["val"] for f in extra_filters if f["col"] == "__time_range"]
>         time_range = time_range[0] if time_range else None
> 
>         since, until = utils.get_since_until(time_range)
>         time_format = '%Y-%m-%d %H:%M:%S'
> 
>         until = until.strftime(time_format)
>         if not since:
>             return '<= \'{}\''.format(until)
>         since = since.strftime(time_format)
>         return 'BETWEEN \'{}\' AND \'{}\''.format(since, until)
>     return default
> 
> 
> JINJA_CONTEXT_ADDONS = {
>     'time_filter': time_filter
> }
> ```
> 
> This is what I do, and it works for me. I do make some assumptions (taking the first time range filter if there are multiple, for example).
> 
> @villebro & other maintainers: do we want this? I can open a PR with `time_filter` as a default Jinja function if we do.

In recent releases, the form_data structure has changed
v0.35, `time_range = form_data.get("time_range")`

```python
# jinja_context.py
from superset.utils import core as utils

# ....

def time_filter(
        time_format: str = '%Y-%m-%d %H:%M:%S',
        cast: str = 'datetime',
        engine: str = 'default',
        default: Optional[str] = None) -> Optional[Any]:
    """
    get time filter from form_data
    :param time_format: datetime format string
    :param cast: database cast function, like mysql "cast('20191111' as SIGNED)"
    :param engine: database engine
    :param default: default value to return if there's no data
    :return: returns a date string or None
    """
    form_data = request.form.get("form_data")
    from string import Template

    # todo other database
    _dict = {
        'mysql': Template('CAST(\'${value}\' AS ${cast})'),
        'default': Template('\'${value}\'')
    }
    t = _dict.get(engine)

    if isinstance(form_data, str):
        form_data = json.loads(form_data)
        # extra_filters = form_data.get("extra_filters") or {}
        # time_range = [f["val"] for f in extra_filters if f["col"] == "time_range"]
        # time_range = time_range[0] if time_range else None

        time_range = form_data.get("time_range")
        since, until = utils.get_since_until(time_range)

        until = until.strftime(time_format)
        t_until = t.substitute(value=until, cast=cast)

        if not since:
            return '<= {} '.format(t_until)
        t_since = t.substitute(value=since.strftime(time_format), cast=cast)
        return 'BETWEEN {} AND {} '.format(t_since, t_until)
    return default


# config.py
JINJA_CONTEXT_ADDONS = {"time_filter": time_filter}
```
test original sql
```sql
select * from xxx WHERE data_day {{ time_filter('%Y%m%d', 'SIGNED', 'mysql')}}
```
jinja2 formatted like
```sql
select * from xxx WHERE data_day BETWEEN CAST('20191122' AS SIGNED) AND CAST('20191124' AS SIGNED)
```

**Comment by mohitahuja1** [comment]
Any updates here?

**Comment by FredericoCoelhoNunes** [comment]
I'm running a visualization over a custom source that is created by several sequential `WITH ... AS` statements, and I need to apply date filters to the middle steps, and not only the final `SELECT` statement.

**Comment by elaragon** [comment]
> This is what I do, and it works for me. I do make some assumptions (taking the first time range filter if there are multiple, for example).

@rubypollev thanks for sharing this patch (I also need to pass time filters to SQL Lab queries). 

Since I have just started with Superset, **could you please tell to which python file I should add your code snippet?** Thanks again :)

**Comment by dharamgajera** [comment]
> > This is what I do, and it works for me. I do make some assumptions (taking the first time range filter if there are multiple, for example).
> 
> @rubypollev thanks for sharing this patch (I also need to pass time filters to SQL Lab queries).
> 
> Since I have just started with Superset, **could you please tell to which python file I should add your code snippet?** Thanks again :)

You need to add in superset config.py file.
