### ISSUE TITLE
Why Dashboard is blank?

### ISSUE THREAD

**Issue by Demonya** [apache/incubator-superset#8186]
![image](https://user-images.githubusercontent.com/32725399/64406955-b1134980-d0b5-11e9-8dd2-dc1654780c11.png)

I create some slice in dashboard,but sometimes it shows error above the link youcan see,if refresh,some slices will be normal,but others still have error! I don't kown if I make something wrong or other questions? Thanks a lot if you can provide solution!

**Comment by mistercrunch** [comment]
Do you have a stacktrace from the server process / logs?
