### ISSUE TITLE
WordCloud font-size set to 0px when displaying single value

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#8190]
In superset 0.34 WordCloud charts are empty when supposed to display a single value. 
By inspecting the element I can see that is not really empty but the font size of the text to display is set to 0px.
It is still working when displaying a list of values.

**Comment by villebro** [comment]
I was unable to reproduce; can you elaborate with a more detailed example?

**Comment by lilila** [comment]
Hello @villebro , I made a few tests. It appears the font size depends on metric. I had as metric "MAX(title)" but when I change for "COUNT_DISTINCT(title)" it works well. 
So I suppose the metric has to be a numeric value 


![Screen Shot 2019-09-18 at 09 58 27](https://user-images.githubusercontent.com/607430/65129224-2a3a6700-d9fb-11e9-8370-bcb7e0fe04a1.png)
![Screen Shot 2019-09-18 at 09 47 45](https://user-images.githubusercontent.com/607430/65129227-2ad2fd80-d9fb-11e9-9591-32346d80e661.png)

**Comment by villebro** [comment]
Hmm, perhaps we should raise an Exception if a metric is not numeric.
