### ISSUE TITLE
fix "target" typo in Sankey Diagram Hover Text

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#8192]
Is it possible to remove the extra "target" word that is added in the hover text of sankey diagrams? 
<img width="817" alt="Screen Shot 2019-09-08 at 08 45 32" src="https://user-images.githubusercontent.com/607430/64484651-b7203c00-d215-11e9-87af-aaac074f9463.png">

The new position and style of the hover text is great. However, depending on the what is below the sankey chart, it can be hidden. Is there a way to fix this? 

### Eg. without adding extra space
<img width="430" alt="Screen Shot 2019-09-08 at 08 54 40" src="https://user-images.githubusercontent.com/607430/64484711-91dffd80-d216-11e9-87ac-664569159519.png">

### Adding extra space below sankey diagram
<img width="439" alt="Screen Shot 2019-09-08 at 08 54 56" src="https://user-images.githubusercontent.com/607430/64484703-7b39a680-d216-11e9-8399-bcd562657eda.png">

**Comment by mlmaverick** [comment]
@lilila Hi, can you please help in how to create the multi-level sankey diagram. I have my table in the format 

source, target, count
step-1, step-2, 10
step-1, step-3, 30
step-2, step-4, 10
step-2, step-5, 30

But still end up with single level diagram. Thanks.
