### ISSUE TITLE
Tabs of bug 

### ISSUE THREAD

**Issue by makxie** [apache/incubator-superset#8195]
Hello, I have a Bug about tabs. Switching tabs will cause the width of the th table to become 0 px
### Expected results
The page should not refresh after TAB toggle
what you expected to happen.

### Actual results
The header is automatically indented
what actually happens.
width to become 0px
#### Screenshots
![image](https://user-images.githubusercontent.com/40452296/64489832-128c1180-d28a-11e9-9722-135af00affe9.png)

### Environment

(please complete the following information):

- superset version: `superset version` 0.28.1
- python version: `python --version` 3.6.5
- node.js version: `node -v` 7..10.0
- npm version: `npm -v` 6.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ √] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ √] I have reproduced the issue with at least the latest released version of superset.
- [ √] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by makxie** [comment]
I don't get it.

**Comment by aaa92729** [comment]
its still happend!
