### ISSUE TITLE
Missing dashboard id on export duplicates imported dashboards

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#8199]
Importing same dashboard with changes generates a copy

### Expected results

Dashboard gets updated

### Actual results

Multiple copies of the same dashboard. Slices are updated correctly

#### Screenshots
![image](https://user-images.githubusercontent.com/767180/64529890-37c16400-d30c-11e9-8d8d-aca0cff07527.png)

![image](https://user-images.githubusercontent.com/767180/64529870-2bd5a200-d30c-11e9-93a0-ee6fddc8d134.png)

![image](https://user-images.githubusercontent.com/767180/64529913-43ad2600-d30c-11e9-9089-8954afcf5d9b.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by chesterxgchen** [comment]
This PR should fix this: 
https://github.com/apache/incubator-superset/pull/9506
