### ISSUE TITLE
Empty Display 'List View Menus' 

### ISSUE THREAD

**Issue by sandy-ha** [apache/incubator-superset#8200]
The "List View Menus" display is empty if I first select a page count that is not reached with the page size selected at the second. It is a trivial problem. It causes irritation.

### Expected results

The list should go back to the first site of the list.

### Actual results

I get a empty list. 
#### Screenshots

![image](https://user-images.githubusercontent.com/53593919/64525564-6c7bee00-d301-11e9-830c-34ed866dd9ec.png)

#### How to reproduce the bug

1. Go to 'Security'
2. Click on 'Base Permissions' or 'Views/Menus'
3. Scroll down to Page
4. Select the last page for example
5. Change page size to '100'
6. See error

for example:
http://localhost:8088/viewmenus/list/?page_ViewMenuModelView=5&psize_ViewMenuModelView=100

### Environment

(please complete the following information):

superset version: 0.28.1
python version: 3.6.8
node.js version: v8.10.0
npm version: 3.5.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @sandy-ha,

Yes, it's a bug on FAB, could you please close this issue on superset and reopen it on FAB?

Thank you

**Comment by sandy-ha** [comment]
> Hi @sandy-ha,
> Yes, it's a bug on FAB, could you please close this issue on superset and reopen it on FAB?
> Thank you

Hi @ dpgaspar
What do you mean with FAB?

**Comment by dpgaspar** [comment]
https://github.com/dpgaspar/Flask-AppBuilder
