### ISSUE TITLE
sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 10 reached, connection timed out, timeout 30

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#8207]
can not add 'pool_size'  to metadata_params{}

**Comment by etr2460** [comment]
We've seen a similar issue before, but after some sqlalchemy config tweaks and some db optimizations in flask appbuilder, it went away. Maybe try adding the following to your superset config to fix the issue:
```
SQLALCHEMY_ENGINE_OPTIONS = {
    "max_overflow": 15,
    "pool_pre_ping": True,
    "pool_recycle": 60 * 60,
    "pool_size": 30,
}
```

**Comment by swapnil-chenoa** [comment]
We've faced a similar issue before,We have added below parameters in config.py of superset to fix the issue.

SQLALCHEMY_POOL_SIZE=20
SQLALCHEMY_POOL_TIMEOUT=300
