### ISSUE TITLE
Problem installing Superset via Docker

### ISSUE THREAD

**Issue by ivansocket** [apache/incubator-superset#8211]
Following the "Start with Docker" instructions from: https://superset.incubator.apache.org/installation.html

When executing the following command: https://superset.incubator.apache.org/installation.html 

I get the warning: (node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
in red color and then:

clean-webpack-plugin: /home/superset/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/superset/.npm/_logs/2019-09-10T16_43_28_302Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd superset/assets     && npm ci     && npm run build     && rm -rf node_modules' returned a non-zero code: 1

Afther this the instalation stops.
I don't understand what do I need to do in order for Superset to install normally.

Thanks in advance.

**Comment by mmantel** [comment]
I had this same problem and was able to get past it after increasing the resources in my Docker preferences (from 2.0 GiB to 4.0GiB of memory and 1.0 GiB to 2.0 GiB of swap).

**Comment by domehead100** [comment]
Just ran into this trying to run superset in docker (Docker Desktop for Windows with Linux containers).  Docker has 8GB of memory and 1GB of swap.

Seems this might be related to https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/272, though that issue is related to Uglify is closed and they seem to think it is fixed in the Terser plugin, but it seems it might not be entirely fixed.

I did increase the swap from 1GB to 2GB, and then it built okay on the second attempt.

**Comment by micimize** [comment]
Same applied with docker for mac - 2 -> 5GB memory and 1 -> 2GB swap worked for me.
`92% chunk asset optimization TerserPlugin` is where my build hung.

**Comment by moonrinnn** [comment]
What is node's version do we need to use?

**Comment by schrepfler** [comment]
Still an issue with latest from master.

**Comment by barmic12** [comment]
Increasing swap to 2GB and memory to 4GB resolved problem for me

**Comment by bharath0208** [comment]
I have increased my memory and swap now this step goes by but i am getting an error after creating a user.
Any Idea on why this is occuring

Password: 
Repeat for confirmation: 
Usage: flask fab create-admin [OPTIONS]

Error: A valid Flask application was not obtained from "superset:app".

**Comment by bharath0208** [comment]
The same thing worked for me

**Comment by cfmeyers** [comment]
Increasing the swap/memory did work for me (2GB swap, 4GB memory).  It did pause for 3-5 minutes on that same 92% chunk asset optimization TerserPlugin, but it moved past that step and finish successfully.

**Comment by dpgaspar** [comment]
Thank you everyone for your help here. @ivansocket going to close this, feel free to reopen if the memory increase did not solved the issue

**Comment by SAVE-POlNT** [comment]
hello, i have same problem here ,  my build stoped at 92% chunk asset optimization TerserPlugin 
do i need to let it continew or i have to stop it ? it is like this for like 15 min
im using linux server with 4gb ram and 2gb swap 

what im trying to do it changing the colors and the logo of superset , is it the right way to do it ?  going into assets and rebuild them with new colors in variables.less and change the logo from the images folder ?
