### ISSUE TITLE
Allow different x-axis for line charts

### ISSUE THREAD

**Issue by leoblue** [apache/incubator-superset#822]
The x-axis need not necessarily be a time/date, it could just be any number. Would be great to make that possible!

**Comment by tosolveit** [comment]
This feature would be great, when you analyse the data it's not just time series on the x axis, looking forward for it.

**Comment by vicho29** [comment]
Checking if this feature of supporting Line char X-axis to be non-time/date has been added yet?

Thanks

**Comment by mistercrunch** [comment]
This would be as a new visualization of the `nvd3.js`. The x axis might be either a numeric column that must be "grouped by", or a metric that is an aggregate function. We may need a new control that represents a superset of columns and metrics for that purpose.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 349 days. Feel free to comment and request for this issue to be reopened.

**Comment by timurista** [comment]
Please add this, it's vary constraining to have datetime as the only option for the x axis.

**Comment by pjpringle** [comment]
did this get resolved?

**Comment by villebro** [comment]
@pjpringle we're currently working on this - we should hopefully have this supported in Superset 1.4.

**Comment by villebro** [comment]
Current progress: https://github.com/apache-superset/superset-ui/pull/1356 and #16660 (first prerequisites for adding support for generic x-axis)

**Comment by hansgaurav** [comment]
Hi, any updates on this? Any workaround for this maybe?
