### ISSUE TITLE
why the function have 'self' param in  view/core.py?

### ISSUE THREAD

**Issue by zuoww** [apache/incubator-superset#8227]
def check_datasource_perms(
    self, datasource_type: str = None, datasource_id: int = None
) -> None:

def check_slice_perms(self, slice_id):
    """
    Check if user can access a cached response from slice_json.

    This function takes `self` since it must have the same signature as the
    the decorated method.

    """
    form_data, slc = get_form_data(slice_id, use_slice_data=True)
    datasource_type = slc.datasource.type
    datasource_id = slc.datasource.id
    viz_obj = get_viz(
        datasource_type=datasource_type,
        datasource_id=datasource_id,
        form_data=form_data,
        force=False,
    )
    security_manager.assert_datasource_permission(viz_obj.datasource)

**Comment by mmutiso** [comment]
This is to show that it is a class method and this param can be used to access other class members.
