### ISSUE TITLE
Problem connecting with SQL Server

### ISSUE THREAD

**Issue by SWoto** [apache/incubator-superset#8232]
Cannot connect to SQL Server through Apache Superset on Ubuntu 18 in a Dedicated Server. 

My  SQLAlchemy URI  is `mssql+pymssql://user:password@serverip:port/db`.

I've followed this tutorial: [http://jaygrossman.com/post/2019/03/02/Apache-Superset-Test-Drive.aspx](http://jaygrossman.com/post/2019/03/02/Apache-Superset-Test-Drive.aspx) that says to install the `pymssql` inside the container with `docker exec -it container_ID bash` and `pip install pymssql`.

when i try for the second time:
`
root@container_id:/home/superset# pip install pymssql
Requirement already satisfied: pymssql in /root/.local/lib/python3.6/site-packages (2.1.4)
`

also inside the container, when i try to use `python -i`  than `import pymssql` and make a connection like the pymssql examples i get no error message, everything works smoothly...

Than I tried to change de requirements.txt in the server adding `pymssql` and relaunch the docker-compose... 

### Actual results

`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nNo module named 'pymssql'", "stacktrace": "Traceback (most recent call last):\n  File \"/home/superset/superset/views/core.py\", line 1745, in testconn\n    engine = database.get_sqla_engine(user_name=username)\n  File \"/home/superset/superset/utils/core.py\", line 132, in __call__\n    value = self.func(*args, **kwargs)\n  File \"/home/superset/superset/models/core.py\", line 900, in get_sqla_engine\n    return create_engine(url, **params)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py\", line 435, in create_engine\n    return strategy.create(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 87, in create\n    dbapi = dialect_cls.dbapi(**dbapi_args)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/pymssql.py\", line 61, in dbapi\n    module = __import__(\"pymssql\")\nModuleNotFoundError: No module named 'pymssql'\n"}`

### Environment

(please complete the following information):

- superset version: `0.999.0dev`
- python version: `Python 3.6.9`
- node.js version: `v10.16.3`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

looks like the same problem here, but no solution. [https://github.com/apache/incubator-superset/issues/7970](https://github.com/apache/incubator-superset/issues/7970)

**Comment by dpgaspar** [comment]
Hi @SWoto,

Were you able to solve this? check if your WSGI is running on a python virtenv

**Comment by SWoto** [comment]
I kind of solve it using the hard way... had to do a stop in all containers, deleted the images and rebuild them using the docker-compose. I still didn't figure out what happened neither how to solve it.

**Comment by dpgaspar** [comment]
Glad it's all good
