### ISSUE TITLE
Filter dashboard clicking on chart #5941

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#8234]
**Is your feature request related to a problem? Please describe.**
click the chart to affect the other chart as a filter
**Describe the solution you'd like**
chart filter by single click
**Describe alternatives you've considered**
click based chart filter

**Comment by jitendra-kumawat** [comment]
On which chart do you need this click support...

**Comment by kalimuthu123** [comment]
@jitendra-kumawat  prioritly  i expect this feature in bar chart and pie chart

**Comment by ulriksenstian** [comment]
this feature would be immensely valuable
