### ISSUE TITLE
Pivot Table Freeze Columns or Rows - "Freeze Pane" 

### ISSUE THREAD

**Issue by davidhassan** [apache/incubator-superset#8238]
I would like the ability to freeze a row or column from moving when I scroll down or over on the pivot table chart. 

If you have a large pivot table that involves scrolling in either direction you can easily lose track of which row or column you are looking at. 

By freezing the column or row on scrolling we do not have that issue.

This feature is called "Freeze Pane" in MS Excel.

**Comment by vrnvorona** [comment]
why is it close without any response?

**Comment by saghatelian** [comment]
This would be a great feature. Hope someone will add it.

**Comment by LeoDiep** [comment]
This is a very useful feature, for large table. Please add it

**Comment by LeoDiep** [comment]
any update on this, please?

**Comment by Nimit-Shah** [comment]
Any update please?

**Comment by LeoDiep** [comment]
any update on this, please?

**Comment by cstoff6** [comment]
Any update on this? I would like to implement this feature.

**Comment by dokster8** [comment]
Still need this feature.

**Comment by Nimit-Shah** [comment]
Hi Dimitri,
Yes I still need this feature. On any kind of table being built. Both
columns and rows.
Not sure how many else need this but it will be helpful.

**Comment by LeoDiep** [comment]
the pivot table v2 can freeze the top rows already, but we really need columns freezed as well for large long tables.
I don't think this is too difficult to implement, am I correct?

**Comment by jatin5251** [comment]
yes we need this feature

**Comment by nkdanta1** [comment]
any update on this, please?

**Comment by ashishjaingithub** [comment]
Any update on this?

**Comment by rusackas** [comment]
Hey folks. The thread was closed by a bot, four years ago, because the issue was ignored by the community for 30 days. 

At this point, it wouldn't be allowed as an Issue, since it's not a bug. For feature requests, we advise people to open a GitHub Discussion and/or open a PR. 

In this thread, there are a lot of folks suggesting that it's easy or that they'd like to contribute it. Please do! We're more than happy to review PRs, and would love to bring more contributors into the fold here.

**Comment by LeoDiep** [comment]
> Hey folks. The thread was closed by a bot, four years ago, because the issue was ignored by the community for 30 days.
> 
> At this point, it wouldn't be allowed as an Issue, since it's not a bug. For feature requests, we advise people to open a GitHub Discussion and/or open a PR.
> 
> In this thread, there are a lot of folks suggesting that it's easy or that they'd like to contribute it. Please do! We're more than happy to review PRs, and would love to bring more contributors into the fold here.

Hi, I did raise a discussion months ago. Please help us here to make this function reality.
https://github.com/apache/superset/discussions/23404
