### ISSUE TITLE
Explore Button not working

### ISSUE THREAD

**Issue by syafiqdante** [apache/incubator-superset#8247]
Hello, I quite new with superset.
It seems like the 'explore' button having error
### Expected results

Visualize the chart data from query

### Actual results

Nothing happens, with only error shown in the Chrome console log

#### Screenshots

![explore button error 2](https://user-images.githubusercontent.com/46438728/65134651-36dcb080-da37-11e9-85b5-6efc4eb07722.PNG)
![explore button error](https://user-images.githubusercontent.com/46438728/65134653-37754700-da37-11e9-8873-d3a4dab4bd2f.PNG)

#### How to reproduce the bug

1. Go to 'Sql Editor'
2. Click on 'Explore' button
3. See error in Chrome browser console

### Environment

(please complete the following information):

- superset version: `superset==0.29.0rc7`
- python version: `Python 3.6.8`
- node.js version: `v10.16.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The issue might have similarity to https://github.com/apache/incubator-superset/issues/6557
but I did not setup druid for superset.
Please help, Thanks

**Comment by mistercrunch** [comment]
Please reopen if you can reproduce on `0.34.0`
