### ISSUE TITLE
SQL Lab doesn't display queries results but rather 'offline' followed by an empty table

### ISSUE THREAD

**Issue by CyrilLeMat** [apache/incubator-superset#8248]
Since the 0.34 version, SQL Lab doesn't display queries results but rather 'offline' followed by an empty table

### Expected results

When running a query in the sql lab, we should see the 'running' icon temporarily and then have the results displayed in the tab

### Actual results

After a short display of the 'running' icon, a red 'offline' label is displayed.
Once the data is loaded, an empty table is displayed (we have the columns but no rows).

However:
- This bug is not systemic every few calls we have the expected display
- If I click on "Query History" and then on "Results", the rows are displayed

#### Screenshots
![image](https://user-images.githubusercontent.com/7548748/65137197-2ca3bd80-da09-11e9-8c26-b1aa8da13fa3.png)

![image](https://user-images.githubusercontent.com/7548748/65137170-24e41900-da09-11e9-8425-3dd36e1363ee.png)

#### How to reproduce the bug

1. Go to SQL Lab
2. Choose a Database (Here we only use Postgresql Databases)
3. Click on "Run Query"

### Environment

- superset version: 0.34
- python version: 3.6.6

### Checklist

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @CyrilLeMat,

Are your queries async? Can you post your server logs, when the error occurs?

**Comment by villebro** [comment]
I had this same problem a while ago; started out of nowhere. I was able to resolve it by clearing my browser cache (apparently something bad was caught in localStorage). Please clear your cache to see if that fixes the problem. However, beware that this will also clear your SqlLab tabs!

**Comment by yravindra** [comment]
you can  select column in query like (select column1,column2 from table name ).it will work . select * is not working here.

**Comment by CyrilLeMat** [comment]
- I cleared my cache and it doesn't change anything.
- there is no differences between 'select col1 from' and 'select * from'
- My queries are not async
- Concerning my logs : 
![image](https://user-images.githubusercontent.com/7548748/65260156-36f7b180-db06-11e9-8f81-5016dffd52d0.png)

![image](https://user-images.githubusercontent.com/7548748/65259892-bafd6980-db05-11e9-81c7-74110f573b69.png)

(fyi, the query is working but the results are not displayed. However they are If I click on "Query History" and then on "Results")

**Comment by labelhero** [comment]
We are also having same issue. First we are seeing the "OFFLINE"  then empty results. Query completes fine. Once you hit the "Query History" and then hit the "Results" tab then results are displayed.

**Comment by lepe92** [comment]
I had the same issue, review the difference between my custom roles and the `Admin` figure it out there were some new permissions. Adding `can queries on Superset`, `can query form data on Api` and `can query on Api` worked for us.

**Comment by Rcharriol** [comment]
run `superset init` 
It cleans faulty permissions and creates missing ones.
This solution worked for me

**Comment by shamsherrana** [comment]
Facing same issue, tried superset init, cleared browser cache and also adding mentioned permissions
