### ISSUE TITLE
Unable to display data table in sqlite?

### ISSUE THREAD

**Issue by LoveMyBaby** [apache/incubator-superset#8249]
I have successfully installed superset in docker mode, and the example data is also loaded successfully. When I add local sqlite for testing, it can't display the specific table name in sql lab.

- superset version: `0.28.0`
- python version: `2.7.5`
- node.js version: `10.16.3`
- npm version: `6.9.0`

### Checklist
- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
no any table display in main schema, when i exec select sql: sqlite error: no such table: xxx

1. add datasource:  
Test Connection: OK
expose in SQL Lab: selected
No data table displayed in bottom !

2. View In SQL Lab Editor:  
schema: main(only) 
see table schema(0 in main)

3. View database by sqlite3 in Centos7:  display table

**Comment by villebro** [comment]
This issue refers to an old version of Superset (also deprecated version of Python); please try the most recent official release (0.34) and reopen if the issue persists.

**Comment by everton3x** [comment]
I installed the superset as per the tutorial via Docker Compose on Windows 11 and added a SQLite database using the ```PREVENT_UNSAFE_DB_CONNECTIONS = False``` directive

The connection test is successful.

The database is fully functional and accessible.

The superset version is 0.0.0dev (as stated in the About section of the Settings menu).

But the same thing is happening to me:

View In SQL Lab Editor:
- schema: main (only)
- see table schema (0 in main)

**Comment by everton3x** [comment]
I installed the superset as per the tutorial via Docker Compose on Windows 11 and added a SQLite database using the ```PREVENT_UNSAFE_DB_CONNECTIONS = False``` directive

The connection test is successful.

The database is fully functional and accessible.

The superset version is 0.0.0dev (as stated in the About section of the Settings menu).

But the same thing is happening to me:

View In SQL Lab Editor:
- schema: main (only)
- see table schema (0 in main)

**Comment by capttrousers** [comment]
Can we repoen this? 

I cloned the repo just now and got it running  with `docker compose` and followed this comment https://github.com/apache/superset/issues/9748#issuecomment-1124323169 to get the sqlite db added but I have the same experience, adding the sqlite db file via the path copied into superset_home works with the driver connection string properly formatted, but adding a dataset from the sqlite db results in a single schema `main` and no tables found.

**Comment by mechgt** [comment]
exact same experience just now as capttrousers.  Brand new install, managed to get sqlite db to connect, but main only and no data :(

**Comment by hiwaveSupport** [comment]
I just installed superset using manual steps and have it running. I added a sqlite3 db file under database connections , where it showed the connection to be ok with unsafe flag set to FALSE. I also only see main as schema under the newly attached database and don't see the table which exists when I query the db file via sqlite3 commain line.
![image](https://github.com/apache/superset/assets/39630233/11f7bd76-eaf4-43bb-9104-e80a469ba3a9)
![image](https://github.com/apache/superset/assets/39630233/708b3548-dc01-4928-8744-55cc3dfde98c)

Infra:
SQLite 3.41.2 2023-03-22 11:56:21 0d1fc92f94cb6b76bffe3ec34d69cffde2924203304e8ffc4155597af0c191da
zlib version 1.2.13
gcc-11.2.0
Loaded your LOCAL configuration at [/home/vibhu/src/talkAItive/superset/superset_config.py]
Python 3.10.13
Flask 2.2.5
Werkzeug 2.3.8

Help please.

**Comment by sammigachuhi** [comment]
the same problem persists even as of May 2024. A solution please?

**Comment by janl** [comment]
I ran into this today, it’d be great if we could get this looked at <3

**Comment by rusackas** [comment]
> I ran into this today, it’d be great if we could get this looked at <3

I'm not super inclined to open a 6 year old bug with antiquated context. Assuming you're not using 0.28 (I sure hope not!) it'd be good to start a fresh issue (with updated/reproducible context) and link back to this if needed.
