### ISSUE TITLE
Sqlite TimeGrain not working

### ISSUE THREAD

**Issue by ramarnat** [apache/incubator-superset#8252]
Using SQLite, the bar graph is not setting the timegrain to month

### Expected results

The graph should show by month, `__timestamp`  should show in SQL

### Actual results
The Graph does not show by month, The sql does not show `__timestamp` conversion

#### Screenshots

<img width="676" alt="screenshot" src="https://user-images.githubusercontent.com/88762/65175440-df334a80-da20-11e9-9536-38ccd158a5b0.png">

#### How to reproduce the bug

Create a bar graph with a timegrain of Month

### Environment

- superset version: `0.34.0`
- python version: `Python 3.6.9`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
I think you want to use a "Time-series Bar Chart" for this, not "Bar Chart".

**Comment by ramarnat** [comment]
I can do that, but shouldnt this work for the bar chart as well? I am fairly sure this worked in an earlier version.

**Comment by ramarnat** [comment]
Time-series Bar Chart worked. Thank you.
