### ISSUE TITLE
unable to display data table in sqlite

### ISSUE THREAD

**Issue by LoveMyBaby** [apache/incubator-superset#8259]
last report(run in docker): 
[https://github.com/apache/incubator-superset/issues/8249#issue-495165654
](url)
I have successfully installed superset in docker mode, and the example data is also loaded successfully. When I add local sqlite for testing, it can't display the specific table name in sql lab.

superset version: 0.34.0
python version: 3.6.0
node.js version: 10.16.3
npm version: 6.9.0
Checklist
[ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
[ X] I have reproduced the issue with at least the latest released version of superset.
[ X] I have checked the issue tracker for the same issue and I haven't found one similar.
Additional context
no any table display in main schema, when i exec select sql: sqlite error: no such table: xxx

add datasource:
Test Connection: OK
expose in SQL Lab: selected
No data table displayed in bottom !

View In SQL Lab Editor:
schema: main(only)
see table schema(0 in main)

View database by sqlite3 in Centos7: display table

**Comment by dpgaspar** [comment]
Hi,

Just tested it, I've done the following on superset local dev env, with loaded examples:
- created a sqllite db with one table `create table a(c1 Int);`
- created new data:
```
sqlite> insert into a values(1);
sqlite> insert into a values(2);
sqlite> insert into a values(3);
```
- created a new database connection named test1 pointing the the sqllite file

On SQLLab I can browse the table and query it.

Please repeat a similar test, or (if it still fails), post servers logs and a list of your database connections

**Comment by LoveMyBaby** [comment]
Thanks dpgaspar
even if I repeat the test, this problem still occurs. when I create a new mysql connection, it is right.
so I have given up testing with SQLite and changed to use Mysql to test

**Comment by dpgaspar** [comment]
I don't think we have some sort of bug here, if it's fine by you, please close this issue
