### ISSUE TITLE
contrib/docker doesnt support corporate environment/proxy

### ISSUE THREAD

**Issue by dprophet** [apache/incubator-superset#8260]
### Expected results

If you run
incubator-superset/contrib/docker]$ docker-compose run -e SUPERSET_LOAD_EXAMPLES=yes --rm superset ./docker-init.sh

what you expected to happen.

I would expect the container to run

### Actual results

what actually happens.

Connection errors

#### Screenshots

<img width="693" alt="proxy_error" src="https://user-images.githubusercontent.com/3594022/65256246-35f65e00-dacd-11e9-8006-09aa83bad65b.png">

#### How to reproduce the bug

docker-compose run -e SUPERSET_LOAD_EXAMPLES=yes --rm superset ./docker-init.sh
### Environment

Any environment with a proxy

**Comment by dpgaspar** [comment]
Hi @dprophet,

Can you please try: https://docs.docker.com/network/proxy/
