### ISSUE TITLE
Login Page Default Focus.

### ISSUE THREAD

**Issue by kuckjwi0928** [apache/incubator-superset#8263]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be good to basically focus on the text box when you access to the login page.

**Describe alternatives you've considered**
Automatically move focus to the Username input box when accessing login page.

**Additional context**
This is a minor task, but i think it will be of some help to UX

**Comment by dpgaspar** [comment]
Hi @kuckjwi0928,

The login page is implemented by flask-appbuilder. please close this issue here and open a new one there.

Thks
