### ISSUE TITLE
Heatmap x-axis not sorting properly

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#8264]
### Expected results

sorting on x-axis is proper order like 0, 1, 2, 3, 4, 5, 6,....

### Actual results

Sorting is not in order

#### Screenshots

![Screenshot from 2019-09-20 09-13-46](https://user-images.githubusercontent.com/28984703/65291746-4703a580-db87-11e9-82ed-db96ac10a611.png)
x-axis on Heatmap not sorting properly

![Screenshot from 2019-09-20 09-14-08](https://user-images.githubusercontent.com/28984703/65291763-5c78cf80-db87-11e9-84b1-e8abe1dfa692.png)
Datasource from Druid

### Environment

- superset version: `0.34.0rc1`
- python version: `3.6`
- node.js version: `10.16.0`
- npm version: `6.9.0`
- highcharts version: `7.1.1`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by anandnalya** [comment]
Hi, seems like this issue is still present in Superset 3.0.

**Comment by serra** [comment]
<img width="357" alt="image" src="https://github.com/apache/superset/assets/285398/65ff8458-8b5d-4eb0-902b-529bac3bfc16">
Reproduced in version 3.1.1

**Comment by rusackas** [comment]
Actually, a whole new heatmap plugin just merged, whish should solve this issue anyway. Please feel free to test the latest master if you want to try it, or wait for Superset 4.1
