### ISSUE TITLE
radio or checkbox in filter-box

### ISSUE THREAD

**Issue by Mikky72** [apache/incubator-superset#8267]
**Is your feature request related to a problem? Please describe.**

for a lot of dashboards we need to have a checkbox or radio button in the filter box
and maybe a range for a min-max

**Describe the solution you'd like**

It will be so helpful to a lot of people to have this, more interactive dashboard

**Describe alternatives you've considered**

**Additional context**

**Comment by jitendra-kumawat** [comment]
Do you any ux ..for you requirements
