### ISSUE TITLE
Table filter not working

### ISSUE THREAD

**Issue by cmyip** [apache/incubator-superset#8273]
When "emit filter events" is checked for table, filter no longer works. 

### Expected results
Clicking on rows in table should emit filter event and other widgets should react to filter events

### Actual results
Browser's console would log "Cannot read property 'columns' of undefined".

#### Screenshots
![image](https://user-images.githubusercontent.com/8801373/65371678-9f769800-dc98-11e9-9100-e2090a11a120.png)

![image](https://user-images.githubusercontent.com/8801373/65371665-840b8d00-dc98-11e9-8ceb-0d321afc2ba2.png)

#### How to reproduce the bug
This assumes we are using superset with sample data
1. Open "World's Bank Data" dashboard
2. Select Explore Chart
![image](https://user-images.githubusercontent.com/8801373/65371703-e795ba80-dc98-11e9-8e47-ebef6262d5e2.png)
3. Customize and select "Emit filter events"
![image](https://user-images.githubusercontent.com/8801373/65371710-fe3c1180-dc98-11e9-9c87-dbb3bea95a9d.png)
4. Go back to "World's Bank Data", click first column on any rows, you should see Javascript console error

### Environment

(please complete the following information):

- superset version: `0.34.1`
- python version: `3.7.4`
- node.js version: `10.16.3`
- npm version: `6.10.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ y] I have reproduced the issue with at least the latest released version of superset.
- [ y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cmyip** [comment]
Same as issue apache-superset/superset-ui-plugins#125

**Comment by oscarostlundgs** [comment]
This still seems to be an issue in 1.0.1. The table filter functionality is very useful for interactive dashboards.  Any chance we could reopen the issue? 

I narrowed down the issue to the dashboardFilter reducer trying to update an undefined filter as the getInitialState function only creates an initial filter for filter_box and filter_select types. (See [here](https://github.com/apache/superset/blob/master/superset-frontend/src/dashboard/reducers/getInitialState.js#L170))

Would creating an initial state for tables help here?

**Comment by villebro** [comment]
This functionality is currently being actively worked on - please see https://github.com/apache/superset/pull/12662 for the new functionality that was recently added and is currently being implemented on the table chart (and other charts) to replace the old deprecated logic.

**Comment by oost** [comment]
OK Thanks. Will that functionality be in the next version of Superset? 

If helps, I submitted a PR that fixes the issue with the current implementation. Basically just making sure dashboardFilters get an initial state for tables so when a changeFilter event is emitted, the dashboardFilter state for the chart can be updated.
