### ISSUE TITLE
Time in filter box is showing as unix timestamp

### ISSUE THREAD

**Issue by rajeshchy** [apache/incubator-superset#8278]
I am trying to use filter box and trying to filter data based on date. when i create filter based on date then date is being shown in epoch time. 

### Expected results

Date should show in yyyy-mm-dd format

### Actual results

it shows in epoch time like: 1568505600000

#### Screenshots

https://drive.google.com/file/d/1gTnKG8QkMWkzXoiRF-5fXiwpMo_f5LqC/view?usp=sharing

#### How to reproduce the bug

1. Create a table in postgres with DATE column
2. now create table in superset 
3. Change the Datetime Format in column of table to  %Y-%m-%d
4. try to create the filter box using that column

### Environment
Running superset with docker.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rajeshchy** [comment]
Screenshot:

<img width="566" alt="Screen Shot 2019-09-18 at 5 21 06 PM" src="https://user-images.githubusercontent.com/14107362/65411932-c0abc580-de0b-11e9-9762-e09c11948949.png">

**Comment by williamdrake** [comment]
I'm getting this as well. Not sure of a workaround since we can't filter by custom Metrics.

**Comment by dakotacody** [comment]
I'd like for this to not be stale since I am experiencing this issue too.

**Comment by junlincc** [comment]
problem resolved. https://github.com/apache/incubator-superset/pull/10268

**Comment by PiyushGupta3108** [comment]
Hi guys, i'm pretty new to Superset and have recently upgraded to superset 1.1 and i am getting the UNIX timestamp in filter box. Could you please suggest how to resolve it.

**Comment by snehlata08** [comment]
> change the core.py file under utils folder and change the json_int_dttm_ser function
> 
> def json_int_dttm_ser(obj): """json serializer that deals with dates""" val = base_json_conv(obj) if val is not None: return val if isinstance(obj, (datetime, pd.Timestamp)): # obj = datetime_to_epoch(obj) obj = obj.strftime("%m/%d/%Y") elif isinstance(obj, date):
> 
> ```
>     obj = (obj - EPOCH.date()).total_seconds() * 1000
>     obj = obj.strftime("%m/%d/%Y")
> else:
>     raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
> return obj
> ```
> 
> this worked for me ..

This didn't work for me. Can you please show the full code. Is there some mistake that I might have done.
