### ISSUE TITLE
Table View Data Exploration

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#828]
Typical data exploration steps
- go to table view
- group by dimensionD1
- find valueV1 interesting in dimensionD1
- add filter dimensionD1=valueV1 and replace dimensionD2 in the group by clause. 

Can we have nice way of doing this with UI ? 
I'm thinking on the table view, on-clicking on any Cell, there can be dropdown to select dimensionD2, on selecting which filter & dimension will be replaced. 

@mistercrunch  RFC.

**Comment by aibati2008** [comment]
+1, can we explore the data in table directly but not with group by?
