### ISSUE TITLE
Dashboard/Slice Favorite No Longer Working

### ISSUE THREAD

**Issue by MarcusSorealheis** [apache/incubator-superset#8283]
Every attempt to favorite a dashboard or slice returns a 401.

### Expected results

Favorites or slices. 

### Actual results

Error toast. 

#### Screenshots

![superset_favorite_bug](https://user-images.githubusercontent.com/2353608/65469232-89ddab80-de1b-11e9-914c-afb5fb92a1e5.gif)

#### How to reproduce the bug

1. Go to a dashbaord
2. Click on the favorite star
3. Look down to see the toast
4. See error (#3)

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.6.5`
- node.js version: `12.5.0`
- npm version: `6.10.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kuckjwi0928** [comment]
it is similar to this issue. (https://github.com/apache/incubator-superset/issues/8121)

**Comment by MarcusSorealheis** [comment]
As seen in PR #8013  and #6824  [here:](https://github.com/apache/incubator-superset/issues/6824#issuecomment-485318807) I've enabled proxy in my superset config file. I'm running everything locally and experiencing the issue.

**Comment by MarcusSorealheis** [comment]
ahh that's it. good point. I refreshed this environment today.
