### ISSUE TITLE
Problem upgrading superset to 0.30

### ISSUE THREAD

**Issue by cpr88** [apache/incubator-superset#8290]
Superset version
0.27.0

Expected results
upgrading to 0.30.0

Actual results
Error when I try to open Dashboard, Charts, Tables.

Steps to reproduce
1- pip install --upgrade pip.
2- pip install superset --upgrade
3- superset db upgrade
4- superset init
5- superset runserver

Previously, I did pip uninstall superset.
![image](https://user-images.githubusercontent.com/37386320/65550433-ef05cf80-def5-11e9-8ba0-183c26adc637.png)
![image](https://user-images.githubusercontent.com/37386320/65550447-f62cdd80-def5-11e9-9674-b54c3a57d2ef.png)

**Comment by Demonya** [comment]
Hi,I find the same problem,and I kill pid of superset,And then  can not found command:superset runserver。 when I try to start with command:superset run -p 8080 --with-threads --reload --debugger,I can not access to service even if there is no warning! Do you kown how to start service normally?Thank a lot!

**Comment by mulyadi** [comment]
I did the same things that @Demonya listed.
* Upgraded to 0.30.
* Could not start Superset server because there is no _superset runserver_.
* Ran _superset run -p 8080 --with-threads --reload --debugger_. The Superset server was not accessible anymore.

Also, in the installation documentation, it says port 8088, but the command above says port 8080.

**Comment by Demonya** [comment]
try command as follow:
GUNICORN_CMD_ARGS="--bind=0.0.0.0:8088 --workers=3" gunicorn superset:app
I can access to webserver,but still have other problems which may cause by my enviroment,Hope you can using normally!

**Comment by cpr88** [comment]
Hi! My superset is running on port 8088 and work fine. In fact, I can login into superset, but I cannot use Charts, Dashboards, and SQL Lab. I supose the problem is a version of Flask or SQL Alchemy dependency when I did the upgrade.

**Comment by AasthaPoddar** [comment]
Was anyone able to solve this?
