### ISSUE TITLE
Review and update chart colors for a11y

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#830]

**Comment by milapbhojak** [comment]
Hi @ascott Milap here, I am Product Designer and would love to work on UI, UX, Designing new data Viz for this project. Let me know how to get started.

**Comment by ascott** [comment]
hi @milapbhojak 👋  there are some issues tagged with `ui` that would be a good place to start. 
https://github.com/airbnb/caravel/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aui%20-label%3Aairbnb_roadmap

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.
