### ISSUE TITLE
Apply more Portuguese translations

### ISSUE THREAD

**Issue by oskarhinc** [apache/incubator-superset#8301]
**Is your feature request related to a problem? Please describe.**
There are some phrases across the app that are not translated at all or are missing the Portuguese translations. 

**Describe the solution you'd like**
We should use currently used mechanism to provide additional translations. 

**Additional context**
The list of required strings to translate:
- "Edit Dashboard" to "Editar Painel"
- "Force refresh dashboard" to "Forçar actualização do painel"
- "Set auto-refresh interval" to "Definir intervalo de actualização automática"
- "Share Dashboard" to "Partilhar Painel"
- "Query timeout" to "Demora na Consulta"
- "visualization queries are set to timeout at ${action.timeout} seconds. " to "as consultas de visualização estão definidas para um tempo limite de ${action.timeout} segundos. "
- "Perhaps your data has grown, your database is under unusual load, or you are simply querying a data source that is too large to be processed within the timeout range. If that is the case, we recommend that you summarize your data further." to "Os dados poderão ter aumentado de volume, o banco de dados pode estar sob uma carga incomum ou a consulta de dados seja muito grande para ser processada dentro do intervalo de tempo limite. Se esse for o caso, recomendamos que resuma seus dados ainda mais."
- "Apply" to "Aplicar" to "Last day" to "Último dia"
- "Last week" to  "Último semana"
- "Last month" to "Último mês"
- "Last quarter" to "Último quarto"
- "Last year" to "Último ano"
- "No filter" to "Sem filtro"
- "Last" to "Último"
- "Next" to "Próximo"
- "defaults" to "padrões"
- "seconds" to "segundos"
- "minutes" to "minutos"
- "hours" to "horas"
- "days" to "dias"
- "weeks" to "semanas"
- "months" to "meses"
- "years" to "anos"
- "Start / end" to "Começar / fim"
- "Relative to today" to "Em relação a hoje"
- "Custom" to "Costume"
- "Time range" to "Intervalo de tempo"
- "No results found" to "Dados não encontrados"
- "Data" to "Dados"
- "Customize" to "Customizar"

**Comment by SWoto** [comment]
Did u find a way to translate the time_range filter to Portuguese? Usually, when I change it to portugues the filter stops working.

**Comment by SWoto** [comment]
Yep, the filter and the x axis never gets translated... =/ @oskarhinc, do you know any solution?

**Comment by oskarhinc** [comment]
@SWoto, unfortunately, nothing comes to my mind for now.
