### ISSUE TITLE
Tabs in dashboard columns

### ISSUE THREAD

**Issue by micimize** [apache/incubator-superset#8303]
**problem / proposal**
For design reasons I'd like to nest tabs in columns.

**context**
I implemented on a fork by moving `onChangeTab` to context. If this feature is desired I can fix tests, add nesting constraints, and PR. (Though idk if the nesting constraints are all that necessary)

**Comment by mistercrunch** [comment]
What part of Superset are you referring to?

**Comment by micimize** [comment]
@mistercrunch dashboards. Tabs on `master` can only be top-level or nested within other tabs, and I'm proposing allowing deeper/less constrained nesting for building layouts such as:

![tabs in column](https://user-images.githubusercontent.com/8343799/65819528-72b80880-e1e3-11e9-9f61-6287ccf2762f.gif)

Here's a compressed diff of my current changes to `superset/assets/src/dashboard/util/isValidChild.js` (would of course refine the depth limits in an actual PR):
```diff
const parentMaxDepthLookup = {
   // ...
   [DASHBOARD_GRID_TYPE]: {
-    [TABS_TYPE]: depthOne,
+    [TABS_TYPE]: depthFive,
   },
   // ...
   [TABS_TYPE]: {
-    [TAB_TYPE]: depthTwo,
+    [TAB_TYPE]: depthFive,
   },

   [TAB_TYPE]: {
-    [TABS_TYPE]: depthTwo,
+    [TABS_TYPE]: depthThree,
   },

   [COLUMN_TYPE]: {
     // ...
+    [TABS_TYPE]: depthFive,
   },
   // ...
}
```

**Comment by micimize** [comment]
@mistercrunch would still like to PR this unless it is controversial. The live version of the gif above is [live on the aqdc](https://aqdatacommons.org/superset/dashboard/houston_mobile/) now

**Comment by Dirzel** [comment]
> @mistercrunch would still like to PR this unless it is controversial. The live version of the gif above is [live on the aqdc](https://aqdatacommons.org/superset/dashboard/houston_mobile/) now

Did you ever raise a PR for this, it's exactly what I'm looking for, I've also seen some other requests raised that would benefit from this.

**Comment by micimize** [comment]
@Dirzel I didn't – the ad-hoc solution I made doesn't consider the depth limits very carefully.
