### ISSUE TITLE
Add GroupyBy field to the Big Number

### ISSUE THREAD

**Issue by timurista** [apache/incubator-superset#8306]
**Is your feature request related to a problem? Please describe.**
I want to be able to extract a metric from a group of results.
For example I have a large set of results for a number of flown routes. These routes share several distinct city_pairs and I want to find the distinct count of a group of city pairs. I'd like to be able to group by city pairs and then show that list in a big number.

**Describe the solution you'd like**
Here's an example of the kind of query I would like to support
```
SELECT COUNT(*) FROM (
     SELECT city_pair
    FROM myFlownRoutesTable
    GROUP BY city_pair
    HAVING ((MAX(ss_utilization) > 0)
    )
```

**Describe alternatives you've considered**
I used the table chart to implement a group by city_pair with a having max clause. But while this table shows the results I can't find a way to just show the number of completed routes (ie a count of the table rows)

**Additional context**
The current Big Number
![image](https://user-images.githubusercontent.com/4718607/65722301-debe3380-e060-11e9-8faa-4c5f8d1616db.png)

The proposed Big Number update
![image](https://user-images.githubusercontent.com/4718607/65722436-1cbb5780-e061-11e9-8519-7f8fe5c26607.png)

The Table chart has this, so I would think you can just add another control variable with the group by option...

**Comment by villebro** [comment]
If I understood your use case correctly, creating an ad-hoc metric `COUNT(DISTINCT city_pair)` with an `ss_utilization > 0` WHERE clause should work.

**Comment by timurista** [comment]
@villebro I will try that, thank you. Is there a reason superset doesn't include group by for big number query? I see a cypress test that checks it is not there... and it would seem pretty easy to add BigNumber.js under controls just add the 'groupby' to the query controls. I forked the repo and tested this out and it works... were there some side effects that caused you to remove the groupby from the control set for big number?

**Comment by merkliopas** [comment]
> @villebro I will try that, thank you. Is there a reason superset doesn't include group by for big number query? I see a cypress test that checks it is not there... and it would seem pretty easy to add BigNumber.js under controls just add the 'groupby' to the query controls. I forked the repo and tested this out and it works... were there some side effects that caused you to remove the groupby from the control set for big number?

I second the above question. could any body elaborate on the reasons?

@timurista - could you share your code with the changes? that would be helpful, as I'm trying to make sense of superset code and change to suit my usecases

**Comment by Deninc** [comment]
> If I understood your use case correctly, creating an ad-hoc metric `COUNT(DISTINCT city_pair)` with an `ss_utilization > 0` WHERE clause should work.

This case might work for MAX agg but for other agg like SUM, COUNT there's no way to do it.
