### ISSUE TITLE
Proper documentation & example for - How write a connector?

### ISSUE THREAD

**Issue by ashim-k-saha** [apache/incubator-superset#8310]
### Motivation

Currently, I am using [dgraph](https://github.com/dgraph-io/dgraph) as my primary database. But could not find any connector for that, so decided to write. 

In the [FAQ](https://superset.incubator.apache.org/faq.html#does-superset-work-with-insert-database-engine-here) section I found

> Another key element for a database to be supported is through the Superset [Database Engine Specification](https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py) interface. This interface allows for defining database-specific configurations and logic that go beyond the SQLAlchemy and DBAPI scope.

Where the link ([Database Engine Specification](https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs.py)) is broken.

### Proposed Change

A step by step documentation will be very helpful.

With that, if we have a separate repository with example (maybe connector for REST-API) it will be great.

**Comment by Buuntu** [comment]
Is there currently REST API support or external CSV support to use as a data source?  If not, are there any workarounds to using external data not from a traditional database?

**Comment by mistercrunch** [comment]
The best is to load your data in a database.
