### ISSUE TITLE
Render links in table charts

### ISSUE THREAD

**Issue by holgerbrandl** [apache/incubator-superset#8312]
**Describe the solution you'd like**

In a table chart, I'd like to render a device id column (with values such as `device-1`, `device-2`), as link to the device's config page (e.g. `http://some.where/?q=device-1` ). 

**A clear and concise description of what you want to happen.**

It would be great if an url-template including a value placeholder (e.g. `http://some.where/?q=${s}` or similar) could be configured, which is picked up by the system to render the value as a link.

**Comment by suddjian** [comment]
Tables support HTML tags, so you could do some string manipulation in SQL and get <a> elements in your query results.

**Comment by moksh-enf** [comment]
You can also render them in other tables by modifying the code a little bit.

**Comment by wenqi73** [comment]
Can use CONCAT in calculated columns to resolve this(https://preset.io/blog/understanding-superset-semantic-layer/):
```sql
CONCAT('<a href="https://github.com/', host, '/issues/', '" target="_blank">', host, '</a>')
```

**Comment by moksh-enf** [comment]
> Can use CONCAT in calculated columns to resolve this(https://preset.io/blog/understanding-superset-semantic-layer/):
> 
> ```sql
> CONCAT('<a href="https://github.com/', host, '/issues/', '" target="_blank">', host, '</a>')
> ```


That will work for a Normal table but wont work for a Pivot Table

**Comment by moksh-enf** [comment]
> Hello! Can You inform please this creating link option works only in table chart? I cann't repeat this trick with pivot table or bubble chart to make clickable bubble - is it impossible now or need more specific knowledge? Thanks a lot)

I was able to get links in a pivot table to some extent mentioned here
https://github.com/apache/superset/issues/16778

It did not work when you added filters. Probably some more tweaking and it could work!
