### ISSUE TITLE
Freeze the table header in Time series visualisation

### ISSUE THREAD

**Issue by krishna9626** [apache/incubator-superset#8313]
In the Time series table visualisation,column headers are not fixed.It moves based on scroll bar.If there are more no of columns it is difficult to find the corresponding column header.It affects the readability.
Screenshot for your reference.

**Image1** (Default)
![1](https://user-images.githubusercontent.com/36255856/65758251-67f36a00-e136-11e9-8671-b262637345d5.png)

**Image2**(Scrolling)
![2](https://user-images.githubusercontent.com/36255856/65758257-6aee5a80-e136-11e9-89cb-ac490551844f.png)
                         This visualisation is from "**Reactable NPM**". I didn't find any option to resolve in the document.

**Comment by davidhassan** [comment]
This is also similiar to 8328.

**Comment by kalimuthu123** [comment]
Hii customised fixed Header by using css Plese check this

table thead tr:nth-child(1) th{
   background: white;
   position: sticky;
   top: 0;
   z-index: 10;
 }
