### ISSUE TITLE
Deck GL plots 5.3 version with google maps integration in react js zoom issue with plots

### ISSUE THREAD

**Issue by tanmaykul** [apache/incubator-superset#8321]
I am using deck gl 5.3 version for adding scatter plots and arc layer plot with google maps and I am facing issue as when I am zooming the maps, the plots are not  zooming with the maps. the plots are moving away from the maps when we zoom in or out.

**Comment by tanmaykul** [comment]
![image](https://user-images.githubusercontent.com/15089955/65851932-2d761100-e372-11e9-98d8-ce750c1fb48e.png)

**Comment by suddjian** [comment]
Some repro steps would be useful here.
