### ISSUE TITLE
TypeError: Cannot read property '0b15b5daf836c399f755c742e77dd20c' of undefined #question

### ISSUE THREAD

**Issue by Demonya** [apache/incubator-superset#8323]
### Expected results

Using Time-series-table to show total number.
### Actual results
TypeError: Cannot read property '0b15b5daf836c399f755c742e77dd20c' of undefined
#### Screenshots
![image](https://user-images.githubusercontent.com/32725399/65858675-23b3d400-e399-11e9-9ba9-548d7bcbb6f9.png)
![image](https://user-images.githubusercontent.com/32725399/65858748-5067eb80-e399-11e9-8c91-f2f8ae585daa.png)
![image](https://user-images.githubusercontent.com/32725399/65859343-86599f80-e39a-11e9-8034-ec9d22094ec9.png)

#### How to reproduce the bug

1. Go to 'explore',choose Visualization Type
2. Click on 'Time Series Columns'
3. Scroll down to 'Column Configuration' and choose Type:Time comparison,run query

### Environment

(please complete the following information):

- superset version: `0.30.0`
- python version: `3.7.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Can repro, taking a look at this.

**Comment by suddjian** [comment]
Apparently you need to specify a value for "Time Lag" for this to work.
