### ISSUE TITLE
Superset version .33 version

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8329]
### Expected results

what you expected to happen.

### Actual results

can anyone provide me the actual source code of superset

what actually happens.
i am not able to view charts with gamma user and so many folders are also not coming with .33 version

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by SaitejaP** [comment]
Looks like created the issue by mistake
