### ISSUE TITLE
Today's data is missing when filtering last x days

### ISSUE THREAD

**Issue by SaitejaP** [apache/incubator-superset#8334]
The where clause takes max time till today's 0th hour thereby ignoring entries for today.

### Expected results

When I select last 7 days, the where clause is expected to be `WHERE updated_at >= '2019-09-25 00:00:00' AND updated_at <= now()`

### Actual results

`WHERE updated_at >= '2019-09-25 00:00:00' AND updated_at <= '2019-10-02 00:00:00'`

_Today is 2nd Oct_

#### Screenshots

![image](https://user-images.githubusercontent.com/45468931/66014090-26264300-e4eb-11e9-9101-3be1e87aa1f5.png)
![image](https://user-images.githubusercontent.com/45468931/66014080-1f97cb80-e4eb-11e9-90e7-7ede3ef5c928.png)

#### How to reproduce the bug

1. Go to 'create a new chart'.
2. Select any datasource, choose `Line Chart` as visualization type and create a new chart.
3. Select any `datetime` column for time column, `day` as time grain, `Last Week` as time range.
4. Run query.
5. Click on view query to see the error.

### Environment

- superset version: `0.34.0`
- python version: `3.6.4`
- node.js version: `4.8.2`
- npm version: `not sure`

### Checklist

- [√] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [√] I have reproduced the issue with at least the latest released version of superset.
- [√] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
You can define how `today` is handled by default in `superset_config.py` (check the defaults in `superset/config.py`). You can also write `now` in the to-field to make it reference the current time instead of midnight.
