### ISSUE TITLE
Superset not loading LOCAL configuration

### ISSUE THREAD

**Issue by liya2664** [apache/incubator-superset#8340]
I have set my pythonpath using `export PYTHONPATH=/home/flaskuser/config/`
And when i run `superset db upgrade` it was not loading files in my config folder which consists of `superset_config.py`

`Python 3.6.8`
`superset 0.27.0`

**Comment by mmutiso** [comment]
Could you try setting the SUPERSET_HOME variable as well and see the behaviour?

**Comment by liya2664** [comment]
@mmutiso 
Issue with requirements.txt, I resolved it
Thanks
