### ISSUE TITLE
Package 'libldap2-dev' has no installation candidate

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8342]
### Expected results

I expected the [OS dependencies instructions for Debian](https://superset.incubator.apache.org/installation.html#os-dependencies) to work when I typed `sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip libsasl2-dev libldap2-dev`

### Actual results

```bash
scemelab@metta:~/domains/link/metalevel/superset/incubator-superset$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip libsasl2-dev libldap2-dev
[sudo] password for scemelab:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libldap2-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libldap2-dev:i386

E: Package 'libldap2-dev' has no installation candidate
scemelab@metta:~/domains/link/metalevel/superset/incubator-superset$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip libsasl2-dev libldap2-dev:i386
[sudo] password for schemelab:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libldap2-dev:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libldap2-dev
```

### Environment

`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```bash
scemelab@metta:~/domains/link/metalevel/superset/incubator-superset$ cat /etc/issue
Debian GNU/Linux 9 \n \l

```

**Comment by dpgaspar** [comment]
Hi,

Assuming your using Debian 9 (Stretch), have you done (before apt install):
`sudo apt-get update`
?
