### ISSUE TITLE
Filter Button [Apply] Position 

### ISSUE THREAD

**Issue by SWoto** [apache/incubator-superset#8348]
I've been working with some data that has big company names and noticed that when someone apply several filters (on the same column) the button apply disappear because it is located on the Chart's bottom.

I change the position to bellow the drop-down button, but it still not good (visually), and would be a lot better to be in the left of the drop-down button. I'm trying to do this, but it'll take some time because i don't know React YET...

### Current Modification

I just wrote a css to set a class with
```
margin-left: auto;
margin-right: 0;
display: block;
```
and added the class to the Filter Button.
![Modified](https://user-images.githubusercontent.com/26379593/66209866-c36dac80-e68e-11e9-80c0-ae979ba01f1a.png)

### Expected results

I thin it would be really good to have like the image bellow, better to view and without that problem.
![Desired](https://user-images.githubusercontent.com/26379593/66209771-7db0e400-e68e-11e9-9983-b3d94fcd6d27.png)

### Actual results

Now, with the current way, after selecting a set of filters, it can't be applied because the button is hidden.
![Current Result](https://user-images.githubusercontent.com/26379593/66209987-15aecd80-e68f-11e9-808d-3eaa9a14a922.png)

#### How to reproduce the bug

1. Go to any dashboard
2. Choose any filter slice and configure it to have the apply button.
3. Select enough filters to hide the apply button

### Environment

- superset version: 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.16.3
- npm version: 6.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Somewhat related: the overflow on this component is tricky because the dropdowns containers themselves should scroll, but when the dropdown gets opened-up, it should probably overflow over (not scroll)

**Comment by rusackas** [comment]
@mistercrunch or @SWoto:

When trying to recreate this issue, I don't see the Apply button in the top right like the "expected results" above. I see it below my filter inputs, like so:

![image](https://user-images.githubusercontent.com/812905/68319854-d7cd0c80-0073-11ea-9102-bc48613e721c.png)

Is this correct/expected?

Also, I do see that the input AND the button push out of bounds... I'll look at making that section of the component scrollable when it overflows.

![image](https://user-images.githubusercontent.com/812905/68319973-06e37e00-0074-11ea-9226-a8499d80e140.png)

**Comment by rusackas** [comment]
@mistercrunch Curious as to your thoughts, but I spent some time poking at this thing from various angles. What I don't see is a simple or CSS-based path to fix this. 

To have the fly-out menu of options _NOT_ cut off by the scroll area which _DOES_ cut off the select pulldown inputs, we'd have to have two branches of elements on the DOM tree, and keep them positionally synchronized during scrolling/windowResize events. Not really React's strong suit, but possible. It would also mean building the inputs/menus with new components and not involving the `react-virtualized-select` module (which is not supported anymore anyway), and building something custom, using some other virtualized list library.

Given the time involvement of what it would take to solve this issue while keeping the component working/looking like it does today, I think we should postpone this as we consider a larger design solution around (potentially) a global filters component/system which may ultimately deprecate or replace this.

**Comment by mistercrunch** [comment]
I also sank some time trying to solve this CSS puzzle without success. Solution might be in the dashboard-native filter on the roadmap.
