### ISSUE TITLE
table header taking full height when you explore the table.

### ISSUE THREAD

**Issue by gaurav-infostretch** [apache/incubator-superset#8354]
when i click on SQL Editor and run the query it shows table perfectly but when i click on "Explore", it shows a table with header of full height and not able to view the data. 

When i inspect there is CSS applying to it which show  "height :100% !important" which is dynamic styling due to that not able to override or fix the height of the table header.

**Comment by kuckjwi0928** [comment]
@gaurav-infostretch 
Can you tell me the superset version?

**Comment by gaurav-infostretch** [comment]
> @gaurav-infostretch
> Can you tell me the superset version?

0.28
