### ISSUE TITLE
NLP (Natural Language Processing) Integration with sql Lab

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#8360]
**Is your feature request related to a problem? Please describe.**
I am having a requirement of Bot integration across superset 

**Describe the solution you'd like**
For bot integration i have to process a natural language processing

**Describe alternatives you've considered**
Api microservice which will be ready to process nlp

**Comment by ullayne02** [comment]
how it works? SQLab recives a message and translate to a consult?

**Comment by kalimuthu123** [comment]
get the voice message or text message from end user and then converts it to sql then pass sql query to the sql lab api to get data  and then process the output 
Superset bot

**Comment by willbarrett** [comment]
Hi @kalimuthu123 - this sounds out of scope for Superset, but it could be interesting for you to use one of the many chat bot frameworks out there to integrate with both your text/voice vendor and the SQL Lab API. We've discussed improving the data access layer to better support workflows like this in the future.

**Comment by kalimuthu123** [comment]
hi @willbarrett  i am very much interested to work with this new feature

**Comment by XuanmoFeng** [comment]
https://storage.googleapis.com/pub-tools-public-publication-data/pdf/45791.pdf

**Comment by XuanmoFeng** [comment]
this is  nl2sql

**Comment by kalimuthu123** [comment]
@XuanmoFeng ya exactly iam talking about that Feature things in this Tool if we put it in the tool the tool will be a great one

**Comment by XuanmoFeng** [comment]
> @XuanmoFeng恰好是我在谈论该工具中的功能，如果我们将其放入该工具中，该工具将是一个很棒的工具。我们能够使用pypi [https://pypi.org/project](https://pypi.org/project/ln2sql/)中提供的软件包
> [/ ln2sql /](https://pypi.org/project/ln2sql/)

it's so cool ,we can make a search box that like google ,

**Comment by kalimuthu123** [comment]
yes its possible in thesqllab but making use of this package

**Comment by ShabeeraBeebi** [comment]
@kalimuthu123 where you able to identify the API for queries and connect it to bot?. kindly help
