### ISSUE TITLE
CTAS executed but resulting table not created

### ISSUE THREAD

**Issue by trepmag** [apache/incubator-superset#8362]
CTAS executed but resulting table not created.

### Expected results

Generated table existing in the database.

### Actual results

Log portion showing that the related instruction is executed:

```
superset_1  | 2019-10-09 14:59:13,727:DEBUG:root:Fetching data for query object: {'changedOn': datetime.datetime(2019, 10, 9, 14, 59, 12, 652119), 'changed_on': '2019-10-09T14:59:12.652119', 'dbId': 4, 'db': 'ig3is', 'endDttm': None, 'errorMessage': None, 'executedSql': 'CREATE TABLE public.zzz AS \n-- Note: Unless you save your query, these tabs will NOT persist if you clear your cookies or change browsers.\n\nSELECT id_gas,\n       gas_acro,\n       gas_name,\n       gas_info\nFROM public.gas\nLIMIT 100', 'id': 'iCmKnonTn', 'limit': 100, 'progress': 0, 'rows': None, 'schema': 'public', 'ctas': True, 'serverId': 111, 'sql': '-- Note: Unless you save your query, these tabs will NOT persist if you clear your cookies or change browsers.\n\nSELECT id_gas,\n       gas_acro,\n       gas_name,\n       gas_info\nFROM public.gas\nLIMIT 100', 'sqlEditorId': 'Gxp1oIezo', 'startDttm': Decimal('1570633152373.131000'), 'state': 'running', 'tab': 'test zzz', 'tempTable': 'public.zzz', 'userId': 1, 'user': 'Admin user', 'resultsKey': None, 'trackingUrl': None, 'extra': {'progress': 'Running statement 1 out of 1'}}
superset_1  | 2019-10-09 14:59:13,727:DEBUG:root:[stats_logger] (timing) sqllab.query.time_fetching_results | 3.83984375 
superset_1  | 2019-10-09 14:59:13,727:DEBUG:root:Fetching cursor description
superset_1  | 2019-10-09 14:59:13,734:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@somehost:5432/ig3is
superset_1  | 2019-10-09 14:59:13,735:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@somehost:5432/ig3is
```

![image](https://user-images.githubusercontent.com/875021/66494511-1218ad80-eab8-11e9-9529-9c1ed2a17183.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/875021/66493691-c44f7580-eab6-11e9-95f4-b33f0f32c852.png)

#### How to reproduce the bug

See above screenshot

### Environment

- superset version: `0.34`
- python version: `3.6.8`
- node.js version: `v10.15.3`
- npm version: `6.4.1`

Runned using the docker-compose given in the git repository at https://github.com/apache/incubator-superset/tree/0.34.1rc2/contrib/docker

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @trepmag,

I'm able to reproduce this, investigating...

**Comment by villebro** [comment]
I think you need to commit (remembering a related discussion some time ago). Perhaps we should add an option to autocommit in the datasource settings?

**Comment by dpgaspar** [comment]
May be that, I've checked and the correct query gets to `db_engine_specs.execute`, and (of course) also makes it to PG.

**Comment by villebro** [comment]
Very weird warning, considering it clearly has something to commit. Looked around and stumbled across this, related perhaps? https://stackoverflow.com/questions/28593685/why-does-this-postgresql-transaction-give-warning-there-is-no-transaction-in-p

**Comment by rc-ontruck** [comment]
You can solve this issue in a simple way;
first change your data connection to:
`    postgresql+psycopg2://username:XXXXXXXXXX@database_server_name:5432/database`

them in the extra parameters
```
{
"metadata_params": {},
"engine_params": {"isolation_level":"AUTOCOMMIT"},
"metadata_cache_timeout": {},
"schemas_allowed_for_csv_upload": []
}

```

**Comment by GRIDgeneva** [comment]
Absolutely, it woks!

Thank you all there for looking into this...
