### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by venlee1993** [apache/incubator-superset#8366]
copying superset\static\assets\.cache-loader\e34f9d96f1e720a24eb4203d0ee716ab.json -> build\lib\superset\static\assets\.cache-loader
    copying superset\static\assets\.cache-loader\e7c0cd5a9e08d14a0736090723cefbd2.json -> build\lib\superset\static\assets\.cache-loader
    copying superset\static\assets\.cache-loader\f1745700e3c5df3e849eeb53184ad653.json -> build\lib\superset\static\assets\.cache-loader
    creating build\lib\superset\static\assets\.terser-plugin-cache
    creating build\lib\superset\static\assets\.terser-plugin-cache\content-v2
    creating build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512
    creating build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512\00
    creating build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f
    copying superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f\4e8df4f5ee7921b2270d4e4b41484d51b0f9179c662a55d62128f18abf1686780a3620666b8d0f53752f414c3c1bdf8cafd5de04e357c01b4ec561ab7581 -> build\lib\sup
erset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f
    error: could not create 'build\lib\superset\static\assets\.terser-plugin-cache\content-v2\sha512\00\0f\4e8df4f5ee7921b2270d4e4b41484d51b0f9179c662a55d62128f18abf1686780a3620666b8d0f53752f414c3c1bdf8cafd5de04e357c01b4e
c561ab7581': No such file or directory

**Comment by zhaoyongjie** [comment]
how to reproduce this issue?

**Comment by betodealmeida** [comment]
@venlee1993 can you give more context on this error? What command did you run?

**Comment by ZZXM** [comment]
The same thing happened to me and the solution didn't work

**Comment by willbarrett** [comment]
From the `\` characters in the path, I'm guessing that you are attempting to install Superset on Windows. At the moment, Windows is not a supported operating system.
