### ISSUE TITLE
Update visualizations to use consistent styling for axis, legends, tooltips

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#837]
Focus on these top 7 chart types.
- [ ] Line
- [ ] Area
- [ ] Table
- [ ] Bar
- [ ] Markup
- [ ] Pie/Donut
- [ ] Big Number

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 312 days. Feel free to comment and request for this issue to be reopened.
