### ISSUE TITLE
Finance Related Charts

### ISSUE THREAD

**Issue by majeedus** [apache/incubator-superset#8375]
**Is your feature request related to a problem? Please describe.**
I've been looking around and can't really find any stock/candlestick or finance related charts in the demo/gallery. Are there any implementations out there, and if not, it would be great to add some as a feature.

Thanks

**Comment by zhaoyongjie** [comment]
@majeedus   Can give some finance related charts example?

**Comment by jitendra-kumawat** [comment]
OLHC and candlestick(http://nvd3-community.github.io/nvd3/) can be used for that purpose

**Comment by cnzx219** [comment]
when i can use this feature

**Comment by willbarrett** [comment]
Currently charts are implemented as plugins to Superset. We would be happy to see pull requests implementing additional charts over at https://github.com/apache-superset/superset-ui-plugins

**Comment by LeoDiep** [comment]
> Currently charts are implemented as plugins to Superset. We would be happy to see pull requests implementing additional charts over at https://github.com/apache-superset/superset-ui-plugins

Up.
Finance is one of the fields that extensively utilizes data on a daily basis. Introducing visualization such as stock price charts and additional indicators within Superset could mark a pivotal juncture, drawing considerable user interest
