### ISSUE TITLE
I can't find src folder.

### ISSUE THREAD

**Issue by mingyumkim93** [apache/incubator-superset#8383]
### Expected results

src folder in assets folder

### Actual results

I can't find src folder.

#### Screenshots

<img width="483" alt="Capture" src="https://user-images.githubusercontent.com/43638576/66734983-caa27080-ee6d-11e9-96a3-47217d23d53f.PNG">

#### How to reproduce the bug

1. Go to '.../superset/static/assets/'
2. Check what this folder has

### Environment

- superset version: `0.30.0`
- python version: `3.6.8`
- node.js version: `8.10.0`
- npm version: `3.5.2`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
-  I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I would like to customize view part so I'm looking for front end code files. If I understood correctly, those files should be in src folder and the src folder is in assets folder but I couldn't find it. Am I going wrong way? Any help would be appreciated. Thank you.

**Comment by blcksrx** [comment]
What do you want to do with this directory? it does not exist when you use the built version.

**Comment by mingyumkim93** [comment]
> What do you want to do with this directory? it does not exist when you use the built version.
Thank you very much, I got what you mean.

**Comment by Demonya** [comment]
So which folders replaces src folder ？

**Comment by blcksrx** [comment]
@Demonya Clone the repo and you can find it in `superset/assets` path
