### ISSUE TITLE
Allow the months and days embedded within charts to be displayed in Portuguese

### ISSUE THREAD

**Issue by oskarhinc** [apache/incubator-superset#8388]
**Is your feature request related to a problem? Please describe.**
We could add localization for months and days names for the charts, so it's translated to Portuguese. 

**Describe the solution you'd like**
We could use mechanism built in d3 and moment libraries, to use proper localization here.

**Additional context**
If it'll be quick and easy to achieve, we can also add support for other languages that are supported by the libraries.

**Comment by oskarhinc** [comment]
After I've dived into the implementation, it occurs that those components are defined in [plugins from a separate repo](https://github.com/apache-superset/superset-ui/tree/master/packages/superset-ui-time-format), which uses [d3 library](https://github.com/d3/d3-format) for date and time formatters. D3 supports localization, however, it's not used by the plugins, so I've created [an issue there](https://github.com/apache-superset/superset-ui/issues/238) for supporting it.

**Comment by oskarhinc** [comment]
Closed by mistake - reopening

**Comment by cdmikechen** [comment]
I have also encountered this problem, and I am going to analyze and solve it
