### ISSUE TITLE
Add support for Bound filters in Druid

### ISSUE THREAD

**Issue by psalaberria002** [apache/incubator-superset#839]
It would be great to support the Bound filter in Caravel.

Have you guys thought about it? I guess it also applies for the Javascript filter.

The backend depends on https://github.com/druid-io/pydruid/pull/60

Any ideas about the frontend? How should the bound filter look like?

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 632 days. Feel free to comment and request for this issue to be reopened.
