### ISSUE TITLE
import_datasources not working 

### ISSUE THREAD

**Issue by rinshadka** [apache/incubator-superset#8395]
I am running superset version - 0.29.0rc7 and using postgresql as backend.
While I tried importing datasource from yaml file , the encrypted password field in not updating in the dbs table. But if I configure datasource from interface , its working fine.

I have tried the following command,

superset import_datasources -p DBConnection.yaml

-------- cat DBConnection.yaml ----------
- database_name: DEVL-Database
  extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
    metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
    }\r\n"
  sqlalchemy_uri: postgresql+psycopg2://postgres:postgres123@10.10.10.151/devl
  tables: []
-----------------------------------------

When I click "Test" connection , showing no authentication password supplied.

**Comment by rinshadka** [comment]
While clicking "Test Connection" getting error as -> ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(psycopg2.OperationalError) fe_sendauth: no password supplied\n (Background on this error at: http://sqlalche.me/e/e3q8)"

**Comment by ivansocket** [comment]
@rinshadka any solution found? I am having exactly the same problem. Thanks in advance.

**Comment by DungLai** [comment]
same problem, `import datasources -p file.yaml` is not working

**Comment by ivansocket** [comment]
source venv/bin/activate
superset import_datasources -p /workspace/<path or filename>

**Comment by ljpeters** [comment]
I've managed to get it to work:
```
superset import_datasources -p /tmp/DATABASE.yaml
superset set_database_uri -d name_of_datasource_in_DATABASE.yaml -u postgresql://user:password@host:5432/database
```
after which I have a successful connection test.

**Comment by zseta** [comment]
Just in case anyone finds this via google, the example provided by @ljpeters works, but for me the `name_of_datasource_in_DATABASE.yaml` was confusing so here's another example that works:

sources.yaml:
```yaml
databases:
- database_name: My database
[...]
```

```bash
superset import_datasources -p sources.yaml
superset set_database_uri -d "My database" -u postgresql://user:pass@db_host:5432/db_name
```
