### ISSUE TITLE
explore_json  return error that 'an error occured'

### ISSUE THREAD

**Issue by blcksrx** [apache/incubator-superset#8397]
`explore_json` return error with this content `an error occurred` for queries that approximately takes time more than '00:01:57' while the query returns in the `sql_lab`.
This issue happens while I increased the `webserver timeout` and it's big enough for that!

### Expected results

Show table in `explore_json`

### Actual results

Superset just returns error with this content: `an error occured`

#### Screenshots

![Screenshot from 2019-10-15 18-46-20](https://user-images.githubusercontent.com/35199552/66845055-42f75780-ef7c-11e9-952b-6d89ccc09f19.png)

#### How to reproduce the bug

1. Go to 

### Environment

(please complete the following information):

- superset version: `master branch from 3 weeks ago`
- python version: `3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by blcksrx** [comment]
@mistercrunch Also I have a question about the structure of `viz.py`. I read the code and realized that in the `viz.py` superset does not use `celery task` to run queries of a `dashboard` or `explore_json`.
why it should be not used while the `dashboards` and in general visualization is one major usage of Superset. I mean there are a lot of queries that exist on a dashboard and with celery task, it would be better to run.

**Comment by blcksrx** [comment]
It was related to `gunicorn` timeout.

**Comment by prajamani** [comment]
@blcksrx 

What was the fix that you did for gunicorn timeout ?  I see that the timeout happens at 2 minutes in your example. I'm running into similar issue and played with timeout and worker-class but it didn't help.

**Comment by blcksrx** [comment]
Increase `gunicorn` and `SUPERSET_WEBSERVER_TIMEOUT` both!
In mu case the superset webserver gunicorn was less than gunicorn timeout and in this case the when the gunicorn reached at timeout superset returned error above

**Comment by prajamani** [comment]
`SUPERSET_WEBSERVER_TIMEOUT` is set to 120 seconds. 

`gunicorn` timeout is set to 150 seconds.

`gunicorn \
        --bind  "0.0.0.0:8088" \
        --workers $((2 * $(getconf _NPROCESSORS_ONLN) + 1)) \
        -k gevent \
        --timeout 150 \
        --limit-request-line 0 \
        --limit-request-field_size 0 \
        --access-logfile '-' \
        --error-logfile '-' \
        superset:app`

I'm still getting random timeouts (15 secs, 22 secs,.). Here's the error we get in the browser as the connection gets dropped by the webserver.

`POST superset/explore_json/?form_data=%7B%22slice_id%22%3A62%7D&force=true net::ERR_EMPTY_RESPONSE
TypeError: Failed to fetch`

Do we need any specific timeout setting in ngnix for the above `SUPERSET_WEBSERVER_TIMEOUT` and `gunicorn` timeout settings to work ?
