### ISSUE TITLE
Unable to filter by dates in Dashboard.Throws ORA-01843: not a valid month

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8402]
I have tried to create a dashboard which includes a date column.
When I try to open the dashboard and select a filter which is a date column , it gives me ORA-01843: not a valid month error.

But when I try to take the query object and run in Oracle DB directly , it works well.

But if I run the same query in superset , it throws me error.

When I do the below modifications to the query it works :
1.Either add TO_DATE to the values selected .Example
 where sample_date in TO_DATE('10-10-2019','MM-DD-YYYY')

or

2.Add TO_CHAR to the column 
where TO_CHAR(sample_date,'MM-DD-YYYY) in ('10-10-2019')

Why is it like that.I am unable to perform any date comparisons

**Comment by villebro** [comment]
Please use the standard issue template, it helps the maintainers understand context around your issue. Details such as version number are very helpful information as resolution of certain bugs can be attributed to specific version numbers.

In your dashboard, please click `Explore chart` on the chart that is emitting the error message, and once in the Explore view, click on the upper right-hand menu and select `View query` and paste the contents here. Furthermore, please check the datatype of your temporal column and share that here.

**Comment by umesh11111** [comment]
here are the screen shots for the issue
![image](https://user-images.githubusercontent.com/43033939/66994496-f9794a80-f0ea-11e9-8d3f-2144f26e7a22.png)
![imag1](https://user-images.githubusercontent.com/43033939/66994595-1f9eea80-f0eb-11e9-963d-bd702ec84c79.PNG)

when im selecting any dates from filter box i am getting the error not a valid month

**Comment by villebro** [comment]
I have a hunch where the problem might be, but I seem to have misplaced my Oracle container so can't reproduce+fix+test right away. Will try to look into this in the coming days.
