### ISSUE TITLE
User Impersonation Documentation/Example

### ISSUE THREAD

**Issue by Tom-Kun** [apache/incubator-superset#8406]
We use superset to execute queries on a Hiveserver2 node. But I cannot find any documentation or example of how we can configure superset to use user impersonation through Hive. We want to identify which user run which query.

Users are authenticated through a LDAP configuration which is currently working.

But when I check the "impersonate the logged on user", it's still my "superset" user which is launching the job and not the proper user.

Here is my database configuration:
`hive://node-01.example.com:10000/toto`
`{ "metadata_params": {}, "engine_params": { "connect_args": { "auth": "KERBEROS", "kerberos_service_name": "hive" } } }`

Add a documentation on the "Security" section of the Apache Superset project with a little example on Hive/PrestoDB.

**Comment by dpgaspar** [comment]
Hi @Tom-Kun,

Is your superset auth done with `AUTH_TYPE = AUTH_LDAP`?

**Comment by Tom-Kun** [comment]
Hi @dpgaspar,

Yup, I have the following configuration
`AUTH_LDAP_BIND_USER=uid=admin,cn=users,dc=example,dc=local`
`AUTH_LDAP_BIND_USER=uid=admin,cn=users,dc=example,dc=local`
`AUTH_LDAP_BIND_USER=uid=admin,cn=users,dc=example,dc=local`
`AUTH_LDAP_BIND_USER=uid=admin,cn=users,dc=example,dc=local`
`AUTH_LDAP_BIND_USER=uid=admin,cn=users,dc=example,dc=local`

**Comment by dpgaspar** [comment]
First of all I'm not familiar with hive. 
But superset LDAP authentication is not the same thing as kerberos auth, so this kind of setup will not work.
At most and this is just an uninformed opinion, you could setup kerberos auth at the web server/os level and set superset auth to AUTH_REMOTE_USER, and take it from there.

**Comment by rosmartorres** [comment]
Hi, 
Is it possible use impersonate user for another DB (no hive or presto)? 

Thanks
