### ISSUE TITLE
[docs] Installation instructions refer to port 8088 but command is 8080

### ISSUE THREAD

**Issue by francishemingway** [apache/incubator-superset#8412]
In the installation instructions, the text refers to port 8088 but command is 8080

**Comment by dpgaspar** [comment]
Going to close this one, seen your fix #8413, Thank you!

**Comment by buzzware** [comment]
Is SUPERSET_PORT correctly set to 8080 in the Dockerfile? Or should it be 8088? We are having trouble connecting via wget to superset from outside the container, when we can connect from inside.

**Comment by dpgaspar** [comment]
@buzzware open a specific issue for that, since it's not totally related with this issue

**Comment by buzzware** [comment]
@dpgaspar  Primarily I just want an experienced opinion on whether SUPERSET_PORT is wrongly set to 8080 just like the documentation error this issue refers to.
