### ISSUE TITLE
The database password is exported along with the dashboards

### ISSUE THREAD

**Issue by oskarhinc** [apache/incubator-superset#8415]
While exporting the dashboards, the database password is exported as well (in plaintext) despite it's not used when importing them later.

### Expected results

The password is not exported at all.

### Actual results

The password is exported.

#### How to reproduce the bug

1. Go to 'Dashboards'
2. Select all dashboards
3. Press Actions -> Export
4. In the downloaded JSON file, look for "password:"

### Environment

(please complete the following information):

- superset version: `0.34.0`
- python version: `3.6.8`
- node.js version: `v8.16.1`
- npm version: `6.11.3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
Closing this issue, since it no longer happens.

**Comment by duarte-pompeu-feedzai** [comment]
> Closing this issue, since it no longer happens.

I still see the password in `sqlalchemy_uri` when exporting 🤔
