### ISSUE TITLE
ModuleNotFoundError: No module named 'pyodbc'

### ISSUE THREAD

**Issue by toilv** [apache/incubator-superset#8421]
I followed the guide install the docker.
Trying to connect to SQL server but seem error.
The env of python cause this problem but i don't know how to fix it.
Ubuntu 18.04: python 2.7 and python 3.6 version

File "/home/superset/superset/views/core.py", line 1702, in testconn
superset_1  |     engine = database.get_sqla_engine(user_name=username)
superset_1  |   File "/home/superset/superset/utils/core.py", line 131, in __call__
superset_1  |     value = self.func(*args, **kwargs)
superset_1  |   File "/home/superset/superset/models/core.py", line 911, in get_sqla_engine
superset_1  |     return create_engine(url, **params)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
superset_1  |     return strategy.create(*args, **kwargs)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
superset_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/connectors/pyodbc.py", line 37, in dbapi
superset_1  |     return __import__("pyodbc")
superset_1  | ModuleNotFoundError: No module named 'pyodbc'

**Comment by willbarrett** [comment]
Hi @toilv - Please check the [list of database dependencies](https://superset.incubator.apache.org/installation.html#database-dependencies) and ensure that you have the proper Python packages installed for the database you're targeting. I think you'll need to install `pymssql` to support SQL Server. If installing `pymssql` doesn't fix the issue, it's possible our documentation is out of date. I hope this helps!
