### ISSUE TITLE
Unable to use Table Timestamp Format dropdown option

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8428]
when i am creating the table and selecting the customize option and try to choose any date format value from the option its not working .

### Expected results
Date format should apply on the date column fields in the table

### Actual results
Dropdown value of Table Timestamp Format is not working at all.

![image](https://user-images.githubusercontent.com/43033939/67303275-d813c680-f50f-11e9-9863-bc67c06fb52d.png)

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
👀

**Comment by vnnw** [comment]
I encountered the same issue even trying various versions, such as 0.35.2, 0.34.0...
Any update?
