### ISSUE TITLE
How to add a new Country Map when using Docker?

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#8429]
According to the [docs](https://superset.incubator.apache.org/visualization.html#need-to-add-a-new-country), a user can add a new CountryMap by putting the .geojson file in this directory: `superset/assets/src/visualizations/CountryMap/countries`. This directory however does not exist in this path. It's located only in node modules directory. 

Is it possible to add a new country when Superset is installed with Docker? Or is building from source the only way to achieve this?

**Comment by syazwan0913** [comment]
@klazaj  You need to refer here: https://github.com/apache-superset/superset-ui-plugins/tree/master/packages/superset-ui-legacy-plugin-chart-country-map

**Comment by klazaj** [comment]
@syazwan0913 which file do I add the `key` and `Superchart`?

https://github.com/apache-superset/superset-ui-plugins mentions that :

> @superset-ui/plugin-* packages are newer and has higher quality in general. A key difference that they do not depend on viz.py (which contain visualization-specific python code) and interface with /api/v1/query/ instead: a new generic endpoint instead meant to serve all visualizations. Also should be written in Typescript.

Also, I have made changes in `viz.py`, so I'm not sure this solution would work.

**Comment by visakhmurukes** [comment]
Same issue here
Dont know where I should place the .geojson file inside the docker for superset or add the key and config

**Comment by klazaj** [comment]
@visakhmurukes  what I did was put the [CountryMap](https://github.com/apache-superset/superset-ui-plugins/tree/master/packages/superset-ui-legacy-plugin-chart-country-map/src) in /visualizations directory and change the path of the plugin in MainPreset.js file, so that it points to the CountryMap in visualizations directory.

**Comment by visakhmurukes** [comment]
Where can I find MainPreset.js?
I searched inside Superset docker using find but couldn't find the
specified file.

**Comment by syazwan0913** [comment]
@visakhmurukes https://github.com/apache/incubator-superset/blob/master/superset/assets/src/visualizations/presets/MainPreset.js

**Comment by jackyq2015** [comment]
@visakhmurukes The file is under your local if you create the docker from source. it is mapped to docker volume

**Comment by visakhmurukes** [comment]
So we need to build it from source?
Is there not a direct way to add map to superset running from docker?

**Comment by klazaj** [comment]
@visakhmurukes you don't need to build it from source, and yes there is a direct way (at least when I installed superset). As I mention above, move https://github.com/apache-superset/superset-ui-plugins/tree/master/packages/superset-ui-legacy-plugin-chart-country-map/src to `/visualizations` and do this 
![countrymap](https://user-images.githubusercontent.com/22456202/73248448-49b87c00-41b3-11ea-85ef-fa2c67f571f9.png)

**Comment by visakhmurukes** [comment]
I dont have Mainpreset.js. Instead I see MapChartPreset.js
And it already has these lines

```
import CountryMapChartPlugin from '@superset-ui/legacy-plugin-chart-country-map';

export default class MapChartPreset extends Preset {
  constructor() {
    super({
      name: 'Maps',
      plugins: [
        new CountryMapChartPlugin().configure({ key: 'country_map' })
      ],
    });
  }



```

**Comment by klazaj** [comment]
substitute `import CountryMapChartPlugin from '@superset-ui/legacy-plugin-chart-country-map';` with `import CountryMapChartPlugin from '../CountryMap/CountryMapChartPlugin';`

**Comment by visakhmurukes** [comment]
I substituted the lines as specified and added new country geojson file to assets/src/visualizations/CountryMap/countries folder
I also added new country name to explore/controls.jsx
I restarted docker container as well
Still the map doesnt show new country in the list

**Comment by klazaj** [comment]
That is weird, the country name at least has to show on the list, since docker updates frontend with every change you make. Is your superset in development mode?

**Comment by visakhmurukes** [comment]
Yes
The webserver is in development mode

**Comment by klazaj** [comment]
@visakhmurukes no, the websever should stay in development mode in order for the frontend to be updated

**Comment by visakhmurukes** [comment]
Sorry @klazaj  still not much luck with this :(

**Comment by harshal-c** [comment]
@visakhmurukes Hi, were able to figure it out in the end?
