### ISSUE TITLE
how to pass the filter time to the custom query filter?

### ISSUE THREAD

**Issue by yyccR** [apache/incubator-superset#8431]
Hi, guys

I'm using superset query data from hive which contains time partitions.
I want to pass the filter time to the custom query filter, so i can specify the time partition from it.

below is the filter time:
![supserset_time](https://raw.githubusercontent.com/yyccR/Pictures/master/issue/supserset/superset_time.png)

And how to pass it to the custom filter like:
![supserset_time](https://raw.githubusercontent.com/yyccR/Pictures/master/issue/supserset/superset_filter.png)

Thanks a lot!

**Comment by alexberryman** [comment]
Have you tried setting "No filter" in the `time` section and then defining your custom query in `query`?

I ended up doing that for a custom postgres SQL query like:
```sql
created_at > now() - interval '2 weeks'
```

**Comment by yyccR** [comment]
Thanks @alexberryman
finally I changed my hive table time partition into superset's time column.
