### ISSUE TITLE
How to make pyodbc work in docker

### ISSUE THREAD

**Issue by toilv** [apache/incubator-superset#8435]
I followed the guide setup the docker successfully but when try to add a MSSQL source database the error show up:
` | 2019-10-23 15:46:51,751:ERROR:root:No module named 'pyodbc'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/home/superset/superset/views/core.py", line 1702, in testconn
superset_1  |     engine = database.get_sqla_engine(user_name=username)
superset_1  |   File "/home/superset/superset/utils/core.py", line 131, in __call__
superset_1  |     value = self.func(*args, **kwargs)
superset_1  |   File "/home/superset/superset/models/core.py", line 911, in get_sqla_engine
superset_1  |     return create_engine(url, **params)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
superset_1  |     return strategy.create(*args, **kwargs)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
superset_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/connectors/pyodbc.py", line 37, in dbapi
superset_1  |     return __import__("pyodbc")
superset_1  | ModuleNotFoundError: No module named 'pyodbc'
`

I have already install it:
`pip3 install pymssql`

**Comment by willbarrett** [comment]
Hi @toilv - you'll need to update the container build to include the `pymssql` package. I hope that helps!
