### ISSUE TITLE
heatmap axis cannot display date type column correctly

### ISSUE THREAD

**Issue by hecaodong** [apache/incubator-superset#8437]
when Heatmap axis was date type column, it can not be display correctly.
For example,  2017-09-01 was displayed as 1504224000000

![image](https://user-images.githubusercontent.com/56583108/67450806-6e5cf080-f5d3-11e9-8c20-3ae76a2d852e.png)
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version` 0.34 
- python version: `python --version`  3.6.9
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
yes
- [x] I have reproduced the issue with at least the latest released version of superset.
yes
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.
yes

**Comment by FredericoCoelhoNunes** [comment]
I have the same issue. Any fix coming soon?

**Comment by aussat** [comment]
Just use _to_char()_ function when wrintinhyour SQL query in order to convert your date value to text.
Example: to_char(your_date_column, 'YYYY-MM-DD')
