### ISSUE TITLE
time series bar do not show date with format yyyy-mm-dd? only day and week

### ISSUE THREAD

**Issue by Foristkirito** [apache/incubator-superset#8445]
![image](https://user-images.githubusercontent.com/13299109/67499109-17c6e380-f6b3-11e9-80f1-3fa0a54a088e.png)

**Comment by betodealmeida** [comment]
👀

**Comment by betodealmeida** [comment]
@Foristkirito, the label shows the x-value in the same format as the x-axis. You can change the x-axis formatting to be yyyy-mm-dd:

![Screen Shot 2019-12-02 at 4 05 08 PM](https://user-images.githubusercontent.com/1534870/70005183-86eaef80-151d-11ea-9fc6-7af0e8cbf017.png)
