### ISSUE TITLE
Upload CSV does not work, in replacement and append mode

### ISSUE THREAD

**Issue by pengyejun** [apache/incubator-superset#8451]
errmsg: Table name abc already exists. Please pick another

But I chose the append and replace mode.

**Comment by willbarrett** [comment]
Hi @pengyejun - what flavor of database are you attempting to load data into (postgres, bigquery, etc.)? Thanks for the additional information!

**Comment by axuew** [comment]
Mairadb has the same problem

**Comment by villebro** [comment]
I was able to reproduce. It's not that the csv file isn't being uploaded; rather Superset is complaining that the **Superset** table (=metadata) is already present. I'm thinking users expect `replace` and `append` to assume that the table metadata already exists, and to only try to create metadata if inserting in `fail` mode. Will put through a PR soon.

**Comment by pengyejun** [comment]
> Hi @pengyejun - what flavor of database are you attempting to load data into (postgres, bigquery, etc.)? Thanks for the additional information!
thank you for your reply! I am using sqlite3, Is this defect related to the database?

**Comment by pengyejun** [comment]
Hi @villebro -Thank you for your thoughts, but I found a problem. When replacing the upload csv, the subsequent upload file is different from the first upload file CSV header line. At this time, the table_columns table stores the structure error.

**Comment by villebro** [comment]
@pengyejun please check PR #8457 , is this in line with how you would expect CSV uploading to work?

**Comment by pengyejun** [comment]
@villebro thank you for your reply!  I saw your PR, But it didn't solve my problem. When I want to replace and modify the CSV header structure, I expect that the table_columns table stores the same structure as the CSV header.

**Comment by pengyejun** [comment]
@villebro I think you can check the tables when uploading the CSV. If there is a direct deletion, regenerate the metadata.

**Comment by villebro** [comment]
Currently refreshing the metadata doesn't remove pre-existing but non-present columns from table metadata. Having support for removing non-present columns is a good feature, but requires a separate PR and more discussion on how this should be facilitated so as not to break existing charts. E.g. adding an option "remove non-existent columns when refreshing metadata" in the table metadata could be make sense.

**Comment by pengyejun** [comment]
@villebro Thanks, your suggestion is very correct.
