### ISSUE TITLE
Scan druid datasources request is not defined error

### ISSUE THREAD

**Issue by jmarxuach** [apache/incubator-superset#8456]
Superset 0.34 installed with druid same machine. I have druid working with some datasourses. 
I create in superset a druid cluster, localhost 8082, then I go to superset scan druid datasources.

### Expected results

It should refresh druid datasources and list them in superset. but i get the following error : connection refused.

### Actual results

ConnectionRefusedError: [Errno 111] Connection refused
2019-10-26 11:49:39,659:ERROR:root:name 'requests' is not defined
Traceback (most recent call last):
  File "/var/www/html/venv/lib/python3.6/site-packages/superset/connectors/druid/views.py", line 426, in refresh_datasources
    cluster.refresh_datasources(refreshAll=refreshAll)
  File "/var/www/html/venv/lib/python3.6/site-packages/superset/connectors/druid/models.py", line 193, in refresh_datasources
    ds_list = self.get_datasources()
  File "/var/www/html/venv/lib/python3.6/site-packages/superset/connectors/druid/models.py", line 174, in get_datasources
    auth = requests.auth.HTTPBasicAuth(self.broker_user, self.broker_pass)

#### How to reproduce the bug

1. Go to 'superset'
2. Click on 'Scan new datasources'
3. See error Error while processing cluster 'cluster_druid' name 'requests' is not defined

### Environment

(please complete the following information):

- superset version: `superset version` 0.34
- python version: `python --version`  3.6
- node.js version: `node -v` not installed
- npm version: `npm -v` not installed
 
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I have Druid and superset installed as services. No dockers.
I checked to access Druid broker from command line using
curl http://localhost:8082/druid/v2/datasources 
It worked.

**Comment by jmarxuach** [comment]
Resolved installing pydruid.
pip install pydruid

but exception handling in connectors/druid/models.py should print proper message instead of just pass.

Pep.

**Comment by dpgaspar** [comment]
Hi @jakubczaplicki,

Glad you were able to solve it. A nice way to install the druid extra requirements:
```
pip install "apache-superset[druid]"
```
