### ISSUE TITLE
Unable to change the Datetime Format while editing the datasource  

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8466]
While editing the datasource we can see the option like Label,Description,Datetime Format,when i am giving any dateformat in Datetime Format option,its not reflecting in the table view.
but when i am changing the label name its getting reflected in the column name.

### Expected results
It should apply dateformat into the table what we have given in Datetime Format option.

### Actual results
i am getting the default format of date.
#### How to reproduce the bug

1. Create any chart in table view and save it

2. Click on  datasource link and go to columns tab.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

![image](https://user-images.githubusercontent.com/43033939/67736919-6536ae00-fa2f-11e9-9cc8-e68d505b3c95.png)

**Comment by umesh11111** [comment]
Any update?

**Comment by willbarrett** [comment]
Hi @umesh11111 - please complete all of the required information in the bug report template so that the maintainers can investigate the issue.

**Comment by jefo2k** [comment]
Hi @umesh11111 
Did you solve this issue?!?
If yes, could you please give me some directions?!?
Thank you!

**Comment by sodawy** [comment]
@umesh11111 @jefo2k 

Hope this code link would help you~
[validators_columns of python_date_format](https://github.com/apache/incubator-superset/blob/master/superset/connectors/sqla/views.py#L146)
Base on those format validator.
`%Y-%m-%dT%H:%M:%S.%f`
Words for me.
