### ISSUE TITLE
Bar Chart can not show the correct Bar value when i choose single item

### ISSUE THREAD

**Issue by dingsheng999888** [apache/incubator-superset#8467]
### Expected results

When drawing a Bar Chart, choose to display the value of the bar and select the stacked bar chart. When I select different items, the value of the bar should change dynamically according to the item I selected.

### Actual results

When I select different items, the total value of all items is always displayed.

#### Screenshots

![image](https://user-images.githubusercontent.com/29251725/67741170-35999d00-fa53-11e9-8a18-fe1324f56995.png)
![image](https://user-images.githubusercontent.com/29251725/67744248-f6237e80-fa5b-11e9-9cf4-d925e32c2a27.png)

### Environment

(please complete the following information):

- superset version: `superset version`
Superset 0.32.0
- python version: `python --version`
python 3.6
- node.js version: `node -v`
v11.7.0
- npm version: `npm -v`
6.5.0
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
👀

**Comment by betodealmeida** [comment]
@dingsheng999888, this was fixed earlier this year: https://github.com/apache-superset/superset-ui-plugins/pull/7

Can you try running a newer version?
