### ISSUE TITLE
Data labels overlap with legend once again

### ISSUE THREAD

**Issue by wtfzambo** [apache/incubator-superset#8480]
As described here #3779 and fixed last year by #6145, labels of tall bars overlap with the legend. However, the file modified by #6145 exists only until branch 0.27. Wasn't able to figure out which file to address to fix this in master, sorry.

### Expected results

Bar labels and legend not overlapping.

### Actual results

Bar labels overlapping with legend.

#### Screenshots

![67417267-a7439800-f5c8-11e9-853f-48a6df86ad30](https://user-images.githubusercontent.com/47462792/67862655-c8edd380-fb22-11e9-8f7f-20da3d23c8ed.jpg)

#### How to reproduce the bug

1. Create some fake numeric data, can be all of the same values, just make them large enough (like an array of "1000").
2. Create bar chart from this data, enable legend, enable bar values.
3. Either already in the editor or after exporting to dashboard you'll see labels overlapping the legend.

Screenshot attached for reference anyway.

### Environment

- superset version: 0.34.1
- python version: 3.7.3
- node.js version: 10.16.0
- npm version: 6.10.2

### Checklist

- [✓] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [✓] I have reproduced the issue with at least the latest released version of superset.
- [✓] I have checked the issue tracker for the same issue and I haven't found one similar.
^ Actually I have but it is 1 year old and the bug reappeared despite it being supposedly fixed in a previous version.

**Comment by betodealmeida** [comment]
👀

**Comment by betodealmeida** [comment]
Fixed in https://github.com/apache-superset/superset-ui-plugins/pull/283

**Comment by Neel-rishabhsoft** [comment]
Facing the overlapping values issue in Superset Barchart 
Chart Type: Time Series Bar Chart (when showing bar values)
Screenshot:  
![image](https://user-images.githubusercontent.com/60099288/108812653-854f9080-75d5-11eb-9699-7f3af56ae94e.png)

Superset version: 0.37.0

Please suggest any way to resolve this issue
