### ISSUE TITLE
Rich tooltip not working in barchart time series

### ISSUE THREAD

**Issue by wtfzambo** [apache/incubator-superset#8483]
As title describes, as described in #5431 

### Expected results

Rich tooltip working also for barcharts like it does in linecharts.

### Actual results

Rich tooltip not working for barcharts.

#### Screenshots

![Annotazione 2019-10-30 192842](https://user-images.githubusercontent.com/47462792/67887434-87255300-fb4b-11e9-95d8-5375095902ee.jpg)

#### How to reproduce the bug

1. Create a grouped timeseries bar chart
2. Enable rich tooltip

### Environment

(please complete the following information):

- superset version: 0.34.1
- python version:  3.7.3
- node.js version: 10.16.0
- npm version: 6.10.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.
^ I have and it's been closed but not resolved

**Comment by MarcusSorealheis** [comment]
It's working for me

**Comment by wtfzambo** [comment]
@MarcusSorealheis Uhm... then I guess it's a problem on my end. Odd because installation went smoothly.
Mind sharing which OS you're working on and what installation steps you followed?

**Comment by negbie** [comment]
Rich tooltips are broken for firefox since months. If you need them you have to switch to chrome.

**Comment by wtfzambo** [comment]
I was on chrome, on firefox they don't even appear Q_Q.

**Comment by negbie** [comment]
Oh thats new to me. Thanks, let's give this a thumb up.

**Comment by wtfzambo** [comment]
@negbie I mean, test it first if you're able to. It might be that it is a problem on my end due to the fact that I'm running superset on windows which is technically not supported. Next week I'm going to try on linux and see what goes.

**Comment by MarcusSorealheis** [comment]
@wtfzambo I'm on `10.14.6` Mojave
