### ISSUE TITLE
'ascii' codec can't decode byte 0xcc in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by chairly** [apache/incubator-superset#8488]
Traceback (most recent call last):
  File "D:\Program Files (x86)\superset\superset_python3.6\lib\site-packages\sup
erset\sql_lab.py", line 193, in execute_sql
    data = db_engine_spec.fetch_data(cursor, query.limit)
  File "D:\Program Files (x86)\superset\superset_python3.6\lib\site-packages\sup
erset\db_engine_specs.py", line 431, in fetch_data
    return cursor.fetchall()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 0: ordinal
not in range(128)

**Comment by chairly** [comment]
who can help me  plz?

**Comment by chairly** [comment]
posgresql 当返回数据中有中文时就报错

**Comment by villebro** [comment]
Please help the maintainers assess the problem by providing all information requested in the standard issue template.
