### ISSUE TITLE
Backticks being generated in querys when using MySQL backend

### ISSUE THREAD

**Issue by mrbungie** [apache/incubator-superset#849]
I'm currently using Caravel and querying a Teradata MPP database, but I'm having trouble because Caravel is putting backticks and they're not supported by Teradata SQL.

It's strange because it only happens if I use MySQL as Caravel's backend. Using sqlite shows no problems.

To reproduce:
1) Caravel 0.10
2) Use MySQL as Caravel's backend.
3) Add and query a database that doesn't support backticks.

**Comment by mistercrunch** [comment]
What does your SqlAlchemy connection string to Teradata look like? Which SqlAlchemy dialect/connector are you using?

**Comment by mrbungie** [comment]
My connection string is teradata://user:password@dbhost/ . The dialect I'm using is a modified version of Teradata's SqlAlchemy with more methods implemented (https://github.com/mrbungie?tab=repositories) and with some fixes regarding schemas.

I explored the dialect looking for something and found nothing. But like I said, it's weird because it only happens with MySQL as Caravel's backend.

More info:
Original dialect: https://github.com/Teradata/sqlalchemy-teradata
https://developer.teradata.com/tools/articles/teradata-sqlalchemy-introduction

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
