### ISSUE TITLE
load_examples TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by Gypsying** [apache/incubator-superset#8491]
Hi friends, i found timeout error while `superset load_examples:`

![image](https://user-images.githubusercontent.com/17995262/67999000-83054c80-fc95-11e9-9d89-9176d8142c4f.png)

My server env :
CentOS 7
Python3.8
Superset 0.30.0
Flask 1.1.1
Werkzeug 0.16.0

`superset db upgrade` and `flask fab create-admin` had succeed,
but `superset load_examples` always failed.

And, i used Python3.6 on CentOS 6 is the same problem...

Any help will be appreciated!!!

**Comment by Gypsying** [comment]
I am so sorry, that's my fault:
my server can not resolve the domain: `raw.githubusercontent.com` 

Sorry again ...

**Comment by myzcid** [comment]
> I am so sorry, that's my fault:
> my server can not resolve the domain: `raw.githubusercontent.com`
> 
> Sorry again ...

I use sqlite:
019-11-02 06:22:39,866:INFO:root:Database.get_sqla_engine(). Masked URL: sqlite:////home/work/incubator-superset/superset/.superset/superset.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by metaperl** [comment]
This is occurring for me under SQLite as well.. I would need to supply a proxy if a call to raw.githubusercontent.com is necessary and the proxy would have to be open for that domain.

**Comment by Gypsying** [comment]
> This is occurring for me under SQLite as well.. I would need to supply a proxy if a call to raw.githubusercontent.com is necessary and the proxy would have to be open for that domain.


Yeah, that is right;
Or you can find a reachable ip and bind it to the domain in your /etc/hosts

**Comment by betodealmeida** [comment]
@Gypsying @myzcid would it work if we allowed the examples to be loaded from a local path, instead of a URL? You would download the files somewhere else, and run:

```bash
superset load_examples examples-data-master.zip
```

**Comment by metaperl** [comment]
> @Gypsying @myzcid would it work if we allowed the examples to be loaded from a local path, instead of a URL? You would download the files somewhere else, and run:
> 
> ```shell
> superset load_examples examples-data-master.zip
> ```

Yes, that seems like a workable solution.
