### ISSUE TITLE
Grouping by more than one item is not grouping data by corresponding values

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#8497]
### Expected results

what you expected to happen.
I would expect the output to exclude data which does not correspond with the groups.

### Actual results

what actually happens.
I have data in a pivot table and I have grouped it by two variables say continent and country and the metric is population size.  The output does not exclude data which does not correspond to the first group ie the country row will have the names of all the countries regardless of the continent. If the country name does not correspond to the continent then the metric will be 'null'.

Superset version: 0.30.0
python version: 3.6.8

However, this is working well in Superset 0.28, python version 3.6

**Comment by greenietea** [comment]
I'm experiencing the same issue, and the group by function works in SQL Lab. I'm only seeing this issue in my pivot tables. 

@mashciku have you found a workaround solution yet?
