### ISSUE TITLE
Can't open in smartphone

### ISSUE THREAD

**Issue by marindahulfa** [apache/incubator-superset#8499]
I want to ask why when I try to open Apache Superset via Smatrphone failure, what causes it to happen? thanks.

**Comment by willbarrett** [comment]
Hi @marindahulfa - Superset is a very large application that requires a lot of client resources. It is optimized for use on laptop and desktop computers.

**Comment by marindahulfa** [comment]
But I also want to ask when I use another laptop to open Apache Superset by shooting to my laptop, I still can't, even though I already use the same WiFi and the IP that is written is also correct. how can it be like that ? thanks.

**Comment by willbarrett** [comment]
Please provide all of the information requested for bug reports to allow maintainers to help you resolve your issue.

**Comment by marindahulfa** [comment]
I want to ask how to set up a virtual machine (vm) in Apache Superset? thank you

**Comment by marindahulfa** [comment]
I want to ask how to set up a virtual machine (vm) in Apache Superset? thank you

**Comment by marindahulfa** [comment]
I tried to open my local Apache Superset through another computer using my laptop's IP but it still failed? how to handle it? thank you

**Comment by willbarrett** [comment]
@marindahulfa you'll want to make sure that Superset is binding to `0.0.0.0` rather than `localhost` or `127.0.0.1`. It's likely that your local development server isn't listening on external interfaces.

**Comment by marindahulfa** [comment]
Then what must I do to be able to? because I am still learning in this matter so I still don't understand at all. Please help. Thank you.

**Comment by willbarrett** [comment]
Hi @marindahulfa - you can follow this section of the installation instructions to get Superset running on `0.0.0.0` via `gunicorn`: https://superset.incubator.apache.org/installation.html#a-proper-wsgi-http-server
