### ISSUE TITLE
Still fetching fav-star data when no user is logged in

### ISSUE THREAD

**Issue by aspedrosa** [apache/incubator-superset#8501]
By giving the permissions:
- can dashboard on Superset
- can csrf token on Superset
- can explore json on Superset
- can list on CssTemplateAsyncModelView
- all datasource access on all_datasource_access

to the public role, any non logged in user can explore any dashboard. However, even with no user logged in, frontend app still tries to fetch the favorite status of the current dashboard.

### Expected results

Verify if a user is logged in and only if it is then fetch the favorite status of the current dashboard.

### Actual results

The favorite status of the current dashboard is always fetched

#### Screenshots

![fav-start-showing](https://user-images.githubusercontent.com/23409890/68135502-a93c1e00-ff1b-11e9-8214-4f80108d84a0.png)

#### How to reproduce the bug

1. Give the permissions mentioned on the beggining of the issue to the public role
2. Log out
3. Go to the url of any dashboard
4. See toast and fav-start still showing

### Environment

- using docker on commit [[SIP-15] Updating ISO 8601 regex match to make time optional (#8494) ](https://github.com/apache/incubator-superset/commit/fda2333cf21c2d71ad0ca276f78fd4b5b6fef314)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by aspedrosa** [comment]
Fixed with #8527

**Comment by EdwardVargatuk** [comment]
Hello. the bug started playing again after changes in April 2021

**Comment by n19besson** [comment]
Hey, same issue here.. it's happening again !

**Comment by aspedrosa** [comment]
Found the source of the new bug
The code shows this [line](https://github.com/apache/superset/blob/1.2.0rc2/superset-frontend/src/dashboard/components/Header/index.jsx#L405). The variable `dashboardInfo.userId` is a valid string so react renders the FaveStar component.

![bug_favstar](https://user-images.githubusercontent.com/23409890/122453156-f1e60500-cfa1-11eb-9a9e-6d152985fcd2.png)

Don't know who to tag, so I will tag the ones that reviewed the PR that fixed the previous version of this bug @etr2460 @nytai

**Comment by hatbout** [comment]
Any idea 

> Found the source of the new bug
> The code shows this [line](https://github.com/apache/superset/blob/1.2.0rc2/superset-frontend/src/dashboard/components/Header/index.jsx#L405). The variable `dashboardInfo.userId` is a valid string so react renders the FaveStar component.
> 
> ![bug_favstar](https://user-images.githubusercontent.com/23409890/122453156-f1e60500-cfa1-11eb-9a9e-6d152985fcd2.png)
> 
> Don't know who to tag, so I will tag the ones that reviewed the PR that fixed the previous version of this bug @etr2460 @nytai

Any idea when this can be fixed?  Kind of annoying when showing a dashboard to public.

**Comment by nytai** [comment]
This was fixed by https://github.com/apache/superset/pull/15590

**Comment by hatbout** [comment]
> This was fixed by #15590

Thanks a lot!  I just pulled the newest docker image and deployed again. I can confirm this bug is gone!
