### ISSUE TITLE
The time-thermal map shows the problem

### ISSUE THREAD

**Issue by mklzl** [apache/incubator-superset#8502]
When I create a time heat map
The beginning of each month should be the first of the month
But this is the last day of last month
for example:
![image](https://user-images.githubusercontent.com/36362816/68172634-354d5480-ffb3-11e9-9c2c-ce571479f6d9.png)

**Comment by betodealmeida** [comment]
@mklzl can you give more info on how to repro this? I tested with master and it works as expected.

**Comment by mklzl** [comment]
> @mklzl can you give more info on how to repro this? I tested with master and it works as expected.

      Thank you for your reply !  We used docker to deploy the superset，and the version of Python is  2.7.5.
       when i create a heat map in my dashboard, and use a field of type timestamp as the time field.
Then i choose the Last year as the Time range , and  choose the month as the region the day as subregion, and count the number of  fields as queries . After i run this query , I saw the problem I was asking.
    Does this have anything to do with superset`s version?

**Comment by betodealmeida** [comment]
@mklzl do you know which version of Superset you're running? We dropped support for Python 2, so I'm assuming it's an earlier version. This seems to be working now, and we just released 0.35.

**Comment by mklzl** [comment]
> @mklzl do you know which version of Superset you're running? We dropped support for Python 2, so I'm assuming it's an earlier version. This seems to be working now, and we just released 0.35.
The version of Superset we're running is Superset 0.999.0dev ,and the version of Python we're running is Python 3.6.9 ,not Python 2.7.5

**Comment by mklzl** [comment]
> @mklzl do you know which version of Superset you're running? We dropped support for Python 2, so I'm assuming it's an earlier version. This seems to be working now, and we just released 0.35.

you can have a  look at this issue [https://github.com/apache-superset/superset-ui-plugins/issues/52](url) . His problem was seem as mine, and someone offered a solution.
