### ISSUE TITLE
Unable to use 'explore' on sql lab

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#8528]
I have two databases connected to superset. I can query both in sql lab but for some reason I cannot explore the data of one of them. The data is not very different and the settings are the same for both

I expect to be able to explore data in both databases, but I am able to explore only one of them.
I can click on 'explore' but it is not opening a window where I can create a chart.

Someone please help, I am really stuck here

Python version: 3.6.8
superset version 0.28.1
os: centos
![Screenshot (45)](https://user-images.githubusercontent.com/29142200/68407727-20c8b200-0195-11ea-9ac6-bc886fce9a7e.png)

**Comment by villebro** [comment]
I recommend trying a more recent version, e.g. `0.34.1` which can be installed by running `pip install apache-superset==0.34.1`. `0.28.1` is not an official version, and in general it is recommended to always try to reproduce the error either on the most recent release or `master` branch. Also, please provide more context; e.g. specifying the database type would be helpful.

**Comment by imvemuri** [comment]
Are you seeing any error? It might have to do with table schema.

**Comment by mashciku** [comment]
@villebro I am using a mysql database on aws cloud.

@imvemuri one of the databases is giving me this error 'An error occurred while creating the data source'
The second one is not giving me any error.

**Comment by imvemuri** [comment]
I have something similar where when I click on explore it won't work. So, I altered the length of the column TYPE in 'table_columns' which fixed the issue.

**Comment by mistercrunch** [comment]
What database engine is this?

**Comment by villebro** [comment]
Ah yes, I believe this was fixed quite a few versions ago (the collation info overflowed the type column length). A similar fix was done for MSSQL. This should be fixed in the latest stable release.

**Comment by villebro** [comment]
I believe the collation bug (which I believe this is) was fixed some time around `0.33`. Please update to the latest version (`0.35.2`).

**Comment by zseta** [comment]
my issue was that my browser doesn't allow any pop-ups so Superset couldn't open a new tab... needed to allow pop-ups (i leave it here if someone comes from google like me...)
