### ISSUE TITLE
Bar values does not re-align when clicking the legend

### ISSUE THREAD

**Issue by KennethEnevoldsen** [apache/incubator-superset#8532]
Github issue:  
Check checking/unchecking the bar values is not re-aligned with the bars.

### Expected results
When trying to uncheck the legend in the time series bar chart, The bar values does not clean up. This appear for both grouped and stacked chart. I would expect them to realign according to the bars. There is no issue before unchecking the legend.

### Actual results
(these screenshots are taken from the previous post, but the same issue applies)
![37780770-750a42de-2e15-11e8-85de-c997d834fa21](https://user-images.githubusercontent.com/23721977/68015720-1be69880-fc93-11e9-94fa-af6000330908.png)

![37780844-984910cc-2e15-11e8-8b57-44111e4562c3](https://user-images.githubusercontent.com/23721977/68015749-2a34b480-fc93-11e9-9d81-477c35ba2f69.png)

As you can see in the above screenshot the current values aren't removed and replaced. 

#### How to reproduce the bug

1. create a chart with time series bar as visualisation type
2. choose a metric and choose a column under group by
3. check the legends and bar values check box
4. Now in the chart click on the legend to uncheck it .

### Environment

Superset version 0.28.1
Python 3.7.2
Node v10.16.3
npm 6.9.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar, **which still solves the issue**. (see this [issue] (https://github.com/apache/incubator-superset/issues/4667))

### Additional context
This is a repost of this [issue](https://github.com/apache/incubator-superset/issues/4667), although the solution of editing the NVD3VIs.js file no longer applies as the files (to my knowledge) no longer exist. Wasn't able to locate the replacement file either.

**Comment by betodealmeida** [comment]
Taking a look.

**Comment by betodealmeida** [comment]
@KennethEnevoldsen this has been fixed in later versions.
