### ISSUE TITLE
Upload File By SuperSet Fail !

### ISSUE THREAD

**Issue by somyote4** [apache/incubator-superset#8539]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `version": "0.23.3`
- python version:' 2.7.5 `
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I use superset "version": "0.23.3"   on HDP-3.1.0.0, 
Why can't i have  upload file by superset .   

![image](https://user-images.githubusercontent.com/17447176/68579489-cf773600-04a6-11ea-9b9d-81f8d4bd73bf.png)

I config  detail database show in image. 

![image](https://user-images.githubusercontent.com/17447176/68580006-0863da80-04a8-11ea-9f52-eaef154761d7.png)

**Comment by axuew** [comment]
The new version has been fixed，reference：https://github.com/apache/incubator-superset/pull/8457#issue-332768823

**Comment by dpgaspar** [comment]
Please update to a newer superset version.

I don't have much knowledge with Hive, but it seems like you need to set `CSV_TO_HIVE_UPLOAD_S3_BUCKET` config var with a previously created S3 bucket

Feel free to reopen if your still experiencing  issues related with this problem
