### ISSUE TITLE
Height in Deck.gl Grid wrong if aggregated

### ISSUE THREAD

**Issue by jaksmid** [apache/incubator-superset#8540]
I am using Deck.gl Grid to show prices per square meter. As a height parameter, I have `AVG(price_per_square_meter)`. However, I noticed that when there are multiple places at the same location, the aggregate is wrong and even exceeding `max(price_per_square_meter)` when queried in the database. If there is a single place at the location, the height is calculated as expected.

### Expected results

Heigh is calculated correctly as defined by the aggregate function.

### Actual results

It seems that the `sum` is used instead of used aggregate.

### How to reproduce
Go to the chart with example Grid. Change the height to the `AVG(occupancy)`. Even though the max occupancy in the database is 6, you can observe that the heigh column reaches to values like 36.

### Environment

(please complete the following information):

- superset version: `0.34.1`
- python version: `python 3.7.3`
- node.js version: `v10.15.2`
- npm version: `5.8.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
-  [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by gustavscholin** [comment]
Also experiencing this, any updates or work arounds?
