### ISSUE TITLE
Problem uploading CSV to PostgreSQL database

### ISSUE THREAD

**Issue by Sascha-Gschwind** [apache/incubator-superset#8542]
When you try to upload a CSV that has parentheses in the title column to a PostgreSQL database it fails with an error, showing the column title.

If you upload the same file to a SQLite database it succeeds.

### Expected results

The CSV can be successfully uploaded to a PostgreSQL database.

### Actual results

The CSV can not be successfully uploaded to a PostgreSQL database.

#### Screenshots

CSV-Content:
![image](https://user-images.githubusercontent.com/17166009/68658297-7a363580-0535-11ea-8434-ec1153acaaa1.png)

Error displayed when uploading to a PostgreSQL database:
![image](https://user-images.githubusercontent.com/17166009/68658321-84583400-0535-11ea-877e-91d490287483.png)

Database-Connection configuration:
![image](https://user-images.githubusercontent.com/17166009/68658342-8de19c00-0535-11ea-8874-2cf87394f223.png)

Link to CSV:
https://etherscan.io/chart/tx?output=csv

#### How to reproduce the bug

1. As an Admin go to "Sources" > "Databases" and Create a new database connection.
2. Enter the connection string to a PostgreSQL database and ensure "Allow CSV Upload" is ticked
3. Go to "Sources" > "Upload a CSV"
4. Upload the CSV from https://etherscan.io/chart/tx?output=csv

### Environment
- superset version: `0.999.0dev` (We are using the master-branch based on the commit `6d418308c734835b4b9257be32387d74f1a773a4`)
- python version: `3.6.9`
- node.js version: `v10.16.3`
- npm version: `6.9.0`
- PostgreSQL version: `PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1)`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @Sascha-Gschwind,

Have not tried to reproduce, but, could you please update to a more current commit, since 6d418 there was a fix regarding CSV upload #8457
