### ISSUE TITLE
[SIP-27] Proposal for Improvement on CSV Upload

### ISSUE THREAD

**Issue by Sascha-Gschwind** [apache/incubator-superset#8543]
### Motivation

For non-technical users the process to upload a CSV can be a bit complicated since it is very verbose. If there is no database connection that has "Allow CSV Upload" enabled the user probably does not know what to do exactly.

We want to improve the way CSV data is uploaded that is a bit less verbose and supports creating new SQLite databases. It will also allow upload via Drag&Drop. If no database connection with "Allow CSV Upload" exists it should automatically create and use a new SQLite database connection.

### Proposed Change

We will replace the current form with a React-based form that supports Drag&Drop. It shows the most important form entries and has an "Advanced Options" menu where you can still access all the other fields that aren't needed most of the time.

Once they click "Save" the following mechanism should be executed:
1. Send the form-data to a backend API endpoint.
2. The backend API endpoint checks if it should create a new database or load the CSV to the existing one.
3. If a new database has to be created it checks if a file with that name already exists and informs the user if that is the case. Otherwise it will create the database file and add a database connection.
4. Finally the CSV-Upload is completed (same way it is done now)

In case of creating a new database, if anything goes wrong during the process, we try deleting the database and clean up the created files.

### New or Changed Public Interfaces

* There will be a new form for the "CSV to Database configuration" in React exposed at "/superset/csvtodatabase"
* There will be a new API endpoint "/superset/csvtodatabase/add" that can also create an SQLite database and an SQLite database connection if needed. The endpoint will still be able to handle the CSV Upload as usual.

### New dependencies

* We **do not need** any new dependencies

### Migration Plan and Compatibility

It would be beneficial if a chapter describing the process of uploading a CSV file would be added to the existing documentation.
Since not every browser supports Drag&Drop a fallback will be implemented showing the usual file upload input.

### Rejected Alternatives

* We considered changing the current CSV upload mechanism but since the flask-forms are very limited and we wanted to implement a Drag&Drop chose to implement it in React.

**Comment by willbarrett** [comment]
Hi @Sascha-Gschwind - this is great. That form really needs an upgrade. Should there be functionality to spin up other, non-SQLite databases? I'm wary of introducing functionality that creates drift in database support between DB engines.

**Comment by mistercrunch** [comment]
+1 on Will's point. Surprised of all databases why SQLLite, where is it even stored?

We have some work to do on building a "single page React app" as a new place to move towards all the current Jinja/MVC forms + CRUD.

**Comment by Sascha-Gschwind** [comment]
Thanks @willbarrett and @mistercrunch for your feedback! Maybe we did not make that clear enough: We definetely plan to let the user configure the database creation (for ex. if the user wants a PostgreSQL, MySQL, SQLite etc.), it's just not implemented yet. On the same note it will most likely also be possible to configure it so this option is not available (for ex. if an administrator does not want users to be able to create databases).
We used SQLite so we can create a sort of minimum viable product to be able to gather more feedback and adjust our implementation accordingly.
We are ready to create a [WIP] Pull Request, which already works, so you can have a closer look. We would love to get some feedback on the UI too. For now the form is intentionally designed to look close the previous, flask-based form (table-like look) but we are very willing to modernize it even more.

**Comment by willbarrett** [comment]
@Sascha-Gschwind if you have a WIP implementation, we'd be happy to take a look at what you've come up with! Go ahead and open the PR and we'll continue the conversation there.

**Comment by Sascha-Gschwind** [comment]
@willbarrett We opened a WIP PR #8556 so you can have a look! Looking forward to further feedback so we can make improvements if needed!
