### ISSUE TITLE
Load CSV from backend storage (GCS)

### ISSUE THREAD

**Issue by YannBrrd** [apache/incubator-superset#8546]
### Motivation

Providing a way to load CSV from different storages (first in my mind is GCS).

### Proposed Change

On top of providing a way to load CSV from user interface, allow to load a file from a backend storage such as GCS or other backends from cloud providers

### New or Changed Public Interfaces

Adding a 'Load CSV from...' button

### New dependencies

I'd tend to use [libcloud](https://libcloud.apache.org/), from Apache.

### Migration Plan and Compatibility

None

### Rejected Alternatives

None, AFAIK.

**Comment by willbarrett** [comment]
Thank you for opening the SIP - I'd love to understand the usecase better here. What is the motivation for adding the ability to load CSVs from cloud locations? What user behavior are you trying to support. Thanks!

**Comment by mistercrunch** [comment]
If it fits in a few lines it probably does not require the formal SIP process.
https://github.com/apache/incubator-superset/issues/5602

I think we should completely rebuild the CSV uploader in React.

**Comment by YannBrrd** [comment]
Use case is basic, in a corporante environnement, team would share a CSV on a backend storage and then could be analyzed using SuperSet without getting the data out of cloud... Does it make sense ?

**Comment by willbarrett** [comment]
Yes, that makes sense @YannBrrd. Go for it. Be aware that this system is going to be rebuilt from scratch at some point in the near future, so please attempt to make your addition modular and loosely coupled. That will help us avoid redoing your work when we migrate the feature.

**Comment by YannBrrd** [comment]
I've been looking at how you connect to BigQuery. It is an application level access if I got it well. Might not it be better/an option to have OAuth2 ? Doing this, I'd inherit accesses for current user...

**Comment by willbarrett** [comment]
Adding an option for OAuth2 connections to BigQuery would be a great addition. It might be worth a SIP to investigate the approach before moving forward. I do know some organizations have been able to use a service account and impersonation to achieve the same access controls.

**Comment by YannBrrd** [comment]
Once done for BQ it will be basic for GCS. Have access rto the method others used?

**Comment by willbarrett** [comment]
@YannBrrd unfortunately that code is closed-source, so I cannot share it.

**Comment by YannBrrd** [comment]
Fair enough.

I'm drowning in Google Python APIs. 😃
