### ISSUE TITLE
Copy one of superset.db to the other

### ISSUE THREAD

**Issue by vliweihan** [apache/incubator-superset#8569]
I am going to create two environments for testing and deploying, and copy one of superset.db to the other, will it work fine and is there any problem?  thanks.

**Comment by dpgaspar** [comment]
Have not tested it, but I think it should work as long as you keep the same `SECRET_KEY` on both environments (not very recommended). Note that sqlite should not be used on a production environment

**Comment by willbarrett** [comment]
@vliweihan this is not in any way a secure setup. Your test database and your production database should not share a secret key. I would advise strongly against this course of action.

**Comment by vliweihan** [comment]
> @vliweihan this is not in any way a secure setup. Your test database and your production database should not share a secret key. I would advise strongly against this course of action.

@willbarrett @dpgaspar   I get it. thank you for your advice.

**Comment by dpgaspar** [comment]
Closing, feel free to reopen if you need any further assistance with this
