### ISSUE TITLE
Malformed JSON in the extras field: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by gamebusterz** [apache/incubator-superset#8607]
While adding a new database connection (tried for Postgres and Redshift both), clicking on '**Test Connection**' gives  `Malformed JSON in the extras field: SyntaxError: Unexpected end of JSON input` error.
The **Extra** field has 
```
{
    "metadata_params": {},
    "engine_params": {},
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
```
And the **Secure Extra** field is empty. I also tried removing the JSON in the **Extra** field altogether but I still get this error. 

The connection strings, I've tried are:
`redshift+psycopg2://user:pass@host/dbname` for Redshift and `postgresql://user:pass@host:5432/dbname` for Postgres 

### Expected results
The connection should be tested successfully.

### Actual results
Clicking on '**Test Connection**' gives  `Malformed JSON in the extras field: SyntaxError: Unexpected end of JSON input` error.

#### Screenshots
<img width="449" alt="Screenshot 2019-11-20 at 15 19 36" src="https://user-images.githubusercontent.com/6880188/69229269-236ed280-0bab-11ea-9f2a-3e531e1b1882.png">

#### How to reproduce the bug

1. Go to Sources > Databases
2. Click on 'Add a new record' (Plus button)
3. Keeping all the field as it is, just add the database name and database URI
4. Click on 'Test Connection' to see the error.

### Environment

(please complete the following information):

- superset version: `"0.999.0dev",`
- python version: `Python 3.6.7`
- node.js version: `v13.1.0`
- npm version: `6.12.1`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have copied the default JSON in the extras field and checked its validity, and it is a valid JSON.

**Comment by dpgaspar** [comment]
Hi @gamebusterz,

Thank you for taking the time to report this, I'm able to reproduce

Investigating cause and possible fix

**Comment by maxmelnick** [comment]
@dpgaspar - I added #8630 to fix this issue.

Also, sorry...realize I missed this issue at first glance and created a new issue #8628 . I'll close my issue and update my PR to reference fixing this issue.

**Comment by bharath0208** [comment]
Getting the same error when trying to add a new presto database connection.
 
<img width="1369" alt="Screen Shot 2019-11-25 at 4 34 32 PM" src="https://user-images.githubusercontent.com/44377322/69579926-7b3d7d00-0fa1-11ea-9de8-a2823a0f8b41.png">

**Comment by gamebusterz** [comment]
@bharath0208 are you using the latest version?

**Comment by bharath0208** [comment]
@gamebusterz I think it's fixed now I tried with the latest version and I don't see the error anymore
