### ISSUE TITLE
Slack invitation in docs is expired

### ISSUE THREAD

**Issue by CalRobert** [apache/incubator-superset#8613]
The link to join Slack at https://superset.incubator.apache.org/ is expired. This is under "Join our Slack" in "Superset Resources"
https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LTc2Y2QwYjE4NGYwNzQyZWUwYTExZTdiZDMzMWQwZjc2YmJmM2QyMDkwMGVjZTA4N2I2MzUxZTk2YmE5MWRhZWE

### Expected results

I'm invited to the Superset slack

### Actual results

The link is expired

#### How to reproduce the bug

1. Go to https://superset.incubator.apache.org/
2. Click on "Join Our Slack"
3. See Error

### Environment
N/A

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!
N/A

**Comment by mistercrunch** [comment]
🏷 documentation

**Comment by robdiciuccio** [comment]
The link in the README has been updated:
https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU
