### ISSUE TITLE
Docs recommend `pip install superset` even though superset is superceded by apache-superset

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8624]
The [docs](https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization) recommend `pip install superset` but [Superset has moved to apache-superset on PyPi](https://pypi.org/project/superset/).

**Describe the solution you'd like**
Update the docs to point to the more recent version of superset.

**Comment by dpgaspar** [comment]
Hi @metaperl,

Nice catch, are you wiling to submit a PR for this?

**Comment by metaperl** [comment]
Perhaps the score of the variance between the 2 PyPi distributions should be widened? I wanted to install both `superset` and `apache-superset` from PyPI but both distributions write to `/root/.superset/superset.db` with the default config file.

It would be nice if each wrote to a unique default db.

As far a PR, I dont have that level of sophistication or free time at the moment.

**Comment by zhouyao1994** [comment]
> Hi @metaperl,
> 
> Nice catch, are you wiling to submit a PR for this?

I find that the github document had been fix it ,but the [doc](https://superset.incubator.apache.org/installation.html) not update,why that happend?

**Comment by dpgaspar** [comment]
@zhouyao1994, I see that's included on 0.35.0 but the docs were not updated yet, we are waiting or 0.35.1 that will probably be out next week.

**Comment by zhouyao1994** [comment]
@dpgaspar ok,thanks~
