### ISSUE TITLE
Bug using redis cache through jinja template

### ISSUE THREAD

**Issue by axuew** [apache/incubator-superset#8631]
### Expected results
I configured the cache as follows, but configured the chart using the jinja template, and found that different users saw the same data when they logged in

 CACHE_CONFIG = {
	    'CACHE_TYPE': 'redis',
	    'CACHE_DEFAULT_TIMEOUT': 60 * 60 * 24, # 1 day default (in secs)
	    'CACHE_KEY_PREFIX': 'superset_results',
	    'CACHE_REDIS_URL': 'redis://localhost:6379/0',
	}

ex:
SELECT count(1) FROM user_choice WHERE 1 = 1 and username in ('{{current_username()}}')

Jinja template has changed the original SQL search conditions, the results should be different

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
Please check `cache_key_wrapper`: https://superset.apache.org/sqllab.html#superset.jinja_context.CacheKeyWrapper.cache_key_wrapper

**Comment by axuew** [comment]
> Please check `cache_key_wrapper`: https://superset.apache.org/sqllab.html#superset.jinja_context.CacheKeyWrapper.cache_key_wrapper

thanks
