### ISSUE TITLE
Document enabling debugging in companion modules

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8634]
### Expected results

I expected to be able to read the Superset docs to see how to enable `DEBUG` level in modules that Superset relies on (e.g. Flask-Appbuilder, Flask-OAuthlib).

### Actual results

Not sure how to instrument `superset_config.py` so that I can get detailed feedback on how the OAuth2 authorization is taking place in my custom SSO security model.

### Checklist

- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

As you can see, this is a popular question, but no one has answered:
* https://www.reddit.com/r/flask/comments/dzy3f0/how_to_configure_logging_for_an_imported_module/
* https://stackoverflow.com/questions/58999444/how-to-configure-logging-for-an-imported-module

**Comment by metaperl** [comment]
As a concrete example, I am not seeing the log messages from [this method](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L674) during my execution of Superset but I know that method is being called.

I do not know how to enable logging for this (or ideally all) of Flask Appbuilder from Superset.

**Comment by metaperl** [comment]
** UPDATE ** - it is easy enough to configure logging from statically loaded modules available when `superset_config.py` is invoked. Hence for `flask_appbuilder.security.views` one simply needs to get the logger and set the level.

However Flask-OAuthLib is not available when `superset_config.py` is loaded. So it's not clear how to configure it's logger.

**Comment by colin-byrne-1** [comment]
> ** UPDATE ** - it is easy enough to configure logging from statically loaded modules available when `superset_config.py` is invoked. Hence for `flask_appbuilder.security.views` one simply needs to get the logger and set the level.
> 
> However Flask-OAuthLib is not available when `superset_config.py` is loaded. So it's not clear how to configure it's logger.

Did you ever solve this? Stuck on this as well!
