### ISSUE TITLE
[CSS] Font color contrast

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#8635]
I noticed there are some css and styling consolidation recently. It results some gray text become much lighter. See Run Query and other buttons: 

#### Screenshots
<img width="1174" alt="Screen Shot 2019-11-22 at 12 52 20 PM" src="https://user-images.githubusercontent.com/27990562/69462564-2a721e00-0d2e-11ea-8b90-8332c1803b7f.png">

In the current font color standard, it's hard to tell the button is active or inactive state. And color contrast is not strong enough it makes me feel hard to read (but probably just me 😢

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Heya @graceguo-supercat :)

I'll make some touchups to address these issues. There were some cases where shades of gray were rounded to the nearest level a bit more harshly than others - I'll adjust the lighter bits of UI seen here. 

We may find some additional elements that need tweaks, so please feel free to add to this PR or ping me on Superset Slack, and I'll tackle them as they come up.

**Comment by rusackas** [comment]
@graceguo-supercat Just opened https://github.com/apache/incubator-superset/pull/8650 to address this.

**Comment by graceguo-supercat** [comment]
Verified it is fixed in the latest build!
