### ISSUE TITLE
How do I join two tables in Superset ? I need to combine the result in order to visualize the data

### ISSUE THREAD

**Issue by DishiBhinde** [apache/incubator-superset#8645]
How do I join two tables in Superset ? I need to combine the result in order to visualize the data

**Comment by suddjian** [comment]
You can use SQL Lab (+new button > SQL Query) to write any sql you want, and then hit the "Explore" button to make a chart from your query.

**Comment by mistercrunch** [comment]
You may also want to create a view a view in your database and use this view as a datasource. It's effectively the same as the solution above, except the view is stored in the database and can/could be reused outside of Superset

**Comment by barmic12** [comment]
I'm not sure that I understand SQL Lab View correctly. It doesn't create SQL view, right?

**Comment by DishiBhinde** [comment]
Yes It doesnt create sql view.!!

**Comment by mistercrunch** [comment]
The "Explore" button in SQL Lab is effectively creating a Superset-managed view. The "datasource" object that gets created stores that SQL in its definition, and runs queries against it the same way that it would against a table, but as a subquery.

**Comment by ManZzup** [comment]
Is this still open? like to work on this since it aligns with a current requirement we are having

**Comment by thunderbird57** [comment]
> Is this still open? like to work on this since it aligns with a current requirement we are having

I don't think we need to do something here. There are 2 options
#1 Join in SQL Lab - It will be stored in Superset internal database and the view will not be available outside Superset.
#2 Create a view in source database by joining those tables and use the view inside Superset 

Number 2 is preffered option mostly as it pushes data prep to Database itself and make it available for other BI platforms too.

**Comment by linganmm** [comment]
> 
Can the 2nd option be done with superset? Or does the user have to log on the backend database and create a view on it?

**Comment by asemprini** [comment]
So... if I have a fact table with dimensions, I have to create a super view with all the fields I will be using? It's the only way?

**Comment by m-ocean-it** [comment]
@linganmm:
> Can the 2nd option be done with superset? Or does the user have to log on the backend database and create a view on it?

You can do that right from Superset! You just need to make sure the "Allow CREATE VIEW AS" is enabled for that specific database.

**Comment by ttauzo** [comment]
it is still not a efficient solution because:
1. you should be able to join by click all fact and dimension tables bases on relationships (why to use sql for sth that can be clickable in a tool for business users)
2.  still if you join all tables you can apply filter either:
 - on technical ids that use db index but are not understandable for business user or 
 - on "business name" but then supserset will run a query with condition on a column without index (you would have to duplicate indexes and have indexes on both technical and business columns which is waste of resources)
Techncial and business "layer" should be separated

**Comment by mistercrunch** [comment]
This write up explains a bit more where Superset stands:
https://preset.io/blog/dataset-centric-visualization/

**Comment by rusackas** [comment]
I'll add that there are _many_ tools and techniques to do this lower in the stack, including semantic layers like Cube or DB-like tools such as Trino. It might also be worth mentioning here that Superset does have an _experimental_ in-memory "[meta database](https://superset.apache.org/docs/databases/meta-database/)" that one can use to join... but I wouldn't use it on large joins... it's more for lighter tasks like CSV-driven workflows.
