### ISSUE TITLE
Filters not being applied on annotation layers

### ISSUE THREAD

**Issue by HusnaHariz** [apache/incubator-superset#8647]
Filters fail to be applied on annotation layers added to a time series line chart. The filter will only be applied to the base line chart onto which the annotation layers were added. The annotation layer graphs remain the same.

### Expected results

Filters to be applied on annotation layers

### Actual results

Filters are only applied to the base chart. Annotation layer graphs remain unchanged.

#### Screenshots

The chart below shows the number of visits to a facility observed between December and March. There are three line graphs: The blue line graph which is the base graph, plots the total number of visits made in a month. The other two line graphs represent two added annotation layers, the High Risk layer(orange) and Low Risk layer(maroon). Each of these annotation layers show the total visits done for each of the risk cases per month. 

![Base Chart with Annotations Added](https://user-images.githubusercontent.com/45279477/69551120-39b2cf00-0fad-11ea-96fb-77b7eb521a36.png)

On applying a filter as highlighted by the red box, the values of the line graphs remain the same for both the annotation layers (High risk and low risk line graphs). Only values of the base chart(blue graph) are updated.

![image](https://user-images.githubusercontent.com/45279477/69551373-a037ed00-0fad-11ea-9df1-e4d0a65d0b9b.png)

### Environment

- superset version: `0.34.0`
- python version: `3.6`

### Steps to reproduce
1) Plot a time series
2) Add annotation layers (also time series)
3) Apply a filter

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kevinyuliawan** [comment]
Is this bug truly closed and will be unaddressed, or is/will there be some consideration for this feature in the future? 
My team is running into a similar use-case as @HusnaHariz where we desire the annotations to be affected by the same filters as the chart.
