### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

### ISSUE THREAD

**Issue by bharath0208** [apache/incubator-superset#8664]
Hi Folks,

I have a presto coordinator running on my k8's. I created a Keystore file with the cluster cert and key details.  I placed this Keystore inside my presto-coordinator now when .i am using any BI tools to connect to presto i was using this Keystore for validation. For Apache superset, i converted this Keystore file to PEM file and i did specify this in the extra params.
   {
        "metadata_params": {},
        "engine_params": {
           "connect_args":{
              "protocol": "https",
              "requests_kwargs": {
                       "verify": "/path/alpha.pem"
                }
           }
         },
        "metadata_cache_timeout": {},
        "schemas_allowed_for_csv_upload": []
    }
I am trying to connect to my presto coordinator from superset over https but i am getting this error.
Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3fe6367fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Que: Any suggestions or ideas on how this can be resolved?

**Comment by craig-rueda** [comment]
Can include a full stack? It looks like the verification part of the TLS handshake is a red herring here. `Connection refused` issues tend to be lower on the stack (TCP). Are you certain that you're able to connect from Superset into your presto cluster? (try something like `telnet <hostname.of.coordinator> 443` from inside one of your Superset containers)

**Comment by bharath0208** [comment]
Hey Craig,
I am able to connect it now but I get the below error. I have a keytore file in my presto-cordinator and using this file i created a PEM file out of it. I placed this PEM file inside superset containter 
ERROR:
```superset_1  | requests.exceptions.SSLError: HTTPSConnectionPool(host='*************', port=443): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
superset_1  | 172.18.0.1 - - [27/Nov/2019 19:46:12] "POST /superset/testconn HTTP/1.1" 500 -```

I am able to telnet from inside my superset container

```root@2ad8c9c40d13:/home/superset/superset# telnet presto-********** 443
Trying 169.6*.**.****...
Connected to **************.cloud.
Escape character is '^]'.
Connection closed by foreign host.```

**Comment by bharath0208** [comment]
> Issue Label Bot is not confident enough to auto-label this issue. See [dashboard](https://mlbot.net/data/apache/incubator-superset) for more details.

#quwation

**Comment by PRamia** [comment]
Hello there,

i am running superset with docker. All works fine. I want to add a SSL certificate to access via https, but i found any documentation about how to do it. Could somebody help me with this? i have my own certificate, so no need to use letsencript.

Thanks in advance!
