### ISSUE TITLE
Not all datasources render in the Change Datasource Modal Search

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8665]
Not all datasources render in the Change Datasource Modal Search

### Expected results

To see all the datasources in the table, and be able to search for every one

### Actual results

Not all datasources are visible

#### How to reproduce the bug

1. Have a large number of datasources
2. When searching in the explore view change datasource dropdown list, not all are searchable/listed

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michellethomas** [comment]
This is only an issue in our version likely because of something we are doing on setup, not an open source issue.
