### ISSUE TITLE
Support `start of` and `end of` in free text time range selector

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8667]
**Is your feature request related to a problem? Please describe.**
Right now, typing `start of this month` maps to the end of the month, and `end of last month` maps to the beginning of last month.  this is because we don't support the `start of` and `end of` syntax and this gets simplified to `this month` and `last month`.

**Describe the solution you'd like**
Support the `start of` and `end of` modifiers

**Comment by axuew** [comment]
Many people need current year-to-date, month-to-month, or year-to-year time
