### ISSUE TITLE
Superset returns an internal server error when there are duplicated calculated column names

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8668]
Superset returns an internal server error when there are duplicated calculated column names

### Expected results

No 5xx

### Actual results

5xx

#### Screenshots

![image](https://user-images.githubusercontent.com/7409244/69683280-22391c00-1069-11ea-9331-11bad441b29a.png)

#### How to reproduce the bug

While recently creating a new set of calculated columns I forgot to change the name from the default of <new column> for all the fields. While attempting to save this, I wound up getting an internal server error on the front end which mapped to a "Duplicate entry '<new column>-77284' for key 'uq_table_columns_column_name'" internally.

It would be nice if that exception was caught or a specific error message surfaced so that people knew what they did wrong.

### Environment

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
I'll take this one!
