### ISSUE TITLE
Tooltip box too small for some charts

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8669]
For the area charts in the dashboard I'm working on, the tooltip box size doesn't match the contents and the text overflows (image attached).

### Expected results

Tooltip to render properly

### Actual results

![Screen Shot 2019-11-26 at 4 26 45 PM](https://user-images.githubusercontent.com/7409244/69683464-cae77b80-1069-11ea-8450-04bd6f44d7f1.png)

#### How to reproduce the bug

Make an area chart with long series values

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by etr2460** [comment]
Likely an issue with the nvd3 plugin https://github.com/apache-superset/superset-ui-plugins/tree/master/packages/superset-ui-legacy-preset-chart-nvd3

**Comment by rusackas** [comment]
I can't see the top blacked-out text, but I'm curious if adding some CSS to that element, i.e. `word-break: break-word;` might be enough.

**Comment by etr2460** [comment]
That might be enough, or maybe making the box itself bigger

**Comment by rusackas** [comment]
The long game will be deprecating NVD3... but that's another story. :)

**Comment by rusackas** [comment]
I'll tackle this one... @etr2460 / @mistercrunch feel free to assign to me.

**Comment by rusackas** [comment]
PR created on `superset-ui-plugins`:
https://github.com/apache-superset/superset-ui-plugins/pull/276

**Comment by etr2460** [comment]
This is merged into master now, closing
