### ISSUE TITLE
Bar chart doesn't create a bar for a null value in the series

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#8672]
Bar chart doesn't create a bar for a null value in the series

### Expected results

A bar for null values in the series as well as all the set values

### Actual results

only places where the series is specified has a bar for it

#### Screenshots

Data table shows rows where the first column (the series column) is null
![Screen Shot 2019-11-26 at 5 11 29 PM](https://user-images.githubusercontent.com/7409244/69685151-43513b00-1070-11ea-8046-66a38c784756.png)

But only one bar shows up

#### How to reproduce the bug

1. Set a column for series where there are null values
2. Don't see a bar for null values

### Environment

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by betodealmeida** [comment]
Taking a look.

**Comment by suddjian** [comment]
This happens in a call to the pandas `dataframe.groupby().sum()`: https://github.com/apache/incubator-superset/blob/ac0e353a542bc6daaa9a5f6ef07459ed7c5b71a4/superset/viz.py#L1547

I'm not sure how to tell pandas to allow `None` as a valid grouping value
