### ISSUE TITLE
How to deploy superset in a production environment?

### ISSUE THREAD

**Issue by vliweihan** [apache/incubator-superset#8673]
There is a warning when i execute the following command, what can I do if deployed in a production environment, Any suggestions? thanks.

(superset) [root@localhost ~]# superset run -p 8088 --with-threads --reload --debugger --host=0.0.0.0
2019-11-27 09:21:09,162:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by liuhao-121** [comment]
I have the same question

**Comment by vliweihan** [comment]
@liuhao-121  There is a solution using gunicorn , refer to the Superset documentation(https://superset.incubator.apache.org/installation.html)

(superset_test) [root@localhost superset]# gunicorn \
      -w 10 \
      -k gevent \
      --timeout 120 \
      -b  0.0.0.0:6666 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      --statsd-host localhost:8125 \
      superset:app

**Comment by liuhao-121** [comment]
@vliweihan How to deploy the web in a production environment？

**Comment by rvazquezglez** [comment]
I've found is the @abhioncbr [on DZone](https://dzone.com/articles/apache-superset-in-the-production-environment), but I think there is still a gap in the documentation for running on production environments.
