### ISSUE TITLE
Set dynamically default value of data filter

### ISSUE THREAD

**Issue by jeremy-bi** [apache/incubator-superset#8675]
Hi,

I use Apache superset 0.34.
I trying to set a default value to a data filter.
I know i can set a value and save my dashboard to set a default valu, but i want my default value be set dynamically.
If i'm in february i want my dashboard filtered by january data.
If i'm in ma March i want my dashboard filtered by february data.
...

It's possible in apache superset 0.34 ?
If it's possible how can i do ?

Thanks :)

**Comment by suddjian** [comment]
You can enter raw SQL as the value for your filter, so I think this should be doable using the `now()` function with some manipulation.

**Comment by liuyong888** [comment]
I have similar needs.
