### ISSUE TITLE
 How to access through IP + port

### ISSUE THREAD

**Issue by liuhao-121** [apache/incubator-superset#8682]
Why can't I access web on another computer (or local computer) through IP + port after the development environment starts the program? Can only be accessed through localhost + port?

### Expected results

access the web through IP + port

### Actual results

only localhost + port access

**Comment by vliweihan** [comment]
@liuhao-121 Check if you have the option of --host-0.0.0.0 when you start the service

**Comment by liuhao-121** [comment]
@vliweihan  yes, I start web like this  npm run dev-server --host-0.0.0.0, server: FLASK_ENV=development superset run -p 8088 --with-threads --reload --debugger

**Comment by liuhao-121** [comment]
flask server can reach through after add --host 0.0.0.0 when I start the service , but the web still can not reach @vliweihan

**Comment by liuhao-121** [comment]
I fix it now ,thanks @vliweihan

**Comment by schaurasia-quot** [comment]
superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
this option is working
