### ISSUE TITLE
Add checkbox beside each row of "table"

### ISSUE THREAD

**Issue by jackyq2015** [apache/incubator-superset#8683]
**Is your feature request related to a problem? Please describe.**
Add checkbox beside each row of "table" visualization type to allow user to select from the list and reflect the rows to another chart(such as line diagram). ie, If user select 3 rows out of 10 records, only the selected rows will be on the line chart.

**Additional context**
Current "table" is not so powerful. As a cornerstone to data presentation, the most important missing feature IMHO is to have a way to interact with user in order to provide a self-service platform.

**Comment by axuew** [comment]
You want to implement these features, which means you need to drill down and so on

**Comment by jackyq2015** [comment]
Should this be extended from the legacy package or plugin-* packages? I saw the recent discussion still around the legacy one. Is it because the plugin-* packages is not mature/stable enough to extend?
```
@superset-ui/plugin-* packages are newer and has higher quality in general. A key difference that they do not depend on viz.py (which contain visualization-specific python code) and interface with /api/v1/query/ instead: a new generic endpoint instead meant to serve all visualizations. Also should be written in Typescript.
```
Also what's the start point/approach to implement these? Any hint or document is helpful. Thanks

**Comment by suddjian** [comment]
I suggest looking at the "emit filter events" option in the "Customize" menu for the table viz. It might already have what you're looking for or just require a bit of tweaking.

**Comment by jackyq2015** [comment]
@suddjian Thanks for the info. I found this issues on ui-plugin repo might be useful. will take a look:
https://github.com/apache-superset/superset-ui-plugins/issues/125
