### ISSUE TITLE
How is viz.py works 

### ISSUE THREAD

**Issue by liuhao-121** [apache/incubator-superset#8685]
I know when i need a new chart , i need modify viz.py to add a new class which will support the view and get data , response;
but i can only find where it defined, find no where and how it works

**Comment by liuhao-121** [comment]
@vliweihan

**Comment by jackyq2015** [comment]
I also want to do the similar thing. All the UI code is under:
https://github.com/apache-superset/superset-ui-plugins

Also in the readme page you can see their recommendation:
```
@superset-ui/legacy-* packages are extracted from the classic Apache Superset and converted into 
plugins. These packages are extracted with minimal changes (almost as-is). They also depend on 
legacy API (viz.py) to function.


@superset-ui/plugin-* packages are newer and has higher quality in general. A key difference that 
they do not depend on viz.py (which contain visualization-specific python code) and interface with 
/api/v1/query/ instead: a new generic endpoint instead meant to serve all visualizations. Also should 
be written in Typescript.
```

**Comment by vliweihan** [comment]
@liuhao-121 I found some introductions online about how to add a new visualization , It only works for older versions. The file architecture of present version of superset seems very different. If you use the previous version of 0.28 and include 0.28, you can try it.

https://github.com/apache/incubator-superset/pull/3013
