### ISSUE TITLE
Error while changing data source in chart

### ISSUE THREAD

**Issue by hemantaggarwal** [apache/incubator-superset#8686]
I am getting an error while changing data source in chart after selecting new data source

### Expected results

Data source should get changed to chosen source.

### Actual results

Message "An error occurred" 

 ### Screenshots

![image](https://user-images.githubusercontent.com/31547162/69807957-93fd9b00-120c-11ea-89f9-f6271740e424.png)

![image](https://user-images.githubusercontent.com/31547162/69808109-daeb9080-120c-11ea-9dca-939db4e408ca.png)

### Environment

- superset version: 0.30.0
- python version: 3.6.9
`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Thank you for reporting, yet I'm not able to replicate the issue, please upgrade superset to a newer version and re-test

**Comment by hemantaggarwal** [comment]
@dpgaspar: I will re-test it after upgrading it. But after upgrading If I am right I have to run "superset db upgrade" then will I loose all my current dashboards?
Currently I am using postgres as superset metadata storage (by setting postgres uri in config.py).

**Comment by hemantaggarwal** [comment]
I tried upgrading using command "pip3 install apache-superset==0.35.1" but after successful installation, I got an error while running superset:

**Traceback (most recent call last):
  File "/usr/local/bin/superset", line 21, in <module>
    from superset.cli import create_app
  File "/usr/local/lib/python3.6/dist-packages/superset/__init__.py", line 133, in <module>
    app.config["LOGGING_CONFIGURATOR"].configure_logging(app.config, app.debug)
KeyError: 'LOGGING_CONFIGURATOR'** 

Then I tried to install version 0.34 using command "pip3 install apache-superset==0.34.0 and did "db upgrade" but it is still showing version as 0.30.0

**Comment by hemantaggarwal** [comment]
Finally I was able to upgrade it to 0.35.1 and ran "db upgrade" and "init" command. 'Logging_configurator' error was due to pip3, only pip should be use to install.
But I am still facing the issue of changing data source in chart and this issue is coming only on production server not in staging. Only difference between two setup is that on production we are using nginx reverse proxy and gunicorn for superset.

**Comment by hemantaggarwal** [comment]
@dpgaspar : Any suggestions for this?

**Comment by TheRum** [comment]
I am also facing the same issue. And also I cannot see any logs in the superset.
Superset version - 0.35.2

**Comment by sedhha** [comment]
> Update:
> Finally I was able to upgrade it to 0.35.1 and ran "db upgrade" and "init" command. 'Logging_configurator' error was due to pip3, only pip should be use to install.
> But I am still facing the issue of changing data source in chart and this issue is coming only on production server not in staging. Only difference between two setup is that on production we are using "nginx" reverse proxy and "gunicorn" for superset and using "postgres" to store superset metadata instead of default sqllite.
> Is it due to postgres database?

Did you find any solution to it? I am still facing the issue in superset 0.36.0

**Comment by hemantaggarwal** [comment]
@sedhha : No, I am still facing this issue and haven't find any solution to this.

**Comment by dharamgajera** [comment]
It is working for me but not all times.
I tried with mysql and postgres as metadata store for superset and it is working. 
This functionality is not working in our production superset server but works in our staging server. 

Environment :
Server - AWS EC2 - t3.small
Docker - amancevice/superset:0.36.0

**Comment by TheRum** [comment]
It is working for me but not all times.
I tried with mysql and postgres as metadata store for superset and it is working.
This functionality is not working in our production superset server but works in our staging server.

Environment :
Server - AWS EC2 - t3.small
Docker - amancevice/superset:0.36.0

**Comment by hemantaggarwal** [comment]
@TheRum : Were you able to find the cause?

**Comment by TheRum** [comment]
@hemantaggarwal Nope. I tried reproducing but no luck. Also cannot see anything in logs as well.

**Comment by Jclevinson** [comment]
Also experiencing this consistently - would love a fix!

**Comment by villebro** [comment]
@Jclevinson on what version of Superset are you on? Have you tried this on master branch?

**Comment by sedhha** [comment]
@villebro I am experiencing this on superset version 0.36.0.
Machine: GCP Ubuntu 18.04 LTS

**Comment by villebro** [comment]
Thanks @sedhha . This seems to be fixed on master branch, so all the more reason to release `0.37.0` as quickly as possible. I will try to push through the last blockers today so we can get the release vote started.

**Comment by sedhha** [comment]
> Thanks @sedhha . This seems to be fixed on master branch, so all the more reason to release `0.37.0` as quickly as possible. I will try to push through the last blockers today so we can get the release vote started.

Hi @villebro alright awesome! When's it going to release? Are you on that slack channel as well?

**Comment by villebro** [comment]
The minimum time that the vote will take is 6 days (3 days community vote, 3 days Incubator PMC vote), assuming no problems come up during testing/voting. I'm on that Slack channel, too (#apache-releases), I will post an update there as things progress.

**Comment by sedhha** [comment]
> The minimum time that the vote will take is 6 days (3 days community vote, 3 days Incubator PMC vote), assuming no problems come up during testing/voting. I'm on that Slack channel, too (#apache-releases), I will post an update there as things progress.

Awesome! Thanks... had some feature request, just wanted to know if they're incorporated or not. Posted them in slack channel itself!

**Comment by czue** [comment]
I'm also experiencing this on `0.36.0`. My issue appears related to this one https://github.com/apache/incubator-superset/issues/8686 in that I'm getting a JavaScript console error:

```
Unsafe attempt to load URL http://example.com/datasource/get/table/27/ from frame with URL https://example.com/superset/explore/?form_data=....#. Domains, protocols and ports must match.
```

However I have applied every workaround, including setting `ENABLE_PROXY_FIX` and `PROXY_FIX_CONFIG` in `superset_config.py` as well as validating the `X-Forwarded-Proto` and other headers are set and it doesn't seem to resolve the issue.

**Comment by sedhha** [comment]
> I'm also experiencing this on `0.36.0`. My issue appears related to this one #8686 in that I'm getting a JavaScript console error:
> 
> ```
> Unsafe attempt to load URL http://example.com/datasource/get/table/27/ from frame with URL https://example.com/superset/explore/?form_data=....#. Domains, protocols and ports must match.
> ```
> 
> However I have applied every workaround, including setting `ENABLE_PROXY_FIX` and `PROXY_FIX_CONFIG` in `superset_config.py` as well as validating the `X-Forwarded-Proto` and other headers are set and it doesn't seem to resolve the issue.

I get the same thing in my console.

**Comment by Jclevinson** [comment]
> Thanks @sedhha . This seems to be fixed on master branch, so all the more reason to release `0.37.0` as quickly as possible. I will try to push through the last blockers today so we can get the release vote started.

Has this fix been released yet?

**Comment by villebro** [comment]
@Jclevinson many issues were fixed yesterday, but one last blocker remains: #10307 We're working hard to get it fixed and get a new RC out today (UTC).

**Comment by Jclevinson** [comment]
> @Jclevinson many issues were fixed yesterday, but one last blocker remains: #10307 We're working hard to get it fixed and get a new RC out today (UTC).

thanks @villebro !

**Comment by hemantaggarwal** [comment]
Finally for me this issue is resolved by setting parameter "ENABLE_PROXY_FIX = True" in config file.

**Comment by ibotheperfect** [comment]
We have same issue with 0.37 and using nginx proxy. Setting ENABLE_PROXY_FIX = True didn't help.

**Comment by ibotheperfect** [comment]
I resolved issue by adding this to superset config 

`ENABLE_PROXY_FIX = True`

and configuring nginx like this 

```
   location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header X-Forwarded-SSL on;
      proxy_set_header X-Forwarded-Proto https;

      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;

      proxy_pass http://127.0.0.1:8088/;
      proxy_redirect off;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
```

These lines do the trick 
      proxy_set_header X-Forwarded-SSL on;
      proxy_set_header X-Forwarded-Proto https;

**Comment by scampion** [comment]
Same issue here but behind an F5 proxy and we can't manage it. 
I tried the latest nginx conf, in our case X-Real-IP is not available, Superset in unusable in that case.

**Comment by reignmaker** [comment]
The only thing that helped me is setting `X-Forwarded-Proto https;` explicitly (not the `$scheme` var), just as stated in the docs:

> In case the reverse proxy is used for providing SSL encryption, an explicit definition of the X-Forwarded-Proto may be required.

https://superset.apache.org/docs/installation/configuring-superset#configuration-behind-a-load-balancer
