### ISSUE TITLE
Connection failed when trying to add a new database 

### ISSUE THREAD

**Issue by harshaSenaratne** [apache/incubator-superset#8691]
Hi, I'm new to superset, I am getting an connection failed error when I'm trying to add my greenplum database to the superset. It would be a great help if anyone could suggest a solution for this.

**Note:- I'm using a ssh tunnel to access the server where database resides, since I do not have direct access to it.**

**Comment by hemantaggarwal** [comment]
Can you provide more details? If you are trying adding database from the "sources" menu the you have to give sqlalchemy uri for the database connection. May be there is issue with the connection string. It will be better if you give more details or screenshots.
