### ISSUE TITLE
PyPI page - broken link and gitter

### ISSUE THREAD

**Issue by francishemingway** [apache/incubator-superset#8696]
There's a few minor issues with the PyPI readme:
1) A problem with the image for Visualize geospatial data with deck.gl
![Capture](https://user-images.githubusercontent.com/45243854/69891701-7ee84100-12cc-11ea-8c7a-39f871da758b.PNG)

2) Still pointing people to the Gitter in the Resources section.

@dpgaspar

**Comment by dpgaspar** [comment]
Thank you for reporting this, the gitter chat is fixed on master #8330. But the image problem with deck.gl seems a bit strange to me. The URL's on 0.35.1 are correct, needs further investigation
