### ISSUE TITLE
How do i remove the link "Explorer in Superset" in email report

### ISSUE THREAD

**Issue by toilv** [apache/incubator-superset#8698]
I would like to disable the link for access to superset server
I have already tried "WEBDRIVER_BASEURL = None" but it seem invalid

**Comment by zheya08** [comment]
edit superset/tasks/schedules.py  _generate_mail_content , edit 
```
        body = __(
            '<b><a href="%(url)s">Explore in Superset</a></b><p></p>',
            name=name,
            url=url,
        )
```
remove 
```
<b><a href="%(url)s">Explore in Superset</a></b><p></p>
```
maybe works

**Comment by rishirajani-flexmoney** [comment]
> edit
> 
> ```
>         body = __(
>             '<b><a href="%(url)s">Explore in Superset</a></b><p></p>',
>             name=name,
>             url=url,
>         )
> ```
> 
> in superset/tasks/schedules.py _generate_mail_content remove
> 
> ```
> <b><a href="%(url)s">Explore in Superset</a></b><p></p>
> ```
> 
> may works

Hi @shawnz0 
Tried this solution but it doesn't seem to work for Superset 2.0
Wanted to know if this change now has to be made in superset/reports/notifications/email.py
