### ISSUE TITLE
I need help please , does  the jquery  affect the result of add database option，my version is the latest 0.35.1

### ISSUE THREAD

**Issue by xiaobaig0407** [apache/incubator-superset#8700]
my superset version  is the latest 0.35.1,kylin is 2.4,python is 3.7

where I choose add database , and the test connection button is responding correctly. but at the bottom I can not see the tables,   I see chrome  consoles error.   It's like that `jquery-latest.js:4 Uncaught TypeError: Cannot use 'in' operator to search for '1' in OK
    at M (jquery-latest.js:4)
    at Function.each (jquery-latest.js:4)
    at Object.<anonymous> (add:1080)
    at c (jquery-latest.js:4)
    at Object.fireWith [as resolveWith] (jquery-latest.js:4)
    at k (jquery-latest.js:6)
    at XMLHttpRequest.r (jquery-latest.js:6)`
 
Is that why the column of the table is missing .
Thank you very much 

![abccccc](https://user-images.githubusercontent.com/3224536/69897030-23c45600-1381-11ea-92a7-e766da81a2ba.jpg)

![ewwewewe](https://user-images.githubusercontent.com/3224536/69897074-7140c300-1381-11ea-8cdc-b4caad55ea2f.png)

**Comment by metaperl** [comment]
Your report is supposed to list the versions of various components of the Superset distribution.

**Comment by xiaobaig0407** [comment]
thank you. I have added it.

**Comment by xiaobaig0407** [comment]
> Your report is supposed to list the versions of various components of the Superset distribution.

I have added it.Please look at it agin .Thank you very much
