### ISSUE TITLE
Improve and fix portuguese translation

### ISSUE THREAD

**Issue by rodrigoguariento** [apache/incubator-superset#8701]
The current brazilian-portuguese translation is deprecated.

### Expected results

To have all translation updated and with cohesion.

### Actual results

There is a lot of sentences untranslated and wrong, with no cohesion.

#### How to reproduce the bug

1. Set brazilian-porruguese language
2. Navigate and being a Brazilian try understand (you'll probably won't get)

### Environment

- latest superset version (~ Nov 30, 2019)

**Comment by betodealmeida** [comment]
Reviewing the PR, thanks for contributing!
