### ISSUE TITLE
CSS loads lat and app flickers (pre-post CSS load)

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#8711]
When loading just about any page, the app without any CSS theme flashes before the CSS gets loaded and things look ok after an instant (hundreds of ms?)

### Expected results

No flickering

### Actual results

Flickers

#### Screenshots

happens too quickly to capture

#### How to reproduce the bug

1. any page
2. force refresh

**Comment by mistercrunch** [comment]
Issue appeared here https://github.com/apache/incubator-superset/pull/8637

**Comment by rusackas** [comment]
@mistercrunch someone created this to address exactly this issue, replacing `style-loader`:
https://github.com/NeekSandhu/css-visor

... but it seems relatively obscure, so I'm not sure it's a wise choice
