### ISSUE TITLE
How to use custom SQL in metric field in chart?

### ISSUE THREAD

**Issue by hemantaggarwal** [apache/incubator-superset#8727]
Can someone kindly tell how to use custom sql feature in metric field in charts? Is is similar to writing sql queries in SQL editor in superset? Can this feature work with postgresql?

**Comment by betodealmeida** [comment]
The custom SQL allows you to define a metric using any valid expression for the DB you're targeting. For example, if you're using Postgres with the GIS extension you could define a metric that is the area of a given geometry by using the following expression in the custom SQL tab:

```sql
ST_Area(geom)
```

When clicking "Run Query" Superset will compose a query that would look like:

```sql
SELECT ST_Area(geom) AS `ST_Area(geom)`
...
```

You can inspect the query generated by going into the hamburger menu in the top right and clicking "View query":

<img width="1298" alt="Screen Shot 2019-12-03 at 2 21 35 PM" src="https://user-images.githubusercontent.com/1534870/70094871-40a69680-15d8-11ea-8dc8-2733929ba49c.png">

**Comment by hemantaggarwal** [comment]
Thanks for the detailed explanation.

**Comment by Yaswanth-Perumalla** [comment]
How to display columns with alias names in raw records and also how to write a custom SQL query. If I write like a normal SQL query. I

**Comment by Jayen16** [comment]
> How to display columns with alias names in raw records and also how to write a custom SQL query. If I write like a normal SQL query(select customer_id as `cid`), it is showing like Expected text or file-like object, got <class 'dict'>. If I try to edit the label, its getting saved with original name. <img alt="Screenshot 2022-11-18 at 3 44 39 PM" width="1674" src="https://user-images.githubusercontent.com/109591061/202678363-a415e610-ee0e-4e03-a73c-e46758659bc5.png">

try use case statement.. if you want to have the sub queries in custom sql, create a dataset in sql lab
