### ISSUE TITLE
the script get stuck in Step 9/24 : RUN cd /app/superset/assets         && npm ci         && npm run build         && rm -rf node_modules  ---> Running in ccea2e24031d

### ISSUE THREAD

**Issue by Aabhusan** [apache/incubator-superset#8762]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Aabhusan** [comment]
i have used these steps: as mentioned in the official docx
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
# you can run this command everytime you need to start superset now:
docker-compose up
i am trying to install apache-superset in ec2-instance with ubuntu 18.04 using docker 4
i am stuck in 9th step
Starting type checking service...
Using 1 worker with 2048MB memory limit
 68% building 1515/1550 modules 35 active ...node_modules/d3-selection/src/create.js

**Comment by craig-rueda** [comment]
@Aabhusan - I've just opened #8775 to try and improve docker-compose a bit. Have tested locally, and seems to work great. Would love to see if this helps your issue.

**Comment by nytai** [comment]
@Aabhusan this is likely caused by the limited resources of the box you're trying to build on. For help debugging, the slack community is probably a better place. You can join by following this link: https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU
