### ISSUE TITLE
How can I compile and run the project from source code

### ISSUE THREAD

**Issue by viking714** [apache/incubator-superset#8779]
I want to develop on the source code of superSet, but I browse the doc, can't find how to set a develop environment. If I don't install superset through pip, I can't run "fabmanager create-admin –app superset", but if I run the code, I can't use the source code. Thank you very much.

**Comment by nytai** [comment]
@viking714 is this what you're looking for? https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#flask-server

**Comment by nytai** [comment]
@viking714 if you need help debugging the slack community is a good resource: https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU
