### ISSUE TITLE
Superset installation build fails using Docker on MS-Windows - fatal errors result in non-working system

### ISSUE THREAD

**Issue by richdevboston** [apache/incubator-superset#8790]
### Expected results

Clone and load the SuperSet demonstration Docker container by Run the following commands on the Superset Home page:

```git clone https://github.com/apache/incubator-superset/
cd incubator-superset
# you can run this command everytime you need to start superset now:
docker-compose up```

"After several minutes for superset initialization to finish, you can open a browser and view http://localhost:8088 to start your journey."


### Actual results

The build gets to Step 11/32 and throws an error due to an incompatible version of a JavaScript package.  Updating caniuse-lite is a red herring and does not help.  Running `npm update` does not help either.  Allocating more RAM as suggested by others does not help either.  

```
Step 11/32 : RUN cd /app/superset/assets         && npm run build         && rm -rf node_modules
 ---> Running in 4d072668b171

> superset@0.999.0-dev build /app/superset/assets
> cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress

clean-webpack-plugin: /app/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-06T01_40_49_400Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset/assets         && npm run build         && rm -rf node_modules' returned a non-zero code: 1
```
#### How to reproduce the bug

1. Go to 'https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization'
2. Execute Docker container gitclone instruction: git clone https://github.com/apache/incubator-superset/
3. change directory to superset ```cd incubator-superset```

# you can run this command everytime you need to start superset now:
```docker-compose up```

4. wait about 15-20 minutes for Docker container to build executable file from Python, Javascript, Postgres and other components. 
4. See error in terminal

### Environment

Docker Desktop Community Edition v2.1.0.5 (40693) on Windows 10 

- superset version: `superset version`  Latest as of this posting
- python version: `python --version`   3.7.1
- node.js version: `node -v`  10.16.0
- npm version: `npm -v` 6.9.0

### Checklist

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x]  I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Try increasing the available resource on the linux VM: https://docs.docker.com/docker-for-windows/

**Comment by nickchoate** [comment]
@dpgaspar Increasing the memory helped move past the npm build step that was failing, however I am now getting a new error.  This for docker on windows as well.  I'm going to try to run on Linux and see if there's a difference.
```Step 21/32 : RUN cd /app         && chown -R superset:superset *         && pip install -e .
 ---> Running in 3d9635489468
Obtaining file:///app
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/setup.py'"'"'; __file__='"'"'/app/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /app/
    Complete output (10 lines):
    fatal: not a git repository (or any of the parent directories): .git
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    VERSION: 0.999.0dev
    GIT SHA:
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/app/setup.py", line 57, in <module>
        with open(VERSION_INFO_FILE, "w") as version_file:
    NotADirectoryError: [Errno 20] Not a directory: '/app/superset/static/assets/version_info.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by anshumanpatil** [comment]
@dpgaspar tried increasing memory on windows docker and getting following error 




Obtaining file:///app
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/setup.py'"'"'; __file__='"'"'/app/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /app/
    Complete output (10 lines):
    fatal: not a git repository (or any of the parent directories): .git
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    VERSION: 0.999.0dev
    GIT SHA:
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/app/setup.py", line 57, in <module>
        with open(VERSION_INFO_FILE, "w") as version_file:
    NotADirectoryError: [Errno 20] Not a directory: '/app/superset/static/assets/version_info.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app         && chown -R superset:superset *         && pip install -e .' returned a non-zero code: 1

**Comment by willbarrett** [comment]
Hi @anshumanpatil. Currently Superset does not support Windows as a host OS. My recommendation would be to install Superset inside of a Linux VM rather than using Docker for Windows. There are multiple recorded incompatibilities with Microsoft Windows.

**Comment by octaviancorlade** [comment]
@richlysakowski my changes mentioned above were later reverted in #10236. In 2020 that change was enough to make Superset run on Windows, but I don't have a way to test now anymore. 

If Superset is not building on Windows it would be helpful to share details about the problem, the set of incompatibilities probably changed in the last years
