### ISSUE TITLE
What is the "expanded_slices" option used for?

### ISSUE THREAD

**Issue by kaspergaj** [apache/incubator-superset#8791]
In the dashboard JSON metadata a set of options is given and I have found an example in the FAQ for some of the options:
`{
    "filter_immune_slices": [324, 65, 92],
    "expanded_slices": {},
    "filter_immune_slice_fields": {
        "177": ["country_name", "__time_range"],
        "32": ["__time_range"]
    },
    "timed_refresh_immune_slices": [324]
}`
However I do not understand nor can I find any information on what the option "expanded_slices" can be used for. Can anybody explain this? Thanks

**Comment by mistercrunch** [comment]
This looks like an artifact from a deprecated feature. Prior to dashboard v2, you could expand the chart description in the context of the dashboard and it would show as a sub-header. When saving the dashboard, it would remember which charts had the sub-header showing and would save that in the state.

@graceguo-supercat I think this is deprecated, right?

**Comment by graceguo-supercat** [comment]
No it's not deprecated. if a chart has "description" metadata, it will show up here:
<img width="1257" alt="Screen Shot 2019-12-09 at 10 59 27 PM" src="https://user-images.githubusercontent.com/27990562/70503142-a82c7c80-1ad7-11ea-831e-4ed3952fc97a.png">
