### ISSUE TITLE
Gantt Chart or Custom Chart 

### ISSUE THREAD

**Issue by rrjanbiah** [apache/incubator-superset#8792]
### Motivation

Gantt Chart would be cool. 

Similarly, adding user avatars in any other charts would be cool (and so, possibility to extend current chart with custom would be really useful)

### Proposed Change

Issue #4035 already got closed. PR #5174 seems to be complete and also got closed. Unfortunately, not very technical in terms of Superset and can't comment on it.

**Comment by redanium** [comment]
With help of cursor and some tweakings I got it working 
![Image](https://github.com/user-attachments/assets/686814e3-952f-48af-b6af-a72ebfd99bbe)

**Comment by edogev** [comment]
> С помощью курсора и некоторых настроек я кое-что сделал (на основе столбцов, которые вы видите, и D3.js)
> 
> ![Image](https://github.com/user-attachments/assets/0def96c0-c121-4290-8b65-3ead6adb057b)
> 
> ![Image](https://github.com/user-attachments/assets/686814e3-952f-48af-b6af-a72ebfd99bbe)
> 
> ![Image](https://github.com/user-attachments/assets/dc9bf1d0-6cd7-4129-9b06-6ccd1c7b4f66)

A very good solution, can you tell me how I can install it in my superset?

**Comment by redanium** [comment]
@edogev  it's under dev ... as soon as I finished it , I'll make a PR.
