### ISSUE TITLE
How to programmatically import a CSV file as a table?

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#8796]
I am running the last version of Superset via Docker. 

If I want to import a CSV file to Superset, I go through this route: 
**Open Superset -> Sources -> Upload a CSV**

I want to write a script that uploads a CSV file to superset. Is it possible to perform this task programmatically?

**Comment by mistercrunch** [comment]
Might as well write a script that uploads data directly to your database (?)

**Comment by davidhassan** [comment]
I had to write a script to write my tables into the database.

**Comment by klazaj** [comment]
@mistercrunch If I do that then I'd have to stop the Superset Server every time I upload the data to the postgreSQL database. 
I was wondering whether there was another way

**Comment by dpgaspar** [comment]
@klazaj, why do you need to stop superset?

**Comment by klazaj** [comment]
@davidhassan did you also run superset with docker? was your database the superset postgres?

**Comment by klazaj** [comment]
@dpgaspar I thought I had to stop it because it was using the same postgres port, but apparently I don't need to

**Comment by klazaj** [comment]
What I resorted to doing: 

1. copy file from local to live container: `docker cp file.csv container:/file.csv`
2. enter live container: `docker exec -it container_id bash`
3. login postgres database from within the container: `psql -U superset -d superset`
4. create table in db and copy new table:
```
create table new (field type ...);
\copy new from 'file.csv' with delimiter as ',' csv header;
```

If someone knows a better way please comment below!
