### ISSUE TITLE
Issue with Superset installation at build step

### ISSUE THREAD

**Issue by sarithapodali** [apache/incubator-superset#8798]
> core-js@3.2.1 postinstall /app/superset/assets/node_modules/@babel/register/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 2773 packages in 66.289s
Removing intermediate container dff9157199e0
 ---> 9f70eeaafc00
Step 10/32 : COPY ./superset/assets /app/superset/assets
 ---> 18d77c5fe99d
Step 11/32 : RUN cd /app/superset/assets         && npm run build         && rm -rf node_modules
 ---> Running in 15543a387124

> superset@0.999.0-dev build /app/superset/assets
> cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress

clean-webpack-plugin: /app/superset/assets/dist has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-09T22_53_26_487Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset/assets         && npm run build         && rm -rf node_modules' returned a non-zero code: 1

#### How to reproduce the bug

I am trying to setup Superset on my local using Docker ToolKit for Windows that in turn creates a linux VM. This step went through fine. 
After that I am trying to install Apache Superset (http://superset.apache.org/installation.html)and I ended up in this.

### Environment

(please complete the following information):

- superset version: https://github.com/apache/incubator-superset/

**Comment by dpgaspar** [comment]
Take a look at #8763, #8790
