### ISSUE TITLE
Unable to resize charts in dashboard

### ISSUE THREAD

**Issue by azure31** [apache/incubator-superset#8801]
I'm unable to resize the charts of my dashboard. 
As per the [documentation](https://superset.apache.org/tutorial.html),

> you can adjust the size of slices in a dashboard by clicking, holding and dragging the bottom-right corner to your desired dimensions

but this doesn't seem to be working and I don't see any caret sign for resizing. 

### Environment
- apache-superset package version: `0.35.1`
- python version: `3.6.7`
- node.js version: `v8.10.0`
- npm version: `3.5.2`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Did you switch to "edit mode"?

**Comment by azure31** [comment]
Oh got it now, thanks 

> Did you switch to "edit mode"?
