### ISSUE TITLE
Invalid Columns message box in SQL Lab is not dismissed on Ok button click

### ISSUE THREAD

**Issue by KrishnaPG** [apache/incubator-superset#8803]
### Expected results

When clicked on the Ok button the invalid columns message box (in SQL Lab) should be dismissed.

### Actual results

The Error message dialog stays on

#### Screenshots

![image](https://user-images.githubusercontent.com/4610831/70533877-f8f7b000-1b7f-11ea-8ae3-d13d7bc39c4d.png)

#### How to reproduce the bug
1. Enter any query in SQL Lab (something like below:)
````
SELECT name AS name,
       ds AS __timestamp,
       SUM(num) AS sum__num,
       SUM(CASE
               WHEN state = 'CA' THEN num
               ELSE 0
           END) AS `SUM(num_california)`
FROM birth_names
INNER JOIN
  (SELECT name AS name__,
          SUM(num) AS mme_inner__
   FROM birth_names
   WHERE ds >= STR_TO_DATE('1919-12-10 00:00:00', '%Y-%m-%d %H:%i:%s')
     AND ds <= STR_TO_DATE('2019-12-10 04:13:03', '%Y-%m-%d %H:%i:%s')
   GROUP BY name
   ORDER BY SUM(CASE
                    WHEN state = 'CA' THEN num
                    ELSE 0
                END) DESC
   LIMIT 10) AS anon_1 ON name = name__
WHERE ds >= STR_TO_DATE('1919-12-10 00:00:00', '%Y-%m-%d %H:%i:%s')
  AND ds <= STR_TO_DATE('2019-12-10 04:13:03', '%Y-%m-%d %H:%i:%s')
GROUP BY name,
         ds
ORDER BY sum__num DESC
LIMIT 50000;
````
2. Run the query, and once the results are avilable click on the "Explore" button
3. You should see an error message regarding column names. Click on `ok` to dismiss the dialog. It won't go away

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

https://github.com/apache/incubator-superset/blob/44d919c757fec0705f52cede8a1c6289fbf79817/superset/assets/src/SqlLab/components/ExploreResultsButton.jsx#L201-L205

**Comment by mxmulder** [comment]
I've attempted to replicate this problem with the most up to date version of superset and while I do see this error message, I have not had a problem with the OK button. Can you provide more context about your problem? I've tested this in Safari, Firefox and Chrome.
