### ISSUE TITLE
Building Superset fails with NotADirectoryError: [Errno 20] Not a directory: '/app/superset/static/assets/version_info.json

### ISSUE THREAD

**Issue by sarithapodali** [apache/incubator-superset#8804]
Step 19/32 : COPY superset /app/superset
 ---> a15169a256dd
Step 20/32 : COPY setup.py MANIFEST.in README.md /app/
 ---> e68a6c753c5a
Step 21/32 : RUN cd /app         && chown -R superset:superset *         && pip install -e .
 ---> Running in fe0f965f40ca
Obtaining file:///app
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/setup.py'"'"'; __file__='"'"'/app/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /app/
    Complete output (10 lines):
    fatal: not a git repository (or any of the parent directories): .git
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    VERSION: 0.999.0dev
    GIT SHA:
    -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/app/setup.py", line 57, in <module>
        with open(VERSION_INFO_FILE, "w") as version_file:
    NotADirectoryError: [Errno 20] Not a directory: '/app/superset/static/assets/version_info.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app         && chown -R superset:superset *         && pip install -e .' returned a non-zero code: 1

**Comment by craig-rueda** [comment]
Hey @sarithapodali, what sha are you running? I recall this was an issue a few commits back, but has been fixed since.

**Comment by sarithapodali** [comment]
> Hey @sarithapodali, what sha are you running? I recall this was an issue a few commits back, but has been fixed since.

@craig-rueda I pulled in the latest.  git clone https://github.com/apache/incubator-superset/

**Comment by nytai** [comment]
@sarithapodali are you trying to build docker on windows?

**Comment by sarithapodali** [comment]
@nytai Yes. That's right.

**Comment by mistercrunch** [comment]
Issue around symlinks?

**Comment by nytai** [comment]
@sarithapodali there's no official support for windows. The issue here is that there should be a symlink from `superset/assets/` to `superset/static/assets`, however git doesn't not create this symlink on windows. 
more on this here: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

We probably should fix some of this and not rely on a symlink, but that probably won't get worked on for a while. 

As a quick workaround you can probably create a symlink or just copy `superset/assets` to `superset/static/assets`.

**Comment by sarithapodali** [comment]
Thank you @nytai that works. But I run into different issues further.
