### ISSUE TITLE
Cannot add new country to CountryMap chart

### ISSUE THREAD

**Issue by barmic12** [apache/incubator-superset#8819]
I was trying add new country following to https://superset.apache.org/visualization.html#need-to-add-a-new-country, however it doesn't work - new country is visable in dropdown, but when I click on it, map is blank.

### Expected results

Can display new added map from .geojson

### Actual results
![image](https://user-images.githubusercontent.com/5133050/70693016-db7c3080-1cbc-11ea-857b-36b79c11e20e.png)

I get 404 when I click new country on dropdown map is fetching:
```
Request URL: http://localhost:5000/superset/explore/undefined
Status Code: 404 NOT FOUND
```

Other (default) maps works properly:

```
Request URL: http://localhost:5000/static/assets/dist/5f64d14062abb5f5fd6610972976ebe6.geojson
Status Code: 200 OK
```

I was able to resolve this issue by editing `assets/node_modules/@superset-ui/legacy-plugin-chart-country-map/countries.js` and add `.geojson` file to this directory. So it means that maps are fetched from npm package? 

#### How to reproduce the bug

https://superset.apache.org/visualization.html#need-to-add-a-new-country

### Environment

- superset version: `0.999.0dev`
- python version: `Python 3.7.5`
- node.js version: `v12.12.0`
- npm version: `6.11.3`

I built superset from source.

**Comment by PeterCahn** [comment]
> I was able to resolve this issue by editing `assets/node_modules/@superset-ui/legacy-plugin-chart-country-map/countries.js` and add `.geojson` file to this directory. So it means that maps are fetched from npm package?

I needed to add a map and this was the only working way that I found.

It would be possible to have a way to add a new map instead of building it from source? There is some workaround?

**Comment by Sandwichzhao** [comment]
hello, I want to get city of guangdong province,how can I do.Can you help me?
![image](https://user-images.githubusercontent.com/13583249/78120615-d6461b80-743c-11ea-8469-904585e898d5.png)

**Comment by czue** [comment]
I just submitted a PR to update the docs for this: https://github.com/apache/incubator-superset/pull/10621 based on [this comment](https://github.com/apache/incubator-superset/issues/8819#issuecomment-566028735) and successfully going through the process. Hopefully it will be merged and save others the trouble that I've had to go through to get this working!
