### ISSUE TITLE
Can we save superset metadata tables  to oracle db instead of postgres db.

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8821]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Oracle is not included on the tests, but I think it should work

**Comment by umesh11111** [comment]
can you please elaborate more on to this steps,
any help would be appreciated..
Thanks,
Umesh

**Comment by dpgaspar** [comment]
Set `SQLALCHEMY_DATABASE_URI` to Oracle. If you already have data on PG you need to migrate it too

**Comment by umesh11111** [comment]
So i need to change the url to oracle in config file like  SQLALCHEMY_DATABASE_URI = 'oracle://app@localhost/myapp' and then run the superset db upgrade script

**Comment by dpgaspar** [comment]
Yes it will start saving superset metadata db on oracle

**Comment by umesh11111** [comment]
so it will work for any superset version or there are any specific superset version we need to use?

**Comment by dpgaspar** [comment]
No specific version, but I advise you to use the latest 0.35.1. Again, Oracle is not part of our unit tests

**Comment by umesh11111** [comment]
after running the superset db upgrade command , i got the the below error.
flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (cx_Oracle.DatabaseError) ORA-12541: TNS:no listener
(Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by dpgaspar** [comment]
That's database connection error, not related to superset.

**Comment by umesh11111** [comment]
i have installed cx_oracle module and then tried to ran but no luck,can you please suggest what i need to do?

**Comment by umesh11111** [comment]
in the connection string i mentioned only the owner name,username,passsword,hostname,and db name and the hostname is not the localhost so do i need to mentioned the port number n all anywhere?

**Comment by villebro** [comment]
I have an Oracle docker instance that I use for testing with the following URL:
`oracle+cx_oracle://system:XXXXXXXXXX@localhost:49161/?service_name=xe`. So I think you need to provide the TNS name in the URI (`xe` in my example). Having said that... While running the metadata backend on Oracle should in theory work, Oracle is not officially supported, and hence I would expect you to run into problems. Therefore, I strongly urge you to consider using Postgres or MySQL, as they are extensively used in Superset production envs.

**Comment by umesh11111** [comment]
so i need to use the connection in below format.
oracle+cx_oracle://username:password@hostname:port/dbname'
so where i need to use the ?service_name=xe in this connection string?

**Comment by umesh11111** [comment]
Getting the below error after running the db upgrade command,
its creating the few table and after that its throwing the error.

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-02274: duplicate referential constraint specifications
[SQL:

**Comment by umesh11111** [comment]
Any reply on this?

**Comment by dpgaspar** [comment]
Can you please post your full migration logs?

**Comment by umesh11111** [comment]
@dpgaspar oracle is not considering the duplicate value as well as some of the column name in postgres,its became  keyword in oracle like date etc..

**Comment by dpgaspar** [comment]
@umesh11111 I'm sorry for this, like @villebro said, it would in work in theory, but we strongly advise you to consider MySQL or Postgres
