### ISSUE TITLE
Visualization and explore with celery

### ISSUE THREAD

**Issue by blcksrx** [apache/incubator-superset#8823]
Dashboards and Charts include at least more than one query and this would be helpful to distribute these queries to celery workers to increase performance and loads on superset.

**Comment by jackyq2015** [comment]
Any idea how to do the profiling to identify the slowness? I feel there is something wrong with the front end also. The reason is that even for a small query(with one filter box and a table), it will take times to load it. I can see there are lots of dispatch happens. Not sure if some of them can be skipped or cached.

**Comment by blcksrx** [comment]
Agreed! Maybe @mistercrunch can help us.

**Comment by jackyq2015** [comment]
Actually, even you have 10 queries on one dashboard, celery worker can only help ease the load the flask server. All the queries eventually will be ran against the same DB where the bottleneck comes from(if there is any). If you have a MPP database like druid, it should still ok. If you have a regular db like mysql, it still an issue no matter you spread the work load or not(the amount of data transferred for dashboard  normal not that much).

That's my assumption. But it is only an assumption if there is no method/tool to profiling the whole life cycle.

**Comment by blcksrx** [comment]
> Actually, even you have 10 queries on one dashboard, celery worker can only help ease the load of the flask server. All the queries eventually will be ran against the same DB where the bottleneck comes from(if there is any). If you have a MPP database like druid, it should still ok. If you have a regular db like mysql, it still an issue no matter you spread the work load or not(the amount of data transferred for dashboard normal not that much).
> 
> That's my assumption. But it is only an assumption if there is no method/tool to profiling the whole life cycle.

Actually, currently `sql_lab` uses celery to distribute the tasks, so why `explore_json` or `dashboards` should not use that?

**Comment by jackyq2015** [comment]
I think fire and go is needed for SQL lab. it can send the result to email or what ever user want. for another 2 cases, firstly user need to wait and see result. secondly, it may not solve the slowness issue as I mentioned above
