### ISSUE TITLE
Permit "EXPLAIN" with "Allow DML" unchecked

### ISSUE THREAD

**Issue by rubypollev** [apache/incubator-superset#8827]
**Is your feature request related to a problem? Please describe.**
`EXPLAIN` commands are essential to the workflow of many analysts; they are often a pre-cursor to a `SELECT`. `EXPLAIN`s are, however, not permitted with `Allow DML` unchecked. This is problematic.

**Describe the solution you'd like**
`EXPLAIN` should be allowed with `Allow DML` unchecked. This is not a destructive command. 

**Describe alternatives you've considered**
Maybe an independent checkbox? Not sure why we'd want this.

**Comment by mistercrunch** [comment]
Sounds totally reasonable.

+1

**Comment by willbarrett** [comment]
Bump to keep active :)

**Comment by willbarrett** [comment]
Bump

**Comment by willbarrett** [comment]
Bump

**Comment by bkyryliuk** [comment]
Also it would be nice to add SET support for the hive engine as well

**Comment by villebro** [comment]
Let's try to prioritize this to get it off the backlog
