### ISSUE TITLE
Do we really need four different Python linters?

### ISSUE THREAD

**Issue by suddjian** [apache/incubator-superset#8828]
The rules often conflict with each other on things like import order or how you should break up long lines, leading to `disable` comments scattered all over the codebase and a lack of cohesive code style. How would folks feel about switching to just one?

**Comment by craig-rueda** [comment]
How do people feel about Flake? I heard it was removed recently in favor of the current linters. Have you searched closed PRs for the change that changed linters?

**Comment by willbarrett** [comment]
As it stands now, we have:

`black` - automatic code formatting
`pylint` - enforces a wide variety of rules
`mypy` - type checking
`isort` - automatic package sorting

`black`'s maintainers explicitly recommend using `black` with `isort`, and are working on ensuring interoperability. Neither of those tools do anything with type checking, hence the inclusion of `mypy`. `pylint` is the most annoying to deal with, IMHO, when it comes to code formatting issues. The bits of it I like are ensuring that classes inheriting from a parent don't alter method signatures, ensuring that classes implement all of the methods required by their abstract classes, and identifying classes and functions that are too big and should be broken up.

I'd love to get this down to a single linter as well, but I'm wondering which checks we'd be willing to walk away from? There doesn't seem to be a single linter that covers everything in the Python ecosystem right now, but I'd love to be proven wrong on that!

The main pain points I have:
1. I have to run a bunch of different commands to see if my code will pass all the linters, and I usually miss one or more for N files in any PR where I'm making changes, even with auto-linting set up in PyCharm. I wonder if there is a way we could implement a `superset lint X` command that would do all the things at once and act as a controller for whatever linters we have in the project?
2. `isort` and `black` disagreeing on whitespace when I'm trying to comment on an `import` statement
3. `pylint: disable=` comments triggering `black` reformatting

**Comment by mistercrunch** [comment]
Did you setup `pre-commit`?
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#git-hooks

It checks only touched files so it's fast (pylint is super slow to run across the codebase)

About `pylint` vs `flake8`: pylint is dynamic so it can do things `flake8` (static analysis) will probably never do. Things like method signatures matching over inheritance, code complexity checks, number of arguments too high, ... It's old and clunky but somewhat powerful. We can disable checks we don't like. 

`black` and `flake8` had lots of overlap and some conflicts. It made sense to kill `flake8`

`mypy` is type checking, different purpose, we should enable in pre-commit if possible

**Comment by craig-rueda** [comment]
Flake is pluggable, which I think is nice. We're using flake-mypy internally, along with various other features. I think that from a usability standpoint, needing to run so many commands to test/lint is a bit much (current count is 6 when running outside of tox). Perhaps this warrants a "test" script or something like that? We could install something through setup.py?

**Comment by suddjian** [comment]
`pre-commit` doesn't run all the linters, only black and isort. Even if it did, linters conflicting with each other would still be a problem. It would also be nice to be able to run the checks against your code without committing.

**Comment by etr2460** [comment]
Unfortunately, flake-mypy doesn't support all the functionality we'd need to do full typechecking. Flake runs at the file level, so it doesn't guarantee type consistency between files. See here for details: https://github.com/apache/incubator-superset/pull/8409

I'd strongly recommend bringing this up in the next superset meetup as I think @john-bodley has been doing a lot of work in this space and he's on PTO right now.

**Comment by john-bodley** [comment]
As @willbarrett pointed out these four linters all provide different linting functionality from code formatting, type checking, and flagging programatic errors. Personally I would love for `black` to be opinionated with regards to imports which would remove the need to use `isort`. 
 
As @mistercrunch mentioned `pylint` is dynamic and provides functionality that `flake8` never could. I sense that `black` + `isort` + `mypy` + `pylint` is a superset of `flake8` hence why `flake8` was removed. `pylint` has its detractors and at times it feels somewhat dated but personally I'm a fan. The signature checking is vital and the syntax checks generally make sense which aid with code quality.

**Comment by mistercrunch** [comment]
Related project to check out that attempts making much of the tooling we use more comprehensible: https://bento.dev/

I spoke with the bento team and they are interested to engage with us if we want to. For the record they picked flake8 over pylint, preferring static analysis over dynamic.
