### ISSUE TITLE
Missing CSRF token when embedding dashboard using iframe in development mode

### ISSUE THREAD

**Issue by azure31** [apache/incubator-superset#8830]
### Expected results
I am trying out superset for the first time. I am currently running it in development mode from my local machine and want to embed the dashboards I created in an html using iframes 
`<iframe src="http://172.20.33.111:8088/superset/dashboard/7/?standalone=true"
								height="600" width="1200">` 

The embed asks for login credentials and then throws a `CSRF token is missing` error. 

#### Screenshots

Same as [#8382]

#### How to reproduce the bug

Launch Apache Superset using superset run -h 0.0.0.0 -p 8088

Connect the link via iframe into another separate webpage
See error

### Environment

-  superset package version: `0.35.1`
- python version: `3.6.7`
- node.js version: `v8.10.0`
- npm version: `3.5.2`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
As per [#8382], I have updated the `SESSION_COOKIE_SAMESITE` value to None, but it didn't work for me.

**Comment by emersondasilva** [comment]
# 8382

**Comment by andrewmusselman** [comment]
I'm experiencing this issue as well; I saw issue #8382 linked above but the solution is to set what looks like a flask variable: `SESSION_COOKIE_SAMESITE = None # One of [None, 'Lax', 'Strict']`

The install of superset I'm using is from pip, so I don't seem to have any superset or flask config files to edit.

Is there a way to invoke this variable on the command line when starting superset?

**Comment by azure31** [comment]
@andrewmusselman: there should be a `config.py` file where the superset package is installed. the flags can be set there. I'm still facing the issue though.

**Comment by andrewmusselman** [comment]
Thanks Pranita; I just don't seem to have that file in my installation.
