### ISSUE TITLE
Cannot filter based on druid lookup dimension

### ISSUE THREAD

**Issue by stelios313** [apache/incubator-superset#8831]
I am trying to filter with bound > operator on a druid lookup dimension, and it does not work. 

### Expected results

Expected to work same as any other dimension i am filtering. 

### Actual results

![image](https://user-images.githubusercontent.com/3808966/70791662-2d49b700-1da0-11ea-85ac-a6dc4f2cd824.png)

#### How to reproduce the bug

- Add a druid datasource to superset
- Publish a lookup to the druid cluster
- Define in the datasource a custom dimension based on a lookup such as:
```
{
    "type": "extraction",
    "dimension": "publisher_id",
    "outputName": "publisher_first_revenue_month",
    "outputType": "LONG",
    "extractionFn": {
        "type": "registeredLookup",
        "optimize": true,
        "lookup": "publisher_first_revenue_month"
    }
}    
```
In the explore screen, generate a query using the custom dimension as the filter criteria with a bound operator (>, < , >=, <=). And the error from pydruid will show up.

### Environment

- superset version: `0.35.0`
- python version: `3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Pretty sure that's been fixed in `master` at the bug bash. Here https://github.com/apache/incubator-superset/pull/8714
