### ISSUE TITLE
Step 1/32 : ARG PY_VER=3.6.9 ERROR: Service 'superset' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by oguzhan10** [apache/incubator-superset#8832]
after docker-compose up command 

This error happens

Step 1/32 : ARG PY_VER=3.6.9 ERROR: Service 'superset' failed to build: Please provide a source image with `from` prior to commit

**Comment by dpgaspar** [comment]
What's the docker version your using?

**Comment by craig-rueda** [comment]
Please upgrade to the latest docker version 😃

**Comment by oguzhan10** [comment]
I updated my docker version thank you so much everybody. But when I write docker-compose up it stucked on this. I cant localhost:8088.

superset_1         | 127.0.0.1 - - [13/Dec/2019 20:21:31] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:21:31] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:22:01] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:22:01] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:22:31] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:22:31] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:23:02] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:23:02] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:23:32] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:23:32] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:24:02] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:24:02] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:24:32] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:24:32] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:25:03] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:25:03] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:25:33] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:25:33] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:26:04] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:26:04] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:26:34] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:26:34] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:27:04] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:27:04] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [13/Dec/2019 20:27:34] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [13/Dec/2019 20:27:34] "GET /health HTTP/1.1" 200 -

**Comment by craig-rueda** [comment]
That looks good - what you're seeing there is the health check being pinged by the Docker daemon. Try doing a `docker ps` to see what ports are mapped where. The compose file maps 8088 to 8088:
```
    ports:
      - 8088:8088
```

**Comment by oguzhan10** [comment]
thanks everybody case closed

**Comment by oguzhan10** [comment]
thanks everybody case closed

**Comment by semihmasat** [comment]
Hello. I am having the same problem.

both docker and docker-compose is on the latest version.

Docker version 1.13.1, build 4ef4b30/1.13.1
docker-compose version 1.25.3, build d4d1b42b

`
[xxxx-superset]$ docker-compose up
Building superset
Step 1/32 : ARG PY_VER=3.6.9
ERROR: Service 'superset' failed to build: Please provide a source image with `from` prior to commit
[xxxx-superset]$ 
`

`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"`

**Comment by craig-rueda** [comment]
Looks like you need to update Docker. `1.13` doesn't support ARGs before `FROM` :(

**Comment by semihmasat** [comment]
Oh. My bad. it looks like Centos, yum doesn't automaticaly updates docker. updated it, added docker to a usergroup and it fixed the problem. 

thanks.

**Comment by BBenQi** [comment]
> Please upgrade to the latest docker version 😃

thanks!
