### ISSUE TITLE
"Table [table_name] doesn't seem to exist, couldn't fetch metadata" 

### ISSUE THREAD

**Issue by mahedi0244** [apache/incubator-superset#884]
I encountered this error after I replaced caravel db into MySQL. I am trying to add a mysql database that I want to work with. The database is loading properly as I see "seems ok" when I test the connection. But the error occurs when i want to add any valid table from my database.

**Comment by xrmx** [comment]
The error should be quite clear. Do you have that table in the db?

**Comment by topazas** [comment]
Exactly the same problem with postgresql.
That error message is simply wrong, because table exists and connected user has all rights.

**Comment by xrmx** [comment]
@topazas if you know what's wrong then please fix it and open a pull request, it would be great :)

**Comment by mistercrunch** [comment]
This should be something simple like your connection string (URL) isn't pointing to the right database (schema). That or maybe you have something funky going on in the table name (space, unicode, ...)

**Comment by topazas** [comment]
Yesterday tried to upgrade caravel and dependencies (with pip), tested with couple PG users and connection string variants, no spaces or any funky symbols, other software uses the same user with no problems (RoR app, scala app with jdbc connection, simple python flask rest app). Caravel spits error messages :( Mainly, it cannot read table columns. It finds DB and tables, but cannot read column information.

Today evening gonna debug and look further in to code... For now cannot confirm bug.

**Comment by aljones** [comment]
I had this problem with a mssql db when the column type field was not long enough to hold a column's type I was trying to add.  I edited the column directly in the db and promptly forgot about it...

If I remember correctly there was a stack trace in the caravel log that sent me in that direction, so check log.

**Comment by mahedi0244** [comment]
@mistercrunch I just figured out that, I am actually able to load some tables from my database,
but the error occurs for most of the table even though the table name is 100% correct. 
(just to let you know: previously,  I loaded and worked with my database in caravel properly when I used sqlite as caravel database)

**Comment by cactusthinking** [comment]
this maybe coursed by some fields in you data table exceed the caravel table:table_columns,field:type 's size limit 
I used MySQL: error when add table.
(1406, "Data too long for column 'type' at row 1") [SQL: 'INSERT INTO table_columns (created_on, changed_on, table_id, column_name, verbose_name, is_dttm, is_active, type, groupby, count_distinct, sum, max, min, filterable, expression, description, python_date_format, database_expression, created_by_fk, changed_by_fk) VALU

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 579 days. Feel free to comment and request for this issue to be reopened.
