### ISSUE TITLE
Cant creating chart in superset via Kylin

### ISSUE THREAD

**Issue by oguzhan10** [apache/incubator-superset#8842]
First of all, we connected Kylin to superset using Kylin's connection string. So we've been able to see Kylin tables in Superset. But when we try to create a chart we saw the error given below.  

![Ek Açıklama 2019-12-16 133227](https://user-images.githubusercontent.com/34449619/70899852-9cc1df80-2008-11ea-903d-1565424fb5c4.jpg)

Then we changed the " /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kylinpy/sqla_dialect.py " file. We changed initial code as shown above into configuration like that initial_quote=' ', escape_quote= ' '. 

```
    def __init__(self, dialect, initial_quote='"',
                 final_quote= None , escape_quote= '"', omit_schema=True):
        super(KylinIdentifierPreparer, self).__init__(
            dialect, initial_quote, final_quote, escape_quote, omit_schema
        )

```

That's how we've been able to preview the table but then when we try to create a bar chart the problem remained and our query looked like that;

![1Ek Açıklama 2019-12-16 135045](https://user-images.githubusercontent.com/34449619/70901142-42764e00-200b-11ea-977a-0a08874600d2.jpg)

However the same table and the same query is working when we use Impala as shown below.

![2Ek Açıklama 2019-12-16 140529](https://user-images.githubusercontent.com/34449619/70902111-28d60600-200d-11ea-82a5-e0d73341bf61.jpg)

### Environment

- superset version: `0.30.0`
- python version: `3.6.3`
- kylin version: `3.0`
- kylin.py version: `2.3.1`
- impala version: `0.13.7`

**Comment by zhaoyongjie** [comment]
@oguzhan10 
This is a bug in kylinpy. I have fixed this problem. In kylinpy 2.4 and above fixed. you can run
```
 pip install -U kylinpy 
```
to upgrade
