### ISSUE TITLE
Getting error while installing the superset .35.1 version using pip install apache-superset==0.35.1

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8853]
ERROR: Could not find a version that satisfies the requirement pyarrow<0.15.0,>=0.14.1 (from apache-superset==0.35.1) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.15.1)
ERROR: No matching distribution found for pyarrow<0.15.0,>=0.14.1 (from apache-superset==0.35.1).

### Expected results

what you expected to happen.
It should install the superset
### Actual results

what actually happens.
ERROR: Could not find a version that satisfies the requirement pyarrow<0.15.0,>=0.14.1 (from apache-superset==0.35.1) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.15.1)
ERROR: No matching distribution found for pyarrow<0.15.0,>=0.14.1 (from apache-superset==0.35.1)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi,

Please post you OS name and version

**Comment by gry77** [comment]
I'm facing this issue as well...
OS : macOS Mojave 10.14.6
command to install : "pip install apache-superset"

**Comment by umesh11111** [comment]
windows 10

**Comment by rplescia** [comment]
Windows 10, Python 3.7.5
It seems as though pyarrow 0.14.1 has been removed from PyPi.org. if I run 'pip install pyarrow==0.14.1' I get the same error message, I can install everything <= 0.14.0 and >=0.15.0. Perhaps the dependency on 0.14.1 needs to be removed

**Comment by umesh11111** [comment]
so we can not install .35 in windows

**Comment by rplescia** [comment]
> so we can not install .35 in windows

and MacOS, see gry77's post in further up the thread. I don't think this is an issue with superset but rather that the pyarrow 0.14.1 library has been removed from PyPi so the dependency needs to be mitigated

**Comment by umesh11111** [comment]
can you help me out , can we save superset metadata to Oracle db instead of postgresdb?

**Comment by dpgaspar** [comment]
The oracle issue is reported on #8821 

I'm really surprised pyarrow 0.14.1 does not work on MacOS can you post your logs @gry77 ? Thank you.

@umesh11111 Windows is not supported. But can I ask you to `pip install pyarrow==0.15.1` on your env?

**Comment by gry77** [comment]
@dpgaspar , below is the error when i run "pip install apache-superset"
````
ERROR: Could not find a version that satisfies the requirement pyarrow<0.15.0,>=0.14.1 (from apache-superset) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1)
ERROR: No matching distribution found for pyarrow<0.15.0,>=0.14.1 (from apache-superset)
````
Then I tried run "pip install pyarrow==0.14.1"
````
ERROR: Could not find a version that satisfies the requirement pyarrow==0.14.1 (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1)
ERROR: No matching distribution found for pyarrow==0.14.1
````

I think what @rplescia mentioned is correct. Somehow pyarrow 0.14.1 can't be downloaded from pypi.org and when I google this error, several other github project also facing same issue

**Comment by rplescia** [comment]
> @umesh11111 Windows is not supported. But can I ask you to `pip install pyarrow==0.15.1` on your env?

This doesn't fix the issue, this is because of the requirement is hard set using 0.14.1. If you update this to use 0.15.1 it would not be an issue.

ERROR: Could not find a version that satisfies the requirement **pyarrow<0.15.0,>=0.14.1** (from apache-superset)

**Comment by rplescia** [comment]
I cloned the git repository last night and inspected the code. In setup.py I found this on line #100 `pyarrow>=0.15.1, <0.16.0` which is very similar to the offending code in my post above

I therefore think the version currently on PyPi.org is not 0.35.1 or it has been uploaded with the wrong setup.py file. I think a fresh commit to PyPi might solve the problem.

**Comment by dpgaspar** [comment]
@rplescia, there's no mismatch, each release obeys the Apache release process (https://github.com/apache/incubator-superset/tree/master/RELEASING), and master is always ahead.

A new patch release is being prepared (0.35.2) that contains the fix you mention

**Comment by rplescia** [comment]
I look forward to the new release

**Comment by rplescia** [comment]
@dpgaspar I can now confirm this works for me, you can probably close this issue if no one objects
