### ISSUE TITLE
Can Snowflake be used as metadata database in Superset?

### ISSUE THREAD

**Issue by sarithapodali** [apache/incubator-superset#8855]
Can Snowflake be used as metadata database in Superset?

**Comment by villebro** [comment]
The short answer is no. Snowflake is very limited in functionality found in typical OLTP databases (e.g. only supports constraints and primary/foreign keys for documentation purposes), and in general performs poorly for low-latency low-volume queries. You're best off keeping your metadata in Postgres or MySQL, and using Snowflake for analytical workloads.
