### ISSUE TITLE
The default role should be a list not a scalar?

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8861]
**Is your feature request related to a problem? Please describe.**
I need a default role that enhances the abilities of the gamma user. I do not want to copy all the gamma abilities and then add the extra abilities and lump them into a single role. Superset/FAB RBAC is compositional and I insist on being able to build user roles in agreement with this approach.

**Describe the solution you'd like**
in my `superset_config.py` I set:
    `AUTH_USER_REGISTRATION_ROLE = ["Gamma", "Gamma_extra"]`

and the default user is assigned a set of roles instead of a single role.

**Describe alternatives you've considered**
It is certainly possible to write all the code to do this similar to https://github.com/apache/incubator-superset/issues/3419

But I think a simpler solution would be to admit that RBAC is compositional and allow for that directly from config file.

**Comment by dpgaspar** [comment]
The context for this enhancement is for flask-appbuilder, please open an issue there
