### ISSUE TITLE
deprecate tslint in favor of eslint w/ typescript support

### ISSUE THREAD

**Issue by nytai** [apache/incubator-superset#8865]
Having recently written some typescript in the repo I found the tslint rules to be very strict. Rules like alphabetizing object keys, not allowing lambdas in jsx, not allowing multiline expressions in jsx, among others don't coincide with the eslint rules and are not autofixable. Spending time fixing these is tedious and does not encourage use of typescript. 

In order to increase adoption of typescript in the repo I think it would be good to have the typescript developer experience to be as closer to the current javascript experience. Also, it looks like the creators of tslint are [recommending not using that library anymore](https://medium.com/palantir/tslint-in-2019-1a144c2317a9). 

We should configure eslint to support typescript and try to have as many of the same rules in both environments as possible. Info on how to implement this: https://codeburst.io/from-eslint-to-tslint-and-back-again-bf259c2e7437

**Comment by nytai** [comment]
🏷 frontend

**Comment by etr2460** [comment]
cc @williaster and @kristw for their opinions.

Also, have you considered looking into the build configs in the superset-ui-plugins and superset-ui repos and seeing if they make sense here?

**Comment by kristw** [comment]
Those repositories use `eslint` with `typescript`.

**Comment by williaster** [comment]
standardizing on the `nimbus` build configs from `superset-ui` + `superset-ui-plugins` repos seems like it could be a good idea. then it's one thing to learn across all repos.
