### ISSUE TITLE
how to add echart with 0.99version?

### ISSUE THREAD

**Issue by nick08007** [apache/incubator-superset#8869]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `0.99`
- python version: `python --3.7`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kalimuthu123** [comment]
make a package installed in node modules (npm install echart --save)
and then compile  (npm run build)
and run the debugg server (superset runserver -d )

**Comment by nick08007** [comment]
> make a package installed in node modules (npm install echart --save)
> and then compile (npm run build)
> and run the debugg server (superset runserver -d )

how to use it?  if  I want to use it, how to config it in the superset project？
