### ISSUE TITLE
 Integrity error, probably unique constraint (two mysql databases with same tables)

### ISSUE THREAD

**Issue by facePlanted** [apache/incubator-superset#8871]
With MySQL, after adding the second database and trying to add tables,
I'm getting: Integrity error, probably unique constraint

I've tried also with db.table
and db:table
and also with schema.

Is having two (or multiple) databases with the tables named in the same way
supported in superset ?

**Comment by ivanmartos** [comment]
any update pls?

**Comment by FredericLatour** [comment]
Honestly, it sounds incredible that it's not possible to have the same table name with two different databases.
The tool must have some qualities but between this and the confusing interface, I'm done with it.

**Comment by mprior10** [comment]
A workaround is to create a View, for the subsequent tables, so they are unique.

**Comment by lilykuang** [comment]
it's probably impossible to remove constraints on some databases. There's some comment from previous issues https://github.com/apache/incubator-superset/issues/5557#issuecomment-410306136. Hope that help

**Comment by mistercrunch** [comment]
This should help https://github.com/apache/incubator-superset/pull/9882
