### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:snowflake error when testing connection while adding datasource

### ISSUE THREAD

**Issue by sarithapodali** [apache/incubator-superset#8877]
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:snowflake", "stacktrace": "Traceback (most recent call last):\n  File \"/app/superset/views/core.py\", line 1769, in testconn\n    engine = database.get_sqla_engine(user_name=username)\n  File \"/app/superset/utils/core.py\", line 130, in __call__\n    value = self.func(*args, **kwargs)\n  File \"/app/superset/models/core.py\", line 971, in get_sqla_engine\n    return create_engine(sqlalchemy_url, **params)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py\", line 435, in create_engine\n    return strategy.create(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 61, in create\n    entrypoint = u._get_entrypoint()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/url.py\", line 172, in _get_entrypoint\n    cls = registry.load(name)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 240, in load\n    \"Can't load plugin: %s:%s\" % (self.group, name)\nsqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:snowflake\n"}

- I have run pip3 install snowflake-sqlalchemy
- Verified installation as per https://github.com/snowflakedb/snowflake-sqlalchemy

Please let me know if there are more things to be done here. Thanks!

**Comment by AnkitSingh02** [comment]
Even I am facing similar issue! with Clickhouse.

Can you please share your steps in-case you were able to fix it.

**Comment by sarithapodali** [comment]
@AnkitSingh02 Make sure that all the library installations are done inside the docker.

**Comment by AnkitSingh02** [comment]
Have already installed the library sqlalchemy_clickhouse inside the container, manually by exec into the container (not at the time of creating the container) does that make any difference? Installation while creating the container or installing it by exec inside a container.
