### ISSUE TITLE
[BUG] Can not use comparison operator [Explore][Adhoc Filters]

### ISSUE THREAD

**Issue by hushaoqing** [apache/incubator-superset#8885]
<img width="561" alt="Screen Shot 2019-12-23 at 14 42 18" src="https://user-images.githubusercontent.com/10289162/71340832-fc813300-2592-11ea-95c0-443d75aeb5d8.png">

It seems to be associated with this https://github.com/apache/incubator-superset/pull/5160

**Comment by sanjaythkr7** [comment]
I have same problem. It fails with 
```
/opt/superset/superset-env/lib64/python3.6/site-packages/pydruid/utils/filters.py", line 87, in __init__
    "ordering": args["ordering"],
KeyError: 'ordering'
```
