### ISSUE TITLE
FLASK_APP create-admin not working

### ISSUE THREAD

**Issue by Amogh-Balachandra5** [apache/incubator-superset#8886]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kuckjwi** [comment]
Could you attach the error log?

**Comment by kuckjwi0928** [comment]
Could you attach the error log?

**Comment by Amogh-Balachandra5** [comment]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by Amogh-Balachandra5** [comment]
I have also set the environment variable
as below 
export FLASK_APP=/WebSphere/apache-superset-0.35.1/superset/

where folder superset contains

![image](https://user-images.githubusercontent.com/47969185/71345967-c2ad2e00-258c-11ea-90f5-438dd817e710.png)

**Comment by dpgaspar** [comment]
Hi @Amogh-Balachandra5,

Please follow install instruction in detail: https://superset.apache.org/installation.html#installation-configuration

If the problem persists, post all your commands and output, thank you

**Comment by Amogh-Balachandra5** [comment]
Hi Daniel,

Below are the steps i have followed post installation

Step 1 : **sudo superset db upgrade** 

/usr/local/lib/python3.7/site-packages/SQLAlchemy-1.3.8-py3.7-linux-x86_64.egg/sqlalchemy/sql/functions.py:67: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier)
2019-12-23 13:39:11,411:INFO:root:logging was configured successfully
2019-12-23 13:39:11,526:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.


Step 2 : **sudo flask fab create-admin**

Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: amogh.balachandra@dikshatech.com
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by dpgaspar** [comment]
Really go trough all the steps, install the dependencies, create a virtualenv, and don't use `sudo`

**Comment by Amogh-Balachandra5** [comment]
I have found the solution instead of running 
**sudo flask fab create-admin**

i have ran below and everything worked fine

**sudo fabmanager create-admin --app superset**
