### ISSUE TITLE
limit the memory used??

### ISSUE THREAD

**Issue by wushenchao** [apache/incubator-superset#8895]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Can we limit the memory used when start the project? 
Operation personnel want to limit the memory size of the project，How can we use it？

**Comment by tooptoop4** [comment]
did u solve @wushenchao  ?

**Comment by wushenchao** [comment]
> did u solve @wushenchao ?

no
