### ISSUE TITLE
Display both raw and processed data when using Advanced Analytics 

### ISSUE THREAD

**Issue by zheya08** [apache/incubator-superset#8897]
### Motivation

When I using Advanced Analytics, e.g. Moving Average,  I want to compare
raw data and moving average in the same chart, but the API did not get raw data when using Advanced Analytics, so I cannot get both raw data and processed data in the same chart.

### Proposed Change
Add  switch in the ui, when switch is on,  add call API to get raw data.

**Comment by Deninc** [comment]
+1 this is much needed for showing trends. E.g. stock market, sales...
