### ISSUE TITLE
SQL Lab Query doesn't get reflected in chart

### ISSUE THREAD

**Issue by durchgedreht** [apache/incubator-superset#8898]
1. I go into SQL Lab and create a query. e.g. "SELECT * FROM data_table WHERE id > 10;"
2. Then I do save the query.
3. Clicking on 'run'.
4. On the data view click on 'explore'
5. Create a char with e.b. Bar Charts
6. Save chart as "MyChart"

THEN:

1. Open saved query and change it. e.g. "SELECT * FROM data_table WHERE id >999"
2. Save changed query
3. Reopen Chart
4. Data is same as before
5. Chart datasource is something like "foo@bar.com --queryname-FYzgGs0CD" 

### Expected results

I'd expect the chart reflects the changed query and doesn't do an 'in-time-smapshot'

OR

Another way to point to the 'original' query using a kind of pointer logic. 
(By the way - changing a Datasource to SQLLab Query seems non supported as well)

**Comment by villebro** [comment]
@durchgedreht are you using Redis to cache results?

**Comment by durchgedreht** [comment]
No, I'm running against Clickhouse directly.

**Comment by durchgedreht** [comment]
To be more precise: I can edit the query in the data source view within the chart and can see the changes are not reflected. I'm wondering why every query should be immutable bound to a chart? This way it's pretty hard to do changes upon the same query. Fixing an error will result in n changes. This seems unwanted as changes in the other data sources are also reflected - so why should SQL queries underneath a chart behave differently?

**Comment by villebro** [comment]
FYI I identified a bug (or more like an oversight) in the code that I've already fixed locally thanks to this ticket. Will do some more testing and put in PR in the coming days.

**Comment by durchgedreht** [comment]
Ok, cool! I'll keep an eye to the ticket so I will do some testing when done.

**Comment by tcopple** [comment]
Is this a bug? I thought this was intentional. I agree it's frustrating but I just assumed the "derived" queries created from SqlLab were intentional.
