### ISSUE TITLE
How change the sequence of table field of slice in dashboard 

### ISSUE THREAD

**Issue by lihemin** [apache/incubator-superset#890]

**Comment by mistercrunch** [comment]
The field order in the table view should match the order in the dropdown list. Is that not the case? Which version are you on?

**Comment by lihemin** [comment]
0.9.1         
the field order in the form of the  dashboard view

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 623 days. Feel free to comment and request for this issue to be reopened.
