### ISSUE TITLE
Starting up using docker-compose on Ubuntu fails

### ISSUE THREAD

**Issue by denkab** [apache/incubator-superset#8907]
Following instructions https://superset.apache.org/installation.html#start-with-docker

### Expected results

Following execution of "docker-compose up" command, for the container to be up and running.

### Actual results

:~/Projects/incubator-superset$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

#### How to reproduce the bug

Just been following the instructions at the URL above, step by step.

### Environment

(please complete the following information):

- superset version: latest on main branch
- python version: n/a
- node.js version: n/a
- npm version: n/a

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [n/a] I have checked the superset logs for python stacktraces and included it here as text if there are any. N/A - did not start!
- [n/a] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

:~/Projects/incubator-superset$ uname -a
Linux nm-VirtualBox 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

:~/Projects/incubator-superset$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

:~/Projects/incubator-superset$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

**Comment by nytai** [comment]
Have you tried upgrading docker-compose and/or docker to the latest versions?

**Comment by denkab** [comment]
yes

**Comment by craig-rueda** [comment]
Please upgrade to the latest docker-compose version. This combo is working for me:

docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8

**Comment by denkab** [comment]
Thank you, this was helpful. Pity docker-compose needs to be managed of APT toolchain, but that's neither here nor there.
