### ISSUE TITLE
function date_trunc(unknown, text) does not exist in Line Chart

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#8910]
When trying to create a line chart from a datasource I have uploaded (through CSV upload), I get the following error: 

> function date_trunc(unknown, text) does not exist LINE 2: DATE_TRUNC('day', created) AS __timestamp, ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.

Column details:
![image](https://user-images.githubusercontent.com/22456202/71677246-a70f0800-2d82-11ea-91bf-5dd3ae922100.png)

The column details and date format are exactly the same as the 'examples.birthnames' provided by Superset.  Why do I get an error? Database is Superset's own Postgres

**Comment by klazaj** [comment]
If I put the date column in `Parse Dates` field when importing the CSV, I do not get this error anymore.  
Maybe someone can elaborate why changing the column type manually results in an error?

**Comment by villebro** [comment]
@klazaj what database engine are you on?

**Comment by rumbin** [comment]
In my understanding Postgres tries to apply the date_trunc() function on a column with data type 'text', which will obviously fail.

If you check the column dtype of this table, e.g., using any DB explorer like pgadmin or DBeaver you will most likely see that it is of type text and not timestamp.

By adding the column to the Parse Dates list, you tell Superset (in fact, supposedly, Pandas' read_csv() function) to try to interpret the column as timestamp, which then leads to setting the correct dtype in the DB table.

**Comment by rumbin** [comment]
In my eyes this probably is the expected behaviour, at least from Superset's point of view.

The user might expect something different, perhaps.
