### ISSUE TITLE
How to increase the number of queries executing concurrently while loading dashboard?

### ISSUE THREAD

**Issue by ArvindRaj17** [apache/incubator-superset#8916]
I'm trying to run a dashboard with 12 slices. I noticed that only six slice queries are running concurrently. Is there any way to increase the number? Is there a way to run all the 12 slice queries at the same time?

**Comment by willbarrett** [comment]
The limit is the result of the browser's limit on concurrent requests to the same domain. At Preset we're considering a different architecture that will get around that limit, but this is well in the future at this point. For now, you can domain-shard your requests. If that sounds interesting, other contributors can speak more to how that's accomplished.

**Comment by ArvindRaj17** [comment]
Thanks for the response. I would love to know more about domain-sharding. 

I have another question. While using Oracle BI, I've never faced this limit issue. So, is this a limitation of Superset?

**Comment by willbarrett** [comment]
Hi @ArvindRaj17 this is a limit in Superset, given the way you've got it deployed currently. I believe @betodealmeida, @mistercrunch, or @john-bodley could provide more information on domain sharding.

**Comment by john-bodley** [comment]
@graceguo-supercat could you provide some context?

**Comment by ArvindRaj17** [comment]
Thanks, @willbarrett.

**Comment by ebogdanov** [comment]
we've solved this with enabling http2 on L7-balancer in face of superset
