### ISSUE TITLE
Allow creating datasources from a custom SQL query, when using the filter_values function. 

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [apache/incubator-superset#8921]
**Is your feature request related to a problem? Please describe.**
My problem arises when I want to create a chart that responds to filters in the dashboard in a customized way, making use of the templating engine and the filter_values() function. 
I usually know what SQL query I need, so I go to SQL Lab, write the query with the filter_values() function already included, and... no values are returned. I can't "explore" the results and create my chart!
What I usually do (which is what frustrates me) is: I create a version of the query which returns some results (with placeholder values for the filters), and then in the chart I edit my datasource and add all the filter_values() lines. 

**Describe the solution you'd like**
I would like it to be possible to add datasources directly from SQL code, with a better interface for changing these datasources (currently it's a tiny text box when I click the grey Datasource box in the Chart tab).
I would also like to be able to name these datasources something other than *null.my_username-query_name-random_string*.

**Describe alternatives you've considered**
An alternative would be allowing the user to "explore" queries that return no results directly from SQL Lab, because queries with the filter_values() function can only ever return results when inside a dashboard with the respective filters.  

**Additional context**
None.

**Comment by ogrehunter** [comment]
Very good feature indeed, I found myself cannot add tables from another schema on my database although the table can be accessed from SQL Editor. Maybe allowing to create data source from SQL Query should solve my problem.

**Comment by Provoo** [comment]
I don't understand why is so complicated to allow users, to create custom querys for present as a tables in multiples dashboards or even just only duplicate a virtaul datasource to change database a present multiplo charts. I have to create an entire dashboard with same graphs and the only diference is the Physical Table. I really like superset but has to much problems.
