### ISSUE TITLE
Please document how to configure external database for docker-based deployment

### ISSUE THREAD

**Issue by denkab** [apache/incubator-superset#8922]
### Motivation

Wish to try Superset deployed using docker-compose with Elasticsearch. Out of the box, Docker-based configuration does not include required dependencies for SQLAlchemy to parse elasticsearch+http:// URL, which ends up displaying error ""

### Proposed Change

Need guidance - please expand instructions or cross-link instructions into https://superset.incubator.apache.org/installation.html#start-with-docker

### New or Changed Public Interfaces

N/A - documentation only

### New dependencies

N/A

### Migration Plan and Compatibility

N/A

### Rejected Alternatives

Few clueless trial and error attempts to edit setup.py proven fruitless :)

**Comment by ebauch** [comment]
Also didn't get the docker image to work; installing in a python env worked pretty easily.

**Comment by mistercrunch** [comment]
Check out "how to extend this image" section at the bottom https://hub.docker.com/repository/docker/preset/superset

**Comment by cricket007** [comment]
@mistercrunch How about adding some build-arg / env var that does `RUN pip install [pypi-database-drivers...]`

Similar to [how I added this code for Apache Zeppelin interpreters](https://github.com/risdenk/apache-zeppelin-docker/pull/2/files#diff-3254677a7917c6c01f55212f86c57fbfR14-R19)
