### ISSUE TITLE
Editing an existing schedule for Chart Email Delivery breaks with an error

### ISSUE THREAD

**Issue by visakhmurukes** [apache/incubator-superset#8926]
Try to modify the schedule of a chart added for email delivery

### Expected results

The schedule will get modified based on given input

### Actual results

Getting below error

#### Screenshots

![supsersetsched](https://user-images.githubusercontent.com/14180077/71805878-ce1a5200-3080-11ea-9dff-70170245deab.png)

#### How to reproduce the bug

Go to Manage -> Chart Email Schedule
Click on edit  record option for an existing schedule
Modify the given schedule
On save you get error as given below

### Environment

(please complete the following information):

superset version: 0.33.0rc1
python version: 3.6.9

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by blcksrx** [comment]
Please Update your superset version and the error will be fixed!

**Comment by visakhmurukes** [comment]
> Please Update your superset version and the error will be fixed!

I updated. Now the above issue is gone. But instead lots of other functionalities are breaking
Like rendering chart, refreshing druid datasource etc
The error seems to be consistent and is in lines of the below

  **Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column metrics.is_restricted does not exist
LINE 1: ...type, metrics.description AS metrics_description, metrics.is...**

Looks like issue with metadata objects stored in sqlite

**Comment by blcksrx** [comment]
Actually because of you need to migrate you database to the latest version. Please be sure to follow the documentation

**Comment by visakhmurukes** [comment]
how to migrate the database to latest version?
Can you please point me to the correct documentation?
my superset instance is using postgre as the metadatastore

**Comment by blcksrx** [comment]
Please read this:
https://superset.incubator.apache.org/installation.html#upgrading

**Comment by visakhmurukes** [comment]
Ok. I finally created a new copy of the db after the upgrade and then it worked. Otherwise it was giving above error.
In my case the metadatastore was initially setup in postgre
