### ISSUE TITLE
how to add a New chart type

### ISSUE THREAD

**Issue by leesonwei** [apache/incubator-superset#8928]
**Is your feature request related to a problem? Please describe.**
https://Github.com/airbnb/superset/pull/3013

**Describe the solution you'd like**
I want to add chart type use echart, then i follow https://Github.com/airbnb/superset/pull/3013, but it did'nt work. some body can help me?

**Describe alternatives you've considered**
https://Github.com/airbnb/superset/pull/3013

**Comment by willbarrett** [comment]
Please fill out the full issue template so that the project maintainers can provide assistance.

**Comment by maltoze** [comment]
ref:
https://github.com/apache/incubator-superset/pull/8229
https://github.com/apache-superset/superset-ui-plugins/pull/202
