### ISSUE TITLE
Superset to use both Local authentication plus OAuth authentication 

### ISSUE THREAD

**Issue by MattSmith46** [apache/incubator-superset#8932]
Hello I have setup superset to authenticate with Auth0 over OAuth and everything working fine on that end. The question that I have is that while connecting with Auth0 is working well I'm not able to login as an administrator and make any administration changes. Wanted to know if there is a way to use both local login for the admin account and OAuth login for user accounts. Below is my current code.

**superset_config.py**
```
   ROW_LIMIT = 5000
   SUPERSET_WORKERS = 4
   SUPERSET_WEBSERVER_PORT = 8088
   import os
   import logging
   from flask_appbuilder.security.manager import AUTH_OID, AUTH_REMOTE_USER, AUTH_DB, 
   AUTH_LDAP, AUTH_OAUTH
   from custom_sso_security_manager import CustomSsoSecurityManager
   CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
   basedir = os.path.abspath(os.path.dirname(__file__))
  
   AUTH_TYPE = AUTH_OAUTH
   AUTH_USER_REGISTRATION = True
   AUTH_USER_REGISTRATION_ROLE = "Gamma"
  
   PUBLIC_ROLE_LIKE_GAMMA = True
  
   OAUTH_PROVIDERS = [{
     'name':'auth0',
     'token_key': 'access_token',
     'icon':'fa-google',
     'remote_app': {
         'consumer_key': '',
         'consumer_secret': '',
        'request_token_params': {
            'scope': 'openid email profile'
        },
        'base_url': '',
        'access_token_url': '/oauth/token',
        'authorize_url': '/authorize',
        'access_token_method':'POST',
    }
    }]
```
**custom_sso_security_manager.py**
```
     from superset.security import SupersetSecurityManager
     import logging
     
     logger = logging.getLogger('auth0_login')
     
     class CustomSsoSecurityManager(SupersetSecurityManager):
     
        def oauth_user_info(self, provider, response=None):
            if provider == 'auth0':
                res = self.appbuilder.sm.oauth_remotes[provider].get('userinfo')
                if res.status != 200:
                    logger.error('Failed to obtain user info: %s', res.data)
                    return
                me = res.data
                logger.debug(" user_data: %s", me)
                prefix = 'Superset'
                return {
                    'username' : me['email'],
                    'name' : me['name'],
                    'email' : me['email'],
                    'first_name': me['given_name'],
                    'last_name': me['family_name'],
                }

```

**Comment by imvemuri** [comment]
If you want to login as Admin then change the default role from 'Public' to 'Admin'. To do this add **AUTH_USER_REGISTRATION_ROLE = 'Admin'** in superset_config.py or config.py. Doing so, would register all new users as Admins. 
If you just want to change the permission of a single user then just update the corresponding user record in **ab_user_role** to admin role which I believe is mapped to 1.

**Comment by Ryouku** [comment]
I think this is more generalised request/question than just change the user role using DB. Most applications offers at least few sign-in methods - Google Auth, DB Auth and similar available at the same time.

What @MattSmith46 says is that he needs to have two of sign-in options available at the same time and the way superset is built - it does not allow this to happen using possible configuration options.

However, if you would create a few controllers and add routes/views to them, I think you would be able to have sign-in forms displayed. Not sure about the credentials/DB handling, but you can override the logic in your custom security_manager and explicitly define the logic for the DB Auth (as it is simple user/credentials check and authentication using `login_user(user)`.

**Comment by augier** [comment]
Also wondering the same. I'd like to be able to use OAUTH as primary mechanism but to also enable basic auth for some special users.

**Comment by nitacekarki** [comment]
Hello All,
I am unable to login via 0Auth, can you help me out?

**Comment by CaptainHoangLe** [comment]
Dear All ! 
Can i switch between 2 login methods in screen login ? Can you help me ,please? Thanks all

**Comment by Ryouku** [comment]
Hello @CaptainHoangLe,
Superset (it's a Flask backend in fact) provides tools (or code blocks if you will) to build an authorization system that you prefer. 

However, this is not a standard, pre-built solution and here you have to implement it yourself.

This is not a difficult task, you would be able to find on the Internets or SO something along the line "flask multiple sign-in options form", implement your custom security manager, create templates and you are good to go.

**Comment by CaptainHoangLe** [comment]
> custom security manager, create templates and you are good to go.

I am new bie. I am having trouble with how to pass AUTH_TYPE from choosing in jinja template to file config.py.
my template belows
![image](https://user-images.githubusercontent.com/53038465/114679757-a95a6300-9d36-11eb-8bcb-177abb71bdb5.png)
and i rended this template before login
![image](https://user-images.githubusercontent.com/53038465/114680031-f3dbdf80-9d36-11eb-85d0-464ef1a7f481.png)

**Comment by revkov** [comment]
Superset auth based on Flask-Appbuilder. According to Flask-Appbuilder [documentation ](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-methods) you can choose only **one** of five auth methods. Thus, you can't use both auth for example AUTH_DB and AUTH_OAUTH in Apache Superset.

**Comment by Mavyre** [comment]
Maybe adding Flask Multipass would help to add multiple authentication types?

**Comment by Negashev** [comment]
For gitlab oauth in helm
```
    configOverrides:
      ingress_proxy: |
        ENABLE_PROXY_FIX = True
        TALISMAN_ENABLED = False
      enable_oauth: |
        from flask_appbuilder.security.manager import (AUTH_DB, AUTH_OAUTH)
        AUTH_TYPE = AUTH_OAUTH
        OAUTH_PROVIDERS = [
            {
                "name": "gitlab",
                "icon": "fa-gitlab",
                "token_key": "access_token",
                "remote_app": {
                    "jwks_uri": "https://gitlab.SERVER/-/jwks",
                    "client_id": "CHANGE_ME_1",
                    "client_secret": "CHANGE_ME_2",
                    "api_base_url": "https://gitlab.SERVER/api/v4/user",
                    "client_kwargs": {"scope": "email openid read_user profile"},
                    "request_token_url": None,
                    "access_token_url": "https://gitlab.SERVER/oauth/token",
                    "authorize_url": "https://gitlab.SERVER/oauth/authorize"
                }
            }
        ]

        AUTH_USER_REGISTRATION = True
        AUTH_USER_REGISTRATION_ROLE = 'Admin'
        AUTH_ROLE_ADMIN = 'Admin'
      auth_manager: |
        import logging
        from superset.security import SupersetSecurityManager

        class GitlabSecurityManager(SupersetSecurityManager):
            def oauth_user_info(self, provider, response=None):
                logging.debug("Oauth2 provider: {0}.".format(provider))
                if provider == 'gitlab':
                        me = self.appbuilder.sm.oauth_remotes[provider].get('user').json()
                        logging.debug("user_data: {0}".format(me))
                        name = me['name']
                        first_name = ''
                        last_name = ''
                        if ' ' in name:
                                s = name.split(' ')
                                first_name = s[0]
                                last_name = s[1]
                        return { 'name' : me['name'], 'email' : me['email'], 'id' : me['id'], 'username' : me['username'], 'first_name': first_name, 'last_name': last_name}
        CUSTOM_SECURITY_MANAGER = GitlabSecurityManager
```

**Comment by musthak2** [comment]
Any solution for this ?
