### ISSUE TITLE
utf8mb4 support - german characters

### ISSUE THREAD

**Issue by PRamia** [apache/incubator-superset#8933]
### Environment

- superset version: 0.34.0
- python version: 3.6.9
- Running Superset with Docker Containers

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

**PROBLEM:** 

I cannot render properly the german characters öäü. The data comes from an external MySQL server with utf8mb4 encoding + collation utf8mb4_unicode_520_ci

my superset_config.py contains:
SQLALCHEMY_DATABASE_URI = 'mysql://root:@db:3306/superset?charset=utf8mb4'

into the docker-compose.yml file added the following command under mysql:
command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci

mysql> SHOW VARIABLES LIKE 'collation%';
+----------------------+------------------------+
| Variable_name        | Value                  |
+----------------------+------------------------+
| collation_connection | utf8mb4_general_ci     |
| collation_database   | utf8mb4_unicode_520_ci |
| collation_server     | utf8mb4_unicode_520_ci |
+----------------------+------------------------+
3 rows in set (0.00 sec)

mysql> SHOW VARIABLES LIKE 'character_set%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

Maybe somebody faced this problem before and could help me.

Thanks a lot!

**Comment by hossam-96** [comment]
Did you find a solution ?

**Comment by PRamia** [comment]
yes, it was a problem from the source db

**Comment by hossam-96** [comment]
> yes, it was a problem from the source db

okay thanks. the solution was actually to just add "?charset=utf8mb4" in the end of the SQLALCHEMY_DATABASE_URI
