### ISSUE TITLE
SQL Lab allows queries that have create temp table. However, explore errors out that "Create" is unexpected

### ISSUE THREAD

**Issue by sarithapodali** [apache/incubator-superset#8934]
SQL Lab allows queries that have create temp table. However, explore errors out that "Create" is unexpected.

### Expected results

Create charts using complex queries that have temp table creation. 

### Actual results

SQL Lab allows queries that have create temp table. However, explore errors out that "Create" is unexpected.

#### How to reproduce the bug

1. Go to SQL lab and write a query to create a temp table and write a join query using the temp table. Run query. It works.
2. Click on Explore.
3. See error : SQL compilation error - unexpected create

Is this a supported scenario yet? OR do I miss any configuration?

**Comment by willbarrett** [comment]
Apologies for the silence here - I'll see if I can reproduce this in the next few days.
