### ISSUE TITLE
The Time range Defaults BUG!

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#8936]
The Time range Defaults`s  "Last month"、“Last quarter”、“Last year”  have some bug!

### Expected results

 "Last month" ：2019-12-01 to 2019-12-31

### Actual results

 "Last month" ：2019-12-08 to 2020-01-08

#### Screenshots

![ss-time](https://user-images.githubusercontent.com/1625023/71946394-a81dba80-3204-11ea-9762-a8bd21f0dfe3.png)

- superset version: 0.35
- python version: 3.6、3.7
- node.js version:  v12.10.0
- npm version: 6.11.3

**Comment by ebauch** [comment]
I don't think that is a bug. The current behavior is what I would expect. It's a relative time span of one month, quarter, year taken from the current date: 

current date - time span (month, quarter, year,...)

**Comment by alexandrejuma** [comment]
A slightly different problem: The relative time picker (at least for the line chart) is not working correctly

It's 18h37 and I selected the last 10 hours. The calculated start/end is for yesterday. This doesn't seem the correct behaviour.

![Timepicker misbehaving](https://imgur.com/download/xGH70JT)

This is particularly grave for when you want to have real-time dashboards refreshing with, let's say, the last 8h of data.
