### ISSUE TITLE
Docker Superset doesn't have export Dashboard option

### ISSUE THREAD

**Issue by snv1995** [apache/incubator-superset#8937]
Hi

I m using superset by DOCKER i was to trying to export and import dashboard in superset , but superset doesn't have EXPORT dashboard option in superset which is running in docker.help me out in this or say how to export dashboard from superset.

**Comment by dpgaspar** [comment]
Hi @snv1995 what version or commit SHA are you using?

This issue was solve here: https://github.com/apache/incubator-superset/pull/8942
