### ISSUE TITLE
Superset Dashboard Loading Slow when Enable HTTPS

### ISSUE THREAD

**Issue by SyamprasadNakka** [apache/incubator-superset#8938]
Hello Team,

We have enabled HTTPS by running superset with GUNICORN server and observed the dashboard page is loading slow. It's taking around 10-15 Sec delay and loading the page. We didn't face this slowness issue when running the server with HTTP.

###Command used to run: 
gunicorn -w 10 --certfile /home/superset/ssl/companyname.crt --keyfile /home/superset/ssl/companyname.key -b 0.0.0.0:1574 --limit-request-line 0 --limit-request-field_size 0 superset:app

### Expected results

Dashboard page should load without any delay

### Actual results

Dashboard page is loading with 10-15 sec delay when enable https

#### How to reproduce the bug

1. Run superset with gunicorn server by using HTTPS
2. Click on any Dashboard from dashboard menu
3. Observe the page loading time
4. See the time lag.

### Environment

- superset version: `unofficial-superset==0.33.10402`
- python version: `python 3.7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
You will experience better performance by setting up NGinx on the machine and terminating SSL at the web server rather than the Python process. I would recommend setting up gunicorn to only listen on the local loopback and having NGinx proxy requests via localhost. I hope this helps!

**Comment by SyamprasadNakka** [comment]
Hello Willbarret,
Thanks for the update.

We have enabled CAS - SSO ([#968](https://github.com/dpgaspar/Flask-AppBuilder/pull/968/commits/2ee50b6eb84f0ae36967cce5148760e48b86c841)) and enabled the SSL through gunicorn server to work with HTTPS.

Currently we are not using nginx to terminate the SSL from gunicorn. Are there any steps needs to perform to work with both HTTPS and SSO along with nginx/apache httpd server?

Can you please provide any inputs.

Regards,
Syam

**Comment by willbarrett** [comment]
Hi @SyamprasadNakka - it appears I didn't see your message when I came through my inbox originally.

CAS - SSO should not have a problem with SSL termination at NGinx. Digital Ocean has a good walkthrough for setting up an NGinx proxy with SSL termination here: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04
