### ISSUE TITLE
connect clickhouse Password required for user default

### ISSUE THREAD

**Issue by ksice** [apache/incubator-superset#8953]
DB::Exception: Password required for user default (version 19.17.4.11 (official build))\n", "stacktrace": "Traceback (most recent call last):\n File "/usr/local/python3/lib/python3.7/site-packages/superset/views/core.py", line 1706,

**Comment by willbarrett** [comment]
Hi @ksice - please provide the version of Superset that you're running so that we can better help you out.

**Comment by akrus** [comment]
@willbarrett, I have the same problem, got Superset from git:
https://github.com/apache/incubator-superset/
Ref 7b11b44abe08c131fb9df6ec479ea29c24c784ec

Added to docker/requirements-extra.txt:
sqlalchemy-clickhouse

Then
# docker-compose up
