### ISSUE TITLE
jinja url_param in Sql_lab sql query not working

### ISSUE THREAD

**Issue by labelhero** [apache/incubator-superset#8962]
Unable to run query after passing url_param parameters to sql_lab query. Button does not do anything.

![image](https://user-images.githubusercontent.com/56454803/72317346-34413f00-3656-11ea-9493-6886e1792aea.png)

This functionality used to run in 0.28 version, however after upgrading to 0.35 it not running anymore.

Are these fields supposed to be pre-filled using url_param?

![image](https://user-images.githubusercontent.com/56454803/72317372-491dd280-3656-11ea-879d-a95a53f1b83e.png)

Can some one please help with this, if possible please post some examples on how to pass url_param in newer version.

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### How to reproduce the bug

1. Pass the table parameters in the url and sql query with url_param
2. All database,schema and table fields are supposed to be empty.
3. Click "Run query" button.
4. Nothing happens.

### Environment

(please complete the following information):

- superset version: `0.35.1`
- python version: `3.6`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
There was a fix related to `url_params` that was included in `0.35.1`, see #8536 . However, that particular PR focused on all other areas of Superset **except** SqlLab. I can look into this in the coming days.

**Comment by villebro** [comment]
This does appear to be a regression, not sure when it was introduced. I need to think about how to resolve this, as there are many potential solutions. Also, the (`url_params`) feature needs to be more thoroughly unit tested and documented going forward.

**Comment by pbgc** [comment]
> There was a fix related to `url_params` that was included in `0.35.1`, see #8536 . However, that particular PR focused on all other areas of Superset **except** SqlLab. I can look into this in the coming days.

@villebro I try to do exactly (I think...) of what it's shown in the PR and it does not work. url_params in the dashboard are not being passed to the chart and then to the datasource sql.
I'm on 0.35.2
