### ISSUE TITLE
[dashboard] metadata editing modal generates invalid dashboard url

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#8968]
Related to #8876.

### Expected results

Empty `slug` and save should work.

### Actual results

![wcP2m7fq5D](https://user-images.githubusercontent.com/27990562/72391765-fa6a4a00-36e2-11ea-89d6-6247ed530d5c.gif)

### Environment

(please complete the following information):

- superset version:  latest master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @suddjian

**Comment by suddjian** [comment]
😱thanks for catching!
