### ISSUE TITLE
Problem with rendering bar chart (refresh page is needed)

### ISSUE THREAD

**Issue by barmic12** [apache/incubator-superset#8970]
Hello everyone. With our team we've noticed a problem with bar chart rendering - after click Run Query there was nothing to display, although there was 198 rows:

![image](https://user-images.githubusercontent.com/5133050/72423215-2c7fb880-3784-11ea-8b05-65632d45f759.png)

When the page is refreshed (CTRL + R), the chart is displayed:

![image](https://user-images.githubusercontent.com/5133050/72424123-c3994000-3785-11ea-9fc2-d9e065861bed.png)

Behavior is the same on different computers and browsers. There is no errors in console.

### Expected results

Render the chart without refreshing the page.

### Actual results

Refresh page is needed to display chart

#### How to reproduce the bug

1. Go to chart editor
2. Generate bar chart '
3. Click Run Query - chart shouldn't be displayed.
5. Refresh the page (ctrl + r) - chart should be displayed

### Environment

- superset version: 0.999.0dev
- python version: Python 3.7.5
- node.js version: v12.12.0
- npm version: 6.11.3

**Comment by willbarrett** [comment]
Hi @barmic12 - thanks for your error report! Judging by the superset version number you have listed, it appears you're running your own build rather than one of the Apache releases. Do you happen to know the SHA from Superset that you're running? This will help us fix your issue. Thanks!
