### ISSUE TITLE
UI not working in docker production setup.

### ISSUE THREAD

**Issue by leninworld** [apache/incubator-superset#8975]
### Expected results

what you expected to happen.
After login with admin/admin for production docker running image, there is no menu/dashboard showing up. 

### Actual results

what actually happens.

Instead it shows up some blank page with a button.

#### Screenshots
 
![2020-01-15_12-45-48](https://user-images.githubusercontent.com/2639584/72469881-01ea2b80-3795-11ea-9e91-84d23f44b364.png)

#### How to reproduce the bug

1. changes in .env file as production for FLASK_ENV and SUPERSET_ENV.
2. run sudo SUPERSET_LOAD_EXAMPLES=yes docker-compose run --rm superset ./docker-init.sh
3. run sudo docker-compose up
4. go to the endpoint login page in the browser. Enter admin/admin. You can see a blank page with a button in it and nothing else.

### Environment
Latest from master branch

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Log attached below.

**Comment by gk1089** [comment]
I installed Superset from "bottoms up" in a Ubuntu 18.04 VM right now and can confirm about getting the same issue. Only I am not even getting to the login page. The console shows:
```
**superset run -p 8088 --with-threads --reload --debugger**
INFO:root:logging was configured successfully
 * Serving Flask app "superset" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:8088/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:logging was configured successfully
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 292-408-079
```
There is no relevant entry for superset in /var/log so I am not sure where to look for them.

**Comment by leninworld** [comment]
> I installed Superset from "bottoms up" in a Ubuntu 18.04 VM right now and can confirm about getting the same issue. Only I am not even getting to the login page. The console shows:
> 
> ```
> **superset run -p 8088 --with-threads --reload --debugger**
> INFO:root:logging was configured successfully
>  * Serving Flask app "superset" (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> INFO:werkzeug: * Running on http://127.0.0.1:8088/ (Press CTRL+C to quit)
> INFO:werkzeug: * Restarting with stat
> INFO:root:logging was configured successfully
> WARNING:werkzeug: * Debugger is active!
> INFO:werkzeug: * Debugger PIN: 292-408-079
> ```
> 
> There is no relevant entry for superset in /var/log so I am not sure where to look for them.

Is this also from master branch latest source code?

**Comment by DylanNWatt** [comment]
I also came across this, and after a long debugging session I walked away and it was working. I'm pretty sure it's just that you're able to access the webpage long before the npm installation process has completed. If you inspect the source of the returned page when it's in that, there are no script tags embedded. 

After waiting for about 15 minutes on a modern macbook pro, the logs progressed from `npm ci` step to the actual build, and it started working. The fix here is probably just not starting the web server until the build is complete, and adding more clear logging after `npm ci` of "Installing web dependencies, this may take a while"/

**Comment by gk1089** [comment]
> Is this also from master branch latest source code?
Yes. I pip installed using `git+https://github.com/apache/incubator-superset/`

**Comment by gk1089** [comment]
> 
> 
> I also came across this, and after a long debugging session I walked away, came back, and it was working. I'm pretty sure it's just that you're able to access the webpage long before the npm installation process has completed. If you inspect the source of the returned page when it's in that state, there are no script tags embedded.
> 
> After waiting for about 15 minutes on a modern macbook pro, the logs progressed from `npm ci` step to the actual build, and it started working. The fix here is probably just not starting the web server until the build is complete, and adding more clear logging after `npm ci` of "Installing web dependencies, this may take a while."

So what you are suggesting is that post installation, when I run with the command `superset run -p 8088 --with-threads --reload --debugger`, I should wait for 'some' time before I fire the link in the browser. My host machine is pretty powerful, but I am running this in a VM with 4 gigs of RAM and a couple of cores, so let us see how it fares against a dedicated machine like you said.

**Comment by gk1089** [comment]
I tried the suggestion made by @DylanNWatt and it still does not work for me after waiting for a good amount of time. Where exactly does superset log its events? And how do I turn the debug mode on when running the application?

**Comment by abdulganierkan** [comment]
@DylanNWatt's answer worked. You have to install npm dependencies for the client-side. Additionally, if you're using docker just do it for the related container like:
`docker exec -it incubator-superset_superset-node_1 sudo npm ci`
