### ISSUE TITLE
Chord Diagram get  Metric 'SUM(redu)' does not exist

### ISSUE THREAD

**Issue by hefeng11725** [apache/incubator-superset#8977]
chord diagram shows nothing when run query

### Expected results

something like the example picture

### Actual results

 get an error like this  
![image](https://user-images.githubusercontent.com/19297887/72489080-da0ace80-384d-11ea-8abb-38a609b695fa.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/19297887/72488929-6799ee80-384d-11ea-85fd-b83aedf7ca13.png)

- superset version: `Superset 0.34.0`
- python version: `Python 3.6.8`
- node.js version: `v10.14.1`
- npm version: `6.4.1`

**Comment by villebro** [comment]
What analytical database are you using? Are you also able to test a more recent version, e.g. `0.35.2`?

**Comment by mtomov** [comment]
Hi,

I'm getting the same error with latest 0.35.2 using Postgres. I actually can't do any metric other than `COUNT(*)`, and weirdly I can only do `COUNT(*)` if I choose it as a last option in the `Metric` dropdown, but not if I type it in.

![image](https://user-images.githubusercontent.com/1651750/74593493-556dc480-5034-11ea-89ef-0c5bf5426ab1.png)

^ This is the only option that works on the Chort Diagram Metric field

**Comment by villebro** [comment]
Thanks for testing on `0.35.2` @mtomov , I will look into this.

**Comment by mtomov** [comment]
Thank you!

**Comment by mtomov** [comment]
wow, that was unexpectedly quickly fixed! Thank you @villebro! Much appreciated
