### ISSUE TITLE
Error when run query from SQL Lab using json_agg/json_build_object

### ISSUE THREAD

**Issue by lxhoang97** [apache/incubator-superset#8978]
I need to run some query using json_agg/json_build_object in Postgres database, but I got an error
`pyarrow.lib.ArrowNotImplementedError: Not implemented type for list in DataFrameBlock: struct<table_name: string, database_id: int64>`

My query: 

> SELECT id, json_agg(json_build_object('table_name',table_name,'database_id',database_id)) FROM (SELECT * FROM tables) AS tables GROUP BY id

### Error details:

>ERROR:superset.sql_lab:Query 11: Not implemented type for list in DataFrameBlock: struct<table_name: string, database_id: int64>
Traceback (most recent call last):
  File "/app/superset/sql_lab.py", line 170, in get_sql_results
    log_params=log_params,
  File "/app/superset/sql_lab.py", line 391, in execute_sql_statements
    expand_data,
  File "/app/superset/sql_lab.py", line 291, in _serialize_and_expand_data
    df = result_set.to_pandas_df()
  File "/app/superset/result_set.py", line 152, in to_pandas_df
    return self.convert_table_to_df(self.table)
  File "/app/superset/result_set.py", line 129, in convert_table_to_df
    return table.to_pandas(integer_object_nulls=True)
  File "pyarrow/array.pxi", line 468, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1238, in pyarrow.lib.Table._to_pandas
  File "/usr/local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 704, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories)
  File "/usr/local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 976, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories)
  File "pyarrow/table.pxi", line 780, in pyarrow.lib.table_to_blocks
  File "pyarrow/error.pxi", line 86, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Not implemented type for list in DataFrameBlock: struct<table_name: string, database_id: int64>
 

#### Screenshots
![image](https://user-images.githubusercontent.com/52392577/72516132-c2e6d380-3883-11ea-8051-68a565631ac7.png)

### Environment

(please complete the following information):

- superset version: master branch
- python version: 3.6.9
- node.js version: 10
- npm version: 6.13.4

**Comment by dpgaspar** [comment]
Hi @lxhoang97,

Please update your issue with:

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

**Comment by graceguo-supercat** [comment]
I have seen similar error message, but caused by different data type: https://github.com/apache/incubator-superset/pull/8946#issuecomment-573261231
@robdiciuccio

**Comment by robdiciuccio** [comment]
I can reproduce the issue locally with the query provided. Arrow appears to [support struct types](https://issues.apache.org/jira/browse/ARROW-1705); the issue looks to be in the conversion to a pandas dataframe.

**Comment by robdiciuccio** [comment]
[This looks to be a fix in Arrow](https://github.com/apache/arrow/pull/6199), but it is not yet released. Trying to verify against master, but building Arrow on MacOS is turning out to be a pain. In the meantime, I'm going to open a PR to serialize nested data types as JSON strings. Not an ideal solution, but will buy us some time for a proper Arrow fix to be released. Also looking into solutions for bypassing Pandas altogether for SQL Lab in the long run.
