### ISSUE TITLE
Getting General Error <class 'sqlalchemy.exc.ProgrammingError'> error while deleting the chart

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#8987]
### Expected results
It should delete the chart
what you expected to happen.

### Actual results
Getting the error
what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/43033939/72819951-26ae3980-3c94-11ea-9624-fd10bb7b5030.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @umesh11111,

Please your post server logs and fill the environment info
