### ISSUE TITLE
how to- convert timestamp to date

### ISSUE THREAD

**Issue by eliab** [apache/incubator-superset#899]
hi brains
is there any way to convert timestamp to date?
I wanna create date filter, but have timestamp field 

10X

**Comment by georgeke** [comment]
What backend are you using? You can use a calculated column to cast your timestamp to a date. (Edit Table -> List Table Column -> (+) -> Put expression in "Expression"

**Comment by eliab** [comment]
great
do you know why I cant filter by this custom field? 

I get the following error:
![image](https://cloud.githubusercontent.com/assets/20900947/17518395/67f532ca-5e50-11e6-9376-23f95cca9880.png)

10x

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 621 days. Feel free to comment and request for this issue to be reopened.
