### ISSUE TITLE
Unable to explore data on sqllab because I keep getting "An error occurred while creating the data source"

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#8990]
Every time I try to explore the results of a query, I get "**An error occurred while creating the data source**".

Initially, this was working well but I tried it today and I cannot explore results from any queries.

### Expected results
To explore query results successfully.

### Actual results
 When I click on explore I get  An error occurred while creating the data source

#### How to reproduce the bug
1. Go to 'sql lab and run a query'
2. Click on 'explore'

### Environment
- superset version: `superset version`- 0.34.1
- python version: `python --version` 3.6.8
-Centos
-mysql database on cloud

### Additional context

![bug](https://user-images.githubusercontent.com/29142200/72892672-2bbcc880-3d28-11ea-89b3-fac74484224f.PNG)

**Comment by dpgaspar** [comment]
Hi @mashciku,

Please post you server logs at the time of the error

**Comment by mashciku** [comment]
@dpgaspar I have seen the error. It was a server issue that has been resolved.
