### ISSUE TITLE
[table vis] last column selected not shown

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#8994]
<img width="1670" alt="Screen Shot 2020-01-22 at 9 54 38 AM" src="https://user-images.githubusercontent.com/487433/72920052-5f362d80-3cfd-11ea-86db-44ab66d42efd.png">
When picking a set of columns in the `NOT GROUPED BY` control, all show up in the table except for the last one.

Also an issue, aggregate functions should not show up here, simply a list of columns. Seems like this should be using the `SelectControl`, and not the `AdhocMetricControl`

#### How to reproduce the bug
mimic screenshot

### Environment
latest `master`

**Comment by villebro** [comment]
.pinned
