### ISSUE TITLE
Nanosecond timestamp year range workaround

### ISSUE THREAD

**Issue by leoblue** [apache/incubator-superset#900]
Hi, pd timestamps are restricted to the years 1677-2262. It would be nice to allow different dates as well that go beyond this range. For instance, periodranges could be an alternative. That would allow graphing of longer timeseries plots.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 621 days. Feel free to comment and request for this issue to be reopened.

**Comment by mashbourne** [comment]
Throws (default): pd.to_datetime(datetime.date(2262, 4, 12),errors='raise')
Swallows: pd.to_datetime(datetime.date(2262, 4, 12),errors='coerce')

any chance we could change this to coerce?
