### ISSUE TITLE
not able to add the chart into the dashborads, which is created by another user in superset even for admin role  also i am not able to add the chart

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#9000]
### Expected results
we should be able to edit the chart which is creating by another user
what you expected to happen.

### Actual results
Not able to edit the chart
what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/43033939/72956492-e6e76f00-3dc5-11ea-81c3-c898183845f8.png)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@umesh11111 You should be able to make other users "owners" of your chart. If you visit `/chart/edit/<CHART_ID>` where chart id is the chart in question you should see a field for "Owners" where you can add other users

**Comment by mhakkiersoy** [comment]
Hi umesshh,

We have the same problem but a little bit different from yours. We have tried to add custom chart into superset library however we haven't had a satisfied result. Can you guide us how we can implement custom charts to superset from the beginning. This cause a huge problem for our running project.
