### ISSUE TITLE
[FEATURE-Request] Contextualization on filter_box

### ISSUE THREAD

**Issue by airliquide31** [apache/incubator-superset#9003]
**Motivation**

Allow contextual filter on filter-box to speed up drill down on data. 

Example when two filters (Compagny and Employee Name) are used try to get context from filter 1 to prefilter filter value2 (based on same dataset). 

When you select the compagny only have  Employee relevent to the copagny.

Many thanks for the already accomplish work.

**Comment by rumbin** [comment]
You can reach this behaviour by dividing the two filter columns into two different filter charts/slices on the same dashboard.
This way any selection from one filter chart will act in the other filter chart and vice versa.

**Comment by airliquide31** [comment]
That does the trick ! 
Awesome ! 

Many thanks !
