### ISSUE TITLE
can_list on UserOAuthModelView not added to Admin and Alpha when AUTH_TYPE = AUTH_OAUTH

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#9005]
### Expected results

A user with Admin (or Alpha) role logs in and then requests userinfo or the list of users via the paths `/users/userinfo/` or `/users/list/` and the relevant data is listed.

### Actual results

A user with Admin (or Alpha) role logs in and then requests userinfo or the list of users via the paths `/users/userinfo/` or `/users/list/` and the user is then
1.  redirected to `/login` (which is a problem because it should be `/login/<provider>`
1. the user see a the welcome screen
1. the requested userinfo or user list is not provided.

### Environment

(please complete the following information):

- superset version: `superset version` = Superset 0.35.1
- python version: `python --version` = Python 3.6.8
- node.js version: `node -v` = bash: node: command not found
- npm version: `npm -v` = bash: npm: command not found

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

#  stacktraces
```
[2020-01-23 18:59:24 +0000] [27934] [DEBUG] GET /users/list/
[WARNING:flask_appbuilder.security.decorators:decorators.py:128 -                wraps() ] Access is Denied for: can_list on: UserOAuthModelView
[2020-01-23 18:59:25 +0000] [27938] [DEBUG] GET /login/
[DEBUG:flask_appbuilder.security.views:views.py:631 -                login() ] Provider: None
[DEBUG:flask_appbuilder.security.views:views.py:633 -                login() ] Already authenticated Terrence Brannon
[2020-01-23 18:59:25 +0000] [27933] [DEBUG] GET /
[2020-01-23 18:59:25 +0000] [27933] [DEBUG] GET /superset/welcome
[2020-01-23 18:59:25 +0000] [27930] [DEBUG] GET /static/appbuilder/css/flags/flags16.css
```

- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by metaperl** [comment]
Oddly enough, in https://github.com/apache/incubator-superset/issues/8545 @qiuyuzhou was able to fix it by running `superset init` but that did not fix it for me.

**Comment by dpgaspar** [comment]
Try `flask fab create-permissions`, this may mean you have set `AUTH_TYPE` on superset_config.py without setting PYTHONPATH.

**Comment by metaperl** [comment]
> Try `flask fab create-permissions`, this may mean you have set `AUTH_TYPE` on superset_config.py without setting PYTHONPATH.

That command completed with `Created all permissions` but listing the roles does not show `UserOAuthModelView` on any role, including Admin.

**Comment by metaperl** [comment]
> Try flask fab create-permission

I think you presumed i was smart enough to know that

`export FLASK_APP=superset`

was needed first.

**Comment by metaperl** [comment]
> flask fab create-permissions

this did not add a `can list` permission. It added the following:
```
 can add on UserOAuthModelView, can delete on UserOAuthModelView, can edit on UserOAuthModelView, can show on UserOAuthModelView, can userinfo on UserOAuthModelView, can list on UserOAuthModelView, can download on UserOAuthModelView, userinfoedit on UserOAuthModelView, can list on RegisterUserModelView, can show on RegisterUserModelView, can delete on RegisterUserModelView
```

I then went to List Roles in the UI and typed in "can list" but only UserDBModelView comes up, not UserOAuthModelView.

**Comment by metaperl** [comment]
> it created a new role, that is named the same as the username who is configured as `admin` in `superset_config.py`.

This occurred because `AUTH_ROLE_ADMIN` is set to a particular username.
