### ISSUE TITLE
Retrieve the table names from the query

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#902]
There are multiple use cases:
- check permissions
- relate the queries to the tables used for query discovery
- have better audit trail
  
  Sqlparse provides the stream of tokens but don't provide the API to access the table names, more on it:
-  https://groups.google.com/forum/#!topic/sqlparse/sL2aAi6dSJU
-  https://github.com/andialbrecht/sqlparse/blob/master/examples/extract_table_names.py

Another approach would be to run the EXPLAIN on the sql statement (DB specific):
-  https://prestodb.io/docs/current/sql/explain.html
-  https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Explain

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 566 days. Feel free to comment and request for this issue to be reopened.
