### ISSUE TITLE
Internet Explorer 11 does not load Apache superset URL

### ISSUE THREAD

**Issue by MahsaSeifikar** [apache/incubator-superset#9022]
I run the apache superset on Centos 7 with a docker image. When I enter the apache superset URL in IE11 and the main page does not load after login!

(please complete the following information):

- superset version: `0.35.1`
- python version: `3.6`
- node.js version: `8.17`
- npm version: `6.13`

**Comment by keehl1213** [comment]
I got the same error.  Is there any solution?

**Comment by MahsaSeifikar** [comment]
@keehl1213 I haven't solved the problem yet!

**Comment by swanitzek** [comment]
Are there any information available what is required to get the Internet Explorer working with Superset?

**Comment by MahsaSeifikar** [comment]
@swanitzek If you find any please share here.

**Comment by SaiManojG** [comment]
are there any workarounds for the IE support?
please let us know @mistercrunch 

also did you find any way to support superset in IE..? @MahsaSeifikar  @swanitzek  @keehl1213

**Comment by keehl1213** [comment]
> I have to support superset in IE11, as there is no official way found, i have tried the below steps and still got no luck :(
> 
> 1. installed react-app-polyfill & babel-polyfill packages in (superset-frontend) and imported them at the very top in index files as below
> 
> import 'babel-polyfill';
> import 'react-app-polyfill/ie11';
> import 'react-app-polyfill/stable';
> 
> 1. added "not dead" in browserslist section in package.json (superset-frontend)
> 2. added target: "es5" in tsconfig.json (superset-frontend)
> 
> also builded the project with above changes and still iam not able to run superset in IE.
> 
> iam getting login screen and then after entering the login credentials, iam getting infinite loading screen and an error stating "Expected :" from welcome.**hash**.entry.js
> 
> please let us know if there any workarounds for the IE support? @mistercrunch
> 
> also did you find any way to support superset in IE..? @MahsaSeifikar @swanitzek @keehl1213
> 
> Thanks in advance..

I finally gave up supporting IE11 and legacy Edge because of this [announcement](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666).
I suggest you only support chromium-based Edge since IE11 and legacy edge both have security problems.
