### ISSUE TITLE
databaseview/add should allow customization of the extras attribute via superset_config.py

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#9029]
**Our feature request is related to this problem:**
When adding a database via **Sources -> Databases -> Add** (`databaseview/add`), we have a need to supply a different set of default values for the "Extra" parameter.

However, the current code does not allow for customization/override of [the `superset.models.core.Database.extra` parameter](https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L125).

**A solution I'd like**
I would like to be able to provide a dictionary in `superset_config.py` that is converted to a json string (since this is the format of the current `extra` parameter).

**Additional context**
Functionality is already in place for `superset_config.py` to override the `excrypted_extra` parameter:
https://github.com/apache/incubator-superset/blob/master/superset/models/core.py#L138

# FUTURE SCOPE (not for this ticket)

Currently the user has to develop a SQLAlchemy string without a helper or wizard. This makes it impossible to program a set of `extra` parameters as a function of the type of connection being created.

It is well within reason to presume that the default `extra` parameters will vary as a function of the database being added.

However, for the time being, it is good enough that we simply be able to override/customize the default extra parameters.

**Comment by nytai** [comment]
@metaperl seems like you have a fairly good grasp of the work involved here, think you can turn it into a PR?
