### ISSUE TITLE
Add support for cockroach db

### ISSUE THREAD

**Issue by derari** [apache/incubator-superset#9032]
I use superset on a cockroach DB. After installing [the SQLAlchemy module](https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/), setup of the database was no problem.

However, I cannot pick time granularity for charts as they are "defined  per database engine in the superset source code".

Since cockroach is a Postgres database, implementing this should be as simple as just making the existing Postgres time grain configuration available for cockroach.

**Comment by villebro** [comment]
@derari , you need to create a new file `superset/db_engine_specs/cockroachdb.py`, where you specify any quirks that the cockroach dialect may have. I would start by extending `PostgresEngineSpec` from `superset/db_engine_specs/postgres.py` and making any necessary modifications. If you open up a PR I will be happy to help work out any problems you may encounter.
