### ISSUE TITLE
Username/Password doesn't work on docker image

### ISSUE THREAD

**Issue by jbs123** [apache/incubator-superset#9037]
### Expected results
Expected the username/password to be admin/admin according to the docker-init.sh file.
"Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )"

### Actual results

Access Denied

#### How to reproduce the bug

1. Fresh install using the instructions here: https://superset.incubator.apache.org/installation.html
2. After the docker image builds, go to the UI to log in. 
3. Denied

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
You can stop and do another doocker-compose up, the admin/admin will work then you have the issues: You don't have the necessary permissions to load dashboards. Please contact your administrator.
* After restarting four times, it finally works. FYI, updating as I test it.

**Comment by willbarrett** [comment]
Hi @jbs123, thanks for submitting a bug report. Can you share the SHA or release you were working with when you experienced this issue? We know that the docker build is lengthy. It's likely that the system failed at one point or another along the way and that the restarts eventually caused the initialization steps to converge. Any specific error messages you encountered along the way would be very helpful in finding the source of the issues.

**Comment by panesofglass** [comment]
I experienced the same issue. I was running commit 4485800e2118f8bc1424bdf67d2200eb5f0056ac.

**Comment by nwa2018** [comment]
The same here，I was running commit [8a3c99b](https://github.com/apache/incubator-superset/commit/9d3da79c4bf8b23b3ac7bf2f5093f01698a3c99b).
