### ISSUE TITLE
View Icon gone from Chart, Table, Dashboard CRUD Views

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#9039]
The magnifying glass view icon is gone from the CRUD views now, is this intended?

### Expected results
To see these three icons:
![image (4)](https://user-images.githubusercontent.com/7409244/73314148-ee51b280-41e1-11ea-821d-30744bcbb44e.png)

### Actual results
Only see two icons:
<img width="151" alt="Screen Shot 2020-01-28 at 3 20 24 PM" src="https://user-images.githubusercontent.com/7409244/73314158-f7428400-41e1-11ea-9111-d1541c6087e2.png">

#### How to reproduce the bug

1. Go to the Charts CRUD view
2. Don't see any view icons

### Environment

- superset version: `master

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

to: @mistercrunch @nytai 
cc: @john-bodley

**Comment by nytai** [comment]
Looks like that change was introduced by: https://github.com/apache/incubator-superset/pull/8960

**Comment by mistercrunch** [comment]
The change was intended. I didn't think these views were actually useful / used. Curious about the use cases...

**Comment by john-bodley** [comment]
@mistercrunch a document writer at Airbnb raised the issue. It seems we should try to ensure the CRUD views remain consistent (and inline with the documentation) until they're replaced with @nytai's React components.

**Comment by thunter009** [comment]
> The change was intended. I didn't think these views were actually useful / used. Curious about the use cases...

I have occasionally used these views when I am trying to find all the related charts to a specific table so I can delete it from the database.

**Comment by john-bodley** [comment]
I agree with @thunter009. The show option provides additional context and is often more performant that edit for gathering relevant metadata.
