### ISSUE TITLE
Allow environment variables for sqlalchemy uri

### ISSUE THREAD

**Issue by gbrian** [apache/incubator-superset#9045]
**Is your feature request related to a problem? Please describe.**
When deploying to multiple environments we'll like to be able to switch database connection.
Currently we have one script fixing database sqlalchemy uri

**Describe the solution you'd like**
Allow the use of environment variables as the value of `sqlalchemy_uri` property of `Database`

**Describe alternatives you've considered**
None yet

**Additional context**
We deploy using docker

**Proposal**

    class Database(Model, AuditMixinNullable, ImportMixin):
    ....
    allow_env_for_uri = Column(Boolean, default=False)
    ....
    @property
    def expanded_sqlalchemy_uri(self):
        if self.allow_env_for_uri:
            return os.path.expandvars(self.sqlalchemy_uri)
        return self.sqlalchemy_uri
    
    @property
    def sqlalchemy_uri_decrypted(self):
        conn = sqla.engine.url.make_url(self.expanded_sqlalchemy_uri)
        if custom_password_store:
            conn.password = custom_password_store(conn)
        else:
            conn.password = self.password
        return str(conn)

**Comment by willbarrett** [comment]
@gbrian you are free to extend the Python configuration as described in [the documentation] https://superset.apache.org/installation.html#configuration - as the configuration is a Python file, it is possible to tell Superset to look for environment variables for any configuration option. I hope this approach will work for you!

**Comment by mistercrunch** [comment]
@willbarrett,  @gbrian is not referring to `SQLALCHEMY_DATABASE_URI`, but to the ones ones that we encrypt and store in the database.

I'm not sure how well that is documented, but with `DB_CONNECTION_MUTATOR` (a configuration hook) you can intercept the `Database` at runtime and do whatever, meaning you can put in bogus username/password in the database, and your `DB_CONNECTION_MUTATOR` function can read an env var and replace the proper value.

```python
def DB_CONNECTION_MUTATOR(sqlalchemy_url, params, effective_username, security_manager, source):
    # Assuming that by convention your `sqlalchemy_url` references the env var you want to use
    sqlalchemy_url = os.environ.get(sqlalchemy_url)
    return sqlalchemy_url, params
```

**Comment by gbrian** [comment]
Thanks @willbarrett , @mistercrunch.
I implemented differently as wanted to have a flag on database connection to set if ENV replacement should apply but reconsidering in favor of:  DB_CONNECTION_MUTATOR and SQL_QUERY_MUTATOR
