### ISSUE TITLE
documentation outdated

### ISSUE THREAD

**Issue by dataf3l** [apache/incubator-superset#9067]
The documentation reports a superset.create_app, which doesn't exist.
documentation should be updated to superset.app instead of create_app

**Comment by mistercrunch** [comment]
Versioned docs here: https://readthedocs.org/projects/apache-superset/

`create_app` exists in current `master`, and probably `0.35.2` as well. `superset.apache.org` should be the docs as of latest release (0.35.2)

**Comment by mistercrunch** [comment]
Made versioned docs discoverable here https://github.com/apache/incubator-superset/pull/9069
