### ISSUE TITLE
CELERYBEAT_SCHEDULE not registering tasks for email reports

### ISSUE THREAD

**Issue by yatin-kapur** [apache/incubator-superset#9079]
CELERYBEAT_SCHEDULE doesn't seem to get triggered when trying to queue email report requests. 

My docker-entrypoint.sh has all three of these commands:

```
celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair &
celery worker --app=superset.tasks.celery_app:app --pool=prefork --loglevel=info -O fair -c 4 &
celery beat --app=superset.tasks.celery_app:app --loglevel=info &
```

### Expected results

I have a task that should run every two seconds, and have created that task in schedules.py just like the email report, but neither of them work.

### Actual results

The celery beat logs don't seem to show anything.

### Environment

(please complete the following information):

- superset version: `superset version` 0.34
- python version: `python --version` 3.6
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jackyq2015** [comment]
You can set celery beat logs level to debug.

Also, can you please post the change you made?

**Comment by yatin-kapur** [comment]
Forgot to update this thread, but can close the issue now. I was writing to the incorrect superset_config.py file so my settings were getting overwritten.
