### ISSUE TITLE
Superset clipboard contents should paste nicely in Excel

### ISSUE THREAD

**Issue by rubypollev** [apache/incubator-superset#9080]
**Is your feature request related to a problem? Please describe.**
Clipboard contents from Superset paste as on one like in Excel. That's kind of frustrating. Copying tabular content from SQL Lab should paste nicely into a tabular program like Excel or Google Sheets. 

**Describe the solution you'd like**
Described the outcome above. The work might be as simple as swapping out a character or two. Not sure.

**Comment by suddjian** [comment]
This seems like a good idea to me. I should note that you can save query results as a CSV, which can be opened in Excel. But that's not very convenient if you just want to quickly copy/paste a portion of the results.

Right now results are rendered as `<div>`s. I'm not very familiar with how copy-pasting formatted data works, but I would think using proper HTML `<table>` tags would do the trick.

Changing to `<table>` is a bit tricky though, as we're using [react-virtualized](https://github.com/bvaughn/react-virtualized) to render the table for performance. It looks like the `Grid` component is being used for this, but I'm not sure if there is a `react-virtualized` component that allows rendering to a `<table>`.

**Comment by suddjian** [comment]
This could also be done via JS event handlers on the [copy](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) event. We could manually insert a `text/html` formatted entry into the clipboard, but it would be very tricky to make sure we get the selection right and strikes me as a very bug-prone solution.
