### ISSUE TITLE
Error while Connecting to Snowflakes

### ISSUE THREAD

**Issue by saurabhperiwal** [apache/incubator-superset#9083]
I'm trying to connect to snowflakes. After entering SQLAlchemy URI, I get  error

### Expected results

Test connection should be successful

### Actual results

It throws an error
`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:snowflake", "stacktrace": "Traceback (most recent call last):\n  File \"/app/superset/views/core.py\", line 1358, in testconn\n    engine = database.get_sqla_engine(user_name=username)\n  File \"/app/superset/utils/core.py\", line 131, in __call__\n    value = self.func(*args, **kwargs)\n  File \"/app/superset/models/core.py\", line 318, in get_sqla_engine\n    return create_engine(sqlalchemy_url, **params)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py\", line 479, in create_engine\n    return strategy.create(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 61, in create\n    entrypoint = u._get_entrypoint()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/url.py\", line 172, in _get_entrypoint\n    cls = registry.load(name)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 240, in load\n    \"Can't load plugin: %s:%s\" % (self.group, name)\nsqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:snowflake\n"}
`
#### How to reproduce the bug

1. Use docker image to run superset
2. Login -> Sources -> Databases -> Add Database enter URI in SQLAlchemy URI 

### Environment

(please complete the following information):

- superset version: `0.999dev`
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Hi. It appears that you are missing the optional Snowflake SQLAlchemy package. You can fix the issue by running `pip install snowflake-sqlalchemy` in your execution context. Many database driver packages are optional due to a few reasons. One common one the licensing of the driver being incompatible with Apache's guidelines in some instances. Another is a desire to keep our base installations small - it is expected that users will choose the drivers appropriate for their installation. Thanks for opening this issue!

**Comment by salano21** [comment]
I have installed  `snowflake-sqlalchemy` dependency still not able to connect 
```
superset_app            | snowflake.connector.vendored.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='%7brl52352%7d.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=5b3581cb-e30e-450e-be62-e2e8e4d53721&databaseName=dev_db&request_guid=f1df6bd8-90de-4df9-a308-983bcb3afe4c (Caused by NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7f476c0783d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
