### ISSUE TITLE
Unable to run apache superset with https

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#9089]
I am trying to configure SSL for superset on apache. However, my setup doesn't work. I am running superset locally on port 9020, but since I can't bind apache on the same port I have configured SSL for the UI on port 8080 with a proxy pass that forwards requests locally to port 9020.
Currently, any requests to mysuperset:9020 fail with the 404 error: The plain HTTP request was sent to HTTPS port, but after a few attempts of forcing https it finally redirects to the superset login page.
### Expected results
mysuperset:9020 should redirect successfully to https

### Actual results
HTTP error 404: The plain HTTP request was sent to HTTPS port

#### Screenshots
![bug1](https://user-images.githubusercontent.com/29142200/73825728-93394480-480d-11ea-9c52-16d1d1b0bc9e.PNG)

### Environment
superset version: 0.34
python version: 3.6
aws centos 7 ec2 instance
ELB configured

### Logs

2020-01-31 07:01:46,187:INFO:werkzeug:10.100.4.34 - - [31/Jan/2020 07:01:46] "GET / HTTP/1.1" 302 -
2020-01-31 07:01:48,897:INFO:werkzeug:10.100.4.34 - - [31/Jan/2020 07:01:48] "GET /superset/welcome HTTP/1.1" 302 -
2020-01-31 07:01:58,855:INFO:werkzeug:10.100.3.150 - - [31/Jan/2020 07:01:58] "GET / HTTP/1.1" 302 -

**Comment by willbarrett** [comment]
Hi @mashciku - this looks like an issue with your Apache setup. I'd recommend looking at documentation on setting up a Python-based web application under the webserver using GUnicorn.
