### ISSUE TITLE
SQL Lab editor cursor position is incorrect in Safari

### ISSUE THREAD

**Issue by bradgessler** [apache/incubator-superset#9095]
When I type a SQL query in SQL Lab with the latest version of Safari Version 13.0.5 (15608.5.11), the cursor doesn't lineup with where I'm actually typing.

### Expected results

I expect the cursor to remain at the end of the line while I'm typing.

### Actual results

The cursor slowly starts to fall behind in Safari as I type.

#### Screenshots

A video of the issue may be watched at https://s3.amazonaws.com/bradgessler/Screen-Recording-2020-02-06-at-10.29.14-Z2v0KXdYZrAp.mov

#### How to reproduce the bug

1. Using the latest version of Safari, go to `/superset/sqllab`
2.Begin typing a query, keep typing at least 40 chars
3. Observe the cursor fall behind

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This use to be an issue in Firefox and Chrome, but before submitting this bug I verified this is no longer a problem in those browsers.

**Comment by etr2460** [comment]
This looks like a bug in Safari because when keywords are getting bolded, they slightly increase in width but the cursor doesn't move with them. We don't really support Safari that well, so I might recommend using Chrome or Firefox as I can't guarantee that this issue will get attention very quickly

**Comment by etr2460** [comment]
Maybe @willbarrett could take a look though, is Preset planning on supporting Safari?

**Comment by willbarrett** [comment]
I'll redirect that question to @rusackas who's more front-end focused than myself :)

**Comment by rusackas** [comment]
Wow, that looks completely infuriating. I'll try to replicate/fix asap.

**Comment by LuPan2015** [comment]
I have the same problem with superset 1.4.0.

**Comment by chintanp** [comment]
I am facing this issue on Google Chrome and Firefox, Superset 2.0.0. Renders it impossible to use.
