### ISSUE TITLE
Connecting to Elsaticsearch

### ISSUE THREAD

**Issue by GouthamanAsokan** [apache/incubator-superset#9104]
Have been trying to elasticsearch thru superset
I typed in SQLAlchemy URI as
elasticsearch+http://[username]:[password]@localhost:9200/
is this is the correct syntax because it tells the connection seems ok but the tables are not showing,what can be done
Also,what happens when we give the mapping in addition like 
elasticsearch+http://[username]:[password]@localhost:9200/monthly

**Comment by dpgaspar** [comment]
Hi,

Please post the output from:
`curl -u username:password http://localhost:9200/_cat/indices`

**Comment by GouthamanAsokan** [comment]
green  open .apm-agent-configuration PagMWp9kR4Sw0F2VPx4Zxw 1 0     0 0    283b    283b
yellow open monthlydate              KRMZ77s1Q3aq9OxOSg8rYA 1 1     0 0    283b    283b
green  open .reporting-2020.02.02    27fHmtIITIS4pj1mz_hzBw 1 0     1 0 407.7kb 407.7kb
green  open .kibana_1                si-Se2tKQ46authC3xy5XA 1 0     7 0  22.4kb  22.4kb
yellow open movies                   ArWlVhksQ9e2ISyuMJhqzg 1 1     0 0    283b    283b
green  open .kibana_task_manager_1   uIOLevlbTvK1JJjF5Boghg 1 0     2 0  12.5kb  12.5kb
yellow open apache_superset          YGQvuDmET4KxJt2xliIrxw 1 1     0 0    283b    283b
yellow open daily                    iYCHZLO2TUSJhnGfjZtLOw 1 1     0 0    283b    283b
yellow open monthggd                 WDp-DfRQTxm7MVbKhNyrkg 1 1     0 0    283b    283b
yellow open monthly                  LocrDyBrTKyOvOZFxgga2g 1 1 10102 0   1.6mb   1.6mb
yellow open monthly_table            9XBpKMDhQrmKY4P_xzZwMA 1 1     0 0    283b    283b
yellow open monthlydd                Pkyd32tmQB-FKGeF2M7tHQ 1 1     0 0    283b    283b
yellow open monthly_date             Fh5H1SzlTbOqmNH6R429Lw 1 1     0 0    283b    283b
yellow open table                    sTBFZmIqQAGbQZIs3wBpEw 1 1     0 0    283b    283b

**Comment by dpgaspar** [comment]
This is probably because all your non internal indexes are on a yellow state.
You can check what elasticsearch will recognize has "tables" by issuing the following command:

POST /_sql?format=txt
{
    "query": "SHOW TABLES'"
}

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-syntax-show-tables.html#sql-syntax-show-tables
