### ISSUE TITLE
I can not start superset

### ISSUE THREAD

**Issue by junwansas** [apache/incubator-superset#9105]
I get everything installed. and run ./superset run -p 8088 --with-threads --reload --debugger

Get this response.

[root@dvtcbddd951 bin]# ./superset run -p 8088 --with-threads --reload --debugger
2020-02-09 16:34:22,553:INFO:root:logging was configured successfully
2020-02-09 16:34:22,633:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-02-09 16:34:23,564:INFO:werkzeug: * Running on http://127.0.0.1:8088/ (Press CTRL+C to quit)
2020-02-09 16:34:23,564:INFO:werkzeug: * Restarting with stat
2020-02-09 16:34:24,450:INFO:root:logging was configured successfully
2020-02-09 16:34:24,529:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2020-02-09 16:34:25,460:WARNING:werkzeug: * Debugger is active!
2020-02-09 16:34:25,470:INFO:werkzeug: * Debugger PIN: 554-599-075

But When I go to http://myservername:8088/
I did not get anything.

Did I missing anything? Where is the log for superset? I can not find the log file. I have downgrade werkzeug to 0.16.0 and the python version is 3.7.6

my os is RHEL Red Hat Enterprise Linux Server release 7.4 (Maipo).

I installed the python in a different location /opt/software/hadoop/p376 and did make altinstall

Thank you!

Jun

**Comment by dpgaspar** [comment]
Hi,

127.0.0.1 is localhost so your server is listening on the loopback interface. Try:

`superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger`

Note: that this way of running superset is for development, do not use it in production

**Comment by junwansas** [comment]
Any instruction on production? That will be my next step if I can fix this problem.

Thank you!

Jun Wan
Enterprise Data Services
O 404.269.6804
C 404.625.2056
CTECHA.5. 112E
6305 Peachtree Dunwoody Rd. Atlanta, GA 30328
[signature_976828730]<https://www.cox.com/>

**Comment by junwansas** [comment]
It looks like working now but the -h has to be an ip address. Is it possible to run on a dns name? like servername.cox.com? I have the servername in our dns server. But I used that servername in -h option to start superset. It did not go through. Did I missing anything?

Jun Wan
Enterprise Data Services
O 404.269.6804
C 404.625.2056
CTECHA.5. 112E
6305 Peachtree Dunwoody Rd. Atlanta, GA 30328
[signature_976828730]<https://www.cox.com/>

**Comment by dpgaspar** [comment]
Superset is just a flask app, you can read: https://flask.palletsprojects.com/en/1.1.x/deploying/
