### ISSUE TITLE
UI won't load

### ISSUE THREAD

**Issue by Taki-Eddine** [apache/incubator-superset#9108]
I am using the docker image to use Apache superset, I followed the instructions.
I cloned the git repository then a docker-compose up
 

### Expected results

The UI to load

### Actual results

The UI won't load, here is a screenshot
![Screenshot from 2020-02-10 17-32-07](https://user-images.githubusercontent.com/20522687/74169284-5c0ecd00-4c2b-11ea-997c-8e13d9b4996b.png)

#### How to reproduce the bug
I followed the instructions to use the docker image.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [* ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ *] I have reproduced the issue with at least the latest released version of superset.
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

the docker logs show that incubator-superset_superset-node_1 fails to cd into /app/superset-frontend/, I am getting the following error message:
`superset-node_1    | bash: line 0: cd: /app/superset-frontend/: No such file or directory`

The problematic instruction lies in the docker-compose.yml file; line 69:

`    command: ["bash", "-c", "ls /app/ && cd /app/superset-frontend/ && npm install && npm run dev"]
`

**Comment by IndexOutOfRange** [comment]
Hello, what is the url address you are accessing in your browser ? looks like you are trying to connect to the flask server directly and not the node one.

**Comment by Taki-Eddine** [comment]
> Hello, what is the url address you are accessing in your browser ? looks like you are trying to connect to the flask server directly and not the node one.

@IndexOutOfRange  I am accessing it using localhost:8088 as specified in the doc. I am being prompted a login page then when I enter creds (admin:admin) I get the page I showed in the screenshot. I believe that `superset-node_1` was not able to load the UI.

**Comment by IndexOutOfRange** [comment]
what's the result of accessing superset through port 9000 ?

**Comment by Taki-Eddine** [comment]
> what's the result of accessing superset through port 9000 ?

I am unable to connect. Nothing is listening on 9000 I think.

**Comment by vikt0rs** [comment]
I've got the same issue after installation inside the virtualenv according to the manual [0]. Service was run as `superset run -p 8088 --with-threads --reload --debugger`
I've had to checkout to tag `0.35.2` to get rid of this
 
[0] - https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization

**Comment by Taki-Eddine** [comment]
Fixed by  #9114. Thanks

**Comment by jmmadsen** [comment]
I am getting the exact same issue as the original poster, following the same steps. I am running on Mac OS X, and have upped my Docker RAM to 6GB.

Does anyone know what causes the UI to fail to load?

```superset_app             | 172.20.0.1 - - [22/Sep/2020 14:17:24] "POST /login/ HTTP/1.1" 302 -
superset_app             | INFO:werkzeug:172.20.0.1 - - [22/Sep/2020 14:17:24] "POST /login/ HTTP/1.1" 302 -
superset_app             | 172.20.0.1 - - [22/Sep/2020 14:17:24] "GET / HTTP/1.1" 302 -
superset_app             | INFO:werkzeug:172.20.0.1 - - [22/Sep/2020 14:17:24] "GET / HTTP/1.1" 302 -
superset_app             | 172.20.0.1 - - [22/Sep/2020 14:17:25] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | INFO:werkzeug:172.20.0.1 - - [22/Sep/2020 14:17:25] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | 172.20.0.1 - - [22/Sep/2020 14:17:25] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app             | INFO:werkzeug:172.20.0.1 - - [22/Sep/2020 14:17:25] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -```

**Comment by DarwinDennis003** [comment]
ERROR : 8Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' 'strict-dynamic' 'nonce-UMC4d_d8VXZtjXJ6PbucVtBTB51Zvxv-'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Got this while running frontend on 9000 . Try set CSF config false . still persists ,

**Comment by luis-fnogueira** [comment]
I had the same issue following the same steps. Unfortunately I had do uninstall Superset and use another dataviz due to urgency.

**Comment by DarwinDennis003** [comment]
Use node version v20.9.0.
Helps in my case for the same

**Comment by wangyequn** [comment]
Currently, I am also encountering the same issue. Could you please share how you resolved it?

**Comment by DarwinDennis003** [comment]
Try switch node latest version and check whether the backend service receiving the api calls.

**Comment by vikashrajgupta** [comment]
@DarwinDennis003 - I have upgraded the node as well but still getting the error 
![Screenshot from 2024-04-04 18-45-35](https://github.com/apache/superset/assets/40394708/9e944074-3cbb-42b4-9124-e3d8d0386a69)

The main point is I'm getting this CSP violation issue only when I'm using the domain name, without the domain it's working fine.
For example I'm running this on localhost:9888 and whenever I'm using this via domain it showing CSP error.
That would be great if you can help!!

**Comment by Mehdi-YC** [comment]
Hello, i'm a bit late here but i wanted to tell you, after you start the superset server with docker-compose it will take a while to really "start"

![Image](https://github.com/user-attachments/assets/c9737e27-b61f-44b7-8b7a-c21380a1e69b) jest be patient, after like 5 mins you will see this, and after it , the Ui will load
