### ISSUE TITLE
Superset-node docker compose fails to create container

### ISSUE THREAD

**Issue by psiegrist** [apache/incubator-superset#9112]
Docker-compose off of the master branch fails to launch the superset-node container with `No such file or directory`

### Expected results
Superset-node container starts with docker-compose. 

### Actual results

Superset-node container does not start with docker-compose. 

The docker error is bash: line 0: cd: /app/superset-frontend: No such file or directory
Seems like this commit may have caused the problem:
291306392 (David Aaron Suddjian 2020-02-09 17:53:56 -0800 69)     command: ["bash", "-c", "cd /app/superset-frontend && npm install && npm run dev"]

#### How to reproduce the bug
git clone https://github.com/apache/incubator-superset/
docker-compose up

### Environment
Ubuntu 18.04.3 - AWS

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by suddjian** [comment]
Can you try running `docker-compose build` first?

**Comment by suddjian** [comment]
Delving further into this, I've discovered a related issue with the Dockerfile: some files are not being copied at the correct times from the correct places. I'll have a fix up soon. `docker-compose build` or `docker-compose up --build` will still be necessary after the fix.
