### ISSUE TITLE
Empty screen after docker-compose build & up

### ISSUE THREAD

**Issue by l1x** [apache/incubator-superset#9116]
Superset is not starting up properly after docker-compose build & up

### Expected results

Get a working Superset.

### Actual results

Empty screen.

#### Screenshots

<img width="552" alt="Screenshot 2020-02-11 at 14 37 44" src="https://user-images.githubusercontent.com/20079/74241505-7359c300-4cdc-11ea-8e26-48ebe018ee5e.png">

#### How to reproduce the bug

1. docker-compose build 
2. docker-compose up
3. See error

### Environment

- superset version: latest in from source
- python version: Python 3.6.9

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /logout/ HTTP/1.1" 302 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:23] "GET / HTTP/1.1" 302 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET / HTTP/1.1" 302 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /superset/welcome HTTP/1.1" 302 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /superset/welcome HTTP/1.1" 302 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /login/ HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /login/ HTTP/1.1" 200 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /static/assets/images/superset-logo@2x.png HTTP/1.1" 404 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /static/assets/images/superset-logo@2x.png HTTP/1.1" 404 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /static/assets/images/superset-logo@2x.png HTTP/1.1" 404 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:23] "GET /static/assets/images/superset-logo@2x.png HTTP/1.1" 404 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:27] "POST /login/ HTTP/1.1" 302 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:27] "POST /login/ HTTP/1.1" 302 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:27] "GET / HTTP/1.1" 302 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:27] "GET / HTTP/1.1" 302 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:27] "GET /superset/welcome HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:27] "GET /superset/welcome HTTP/1.1" 200 -
superset_1         | 172.18.0.1 - - [11/Feb/2020 13:37:27] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_1         | INFO:werkzeug:172.18.0.1 - - [11/Feb/2020 13:37:27] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_1         | 127.0.0.1 - - [11/Feb/2020 13:37:36] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [11/Feb/2020 13:37:36] "GET /health HTTP/1.1" 200 -
superset_1         | 127.0.0.1 - - [11/Feb/2020 13:38:06] "GET /health HTTP/1.1" 200 -
superset_1         | INFO:werkzeug:127.0.0.1 - - [11/Feb/2020 13:38:06] "GET /health HTTP/1.1" 200 -
```

**Comment by hozn** [comment]
Seeing same issue here on a clean install (MacOS -- with updated resource limits so that build would work).

**Comment by vikt0rs** [comment]
Seems to be duplicate of https://github.com/apache/incubator-superset/issues/9108

**Comment by nytai** [comment]
should be fixed by: https://github.com/apache/incubator-superset/pull/9114

**Comment by willbarrett** [comment]
Hi @l1x and @vikt0rs - are you still experiencing this issue?

**Comment by l1x** [comment]
> Hi @l1x and @vikt0rs - are you still experiencing this issue?

It worked after the update.

**Comment by vikt0rs** [comment]
works for me as well, thanks!

**Comment by inetfuture** [comment]
I had the same symptom, the cause is [the `npm install` command of superset-node container](https://github.com/apache/incubator-superset/blob/232925b7bf0e2ffbe23029a77a97223663830968/docker-compose.yml#L72) did not run successfully due to network failure(I'm at China mainland), I had to mannuly set the npm registry to a China mirror to make it work, posting here just in case someone else run into this.

**Comment by Meizuamy** [comment]
> I had the same symptom, the cause is [the `npm install` command of superset-node container](https://github.com/apache/incubator-superset/blob/232925b7bf0e2ffbe23029a77a97223663830968/docker-compose.yml#L72) did not run successfully due to network failure(I'm at China mainland), I had to mannuly set the npm registry to a China mirror to make it work, posting here just in case someone else run into this.

I hava the same problem when i install the superset ,can u tell me how can i change the npm registry.

**Comment by lanyusea** [comment]
I met the same problem, but I haven't install npm in my Linux, any thought?

**Comment by damnko** [comment]
I'm also having this issue with a clean install on mac, following the instructions here https://superset.apache.org/docs/installation/installing-superset-using-docker-compose. Any hints on how to solve it? Thanks

**Comment by Meizuamy** [comment]
> I'm also having this issue with a clean install on mac, following the instructions here https://superset.apache.org/docs/installation/installing-superset-using-docker-compose. Any hints on how to solve it? Thanks
just wait a minute.

**Comment by mona-mk** [comment]
Solution is to wait until it gets fully complied (~ 10min on macOS Catalina 2,6 GHz 6-Core Intel Core i7)

**Comment by Kyeongan** [comment]
I have the same issues - looking for solutions, but it seems no solution yet.

**Comment by clear-m** [comment]
Looks like I have the same problem (empty screen) when building and installing from the current master.

**Comment by clear-m** [comment]
> I have the same issues - looking for solutions, but it seems no solution yet.

try https://hackernoon.com/a-better-guide-to-build-apache-superset-from-source-6f2ki32n0

**Comment by amravazzi** [comment]
As it was said before, you should wait for Webpack to finish its slow job. It took 170s to finish. I'm running it in a docker and everything was setup when I received `<s> [webpack.Progress] 100%` in the terminal as follows:
<img width="778" alt="Screen Shot 2021-04-19 at 13 25 15" src="https://user-images.githubusercontent.com/6233950/115271323-96b7a380-a113-11eb-9087-69f6db214100.png">

**Comment by mymzheka** [comment]
> 
> 
> I had the same symptom, the cause is [the `npm install` command of superset-node container](https://github.com/apache/incubator-superset/blob/232925b7bf0e2ffbe23029a77a97223663830968/docker-compose.yml#L72) did not run successfully due to network failure(I'm at China mainland), I had to mannuly set the npm registry to a China mirror to make it work, posting here just in case someone else run into this.

Thanks for that, I added http_proxy && https_proxy env vars to docker/.env file, its solve the problem for me

**Comment by matustema** [comment]
I had the same issue and was solved by running;

`$ docker-compose -f docker-compose-non-dev.yml up`

**Comment by techian-sp** [comment]
Team, I still face this issue in the latest build. I followed the instructions in [https://superset.apache.org/docs/installation/installing-superset-using-docker-compose](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose). I waited for almost 2 hours. I didn't see it fixed. So I moved to the production version (`docker-compose -f docker-compose-non-dev.yml up`) 

Anyone else is facing the issue? Can you help me, how to fix the issue in dev build.

**Comment by spcvalente** [comment]
I had the same issue yesterday. no solution on this or other posts fixed it for me.

I fixed it by doing these steps, although I am not sure which one actually did it:
 
- increasing docker resources, mainly memory to 16GB
- `docker system prune`, fresh start, removing volumes, etc.
- running again, until stable - the blank page is still there
- attaching a shell to the `superset_node` container and running `npm run build`
- waiting
- the blank page is gone

I hope this helps
