### ISSUE TITLE
"Exception: No ldap library for python" when running Superset with Docker

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#9127]
I'm running Superset with Docker. 
I changed the Authentication type from `AUTH_DB` to `AUTH_LDAP` in `config.py` like so:

```
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = "ldap://ldap.forumsys.com"
AUTH_LDAP_SEARCH = "dc=example ,dc=com"
AUTH_LDAP_BIND_USER = "uid=riemann,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD = "password"
```

But when I try to login, I get the exception `No ldap library for python`. Why is that? Doesn't Python ldap install at the beginning of the image creation?  Do I need to add `pyldap` or something similar to the requirements.txt and rebuild the image?

**Comment by saurabhdhupar** [comment]
If you login to docker container and try pip freeze you should be able to find if this dependency is missing. You can add a dependency to requirements-dev.txt and rebuild the docker image.

**Comment by klazaj** [comment]
@saurabhdhupar I'm not sure which dependency I'm supposed to look for. There is no `ldap` of some sort in requirements.txt or requirements-dev.txt file to begin with.

**Comment by dpgaspar** [comment]
You need to install `python-ldap` adding it to `requirements-extra.txt` and rebuilding the image should work

**Comment by perrfect** [comment]
Hello.
I have the save issue.
I use a docker-compose and latest code from the github repo.
I've tried to add python-ldap in all requirement files, but got error: "python-ldap library is not installed".
After that i had tried install python-ldap directly in a docker container, but got error: "ERROR:flask_appbuilder.security.manager:(0, 'Error')"
How can fix it and which requirements file should i use for that?
And when i tried install python-ldap directly in docker container i needed install additional packages for ubuntu:
"python-dev libldap2-dev libsasl2-dev libssl-dev"
