### ISSUE TITLE
RECAPTCHA_DISABLE not supported by AUTH_DB

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#9136]
**Is your feature request related to a problem? Please describe.**
When using `AUTH_DB`, apparently one must have a valid public key defined as 
`RECAPTCHA_PUBLIC_KEY` for google recaptcha.

**Describe the solution you'd like**
I dont want a RECAPTCHA on my user registration page. I'm not even sure the requests for such a thing would make it through our proxy.

because the user registration is built on flask-wtf and since [flask-wtf accepts a `RECAPTCHA_DISABLE` configuration parameter](https://github.com/lepture/flask-wtf/pull/214/files) then it stands to reason that Superset should support this parameter.

**Comment by nytai** [comment]
@metaperl seems like a simple enough config to add, would you be interested in opening a PR?
