### ISSUE TITLE
Document AUTH_DB configuration

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#9137]
**Is your feature request related to a problem? Please describe.**
If one attempts to use `AUTH_DB` in configuration, one encounters errors because the docs do not instruct on what auxiliary parameters from FAB must be defined.

**Describe the solution you'd like**
Link to [the relevant FAB docs](https://flask-appbuilder.readthedocs.io/en/latest/user_registration.html#database-authentication) and mention that only 3 of the variables need be defined:

1.  `RECAPTCHA_PUBLIC_KEY = 'oh say can you see'`
1.  `RECAPTCHA_PRIVATE_KEY = 'dont even start'`
1.  `MAIL_DEFAULT_SENDER='asdfasdfsdf@aadsasfasdfme.com'`

**Comment by metaperl** [comment]
Also instruct the user to register a public /private key pair at the google recaptcha site.

**Comment by nytai** [comment]
@metaperl seems like this is a fairly simple docs change, mind opening a PR?
