### ISSUE TITLE
[Explore] persist options after the datasource is modified

### ISSUE THREAD

**Issue by serenajiang** [apache/incubator-superset#9148]
**Is your feature request related to a problem? Please describe.**
Not sure if this qualifies as a bug or a feature request.

In chart explore view, when you click `Edit datasource` and save, it clears all the chart options. Even if no changes are made 😮

**Describe the solution you'd like**
Possible solutions:
* Keep all chart options. Running the query could result in an error if the datasource edit significantly changed relevant columns/metrics
* Keep all chart options and flag invalid options.
* Remove invalid options

**Describe alternatives you've considered**
* Leaving things as they are. Maybe this behavior is intentional/too hard to change?

**Comment by etr2460** [comment]
This was fixed by https://github.com/apache/incubator-superset/pull/10092
