### ISSUE TITLE
the version of 0.28 . the button of dashboard export dose not work.

### ISSUE THREAD

**Issue by dushang2016** [apache/incubator-superset#9151]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### How to reproduce the bug

1. Go to 'dashboard'
2. Click on 'export'
no work
### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @dushang2016,

Please upgrade to the latest official release 0.35.2. If the problem persists, update the issue template with all the requested information.
