### ISSUE TITLE
Issue with connecting mysql to Apache superset

### ISSUE THREAD

**Issue by aniii** [apache/incubator-superset#9153]
I am exploring Apache SuperSet. I want to connect to mysql database on server i.e., EC2 instance. I have installed all the required libraries based on https://superset.incubator.apache.org/installation.html and launched the superset as well.
I did go through https://docs.sqlalchemy.org/en/12/core/engines.html#database-urls. 
entered mysql://{username}:{password}@{ip address of ec2 instance}/{database name} in the URL
Although i have the library, yet when i try to connect the mysql it says "No module named 'MySQLdb'". (Yes i have installed mysql-client)

 Please help me with how to proceed?

**Comment by dpgaspar** [comment]
Hi @aniii,

Use `pip install mysqlclient`. If it still fails post the output of `pip freeze`

**Comment by aniii** [comment]
i did, it says requirement already satisfied. i have attached the screenshot of pip freeze. 

![Screenshot from 2020-02-19 11-03-30](https://user-images.githubusercontent.com/10722470/74804893-90f3e180-5307-11ea-8fa6-fc7136709888.png)
![Screenshot from 2020-02-19 11-03-43](https://user-images.githubusercontent.com/10722470/74804895-92250e80-5307-11ea-8bf6-7ebc1280afd1.png)
![Screenshot from 2020-02-19 11-03-48](https://user-images.githubusercontent.com/10722470/74804898-93563b80-5307-11ea-9992-29915e863ba5.png)

**Comment by jackyq2015** [comment]
Maybe the pip didn't install the module to the environment where your superset is running? are you using virtualenv? Also please check the python version

**Comment by aniii** [comment]
![Screenshot from 2020-02-24 10-47-11](https://user-images.githubusercontent.com/10722470/75130208-0e966380-56f3-11ea-9b48-49eca9b577d6.png)
The requirement is already 
python version is Python 3.6.9,
yes i am using virtual env

**Comment by willbarrett** [comment]
Sorry @aniii - you've got us stumped. We are unable to duplicate this issue. If Superset is running in that virtual environment, you should not be experiencing this issue.

**Comment by hemantaggarwal** [comment]
@aniii  : Try running "pip show mysqlclient" and "pip show apache-superset" in virtual environment. It will show the installed location of both packages. 
Also you installed both package using 'pip' only, not with 'pip3'?
