### ISSUE TITLE
Nulltype shown for Timestamp and varchar types using Clickhouse 20.1.4.1

### ISSUE THREAD

**Issue by durchgedreht** [apache/incubator-superset#9155]
We're using Clickhouse database and have troubles with tables showing "Nulltype" for timestamp and varchar running on Superset 0.34.0rc1.
It's strange as JDBC like DBeaver work fine and also show correct column data. Also Superset seems to get the correct metadata as the error message shows "No field class for timestamp" or "No field class for varchar".

All other columns on the same table work ok and have no issue (int). Also this is the case for tables and views. This showed up in charts first, but also happen in SQL Lab. See screenshots attached: 
<img width="819" alt="Screenshot 2020-02-17 at 16 45 14" src="https://user-images.githubusercontent.com/4490840/74668298-3cd0ec00-51a5-11ea-83ab-21009320da53.png">
<img width="1233" alt="Screenshot 2020-02-17 at 16 25 33" src="https://user-images.githubusercontent.com/4490840/74668305-3f334600-51a5-11ea-9ab9-e20b19f01029.png">

**Comment by mistercrunch** [comment]
I'm guessing that error is emitted by the `sqlalchemy-clickhouse` library. Can you get the stacktrace out of you server logs and share that here?

**Comment by villebro** [comment]
I agree with @mistercrunch , this is a problem in `sqlalchemy-clickhouse`: https://github.com/cloudflare/sqlalchemy-clickhouse/blob/master/connector.py#L99

**Comment by durchgedreht** [comment]
Ok following up there. Thanks for the quick feedback - will close the issue.
Thanks for the great work in superset!
