### ISSUE TITLE
Improve Filter Box Control to accept Conditional Filters 

### ISSUE THREAD

**Issue by shanmukhsista** [apache/incubator-superset#9156]
**Is your feature request related to a problem? Please describe.**
Currently, Dashboard filters accept a list of dimensions and you can filter on values. But , for a few reports, I also want to filter based on some conditions. Let's take the example of the Sample Dashboard World Bank's Data. I wanted to see Life Expectency for Asia without the Country India.

**Describe the solution you'd like**

Currently, i can only select filters where value is in [some value] . I would like the filters to be more dynamic and one can build upon those instead of selecting a value. 

<img width="322" alt="Screen Shot 2020-02-17 at 7 57 29 AM" src="https://user-images.githubusercontent.com/6358603/74669293-b6dc8300-515b-11ea-8735-c19d772a72f8.png">

Instead of this, i would like a representation that has the following 

<img width="333" alt="Screen Shot 2020-02-17 at 7 58 07 AM" src="https://user-images.githubusercontent.com/6358603/74669325-c78cf900-515b-11ea-856b-e37b30065cba.png">

You can build filter controls with a specified set of dimensions but while rendering the dashboard, you can pick and select them just like filter controls. 

**Describe alternatives you've considered**

I have considered adding a filter to the chart itself. But there are times when i just want to filter out on some values from the dashboard / just do a quick compare with different filter conditions. 

**Additional context**

 I saw a similar request here but it's been closed now. 

https://github.com/apache/incubator-superset/issues/8194

**Comment by klazaj** [comment]
You can create a filter based on a query in SQL-Lab, and then use it in the Dashboard.
