### ISSUE TITLE
docker compose up encounter an issue of image missing

### ISSUE THREAD

**Issue by anriliu** [apache/incubator-superset#9159]
I downloaded the release package 0.35 and ran on the linux with "docker-compose up", but there is an issue:

` Step 14/34 : FROM python:${PY_VER} AS lean
 ---> 5bf410ee7bb2
Step 15/34 : ENV LANG=C.UTF-8     LC_ALL=C.UTF-8     FLASK_ENV=production     FLASK_APP="superset.app:create_app()"     PYTHONPATH="/app/pythonpath"     SUPERSET_HOME="/app/superset_home"     SUPERSET_PORT=8080
 ---> Using cache
 ---> 2262c6496666
Step 16/34 : RUN useradd --user-group --no-create-home --no-log-init --shell /bin/bash superset         && mkdir -p ${SUPERSET_HOME} ${PYTHONPATH}         && apt-get update -y         && apt-get install -y --no-install-recommends             build-essential             default-libmysqlclient-dev             libpq-dev         && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 34102eb3fe89
Step 17/34 : COPY --from=superset-py /usr/local/lib/python3.6/site-packages/ /usr/local/lib/python3.6/site-packages/
---> 5b2de6af3e10
Step 18/34 : COPY --from=superset-py /usr/local/bin/gunicorn /usr/local/bin/celery /usr/local/bin/flask /usr/bin/
 ---> f3a93c01f8ee
Step 19/34 : COPY --from=superset-node /app/superset/static/assets /app/superset/static/assets
ERROR: Service 'superset' failed to build: invalid from flag value superset-node: No such image: sha256:8402013096c0c185b0069be82609faaf58bab7d340e161eb9eea0a84da19d054
`

OS info is:
"Linux hades.dev 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"

$ docker version

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by dpgaspar** [comment]
Hi @anriliu,

Assuming that you downloaded the tar.gz for apache-superset 0.35.2 from Apache. You should use the 

https://github.com/apache/incubator-superset/tree/0.35

And use docker instructions from: https://github.com/apache/incubator-superset/tree/0.35/contrib/docker

or here: https://apache-superset.readthedocs.io/en/0.35.1/installation.html#start-with-docker

**Comment by anriliu** [comment]
Thanks
