### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by blcksrx** [apache/incubator-superset#9160]
Python 3.8 Support

**Comment by mistercrunch** [comment]
I think it should work though we test against 3.6 still. I wonder if we should build against 3.7 / 3.8 also. Clearly we don't want to add a new dimension to the build matrix and multiply it by 3, but we could pick a certain database (say postgres) and run the python test suite against it, growing the matrix by 2 slots.

**Comment by villebro** [comment]
With the release of `gunicorn>=20` Superset should now be fully 3.7 compliant, so it would make sense to add at least a test for that. I expect 3.8 to mostly work, but would be surprised if all dependencies are already fully 3.8 compliant. In my experience the ecosystem catches up to new python minors in about a year.
