### ISSUE TITLE
Version control / plaintext config?

### ISSUE THREAD

**Issue by dylburger** [apache/incubator-superset#917]
There are technically two points of feedback here, which I'm happy to break out into two separate issues if y'all want.

For context, I'm coming to Caravel as a user who's used Looker a lot in the past. Looker manages the bulk of its configuration of tables / measures / dimensions via a YAML config file, which is also managed via version control (light UI to abstract git workflow).

This has two awesome benefits:
- The git workflow enables developers to edit configs using standard version control workflow, merging changes, "pushing" those changes to users after having staged and tested them (on the developer's local branch), and enables rollbacks to specific commits were something to go wrong.
- Since the config is plaintext, it's easy to use standard code review practices for pushing new changes to measures / dimensions. Overall, it's also easy to diff changes over time.

I'm still very new to Caravel, but this is a feature I hadn't seen an equivalent for and wanted to share thoughts on the potential benefits of such a model. Thanks!

Dylan

**Comment by mistercrunch** [comment]
A few notes from our conversation:
* Let's use javascript objects (not json) over yaml
* We want to support both UI forms and source control!
* The UI could pivot to JSON
* We may need a "policy" where an admin would be able to define which datasources are editable in UI vs source control
*...

**Comment by guillaumewibaux** [comment]
Totally makes sense in my opinion. Keeping tracks of queries with git is what I am doing in any case. This came naturally as my usage of the semantic layer got significant.
And the semantic layer really is a cool feature.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 230 days. Feel free to comment and request for this issue to be reopened.

**Comment by jotarada** [comment]
Hi. This feature will not be implemented? it seams a nice plus have this

**Comment by cobyrne09** [comment]
Any updates on this? Maybe I've missed it but is there a way pull datasets or other config in github or other version control?
