### ISSUE TITLE
Owner selectors sometimes display full name, other times username

### ISSUE THREAD

**Issue by suddjian** [apache/incubator-superset#9171]
The Edit Dashboard and Edit Chart modals display the user's full name when selecting an owner from the dropdown, but display the username when simply displaying the existing owners.

The cause of this is that the `/dashboard/related/owners` api endpoint returns full name, while the `/dashboard/:id` endpoint returns only the username, so the modal is just using the information that it has available. Both endpoints return the user id, so this doesn't lead to real bugs, just visual confusion. I think the best solution would be for the endpoints to return more information, but I'm unsure how to accomplish that within FAB. Open to other suggestions as well.

Pinging @dpgaspar for FAB expertise.

### Expected results

Should use the owner's name

### Actual results

Mixed results

#### How to reproduce the bug

1. Go to a chart or a dashboard
2. Click on "edit properties" to open the edit modal
3. Set some owners
4. Reload the modal, owners are now displayed by username instead of name

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
@suddjian These are the fields for the `/dashboard/:id` endpoint https://github.com/apache/incubator-superset/blob/master/superset/views/dashboard/api.py#L144

This is the `/related/:col_name` endpoint https://github.com/apache/incubator-superset/blob/master/superset/views/base_api.py#L132

**Comment by nytai** [comment]
Seems like the related endpoint is just using `str(col)` which is configured in FAB, I believe.

**Comment by dpgaspar** [comment]
@nytai The related will use whatever you configure on the model magic method `__repr__(self)`. On this case, Model `USer` is on FAB

**Comment by suddjian** [comment]
This was fixed a while ago
