### ISSUE TITLE
Ability to rename database table

### ISSUE THREAD

**Issue by dylburger** [apache/incubator-superset#918]
I love the ability Caravel presents to edit the names of fields / measures tied to a specific data table. From a UX point of view, seeing "Count of Orders" vs. "COUNT(*)" really makes a difference to users unfamiliar with SQL!

In the same way, enabling an admin to change the table name presented to users would be ideal. After configuring my table, I see this when trying to query:

![screen shot 2016-08-10 at 12 52 05](https://cloud.githubusercontent.com/assets/242668/17568636/719730fe-5ef9-11e6-9ebb-04eb696fc252.png)

But I'd love the ability to rename that to "SFPD Incidents", hiding both the database and table name from users and presenting a more clear description of the data.

**Comment by xrmx** [comment]
Adding a verbose name for the Table should be easy, regarding the metrics, you can already rename them. Care to open a pull request?

**Comment by dylburger** [comment]
It'd certainly be fun to hack on Caravel. If I have the time I'd love to see if I can make the change and submit a PR! No promises :), but I'll put it on my backlog.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 620 days. Feel free to comment and request for this issue to be reopened.
