### ISSUE TITLE
sudo superset db upgrade

### ISSUE THREAD

**Issue by carlossleao** [apache/incubator-superset#9186]
Good afternoon, when installing the database "sudo superset db upgrade", I get this error, could someone help?
![erroSuperSet](https://user-images.githubusercontent.com/32639020/75065007-baa73700-54c6-11ea-9561-e7932e3050e8.png)

**Comment by dpgaspar** [comment]
Hi @carlossleao,

I advise you not to run superset has `root`, also use a python virtualenv with the pinned `requirements.txt` installed on it.
