### ISSUE TITLE
Superset 0.36.0 Pivot Table prints the "Column Name" instead of "Verbose Name"

### ISSUE THREAD

**Issue by gbonazzoli** [apache/incubator-superset#9198]
In Superset version 0.36.0 (as on 0.35.2) in every Pivot Table Visualization only the first Column referred is rapresented with its "Verbose Name".

All the others are printed with the technical field name of the physical table.

See the screenshot below.
```
root@srv-superset:~# superset version
Superset 0.36.0

root@srv-superset:~# python3 --version
Python 3.7.5
```
<img width="1440" alt="Screenshot 2020-02-25 at 05 11 09" src="https://user-images.githubusercontent.com/17742862/75214537-37b80200-578e-11ea-87e1-bb6b7d3383a8.png">

**Comment by dinhthengoc2021998** [comment]
some1 can give me a solution for this. I've met the same problem too.

**Comment by GiannisDimitriou** [comment]
+1
