### ISSUE TITLE
Superset - 500 Internal Server Error

### ISSUE THREAD

**Issue by SyamprasadNakka** [apache/incubator-superset#9200]
Hello,
We have installed Superset=0.33.010402 and running superset with Gunicorn server by enabling the log-level in debug mode. 
We have given demo to our customer without any report development (just ran few reports), but ran into 500 Internal Server Error. 

We have analyzed the logs and couldn't found any information on server down, after few minutes we were able to access the superset application without any restart.

**Log Info:**
[**2020-02-20 12:21:03 -0500**] [43008] [DEBUG] **GET /sliceemailscheduleview/list/**
[2020-02-20 12:21:03 -0500] [19195] [DEBUG] Error processing SSL request.
[2020-02-20 12:21:03 -0500] [19195] [DEBUG] Invalid request from ip=127.0.0.1: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2488)

[**2020-02-20 13:13:04 -0500**] [19191] [DEBUG] **GET /superset/welcome**
[2020-02-20 13:13:05 -0500] [31855] [DEBUG] Error processing SSL request.
[2020-02-20 13:13:05 -0500] [31855] [DEBUG] Invalid request from ip=127.0.0.2: [SSL: SSL_HANDSHAKE_FAILURE] ssl 

Is there a way that we can find the issue details when the application was not accessible?

### Expected results

If something went wrong to the application it should write to logs with all the crash/issue details.

### Actual results

Didn't find any information in logs if something happened to the application.

#### How to reproduce the bug
Issue was not reproducible every time. 

### Environment

(please complete the following information):

- superset version: `0.33.010402`
- python version: `python3.7.3`
- Linux OS: `Redhat 7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

As we are planning to go-live this week, it would be great if you can provide solution/inputs on the same.

Regards,
Syam

**Comment by nytai** [comment]
From the logs this looks to be an issue with SSL. Are you accessing over `https` or `http`?

**Comment by SyamprasadNakka** [comment]
> 
> 
> From the logs this looks to be an issue with SSL. Are you accessing over `https` or `http`?

We are running HTTPS with self-signed certificates and not sure it's because of SSL, because SSL handshake error will always write when we access any object and it's not throw 505 internal error.

Please let me know if need any more details.

Regards,
Syam

**Comment by willbarrett** [comment]
@SyamprasadNakka are you terminating SSL at the `gunicorn` process? Typically it's a good practice to terminate `ssl` at a web server like NGinx or Apache running on the same machine, then access the service provided by `guincorn` over un-encrypted HTTP via the local loopback.
