### ISSUE TITLE
Using oracle as DataSource in superset with Docker

### ISSUE THREAD

**Issue by ilyakitaev** [apache/incubator-superset#9216]
Hello, just as a solution and for future development.

Quick fix

1. First you need to download oracle client with libraries and put them into superset image
2. install cx_Oracle and libaio1 inside container
`apt update; apt install -y libaio1; pip install cx_Oracle`
3. For normal language support set env variable in the docker/.env
NLS_LANG=RUSSIAN_RUSSIA.AL32UTF8 # for Russian with UTF-8
4. Superset does not detect oracle and uses postgres specs for that datasource. So you need to comment this line to fix SQL Lab error
superset/db_engine_specs/postgres.py +52
`# cursor.tzinfo_factory = FixedOffsetTimezone`

hope it will be helpfull

**Comment by nk-fouque** [comment]
I think I have the problem you fix with your 4th point, but doing that didn't change anything, should I restart something ?

**Comment by ilyakitaev** [comment]
> I think I have the problem you fix with your 4th point, but doing that didn't change anything, should I restart something ?

can you provide any logs? That was quickfix for demo, m.b. I can help you
