### ISSUE TITLE
i want to develop base on caravel  on windows 7

### ISSUE THREAD

**Issue by lihemin** [apache/incubator-superset#922]
in this process， i found that  gunicorn is Incompatible  with win7.    how to tackle it

**Comment by xrmx** [comment]
@lihemin my first answer would be: don't :) Anyway caravel is a flask app, whatever works for a flask app on windows will work for caravel too. Hopefully someone on the internet had your problem and solved it.

**Comment by aljones** [comment]
I have a [windows-support](https://github.com/aljones/caravel/tree/windows-support) branch. It uses [waitress](http://docs.pylonsproject.org/projects/waitress/en/latest/) which I have no prior experience with. There are also changes in that branch to support mssql better. Been testing it this week with a couple users. Would be nice to hear if it works for others.

**Comment by xrmx** [comment]
@aljones nice! 7ee6cc5a7203cfe06104ba38e0e96ced876e0897,  377c8268071137e7f69827c85b892e9073e747f2 and 1433e73087d23598b1e55080eb16f8572a121a9c looks sensible if you can put in a branch on their own and open a PR would be great. Same for 01756af399a5f4ec6ef8e64c283227dea60e7dc9 and another branch for 07443fd9bf161d6d64c08eee672dca0d4b587598

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 618 days. Feel free to comment and request for this issue to be reopened.
