### ISSUE TITLE
No database privilege created when database is created.

### ISSUE THREAD

**Issue by dwene** [apache/incubator-superset#9225]
When a new database is created, there isn't a corresponding database privilege created.

I've been trying to follow the docs for adding Gamma users here: https://superset.incubator.apache.org/security.html#sql-lab

I'd like to create a Gamma user, give them sql lab rights, and give them access to a single database.
When I add a database in the UI, and try to create a new role with privileges to query that database, there doesn't appear to be one.

There is however a database privilege for the initially `examples` database. So it seems to me like there should be a database privilege for the other databases I added also, so that I can grant Gamma+sql_lite role users access to use sql lab.

### Expected results

A new database privilege is created when I add a database

### Actual results

No database privilege is created.

#### Screenshots

<img width="653" alt="Screen Shot 2020-02-28 at 5 32 00 PM" src="https://user-images.githubusercontent.com/12628251/75594998-636a0f00-5a50-11ea-8afb-ac68aef58150.png">
<img width="649" alt="Screen Shot 2020-02-28 at 5 32 11 PM" src="https://user-images.githubusercontent.com/12628251/75594999-6402a580-5a50-11ea-9a8b-d1996670a62a.png">

Notice how there is no database privilege for "dwene" but there is one for "example"

#### How to reproduce the bug

1. Go to Sources -> Databases.
2. Add a new database.
3. Go to roles.
4. Try to create a new role with the new database privilege.
5. Notice that there is no database privilege, only datasource and schema privileges.

### Environment

(please complete the following information):

- superset version: `0.35.2`
- python version: whatever is in the built docker container.

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nytai** [comment]
hey @dwene check out: https://github.com/apache/incubator-superset/pull/8699

It may satisfy your requirements

**Comment by dwene** [comment]
Hey @nytai , thanks for responding. 

The row based security is pretty cool! But not really what I'm looking for. I'm looking for a way to grant a user access to SQL lab for only 1 database. It seems like the way to do that is by making a new role with that database privilege (datasource and schema privileges don't appear to be enough), but I can't seem to find a way to add it.

**Comment by dwene** [comment]
Additional screenshot showing missing database_access privilege.
I've added 2 other databases.

![image](https://user-images.githubusercontent.com/12628251/75600502-9ecb0480-5a75-11ea-877b-f62efcd993a6.png)

**Comment by dwene** [comment]
Interestingly enough, editing the database and saving (without making any changes) seems to resolve the problem.
