### ISSUE TITLE
Failed Mac Docker Install

### ISSUE THREAD

**Issue by DennisFaucher** [apache/incubator-superset#9226]
### Expected results

superset installed in Docker Mac

### Actual results

 11% building 9/18 modules 9 active ...t-frontend/src/showSavedQuery/index.jsxBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T17_03_00_419Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset-frontend         && npm run build         && rm -rf node_modules' returned a non-zero code: 1

#### Screenshots

N/A

#### How to reproduce the bug

docker-compose up

### Environment

(please complete the following information):

- superset version: N/A
- python version: Python 2.7.16
- node.js version: v12.14.1
- npm version: 6.14.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

 11% building 9/18 modules 9 active ...t-frontend/src/showSavedQuery/index.jsxBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T17_03_00_419Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset-frontend         && npm run build         && rm -rf node_modules' returned a non-zero code: 1

**Comment by willbarrett** [comment]
Hi @DennisFaucher, thanks for the bug reports! I've seen problems with `terser` crop up when the docker system runs out of memory - if I remember correctly, the default install comes with a 2GB RAM limit. I've found that bumping this to 4GB or 6GB via the "Resources" section of the preferences pane resolves the issue. I hope this helps!

We've discussed the resource-intensive nature of Terser before. It's of value in a production environment but we want to make this experience better in development.

**Comment by DennisFaucher** [comment]
Thanks @willbarrett I'll try that

**Comment by willbarrett** [comment]
Cool. Let us know if it works for you and I'll update the documentation.

**Comment by willbarrett** [comment]
Confirmed on https://github.com/apache/incubator-superset/issues/9227 that this was caused by insufficent RAM.

**Comment by DennisFaucher** [comment]
@willbarrett Increased RAM for Mac Docker and all is good. Also that "Force Layout" chart is trippy. I need to find a reason to use that.
<img width="1420" alt="Screen Shot 2020-03-09 at 2 02 01 PM" src="https://user-images.githubusercontent.com/9034190/76243349-952c6400-620e-11ea-9de3-f78964dea533.png">

**Comment by willbarrett** [comment]
Awesome. I'm glad we could get it sorted out.
