### ISSUE TITLE
Failed Ubuntu Docker Install

### ISSUE THREAD

**Issue by DennisFaucher** [apache/incubator-superset#9227]
### Expected results

superset installs cleanly

### Actual results
```
 11% building 9/18 modules 9 active ...t-frontend/src/showSavedQuery/index.jsxBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T18_20_06_849Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset-frontend         && npm run build         && rm -rf node_modules' returned a non-zero code: 1
```

#### Screenshots

N/A

#### How to reproduce the bug

docker-compose up

### Environment

(please complete the following information):

- superset version: N/A
- python version: 2.7.17
- node.js version: v8.10.0
- npm version: 3.5.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
Things are working here https://hub.docker.com/repository/docker/preset/superset/general

What branch/SHA are you building? Did you modify anything?

**Comment by DennisFaucher** [comment]
@mistercrunch  I followed the exact instructions today on the web page below. Version are included above.  
https://superset.incubator.apache.org/installation.html#

**Comment by willbarrett** [comment]
Hi @DennisFaucher I just tried to reproduce this problem in an Ubuntu 18.04 virtual machine with 8 GB of assigned RAM and 40gb of assigned hard drive space. I did not run into the same issue you did using Superset SHA 26e916e46b1f8b066ef91fdcb2f0dcfc85c83715. Would you mind sharing the SHA of Superset that you were attempting to install as well your Ubuntu and Docker versions? I'd love to be able to reproduce this on my end so that I can debug. Thanks!

**Comment by DennisFaucher** [comment]
@willbarrett Excellent. Looks like RAM may be the culprit here Ave and MacOS. I'll test this as well. Thank you.

**Comment by DennisFaucher** [comment]
@willbarrett Upping the VM RAM to 8 GB did the trick. Now for those treemap colors... :)
<img width="916" alt="Screen Shot 2020-03-09 at 1 14 51 PM" src="https://user-images.githubusercontent.com/9034190/76239536-1fbd9500-6208-11ea-8b40-e7c9063f7375.png">

**Comment by willbarrett** [comment]
Thanks @DennisFaucher I'm glad that did the trick. Yes, those colors could use a tweak for sure!
