### ISSUE TITLE
Months Unavailable in Time Series Bar Chart of Week Granularity 

### ISSUE THREAD

**Issue by MarcusSorealheis** [apache/incubator-superset#9229]
When a Time Series Bar Chart displays data at "Week" granularity but spanning multiple months, there is no month label. It can be tricky to keep track of which month you might be looking at. 

### Expected results

I would expect that the month would be appended to the label so that viewers still know which month they are looking at. 

### Actual results

Instead, what actually happens is that only the day date is shown, so users only see a sea of Mondays.

#### Screenshots

![supersettimeseriesbug](https://user-images.githubusercontent.com/2353608/75751280-f6b67500-5cda-11ea-98bf-8efb0a0ed0d8.gif)

#### How to reproduce the bug

1. Go to 'charts'
2. Click on 'the Create a chart plus sign' and create time series bar chart.
3. Use date range spanning more than one month, and set time granularity to  'week.'

### Environment

(please complete the following information):

- superset version: `Master`
- python version: `Python 3.6.10 (default, Jan  4 2020, 03:14:07)`
- node.js version: `v12.5.0`
- npm version: `6.9.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by snowwiki** [comment]
Didi you ever find solution for this? I'm having same issue.

**Comment by snowwiki** [comment]
@MarcusSorealheis did you ever find solution for this? I'm seeing same issue. 
Superset 0.36.0
