### ISSUE TITLE
[feature] access control on chart/dashboard

### ISSUE THREAD

**Issue by zhxjdwh** [apache/incubator-superset#9230]
we has some big table  which more than 500+ column , in my company , all of department work on  few tables, now we have 200+ charts in the chart list page.  it make us confused，

so，How can i set the chart/dashboard only visible for **me or my department  or specific users** ?

**Comment by willbarrett** [comment]
Hi @zhxjdwh - to my knowledge, charts and dashboards don't have visibility options in Superset at this time. I'm happy to hear your organization is getting so much use out of Superset.

**Comment by zhxjdwh** [comment]
> Hi @zhxjdwh - to my knowledge, charts and dashboards don't have visibility options in Superset at this time. I'm happy to hear your organization is getting so much use out of Superset.

thanks，Do superset plan to add this feature like “access control on chart/dashboard” in the future?

**Comment by willbarrett** [comment]
We've discussed evolving the security model - if others would find this functionality useful I'm sure we'd consider it!
