### ISSUE TITLE
Email scheduling functionality not working in docker container

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#9236]
We have configured superset application inside docker container and scheduled some raw data emails. For the scheduling functionality we are using "redis" as backed result storage and message broker. After scheduling, got mails in first one hour and then started getting issues like "TIMEOUT" errors in log file. do you have any idea why exactly "TIMEOUT" errors are coming and emails are stopped coming after 1 hour?

The following are the celery worker and celery beat commands we using to bring up celery services.
1) celery worker -c 4 --without-gossip --app=superset.tasks.celery_app:app --max-tasks-per-child=128 --pool=prefork -Ofair
2) celery beat --app=superset.tasks.celery_app:app  --loglevel=debug

The following are the celery cofiguration
BROKER_URL = 'redis://<host>:6379/0'
CELERY_RESULT_BACKEND = 'redis://<host>:6379/1'
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 10
    CELERY_ACKS_LATE = True
    CELERY_ANNOTATIONS = {
        'email_reports.send': {
            'rate_limit': '1/s',
            'time_limit': 150,
            'soft_time_limit': 180,
            'ignore_result': True,
        },
CELERYBEAT_SCHEDULE = {
        'email_reports.schedule_hourly': {
            'task': 'email_reports.schedule_hourly',
            'schedule': crontab(minute=1, hour='*'),
        },

we are using visibility timeout for redis : broker_transport_options = {'visibility_timeout': 3600}

Additional information form log file:
[2020-03-04 08:18:02,194: ERROR/MainProcess] Process 'ForkPoolWorker-14' pid:994 exited with 'signal 9 (SIGKILL)'
[2020-03-04 08:18:04,212: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(150)
Traceback (most recent call last):
  File "/usr/local/python3.7/lib/python3.7/site-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(150,)

**Comment by willbarrett** [comment]
Hi @thammaneni - it appears that your tasks are running into a default time limit configured in `superset/config.py` under the `CELERY_ANNOTATIONS` constant. I'm not sure why your tasks start taking longer after an hour, but I would experiment with altering the configuration on your install to allow for a longer `soft_time_limit` and `hard_time_limit`. Here are the relevant line in the Superset configuration: https://github.com/apache/incubator-superset/blob/7a91498cf1a9e56d4b3d7b3805076137525ea277/superset/config.py#L479-L480

**Comment by thammaneni** [comment]
> Hi @thammaneni - it appears that your tasks are running into a default time limit configured in `superset/config.py` under the `CELERY_ANNOTATIONS` constant. I'm not sure why your tasks start taking longer after an hour, but I would experiment with altering the configuration on your install to allow for a longer `soft_time_limit` and `hard_time_limit`. Here are the relevant line in the Superset configuration:
> 
> https://github.com/apache/incubator-superset/blob/7a91498cf1a9e56d4b3d7b3805076137525ea277/superset/config.py#L479-L480

@willbarrett , Thanks for the reply.
i have increased the  time limits from configuration file like below.
"time_limit": 300, 
 "soft_time_limit": 350,
I restarted and scheduled, initial one hour i am able receive emails after that i started getting the Timeout error again. is there any other reason related to memory capacity increment or what is taking long time to fetch data from response object ?

**Error Info:**
[2020-03-05 06:25:51,285: WARNING/MainProcess] Soft time limit (350s) exceeded for ftp_reports.send[c4ba4cbc-ef85-41ee-824f-15611e36129c]
[2020-03-05 06:25:51,287: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(300)
Traceback (most recent call last):
  File "/usr/local/python3.7/lib/python3.7/site-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(300,)
[2020-03-05 06:25:51,287: ERROR/MainProcess] Hard time limit (300s) exceeded for ftp_reports.send[c4ba4cbc-ef85-41ee-824f-15611e36129c]

**Comment by willbarrett** [comment]
I'm not certain what is causing your task to take so long. It might be related to a particularly long-running query on one of the reports you're trying to email, or it might be entirely unrelated. If a memory limit were reached I would expect the container to be killed, which would result in a different error message.

I'd recommend looking at the report in question to see if there are any clues to be found there.
