### ISSUE TITLE
How to config server port by config file ?

### ISSUE THREAD

**Issue by nvlong198** [apache/incubator-superset#9257]
I saw default webserver port is 8088, but actually port ruining is 5000.
What am I doing wrong? Thank you.
![image](https://user-images.githubusercontent.com/23328191/76160079-76b86100-6159-11ea-8349-53f27e475ab7.png)

**Comment by willbarrett** [comment]
Hi @nvlong198 - you're altering the correct configuration option, but you may be altering it in the wrong place. This configuration can be overridden based on a `superset_config.py` file placed in your PYTHONPATH [as described in the documentation]( https://superset.incubator.apache.org/installation.html#configuration). I would check that the PYTHONPATH is configured correctly and the file is named appropriately. If you'd like to share more details of your setup I can help you debug further.
