### ISSUE TITLE
Migrating Superset from version  0.22.1 to version 0.35.0

### ISSUE THREAD

**Issue by srikark16** [apache/incubator-superset#9260]
We are currently running on superset 0.22.1 with python 2.7 on Ubuntu 16.04 LTS.
We are planning to upgrade superset to 0.35.0 version with python 3.6.9 on Ubuntu 18.04.3 LTS.
Can you kindly let us know whether we can use old superset 0.22.1 dashboards after upgrading to superset 0.35.0 ?
OR
Should we build all the superset dashboards from scratch after upgrading to 0.35.0 version ? 

### Environment

- OS: Ubuntu 16.04 LTS
- superset version:  0.22.1
- python version:  2.7

**Comment by willbarrett** [comment]
Hi @srikark16, thanks for the question! 0.22.1 is certainly an older version at this point. I can't tell you with certainty that everything will work. Superset is pre-1.0 so breaking changes are not out of the question at this point.

My recommendation for an upgrade that substantial would be to duplicate Superset's metadata database, set up a new install of Superset configured to point at the copy, and perform the upgrade on that. You'll then be able to check on your charts and dashboards in the new version to determine the best approach for your organization. I hope that's helpful!

**Comment by srikark16** [comment]
Thank you @willbarrett

**Comment by WenQiangW** [comment]
@srikark16 @willbarrett  Hi,  How do I upgrade？ Now, I want Migrate Superset from version 0.30.1 to version 0.35.0,  I backed up the Database ， use 0.35.0 connect copy database,  then commnd：superset db upgrade,  the error :ERROR [root] Error: Can't locate revision identified by 'e96dbf2cfef0'

**Comment by sazary** [comment]
same happening here. what can i do?

**Comment by sazary** [comment]
current revision:

```
superset=> select * from alembic_version
superset-> ;
 version_num
--------------
 f959a6652acd
(1 row)
```
