### ISSUE TITLE
How to add Echarts to the Superset(0.35.2)?

### ISSUE THREAD

**Issue by DilicelSten** [apache/incubator-superset#9270]
I install superset by pip(pip install apache-superset). However, the code is inconsistent with the github(assets and static/assets), so I am confused about it because I can not find the src directory when i run the npm command.
```
(superset_env) root@Ubuntu-cxt:~/superset_env/lib/python3.6/site-packages/superset/assets# npm run dev

> superset@0.35.2 dev /root/superset_env/lib/python3.6/site-packages/superset/assets
> webpack --mode=development --colors --progress --debug --watch

10% building 0/0 modules 0 active
webpack is watching the files…


Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: fbf46623c69bc2a8e3db
Version: webpack 4.42.0
Time: 54ms
Built at: 03/09/2020 9:53:47 AM

ERROR in Entry module not found: Error: Can't resolve './src' in '/root/superset_env/lib/python3.6/site-packages/superset/assets'
```
I don't know how to deal with it. Hope to get the answer!

**Comment by willbarrett** [comment]
Hi @DilicelSten. Thanks for reaching out to the community. There has been a reorganization of the repository since 0.35.2 was released - you can find the code for 0.35.2 at https://github.com/apache/incubator-superset/tree/7cb3d3b5d2e05f98f0683bc72514e4d9f4ce13f8. It seems like you're trying to do something quite sophisticated, so I thought the best thing I could do to help would be to point you to the proper source files. I hope that helps! Let us know if you have further questions.

**Comment by DilicelSten** [comment]
@willbarrett Thanks for your guide.

**Comment by DilicelSten** [comment]
Hi @willbarrett  I find something wrong with the code you provided. After i change the code and run the superset, it is always in the loading condition and I can not do anything. Hope to get your answer! Regards.

**Comment by willbarrett** [comment]
Hey @DilicelSten - are you running under docker? Are there any error messages as part of startup? Are there any error messages from the web server or from the browser console? I'll need more information in order to provide an opinion. Thanks!

**Comment by DilicelSten** [comment]
@willbarrett oh no, I am not running under docker. I just change the code which is installed by pip(pip install apache-superset) and there is no error come from anywhere. It is just loading all the time.
![微信截图_20200313100143](https://user-images.githubusercontent.com/23657578/76582591-ac6e9880-6511-11ea-8b75-4c75684e4077.png)

**Comment by DilicelSten** [comment]
@willbarrett oh no, I am not running under docker. I just change the code which is installed by pip(pip install apache-superset) and there is no error come from anywhere. It is just loading all the time.
![loading](https://user-images.githubusercontent.com/23657578/76582687-ed66ad00-6511-11ea-8c6f-0c9c28934a12.png)

**Comment by WenQiangW** [comment]
@DilicelSten  need run build front
