### ISSUE TITLE
Error updating table colums from changed source

### ISSUE THREAD

**Issue by dpugulo** [apache/incubator-superset#9278]
Error updating table colums from source

(psycopg2.DataError) value too long for type character varying(32) [SQL: UPDATE table_columns SET changed_on=%(changed_on)s, is_active=%(is_active)s, type=%(type)s, is_dttm=%(is_dttm)s, changed_by_fk=%(changed_by_fk)s WHERE table_columns.id = %(table_columns_id)s] [parameters: ({'changed_on': datetime.datetime(2020, 3, 11, 6, 22, 30, 509794), 'is_active': None, 'type': 'TINYINT(1)', 'is_dttm': None, 'changed_by_fk': 6, 'table_columns_id': 1381}, {'changed_on': datetime.datetime(2020, 3, 11, 6, 22, 30, 509830), 'is_active': None, 'type': 'VARCHAR(4) CHARACTER SET utf8mb4', 'is_dttm': None, 'changed_by_fk': 6, 'table_columns_id': 1382}, {'changed_on': datetime.datetime(2020, 3, 11, 6, 22, 30, 509847), 'is_active': None, 'type': 'VARCHAR(12) CHARACTER SET utf8mb4', 'is_dttm': None, 'changed_by_fk': 6, 'table_columns_id': 1383})] (Background on this error at: http://sqlalche.me/e/9h9h)

### Expected results

update colums

### Actual results

error

#### Screenshots

![image](https://user-images.githubusercontent.com/55461451/76388173-82826e00-6379-11ea-9266-0aa1811dbbcf.png)

#### How to reproduce the bug

1. Edit Datasource
![image](https://user-images.githubusercontent.com/55461451/76388505-5fa48980-637a-11ea-813a-a44180dc55f4.png)

2. Click 'Sync from source'
![image](https://user-images.githubusercontent.com/55461451/76388987-6aabe980-637b-11ea-822c-62feed870668.png)

3. Click 'Save '
![image](https://user-images.githubusercontent.com/55461451/76389893-697bbc00-637d-11ea-9bdc-ee8a46f32760.png)

![image](https://user-images.githubusercontent.com/55461451/76389988-9c25b480-637d-11ea-9960-6dfb3d4c1059.png)

### Environment

- superset version: Superset 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.19.0
- npm version: 6.13.4

**Comment by villebro** [comment]
What database is this? the character encoding implies MySQL, but you seem to be using Psycopg2 which implies Postgres.

**Comment by dpugulo** [comment]
mysql

**Comment by dpugulo** [comment]
> What database is this? the character encoding implies MySQL, but you seem to be using Psycopg2 which implies Postgres.

mysql
