### ISSUE TITLE
Superset installation build fails using Docker-compose up on MacOS 

### ISSUE THREAD

**Issue by TinusChen** [apache/incubator-superset#9280]
fatal error

#### Screenshots
$ docker-compose up
Building superset
Step 1/34 : ARG PY_VER=3.6.9

... ...
... ...

Step 12/34 : RUN cd /app/superset-frontend         && npm run build         && rm -rf node_modules
 ---> Running in 98a9928ee875

> superset@0.999.0-dev build /app/superset-frontend
> cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress

Starting type checking service...

Using 1 worker with 2048MB memory limit
 11% building 9/18 modules 9 active ...t-frontend/src/showSavedQuery/index.jsxBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 92% chunk asset optimization TerserPluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-11T10_37_14_899Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c cd /app/superset-frontend         && npm run build         && rm -rf node_modules' returned a non-zero code: 1

#### How to reproduce the bug

git clone https://github.com/apache/incubator-superset/
cd incubator-superset
docker-compose up

**Comment by craig-rueda** [comment]
Hey @TinusChen , can you try bumping the available memory to your docker engine ? (try 4-6GB, resources tab under preferences)

Thanks

**Comment by TinusChen** [comment]
@craig-rueda OK, thank you!

**Comment by craig-rueda** [comment]
BTW, I have a PR that might fix this issue: #9285

**Comment by TinusChen** [comment]
Great.
