### ISSUE TITLE
Blank login Page when building from 0.36.rc1 release branch

### ISSUE THREAD

**Issue by sahiljain001** [apache/incubator-superset#9288]
Blank login Page when building from 0.36.rc1 release branch. Only close button is present

### Expected results

proper login page

### Actual results

Blank login page with close button present

#### How to reproduce the bug

Just follow the steps to run apache superset from the source code from branch 0.36 rc1

**Comment by willbarrett** [comment]
Hi @sahiljain001 - thanks for checking out the RC! I believe this release candidate was cancelled due to a number of bugs that were discovered as part of the release process. Hopefully you won't experience the same issue in the next RC.

**Comment by sahiljain001** [comment]
> Hi @sahiljain001 - thanks for checking out the RC! I believe this release candidate was cancelled due to a number of bugs that were discovered as part of the release process. Hopefully you won't experience the same issue in the next RC.

Hi, thanks for the quick response. Can you please when is the 0.36 release expected.

**Comment by willbarrett** [comment]
@sahiljain001 hopefully in the next couple of weeks, but it depends on the Apache release process and what issues are discovered along the way.

**Comment by sahiljain001** [comment]
@willbarrett Thanks for the information. Actually we have a use case where we want to show a user specific data to a user. For example we have a data source with many client_ids . A logged in user must see data related to his clientId only. Therefore we thought to pass the clientId in URL and then use in all charts for that dashboard that why we were waiting for 0.36 release. Can you please share if there is any other workaround for the same in 0.35.2 release so that we can continue with our work.

**Comment by willbarrett** [comment]
@sahiljain001 there is not a workaround that I am aware of.

**Comment by WenQiangW** [comment]
@willbarrett  hi， superset  version 0.30.1 corresponds to which branch of git .  I don't find this branch in git, and the version superset== 0.30.1 is better than apache-superset==0.35.2 ??? 
(superset== 0.30.1  posted on 2020.1.30,  but apache-superset==0.35.2 posted on 2020.1.7)

**Comment by willbarrett** [comment]
@WenQiangW all of the releases are *tagged* on Github, they are not represented by branches. You can find the tags under the *Releases* tab on this repository.

**Comment by WenQiangW** [comment]
thanks ，but superset 0.30.1 not find  the branch or tag on the git ！

other messege： pypi：the superset0.30.1 release on 2020.1.30， the apache-superset 0.35.2 release on 2020.1.15

**Comment by willbarrett** [comment]
I'm sorry, if it isn't recorded in Github, I have no way of finding out.

**Comment by WenQiangW** [comment]
> I'm sorry, if it isn't recorded in Github, I have no way of finding out.

Thanks
