### ISSUE TITLE
Database unsupported SqlAIchemy dialect,but have python driver

### ISSUE THREAD

**Issue by gitlyx** [apache/incubator-superset#9289]
superset and database 
### DataBase: trafodion
` a database unsupported SqlAIchemy dialect,but have python driver,how could i solve this problem? `

**Comment by zhaoyongjie** [comment]
@gitlyx need to make a SQLAlchemy dialect plugins

**Comment by willbarrett** [comment]
Hi @gitlyx - Apache Trafodion is not currently supported by Superset or SQLAlchemy. To support this database, the community would need to build and release a SQLAlchemy dialect for Apache Trafodion, define it as an extra package for installation, and then update Superset with a new `db_engine_spec` to support the database. If you're interested in taking on this work, let us know and we can connect you with engineers who can provide more guidance.
