### ISSUE TITLE
Big Number formatting(Slice with in Slice) and conditional formatting 

### ISSUE THREAD

**Issue by Harish142** [apache/incubator-superset#9293]
Hi,

I have a scenario where i  want to add an **image and two numbers** in big number section  as shown in screenshot attached. I am not able to get how it can be achieved. 

Also there is one more requirement to change the image conditionally on basis of number like if number is positive image(arrow) displayed should be in green if negative it should be in red (**conditional formatting**)

Can anyone please help me how to incorporate the same.

Thanks in advanced!!

<img width="138" alt="Summary" src="https://user-images.githubusercontent.com/62091483/76499212-4ed04280-6464-11ea-9ab9-6cfa6a453c76.png">

**Comment by ValentinC-BR** [comment]
I agree ! 
Having KPIs that cannot go from green to red (depending on the metric/% change) is not that useful.

Of course, it's useful to sum things up. However I think what decision-makers need (or even any user that monitors an app/ a business) is to _quickly see if things go well or not_. 

Colors are the best way to quickly get it :
* All the KPIs are green ? Things are OK
* One of them is red ? I will check it

What's more, with colors, you cannot make a mistake by reading too fast.

**Comment by wrq2000** [comment]
Yes, I also agree!
