### ISSUE TITLE
How do you connect to Druid datasource today?

### ISSUE THREAD

**Issue by MaxOrelus** [apache/incubator-superset#9300]
A lot of the documentation found on the net is referencing the old Superset that had a Druid Cluster menu item to configure Druid. I'm trying to connect Druid to the new modernize platform where Druid is not the sole database you try to connect to.

Two questions:

1. How do I connect to my druid cluster using the new interface?
2. How do I connect to a druid cluster that has TLS/SSL enabled?

Warm regards.

**Comment by nytai** [comment]
@MaxOrelus You can either use the sqlalchemy druid dialect and connect via a connection string, or you can enable the `DRUID_IS_ACTIVE` config flag in your superset config to use the legacy connector.

**Comment by MaxOrelus** [comment]
@nytai using `DRUID_IS_ACTIVE` did the trick for bringing back the druid cluster menu. Do you have any advice on how to connect to a TLS/SSL enabled druid? The port typically used is usually `8082`, but since I'm using TLS it's `8282` and I'm not sure where I should be adding the client certificate, client key, and ca certificate.

**Comment by nytai** [comment]
are these any help? https://github.com/apache/incubator-superset/issues/7596 and https://github.com/apache/incubator-superset/pull/4480/

**Comment by wchaofan** [comment]
so ,How do I connect to my druid cluster using the superset of 1.1.0?
I set DRUID_IS_ACTIVE=True ,but this was not work

**Comment by colax94** [comment]
Same issue here, how to navigate to Druid datasources in Superset 1.1.0 ?

**Comment by diogenes1oliveira** [comment]
@wchaofan  and @colax94, have you tried running `superset init` again after enabling the DRUID_IS_ACTIVE flag? Found that in the Slack channel, it worked for me
