### ISSUE TITLE
Jinja tempate is not getting evaluated while in explore or dashboad view

### ISSUE THREAD

**Issue by sahiljain001** [apache/incubator-superset#9301]
while using jinja tempate in filters in where clause of explore view do data is showing up but the same query is working in sql lab in 0.35.2 version
![Screenshot from 2020-03-13 16-20-32](https://user-images.githubusercontent.com/62089487/76614940-06d61c00-6547-11ea-85ea-0dc2876e4dd1.png)

### Expected results

jinja template should have got evaluated in explore and dashboard view

### Actual results

no data i.e jinja template is not getting evaluated in exlpore view

#### Screenshots

![Screenshot from 2020-03-13 16-20-32](https://user-images.githubusercontent.com/62089487/76614964-13f30b00-6547-11ea-95f5-293e798200d2.png)

**Comment by sahiljain001** [comment]
I want to use jinja template in explore view so that by using it i can create a dashboard. Is it possible in superset?

**Comment by lilila** [comment]
Hello, I have more or less the same problem [described here](https://github.com/apache/incubator-superset/issues/9328). 

Can you show your Jinja code?

 My impression is that Jinja is working well in Explore View expect the it does not collect filter values as it does in Dashboard context.

**Comment by mistercrunch** [comment]
Is this still an issue?

**Comment by lilila** [comment]
No, it works well with classical slices. However, Jinja filters are still no applied on Annotations
