### ISSUE TITLE
Option to adjust column width in Table view

### ISSUE THREAD

**Issue by swattamw** [apache/incubator-superset#9302]
Currently the table view adjusts to header column width and not dynamically adjust to size of contents.
Can we get an option to adjust the size of column width accordingly.
The issue was open before but it is closed now and there was no solution provided

**Comment by ValentinC-BR** [comment]
This would indeed be a good enhancement. Tables would be more readable if we could adjust column width.

**Comment by markvh033** [comment]
Id like to second this, would be a great feature.

**Comment by schmiman** [comment]
I would like tho third this, would be useful for us.
