### ISSUE TITLE
Should we update logo profile link to `/superset/welcome`?

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#9303]
**Is your feature request related to a problem? Please describe.**

The default page after login is `/superset/welcome`, which contains a list of recently updated dashboards and a tab for recently viewed charts, where users can conveniently search them by title.

But the logo is linked to user profile page. I often get frustrated when clicking on the logo, expecting to be back to the welcome page, only to find a page where I cannot do much.

**Describe the solution you'd like**

Update the link on the logo to the home page (`/superset/welcome`). The user profile page can be added to the dropdown menu on the top right corner.

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://user-images.githubusercontent.com/335541/76669968-47d02f80-654b-11ea-85e3-7216ca929f8b.png)
This link should point to the user profile page currently linked on the logo. Its current link (`/user/userinfo`) could be put in a link called "Settings" if users are allowed to change their own info.

**Comment by ktmud** [comment]
Add reaction to vote:

👍 Yes
👎 No

**Comment by nytai** [comment]
@ktmud There's a config `LOGO_TARGET_PATH` that allows customizing this. 

I'd be in favor of changing the default though. I've just learned to click on `Dashboards` instead of the logo.
