### ISSUE TITLE
Timezone config doesn't work?

### ISSUE THREAD

**Issue by FU100** [apache/incubator-superset#9304]
Version: 0.999.0dev

### Expected results

__time = 2020-03-04T10:00:00.000Z

### Actual results

__time = 2020-03-04T02:00:00.000Z

#### How to reproduce the bug

1. in druid
__time:2020-03-04T02:00:00.000Z

2. /usr/local/src/incubator-superset# docker exec -it ef023b203bb9 /bin/bash

3. superset@ef023b203bb9:/app$ date -R
Sat, 14 Mar 2020 19:18:48 +0800
superset@ef023b203bb9:/app/superset$ cat config.py | grep DRUID_TZ
#DRUID_TZ = tz.tzutc()
DRUID_TZ = tz.gettz('Asia/Shanghai')

4. in superset 
Go to Sources->Tables->Edit Table  
Offset:8

Run Query
 get __time = 2020-03-04T02:00:00.000Z
but not 2020-03-04T10:00:00.000Z

### Environment

(please complete the following information):

- superset version: ` 0.999.0dev`
- python version: `3.6.9`
- node.js version: `node -v`
- npm version: `npm -v`

**Comment by ktmud** [comment]
"Z" in the timestamp actually means UTC time (+00:00), so whatever time zone you set, as long as the data type is timestamp, it will always return in UTC time. You can probably create a calculated column with time offset instead.

There are significant complexity revolving timezone configs. Superset decided to always UTC time to keep things simple. It'd be quite some work if we want to add custom timezone support.
