### ISSUE TITLE
Jinja template not working in explore or dashboard view on pydruid

### ISSUE THREAD

**Issue by sahiljain001** [apache/incubator-superset#9307]
when we are using jinja template in sql lab then we are getting the data but when we are using the same jinja template in explore or dashboad view then we are not getting any data

### Expected results

Jinja template should be evaluated in explore or dashboard view

**Comment by villebro** [comment]
Please fill out the standard issue template, as it is very difficult to debug this issue without accurate information regarding versions etc.

**Comment by sahiljain001** [comment]
Hi Villebro,

We are using superset 0.35.2 version. So when in sql lab editor we are using jinja template i.e a query like select * from table where client_id='{{current_username()}}' then this is giving us result in sql editor itself.

But when we are using this same jinja expression in filters section of any slice then it is not getting evaluated, no data is coming .

![jinja](https://user-images.githubusercontent.com/62089487/76829384-15734a80-6849-11ea-8215-1f7915b1df5e.png)

You can see view query is not getting avaluated:
![view_query](https://user-images.githubusercontent.com/62089487/76829481-4bb0ca00-6849-11ea-998b-ec898ecd1666.png)
Can you please share your views in this as this feature is really needed for us  because we need to show a user specific data only when he logs in to the application.

**Comment by villebro** [comment]
I  believe you should put single quotes around the expression, i.e. `clientId = '{{current_username()}}'`. Also, if you're using caching, be sure to add `cache_key_wrapper()` around `current_username()` to make sure cached resuls don't leak from one user to the next.

**Comment by sahiljain001** [comment]
Tried putting in single quotes too but no results in explore view. we are only getting result in sql labs and we are not using cache as of now.

**Comment by villebro** [comment]
Ok, thanks for the prompt answer, I will look into this asap.

**Comment by sahiljain001** [comment]
Thanks. waiting for your reply or maybe some sort of work around to achieve this.

**Comment by villebro** [comment]
I am unable to replicate on both `master` and `0.35.2`:
SQL Lab
![image](https://user-images.githubusercontent.com/33317356/76835570-033ce080-6838-11ea-8481-a86a4e7f76d7.png)
Chart:
![image](https://user-images.githubusercontent.com/33317356/76835456-cffa5180-6837-11ea-9fd1-da978bcd2b05.png)
Jinja templating seems to be applying correctly. It seems you are using Druid using the SQL connector?

**Comment by sahiljain001** [comment]
yes we are using druid for our scenario

**Comment by sahiljain001** [comment]
So it it not possible with druid?

**Comment by villebro** [comment]
Yes, it should work just like with any other sqlalchemy connector.

**Comment by sahiljain001** [comment]
But i tried it, its not working with our case. i did the same thing but for me its only working in sql labs editor. Neither in slice view nor in dashboard.

**Comment by sahiljain001** [comment]
SO when i switched to birth_names sample data which is not on druid then it worked fine for me as well but not with my data source

**Comment by villebro** [comment]
Ok thanks, this narrows the scope down, it seems the query is getting escaped prior to rendering or something similar by pydruid. I believe there was some similar problems with Presto. I'll try to look into this in the coming days.

**Comment by sahiljain001** [comment]
Ok thanks, i will be waiting for the same. :)

**Comment by sahiljain001** [comment]
also please let me know in case you find any workaround for the same because we are blocked till the time we get this functionality

**Comment by sahiljain001** [comment]
Hi Villebro, Just to let you know that when we put the expression in custom sql in filters then it works fine.

**Comment by villebro** [comment]
Ah yes, that explains it. To my knowledge jinja has to be entered in custom SQL filters, i.e. this is expected behaviour.
