### ISSUE TITLE
Time Series Bar Chart(monthly) with 1 year time shift

### ISSUE THREAD

**Issue by dpugulo** [apache/incubator-superset#9308]
Why does the monthly evaluation and 1-year time shift look like this in the time series bar chart?
Shouldn't it look next to each other as in the current month and 1 year ago?

### Expected results
appear side by side

### Actual results
bar chart separately

#### Screenshots

![image](https://user-images.githubusercontent.com/55461451/76730812-120a9100-676d-11ea-94dd-66a18b742ca9.png)

#### How to reproduce the bug

1. Go to 'Time Series Bar Chart'
2. Click on 'monthly time grain and last 7 month'
3. Scroll down to '1 year time shift'

### Environment

- superset version: Superset 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.19.0
- npm version: 6.13.4

**Comment by villebro** [comment]
@dpugulo I believe the reason here is that we are currently in the middle of March, and as such a 1 year time shift with monthly time grains will produce observations for both March 2019 and March 2020. To avoid this, a slightly custom time filter would need to be applied that only considers whole months. I haven't done anything similar, but I believe it should be possible.

**Comment by dpugulo** [comment]
same problem,
my time filter 2019-10-01 => 2020-03-31

This chart; 365 day shift
![image](https://user-images.githubusercontent.com/55461451/78509699-ba25df80-7798-11ea-89cd-b982c42594cd.png)


This chart; 1 year shift
![image](https://user-images.githubusercontent.com/55461451/78509761-1f79d080-7799-11ea-9e5c-9c58bd0ea6b9.png)

This chart; 12 month shift
![Uploading image.png…]()

**Comment by dpugulo** [comment]
i tested demo data with time series bar with 1 year/365day shift, some result

![image](https://user-images.githubusercontent.com/55461451/78662435-0d9f4700-78d9-11ea-8e3a-c57dde554db4.png)

**Comment by eugeniamz** [comment]
I am also able to reproduce in the time Series Bar Chart. Seems that it get messed up with the Leap Years. 
The most weird part is that when you put
- 365 days, it messes up with the years that ARE leap years : 
![image](https://user-images.githubusercontent.com/58375897/79135441-5180c900-7d7d-11ea-9826-8684983b1ca0.png)

- 1 Year : it messes up with the years that ARE NOT leap years : 
![image](https://user-images.githubusercontent.com/58375897/79135543-80973a80-7d7d-11ea-97a3-0b9ec390530a.png)

However, the line chart seems to work properly. This could be your workaround until the Bar Chart is fixed. 
![image](https://user-images.githubusercontent.com/58375897/79135624-a6244400-7d7d-11ea-9085-1e672973c18e.png)

**Comment by dpugulo** [comment]
> I am also able to reproduce in the time Series Bar Chart. Seems that it get messed up with the Leap Years.
> The most weird part is that when you put
> 
> * 365 days, it messes up with the years that ARE leap years :
>   ![image](https://user-images.githubusercontent.com/58375897/79135441-5180c900-7d7d-11ea-9826-8684983b1ca0.png)
> * 1 Year : it messes up with the years that ARE NOT leap years :
>   ![image](https://user-images.githubusercontent.com/58375897/79135543-80973a80-7d7d-11ea-97a3-0b9ec390530a.png)
> 
> However, the line chart seems to work properly. This could be your workaround until the Bar Chart is fixed.
> ![image](https://user-images.githubusercontent.com/58375897/79135624-a6244400-7d7d-11ea-9085-1e672973c18e.png)

Thanks for reply

**Comment by willbarrett** [comment]
Reopen please :)
