### ISSUE TITLE
Thoughts on improvements to the Filter form

### ISSUE THREAD

**Issue by the-dcruz** [apache/incubator-superset#933]
The current filter form displayed during slice creation/update currently contains three inputs:
1. Column to be filtered on
2. Type of filter to apply (in, not in, regex)
3. Value used for filtering

The 3rd input, the value, is currently a plain text field. It can be difficult for a user to figure out the appropriate value to enter without looking at a couple example values first.

I would like to change this text field into a dynamic select field that is populated with some real values from the column selected in the first input. The options will not contain all of possible values, but some reasonably sized subset that can give the user the gist of expected values.

I’d appreciate some feedback on whether it would be a useful feature. Also, if you have any thoughts on the best way to implement this, please let me know. Currently, the basic idea is to query for some column values onChange of the selected column. The select would be a FreeFormSelect so that the user is also able to enter in values that do not exist as an option, which is most likely the case for a _regex_ operation.

<img width="357" alt="screen shot 2016-08-11 at 5 13 35 pm" src="https://cloud.githubusercontent.com/assets/1399237/17609143/00a9801a-5fe7-11e6-87ab-d4db88a99826.png">

**Comment by mistercrunch** [comment]
For druid it's cheap and easy, it's a matter of running a topN query on a recent time range. 

If you were thinking about on the SQL side, you probably want a UI control that is a select multiple that is free form, and run some sort of 
```
select distinct val from(
  SELECT {col} FROM {table} LIMIT {some_constant_maybe_10k_ish}
) as qry
```
using the SqlAlchemy expression of course so it can be translated

The control would need to behave nicely event if the results haven't come back, maybe this feature can be enabled/disabled on a per-table basis?

**Comment by the-dcruz** [comment]
@mistercrunch Sounds good. That's what I have working so far. The tricky part was refactoring how each filter is rendered since it was just cloning `flt0` every time `Add Filter` was hit. The select IDs have to be unique upon render in order populate the correct dropdown. 

Enabling on a per table basis is a good idea!
Still a work in progress...

**Comment by mistercrunch** [comment]
That's a sweet feature! Seems superfluous at first but it definitely makes a huge difference.

I think the key is to cache that endpoint. If it's a free-form multi-choice select you can always enter your value by end if it's a new or long-tail value... 

The cloning part of the code is a bit nasty, feel free to redesign it if it's easy than working with it. Seems like the kind of stuff that would work nicely in React....

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 531 days. Feel free to comment and request for this issue to be reopened.
