### ISSUE TITLE
schedule mail missing

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#9334]
version=0.35.2

Before enable:
![before enable](https://user-images.githubusercontent.com/42966797/77147431-3939c900-6ab3-11ea-9fe2-8455974c5268.png)

after enable:
![after enable](https://user-images.githubusercontent.com/42966797/77147492-5a021e80-6ab3-11ea-84c8-ebe48376cbb4.png)

**Comment by lilila** [comment]
You can refer to the following [issue](https://github.com/apache/incubator-superset/issues/8201)
You need to configure it

**Comment by kalimuthu123** [comment]
@lilila its working finely

**Comment by lilila** [comment]
In this case @kalimuthu123 , can you close the issue?
