### ISSUE TITLE
Option to Remove Suggested Fields in Superset

### ISSUE THREAD

**Issue by jamesfurnary** [apache/incubator-superset#9335]
Problem: When I'm writing a query in Superset, I have to constantly hit the `esc` key to prevent Superset from auto-filling a field or table name that I don't want. 

Solution: I'd like the option to turn off the auto-fill / suggested field feature in Superset. 

![image (1)](https://user-images.githubusercontent.com/62447802/77206129-8027be80-6ab3-11ea-923c-ce255d75e0e0.png)

![image](https://user-images.githubusercontent.com/62447802/77206076-65554a00-6ab3-11ea-8a04-bef305f71492.png)

**Comment by etr2460** [comment]
@rusackas, @nytai, or @betodealmeida: any interest in implementing this?
