### ISSUE TITLE
add base_url for istio support

### ISSUE THREAD

**Issue by dark-spark2** [apache/incubator-superset#9344]
**Is your feature request related to a problem? Please describe.**
Hi,
It would be great to have the ability to change base_url of superset,
in order to support istio gateway redirection. ( To have the ability to 
go to http://address:8088/superset.
Best Regards.

**Comment by willbarrett** [comment]
Hi @dark-spark2 - thanks for the issue. Can you elaborate on your use-case for changing the base URL? Thanks!

**Comment by dark-spark2** [comment]
Hi @willbarrett - I am trying to deploy superset as docker on kubernetes cluster with istio as ingress.
In istio, the process is to define 1 gateway and allow multiple applications to access from outside the cluster through that gateway. Since the cluster contains multiple application, in order to access superset I need to create baseUrl different from root. 
The inability to change the baseUrl prevents me from accessing through the istio gw with virtual service. So the only option to access the UI is through port-forwarding, something I can not share with product team.
Thanks!

**Comment by eagle8089** [comment]
I have been trying to get superset working on istio with a different base URL. Please advice...
