### ISSUE TITLE
 The front end is built locally and cannot be run after uploading to the server？

### ISSUE THREAD

**Issue by WenQiangW** [apache/incubator-superset#9347]
question: The front end is built locally ，it can run ， but upload to the server， it can't run 

version: 0.36.0 
operateion:  
- local: cd superset-front  npm ci  && npm build   
      Generate some front-end files， then  upload all files to the server ， 
the server appears blank home page

**Comment by kalimuthu123** [comment]
@WenQiangW  give me the some detailed screenshots

**Comment by WenQiangW** [comment]
> @WenQiangW 给我一些详细的屏幕截图
some front file not find , and the home page is blank (  If  I  build in local,  it work in local , but  i upload  the generated file to server, it dont work in the server)

[![87vx2t.png](https://s1.ax1x.com/2020/03/23/87vx2t.png)](https://imgchr.com/i/87vx2t)
[![87vtHg.png](https://s1.ax1x.com/2020/03/23/87vtHg.png)](https://imgchr.com/i/87vtHg)

**Comment by durchgedreht** [comment]
Hi,
I guess this is related to some modifications of UI files (Images, JS, etc.).
I also find it very inconvenient to  modify look and feel to ones individual needs - especially addressing the OpenSource community.

As I'm using docker I ended up creating a complete dedicated dockerfile for my own customizations as the old one was kind of ... suboptimal. In the latest release I recognized a lot of work around the docker images, which is great and cleaned up a lot.

But still: Can someone elaborate which is the GOTO solution to change a UI asset in a docker production scenario?  

- fork, add files, build from scratch
- use e.g. docker, add npm (to prod!?), add the files to  image (hack dockerfile?), npm compile  
- use e.g. docker, add npm (to prod!?), add the files using volumes

It would be great to have something like a modification folder that's picked up and merged (overwrites only the added files).  This would allow in most cases to stick with release images - which you can't in the other cases (or I simply found not the right way of doing it out of the box). 

Thanks!

**Comment by willbarrett** [comment]
Hi @durchgedreht - other than updating the logo in the header, Superset does not support theming at the moment. There is no workflow recommended for customizing the look and feel of Superset at this time.
