### ISSUE TITLE
Dynamic time grain option for charts

### ISSUE THREAD

**Issue by mprabakaran** [apache/incubator-superset#9362]
**Is your feature request related to a problem? Please describe.**
We have 15 mins interval data for over 2 months, when visualizing the data for a single day it looks good as the time grain is 15 mins, But when we expand the data to view 5 days worth of data, the chart struggles to load as there are more data points (15 * 4 * 24 * 5). 

**Describe the solution you'd like**
Would be nice if there a way to dynamically adjust the time grain, say **15 mins** when I am looking at a days worth of data and time grain adjusting itself to **day** view when updating filter to view 5 or more days of data and so on

**Describe alternatives you've considered**
I don't see any alternatives at this point in time

**Additional context**

**Comment by OlafKocanda** [comment]
Are there any updates on this? Setting individual time grains like 15 or 30 minutes would be really great!
