### ISSUE TITLE
sql lab didn't select default database when open the first tab on superset

### ISSUE THREAD

**Issue by jiegzhan** [apache/incubator-superset#9369]
I setup these two parameters in `superset_config.py`
```
# The db id here results in selecting this one as a default in SQL Lab
DEFAULT_DB_ID = 7 # https://github.com/apache/incubator-superset/blob/master/superset/config.py#L512

# SQLLAB_DEFAULT_DBID
SQLLAB_DEFAULT_DBID = 7 # https://github.com/apache/incubator-superset/blob/master/superset/config.py#L521
```

I don't have any tabs, then I opened the **first** tab, superset didn't select the default database that I setup in `superset_config.py`

Is this the right way to setup default database? Or the code here didn't work? https://github.com/apache/incubator-superset/blob/master/superset-frontend/src/SqlLab/components/TabbedSqlEditors.jsx#L223

**Comment by willbarrett** [comment]
Hi @jiegzhan - please fill out all of the required information in the issue template to help the maintainers better assist you.
