### ISSUE TITLE
presto issues

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9384]
using superset for first time on 0.35.2 release , found several oddities:

1. Schema on the left shows datatype of OTHER instead of varchar(40) or decimal(38,18)

log has
2020-03-26 00:13:10,188:INFO:root:Did not recognize type varchar(300) of column country_name
2020-03-26 00:13:10,188:INFO:root:Did not recognize type varchar(40) of column ccn

2. bad auto SQLs being sent (should say TABLE not VIEW)

com.facebook.presto.sql.analyzer.SemanticException: line 1:1: Relation 'hive.sc.t2' is a table, not a view
SHOW CREATE VIEW sc.t2

3.  bad auto SQL being sent (does not filter on TIMESTAMP col properly)

com.facebook.presto.sql.analyzer.SemanticException: line 83:21: '=' cannot be applied to timestamp, varchar(23)

select a,b,c
FROM "sc"."tb"
WHERE "datestr" = '20190114'
  AND "filename" = 'Current_Book_Monthly_ASIA'
  AND "insert_time" = '2020-03-25 18:36:07.476'
LIMIT 100

4. it seems to assume schema is 'default' instead of using actual schema

com.facebook.presto.sql.analyzer.SemanticException: line 1:15: Table hive.default.current_book_monthly$partitions does not exist
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:917)
    
SELECT * FROM "current_book_monthly$partitions"
ORDER BY datestr DESC, filename DESC, insert_time DESC
LIMIT 1

5. upload csv
Unable to upload CSV file "x.csv" to table "vvv" in database "presto". Error message: (builtins.ValueError) Protocol must be https when passing a password [SQL: SHOW COLUMNS FROM "x"."vvv"]

6. tick 'allow impersonation':

(pyhive.exc.OperationalError) Unexpected status code 401 b'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<title>Error 401 Access Denied: Invalid credentials</title>\n</head>\n<body><h2>HTTP ERROR 401</h2>\n<p>Problem accessing /v1/statement. Reason:\n<pre> Access Denied: Invalid credentials</pre></p>\n</body>\n</html>\n' [SQL: SHOW SCHEMAS] (Background on this error at: http://sqlalche.me/e/e3q8)

7. /superset/welcome page has the infinite icon spinning forever

8. 
log has this error frequently

2020-03-26 00:13:14,836:WARNING:root:timeout can't be used in the current context
2020-03-26 00:13:14,836:ERROR:root:signal only works in main thread
Traceback (most recent call last):
  File "/usr/lib/python3.6/dist-packages/superset/utils/core.py", line 593, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
  File "/usr/lib64/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

9.
sqllab sometimes gives (even with a single datasource only and default db id in config.py - the db is not populated first in the dropdown):
invalid literal for int() with base 10: 'Infinity'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views/base.py", line 107, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 151, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 1055, in schemas
    db_id = int(db_id)
ValueError: invalid literal for int() with base 10: 'Infinity'

Updates:
see attached patch 
[presto.txt](https://github.com/apache/incubator-superset/files/4652959/presto.txt)

1. fixed by patch
2. from reading the code it is expected as a test for view vs table
3. still an issue
4. fixed by patch
5. fixed in 0.36
6. fixed in 0.36
7. fixed in 0.36
8.  still an issue
9.  still an issue

**Comment by willbarrett** [comment]
I'm not super familiar with Presto, but I think @villebro or @john-bodley could probably answer this question.

**Comment by elukey** [comment]
@tooptoop4 I am using Presto + Kerberos with Superset 0.35.2, I might be able to help, but can you please add more info about how to reproduce? For example, are you using kerberos? Where are you running those commands, in sql lab? If so, how is Presto configured as datasource?

**Comment by tooptoop4** [comment]
no kerberos. using ldap. i just used sqllab. seems superset is generating those queries itself for things like: data preview, column list/data types, latest partition. standard datasource connecttion was setup beforehand

**Comment by tooptoop4** [comment]
commenting out https://github.com/apache/incubator-superset/blob/0.36/superset/db_engine_specs/presto.py#L859-L862 is a workaround for point 3 error. io.prestosql.spi.PrestoException: line 31:19: '=' cannot be applied to timestamp(3), varchar(23) in Table Preview of 100 rows

"feed_date" = '2020-07-23 00:00:00.000' WHERE filter got generated instead of AND "feed_date" = date_parse('2020-07-23 00:00:00.000','%Y-%m-%d %H:%i:%S.%f')

but it means just first 100 rows get shown but not specifically 100 rows from latest partition in the table preview
