### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by petacube** [apache/incubator-superset#9390]
pip install apache-superset
-- worked fine
superset db upgrade

ImportError: cannot import name 'secure_filename' from 'werkzeug' (/Users/joe/miniconda3/lib/python3.7/site-packages/werkzeug/__init__.py)

conda install superset -c conda-forge
superset db upgrade

ImportError: cannot import name 'DatasourceName' from 'superset.utils.core' (/Users/joe/miniconda3/lib/python3.7/site-packages/superset/utils/core.py)

did anybody on the project tested install recently?

**Comment by willbarrett** [comment]
Hi @petacube - we do test install on a regular basis. Please provide all of the information requested in the bug report issue template so that the project maintainers can better assist you.

**Comment by petacube** [comment]
python 3.7
macos 10.13
anaconda distribusion. 

everything else in the initial report

**Comment by willbarrett** [comment]
Thanks @petacube - Superset does not support Python 3.7. We are on 3.6. Please try with a supported Python version and let us know if your issue persists.
