### ISSUE TITLE
Propagation of roles and permissions from Keycloak to Superset

### ISSUE THREAD

**Issue by nawazxy** [apache/incubator-superset#9393]
**Problem Description**
I was able to set up authentication via **Keycloak** thanks to a couple of Stackoverflow answers and quite satisfied with the outcome. As of now, I'm able to manage users completely via Keycloak, every newly created user in Keycloak is given the role of an **admin** by default (handled by the OIDC Custom Security Manager script) and requires either the user to sign in to Superset and downgrade his role (to Gamma) or have the admin do this for him and this isn't a very graceful solution to managing users in a production environment.

**Proposed Solution**
I was wondering it would be great if there was a way to manage Superset's roles and permissions via Keycloak as well since doing so will allow an admin to manage access to Superset from a single location as I believe this would require deep modifications to Superset's source code.

Any ideas/suggestions are welcomed :)

**Comment by ArchanaSekhar20** [comment]
.pinned

**Comment by aciccioli** [comment]
Working on that to ...

**Comment by nawazxy** [comment]
Thanks @aciccioli please keep us posted

**Comment by andreas-eberle** [comment]
Since this isn't implemented, can it be reopend?

**Comment by shubham897** [comment]
Any updates @aciccioli or @nawazxy  as of yet. I am also facing the same issue. I can create roles from Keycloak and it reflects in superset but, I can't add permissions to it. Please @aciccioli , @nawazxy  update us with the solution.

**Comment by krakzk** [comment]
Any update on the above topic?
