### ISSUE TITLE
Warning message "Action Required ..." always appearing in Explore Chart

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#9394]
The following message ("Action Required: Preview then save your chart using the ..." ) appears everytime Explore Chart view is open (pic1). 
It appears for all roles (at leat for admin and public roles) 

The same message also appears on "standalone" plots (pic2)

<img width="697" alt="Screenshot 2020-03-26 at 10 42 29" src="https://user-images.githubusercontent.com/607430/77632893-e9458100-6f4e-11ea-8c6f-0d45e3214373.png">

<img width="494" alt="Screenshot 2020-03-26 at 10 43 31" src="https://user-images.githubusercontent.com/607430/77632937-ffebd800-6f4e-11ea-9229-ba51f50524ef.png">

**Comment by villebro** [comment]
@lilila I would recommend updating the charts to use the new time range endpoints, as they will replace the old format at some point. Would that be an option in this case?

**Comment by mistercrunch** [comment]
Related: we need to upgrade the examples and re-think the design of the current solution around the time range filter control and its label. Also the term "endpoint" and the message here is confusing.  @john-bodley

**Comment by john-bodley** [comment]
@lilila just to clarify is then every time you explore a chart or every time you explore an existing chart for which the time range endpoints haven't been updated to be `[start, end)`, i.e., inclusive of start and exclusive of end? Note that this message will persist until either: 

1. You preview and re-save the chart per the messaging. 
2. The grace period for manually updating your charts has ended  per [here](https://github.com/apache/incubator-superset/blob/master/superset/config.py#L808). After which all charts will use the `[start, end)` interval.

**Comment by lilila** [comment]
Thank you @john-bodley , @mistercrunch, @villebro for your answers. 
It was my fault, if I explore the chart first, save the new chart and then create the iframe the message does not appear anymore :D .

So it is fixed!
