### ISSUE TITLE
Preserve label_colors in standalone mode

### ISSUE THREAD

**Issue by lilila** [apache/incubator-superset#9395]
Label colors are not considered when using standalone=True on Explore Chart views. 
However all labels colors are defined in the URL generated under the "iframe" tab of the explore chart view. 

If I get the chart without standalone option I get the following 
<img width="697" alt="Screenshot 2020-03-26 at 10 42 29" src="https://user-images.githubusercontent.com/607430/77633450-c7003300-6f4f-11ea-978d-87fe618d24df.png">

When standalone is set to True, the same chart loads as: 
<img width="489" alt="Screenshot 2020-03-26 at 10 42 22" src="https://user-images.githubusercontent.com/607430/77633497-d8493f80-6f4f-11ea-9c26-98649f3322cb.png">

**Comment by villebro** [comment]
Thanks @lilila , I was able to reproduce this bug, will investigate

**Comment by lilila** [comment]
any news on this issue?

**Comment by villebro** [comment]
@lilila unfortunately I wasn't able to solve this, as this part of the codebase is slightly unfamiliar to me. @graceguo-supercat do you know how this could be fixed?

**Comment by lilila** [comment]
Dear @graceguo-supercat , do you have any clue to solve this issue ? Thank you

**Comment by Neel-rishabhsoft** [comment]
@graceguo-supercat +1 on this issue. Please let me know for any possible solution on this.

**Comment by Neel-rishabhsoft** [comment]
Any update on this issue?

**Comment by lilila** [comment]
@junlincc, Do you know if there is any update on the problem of preserving label colors in Standalone (and Explore Chart) mode?

**Comment by junlincc** [comment]
@lilila Lila sorrry we probably will not fix it anytime soon. :(

**Comment by lilila** [comment]
not even for the Explore chart mode 😭?
