### ISSUE TITLE
Translation function "gettext as __" is not working

### ISSUE THREAD

**Issue by oashton** [apache/incubator-superset#9398]
The function __( is not translating.
For example the string "SQL Editor"

### Expected results

I expect the function __() applied to a string, translate the string

### Actual results

The app keeps showing the english translation

#### Screenshots

![Sin título2](https://user-images.githubusercontent.com/6887197/77690107-c926b980-6f70-11ea-8003-eab3fad23675.png)
![Sin título](https://user-images.githubusercontent.com/6887197/77690108-c9bf5000-6f70-11ea-82f7-568f22c4462a.png)

#### How to reproduce the bug

1. Change the language to spanish
2. The submenú "SQL Editor" is not translated to "Editor SQL"

### Environment

- superset version: `Superset 0.999.0dev`
- python version: `3.6.8`
- node.js version: `12.10.0`
- npm version: `6.14.2`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional comments
If I change from __() to _() the label "SQL Editor", it works
![Sin título3](https://user-images.githubusercontent.com/6887197/77690505-6550c080-6f71-11ea-93fd-5b26f4b9e5fd.png)

![Sin título4](https://user-images.githubusercontent.com/6887197/77691596-35a2b800-6f73-11ea-8011-8beb25ca4a08.png)

**Comment by venter-zhu** [comment]
maybe you have no `meaages.mo `，try this command `pybabel compile -d <the superset install path>\translations\`

**Comment by oashton** [comment]
> maybe you have no `meaages.mo `，try this command `pybabel compile -d <the superset installed path>\translations\`

Yes, I did that also: `pybabel compile -f -d superset/translations -l es`. I forgot to put it in the bug description
