### ISSUE TITLE
Want to add custom charts

### ISSUE THREAD

**Issue by puruaptus** [apache/incubator-superset#9402]
I need horizontal and vertical bar chart support, I have seen many queries related but can't find a working one.

I also want to add charts that are in d3, but can't find a good solution to guide me through it. So, please help me out. I also need to know which folder needs to changed in order to have such changes.

**Comment by jackyq2015** [comment]
You can check the example dashboard:
https://superset.incubator.apache.org/installation.html?highlight=example

Also, if you want to tweak the d3 to add your own, You need to check another repo:
https://github.com/apache-superset/superset-ui-plugins
