### ISSUE TITLE
Cat picture in documentation

### ISSUE THREAD

**Issue by clearnote01** [apache/incubator-superset#9414]
A cat picture appears in the source code at path: "docs/images/viz_thumbnails/iframe.png". Image taken from the viz gallery in documentation: https://superset.apache.org/_images/iframe.png

![image](https://user-images.githubusercontent.com/9555129/77852596-17e88380-71fd-11ea-97a3-713a781d31f7.png)

Maybe it's kept there as a joke, I don't know.

**Comment by dpgaspar** [comment]
LOL, their everywhere!

**Comment by alectrocute** [comment]
This is quite clearly not an issue.

**Comment by nawazxy** [comment]
It's called an easter egg my friend

**Comment by clearnote01** [comment]
It also shows when seeing the gallery of all visualizations, it's a rather open Easter egg then, still funny.
