### ISSUE TITLE
Statsd Logger can't load

### ISSUE THREAD

**Issue by johnseekins** [apache/incubator-superset#9420]
Based on docs here: https://superset.incubator.apache.org/installation.html#statsd-logging ...

### Expected results

Statsd logging is enabled and the host begins to send stats

### Actual results

```
2020-03-30T19:56:15.244680+00:00 daemon.info use1-superset-1 gunicorn[32388]: ImportError: cannot import name 'StatsdStatsLogger'
2020-03-30T19:56:15.252975+00:00 daemon.info use1-superset-1 gunicorn[32388]:     from superset.stats_logger import StatsdStatsLogger
```

#### How to reproduce the bug

1. Install Superset (pip3 install apache-superset)
2. Enable statsd logging (following docs
3. See error

### Environment

- superset version: `0.35.2`
- python version: `3.6.8`
- node.js version: `??`
- npm version: `??`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
I could not reproduce on master:
```
22:25 $ ipython
Python 3.7.6 (default, Dec 30 2019, 19:38:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from superset.stats_logger import StatsdStatsLogger
In [2]:
```

**Comment by songololo** [comment]
I am encountering the same error messages.

Am using the amancevice docker version (v0.37.2).

**Comment by harshgadhia** [comment]
I am getting the same error.

I am using SuperSet latest version 1.3.0

![image](https://user-images.githubusercontent.com/10794287/138008526-ef900f3f-5462-4241-a4ae-f3779ba80748.png)

**Comment by Fredmomo** [comment]
My solution to this is to add/install the [statsd package](https://pypi.org/project/statsd/) in the Superset Python environment.
