### ISSUE TITLE
Can not add or edit database

### ISSUE THREAD

**Issue by meinnamehier** [apache/incubator-superset#9430]
When I try to add or edit a database, i get the error "'NoneType' object has no attribute 'encode'" and no database is added or edited.
This happens with the demo database as well as a Snowflake database.
Clicking on "Test Connection" shows success.

### Expected results

The database is added to the list of sources

### Actual results

An error message is displayed: 'NoneType' object has no attribute 'encode'
There is no information on the console output, loglevel is "DEBUG"

#### Screenshots
<img width="1574" alt="Bildschirmfoto 2020-04-01 um 09 13 20" src="https://user-images.githubusercontent.com/17614384/78109276-2f8c5b80-73f9-11ea-91d7-0918686e4e27.png">

#### How to reproduce the bug

1. Go to Sources -> Database
2. Click on "Save"
3. See error

### Environment
Docker container

Host Information:
- superset version: latest Master branch 
- python version: 3.7.7
- node.js version: 12.8.0
- npm version: 6.11.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Host OS: MacOS Mojave 10.14.6
The Snowflake connection string looks like this: 
snowflake://USER:xxxxxxxx@nfXXXX.eu-central-1/DATABASE/PUBLIC?warehouse=WAREHOUSE&role=PRODUCTION_USER
Snowflake-SQLalchemy is installed.

**Comment by villebro** [comment]
Thanks for the bug report @meinnamehier , I am able to reproduce, will post a bugfix shortly.

**Comment by ustinovam** [comment]
And i not add mysql database
