### ISSUE TITLE
How to increase max rows download in csv (not retrieval but download)

### ISSUE THREAD

**Issue by Nathandrake01** [apache/incubator-superset#9447]
I am unable to download more than 1000 rows (though table has more than that, even the display is more than that).

How to do it. Please mention the file name to change (if any).

**Comment by willbarrett** [comment]
@Nathandrake01 if you're downloading via SQL Lab, you'll want to set a LIMIT on the query. Queries without LIMITs are automatically limited to the value of `DEFAULT_SQLLAB_LIMIT` - providing a larger LIMIT inside the query text will override that setting.

**Comment by qinlz-1** [comment]
@willbarrett Download via chart query
