### ISSUE TITLE
Timestamps are only displayed in UTC and not in local timezone

### ISSUE THREAD

**Issue by jayhjha** [apache/incubator-superset#9449]
All timestamps are only displayed in UTC and not in the local timezone. 
I found this issue from 2 years ago regarding this, but there was no resolution: https://github.com/apache/incubator-superset/issues/3928

Ideally, this should be configurable to allow users to select their timezone.
Are there any plans to support this?

**Comment by eugeniamz** [comment]
I can't reproduce it. I did this simple test.

My Database is in UTC : 

![image](https://user-images.githubusercontent.com/58375897/78840478-e6c03e00-79c8-11ea-907e-4a7f796ed3c4.png)

But when query in Superset, I am in EST, 
![image](https://user-images.githubusercontent.com/58375897/78840523-03f50c80-79c9-11ea-9b60-92a7ec406db8.png)

Seems that it shows accordingly. Can you please show an example to reproduce?

**Comment by jayhjha** [comment]
@eugeniamz Thanks for getting back to me.
My DB is in UTC as well and this is the result of my query:
<img width="310" alt="Screen Shot 2020-04-08 at 10 30 50 PM" src="https://user-images.githubusercontent.com/49882088/78861112-d15b0c00-79e8-11ea-8e37-1fa6c57189f4.png">

And the exact same query when run in SQL Lab (I am in PST)
<img width="268" alt="Screen Shot 2020-04-08 at 10 31 32 PM" src="https://user-images.githubusercontent.com/49882088/78861145-eafc5380-79e8-11ea-8672-9c96748abd9b.png">

Did you have to SET the timezone first to get the correct results? Or do anything else?

I'm using Superset 0.35.1.

**Comment by mkdym** [comment]
Same issue.
I'm using clickhouse and superset.
![image](https://user-images.githubusercontent.com/10892624/87500953-76dce600-c690-11ea-9e68-14e6323f1db6.png)
Datetime data is converted to utc timezone, I'm confused.
I have changed the superset host and container timezone to db's timezone(Asia/Shanghai).
Tried https://pypi.org/project/sqlalchemy-clickhouse-timezone/ , but no sense.

I'm using amancevice/superset:0.36.0 docker image.

**Comment by mkdym** [comment]
https://github.com/apache/incubator-superset/issues/9304#issuecomment-609524741

>There are significant complexity revolving timezone configs. Superset decided to always UTC time to keep things simple. It'd be quite some work if we want to add custom timezone support.

**Comment by poleft** [comment]
> [#9304 (comment)](https://github.com/apache/superset/issues/9304#issuecomment-609524741)
> 
> > There are significant complexity revolving timezone configs. Superset decided to always UTC time to keep things simple. It'd be quite some work if we want to add custom timezone support.

I found that this problem only occurs when using clickhouse, superset will visual local time when the datasource is mysql. I guess whether there are some bugs when connecting clickhouse

**Comment by krsnik93** [comment]
Seeing the same even without clickhouse. Using a postgresql database and while the field dtype is a `timestamp with time zone` and looks that way in the SQL Lab, when displayed on a chart, the timezone offset is just thrown away.
