### ISSUE TITLE
npm run prod error at 0.36.0rc3

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#9450]
superset version: 0.36.rc3
python version: 3.7.7
node.js version: 13.12.0
npm version: 6.14.4

F:\superset-dev\superset-frontend>npm run prod

> superset@0.36.0 prod F:\superset-dev\superset-frontend
> node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --mode=production --colors --progress

Starting type checking service...
Using 1 worker with 2048MB memory limit
   591 modules

ERROR in ./src/SqlLab/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/welcome/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/profile/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/addSlice/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('js-add-slice-container'));
|

ERROR in ./src/showSavedQuery/index.jsx 39:4
Module parse failed: Unexpected token (39:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   ReactDom.render(
>     <div>
|       <Form
|         schema={config.JSONSCHEMA}

ERROR in ./src/dashboard/index.jsx 42:16
Module parse failed: Unexpected token (42:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|

ERROR in ./src/explore/index.jsx 44:16
Module parse failed: Unexpected token (44:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.36.0 prod: `node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --mode=production --colors --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the superset@0.36.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-02T10_02_26_178Z-debug.log

**Comment by villebro** [comment]
I believe this is a duplicate of #9457 . Please check if downgrading to Node 12 fixes the problem.

**Comment by toop** [comment]
OS： win10 64
superset version: 0.36.rc3
python version: 3.7.7
node.js version: 12.16.1
npm version: 6.11.3

OS：win10 64 
superset version: 0.36.rc3
python version: 3.7.7
node.js version: 13.12.0
npm version: 6.14.4

The same error，@villebro

**Comment by WenQiangW** [comment]
I have same error , too 
superset : 0.36.rc1
node : v12.3.1
npm : 6.9.0
