### ISSUE TITLE
How to download more than 1000 rows in a csv

### ISSUE THREAD

**Issue by Nathandrake01** [apache/incubator-superset#9452]
I am unable to download more than 1000 rows (though table has more than that, even the display is more than that).

How to do it. Please mention the file name to change (if any).

**Comment by gaurav1999** [comment]
Working for me fine here, wondering if you can share the logs. For example when you superset load_example you get this example chart with 3000+ rows and it perfectly downloads.

Note: I had to change the extension as github does not support .csv
[Scatterplot3103_0020.txt](https://github.com/apache/incubator-superset/files/4422422/Scatterplot3103_0020.txt)
