### ISSUE TITLE
Apache-superset exception - click on chart gives exception

### ISSUE THREAD

**Issue by ArchanaSekhar20** [apache/incubator-superset#9453]
"/chart/add" is showing exception

cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column datasources.cluster_name does not exist
LINE 1: ...tch_values_from AS datasources_fetch_values_from, datasource...

Please help with a fix

**Comment by ArchanaSekhar20** [comment]
Still am facing the issue . please help

**Comment by eugeniamz** [comment]
@ArchanaSekhar20  I can't reproduce the issue, Does it happen with any chart or specific one? What about if you create a new chart? Maybe it is environmental, the error suggest that the chart's data source is missing a column ( cluster_name in this case).
