### ISSUE TITLE
Can't log in using 0.36.0rc3

### ISSUE THREAD

**Issue by francishemingway** [apache/incubator-superset#9457]
### Expected results

I'm able to log in.

### Actual results
Login page comes up, I enter my credentials.
<img width="481" alt="login" src="https://user-images.githubusercontent.com/45243854/78304160-11635000-750c-11ea-9218-4c5a0a258b1a.PNG">
I just see a spinner and it never goes anywhere.
<img width="475" alt="spinner" src="https://user-images.githubusercontent.com/45243854/78304148-0c060580-750c-11ea-917a-9941fe003b18.PNG">

#### How to reproduce the bug

Log in using credentials. 

To install, I followed the instructions listed here: https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization

with one exception in that I ran 
pip install https://dist.apache.org/repos/dist/dev/incubator/superset/0.36.0rc3/apache-superset-incubating-0.36.0rc3-source.tar.gz

### Environment

- superset version: 0.36.0
- python version: 3.8.2
- node.js version: v13.12.0
- npm version: 6.14.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Here's the output when I run Superset:

(venv) [francis@localhost ~]$ superset run -p 8088 --with-threads --reload --debugger -h 0.0.0.0        logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/home/francis/venv/lib64/python3.8/site-packages/flask_caching/__init__.py:188: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
 * Serving Flask app "superset" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/home/francis/venv/lib64/python3.8/site-packages/flask_caching/__init__.py:188: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 144-298-740
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:43] "GET / HTTP/1.1" 302 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:43] "GET /superset/welcome HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET / HTTP/1.1" 302 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /superset/welcome HTTP/1.1" 302 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /login/ HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/css/font-awesome.min.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/css/bootstrap.min.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/datepicker/bootstrap-datepicker.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/select2/select2.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/css/ab.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/css/flags/flags16.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/js/ab_filters.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/js/ab_actions.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/js/jquery-latest.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/js/bootstrap.min.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/datepicker/bootstrap-datepicker.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/js/ab.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/assets/images/superset-logo@2x.png HTTP/1.1" 404 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/img/flags/flags16.png HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:53] "GET /static/appbuilder/select2/select2.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 17:59:54] "GET /static/assets/images/favicon.png HTTP/1.1" 404 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 18:00:57] "GET /superset/ HTTP/1.1" 404 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 18:00:57] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 18:00:59] "GET / HTTP/1.1" 302 -
INFO:werkzeug:10.0.2.2 - - [02/Apr/2020 18:00:59] "GET /superset/welcome HTTP/1.1" 200 -

**Comment by francishemingway** [comment]
@villebro I tested the latest release candidate and I got stuck here.

**Comment by villebro** [comment]
@francishemingway  You should not be using Node 13, please downgrade to Node 12. Can you see if that solves it? If so I'll add that to the docs! Alternatively, feel free to put through a PR 🙂

**Comment by narendrans** [comment]
I faced the same issue and Node 12 makes it to work. I can confirm it.

**Comment by i2cute** [comment]
I have downgraded to Node 12 but still facing the same issue.

Node version: v12.16.1

```
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/data/superset/lib64/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/data/superset/lib64/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 234-768-526
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:28] "GET / HTTP/1.1" 302 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:28] "GET /superset/welcome HTTP/1.1" 302 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:28] "GET /login/ HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:37] "POST /login/ HTTP/1.1" 302 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:37] "GET / HTTP/1.1" 302 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:02:38] "GET /superset/welcome HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.1 - - [06/Apr/2020 18:03:49] "GET /superset/welcome HTTP/1.1" 200 -
```

**Comment by francishemingway** [comment]
Yes, it didn't work for my either to downgrade to Node 12. I think it was something to do with the building of the frontend assets as. I will close and reopen if I have a problem with the final release.
