### ISSUE TITLE
table permission is not working after table name change 

### ISSUE THREAD

**Issue by zhxjdwh** [apache/incubator-superset#9459]
### Motivation

table permission is not working after change table name,

if i change the table name,  all of users in superset can not read this table ( because no permission),
this is really bad

change table name : superset menu “Sources” -> "Tables" -> "Edit Record" -> rename the "Table Name"

superset version :  0.34

**Comment by villebro** [comment]
@zhxjdwh where are you changing the table name? In the database, or via Superset?

**Comment by zhxjdwh** [comment]
> @zhxjdwh where are you changing the table name? In the database, or via Superset?

superset menu “Sources” -> "Tables" -> "Edit Record" -> rename the "Table Name"
