### ISSUE TITLE
Superset fails Docker build using "Start with Docker" installation instructions on home page

### ISSUE THREAD

**Issue by richdevboston** [apache/incubator-superset#9467]
When I run the installation using Docker according to the instructions provided on the Installation and Configuration Page:  ( [https://superset.incubator.apache.org/installation.html] ) 

```
>> git clone https://github.com/apache/incubator-superset/
>> cd incubator-superset
>> docker-compose up
```

I get the following result: 

```
Step 13/37 : RUN /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci
 ---> Running in fc57f54ab486
: No such file or directory
ERROR: Service 'superset' failed to build: The command '/bin/sh -c /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci' returned a non-zero code: 127

```
It does not tell me what file is missing.  
Is the error referring to the 
"frontend-mem-nag.sh", the "/app/superset-frontend" or the "npm ci"
 ---> Running in fc57f54ab486

And what does the return code "127" mean?   Is this a permissions problem? 

### Expected results
The instructions work.

### Actual results

docker-compose halts at Step 17/37 with the error above.

#### How to reproduce the bug

Run command above "docker-compose up" at the command line in a Windows 10 Console with Administrator privileges.  

### Environment

(please complete the following information):

- superset version: `superset version`  latest 
- python version: `python --version`   latest v3.6.9 specified in Dockerfile
- node.js version: `node -v`  latest specified in Dockerfile
- npm version: `npm -v `specified in Dockerfile

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ no - where are the superset logs located?  ] I would have checked the superset logs for python stacktraces and included it here as text ( if there was a location by the installer given to check)
- [ yes ] I have reproduced the issue with at least the latest released version of superset.
- [ yes ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I am running Windows 10 v1903 (updated yesterday).
Docker version 19.03.8, build afacb8b

**Comment by anujit-chatterjee** [comment]
I am facing a similar issue while running Docker build github.com/apache/incubator-superset  in Step 15/37. The log says npm is failing to locate package.json in my local directory.

**Comment by eugeniamz** [comment]
I installed in Mac, Centos and Ubuntu and have no issues from clean boxes. @anujit-chatterjee  are you also in Windows?

**Comment by bocharoviliyav** [comment]
To solve this problem on my Windows 10 Pro 1909 machine i'm change Dockerfile
from:
```
RUN /frontend-mem-nag.sh && cd /app/superset-frontend && npm install
```
to:
```
# /frontend-mem-nag.sh
RUN cd /app/superset-frontend && npm install
```

**Comment by dpgaspar** [comment]
Yes I think it makes sense, that bash script will not work on windows. Are you willing to make a PR proposing a fix @bocharoviliyav ?

**Comment by lexisstv** [comment]
Is running "/frontend-mem-nag.sh" optional?

**Comment by vdmitriyev** [comment]
A possible solution / workaround suggester here - https://github.com/apache/incubator-superset/issues/8632

**Comment by vdmitriyev** [comment]
> Is running "/frontend-mem-nag.sh" optional?

I think that it's optional, because it check if you have enough resources to start all relevant docker containers. If you initially do not have enough resources for your docker, it could be that you will wait endlessly until the installation finished and nothing will be installed at the end and no error produced.

**Comment by anujit-chatterjee** [comment]
> I installed in Mac, Centos and Ubuntu and have no issues from clean boxes. @anujit-chatterjee are you also in Windows?

@eugeniamz ..No I was on Ubuntu 18.04

**Comment by fooevr** [comment]
rm superset-frontend/package-lock.json works for me.
