### ISSUE TITLE
expose dashboard without credentials

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#9470]
hi,

 i am expecting feature of creating the dashboard which are visible without using credentials
ping meif u have any ideas

Thank you

**Comment by willbarrett** [comment]
Hi @kalimuthu123 - this is not currently supported by Superset, but it is something we would like to enable in the future.

**Comment by eugeniamz** [comment]
@willbarrett  public role should not be used to have public dashboards?

**Comment by trepmag** [comment]
It should but actually the following instructions doesn't work with the actual master HEAD: https://superset.apache.org/security.html#public

**Comment by willbarrett** [comment]
bump
