### ISSUE TITLE
email scheduler is failing

### ISSUE THREAD

**Issue by miteshchavda** [apache/incubator-superset#9477]
Email scheduler is not working as expected. 

### Actual results

```Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/superset/tasks/schedules.py", line 422, in schedule_email_report
    deliver_dashboard(schedule)
  File "/app/superset/tasks/schedules.py", line 241, in deliver_dashboard
    logging.debug("deliver_dashboard 0 page_source {}".format(driver.title))
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

#### Screenshots

<img width="1630" alt="Screen Shot 2020-04-02 at 5 12 45 pm" src="https://user-images.githubusercontent.com/38026081/78539344-c3b15500-7835-11ea-8629-37ae97d39fd7.png">

#### How to reproduce the bug

I'm using master branch and having code until this commit.
https://github.com/apache/incubator-superset/commit/2d456e88ebf1ef6fe4da7bdca1e25dcf098f6533

### Environment

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.6.9`
- firefox version: `72.0`
- geckodriver version: `v0.26.0` 

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by miteshchavda** [comment]
Its working fine by replacing firefox with google chrome.

```
# Install Google Chrome
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add \
    && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get -y update \
    && apt-get -y install google-chrome-stable
# Install ChromeDriver
RUN wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/ \
    && unzip ~/chromedriver_linux64.zip -d ~/ \
    && rm ~/chromedriver_linux64.zip \
    && mv -f ~/chromedriver /usr/local/bin/chromedriver \
    && chown root:root /usr/local/bin/chromedriver \
    && chmod 0755 /usr/local/bin/chromedriver
```

**Comment by singh-ab** [comment]
@miteshchavda : I was trying this fix of yours , couldn't get it working  . Here's the issue detail - https://github.com/apache/superset/issues/12871 

Tried with firefox and chrome  . Let me know if you have inputs on this related to the `config` or the `dockerfile`
