### ISSUE TITLE
Applying filter on the box plot didn't update the view

### ISSUE THREAD

**Issue by Shubham-Shendre** [apache/incubator-superset#9478]
Applying filter on the box plot didn't update the view .

### Expected results

Should update box plot view after running query

### Actual results

Box plot only updates after saving the view.

#### How to reproduce the bug

1. Create a box plot
2. Apply filter on data
3. Run the query after applying filter
4. The box plot didn't update

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.6`
- node.js version: `latest`
- npm version: `latest`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of the superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eugeniamz** [comment]
Duplicate of this  https://github.com/apache/incubator-superset/issues/9130
