### ISSUE TITLE
Migrate to CircleCI?

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#9481]
[My](https://github.com/apache/incubator-superset/pull/9439) [PRs](https://github.com/apache/incubator-superset/pull/9439) have been stuck at Travis CI for a couple of days. Tried to rebase and close/reopen, still can't get the CI checks to go green---sometimes even when it has successfully built in Travis itself.

Should we consider moving to other CI tools? Almost all the popular open source projects I checked have been, or are now using [CircleCI](https://circleci.com/), including React, Vue.js, Gatsby, Redash, MetaBase...

A quick search on GitHub has found many GitHub projects migrated [from Travis to CircleCI](https://github.com/search?p=2&q=circleci+travis&type=Issues) at some point, but seldom the other way around. There were chatters about [Travis going through some hardship](https://news.ycombinator.com/item?id=19218036), too.

CircleCI offers free builds for open source projects just like Travis. They also have an [official migration guide](https://circleci.com/docs/2.0/migrating-from-travis/), which should make things easier.

---

Can those who used CircleCI before comment on their experiences?

**Comment by nytai** [comment]
@ktmud I believe the travis choice is due to to apache's rules. I think the main issue with travis is the limited resources for apache owned repos. If there are various other builds occuring in the apache org then things can grind to a halt and it can be quite frustrating. While CircleCi is probably better maintained than travis and their tooling and performance is likely better I'm not sure the migration would completely solve these pains

**Comment by nytai** [comment]
Actually, looking at your PRs it appears the issue is travis isn't updating the github status check after it passes. That's definitely a headbanger. Maybe reopen the PR in another branch?

**Comment by ktmud** [comment]
Just created [a new PR with a new branch](https://github.com/apache/incubator-superset/pull/9482) and it's still stuck...

As @kristw mentioned to me offline, another choice is to use GitHub Actions. Indeed, it seems no Apache projects are currently using CircleCI. Some of them had CircleCI configs checked in the code, but it's not active running, at least not on GitHub.

There are some Apache projects already using GitHub Actions, including [Spark](https://github.com/apache/spark/pull/25440),  [incubator-dolphinscheduler](https://github.com/apache/incubator-dolphinscheduler/issues/826), [incubator-echarts](https://github.com/apache/incubator-echarts/runs/555100811),  and [Groovy](https://github.com/apache/groovy/commits/master/.github/workflows). It's also completely free and seems pretty easy to set up. 

Should we give it a try?

**Comment by villebro** [comment]
@ktmud I agree that things could be better with CI right now. I don't have strong feelings about CI platforms, but anything that gets the job done quickly, reliably and is ok'ed by Apache gets my vote.

**Comment by nytai** [comment]
Github actions looks really promising, 👍 from me

**Comment by dpgaspar** [comment]
+1 for github actions. We can go side by side for a while and see how it goes
