### ISSUE TITLE
Error：superset load_examples

### ISSUE THREAD

**Issue by binbinyounimen** [apache/incubator-superset#9488]
OS：CentOS Linux release 7.7.1908 (Core)
I operate according to the [manual](https://superset.incubator.apache.org/installation.html)。

- pip install apache-superset

- superset db upgrade

- export FLASK_APP=superset

- flask fab create-admin
`It's fine up to here`

- superset load_examples
`This is where the error starts`

### Expected results

Load some data to play with

### Actual results

> 2020-04-08 10:22:09,186:INFO:root:logging was configured successfully
2020-04-08 10:22:09,578:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
2020-04-08 10:22:11,688:INFO:root:Database.get_sqla_engine(). Masked URL: sqlite:////home/***/.superset/superset.db
Creating table [wb_health_population] reference
Loading [World Bank's Health Nutrition and Population Stats]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/python3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/python3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "/home/***/python37/bin/superset", line 31, in <module>
>     cli()
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/flask/cli.py", line 586, in main
>     return super(FlaskGroup, self).main(*args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
>     return __ctx.invoke(f, *args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/***/python37/lib/python3.7/site-packages/superset/cli.py", line 142, in load_examples
>     load_examples_run(load_test_data, only_metadata, force)
>   File "/home/***/python37/lib/python3.7/site-packages/superset/cli.py", line 86, in load_examples_run
>     examples.load_world_bank_health_n_pop(only_metadata, force)
>   File "/home/***/python37/lib/python3.7/site-packages/superset/examples/world_bank.py", line 52, in load_world_bank_health_n_pop
>     data = get_example_data("countries.json.gz")
>   File "/home/***/python37/lib/python3.7/site-packages/superset/examples/helpers.py", line 73, in get_example_data
>     content = request.urlopen(f"{BASE_URL}{filepath}?raw=true").read()
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 563, in error
>     result = self._call_chain(*args)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 755, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 563, in error
>     result = self._call_chain(*args)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 755, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 1362, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/usr/local/python3/lib/python3.7/urllib/request.py", line 1321, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

#### Screenshots

![image](https://user-images.githubusercontent.com/45166250/78738962-cb800f00-7985-11ea-87f7-714b558e2eee.png)

#### How to reproduce the bug

1 pip install apache-superset
2 superset db upgrade
3 export FLASK_APP=superset
4 flask fab create-admin
5 superset load_examples

### Environment

(please complete the following information):

- superset version: `Superset 0.35.2`
- python version: `Python 3.7.7`
- node.js version: `uninstall`
- npm version: `uninstall`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [N] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [N] I have reproduced the issue with at least the latest released version of superset.
- [N] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by mistercrunch** [comment]
I'm pretty sure that means that your process can't connect to your example database.

**Comment by binbinyounimen** [comment]
I built an http service locally. solved this problem。Think You

**Comment by sundroid2020** [comment]
> I built an http service locally. solved this problem。Think You

Can you explain more please because I am facing the same issue now

**Comment by BigDataMind** [comment]
![2020-05-05_112036](https://user-images.githubusercontent.com/39152138/81032459-7a9b0200-8ec2-11ea-9184-b397af80fd6c.png)

Environment
python version: Python 3.6.64

**Comment by reesezxf** [comment]
> I built an http service locally. solved this problem。Think You

I also want load examples data from local,but I do not konw how to do. Can you explain in detail, any way thank you.

**Comment by malone6** [comment]
这个问题实际是由于初始化需要的数据是用github下载的，而在中国大陆访问有限制导致下载失败，如果你对python比较熟悉的话，不难调查出此问题。
![image](https://user-images.githubusercontent.com/15245112/92353655-676b9d80-f113-11ea-9461-82b6b0b3ff30.png)
解决办法就是是墙外从github下载样例数据，将数据在本地启动一个http文件服务，修改BASE_URL为本地地址即可，启动方式可以了解下python的内置库http.server，或者其他工具也可以

**Comment by weidongkl** [comment]
> 这个问题实际是由于初始化需要的数据是用github下载的，而在中国大陆访问有限制导致下载失败，如果你对python比较熟悉的话，不难调查出此问题。
> ![image](https://user-images.githubusercontent.com/15245112/92353655-676b9d80-f113-11ea-9461-82b6b0b3ff30.png)
> 解决办法就是是墙外从github下载样例数据，将数据在本地启动一个http文件服务，修改BASE_URL为本地地址即可，启动方式可以了解下python的内置库http.server，或者其他工具也可以

牛皮

**Comment by geosmart** [comment]
1. start a vpn server at localhost with http proxy 
2. set docker network= host  add HTTPS_PROXY env to run superset container

example
```
sudo docker run -d --network host -p 8080:8080 --env HTTP_PROXY="http://127.0.0.1:7890" --env HTTPS_PROXY="http://127.0.0.1:7890" --name superset apache/superset  
```

**Comment by hengaini2055** [comment]
@malone6 我遇到这类似的问题。我是在虚拟机ubuntu安装的superset，我设置了ssh，这样在命令行可以通过git clone来从github.com下载库。如果是通过 superset load_example，来从github.com来下载内容，就是失败的，导致了load_examples失败。我是搞不明白，这样在superset load_example下载github.com的内容，不是使用git clone这样的办法吗？最近别的项目也牵扯类似的问题。望赐教！

**Comment by fzh075** [comment]
In addition to the BASE_URL mentioned above by @malone6 , there's also this pile of "data" that needs to be changed. It took me a total of two days to solve this problem😩

Maybe I can add this to the Installation directory in the documentation?

![image](https://github.com/user-attachments/assets/9464d088-b095-4a54-8feb-8c01618bb002)

**Comment by fzh075** [comment]
有没有人是通过直接给 docker 设置代理来解决这个问题的？我尝试给 docker 加了 HTTP_PROXY 环境变量，但是报了一个“ssh”错误。因为问题已经解决，就不想深究了。如果有人知道，希望可以指导一下如何操作。

Has anyone solved this issue by setting up proxies directly to docker? I tried to add the HTTP_PROXY environment variable to docker, but encountered an "ssh" error. Because the problem has been solved, I don't want to go into it. If anyone knows, Id appreciate some guidance on the process.

**Comment by malone6** [comment]
> In addition to the BASE_URL mentioned above by [@malone6](https://github.com/malone6) , there's also this pile of "data" that needs to be changed. It took me a total of two days to solve this problem😩
> 
> Maybe I can add this to the Installation directory in the documentation?
> 
> ![image](https://github.com/user-attachments/assets/9464d088-b095-4a54-8feb-8c01618bb002)

Great idea. I think you can try submitting a PR to this project which will be save a lot of time for other user(I haven't use this product for a long time).

**Comment by tianyang-abc** [comment]
> 这个问题实际是由于初始化需要的数据是用github下载的，而在中国大陆访问有限制导致下载失败，如果你对python比较熟悉的话，不难调查出此问题。 ![image](https://user-images.githubusercontent.com/15245112/92353655-676b9d80-f113-11ea-9461-82b6b0b3ff30.png) 解决办法就是是墙外从github下载样例数据，将数据在本地启动一个http文件服务，修改BASE_URL为本地地址即可，启动方式可以了解下python的内置库http.server，或者其他工具也可以


同样遇到大陆防火墙的困扰，我的解决办法：
1. 使用自有vpn。
2. 检查 github.com 和 raw.githubusercontent.com 两个域名的DNS，不行就直接写死。
3. 使用proxychains解决python request()默认不使用代理设置环境变量问题。例如：proxychains superset load_examples

💯大家开心
