### ISSUE TITLE
Dashboards View on welcome page shows loading gears if there is no dashboards available in the list

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9489]
see https://github.com/apache/incubator-superset/issues/7457

**Comment by dpgaspar** [comment]
Hi @tooptoop4,

I'm not able to reproduce, can you please add more info? Would help to fill the proposed issue template

**Comment by tooptoop4** [comment]
install brand new superset (v 0.35.2) then go to main url. it will show loading.gif (spinning infinite logo in the middle of the screen) forever, you can still click on other links and after creating first dashboard the loading.gif will disappear

**Comment by dpgaspar** [comment]
Yes, I'm able to reproduce it, just check master does not have this issue and new 0.36.0 (about to be release) is safe from this also.
