### ISSUE TITLE
Filter box on a metric

### ISSUE THREAD

**Issue by jpetot** [apache/incubator-superset#9502]
Hi, 

I want to create a filter box for my dashboard. 
I want to apply the filter control on a metrics (not a columns)

### Expected results

I expect metric or custom sql space in the filter controls bar 

### Actual results

currently I can only choose my columns

#### Screenshots

![Capture d’écran 2020-04-10 à 16 19 14](https://user-images.githubusercontent.com/48205834/78997778-8572a900-7b47-11ea-9e1c-0294ca97cedd.png)

### Environment

(please complete the following information):

- superset version: `superset website`
- python version: `python --3.7`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by thunderbird57** [comment]
I have exactly same problem

**Comment by mistercrunch** [comment]
The filter box "visualization" could have an option to reuse the `FilterControl`. In theory this should work

**Comment by mistercrunch** [comment]
Workaround idea: creating a "bracket" column either as a physical column or as an expression.

**Comment by thunderbird57** [comment]
> Workaround idea: creating a "bracket" column either as a physical column or as an expression.

Yes this work in cases where we have static ranges known. We have created some calculated columns to define filter ranges and then use it dimension filters.

**Comment by mistercrunch** [comment]
Longer term we want to make filter box as a dashboard native component and completely redesign it. [SIP-34](https://github.com/apache/incubator-superset/issues/8976) touches on some ideas around contextual filter bars.
