### ISSUE TITLE
Chart embedding without using iframe

### ISSUE THREAD

**Issue by DSquareTechnologies** [apache/incubator-superset#9504]
Hi, request help for understanding how superset charts / dashboard can be embedded in other sites / application without using iframe?

Thanks

**Comment by eugeniamz** [comment]
:label .question

**Comment by eugeniamz** [comment]
🏷️ .question

**Comment by eugeniamz** [comment]
🏷️ #question

**Comment by eugeniamz** [comment]
🏷️ #questions
