### ISSUE TITLE
Error: Could not import "superset.superset"

### ISSUE THREAD

**Issue by jvcson** [apache/incubator-superset#9528]
I have installed superset using `pip install apache-superset` on windows10. 
Then i try to `flask fab create-admin` but it's saying : `Error: Could not import "superset.superset"`.

Can anyone help me here?

#### How to reproduce the bug

1. (superset) D:\dev\python\python_vir_env\superset\Lib\site-packages\superset>set FLASK_APP=superset
2. (superset) D:\dev\python\python_vir_env\superset\Lib\site-packages\superset>set FLASK_APP
FLASK_APP=superset
3. (superset) D:\dev\python\python_vir_env\superset\Lib\site-packages\superset>flask fab create-admin
 Username [admin]:
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 1
Password:
Repeat for confirmation:
2020-04-14 18:09:56,324:INFO:root:logging was configured successfully
2020-04-14 18:09:56,488:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Usage: flask fab create-admin [OPTIONS]

Error: Could not import "superset.superset".

### Environment

(please complete the following information):

- superset version: `apache-superset-0.35.1`
- python version: `Python 3.6.6`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi,

Windows is not supported, yet try running `superset fab create-admin`

**Comment by jvcson** [comment]
> Hi,
> 
> Windows is not supported, yet try running `superset fab create-admin`

Thank you very much about your answer,The problem has fixd,Thank you very much again.

(superset) D:\dev\python\python_vir_env\superset\Lib\site-packages\superset\bin>python superset fab create-admin
2020-04-14 19:33:20,482:INFO:root:logging was configured successfully
2020-04-14 19:33:20,697:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Username [admin]:
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 
Password:
Repeat for confirmation:
Recognized Database Authentications.
Admin User admin created.

**Comment by dpgaspar** [comment]
No problem, enjoy superset
