### ISSUE TITLE
Discussion Forum for apache superset?

### ISSUE THREAD

**Issue by gferrette** [apache/incubator-superset#9534]
Hello!

Is there a discussion forum for apache superset? i.e "discourse"

Thanks!

**Comment by willbarrett** [comment]
Hi @gferrette - we do not have a discourse forum for Superset, but we do have a Slack group and a mailing list, both linked from the project's README: here's a deep link to the relevant section: https://github.com/apache/incubator-superset/#resources

**Comment by gferrette** [comment]
Thanks willbarret!

I'll join the slack.
