### ISSUE TITLE
Unknown error returned when a Alpha user tries to use Sqllab

### ISSUE THREAD

**Issue by elukey** [apache/incubator-superset#9543]
Hi!
I have recently tried to debug why users where not able to use Presto (configured as database via sql alchemy) in Sqllab. They reported an "Unknown error" reported as big red box when accessing the Sqllab. I discovered later on that this was due to the absence of the sqllab role, but I think that the error message should be more clear (like "you don't have permissions to do this etc..". 

Also, I see that Alpha has a lot of permissions for the Sqllab (listed in the role definition), but the most important ones are missing to allow users to query data. I get why one would want to selectively allow access to sqllab and not grant it by default, but wouldn't it be better all or nothing?

For example, the sqllab role in my Superset allows:
can search queries on Superset,
can sql json on Superset,
can csv on Superset, 
menu access on SQL Lab, 
can sqllab on Superset, 
can sqllab viz on Superset, 
menu access on SQL Editor, 
menu access on Query Search, 
menu access on Saved Queries, 
can list on UserDBModelView, 
can list on UserRemoteUserModelView

And only the following are not in Alpha:
can sql json on Superset
menu access on SQL Lab
can list on UserDBModelView
can list on UserRemoteUserModelView

### Expected results

A clear error about permissions, that leads an admin to the proper debugging. 

### Actual results

A general "Unknown error" is displayed, without any trace of it in the logs (to gather further info).

#### How to reproduce the bug

1. Alpha user goes to the Sqllab
2. Alpha user tries to use any database, getting Unknown Error

### Environment

(please complete the following information):

- superset version: latest

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by elukey** [comment]
In the JS console I see the following:

```
Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
```

**Comment by gauravencoded** [comment]
I am facing similar issues I need urgent help

**Comment by elukey** [comment]
For me the issue was fixed simply adding `menu access on SQL Lab` and `menu access on SQL Lab` to the Alpha permssions.

**Comment by DRavikanth** [comment]
So, you need to select all the needed database actions for Alpha role to avoid running into this problem. In my case, `can sql json on Superset` is not included for Alpha role, once added its all good.
