### ISSUE TITLE
Translations are not working

### ISSUE THREAD

**Issue by fjcobo** [apache/incubator-superset#9546]
Translations are not working for the most UI elements.

- Superset version 0.35.2 with this configuration:

```
BABEL_DEFAULT_LOCALE = "es"
BABEL_DEFAULT_FOLDER = "superset/translations"
LANGUAGES = {
    "es": {"flag": "es", "name": "Spanish"},
}
```
I have also tried other languages ​​and the result is the same. For example, from the top menu, only the Security combobox is translated correctly. The rest of the elements are in English permanently.

**Comment by dpgaspar** [comment]
Hi @fjcobo,

This seems like a problem with the release process itself. Thank you for reporting.

Meanwhile you can fix it by using:
```
superset fab babel-compile --target venv/lib/python3.6/site-packages/superset/translations
```
replace `venv/lib/python3.6/site-packages/` with the path to your venv

**Comment by fjcobo** [comment]
Hi @dpgaspar 

Thanks for the reply. The command runs correctly but I don't get the expected result.

**Comment by cdmikechen** [comment]
@fjcobo 
You can see this link https://github.com/cdmikechen/incubator-superset/blob/0.35-syzh/README-%E6%B1%89%E5%8C%96.md
