### ISSUE TITLE
Unable to start with Apache Superset when trying with the command docker-compose up 

### ISSUE THREAD

**Issue by Michael3190** [apache/incubator-superset#9554]
File
"/usr/local/lib/python3.6/urllib/request.py".py,line 1361,in https_open superset-init_1 | context=self._context,check_hostname=self._check_hostname) superset-init_1 | File "/usr/local/lib/python3.6/urllib/request.py", line 1283 , in do_open superset_init_1 | raise URLError('no host given') superset_init_1 | urllib.error.URLError: <urlopen error no host given >

**Comment by dpgaspar** [comment]
Hi,

Please post the full (or a bigger chunk) log to help us troubleshoot
