### ISSUE TITLE
FilterBox is not working as expected

### ISSUE THREAD

**Issue by cah-arunkumarpasula** [apache/incubator-superset#9557]
I was confused about the filter box functionality.I have a dashboard with two three charts, one of which is filterbox used to filter the other two.

When I select a value from filter, then change it and select another value, seems the chart is taking in the previous filter value too resulting in malformed sql and no data for that chart.

### Expected results

When I select a value from the filter the query under the hood should consider only the same and return the results if any

### Actual results

say I select CVS pharmacy from filterbox field to see the stats for them . I have two other charts in the dashboard. This works fine and next when I select another pharmacy, say, Walgreens by clearing previous filter..the chart says no data which is not correct.

This is because the query formed under the hood for the chart with no data when I click on explore chart shows me  filters like this:
IN(CVS PHARMACY)
IN(WALGREENS)
instead of just one IN condition

I selected : 
![image](https://user-images.githubusercontent.com/42588955/79453185-53ce6780-7fb7-11ea-811e-c800bcf0b067.png)

Chart with No Data has the filters:
![image](https://user-images.githubusercontent.com/42588955/79453038-19fd6100-7fb7-11ea-89cd-6a845df5e9bf.png)

WALGREENS was selected previously but I cleared it off and selected only CVS.

**Comment by ramdesh** [comment]
Just to add some context to this, in the above filter, the first run sends out the correct filters, but on clicking 'clear' and choosing another filter, it seems to send the old filters to the backend as well. Here is the `form_data` that is sent to the backend:

```
{"datasource":"446__table","viz_type":"dist_bar","slice_id":435,"granularity_sqla":"year","time_grain_sqla":"P1D","time_range":"100 years ago : ","metrics":[{"aggregate":"COUNT","column":{"column_name":"centerID","description":null,"expression":null,"filterable":true,"groupby":true,"id":5699,"is_dttm":false,"optionName":"_col_centerID","python_date_format":null,"type":"INT","verbose_name":null},"expressionType":"SIMPLE","fromFormData":true,"hasCustomLabel":true,"label":"Total Pharmacies","optionName":"metric_1aiyetjyng4_9dblxojmirk","sqlExpression":null}],"adhoc_filters":[{"clause":"WHERE","comparator":["WALGREENS DRUG STORE               ","ACME PHARMACY                      "],"expressionType":"SIMPLE","filterOptionName":"aa4d0ae1-36b0-4483-812d-4e12d71ebe42","operator":"in","subject":"chainNM"}],"groupby":["year","quarter"],"columns":[],"row_limit":1000,"contribution":false,"color_scheme":"bnbColors","label_colors":{"Total Pharmacies":"#ff5a5f"},"show_legend":true,"show_bar_value":false,"bar_stacked":false,"order_bars":true,"y_axis_format":"SMART_NUMBER","y_axis_label":"total pharmacies","show_controls":false,"x_axis_label":"time","bottom_margin":"auto","x_ticks_layout":"auto","reduce_x_ticks":true,"extra_filters":[{"col":"chainNM","op":"in","val":["CVS PHARMACY INC                   "]}]}
```

**Comment by cah-arunkumarpasula** [comment]
I still see the issue. Appreciate any help.

**Comment by mistercrunch** [comment]
I could not reproduce. I used the "World Bank Data" example and added / removed filters hoping to recreate and couldn't. What version are you on? Can you reproduce against `master`?

**Comment by Dragonwarrior47** [comment]
@cah-arunkumarpasula cah-arunkumarpasula  I am also facing this issue how did you resolve it.
