### ISSUE TITLE
Running setup.py install for python-geohash ... error

### ISSUE THREAD

**Issue by kumarprahlad** [apache/incubator-superset#9558]
Running setup.py install for python-geohash 
```
... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nhtndi9s/python-geohash/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nhtndi9s/python-geohash/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wzqmtao9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/python-geohash
         cwd: /tmp/pip-install-nhtndi9s/python-geohash/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying geohash.py -> build/lib.linux-x86_64-3.6
    copying quadtree.py -> build/lib.linux-x86_64-3.6
    copying jpgrid.py -> build/lib.linux-x86_64-3.6
    copying jpiarea.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_geohash' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPYTHON_MODULE=1 -I/usr/include/python3.6m -c src/geohash.cpp -o build/temp.linux-x86_64-3.6/src/geohash.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nhtndi9s/python-geohash/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nhtndi9s/python-geohash/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wzqmtao9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/python-geohash Check the logs for full command output.
```

**Comment by kumarprahlad** [comment]
unable to implement requirement and other commands it keep on showing this error.

**Comment by dpgaspar** [comment]
Seems like you need gcc first:
```
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
```

https://superset.apache.org/installation.html#os-dependencies

**Comment by kumarprahlad** [comment]
tried gcc installations commands it is showing :

No package build-essential available.
No package libssl-dev available.
No package libffi-dev available.
No package python-dev available.
No package libsasl2-dev available.
No package libldap2-dev available.
Nothing to do

**Comment by rajeshkorandla** [comment]
@dpgaspar, I have the same issue and I have installed the OS dependencies. Any help with this?

**Comment by mistercrunch** [comment]
Well you'll need gcc, you can test whether you have gcc installed with`$ gcc -v`.

**Comment by rajeshkorandla** [comment]
@mistercrunch  this is what I have - gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC)

**Comment by mstainsbury** [comment]
I also have this problem. I have attached the error output. gcc is installed.
[Apache Superset install error.txt](https://github.com/apache/incubator-superset/files/4830727/Apache.Superset.install.error.txt)

**Comment by willbarrett** [comment]
This appears to be an error with the `python-geohash` dependency related to your environment. I recommending reaching out at https://github.com/hkwi/python-geohash for support.

**Comment by leonardogmachado** [comment]
I got this error in CentOS and python 3.6

I solved this after installed the OS dependencies (changing to python3):

sudo yum install gcc gcc-c++ libffi-devel **python3**-devel **python3**-pip **python3**-wheel openssl-devel cyrus-sasl-devel openldap-devel

**Comment by willbarrett** [comment]
Awesome. Closing.

**Comment by deepak13tekwani** [comment]
> I also have this problem. I have attached the error output. gcc is installed. [Apache Superset install error.txt](https://github.com/apache/incubator-superset/files/4830727/Apache.Superset.install.error.txt)

can you find the solution for this?

**Comment by baharmf93** [comment]
I have such an error.
This package uses codes from 10 years ago ([python-geohash](https://github.com/hkwi/python-geohash)) !!!!

**Comment by baharmf93** [comment]
> I got this error in CentOS and python 3.6
> 
> I solved this after installed the OS dependencies (changing to python3):
> 
> sudo yum install gcc gcc-c++ libffi-devel **python3**-devel **python3**-pip **python3**-wheel openssl-devel cyrus-sasl-devel openldap-devel

It does not work for me.
How do I do it in Linux?

**Comment by userkdg** [comment]
if ptyhon==3.9
   sudo dnf install gcc gcc-c++ libffi-devel python39-devel python39-pip python39-wheel openssl-devel cyrus-sasl-devel openldap-devel
if python==3.8
   sudo dnf install gcc gcc-c++ libffi-devel python38-devel python38-pip python38-wheel openssl-devel cyrus-sasl-devel openldap-devel

**Comment by mistercrunch** [comment]
Highly recommend using docker-compose for dev and docker images in production. This shouldn't be an issue in our official docker
