### ISSUE TITLE
Imported Dashboards become immutable Dashboard

### ISSUE THREAD

**Issue by chesterxgchen** [apache/incubator-superset#9561]
Version: Superset 0.34

Here is the use case
1) first export the dashboard Json file from UI, then delete the dashboard
2) then imported dashboard Json file back to system  from command line. 
3) now, go to the newly imported dashboard and try to update of the chart in the dashboard. You will find that you can not save it to the existing chart and can't save the existing dashboard.  If you use the same chart title as old one, a new chart with the same name will be created instead update the existing one. If you pick the save to existing dashboard option,  existing dashboards are not in the drop down list,  thus you can't save to the existing dashboard. 

In other words, the dashboard becomes immutable. 

### Expected results
Able to continue edit charts and save the update charts to existing dashboard
what you expected to happen.
Able to continue edit charts and save the update charts to existing dashboard
### Actual results
can not update chart and dashboard
what actually happens.
can not update chart and dashboard

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eugeniamz** [comment]
I just tried with the latest master and it worked just fine, I was able to modify a chart and also to add new charts to imported dashboard. I am an admin on the workspace.

**Comment by willbarrett** [comment]
@chesterxgchen please try again with the most recent Superset release (0.36) and let us know if the problem continues. Closing until then.
