### ISSUE TITLE
Unable to start to apache superset .when trying for the command docker-compose up

### ISSUE THREAD

**Issue by Michael3190** [apache/incubator-superset#9564]
File
"/usr/local/lib/python3.6/urllib/request.py".py,line 1361,in https_open superset-init_1 | context=self._context,check_hostname=self._check_hostname) superset-init_1 | File "/usr/local/lib/python3.6/urllib/request.py", line 1283 , in do_open superset_init_1 | raise URLError('no host given') superset_init_1 | urllib.error.URLError: <urlopen error no host given >

**Comment by Michael3190** [comment]
npm ERR: code ENOENT
npm ERR:errno ENOENT
npm ERR:enoent request to https://registry.npm.js.org/kind of failed

**Comment by willbarrett** [comment]
Hi @Michael3190 - I have not seen this error before. Please try again with the latest master and let us know your results. If the problem continues, please share details of your execution environment. Thanks!

**Comment by willbarrett** [comment]
Closing as we have not been able to reproduce.
