### ISSUE TITLE
postgresql database connect ok but tables not shown

### ISSUE THREAD

**Issue by sunnysnowhi** [apache/incubator-superset#9565]
I install the superset in my CentOS server, and login from web successfully. 
And then I add the database and check connection, the check result is "seems ok!"
![image](https://user-images.githubusercontent.com/52787424/79543414-fe31b200-80bf-11ea-8d25-27bbb0bdcd10.png)

but at the bottom , the table list is empty!
![image](https://user-images.githubusercontent.com/52787424/79542550-7303ec80-80be-11ea-92bc-1d4fb2e45004.png)

when I click 'Tables' and search , there is still no result 
![image](https://user-images.githubusercontent.com/52787424/79542604-857e2600-80be-11ea-9e9c-268e61265919.png)

my database is postgresql,  and I tried both the url "postgresql://" and "postgresql+psycopg2:// ", the connect is all ok and tables are all not shown.

 I am sure I have some tables in my database, what's wrong?

Thank you!

**Comment by sunnysnowhi** [comment]
and no error log on the server screen 
![image](https://user-images.githubusercontent.com/52787424/79543618-5b2d6800-80c0-11ea-9546-b61fb9ab1d4c.png)

**Comment by eugeniamz** [comment]
@sunnysnowhi , In tables you see the tables that YOU add. It does not automatically load there. 
SQL Lab -> SQL Editor is the only place that the tables get automatically filled so you can do queries to explore the data, as in this : 
![image](https://user-images.githubusercontent.com/58375897/79787529-25cd8800-8315-11ea-85b8-0960e0d697e2.png)

But  in tables are just the tables that you upload to do charts.

**Comment by sunnysnowhi** [comment]
@eugeniamz thank you very much, table must add manually!
Click the + button in Tables
![image](https://user-images.githubusercontent.com/52787424/80576932-991f7a00-8a38-11ea-9a99-09facb4aa258.png)

And choose the database , then write the table name here and save
![image](https://user-images.githubusercontent.com/52787424/80577132-f4516c80-8a38-11ea-8faf-9d6bd7cf7c7e.png)

Then the table will display here~~
![image](https://user-images.githubusercontent.com/52787424/80577206-14812b80-8a39-11ea-90e7-1be1fb65e93e.png)

**Comment by stardev24** [comment]
@eugeniamz 
I am trying to add Postgres database table.Even though I have table in my database while adding
it manually into superset tables I am getting table not found error.
**Error:**
Table [public.trail] could not be found, please double check your database connection, schema, and table name

Please find the attached screenshots

![TableReferenceInPGAdmin](https://user-images.githubusercontent.com/13711150/81787871-4a391080-951f-11ea-99e0-9b4ce7be3a04.png)
![TableError](https://user-images.githubusercontent.com/13711150/81787879-4d340100-951f-11ea-8a4b-cf6519acdb91.png)

**Comment by PetengDedet** [comment]
Superset uses SQLAlchemy Schema. It returns connection OK on postgres even without defining dbname at the end.
In order to show tables on that db, we need to specify dbname after port number:
```
postgresql://<username>:<password>@<host>:<port>/<db_name>
```

**Comment by zhaoyongjie** [comment]
> @eugeniamz thank you very much, table must add manually!
> Click the + button in Tables
> ![image](https://user-images.githubusercontent.com/52787424/80576932-991f7a00-8a38-11ea-9a99-09facb4aa258.png)
> 
> And choose the database , then write the table name here and save
> ![image](https://user-images.githubusercontent.com/52787424/80577132-f4516c80-8a38-11ea-8faf-9d6bd7cf7c7e.png)
> 
> Then the table will display here~~
> ![image](https://user-images.githubusercontent.com/52787424/80577206-14812b80-8a39-11ea-90e7-1be1fb65e93e.png)

Please check the Postgresql schema settings. Try filling in `public` in the Schema input box.
