### ISSUE TITLE
Sybase SQL Lab Limit

### ISSUE THREAD

**Issue by wisefool769** [apache/incubator-superset#9573]
queries to Sybase in SQL Lab don't work because there is an automatically applied row limit. Because there is no db_engine_spec for Sybase, the default limit syntax of appending "limit 1000" causes a SyntaxError. 

### Expected results

Query to configured Sybase datasource succeeds

### Actual results
('42000', "[42000] [FreeTDS][SQL Server]Erro do SQL Anywhere -131: Erro de sintaxe próximo de 'LIMIT' na linha 32\x00 (102) (SQLExecDirectW)")

#### How to reproduce the bug

1. Configure a sybase datasource using the syntax sybase+pyodbc://user:passwd@database 
2. Run any query in SQL Lab

### Environment

(please complete the following information):

- superset version: 0.35.2
- python version: 3.6.7
- node.js version: 0.15.2
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This [issue](https://github.com/apache/incubator-superset/issues/7440) is related. 
I tried writing a sybase db_engine_spec which basically copies the mssql engine spec, and that seems to resolve the error.

**Comment by villebro** [comment]
Thanks @wisefool769 ! I have a few small suggestions, I will give this a review pass today.
