### ISSUE TITLE
Set batch size for impala connections

### ISSUE THREAD

**Issue by carloVentrella** [apache/incubator-superset#9575]
When connecting to Impala, the default batch size in impyla is 1024. For large resultsets this can be a bottleneck and it would be useful to add the possibility to tune it via config file (e.g. an `IMPALA_BATCH_SIZE` parameter).

Since `BaseEngineSpec` already handles the batchsize (i.e. arraysize) in the `fetch_data` method (https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/base.py#L298), which is inherited by `impala.py`, it would be just a matter of populating the `arraysize` from the value set in the config.py.

**Comment by villebro** [comment]
You can check the extra parameters under your database; if the engine supports passing a custom batch size in the `create_engine` call, this should be easy to do without a custom config variable.

![image](https://user-images.githubusercontent.com/33317356/79668703-60251100-81bf-11ea-9b64-3bccca870087.png)
