### ISSUE TITLE
static resource http 404  ,can't open

### ISSUE THREAD

**Issue by longxibendi** [apache/incubator-superset#9581]
### http://superset.apache.org/usertutorial.html#dashboard-basics
some static resources are 404 http status.
http://superset.apache.org/_static/images/usertutorial/chose_a_datasource.png

what you expected to happen.

**Comment by villebro** [comment]
Thanks for reporting @longxibendi , there seems to be a problem with the deployment of the docs for `0.36.0`. I will investigate and try to redeploy working docs asap.

**Comment by villebro** [comment]
Docs should now work again.
