### ISSUE TITLE
Is there SQLAlchemy dialect support JDBC? I want to connect Apache Ignite database in superset

### ISSUE THREAD

**Issue by rangerzhou** [apache/incubator-superset#9588]
Is there SQLAlchemy dialect support JDBC? I want to connect Apache Ignite database in superset, but I do not known how to type 'SQLAlchemy URI'.

Thanks.

**Comment by dpgaspar** [comment]
Apache ignite is not currently supported by superset

**Comment by singh-abhijeet** [comment]
@rangerzhou Try using [SQLAlchemy generic JDBC](https://github.com/daneshpatel/sqlalchemy-jdbcapi) dialect.
