### ISSUE TITLE
Not able to launch superset

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#9595]
I have setup the superset version 0.36, using following command to launch application. It seems application launch fine but when i try to access login page it is throwing internal server error. I am uploading the console screenshot for more info. Can you please suggest something. 

command: 
gunicorn -b 0.0.0.0:1600 --limit-request-line 0 --limit-request-field_size 0 --log-level=debug superset:app
### Expected results

what you expected to happen.

### Actual results
![image](https://user-images.githubusercontent.com/16102955/79739578-fff7b180-831b-11ea-8b32-4d0a987faf1c.png)

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Use the following instead:
 `gunicorn -b 0.0.0.0:1600 --limit-request-line 0 --limit-request-field_size 0 --log-level=debug "superset.app:create_app()"`

**Comment by thammaneni** [comment]
Thanks dpgaspar.
