### ISSUE TITLE
teradatasql - 'LIMIT' keyword error

### ISSUE THREAD

**Issue by Nageshyr** [apache/incubator-superset#9600]
Ji - I am using [teradatasqlalchemy - teradatasql](https://pypi.org/project/teradatasqlalchemy/) driver, connectiong to superset - connection is fine, I see my schemas & tables.

When I query a table - I get the below error on the keyword - 'LIMIT" - In other words - the SQL query which is generated by Superset, looks like has a default keyword 'LIMIT at the end - and Teradata doesn't accept keyword 'LIMIT'.

 
### Expected results
Simple query should return rows from table

what you expected to happen.

### Actual results
**Get this error**

base error: [Version 16.20.0.60] [Session 1583] [Teradata Database] [Error 3706] Syntax error: expected something between the word 'engines' and the 'LIMIT' keyword. at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1138 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1154 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1217 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1712 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:548 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:416 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2080 at database/sql.ctxDriverQuery ctxutil.go:48 at database/sql.(*DB).queryDC.func1 sql.go:1464 at database/sql.withLock sql.go:3032 at database/sql.(*DB).queryDC sql.go:1459 at database/sql.(*Conn).QueryContext sql.go:1701 at main.goCreateRows goside.go:652 at main._cgoexpwrap_212fad278f55_goCreateRows _cgo_gotypes.go:357 at runtime.call64 asm_amd64.s:574 at runtime.cgocallbackg1 cgocall.go:316 at runtime.cgocallbackg cgocall.go:194 at runtime.cgocallback_gofunc asm_amd64.s:826 at runtime.goexit asm_amd64.s:2361
what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/20627783/79794037-98dbfc00-831f-11ea-852b-15d8ec8fba40.png)

### Environment
Ubuntu 18.04 LTS
(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
It appears the `LIMIT` syntax is being applied instead of `TOP`. What version of Superset are you on?

**Comment by Nageshyr** [comment]
I have installed the latest based on these instructions...https://superset.incubator.apache.org/installation.html.

Yes - its adding the LIMIT keyword at the end by default - I can go and muck with the python code and make changes...

But, I though there should be an easier way to do the configuration.

When I did a superset --version, this is what I got.

Python 3.6.8
Flask 1.1.2
Werkzeug 1.0.1

Pl. let me know if you need any other info...

Thx - N

**Comment by dpgaspar** [comment]
Please post the output from `pip freeze`

**Comment by Nageshyr** [comment]
appdirs==2.4.3
backports.ssl-match-hostname==3.5.0.1
blivet==0.61.15.74
Brlapi==0.6.0
cffi==1.6.0
chardet==2.2.1
chrome-gnome-shell==0.0.0
configobj==4.7.2
configshell-fb==1.1.25
contextlib2==0.6.0.post1
coverage==3.6b3
cryptography==1.7.2
cupshelpers==1.0
decorator==3.4.0
di==0.3
distlib==0.3.0
dnspython==1.12.0
enum34==1.0.4
ethtool==0.8
filelock==3.0.12
firstboot==19.5
fros==1.0
futures==3.1.1
gssapi==1.2.0
idna==2.4
importlib-metadata==1.6.0
importlib-resources==1.4.0
iniparse==0.4
initial-setup==0.3.9.44
ipaclient==4.6.5
ipaddr==2.1.11
ipaddress==1.0.16
ipalib==4.6.5
ipaplatform==4.6.5
ipapython==4.6.5
IPy==0.75
Type  :quit<Enter>  to exit Vim                                                                                                                1,10          Top

**Comment by Nageshyr** [comment]
So the sql you enter in SQL Lab is converted to another sql context with the LIMIT keyword added to the end of the sql command.

I have found the keyword LIMIT being added at the end of the SQL context created in SQL_Parser.py.

I was able to make changes and remove the word LIMIT for teradata...it works!

I still believe, this is not the right way to do - there must be an easier way to do this config in JSON or something while adding the teradatasql connection in the database connection.

Hopefully this help...

**Comment by dpgaspar** [comment]
What surprises me is that teradata limit should be using `TOP` here: https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/teradata.py#L24

and then here: https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/base.py#L395

So the limit keyword is applied by sqlalchemy dialect, that's why it's important to know the version of superset and your connector/dialect. Yet from the `pip freeze` output you sent, I see no entries for superset or teradata sqlalchemy dialect.

**Comment by Nageshyr** [comment]
> What surprises me is that teradata limit should be using `TOP` here: https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/teradata.py#L24
> 
> and then here: https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/base.py#L395
> 
> So the limit keyword is applied by sqlalchemy dialect, that's why it's important to know the version of superset and your connector/dialect. Yet from the `pip freeze` output you sent, I see no entries for superset or teradata sqlalchemy dialect.

I dont know if I am doing it right...

But this what I get for version...

ocalhost site-packages]$ superset --version
Python 3.6.8
Flask 1.1.2
Werkzeug 1.0.1

**Comment by Aliaksei-Surautsau** [comment]
I have the same issue:
$ pip3 freeze
alembic==1.3.2
amqp==2.5.2
# Editable install with no version control (apache-superset==0.999.0.dev0)
-e /app
apispec==1.3.3
appdirs==1.4.3
aspy.yaml==1.3.0
astroid==1.6.6
attrs==19.3.0
Babel==2.8.0
backcall==0.1.0
backoff==1.10.0
billiard==3.6.1.0
black==19.10b0
bleach==3.1.0
celery==4.4.0
certifi==2020.4.5.1
cffi==1.13.2
cfgv==3.1.0
chardet==3.0.4
click==7.1.1
colorama==0.4.3
contextlib2==0.6.0.post1
coverage==4.5.3
croniter==0.3.31
cryptography==2.8
decorator==4.4.1
defusedxml==0.6.0
distlib==0.3.0
filelock==3.0.12
Flask==1.1.1
Flask-AppBuilder==2.3.2
Flask-Babel==1.0.0
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-Cors==3.0.7
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-talisman==0.7.0
Flask-Testing==0.7.1
Flask-WTF==0.14.2
future==0.18.2
geographiclib==1.50
geopy==1.20.0
gevent==1.4.0
greenlet==0.4.15
gunicorn==20.0.4
humanize==0.5.1
identify==1.4.15
idna==2.8
importlib-metadata==1.4.0
importlib-resources==1.5.0
ipdb==0.12
ipython==7.14.0
ipython-genutils==0.2.0
isodate==0.6.0
isort==4.3.21
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.10.3
jsonschema==3.2.0
kombu==4.6.7
lazy-object-proxy==1.4.3
Mako==1.1.1
Markdown==3.1.1
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
mccabe==0.6.1
more-itertools==8.1.0
msgpack==0.6.2
mypy==0.770
mypy-extensions==0.4.3
nodeenv==1.3.5
nose==1.3.7
numpy==1.18.1
pandas==1.0.3
parsedatetime==2.5
parso==0.7.0
pathlib2==2.3.5
pathspec==0.8.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pip-tools==4.5.1
pluggy==0.13.1
polyline==1.4.0
pre-commit==1.17.0
prison==0.1.3
prompt-toolkit==3.0.5
psycopg2-binary==2.7.5
ptyprocess==0.6.0
py==1.8.1
pyarrow==0.16.0
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.9.7
pydruid==0.5.7
Pygments==2.6.1
PyHive==0.6.1
PyJWT==1.7.1
pylint==1.9.2
pyrsistent==0.15.7
python-dateutil==2.8.1
python-dotenv==0.10.5
python-editor==1.0.4
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.3
redis==3.2.1
regex==2020.5.7
requests==2.22.0
retry==0.9.2
selenium==3.141.0
simplejson==3.17.0
six==1.14.0
SQLAlchemy==1.3.16
SQLAlchemy-Utils==0.36.1
sqlparse==0.3.0
statsd==3.3.0
**teradatasql==16.20.0.61
teradatasqlalchemy==16.20.0.8**
toml==0.10.0
tox==3.11.1
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.8
vine==1.3.0
virtualenv==20.0.20
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.12.1
WTForms==2.2.1
WTForms-JSON==0.3.3
zipp==2.0.0

**Comment by mistercrunch** [comment]
I think it's a sqlalchemy dialect issue, here's how it's implemented in the MSSQL dialect
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mssql/base.py#L1640-L1655

Something similar would have to be contributed here https://github.com/Teradata/sqlalchemy-teradata/blob/master/sqlalchemy_teradata/dialect.py

**Comment by ankitmani2004** [comment]
Facing the same issue, is there any update for this iissue?

**Comment by radhakvnr** [comment]
Facing the same issue with Teradata.. any luck?

**Comment by Aliaksei-Surautsau** [comment]
Yes. There is a solution - pull request - https://github.com/apache/superset/pull/13519

**Comment by radhakvnr** [comment]
this is not a completed solution as there are some unsuccessful checks
