### ISSUE TITLE
Unable to find controls.jsx file after installation.

### ISSUE THREAD

**Issue by Sumit12594** [apache/incubator-superset#9603]
I want to add country in the list. 
I am windows and followed steps as illustrated.
I don't find superset-frontend folder and many more directories that are mentioned in the illustration does not follow with the folder structure that is installed in my local.
Also, I don't see controls.jsx file anywhere created.
I want to know where i am going wrong and how do i get react js file.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md
