### ISSUE TITLE
New visulaisation  python script & R  script in visualisation

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#9609]
hi i  want to create a new visulisation which are formed by creating seaborn and matplot python libraries

**Comment by willbarrett** [comment]
Hi @kalimuthu123 - we don't currently support plotting from Python or R, but we've discussed it as a possible future project direction. I'm not aware of anyone working on this actively at the moment but this isn't the first time it was requested. Thanks for bringing it up.
