### ISSUE TITLE
superset 0.36.0 can not connect to sqlalchemy_dremio

### ISSUE THREAD

**Issue by 4ss3g4f** [apache/incubator-superset#9610]
Can not connect to dremio via sqlalchemy_dremio

### Expected results

what you expected to happen.
Success connection

### Actual results
Error

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/22811935/79972935-e5127200-84c0-11ea-8fcd-4d2a11ef74a9.png)

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

We used dremio+pyodbc://admin:P4ssw0rd@dremio-client.dremio.svc.cluster.local:31010/k8s-postgres-operator-airflow

**Comment by villebro** [comment]
@4ss3g4f have you installed the Dremio ODBC driver?

**Comment by 4ss3g4f** [comment]
@villebro yes i have tried, here are the results,

![image](https://user-images.githubusercontent.com/22811935/80047773-8983cb00-8538-11ea-8496-8174496caff2.png)

dremio only provide rpm pakage not deb for superset debian os,

![image](https://user-images.githubusercontent.com/22811935/80047832-ac15e400-8538-11ea-8b60-c0984402f346.png)

is this mean that we have to convert dremio ODBC rpm package to deb package first ??

**Comment by 4ss3g4f** [comment]
We have install dremio ODBC,

![image](https://user-images.githubusercontent.com/22811935/80177415-ed37f200-8625-11ea-8004-73d4fc71d182.png)

But still can not add dremio,

![image](https://user-images.githubusercontent.com/22811935/80177473-0e98de00-8626-11ea-8d67-573b9aadd287.png)

we tried with,

dremio+pyodbc://admin:P4ssw0rd@dremio-client.dremio.svc.cluster.local:31010/Samples

**Comment by 4ss3g4f** [comment]
We also have installed pyodbc and sqlalchemy_dremio, still can not connect to dremio,

![image](https://user-images.githubusercontent.com/22811935/80190238-2b411000-863e-11ea-8b32-67962947e687.png)

**Comment by 4ss3g4f** [comment]
ok solved,

![image](https://user-images.githubusercontent.com/22811935/80346939-c7188900-8895-11ea-899e-90de43e412b3.png)

we fork new docker file,

```
core@worker-020 ~ $ cat Dockerfile 
FROM amancevice/superset:0.36.0
USER root
COPY dremio-odbc_1.4.2.1003-2_amd64.deb /home/superset/
RUN dpkg -i /home/superset/dremio-odbc_1.4.2.1003-2_amd64.deb
RUN apt-get install -y unixodbc-bin && apt-get install -y unixodbc-dev
RUN pip install pyodbc && pip install sqlalchemy_dremio && pip install dremio_client[full]
```
result:

> core@worker-020 ~ $ docker build -t assegaf/superset-k8s:0.36.0 .
> Sending build context to Docker daemon  12.76MB
> Step 1/6 : FROM amancevice/superset:0.36.0
> 0.36.0: Pulling from amancevice/superset
> 7e2b2a5af8f6: Pull complete 
> 09b6f03ffac4: Pull complete 
> dc3f0c679f0f: Pull complete 
> fd4b47407fc3: Pull complete 
> b32f6bf7d96d: Pull complete 
> 128c8ba918f2: Pull complete 
> 49bf40fd39f2: Pull complete 
> 685d91195d65: Pull complete 
> 32cd559ee9c9: Pull complete 
> 0af3db29f80f: Pull complete 
> 2ec224ae1d65: Pull complete 
> 91ff90e8f782: Pull complete 
> 63cb630ccee3: Pull complete 
> Digest: sha256:b3710dcb24db4b41d4eef49a7bb5412f6ae6265d2e62a2a181540f11e000e55f
> Status: Downloaded newer image for amancevice/superset:0.36.0
>  ---> 2d8fa12c88b0
> Step 2/6 : USER root
>  ---> Running in 677d2a03c6d2
> Removing intermediate container 677d2a03c6d2
>  ---> 302b0a758d51
> Step 3/6 : COPY dremio-odbc_1.4.2.1003-2_amd64.deb /home/superset/
>  ---> 198139023317
> Step 4/6 : RUN dpkg -i /home/superset/dremio-odbc_1.4.2.1003-2_amd64.deb
>  ---> Running in 829c51de51df
> Selecting previously unselected package dremio-odbc.
> (Reading database ... 25014 files and directories currently installed.)
> Preparing to unpack .../dremio-odbc_1.4.2.1003-2_amd64.deb ...
> Unpacking dremio-odbc (1.4.2.1003-2) ...
> Setting up dremio-odbc (1.4.2.1003-2) ...
> /var/lib/dpkg/info/dremio-odbc.postinst: line 3: odbcinst: command not found
> /var/lib/dpkg/info/dremio-odbc.postinst: line 5: [: configure: integer expression expected
> Processing triggers for libc-bin (2.28-10) ...
> Removing intermediate container 829c51de51df
>  ---> 54eb6d0eff1b
> Step 5/6 : RUN apt-get install -y unixodbc-bin && apt-get install -y unixodbc-dev
>  ---> Running in 93f572921b34
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   dbus libapparmor1 libaudio2 libavahi-client3 libavahi-common-data
>   libavahi-common3 libcups2 libdbus-1-3 libmng1 libodbcinstq4-1 libqt4-dbus
>   libqt4-network libqt4-xml libqtassistantclient4 libqtcore4 libqtdbus4
>   libqtgui4 odbcinst odbcinst1debian2 qdbus qt-at-spi qtchooser qtcore4-l10n
> Suggested packages:
>   default-dbus-session-bus | dbus-session-bus nas cups-common libicu57
>   qt4-qtconfig
> The following NEW packages will be installed:
>   dbus libapparmor1 libaudio2 libavahi-client3 libavahi-common-data
>   libavahi-common3 libcups2 libdbus-1-3 libmng1 libodbcinstq4-1 libqt4-dbus
>   libqt4-network libqt4-xml libqtassistantclient4 libqtcore4 libqtdbus4
>   libqtgui4 odbcinst odbcinst1debian2 qdbus qt-at-spi qtchooser qtcore4-l10n
>   unixodbc-bin
> 0 upgraded, 24 newly installed, 0 to remove and 0 not upgraded.
> Need to get 9502 kB of archives.
> After this operation, 32.8 MB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian buster/main amd64 libapparmor1 amd64 2.13.2-10 [94.7 kB]
> Get:2 http://deb.debian.org/debian buster/main amd64 libdbus-1-3 amd64 1.12.16-1 [214 kB]
> Get:3 http://deb.debian.org/debian buster/main amd64 dbus amd64 1.12.16-1 [235 kB]
> Get:4 http://deb.debian.org/debian buster/main amd64 libaudio2 amd64 1.9.4-6 [80.0 kB]
> Get:5 http://deb.debian.org/debian buster/main amd64 libavahi-common-data amd64 0.7-4+b1 [122 kB]
> Get:6 http://deb.debian.org/debian buster/main amd64 libavahi-common3 amd64 0.7-4+b1 [54.6 kB]
> Get:7 http://deb.debian.org/debian buster/main amd64 libavahi-client3 amd64 0.7-4+b1 [58.1 kB]
> Get:8 http://deb.debian.org/debian buster/main amd64 libcups2 amd64 2.2.10-6+deb10u2 [325 kB]
> Get:9 http://deb.debian.org/debian buster/main amd64 libmng1 amd64 1.0.10+dfsg-3.1+b5 [211 kB]
> Get:10 http://deb.debian.org/debian buster/main amd64 qtcore4-l10n all 4:4.8.7+dfsg-18 [662 kB]
> Get:11 http://deb.debian.org/debian buster/main amd64 libqtcore4 amd64 4:4.8.7+dfsg-18 [1638 kB]
> Get:12 http://deb.debian.org/debian buster/main amd64 libqt4-xml amd64 4:4.8.7+dfsg-18 [149 kB]
> Get:13 http://deb.debian.org/debian buster/main amd64 libqtdbus4 amd64 4:4.8.7+dfsg-18 [238 kB]
> Get:14 http://deb.debian.org/debian buster/main amd64 libqt4-network amd64 4:4.8.7+dfsg-18 [623 kB]
> Get:15 http://deb.debian.org/debian buster/main amd64 libqtassistantclient4 amd64 4.6.3-7+b1 [12.9 kB]
> Get:16 http://deb.debian.org/debian buster/main amd64 libqtgui4 amd64 4:4.8.7+dfsg-18 [4233 kB]
> Get:17 http://deb.debian.org/debian buster/main amd64 odbcinst amd64 2.3.6-0.1 [48.4 kB]
> Get:18 http://deb.debian.org/debian buster/main amd64 odbcinst1debian2 amd64 2.3.6-0.1 [78.1 kB]
> Get:19 http://deb.debian.org/debian buster/main amd64 libodbcinstq4-1 amd64 2.3.0-4+b1 [189 kB]
> Get:20 http://deb.debian.org/debian buster/main amd64 qtchooser amd64 66-2 [26.3 kB]
> Get:21 http://deb.debian.org/debian buster/main amd64 qdbus amd64 4:4.8.7+dfsg-18 [77.5 kB]
> Get:22 http://deb.debian.org/debian buster/main amd64 libqt4-dbus amd64 4:4.8.7+dfsg-18 [53.8 kB]
> Get:23 http://deb.debian.org/debian buster/main amd64 qt-at-spi amd64 0.4.0-9 [62.7 kB]
> Get:24 http://deb.debian.org/debian buster/main amd64 unixodbc-bin amd64 2.3.0-4+b1 [17.8 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 9502 kB in 1s (6416 kB/s)
> Selecting previously unselected package libapparmor1:amd64.
> (Reading database ... 25043 files and directories currently installed.)
> Preparing to unpack .../00-libapparmor1_2.13.2-10_amd64.deb ...
> Unpacking libapparmor1:amd64 (2.13.2-10) ...
> Selecting previously unselected package libdbus-1-3:amd64.
> Preparing to unpack .../01-libdbus-1-3_1.12.16-1_amd64.deb ...
> Unpacking libdbus-1-3:amd64 (1.12.16-1) ...
> Selecting previously unselected package dbus.
> Preparing to unpack .../02-dbus_1.12.16-1_amd64.deb ...
> Unpacking dbus (1.12.16-1) ...
> Selecting previously unselected package libaudio2:amd64.
> Preparing to unpack .../03-libaudio2_1.9.4-6_amd64.deb ...
> Unpacking libaudio2:amd64 (1.9.4-6) ...
> Selecting previously unselected package libavahi-common-data:amd64.
> Preparing to unpack .../04-libavahi-common-data_0.7-4+b1_amd64.deb ...
> Unpacking libavahi-common-data:amd64 (0.7-4+b1) ...
> Selecting previously unselected package libavahi-common3:amd64.
> Preparing to unpack .../05-libavahi-common3_0.7-4+b1_amd64.deb ...
> Unpacking libavahi-common3:amd64 (0.7-4+b1) ...
> Selecting previously unselected package libavahi-client3:amd64.
> Preparing to unpack .../06-libavahi-client3_0.7-4+b1_amd64.deb ...
> Unpacking libavahi-client3:amd64 (0.7-4+b1) ...
> Selecting previously unselected package libcups2:amd64.
> Preparing to unpack .../07-libcups2_2.2.10-6+deb10u2_amd64.deb ...
> Unpacking libcups2:amd64 (2.2.10-6+deb10u2) ...
> Selecting previously unselected package libmng1:amd64.
> Preparing to unpack .../08-libmng1_1.0.10+dfsg-3.1+b5_amd64.deb ...
> Unpacking libmng1:amd64 (1.0.10+dfsg-3.1+b5) ...
> Selecting previously unselected package qtcore4-l10n.
> Preparing to unpack .../09-qtcore4-l10n_4%3a4.8.7+dfsg-18_all.deb ...
> Unpacking qtcore4-l10n (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqtcore4:amd64.
> Preparing to unpack .../10-libqtcore4_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqtcore4:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqt4-xml:amd64.
> Preparing to unpack .../11-libqt4-xml_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqt4-xml:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqtdbus4:amd64.
> Preparing to unpack .../12-libqtdbus4_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqtdbus4:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqt4-network:amd64.
> Preparing to unpack .../13-libqt4-network_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqt4-network:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqtassistantclient4:amd64.
> Preparing to unpack .../14-libqtassistantclient4_4.6.3-7+b1_amd64.deb ...
> Unpacking libqtassistantclient4:amd64 (4.6.3-7+b1) ...
> Selecting previously unselected package libqtgui4:amd64.
> Preparing to unpack .../15-libqtgui4_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqtgui4:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package odbcinst.
> Preparing to unpack .../16-odbcinst_2.3.6-0.1_amd64.deb ...
> Unpacking odbcinst (2.3.6-0.1) ...
> Selecting previously unselected package odbcinst1debian2:amd64.
> Preparing to unpack .../17-odbcinst1debian2_2.3.6-0.1_amd64.deb ...
> Unpacking odbcinst1debian2:amd64 (2.3.6-0.1) ...
> Selecting previously unselected package libodbcinstq4-1:amd64.
> Preparing to unpack .../18-libodbcinstq4-1_2.3.0-4+b1_amd64.deb ...
> Unpacking libodbcinstq4-1:amd64 (2.3.0-4+b1) ...
> Selecting previously unselected package qtchooser.
> Preparing to unpack .../19-qtchooser_66-2_amd64.deb ...
> Unpacking qtchooser (66-2) ...
> Selecting previously unselected package qdbus.
> Preparing to unpack .../20-qdbus_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking qdbus (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package libqt4-dbus:amd64.
> Preparing to unpack .../21-libqt4-dbus_4%3a4.8.7+dfsg-18_amd64.deb ...
> Unpacking libqt4-dbus:amd64 (4:4.8.7+dfsg-18) ...
> Selecting previously unselected package qt-at-spi:amd64.
> Preparing to unpack .../22-qt-at-spi_0.4.0-9_amd64.deb ...
> Unpacking qt-at-spi:amd64 (0.4.0-9) ...
> Selecting previously unselected package unixodbc-bin.
> Preparing to unpack .../23-unixodbc-bin_2.3.0-4+b1_amd64.deb ...
> Unpacking unixodbc-bin (2.3.0-4+b1) ...
> Setting up libmng1:amd64 (1.0.10+dfsg-3.1+b5) ...
> Setting up libapparmor1:amd64 (2.13.2-10) ...
> Setting up libavahi-common-data:amd64 (0.7-4+b1) ...
> Setting up libdbus-1-3:amd64 (1.12.16-1) ...
> Setting up dbus (1.12.16-1) ...
> invoke-rc.d: could not determine current runlevel
> invoke-rc.d: policy-rc.d denied execution of start.
> Setting up libaudio2:amd64 (1.9.4-6) ...
> Setting up qtchooser (66-2) ...
> Setting up qtcore4-l10n (4:4.8.7+dfsg-18) ...
> Setting up libavahi-common3:amd64 (0.7-4+b1) ...
> Setting up libqtcore4:amd64 (4:4.8.7+dfsg-18) ...
> Setting up libavahi-client3:amd64 (0.7-4+b1) ...
> Setting up libqtgui4:amd64 (4:4.8.7+dfsg-18) ...
> Setting up libqt4-xml:amd64 (4:4.8.7+dfsg-18) ...
> Setting up libcups2:amd64 (2.2.10-6+deb10u2) ...
> Setting up libqtdbus4:amd64 (4:4.8.7+dfsg-18) ...
> Setting up libqt4-network:amd64 (4:4.8.7+dfsg-18) ...
> Setting up qdbus (4:4.8.7+dfsg-18) ...
> Setting up libqtassistantclient4:amd64 (4.6.3-7+b1) ...
> Setting up libqt4-dbus:amd64 (4:4.8.7+dfsg-18) ...
> Setting up qt-at-spi:amd64 (0.4.0-9) ...
> Setting up odbcinst (2.3.6-0.1) ...
> Setting up odbcinst1debian2:amd64 (2.3.6-0.1) ...
> Setting up libodbcinstq4-1:amd64 (2.3.0-4+b1) ...
> Setting up unixodbc-bin (2.3.0-4+b1) ...
> Processing triggers for libc-bin (2.28-10) ...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following NEW packages will be installed:
>   unixodbc-dev
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 261 kB of archives.
> After this operation, 1829 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian buster/main amd64 unixodbc-dev amd64 2.3.6-0.1 [261 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 261 kB in 0s (672 kB/s)
> Selecting previously unselected package unixodbc-dev:amd64.
> (Reading database ... 25456 files and directories currently installed.)
> Preparing to unpack .../unixodbc-dev_2.3.6-0.1_amd64.deb ...
> Unpacking unixodbc-dev:amd64 (2.3.6-0.1) ...
> Setting up unixodbc-dev:amd64 (2.3.6-0.1) ...
> Removing intermediate container 93f572921b34
>  ---> 5e53cb6346fe
> Step 6/6 : RUN pip install pyodbc && pip install sqlalchemy_dremio && pip install dremio_client[full]
>  ---> Running in 37349859043f
> Collecting pyodbc
>   Downloading pyodbc-4.0.30.tar.gz (266 kB)
> Building wheels for collected packages: pyodbc
>   Building wheel for pyodbc (setup.py): started
>   Building wheel for pyodbc (setup.py): finished with status 'done'
>   Created wheel for pyodbc: filename=pyodbc-4.0.30-cp36-cp36m-linux_x86_64.whl size=344942 sha256=50b07326795a239293e92f9d7dea1ec55fb15a45023e6cd8ffaf9f2a9011fb8a
>   Stored in directory: /root/.cache/pip/wheels/e3/3f/16/e11367542166d4f8a252c031ac3a4163d3b901b251ec71e905
> Successfully built pyodbc
> Installing collected packages: pyodbc
> Successfully installed pyodbc-4.0.30
> Collecting sqlalchemy_dremio
>   Downloading sqlalchemy_dremio-1.1.3.tar.gz (14 kB)
> Requirement already satisfied: pyodbc>=4.0.17 in /usr/local/lib/python3.6/site-packages (from sqlalchemy_dremio) (4.0.30)
> Requirement already satisfied: sqlalchemy>=1.2 in /usr/local/lib/python3.6/site-packages (from sqlalchemy_dremio) (1.3.12)
> Requirement already satisfied: pyarrow in /usr/local/lib/python3.6/site-packages (from sqlalchemy_dremio) (0.16.0)
> Requirement already satisfied: six>=1.0.0 in /usr/local/lib/python3.6/site-packages (from pyarrow->sqlalchemy_dremio) (1.14.0)
> Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.6/site-packages (from pyarrow->sqlalchemy_dremio) (1.18.1)
> Building wheels for collected packages: sqlalchemy-dremio
>   Building wheel for sqlalchemy-dremio (setup.py): started
>   Building wheel for sqlalchemy-dremio (setup.py): finished with status 'done'
>   Created wheel for sqlalchemy-dremio: filename=sqlalchemy_dremio-1.1.3-py2.py3-none-any.whl size=18041 sha256=a0126564a32b2e8157131f960b10234ea71a4d1763050814de57daffb1500e4c
>   Stored in directory: /root/.cache/pip/wheels/00/3a/0f/a4e0b6df805a7cd2c212d799fa2392ab5beb8bd8ca16e8dfa2
> Successfully built sqlalchemy-dremio
> Installing collected packages: sqlalchemy-dremio
> Successfully installed sqlalchemy-dremio-1.1.3
> Collecting dremio_client[full]
>   Downloading dremio_client-0.12.0-py2.py3-none-any.whl (46 kB)
> Requirement already satisfied: simplejson in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (3.17.0)
> Requirement already satisfied: attrs in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (19.3.0)
> Collecting confuse
>   Downloading confuse-1.1.0.tar.gz (32 kB)
> Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (2.23.0)
> Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (7.1.1)
> Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (1.14.0)
> Requirement already satisfied: pyarrow>=0.15.0; extra == "full" in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (0.16.0)
> Requirement already satisfied: markdown; extra == "full" in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (3.1.1)
> Collecting requests-futures==1.0.0; extra == "full"
>   Downloading requests-futures-1.0.0.tar.gz (10 kB)
> Requirement already satisfied: pandas>=0.24.2; extra == "full" in /usr/local/lib/python3.6/site-packages (from dremio_client[full]) (0.25.3)
> Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/site-packages (from confuse->dremio_client[full]) (5.3)
> Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->dremio_client[full]) (2.9)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->dremio_client[full]) (3.0.4)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->dremio_client[full]) (2020.4.5.1)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.21.0->dremio_client[full]) (1.25.8)
> Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.6/site-packages (from pyarrow>=0.15.0; extra == "full"->dremio_client[full]) (1.18.1)
> Requirement already satisfied: setuptools>=36 in /usr/local/lib/python3.6/site-packages (from markdown; extra == "full"->dremio_client[full]) (46.1.3)
> Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/site-packages (from pandas>=0.24.2; extra == "full"->dremio_client[full]) (2.8.1)
> Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/site-packages (from pandas>=0.24.2; extra == "full"->dremio_client[full]) (2019.3)
> Building wheels for collected packages: confuse, requests-futures
>   Building wheel for confuse (setup.py): started
>   Building wheel for confuse (setup.py): finished with status 'done'
>   Created wheel for confuse: filename=confuse-1.1.0-py3-none-any.whl size=17573 sha256=33582e599f885757eff0c1e347b2bd6cbc4b2b59ea322eb1416fdc94823e8450
>   Stored in directory: /root/.cache/pip/wheels/0b/b9/ff/e8288eaedc9ead7b6f32555771ccd4b5bcec1566553b4c4859
>   Building wheel for requests-futures (setup.py): started
>   Building wheel for requests-futures (setup.py): finished with status 'done'
>   Created wheel for requests-futures: filename=requests_futures-1.0.0-py3-none-any.whl size=7013 sha256=89ac08c59ee895d012fdfb59a898498f4f6ada6a209a291448a62bb74befbdb1
>   Stored in directory: /root/.cache/pip/wheels/15/03/c1/78bc17e91a6f740565af018749431a5c35e62ee93a32824344
> Successfully built confuse requests-futures
> Installing collected packages: confuse, requests-futures, dremio-client
> Successfully installed confuse-1.1.0 dremio-client-0.12.0 requests-futures-1.0.0
> Removing intermediate container 37349859043f
>  ---> f0166c9e2abd
> Successfully built f0166c9e2abd
> Successfully tagged assegaf/superset-k8s:0.36.0
