### ISSUE TITLE
connection refused error from Email Report after upgrading to Latest Superset Version.

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#9616]
I am running Superset with Docker.

I was [having issues](https://github.com/apache/incubator-superset/issues/9426) with making celery worker functional with my Superset Version (circa 2019), so I decided to update to the latest release **0.36.0**. 

I am using the same versions of geckodriver (**0.24.0**) and firefox (**68.5.0esr**) as I was using prior to the update. Python (**3.6.9**) and Selenium (**3.141.0**) versions are still the same.

However, when trying to send an email, I am getting the following error:

```
erset-worker_1  |   "Flask-Caching: CACHE_TYPE is set to null, "
superset-worker_1  | [2020-04-22 15:36:09,452: ERROR/ForkPoolWorker-8] Task email_reports.send[eb4ddfba-0901-427e-be05-743c9c97a2f5] raised unexpected: WebDriverException('connection refused', None, None)
superset-worker_1  | Traceback (most recent call last):
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
superset-worker_1  |     R = retval = fun(*args, **kwargs)
superset-worker_1  |   File "/app/superset/app.py", line 114, in __call__
superset-worker_1  |     return task_base.__call__(self, *args, **kwargs)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
superset-worker_1  |     return self.run(*args, **kwargs)
superset-worker_1  |   File "/app/superset/tasks/schedules.py", line 373, in schedule_email_report
superset-worker_1  |     deliver_dashboard(schedule)
superset-worker_1  |   File "/app/superset/tasks/schedules.py", line 211, in deliver_dashboard
superset-worker_1  |     driver = create_webdriver()
superset-worker_1  |   File "/app/superset/tasks/schedules.py", line 163, in create_webdriver
superset-worker_1  |     driver = driver_class(**kwargs)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
superset-worker_1  |     keep_alive=True)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
superset-worker_1  |     self.start_session(capabilities, browser_profile)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
superset-worker_1  |     response = self.execute(Command.NEW_SESSION, parameters)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
superset-worker_1  |     self.error_handler.check_response(response)
superset-worker_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
superset-worker_1  |     raise exception_class(message, screen, stacktrace)
superset-worker_1  | selenium.common.exceptions.WebDriverException: Message: connection refused
```

'geckodriver.log':
```
1587569769443	mozrunner::runner	DEBUG	Killing process 104
1587569769447	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
```

Why is this error occurring? What change in Superset is affecting the Email Report feature?

All package versions:

- geckodriver -- **0.24.0**
- python -- **3.6.9**
- firefox -- **68.5.0esr**
- selenium -- **3.141.0**

**Comment by klazaj** [comment]
To bypass this error, remove `USER superset` from 'docker-compose.yml'

**Comment by avicenteg** [comment]
Hello @klazaj,
Do you finally get the sending of any email? 
I saw that you had many problems, as I am, but currently, after follow your issues I'm getting: 
` selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//127.0.0.1%3A8088/login/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20127.0.0.1%3A8088 `
Do you know how to fix it?

**Comment by poppyc0ck** [comment]
> Hello @klazaj,
> Do you finally get the sending of any email?
> I saw that you had many problems, as I am, but currently, after follow your issues I'm getting:
> `selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//127.0.0.1%3A8088/login/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20127.0.0.1%3A8088`
> Do you know how to fix it?

@avicenteg [this](https://github.com/apache/incubator-superset/issues/9135#issuecomment-587574966)

**Comment by avicenteg** [comment]
@poppyc0ck  thanks, finally my error was a similar one. My Docker container didn't use the ip: 0.0.0.0, I changed it by superset-app (the name of the container) and using the 8088 port, and now it is running perfectly.

**Comment by Shkurupii** [comment]
Hello @avicenteg @poppyc0ck !
Your advice will be very appreciated. 
```
# The base URL to query for accessing the user interface
WEBDRIVER_BASEURL = "http://0.0.0.0:8088/"
```
In my case superset and celery don't bound to 8088. What's the service stands behind 8088 in your case? I can't figure out myself.

Thanks!
