### ISSUE TITLE
[BUG] Explore table viz returns no result when filter is NULL or NOT NULL

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#9618]
Explore table viz returns no result when filter is NULL or NOT NULL
### Expected results
It should return the result set
### Actual results
No data available in table
#### Screenshots
![image](https://user-images.githubusercontent.com/11397834/80008507-b4a8e480-847c-11ea-9e71-c999335005f5.png)

#### How to reproduce the bug

1. Go to table  
2. Click on 'bart_line' table to explore
3. Scroll down to select Filter -> column 'name' -> is NULL or NOT NULL 
4. Run Query
5. See error

### Environment

(please complete the following information):

- superset version: Superset 0.999.0dev (check out master)
- python version: 3.6.8
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
`SELECT name AS name,
 count(color) AS "COUNT(color)"
FROM bart_lines
WHERE false
GROUP BY name
ORDER BY "COUNT(color)" DESC
LIMIT 10000;`

The explore request:
`http://localhost:8088/superset/explore/?form_data={"datasource":"13__table","viz_type":"table","url_params":{},"time_range_endpoints":["inclusive","exclusive"],"granularity_sqla":null,"time_grain_sqla":"P1D","time_range":"Last+week","groupby":["name"],"metrics":[{"expressionType":"SIMPLE","column":{"id":456,"column_name":"color","verbose_name":null,"description":null,"expression":null,"filterable":true,"groupby":true,"is_dttm":false,"type":"VARCHAR(255)","optionName":"_col_color"},"aggregate":"COUNT","sqlExpression":null,"hasCustomLabel":false,"fromFormData":true,"label":"COUNT(color)","optionName":"metric_qqaak8p1tnh_c7yss63hqv7"}],"percent_metrics":[],"timeseries_limit_metric":null,"row_limit":10000,"include_time":false,"order_desc":true,"all_columns":[],"order_by_cols":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"name","operator":"IS+NULL","comparator":"","clause":"WHERE","sqlExpression":null,"isExtra":false,"fromFormData":true,"filterOptionName":"filter_o0vgzbylo8j_78ppchfrsx3"}],"table_timestamp_format":"%Y-%m-%d+%H:%M:%S","page_length":0,"include_search":false,"table_filter":false,"align_pn":false,"color_pn":true,"show_cell_bars":true}`

**Comment by etr2460** [comment]
I believe this was resolved with https://github.com/apache/incubator-superset/pull/9613
