### ISSUE TITLE
Error: found in Chart.yaml, but missing in charts/ directory: postgresql, redis

### ISSUE THREAD

**Issue by anouar-zh** [apache/incubator-superset#9622]
After this last commit, when I try  to install superset using helm:

`helm install superset --set persistence.enabled=true,persistence.existingClaim=superset-pvc ./install/helm/superset`

I get:

`Error: found in Chart.yaml, but missing in charts/ directory: postgresql, redis`

**Comment by craig-rueda** [comment]
Try running `helm dependency update ./install/helm/superset` before installing

**Comment by wangchunxiang8090** [comment]
asdf
