### ISSUE TITLE
package.json file

### ISSUE THREAD

**Issue by cyang52** [apache/incubator-superset#9626]
why i can not find package.json file?
it should be under assists folder
any ideas?

**Comment by rusackas** [comment]
The package.json file is for the frontend/client application, which resides within the `superset-frontend` directory, within the root folder of Superset. Let me know if you see it there (or not).

**Comment by cyang52** [comment]
thanks and where i can find config.py?

**Comment by rusackas** [comment]
In the root directory of the repo, there's a `superset` folder. `config.py` is in there.
