### ISSUE TITLE
Chord diagram metric does not exist

### ISSUE THREAD

**Issue by kmac83** [apache/incubator-superset#9627]
chord diagram will tell me 'sum(column_name) metric does not exist'  even though it does...this looks similar to issue #8977 ...but i installed superset this week (4/19/2020)

### Expected results

Chord diagram
![image](https://user-images.githubusercontent.com/52050204/80038651-1a6c8f00-84c4-11ea-95bc-ac7df87934b8.png)

### Actual results

![image](https://user-images.githubusercontent.com/52050204/80037725-28b9ab80-84c2-11ea-8593-ec9cb9f395d7.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/52050204/80037788-47b83d80-84c2-11ea-8e94-1ea05eda3f8a.png)

### Environment

(please complete the following information):

- superset version: 0.35.2
- python version: 3.7.3
- node.js version: v13.13.0
- npm version: 6.14.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any. (honestly, no clue what this is) 
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar. (i have but it said the bug was fixed, but i cant seem to make this work, sorry! )

**Comment by villebro** [comment]
This was fixed by #9149
