### ISSUE TITLE
Point superset metadata Tables to Custom postgresql schema 

### ISSUE THREAD

**Issue by npaladug1** [apache/incubator-superset#9629]
When i am running the superset_config.py file the superset metadata tables are by default getting loaded into public schema .I want the tables to be  loaded to Custom Postgresql schema .Any help will be highly appreciated 

Regards,
Nithin.

**Comment by willbarrett** [comment]
Hi @npaladug1 - to my knowledge what you are trying to do is not currently supported in Superset. You could create a new user in Postgres for your Superset install and then update its default search path to your custom schema. That would likely work, as I believe Superset's metadata queries are not schema-qualified.

I hope this helps!
