### ISSUE TITLE
#Question: UI styling is not loading as expected.

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#9631]
I have installed latest version 0.36, but some pages like dashboards, sqllab and default welcome screen UI components are not loading as expected. Can you provide any suggestions or ideas? 
Providing sample screens below for your reference. 
Thanks.

### Actual results
![image](https://user-images.githubusercontent.com/16102955/80062056-711faa80-8550-11ea-8e00-7275d7e1f1ea.png)

![image](https://user-images.githubusercontent.com/16102955/80062124-9f9d8580-8550-11ea-8128-a1aa67490174.png)

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Hi @thammaneni - please share the information requested in the bug template so that we can better assist you in diagnosing the issue.
