### ISSUE TITLE
Histogram not working properly

### ISSUE THREAD

**Issue by gogitub** [apache/incubator-superset#9632]
Hi,

Observed couple of issues with histogram graph

Issue-1) Seeing unwanted X-Axis labels
![image](https://user-images.githubusercontent.com/61489253/80061961-33bb1d00-8550-11ea-8c19-8e0aab7ea694.png)
Here the values 1.2,1.4,1.6, 1.8 and so on are not needed as the expectation is to see only edge values 1,2,3 etc.

Issue-2) Showing incorrect number of bins/bars
instead of showing 4 bins, it shows only 3
if we choose 5, it shows 6
![image](https://user-images.githubusercontent.com/61489253/80062154-b5ab4600-8550-11ea-8132-34c92a5548bc.png)

Please advise.
Thanks!!

**Comment by bradleydamato** [comment]
@gogitub seeing issue #2 when bucketing boys names in a histogram, mainly with odd numbers snapping to an even number of buckets. Investigating now.
