### ISSUE TITLE
fail after run npm run dev

### ISSUE THREAD

**Issue by cyang52** [apache/incubator-superset#9633]
after run npm run dev
it reports: 

> 98% after emitting SizeLimitsPluginERROR in /Users/yes/Downloads/incubator-superset-master/superset-frontend/src/components/ListView/TableCollection.tsx(45,22):
TS2339: Property 'hidden' does not exist on type 'ColumnInstance<{}>'.
ERROR in /Users/yes/Downloads/incubator-superset-master/superset-frontend/src/components/ListView/TableCollection.tsx(48,28):
TS2339: Property 'sortable' does not exist on type 'ColumnInstance<{}>'.
ERROR in /Users/yes/Downloads/incubator-superset-master/superset-frontend/src/components/ListView/TableCollection.tsx(54,27):
TS2339: Property 'sortable' does not exist on type 'ColumnInstance<{}>'.
ERROR in /Users/yes/Downloads/incubator-superset-master/superset-frontend/src/components/ListView/TableCollection.tsx(83,33):
TS2339: Property 'hidden' does not exist on type 'ColumnInstance<{}>'.
ERROR in /Users/yes/Downloads/incubator-superset-master/superset-frontend/src/components/ListView/TableCollection.tsx(85,53):
TS2339: Property 'cellProps' does not exist on type 'ColumnInstance<{}>'.
Version: typescript 3.8.3

any idea?
thanks

**Comment by wgonzalez25** [comment]
after npm run build

Appear this error message:
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(45,22):
TS2339: Property 'hidden' does not exist on type 'ColumnInstance<{}>'.

ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(48,28):
TS2339: Property 'sortable' does not exist on type 'ColumnInstance<{}>'.

ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(54,27):
TS2339: Property 'sortable' does not exist on type 'ColumnInstance<{}>'.

ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(85,33):
TS2339: Property 'hidden' does not exist on type 'ColumnInstance<{}>'.

ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx
ERROR in /Users/Walter/incubator-superset/superset-frontend/src/components/ListView/TableCollection.tsx(87,53):
TS2339: Property 'cellProps' does not exist on type 'ColumnInstance<{}>'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Walter/.npm/_logs/2020-05-19T18_54_19_904Z-debug.log

Some idea to fix?

**Comment by wushu0725** [comment]
Some idea to fix?

**Comment by ruanoct** [comment]
I encountered the same problem.

**Comment by wgonzalez25** [comment]
> Some idea to fix?

Hi @wushu0725 I fixed but I don't used the docker-compose up from incubator-superset. I installed using this steps by steps from this webpage https://medium.com/@kharekartik/a-better-guide-to-building-apache-superset-from-source-2c8dbad38b2b

**Comment by wushu0725** [comment]
I fixid it in Centos system,  It's window problem.

**Comment by lilila** [comment]
How did you fix it @wushu0725 ?

**Comment by villebro** [comment]
Are you running Node 12? I think newer versions are not yet supported, so running on 13 or 14 probably doesn't work properly right now.

**Comment by sedhha** [comment]
> Are you running Node 12? I think newer versions are not yet supported, so running on 13 or 14 probably doesn't work properly right now.

I am running on v12.18.2 it's still not working.
