### ISSUE TITLE
can we use redis-cluster for superset scheduling?

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#9635]
Hi, i was using redis server for scheduling in superset. due to some scheduling functionality issues i am trying to use redis-cluster. when configure scheduling with redis-cluster, celery worker is throwing an error as like below. i need to some suggestions here for superset scheduling which is best in redis, redis-cluster or rabitmq ? Thanks.

Worker log for redis-cluster:
![image](https://user-images.githubusercontent.com/16102955/80093219-b7d9c880-8581-11ea-98b3-71f49e76d18b.png)

**Comment by bsergean** [comment]
This redis client (used by celery it seems, probably redis-py) does not seem to support the redis cluster protocol. You could use a new project called [redis-cluster-proxy](https://github.com/RedisLabs/redis-cluster-proxy) to workaround that. You would install it 'in front' of your cluster.

You can also ask / research on the kombu github project whether they support redis-cluster.

(I wrote a tool to play with redis cluster if you're interested in trying it -> https://machinezone.github.io/rcc/cluster_testbed/)

**Comment by thammaneni** [comment]
Thanks basergean.
