### ISSUE TITLE
Missing cast  'Fetch Values Predicate' where clause as sqlalchemy.sql text break its functionality

### ISSUE THREAD

**Issue by vnnw** [apache/incubator-superset#9642]
Multiple versions in the code file missing the cast funcion of  Fetch Values Predicate' where clause as Sqlalchemy Text, result in raising error such as: sqlalchemy.exc.ArgumentError: Textual SQL expression "ds < datetime('now')" should be explicitly declared as text("ds < datetime('now')")

This line 
https://github.com/apache/incubator-superset/blob/master/superset/connectors/sqla/models.py#L604

should be modified as 

```
qry = qry.where(text(tp.process_template(self.fetch_values_predicate)))
```

**Comment by villebro** [comment]
You're right @vnnw , I believe some dialects are more sensitive to these omissions. What dialect are you using? We should probably clean these up in one go.

**Comment by vnnw** [comment]
> You're right @vnnw , I believe some dialects are more sensitive to these omissions. What dialect are you using? We should probably clean these up in one go.

I tried Sqlite and Clickhouse. After doing the modification mentioned above, all seems good now.

**Comment by villebro** [comment]
@vnnw would you mind opening a Pull Request for this?
