### ISSUE TITLE
Add facets as a graph type

### ISSUE THREAD

**Issue by jeremyhiggs** [apache/incubator-superset#9645]
**Is your feature request related to a problem? Please describe.**
When comparing different values within a dimension (e.g. shop), one currently has to copy charts and set different values in the filter. This is cumbersome, and requires manual configuration when new values are added to that dimension.

**Describe the solution you'd like**
Please add facets as a visualisation type, e.g. https://plotly.com/python/facet-plots/

For this, one would select a particular column as the facet. If there are 6 values in that column/dimension, 6 different graphs would be generated as a group.

**Describe alternatives you've considered**
Creating one chart per value is cumbersome:
* When you add a new value (e.g. add a new shop, district, etc), another chart has to be created.
* Each chart is separate. Changes to one chart requires updating all the other charts manually.

**Additional context**

**Comment by benceorlai** [comment]
Hi @jeremyhiggs 

I ran this by the team here and they recommended very similar alternatives in ECharts. 

https://echarts.apache.org/en/option.html#grid
https://echarts.apache.org/examples/en/editor.html?c=dataset-encode1&theme=light

I'd be curious to know if these meet your needs.

The reason why the team prefers ECharts is because they have been researching it heavily as a new chart library to consider for adoption and it will probably be easier to work with than Plotly, which is python based.

I hope this helps

**Comment by mistercrunch** [comment]
I thought this was about https://pair-code.github.io/facets/ which is totally like running an app in an app. Totally different thing though...

I really like eCharts personally, but with viz plugins we're not limited!

**Comment by jeremyhiggs** [comment]
Hi, thanks for looking into this.

The eCharts "grid" looks good, but is limited in that you can only have a 2x2 grid.

Seaborn has a "FacetGrid". Is it feasible to integrate with that?
https://seaborn.pydata.org/generated/seaborn.FacetGrid.html

**Comment by harryprince** [comment]
+1 same issue

**Comment by MichaelTiemannOSC** [comment]
+1 from me too!

**Comment by kobrien722** [comment]
+1 from me too!

**Comment by dlg0** [comment]
+1 would love to see faceting in apache superset

**Comment by rusackas** [comment]
Anyone that's interested in faceting (ECharts-based or otherwise) is welcome to start a GitHub Discussion "Ideas" thread, or open a SIP with a detailed proposal here on GitHub Issues. We'd love to see such a contribution!

**Comment by joshuaclausen** [comment]
Here is a GitHub discussion about the topic of getting small multiples, faceted visualization, lattice charts, or trellis charts into Superset: https://github.com/apache/superset/discussions/25319
