### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by cyang52** [apache/incubator-superset#9648]
after run 

> python superset db upgrade

 I got this error:

>  import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed: The specified module could not be found.

I did some search, it seems it will be fixed if :

> pip uninstall pandas
pip install pandas==1.0.1

but it seems apache-superset requires : 
      

>  ERROR: apache-superset 0.999.0.dev0 has requirement pandas<1.1,>=1.0.3, but you'll have pandas 1.0.1 which is incompatible.

**Comment by bradleydamato** [comment]
I'd be willing to take this on as a first issue on the project.

**Comment by bradleydamato** [comment]
@cyang52 unable to replicate this error on fresh install on Ubuntu 18.04 , do you think it's worth cloning your fork and checking myself?
