### ISSUE TITLE
'superset db upgrade' exit with code 132

### ISSUE THREAD

**Issue by ZOOUQinn** [apache/incubator-superset#9653]
I try to install superset on Fedora 31, I've followed the official document [site](https://superset.incubator.apache.org/installation.html#superset-installation-and-initialization).

I have this error when execute 

superset db upgrade

logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully /home/mos/Workspace/superset/venv37/lib64/python3.7/site-packages/flask_caching/init.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
"Flask-Caching: CACHE_TYPE is set to null, "
Illegal instruction (core dumped)

with exit code 132

Are there anyone can help me?

**Comment by Pinimo** [comment]
Hi, first of all I can tell it has probably nothing to do with the `CACHE_TYPE` error that is logged. IMHO it is related to docker and to your CPU version (from [this question](https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132)).

For the community to help you efficiently, you should share your config, especially system versions (as said in this repository's issue template).

**Comment by ZOOUQinn** [comment]
I figure it out. It caused by the absence of AVX(Advanced Vector Extensions) support in the CPU.

**Comment by twointum** [comment]
> I figure it out. It caused by the absence of AVX(Advanced Vector Extensions) support in the CPU.

Is this a hardware issue? Am I stuck if I am at this point?

**Comment by martimors** [comment]
Seeing this on Arm CPU (MacOS), using an image that was built on x86 linux and the colima emulator. Emulators are always flaky and this kind of thing can happen. Very frustrating, because Arm is currently broken because of not being able to install psycopg2 because of [this issue](https://github.com/python-lz4/python-lz4/issues/299).
