### ISSUE TITLE
change title and /url of superset 

### ISSUE THREAD

**Issue by nitacekarki** [apache/incubator-superset#9668]
**Is your feature request related to a problem? Please describe.**
Is it possible to change title name and the URL of superset to something else ?

**Comment by krishna9626** [comment]
Hi @nitacekarki  ,You can change the title by modifying APP_NAME in config.py .I don't think so whether the url of superset can be modified or not.

**Comment by nitacekarki** [comment]
Thanks for your reply Krist, we are now able to change also if it's
possible can we change the URL prefix of the superset.
Currently its https://wasci.sectorinsight.com.au/superset can we change it
to https://wasci.sectorinsight.com.au/
<https://wasci.sectorinsight.com.au/superset>custom?

Thanks in advance :) Regards
