### ISSUE TITLE
Tokenize text when making a word cloud

### ISSUE THREAD

**Issue by jzonthemtn** [apache/incubator-superset#9672]
**Is your feature request related to a problem? Please describe.**
When using the word cloud on fields that contain sentences, the word cloud treats each field as a "word" in the word cloud. The word cloud then contains each sentence.

**Describe the solution you'd like**
Have an option to tokenize (or simply split on whitespace) the words in a field so the word cloud will be able to make counts for each individual word in the field.

**Describe alternatives you've considered**
Changing how data gets ingested into the database but I don't see a good solution from that angle if the word cloud is expecting one word per field.

**Additional context**
None.

**Comment by villebro** [comment]
This is an interesting idea @jzonthemtn . To make sure the proposed feature is as generic as possible, do you have any suggestions for tokenization options? I'm thinking how to handle periods, commas, special characters etc?

**Comment by jzonthemtn** [comment]
@villebro My recommendation would be to strip punctuation and then split on whitespace. This would work well for my use-case. If that is not sufficient for a user then I would suggest they do any necessary preprocessing of the text prior to saving it in their database so that way they have control over how they want to handle the tokenizing.

**Comment by ktmud** [comment]
While this feature would definitely be useful, it’s also pretty easy to create virtual data sources that split strings and explode arrays into rows:

https://stackoverflow.com/questions/51063730/split-one-row-into-multiple-rows-based-on-comma-separated-string-column

https://stackoverflow.com/questions/17942508/sql-split-values-to-multiple-rows
