### ISSUE TITLE
Superset DB API relies on the DB being online

### ISSUE THREAD

**Issue by bkyryliuk** [apache/incubator-superset#9678]
https://github.com/apache/incubator-superset/blob/980dd2fd419893ec5ed9386ca28fa87115a3753d/superset/views/database/api.py#L138

"function_names"  needs a database connection, e.g. 
https://github.com/apache/incubator-superset/blob/980dd2fd419893ec5ed9386ca28fa87115a3753d/superset/db_engine_specs/hive.py#L446

This leads to the problem that 1 db being down makes a superset a bit dysfunctional e.g. sqllab will not return the list of databases and will crash the api request.

Introduced: https://github.com/apache/incubator-superset/pull/9012

cc @etr2460 ,  @dpgaspar,  @villebro

**Comment by dpgaspar** [comment]
Thks @bkyryliuk for reporting this. @etr2460 what do you think about making a dedicated endpoint to fetch database function names?

**Comment by villebro** [comment]
@dpgaspar good idea. To avoid having to introduce a new endpoint every time we add some new features, perhaps we could make it a "database extras" endpoint?

**Comment by bkyryliuk** [comment]
Another thing that could be done is to catch requests exceptions in the model functions that require external services & will be exposed in the different APIs.

**Comment by etr2460** [comment]
I like the idea of catching the exceptions and falling back to an empty array as @bkyryliuk did in his PR. That said, i can see the need for a new endpoint for db engine specific attributes that aren't fully populatable by the database model

**Comment by dpgaspar** [comment]
@bkyryliuk that would make an easy/quick fix. Yet I think `function_names` inclusion on the GET (list) endpoint should be changed to live on it's own endpoint, taking on the @villebro's idea, and since we already have a `table_metadata` EP, include this kind of info on a `database_metadata` for example. Note that this property will increase GET (list) response time (yet this can be avoided by just requesting for the exact columns)

**Comment by bkyryliuk** [comment]
This one is actually resolved.

**Comment by magor** [comment]
Hi there! @bkyryliuk , I don't think this is solved. I just tried to list databases in my instance with one hive db backend, which is down right now and the request for database list just timeouts and empty list is returned. I don't think this is expected behaviour.
