### ISSUE TITLE
How to make Time Grain in Chart calculate day based on local time zone

### ISSUE THREAD

**Issue by sunnysnowhi** [apache/incubator-superset#9681]
I have a postgresql table with colume like this:
   create_time   timestamp without time zone
   resource_id   varchar(32)

Then I set the chart like this:
![image](https://user-images.githubusercontent.com/52787424/80577939-5068c080-8a3a-11ea-86c3-33098c792789.png)

I found in super set log , the sql is like this:
SELECT DATE_TRUNC('day', create_time) AS __timestamp, count(resource_id) AS "COUNT(resource_id)"
FROM dbadmin.de_billing
WHERE create_time >= '2020-03-29 00:00:00' AND create_time <= '2020-04-29 00:00:00' GROUP BY DATE_TRUNC('day', create_time) ORDER BY "COUNT(resource_id)" DESC
 LIMIT 50000

which means Time Grain calculate the day in this  way :  DATE_TRUNC('day', create_time) , 
for example : UTC 2020-04-28 00:00:00 to UTC 2020-04-29 00:00:00

But what I want is  showing the count of resource_id every day **based on local timezone** 
my local time zone is Asia/Shanghai, which is **utc+8**  hour
so I want it calculate in this way  , for example,  UTC 2020-04-27 16:00:00 to UTC 2020-04-28 16:00:00  , which means local time 2020-04-28 00:00:00 to local time 2020-04-29 00:00:00, the **day** of the local time 

First I tried this way: add a new calculated columu , e8_create_time =  create_time + INTERVAL '8 hour'
,then select the e8_create_time  as the time colume in chart.
![image](https://user-images.githubusercontent.com/52787424/80579743-1f3dbf80-8a3d-11ea-99f3-6f6d5bf776af.png)

**But I have a lot of tables! This  method is very complex, I must add one or more new colomn for every table!**

The I found in table settings there is a offset setting, **But it did not work as I want**,
![image](https://user-images.githubusercontent.com/52787424/80580048-852a4700-8a3d-11ea-9672-b7dca19a2e41.png)
![image](https://user-images.githubusercontent.com/52787424/80580063-89566480-8a3d-11ea-90ba-b1d1b1d58402.png)
 when I set 8 here,  it seems not calculate a whole day from 00:00:00 to 00:00:00, it shows 08 AM here
![image](https://user-images.githubusercontent.com/52787424/80580211-c7538880-8a3d-11ea-8e1b-669aafdc89da.png)

I search this question on internet ,  many anserwers say set superset config.py DRUID_TZ = tz.gettz('Asia/Shanghai'),  but  I  did not use druid as the datasource, My database is  here and druid datasources is empty 
![image](https://user-images.githubusercontent.com/52787424/80580762-ab041b80-8a3e-11ea-938c-c1fa5dc021a8.png)

Is there a better way to achieve my goal? Thanks!!!

**Comment by sunnysnowhi** [comment]
anyone help?

**Comment by eugeniamz** [comment]
Which database do you use? Maybe in the extra field you could set the timezone. 
![image](https://user-images.githubusercontent.com/58375897/81068800-f428f500-8eae-11ea-9d74-3c64a4dfe6bf.png)

Let me know what db you use and I can try to find the answer. Every database is different,

**Comment by sunnysnowhi** [comment]
@eugeniamz I use the postgresql

**Comment by jayhjha** [comment]
You can update the base query for the data source. Go to sources > Tables > Edit record and under SQL, add:
```
    SELECT *, create_time at time zone 'Asia/Shanghai' at time zone 'utc' as create_time_zone
    FROM dbadmin.de_billing;
```
and the column `create_time_zone` will be available for all charts using that source. 
So you use that instead of `create_time` in your charts.
