### ISSUE TITLE
Can't connect to mongodb BI connector with mysql driver

### ISSUE THREAD

**Issue by aguspina** [apache/incubator-superset#9683]
I'm connecting superset to mongodb BI connector through mysql driver but i'm getting the following error when I try to add the database:

```
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: mysql:/XXXXXX:XXXXXXXXXX@XX:XXXX/XXXXX
ERROR:superset.views.core:Unexpected error (MySQLdb._exceptions.ProgrammingError) (1064, "parse sql 'ROLLBACK' error: unexpected ID at position 9 near ROLLBACK")
```

I'm using superset with docker-compose installation.

**Comment by dpgaspar** [comment]
Hi @aguspina mongodb is not supported by superset.
Yet, mongodb BI connector should translate SQL to mongoDB (but it may not be that simple), are you using this has the metadata DB?

**Comment by aguspina** [comment]
Hey @dpgaspar ! Thanks for the answer. I didn't understand completely the final question... I'm not sure what you mean when you say "metadata DB".

**Comment by dpgaspar** [comment]
Well, superset has a metadata DB that contains data about your users, dashboards, charts etc... this DB is defined on the config by `SQLALCHEMY_DATABASE_URI`

All the other DB's for analytics are defined on the UI and may need specific dbapi drivers

**Comment by aguspina** [comment]
Great. I'm trying to add Mongo through the ui for analytics. I'm using this driver https://pypi.org/project/mysqlclient/ and the sqlalchemy look like this mysql:/XXXXXX:XXXXXXXXXX@XX:XXXX/XXXXX.

**Comment by cw1427** [comment]
Can it be resolved when connect to MongoBI with superset mysql driver?

**Comment by jan-stillfried-toteat** [comment]
We are having a similar issue with any read operation on MongoBI through the mysql driver:

(1064, "parse sql 'COMMIT' error: syntax error: unexpected ID at position 7 near COMMIT")

It seems to stem from the fact that there is an automatic commit with any select query, even though it is a read-only database. Is there any known way to maybe disable this through settings?

**Comment by hetz** [comment]
Thanks for reporting this issue.

To apply a temporary fix, you can patch the SQLAlchemy `default.py` file inside the `superset_app` container to conditionally skip the `rollback()` call when connecting to a specific MySQL port (e.g., 3307). This is useful in scenarios where the underlying database (like some MySQL setups) does not expect or properly handle explicit rollback calls.

You can apply the patch and restart the container using the following commands:

```bash
docker exec -i superset_app bash <<'EOF'
sed -i."$(date +%Y%m%d_%H%M%S)_bak" '/def do_rollback(self, dbapi_connection):/{
    N
    s/dbapi_connection\.rollback()/\
try:\\n    if getattr(dbapi_connection, "port", None) == 3307:\\n        return\\nexcept Exception:\\n    pass\\n    dbapi_connection.rollback()/
}' /app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py
EOF

docker restart superset_app
```

**Explanation:**
- The `sed` command creates a timestamped backup of the original file.
- It modifies the `do_rollback` method to skip calling `rollback()` if the connection's port is 3307 (commonly used for certain MySQL proxies or read replicas).
- This change is ephemeral and will be lost if the container is rebuilt, so consider baking this into a custom image for production use.

> ⚠️ **Note**: Modifying files inside a running container is not recommended for production environments. This workaround is intended for testing or temporary mitigation. A more robust solution would involve upgrading SQLAlchemy, patching the application, or adjusting the database driver behavior.
