### ISSUE TITLE
minimum width height bar graph

### ISSUE THREAD

**Issue by mantej-emilence** [apache/incubator-superset#9699]
i need to set minimun width and height of a bar graph to make it look good as small bars are coming
### Expected results

![image](https://user-images.githubusercontent.com/61014306/80676739-10a2e700-8ad5-11ea-81ca-4eb1c1546fc0.png)

what you expected to happen.

### Actual results
![image](https://user-images.githubusercontent.com/61014306/80676716-fec14400-8ad4-11ea-9187-3d58f95e892a.png)
what actually happens.

#### How to reproduce the bug

1. Go to '...' bar chart 
2. Click on '....'series 
3. Scroll down to '....' add country

### Environment

(please complete the following information):

- superset version: `superset version 0.35`
- python version: `python --version 3.6`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [. ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [. ] I have reproduced the issue with at least the latest released version of superset.
- [ .] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment]
🗑🏷inactive
