### ISSUE TITLE
Remove Heatmap in Table-visualization metrics column

### ISSUE THREAD

**Issue by G0dspeeDy** [apache/incubator-superset#9700]
I want to remove the heatmap displayed for the metrics in Table-visualisation.

I cannot find a way to make this change by altering the json-parameters of the visualisation.

Is there a way to make this change without having to make any customising the table-visualisation itself ?

**Comment by sedhha** [comment]
Hi, I don't have a absolute way to do so as of now, but I can tell you a hacky way to do so. For example if you want to remove heat map of metric abc, just cast it as string based on the type of SQL you are using. I have configured my superset with BigQuery and so using:
**CAST(METRICNAME as String)**
removes heatmap, similarly if you're using some other SQL maybe using:
**String(METRICNAME)**
can help you to remove the heatmap as it is now visualized as string.
