### ISSUE TITLE
add user but unsupported hash type

### ISSUE THREAD

**Issue by wangdongsong** [apache/incubator-superset#9701]
### Expected results

what you expected to happen.

2020-04-30 16:48:00,395:INFO:root:logging was configured successfully
2020-04-30 16:48:00,499:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Email [admin@fab.org]: 
Recognized Database Authentications.
2020-04-30 16:48:02,758:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. unsupported hash type
No user created an error occured

### Actual results

what actually happens.

#### How to reproduce the bug

1.Install by http://superset.apache.org/installation.html#superset-installation-and-initialization.
2.exectue the command:./superset fab create-admin --username admin --firstname admin --lastname admin  --password admin
3.above is the output

- superset version: `superset version` Superset 0.35.1
- python version: `python --version` Python 3.7.4
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!
 [* ] I have reproduced the issue with at least the latest released version of superset.

**Comment by dpgaspar** [comment]
I'm not being able to replicate this issue, can you share the output from `superset fab list-users`?

**Comment by wangdongsong** [comment]
2020-04-30 17:22:10,297:INFO:root:logging was configured successfully
2020-04-30 17:22:10,402:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
List of users
-------------

**Comment by wangdongsong** [comment]
no users

**Comment by wangdongsong** [comment]
flask_appbuilder version confilct?

**Comment by dpgaspar** [comment]
Don't know yet, can you post flask-appbuilder version, use `pip freeze`

**Comment by wangdongsong** [comment]
Flask==1.1.1
Flask-AppBuilder==2.2.1
Flask-Babel==0.12.2
Flask-Babel2==0.1
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-talisman==0.7.0
Flask-WTF==0.14.2

**Comment by dpgaspar** [comment]
can you test upgrading to the latest or downgrading 2.1.13 using the pinned requirements from 0.35.1. It does not seem like your using a fresh 0.35.1 install, have you upgraded/changed anything?

**Comment by wangdongsong** [comment]
closed, it's the openssl version. Thanks.
