### ISSUE TITLE
Time grain (week) starts from Sunday

### ISSUE THREAD

**Issue by mahedi0244** [apache/incubator-superset#971]
I am using caravel for a while and when I add a slice where the visualization type is "Time Series", I noticed that the week starts from Sunday by default. It can be changed easily to start the week on Monday, instead of Sunday. Is the caravel community thinking about adding a feature to select the start date or I can change it to Monday by default if you suggest.

**Comment by xrmx** [comment]
@mahedi0244 nice finding! Is this on the python or js side? maybe we can have do it based on the locale?

**Comment by mahedi0244** [comment]
@xrmx this is the part that I had to change and it seems like working
https://github.com/mahedi0244/caravel/commit/7743cb2001ed6fde3b47778b0702f16ed14d1989

**Comment by xrmx** [comment]
@mahedi0244 so it looks like that just removing the * - 1 DAY* would be enough no?

**Comment by mahedi0244** [comment]
@xrmx 
DAYOFWEEK(created_at) —>returns 1 for Sunday, 2 for Monday and so on.
 
DATE_SUB(created_at, INTERVAL DAYOFWEEK(created_at) - 1 DAY) —> will subtract days in such a way so it returns the previous Sunday

If I just replace it with “WEEKDAY(created_at) - 0 DAY))” , the week will start on Monday, as WEEKDAY(created_at) returns 0 for Monday, 1 for Sunday and so on.

**Comment by xrmx** [comment]
@mahedi0244 thanks for the explanation! but why `- 0 day` then is weekday is fine on its own?

**Comment by mahedi0244** [comment]
@xrmx “WEEKDAY(created_at)  DAY” will also work

**Comment by mistercrunch** [comment]
Just add a new grain "week starting monday".

**Comment by daudryc** [comment]
I've been using superset for a while, just wondering if there is a feature on the dashboard that can alter time grain as we desired?

I mean the time grain config is the best, just wondering if we can also change it on dashboard view for various users.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 438 days. Feel free to comment and request for this issue to be reopened.

**Comment by xrmx** [comment]
@mistercrunch could you please reopen this?

**Comment by ismael-benitez** [comment]
I need this feature too

**Comment by mistercrunch** [comment]
We have this for some database, it's just a matter of adding the proper expression for your database engine. Here's how it's done on MySQL
