### ISSUE TITLE
Memory Insufficient Warning with docker

### ISSUE THREAD

**Issue by yanickrochon** [apache/incubator-superset#9711]
On a VM wich initially ran with only 1 GB of RAM, I increased that amount to 4 GB, installed docker and other requirements, then ran `docker-composer up`, as indicated on the [Installation & Configuration](https://superset.incubator.apache.org/installation.html) page. But after downloading  5.2 GB of stuff, I get this message

```
Step 13/37 : RUN /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci
 ---> Running in e18f62b44119
    ===============================================
    ========  Memory Insufficient Warning =========
    ===============================================

    It looks like you only have 0.284832 GB of
    memory free. Please increase your Docker
    resources to at least 3GB

    ===============================================
    ========  Memory Insufficient Warning =========
    ===============================================
npm ERR! network timeout at: https://registry.npmjs.org/@babel/plugin-syntax-dynamic-import/-/plugin-syntax-dynamic-import-7.8.3.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-01T20_06_18_860Z-debug.log
ERROR: Service 'superset' failed to build: The command '/bin/sh -c /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci' returned a non-zero code: 1
```

### Expected results

The process should use the available memory

```
$ free
              total        used        free      shared  buff/cache   available
Mem:        4041492      401264      513704        6940     3126524     3344720
Swap:       1046524        6412     1040112
```

### Actual results

Not enough memory (for some reason)

### Environment

- superset version: as of May 1st 2020 (seriously, where can I find the version number?)
- python version: `3.7.3`
- node.js version: `12.10.0`
- npm version: `6.14.4`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yanickrochon** [comment]
Closing this issue because it can be resolved by boosting the RAM until it works. I didn't bother to try the bare minimum, 8 GB and this error goes away.

But I still have an error, so will open another issue.

**Comment by jayakrishnankk** [comment]
@yanickrochon - what command did you use to increase the memory allocation for docker ?

**Comment by yanickrochon** [comment]
I do not recall. We scrapped the idea of using docker and installed Superset as a Python module instead. Not as pretty, but we could spare the extra VM in this case. I would've hoped that someone more experienced with Docker would have answered by now.
