### ISSUE TITLE
jwt authentication in version 0.35.2

### ISSUE THREAD

**Issue by kalimuthu123** [apache/incubator-superset#9717]
when try with this authentication its not working 
jwt token is get but the 
when we get apis 

Access denied error
### Actual results
![jwttoken](https://user-images.githubusercontent.com/42966797/80863865-afc60b00-8c9c-11ea-9b44-bb3d27623a51.png)

Please anyone suggest me some ideas 
is superset works like thsi

**Comment by kalimuthu123** [comment]
HI @dpgaspar i am used this authentication for getting dashboard urls

**Comment by zufolo441** [comment]
I have this problem too....
I can obtain token, but when I try to use it in headers with "Authorization: Bearer" in logs I find: ERROR:root:'AnonymousUserMixin' object has no attribute 'get_user_id'. 
I'm using github version as of 3 days ago.

**Comment by zufolo441** [comment]
Solved, thanks. I had to rewrite a new custom authenticator.

**Comment by chen-ABC** [comment]
@zufolo441   I have the same problem, could you please provide me with your solution demo

**Comment by zufolo441** [comment]
Hi,
I followed these instructions: https://laptrinhx.com/tutorial-how-to-integrate-superset-in-your-own-application-2272552308/

**Comment by pranjal5215** [comment]
Above link is not opening => Is this still up ?
