### ISSUE TITLE
Clickhouse connection issue

### ISSUE THREAD

**Issue by chuang39** [apache/incubator-superset#9719]
After "pip install superset-clickhouse", I couldn't add the clickhosue in superset as below. 
<img width="782" alt="Screen Shot 2020-05-02 at 6 08 14 PM" src="https://user-images.githubusercontent.com/1077727/80896150-244e7900-8ca0-11ea-942c-938e5882bb59.png">

The port change can make effect. If I don't use 8123, it reports error since it is http connectin. However, no matter what I set for other fields like user, password. It will always gave error in server log as below.

`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8123
DEBUG:urllib3.connectionpool:http://localhost:8123 "POST / HTTP/1.1" 401 None
Unexpected error Code: 194, e.displayText() = DB::Exception: Password required for user default (version 19.17.5.18 (official build))

ERROR:superset.views.core:Unexpected error Code: 194, e.displayText() = DB::Exception: Password required for user default (version 19.17.5.18 (official build))

INFO:werkzeug:127.0.0.1 - - [03/May/2020 01:08:00] "POST /superset/testconn HTTP/1.1" 400 -`

Any idea? Thanks!

#### How to reproduce the bug

- Go to Sources -> Databases
- Click on '+' button
- fill Database and URI
- press Test Connection

### Environment

(please complete the following information):

- superset version:0.30.1 or  0.36.0 for apache-superset
- python version: `3.6.9`
- sqlalchemy-clickhouse version: 0.1.5.post0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rubenSastre** [comment]
I have used, clickhouse-sqlalchemy instead of sqlalchemy-clickhouse, seems to have a recent version, but i am finding some diferent problems for it(missing first 2 rows of result).I am trying to find a solution also.

**Comment by Sam--Shan** [comment]
@rubenSastre @chuang39  hi,did you find any solution.i came across the issue,too,but different message:

INFO:werkzeug:218.4.91.131 - - [18/May/2020 08:05:46] "POST /superset/testconn HTTP/1.1" 400 -
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 42.159.158.64:8123
DEBUG:urllib3.connectionpool:http://42.159.158.64:8123 "POST / HTTP/1.1" 500 None
Unexpected error Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 20.4.1.2909)

ERROR:superset.views.core:Unexpected error Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 20.4.1.2909)

**Comment by Sam--Shan** [comment]
I tried re install  infi.clickhouse_orm and it works.
pip uninstall infi.clickhouse_orm
pip install infi.clickhouse_orm==1.0.4

**Comment by mdianjun** [comment]
I have another error: 

![image](https://user-images.githubusercontent.com/12122541/87026216-05271700-c20e-11ea-91de-3fa8567f2089.png)

**Comment by dubin555** [comment]
same issue, can someone take a look?

**Comment by villebro** [comment]
I can take a look.

**Comment by victorcheng2333** [comment]
> pip install infi.clickhouse_orm==1.0.4
Thanks , it also work to me

**Comment by windylcx** [comment]
> I tried re install infi.clickhouse_orm and it works.
> pip uninstall infi.clickhouse_orm
> pip install infi.clickhouse_orm==1.0.4

work for me ,thx.

**Comment by rogerlzp** [comment]
cool, it works for me.
For local install, you can use the infi.clickhouse_orm-1.0.4-py2-none-any.whl file directly,  if you are using python2;
However, you have to download infi.clickhouse_orm-1.0.4.tar.gz, and using "python3 setup.py install" command to install it when you are using Python3.
