### ISSUE TITLE
Markup with data abilities

### ISSUE THREAD

**Issue by AlexStanovsky** [apache/incubator-superset#972]
Is the a way the html code in the markup can receive data from selected row on one of the slices in the dashboard, so i could be visualized?

**Comment by xrmx** [comment]
Sorry I haven't really understood what you want to do but since this is an open question it's better to discuss on the mailing list instead of here.

**Comment by vicho29** [comment]
Could you tell me more what is the mailing list mentioned is for and how to subscribe/ask questions there?

Thanks

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 236 days. Feel free to comment and request for this issue to be reopened.
