### ISSUE TITLE
is the porject support HBase ?

### ISSUE THREAD

**Issue by ISLEMNEDDAR** [apache/incubator-superset#9720]
hiii supersetTeam,
i wish you doing well
i want to use this project with my hbase database, but i didn't find the way how to integrate it
and can i use impala or pheonix as layer in my hbase database ?

thank you

**Comment by cgivre** [comment]
@ISLEMNEDDAR 
You can use Superset to query HBase via Apache Drill.  Basically all you have to do is set up Drill to access your HBase installation and then connect Drill to Superset.

**Comment by mistercrunch** [comment]
At Airbnb we have a Presto connector to HBase. There's also Phoenix that maybe able to do this.

**Comment by mistercrunch** [comment]
Oh and Kylin?
