### ISSUE TITLE
need crontab syntax for First monday of every month

### ISSUE THREAD

**Issue by gogitub** [apache/incubator-superset#9726]
Hi,

Can anyone please help me with Schedule Email Reports Crontab syntax for "First monday of every month"?
Tried below options but not working.
0 8 1-7 * 1
0 8 1-7 * * [ "$(date '+\%a')" = "Mon" ]
0 8 * * 1 [ `date '+\%m'` == `date '+\%m' -d "1 week ago"` ]

Please advise.
Thanks.

**Comment by mistercrunch** [comment]
I'll bite, does this work? https://crontab.guru/#0_0_1-7_*_1

**Comment by willbarrett** [comment]
As this is not a Superset-specific question, but one about a widely used syntax, I'd recommend asking on [Stack Oveflow](https://stackoverflow.com)
