### ISSUE TITLE
Toast "An error occured while fetching dashboards" on login

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#9727]
Upon successful login, the "Welcome" page displays an error toast "An error occured while fetching dashboards"
Used to work in 0.34.0

### Expected results

Login, Welcome page displays a list of Dashboards, another tab with recent activit, a third tab with favorites

### Actual results

Login, Dashboards tab is empty, bottom shows a Toast error message "An error occured while fetching dashboards"

Other tabs are fine

#### Screenshots
![image](https://user-images.githubusercontent.com/4623644/80969544-0efd5a00-8e1a-11ea-8518-c49611bba6e2.png)

#### How to reproduce the bug

1. Go to main page, 
2. Click login button
3. See error

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `Python 3.6.10` : 
- node.js version: `v12.16.3`
- npm version: `6.14.4`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I investigated a bit.

The URI called is `/api/v1/dashboard/?q={"order_column":"changed_on","order_direction":"desc","page":0,"page_size":25}`

it returns an error 400 that isn't displayed anywhere (stack is catched, only toast is left)
as seen in DashboardTable.jsx
```    return SupersetClient.get({
      endpoint: `/api/v1/dashboard/?q=${queryParams}`,
    })
      .then(({ json }) => {
        this.setState({ dashboards: json.result, dashboard_count: json.count });
      })
      .catch(response => {
        if (response.status === 401) {
          this.props.addDangerToast(
            t(
              "You don't have the necessary permissions to load dashboards. Please contact your administrator.",
            ),
          );
        } else {
          this.props.addDangerToast(
            t('An error occurred while fetching Dashboards'),
          );
        }
      })
      .finally(() => this.setState({ loading: false }));
  };
```

Previous version seemed to call this :

`/dashboardasync/api/read?_oc_DashboardModelViewAsync=changed_on&_od_DashboardModelViewAsync=desc`

Also note that the URL `/dashboard/list/' works fine, but I wasn't ablo to track down the underlying api call, it's far beyond my knowledge.

I only I could manage to 
- display the error that is caught
- point to the probably offending dao

I could maybe workaround the issue somehow ?

**sidenote** : no way to get DEBUG log level ! That would help a lot

I'm running superset within docker.
(using aproximately this Dockerfile https://github.com/amancevice/docker-superset/blob/master/Dockerfile)

**Comment by squalou** [comment]
I added a "console.log(response)" at the 'toasting' place, unfortunately nothing of interest here

```Response
body: (...)
bodyUsed: false
headers: Headers
__proto__: Headers
ok: false
redirected: false
status: 400
statusText: ""
type: "basic"
url: "https://xxxx(obfuscated)xxxxxxx/api/v1/dashboard/?q={%22order_column%22:%22changed_on%22,%22order_direction%22:%22desc%22,%22page%22:0,%22page_size%22:25}"
__proto__: Response
arrayBuffer: ƒ arrayBuffer()
blob: ƒ blob()
body: (...)
bodyUsed: (...)
clone: ƒ clone()
formData: ƒ formData()
headers: (...)
json: ƒ json()
ok: (...)
redirected: (...)
status: (...)
statusText: (...)
text: ƒ text()
type: (...)
url: (...)
constructor: ƒ Response()
Symbol(Symbol.toStringTag): "Response"
get body: ƒ body()
get bodyUsed: ƒ bodyUsed()
get headers: ƒ headers()
get ok: ƒ ok()
get redirected: ƒ redirected()
get status: ƒ status()
get statusText: ƒ statusText()
get type: ƒ type()
get url: ƒ url()
__proto__: Object```

**Comment by squalou** [comment]
Had a look at `/tests/dashboards/api_tests.py` : the uri that causes me problems is tested. Cool.

But I cant find the code portion that answers to this rest path.

`/superset/views/dashboard/views.py` does expose'/list' or '/new', I did fint '/' exposed with a POST, but ... no clie as to where the '/' for a GET is hidden.

**Comment by squalou** [comment]
Note that I managed an ugly patch.

in `superset-frontend/src/welcome/DashboardTable.jsx` line 117 (tag 0.36.0 of the file)

i replaced

```
    return SupersetClient.get({
      endpoint: `/api/v1/dashboard/?q=${queryParams}`,
    })
```

by 

```
    return SupersetClient.get({
      endpoint: `/dashboardasync/api/read?_oc_DashboardModelViewAsync=changed_on&_od_DashboardModelViewAsync=desc`,
    })
```

from a weird kind of clue seen in `src/components/OmniContainer.jsx` : there is an **todo** there ... so maybe it's not yet fully implemented in tag 0.36.0 ? that's weird.

```
const getDashboards = query =>
  // todo: Build a dedicated endpoint for dashboard searching
  // i.e. superset/v1/api/dashboards?q=${query}
  SupersetClient.get({
    endpoint: `/dashboardasync/api/read?_oc_DashboardModelViewAsync=changed_on&_od_DashboardModelViewAsync=desc&_flt_2_dashboard_title=${query}`,
  })
```

**Comment by dpgaspar** [comment]
Ok, thks for reporting this, can you post here the full response from the API call. Can't reproduce this

**Comment by squalou** [comment]
One precision : I did have 0.34.0 data already. Maybe the db update did go wrong somehow ? 
Will try again restoring a backup and see what happens.

Regarding the response ... I have nothing more than what is already posted above, a.k.a nothing. ..

If you point me to the code portion I can tweak, I can easily add some debug logs and rebuild all.

**Comment by squalou** [comment]
DAMN !
using production 0.34.0 dump of 'superset' schema,
running 'superset db upgrade'
I now have nelow error.

I'm a supposed to upgrade to 0.35 first ?

```sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1215, 'Cannot add foreign key constraint')
[SQL: 
CREATE TABLE tab_state (
	created_on DATETIME, 
	changed_on DATETIME, 
	extra_json TEXT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER, 
	label VARCHAR(256), 
	active BOOL, 
	database_id INTEGER, 
	`schema` VARCHAR(256), 
	`sql` TEXT, 
	query_limit INTEGER, 
	latest_query_id VARCHAR(11), 
	autorun BOOL NOT NULL, 
	template_params TEXT, 
	created_by_fk INTEGER, 
	changed_by_fk INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id), 
	FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
	FOREIGN KEY(database_id) REFERENCES dbs (id), 
	FOREIGN KEY(latest_query_id) REFERENCES query (client_id), 
	FOREIGN KEY(user_id) REFERENCES ab_user (id), 
	CHECK (active IN (0, 1)), 
	CHECK (autorun IN (0, 1))
)

```

**Comment by dpgaspar** [comment]
HTTP 400 is really unexpected here, it would help getting the API response, you can easily access that using chrome developer mode, the got to network tab:

<img width="1750" alt="Screenshot 2020-05-06 at 10 45 35" src="https://user-images.githubusercontent.com/4025227/81163677-070ef880-8f87-11ea-9762-43743b8620a0.png">

**Comment by squalou** [comment]
Hi,
the response if in the first comment I made to my issue, i dont have more info displayed.

I added myself a console.log(reponse) in the file to have it displayed entirely in chrome dev tools as you show it.

Nothing more than "400", empty answer

**Comment by squalou** [comment]
Tried 'master' instead of 0.36.0 tag, here's the out of th box nohingness I get as an API response

![image](https://user-images.githubusercontent.com/4623644/81194446-f2e5ee00-8fbc-11ea-9dc8-c46c4c3af781.png)

**Comment by squalou** [comment]
Issue Solved !

Sorry, it was not a superset issue at all.

On my test environment, there's a load balancer ... that was misconfigured and as a result some api calls where not routed to superset.
But only a few...

I hope it's the same thing for others having the same issue.

tanks for your attention anyway!
