### ISSUE TITLE
404 for static assets like loading.gif

### ISSUE THREAD

**Issue by clach04** [apache/incubator-superset#9730]
### Expected results

Superset web interface to load without error

### Actual results

404 for :

/static/assets/images/loading.gif

#### Screenshots

NA

#### How to reproduce the bug

checkout source from github:

follow https://superset.apache.org/installation.html for pre-setup until `pip install apache-superset`

    git clone https://github.com/apache/incubator-superset.git
    cd incubator-superset
    pip -e .  # this replaces "pip install apache-superset"

follow https://superset.apache.org/installation.html for rest of setup after `pip install apache-superset`

### Environment

(please complete the following information):

- superset version: `0.999.0dev`
- python version: `3.8.2`
- node.js version: `v10.19.0`
- npm version: `6.14.4`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.
NB see #657 which is closed

### Additional context

This appears to be the same as reported in #657 - solution for current code was pretty similar, `npm install node-gyp` then ran `./cypress_build.sh` (I also ran `./js_build.sh` before hand with limited success).

Not sure what a fix for this looks like. Opening to share how I got past this.

**Comment by weidongkl** [comment]
i see this error too
