### ISSUE TITLE
SQLLab : error while fetching database list (0.36.0)(0.35.2)

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#9732]
### Expected results

In SQLLab, list of databases is displayed and available

### Actual results

No databases available, Toaster message "Error while fetching database list"

In browser console, there's a 404

```sqllab.2cb609d23e6326ebb8f8.entry.js:2 GET https://superset.mycompany.com/api/v1/database/?q=(keys:!(none),filters:!((col:expose_in_sqllab,opr:eq,value:!t)),order_columns:database_name,order_direction:asc,page:0,page_size:-1) ```

#### Screenshots

![image](https://user-images.githubusercontent.com/4623644/81017158-1e07fa80-8e62-11ea-91f6-e14ba6da421a.png)

#### How to reproduce the bug

1. Login, 
2. Click on SQL Lab
3. See error

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `Python 3.6.10` : 
- node.js version: `v12.16.3`
- npm version: `6.14.4`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Running inside Docker, built on 0.36.0 tag sources

Using OAuth2

Migrating data from 0.34.0 with some errors

```
ERROR:superset.views.base:invalid literal for int() with base 10: 'Infinity'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views/base.py", line 107, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 151, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 1055, in schemas
    db_id = int(db_id)
ValueError: invalid literal for int() with base 10: 'Infinity'



```

Note that creating a new database connexion does not solve anything.

**Comment by krishna9626** [comment]
Getting same issue

**Comment by squalou** [comment]
I'm getting the same result with 0.35.2

I did restore my 0.34 setup
installed 0.35.2
... and I'm facing the exact same issue.

**Comment by belongwqz** [comment]
Getting same issue

**Comment by dpgaspar** [comment]
Have you run `superset init` on the upgraded 0.35.2/0.36.0?

If yes, can you check you have permissions to view/access your databases on superset. Simple way add yourself `all database access on all_database_access` permission.

**Comment by squalou** [comment]
I did run the superset init command.

my user has an 'Admin' role which contains `, all database access on all_database_access, `

**Comment by squalou** [comment]
Just to make sure I did try with 'master' branch. Same thing.

**Comment by squalou** [comment]
Note : I **do** have Oauth users only, no local users. Maybe there could be something related ? OAuth is configured since 0.28 I guess

**Comment by squalou** [comment]
and just in case :

![image](https://user-images.githubusercontent.com/4623644/81197248-5887a980-8fc0-11ea-8a6f-dfa37700511c.png)

**Comment by squalou** [comment]
Issue Solved !

Sorry, it was not a superset issue at all.

On my test environment, there's a load balancer ... that was misconfigured and as a result *some* api calls where not routed to superset.
But only a few...

I hope it's the same thing for others having the same issue.


tanks for your attention anyway!

**Comment by true1337** [comment]
Can you describe the solution? How do you fix this problem?

**Comment by squalou** [comment]
Sure, it all depends what you have in front of your superset intallation.
(could be apache, nginx, whatever).
In my case I have a load balancer that makes some magic on hosts and urls to redirect queries to a server.

`/api/v1` urls were redirected to another service. => superset never received gem => front never got answers

I had to reorder priorities as they should always have been : if host = superset => all queries go to superset server.

**Comment by valferon** [comment]
I had the same issue and could see some missing dependencies in an exception in the logs.
Had to add thrift / sasl dependencies in the docker image.

**Comment by elaademiir** [comment]
> Sure, it all depends what you have in front of your superset installation. (could be apache, nginx, whatever). In my case I have a load balancer that makes some magic on hosts and urls to redirect queries to a given server. (shared resources for my test setup)
> 
> `/api/v1` uri's were redirected to another service. => superset never received them => superset front never got answers
> 
> I had to reorder priorities as they should always have been : if host = superset => all queries go to superset server.

this is the same error in my local superset venv. Sorry I couldnt understand the solution exactly. Can you please describe it more detail?
