### ISSUE TITLE
How can I change the timezone displayed on Superset logs?

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#9743]
This are the `HEALTHCHECK` logs:
![image](https://user-images.githubusercontent.com/22456202/81102743-5a922f80-8f10-11ea-9056-6e27870c86ff.png)

The time shows as 18:36, when the real time is 20:36. How can I change the timezone?

**Comment by dpgaspar** [comment]
Change the OS timezone

**Comment by klazaj** [comment]
@dpgaspar I fixed it by adding the following lines to the Dockerfile:

```
ENV TZ Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by always-busy** [comment]
thranks, my logs show the right time now

**Comment by always-busy** [comment]
> @dpgaspar I fixed it by adding the following lines to the Dockerfile:
> 
> ```
> ENV TZ Europe/Amsterdam
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> ```
> 
> The previous default timezone was etc/UTC

but i have another problem, the dttm field of log table never change

**Comment by yellow456434** [comment]
dttm field not use timezone, because the file 'superset/models.core.py' 
`dttm = Column(DateTime, default=datetime.utcnow)`
【datetime.utcnow】 could need to change 【datetime.now】
