### ISSUE TITLE
Italian Custom Map

### ISSUE THREAD

**Issue by federicobaraldi** [apache/incubator-superset#9750]
Hi .. in the Custom Map visualization tool Italy is sliced only by province and not also by region.
Is it possible to add this feature ?

Thanks.

**Comment by zufolo441** [comment]
I' realizing maps with QGIS starting from .shp files released by ISTAT.
[italy_regioni.zip](https://github.com/apache/incubator-superset/files/4662931/italy_regioni.zip)
