### ISSUE TITLE
visualization timeout error

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#9772]
server start with  gunicorn -w 5 -k gevent --timeout 3600  
and config.py  SUPERSET_WEBSERVER_TIMEOUT = 600
but When the query time exceeds 3 minutes visualization error
![image](https://user-images.githubusercontent.com/20242930/81371716-29417b80-912b-11ea-8368-4f35847fb44e.png)
![image](https://user-images.githubusercontent.com/20242930/81371723-2fcff300-912b-11ea-911e-26dd240d2208.png)

**Comment by MarcusSorealheis** [comment]
Which view is this @qinzl1 ?

**Comment by MarcusSorealheis** [comment]
Also, is there any load balancer timeout? That will need to be longer than 3600  😅

**Comment by qinzl1** [comment]
@MarcusSorealheis superset version 0.28.1

**Comment by willbarrett** [comment]
Hi @quinzl1 - it looks like you're hitting a global query timeout. My recommendation would be to look at the underlying query and optimize your datastore as a concrete next step. We've discussed adding a different mechanism for populating graphs (see [SIP-39](https://github.com/apache/incubator-superset/issues/9190)) but for now this is the best recommendation I can give.
