### ISSUE TITLE
Service 'superset' failed to build

### ISSUE THREAD

**Issue by yanickrochon** [apache/incubator-superset#9780]
First, I really want to give as much information as I can at this time, but the message indicate
```
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-11T13_13_30_388Z-debug.log
```
However there is no file there!

Following the [Installation & Configuration](https://superset.incubator.apache.org/installation.html) page, I have executed the three commands :

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
docker-compose up
```

But right from the start I see `debconf: delaying package configuration, since apt-utils is not installed`, however `apt-utils` is in fact installed : `apt-utils is already the newest version (1.8.2)`

Then the process downloads and installs a bunch of docker containes, and then after a while, I get this message :

```
npm ERR! network timeout at: https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.14.0.tgz
ERROR: Service 'superset' failed to build: The command '/bin/sh -c /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci' returned a non-zero code: 1
```

### Expected results

I'm not sure what I'm suppose to expect, if not that the app should start and be available.

### Actual results

Some failure without logs to know what happened.

#### Screenshots

![image](https://user-images.githubusercontent.com/78461/81567017-b4a85000-9369-11ea-9a27-9609615eeb5d.png)

#### How to reproduce the bug

1. Install Debian 10
2. Follow instructions for a docker install at [Installation & Configuration](https://superset.incubator.apache.org/installation.html)

### Environment

- superset version: commit [42b10ae](https://github.com/apache/incubator-superset/commit/42b10aecaeff21b870c1f825b9c6e5c9dc5f95a3)
- python version: `2.7.16` (and python3 version: `3.7.3`)
- node.js version: `v12.10.0`
- npm version: `6.14.4`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
@yanickrochon "network timeout", can you retry, if it fails again please confirm you can access `https://registry.npmjs.org/` (use curl or your browser from the same instance)

**Comment by yanickrochon** [comment]
Hi @dpgaspar, I seem to have no issue whatsoever accessing the file :

```
$ wget https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.14.0.tgz
--2020-05-12 08:11:07--  https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.14.0.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.18.35, 104.16.22.35, 104.16.24.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.18.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 156329 (153K) [application/octet-stream]
Saving to: ‘eslint-plugin-import-2.14.0.tgz’

eslint-plugin-import-2. 100%[============================>] 152.67K  --.-KB/s    in 0.01s   

2020-05-12 08:11:07 (12.1 MB/s) - ‘eslint-plugin-import-2.14.0.tgz’ saved [156329/156329]
```
The file extracts just fine.

So I just tried `docker-compose up` again, and the same problem; the line `'/bin/sh -c /frontend-mem-nag.sh         && cd /app/superset-frontend         && npm ci'` fails for some reason.

**Comment by yanickrochon** [comment]
Note that I have other Node.js projects installed and running, so I _know_ that `npm install` (as well as `yarn add`) works.

**Comment by DanielGnzlzVll** [comment]
I have same issue on a windows machine.

How reproduce it?

```bash
docker-compose build --no-cache
```

![image](https://user-images.githubusercontent.com/22230373/81961869-94ca9380-95d8-11ea-9d9a-7c1192c3d931.png)
