### ISSUE TITLE
Elasticsearch query return the {e} in result

### ISSUE THREAD

**Issue by ankur-vyas14** [apache/incubator-superset#9781]
I am able to connect the Elasticsearch with the Apache Superset and it also shows the the table in the left panel. But when I am trying to fire the query on the table it returns the {e} as a result. 

#### Screenshots

![image](https://user-images.githubusercontent.com/41239909/81569026-4d67bb80-93bc-11ea-9a40-81048e25402e.png)

### Environment
- superset version: 0.36.0
- python version: 3.7
- node.js version: 12.16.1
- npm version: 6.13.4
- elasticsearch version: 7.6.2

**Comment by dpgaspar** [comment]
Hi @ankur-vyas14 thank you for reporting, do you mind opening an issue here?: https://github.com/preset-io/elasticsearch-dbapi/issues

**Comment by ankur-vyas14** [comment]
@dpgaspar Added issue here https://github.com/preset-io/elasticsearch-dbapi/issues/27. The issue seems to be with Apache Superset because when I am trying to fetch the data with the Python script it returns the result.

**Comment by dpgaspar** [comment]
Going to close this to avoid confusion, we'll follow it on the elasticsearch-dbapi repo
