### ISSUE TITLE
postgresql error: function date_trunc(unknown, text) does not exist LINE 1

### ISSUE THREAD

**Issue by billy-odera** [apache/incubator-superset#9783]
I am trying to run a timeseries line chart as capture below. I converted one of my columns labelled date which was imported as TEXT  after uploading from csv to DATETIME and checked  the is temporal checkbox.

But when i run the query, i get the error below. I ma using postgresql as the database connection
![image](https://user-images.githubusercontent.com/12785557/81588182-cff27a00-93c0-11ea-887c-7ad36f503f99.png)

> postgresql error: function date_trunc(unknown, text) does not exist LINE 1: SELECT DATE_TRUNC('day', "Date") AS __timestamp, ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by eugeniamz** [comment]
What Database Engine that you use? Postgres? I tested with latest release with Postgres and I can't reproduce. Please confirm.

**Comment by billy-odera** [comment]
I am running on postgres all in docker that is redis,postgres and superset
postgresql+psycopg2://superset:XXXXXXXXXX@XXX.XX.XX.XX:5432/superset

**Comment by billy-odera** [comment]
I am using this setup
https://medium.com/uc-engineering/apache-superset-setup-in-production-a8f4ae43b330

**Comment by dpgaspar** [comment]
@billy-odera can you go to SQLLab and confirm that the column "Date" is DATETIME

**Comment by billy-odera** [comment]
@dpgaspar below is the screenshot from table view
![image](https://user-images.githubusercontent.com/12785557/81673718-bdc21b80-9454-11ea-83b7-2827427917bd.png)
and also from sql
![image](https://user-images.githubusercontent.com/12785557/81673826-e2b68e80-9454-11ea-856e-22b3c68f677b.png)

**Comment by eugeniamz** [comment]
I think the docker amancevice/superset has an old version of superset, I am wondering if it has the right drivers. I am using postgresql:// no postgresql+psycopg2://

There is an [official docker](https://hub.docker.com/r/preset/superset/tags) and there is also a new  [blog ](https://preset.io/blog/2020-05-11-getting-started-installing-superset/) published a couple of days ago.

**Comment by rumbin** [comment]
My guess is that the table column really is of type text on the Postgres DB. Please check it either with SQLLab or external Clients like, e.g., DBeaver. Just access your database, navigate to the table and check the dtypes.
Postgres' error message is pretty precise, that it is a data type mismatch on the SB table column.

**Comment by SANGET** [comment]
because the column type is string. You can change your date column to date type, like:
`to_char (create_date, 'YYYY-MM-DD')::date AS create_date`
