### ISSUE TITLE
superset-fontend Error after run npm run dev-server 

### ISSUE THREAD

**Issue by Amylee520** [apache/incubator-superset#9785]
`98% after emitting SizeLimitsPluginType checking in progress...
× ｢wdm｣:    718 modules

ERROR in ./src/welcome/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/SqlLab/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/profile/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/addSlice/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('js-add-slice-container'));
|

ERROR in ./src/showSavedQuery/index.jsx 39:4
Module parse failed: Unexpected token (39:4)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
|
|   ReactDom.render(
>     <div>
|       <Form
|         schema={config.JSONSCHEMA}

ERROR in ./src/dashboard/index.jsx 42:16
Module parse failed: Unexpected token (42:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|

ERROR in ./src/explore/index.jsx 44:16
Module parse failed: Unexpected token (44:16)
You may need an appropriate loader to handle this file type, currently no load
s are configured to process this file. See https://webpack.js.org/concepts#loa
rs
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|
i ｢wdm｣: Failed to compile.
No type errors found
Version: typescript 3.8.3`
How can I solve it

**Comment by KanishkSrivastava** [comment]
@Amylee520 Did you solve this issue?

**Comment by prs1022** [comment]
@Amylee520 I have met the same problem,how to fix this bug?

**Comment by KennCai** [comment]
Do you resolved it? I have got this bug too,how to fix it ?

**Comment by BhavaniVertace** [comment]
Is it resolved?
