### ISSUE TITLE
Elasticsearch query return the all shards failed

### ISSUE THREAD

**Issue by harshmanvar** [apache/incubator-superset#9787]
i am able to create a connection from apache superset to elastic search but when trying it showing error `all shards failed`

We are running ES 7.3.2 with single node in Kubernetes

it's working fine with other applications only getting error in the superset.

![es-issue](https://user-images.githubusercontent.com/50694399/81665280-2792f300-945e-11ea-9a24-23cec0d9aa2f.PNG)

**Comment by dpgaspar** [comment]
Please post the output from: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html

At the time of the query

**Comment by harshmanvar** [comment]
Cluster health :
 ```
{
  "cluster_name": "staging_cluster",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 1,
  "active_shards": 1,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 1,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 50.0
}
```

**Comment by harshmanvar** [comment]
@dpgaspar  CURL output : 

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Trying to retrieve too many docvalue_fields. Must be less than or equal to: [100] but was [132]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"conversation_summary","node":"xCWQvbXgQu6Rufrzs0Tg7w","reason":{"type":"illegal_argument_exception","reason":"Trying to retrieve too many docvalue_fields. Must be less than or equal to: [100] but was [132]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Trying to retrieve too many docvalue_fields. Must be less than or equal to: [100] but was [132]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting.","caused_by":{"type":"illegal_argument_exception","reason":"Trying to retrieve too many docvalue_fields. Must be less than or equal to: [100] but was [132]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting."}}},"status":400}`

**Comment by dpgaspar** [comment]
Your cluster status is yellow and the direct query to elasticsearch returns an error:

`Trying to retrieve too many docvalue_fields. Must be less than or equal to: [100] but was [132]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting`

Fix both problems then retry
