### ISSUE TITLE
celery containers exits immefiately in superset

### ISSUE THREAD

**Issue by billy-odera** [apache/incubator-superset#9788]
I am running celery using the below docker command

> sudo docker run --detach -e REDIS_SERVER_IP=xxx.xxx.xxx.xx -e REDIS_PASSWORD=x -e POSTGRES_SERVER_IP=xxx.xxx.xxx.xx -e POSTGRES_PASSWORD=x --volume $PWD:/etc/superset --volume $PWD:/var/lib/superset amancevice/superset celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair

I have also set my database conection to allow async execution
![image](https://user-images.githubusercontent.com/12785557/81694868-85c5d300-946a-11ea-9c65-2e200a12ce48.png)

but the container starts and exists immediately
 
![image](https://user-images.githubusercontent.com/12785557/81694926-9c6c2a00-946a-11ea-940e-d3bcbfc71cee.png)

meaning my sql queries remain in pending status
![image](https://user-images.githubusercontent.com/12785557/81695016-b9a0f880-946a-11ea-8b6f-157f4ceda221.png)

**Comment by dpgaspar** [comment]
Please post your docker logs from the celery worker

**Comment by billy-odera** [comment]
> Please post your docker logs from the celery worker

![image](https://user-images.githubusercontent.com/12785557/81713345-6d5fb380-947e-11ea-8694-e881b4a29e3c.png)

**Comment by billy-odera** [comment]
> Please post your docker logs from the celery worker

>  File "/usr/local/lib/python3.6/site-packages/superset/sql_lab.py", line 43, in <module>
>     from superset.db_engine_specs import BaseEngineSpec
>   File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/__init__.py", line 36, in <module>
>     from superset.db_engine_specs.base import BaseEngineSpec
>   File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/base.py", line 54, in <module>
>     from superset.models.sql_lab import Query
>   File "/usr/local/lib/python3.6/site-packages/superset/models/__init__.py", line 17, in <module>
>     from . import core, datasource_access_request, schedules, sql_lab, user_attributes
>   File "/usr/local/lib/python3.6/site-packages/superset/models/core.py", line 55, in <module>
>     from superset.db_engine_specs.base import TimeGrain
> ImportError: cannot import name 'TimeGrain'
> /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> Traceback (most recent call last):
>   File "/usr/local/bin/celery", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
>     _main()
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
>     cmd.execute_from_commandline(argv)
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
>     super(CeleryCommand, self).execute_from_commandline(argv)))
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
>     argv = self.setup_app_from_commandline(argv)
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
>     self.app = self.find_app(app)
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 531, in find_app
>     return find_app(app, symbol_by_name=self.symbol_by_name)
>   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 373, in find_app
>     sym = symbol_by_name(app, imp=imp)
>   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 534, in symbol_by_name
>     return imports.symbol_by_name(name, imp=imp)
>   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
>     module = imp(module_name, package=package, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
>     return imp(module, package=package)
>   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/usr/local/lib/python3.6/site-packages/superset/sql_lab.py", line 43, in <module>
>     from superset.db_engine_specs import BaseEngineSpec
>   File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/__init__.py", line 36, in <module>
>     from superset.db_engine_specs.base import BaseEngineSpec
>   File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/base.py", line 54, in <module>
>     from superset.models.sql_lab import Query
>   File "/usr/local/lib/python3.6/site-packages/superset/models/__init__.py", line 17, in <module>
>     from . import core, datasource_access_request, schedules, sql_lab, user_attributes
>   File "/usr/local/lib/python3.6/site-packages/superset/models/core.py", line 55, in <module>
>     from superset.db_engine_specs.base import TimeGrain
> ImportError: cannot import name 'TimeGrain'

**Comment by hotvscool** [comment]
same question: https://github.com/apache/incubator-superset/issues/9589

Use the following command instead:
celery worker --app=superset.tasks.celery_app:app -Ofair

**Comment by billy-odera** [comment]
> same question: #9589
> 
> Use the following command instead:
> celery worker --app=superset.tasks.celery_app:app -Ofair

thanks it has worked.
