### ISSUE TITLE
Get "Commands out of sync; you can't run this command now" error on large table

### ISSUE THREAD

**Issue by ankur-vyas14** [apache/incubator-superset#9797]
I Got this error **"Commands out of sync; you can't run this command now"** When running the simple select query on large table having nearly **7 million** records. 

Sql query timeout is set to 180 seconds in config.py file but this error comes before the timeout.

### Expected results
- Select table query should run normally and return result

### Actual results
- Select table query returns a error **"Commands out of sync; you can't run this command now"**

#### Screenshots
![image](https://user-images.githubusercontent.com/41239909/81792453-b4ed4a80-9525-11ea-90b6-2485ad56c4fe.png)

**Comment by willbarrett** [comment]
Hi @ankur-vyas14 - would you mind sharing the type of the underlying datastore that you're attempting to query and the version of Superset that you're running? That will help us point you in the right direction.
