### ISSUE TITLE
Table display "null" instead of empty values (0.36.0 compared to 0.34.0)

### ISSUE THREAD

**Issue by squalou** [apache/incubator-superset#9805]
In a simple table chart, when nothing was to be displayed, the cell was empty. Now 'null' is written

### Expected results

Here's the display of null values in 0.34.0. As you can see, `<td></td>` cell is empty. Hover the mouse makes 'null" appear which is fine.

![image](https://user-images.githubusercontent.com/4623644/81940739-32818b00-95f8-11ea-81aa-d419240b20c1.png)

### Actual results
0.36.0 : 'null' is written and displayed : ` <td>null</td> `

![image](https://user-images.githubusercontent.com/4623644/81941065-a0c64d80-95f8-11ea-8c50-a19ab3f74568.png)

#### Screenshots

see above

#### How to reproduce the bug

1. Create a chart displaying empty values
2. See 'null' in cell

### Environment

(please complete the following information):

- superset version: `superset version` 0.36.0
- python version: `python --version`  Python 3.6.7
- node.js version: `node -v` v14.2.0
- npm version: `npm -v` 6.14.5

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

To make things clear : there is now way for instance to make a difference between the String "null" that would be inserted in a database, and an actually empty / null value.

So it's quite annoying.

**Comment by squalou** [comment]
Okay .... so displaying fake values is not considered a bug, and it automatically closes.

FU all.

**Comment by rumbin** [comment]
@squalou: I understand your anger, as I am also not quite pleased with the stale bot's rather aggressive closing policy.
However, please keep in mind that this is a non-commercial Open Source project. You don't pay anything and nobody owes you anything. The software is delivered "as is" and you may use it or not. You can even contribute or not.

Regarding your issue:
Handling and displaying NULL values is always challenging and there is no best practice that would fit all different users and audiences.
Not displaying anything may be useful for many non technical users. However, the more versed users may want to distinguish NULL values, i.e. non-existent values from, e.g. empty strings or whitespace-only values.
In my eyes, this is a design decision and I suppose that you will probably find a discussion on this topic associated with the pull request that caused the change in behaviour.

**Comment by squalou** [comment]
Yeah sure,
One point though : 'graphical displays', which is superset very existence reason, is aimed at non technical guys mostly. This could be debated of course.

The only sane way to address this would be to  leave people configure what they want to display for null values.
In the meantime, I can always use 'COALESCE' or equivalent in underlying queries, but it then requires to create queries even for simple table drilldown.

It's not the only missing 'configurability option' I've noticed

Don't take it bad, but, even for an open source project, I consider these missing features much more important than changing a font in the UI.
(for a font that miss-align dates in tables, at that, at the price of a considerable effort when you look at the commits)

Good news is : it's open source, so indeed, I can tweak and undo things I'm displeased with. I usually do it (did it for the fonts, and other null values in pivot tables)

Only issue is : in this very specific case I can't figure how to do that and revert properly things.

**Comment by squalou** [comment]
Still no news about this one ?
