### ISSUE TITLE
inserting a new database into Superset

### ISSUE THREAD

**Issue by smirs** [apache/incubator-superset#9815]
I am trying to insert a new database into Superset and I need your help.

Initially, what I wanted to to was inserting a csv file into Superset
and use as a db/table. I quickly realized "upload csv" is disabled in
Superset for some reasons. Then I started to create a db file from a csv
in sqlitestudio (successfull) and trying to insert that db file into
Superset (unsuccessfull).

All of my attempts to search and pass the appropriate SQLAlchemy URL in
Superset [add new database] has failed. I read the documentations too,
but still need help...

**Comment by pengyejun** [comment]
Please upload a picture to see the detailed error

**Comment by smirs** [comment]
![screen](https://user-images.githubusercontent.com/27302370/82342083-d1223900-99b6-11ea-8956-3562ee9d7230.png)

**Comment by smirs** [comment]
![screen2](https://user-images.githubusercontent.com/27302370/82342417-32e2a300-99b7-11ea-972b-7761a68b821b.png)

**Comment by pengyejun** [comment]
For the safety of superset, it is forbidden to add sqlite database. For details, please see PREVENT_UNSAFE_DB_CONNECTIONS parameter, the path is superset / config.py: 815

**Comment by pengyejun** [comment]
![DeepinScreenshot_select-area_20200519231205](https://user-images.githubusercontent.com/31479786/82344544-c0a9a700-9a26-11ea-8e73-ab0c970a6186.png)

**Comment by pengyejun** [comment]
https://github.com/apache/incubator-superset/pull/9218
