### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (NOT FOUND) 

### ISSUE THREAD

**Issue by dpugulo** [apache/incubator-superset#9822]
After starting the containers with docker-compose up, the first 20-30 sec
Well, it's okay, but when I try to login after 30 seconds, I get 404 error for some files.

### Expected results
no 404

### Actual results
# 404 error on login page
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-major.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-addSlice-dashboard-explore-preamble-profile-showSavedQuery-sqllab-welcome.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-addSlice-dashboard-explore-preamble-profile-sqllab-welcome.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
preamble.aee09120.entry.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-major.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-addSlice-dashboard-explore-preamble-profile-showSavedQuery-sqllab-welcome.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vendors-addSlice-dashboard-explore-preamble-profile-sqllab-welcome.aee09120.chunk.js: 1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
preamble.aee09120.entry.js: 1
#### Screenshots
![image](https://user-images.githubusercontent.com/55461451/82140088-ed4a9c80-9835-11ea-8a64-b693519aa08c.png)

#### How to reproduce the bug

1. Go to project folder
2. docker-compose up -d
3. go login page
4. See 404 error

### Environment

- superset version: Superset 0.999.0dev
- python version: Python 3.6.9
- node.js version: v10.19.0
- npm version: 6.13.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpugulo** [comment]
same result when restarting incubator-superset_superset_1 container, first 20-30 sec no problem then 404 error

**Comment by hershaw** [comment]
Any word on this? It just started happening on our end as well here. EXACT same issue.

**Comment by willbarrett** [comment]
It looks like your front-end assets are not building correctly. Please check the output of the container `superset-node` for errors when building front-end assets for the project. Post any errors you discover here and I'll do my best to help.

**Comment by hershaw** [comment]
okay so for what it's worth the problem was that our machine was out of disk space and randomly failing to serve some assets. totally 100% my fault!

**Comment by willbarrett** [comment]
I'm glad you resolved it!
