### ISSUE TITLE
filter box be applyed to all charts of one dashboard

### ISSUE THREAD

**Issue by petitpetit** [apache/incubator-superset#9823]
I created a dashboard with tabs, and different tab pages has its charts, when I apply one filter box to one of those tab pages, all charts can be filtered.

Can I use filter box only applied to some selected chart? How?

**Comment by esilver** [comment]
You can do it by adding the charts to the `filter_immune_slices` metadata field. It is in the documentation:
http://superset.apache.org/faq.html#how-to-add-dynamic-filters-to-a-dashboard

**Comment by lilila** [comment]
There is a nice way to edit filter scope. Click on `edit dashboard` then click on "filters" (1). It opens a nice interface to edit filter scope (2)

(1)
<img width="525" alt="Screenshot 2020-05-19 at 06 00 05" src="https://user-images.githubusercontent.com/607430/82283265-24d05a80-9996-11ea-8ab8-65fa728ba4cc.png">
(2)
<img width="946" alt="Screenshot 2020-05-19 at 06 00 16" src="https://user-images.githubusercontent.com/607430/82283270-269a1e00-9996-11ea-9743-0edf36ab11a4.png">
