### ISSUE TITLE
Tooltip didn't highlight when mouse moving on the line in  Multiple Line Chart

### ISSUE THREAD

**Issue by zheya08** [apache/incubator-superset#9838]
When I'm using  Multiple Line Chart, I move the mouse on the line, but the color in the tooltip didn't highlight, so I can't get the class of line clearly.
![image](https://user-images.githubusercontent.com/6650776/82291962-7d2a4b00-99dc-11ea-949d-a677526f1b56.png)

### Expected results

I expect it behaves like Line Chart, when I move the mouse on the line, the border of color in the tooltip is bolder,
![image](https://user-images.githubusercontent.com/6650776/82291853-566c1480-99dc-11ea-91ee-69f0f49b2da5.png).

**Comment by eugeniamz** [comment]
I don't think that in the line chart highlight the color of the series that the mouse is on it. It just show the series values at the X value where the mouse is positioned. 
![image](https://user-images.githubusercontent.com/58375897/82350235-15b6d000-99c9-11ea-8773-f5f48a46f8b0.png)

So it may be a feature for both charts
