### ISSUE TITLE
Refresh annotation layers

### ISSUE THREAD

**Issue by agatheLB-OUI** [apache/incubator-superset#9842]
I'm new to using Apache Superset but I seem to have dug deeper and not found the feature.

By creating a graph (line chart and time series) and adding annotation layers (of the same kind), if the curves from the original graph refresh well, it is not the case for the curves from the annotation layers.
I am forced to launch the charts corresponding to the annotation layers again to allow the queries to be refreshed; then I have to recreate the annotation layers on my global graph.

Maybe I missed something, but if it doesn't work, it's quite annoying.
Did I make a mistake or do you have any idea how to make this possible?

**Comment by eugeniamz** [comment]
I think that what you want is Multiple Line Charts, rather than annotations. 

Multiple Line charts will refresh and filter both charts in the chart at the same time. I did a [video in how to merge 2 charts. 
](https://www.youtube.com/watch?v=GwnkbhAMQTk)

Please confirm if this helps or if misunderstood the question.

**Comment by agatheLB-OUI** [comment]
yes that's what i was looking for; thanks a lot!!

**Comment by bellowswang** [comment]
But actually the same problem exists for the "event" annotation layer. The table that records the events has been refreshed. The time series chart has been refreshed. But the event vertical reference lines in the time series chart has not been refreshed. Sometimes, clicking "force refresh dashboard" would fix the problem, but sometimes it wouldn't.

**Comment by Vance-Chen** [comment]
> But actually the same problem exists for the "event" annotation layer. The table that records the events has been refreshed. The time series chart has been refreshed. But the event vertical reference lines in the time series chart has not been refreshed. Sometimes, clicking "force refresh dashboard" would fix the problem, but sometimes it wouldn't.

I meet this problem too, when  i change filter values, the parent chart update, but the annotation is still older one, should refresh the chart or dashboard by manual。
