### ISSUE TITLE
Get bar colors from tables

### ISSUE THREAD

**Issue by zufolo441** [apache/incubator-superset#9843]
Hi all, 
I'd need to represent data in bar chart with different colors depending of value. Is there a way to graduate color of bars or - alternatively - get color code from table? in this case I'd calculate color from value to be represented.
Thanks!

**Comment by skannan-maf** [comment]
This should be great feature addition. For e.g. When we draw bar charts, I want to visually indicate anomalies using RED color bars while having Green/Blue for others. And I want to pick the bar-color-decision-variable from the database table itself.
