### ISSUE TITLE
possible ways to integrate python or r to visualize and share data??

### ISSUE THREAD

**Issue by stardust59** [apache/incubator-superset#9849]
any leads to integrate either python or r so as to extend the superset capabilities, we are trying to view the survival analysis in superset.

**Comment by mukhwami** [comment]
Anyone who has integrated superset with python, please do help.

**Comment by sarthak405** [comment]
I got these references, might be helpful:

[Github Repo 1](https://github.com/sairamkrish/django-demo-project)

[Github Repo 2](https://github.com/sairamkrish/superset-custom-authentication)
