### ISSUE TITLE
docker-compose up but cant sign in with admin user

### ISSUE THREAD

**Issue by amy108** [apache/incubator-superset#9852]
![image](https://user-images.githubusercontent.com/48902828/82403569-bd97d080-9a91-11ea-833b-c33f01eee566.png)
![image](https://user-images.githubusercontent.com/48902828/82403582-c8eafc00-9a91-11ea-853d-3d6ee40aa66b.png)
![image](https://user-images.githubusercontent.com/48902828/82403661-f20b8c80-9a91-11ea-9ed5-084a6713c886.png)
hi, i started with docker but cant sign in.

**Comment by noklam** [comment]
@amy108  Hi, I am getting same issue, may I know how did you solve it?

**Comment by Yuchen-Wang-SH** [comment]
Same here. Have you guys figured this out?

**Comment by vaughnteegarden** [comment]
Same thing, admin/admin does not work to log in. Win 10 Pro, cloned from github today, May 28 2020.

**Comment by rusackas** [comment]
> Same thing, admin/admin does not work to log in. Win 10 Pro, cloned from github today, May 28 2020.

Windows is going to be a tough environment in which to get this up and running at all. You'll probably want some sort of linux VM solution, from what I've heard.

**Comment by willbarrett** [comment]
Please look carefully at the output from `docker-compose up`. the `superset-init` container is supposed to create the proper admin user. Please check this container's output carefully for errors - it's possible for that process to fail and still have the server boot successfully.
