### ISSUE TITLE
Ability to add/remove datasources and roles programatically

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9856]
Seems only way to add datasource (ie presto sql alchemy url and creds), or a role (ie access to a presto datasource) is via the UI. To avoid manual steps, would like to be able to add datasource and role via cli or api call as part of superset installation

**Comment by tooptoop4** [comment]
I've since discovered datasource options via cli (haven't tried yet) but still can't see any way to add roles via cli

**Comment by mistercrunch** [comment]
It's possible to tap in the [private] REST api and/or directly using the ORM in python scripts.

We've been pushing hard lately to make the REST api more public, and you can take a look at the swagger docs. More about this effort here https://github.com/apache/incubator-superset/issues/7259

**Comment by tooptoop4** [comment]
have you got a small snippet of using ORM to add a role?
Also  for point 9 of https://github.com/apache/incubator-superset/issues/9384 I would like to use ORM to get min() dbid from dbs table
