### ISSUE TITLE
Question about row limits on SQLLAB vs table chart or slice

### ISSUE THREAD

**Issue by pganesh** [apache/incubator-superset#9861]
Hi

From what I understand, on SQLLab we have two different row limit parameters: 

DISPLAY_MAX_ROW : controls the display so browsers don't crash on large number of rows
and 
SQL_MAX_ROW: controls total rows returned from the database. this limit is useful for downloading entire data into CSV, but not break the browser

Works great

But on the Table Chart/slice/dashboard view: there seems to be only one row limit parameter
ROW_LIMIT. Because if this limitation, large number of rows crashes the browser; and if limit the rows to make the broswer work, the CSV download is not complete.

Why can't the TableChart use the same SQLLAB parameters to control display vs download?

I noticed another parameter called VIZ_ROW_LIMIT - this does not seem to be used.

It almost seems like the Table Chart is a completely different entity from a SQLLog Query -is that right? Please let me know if I misunderstood.

**Comment by pzhuk** [comment]
Having a same problem - single row limit in table chart is used for both display lines and csv export
Not possible to have them different :(

**Comment by rorymillersoft** [comment]
This would be very useful in order to limit visualisation limit but keep the ability to download large datasets

**Comment by welee-li** [comment]
How to solve this problem? I want to show 100 lines in dashboard, but want to download all data through 'Export CSV' in table chart
