### ISSUE TITLE
CSV_TO_HIVE_UPLOAD_S3_BUCKET using presto datasource and EXTERNAL table

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9867]
CSV_TO_HIVE_UPLOAD_S3_BUCKET uses 'managed' hive table and hiveserver2.

proposing 'external' hive table and using presto data source

**Comment by bkyryliuk** [comment]
you can do it using hive database, we have a setup where csv upload happens in hive db, but the table is registered via presto - it can be configured

**Comment by tooptoop4** [comment]
have a firewall on hive db, so superset can't access it. was hoping that superset to presto db could do it

**Comment by bkyryliuk** [comment]
it will require implementing custom csv upload function for the presto
