### ISSUE TITLE
How to run SuperSet ouside the Virutal Environment

### ISSUE THREAD

**Issue by som2014** [apache/incubator-superset#9871]
I have installed superset on in python virutal env, now i don't want to activate the environment every time to run Superset

I am running the following command

 gunicorn -w 5 --timeout 120 -b 0.0.0.0:8088  "superset.app:create_app()"
It works fine when inside the virutal env, but outside it throwing me this error:

ImportError: No module named superset.app
How i can run superset outside the virtual env and i am also running celery worker.

**Comment by GOPIPACHA** [comment]
is this issue resolved?
