### ISSUE TITLE
Run SuperSet Forever 

### ISSUE THREAD

**Issue by som2014** [apache/incubator-superset#9873]
I have installed superset in python virtual env on GCP VM. I am running the superset using following command inside the virutal env.

`gunicorn -w 5 --timeout 120 -b 0.0.0.0:8088 "superset.app:create_app()"`

But when i  terminate my SSH connection the server stops, How to run SupserSet forever irrespective of my SSH connection.

**Comment by nytai** [comment]
You could run the command in [screen](https://linuxize.com/post/how-to-use-linux-screen/) and then detach and close ssh or you could [daemonize](https://linux.die.net/man/1/daemonize) the process so it is always running, even when it crashes, or the server reboots, it restarts.

**Comment by mistercrunch** [comment]
Closing as this is not Superset-specific. Here are more pointers:
- https://flask.palletsprojects.com/en/1.1.x/deploying/
- https://docs.gunicorn.org/en/stable/deploy.html#monitoring
