### ISSUE TITLE
Box plot shows "[object Object]" for Y axis label with no way to change.

### ISSUE THREAD

**Issue by txjmb** [apache/incubator-superset#9877]
### Expected results
Box plot should at least show a metric name for Y axis.  Customize menu on Box Plot should allow user to change Axis Titles as is the case with most charts.

### Actual results

Box plot shows "[object Object]" for Y axis label.  Customize menu has no options for axis labels.  It's clear that the label is somehow bubbling up to the control as an object rather than a string.  I am not yet familiar enough with the Superset codebase to trace it out well, so I thought I'd throw it out there to the community.

#### Screenshots

![image](https://user-images.githubusercontent.com/1986390/82587027-1e8cda80-9b5e-11ea-93e9-51f392ddba02.png)

#### How to reproduce the bug

I have provided a CSV file to test with.  Load CSV with Timestamp column as Index and set Timestamp column to be parsed as Datetime.

Here is the chart metadata, but you should be able to easily create a box plot with no time filter, and group by month with average of metric1 as metric.

```
{
  "adhoc_filters": [
    {
      "clause": "WHERE",
      "comparator": "2019",
      "expressionType": "SIMPLE",
      "filterOptionName": "filter_cceu05ohtzh_0afifgif2u1o",
      "fromFormData": true,
      "isExtra": false,
      "operator": "==",
      "sqlExpression": null,
      "subject": "Year"
    }
  ],
  "color_scheme": "bnbColors",
  "datasource": "16__table",
  "granularity_sqla": "Timestamp",
  "groupby": [
    "Month"
  ],
  "label_colors": {},
  "metrics": [
    {
      "aggregate": "AVG",
      "column": {
        "column_name": "Metric1",
        "description": null,
        "expression": null,
        "filterable": true,
        "groupby": true,
        "id": 664,
        "is_dttm": false,
        "optionName": "_col_Metric1",
        "type": "DOUBLE PRECISION",
        "verbose_name": null
      },
      "expressionType": "SIMPLE",
      "fromFormData": true,
      "hasCustomLabel": false,
      "label": "AVG(Metric1)",
      "optionName": "metric_kyrm5ej3a3e_2gadnfc61l7",
      "sqlExpression": null
    }
  ],
  "slice_id": 571,
  "time_range": "No filter",
  "time_range_endpoints": [
    "inclusive",
    "exclusive"
  ],
  "url_params": {},
  "viz_type": "box_plot",
  "whisker_options": "9/91 percentiles",
  "x_ticks_layout": "auto"
}
```

### Environment

(please complete the following information):

- superset version: 0.36.0
- python version: using Dockerfile (indicates 3.6.9
- node.js version: 10.20.1
- npm version: 6.14.4

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

[test_box.zip](https://github.com/apache/incubator-superset/files/4664130/test_box.zip)

**Comment by shaaaarpy** [comment]
Hi 
A small hot fix for this error :
`if(encoder.channels.y.axis.config.title.label) {
      encoder.channels.y.axis.config.title = encoder.channels.y.axis.config.title.label
    }`
Add this line of code before rendering the chart and this should work.
