### ISSUE TITLE
don't create examples sqlite datasource

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9879]
how to not create it? I have mysql metastore and don't want any example datasource

seems like this line should have a config option:
https://github.com/apache/incubator-superset/blob/d81f720502375101b43ffe9e2e6c28c0687b00f9/superset/cli.py#L71

**Comment by mistercrunch** [comment]
Mmmmh, that line doesn't make sense as part of `superset init`

**Comment by mistercrunch** [comment]
Trying this https://github.com/apache/incubator-superset/pull/9881 hoping CI passes
