### ISSUE TITLE
Make histogram viz support "group by"

### ISSUE THREAD

**Issue by mistercrunch** [apache/incubator-superset#988]
Right now it only works off of raw value in the table, so it only works if the grain of the table is the grain you care about.

**Comment by shkr** [comment]
I can work on this.

**Comment by ascott** [comment]
thanks @shkr!

**Comment by shkr** [comment]
I have been (working on) [https://github.com/shkr/caravel/tree/histogram_groupby] for generating multiple histograms when a group by key is specified #988.
*I was wondering which of these two arrangements is preferable ?*

1) Stacked on top of each other

![stacked charts](https://originlab.jira.com/wiki/download/attachments/29589627/StackedHist1.gif?version=1&modificationDate=1385466105620&api=v2)

2) Overlapping on each other 

![overlapping charts](http://www.astro.sunysb.edu/mzingale/simulations/wdconvect/R_hist_vr_576_norotate_Tminus_200x0_tbin_1x0_sm.png)


I will switch to nvd3 if that is preferable as recommended in this issue #989
