### ISSUE TITLE
creating admin user fails with Error! User already exists admin

### ISSUE THREAD

**Issue by MihailGershkovich** [apache/incubator-superset#9889]
"Snapshot" of the shell:

```
 # superset fab create-admin
 logging was configured successfully
 INFO:superset.utils.logging_configurator:logging was configured successfully
 /srv/www/htdocs/superset/lib64/python3.8/site-packages/flask_caching/__init__.py:188:  UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
 Username [admin]: admin
 User first name [admin]: admin
 User last name [user]: user
 Email [admin@fab.org]: admin.user@test.local
 Password:
 Repeat for confirmation:
 Recognized Database Authentications.
 Error! User already exists admin
```

**Comment by pengyejun** [comment]
Have a look at  ~/.superset/superset.db whether the admin user exists

**Comment by MihailGershkovich** [comment]
The users exist. This command creates the user and then I can change the passwords and it works.
 If I execute again, the command overwrites the admin user, and I have to change the pwd again.
Right now we have a workaround, but wanted to keep you informed.

**Comment by kartik96** [comment]
Hi,

Do we have any update on how can we deal with this issue? I am facing the same issue while setting up Superset with Ec2 container
