### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by Malestudents** [apache/incubator-superset#9907]
(superset) D:\python\envs\superset\Lib\site-packages\superset\bin>set FLASK_APP=main

(superset) D:\python\envs\superset\Lib\site-packages\superset\bin>flask fab create-admin
Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: admin
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: Could not import "superset.bin.main".

(superset) D:\python\envs\superset\Lib\site-packages\superset\bin>set FLASK_APP=superset

(superset) D:\python\envs\superset\Lib\site-packages\superset\bin>flask fab create-admin
Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: admin
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: Could not import "superset.bin.superset".

**Comment by zhaoyongjie** [comment]
@Malestudents Superset only supported Linux-like os.
