### ISSUE TITLE
apache superset 35 mysql connection error

### ISSUE THREAD

**Issue by reddipravi** [apache/incubator-superset#9913]
I have installed apache superset v0.35 on RHEL7 docker image, but when trying to connect to mysql database it gives me an 
```
ERROR: {
	"error": "Connection failed!\n\nThe error message returned was:\n/usr/local/lib64/python3.6/site-packages/MySQLdb/_mysql.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct",
	"stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/superset/views/core.py\", line 1703, in testconn\n    engine = database.get_sqla_engine(user_name=username)\n  File \"/usr/local/lib/python3.6/site-packages/superset/utils/core.py\", line 131, in __call__\n    value = self.func(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/superset/models/core.py\", line 923, in get_sqla_engine\n    return create_engine(url, **params)\n  File \"/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/__init__.py\", line 488, in create_engine\n    return strategy.create(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 87, in create\n    dbapi = dialect_cls.dbapi(**dbapi_args)\n  File \"/usr/local/lib64/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py\", line 118, in dbapi\n    return __import__(\"MySQLdb\")\n  File \"/usr/local/lib64/python3.6/site-packages/MySQLdb/__init__.py\", line 18, in <module>\n    from . import _mysql\nImportError: /usr/local/lib64/python3.6/site-packages/MySQLdb/_mysql.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct\n"
}
```
Can anyone please assist what is incorrect with my installation. Here is the output of my pip3 freeze

alembic==1.4.2
amqp==2.5.2
apache-superset==0.35.2
apispec==1.3.3
attrs==19.3.0
Babel==2.8.0
backoff==1.10.0
billiard==3.6.3.0
bleach==3.1.5
Brotli==1.0.7
celery==4.4.2
cffi==1.14.0
click==6.7
colorama==0.4.3
contextlib2==0.6.0.post1
croniter==0.3.31
cryptography==2.9.2
decorator==4.4.2
defusedxml==0.6.0
dnspython==1.16.0
email-validator==1.1.0
Flask==1.1.2
Flask-AppBuilder==2.2.4
Flask-Babel==1.0.0
Flask-Caching==1.8.0
Flask-Compress==1.5.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.2
flask-talisman==0.7.0
Flask-WTF==0.14.3
geographiclib==1.50
geopy==1.21.0
gunicorn==19.8.1
humanize==2.4.0
idna==2.9
importlib-metadata==1.6.0
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
kombu==4.6.8
Mako==1.1.2
Markdown==3.2.2
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.0
msgpack==0.6.2
mysql-connector-python==8.0.20
mysqlclient==1.4.6
numpy==1.18.4
packaging==20.4
pandas==0.24.2
parsedatetime==2.5
pathlib2==2.3.5
polyline==1.4.0
prison==0.1.3
protobuf==3.12.1
py==1.8.1
pyarrow==0.15.1
pycparser==2.20
PyJWT==1.7.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
python-dotenv==0.13.0
python-editor==1.0.4
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2020.1
PyYAML==5.3.1
retry==0.9.2
selenium==3.141.0
simplejson==3.17.0
six==1.15.0
SQLAlchemy==1.3.17
SQLAlchemy-Utils==0.36.5
sqlparse==0.3.1
urllib3==1.25.9
vine==1.3.0
webencodings==0.5.1
Werkzeug==0.16.1
WTForms==2.3.1
WTForms-JSON==0.3.3
zipp==3.1.0

**Comment by mistercrunch** [comment]
What version of mysql?

**Comment by reddipravi** [comment]
I got the issue resolved. the issue was because of using python-devtools instead of python3-devtools. After installing the right version of python devtools the issue got resolved. I am able to connect to MySQL database and query it from  superset. 

The remote MySQL version I am connecting is 5.1 
mysql-connector-python==8.0.20
mysqlclient==1.4.6
