### ISSUE TITLE
导出superset的看板报表

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-superset#9927]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zengqinchris** [comment]
/dashboard/export_dashboards_form?id=3&id=2&action=go
这种方式导出报错

**Comment by pengyejun** [comment]
> /dashboard/export_dashboards_form?id=3&id=2&action=go
> 这种方式导出报错

可否给出具体的错误信息或者截图

**Comment by zhaoyongjie** [comment]
Hi, if you need help, please show more exception logs. could you try in CLI
mode export?
