### ISSUE TITLE
How to create a chart template, and reuse it several times in a Dashboard or several Dashboards?

### ISSUE THREAD

**Issue by luoxi001713** [apache/incubator-superset#9937]
Two Charts, all are the same except the where filter values, like:

Chart A:  filter Column City = 'New York'
Chart B:  filter Column City = 'London'

How to create as one Chart, but I can add it many times into a Dashboard or several Dashboards?

Now I have about 10 dashboards, and each dashboard will include the similar Charts many times, I need to create for each, so there are too many charts now and now easy to maintain, so it there a better way?

**Comment by zufolo441** [comment]
I have same problem, and I'm trying to use url parameters for changing chart aspect, but jinja templates are not implemented for charts metadata.

**Comment by ebauch** [comment]
I don't think this is a bug. If anything, a feature request.

**Comment by EBoisseauSierra** [comment]
It would be a nice feature request indeed. One solution could be to create a [custom viz plugin](https://preset.io/blog/building-custom-viz-plugins-in-superset-v2/) that would be “forked” from the official definition, but then pre-define (i.e. hardcode) all parameters but the filter.

This way, you would have only one piece of code to change when you want to update all charts. But it creates the burden to maintain a fork.
