### ISSUE TITLE
Dashboard access permission

### ISSUE THREAD

**Issue by amitNielsen** [apache/incubator-superset#9938]
**Is your feature request related to a problem? Please describe.**
I'm missing then ability to permit access in the dashboard level.
there is only ability to set owners, but owners have full permissions on the dashboard they own but in my use-case I need to give basic access to specific dashboards **only**
I want for security purposes  to block access for non permitted user to access dashboards

**feature summary**

- Create permissions for each dashboard with the format "dashboard access on dashboard_title [dashboard_id]"
- The name of the permission is updated if the dashboard title is changed.
- Add a dashboard permission to a role via the Edit Role form, or, for convenience, add a role to a dashboard via the Edit Dashboard form.
- Optionally, add a default role to be added to each new dashboard created from a slice.
- The permission "all_dashboard_access" is added to Admin, Alpha, and Gamma roles.
- To allow private dashboards, remove "all_dashboard_access" from a role. This role will then only have access to the dashboards specified. Add a dashboard's permission to a role to "publish" it.
- Note that these permissions do not apply to slices. To make the data in a dashboard truly private, use dashboard permissions with a read only role that has no slice/explore access.

**Describe the solution you'd like**
Use **FAB permission view** mechanism to have new permissions named **dashboard read/edit access**
and for every dashboard there would be a matching **view_menu** instance that can be used a permission_view and be assigned into Roles

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblx0QVtkYXNoYm9hcmQgaW5zdGFuY2VdIC0tPnxoYXMgYSBtYXRjaGluZ3wgQihhYl92aWV3X21lbnUpXG5cdEIgLS0-IHxmb3JtIHRvZ3RoZXJ8IEN7cGVybWlzc2lvbl92aWV3fVxuICAgIERBW2Rhc2hib2FyZCByZWFkIGFjY2Vzc10tLT58aW5zdGFuY2Ugb2Z8IGFiX3Blcm1pc3Npb25cblx0REVBW2Rhc2hib2FyZCBlZGl0IGFjY2Vzc10tLT58aW5zdGFuY2Ugb2Z8IGFiX3Blcm1pc3Npb25cbiAgICBhYl9wZXJtaXNzaW9uIC0tPiB8Zm9ybSB0b2d0aGVyfCBDe2FiX3Blcm1pc3Npb25fdmlld31cblx0QyAtLT58dXNlZCBpbnwgRFthYl9wZXJtaXNzaW9uX3ZpZXdfcm9sZV0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0QVtkYXNoYm9hcmQgaW5zdGFuY2VdIC0tPnxoYXMgYSBtYXRjaGluZ3wgQihhYl92aWV3X21lbnUpXG5cdEIgLS0-IHxmb3JtIHRvZ3RoZXJ8IEN7cGVybWlzc2lvbl92aWV3fVxuICAgIERBW2Rhc2hib2FyZCByZWFkIGFjY2Vzc10tLT58aW5zdGFuY2Ugb2Z8IGFiX3Blcm1pc3Npb25cblx0REVBW2Rhc2hib2FyZCBlZGl0IGFjY2Vzc10tLT58aW5zdGFuY2Ugb2Z8IGFiX3Blcm1pc3Npb25cbiAgICBhYl9wZXJtaXNzaW9uIC0tPiB8Zm9ybSB0b2d0aGVyfCBDe2FiX3Blcm1pc3Npb25fdmlld31cblx0QyAtLT58dXNlZCBpbnwgRFthYl9wZXJtaXNzaW9uX3ZpZXdfcm9sZV0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

Users will be validated with the necessary permissions when requesting dashboards(specific or list)  and will be rejected if they don't have them
Also will be validated on on dashboard edit access (UI & BE)

**Comment by yishaifri** [comment]
nice

**Comment by amitNielsen** [comment]
@mistercrunch @villebro @altef

**Comment by altef** [comment]
I would very much like dashboard level permissions as well; Thanks for writing this up, @amitNielsen!  

@justin-barton

**Comment by amitNielsen** [comment]
@altef we are using your rls implementation thanks for that!

**Comment by amitNielsen** [comment]
there is an old PR #5099 but now it is stable
I plan to re-implement just trying to make sure the feature summary that I've listed is the right way to go 
@mistercrunch @altef

**Comment by Clement-Ru** [comment]
@amitNielsen This would be a very useful feature indeed ! Thanks for taking a look at it.
The feature summary you described is exactly what I would expect from this feature

**Comment by rubenSastre** [comment]
great new fature!

**Comment by amitNielsen** [comment]
I've open a sip #10408
