### ISSUE TITLE
Schema and table browser in table definition UI

### ISSUE THREAD

**Issue by larshelge** [apache/incubator-superset#9957]
This feature request is about being able to browse available schemas and tables in the "Import a table definition" UI. This UI is accessible at `/tablemodelview/add`. 

As an admin user, when importing a table definition, after selecting a database, I would like to view the available schemas in a drop-down list, and after selecting a schema, view the available tables in the schema in a drop-down list. After viewing the tables, I want to select a table.

Currently one must type in the name of the schema and table manually. It would be helpful to be able to select a schema and table from a drop-down list. This is useful in order to avoid typing errors, and to avoid using a third-party tool to look up schemas and tables.

![schema](https://user-images.githubusercontent.com/908206/83401648-8e744e00-a405-11ea-9afc-051d5c7edb60.png)

**Comment by willbarrett** [comment]
@larshelge we've been working on a new set of React-based views, and have recently implemented precisely this feature. You can try them out by setting `ENABLE_REACT_CRUD_VIEWS = True` in `config.py`.

**Comment by bkyryliuk** [comment]
+1 we have been using them in production for quite some time, much better user experience

**Comment by willbarrett** [comment]
Closing as this enhancement is available.

**Comment by larshelge** [comment]
Great, thanks for the response @willbarrett . For the record, this is now supported nicely in the new dataset editor UI.

![schema-superset](https://github.com/apache/superset/assets/908206/f9e99950-2187-449d-994f-e42e5f46e6f6)
