### ISSUE TITLE
No dropdown options in Column containing event names in EventFlow Chart

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-superset#9961]
There is no drop down options for `Column containing event names` under `Event definition` in Visualization Type: `Event Flow`

### Expected results
Expected to see a drop down list with columns

### Actual results
It shows no option.

#### Screenshots

![image](https://user-images.githubusercontent.com/1202120/83498959-72a69180-a471-11ea-8f4e-119527c7fc6d.png)

#### How to reproduce the bug

1. Go to Any Chart
2. Change `Visualization Type` to 'Event Flow'.
3. Click on `Event Definition`
4. See error: `Column containing event names` has 0 Options

![image](https://user-images.githubusercontent.com/1202120/83499508-57885180-a472-11ea-88e1-8cec1be5b142.png)

### Environment

(please complete the following information):

- superset version: master branch
- python version: 3.6.9

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It works in 0.36 but found in current dev master branch.

**Comment by fx19880617** [comment]
has anyone look into this?

**Comment by vnktsh** [comment]
I think this Viz is dead. Check below.
https://github.com/williaster/data-ui/issues/201
