### ISSUE TITLE
Superset chart with percentiles with data from druid

### ISSUE THREAD

**Issue by bvsbrk** [apache/incubator-superset#9963]
We have a use case where we have to show the 90th, 95th and 99th percentile value of a dimension. I came across this https://druid.apache.org/docs/latest/development/extensions-core/datasketches-quantiles.html. Here we can add this extension to druid to get the 95th percentile aggregator. Is there any way to use this aggregator in Superset so that we can plot 90th, 95th, 99th percentile value of a dimension in a single chart or across multiple charts ? I found that we can define custom post agrregators in Superset for druid but not sure if we can define custom aggregators too. 

This is an example of what we are looking for 

![image](https://user-images.githubusercontent.com/25194884/83504391-13cd3080-a4e2-11ea-8faf-0f43a7a8d171.png)

This representation is from kibana where the datasource is different (elastic)

**Comment by villebro** [comment]
If you're using Druid via the Sql Alchemy connector, you should be able to easily leverage the quantile aggregators, e.g. `APPROX_QUANTILE`: https://druid.apache.org/docs/latest/querying/sql.html#aggregation-functions

**Comment by RRethy** [comment]
It seems `pydruid` doesn't support columns of type `OTHER` which is the type for those quantile datasketches.
