### ISSUE TITLE
error when npm run prod at v0.36.0、0.999.0dev

### ISSUE THREAD

**Issue by toop** [apache/incubator-superset#9972]
```
versions：
  os：'windows 10',
  python：'3.6.7',
  yarn: '1.22.4',
  superset: '0.999.0-dev' and '0.36.0',
  node: '12.16.2',
  npm:'6.14.4',
  v8: '7.8.279.23-node.34',
  uv: '1.34.2',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1e',
  cldr: '36.0',
  icu: '65.1',
  tz: '2019c',
  unicode: '12.1'

**yarn run prod or npm run prod:**
yarn run v1.22.4
$ node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --mode=production --colors
Starting type checking service...
Using 1 worker with 2048MB memory limit
   548 modules

ERROR in ./src/welcome/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/SqlLab/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/profile/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('app'));
|

ERROR in ./src/addSlice/index.jsx 23:16
Module parse failed: Unexpected token (23:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import App from './App';
|
> ReactDOM.render(<App />, document.getElementById('js-add-slice-container'));
|

ERROR in ./src/showSavedQuery/index.jsx 39:4
Module parse failed: Unexpected token (39:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   ReactDom.render(
>     <div>
|       <Form
|         schema={config.JSONSCHEMA}

ERROR in ./src/dashboard/index.jsx 42:16
Module parse failed: Unexpected token (42:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|

ERROR in ./src/explore/index.jsx 44:16
Module parse failed: Unexpected token (44:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
|
> ReactDOM.render(<App store={store} />, document.getElementById('app'));
|
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wushu0725** [comment]
not windows, just ubantu or centos

**Comment by toop** [comment]
The version 0.35.2 frontend npm run build is worked at windows 10，The same environment.

**Comment by toop** [comment]
**npm ls:**

npm ERR! peer dep missing: @superset-ui/chart@^0.12.0, required by @superset-ui/legacy-plugin-chart-event-flow@0.11.15
npm ERR! peer dep missing: @superset-ui/chart@0.13.3, required by @superset-ui/legacy-plugin-chart-partition@0.13.11
npm ERR! peer dep missing: @superset-ui/chart@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/color@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/connection@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/core@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/dimension@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/number-format@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/time-format@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: @superset-ui/translation@^0.12.0, required by @superset-ui/legacy-plugin-chart-event-flow@0.11.15
npm ERR! peer dep missing: @superset-ui/translation@^0.12.0, required by @superset-ui/legacy-preset-chart-deckgl@0.2.3
npm ERR! peer dep missing: eslint@^3.19.0 || ^4.3.0, required by eslint-config-airbnb@15.1.0
npm ERR! peer dep missing: eslint@2.x - 5.x, required by eslint-plugin-import@2.14.0
npm ERR! peer dep missing: eslint@^2.10.2 || ^3 || ^4, required by eslint-plugin-jsx-a11y@5.1.1
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/chart@0.13.7
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/chart-composition@0.13.5
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/control-utils@0.13.12
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/legacy-plugin-chart-partition@0.13.11
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/legacy-plugin-chart-rose@0.13.10
npm ERR! peer dep missing: react@^16.13.1, required by @superset-ui/legacy-plugin-chart-table@0.13.21
npm ERR! peer dep missing: react@^15.5.4, required by omnibar@2.1.1
npm ERR! peer dep missing: react-dom@^16.13.1, required by @superset-ui/legacy-plugin-chart-table@0.13.21
npm ERR! peer dep missing: react-dom@^15.5.4, required by omnibar@2.1.1
npm ERR! peer dep missing: react-select@^1.0.0-beta14, required by react-select-fast-filter-options@0.2.3
npm ERR! peer dep missing: nyc@>=15, required by @istanbuljs/nyc-config-typescript@1.0.1
npm ERR! peer dep missing: ts-node@*, required by @istanbuljs/nyc-config-typescript@1.0.1
npm ERR! peer dep missing: tslint@^4.0.0 || ^5.0.0, required by fork-ts-checker-webpack-plugin@0.4.15
npm ERR! peer dep missing: aphrodite@^1.2.0, required by @data-ui/event-flow@0.0.84
npm ERR! peer dep missing: aphrodite@^1.2.0, required by @data-ui/forms@0.0.84
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by recompose@0.23.5
npm ERR! peer dep missing: eslint@^3.19.0 || ^4.5.0, required by eslint-config-airbnb-base@11.3.2
npm ERR! extraneous: istanbul-lib-instrument@4.0.1 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\istanbul-lib-instrument
npm ERR! extraneous: jest-cli@25.1.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\jest-cli
npm ERR! extraneous: jest-haste-map@25.1.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\jest-haste-map
npm ERR! extraneous: jest-regex-util@25.1.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\jest-regex-util
npm ERR! extraneous: locate-path@5.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\locate-path
npm ERR! extraneous: ms@2.1.2 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\ms
npm ERR! extraneous: normalize-path@3.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\normalize-path
npm ERR! extraneous: path-exists@4.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\path-exists
npm ERR! extraneous: pkg-dir@4.2.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\pkg-dir
npm ERR! extraneous: resolve-cwd@3.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\resolve-cwd
npm ERR! extraneous: slash@3.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\slash
npm ERR! extraneous: source-map@0.6.1 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\source-map
npm ERR! extraneous: test-exclude@6.0.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\test-exclude
npm ERR! extraneous: to-regex-range@5.0.1 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\to-regex-range
npm ERR! extraneous: wrap-ansi@6.2.0 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\wrap-ansi
npm ERR! extraneous: write-file-atomic@3.0.3 F:\superset-dev\superset-frontend\node_modules\has-values\node_modules\write-file-atomic
