### ISSUE TITLE
Not able to send email reports from superset.

### ISSUE THREAD

**Issue by devesharora90** [apache/incubator-superset#9977]
** Options are visble
![image](https://user-images.githubusercontent.com/24583867/83657229-33498380-a5de-11ea-8e93-df89e2d7a1ce.png)
** Cron Setup Complete
![image](https://user-images.githubusercontent.com/24583867/83657340-58d68d00-a5de-11ea-83b3-c05a22f9f0ec.png)
** Smtp Setup Complete
** Issue - not getting email from superset.
Why???

**Comment by kalimuthu123** [comment]
Did y start the celery worker and celery beat command

**Comment by devesharora90** [comment]
> Did you start the celery worker and celery beat command

Not yet. It is required to send email reports?

**Comment by mgulaydin** [comment]
@devesharora90 yes. This is done by celery library. You have to be sure both celery worker and celery beat is running. For further information please refer to the documentation*. There is a section about how to start those services (Celery Tasks). 

*https://superset.incubator.apache.org/installation.html#email-reports
