### ISSUE TITLE
Custom time grain options

### ISSUE THREAD

**Issue by nk-fouque** [apache/incubator-superset#9993]
**Describe the solution you'd like**
It would be nice if you could set the time grain to be *a certain number of* days/hours/minutes instead of just choosing the unit

**Describe alternatives you've considered**
I could program my own request in SqlLab with a date transformation but not everyone knows how to do that

**Additional context**
Of course I realize this is way more complicated than what I assume is the current method with just a truncation of the date to the required unit

**Comment by rumbin** [comment]
I see two challenges here.
First, implementing this feature for each and every DB that Superset supports. Have a look at the time grain definitions in /superset/db_engine_specs/. For some DBs there are already quite awkward approaches needed to support the current fixed time grains. See hana.py for such an example. Implementing a flexible time grain would be way harder.
Second, the user interface would have to be modified accordingly. Not only in Explore, but also in the Filter Slice where you may also change the granularity.
