### ISSUE TITLE
I'm not able to install Superset on my server.

### ISSUE THREAD

**Issue by jcobiaya** [apache/incubator-superset#9994]
I can't install Superset on my AWS server. Everytime I try to run on port 8088 it stops at the following stage:
```
^C(venv) root@ip-172-31-47-181:/home/ubuntu# superset run -p 8088 --with-threads --reload --debugger
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/home/ubuntu/venv/lib/python3.6/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:8088/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/home/ubuntu/venv/lib/python3.6/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 186-604-160
```
Can someone help?

**Comment by larshelge** [comment]
This is not an error message which will stop the startup, rather just a warning that you have not configured caching. You can read more about caching by researching "Flask-Cache".

**Comment by jcobiaya** [comment]
What could be preventing it from working? It stops right at that point and doesn't do anything after that. I went to the IP address of my server followed by port :8088, but its not working. I double checked my inbound rules and it shows that port 8088 is open so not sure what I'm doing wrong.

**Comment by NathanHatch** [comment]
That looks initialised correctly to me - more log lines will appear as the application is hit, if you can't reach it then none appearing is expected behaviour (ish).

Try adding "--host=0.0.0.0" to your command, depending where you are hitting it from at the moment you aren't exposing it externally.

**Comment by nishwalshetty** [comment]
@jcobiaya is the issue resloved ? i have the same isssue
