### ISSUE TITLE
Line Chart tooltips in Firefox not showing

### ISSUE THREAD

**Issue by klazaj** [apache/incubator-superset#9996]
Superset Version: **0.36.0**

The tooltip on the line chart in Firefox is not functional and not displaying any information. 

There seems to be [another issue](https://github.com/apache/incubator-superset/issues/7822) on this, but it is one year old and already closed.

**Comment by Pinimo** [comment]
I've been encountering the same problem for the last months, it would be nice to get this fixed soon. I'm enclosing @klazaj's snapshot from Slack.


![Left: Firefox. Right: Chrome](https://user-images.githubusercontent.com/14152858/89270597-d862f580-d63b-11ea-87ab-1cdbc2e20731.png)
<center>Left: Firefox; right: Chrome</center>

**Comment by Pinimo** [comment]
This is a duplicate of #9976
