### ISSUE TITLE
Filter before grouping

### ISSUE THREAD

**Issue by kwims** [apache/incubator-superset#9999]
Hi I am trying to draw an timeline histogram that support filter as parameter ( from a filter box) before grouping by time range but it does not work. 
Suppose I have a table USER_PRESENTATION and a table TAG and a view USER_PRESENTATION_TAG_VIEW that is the result of both tables joined

USER_PRESENTATION
|id|username|time|
|1|Johndoe|2020-01-01|
|2|Johndoe|2020-02-01|

TAG 
|user_presentation_id|tag|
|1|java|
|1|cobol|
|2|java|

USER_PRESENTATION_TAG_VIEW 
|id|username|time|tag|
|1|Johndoe|2020-01-01|java|
|1|Johndoe|2020-01-01|cobol|
|2|Johndoe|2020-02-01|java|

I want a timeline histogram that would show when I filter on"java" ( using filterBox) 
1 hit on 2020-01-01 and 1 hit on 2020-01-01

But it is showing me instead **2 hits** on 2020-01-01 and 1 hit on 2020-01-01 **because The filter is not injected before grouping by time**

Could you please help? Is Superset not supporting this?

**Comment by rumbin** [comment]
Could you please paste the SQL query that is generated by Superset?
In my understanding Superset _does_ the filtering before grouping. But having the query would help us understand what is actually happening.

**Comment by kwims** [comment]
Hi @rumbin , I was able to fix the code by using jinja template and Calculated Columns. I have been inspired by this ticket https://github.com/apache/incubator-superset/issues/4181.

_Note I updated the example to add another column._
 
SQL was like : 
`Select count(*), time  USER_PRESENTATION_TAG_VIEW where tag = 'java' group by time`

What I manage to do with jinja was to do update Datasource of USER_REPRESENTATION as follows:
```
Select * USER_PRESENTATION where id in (select id from USER_PRESENTATION_TAG_VIEW where 
 {% set f_tag = filter_values('tag') %}
    {% if f_tag %}
		AND tag in ( {{ "'" + "','".join(f_tag) + "'" }} )
   {% endif %}
)  group by time
```
 
Finally my SQL looks like:
`Select count(*), time USER_PRESENTATION where id in (select id from USER_PRESENTATION_TAG_VIEW where tag = 'java')  group by time`
